### ISSUE TITLE
[Meta] Apple Silicon Support

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#10005]
The team is investigating Apple Silicon support on the current Developer Transition Kit (DTK).

As of December 1st the status is:

- Xamarin.Mac - **Works**
    - x86_64 produced binaries work under Rosetta with no known issues
    - Need to produce a new version of Xamarin.Mac.dll for arm64 (with the same binding logic as for DEVICE for iOS)
- Xamarin.iOS simulators - ** Works**
    - Note: While it works on M1-based Macs, it does produces a "This app needs to be updated by the developer to work on this version of iOS." error message on DTK Macs.
- Xamarin.iOS device deployment - **Works** with XI 14.6 stable (or later)
- tvOS - Identical to iOS
- watchOS - Blocked due to [unrelated issue](https://github.com/xamarin/xamarin-macios/issues/9949)

**Comment by saamerm** [comment]
Is there an exception raised with that message with the iOS Simulator? 

And I guess this is great news then!
Because [the apple docs](https://developer.apple.com/support/ios-ipados-mac/) state that: 
> compatible iPhone apps and iPad apps will be available to run on Apple Silicon Macs
and that 
> Your compatible apps will be published automatically on the Mac App Store, unless you edit their availability
so Xamarin developers shouldn't need to do anything!

**Comment by follesoe** [comment]
It would be great if Apple Silicon support could be expanded, by enabling running the app outside the simulator when building/developing on a M1 Mac. This might be an easier feature to allow than say full Catalyst support. Today I have to publish my Xamarin.iOS app to TestFlight/AppStore, and then install it on my M1 Mac to test how the UI looks when running on macOS. I am sure I can also sign/run the PKG file, but would be great if it was built into Visual Studio for Mac, with macOS a run/debug target.

**Comment by saamerm** [comment]
@follesoe have you seen this? https://m.youtube.com/watch?v=IqeRPm197C4

**Comment by follesoe** [comment]
> @follesoe have you seen this? https://youtube.com/watch?v=IqeRPm197C4

Yes. Well aware of Mac Catalyst and different efforts (including this one) for supporting it from Xamarin. However, there are several limitations in the above prototype not making it a viable option for us now (awaiting official support from Microsoft).

But, on M1 Macs our app runs perfectly. But to test it (for instance to verify layout on super large screens) I have to create and package and ad hock build and launch it, versus just launching and running outside simulator.

I believe this would be a much easier scenario to support than full Catalyst support, as they don't need any different libs, underlying .NET runtime etc - it's the exact same pkg file and binary.

**Comment by ronaldobutrus** [comment]
> But, on M1 Macs our app runs perfectly. But to test it (for instance to verify layout on super large screens) I have to create and package and ad hock build and launch it, versus just launching and running outside simulator.

Have you managed to get the Xamarin.iOS application to work on macOS directly?

**Comment by follesoe** [comment]
> > But, on M1 Macs our app runs perfectly. But to test it (for instance to verify layout on super large screens) I have to create and package and ad hock build and launch it, versus just launching and running outside simulator.
> 
> 
> 
> Have you managed to get the Xamarin.iOS application to work on macOS directly? The Praeclarum Mac Catalyst isn't working for my project. 

When running iOS apps on M1 you do not need Catalyst. You run run the exact same binary directly on the Mac. And yes, Xamarin.iOS apps runs just fine, but you need to create a signed AdHoc build and cannot launch it directly from Visual Studio, which is my feature request.

Against, this has nothing to do with Catalyst, and is only relevant for M1 Macs.

**Comment by ronaldobutrus** [comment]
> When running iOS apps on M1 you do not need Catalyst. You run run the exact same binary directly on the Mac. And yes, Xamarin.iOS apps runs just fine, but you need to create a signed AdHoc build and cannot launch it directly from Visual Studio, which is my feature request.
> 
> Against, this has nothing to do with Catalyst, and is only relevant for M1 Macs.

Wow I didn't know you could do that; I thought there was an additional step. Thanks very much!

And yes, it would be a great feature request.

**Comment by saamerm** [comment]
If anyone else is looking to deploy/install your app on an M1 Mac directly from a Xamarin iOS app, you guys should [check this out](https://blog.devgenius.io/build-xamarin-apps-with-vs-code-to-m1-macs-iphones-android-11bc158f3773?sk=bc296c444465642b9d5771aef3f5e731)

**Comment by xfortin-devolutions** [comment]
Any ETA on this for Xamarin.Mac? And will we be able to build universal applications (i.e. built with both the x86_64 and arm64 architectures)?

**Comment by ivanicin** [comment]
> 
> 
> Any ETA on this for Xamarin.Mac? And will we be able to build universal applications (i.e. built with both the x86_64 and arm64 architectures)?

@xfortin-devolutions according to Microsoft no: https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/

To quote that page:

> Universal binaries is another new requirement for apps that are published via the Mac app store. Publishing via the store isn’t a capability we currently support, nor is it something that we hear requested much from .NET developers. We will not be enabling a workflow to publish universal binaries for .NET apps this release. We will reconsider this need with .NET 7.

It is quite interesting that a random comment got two likes in one hour for the topic with so low developer interest. Most of the comments on 'popular topics' don't get a single like.

And to my best knowledge Mac App Store publishing is officially supported, there is an official page on this topic and it never ever says something like 'beta': https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/publishing-to-the-app-store/

While it is a major disappointment that this won't be supported it is even worse that they have used multiple lies to explain their decision. I don't like to use that word, but unfortunately that is how the things are at the moment. Hopefully it will get better.

**Comment by rolfbjarne** [comment]
@xfortin-devolutions 

> Any ETA on this for Xamarin.Mac? And will we be able to build universal applications (i.e. built with both the x86_64 and arm64 architectures)?

We've released support for this as a preview: https://docs.microsoft.com/en-us/xamarin/mac/release-notes/7/7.13#preview-of-apple-silicon-support

@ivanicin 

> @xfortin-devolutions according to Microsoft no: https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/
> 
> To quote that page:
> 
> Universal binaries is another new requirement for apps that are published via the Mac app store. Publishing via the store isn’t a capability we currently support, nor is it something that we hear requested much from .NET developers. We will not be enabling a workflow to publish universal binaries for .NET apps this release. We will reconsider this need with .NET 7.

Unfortunately this is case of different people talking about different things. This paragraph is referring to .NET 5's existing macOS support (without Xamarin, just a plain .NET command line executable for instance): you can't create an .app with .NET 5 this way and publish it to the app store. And neither is it a goal for us to make this possible in .NET 6 (so the App Store's requirement to create universal binaries doesn't really apply, because you can't publish to the App Store _this way_ anyway).

However, if you create a Xamarin-based project, we'll support publishing it to the App Store in .NET 6, and we'll also support universal binaries.

**Comment by rolfbjarne** [comment]
In fact it looks like we've already implemented everything this issue talks about in the description, so I'm closing this.

**Comment by xfortin-devolutions** [comment]
Thanks @rolfbjarne ! I'll look into the preview version in the coming weeks. Do you know when those changes will be in a stable version?

**Comment by rolfbjarne** [comment]
> Thanks @rolfbjarne ! I'll look into the preview version in the coming weeks. Do you know when those changes will be in a stable version?

The changes should already be in the stable version of Xamarin.Mac, they're just considered a preview.

**Comment by xfortin-devolutions** [comment]
Ah, good to know, thanks again.

**Comment by ivanicin** [comment]
> Unfortunately this is case of different people talking about different things. This paragraph is referring to .NET 5's existing macOS support (without Xamarin, just a plain .NET command line executable for instance): you can't create an .app with .NET 5 this way and publish it to the app store. And neither is it a goal for us to make this possible in .NET 6 (so the App Store's requirement to create universal binaries doesn't really apply, because you can't publish to the App Store _this way_ anyway).

@rolfbjarne first I appreciate your explanation and I am also very happy to hear that this support is coming.

However there are some things in this one cannot be happy about, though after your comment those I must stress those are not major things:

1. This article that I have quoted was the only article mentioning Universal binaries and Xamarin.Mac in existence. There should have been by now something on this topic somewhere. But there is nothing, not even on the github. I have no insider information so I can know only what is published.
2. As the only article written on this topic it is confusing at the best. Reading it again I still come to the same conclusion, but I'll trust you that possibly there are some hints somewhere in it from which one can understand the different scope of that statement. However there is no doubt that such statement was put in a text that addresses topics like Xamarin.Mac and MAUI without some clear distinction that it doesn't have any connection with those parts of text.

**Comment by rolfbjarne** [comment]
@ivanicin 

> However there are some things in this one cannot be happy about, though after your comment I must stress those are not major things:

I hear you, and I agree our outward communication can get much better.

I don't think I'll be able to change the existing blogpost, but I'll take this up internally for future blogposts (and any other documentation we write).

**Comment by xfortin-devolutions** [comment]
@rolfbjarne Well, if I can suggest something, in this case, it would have been nice for the github ticket(s) to be updated accordingly. I would have started working on it sooner had I known it was already (although as a preview) available. I'm following those tickets for this reason, but it is not as reliable a method as I would have hoped.
