### ISSUE TITLE
I am getting an exception in production code and cannot trace it

### ISSUE THREAD

**Issue by amy-perelberg-self** [xamarin/xamarin-macios#10035]
### Steps to Reproduce

1. Run Application in Production Code
2. How do I trace where this is coming from?
3. 

### Expected Behavior
Application works in Debug mode. But has (very occasional) crashes in production.
### Actual Behavior
Application crashed in production
### Environment
Xamarin Forms, Visual Studio 2019

```
```

### Build Logs

Report from Microsoft Crash Center:
Runtime.ThrowNSException (System.IntPtr ns_exception)
SIGABRT: Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread. Native stack trace: 0 CoreFoundation 0x000000018e8765c0 472C9193-115D-34CD-AD1D-0E7E091C9432 + 1185216 1 libobjc.A.dylib 0x00000001a28f042c objc_exception_throw + 60 2 CoreAutoLayout 0x00000001a2b76d4c 2F390E30-6E7E-3643-AC2D-B9E7F1FDEE2A + 64844 3 CoreAutoLayout 0x00000001a2b76a20 2F390E30-6E7E-3643-AC2D-B9E7F1FDEE2A + 64032 4 CoreAutoLayout 0x00000001a2b764f8 2F390E30-6E7E-3643-AC2D-B9E7F1FDEE2A + 62712 5 CoreAutoLayout 0x00000001a2b71b34 2F390E30-6E7E-3643-AC2D-B9E7F1FDEE2A + 43828 6 UIKitCore 0x00000001916aaef4 47154C6D-47DF-3ABB-A152-56B159B014E4 + 17399540 7 UIKitCore 0x00000001916bddd4 47154C6D-47DF-3ABB-A152-56B159B014E4 + 17477076 8 QuartzCore 0x0000000191bc7280 FC06CF9F-7FB0-3C72-B2ED-C0728AA956AB + 1421952 9 QuartzCore 0x0000000191bc773c FC06CF9F-7FB0-3C72-B2ED-C0728AA956AB + 1423164 10 QuartzCore 0x0000000191bdbb64 FC06CF9F-7FB0-3C72-B2ED-C0728AA956AB + 1506148 11 QuartzCore 0x0000000191b23114 FC06CF9F-7FB0-3C72-B2ED-C0728AA956AB + 749844 12 QuartzCore 0x0000000191b4e418 FC06CF9F-7FB0-3C72-B2ED-C0728AA956AB + 926744 13 glassgrab 0x00000001015bb4c0 gc.safepoint_poll + 16425088 14 glassgrab 0x0000000101639998 gc.safepoint_poll + 16942424 15 glassgrab 0x000000010082579c gc.safepoint_poll + 2179932 16 glassgrab 0x00000001026bd7d8 gc.safepoint_poll + 34259864 17 glassgrab 0x0000000102778e8c gc.safepoint_poll + 35027532 18 glassgrab 0x000000010277e778 gc.safepoint_poll + 35050296 19 glassgrab 0x00000001027c6f60 gc.safepoint_poll + 35347232 20 glassgrab 0x00000001027c6cec gc.safepoint_poll + 35346604 21 libsystem_pthread.dylib 0x00000001d5dceca8 _pthread_start + 320 22 libsystem_pthread.dylib 0x00000001d5dd7788 thread_start + 8

**Comment by chamons** [comment]
Thanks for the feedback.

As noted in the [Apple Documentation](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Multithreading/ThreadSafetySummary/ThreadSafetySummary.html) in UIKit and AppKit you may only access UI elements on the main thread. It is undefined behavior to change properties on other threads.

This exception is from Apple, saying someone modified a layout engine property (Frame or Bounds for example) from another thread.

Consider reviewing your application code to verify any callbacks are on the main thread or moved with APIs such as BeginInvokeOnMainThread.

As you did not include a call stack, I'm unable to help you pinpoint it further.
