### ISSUE TITLE
Xamarin camera renderer can't recording video after iOS 14 update

### ISSUE THREAD

**Issue by HitaloDeAraujo** [xamarin/xamarin-macios#10063]
### Description
I'm programming on Xamarin Forms and created a renderer to iOS. So after iOS 14 update, my app starts the recording but stops immediatly after. On iOS 13 the record runs perfectly.

### Steps to Reproduce

Steps to face the problem on iOS 14:
1. Camera preview is showed.
2. The user clicks on start record button.
3. The recording video status icon is shown on iPhone top bar (native)
4. The capture is stopped immediatly

Steps on iOS 13:
1. Camera preview is showed.
2. The user clicks on the start record button.
3. The recording video status icon is shown on iPhone top bar (native)
4. The capture is stopped after 5 seconds (time limit that I set).

### Expected Behavior
The capture is stopped after 5 seconds (time limit that I set).

### Actual Behavior
The capture is stopped immediatly
### Environment
Xamarin.iOS: v4.0.30319
IDE: Microsoft Visual Studio Enterprise 2019 Version 16.5.4

### Example Project
```
    private void StartVideo(object sender, EventArgs e)
    {
        Element.completed = new TaskCompletionSource<VideoViewResult>();
        NSUrl url = new NSUrl(PathFile, true);

        if (avDel == null) avDel = new AVCaptureFileOutputRecording();
        if (output == null) output = new AVCaptureMovieFileOutput();

        var stillImageOutput = new AVCaptureStillImageOutput()
        {
            OutputSettings = new NSDictionary()
        };

        output.MaxRecordedDuration = CoreMedia.CMTime.FromSeconds(5, 1); // time limit
        // output.MaxRecordedDuration = CoreMedia.CMTime.FromSeconds(50000, 1);  //not working too

        if (Control.CaptureSession.CanAddOutput(output)) Control.CaptureSession.AddOutput(output);

        output.StartRecordingToOutputFile(url, avDel);

        avDel.StopRecord += StopRecording;
    }
```

**Comment by chamons** [comment]
Please attach a full sample project. There are entitlements required for video capture you may not have enabled.

**Comment by HitaloDeAraujo** [comment]
The problem was in the location of the video file.

Old code:
```
private static string GetOutputPath()
{
    string folder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "MyApp");
    Directory.CreateDirectory(folder); 
            
    return Path.Combine(folder, $"{Guid.NewGuid().ToString("N")}.{VideoFormat}");
}
```
New code:

```
private static NSUrl GetOutputPath()
{
   NSUrl url;

   if (UIDevice.CurrentDevice.CheckSystemVersion(14, 0))
      url = NSFileManager.DefaultManager.GetTemporaryDirectory().Append($"{Guid.NewGuid():N}.{VideoFormat}", false);
   else
   {
      string folder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "MyApp");
      Directory.CreateDirectory(folder);

      var PathFile = Path.Combine(folder, $"{Guid.NewGuid():N}.{VideoFormat}");

      url = new NSUrl(PathFile, true);
    }

    return url;
}
```
Now the video is recorded correctly, 

The application has full access to Photo with the user's permission (NSPhotoLibraryUsageDescription/NSPhotoLibraryAddUsageDescription)

**Comment by chamons** [comment]
So @HitaloDeAraujo it sounds like the issue is now resolved?

**Comment by HitaloDeAraujo** [comment]
I started using a temporary folder and my problem was solved. However, wouldn't it be nice to still work with the Personal directory (Environment.SpecialFolder.Personal) as in previous iOS versions?

**Comment by rolfbjarne** [comment]
This might be because write permissions to this folder could have in iOS 14. Unfortunately we won't be able to change which directory `Environment.SpecialFolder.Personal`, so there's not much we can do here.
