### ISSUE TITLE
Add support for arm64e archives so that developers can use iOS 14's MetricKit MXCrashDiagnostic

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [xamarin/xamarin-macios#10067]
### Steps to Reproduce

I'm trying to use MetricKit's new MXDiagnosticPayload to capture types of crashes that are otherwise not reported to AppCenter or App Store Connect (i.e. watchdog, jetsam, etc.). This is the representation of the backstack I'm trying to symbolicate: [MXCallStackTree](https://developer.apple.com/documentation/metrickit/mxcallstacktree/3552293-jsonrepresentation)

Visual Studio / Xamarin does not support archiving multiple architectures (i.e. arm64 AND arm64e)
[arm64e Xcode support](https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication)

MetricKit output is creating backstack frames with the arm64e architectures. The 'atos' command needs to specify arm64e to match the stack trace, but presently there is no way to generate an arm64e .dSYM file. This is supported directly in Xcode since Xcode 10.1 (2018).

1. Implement MetricKit's subscriber
2. In Diagnostic callback, serialize body to json and save to disk
3. Create code that will forcefully cause a crash (i.e. button press that throws not implemented exception)
4. Archive the app
5. Use Xcode to load the archive to device
6. Cause crashes, wait for diagnostic payload to be delivered to app
7. Extract the resulting .json file and use the address, binary, architecture, and offset to execute 'Atos' command to symbolicate frames.
8. Archived DSYM file is not arm64e, but MetricKit crash report is arm64e. The symbolication process fails.

### Expected Behavior

Visual Studio should support archiving for the newer chip architecture that was released with Xcode 10.1 (iPhone XS being first device in 2018)

### Actual Behavior

Visual Studio does not support archiving with multiple architectures, therefore any device running on arm64e that generates a MXDiagnosticPayload cannot be used to symbolicate the new iOS 14 crash data.

In the output, the architecture is shown here as arm64e, following Apple's instructions to symbolicate using atos [here](https://developer.apple.com/documentation/xcode/diagnosing_issues_using_crash_reports_and_device_logs/adding_identifiable_symbol_names_to_a_crash_report) results in a failed conversion.

atos -arch arm64e -o ~/Desktop/archive.xcarchive/dSYMs/MetricKitdemo.app.dSYM/Contents/Resources/DWARF/MetricKitDemo -l 0x4377849328 0x4374544384

The architecture, binary name, load address, and offset are all taken from the MetricKit data.

<img width="917" alt="Screen Shot 2020-11-06 at 12 00 16 PM" src="https://user-images.githubusercontent.com/73653238/98399245-bc4e6600-2027-11eb-9f07-667164be0f8b.png">

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.7.9 (build 9)
Installation UUID: 07aeae16-aa02-4f37-bc40-46fc0b4c33a7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.403/Sdks
SDK Versions:
	3.1.403
	3.1.402
	3.1.301
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.9
	3.1.8
	3.1.5
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.19
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.1 (17222)
Build 12A7403

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.2.0.12 (Visual Studio Community)
Hash: e0ce49680
Branch: xcode12.1
Build date: 2020-10-20 09:52:06-0400

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/dorphe1/Library/Android/sdk
	Supported Android versions:
		6.0 (API level 23)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/dorphe1/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Build Information ===

Release ID: 807090009
Git revision: d29d54665a1fc79986687a540a7a4676f97ad3da
Build date: 2020-10-21 15:05:18-04
Build branch: release-8.7
Xamarin extensions: d29d54665a1fc79986687a540a7a4676f97ad3da

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

### Build Logs

Not applicable. See attachment showing options for Xamarin.iOS supported architecture vs Xcode.

Visual Studio archive options
<img width="735" alt="Screen Shot 2020-11-06 at 11 56 40 AM" src="https://user-images.githubusercontent.com/73653238/98398843-36321f80-2027-11eb-90fa-1129f11ac6e0.png">

Xcode 12.x archive options (added arm64e). Resulting archive operation will show multiple architectures (arm64 and arm64e) in Xcode Organizer.
<img width="785" alt="Screen Shot 2020-11-06 at 11 51 59 AM" src="https://user-images.githubusercontent.com/73653238/98398894-4813c280-2027-11eb-89a2-29ba79a321e5.png">

### Example Project (If Possible)

Not provided

**Comment by spouliot** [comment]
The issue is not with **archiving**, that's simply packaging.

Today Xamarin.iOS supports compiling for device with `arm7`, `arm7s` and `arm64` processors. `arm64e` is a superset of `arm64` and is not yet supported, all those devices will run a `arm64` slice just fine. We'll ship support for the `arm64e` architecture once mono adds support for it. You can track this [here](https://github.com/dotnet/runtime/issues/34121)

It's unclear why MeticKit would give you `arm64e` data. It does seems to produce device specific data but your process (and symbols) remains `arm64`.

> The symbols for system frameworks are specific to the operating system release and the CPU architecture of the device. For example, the symbols for an iPhone running iOS 13.1.0 aren’t the same as the symbols for the same iPhone running iOS 13.1.2. If your app runs on operating system versions that support multiple CPU architectures, such as arm64 and arm64e, a device with an arm64 architecture will only contain the symbols for the arm64 version of the operating system frameworks; it won’t have symbols for the operating system frameworks on arm64e devices.
https://developer.apple.com/documentation/xcode/diagnosing_issues_using_crash_reports_and_device_logs/adding_identifiable_symbol_names_to_a_crash_report?language=objc

There's not enough data in the above screenshot for me to conclude if the `arm64e` is related to your process or not. It's mentioned as the `platformArchitecture`, which is true, but it does not mean it was the process' architecture. It does seems weird (and not future proof) for Apple to require a specific architecture to return metrics (e.g. a new, compatible CPU arch would mean you get nothing from new phones from existing applications).

It's possible that other related (but not from your process) crashes could be `arm64e` on phones with recent processors. However your application's `.dSYM` would not be helpful to symbolicate them.

**Comment by SwiftNativeDeveloper** [comment]
Thanks @spouliot for your detailed reply. There is very little documentation on MetricKit's diagnostic payload and what to do with it, so some of my above was trial by fire.

I was able to get 'atos' to work after realizing that the numbers provided in the json representation of the diagnostic payload were decimal not hex and that the offset was the load address.

Regarding the arm64e in a native app I have access to, the binary UUID reported in the payload didn't match the dwarfdump -u output from the archive, I had to download symbols in Xcode organizer to get the matching one; so Apple probably just used the bitcode to recompile for arm64e when distributed via App Store / Test Flight. 

Now having said that, archiving a simple Xamarin Hello World with a button that throws a NotImplementedException, that also generated a payload that said arm64e. Even though the report says the platform arch is arm64e, as you described we don't know if that is platform AND app instructions, or just platform. Both arm64 and arm64e parameters to 'atos' seem to work against a LOCAL archive that used ad-hoc distribution. If I get a Xamarin based app into TestFlight and find that arm64 arg does NOT work I'll update this.

**Comment by spouliot** [comment]
> so Apple probably just used the bitcode to recompile for arm64e when distributed via App Store / Test Flight.

That's unlikely as we do not generate bitcode for iOS applications (it's optional).

**Comment by rolfbjarne** [comment]
@SwiftNativeDeveloper were you able to figure this out, or do you still think there's a bug in Xamarin.iOS somewhere?

**Comment by spouliot** [comment]
Closing (inactivity).
