### ISSUE TITLE
[Clarification] Named mutexes/pipes on Xamarin.Mac

### ISSUE THREAD

**Issue by alexprogrammr** [xamarin/xamarin-macios#10068]
**Description**
I was trying to use named mutexes and named pipes to implement an inter-process communication system between different processes of Xamarin.Mac-based application. But unfortunately, I got `PlatformNotSupportedException`. I am at a loss right now.

As I see in the documentation, [NamedPipeServerStream](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes.namedpipeserverstream?view=netstandard-2.1) is a part of .NET Standard 2.1 specification. At the same time Xamarin.Mac [supports](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) .NET Standard 2.1 starting from 5.16 version (I currently use 6.20.2).

Could you please clarify my understanding of the Xamarin.Mac compatibility with the .NET Standard?
If the framework is .NET Standard compatible, does it means that all specified API should work correctly without throwing `PlatformNotSupportedException`?
How can I know that some parts of the .NET Standard API are not supported if there are no mentions about it in the documentation?

Please note, that NamedPipeServerStream, NamedPipeClientStream, and named Mutex are successfully working in .NET Core 3.1 runtime on macOS.

Thanks!

**Comment by chamons** [comment]
Thanks for the feedback.

The thing with netstandard is that it defines the API surface you can compile against, not necessarily the behavior of any of the APIs on a given platform. 

There are some "Windows isms", such as the Registry and in this case named pipes, that are not implemented on non-Windows platforms. Those will throw exceptions on other platforms.

If you wish to implement something like this on macOS, you can start with the [mkfifo](https://linux.die.net/man/3/mkfifo) system API.

You are welcome to provide feedback on this in the mono [here](https://github.com/mono/mono/issues/new).
