### ISSUE TITLE
[Bug] [Mac] MM2001 could not link assemblies (GetNamedColor)

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/xamarin-macios#10089]
# Description

Mac release build fails with:

```
MMP : error MM2001: Could not link assemblies. Reason: Error processing method: 'Xamarin.Forms.Color Xamarin.Forms.Forms/IOSPlatformServices::GetNamedColor(System.String)' in assembly: 'Xamarin.Forms.Platform.macOS.dll' [/Users/runner/work/1/s/Platforms/50Mac/50Mac.csproj]
```

I cannot find where GetNamedColor could be used as we are not invoking it or using xaml.

### Expected Behavior

- Getting Colors from strings is not used unless the user deliberately invokes this method
- Even if used, it doesn't generate an MM2001 exception

### Basic Information

- Version with issue: Xamarin.Forms 4.8.0.1687
- Last known good version: 4.6.0.1073

cc: @kevcrooks

**Comment by spouliot** [comment]
@charlesroddie please provide the information from our template, https://github.com/xamarin/xamarin-macios/issues/new

Minimally, your version information

1.
Visual Studio: Help > About Microsoft Visual Studio > Copy Info [button]
Visual Studio for Mac: Visual Studio > About Visual Studio > Show Details > Copy Information [button]
2. Paste into the code block below (between ```)

and the build logs

1. Place cursor below this comment block.
2. Attach build log or link to gist (https://gist.github.com/) of the log.
3. Logs can be found in the Build Output tab of the Errors pad in Visual Studio
To get full build logs, set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run
On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

and ideally with an attached test project so we can duplicate the issue.


@Redth can you update the issue template to include the things we ask inside ours ?
We can't take action on issues you transfer issues unless we have the data, so not asking it only introduce more delays for the reporter.

FWIW it looks like XF was compiled with a newer XM than the one used by the customer.

**Comment by charlesroddie** [comment]
This could be a false alarm. Checking internally. Sorry if this is the case. Will re-open if I can confirm this problem.

**Comment by charlesroddie** [comment]
Apparently this issue comes eventually from https://github.com/xamarin/Xamarin.Forms/issues/11703

To solve this we added:

```fsharp
if (deviceOS = OS.Droid) then
    buttonStyle.Setters.Add(Setter(Property = Button.TextTransformProperty, Value = TextTransform.None))
```

And that causes the issue on Mac somehow.
