### ISSUE TITLE
SIGABRT: Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method' was thrown.

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/xamarin-macios#10134]
Hi.

I see the following crash in App Center:

```
SIGABRT: Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method' was thrown.

UIApplicationDelegate.ReceiveMemoryWarning (UIKit.UIApplication application)
AppDelegate.ReceiveMemoryWarning (UIKit.UIApplication application)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

But searching for You_Should_Not_Call_base_In_This_Method gives almost no information whatsoever.
I am assuming the culprit is here:

```c#
public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
{
        // ... some code here ...

        public override void ReceiveMemoryWarning(UIApplication application)
        {
            // ... some cleanup code here ...

            base.ReceiveMemoryWarning(application); // <-- here?
        }
}
```

... but I fail to understand why it would throw? I don't want to remove the base call without confirming first if this is intended behaviour, and why exactly base shouldn't be called there? Also, if it indeed is intended that base should not be called, should Android's MainActivity's OnTrimMemory call also omit calling base?

Thank you.

VS for Mac 8.9 Preview build 265, latest pre-release Xamarin.Forms.

**Comment by rolfbjarne** [comment]
> I am assuming the culprit is here:

Yes, you're correct.

> ... but I fail to understand why it would throw?

to tell you that you shouldn't call base.

> I don't want to remove the base call without confirming first if this is intended behaviour

it is the intended behavior.

> and why exactly base shouldn't be called there?

Because on iOS there is no base method to call.

It's an optional method to implement, while at the same time there's no base method to call, and since there's no exact way to model that in C# in a way that the C# compiler would let you know that you did something wrong, we decided to throw an exception instead.

> Also, if it indeed is intended that base should not be called, should Android's MainActivity's OnTrimMemory call also omit calling base?

I don't know anything about Android, but it's entirely possible that the requirements are different there, because it's a very different platform.

**Comment by Tommigun1980** [comment]
> > I am assuming the culprit is here:
> 
> Yes, you're correct.
> 
> > ... but I fail to understand why it would throw?
> 
> to tell you that you shouldn't call base.
> 
> > I don't want to remove the base call without confirming first if this is intended behaviour
> 
> it is the intended behavior.
> 
> > and why exactly base shouldn't be called there?
> 
> Because on iOS there is no base method to call.
> 
> It's an optional method to implement, while at the same time there's no base method to call, and since there's no exact way to model that in C# in a way that the C# compiler would let you know that you did something wrong, we decided to throw an exception instead.
> 
> > Also, if it indeed is intended that base should not be called, should Android's MainActivity's OnTrimMemory call also omit calling base?
> 
> I don't know anything about Android, but it's entirely possible that the requirements are different there, because it's a very different platform.

Thanks for the answer but that’s quite a baffling decision.

If you override a virtual method of course you are going to call the base method from there. If iOS doesn’t have an implementation for that particular method, then why crash my app for it? Or should I in the future think that any virtual method’s base call can crash my app, especially as it’s not documented at all?

**Comment by rolfbjarne** [comment]
> If you override a virtual method of course you are going to call the base method from there.

Agreed.

> If iOS doesn’t have an implementation for that particular method, then why crash my app for it?

We throw an exception with a descriptive name (`You_Should_Not_Call_base_In_This_Method`) because if we try to call the non-existent implementation in iOS, the app will crash anyway, and the crash information you'll get will be much less helpful.

> so why not just have the base implementation not do anything instead?

Because that's not so easy with other method signatures. What should the base implementation return if it's supposed to return a value? Or if it has an out parameter?

> Or should I in the future think that any virtual method’s base call can crash my app, especially as it’s not documented at all?
