### ISSUE TITLE
VS Mac - error MSB4018: The "GetMinimumOSVersion" task failed unexpectedly.

### ISSUE THREAD

**Issue by stesvis** [xamarin/xamarin-macios#10149]
I am not able to build my iOS project on VS for Mac after the latest VS updates. Everything worked fine until an hour ago before I updated VS.

### Steps to Reproduce

1. Update VS for Mac to the latest version 8.8.2 (build 41)
2. Build iOS project

I also noticed that when I try to open Info.plist it showa just all blank.

### Expected Behavior
Build succeeds.

### Actual Behavior
Build fails with:

> error MSB4018: The "GetMinimumOSVersion" task failed unexpectedly.
> error MSB4018: System.ArgumentNullException: Parameter "message" cannot be null.

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.8.2 (build 41)
Installation UUID: 5f58b7d0-c2f7-4d81-8fa8-033c1df95bd4
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	2.1.23
	2.1.22
	2.1.21
	2.1.20

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.507
Hash: e87b24884
Branch: remotes/origin/d16-8
Build date: 2020-10-29 00:31:38 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/cristianmerli/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/cristianmerli/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Build Information ===

Release ID: 808020041
Git revision: dba789c00d07d6923cce74016b7e406526d683da
Build date: 2020-11-23 04:40:23-05
Build branch: release-8.8
Xamarin extensions: dba789c00d07d6923cce74016b7e406526d683da

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Oct 29 22:56:45 PDT 2020
    root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

XAML Styler 2.0.1
```

### Build Logs

> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018: The "GetMinimumOSVersion" task failed unexpectedly.
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018: System.ArgumentNullException: Parameter "message" cannot be null.
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentNull (System.Object parameter, System.String parameterName, System.String resourceName) [0x0000a] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Shared/ErrorUtilities.cs:797 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentNull (System.Object parameter, System.String parameterName) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Shared/ErrorUtilities.cs:784 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.Utilities.TaskLoggingHelper.LogError (System.String subcategory, System.String errorCode, System.String helpKeyword, System.String helpLink, System.String file, System.Int32 lineNumber, System.Int32 columnNumber, System.Int32 endLineNumber, System.Int32 endColumnNumber, System.String message, System.Object[] messageArgs) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Shared/TaskLoggingHelper.cs:641 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.Utilities.TaskLoggingHelper.LogError (System.String message, System.Object[] messageArgs) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Shared/TaskLoggingHelper.cs:574 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at (wrapper remoting-invoke-with-check) Microsoft.Build.Utilities.TaskLoggingHelper.LogError(string,object[])
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Xamarin.MacDev.Tasks.GetMinimumOSVersionTaskBase.Execute () [0x00039] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetMinimumOSVersionTaskBase.cs:25 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:577 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002b9] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:809 

### Example Project (If Possible)

N/A

**Comment by rolfbjarne** [comment]
Could you attach a diagnostic build log? The SDK version should default to the SDK version shipped with the Xcode you're using, and for some reason that doesn't seem to happen.

**Comment by stesvis** [comment]
@rolfbjarne I am attaching the log, thanks.
[build-log.txt](https://github.com/xamarin/xamarin-macios/files/5597719/build-log.txt)

**Comment by stesvis** [comment]
I was able to build again. It took a while to figure out but it looks like i had a corrupted `Info.plist` which caused this headache.

**Comment by rolfbjarne** [comment]
@stesvis what did your Info.plist look like? If we can reproduce this, we might be able to produce a better error message for the next person who hits this.

**Comment by stesvis** [comment]
@rolfbjarne In my case I think it was corrupted by a merge issue.
When I went thru it there was a line between `<<<<<<<<<<` and `>>>>>>>>>>`...and that's why VS wouldn't open the file. I noticed it when I opened it in VS Code. I didn't get any conflict warning tho, which was weird and that's why i wasted some time.

**Comment by tj-devel709** [comment]
Glad to hear that you were able to figure this out.
We will consider your situation regarding warnings in the future.
I will be closing this issue now, but feel free to open this issue back up if there are other issues with your Info.plist!

**Comment by ThatCanadianGuy** [comment]
Hi, 
I seem to be encountering the same issue, but my Info.plist is not corrupted like @stesvis' was. 

Build fails after updating to VS for Mac version 8.8.5 on MacOS 11.1. Was working before the update.

### Environment:
=== Visual Studio Community 2019 for Mac ===

Version 8.8.5 (build 18)
Installation UUID: 0a68d20b-2a0d-4cb7-b5d2-3a278ac43c39
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.102/Sdks
SDK Versions:
	5.0.102
	3.1.405
	3.1.402
	3.1.302
	3.1.200
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.2
	3.1.11
	3.1.8
	3.1.6
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.20
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12

=== .NET Core 3.1 SDK ===

SDK: 3.1.405

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Version: 7.2.0.3 (Visual Studio Community)
Hash: c51fabee8
Branch: xcode12.3
Build date: 2020-12-10 21:05:04-0500

=== Xamarin.iOS ===

Version: 14.8.0.3 (Visual Studio Community)
Hash: c51fabee8
Branch: xcode12.3
Build date: 2020-12-10 21:05:05-0500

=== Build Information ===

Release ID: 808050018
Git revision: e83d51ec050ffcdd573462fc1889b58cfe1a5ad5
Build date: 2021-01-07 14:45:50-05
Build branch: release-8.8
Xamarin extensions: e83d51ec050ffcdd573462fc1889b58cfe1a5ad5

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64


### Build output:
```
Target _GetMinimumOSVersion:
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018: The "GetMinimumOSVersion" task failed unexpectedly.
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018: System.ArgumentNullException: Parameter "message" cannot be null.
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentNull (System.Object parameter, System.String parameterName, System.String resourceName) [0x0000a] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Shared/ErrorUtilities.cs:797 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.Shared.ErrorUtilities.VerifyThrowArgumentNull (System.Object parameter, System.String parameterName) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Shared/ErrorUtilities.cs:784 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.Utilities.TaskLoggingHelper.LogError (System.String subcategory, System.String errorCode, System.String helpKeyword, System.String helpLink, System.String file, System.Int32 lineNumber, System.Int32 columnNumber, System.Int32 endLineNumber, System.Int32 endColumnNumber, System.String message, System.Object[] messageArgs) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Shared/TaskLoggingHelper.cs:641 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.Utilities.TaskLoggingHelper.LogError (System.String message, System.Object[] messageArgs) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Shared/TaskLoggingHelper.cs:574 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at (wrapper remoting-invoke-with-check) Microsoft.Build.Utilities.TaskLoggingHelper.LogError(string,object[])
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Xamarin.MacDev.Tasks.GetMinimumOSVersionTaskBase.Execute () [0x00039] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/GetMinimumOSVersionTaskBase.cs:25 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:577 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(227,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002b9] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:809 
Done building target "_GetMinimumOSVersion" in project "Utility.MD.csproj" -- FAILED.
```
And attached is the diagnostic output I have for the run. 
[build-log.txt](https://github.com/xamarin/xamarin-macios/files/5838337/build-log.txt)

Thanks for any help on this! Let me know if I should post this elsewhere.

**Comment by rolfbjarne** [comment]
This is an issue with error reporting: we're detecting an error condition, and then another error occurs that hides the first one.

The error reporting failure was fixed in 58e10cbf3954d49627bac2c4ab2f61b15a5d0734, and is available in the beta channel, so can you try the beta channel and see if you get a better error?

**Comment by ahmedalejo** [comment]
@ThatCanadianGuy just try searching for `<<<<<<<<<<` or `>>>>>>>>>>` in your codebase.
After locating the culprits
- either remove them
- or undo changes to the file

This something I have found my team facing with VS4Mac while pulling in changes with pending changes,
While Stash and Rebase is enabled.

The git experience is just as good as Visual Studio.
I'll be using [Atlassian Sourcetree](sourcetreeapp.com) for git workings until it gets better enough.

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
