### ISSUE TITLE
Visual Studio for Mac. Could not locate the assembly "Xamarin.iOS"...

### ISSUE THREAD

**Issue by fjavaler** [xamarin/xamarin-macios#10191]
### Description
Hi, I have a solution generated in VS 2019 (Windows) and runs fine in it, however, in VS for Mac I get the following error: 

/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xamarin.iOS". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. (MSB3245)

I am making a few references to the UIKit, CoreGraphics, and Foundation namespaces in my code and those namespaces are not able to be found. E.g. UIKit.UIImage, UIColor.Yellow, etc. I have tried uninstalling and reinstalling the Xamarin.Forms NuGet package and have also ensured that the iOS project is referencing Xamarin.iOS and that no other projects are referencing it.

### Steps to Reproduce

1. Make reference to any UIKit namespaces.
2. VS cannot find namespace UIKit despite having a "using UIKit;" statement.

### Expected Behavior
Namespace should be found as in Windows VS 2019.

### Actual Behavior
Namespaces not found.

### Basic Information

- Version with issue: VS for Mac 8.8.3.
- Last known good version: First time trying on VS for Mac.
- Platform Target Frameworks: 
  - iOS:  14.2
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages: Xamarin.Forms 4.8.0.1687
- Affected Devices:

### Environment

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.8.3 (build 16)
Installation UUID: 9377e409-c603-4fe4-88aa-828a3863e75a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.10

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Professional)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/gpsdev/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/gpsdev/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Xamarin Designer ===

Version: 16.8.0.507
Hash: e87b24884
Branch: remotes/origin/d16-8
Build date: 2020-10-29 00:31:38 UTC

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Professional)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Professional)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Build Information ===

Release ID: 808030016
Git revision: cc6375d2fdcc1b42532e551e24ce650eaca1ae45
Build date: 2020-11-25 13:16:20-05
Build branch: release-8.8
Xamarin extensions: cc6375d2fdcc1b42532e551e24ce650eaca1ae45

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

```

### Build Logs

https://gist.github.com/fjavaler/caafa05b3340c0800728ad9950f482b3

### Screenshots

![Screen Shot 2020-12-01 at 11 57 09 PM](https://user-images.githubusercontent.com/9067250/100839362-56d87400-3431-11eb-8e35-70b1a8523214.png)

**Comment by rolfbjarne** [comment]
It looks like your csproj has a reference to the Xamarin.iOS.dll location on your Windows system:

```
    Primary reference "Xamarin.iOS".
    /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2143,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xamarin.iOS". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
            For SearchPath "{HintPathFromItem}".
            Considered "/Users/gpsdev/Desktop/Source/GPS.CollateralUploader.App/CollateralUploader/CollateralUploader/C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/ReferenceAssemblies/Microsoft/Framework/Xamarin.iOS/v1.0/Xamarin.iOS.dll", but it didn't exist.
            For SearchPath "{RawFileName}".
            Considered treating "Xamarin.iOS" as a file name, but it didn't exist.
```

check your csproj and make sure the reference should only be `<Reference Include="Xamarin.iOS" />`

**Comment by fjavaler** [comment]
Hi Rolf,

Thank you for the help. I tried what you had suggested, however, removing the Windows path doesn't seem to have fixed the problem. It seems like VS for Mac still can't find the Xamarin.iOS.dll's location on the Mac.

I get the following build errors:
```
Could not resolve this reference. Could not locate the assembly "Xamarin.iOS". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. (MSB3245)
```

**Comment by rolfbjarne** [comment]
Can you attach your csproj file?

**Comment by fjavaler** [comment]
Sure thing here is a Gist with it: https://gist.github.com/fjavaler/56b1647a50aa3591104a535aebdf57ee

**Comment by rolfbjarne** [comment]
It looks like you're building a netstandard2.0 project, not a Xamarin.iOS project: https://gist.github.com/fjavaler/56b1647a50aa3591104a535aebdf57ee#file-collateraluploader-csproj-L5.

If you want to build a Xamarin.iOS library, you need to use a Xamarin.iOS project as well. If you want to build a netstandard2.0 project, you can't use any API specific to Xamarin.iOS. Exactly what are you trying to do?

**Comment by fjavaler** [comment]
The .csproj file that I sent you is the .csproj file for the shared project. I do have a seperate .iOS project as well. Did you want that .csproj file?

**Comment by fjavaler** [comment]
Here it is: https://gist.github.com/fjavaler/65378340c6757ac64b967b240bcc40f7

**Comment by rolfbjarne** [comment]
You reference Xamarin.iOS from your shared project (https://gist.github.com/fjavaler/56b1647a50aa3591104a535aebdf57ee#file-collateraluploader-csproj-L279), and that won't work. You can only reference Xamarin.iOS from your Xamarin.iOS project.

**Comment by fjavaler** [comment]
I see. So is it not possible to use UIKit in the shared project? That's why I had the reference in there. So that I can use namespaces like UIKit.

**Comment by fjavaler** [comment]
Also, do you know why VS 2019 doesn't complain about it on Windows? It successfully compiles and everything on Windows.

**Comment by rolfbjarne** [comment]
> I see. So is it not possible to use UIKit in the shared project? That's why I had the reference in there. So that I can use namespaces like UIKit.

You need separate platform-specific projects to use platform-specific code, but you can have a shared project that exposes a platform-neutral API.

I'm not sure how it works in VS, but in VS for Mac you can create a multi-platform library projects which will set everything up for you, with a shared project that contains platform-neutral API, and platform-specific implementation projects.

This might also explain things a bit: https://github.com/mattleibow/CreatingPlatformPlugins

> Also, do you know why VS 2019 doesn't complain about it on Windows? It successfully compiles and everything works on Windows.

It compiled because you had a reference to your local copy of Xamarin.iOS.dll (like you can add a reference to any .dll on your local system). The end result would be a shared assembly that would only be usable from other Xamarin.iOS projects, you couldn't use it in a Xamarin.Android project for instance.

**Comment by fjavaler** [comment]
Thank you for the explanation! I will review the material you linked to and I appreciate your help on this.
