### ISSUE TITLE
Mac Catalyst: review API surface

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10216]
* [x] [Mac Catalyst: make xtro tests work](https://github.com/xamarin/xamarin-macios/issues/10214)
* [x] [Mac Catalyst: fix introspection failures](https://github.com/xamarin/xamarin-macios/issues/10215)
* [x] Fix compatibility for Xamarin.iOS stubs/forwarders (several PRs)
* [x] Go through xtro todo items and fix those
  * [x] Remove extra API (not part of Mac Catalyst) 
  * [x] Add missing API and annotations
* [x] Verify that we're not shipping any obsolete API

---

Time estimate: 8 weeks.

**Comment by spouliot** [comment]
# Xamarin.iOS stubs/forwarders

maccat-to-ios.md https://gist.github.com/spouliot/984c92ce97d2b294088606f0bf697ef8

## Breaking Changes

* enum values are incorrect
* several missing interfaces (protocols)
* some missing `virtual`
* incorrect (missing `this`) on extension methods
* some errors with arrays (lost in conversion)

## Others

* apidiff does not follow forwarders so there's a bunch of removed types
  * we can filter them out (easier)
  * we can try to merge things (harder)

**Comment by chamons** [comment]
https://github.com/xamarin/xamarin-macios/issues/10215 is showing as closed so checking that box.
