### ISSUE TITLE
Make CGColor.CreateByMatchingToColorSpace public

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#10212]
Could the accessibility of this method be switched to "public"? :)
I'd like to use it in my app and I've copied the method into my project as a workaround.

https://github.com/xamarin/xamarin-macios/blob/2d7edf555f85dea7f5c4ad18440a1cf1a64f55b9/src/CoreGraphics/CGColor.cs#L274-L280

**Comment by rolfbjarne** [comment]
Huh, that's a rather useless function, we don't call it from anywhere else, and it's private.

**Comment by tipa** [comment]
It's not useless for me (if it was public 😉).
I don't think it should be private: https://developer.apple.com/documentation/coregraphics/1455493-cgcolorcreatecopybymatchingtocol

**Comment by spouliot** [comment]
That's likely a mistake - it should have been public and decorated with the same availability attributes as the p/invoke

This is why insisting on unit tests for manually bound API is important 😸
