### ISSUE TITLE
Xamarin.Forms - Crashlytics is not logging crashes [Xamarin.Forms 5.0.0.1709-pre4 & Crashlytics 4.6.2] [Bug]

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-macios#10227]
@Redth suggested I move this issue over to here
https://github.com/xamarin/Xamarin.Forms/issues/13011

### Description
Hi! I'm using Crashlytics v4.6.2 for my Xamarin.Forms app. Though the crash count is increasing but still no error message/stack trace is logged in the Firebase Console. I tried in release device build as well.

I get the following below logs which makes me think that something else is interfering, but though I tried, I couldn't find what is interfering with Crashlytics (if I've perceived it correctly)

### Expected Behavior
Crashes are not logged with stack trace. I tried throwing NotImplemented exception, Null reference exception and also one crash in picker whose fix is in Xamarin.Forms 5.0.0.1709-pre4

### Actual Behavior
Log crashes with stack trace/error message

### Basic Information

- Version with issue: 5.0.0.1709-pre4
- Last known good version: 3.4.0.1029999
- Platform Target Frameworks: 
  - iOS:  14.1

### Environment

![image](https://user-images.githubusercontent.com/42689728/100740568-f16b8f80-33fe-11eb-8bd5-c3e4f4707b5e.png)

### Build Logs

```
[Crashlytics] The signal SIGABRT has a non-Crashlytics handler (sigabrt_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGBUS has a non-Crashlytics handler (mono_sigsegv_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGFPE has a non-Crashlytics handler (mono_sigfpe_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGILL has a non-Crashlytics handler (<redacted>).  This will interfere with reporting.

[Crashlytics] The signal SIGSEGV has a non-Crashlytics handler (mono_sigsegv_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGSYS has a non-Crashlytics handler (mono_crashing_signal_handler).  This will interfere with reporting.
[Crashlytics] The signal SIGTRAP has a non-Crashlytics handler ((null)).  This will interfere with reporting.
```

### Workaround

No.

**Comment by PaulsonMac** [comment]
Hi Xamarin Team, any updates on this issue please? I'm running out of time! Please consider this as priority

I'm sure you devs should be knowing a way to remove the non-crashlytics handler or any other similar thing..? so that then Crashlytics might be able to catch the exceptions and report the same in the Firebase Console.

**Comment by rolfbjarne** [comment]
How to accomplish what you need is documented here:

https://www.mono-project.com/docs/advanced/signals/
https://stackoverflow.com/a/42421085/183422

**Comment by PaulsonMac** [comment]
Hi @rolfbjarne , I've already tried https://stackoverflow.com/a/42421085/183422. But it didnt work.

**Comment by PaulsonMac** [comment]
I still got the same messages in the logs i.e., 

```
[Crashlytics] The signal SIGABRT has a non-Crashlytics handler (sigabrt_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGBUS has a non-Crashlytics handler (mono_sigsegv_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGFPE has a non-Crashlytics handler (mono_sigfpe_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGILL has a non-Crashlytics handler (<redacted>).  This will interfere with reporting.

[Crashlytics] The signal SIGSEGV has a non-Crashlytics handler (mono_sigsegv_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGSYS has a non-Crashlytics handler (mono_crashing_signal_handler).  This will interfere with reporting.
[Crashlytics] The signal SIGTRAP has a non-Crashlytics handler ((null)).  This will interfere with reporting.
```

**Comment by rolfbjarne** [comment]
Can you attach a test project that shows what you're doing and that we could use to reproduce this?

**Comment by PaulsonMac** [comment]
Ok, I'll check and let you know. Thank you :)

**Comment by PaulsonMac** [comment]
Thank you JESUS..!! This issue is resolved.

Don't know why.. After uninstalling CarouselView.FormsPlugin package, the logs went off. Crashes are now reported properly

Maybe some error handling is being done in the CarouselView.FormsPlugin package.

Thank you @rolfbjarne

**Comment by PaulsonMac** [comment]
While testing each crash, I only got this CarouselView.FormsPlugin named exception being reported in the Firebase console. In that way, I identified that this package is interfering with the Crashlytics reporting as displayed in the logs
