### ISSUE TITLE
introspection/watchOS 32-bits - simulator/Debug (watchOS 3.2): Crashed

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#10236]
watchOS was re-enabled in `main` and `xcode12.3`

However xharness needs to provide a fat or i386 binary when running introspection for watchOS 3.2 (oldest simulator supported)

Only Xcode 12.0 supported either i386 or x86_64.
Before 12.0 (watchOS 7.0) only i386 was supported.
After 12.0 (watchOS 7.1) only x86_64 is supported.

**Comment by rolfbjarne** [comment]
This was fixed here: https://github.com/xamarin/xamarin-macios/pull/10648
