### ISSUE TITLE
NSUrl.CreateBookmarkData doesn't allow nulls for resource values

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#10261]
### Steps to Reproduce

1. Use `NSUrl.CreateBookmarkData(0, null, null, out _)`
2. Observe null ref exception for `resourceValues`
3. https://developer.apple.com/documentation/foundation/nsurl/1417795-bookmarkdata

### Environment

```
```

**Comment by rolfbjarne** [comment]
As far as I can understand, Apple's documentation doesn't say that the resource values can be null. Exactly what made you think they can be?

**Comment by mattleibow** [comment]
`[URLResourceKey]?`

```swift
func bookmarkData(options: NSURL.BookmarkCreationOptions = [], 
    includingResourceValuesForKeys keys: [URLResourceKey]?, 
    relativeTo relativeURL: URL?) throws -> Data
```

I have also seem most samples using `nil`

**Comment by Therzok** [comment]
Maybe some implicit boxing to NSNull is done by the compiler?

> The values of these properties must be of a type that the bookmark generation code can serialize. Specifically, the values can contain any of the following primitive types:
> ...
> kCFNull or NSNull

**Comment by rolfbjarne** [comment]
It's a nullable in the header, but not the documentation 😒 

> - (nullable NSData *)bookmarkDataWithOptions:(NSURLBookmarkCreationOptions)options includingResourceValuesForKeys:(nullable NSArray<NSURLResourceKey> *)keys relativeToURL:(nullable NSURL *)relativeURL error:(NSError **)error API_AVAILABLE(macos(10.6), ios(4.0), watchos(2.0), tvos(9.0));
