### ISSUE TITLE
Xamarin Forms build time for iOS is painfully slow and buggy

### ISSUE THREAD

**Issue by gitKRM** [xamarin/xamarin-macios#10267]
### Description
when creating a Xamarin forms application then setting iOS as the start up project, building the application onto a device is ridiculously slow. Building to an emulator is pretty much the same regards to speed.
I have tried different approaches e.g. we develop on a windows machine and was just using the mac as a build host, therefore i attempted loading the solution into VS for mac and the time it takes to build the project onto a device isn't any better.

At times the build can take anywhere from 5-15 mins, on the rare occasion it can take maybe 2-3 minutes -- Building to an iOS device or emulator is also terribly buggy, we build to a device, run some tests identify changes that need made., make some small change then wait up to 15min for the project to build to be tested.
 
### Steps to Reproduce

1.  Just create any xamarin forms project and attempt to deploy to an iOS device -- Currently the project i'm working on is about 40 MB however if you want to see the different between xamarin forms and xCode it's very easy to create a couple of test projects using both xamarin forms and swift
2. 
3. 

### Expected Behavior
That i can use Xamarin forms for professional development when supporting iOS
### Actual Behavior
I can't
### Basic Information

- Version with issue: 4.8.0.1560
- Last known good version: -- None
- IDE: Visual studio Enterprise 2019 v16.6.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Nuget Packages: We have many Nuget packages 
- Affected Devices:

**Comment by rolfbjarne** [comment]
@MitchBomcanhao that does not apply to Xamarin.iOS, because we don't need these symbols on the iOS device (and never copy them there either).

**Comment by spouliot** [comment]
Closing (inactivity). The provided logs showed a different issue (Xcode) which was explained.

If you can still duplicate the original issue then please provide the [requested logs](https://github.com/xamarin/xamarin-macios/issues/10267#issuecomment-720534783) and we can re-open the issue. Thanks!
