### ISSUE TITLE
iOS code signing key 'Apple Distribution: ...' not found in keychain

### ISSUE THREAD

**Issue by SoledadIce** [xamarin/xamarin-macios#10265]
Get this error when build Xamarin.iOS project under "Ad-Hoc, iPhone".

The key is available in the "Keychain Access" in Mac.

Have tried to recreate certificate as well as profile. 

### Environment
1. Xcode: Version 12.2
2.
Microsoft Visual Studio Professional 2019 (2)
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-30015-46448-AA022
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.554.20160
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.554.20160
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.554.20160
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.554.20160
Azure Functions and Web Jobs Tools

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CSS Tools 2019   1.1.4
Provides additional features to the CSS editor in Visual Studio.

EditorConfig Language Service   1.17.284
Language service for .editorconfig files.

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

File Nesting   2.6.85
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitExtensions   1.0
Git Extensions is a graphical user interface for Git that allows you to control Git without using the command-line

Image Optimizer   4.0.132
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Image Sprites   1.4.61
Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Markdown Editor   1.12.253
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.4.233
2.4.233

Package Installer   2.0.103
Makes it easier, faster and more convenient than ever to install Bower, npm, Yarn, JSPM, TSD, Typings and NuGet packages to any project

Package Security Alerts   1.0.22
Identifies npm and Bower packages that contains known security vulnerabilities to ensure your project is always using the most secure package versions.

Productivity Power Tools 2017/2019   16.0
Installs the individual extensions of Productivity Power Tools 2017/2019

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

SVG Viewer   1.0.9
Makes it much easier to work with SVG files by showing a live preview in the bottom-right corner of the code window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Web Accessibility Checker   1.5.58
The easiest way to perform accessibility checks on any ASP.NET web application. Fully customizable and support all the major international accessibility standards.

Web Compiler   1.12.394
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2019   0.5.10
The easiest way to set up Visual Studio for the ultimate web development experience.

WiX Toolset Visual Studio Extension   1.0.0.4
WiX Toolset Visual Studio Extension version 1.0.0.4
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   16.8.000.260 (d16-8@fd405a2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.6.0.15 (87a1b18d8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

ZenCoding   1.2.12
Provides ZenCoding for the HTML Editor - full support for static HTML, Razor and WebForms.

**Comment by rolfbjarne** [comment]
Please attach a diagnostic build log. Build log can be found in the Build Output tab of the Errors pad in Visual Studio

To get a diagnostic build log, set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

**Comment by SoledadIce** [comment]
> Please attach a diagnostic build log. Build log can be found in the Build Output tab of the Errors pad in Visual Studio
> 
> To get a diagnostic build log, set the log verbosity to diagnostic at the following locations:
> 
> * On Visual Studio for Mac: Preferences > Projects > Build
> * On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run
> 
> On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

[build log.txt](https://github.com/xamarin/xamarin-macios/files/5688261/build.log.txt)

**Comment by SoledadIce** [comment]
> Please attach a diagnostic build log. Build log can be found in the Build Output tab of the Errors pad in Visual Studio
> 
> To get a diagnostic build log, set the log verbosity to diagnostic at the following locations:
> 
> * On Visual Studio for Mac: Preferences > Projects > Build
> * On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run
> 
> On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

[build log-WithMtouchArguments.txt](https://github.com/xamarin/xamarin-macios/files/5688441/build.log-WithMtouchArguments.txt)

**Comment by rolfbjarne** [comment]
@SoledadIce what's the error that shows in the IDE for these builds? It does not look like a signing error, but instead it seems it's a check that you have the right Xcode version on the Mac machine that is triggered.

**Comment by SoledadIce** [comment]
> @SoledadIce what's the error that shows in the IDE for these builds? It does not look like a signing error, but instead it seems it's a check that you have the right Xcode version on the Mac machine that is triggered.

Hey Rolf, thanks for your reply.
I only got the error below. Besides, I only have one Xcode installed on my mac, which has the verison 12.2(12B35b). I will try to reinstall the Xcode then come back to you with result.

Target "_DetectLocalSigningIdentity: (TargetId:163)" in file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Local.targets" from project "C:\Users\jwu\Documents\Workspace\MOAA.MobileReport\MOAA.MobileReport\MOAA.MobileReport.iOS\MOAA.MobileReport.iOS.csproj" (target "_CompileInterfaceDefinitions" depends on it):
2>Using "DetectLocalSigningIdentity" task from assembly "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Local.Tasks.dll".
2>Task "DetectLocalSigningIdentity" (TaskId:97)
2>  Task Parameter:SigningKey=Apple Distribution: Masters of Arts Anwendungsentwicklung GmbH (BT9BQSPS6F) (TaskId:97)
2>  Task Parameter:ProvisioningProfile=HansaSIR Provision (Add-Hoc) (TaskId:97)
2>  Task Parameter:AppManifest=Info.plist (TaskId:97)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Local.targets(18,3): error : iOS code signing key 'Apple Distribution: Masters of Arts Anwendungsentwicklung GmbH (BT9BQSPS6F)' not found in keychain.
2>  Output Property: _BundleIdentifier=com.moaa.HansaSIR (TaskId:97)
2>  Output Property: _AppDisplayName=Hansa SIR (TaskId:97)
2>Done executing task "DetectLocalSigningIdentity" -- FAILED. (TaskId:97)
2>Done building target "_DetectLocalSigningIdentity" in project "MOAA.MobileReport.iOS.csproj" -- FAILED.: (TargetId:163)

**Comment by SoledadIce** [comment]
> @SoledadIce what's the error that shows in the IDE for these builds? It does not look like a signing error, but instead it seems it's a check that you have the right Xcode version on the Mac machine that is triggered.

FYI, after reinstalling Xcode, still get the same error. I don't know what to do anymore :(

**Comment by rolfbjarne** [comment]
@SoledadIce this error:

> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Local.targets(18,3): error : iOS code signing key 'Apple Distribution: Masters of Arts Anwendungsentwicklung GmbH (BT9BQSPS6F)' not found in keychain.

does not show up in the files you attached.

**Comment by SoledadIce** [comment]
> @SoledadIce this error:
> 
> > 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Local.targets(18,3): error : iOS code signing key 'Apple Distribution: Masters of Arts Anwendungsentwicklung GmbH (BT9BQSPS6F)' not found in keychain.
> 
> does not show up in the files you attached.

Hi Rolf, after a lot of try, I found it works when I use the full administrator account to start visual studio. So this might be an issue with VS or our system administrator. Thanks for the checking and I think this issue can be closed.

**Comment by rolfbjarne** [comment]
@SoledadIce ok, I'll close this then. Feel free to reopen or create a new issue if you have any further problems!
