### ISSUE TITLE
.NET 6: device support

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10291]
# Current status

Seems to work for the most part.

## Tests

* ✅  don't link
    * ✅ iOS 64-bit - device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * ⚠️ iOS 32-bit - device
        * ⚠️ Debug [dotnet]: build fails due to code being too large (app isn't linked)
        * ⚠️ Release [dotnet]: build fails due to code being too large (app isn't linked)
    * ✅ tvOS 64-bit - device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
* ✅ framework-test
    * ✅ iOS 64-bit device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * ✅ iOS 32-bit device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * ✅ tvOS 64-bit device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
* ✅ fsharp
    * ✅  iOS 64-bit device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * ✅ iOS 32-bit device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * ✅ tvOS 64-bit device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
* ❓ interdependent-binding-tests
    * iOS 64-bit - device
        * ❌ Debug [dotnet]: BuildFailure: #12275
        * ❌ Release [dotnet]: BuildFailure: #12275
    * iOS 32-bit - device
        * ❓ Debug [dotnet]
        * ❓ Release [dotnet]
    * tvOS 64-bit - device
        * ❌ Debug [dotnet]: BuildFailure: #12275
        * ❌ Release [dotnet]: BuildFailure: #12275
* ✅ introspection
    * ✅ iOS 64-bit - device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * ⚠️ iOS 32-bit - device
        * ⚠️ Debug [dotnet]: build fails due to code being too large (app isn't linked)
        * ⚠️ Release [dotnet]: build fails due to code being too large (app isn't linked)
    * tvOS 64-bit - device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
* ✅ link all
    * ✅ iOS 64-bit - device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * ✅ iOS 32-bit - device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * tvOS 64-bit - device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
* ✅ link sdk
    * ✅ iOS 64-bit - device
        * ✅ Debug [dotnet]
            * [#2266](https://github.com/mono/linker/issues/2266)  - test ignored for now
        * ✅ Release [dotnet]
            * [#2266](https://github.com/mono/linker/issues/2266)  - test ignored for now
    * ✅ iOS 32-bit - device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * ✅ tvOS 64-bit - device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
* ✅ monotouch-test
    * ✅ iOS 64-bit - device
        * ✅ Debug (all optimizations) [dotnet]
        * ✅ Debug (dynamic registrar) [dotnet]
        * ✅ Debug (interpreter -mscorlib) [dotnet]
        * ✅ Debug (interpreter) [dotnet]
        * ✅ Debug (sgenconc) [dotnet]
        * ✅ Release (all optimizations) [dotnet]
        * ✅ Release (interpreter -mscorlib) [dotnet]
        * ✅ Release (LLVM) [dotnet]
        * ✅ Release [dotnet]
    * ✅ iOS 32-bit - device
        * ✅ Debug (all optimizations) [dotnet]
        * ✅ Debug [dotnet]
        * ✅ Debug (sgenconc) [dotnet]
        * ✅ Release (LLVM) [dotnet]
        * ✅ Release [dotnet]
    * ✅ tvOS 64-bit - device
        * ✅ Debug (all optimizations) [dotnet]
        * ✅ Debug (dynamic registrar) [dotnet]
        * ✅ Debug (interpreter -mscorlib) [dotnet]
        * ✅ Debug (interpreter) [dotnet]
        * ✅ Debug [dotnet]
        * ✅ Debug (sgenconc) [dotnet]
        * ✅ Release (all optimizations) [dotnet]
        * ✅ Release (interpreter -mscorlib) [dotnet]
        * ✅ Release (LLVM) [dotnet]
        * ✅ Release [dotnet]
* ✅ xcframework-test
    * ✅ iOS 64-bit device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * ✅ iOS 32-bit device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
    * ✅ tvOS 64-bit device
        * ✅ Debug [dotnet]
        * ✅ Release [dotnet]
---

Time estimate: 1 week once existing runtime bugs have been fixed for remaining tasks.

**Comment by spouliot** [comment]
why the link to #10290 ? typo ?

**Comment by rolfbjarne** [comment]
> why the link to #10290 ? typo ?

Yes, that was a c&p mistake (fixed now).

**Comment by rolfbjarne** [comment]
All the device tests have been executed, and all the failures except one has been fixed. That failure is tracked separately, and it's not necessary to keep this open anymore, so I'm closing this issue.
