### ISSUE TITLE
'VS for Mac' or 'BTOUCH' have a bug

### ISSUE THREAD

**Issue by locustgxf** [xamarin/xamarin-macios#10316]
When I check the 'Enalbe incremental builds' option, or set 'Additional mtouch arguments' to empty, errors will occur when the program is running.

From the error log, I can see that the frameworks such as BUSDKAuxiliary.framework are not linkted and compiled into my program. Which caused an error that could not find the'selector',during the program running.

I put the test project code in the URL below:
http://driver.tongbu.com/TestSDK_20201218.zip

![image](https://user-images.githubusercontent.com/31130962/102571698-18c39b80-4125-11eb-8d05-e47faf8aa643.png)

### Application Output
2020-12-18 11:46:23.992 TestSDK[44444:6260381] +[BUSDKAuxiliary bu_GDPR_URL]: unrecognized selector sent to class 0x10baf0140
2020-12-18 11:46:24.176 TestSDK[44444:6260381] ------------Time:2020/12/18 11:46:24---------------
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: +[BUSDKAuxiliary bu_GDPR_URL]: unrecognized selector sent to class 0x10baf0140
Native stack trace:
	0   CoreFoundation                      0x00000001b9333770 <redacted> + 256
	1   libobjc.A.dylib                     0x00000001b853bd00 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001b9251a60 <redacted> + 0
	3   CoreFoundation                      0x00000001b93390fc <redacted> + 1412
	4   CoreFoundation                      0x00000001b933aeb0 _CF_forwarding_prep_0 + 96
	5   libCoreSDK.dll.dylib                0x000000010b635a80 -[BUAdSDKManager setupService] + 176
	6   libCoreSDK.dll.dylib                0x000000010b634ffc __32+[BUAdSDKManager sharedInstance]_block_invoke + 96
	7   libdispatch.dylib                   0x00000001b8d458f4 <redacted> + 20
	8   libdispatch.dylib                   0x00000001b8d47788 <redacted> + 32
	9   libCoreSDK.dll.dylib                0x000000010b634f98 +[BUAdSDKManager sharedInstance] + 112
	10  libCoreSDK.dll.dylib                0x000000010b636530 +[BUAdSDKManager appID] + 32
	11  libCoreSDK.dll.dylib                0x000000010b868a58 wrapper_managed_to_native_ApiDefinition_Messaging_IntPtr_objc_msgSend_intptr_intptr + 200
	12  libCoreSDK.dll.dylib                0x000000010b720598 iTong_CoreSDK_BUAdSDKManager_get_AppID + 168
	13  libTestSDK.exe.dylib                0x000000010314c6b0 TestApp_BU_SetAppID_string_bool_bool + 128
	14  libTestSDK.exe.dylib                0x000000010314cad8 TestApp_BU_ShowSplashAD_TestApp_AdInfo_System_EventHandler_1_TestApp_AdEventArgs + 792
	15  libTestSDK.exe.dylib                0x00000001031451a8 TestApp_ViewController_ViewDidLoad + 648
	16  libmscorlib.dll.dylib               0x0000000103e3a180 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 272
	17  libmonosgen-2.0.dylib               0x000000010beb564c mono_jit_runtime_invoke + 1144
	18  libmonosgen-2.0.dylib               0x000000010bf718ac mono_runtime_invoke_checked + 148
	19  libmonosgen-2.0.dylib               0x000000010bf75110 mono_runtime_invoke + 144
	20  TestSDK                             0x00000001028bcd50 _ZL30native_to_managed_trampoline_6P11objc_objectP13objc_selectorPP11_MonoMethodj + 236
	21  TestSDK                             0x00000001028bcc58 -[ViewController viewDidLoad] + 44
	22  UIKitCore                           0x00000001e5c44360 <redacted> + 1028
	23  UIKitCore                           0x00000001e5c4476c <redacted> + 32
	24  UIKitCore                           0x00000001e624ab2c <redacted> + 140
	25  UIKitCore                           0x00000001e624b0dc <redacted> + 276
	26  UIKitCore                           0x00000001e625be28 <redacted> + 52
	27  UIKitCore                           0x00000001e620c944 <redacted> + 3604
	28  UIKitCore                           0x00000001e62122b0 <redacted> + 1584
	29  UIKitCore                           0x00000001e5aa5e20 <redacted> + 800
	30  UIKitCore                           0x00000001e5aae7e8 <redacted> + 168
	31  UIKitCore                           0x00000001e5aa5a88 <redacted> + 252
	32  UIKitCore                           0x00000001e5aa63a4 <redacted> + 1068
	33  UIKitCore                           0x00000001e5aa45ec <redacted> + 748
	34  UIKitCore                           0x00000001e5aa42b0 <redacted> + 460
	35  UIKitCore                           0x00000001e5aa8fd0 <redacted> + 224
	36  UIKitCore                           0x00000001e5aa9e1c _performActionsWithDelayForTransitionContext + 120
	37  UIKitCore                           0x00000001e5aa8e84 <redacted> + 260
	38  UIKitCore                           0x00000001e5aade68 <redacted> + 364
	39  UIKitCore                           0x00000001e62107ec <redacted> + 556
	40  UIKitCore                           0x00000001e5df3648 <redacted> + 376
	41  FrontBoardServices                  0x00000001bbcf13a8 <redacted> + 456
2020-12-18 11:46:24.176 TestSDK[44444:6260381] 
	42  FrontBoardServices                  0x00000001bbcfb6e4 <redacted> + 284
	43  FrontBoardServices                  0x00000001bbcfae34 <redacted> + 72
	44  libdispatch.dylib                   0x00000001b8d458f4 <redacted> + 20
	45  libdispatch.dylib                   0x00000001b8d48ecc <redacted> + 252
	46  FrontBoardServices                  0x00000001bbd2e218 <redacted> + 48
	47  FrontBoardServices                  0x00000001bbd2de94 <redacted> + 436
	48  FrontBoardServices                  0x00000001bbd2e490 <redacted> + 56
	49  CoreFoundation                      0x00000001b92c3954 <redacted> + 28
	50  CoreFoundation                      0x00000001b92c38d0 <redacted> + 92
	51  CoreFoundation                      0x00000001b92c318c <redacted> + 180
	52  CoreFoundation                      0x00000001b92bde60 <redacted> + 988
	53  CoreFoundation                      0x00000001b92bd764 CFRunLoopRunSpecific + 452
	54  GraphicsServices                    0x00000001bb4f9dd4 GSEventRunModal + 108
	55  UIKitCore                           0x00000001e621400c UIApplicationMain + 216
	56  libXamarin.iOS.dll.dylib            0x0000000105fa0518 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 344
	57  libXamarin.iOS.dll.dylib            0x000000010565c780 UIKit_UIApplication_Main_string___intptr_intptr + 48
	58  libXamarin.iOS.dll.dylib            0x000000010565c604 UIKit_UIApplication_Main_string___string_string + 68
	59  libTestSDK.exe.dylib                0x0000000103144880 TestApp_Application_Main_string__ + 128
	60  libmscorlib.dll.dylib               0x0000000103e3a180 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 272
	61  libmonosgen-2.0.dylib               0x000000010beb564c mono_jit_runtime_invoke + 1144
	62  libmonosgen-2.0.dylib               0x000000010bf718ac mono_runtime_invoke_checked + 148
	63  libmonosgen-2.0.dylib               0x000000010bf77b04 mono_runtime_exec_main_checked + 128
	64  libmonosgen-2.0.dylib               0x000000010be92f88 mono_jit_exec + 376
	65  libxamarin-debug.dylib              0x000000010343475c xamarin_main + 1976
	66  TestSDK                             0x0000000102952670 main + 84
	67  libdyld.dylib                       0x00000001b8d7cffc <redacted> + 4

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: 6a0d5361-1838-4a76-8f64-73f78ae448d8
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	5.0.100
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.200
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.302
	2.1.4
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	5.0.0
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.2
	2.0.5

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Sun Jul  5 00:43:10 PDT 2020
    root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

```

**Comment by rolfbjarne** [comment]
You should be able to remove the additional mtouch flags if you add those flags to the LinkerFlags property for the frameworks that need them in the binding project.

And once that's done, try again to enable device specific builds.

**Comment by locustgxf** [comment]
I tried dropping the mtouch parameters or enabling incremental builds, but the program didn't work. I had to disable incremental builds and add mtouch parameters for the program to run properly. I don't know why this is the case. In the past, when the VS version was lower, there was no such problem.

**Comment by tj-devel709** [comment]
Hello. When you removed the mtouch parameters from the options, did you add them to Native References node’s Properties of each framework in the binding project? If not, you can open up your Native References and right click on them to open the Properties tab. Then, you can add the appropriate Frameworks and Linker Flags there. Doing this should allow you to get rid of the additional mtouch arguments.
![image](https://user-images.githubusercontent.com/50846373/103591422-c10f8900-4eb5-11eb-9dd7-2c9620a7286c.png)

**Comment by locustgxf** [comment]
I tried to remove the mtouch parameter. In the properties tab of the local reference library of the ObjCBinding project, I set the frame and linker flags, but the program still cannot run normally.

I tried the following two solutions, but the program does not work properly:
One,
Framework: StoreKit MobileCoreServices WebKit MediaPlayer CoreMedia CoreLocation AVFoundation CoreTelephony SystemConfiguration AdSupport CoreMotion Accelerate ImageIO Security
Linker Flags: -lresolv -lc++ -lz -lsqlite3 -lbz2 -lxml2 -liconv

two,
Linker Flags: -lresolv -lc++ -lz -lsqlite3 -lbz2 -lxml2 -liconv -framework StoreKit -framework MobileCoreServices -framework WebKit -framework MediaPlayer -framework CoreMedia -framework CoreLocation -framework AVFoundation -framework CoreTelephony -framework SystemConfiguration -framework AdSupport -framework CoreMotion -framework Accelerate -framework ImageIO -framework Security

**Comment by tj-devel709** [comment]
Would you be able to send an updated project with these changes?

**Comment by locustgxf** [comment]
I put the updated project code in the URL below:
http://driver.tongbu.com/TestSDK_20210108.zip

**Comment by locustgxf** [comment]
I put the updated project code in the URL below:
http://driver.tongbu.com/TestSDK_20210108.zip

**Comment by locustgxf** [comment]
I put the updated project code in the URL below:
http://driver.tongbu.com/TestSDK_20210108.zip

You can debug the code and breakpoint under the ‘SetAppID’ of the ‘ShowSplashAD’ function in the ‘TestApp/TestApp/zClass/BU.cs’ file.
As long as the mtouch parameter is blank, the program will report an error when running on the device.


TestApp/TestApp/zClass/BU.cs
public static UIWindow ShowSplashAD(AdInfo adInfo, EventHandler<AdEventArgs> adCloseCallback)
{
...
SetAppID(adInfo.AppID);//Set a breakpoint here, and an error will be reported when this function is executed
...
}

In the native reference of CoreSDK_iOS project, I tried to set the following two parameters in BUAdSDK, BUCNAuxiliary and BUFoundation,but the program still cannot run normally.

One,
Framework: StoreKit MobileCoreServices WebKit MediaPlayer CoreMedia CoreLocation AVFoundation CoreTelephony SystemConfiguration AdSupport CoreMotion Accelerate ImageIO Security
Linker Flags: -lresolv -lc++ -lz -lsqlite3 -lbz2 -lxml2 -liconv

two,
Linker Flags: -lresolv -lc++ -lz -lsqlite3 -lbz2 -lxml2 -liconv -framework StoreKit -framework MobileCoreServices -framework WebKit -framework MediaPlayer -framework CoreMedia -framework CoreLocation -framework AVFoundation -framework CoreTelephony -framework SystemConfiguration -framework AdSupport -framework CoreMotion -framework Accelerate -framework ImageIO -framework Security

**Comment by locustgxf** [comment]
The following link is the SDK download url, including OC source code examples.
https://sf1-be-tos.pglstatp-toutiao.com/obj/union-platform/cd183d8509f4060266216ed764b92b12.zip

**Comment by spouliot** [comment]
> When I check the 'Enalbe incremental builds' option, or set 'Additional mtouch arguments' to empty

@locustgxf when using your http://driver.tongbu.com/TestSDK_20210108.zip I can deploy the app to my phone without any issue.

If I click on "Enable incremental builds", do a clean and build again, the app also deploy and runs fine on my phone.

In both case the "Additional mtouch arguments" were

```
-gcc_flags "-ObjC -lresolv -lc++ -lz -lsqlite3 -lbz2 -lxml2 -liconv -framework StoreKit -framework MobileCoreServices -framework WebKit -framework MediaPlayer -framework CoreMedia -framework CoreLocation -framework AVFoundation -framework CoreTelephony -framework SystemConfiguration -framework AdSupport -framework CoreMotion -framework Accelerate -framework ImageIO -framework Security"
```

If I remove the "Additional mtouch arguments" then the app also starts fine.

**Comment by spouliot** [comment]
The first flag of your **Additional mtouch arguments** is `-ObjC`

None of the **Native References** had that flag set. So when you deleted the **Additional mtouch arguments** you were actually doing a different build that excluded ObjC code - which means the frameworks were not added to the `.app`.

The fix is to add `-ObjC` to at least one of the **Native References** **Linker Flags** and rebuild.
