### ISSUE TITLE
Invalid Executable - The executable ProjectName WatchKit Extension' does not contain bitcode

### ISSUE THREAD

**Issue by shiv-it2012** [xamarin/xamarin-macios#10327]
I have been trying to submit my watch app in the app store but It's been rejected due to the following reason.

**Invalid Executable - The executable 'ProjectName.app/Watch/ProjectName WatchKit App.app/PlugIns/ProjectName WatchKit Extension.appex/ProjectName WatchKit Extension' does not contain bitcode**

I have enabled the bitcode of all the targets except the Test target.
Also i don't see any bitcode related settings in the target for watchExtension.
I have strolled through many links but didn't find any concrete solution as yet.

Any help would be highly appreciated. Thank you so much in advance.

**Comment by dalexsoto** [comment]
Hello, please try to run this command against you watch executable in a mac machine

`otool -l "ProjectName.app/Watch/ProjectName WatchKit App.app/PlugIns/ProjectName WatchKit Extension.appex/ProjectName WatchKit Extension" | grep __LLVM`

You should see something like `segname __LLVM` if that shows up it means your executable contains bitcode

If you do not get any output could you try to replicate this on a brand new project and try to submit to apple to see if it fails the same way, if it does please share your test case with us, if it doesn't fail please try to match the project settings on your app.

Thank you!

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
