### ISSUE TITLE
Packaging issue on xamarin ios on mac

### ISSUE THREAD

**Issue by DmitryLukyanov** [xamarin/xamarin-macios#10337]
### Steps to Reproduce

1.  Create a new xamarin multiplatform app with xamarin iOS.
2.  Consume MongoDB.Driver nuget: https://www.nuget.org/packages/MongoDB.Driver/2.11.5  
3.  Rebuild application

### Expected Behavior

No errors

### Actual Behavior

I see this error:

    #FULLPATH#/testapp.iOS/MTOUCH:Error MT0009: Error while loading assemblies: /Users/#USERNAME#/.nuget/packages/mongodb.driver.core/2.11.5/runtimes/win/native/libzstd.dll. (MT0009) (testapp.iOS)

### Environment

![image](https://user-images.githubusercontent.com/44870738/103382468-323eed00-4b00-11eb-8bcc-e623956b9e3d.png)

### Build Logs

		...
		Target _DetectDebugNetworkConfiguration:
			  DebugIPAddresses: 127.0.0.1
		Target _CompileAppManifest:
			Directory "bin/iPhoneSimulator/Debug/device-builds/ipod touch (7th generation)-14.3/testapp.iOS.app.dSYM" doesn't exist. Skipping.
		Target _ParseExtraMtouchArgs:
			  NoSymbolStrip Output: False
			  NoDSymUtil Output: false
		Target _CompileToNative:
			/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch "@/Users/#USERNAME#/Projects/testapp/testapp.iOS/obj/iPhoneSimulator/Debug/device-builds/ipod touch (7th generation)-14.3/response-file.rsp" 
			Xamarin.iOS 14.6.0.15 (d16-8: ### using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk
			MTOUCH : error MT0009: Error while loading assemblies: /Users/#USERNAME#/.nuget/packages/mongodb.driver.core/2.11.5/runtimes/win/native/libzstd.dll.
			
		Done building target "_CompileToNative" in project "testapp.iOS.csproj" -- FAILED.
		Done building project "testapp.iOS.csproj" -- FAILED.

		Build FAILED.
		...

### Example Project

I generate a nuget package (via `dotnet pack`) based on the below versions:
See this commit: https://github.com/DmitryLukyanov/mongo-csharp-driver/commit/27fc577fdd38c28a76d7630d68570bed7cb5ac3f

* The base commit for the above:
    When I consume the generated nuget on xamarin iOS and then build the consumer app, it fails with the mentioned error. 
* The changed version contains the workaround. You may see that the only difference that I changed the top-level RID from `win` to `win-x32` and `win-x64`. Even though the workaround looks valid, I would prefer to leave the previous version (since originally this was implemented in this way by purpose). 

So this issue looks like a bug since, for some reason, `xamarin iOS` is trying to process a windows related library from `win` folder on `mac OS` and don't do it if I use `win-x32/win-x64`.

It looks like this is related to this issue: https://github.com/xamarin/xamarin-macios/issues/5265 But nothing from the mentioned issue helped me. Are there any ideas?

NOTE: I always build nuget packages on windows.

**Comment by pasha-o** [comment]
@tj-devel709 @DmitryLukyanov can you guys advise where are you with this serious issue. i reported this mid 2020 and is stopping us from deploying latest version of the mongodb driver to xamarin  iOS. this is becoming unbearable how things are moving so slow. any update?

**Comment by DmitryLukyanov** [comment]
Hey, is there a raw estimation of when this issue can be investigated? :)

**Comment by spouliot** [comment]
This can be duplicated and should have been earlier, sorry about that.

The `_CopyFilesMarkedCopyLocal` task from `msbuild` incorrectly gives us the win-specific assemblies to copy. This is wrong and what you're seeing, later, is our tool complaining about it. 

I'm not sure if the issue is with the nuget package, nuget itself or msbuild.

However the SDK error is "normal" since we're not provided with the correct input, hence cannot produce a correct output.

```
Target "_CopyFilesMarkedCopyLocal" in file "/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets":
  Using "Copy" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/../iOS/Xamarin.iOS.Tasks.dll".
  Task "Copy"
    Copying file from "/Users/poupou/.nuget/packages/mongodb.driver/2.11.6/lib/netstandard2.0/MongoDB.Driver.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/MongoDB.Driver.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.driver.core/2.11.6/runtimes/win/native/snappy64.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/snappy64.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.driver.core/2.11.6/runtimes/win/native/snappy32.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/snappy32.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.bson/2.11.6/lib/netstandard2.0/MongoDB.Bson.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/MongoDB.Bson.dll".
    Copying file from "/Users/poupou/.nuget/packages/dnsclient/1.3.1/lib/netstandard2.1/DnsClient.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/DnsClient.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.driver.core/2.11.6/runtimes/win/native/libzstd.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/libzstd.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.driver.core/2.11.6/lib/netstandard2.0/MongoDB.Driver.Core.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/MongoDB.Driver.Core.dll".
    Copying file from "/Users/poupou/.nuget/packages/mongodb.libmongocrypt/1.0.0/lib/netstandard1.5/MongoDB.Libmongocrypt.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/MongoDB.Libmongocrypt.dll".
    Copying file from "/Users/poupou/.nuget/packages/sharpcompress/0.23.0/lib/netstandard2.0/SharpCompress.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/SharpCompress.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.buffers/4.4.0/lib/netstandard2.0/System.Buffers.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Buffers.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.io.compression/4.3.0/runtimes/win/lib/netstandard1.3/System.IO.Compression.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.IO.Compression.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.net.http/4.3.0/runtimes/win/lib/netstandard1.3/System.Net.Http.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Net.Http.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.runtime.interopservices.runtimeinformation/4.3.0/runtimes/win/lib/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Runtime.InteropServices.RuntimeInformation.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.security.cryptography.algorithms/4.3.0/runtimes/win/lib/netstandard1.6/System.Security.Cryptography.Algorithms.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Security.Cryptography.Algorithms.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.security.cryptography.encoding/4.3.0/runtimes/win/lib/netstandard1.3/System.Security.Cryptography.Encoding.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Security.Cryptography.Encoding.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.security.cryptography.x509certificates/4.3.0/runtimes/win/lib/netstandard1.6/System.Security.Cryptography.X509Certificates.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Security.Cryptography.X509Certificates.dll".
    Copying file from "/Users/poupou/.nuget/packages/system.text.encoding.codepages/4.5.1/runtimes/win/lib/netstandard2.0/System.Text.Encoding.CodePages.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/System.Text.Encoding.CodePages.dll".
    Copying file from "/Users/poupou/.nuget/packages/xamarin.essentials/1.5.3.2/lib/xamarinios10/Xamarin.Essentials.dll" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/Xamarin.Essentials.dll".
    Copying file from "/Users/poupou/.nuget/packages/xamarin.essentials/1.5.3.2/lib/xamarinios10/Xamarin.Essentials.pdb" to "/Users/poupou/Projects/bugs/gh10337/bin/iPhoneSimulator/Debug/Xamarin.Essentials.pdb".
  Done executing task "Copy".
  Using "Touch" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/../iOS/Xamarin.iOS.Tasks.dll".
  Task "Touch"
    Creating "/Users/poupou/Projects/bugs/gh10337/obj/iPhoneSimulator/Debug/gh10337.csproj.CopyComplete" because "AlwaysCreate" was specified.
  Done executing task "Touch".
Done building target "_CopyFilesMarkedCopyLocal" in project "gh10337.csproj".
```

I opened an issue with msbuild https://github.com/dotnet/msbuild/issues/6072
