### ISSUE TITLE
error MT0099 : Internal error : The interpreter is currently only available for 64 bits.

### ISSUE THREAD

**Issue by omatrot** [xamarin/xamarin-macios#10331]
Unable to target both ARMv7 + ARM64 on a specific Xamarin.Forms iOS project.

It works in other projects so I guess it is a library/nuget issue.

### Steps to Reproduce

Unable to reproduce it in a sample. Diagnostic build log available below.

### Expected Behavior

Build works.

### Actual Behavior

Build fails.

### Environment

```
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.9 Preview (8.9 build 964)
Installation UUID: 378f19df-e192-4f2d-95f8-31b06b3acf15
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.9.0-2.20573.18+bc20ce579f9b17c9153f3f54a0690d23c482d899

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	5.0.100
	5.0.100-rc.2.20479.15
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.100
	3.1.100-preview3-014645
	3.1.100-preview2-014569
	3.0.100
	3.0.100-rc1-014190
	3.0.100-preview9-014004
	3.0.100-preview8-013656
	2.1.811
	2.1.810
	2.1.701
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	5.0.0
	5.0.0-rc.2.20475.5
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.0
	3.1.0-preview3.19553.2
	3.1.0-preview2.19525.6
	3.0.0
	3.0.0-rc1-19456-20
	3.0.0-preview9-19423-09
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.14
	2.1.13
	2.1.12

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.9.0.27 (Visual Studio Community)
Hash: f4c9327fa
Branch: main
Build date: 2020-11-19 10:57:31-0500

=== Xamarin Designer ===

Version: 16.9.0.105
Hash: f693266a2
Branch: remotes/origin/main
Build date: 2020-12-02 05:56:40 UTC

=== Xamarin.Android ===

Version: 11.1.99.218 (Visual Studio Community)
Commit: xamarin-android/master/9bc0003
Android SDK: /Users/omatrot/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: ac59637
Java.Interop: xamarin/java.interop/master@99897b2
ProGuard: Guardsquare/proguard/v7.0.0@84e8560
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@ab650f5

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/omatrot/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.19
Hash: 9771026
Branch: remotes/origin/HEAD
Build date: 2020-11-21 02:03:08 UTC

=== Android Device Manager ===

Version: 16.9.0.13
Hash: bbbb387
Branch: remotes/origin/main
Build date: 2020-11-21 02:03:28 UTC

=== Build Information ===

Release ID: 809000964
Git revision: 0ab5ced8f8f39c1837b5879f51401c6fd1ae41ef
Build date: 2020-12-15 08:05:14-05
Build branch: release-8.9
Xamarin extensions: 0ab5ced8f8f39c1837b5879f51401c6fd1ae41ef

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Mon Dec  7 22:04:02 PST 2020
    root:xnu-7195.80.16.111.1~1/RELEASE_X86_64 x86_64

```

### Build Logs

https://gist.github.com/omatrot/31a550044a538ea94a3d8bbf33e3a278

**Comment by tj-devel709** [comment]
Hello, thank you very much for your feedback!

The linker currently only supports 64 bits.

**Comment by omatrot** [comment]
As I said, it works well for other project...
Anyway, if we won't go any further with this, please adjust the compiler error, because opening an issue is worthless.

**Comment by dalexsoto** [comment]
Hello @omatrot thanks for reaching out!

First of all sorry, it seems that we have a bit of a misunderstanding here, we were a little to quick to pull the trigger. What @tj-devel709 wrote is correct, the [interpreter](https://devblogs.microsoft.com/xamarin/introducing-xamarin-ios-interpreter/) is only 64 bits as of today but it looks like you did not enable the interpreter yourself (at least from the info you provided). 

What could be happening is that you may have the [XAML Hot Reload](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload) feature enabled for your project which required the interpreter to be enabled and it is preventing you to build for `ARMv7 + ARM64` so you would have two options if this is the case

1. Disable XAML Hot Reload
2. Just build for arm64

The build log provided seems incomplete so I can't know for sure if this is you actual issue but I think it is.

Hope this helps and sorry again.

**Comment by omatrot** [comment]
I've disabled XAML Hot Reload and the mono interpreter.
I need to build for ARM7 because I wanted to target iOS 9.3.6 on 32-bit devices.
I now have other errors suggesting that the mono interpreter is required for Xamarin.Forms on iOS.
I can say that the other projects where I could target iOS 9.3.6 on 32-bit devices are not using Xamarin.Forms, just Xamarin.iOS.

**Comment by dalexsoto** [comment]
@omatrot that seems odd, I do not think that Xamarin.Forms has the interpreter as a hard requirement, is there any chance you could isolate this issue zip it and share it with us?

**Comment by omatrot** [comment]
I have hundreds of the following errors with the interpreter disabled:
https://docs.microsoft.com/xamarin/ios/troubleshooting/questions/error-encode-offset-scattered-relocation
Not directly tied to Xamarin.Forms.
I'm afraid I won't have time to spend on this issue.

**Comment by spouliot** [comment]
@omatrot the hot reload ask for the interpreter and to disable the managed linker.

You must re-enable the managed linker (e.g. Link SDK frameworks) for debugging 32bits. Otherwise there's too much code and Apple's native linker cannot create a working executable.

Your other iOS projects, working on 32bits, are likely set to "Link SDK" since this is the default value for new projects.

**Comment by rolfbjarne** [comment]
I'm closing this, since it seems we've answered your questions/problems.

Feel free to reopen if this is not the case.
