### ISSUE TITLE
[Xamarin.Mac] UNUserNotificationCenter in VS4M (v8.8.4.30 - Latest stable) authorisation always fails in Mac app, while Swift.Mac version works. Example code below....

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/xamarin-macios#10356]
### Description
UNUserNotificationCenter in VS4M (v8.8.4.30 - Latest stable) authorisation always fails in Mac app, while this works in Xamarin.iOS and a Swift.Mac version works too.

### Steps to Reproduce

I'm using to the following code to check it my app is authorised for Notifications (only valid in MacOS 10.14+)
    
    uses UserNotifications;
    
    public override void DidFinishLaunching (NSNotification notification)
            {
                   // Check we're at least v10.14
                    if (NSProcessInfo.ProcessInfo.IsOperatingSystemAtLeastVersion (new NSOperatingSystemVersion (10, 14, 0))) {
                        var currentNotificationCenter = UNUserNotificationCenter.Current;
                        currentNotificationCenter.Delegate = new MyUNUserNotificationCenterDelegate ();
        
                        // Request Permissions
                        currentNotificationCenter.RequestAuthorization (UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound, (granted, error) => {
                            if(error != null) {
                                NSApplication.SharedApplication.InvokeOnMainThread (() => {
                                    ShowAlert ("Notification Request Error", error.LocalizedDescription + Environment.NewLine + "Reason: " + error.LocalizedFailureReason);
                                });
                            }
                        });
                    }
    }
    
        internal class MyUNUserNotificationCenterDelegate : UNUserNotificationCenterDelegate
        {
        }

the error variable is always "not null" and the `LocalizedDescription` property reads "Notifications are not allowed for this application".

When I do the same within a Swift application, I get the Authorisation pop-up asking me to authorise Notifications....

    import UserNotifications
        
        struct ContentView: View {
            var body: some View {
                Text("Test UNNotification Authorization")
                    .padding(10)
                    .onAppear {
                        if #available(OSX 10.14, *) {
                            let currentUserNotificationCenter =
                            UNUserNotificationCenter.current()
                            
                            let myDelegate = MyUserNotificationCenterDelegate()
                            currentUserNotificationCenter.delegate = myDelegate // must have delegate, otherwise notification won't appear
                            currentUserNotificationCenter
                              .requestAuthorization(options: [.alert, .sound, .badge]) {
                                [weak myDelegate] granted, error in
                                  
                                print("Permission granted: \(granted)")
                                guard granted else { return }
                              .}
                        }
                    .}
    
    class MyUserNotificationCenterDelegate: NSObject, UNUserNotificationCenterDelegate {
    }

The authorisation pop up, never appears in my VS4M application.

### Expected Behaviour

Authorisation pop-up should appear, like it does on Swift.

### Actual Behaviour

No Authorisation popup appears and instead the error message says "Notifications are not allowed for this application"

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: 60c7c193-36a0-40cb-a1f6-65589da22877
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	5.0.100
	3.1.404
	3.1.403
	3.1.302
	3.1.301
	3.1.200
	2.1.302
	2.1.301
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	5.0.0
	3.1.10
	3.1.9
	3.1.6
	3.1.5
	3.1.2
	2.1.23
	2.1.20
	2.1.19
	2.1.17
	2.1.2
	2.1.1
	2.0.5
	2.0.3
	2.0.0

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/dominique/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/dominique/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Visual Studio for Mac Extension for Tizen 1.5
Meadow 0.7.8

### Build Logs

N/A

### Example Project (If Possible)

See code above, but if you really want one, let me know and I'll add a console project.

**Comment by CartBlanche** [comment]
@chamons, @spouliot or @rolfbjarne : Happy New Year! Hope you are all well and have had a good start to the year.

I'm happy to submit a PR for this, if someone can point me in the rough direction of where to start looking and I'll take it from there.

**Comment by spouliot** [comment]
@CartBlanche happy new year!

> if someone can point me in the rough direction

Just a hunch but your C# and Swift code are not quite identical. The `[weak myDelegate]` plays a role in the swift code. In your C# code `currentNotificationCenter` can be collected (and so would be the delegate) when the processing is done (async).

If that does not help then please attach both (C# and Swift) samples. Permissions are often related to config, e.g. `Info.plist`, and not on source code so partial snippet often don't duplicate correctly.

**Comment by CartBlanche** [comment]
@spouliot Thanks for the quick response. I did read the docs to see if there as anything missing the `Info.plist` and couldn't find anything. I even compared what the Swift's plist had compared to mine, and didn't see anything. I'll upload a zip tomorrow with the 2 projects.

**Comment by spouliot** [comment]
@CartBlanche double-check that your C# app is signed (like the Swift app likely is).

XM does not sign by default but some features, like user notification, requires the app to be signed.

**Comment by CartBlanche** [comment]
@spouliot I totally forgot/ignored that signing the app might be the issue. I don't remember seeing this mentioned, or overlooked it.
Signing the app, even in Debug Mode, shows the notifications. May I suggest we add this to the Xamarin docs, for this API call? As other API calls don't need apps signed.

Thanks again for your awesome help!!

**Comment by spouliot** [comment]
> May I suggest we add this to the Xamarin docs, for this API call?

sounds like a good idea

> I'm happy to submit a PR for this,

and a good contribution for https://github.com/MicrosoftDocs/xamarin-docs ;-)

The closest document would be https://github.com/MicrosoftDocs/xamarin-docs/blob/b12ba00c671cd913a08a526170657ae591e3054a/docs/ios/platform/user-notifications/advanced-user-notifications.md

It's for iOS (but there's no macOS version). A small tip/warning about the signing requirement would likely be seen.

**Comment by CartBlanche** [comment]
I'll try to get a PR up for that docs, later today!

**Comment by CartBlanche** [comment]
@spouliot PR raised here with notes and small code snippet - https://github.com/MicrosoftDocs/xamarin-docs/pull/3207
Hopefully that is enough for other to use it.
