### ISSUE TITLE
[.NET 6] Replace reflection usage when setting up linker pipeline

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10415]
Context:

https://github.com/xamarin/xamarin-macios/blob/92ce9972c4363ad7f6b692bd62ad65433afe0610/tools/dotnet-linker/SetupStep.cs#L19-L28

This reflection usage should be removed at some point.

Ref (Android): https://github.com/xamarin/xamarin-android/issues/4709

**Comment by spouliot** [comment]
removed with https://github.com/xamarin/xamarin-macios/pull/11739
