### ISSUE TITLE
Mac Catalyst: make sure archiving works

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10413]
* [x] Verify that archiving works. https://github.com/xamarin/xamarin-macios/pull/12244.
* [x] Try publishing a Mac Catalyst app to the App Store (done as part of creating a submission test)
* [x] Add a Mac Catalyst submission test.
    * [x] https://github.com/xamarin/SubmissionSamples/pull/36
    * [x] https://github.com/xamarin/maccore/pull/2478

---

Time estimate: 3 days.

**Comment by spouliot** [comment]
> Add a Mac Catalyst submission test.

If we want to test code sharing it should be an existing (submitted) app. It also should not be linked (to get any extra/non-allowed symbols). That would mean iTravel (iirc).

OTOH we can have more than one submission for catalyst if there are other, conflicting conditions we need to test.

**Comment by rolfbjarne** [comment]
This has all been completed now.
