### ISSUE TITLE
Adding .xcassets to the build is failing with no errors or warnings

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-macios#10437]
I'm having trouble getting a custom generated .xcassets to be properly included and built with actool in a custom build task that Resizetizer is using to generate app icons on the fly.  

It works by generating the necessary .appiconset files inside of: `obj/$(Platform)/$(Configuration)/resizetize/r/Resizetizer.xcassets/appicon.appiconset` asset and then including them in the `ImageAsset` msbuild item group.

I believe they are being included properly in the msbuild group early enough in the build, and upon further investigation it appears that the `xcrun actool` may be the culprit, but I'm not quite sure how to proceed.

I'm attaching the .xcassets that I'm generating to this issue.
[Resizetizer.xcassets.zip](https://github.com/xamarin/xamarin-macios/files/5821301/Resizetizer.xcassets.zip)

I might be generating something incorrectly, but nothing is obvious to me as of yet.

When  I try and run `actool`: 

```
/usr/bin/xcrun actool --errors --warnings --notices --output-format xml1 --minimum-deployment-target 8.0 --platform iphonesimulator --compile /path/to/obj/iPhoneSimulator/Debug/actool/bundle /path/to/obj/iPhoneSimulator/Debug/resizetize/r/Resizetizer.xcassets
```

I do not see any errors or warnings, but I get an empty partial plist result back:
```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.actool.compilation-results</key>
	<dict>
		<key>output-files</key>
		<array/>
	</dict>
</dict>
</plist>
```

I also see no .car generated.

Any help would be appreciated!

**Comment by rolfbjarne** [comment]
Looks like you need to add `--output-partial-info-plist partial-info.plist --app-icon appicon` to the arguments to actool to have it compile app icons (and `--launch-image <name>` to compile launch images).

**Comment by Redth** [comment]
Yes! did not know I need those as I was copying the ACTool task's output which was missing them because it wasn't detecting my `ImageAsset` items as appiconset items.  So, got stuck on wondering why the output wasn't as expected.

The real issue then was that ACToolBaseTask wasn't seeing my assets as appiconset type to add those flags.  Adding a `Link` attribute to make them relative to the project path solved this.

Thanks!
