### ISSUE TITLE
Xamarin.Mac 7.3.0.27 Preview breaks signing native libraries

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#10445]
Not sure if it's something that is already fixed but the latest Xamarin.Mac previews (non-NET6, version 7.3.0.27) broke something with signing native libraries (possibly related to the CodesignNativeLibraries unification). Now the first pass correctly recognizes the types of the files (ie. Mach-O, etc.) but in the resulting bundle they end up being truncated to zero bytes. Every successive rebuild fails. Even the first build produces unusable bundle with zero-sized .dylib files though.

On the first build the files are still non-empty at this step:
<img width="959" alt="Screenshot 2021-01-16 at 12 22 06" src="https://user-images.githubusercontent.com/1764393/104810534-7e26ad00-57f5-11eb-9bfe-a6d1c2ee69fa.png">

**Comment by filipnavara** [comment]
MSBuild log: https://1drv.ms/u/s!ArCR3weE274jiREQ12FPIOzU29nx?e=8fz5Lz

**Comment by filipnavara** [comment]
Here's a self-contained project that hits the bug:

[Archive.zip](https://github.com/xamarin/xamarin-macios/files/5830750/Archive.zip)

It's a mix of our real project and some older near-empty test project, so the code is not important; the build options are.

Unzip, then run `rm -fr bin obj TextKitTest/bin TextKitTest/obj; msbuild /restore; ls -l bin/Debug/eM\ Client.app/Contents/MonoBundle`.

It should output something like:
```
_CodesignNativeLibraries:
  Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign 005075A6F70F54991195955542F2CA15DD18DECD --timestamp=none "/Users/filipnavara/Projects/TextKitTest/bin/Debug/eM Client.app/Contents/MonoBundle/libMonoPosixHelper.dylib"
          
  Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign 005075A6F70F54991195955542F2CA15DD18DECD --timestamp=none "/Users/filipnavara/Projects/TextKitTest/bin/Debug/eM Client.app/Contents/MonoBundle/libmono-native.dylib"
          
_CodesignAppBundle:
  Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign 005075A6F70F54991195955542F2CA15DD18DECD --entitlements /Users/filipnavara/Projects/TextKitTest/obj/Debug/TextKitTest/Entitlements.xcent "/Users/filipnavara/Projects/TextKitTest/bin/Debug/eM Client.app"

...

-rwxr-xr-x  1 filipnavara  staff         0 Jan 18 15:27 libMonoPosixHelper.dylib
-rwxr-xr-x  1 filipnavara  staff         0 Jan 18 15:27 libmono-native.dylib
```

**Comment by spouliot** [comment]
@filipnavara I can duplicate the issue. Thanks for the test case, that will help a lot!

**Comment by spouliot** [comment]
It looks like something related to code signing. If I change
```xml
    <EnableCodeSigning>false</EnableCodeSigning>
```
then the binaries are fine (non-zero).

However if I run the signing commands on the terminal then everything is fine too :| so something extra is being done silently.

**Comment by spouliot** [comment]
The culprit looks like
https://github.com/xamarin/xamarin-macios/pull/9731/files#diff-a4fa0e37aed259f0e8237e38b8f36cd948363ab024940e399d75fc6ba984da15R196
where `StampPath` should have been used
and which explains why manually doing every steps worked just fine.

**Comment by filipnavara** [comment]
That indeed looks like the line that causes it. I am kinda happy that my initial guess with the recent CodesignNativeLibraries changes was not too far off.

**Comment by spouliot** [comment]
So `StampPath` -> `/Users/poupou/Downloads/Archive/obj/Debug/TextKitTest/codesign/` and that makes sense

but `outputPath` is `/Users/poupou/Downloads/Archive/bin/Debug/eM Client.app/Contents/MonoBundle/libmono-native.dylib`

because

```csharp
return Path.Combine (StampPath, item.ItemSpec);
```
https://github.com/xamarin/xamarin-macios/pull/9731/files#diff-a4fa0e37aed259f0e8237e38b8f36cd948363ab024940e399d75fc6ba984da15R93

does not work, as expected, if `item.ItemSpec` is not relative. IOW then it starts with a `/` then this becomes the full path.

and this is where it stores the 0-length witness file.
