### ISSUE TITLE
[RFC] Mac Catalyst: availability/system version check

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10453]
Mac Catalyst has two versions:

* The macOS version the app is running on (or targeting).
* The iOS version that macOS version corresponds with.

And they each show up in different places:

* UIDevice.SystemVersion: macOS version
* Objective-C/Swift `@availability` checks: iOS version
* Apple's documentation: iOS version
* Xcode's project file (where the minimum OS version is stored): iOS version

* UIDevice.CheckSystemVersion: macOS version
* Info.plist (LSMinimumSystemVersion): macOS version
* Xcode's UI (to select the minimum OS version): macOS version

From reading llvm's source code, it seems Apple is reading `/System/Library/CoreServices/SystemVersion.plist` and getting the `iOSSupportVersion` to get the iOS version for Mac Catalyst (for their `@availability` checks):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ProductBuildVersion</key>
	<string>19H114</string>
	<key>ProductCopyright</key>
	<string>1983-2020 Apple Inc.</string>
	<key>ProductName</key>
	<string>Mac OS X</string>
	<key>ProductUserVisibleVersion</key>
	<string>10.15.7</string>
	<key>ProductVersion</key>
	<string>10.15.7</string>
	<key>iOSSupportVersion</key>
	<string>13.6</string>
</dict>
</plist>
```

[LLVM Ref 1](https://github.com/llvm/llvm-project/blob/62ec4ac90738a5f2d209ed28c822223e58aaaeb7/lldb/source/Host/macosx/objcxx/HostInfoMacOSX.mm#L100-L105)
[LLVM Ref 2](https://github.com/llvm/llvm-project/blob/383b6501ffedc85c2ecfaa7852ec1a9e9c374e3f/compiler-rt/lib/builtins/os_version_check.c#L159)

---

Which version do we want to surface in each place? For a few we don't really have much choice:

* UIDevice.SystemVersion (because we're just binding a native API)
* Info.plist

but for the following ones we do:

* UIDevice.CheckSystemVersion
* VS UI (to select the minimum OS version)

### UIDevice.CheckSystemVersion

1. Just use the SystemVersion field (which is the macOS version). This is the simplest (no change needed).
2. Have a custom implementation that checks the iOS version.
    Pros:
        * Our code would match Swift/Objective-C.
        * The code would also match Apple's documentation.
        * The code would match our availability annotations.
    Cons:
        * The name of the method suggests that we're checking the SystemVersion field, so it might be a bit unintuitive/surprising if you know what the SystemVersion field returns. I think this could be solved by documentation though.

I think the best would be option 2.

### VS UI (to select the minimum OS version)

Nothing has been implemented yet. I see three options:

* macOS version (like Xcode)
* iOS version
* Show both macOS version and iOS version next to each other.

I think we can improve upon Xcode here, and show both the macOS version and the iOS version.

**Comment by spouliot** [comment]
> I think the best would be option 2.

agreed

**Comment by dalexsoto** [comment]
Ugh what a mess, yeah, I think option 2 is best too.

**Comment by rolfbjarne** [comment]
Our decision was to go with option 2 for UIDevice.CheckSystemVersion.
