### ISSUE TITLE
VNDocumentCameraViewController - discard message and save button are not displayed properly

### ISSUE THREAD

**Issue by onurhazar** [xamarin/xamarin-macios#10500]
We are having issues while presenting the default view controller which iOS Vision framework provides.
[ExampleProject.zip](https://github.com/xamarin/xamarin-macios/files/5855751/ExampleProject.zip)

### Steps to Reproduce

1.  Present the default view controller of Vision framework. VNDocumentCameraViewController.
2. Scan more than one image
3. See the save button and the confirmation popup when you select cancel on top left corner.

### Expected Behavior
Scan button's name should be "Save (2)" when you continue scanning more than one image
Confirmation popup message should be "Are you sure you want to discard this scan?"

### Actual Behavior
Scan button's name becomes "SAVE_2_SCANNED_IMAGES_COUNT" when you continue scanning more than one image
Confirmation popup message is shown as "DISCARD_2_SCANNED_IMAGES_ALERT_MESSAGE"

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.8.5 (build 18)
Installation UUID: 9d3a4390-e13c-4558-b3d0-f3460173ea4c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.102/Sdks
SDK Versions:
	5.0.102
	5.0.101
	5.0.100
	3.1.405
	3.1.404
	3.1.402
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.2
	5.0.1
	5.0.0
	3.1.11
	3.1.10
	3.1.8
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.19
	2.1.18
	2.1.16
	2.1.15
	2.1.14
	2.1.13

=== .NET Core 3.1 SDK ===

SDK: 3.1.405

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.8.0.3 (Visual Studio Community)
Hash: c51fabee8
Branch: xcode12.3
Build date: 2020-12-10 21:05:05-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.26 (Visual Studio Community)
Commit: xamarin-android/d16-8/a36ce73
Android SDK: /Users/onur.hazar/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/onur.hazar/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808050018
Git revision: e83d51ec050ffcdd573462fc1889b58cfe1a5ad5
Build date: 2021-01-07 14:45:50-05
Build branch: release-8.8
Xamarin extensions: e83d51ec050ffcdd573462fc1889b58cfe1a5ad5

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Essential UI Kit for Xamarin.Forms - Syncfusion 3.0.0.0

### Example Project

We attached the example project (simplified from the project which we have this issue)

![actual](https://user-images.githubusercontent.com/5585009/105486843-3a81e680-5cc0-11eb-9a93-8d04b0476b85.PNG)
![expected](https://user-images.githubusercontent.com/5585009/105486863-42418b00-5cc0-11eb-929f-ad850c8566a7.PNG)

**Comment by spouliot** [comment]
The sample app starts with a login screen. Please provide instructions on how to get to the code that shows the above behaviour.

Also note that Xamarin.iOS does not translate, nor modify, iOS text. This is likely an issue on Apple side while loading their translation tables. As such its also likely to depend on which version of iOS your devices are running. Please add this information to the issue.

**Comment by onurhazar** [comment]
Sorry, forgot to mention it. You need to select the button located at the bottom of the page named "Activate with QR Code". Project is simplified so we put the code in this button to reproduce easily.

**Comment by spouliot** [comment]
I can confirm that your app has the problem, while the sample code does not.

The fact that it works on the latter suggest this is not an SDK issue, nor an iOS issue, but something that is not correct inside your application. 

Do you have any reason to believe otherwise ?

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Comment by onurhazar** [comment]
@spouliot 
Yes, you are correct. We couldn't reproduce the issue in a new project. The issue was specific to our project because we are also using different third party packages. We believe that it was a localization problem occurred in Xamarin SDK when we use other third party packages that has multiple localizations. It can't define which localization it should use. We resolved the issue by manually setting custom development region to en-US in info.plist file. Normally, we know that it should be set en-us by Xamarin by default but it is not.

<key>CFBundleDevelopmentRegion</key>
<string>en_US</string>

@rolfbjarne  Thanks for closing the issue and inform us to give feedback.
