### ISSUE TITLE
Xamarin iOS should call monovm_initialize for .NET 6

### ISSUE THREAD

**Issue by CoffeeFlux** [xamarin/xamarin-macios#10504]
`monovm_initialize` is a cleaned-up equivalent to `coreclr_initialize`, which is one of the .NET Core hosting functions in `CoreClrHost.h`.

Signature: https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/mono/mono/mini/mono-private-unstable.h#L30

It needs to be called in net6 embedding projects before the runtime is started. Specifically, what it's doing is:

* Passing in various [runtime properties](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#step-3---prepare-runtime-properties), a subset of which we support. The important ones are:
  * `TRUSTED_PLATFORM_ASSEMBLIES`: Hard-coded list of assemblies, intended to be used for the BCL and fast-path'd in the loading algorithm. They also have some ALC loading implications (default context only).
  * `APP_PATHS`: Essentially the same as `MONO_PATH`. Prefer `TRUSTED_PLATFORM_ASSEMBLIES` where possible.
  * `NATIVE_DLL_SEARCH_DIRECTORIES`: Extra directories to check when loading native libraries for pinvokes.
  * `System.Globalization.Invariant`: Alternative way to set the `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` env var.
  * `PINVOKE_OVERRIDE`: First-chance native callback to control P/Invoke resolution, see https://github.com/dotnet/runtime/pull/44505
* Adding netcore-specific loader hooks, some of which use those properties
* Setting the runtime to use strict assembly name checking, as we still default to the historical behavior otherwise

The runtime properties are also set in files like `.runtimeconfig.json`, which is parsed in by the default host and passed to `coreclr_initialize`. Mono embedders not using the default host will have to handle this themselves, probably at build time in the case of Xamarin, if they wish to support those files.

Applications not calling `monovm_initialize` may result in a runtime error at some undetermined point in the future.

---

* [x] PINVOKE_OVERRIDE: #10932.
* [x] TRUSTED_PLATFORM_ASSEMBLIES: #12272
* [x] APP_PATHS
* [ ] NATIVE_DLL_SEARCH_DIRECTORIES

---

Time estimate: 2 weeks

**Comment by rolfbjarne** [comment]
OK, I'll have a look at this.

Is `monovm_initialize` already available to call, or do I have to wait until it's implemented?

**Comment by CoffeeFlux** [comment]
Already implemented. It's called by the default dotnet host, so if it didn't work we wouldn't function anywhere.

**Comment by CoffeeFlux** [comment]
The main limitations with it right now are:

* We don't support every hosting property that CoreCLR does, though if anything in particular is needed I can probably add it
* Properties set with this aren't always propagated back up through AppContext correctly, though this is a TODO on our end (see https://github.com/dotnet/runtime/blob/master/src/mono/mono/mini/monovm.c#L189)

**Comment by lambdageek** [comment]
Worth adding, `monovm_intialize` is also responsible for surfacing System.AppContext properties from the embedding host through the runtime up to managed https://gist.github.com/lambdageek/c6f101503b6db9876e281e677980b6df

**Comment by rolfbjarne** [comment]
`PINVOKE_OVERRIDE`  was implemented here: https://github.com/xamarin/xamarin-macios/pull/10932.

Still missing:

* [ ] TRUSTED_PLATFORM_ASSEMBLIES
* [ ] APP_PATHS
* [ ] NATIVE_DLL_SEARCH_DIRECTORIES

**Comment by rolfbjarne** [comment]
We're adding all the assemblies in the app bundle to TRUSTED_PLATFORM_ASSEMBLIES, so APP_PATHS shouldn't be needed.
