### ISSUE TITLE
Devops Pipeline fails Can't resolve the reference 'System.Void UIKit.UIPageControl IndicatorViewRenderer (5.0.0.1905)

### ISSUE THREAD

**Issue by developer9969** [xamarin/xamarin-macios#10534]
Hi everyone. I did raise this bug already with the xamarin forms team 
https://github.com/xamarin/Xamarin.Forms/issues/13486, I am STUCK and run out ideas of what could be wrong. I double checked and I am using the latest everywhere.

However I wonder if this is a better forum given the error.  It only happens using xamarin forms 5.x and it implies that I am not using the latest iOS in the pipeline. As you can see I am using microsoft agent (macOS-latest) but I get this error below.
Does the pipeline macOS-latest actually has the latest iOS?

My Bash script is as follows:

  monoVersion: '6_12_0'
  xCodeVersion: '12.3'

`task: Bash@3
displayName: 'Switch to Mono Version ${{ parameters.monoVersion }}'
inputs:
targetType: 'inline'
script: 'sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh ${{ parameters.monoVersion }}'
bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_${{ parameters.xCodeVersion }}.app;sudo xcode-select --switch /Applications/Xcode_${{ parameters.xCodeVersion }}.app/Contents/Developer`

### Steps to Reproduce
1. Project with xamarin 5.0.0.1905
2. Build with Azure Devops pipeline
3. `MTOUCH : error MT2101: Can't resolve the reference 'System.Void UIKit.UIPageControl::set_AllowsContinuousInteraction(System.Boolean)', referenced from the method 'System.Void Xamarin.Forms.Platform.iOS.IndicatorViewRenderer::OnElementChanged(Xamarin.Forms.Platform.iOS.ElementChangedEventArgs1<Xamarin.Forms.IndicatorView>)'
in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. ]`

### Expected Behavior
To successfully build like it does using Xamarin Forms 4.8.x
### Environment
  monoVersion: '6_12_0'
  xCodeVersion: '12.3'
- Pipeline : We are using Microsoft Hosted agent (we have no control over what is installed)
- Pool='macOS-latest' (macos-10.15) which according to the document it has the latest installed
- https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
- Visual studio iOS Project Deployment Target=12.0
- Visual Studio Version : 16.8.4
- And get the error

`MTOUCH : error MT2101: Can't resolve the reference 'System.Void UIKit.UIPageControl::set_AllowsContinuousInteraction(System.Boolean)', referenced from the method 'System.Void Xamarin.Forms.Platform.iOS.IndicatorViewRenderer::OnElementChanged(Xamarin.Forms.Platform.iOS.ElementChangedEventArgs1<Xamarin.Forms.IndicatorView>)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. ]`

Really grateful for anybody feedback or suggestions.

**Comment by spouliot** [comment]
For such error to happen you need to have an XF version that is build using a newer XI than the one you are using to build your app.

`AllowsContinuousInteraction` was added last summer with Xcode 12.0 beta 2. So this means it's been available since Xamarin.iOS 14.0.

The API diff from the [14.0 release notes](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/14/14.0) confirms that

```csharp
public virtual bool AllowsContinuousInteraction { get; set; }
public virtual UIPageControlBackgroundStyle BackgroundStyle { get; set; }
public virtual UIPageControlInteractionState InteractionState { get; }
public virtual UIImage PreferredIndicatorImage { get; set; }
```

Somehow the currently installed Xamarin.iOS version on your host seems to be older than 14.0.

Your build logs should have more details, including the version Xamarin.iOS that was used.

**Comment by developer9969** [comment]
hi there thanks for your reply you said:
`Somehow the currently installed Xamarin.iOS version on your host seems to be older than 14.0.`
looking at microsoft hosted agent (macos-10.15) they do have the latest 

https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md

`Xamarin.iOS

- 14.6.0.15
- 14.4.1.3
- 14.2.0.12
- 14.0.0.0
- 13.20.2.2
- 13.18.2.1
- 13.16.0.13
- 13.14.1.39
- 13.10.0.21
- 13.8.3.0
- 13.6.0.12
- 13.4.0.2
- 13.2.0.47

`

looking at Devops build logs at some point it mentions **"Xamarin.iOS 13.20.2.2"**
`2021-01-26T06:57:08.3973030Z   /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/runner/work/1/s/src/Apps/Consumer/Clients/MyApp/obj/iPhone/Ad-Hoc/response-file.rsp --optimize=experimental-xforms-product-type 
2021-01-26T06:57:08.8049880Z   **Xamarin.iOS 13.20.2.2 (d16-7): 817b6f72a using framework:/Applications/Xcode_12.3.app/** **Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.3.sdk`**

where is this Xamarin.iOS 13.20.2.2 coming from?? it cant be from my environment , must be the agent (which I have no control over)

really appreaciate your help?

Am I missing the obvious here?

**Comment by spouliot** [comment]
> where is this Xamarin.iOS 13.20.2.2 coming from??

Not sure. You'll need to ask the azure devops team. My guess is that you're not asking for a specific XI version and are getting a _default_ (or the current host) version configured.

Some good news, your error makes sense if you're building against 13.20.x since it won't have the API that XF 5.0 binaries refer too.

> Am I missing the obvious here?

A second guess... you mention selecting which mono and Xcode you wanted (in you brash script). I'm fairly sure something similar allows you to ask which version of Xamarin.iOS should be configured.
