### ISSUE TITLE
How is the AudioObjectPropertySelector enum created?

### ISSUE THREAD

**Issue by lukasroberts** [xamarin/xamarin-macios#10554]
### Steps to Reproduce

This is not a bug, just a question!

### Environment

```
```

### Example Project (If Possible)

A question on the Xamarin binding for Core Audio and more specifically Audio Unit.

The First is that I made some changes so that AudioObjectGetPropertyData could return something other than a uint as it's outData, as this is the norm in most cases:

[DllImport(ObjCRuntime.Constants.AudioUnitLibrary)]
static extern unsafe int AudioObjectGetPropertyData(
uint inObjectID,
ref AudioObjectPropertyAddress inAddress,
ref uint inQualifierDataSize,
ref IntPtr inQualifierData,
ref uint ioDataSize,
uint* outData
);

I used it like this to get a list of device ids, now I'm onto retrieving some more specific information about the device ids such as the name, number of input channels, and so on.

But I'm stumped with the enum AudioObjectPropertySelector, as I am needing to add a few more that don't exist yet, I'm guessing 

PropertyDevices = 1684370979, // 'dev#'
Is 1684370979 just 'dev#' converted into a uint? Is anyone able to confirm? or is it just hex?

Eventually, once I've got all the data out for some devices, I'll make a PR into the Xamarin Mac / iOS github repo so that others can get all the device information for the same as what I am doing!

**Comment by rolfbjarne** [comment]
The `AudioObjectPropertySelector` values are FourCC's.

First convert `1684370979` to hex: `0x64657623`.

Then you split into four byte-sized values: `0x64`, `0x65`, `0x76`, `0x23`
Finally you treat each byte as an ascii value: `0x64=d`, `0x65=e`, `0x76=v`, `0x23=#`.

So to get the enum value for a specific string, you just reverse the process.
