### ISSUE TITLE
[.NET 6] Add support for CoreCLR

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10569]
This issue will list what we need to do to support CoreCLR as the runtime.

---

Time estimate: 6 weeks

**Comment by srxqds** [comment]
this means the MonoVM will drop at least?

**Comment by dalexsoto** [comment]
No, MonoVM will still be an option along with CoreCLR for Xamarin.Mac apps. For the rest iOS and company MonoVM will still be used.

**Comment by rolfbjarne** [comment]
As of #11757 CoreCLR is feature-complete with the MonoVM runtime, so this can be closed.

**Comment by trympet** [comment]
How does one opt in to using coreclr (in reference to dotnet/runtime#57877)?

**Comment by rolfbjarne** [comment]
@trympet 

Set `UseMonoRuntime=false` in your project file: https://github.com/xamarin/xamarin-macios/wiki/.NET-6#choosing-the-runtime
