### ISSUE TITLE
Missing release notes for xamarin-ios 14.9.0.27

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-macios#10589]
Release notes are missing for xamarin-ios 14.9.0.27.
This is a recurring issue : https://github.com/xamarin/xamarin-macios/issues/8661

**Comment by rolfbjarne** [comment]
CC @dalexsoto

**Comment by tranb3r** [comment]
New release 14.10.0.4

**Comment by dalexsoto** [comment]
@tranb3r yes, thank you we are working out the release notes for both the current stable and previews. 

A quick note on 14.10.0.4 this adds support for Xcode 12.4 and comes from the branch under the same name there are no other changes inside this release.

**Comment by tranb3r** [comment]
14.14.2.5 is now installed with visual studio 2019 stable.
What's new ?

**Comment by dalexsoto** [comment]
Release notes should be available here https://docs.microsoft.com/xamarin/ios/release-notes/14/14.14 soon.

**Comment by dalexsoto** [comment]
Release notes are up
