### ISSUE TITLE
Xcode 12.5 final audit checklist

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#10649]
# Things to review before release

- [ ] Simulators on bots are not currently used (xharness reports no sim)
   - should be fixed with https://github.com/xamarin/xamarin-macios/pull/10627

# From Xcode 12.3 checklist

- [x] Check on `CoreSpotlight.CSLocalizedString` not a hard blocker since it is also broken in GM
   - still crashing with Xcode 12.3 beta 1, still crashing with macOS 11.1 beta 2

**Comment by rolfbjarne** [comment]
xharness problems fixed years ago.

CSLocalizedString is still an issue, filed https://github.com/xamarin/maccore/issues/2949.
