### ISSUE TITLE
.NET 6: add support for specifying additional partial Info.plists that are to be merged into the final Info.plist

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10646]
It would be possible to make single-project support nicer if it was possible to generate a partial Info.plist that is to be merged into the final Info.plist (for fonts at the very least).

The idea would be to add an additional public itemgroup like the current `_PartialAppManifest` that is passed to the `CompileAppManifest` task + a target that can be used for BeforeTargets.

* [x] Add tests
* [x] Modify our build logic to use `PartialAppManifest` instead of `_PartialAppManifest`.
* [x] Documentation: https://github.com/xamarin/xamarin-macios/wiki/Project-file-properties#partialappmanifest

/cc @Redth

**Comment by Redth** [comment]
@rolfbjarne just an update that `_PartialAppManifest` does indeed work, and running it after the `_CompileCoreMLModels` target works as well.  I think this validates enough the approach of creating a public item group to add these things to before some public target name.

**Comment by AmrAlSayed0** [comment]
Yes, same with the Android Manifest. It would be near impossible to support every valid Info.plist or Android Manifest tag. I'm used to using conditional PropertyGroup so it is not a problem for me but it would be even better if it was supported from the IDE's UI.

Another thing to consider is merging with existing tags. If I wanted to add a tag that is inside the ```application``` that's inside ```manifest``` (and also possibly others) how would I set that?

**Comment by Redth** [comment]
@AmrAlSayed0 this isn't really the right place to discuss the android merging :) but this is already possible today and xamarini.android does use the google manifest merger tool already which actually has a rather prescriptive set of rules around merging and altering the manifest files through partial manifests.

**Comment by AmrAlSayed0** [comment]
Ok, sorry, got carried away 😅

**Comment by Redth** [comment]
@rolfbjarne looks like we still need a non private named target to be able to run before so items can make it into this list without depending on _CompileAppManifests

**Comment by rolfbjarne** [comment]
@Redth You can now add your target to the `CollectAppManifestsDependsOn` property:

```xml
<PropertyGroup>
    <CollectAppManifestsDependsOn>
        $(CollectAppManifestsDependsOn);
        AddPartialAppManifestsTarget;
    </CollectAppManifestsDependsOn>
</PropertyGroup>
```
