### ISSUE TITLE
Use .NET-specific min OS versions to build native code for .NET

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10659]
It looks like we're going to drop support for a few older OS versions.

In particular the new min OS versions are going to be:

* iOS: 10 (https://github.com/dotnet/runtime/issues/44654)
* tvOS 10 (https://github.com/dotnet/runtime/issues/44654)
* macOS: 10.13 (https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#macos)

We have to update our code accordingly to handle this (instead of using the min OS versions defined for legacy Xamarin)

**Comment by spouliot** [comment]
That would be 10.14+ for net6

https://github.com/dotnet/core/blob/master/release-notes/6.0/6.0-supported-os.md

**Comment by spouliot** [comment]
we also need to define/confirm the minimum for Mac Catalyst

it started shipping in 10.15 (so before our minimum Mac) so the (rock bottom) minimum would be 13.0 (since it match the iOS version)

**Comment by rolfbjarne** [comment]
> so the (rock bottom) minimum would be 13.0

Xcode 12.4 doesn't let you select anything lower than 10.15.1/13.2.

IMHO we shouldn't support anything lower than what the current stable Xcode does when our Mac Catalyst support goes to stable.

**Comment by rolfbjarne** [comment]
This will be easier to implement after we've dropped support for legacy Xamarin, which will happen for Xcode 15, so I'm postponing this until .NET 9.
