### ISSUE TITLE
Map TargetPlatformVersion to OSMinimumVersion

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10728]
See: https://github.com/dotnet/designs/blob/main/accepted/2020/minimum-os-version/minimum-os-version.md#msbuild-properties

**Comment by spouliot** [comment]
hmm... that spec mention things, like attributes, that are not part of (the final) .net5. I suspect it's (partially) outdated... 

@terrajobst anything more recent ?

**Comment by rolfbjarne** [comment]
This is the same as #12336, so closing this one.
