### ISSUE TITLE
[generator] Avoid generating older (than type) availability attributes in members

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#10727]
This was out of scope to remove duplicated availability attributes, inside [1], but there's potential to remove more attributes because there's currently no check for cases like:

```
[iOS (12,0)]
public class NSNewer {

	[iOS (11,0)]
	public virtual int Older { get; set; }
}
```

which can happen (most likely) when protocols are inlined.

The duplicate check added in [1] could be modified to filter older versions (instead of a direct version comparison).

It's not clear (need validation) how that affect existing (and upcoming) tooling, which is why this is filed as an **enhancement** right now, but being more consistent can only help.

[1] https://github.com/xamarin/xamarin-macios/pull/10683

**Comment by rolfbjarne** [comment]
Unfortunately availability attributes in .NET have to very explicit, so this is not relevant anymore.
