### ISSUE TITLE
Finish templates

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-macios#10747]
The basic templates for xamarin-macios are implemented in:

* PR: https://github.com/xamarin/xamarin-macios/pull/10741
* Issue: https://github.com/xamarin/xamarin-macios/issues/10252

This gets the basic templates matching what we have for Android.

For .NET 6 GA, we would potentially need more changes:

1. Every template in VS today needs an equivalent template for .NET 6: unless we decide to drop some of them.
2. We might be able to make use of the [new MSBuild project properties](https://github.com/xamarin/xamarin-android/blob/dcd1cb78f67652bb53289e5dd67bc10350513931/Documentation/guides/OneDotNetSingleProject.md) and omit values in `Info.plist`

Equivalent issue on the xamarin-android side: https://github.com/xamarin/xamarin-android/issues/5672

Template source code locations:

* https://github.com/xamarin/vsmac-xamarin-extensions/tree/47507384987d5522983bce0d92afb799b96b5a96/MonoDevelop.MonoMac/MonoDevelop.MonoMac/templates
* https://github.com/xamarin/vsmac-xamarin-extensions/tree/47507384987d5522983bce0d92afb799b96b5a96/MonoDevelop.IPhone/MonoDevelop.IPhone/templates
* https://github.com/xamarin/xamarin-templates

**Comment by rolfbjarne** [comment]
Current status: @davidortinau @ThisIsKirsch are to provide a list of templates we want to port to .NET 6.

**Comment by rolfbjarne** [comment]
We're going to port the following templates:

* iOS
    * [ ] Tabbed app
    *  [ ] Blazor app
* macOS
    * [ ] Port over the current macOS template
* tvOS
    * [ ] Single View App

@ThisIsKirsch to discuss with PM team on Games templates.

**Comment by rolfbjarne** [comment]
We've decided to not add more templates for now, and re-evaluate after the release.

**Comment by rolfbjarne** [comment]
There have been no requests for more templates, so I'm closing this.
