### ISSUE TITLE
SharpCompress crashes on start on Xamarin.Mac

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#10776]
### Steps to Reproduce

1. Add SharpCompress 0.28.1 (latest version) from Nuget
2. Run the app
3. 

### Expected Behavior
The app should run, the same package works on iOS
### Actual Behavior
The app crashes with this:
```
Could not load the file 'System.Runtime.CompilerServices.Unsafe'

at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity) [0x00073] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/corlib/System/AppDomain.cs:758
at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef) [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/corlib/System/AppDomain.cs:724
at (wrapper remoting-invoke-with-check) System.AppDomain.Load(System.Reflection.AssemblyName)
at System.Reflection.Assembly.Load (System.Reflection.AssemblyName assemblyRef) [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/corlib/System.Reflection/Assembly.cs:440
at ObjCRuntime.Runtime.CollectReferencedAssemblies (System.Collections.Generic.List1[T] assemblies, System.Reflection.Assembly assembly) [0x00085] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:545 at ObjCRuntime.Runtime.CollectReferencedAssemblies (System.Collections.Generic.List1[T] assemblies, System.Reflection.Assembly assembly) [0x00085] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:545
at ObjCRuntime.Runtime.RegisterEntryAssembly (System.Reflection.Assembly entry_assembly) [0x00032] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:506
at ObjCRuntime.Runtime.RegisterAssemblies () [0x00001] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:482
at AppKit.NSApplication.Init () [0x00022] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/AppKit/NSApplication.cs:56
at ....MainClass.Main (System.String[] args) [0x00001] in /Users/ivanicin/Projects/.../Main.cs:9
```
### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.8.10 (build 2)
Installation UUID: a4f5fe79-84f0-4390-8613-d7f26e71dd65
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000122

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.122 (2020-02/c621c35ffa0) (64-bit)
	Package version: 612000122

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.103/Sdks
SDK Versions:
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11

=== .NET Core 3.1 SDK ===

SDK: 3.1.406

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.4.0.10 (Visual Studio Community)
Hash: a4c70e7d0
Branch: xcode12.4
Build date: 2021-02-17 17:40:51-0500

=== Xamarin.iOS ===

Version: 14.10.0.4 (Visual Studio Community)
Hash: 5a05865f6
Branch: xcode12.4
Build date: 2021-01-28 02:30:23-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.26 (Visual Studio Community)
Commit: xamarin-android/d16-8/a36ce73
Android SDK: /Users/ivanicin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/ivanicin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:34:58 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:35:22 UTC

=== Build Information ===

Release ID: 808100002
Git revision: f81ffa2444a28c09f173849935ec9ee0195a5b17
Build date: 2021-02-18 12:02:12-05
Build branch: release-8.8
Xamarin extensions: f81ffa2444a28c09f173849935ec9ee0195a5b17

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64


```

**Comment by mandel-macaque** [comment]
System.Runtime.CompilerServices.Unsafe is a nuget. Is the nuget present in your system? Can you please provide a full set of build logs to try and see not only the execution but if the nuget was indeed copied to the final app?

**Comment by ivanicin** [comment]
> System.Runtime.CompilerServices.Unsafe is a nuget. Is the nuget present in your system? Can you please provide a full set of build logs to try and see not only the execution but if the nuget was indeed copied to the final app?

I've provided the explanation on how to reproduce the bug. It takes around 30 seconds to achieve that. So did you try to reproduce that?

I am quite sure that the nuget is not installed as the app would compile without that error. But as it works on Xamarin.iOS without installation of that nuget then there is likely something wrong in Xamarin.Mac.

**Comment by mandel-macaque** [comment]
@ivanicin  no, I have not tested it because I do not have a sample and I cannot create a sample for each of the issue we triage. Specially because the sample I might create can differ from the one you are creating. That is why I need more information. If you share a project I will not make any assumptions that will result in a mismatch of the configurations/results.

**Comment by ivanicin** [comment]
> 
> 
> @ivanicin no, I have not tested it because I do not have a sample and I cannot create a sample for each of the issue we triage. Specially because the sample I might create can differ from the one you are creating. That is why I need more information. If you share a project I will not make any assumptions that will result in a mismatch of the configurations/results.

I have not provided the sample because good support handles this, I had thus far submitted thousands of bugs on various places and I know what is a good support and what is a bad support and what is reasonable and what is not.

Speaking of that cases like this would be handled by Xamarin till year a go, till this transition to .NET 6 it had a reasonably good support.

At this moment the support is at trash level as even well documented and essential bugs are not handled at all.

So if someone from the management like @chamons can confirm that this bug will be worked on in the next few months, I'll do whatever is required. Otherwise, why bother. It is better to spend that time on preparing to switch future projects to some other platform that has at least some level of professional support, and there are few of them.

**Comment by spouliot** [comment]
Xamarin.Mac ships this assembly. It should be used. It's sadly very easy to get it wrong (google for "Could not load the file 'System.Runtime.CompilerServices.Unsafe'").

Solution: Adding the `System.Runtime.CompilerServices.Unsafe` nuget fix the issue.

> the same package works on iOS

Each platform (macOS being different from iOS) has its own directories inside the nuget. Unless each platform is tested by the nuget author then it might not work.

This is something that should get better with the move to net6 as most "general purpose" nuget will be able to target a single platform.
