### ISSUE TITLE
Foundation.MonoTouchException while accessing Uuid property of CLBeaconRegion

### ISSUE THREAD

**Issue by ClaudioBiagioli** [xamarin/xamarin-macios#10801]
### Steps to Reproduce

Run code in the FinishedLaunching() of example project

### Expected Behavior
No errors
### Actual Behavior
Foundation.MonoTouchException while accessing the Uuid property

[0:] Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[CLBeaconRegion UUID]: unrecognized selector sent to instance 0x281956920
Native stack trace:
	0   CoreFoundation                      0x000000018e3af198 <redacted> + 252
	1   libobjc.A.dylib                     0x000000018d5879f8 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018e2cb9bc <redacted> + 0
	3   CoreFoundation                      0x000000018e3b49c8 <redacted> + 1408
	4   CoreFoundation                      0x000000018e3b665c _CF_forwarding_prep_0 + 92
	5   TestCLBeaconRegion                  0x000000010111ac30 TestCLBeaconRegion + 1961008
	6   TestCLBeaconRegion                  0x0000000101109264 TestCLBeaconRegion + 1888868
	7   TestCLBeaconRegion                  0x0000000100f44740 TestCLBeaconRegion + 34624
	8   TestCLBeaconRegion                  0x0000000101108630 TestCLBeaconRegion + 1885744
	9   TestCLBeaconRegion                  0x00000001010a73a0 TestCLBeaconRegion + 1487776
	10  TestCLBeaconRegion                  0x000000010114fe4c mono_pmip + 25056
	11  TestCLBeaconRegion                  0x00000001011e1694 mono_pmip + 621096
	12  TestCLBeaconRegion                  0x00000001011e4afc mono_pmip + 634512
	13  TestCLBeaconRegion                  0x0000000100f41d30 TestCLBeaconRegion + 23856
	14  TestCLBeaconRegion                  0x0000000100f41a20 TestCLBeaconRegion + 23072
	15  CoreLocation                        0x000000019517100c CLClientStopVehicleHeadingUpdates + 77500
	16  CoreLocation                        0x000000019516f414 CLClientStopVehicleHeadingUpdates + 70340
	17  CoreLocation                        0x0000000195159854 CLClientInvalidate + 1288
	18  CoreFoundation                      0x000000018e340d6c <redacted> + 20
	19  CoreFoundation                      0x000000018e340670 <redacted> + 272
	20  CoreFoundation                      0x000000018e33bbdc <redacted> + 2312
	21  CoreFoundation                      0x000000018e33afb4 CFRunLoopRunSpecific + 436
	22  GraphicsServices                    0x000000019053c79c GSEventRunModal + 104
	23  UIKitCore                           0x00000001bad81c38 UIApplicationMain + 212
	24  TestCLBeaconRegion                  0x000000010111c3c8 TestCLBeaconRegion + 1967048
	25  TestCLBeaconRegion                  0x000000010110a9a0 TestCLBeaconRegion + 1894816
	26  TestCLBeaconRegion                  0x000000010110a924 TestCLBeaconRegion + 1894692
	27  TestCLBeaconRegion                  0x0000000100f43ab0 TestCLBeaconRegion + 31408
	28  TestCLBeaconRegion                  0x00000001010a73a0 TestCLBeaconRegion + 1487776
	29  TestCLBeaconRegion                  0x000000010114fe4c mono_pmip + 25056
	30  TestCLBeaconRegion                  0x00000001011e1694 mono_pmip + 621096
	31  TestCLBeaconRegion                  0x00000001011e6710 mono_pmip + 641700
	32  TestCLBeaconRegion                  0x0000000101135328 TestCLBeaconRegion + 2069288
	33  TestCLBeaconRegion                  0x00000001012857d0 xamarin_log + 15348
	34  TestCLBeaconRegion                  0x0000000100f439b4 TestCLBeaconRegion + 31156
	35  libdyld.dylib                       0x000000018ddfe8e0 <redacted> + 4

  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:407 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/runtime/Delegates.generated.cs:126 
  at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
  at (wrapper managed-to-native) ObjCRuntime.Messaging.IntPtr_objc_msgSend(intptr,intptr)
  at CoreLocation.CLBeaconRegion.get_Uuid () [0x00003] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/CoreLocation/CLBeaconRegion.g.cs:365 
  at TestCLBeaconRegion.AppDelegate.Manager_DidDetermineState (System.Object sender, CoreLocation.CLRegionStateDeterminedEventArgs e) [0x00002] in C:\Users\CBiagioli\source\Workspaces\DURANTE\SPACEBOOKING\XMobileApp\TestCLBeaconRegion\AppDelegate.cs:63 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) ObjCRuntime.Messaging.IntPtr_objc_msgSend(intptr,intptr)
  at CoreLocation.CLBeaconRegion.get_Uuid () [0x00003] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/CoreLocation/CLBeaconRegion.g.cs:365 
  at TestCLBeaconRegion.AppDelegate.Manager_DidDetermineState (System.Object sender, CoreLocation.CLRegionStateDeterminedEventArgs e) [0x00002] in C:\Users\CBiagioli\source\Workspaces\DURANTE\SPACEBOOKING\XMobileApp\TestCLBeaconRegion\AppDelegate.cs:63 	0   CoreFoundation                      0x000000018e3af198 <redacted> + 252
	1   libobjc.A.dylib                     0x000000018d5879f8 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018e2cb9bc <redacted> + 0
	3   CoreFoundation                      0x000000018e3b49c8 <redacted> + 1408
	4   CoreFoundation                      0x000000018e3b665c _CF_forwarding_prep_0 + 92
	5   TestCLBeaconRegion                  0x000000010111ac30 TestCLBeaconRegion + 1961008
	6   TestCLBeaconRegion                  0x0000000101109264 TestCLBeaconRegion + 1888868
	7   TestCLBeaconRegion                  0x0000000100f44740 TestCLBeaconRegion + 34624
	8   TestCLBeaconRegion                  0x0000000101108630 TestCLBeaconRegion + 1885744
	9   TestCLBeaconRegion                  0x00000001010a73a0 TestCLBeaconRegion + 1487776
	10  TestCLBeaconRegion                  0x000000010114fe4c mono_pmip + 25056
	11  TestCLBeaconRegion                  0x00000001011e1694 mono_pmip + 621096
	12  TestCLBeaconRegion                  0x00000001011e4afc mono_pmip + 634512
	13  TestCLBeaconRegion                  0x0000000100f41d30 TestCLBeaconRegion + 23856
	14  TestCLBeaconRegion                  0x0000000100f41a20 TestCLBeaconRegion + 23072
	15  CoreLocation                        0x000000019517100c CLClientStopVehicleHeadingUpdates + 77500
	16  CoreLocation                        0x000000019516f414 CLClientStopVehicleHeadingUpdates + 70340
	17  CoreLocation                        0x0000000195159854 CLClientInvalidate + 1288
	18  CoreFoundation                      0x000000018e340d6c <redacted> + 20
	19  CoreFoundation                      0x000000018e340670 <redacted> + 272
	20  CoreFoundation                      0x000000018e33bbdc <redacted> + 2312
	21  CoreFoundation                      0x000000018e33afb4 CFRunLoopRunSpecific + 436
	22  GraphicsServices                    0x000000019053c79c GSEventRunModal + 104
	23  UIKitCore                           0x00000001bad81c38 UIApplicationMain + 212
	24  TestCLBeaconRegion                  0x000000010111c3c8 TestCLBeaconRegion + 1967048
	25  TestCLBeaconRegion                  0x000000010110a9a0 TestCLBeaconRegion + 1894816
	26  TestCLBeaconRegion                  0x000000010110a924 TestCLBeaconRegion + 1894692
	27  TestCLBeaconRegion                  0x0000000100f43ab0 TestCLBeaconRegion + 31408
	28  TestCLBeaconRegion                  0x00000001010a73a0 TestCLBeaconRegion + 1487776
	29  TestCLBeaconRegion                  0x000000010114fe4c mono_pmip + 25056
	30  TestCLBeaconRegion                  0x00000001011e1694 mono_pmip + 621096
	31  TestCLBeaconRegion                  0x00000001011e6710 mono_pmip + 641700
	32  TestCLBeaconRegion                  0x0000000101135328 TestCLBeaconRegion + 2069288
	33  TestCLBeaconRegion                  0x00000001012857d0 xamarin_log + 15348
	34  TestCLBeaconRegion                  0x0000000100f439b4 TestCLBeaconRegion + 31156
	35  libdyld.dylib                       0x000000018ddfe8e0 <redacted> + 4
2021-03-08 12:52:43.079 TestCLBeaconRegion[453:34886] -[CLBeaconRegion UUID]: unrecognized selector sent to instance 0x281956110

[0:] Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[CLBeaconRegion UUID]: unrecognized selector sent to instance 0x281956110
Native stack trace:
	0   CoreFoundation                      0x000000018e3af198 <redacted> + 252
	1   libobjc.A.dylib                     0x000000018d5879f8 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018e2cb9bc <redacted> + 0
	3   CoreFoundation                      0x000000018e3b49c8 <redacted> + 1408
	4   CoreFoundation                      0x000000018e3b665c _CF_forwarding_prep_0 + 92
	5   TestCLBeaconRegion                  0x000000010111ac30 TestCLBeaconRegion + 1961008
	6   TestCLBeaconRegion                  0x0000000101109264 TestCLBeaconRegion + 1888868
	7   TestCLBeaconRegion                  0x0000000100f44740 TestCLBeaconRegion + 34624
	8   TestCLBeaconRegion                  0x0000000101108630 TestCLBeaconRegion + 1885744
	9   TestCLBeaconRegion                  0x00000001010a73a0 TestCLBeaconRegion + 1487776
	10  TestCLBeaconRegion                  0x000000010114fe4c mono_pmip + 25056
	11  TestCLBeaconRegion                  0x00000001011e1694 mono_pmip + 621096
	12  TestCLBeaconRegion                  0x00000001011e4afc mono_pmip + 634512
	13  TestCLBeaconRegion                  0x0000000100f41d30 TestCLBeaconRegion + 23856
	14  TestCLBeaconRegion                  0x0000000100f41a20 TestCLBeaconRegion + 23072
	15  CoreLocation                        0x0000000195170b54 CLClientStopVehicleHeadingUpdates + 76292
	16  CoreLocation                        0x000000019516f414 CLClientStopVehicleHeadingUpdates + 70340
	17  CoreLocation                        0x0000000195159854 CLClientInvalidate + 1288
	18  CoreFoundation                      0x000000018e340d6c <redacted> + 20
	19  CoreFoundation                      0x000000018e340670 <redacted> + 272
	20  CoreFoundation                      0x000000018e33bbdc <redacted> + 2312
	21  CoreFoundation                      0x000000018e33afb4 CFRunLoopRunSpecific + 436
	22  GraphicsServices                    0x000000019053c79c GSEventRunModal + 104
	23  UIKitCore                           0x00000001bad81c38 UIApplicationMain + 212
	24  TestCLBeaconRegion                  0x000000010111c3c8 TestCLBeaconRegion + 1967048
	25  TestCLBeaconRegion                  0x000000010110a9a0 TestCLBeaconRegion + 1894816
	26  TestCLBeaconRegion                  0x000000010110a924 TestCLBeaconRegion + 1894692
	27  TestCLBeaconRegion                  0x0000000100f43ab0 TestCLBeaconRegion + 31408
	28  TestCLBeaconRegion                  0x00000001010a73a0 TestCLBeaconRegion + 1487776
	29  TestCLBeaconRegion                  0x000000010114fe4c mono_pmip + 25056
	30  TestCLBeaconRegion                  0x00000001011e1694 mono_pmip + 621096
	31  TestCLBeaconRegion                  0x00000001011e6710 mono_pmip + 641700
	32  TestCLBeaconRegion                  0x0000000101135328 TestCLBeaconRegion + 2069288
	33  TestCLBeaconRegion                  0x00000001012857d0 xamarin_log + 15348
	34  TestCLBeaconRegion                  0x0000000100f439b4 TestCLBeaconRegion + 31156
	35  libdyld.dylib                       0x000000018ddfe8e0 <redacted> + 4

  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:407 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/runtime/Delegates.generated.cs:126 
  at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
  at (wrapper managed-to-native) ObjCRuntime.Messaging.IntPtr_objc_msgSend(intptr,intptr)
  at CoreLocation.CLBeaconRegion.get_Uuid () [0x00003] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/CoreLocation/CLBeaconRegion.g.cs:365 
  at TestCLBeaconRegion.AppDelegate.Manager_DidDetermineState (System.Object sender, CoreLocation.CLRegionStateDeterminedEventArgs e) [0x00002] in C:\Users\CBiagioli\source\Workspaces\DURANTE\SPACEBOOKING\XMobileApp\TestCLBeaconRegion\AppDelegate.cs:63 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) ObjCRuntime.Messaging.IntPtr_objc_msgSend(intptr,intptr)
  at CoreLocation.CLBeaconRegion.get_Uuid () [0x00003] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/CoreLocation/CLBeaconRegion.g.cs:365 
  at TestCLBeaconRegion.AppDelegate.Manager_DidDetermineState (System.Object sender, CoreLocation.CLRegionStateDeterminedEventArgs e) [0x00002] in C:\Users\CBiagioli\source\Workspaces\DURANTE\SPACEBOOKING\XMobileApp\TestCLBeaconRegion\AppDelegate.cs:63 	0   CoreFoundation                      0x000000018e3af198 <redacted> + 252
	1   libobjc.A.dylib                     0x000000018d5879f8 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018e2cb9bc <redacted> + 0
	3   CoreFoundation                      0x000000018e3b49c8 <redacted> + 1408
	4   CoreFoundation                      0x000000018e3b665c _CF_forwarding_prep_0 + 92
	5   TestCLBeaconRegion                  0x000000010111ac30 TestCLBeaconRegion + 1961008
	6   TestCLBeaconRegion                  0x0000000101109264 TestCLBeaconRegion + 1888868
	7   TestCLBeaconRegion                  0x0000000100f44740 TestCLBeaconRegion + 34624
	8   TestCLBeaconRegion                  0x0000000101108630 TestCLBeaconRegion + 1885744
	9   TestCLBeaconRegion                  0x00000001010a73a0 TestCLBeaconRegion + 1487776
	10  TestCLBeaconRegion                  0x000000010114fe4c mono_pmip + 25056
	11  TestCLBeaconRegion                  0x00000001011e1694 mono_pmip + 621096
	12  TestCLBeaconRegion                  0x00000001011e4afc mono_pmip + 634512
	13  TestCLBeaconRegion                  0x0000000100f41d30 TestCLBeaconRegion + 23856
	14  TestCLBeaconRegion                  0x0000000100f41a20 TestCLBeaconRegion + 23072
	15  CoreLocation                        0x0000000195170b54 CLClientStopVehicleHeadingUpdates + 76292
	16  CoreLocation                        0x000000019516f414 CLClientStopVehicleHeadingUpdates + 70340
	17  CoreLocation                        0x0000000195159854 CLClientInvalidate + 1288
	18  CoreFoundation                      0x000000018e340d6c <redacted> + 20
	19  CoreFoundation                      0x000000018e340670 <redacted> + 272
	20  CoreFoundation                      0x000000018e33bbdc <redacted> + 2312
	21  CoreFoundation                      0x000000018e33afb4 CFRunLoopRunSpecific + 436
	22  GraphicsServices                    0x000000019053c79c GSEventRunModal + 104
	23  UIKitCore                           0x00000001bad81c38 UIApplicationMain + 212
	24  TestCLBeaconRegion                  0x000000010111c3c8 TestCLBeaconRegion + 1967048
	25  TestCLBeaconRegion                  0x000000010110a9a0 TestCLBeaconRegion + 1894816
	26  TestCLBeaconRegion                  0x000000010110a924 TestCLBeaconRegion + 1894692
	27  TestCLBeaconRegion                  0x0000000100f43ab0 TestCLBeaconRegion + 31408
	28  TestCLBeaconRegion                  0x00000001010a73a0 TestCLBeaconRegion + 1487776
	29  TestCLBeaconRegion                  0x000000010114fe4c mono_pmip + 25056
	30  TestCLBeaconRegion                  0x00000001011e1694 mono_pmip + 621096
	31  TestCLBeaconRegion                  0x00000001011e6710 mono_pmip + 641700
	32  TestCLBeaconRegion                  0x0000000101135328 TestCLBeaconRegion + 2069288
	33  TestCLBeaconRegion                  0x00000001012857d0 xamarin_log + 15348
	34  TestCLBeaconRegion                  0x0000000100f439b4 TestCLBeaconRegion + 31156
	35  libdyld.dylib                       0x000000018ddfe8e0 <redacted> + 4
### Environment

```
Microsoft Visual Studio Enterprise 2019 (3)
Version 16.9.0
VisualStudio.16.Release/16.9.0+31025.194
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA133
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.687.37626
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2107702+c4adaa061f13292143de82a96c71341e50bc4032
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.687.37626
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.687.37626
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.687.37626
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.30502.00
Microsoft Office Developer Tools for Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   16.9.000.271 (d16-9@863670b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.0.21 (d16-9/93eab59)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@d6d86b2
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d


Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

Build started...
1>------ Build started: Project: TestCLBeaconRegion, Configuration: Debug iPhone ------
1>  Executing SayHello Task to establish a connection to a Remote Server. 
1>  			Properties: 
1>  				SessionId=7dbbbe98ba9cf36d87e7b851b27d83c724545d11b0d9372d28b1294ad1f2d683, 
1>  				ServerPort=50255, 
1>  				ServerAddress=10.20.4.220, 
1>  				ServerUser=sviluppo, 
1>  				ServerPassword=, 
1>  				SSHKey=, 
1>  				SSHPassPhrase=,
1>  				AppName=TestCLBeaconRegion,
1>  				VisualStudioProcessId=23196,
1>  				ContinueOnDisconnected=False
1>  TestCLBeaconRegion -> C:\Users\CBiagioli\source\Workspaces\DURANTE\SPACEBOOKING\XMobileApp\TestCLBeaconRegion\bin\iPhone\Debug\TestCLBeaconRegion.exe
1>  Detected signing identity:
1>          
1>    Code Signing Key: "xxx" (xxx)
1>    Provisioning Profile: "VS: WildCard Development" (fc4bd49f-d6a1-4d5c-9205-14ca668d0bdd)
1>    Bundle Id: com.companyname.TestCLBeaconRegion
1>    App Id: 5JVRNNJ7H4.com.companyname.TestCLBeaconRegion
1>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/sviluppo/Library/Caches/Xamarin/mtbs/builds/TestCLBeaconRegion/7dbbbe98ba9cf36d87e7b851b27d83c724545d11b0d9372d28b1294ad1f2d683/obj/iPhone/Debug/device-builds/iphone7.2-12.5.1/response-file.rsp 
1>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -num-threads 4 -z -o bin/iPhone/Debug/device-builds/iphone7.2-12.5.1/TestCLBeaconRegion.app.dSYM bin/iPhone/Debug/device-builds/iphone7.2-12.5.1/TestCLBeaconRegion.app/TestCLBeaconRegion 
1>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -i -s obj/iPhone/Debug/device-builds/iphone7.2-12.5.1/mtouch-symbols.list bin/iPhone/Debug/device-builds/iphone7.2-12.5.1/TestCLBeaconRegion.app/TestCLBeaconRegion 
1>  /usr/bin/mdimport bin/iPhone/Debug/device-builds/iphone7.2-12.5.1/TestCLBeaconRegion.app/../ 
1>  /usr/bin/codesign --verify -vvvv "-R=anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.1] exists and (certificate leaf[field.1.2.840.113635.100.6.1.2] exists or certificate leaf[field.1.2.840.113635.100.6.1.4] exists)" bin/iPhone/Debug/device-builds/iphone7.2-12.5.1/TestCLBeaconRegion.app 

### Example Project (If Possible)

[TestCLBeaconRegion.zip](https://github.com/xamarin/xamarin-macios/files/6101193/TestCLBeaconRegion.zip)

**Comment by mandel-macaque** [comment]
Hello,

I have executed the test application on a simulator and on a device with no crashes. What is the testing process to reproduce the crash? Are there any special things to do (since we are dealing with CCLocation).

**Comment by ClaudioBiagioli** [comment]
Hi Manuel, you should have an iBeacon (or some device simulating it) in
order to fully test it.
However the DidDetermineState event should be called even if the beacons
are not in range and there the problem arises (it's just catched in the
sample app I provided, you can check with a break point or remove the
try-catch).

The other (I think same) problem in the EnterRegion event instead needs an
iBeacon.
You can use a simulator app, like "Beacon Simulator" available in Google
and Apple stores (just create the beacon with the same uuid used in the
sample app: 476c6f62-616c-2d54-6167-000000000000)

Let me know if you need further assistance to check the problem.
Thanks

Il giorno mer 10 mar 2021 alle ore 19:50 Manuel de la Pena <
***@***.***> ha scritto:

**Comment by spouliot** [comment]
@ClaudioBiagioli what is the iOS version of the device you're using ?

**Comment by ClaudioBiagioli** [comment]
I've the same problem with an old Iphone6 with iOS12 and a newer IPhone 11
with latest iOS.



Il giorno mar 16 mar 2021 alle ore 17:49 Sebastien Pouliot <
***@***.***> ha scritto:

**Comment by spouliot** [comment]
The `UUID` property was added in iOS 13 - so it won't work in older OS versions, like 12.x. That also match the (expected) native exception you mentioned in your original description.

> Objective-C exception thrown. Name: NSInvalidArgumentException Reason: -[CLBeaconRegion UUID]: unrecognized selector sent to instance 0x281956920

I do not know why it would fail on the _latest_ iOS but, like mentioned, it's a native (not managed) exception which means it comes directly from the OS (and not from Xamarin.iOS). 

Double check the iOS version being used on your device. There might be a difference in the exception message of the newer device/OS.

**Comment by ClaudioBiagioli** [comment]
You're right guys, it was all due to an old version of iOS. Sorry for the misunderstanding. I Close the issue.
