### ISSUE TITLE
[intro] `Introduced` test disabled for `NET`

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#10834]
The test is disabled to avoid failures, e.g.

iOS
```
[FAIL] Introduced : 7573 API with unneeded or incorrect version information
```

tvOS
```
[FAIL] Introduced : 299 API with unneeded or incorrect version information 
```

This requires the new attributes and some generator filtering. This will be done across a few different PR, some will ge quite large.

**Comment by spouliot** [comment]
PR #12361 enabled this on MacCatalyst legacy
Remaining work is for dotnet only

**Comment by rolfbjarne** [comment]
@chamons what's the status of this?

**Comment by chamons** [comment]
I somehow neglected to see this when doing the work. I'll take a look this week.

**Comment by rolfbjarne** [comment]
I've postponed this to .NET 7 since our .NET 6 support is already out.

**Comment by rolfbjarne** [comment]
This is complete now.
