### ISSUE TITLE
C#9 xamarin iOS Build fails against Microsoft hosted agent

### ISSUE THREAD

**Issue by developer9969** [xamarin/xamarin-macios#10854]
Hi 
I have done the following 
Set all the class libraries as follows

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>preview</LangVersion>
      </PropertyGroup>

If I use any of the c#9 feature  I.E  "is not null  or new(); the pipeline fails and gives me errors like  "; expected or ) expected"  but you if you go to the actual line I did change to use a c#9 feature. 

Workaround
Dont use C#9 if you want your iOS project to build when using the pipeline.

I am using the macOS-latest  

Any suggestions? 
thanks

**Comment by dalexsoto** [comment]
Hello,

the current stable versions of Xamarin.Mac and Xamarin.iOS are based in the 2020-02 branch of mono which do not contain C#9 support at the moment. The support for C# 9 and vnext is currently on preview for our .NET 6 edition of the SDKs https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-2/ so if you really need C# 9 features currently the only way to get those is by using our .NET 6 Preview.

**Comment by developer9969** [comment]
@dalexsoto  Hi thanks for your reply. Good to know , however just found an answer here
https://stackoverflow.com/questions/65309660/csc-on-macos-does-not-list-c-sharp-9

stating that if you use dot net build should work. Is this the case?

thanks

**Comment by dalexsoto** [comment]
Our macios tooling as I mentioned is based on the mono 2020-02 branch that lacks C# 9 support, if you use `dotnet` YMMV since that is a tool that ships separately from our SDKs.

**Comment by developer9969** [comment]
I have removed c#9 from all our class libraries, not essential for now  thank you very much for  your replies
