### ISSUE TITLE
Default RuntimeIdentifier

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10861]
Currently we require the RuntimeIdentifier to be set in order to build on all the Apple platforms, but having a default RuntimeIdentifier might make sense, at least in certain cases (and we don't have to do the same thing on all platforms).

### Desktop platforms (macOS + Mac Catalyst)

For desktop platforms (macOS + Mac Catalyst), we have the choice between x64 and arm64, and at least for these platforms I think we should set a default. Options:

1. Require the developer to specify (what we do now).
2. Set the default to x64. Most compatible (runs on both arm64 and x64).
3. Set the default to arm64. Most future-proof (probably), but will be non-intuitive when building on an x64 machine (since the app won't launch).
4. Set the default to the CPU of the machine. Probably the best user experience, but it's undeterministic, since the results depend on the machine you're using to build (CI can become frustrating).

IMHO the second option is the one that makes the most sense.

At least for now I think it makes most sense to have the same default for both platforms.

### Mobile platforms (iOS + tvOS)

We have more options here, because the app can target either a simulator or a device - this is really what it comes down to, if we should default to simulator or device, or if we should require the user to specify.

1. Require the developer to specify (what we do now).
2. Default to build for simulator.
    Pro: should always be able to build something that can be launched.
    Con: ?
3. Default to build for device.
4. Detect if there are any devices attached, and if so build for device, if not build for the simulator
    Cons: undeterministic. Someone trips over a network cable that disconnects your Apple TV, and suddenly your build behaves differently?
5. Build for both the simulator and device just in case.
    Cons: Slow. Will always spend time building something that is not needed.

IMHO we should default to the simulator (if we decide to default to anything).

We should also have in mind that we might want to change the default later.

Any other options/opinions?

We should also validate that the RuntimeIdentifier is one of the values we support.

**Comment by jonathanpeppers** [comment]
My thinking for making the iOS simulator default is to make the getting started experience smoother. A first-time user probably won't have a device connected yet, but the simulator would be able to launch fine. An experienced user will more likely understand how to change a setting to deploy to a device.

Hopefully, the IDE would be able to select the right `$(RuntimeIdentifier)` when you select a device in the dropdown?

**Comment by spouliot** [comment]
> Desktop platforms (macOS + Mac Catalyst)

Agreed with option 2.
We can print something like `Building for x86_64 (default). Override with XXX` on the console (useful in logs).

> Mobile platforms (iOS + tvOS)

Agreed with option 2 on Mac
The (small) _con_ would be to decide "which" simulator (e.g. iPhone vs iPad) but that's more a launch than a build issue (unless they start to differ more in the future)

On Windows... then a Mac might not be connected so it would make sense to build for a device. However it's more an IDE thing than the default tool (which runs on the Mac).

> Hopefully, the IDE would be able to select the right $(RuntimeIdentifier) when you select a device in the dropdown?

Yes, my understanding is that is more CLI defaults than IDE, just like we had with `mtouch` before.
