### ISSUE TITLE
[Question] Is it possible to build and deploy Xamarin.Ios project on linux if mac in the same network?

### ISSUE THREAD

**Issue by brud** [xamarin/xamarin-macios#10885]
I mean something like Visual Studio -> xCode connection.
As I can see for now this is not implemented.
Can someone suggest how difficult will be to try to implement this, or perhaps there are some developments?

**Comment by mandel-macaque** [comment]
Can you please elaborate? When you mean deploy, is that copying the app over to the mac in the same network?

**Comment by brud** [comment]
@mandel-macaque I mean copy all sources via ssh to mac, then build app, and copy app to iphone/emulator

**Comment by brud** [comment]
@mandel-macaque also is it possible to get intellisense in iOS project?

**Comment by mandel-macaque** [comment]
it is not supported, but it 'close' to what is done in the Visual Studio agent, so you could definitely get  a project to work.

**Comment by mandel-macaque** [comment]
I'm closing the issue since it is more of a 'could it be done' question :)
