### ISSUE TITLE
Output Paths for .NET 6 iOS builds are inconsistent

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-macios#10895]
When building an iOS app on .NET 6, the output paths seem to be inconsistent with other .NET 6 framework identifiers.  I think it's worth discussing what the best / most correct / most consistent path should be.

For example, `dotnet build -f net6.0-ios` results in the build output going to:
`bin/Debug/net6.0-ios/ios-x64` (or a pattern of `[bin|obj]/$(Configuration)/$(TargetFramework)/$(RuntimeIdentifier)` ).

If you build with `botnet build -f net6.0-ios -p:Platform=iPhoneSimulator` you end up with:
`bin/Debug/iPhoneSimulator/net6.0-ios/ios-x64` (or a pattern of `[bin|obj]/$(Configuration)/$(Platform)/$(TargetFramework)/$(RuntimeIdentifier)`).

A few observations / questions arise:

1. In the first example, `$(Platform)` is missing completely, and since it's not specified the default seems to be `AnyCPU`, which causes no extra path segment to be used.
2. Since we are getting runtime packs differentiated for simulator and M1, does it make sense to not really use 'Platform' as a variable anymore?  Should RID be enough at that point to differentiate all of the targets?
3. If we do keep `iPhone` and `iPhoneSimulator` values for Platform, I think `$(Platform)` should shift deeper into the output path, perhaps instead we should use: `[bin|obj]/$(Configuration)/$(TargetFramework)/$(RuntimeIdentifier)/$(Platform)`

**Comment by rolfbjarne** [comment]
We're just using the existing OutputPath property, so I'm not sure how much we can do here (or how much we should do).

For question 2: we need the platform when building apps for multiple RIDs.

**Comment by rolfbjarne** [comment]
@Redth we don't modify the OutputPath format, that's defined here:

https://github.com/dotnet/sdk/blob/efd4338e20b302e9ac11cebc7bc2a5a5bb5dd349/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultOutputPaths.targets#L33-L35
https://github.com/dotnet/sdk/blob/efd4338e20b302e9ac11cebc7bc2a5a5bb5dd349/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.TargetFrameworkInference.targets#L245
https://github.com/dotnet/sdk/blob/efd4338e20b302e9ac11cebc7bc2a5a5bb5dd349/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets#L235

so I don't think we can/should do anything here.

**Comment by rolfbjarne** [comment]
Closing as per last comment.
