### ISSUE TITLE
Optimization: make the linker change ObjCRuntime.Runtime.IsCoreCLR a constant

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#10903]
The value for ObjCRuntime.RUntime.IsCoreCLR is a value known at build time, so it's possible for the managed linker to replace it with a constant true/false.

Ref: https://github.com/xamarin/xamarin-macios/pull/10900

**Comment by spouliot** [comment]
That was fixed in bab6827b8d
