### ISSUE TITLE
 Error CS0246: The type or namespace name 'SQLite' could not be found (are you missing a using directive or an assembly reference?) (CS0246) 

### ISSUE THREAD

**Issue by maurocaputi** [xamarin/xamarin-macios#10916]
### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

**Comment by mandel-macaque** [comment]
WE need more information, please provide something for us to work with. But the error seems to be self-explanatory, probably the SQLite nuget is missing.

**Comment by maurocaputi** [comment]
After last update of visual studio xamarin I logged the following error:

/Users/maurocaputi/Projects/InfoSappe/InfoSappe.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Void System.Security.Cryptography.DSACng ::. Ctor (System.Security.Cryptography.CngKey)', referenced from the method 'T Internal.Cryptography.Pal.Windows.PkcsPalWindows :: GetPrivateKey (System.Security.Cryptography.X509Certificates.X509Certificate2, System.Boolean, System.Boolean)' in 'System.Security.Cryptography.Cng, Version = 4.3.3.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a '. (MT2101) (InfoSappe.iOS)


i use mailkit to send mails.
this error only at "release" compile time.
thank you
 Mauro

**Comment by mandel-macaque** [comment]
The above call looks like a win32 call: Internal.Cryptography.Pal.Windows.PkcsPalWindows :: GetPrivateKey we have had an issue with a nuget that was incorrect and was adding win32 libs: https://github.com/xamarin/xamarin-macios/issues/8791

**Comment by spouliot** [comment]
Closing as we have not heard back from the original issue and the other one is already filed (and not part of the SDK).
