### ISSUE TITLE
Asset Catalog not being included in debug build when deploying to device

### ISSUE THREAD

**Issue by Rothanan** [xamarin/xamarin-macios#11012]
How to reproduce:
-Use the latest version of Visual Studio 2019
-Create a Solution with the Xamarin Mobile template.
-Set the Ios solution as the start up project
-Open the asset catalog
-Delete the current AppIcons
-Create a new one with a different icon than the default
-Make sure you readd the app icons in the info.plist under "Visual Assets"
-Deploy a debug build to an ios device(physical device).

What to expect:
The app will be installed and it will have the xamarin logo(ignoring the changes you have just made).

When I deploy it to a Simulator it builds correctly.

I've tested this at least 4 different projects that I had and I tested it on a brand new project and the result is: asset catalog doesn't get included in the debug build for the device. My older solutions used to build just fine.

What I already did:
-Verified the path in the info.plist code
-Reseted my ios device to factory settings
-Deleted bin/obj folder

> VS bug [#1304507](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1304507)

**Comment by mandel-macaque** [comment]
From my understanding this is happening from VS Windows, correct? Can you please add the full version? 

On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item. Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by Rothanan** [comment]
Microsoft Visual Studio Community 2019
Version 16.9.2
VisualStudio.16.Release/16.9.2+31112.23
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA145
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.9.688.6828
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.9.688.6828
Azure App Service Tools v3.0.0

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Unity   4.9.1.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.273 (d16-9@1bba9e0)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.2.1 (d16-9/877f572)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@54f8c24
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11


Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
