### ISSUE TITLE
ApplyTintColor throws exception in iPhone 7 iOS 12.4

### ISSUE THREAD

**Issue by sulayjoshi-bs** [xamarin/xamarin-macios#11065]
**Description**

When I use uIImage.ApplyTintColor on an iPhone 7 iOS 12.4, I get an exception NSInvalidArgumentException

**Steps to Reproduce**

        UIImage uIImage = uiTabBarItem.SelectedImage;
        var color = Color.FromHex("#F29232");
        var uiColor = color.ToUIColor();
        uIImage = uIImage.ApplyTintColor(uiColor);

**Expected Behavior**

Image should be tinted

**Actual Behavior**

Exception thrown:
Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[UIImage imageWithTintColor:]: unrecognized selector sent to instance 0x600002cae1b0

**Basic Information**

 IDE and Platform:
    
    
![image](https://user-images.githubusercontent.com/81735827/113251102-51a40c80-92df-11eb-8eae-65a8f9112810.png)

    
 Affected Devices: iPhone 7 iOS 12.4

**Workaround**

Try/catch around uIImage .ApplyTintColor

**Comment by spouliot** [comment]
That's normal since Apple added the API in iOS 13.0.

```csharp
[Watch (6,0), TV (13,0), iOS (13,0)]
[Export ("imageWithTintColor:")]
UIImage ApplyTintColor (UIColor color);
```

If you want your application to work with earlier iOS versions you need add conditional code around newer API. Example

```csharp
UIImage uIImage = uiTabBarItem.SelectedImage;
if (UIKit.UIDevice.CurrentDevice.CheckSystemVersion (13, 0)) {
    var color = Color.FromHex("#F29232");
    var uiColor = color.ToUIColor();
    uIImage = uIImage.ApplyTintColor(uiColor);
} else {
    // do something else on older OS versions
}
```
