### ISSUE TITLE
Broadcast Extension Project Could not be debug

### ISSUE THREAD

**Issue by jingliancui** [xamarin/xamarin-macios#11132]
![QQ截图20210406233243](https://user-images.githubusercontent.com/16309962/113737211-698ced80-9730-11eb-89c5-2eae0ae9fa27.png)
Although I add xamarin.ios app project to this args. App will run,but:

![QQ截图20210406232908](https://user-images.githubusercontent.com/16309962/113737098-4e21e280-9730-11eb-9c2b-89b79a24af55.png)
VS then show above message.

The broadcast extension could not start to debug.

This link is the  agora share screen sample I flow to do use xamarin.
https://docs.agora.io/en/Video/screensharing_ios?platform=iOS

My xamarin.ios Bundle identifier is com.xamarin.mysampleapp
My Broadcast extension Bundle identifier is com.xamarin.mysampleapp.ShareScreenExtension
And Other setting:

![QQ截图20210406233243](https://user-images.githubusercontent.com/16309962/113738099-2f701b80-9731-11eb-916b-4c253f48ec07.png)

![QQ截图20210406233929](https://user-images.githubusercontent.com/16309962/113738599-a2799200-9731-11eb-8f07-7abf01439e01.png)

**Comment by jingliancui** [comment]
https://1drv.ms/u/s!AiLsd2NKfovHnPxRAVxfkoppzqLf0A

Sample code link above, Thanks.

**Comment by mandel-macaque** [comment]
@jingliancui  can you please re-share the project. The above link does not work. Also please provide use with the full information of you environment.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by jingliancui** [comment]
@mandel-macaque  Sure, I re-upload this sample-code again :
https://1drv.ms/u/s!AiLsd2NKfovHnPxRRPhGbxUWhDT-Mg

**Comment by jingliancui** [comment]
And I found it can be debug on my iphone 12 ios14.4.2 but it can be debug on the iphone 7 plus ios 13.6

**Comment by jingliancui** [comment]
```
=== Visual Studio Community 2019 for Mac ===

Version 8.9.5 (build 4)
Installation UUID: 1470e2f3-64d9-49fd-9b5f-e5d339d5cf3e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.201/Sdks
SDK Versions:
	5.0.201
	3.1.407
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.4
	3.1.13

=== .NET Core 3.1 SDK ===

SDK: 3.1.407

=== Xamarin Designer ===

Version: 16.9.0.323
Hash: 1b4790c08
Branch: remotes/origin/d16-9
Build date: 2021-03-31 05:12:20 UTC

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.8.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

=== Xamarin.iOS ===

Version: 14.14.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Community)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/ericcui/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/ericcui/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9~2
Build date: 2021-03-24 08:30:26 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-03-24 08:30:44 UTC

=== Build Information ===

Release ID: 809050004
Git revision: ec53df089052c178e16b778d89782a97e01d7fa2
Build date: 2021-03-31 17:20:20-04
Build branch: release-8.9
Xamarin extensions: ec53df089052c178e16b778d89782a97e01d7fa2

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:06:51 PST 2021
    root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64


```

**Comment by jingliancui** [comment]
[API-Examples-master.zip](https://github.com/xamarin/xamarin-macios/files/6297367/API-Examples-master.zip)
Another import info is you can use xcode to run this samplle and go to "屏幕共享" feature try xcode debug.
Compile the xcode app will throw error said need key and token ,you can random type anything for key or token ,or you can go the  the agora's page to get these free.
And at last you will found that the xcode still could not be debug with the iphone12 ios 14.4.2 .

**Comment by jingliancui** [comment]
It's seem like that  it's iPhone issue , just restart the device and all fine.
Please visit it:
https://github.com/AgoraIO/API-Examples/issues/148
