### ISSUE TITLE
README: provide download links for d16.8 and d16.9

### ISSUE THREAD

**Issue by janusw** [xamarin/xamarin-macios#11218]
I'm having massive trouble with the latest Xamarin.iOS and Xamarin.Mac versions and would like to downgrade to an older version (probably d16.8). The downloads section in the README has links to older versions, but the recent ones (d16.8 and d16.9) are missing. Could they please be added?

### Steps to Reproduce

1. Open the README at https://github.com/xamarin/xamarin-macios/blob/main/README.md
2. Look at the Downloads section: https://github.com/xamarin/xamarin-macios/blob/main/README.md#downloads
3. Keep staring.

### Expected Behavior

There should be links to all released versions.

### Actual Behavior

The versions of up to d16.7 are present, but d16.8 and d16.9 are missing.

### Environment

Mac OS 11.2.3
VS for Mac 8.9

### Build Logs

--

### Example Project (If Possible)

--

**Comment by janusw** [comment]
Actually I have no idea how to find out the links on `download.visualstudio.microsoft.com`, but I have found some alternative links from homebrew (see https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/xamarin-ios.rb and its history):

* https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-14.14.2.5.pkg
* https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-14.10.0.4.pkg
* https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-14.8.0.3.pkg
* https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-14.6.0.15.pkg
* https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-14.4.1.3.pkg

I think the first one should be for d16.9 (14.14.2.5 is what I see in VS for Mac 8.9). And possibly 14.10.0.4 for d16.8?

**Comment by janusw** [comment]
And analogously for xamarin.mac (see https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/xamarin-mac.rb):

* https://dl.xamarin.com/XamarinforMac/Mac/xamarin.mac-7.8.2.5.pkg
* https://dl.xamarin.com/XamarinforMac/Mac/xamarin.mac-7.4.0.10.pkg
* https://dl.xamarin.com/XamarinforMac/Mac/xamarin.mac-7.2.0.3.pkg
* https://dl.xamarin.com/XamarinforMac/Mac/xamarin.mac-7.0.0.15.pkg
* https://dl.xamarin.com/XamarinforMac/Mac/xamarin.mac-6.22.1.26.pkg

Again, the first one should be for d16.9 (seen with VS for Mac 8.9).

**Comment by mandel-macaque** [comment]
It is a valid request, @dalexsoto can we update the Wiki to point to the latests stable of older versions?

@janusw Our builds create the pkgs and provide them via the statuses of the build, how far do you want to revert and I'll find the correct version for you.

**Comment by janusw** [comment]
> @janusw Our builds create the pkgs and provide them via the statuses of the build, how far do you want to revert and I'll find the correct version for you.

xamarin.ios-14.10.0.4 is sufficient for my purpose. #11219 is the horror I'm running from ...

**Comment by rolfbjarne** [comment]
All released versions can now be downloaded from https://github.com/xamarin/xamarin-macios/blob/main/DOWNLOADS.md.
