### ISSUE TITLE
[dotnet] P4 runtime issue tracking

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#11222]
Updating from P3

## PR#[11127](https://github.com/xamarin/xamarin-macios/pull/11127)
* Microsoft.Dotnet.Sdk.Internal: from 6.0.100-preview.3.21202.5 to 6.0.100-preview.4.21207.50
  * Several tests failures -> merge **~BLOCKED~**

### Fixes
* PR#[11173](https://github.com/xamarin/xamarin-macios/pull/11173) [dotnet][msbuild] Fix RelativePath inside ResolvedFileToPublish
* PR#[11182](https://github.com/xamarin/xamarin-macios/pull/11182) Bump MSBuild.StructuredLogger to 2.1.404

**PR was automatically merged (CI _error_ since it has not run the tests)** -> [reverted](https://github.com/xamarin/xamarin-macios/pull/11167)

## PR#[11175](https://github.com/xamarin/xamarin-macios/pull/11175)
* Microsoft.Dotnet.Sdk.Internal: from 6.0.100-preview.3.21202.5 to 6.0.100-preview.4.21215.1
  * Most failures seems related to linker `Copy` changes -> seems fixed by a later bump (likely the one that included https://github.com/mono/linker/commit/7f7eb298a1ea6a144b2fb795ca10feb138e3988a)
* From Version 6.0.100-preview.3.21202.5 -> To Version 6.0.100-preview.4.21214.14
  * ~~[Update Mono package names](https://github.com/xamarin/xamarin-macios/pull/11175/commits/ed3ac894ae6dc36878fcf04380d2a15dedc96ba6)~~ thanks @pjcollins for heads up
  * ~~[build failures](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4655721&view=logs&j=600d49c6-e96b-5e8b-2c3a-9f351e2e5848&t=07666b37-6d9f-5bbc-b86d-576c4ed77678) (on CI) due to missing `libicudata.a`~~ -> [fix](https://github.com/xamarin/xamarin-macios/pull/11175/commits/a22402ec0fea9ecba81cadbb1b838a3c0a6e3e40)
  * ~~[app builds fails for missing symbols](https://gist.github.com/spouliot/7c0af433d48b4bd96d093473caf2b3f7) hiding previous link sdk issue~~ -> [fix](https://github.com/xamarin/xamarin-macios/pull/11175/commits/106defd7ae065a40bb32356c19f00d4197b39c87)
  * ~~linker not working (tests seems fine) leading to [huge app size](https://gist.github.com/spouliot/443c562371a0c478c96a9a862b2dac02) and build times~~ -> [fix](https://github.com/xamarin/xamarin-macios/pull/11175/commits/c837f583f9938384209a020ae3e6b9e68750069e)
  * monotouch-tests timeout happened on the last 3 runs
    * seems TimeZone / ICU related -> @filipnavara filled both https://unicode-org.atlassian.net/browse/ICU-21591 and https://github.com/unicode-org/icu/pull/1699 -> introduced with https://github.com/dotnet/runtime/pull/48931 -> [workaound](https://github.com/xamarin/xamarin-macios/pull/11175/commits/5fdd4e2dec744e8741beb2edf9c3d20873107283)
    * ~~non-dotnet tests also failed - but they started to work again once the test timing out was ignored (that likely cause an issue on bots)~~
  * ~~coreclr runtime for Mac is not downloaded anymore - but there's no build failures~~ -> [fix](https://github.com/xamarin/xamarin-macios/pull/11175/commits/1e376e7ffc4994241191dfcb4268fc22f869d083)
  * ~~[more path issues affecting satellite assemblies](https://github.com/xamarin/xamarin-macios/issues/11232) likely similar to #11173 above~~ -> [fix](https://github.com/xamarin/xamarin-macios/pull/11175/commits/52ca9625ea37e519971ee9a029fad8e0f2e44e9e)

PR#11175 was merged in `main` and became the base for `release/6.0.1xx-preview4`

Keeping issue open as we can get more P4 bumps (in both branches)

## PR#[11314](https://github.com/xamarin/xamarin-macios/pull/11314) ~~unmerged, blocked by test failures~~ **MERGED**

* ~~[`MSBuild tests/Integration: Failed (Execution failed with exit code 32)`](https://github.com/xamarin/xamarin-macios/pull/11314#issuecomment-826847719)~~
  * Multiple `ArgumentNullException` failures for `Xamarin.iOS.Tasks.DotNetTest`
  * Requires a newer MSBuild.StructuredLogger (2.1.472), waiting for it to be available on our feed
    * Fix https://github.com/xamarin/xamarin-macios/pull/11314/commits/4a31e75dce90468f0c641dc920a96c62ac715386

## PR#[11426](https://github.com/xamarin/xamarin-macios/pull/11426) **MERGED**

* [merged](https://github.com/xamarin/xamarin-macios/commit/014ffa6f26ba507123c44ad99ec7e9fc5df5a8a9)

## PR#[11443](https://github.com/xamarin/xamarin-macios/pull/11443)

* building...

**Comment by spouliot** [comment]
> app builds fails for missing symbols hiding previous link sdk issue

The native libraries are not copied into `obj` so they are not linked to the final executable - so we're left with undefined symbols, which breaks the build.

On preview 4

```
09:29:32.6206100                              /Users/poupou/git/main/xamarin-macios/tests/dotnet/packages/microsoft.netcore.app.runtime.mono.iossimulator-x64/6.0.0-preview.4.21213.3/runtimes/iossimulator-x64/native/libSystem.Net.Security.Native.a
09:29:32.6206150                                      AssemblyVersion=
09:29:32.6206320                                      AssetType=native
09:29:32.6206380                                      CopyLocal=true
09:29:32.6206420                                      DestinationSubPath=libSystem.Net.Security.Native.a
09:29:32.6206470                                      DropFromSingleFile=true
09:29:32.6206520                                      FileVersion=0.0.0.0
09:29:32.6206560                                      IsTrimmable=true
09:29:32.6206620                                      NuGetPackageId=Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64
09:29:32.6206660                                      NuGetPackageVersion=6.0.0-preview.4.21213.3
09:29:32.6206710                                      PublicKeyToken=
09:29:32.6206760                                      RuntimeIdentifier=iossimulator-x64
```

On preview 3

```
DropFromSingleFile=
IsTrimmable=
```

**Comment by rolfbjarne** [comment]
@spouliot any reason we can't close this now? P4 should be good to go.

**Comment by spouliot** [comment]
@rolfbjarne waiting for the public release, just in case a last minute bump was requested

**Comment by spouliot** [comment]
https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-4/
