### ISSUE TITLE
watchOS GC Safe mode in debugger callbacks

### ISSUE THREAD

**Issue by lambdageek** [xamarin/xamarin-macios#11220]
After https://github.com/dotnet/runtime/pull/51185 (merged in https://github.com/dotnet/runtime/commit/75065a231a96cdd7b47f245dd4084a6a6539cc8d), the runtime will call the debugger transport callbacks in GC Safe mode.  Under hybrid and coop suspend this will allow embedders to avoid having to do their own GC thread state transitions.

However for watchOS that means `sdb_recv` will now do a redundant transition to GC Safe - which will cause a runtime assertion.

So for net6+, those calls to `MONO_ENTER_GC_SAFE`/`MONO_EXIT_GC_SAFE` should be removed.

https://github.com/xamarin/xamarin-macios/blob/359b79abbc8549958f8ad58528ca7938d2a3f8c1/runtime/monotouch-debug.m#L796-L802

**Comment by rolfbjarne** [comment]
Marking as low priority since we won't ship watchOS support for .NET 6.

**Comment by rolfbjarne** [comment]
Closing, since it doesn't look like we'll ship watchOS support in .NET anytime soon.
