### ISSUE TITLE
[maccatalyst] `UIKeyboard.BoundsUserInfoKey` member is missing

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#11237]
### Description

Similar to https://github.com/xamarin/xamarin-macios/issues/11236, the following member is present in `xamarinios10` and `net6.0-ios` but is not present in `net6.0-maccatalyst`:

`UIKeyboard.BoundsUserInfoKey`

### Environment

`6.0.100-preview.3.21202.5`

**Comment by spouliot** [comment]
Hidden by `XAMCORE_3_0`

Note that this was deprecated in iOS 3.2 (and Catalyst 13.0).
https://developer.apple.com/documentation/uikit/uikeyboardboundsuserinfokey

**Comment by spouliot** [comment]
You can see the API in the latest (just merged) API diff
https://gist.github.com/vs-mobiletools-engineering-service2/3329d5705cffab4bb74f418414111b77
