### ISSUE TITLE
Universal Links not working with iOS 14.4

### ISSUE THREAD

**Issue by abhaylakkad** [xamarin/xamarin-macios#11234]
was trying to create a deep link (Universal linking) in Andriod and iOS. It's working on anroid simulator. However, I'm not able to test it on iOS Simulator or thru test flight.. Here is what i did

Created and hosted valid "apple-app-site-association" (i put it on root of publicly accessible VD). Also verified this file thru https://branch.io/resources/aasa-validator/. All points passed successfully.

Enable associated domain in Entitlement.plist and Added "applinks:<myDomain>","applinks:*.<myDomain>" and "applinks:<myDomain>?mode=developer" urls.

Enable Associated Domain for this app under developer.apple.com>account>resources>identifier> <myapp>

Now for testing - I run the app in iphone simulator (iMac connected to Windows laptop)... added the url in one of the "contact", and hit it... the URL opens in safari browser. It doesn't open the app.
I tried to download app from test flight, the result is still the same.

Any help is appreciated.
Troubleshooting -
1. For debugging when i run the app from simulator or download the app on iphone from test flight. During the download it should look for "apple-app-site-association" and on my domain server.... i should see it in iis logs. But it doesn't shown up.

There were some entries in iis for apple-app-site-association file request, but at some different time. seeking the file at the root. So i put this file in .well-known folder an at the root.

I also change my web config to return application/josn content for "." (no extension)

I referred approach from https://www.xamboy.com/2019/01/08/applinks-in-xamarin-forms/

What am i missing here ? Does it should work on TestFlight ? or Simulator ? or directly on production ?
Any help is appreciated.

Further Questions - 
1. Not sure if this is a domain issue https://mysite.mycompany.com/apple-app-site-association. How to verify ?
2. Can i test this on Simulator (iMac) from my windows laptop ?
3. Should it be working on test flight ?
4. Anything else missing ?

**Comment by mandel-macaque** [comment]
What you describe sounds like an issue using the Apple SDK, yet this project is for the bindings and issues rather than the SDKs. Nevertheless, I want to try and give you a hand. Have you managed to create a swift/objc app that works?

If we can get a sample that works on swift yet it does not work on Xamarin, we do have an issue with our code, else, we might be able to see what API you need to use.

**Comment by abhaylakkad** [comment]
Thanks for the interest... I'm not sure about the swift/objc app, haven't used it before. 

But there is only three changes in our Xamarin App 
1. Enable Associated domain on apple for this app.
2. Add Associated domain entry in Entitlements.plist
3. in Xamain.ios app.xaml.cs add method OnAppLinkRequestReceived to catch the event 

the only one thing outside app is to host apple association file. ... and if 1 & 2 above are correct... it should simply log an entry in IIS log where i kept apple association file. it should not matter the file exist or not...it should log an entry on app installation.

**Comment by abhaylakkad** [comment]
This issues if fixed. The Entitlements were not included in release build. I have to open the .csproj manually and added following where ever it was missing inside PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'XXXXX' 

<CodesignEntitlements>Entitlements.plist</CodesignEntitlements>

This fixes my problem. Its working now without any other changes. 

Thanks for your time.
