### ISSUE TITLE
[dotnet] Localization files are copied to wrong place

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#11232]
When building https://github.com/xamarin/xamarin-macios/pull/11175 locally I noticed that the localization files were incorrectly copied to a directories like `bin/Debug/net6.0-macos/osx-x64/monotouchtest.app/Contents/MonoBundlees` instead of `MonoBundle/es`. There's a directory separator missing after the `MonoBundle` name.

**Comment by filipnavara** [comment]
This may have been broken by https://github.com/xamarin/xamarin-macios/pull/10621 which removed the last slash from `_AppContentsPath`.

**Comment by spouliot** [comment]
There was an earlier fix, in the P4 bump, to add extra `/` where none were required before. It's likely a similar case.

**Comment by filipnavara** [comment]
Yes, it's very likely also the case of `ResolvedFileToPublish`, just the other ones higher in the same file. I am not sure whether it was intentional breaking change since the MSBuild documentation for `MakeRelative` still shows directory separators being inserted.

**Comment by spouliot** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/pull/11175/commits/52ca9625ea37e519971ee9a029fad8e0f2e44e9e
