### ISSUE TITLE
CoreCLR: NSAutoreleasePool for every thread

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#11256]
CoreCLR has support for an NSAutoreleasePool for thread pool work items (https://github.com/dotnet/runtime/pull/47592), but it's missing support for having an NSAutoreleasePool for every thread.

This issue is to track the required work in CoreCLR and in our own code.

Ref: https://github.com/dotnet/designs/pull/197#issuecomment-818561306
Ref: https://github.com/dotnet/designs/pull/197#issuecomment-823907238
Ref: https://github.com/dotnet/runtime/pull/52023

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky and @kouvel Do either of you have thoughts on how to extend the work in https://github.com/dotnet/runtime/pull/47592 to enable support for all threads?

**Comment by akoeplinger** [comment]
@rolfbjarne with the support added in https://github.com/dotnet/runtime/pull/52023 we can use the `System.Threading.Thread.EnableAutoreleasePool` switch for Mono too and replace the custom code that uses the mono profiler for hooking thread start events in .NET 6 right?

**Comment by rolfbjarne** [comment]
@akoeplinger yes, that would be ideal.
