### ISSUE TITLE
xtro failures in main

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#11308]
xtro fails in main:

```
?fixed-todo? Entry '!missing-protocol-member! MTLDevice::supports32BitFloatFiltering not found' in 'MacCatalyst-Metal.todo' is not found in corresponding 'MacCatalyst-Metal.raw' file
?fixed-todo? Entry '!missing-protocol-member! MTLDevice::supports32BitMSAA not found' in 'MacCatalyst-Metal.todo' is not found in corresponding 'MacCatalyst-Metal.raw' file
?fixed-todo? Entry '!missing-protocol-member! MTLDevice::supportsQueryTextureLOD not found' in 'MacCatalyst-Metal.todo' is not found in corresponding 'MacCatalyst-Metal.raw' file
```

**Comment by spouliot** [comment]
related to https://github.com/xamarin/xamarin-macios/issues/11299

The xcode12.5 backport should have run xtro since binding files were modified. It was not :(
and `xcode12.5` does not have catalyst enabled (for xtro) so it was not caught there

**Comment by mandel-macaque** [comment]
The logs is the sameone we used to have in xharness, I'll take a look at the logs there. @rolfbjarne used run-xtro-tests and that was the diff.

**Comment by mandel-macaque** [comment]
Found out that I did not backport the required fix: https://github.com/xamarin/xamarin-macios/pull/11047
