### ISSUE TITLE
Leaks coming in from CGPath

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#11339]
### Steps to Reproduce

1. Use CGPath.FromRect
2. Profile in instruments
3. See unmanaged memory is leaked

### Expected Behavior

CGPath instances are properly cleaned up.

### Actual Behavior

It seems that there are copies that are lost along the way. MakeMutable always copies and all the users of the API pass it objects which are resulting from `Create*` APIs, which Cocoa API guidelines say that they mean you own the reference.

https://github.com/xamarin/xamarin-macios/blob/99fa931a279a220cd93f7ea842b7043e0e574932/src/CoreGraphics/CGPath.cs#L527

**Comment by Therzok** [comment]
`CGPathCreateMutable` and `Add*` APIs could be used to make this sane.

**Comment by spouliot** [comment]
`MakeMutable` creates a new, mutable, path
but the callers, not `MakeMutable`, are not releasing the original (non-mutable) path (the `IntPtr`)

**Comment by Therzok** [comment]
We could workaround it by changing:
```csharp
// from
var path = CGPath.FromRect(rect);

// to
var path = new CGPath();
path.AddRect(rect);
```

**Comment by nor0x** [comment]
any updates on this? thanks!

**Comment by SeRgI1982** [comment]
Would be great to fix it as soon as possible !
