### ISSUE TITLE
error MT5209: Error: warning: dylib was built for newer iOS version (10.0) than being linked (8.0) (DemoApplication.iOS) Native linking

### ISSUE THREAD

**Issue by nguyenhuutinh** [xamarin/xamarin-macios#11343]
Hello, 
I got this error when I tried to integrated our framework to Xamarin binding.

`error MT5209: Error: warning: dylib was built for newer iOS version (10.0) than being linked (8.0) (DemoApplication.iOS) Native linking`

I don't know how to recompile dylib.  do you have any suggestion?

=== Visual Studio Community 2019 for Mac ===

Version 8.9.7 (build 8)
Installation UUID: 9f4fdfa6-bb79-4fe4-a7e3-4c9dfb6c6640
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.202/Sdks
SDK Versions:
	5.0.202
	3.1.408
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.5
	3.1.14

=== .NET Core 3.1 SDK ===

SDK: 3.1.408

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Community)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/nguyenhuutinh/Library/Android/sdk
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/nguyenhuutinh/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9~2
Build date: 2021-03-24 08:30:26 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-03-24 08:30:44 UTC

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.14.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== Build Information ===

Release ID: 809070008
Git revision: 8b7ac2442978ec88d09703fafa4e43eb774f0a26
Build date: 2021-04-16 07:38:03-04
Build branch: release-8.9
Xamarin extensions: 8b7ac2442978ec88d09703fafa4e43eb774f0a26

=== Operating System ===

Mac OS X 10.16.0

**Comment by mandel-macaque** [comment]
Is there a reason you are linking against iOS 8.0, can you bump the target version.

**Comment by spouliot** [comment]
> warning: dylib was built for newer iOS version (10.0) than being linked (8.0) (DemoApplication.iOS) Native linking

This is (usually) a warning.

It will be turned into an error if there were any previous errors when doing the native linking. However without the full logs we cannot know the original error(s).

Please attach the full logs or (better) a test case we can use the duplicate and investigate the issue. Thanks!

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
