### ISSUE TITLE
Missing release notes for xamarin-ios 14.17.0.247 and 14.17.2.4 and 14.19.0.7

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-macios#11348]
Release notes are missing for xamarin-ios 14.17.0.247 and 14.17.2.4.
Which version adds support for Xcode 12.5 and iOS 14.5 (if any) ?

**Comment by dalexsoto** [comment]
Hello they should be live soon, about Xcode 12.5 support our blessed releases are the following:

* Stable release + xcode12.5 support
    * [xamarin.ios-14.16.0.5.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/xcode12.5/ab40b131d3e87a96c3414447dcded5fec45bce36/4679032/package/notarized/xamarin.ios-14.16.0.5.pkg)
    * [xamarin.mac-7.10.0.5.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/xcode12.5/ab40b131d3e87a96c3414447dcded5fec45bce36/4679032/package/notarized/xamarin.mac-7.10.0.5.pkg)

* Preview release + xcode12.5 support
    * [xamarin.ios-14.19.0.0.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/d16-10/68679309f12f271c385a8f701f70dd7be543d782/4689544/package/notarized/xamarin.ios-14.19.0.0.pkg)
    * [xamarin.mac-7.13.0.0.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/d16-10/68679309f12f271c385a8f701f70dd7be543d782/4689544/package/notarized/xamarin.mac-7.13.0.0.pkg)

These should be available via the updater in the coming days.

**Comment by samchen-g4** [comment]
Hi @dalexsoto , any idea when xamarin-ios-14.17.0.247 will be available for update? I still can't see it in the stable release.

**Comment by tranb3r** [comment]
Same question for the availability of 14.16.0.5.
Also, if xcode12.5 support is in 14.16.05, does it mean it's also in 14.17.* ?

**Comment by tranb3r** [comment]
@dalexsoto Any update ?

**Comment by tranb3r** [comment]
Now 14.19.0.7 has been published... and still no release notes for 14.16 and 14.17

**Comment by dalexsoto** [comment]
Release notes are up, sorry for the delay.
