### ISSUE TITLE
.NET: Implement support for AOT-compiling using LLVM

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#11379]
https://github.com/xamarin/xamarin-macios/blob/b4b8ee735c60bf897c87e71057fd6f2ab11206d6/tools/dotnet-linker/Steps/ComputeAOTArguments.cs#L40-L41

This should be just a matter of copying/porting whatever mtouch does when using LLVM to dotnet-linker.

**Comment by marek-safar** [comment]
Why is it conditional? I thought we discussed that only LLVM AOT will be used for net6 publishing?

**Comment by rolfbjarne** [comment]
> Why is it conditional? I thought we discussed that only LLVM AOT will be used for net6 publishing?

There's no condition, it just hasn't been implemented yet.

Although I don't see why we have to force people to use the LLVM AOT if the normal AOT they may use during debugging works for them (which doesn't mean we can't make the LLVM AOT the default).

**Comment by spouliot** [comment]
Switching to the new AOT msbuild task (part of the workload) should be done first (or at the same time).

**Comment by SamMonoRT** [comment]
@dalexsoto @rolfbjarne @spouliot - any estimate on when this can be done ?

**Comment by rolfbjarne** [comment]
@SamMonoRT I'm hoping to get this done for P7.
