### ISSUE TITLE
Xamarin iOS Importing Certificates and Profiles | Authentication service is unavailable

### ISSUE THREAD

**Issue by roylet** [xamarin/xamarin-macios#11425]
I am raising this as an issue here under recommendation from the Microsoft Support team. I have exhausted all my options here and now believe this issue could be related to the recent VS update. I understand if this is regected as a valid issue, thankyou for your time.

**The issue:**

Since a recent update with **Visual Studio Professional 2019** to **version 16.9.4**, I have had significant issues using the Automatic and/or Manual Provisioning features for Xamarin iOS development.

Following the MS tutorials for Automatic Provisioning [here ](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=windows) and [here](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/apple-account-management?tabs=windows)

We are able to get as far as signing into an Apple ID, as seen in the photo below.

![image](https://user-images.githubusercontent.com/25515720/116967172-14270a80-acf5-11eb-87bc-145d65cc288e.png)

Unfortunately, once we then proceed to “View Details” of the selected Tyeware Pty Ltd team, we are given the following error:

![image](https://user-images.githubusercontent.com/25515720/116967189-1d17dc00-acf5-11eb-939d-5fa7343b4de1.png)

Log dumps of this error:

![image](https://user-images.githubusercontent.com/25515720/116967265-40db2200-acf5-11eb-9ab5-cb7347235d55.png)

**Comment by spouliot** [comment]
This GitHub repository is for the SDK, not the IDE. We cannot help if you do not provide us with the version of the SDK you're using.

Please provide the following information (from our issue template):
```
1.
Visual Studio: Help > About Microsoft Visual Studio > Copy Info [button]
Visual Studio for Mac: Visual Studio > About Visual Studio > Show Details > Copy Information [button]
2. Paste into the code block below (between ```)
```

Whenever logs are asked please attach them as files (long) or paste them into the comments (short ones). IOW no screenshots.

Also, have you recently updated your Mac OS ? like moving to Big Sur (11.x) ?

I've hit something similar once (recently) from the Mac side (I do not use Windows). You might want to check if the same error happens on Visual Studio for Mac too.

Re-installing the (3rd party) `fastlane` tools on the Mac solved the issue for me.

**Comment by roylet** [comment]
Thankyou for your information. Your comment was the best help I've had yet. Updating to Big Sur seems to have fixed the issue.
