### ISSUE TITLE
[dotnet] Support interpreter-only mode in the simulator

### ISSUE THREAD

**Issue by lambdageek** [xamarin/xamarin-macios#11421]
For .NET 6 hot reload to work, and for other scenarios, we need to be able to run apps using the interpreter on the simulator.

Currently calling the following code from `AppDelegate.FinishedLaunching` returns "JIT"

```csharp
using System.Runtime.CompilerServices;

public string GetExecutionMode()
{
  if (!RuntimeFeature.IsDynamicCodeSupported)
    return "AOT";
  if (RutnimeFeature.IsDynamicCodeCompiled)
    return "JIT";
  return "Interpreter";
}
```

**Comment by spouliot** [comment]
`Application.mtouch.cs` is only used for `mtouch`, which is not used for dotnet (only legacy)

Are you seeing the MT0141 error ?

**Comment by lambdageek** [comment]
One way to test whether the interpreter is enabled is using

```
using System.Runtime.CompilerServices;

public string GetExecutionMode()
{
  if (!RuntimeFeature.IsDynamicCodeSupported)
    return "AOT";
  if (!RutnimeFeature.IsDynamicCodeCompiled)
    return "JIT";
  return "Interpreter";
}
```

This test could be adjusted to (a) run, not just build; (b) try to use the above method to detect the execution engine.

https://github.com/xamarin/xamarin-macios/blob/5c12fdfac92277cd19cb4c73daa083ddc75d781b/tests/dotnet/MyInterpretedApp/MyInterpretedApp.csproj

**Comment by spouliot** [comment]
>  (a) run, not just build

No, those projects don't have a way to communicate success/failure back to the runner. They exists so the tooling, like `msbuild` can be verified, or to check for files expected presence (or absence), app bundle size...

Even if we added a success/failure execution report on run it would not tell us much. The interpreter could be enabled but could be crashing in various places that not part of the simple app.

To achieve more useful results we run existing unit tests under several configurations, including the interpreter (at least for legacy). That validates the build **and** that the feature works across a large set of tests.

If would be easy to add a dotnet specific test for `RuntimeFeature` so we know it returns the expected values under the different build configuration.

**Comment by spouliot** [comment]
Example from xharness: All configurations of monotouch-test for `iOS Unified 64-bits - device`

```
iOS Unified 64-bits - device (Ignored)Run all Build all
+AssemblyBuildTarget: dylib (debug) (Ignored) Run Build
+AssemblyBuildTarget: dylib (debug) [dotnet] (Ignored) Run Build
+AssemblyBuildTarget: dylib (debug, profiling) (Ignored) Run Build
+AssemblyBuildTarget: dylib (debug, profiling) [dotnet] (Ignored) Run Build
+AssemblyBuildTarget: SDK framework (debug) (Ignored) Run Build
+AssemblyBuildTarget: SDK framework (debug) [dotnet] (Ignored) Run Build
+AssemblyBuildTarget: SDK framework (debug, profiling) (Ignored) Run Build
+AssemblyBuildTarget: SDK framework (debug, profiling) [dotnet] (Ignored) Run Build
+AssemblyBuildTarget: SDK framework (release) (Ignored) Run Build
+AssemblyBuildTarget: SDK framework (release) [dotnet] (Ignored) Run Build
+Debug (Ignored) Run Build
+Debug (all optimizations) (Ignored) Run Build
+Debug (all optimizations) [dotnet] (Ignored) Run Build
+Debug (dynamic registrar) (Ignored) Run Build
+Debug (dynamic registrar) [dotnet] (Ignored) Run Build
+Debug (interpreter -mscorlib) (Ignored) Run Build
+Debug (interpreter -mscorlib) [dotnet] (Ignored) Run Build
+Debug (interpreter) (Ignored) Run Build
+Debug (interpreter) [dotnet] (Ignored) Run Build
+Debug [dotnet] (Ignored) Run Build
+Debug: SGenConc (Ignored) Run Build
+Debug: SGenConc [dotnet] (Ignored) Run Build
+Release (Ignored) Run Build
+Release (all optimizations) (Ignored) Run Build
+Release (all optimizations) [dotnet] (Ignored) Run Build
+Release (interpreter -mscorlib) (Ignored) Run Build
+Release (interpreter -mscorlib) [dotnet] (Ignored) Run Build
+Release [dotnet] (Ignored) Run Build
```

**Comment by lambdageek** [comment]
> `Application.mtouch.cs` is only used for `mtouch`, which is not used for dotnet (only legacy)
> 
> Are you seeing the MT0141 error ?

No I'm not.  I guess it must be something else that is affecting the execution engine choice.  Sorry. let me update the PR description with just the observable behavior and not my guesses.

**Comment by lambdageek** [comment]
Hmm... I have a sneaking suspicion that this is due to `MONO_AOT_MODE_INTERP`

https://github.com/xamarin/xamarin-macios/blob/b720b4482736b784105385bcf23f86dcb1d0c28a/tools/common/Target.cs#L764

I think that (as opposed to `MONO_AOT_MODE_INTERP_ONLY`) means "use interpreter as the fallback execution engine".  which on simulator (since we're using the JIT) means "try to jit if it fails (it won't), use interpreter".

The mono tests in dotnet/runtime [use `MONO_AOT_MODE_INTERP_ONLY`](https://github.com/dotnet/runtime/blob/b491d634bb793447bf0dbe87eb70a03c4e75bbe1/src/tasks/AppleAppBuilder/Templates/runtime.m#L265).

I'm going to try changing the runtime tests to use `MONO_AOT_MODE_INTERP` and check what behavior we get there.

**Comment by lambdageek** [comment]
So the problem is: we have 3 different execution engins in the simulator that we can use, and they don't really map cleanly onto the two available MSBuild properties.

Execution engines: AOT, Interpreter, JIT.
MSBuild properties: `MtouchInterpreter`, `UseInterpreter`.

Currently both properties mean the same thing.  

What they mean:

- On device (no JIT available): Use AOT if methods are compilable with FullAOT, otherwise fall back to Interpreter.
- On simulator: Use JIT if methods are JITable (all methods are JITable), otherwise fall back to interpreter.

What we really need is:

- On simulator: Disable JIT.  Use AOT if methods are compilable with FullAOT, otherwise fall back to interpreter.

As far as I know, we don't have an option in the runtime to disable the JIT at runtime (we can disable it as part of building the runtime -that's what the devices do).

I think as a first step, we should support "interpreter-only" mode on the simulator.  Never use JIT or AOT, force use of the interpreter.  (For the runtime, the right invocation is `mono_jit_set_aot_mode (MONO_AOT_MODE_INTERP_ONLY)`, as I mentioned https://github.com/xamarin/xamarin-macios/issues/11421#issuecomment-831378147).

What if `<UseInterpreter>true</UseInterpreter>` on net6 used  "interpreter-only" mode.  That would match Xamarin.Android behavior.

**Comment by lambdageek** [comment]
> I think that [`MONO_AOT_MODE_INTERP`]  (as opposed to MONO_AOT_MODE_INTERP_ONLY) means "use interpreter as the fallback execution engine". which on simulator (since we're using the JIT) means "try to JIT; if it fails (it won't), use interpreter".

Hmm... actually I don't know that this is correct.  I think it's possible the `IsDynamicCodeSupported/Compiled` intrinsics might not be telling me the right things.  Need to check some actual dynamic code and see if it's JITed or interpreted

**Comment by lambdageek** [comment]
So here's what needs to happen to get the interpreter working on iOS simulator:

1. We need to compile at least `System.Private.CoreLib.dll` with `mono --aot=interp` and make the resulting aot image available to the runtime.  It's ok to AOT other assemblies with `--aot=interp`, but it's not necessary.  the S.P.C AOT image contains all the necessary interpreter trampolines that we care about.
2. Runtime should start with `MONO_AOT_MODE_INTERP` (as it does now).

On iOSSimulator-arm64 we will run into W^X issues until a runtime pack that includes https://github.com/dotnet/runtime/pull/53197 is used  (I think .NET 6 Preview 6), but iOSSimulator-x64 should be ok now.

@spouliot I think the steps above are similar to what is used for the interpreter on ios devices (although maybe it uses `mono --aot=interp,full`, not `mono --aot=interp`) do you know what is the best way to fix enable the interp for the simulators too?
