### ISSUE TITLE
CoreCLR: add support for crash dumps

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#11432]
When CoreCLR crashes, it will try to execute a `createdump` executable to create a crash dump.

Currently CoreCLR expects the `createdump` executable to be located in the Contents/MonoBundle app directory (because that's where libcoreclr.dylib is located):

https://github.com/dotnet/runtime/blob/0761780988b93a4d1cc98dc5d4e2d84db29e33fd/src/coreclr/pal/src/thread/process.cpp#L3111-L3134

We need to bundle the `createdump` executable if we want to support crash dumps.

**Comment by kdubau** [comment]
@rolfbjarne @dalexsoto can we get this in preview 7?

**Comment by rolfbjarne** [comment]
I can try, it's either quite simple and fast to implement, or not at all.  Hopefully the former 😄
