### ISSUE TITLE
[hotrestart] Debug on device fails: Could not load file or assembly 'iSign.Core

### ISSUE THREAD

**Issue by tristanovic** [xamarin/xamarin-macios#11441]
### Steps to Reproduce

1. try to debug on iOS device. 

### Expected Behavior
App builds and deploys to iPhone 

### Actual Behavior
Error is thrown: Error running hotrestart: 'An error occurred while signing the application 'CrystalFX.app'. Details: Could not load file or assembly 'iSign.Core, Version=1.0.0.0

### Environment
```
Microsoft Visual Studio Enterprise 2019
Version 16.9.4
VisualStudio.16.Release/16.9.4+31205.134
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.693.2781
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.693.2781
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.693.2781
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.693.2781
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40331.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62103.10080
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.273 (d16-9@1bba9e0)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.318 (remotes/origin/7b35adcdd1b204bbdcb279e0f029d151a20a4bf3@7b35adcdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.72 (426ebf6)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.2.1 (d16-9/877f572)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@54f8c24
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11


Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

Apple Support - iTunes installed: 'True', Installation type: 'Store'
1>Starting deploy 'BLE.CrystalFocus.iOS' into the device 'iPhone van tristan'...
1>Deploying 'CrystalFX.app' into the device 'iPhone van tristan'...
Deploying app...
An error occurred while trying to deploy the app 'CrystalFX.app'. Details: Error running hotrestart: 'An error occurred while deploying the application 'CrystalFX.app' into 'iPhone van tristan'. Details: Could not find an app bundle at: C:\Users\TristanKam\AppData\Local\Temp\Xamarin\HotRestart\Signing\CrystalFX.app\out\Payload'. Command: 'deploy -u=a8eb41b0b90483b4df96a41b7a31cd9f92aa5b87 -i=com.crystalfocus.ble -n=CrystalFX.app'
1>Deploy failed. The app 'CrystalFX.app' could not be deployed to the device 'iPhone van tristan'. Please check the logs for more details.
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========

![image](https://user-images.githubusercontent.com/26849528/117114685-754ded00-ad8c-11eb-8611-9d8e2b1c2a5d.png)

### Example Project (If Possible)

> VS bug [#1323855](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1323855)

**Comment by spouliot** [comment]
> Error running hotrestart

Have you tried to disable hot restart ? There are special requirement for this to work and those might only be set properly when you're using the simulator.

If it does not work, without hot-restart, then we'll need a test case to investigate.

**Comment by tristanovic** [comment]
I haven't been using the simulator because this is a BLE project and I need the device. I've been using my iPhone for weeks now to debug but it just stopped. I tried disabling Hot restart but this didn't work. 

How can I provide a test case?

**Comment by spouliot** [comment]
> Error running hotrestart

^ does the following message still show when deploying ?

> How can I provide a test case?

Zip a test case (or a subset of your project) that shows the issue. Drag the zip archive into the comment text box. It will be uploaded to GitHub and we'lll be able to use it to reproduce the issue.

**Comment by tristanovic** [comment]
Without hotrestart (and thus deploying to a simulator) this error isn't there. 
Can build the app on a paired Mac through 'Remote device' without issues
Cannot deploy to iPhone ==> Error running hotrestart

**Comment by tristanovic** [comment]
[App3.zip](https://github.com/xamarin/xamarin-macios/files/6429828/App3.zip)

issue also occurs with default xamarin app template

**Comment by spouliot** [comment]
> Cannot deploy to iPhone ==> Error running hotrestart

That's because HotRestart is not disabled. Your attached sample starts fine with me on device.

HotRestart is currently Windows only and change how build are deployed to device. I'm transferring this issue to the XVS team, which handles HotRestart.

> issue also occurs with default xamarin app template

Same, your problem seems to be with hot-restart

**Comment by tristanovic** [comment]
agreed: the problem is with hot-restart. The project itself builds without issues. it's hot-restart that gives issues. Can I debug on device without hot-restart or how can I solve this issue?

**Comment by tristanovic** [comment]
I tried a Visual studio installer 'repair' which did not resolve the issue.
I tried a full deinstallation and reinstall which did resolve the issue. I am now able to debug using hot-restart again
