### ISSUE TITLE
[.NET 6] Linker may not preserve exported methods with overrides

### ISSUE THREAD

**Issue by sbomer** [xamarin/xamarin-macios#11449]
This check for overrides happens before MarkStep, when the linker has not built type hierarchy info. Even when this changes to run during MarkStep with https://github.com/xamarin/xamarin-macios/pull/11374, there is no guarantee that the override info will be complete, so it will likely neglect to preserve some exported methods that have overrides which aren't discovered yet.

https://github.com/xamarin/xamarin-macios/blob/50b68d4aab0a1099113a68c04aad5a77592b6e52/tools/linker/MarkNSObjects.cs#L84-L91

It seems like this could be changed to walk up the type hierarchy instead (though this would require looking at base methods for many unannotated methods), or it could be cached as part of some custom type map logic that pre-loads assemblies as mentioned in https://github.com/xamarin/xamarin-macios/issues/11447. (I am filing this as a separate issue because it seems like a correctness concern, not just a perf optimization).

**Comment by spouliot** [comment]
iirc that has been fixed a while ago, at least since 045ccaf3a6ac9759eb9166fb01815b0e49f981ef
@sbomer what there anything missing ?

**Comment by sbomer** [comment]
Yup, this was fixed in that change. CoreTypeMapStep now builds the type hierarchy info before this override check.
