### ISSUE TITLE
[dotnet] Missing `mono-cil-strip` (or alternative)

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#11445]
Release builds should strip all IL from assemblies (the one that were AOT'ed) to minimize the final app bundle size.

This is done using `mono-cil-strip` for the legacy SDK. However this tools ships with the Mono SDK and there is not, so far, a package (or an alternative tool) to achieve the same for dotnet SDK.

**Comment by spouliot** [comment]
c.c. @marek-safar

**Comment by marek-safar** [comment]
Yep, it's going to be part of the runtime provided AOT tooling.

/cc @lewing

**Comment by steveisok** [comment]
@marek-safar was the thinking we would get this tool ported out of wasm?  I asked @lewing about it and it's low priority for him.

**Comment by steveisok** [comment]
This is something my team will handle.  Will need a little bit of time

**Comment by akoeplinger** [comment]
@rolfbjarne @spouliot this is available now: https://github.com/dotnet/runtime/pull/57359

**Comment by rolfbjarne** [comment]
@akoeplinger it seems to use the latest version of Cecil, and iirc the reason we were never able to use a newer version of Cecil was that newer versions would change the metadata tokens when writing out the stripped assembly, and that broke us. Is that not an issue anymore?

**Comment by akoeplinger** [comment]
@rolfbjarne it does not use the latest version of Cecil, it embeds the old Cecil into the assembly until we can finish the rewrite on top of System.Reflection.Metadata.
