### ISSUE TITLE
[msbuild] `SdkIsSimulator` is out-dated (arch based)

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#11450]
> msbuild/Xamarin.iOS.Tasks.Core/Tasks/DetectSdkLocationsTaskBase.cs

```csharp
SdkIsSimulator = (architectures & (TargetArchitecture.i386 | TargetArchitecture.x86_64)) != 0;
```

`arm64` is now a valid simulator architecture for simulators.

That affect both legacy and dotnet based SDK.

**Comment by rolfbjarne** [comment]
This was fixed in fc14243c179487438717583c048fdc49845a2288 for .NET.
