### ISSUE TITLE
[macOS] --timestamp=none is added to codesign even if UseHardenedRuntime is true

### ISSUE THREAD

**Issue by nor0x** [xamarin/xamarin-macios#11562]
i'm building a Xamarin.Mac application and have some issues with notarization. As far as i can tell from the source code `UseHardenedRuntime` should control the `--timestamp` flag of the `codesign` command. In my case `--timestamp=none` is added all the time, no matter what value is set for `UseHardenedRuntime`

i tried setting additional arguments for `codesign` via `CodeSignExtraArgs` - which failed because i already had an additional flag here (`--deep`) and it seems that more values here are passed to `codesign` with quotation marks (e.g. `/usr/bin/codesign some values "--deep --timestamp"`) which causes the task command to fail.

### Steps to Reproduce

1. Create Xamarin.Mac App
2. set UseHardenedRuntime to `true`
3. inspect build log for Task `Codesign`

### Expected Behavior

- timestamp flag should respect value of `UseHardenedRuntime`.  `--timestamp=none` should not be added automatically
- users should be able to pass multiple arguments (for example `--deep` AND `--timestamp`) to `CodeSignExtraArgs`

### Actual Behavior
`--timestamp=none` flag is passed to `codesign` all the time - which causes various errors during the apple notarization process:
```
{
      "severity": "error",
      "code": null,
      "path": "MyApp.app.zip/MyApp.app/Contents/MonoBundle/libMonoPosixHelper.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
},
{
      "severity": "error",
      "code": null,
      "path": "MyApp.app.zip/MyApp.app/Contents/MonoBundle/libmono-native.dylib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": null,
      "architecture": "x86_64"
},
```

### Environment

<details>
  <summary>Visual Studio Information</summary>
  

```
=== Visual Studio Community 2019 for Mac ===

Version 8.9.9 (build 3)
Installation UUID: 0898c2fd-30ff-4910-88e9-78dc2a774243
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/6.0.100-preview.3.21202.5/Sdks
SDK Versions:
	6.0.100-preview.3.21202.5
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0-preview.3.21201.4
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11

=== .NET Core 3.1 SDK ===

SDK: 3.1.409

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Community)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/johnny/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/johnny/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/dev/bretjohn/readme-tweak~3
Build date: 2021-04-21 21:23:40 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-04-21 21:23:58 UTC

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Version: 7.10.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:41-0400

=== Xamarin.iOS ===

Version: 14.16.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:42-0400

=== Build Information ===

Release ID: 809090003
Git revision: 163d834aa64ba9129e5ef30e49a947ef67bcd809
Build date: 2021-05-06 10:14:43-04
Build branch: release-8.9
Xamarin extensions: 163d834aa64ba9129e5ef30e49a947ef67bcd809

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Thu Apr 22 21:46:47 PDT 2021
    root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

```
</details>

### Build Logs

[log.txt](https://github.com/xamarin/xamarin-macios/files/6479406/log.txt)

### Example Project (If Possible)
https://github.com/nor0x/repro-XF-10789/blob/master/repro.macOS/repro.macOS.csproj

**Comment by spouliot** [comment]
That should be the case

```
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets:                     UseHardenedRuntime="$(UseHardenedRuntime)"
msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets:                     UseSecureTimestamp="$(UseHardenedRuntime)"
```

`--timestamp` is present two times in the logs

```
    Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp --sign 50A3178A9E562E2850A3DD38C2C3C821E650FE2E --timestamp=none /Users/johnny/Desktop/repro-XF-10789-master/repro.macOS/bin/Debug/repro.macOS.app/Contents/MonoBundle/libmono-native.dylib
            
    Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp --sign 50A3178A9E562E2850A3DD38C2C3C821E650FE2E --timestamp=none /Users/johnny/Desktop/repro-XF-10789-master/repro.macOS/bin/Debug/repro.macOS.app/Contents/MonoBundle/libMonoPosixHelper.dylib
```

and that should not be possible since https://github.com/xamarin/xamarin-macios/pull/10428

> === Xamarin.Mac ===
> Version: 7.10.0.5 (Visual Studio Community)

but you'll need a newer (preview) XM to get that fix

>  main (#10428)
> xamarin-mac-7.13.0.7  xamarin-mac-7.11.2.4 xamarin-mac-7.11.0.247 xamarin-ios-14.19.0.7 xamarin-ios-14.17.2.4 xamarin-ios-14.17.0.247

(from github's commit)

**Comment by nor0x** [comment]
thanks for the reply @spouliot! i know that `--timestamp` is present two times. my question actually was how the second `--timestamp=none` ends up in the command?

**Comment by spouliot** [comment]
It's a bug that was introduced when we merged the XI and XM CodeSign tasks as a single one.

The required checks were different (there's no hardened runtime in iOS) and both were put in the shared implementation, which meant it could be present twice (with different options) when calling `codesign`.

**Comment by nor0x** [comment]
one more question @spouliot - this fix will be in Xamarin.Mac 7.10.* and above, right?
i'm asking because https://github.com/actions/virtual-environments/issues/2486 currently doesn't allow us building with Xcode 12.5 on our CI/CD pipeline
