### ISSUE TITLE
Ship System.ServiceModel.Discovery.dll in Xamarin Mac SDK

### ISSUE THREAD

**Issue by KirillOsenkov** [xamarin/xamarin-macios#11568]
Mono ships System.ServiceModel.dll and System.ServiceModel.Discovery.dll in the GAC:

```
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/gac/System.ServiceModel/4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/gac/System.ServiceModel.Discovery/4.0.0.0__31bf3856ad364e35/System.ServiceModel.Discovery.dll
```

Xamarin Mac ships System.ServiceModel.dll here:
```
/Library/Frameworks/Xamarin.Mac.framework/Versions/7.11.2.6/lib/mono/4.5/System.ServiceModel.dll
```

and I don't see that it ships System.ServiceModel.Discovery.dll anywhere. Also the versions are different.

We may run into a problem where the .dlls are mismatched. I think Xamarin.Mac should ship both .dlls of matching versions.

FYI @spouliot

**Comment by akoeplinger** [comment]
I talked to @KirillOsenkov offline and it turns out that System.ServiceModel.Discovery.dll was pulled in by some dependency that's not actually used and can be removed which means we don't need to do anything here :)
