### ISSUE TITLE
watchOS complication not showing

### ISSUE THREAD

**Issue by tim162** [xamarin/xamarin-macios#11576]
Hi everyone! I've created a watch app for my Xamarin app and successfully deployed it to an Apple Watch. Now I want to add a complication that shows important data on a watch face. I followed the [Xamarin tutorial](https://docs.microsoft.com/en-us/xamarin/ios/watchos/platform/complications) and also Apples documentation on watch complications.

I can still deploy and run the watch app on my watch but the complication is just not shown as a complication to be selected on a watchface.

I created a dummy project in Xcode with a complication and Xcode has the complication as a scheme to start the watch app. The watch app is deployed to my watch and I can select the complication from the watchface directly or from the "Watch" app on the connected iPhone.
![Bildschirmfoto 2021-05-17 um 15 05 39](https://user-images.githubusercontent.com/54797204/118493480-72a2ae80-b721-11eb-97cc-f7808933bcfa.png)

I tried the same with a dummy project using Xamarin and Visual Studio.
![Bildschirmfoto 2021-05-17 um 14 59 36](https://user-images.githubusercontent.com/54797204/118495188-3ff9b580-b723-11eb-8ec5-f5fa0ae884e9.png)
I selected/edited everything according to the Xamarin documentation, deploying to the watch works but the complications isn't shown anywhere on the watch or "Watch" app on the iPhone. Is there something missing in the documentation on how one can start the watch app according to the complication scheme provided by Xcode? Or is this a bug/incompatibility?

**Long story short**: With a dummy project using Xcode the complication is working and the same using Xamarin is not. The documentation/SO does not provide any help on this.

iPhone 12 @ iOS 14.5.1
with Apple Watch series 4 @ watchOS 7.4.1

### Steps to Reproduce

1. Create a new WatchKit project and select "Include complication"
2. Edit WatchKit Extensions Info.plist: Select complication families, create complication asset and set under "Complications Group", create ComplicationController.cs and set as "Data Source Class"
3. Deploy watch app to physical Apple Watch

### Expected Behavior

Complication can be selected directly from watchface and/or Watch app on connected iPhone

### Actual Behavior

Complication is not shown anywhere and can't be selected on a watchface

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.9.8 (build 7)
Installation UUID: ffecd889-50ee-4c42-8f33-1165f685f3f8
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.202/Sdks
SDK Versions:
	5.0.202
	5.0.201
	3.1.408
	3.1.407
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.5
	5.0.4
	3.1.14
	3.1.13

=== .NET Core 3.1 SDK ===

SDK: 3.1.408

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.16.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:42-0400

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Community)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/blurrr/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.0
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/blurrr/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/dev/bretjohn/readme-tweak~3
Build date: 2021-04-21 21:23:40 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-04-21 21:23:58 UTC

=== Build Information ===

Release ID: 809080007
Git revision: 85b793ce322599fe423c2d233c346b13824ca4d8
Build date: 2021-04-28 12:54:34-04
Build branch: release-8.9
Xamarin extensions: 85b793ce322599fe423c2d233c346b13824ca4d8

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

**Comment by spouliot** [comment]
I just followed the tutorial and I can see the complication listed in iOS "Watch" app.

Please attach a test case and I can have a quick look to see differences between your version and mine.

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
