### ISSUE TITLE
Xamarin iOS Issue : iOS Code Signing Key 'iOS Distribution : ABCD Pte. Ltd' not found in KeyChain"

### ISSUE THREAD

**Issue by myintkyaw** [xamarin/xamarin-macios#11572]
Hi,

I am doing the In-House Distribution for my Xamarin iOS project.

I connected from my Window VS to MacBook to build and publish .ipa file.

In MacBook, Certificates and Provision Profiles are already installed.

When I build my Application i got this error "iOS Code Signing Key 'iOS Distribution : ABCD Pte. Ltd' not found in KeyChain".

Does anybody have this issue lately and how it is resolved?

Appreciate your helps. Thanks

**Comment by overzealus** [comment]
I have the same issue.
I have created certificate through XCode preferences, I can select it in Visual Studio for Windows when Mac is connected, but when I try to build, I have this error too.

**Comment by myintkyaw** [comment]
Now i tried to build the Xamarin Project in VS on MAC instead of using VS Window connecting to OS.

Then, .ipa file is published. Anyhow i can build without any issue now in VS on MAC.
