### ISSUE TITLE
MM0179 String.Format failed!

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#11589]
### Steps to Reproduce

On one of my pipelines on DevDiv, I get an exception that is badly formatted:
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4746157&view=logs&j=33aecc80-6b4d-52ff-7ba1-783304fd5eb7&t=f65a3d5e-cfee-5b24-83c3-81cfc85b7b66&l=3437

### Actual Behavior

> MMP : error MM0179: This version of {0} requires the {1} {2} SDK (shipped with Xcode {3}). Either upgrade Xcode to get the required header files or use the dynamic registrar or set the managed linker behaviour to Link Platform or Link Framework SDKs Only in your project's Mac Build Options > Linker Behavior} (to try to avoid the new APIs).. String.Format failed! Arguments were: "Xamarin.Mac" "macOS" "11.3" "12.5". Please file an issue to report this incorrect error handling

### Environment

```
```

**Comment by spouliot** [comment]
I searched for MM0179, not MX (shared), but it just sounded too familiar.

https://github.com/xamarin/xamarin-macios/pull/11509
