### ISSUE TITLE
[Mac OS ]The App Extension '{0}' has a CFBundleVersion ({1}) that does not match the main app bundle's CFBundleVersion ({2})

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#11581]
Moving from an original feedback issue: https://developercommunity.visualstudio.com/t/The-App-Extension-0-has-a-CFBundleVe/1367521

> Xamarin.iOS.Common.targets fails with "The App Extension '{0}' has a CFBundleVersion ({1}) that does not match the main app bundle's CFBundleVersion ({2})”
> 
> I’ve checked all my versions and can’t find the problem. Would be helpful to know which extensions and which versions it’s failing with.
> 
> 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(926,3): warning : "The App Extension '{0}' has a CFBundleVersion ({1}) that does not match the main app bundle's CFBundleVersion ({2})
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(926,3): warning : "
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(926,3): warning : System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(926,3): warning : at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x003da] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Text/StringBuilder.cs:1637 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(926,3): warning : at System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x0000e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/String.Manipulation.cs:471 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(926,3): warning : at System.String.Format (System.IFormatProvider provider, System.String format, System.Object[] args) [0x00018] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/String.Manipulation.cs:463 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(926,3): warning : at Microsoft.Build.Framework.LazyFormattedBuildEventArgs.FormatString (System.Globalization.CultureInfo culture, System.String unformatted, System.Object[] args) [0x00009] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Framework/LazyFormattedBuildEventArgs.cs:258 
> 18 Warning(s)
> 0 Error(s)

## Environment

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.9.4 (build 25)
Installation UUID: a0228d75-a329-463d-8cee-002707bf0f30
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

Package version: 612000125
=== Mono Framework MDK ===

Runtime:
Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.201/Sdks
SDK Versions:
5.0.201
5.0.102
5.0.100
3.1.407
3.1.405
3.1.403
3.1.402
3.1.300
3.1.200
3.1.102
3.1.101
3.1.100
3.0.100
2.2.203
2.2.103
2.1.302
2.0.3
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
6.0.0-preview.2.21154.6
5.0.4
5.0.2
5.0.0
3.1.13
3.1.11
3.1.9
3.1.8
3.1.4
3.1.2
3.1.1
3.1.0
3.0.0
2.2.4
2.2.1
2.1.23
2.1.22
2.1.21
2.1.20
2.1.18
2.1.17
2.1.16
2.1.15
2.1.13
2.1.2
2.0.3

=== .NET Core 3.1 SDK ===

SDK: 3.1.407

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.8.2.5 (Visual Studio Enterprise)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

=== Xamarin.iOS ===

Version: 14.14.2.5 (Visual Studio Enterprise)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

=== Xamarin Designer ===

Version: 16.9.0.316
Hash: 2241b204a
Branch: tags/vsm-rel/d16.9-4540908
Build date: 2021-03-10 21:18:10 UTC

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Enterprise)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/fak/Library/Developer/Xamarin/android-sdk-macosx
Supported Android versions:
7.0 (API level 24)
7.1 (API level 25)
8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information:
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/fak/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9~2
Build date: 2021-03-24 08:30:26 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-03-24 08:30:44 UTC

=== Build Information ===

Release ID: 809040025
Git revision: 5d0f80a4343884101c6c7869bc61d5101cf30052
Build date: 2021-03-25 08:43:13-04
Build branch: release-8.9
Xamarin extensions: 5d0f80a4343884101c6c7869bc61d5101cf30052

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
Thu Jan 21 00:07:06 PST 2021
root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Meadow 0.7.9.1
AddinMaker 1.6.0
Build Light 0.5
MSBuild Editor 2.4.0

This looked like an issue with the translations but also with the comparison since numbers match as per the user comments:

> I realize the translation is messing up, but, more importantly, my bundle versions match so please check that logic.

I did confirm the issue with main.

**Comment by spouliot** [comment]
current code

```CSharp
if (DeploymentTarget != null) {
	if (DeploymentTarget < SdkVersions.GetMinVersion (this))
		throw new ProductException (73, true, Errors.MT0073, ProductConstants.Version, DeploymentTarget, Xamarin.SdkVersions.GetMinVersion (this), PlatformName, ProductName);
```

https://github.com/xamarin/xamarin-macios/pull/8106/files

```diff
- Log.LogWarning ("The App Extension '{0}' has an unrecognized NSExtensionPointIdentifier value ('{1}').", name, extensionPointIdentifier);				
+ Log.LogWarning (MSBStrings.W0073, name, extensionPointIdentifier);
```

https://github.com/xamarin/xamarin-macios/pull/8106/files#diff-8363208a7f790a86cc604eace0fa9fd10bb8fe6f37b8a0bf49d9f7f4e6062d9bL159-R160

```diff
if (version != mainVersion)
- 	Log.LogWarning ("The App Extension '{0}' has a CFBundleVersion ({1}) that does not match the main app bundle's CFBundleVersion ({2})", name, version, mainVersion);
+ 	Log.LogWarning (MSBStrings.W0073, name, version, mainVersion);
```

https://github.com/xamarin/xamarin-macios/pull/8106/files#diff-8363208a7f790a86cc604eace0fa9fd10bb8fe6f37b8a0bf49d9f7f4e6062d9bL78-R79

**Comment by spouliot** [comment]
For the above error to be triggered it would seem the "new" (as in additional) `W0073` is being hit - showing (well trying to) an incorrect message.

**Comment by spouliot** [comment]
Should have been `W0074`
