### ISSUE TITLE
Unable to fetch GPS data when the device is in offline mode(no internet connection)

### ISSUE THREAD

**Issue by ataparia** [xamarin/xamarin-macios#11606]
### Steps to Reproduce

1. Create a sample project to get GPS Location using CLLocationManager class. 
2. Follow the sample from this link - https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/location-walkthrough

### Expected Behavior
App should be able to retrieve GPS data even though the device doesn't have network connectivity as the device has inbuilt GPS chip that doesnt depend on network to collect GPS data.

### Actual Behavior
App cannot collect GPS data as "LocationsUpdated" event on CLLocationManager class instance doesn't fire when network connectivity is not available.

### Environment
=== Visual Studio Community 2019 for Mac ===

Version 8.9.7 (build 8)
Installation UUID: 44083446-0896-454c-a1bc-46de726e3079
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.202/Sdks
SDK Versions:
	5.0.202
	5.0.102
	5.0.100
	3.1.408
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.102
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.302
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.5
	5.0.2
	5.0.0
	3.1.14
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.2
	3.0.0
	2.1.23
	2.1.22
	2.1.15
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.2

=== .NET Core 3.1 SDK ===

SDK: 3.1.408

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.8.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

=== Xamarin.iOS ===

Version: 14.14.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Community)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/ataparia/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/ataparia/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9~2
Build date: 2021-03-24 08:30:26 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-03-24 08:30:44 UTC

=== Build Information ===

Release ID: 809070008
Git revision: 8b7ac2442978ec88d09703fafa4e43eb774f0a26
Build date: 2021-04-16 07:38:03-04
Build branch: release-8.9
Xamarin extensions: 8b7ac2442978ec88d09703fafa4e43eb774f0a26

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

### Example Project (If Possible)
[LocationMonkey.zip](https://github.com/xamarin/xamarin-macios/files/6504567/LocationMonkey.zip)

**Comment by spouliot** [comment]
Xamarin.iOS provides _bindings_ to Apple API. Those bindings are not aware of your internet connection status. 

IOW it's up to Apple API to return any data, _when possible_, and Apple is aware of your cellular/wifi connection.

Availability of GSP data really depends on the device. Some have A-GPS (assisted GPS) that needs cellular help to bootstrap the process. There are also other optimizations that allows additional accuracy (and speed) when the cellular antenna is powered. Being indoor can also block (some, most or all) GPS signal. You might not be noticed this if cellular/wifi is enabled as it can act as a second source of location data. After all it's called `CLLocationManager` not `GPSLocationManager` :-)
