### ISSUE TITLE
[Xamarin.Mac] Unable to do signed build from command line, but can from within Visual Studio Mac

### ISSUE THREAD

**Issue by projectgoav** [xamarin/xamarin-macios#11633]
Our cloud build provider recently updated their version of VSMac and suddenly our Xamarin.Mac application would no longer build. 

On further inspection, we can do signed builds from inside VSMac, but not from the command line. Any build from the cmdline fails with the following error:

```
"solution.sln" (Build target) (1) ->
"solution/project.csproj" (default target) (2) ->
(_CoreArchive target) -> 
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(344,3): error : The task Archive requires TargetFrameworkMoniker to be set. [solution/project.csproj]
```
Our cloud builds operate on VSMac Version ID: 809001651.

I have also been able to reproduce this with the latest VS Mac installed on my machine. Details below. 

### Steps to Reproduce

Working: 
- Open project in VS Mac
- Change to a configuration that creates a signed build
- Right-click -> Build, wait
- Application successfully built and signed.

Command line:
- Navigate to solution directory
- ` /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild ./Solution.sln /p:Configuration=AdHoc "/p:Platform=Any CPU" /p:ArchiveOnBuild=true`
    **NOTE**: AdHoc is a configuration we've setup for a signed build.
- Build fails: `/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(344,3): error : The task Archive requires TargetFrameworkMoniker to be set.`

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.9.10 (build 4)
Installation UUID: 9bfbfd14-2ce7-4a06-873b-32fab4602feb
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.203/Sdks
SDK Versions:
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.101
	5.0.100
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.404
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.200
	3.1.102
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.1
	5.0.0
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.10
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.2
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0

=== .NET Core 3.1 SDK ===

SDK: 3.1.409

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Version: 7.10.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:41-0400

=== Xamarin.iOS ===

Version: 14.16.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:42-0400

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Community)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/ewan/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/ewan/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/dev/bretjohn/readme-tweak~3
Build date: 2021-05-13 17:03:56 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-05-13 17:04:12 UTC

=== Build Information ===

Release ID: 809100004
Git revision: 30612572b7defb0273729cb6b5ea5adc8bd9a147
Build date: 2021-05-13 13:06:24-04
Build branch: release-8.9
Xamarin extensions: 30612572b7defb0273729cb6b5ea5adc8bd9a147

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Thu Apr 22 21:46:47 PDT 2021
    root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
```

### Build Logs

[CmdlineBuild-Detailed.txt](https://github.com/xamarin/xamarin-macios/files/6514951/CmdlineBuild-Detailed.txt)

[VSMacBuild-Detailed.txt](https://github.com/xamarin/xamarin-macios/files/6514952/VSMacBuild-Detailed.txt)

Our project is pretty big and the diagnostic output is very large. If you require this then please let me know and I'll work out some way to send these over to you. 

### Example Project (If Possible)

@rolfbjarne should still have read access to our repo from a previous issue we reported. If required, please let me know.

**Comment by spouliot** [comment]
That seems to work fine for me with `main`, I'll try with the exact same XM version (VSfM is already identical).

Have you tried to remove `"/p:Platform=Any CPU"` ? It's not defined for all projects (and was not for mine).

**Comment by projectgoav** [comment]
No difference unfortunately.

**Comment by projectgoav** [comment]
In case it is helpful - we use Bitrise. 

Their "Previous" image works fine. That is VSfM ID: 808070018 
Stack details: https://github.com/bitrise-io/bitrise.io/blob/447263d971b6cfc9ac56b07f8cbb633611111850/system_reports/osx-vs4mac-previous-stable.log#L1032

The new image brought this to our attention. That is VSfM ID: 809001651
Stackk Details: https://github.com/bitrise-io/bitrise.io/blob/447263d971b6cfc9ac56b07f8cbb633611111850/system_reports/osx-vs4mac-stable.log#L1167

**Comment by spouliot** [comment]
So it happens to me with XM stable (7.0.10.5).

It seems I fixed that, indirectly [1], along symlink support for frameworks in 89482b5d5b9094860c7cfcb6c7a3b62097797728

[1] I did not realize at that time that it happened outside my current work

A workaround would be to apply part of the same fix, but that might not be easy if you don't own your CI.

```
diff --git a/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets b/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
index b03cf85b4..e2f6d4729 100644
--- a/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
+++ b/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets
@@ -354,6 +354,7 @@ Copyright (C) 2014 Xamarin. All rights reserved.
                        ProjectGuid="$(ProjectGuid)"
                        ProjectTypeGuids="$(ProjectTypeGuids)"
                        OutputPath="$(OutputPath)"
+                       TargetFrameworkMoniker="$(_ComputedTargetFrameworkMoniker)"
                        >
                        <Output TaskParameter="ArchiveDir" PropertyName="ArchiveDir" />
                </Archive>
```

The app I used is being tested (very frequently) for submission, which are green. 
I'll have a look why/how it pass there.

**Comment by spouliot** [comment]
> I'll have a look why/how it pass there.

So it pass because we don't archive the builds. We just need the `.pkg` for submitting and since we're not releasing those test apps then the archive is of "no use".

I'll file an enhancement issue so we create the archive since it has value for testing the task (not archiving the data).

**Comment by spouliot** [comment]
So the _good_ news is that the fix is part of `d16-10` which will be soon available in the stable channel.

You can use the "Preview" channel (for XM only) to confirm this (at least locally, not just it your external CI can use previews).

This is the current (as of today) preview I used.
```
Xamarin.Mac
Version: 7.13.0.7 (Visual Studio Community)
Hash: bb4428722
Branch: d16-10
Build date: 2021-04-29 04:38:53-0400
```

I'm closing the issue as there are no additional _trains_ planned for `d16-9` (the current stable) to release a fix.
