### ISSUE TITLE
Enable analyzers for single-file like targets

### ISSUE THREAD

**Issue by marek-safar** [xamarin/xamarin-macios#11636]
.NET6 comes with a new set of analyzers that will issue warnings and offer code fixes for APIs calls that are not supported for single-file setups.

What is needed on the SDK side is to enable `EnableSingleFileAnalyzer` msbuild property. It would be useful to have this enabled for all macios targets but also for the SDK build as well.

**Comment by rolfbjarne** [comment]
I had a look at the list of APIs incompatible with single-file setups, and I believe they all work for us, so I don't think we need to enable this warning.

FWIW these APIs don't work when using NativeAOT, but if NativeAOT is enabled, app developers should already be getting these warnings.
