### ISSUE TITLE
Xamarin.iOS.Common.targets: warning MSB4011, targets cannot be imported again. It was already imported

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-macios#11686]
New warning when building xamarin ios app with VS 2019 16.10.0:

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(27,2): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.Before.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets (25,2)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\Dev\Zitch\secure-httpclient\SecureHttpClient.TestRunner.iOS\SecureHttpClient.TestRunner.iOS.csproj]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1168,2): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.After.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets (1166,2)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\Dev\Zitch\secure-httpclient\SecureHttpClient.TestRunner.iOS\SecureHttpClient.TestRunner.iOS.csproj]
```

Was not happening in 16.9.5.
Could you please take a look ?

**Comment by spouliot** [comment]
There's some difference between `main` and `d16-10` but even the later is not a direct match to your line numbers.

Please provide the exact versions of all software being used

* Visual Studio: Help > About Microsoft Visual Studio > Copy Info [button]
* Visual Studio for Mac: Visual Studio > About Visual Studio > Show Details > Copy Information [button]

and paste this into the issue. Thanks!

c.c. @emaf there was code added for Windows (in `d16-10`) that seems removed in `main`. Know of anything that should be back ported ? thanks!

**Comment by tranb3r** [comment]
Microsoft Visual Studio Community 2019
Version 16.10.0
VisualStudio.16.Release/16.10.0+31321.278
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Xamarin   16.10.000.228 (d16-10@1c8354c)
Xamarin.iOS and Xamarin.Mac SDK   14.20.0.1 (fe0e2c518)

**Comment by tranb3r** [comment]
Line numbers seem to match `d16-10`
https://github.com/xamarin/xamarin-macios/blob/d16-10/msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets

**Comment by emaf** [comment]
@spouliot, yes, that's right, even though that commit was for net6 it indirectly fixed the warnings because the targets are shared.

**Comment by tranb3r** [comment]
@spouliot This is still happening with new release of visual studio 16.10.1

**Comment by emaf** [comment]
Hi @tranb3r, the fix for this problem has not been release yet, and it's now being tracked on the Developr Community https://developercommunity.visualstudio.com/t/Build-Warning-MSB4011-Since-Last-Xamarin/1437761. Please follow that ticket to get notified when a VS version with this fix is released. Thanks!
