### ISSUE TITLE
Pairing mac build server breaks after Visual Studio 2019 16.10 update.

### ISSUE THREAD

**Issue by BeardedGrizzly** [xamarin/xamarin-macios#11694]
Pairing to mac build server is no longer possible after installing Visual Studio 2019 16.10. 

### Steps to Reproduce

1. Install Visual Studio 2019 16.10 update.
2. Add mac build server and update iOS framework (14.20.0.1 in my case).

### Expected Behavior

Adding mac build server and connecting to it.

### Actual Behavior

Process is getting stuck on Installing Broker 16.10.000.228.

### Additional informations

- Mac build server can be accessed from client Windows 10 machine without issues (for example through VNC connection).
- Proccess cannot be stopped and Visual Studio 2019 does not react to network changes during the process (it's possible to disconnect mac server or disconnect the network without any changes). 

### Environment

 

**Visual Studio 2019:**

Microsoft Visual Studio Enterprise 2019
Version 16.10.0
VisualStudio.16.Release/16.10.0+31321.278
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

ASP.NET and Web Tools 2019   16.10.525.31942
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.525.31942
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.525.31942
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.10.525.31942
Azure Functions and Web Jobs Tools

C# Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

ResXManager   ResXManager
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62105.04180
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.228 (d16-10@1c8354c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.1 (d16-10/22fc2b3)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Xamarin.iOS and Xamarin.Mac SDK   14.20.0.1 (fe0e2c518)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
```
**Visual Studio for Mac:**

Version 8.9.10 (build 4)
Installation UUID: d1eff30c-8289-41ca-8aa9-ac672375355e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.203/Sdks
SDK Versions:
	5.0.203
	5.0.101
	5.0.100
	3.1.409
	3.1.404
	3.0.100
	2.1.302
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.6
	5.0.1
	5.0.0
	3.1.15
	3.1.10
	3.0.0
	2.1.2

=== .NET Core 3.1 SDK ===

SDK: 3.1.409

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Enterprise)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/lis-developer/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/lis-developer/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/dev/bretjohn/readme-tweak~3
Build date: 2021-05-13 17:03:56 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-05-13 17:04:12 UTC

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.10.0.5 (Visual Studio Enterprise)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:41-0400

=== Xamarin.iOS ===

Version: 14.20.0.1 (Visual Studio Enterprise)
Hash: fe0e2c518
Branch: d16-10
Build date: 2021-05-19 08:15:56-0400

=== Build Information ===

Release ID: 809100004
Git revision: 30612572b7defb0273729cb6b5ea5adc8bd9a147
Build date: 2021-05-13 13:06:24-04
Build branch: release-8.9
Xamarin extensions: 30612572b7defb0273729cb6b5ea5adc8bd9a147

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Oct 29 22:56:45 PDT 2020
    root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

### Build Logs

Starting IDB.Local 16.10.000.228 in port 51884...
IDB.Local 16.10.000.228 started successfully
Successfully started IDB Local Agent
iTunes has not been found. Please ensure to have a valid iTunes installation in order to communicate with Apple devices in Windows
Checking host configuration for connecting to '192.168.2.4'...
Checking SSH configuration...
Initializing environment...
Checking available disk space...
Checking Mono installation...
Checking Xamarin iOS installation...
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 5%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 10%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 15%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 20%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 25%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 30%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 35%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 40%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 45%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 50%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 55%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 60%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 65%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 70%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 75%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 80%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 85%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 90%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 95%
Downloading Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 100%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 5%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 10%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 15%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 20%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 25%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 30%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 35%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 40%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 45%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 50%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 55%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 60%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 65%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 70%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 75%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 80%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 85%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 90%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 95%
Installing Xamarin.iOS 'xamarin.ios-14.20.0.1.pkg': 100%
Checking host configuration for connecting to '192.168.2.4'...
Host '192.168.2.4' is configured correctly
Starting connection to '192.168.2.4'...
Checking Broker 16.10.000.228 installation...
Installing Broker 16.10.000.228...

> VS bug [#1339830](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1339830)

**Comment by mauroa** [comment]
This issue should already be fixed in latest VS 16.11 or 17.0. Please feel free to re-open it if you still experience similar issues after upgrading. Thanks
