### ISSUE TITLE
iOS app crashes on a device with 'System.ExecutionEngineException: Attempting to JIT compile method...'

### ISSUE THREAD

**Issue by neminush** [xamarin/xamarin-macios#11691]
There is an archive with a source code of an application in an attachment called '[sample_to_reproduce_aot_problem.zip](https://github.com/xamarin/xamarin-macios/files/6968971/nuget_updated_sample_with_sln_fix.zip)' (the link updated). With the source you can reproduce the problem.

The problem is reproducible on Visual Studio for Mac 8.9.10 (build 4) **with Xamarin.iOS 14.16.0.5** (the problem in Xamarin.iOS).

--- --- ---

### Steps to Reproduce
1. Download the sample solution: [sample_to_reproduce_aot_problem.zip](https://github.com/xamarin/xamarin-macios/files/6968971/nuget_updated_sample_with_sln_fix.zip) (the link updated).
2. Compile and run it on an iPhone (I have tested at iPhone 6s and iPhone XS). Use Visual Studio for Mac 8.9.10 (build 4).
3. In 'TimelineDebugView.cs' execution will be stopped at 53 line on break point before a problem place. Then continue execution.
4. Execution will be stopped at 20 line in 'Application.cs' file. You'll see an exception.

### Important !!!
- You can't reproduce this problem in Visual Studio for Mac 8.8.7 (build 18) and Xamarin.iOS v. 14.8.0.3. The app will work fine.
- [This bug](https://github.com/xamarin/xamarin-macios/issues/10917) is now also reproducible with Visual Studio for Mac 8.9.10 (build 4). **Update:** _to be precise, with Xamarin iOS, which was delivered together with the Visual Studio._
- **Update:** _The problem **is precisely in Xamarin.iOS** since version 14.16.0.5 and above._
- **Update:** _There are no problems in Xamarin.iOS version 14.8.0.3 and below._

--- --- ---

### Expected Behavior

The application must work correctly.

### Actual Behavior

System.ExecutionEngineException: Attempting to JIT compile method 'void DDP.Common.Net.Media.RTP.AudioSource/<ProcessNextSampleAsync>d__44:MoveNext ()' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <0c3d4da7367647c9a650750b1a4d0c53>:0 
  at DDP.Common.Net.Media.RTP.AudioSource.ProcessNextSampleAsync (System.Byte[] pcm, SIPSorceryMedia.Abstractions.EncodedSampleDelegate eventHandler) [0x0000c] in <efe0104c4e054dfc9a15cc5e83afdedd>:0 
  at DDP.Common.Net.Media.RTP.AudioSource.MicrophoneListener_NextSampleReceived (System.Object sender, DDP.Common.Events.ValueEventArgs`1[TValue] evArgs) [0x00179] in /Users/Neocriss/Documents/Stuff/AOT-problem/ILive/DDP.Common.Net.Media/RTP/AudioSource.cs:332 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:178 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
  at ILive.iOS.Application.Main (System.String[] args) [0x00002] in /Users/Neocriss/Documents/Stuff/AOT-problem/ILive/ILive.iOS/Application.cs:14 

### Environment

- Visual Studio for Mac 8.9.10 (build 4)
- Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
-  **Update:** _Xamarin.iOS 14.16.0.5 (Visual Studio Community) xcode 12.5_
- Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)

See '[About_Visual_Studio.txt](https://github.com/xamarin/xamarin-macios/files/6547418/About_Visual_Studio.txt)' for details.

### Example Project
Here is '[sample_to_reproduce_aot_problem.zip](https://github.com/xamarin/xamarin-macios/files/6968971/nuget_updated_sample_with_sln_fix.zip)' (the link updated).

**Update:** All links to sample project in this post was updated. The old link to a sample to reproduce aot problem:
https://github.com/xamarin/xamarin-macios/files/6547130/sample_to_reproduce_aot_problem.zip (do not use it - it has error in *.sln file)

@vargaz said it is dll mismatch problem. I.e. the callee uses [System.Memory], while the caller uses [netstandard].
https://github.com/mono/mono/issues/21255#issuecomment-949918939

**Comment by spouliot** [comment]
As described by the [link](https://docs.microsoft.com/xamarin/ios/internals/limitations) in the stack trace a `ExecutionEngineException` is not always a bug. Full AOT has a few limitations and in some cases requires some extra information (e.g. [p/invoke callbacks](https://docs.microsoft.com/en-ca/xamarin/ios/internals/limitations#using-delegates-to-call-native-functions)).

https://docs.microsoft.com/xamarin/ios/internals/limitations

I'll check you attached sample. You might want to read the above limitations to see if some might apply to your code base.


> You can't reproduce this problem in Visual Studio for Mac 8.8.7 (build 18). The app will work fine.
> This bug is now also reproducible with Visual Studio for Mac 8.9.10 (build 4).

Telling us which version of VSfM you're using is not helpful as VSfM can be used with different versions of Xamarin.iOS. VSfM is also rarely the cause of issues that happens at runtime for iOS apps.

Please always provide all version informations using

* Visual Studio: Help > About Microsoft Visual Studio > Copy Info [button]
* Visual Studio for Mac: Visual Studio > About Visual Studio > Show Details > Copy Information [button]

This is the only way we can reproduce the issue (or in this case confirm it worked in earlier versions).

Almost all `ExecutionEngineException` comes from the mono runtime. This runtime has not changed _much_ recently as most efforts are geared for net6. That should make it easy to find a problem if this was working in a recent build.

**Comment by neminush** [comment]
> As described by the [link](https://docs.microsoft.com/xamarin/ios/internals/limitations) in the stack trace a `ExecutionEngineException` is not always a bug. Full AOT has a few limitations and in some cases requires some extra information (e.g. [p/invoke callbacks](https://docs.microsoft.com/en-ca/xamarin/ios/internals/limitations#using-delegates-to-call-native-functions)).

This is a 100% bug that did not exist before.

This error is NOT present in Visual Studio for Mac 8.8.7 (build 18).
This error is present in Visual Studio for Mac 8.9.10 (build 4).

This bug is also reproduced and is still relevant:
[https://github.com/xamarin/xamarin-macios/issues/10917](https://github.com/xamarin/xamarin-macios/issues/10917)

Additional information has long been provided in the text file above. Here is the direct link:
[https://github.com/xamarin/xamarin-macios/files/6547418/About_Visual_Studio.txt](https://github.com/xamarin/xamarin-macios/files/6547418/About_Visual_Studio.txt)

**Comment by neminush** [comment]
This is environment information with Visual Studio for Mac 8.8.7 (build 18) where the problem do not exists:
[https://github.com/xamarin/xamarin-macios/files/6548030/Visual_Studio_for_Mac_8_8_7_.build_18.txt](https://github.com/xamarin/xamarin-macios/files/6548030/Visual_Studio_for_Mac_8_8_7_.build_18.txt)

**Comment by spouliot** [comment]
So the root issue seems to be https://github.com/mono/mono/issues/20805#issuecomment-791429869

The link points to the explanation (bad nugets for NETStandard 2.1) and the next post explains how to workaround it.

This solves the `ExecutionEngineException` but it now fails with
```
System.MissingMethodException: Method not found: System.Threading.Tasks.ValueTask`1<System.IO.Pipelines.FlushResult> System.IO.Pipelines.PipeWriter.WriteAsync(System.ReadOnlyMemory`1<byte>,System.Threading.CancellationToken)
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316 
  at DDP.Common.Net.Media.RTP.AudioSource.ProcessNextSampleAsync (System.Byte[] pcm, SIPSorceryMedia.Abstractions.EncodedSampleDelegate eventHandler) [0x0000c] in <a3601f8fa7464fe39284ed79df7e4292>:0 
  at DDP.Common.Net.Media.RTP.AudioSource.MicrophoneListener_NextSampleReceived (System.Object sender, DDP.Common.Events.ValueEventArgs`1[TValue] evArgs) [0x000a7] in /Users/poupou/Downloads/ILive/DDP.Common.Net.Media/RTP/AudioSource.cs:327 
```

which is likely related to the same root issue (having two different implementations of those types).

**Comment by spouliot** [comment]
So I seem to have success by updating the `System.Memory` nuget to 4.5.4 (you're using 4.5.3). Note that I removed the workaround from above.

https://www.nuget.org/packages/System.Memory/

Could you try this and report back ? thanks!

# Application Output
```
Launched application 'ru.inputlab.iliveru' on 'Mercure' with pid 3220
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/Mono.Security.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/System.Core.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/System.Numerics.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/System.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/System.Net.Http.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/System.Drawing.Common.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/Xamarin.iOS.dll
Thread started:  #2
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/MvvmCross.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/ILive.Core.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/Microsoft.Extensions.Logging.Abstractions.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/SIPSorceryMedia.Abstractions.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/BouncyCastle.Crypto.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/DnsClient.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/System.Runtime.Serialization.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/System.Xml.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/System.Xml.Linq.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/websocket-sharp.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/SIPSorcery.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/DDP.Common.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/System.IO.Pipelines.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/DDP.Common.Net.Media.dll
Loaded assembly: /private/var/containers/Bundle/Application/779239DF-0C4A-40AE-AE3C-5555CF5FB64A/ILive.iOS.app/ILive.iOS.exe
Thread started: <Thread Pool> #3
2021-05-26 15:08:12.422 ILive.iOS[3220:3928323] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Primary start
2021-05-26 15:08:12.422 ILive.iOS[3220:3928323] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: FirstChance start
2021-05-26 15:08:12.425 ILive.iOS[3220:3928323] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Platform services
2021-05-26 15:08:12.425 ILive.iOS[3220:3928323] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: MvvmCross settings start
2021-05-26 15:08:12.427 ILive.iOS[3220:3928323] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Singleton Cache start
2021-05-26 15:08:12.427 ILive.iOS[3220:3928323] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: ViewDispatcher start
Thread started: <Thread Pool> #4
Thread started: <Thread Pool> #5
Thread started: <Thread Pool> #6
Thread started: <Thread Pool> #7
Thread started: <Thread Pool> #8
Thread started: <Thread Pool> #9
Thread started: <Thread Pool> #10
Thread started: <Thread Pool> #11
Thread started: <Thread Pool> #12
2021-05-26 15:08:12.439 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Bootstrap actions
2021-05-26 15:08:12.440 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: StringToTypeParser start
2021-05-26 15:08:12.441 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: FillableStringToTypeParser start
2021-05-26 15:08:12.441 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: PluginManagerFramework start
2021-05-26 15:08:12.464 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Create App
2021-05-26 15:08:12.464 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: NavigationService
2021-05-26 15:08:12.464 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Load navigation routes
2021-05-26 15:08:12.465 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: App start
2021-05-26 15:08:12.465 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Application Initialize - On background thread
2021-05-26 15:08:12.465 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: ViewModelTypeFinder start
2021-05-26 15:08:12.465 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: ViewsContainer start
2021-05-26 15:08:12.465 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Lookup Dictionary start
2021-05-26 15:08:12.470 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Views start
2021-05-26 15:08:12.470 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: CommandCollectionBuilder start
2021-05-26 15:08:12.470 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: NavigationSerializer start
2021-05-26 15:08:12.471 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: InpcInterception start
2021-05-26 15:08:12.471 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: InpcInterception start
2021-05-26 15:08:12.471 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: LastChance start
2021-05-26 15:08:12.480 ILive.iOS[3220:3928356] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Core.MvxSetup) Setup: Secondary end
2021-05-26 15:08:12.480 ILive.iOS[3220:3928323] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Logging.MvxLog) AppStart: Application Startup - On UI thread
2021-05-26 15:08:12.485 ILive.iOS[3220:3928323] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Logging.MvxLog) iOSNavigation
2021-05-26 15:08:12.486 ILive.iOS[3220:3928323] 2021-05-26 15:08:12 [TRACE] (MvvmCross.Logging.MvxLog) PresentationAttribute nor MasterNavigationController found for TimelineDebugView. Assuming Root presentation

 -*-*-> .ctor AudioSource : <1> - starting...

 -*-*-> .ctor AudioSource : <1> - sessionId: 1 - done

 -*-*-> AudioSource : <1> - SetAudioSourceFormat - audioFormat: SIPSorceryMedia.Abstractions.AudioFormat

 -*-*-> AudioSource : <1> - StartAudio - starting...

 -*-*-> AudioSource : <1> - StartAudio - done
Thread finished: <Thread Pool> #6
Thread finished: <Thread Pool> #5
Thread finished: <Thread Pool> #9
Thread started:  #13
--***--***-- $$$ => packagesResult.Count: 2
Thread finished: <Thread Pool> #12
Thread finished: <Thread Pool> #11
Thread finished: <Thread Pool> #4
Thread finished: <Thread Pool> #8
Thread finished: <Thread Pool> #3
Thread started: <Thread Pool> #14
Thread finished: <Thread Pool> #10
Thread finished: <Thread Pool> #7
Thread started: <Thread Pool> #15
Thread started: <Thread Pool> #16
Thread finished: <Thread Pool> #14
Thread started: <Thread Pool> #17
```

**Comment by neminush** [comment]
> https://www.nuget.org/packages/System.Memory/
> 
> Could you try this and report back ? thanks!

Thank you.

I have checked your suggestion by updating the 'System.Memory' nuget package to version 4.5.4 and that didn't solve the problem. Neither in the provided sample nor in our full solution.
I also made an attempt to update more nuget packages starting with the word 'System', but this turned out not successful in solving the problem.

I deleted /bin, /obj and /.vs directories before each test.

**Comment by neminush** [comment]
I also want to draw your attention to the fact that this bug is closed, but not fixed: [https://github.com/xamarin/xamarin-macios/issues/10917](https://github.com/xamarin/xamarin-macios/issues/10917)

At least that example also reproduces a similar error.

**Comment by vshapenko** [comment]
We also have same exception in our app after upgrading ios sdk from 14.2.0.12 to current actual.Also on 14.10.0.4 we have same exception. So temporary solution for us was rollback of ios sdk version on build system.

**Comment by spouliot** [comment]
> I have checked your suggestion by updating the 'System.Memory' nuget package to version 4.5.4 and that didn't solve the problem. Neither in the provided sample nor in our full solution.

@neminush I'm surprised since I used the [sample](https://github.com/xamarin/xamarin-macios/files/6547130/sample_to_reproduce_aot_problem.zip) you provided to test this. I'll try it again.

It's quite a large solution, with several projects. You might also want to check if all nuget references were updated to 4.5.4. If that does not work then please attach an updated version of your build log, so I can compare it to mine. Thanks!

**Comment by spouliot** [comment]
WRT https://github.com/xamarin/xamarin-macios/issues/10917 I think it was closed because it mentioned multiple issues (3) and the last one was fixed. 

It's always best to avoid _meta_ issues since it's very hard, for everyone, to keep the state of everything over multiple conversations.

This issue is open and track that first (and maybe second) issue. There's no point in re-opening it as it will just confuse people that were affected by the last part (the build issue). We can still refer to individual comments on the issue if that helps.

**Comment by neminush** [comment]
Here is my [build_log.txt](https://github.com/xamarin/xamarin-macios/files/6562059/build_log.txt) for a [sample](https://github.com/xamarin/xamarin-macios/files/6562071/nuget_updated_sample.zip) (just uploaded) with 'System.Memory' nuget package of version 4.5.4.

**Comment by rolfbjarne** [comment]
> Here is my [build_log.txt](https://github.com/xamarin/xamarin-macios/files/6562059/build_log.txt) for a [sample](https://github.com/xamarin/xamarin-macios/files/6562071/nuget_updated_sample.zip) (just uploaded) with 'System.Memory' nuget package of version 4.5.4.

I wasn't able to open that solution in VSMac, it just says loading fails.

I tried building from the command line, and it says:

```shell
$ msbuild /r /p:Platform=iPhone ILive.sln
Microsoft (R) Build Engine version 16.10.1 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 7/1/2021 5:04:04 PM.
/Users/rolf/Downloads/ILive/ILive/ILive.sln(671): Solution file error MSB5023: Error parsing the nested project section in solution file. A project with the GUID "{898EEFAC-4212-4665-BFBE-FD9923C2F574}" is listed as being nested under project "{25109133-DFCC-4E38-9F88-A99AFB10D9B4}", but does not exist in the solution.

Build FAILED.
```

I tried building just the ILive.iOS project, but that fails too:

```shell
$ msbuild /r /p:Platform=iPhone ILive.iOS.csproj
[...]
"/Users/rolf/Downloads/ILive/ILive/ILive.iOS/ILive.iOS.csproj" (default target) (1:7) ->
"/Users/rolf/Downloads/ILive/ILive/DDP.Common.iOS/DDP.Common.iOS.csproj" (default target) (22:9) ->
(_CheckForInvalidConfigurationAndPlatform target) -> 
  /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(835,5): error : The BaseOutputPath/OutputPath property is not set for project 'DDP.Common.iOS.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='iPhone'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [/Users/rolf/Downloads/ILive/ILive/DDP.Common.iOS/DDP.Common.iOS.csproj]
````

Full output: https://gist.github.com/rolfbjarne/a423ea3fdf40a1395ff0c12ebd487f2f

**Comment by neminush** [comment]
> I wasn't able to open that solution in VSMac, it just says loading fails.

For me and my friends, the Visual Studio for Mac open and compile this project without any problems.

I have deleted from the iLive.sln file all the lines with the entry {898EEFAC-4212-4665-BFBE-FD9923C2F574} and compressed the solution into a new archive: [nuget_updated_sample_with_sln_fix.zip](https://github.com/xamarin/xamarin-macios/files/6968971/nuget_updated_sample_with_sln_fix.zip). I have it compiled and checked. The problem with an exception ' System.ExecutionEngineException: Attempting to JIT compile method...' is still present.

Please fix this problem. Because of this problem, part of the functionality has not been working for us for half a year.

Information about my environment (Visual Studio and everything else) is in this text file:
[Environment_Info.txt](https://github.com/xamarin/xamarin-macios/files/6968993/Environment_Info.txt)

**Comment by neminush** [comment]
@rolfbjarne , @spouliot 

Please uninstall your Visual Studio from your Mac by following the instructions:
[https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019#visual-studio-for-mac-and-xamarin-script](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019#visual-studio-for-mac-and-xamarin-script)

Then download Visual Studio for Mac from [here](https://visualstudio.microsoft.com/) and install it.

Then open [this](https://github.com/xamarin/xamarin-macios/files/6968971/nuget_updated_sample_with_sln_fix.zip) project and you will see that the problem is reproduced.

**Comment by chamons** [comment]
After fixing up the code signing to use my profile, fixing Into.plist to use my test profile, and removing the entries from Entitlements.plist, I can reproduce this:

```
System.ExecutionEngineException: Attempting to JIT compile method 'void DDP.Common.Net.Media.RTP.AudioSource/<ProcessNextSampleAsync>d__44:MoveNext ()' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
```

Apologies for the delay in response.

**Comment by marek-safar** [comment]
Reopening as this turned our to be iOS issue

**Comment by neminush** [comment]
@spouliot @rolfbjarne

@vargaz said it is dll mismatch problem. I.e. the callee uses [System.Memory], while the caller uses [netstandard].
https://github.com/mono/mono/issues/21255#issuecomment-949918939

If you can't fix it, then at least suggest a workaround. Please.

---

To get around the problem, we have been using the old Xamarin.iOS version 14.8.0.3 (branch: xcode12.3) to build, but it can't last that long.

**Comment by neminush** [comment]
@spouliot @rolfbjarne @chamons @marek-safar

I have updated the first post in this thread about this problem and added important information about the bug to it. I hope this will help solve it.

The problem is precisely in Xamarin.iOS since version 14.16.0.5 and above. There are no problems in Xamarin.iOS version 14.8.0.3 and below.

Now to avoid the problem we use the current version of the Visual Studio fro Mac and the old version of the Xamarin.iOS (14.8.0.3).
We are afraid that when the Visual Studio for Mac comes out with .NET 6 support then it will stop working with the Xamarin.iOS version 14.8.0.3 and we will have big problems.

**Comment by rolfbjarne** [comment]
@neminush can you try adding `<ResolveAssemblyConflicts>true</ResolveAssemblyConflicts>` to the executable project to see if that fixes it?

Like this:

```diff
diff --git a/ILive.iOS/ILive.iOS.csproj b/ILive.iOS/ILive.iOS.csproj
index a357398..3b7c7ac 100644
--- a/ILive.iOS/ILive.iOS.csproj
+++ b/ILive.iOS/ILive.iOS.csproj
@@ -16,6 +16,7 @@
     <RuntimeIdentifiers>osx;osx-x86;osx-x64</RuntimeIdentifiers>
     <NuGetRuntimeIdentifier>osx</NuGetRuntimeIdentifier>
     <ProvisioningType>automatic</ProvisioningType>
+    <ResolveAssemblyConflicts>true</ResolveAssemblyConflicts>
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
     <DebugSymbols>true</DebugSymbols>
```

**Comment by neminush** [comment]
@rolfbjarne

The flag `<ResolveAssemblyConflicts>true</ResolveAssemblyConflicts>` really solves the problem in test project provided here. I will write here about the results as soon as I check this workaround on our production application.

**Comment by neminush** [comment]
@rolfbjarne

We have just completed testing on our production application. 
The flag `<ResolveAssemblyConflicts>true</ResolveAssemblyConflicts>` solves all of our AOT problems in iOS even [this](https://github.com/xamarin/xamarin-macios/issues/10917) undeservedly closed.

Thank you very much!

**Comment by AHComp** [comment]
[https://developercommunity.visualstudio.com/t/bug-in-visual-studio-2022-xamarin-signalr-method-n/1528510](url)

We got the info from microsoft engineer [Nicolas Mousserrin](https://developercommunity2.visualstudio.com/user/3199966c-6933-4f86-b114-8e11b8e95ad5/profile) to reopen this issue because it not solved **everything** !

We have still the problem with signalr since 5 month and it's urgent to solve the bug.
All infos you can find in the link.

I don't know why it's my job to reopen this issue but by the way i like **42** !!!

Regards
Alexander

**Comment by chamons** [comment]
@AHComp - Please open a new issue, filling out the template completely stating your problem and giving use logs/samples so we can look into it.
