### ISSUE TITLE
.NET: Generate a binary version of runtimeconfig.json for mobile targets

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#11745]
We need to generate a binary version of runtimeconfig.json for certain features to work.

Steps:

* Use Mono's task to convert *.runtimeconfig.json to a binary blob.
* Bundle the blob in the .app
* Don't bundle the json in the app.

Ref: https://github.com/xamarin/xamarin-macios/pull/11693#discussion_r640092943
Ref: https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/docs/design/mono/mobile-runtimeconfig-json.md
Ref: https://github.com/dotnet/runtime/issues/49237
Ref: https://github.com/xamarin/xamarin-android/pull/6009

**Comment by rolfbjarne** [comment]
@jonathanpeppers I believe this is something XA should be doing too.

**Comment by jonathanpeppers** [comment]
We just got: https://github.com/xamarin/xamarin-android/pull/5975

I think we can start using the `<RuntimeConfigParser/>` task now:

https://github.com/dotnet/runtime/blob/main/src/tasks/RuntimeConfigParser/RuntimeConfigParser.cs

We probably won't get this until Preview 6 or later.
