### ISSUE TITLE
Seeing “Asset URL has expired” error with Apple On-Demand Resources  

### ISSUE THREAD

**Issue by mbecker73** [xamarin/xamarin-macios#11767]
We are using Apple On-Demand Resources (ODR) technology to download zip file asset packs within our app. For the past several months since rolling this feature out, we have seen many users run into intermittent issues when downloading some asset packs via Apple ODR. This seems to occur within the actual resource request code, accessed via Xamarin Foundation library. The following error is being thrown:

`Caught exception downloading ODR asset pack to device: Error Domain=AssetErrorDomain Code=6 "Asset URL has expired" UserInfo={NSDebugDescription=Asset URL has expired}`

### Steps to Reproduce

We have not been able to consistently reproduce this, but we have a very large number of users in production that are running into this error. It seems to occur when downloading certain asset packs but not others. 

Once a user is in this state we have not been able to find a reliable way to resolve this issue. For users affected, uninstalling and reinstalling the app does not seem to fix the problem. We have tried changing the resource tags for ODR asset packs in an upcoming release to see if that will fix the issue, but would prefer to not have to do that every app release and want to know the root cause of the issue.

### Expected Behavior

Asset packs download to the device without issue. 

### Actual Behavior

Asset pack download fails with error message `Error Domain=AssetErrorDomain Code=6 "Asset URL has expired" UserInfo={NSDebugDescription=Asset URL has expired}`

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.8.10 (build 2)
Installation UUID: 905669e0-c29f-497a-94e7-f4a5993e4187
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.102/Sdks
SDK Versions:
	5.0.102
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.2
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.15
	2.1.14
	2.1.13

=== .NET Core 3.1 SDK ===

SDK: 3.1.102

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.10.0.4 (Visual Studio Community)
Hash: 5a05865f6
Branch: xcode12.4
Build date: 2021-01-28 02:30:23-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.26 (Visual Studio Community)
Commit: xamarin-android/d16-8/a36ce73
Android SDK: /Users/mbecker/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/mbecker/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:34:58 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2021-01-14 00:35:22 UTC

=== Build Information ===

Release ID: 808100002
Git revision: f81ffa2444a28c09f173849935ec9ee0195a5b17
Build date: 2021-02-18 12:02:12-05
Build branch: release-8.8
Xamarin extensions: f81ffa2444a28c09f173849935ec9ee0195a5b17

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Thu Apr 22 21:46:47 PDT 2021
    root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

```

### Build Logs

No build logs, as no errors or issue show during app build. 

### Example Project (If Possible)

Here is some code snippets used within our Xamarin app to create On-Demand Resource requests:

```
public class NSBundleResourceRequestManager : IResourceRequestManager
    {
        private NSBundleResourceRequest _currentResourceRequest;
        public event EventHandler LowDiskSpaceEvent;

        public NSBundleResourceRequestManager()
        {
            // Listen to all notifications posted for any objects about low disk space
            var token = NSBundleResourceRequest.Notifications.ObserveLowDiskSpace((notification, eventArgs) =>
            {
                LowDiskSpaceEvent?.Invoke(this, null);
                Debug.WriteLine("Observed LowDiskSpaceNotification!");
            } );
        }

        // create and initialize new resource request
        public async Task CreateODRResourceRequest(string tag)
        {
            if (string.IsNullOrWhiteSpace(tag))
            {
                throw new ArgumentNullException(nameof(tag));
            }

            // Create resource request
            var request = new NSBundleResourceRequest(new[] { tag });

            // Set highest loading priority
            request.LoadingPriority = NSBundleResourceRequest.LoadingPriorityUrgent;

            _currentResourceRequest = request;

            var resourcesAlreadyAvailable = await request.ConditionallyBeginAccessingResourcesAsync();

            // ensure we only download resource if it's not already on the device
            if (!resourcesAlreadyAvailable)
            {
                await request.BeginAccessingResourcesAsync();
            }
        }

        // Releases resources
        public void RemoveResourceRequest()
        {
            if (_currentResourceRequest != null)
            {
                _currentResourceRequest.EndAccessingResources();
                _currentResourceRequest = null;
            }
        }

        // get bundle path for the resource
        public string GetResourcePath()
        {
            var paths = NSBundle.MainBundle.PathsForResources("zip");
            if (paths.Length == 0)
            {
                throw new Exception("No zips found in bundle");
            }
            return paths[0];
        }
    }
```
We first await `CreateODRResourceRequest` function, then make call to `GetResourcePath` to obtain path to the downloaded asset pack. So this is all done async on a background thread. 

Any information on if this is an issue with the Xamarin Foundation library or our access code? This issue has been plaguing us for some time now. Thanks in advance!

**Comment by spouliot** [comment]
> Xamarin Foundation library

I'm not sure what you mean by this ^ ? 

Is this some other library or are you talking about the Xamarin.iOS SDK ?

> Caught exception downloading ODR asset pack to device: Error Domain=AssetErrorDomain Code=6 "Asset URL has expired" UserInfo={NSDebugDescription=Asset URL has expired}

That message comes from Apple, not our SDK. It sounds like a server-side issue.

It seems to happen to other people as well
https://stackoverflow.com/questions/58593355/what-does-the-ios-on-demand-resource-error-asset-url-has-expired-asseterrordo

> We have not been able to consistently reproduce this,

Did you try to correlate the time when it happens with https://developer.apple.com/system-status/ ? 

> but we have a very large number of users in production that are running into this error. 

You should file an issue (or even a DTS) with Apple to figure out if your issue maps with their service interruptions. ODR is a black box for the SDK. We transfer the calls, back and forth, between C# and ObjC - but we don't have any additional visibility on how (or where) things are going.

**Comment by mbecker73** [comment]
Sorry my wording was off, it's happening with `NSBundleResourceRequest` calls, and that class lives in the `Foundation` [namespace](https://docs.microsoft.com/en-us/dotnet/api/foundation?view=xamarin-ios-sdk-12). 

We have seen many of the StackOverflow posts with similar issues like this, but have not found a working solution from any of them. This is where we got the idea to change the resource tags (but not the filenames). 

Will see if we can correlate the times this happens with system status on Apple's side. We are in the process of working with Apple on this issue but wanted to check on the possibility of this happening from the Xamarin side of things. Thank you for the info!

**Comment by rolfbjarne** [comment]
Were you able to figure out what's happening?

**Comment by mbecker73** [comment]
@rolfbjarne We have not. We have not received any substantial info from Apple support on the root cause and none of our dev team has been able to reproduce it locally. For the time being we are changing the resource tags for every On Demand Resource asset every app release, which is the only workaround we have found to avoid this issue. This is obviously not ideal, and Apple explicitly told us we shouldn't have to do this, but right now we can't figure out how else to avoid the problem.

**Comment by spouliot** [comment]
closing (inactivity)

If you get any answer (from Apple) please let us know (we're curious)
and we can re-open the issue if there's anything we need to fix on our side.
