### ISSUE TITLE
In VS 2019 16.11.0 Preview 1 and the WeatherTwentyOne sample fails to build iOS Simulator using paired macOS machine

### ISSUE THREAD

**Issue by wli3** [xamarin/xamarin-macios#11808]
---
**Issue moved from dotnet/sdk#17927**
- Please respond to @hypermoose.

---

_From @hypermoose on Thursday, May 27, 2021 6:28:15 PM_

Here is the error:

2>Could not execute because the specified command or file was not found.
2>Possible reasons for this include:
2>  * You misspelled a built-in dotnet command.
2>  * You intended to execute a .NET program, but dotnet-sdk/6.0.100-preview.4.21255.9/Sdks/Microsoft.NET.ILLink.Tasks/build/../tools/net5.0/illink.dll does not exist.
2>  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\14.5.100-preview.4.638\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(354,3): error MSB6006: "dotnet" exited with code 1.
2>Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#17927**
- Please respond to @dotnet-issue-labeler[bot].

---

_From @dotnet-issue-labeler[bot] on Thursday, May 27, 2021 6:28:17 PM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by spouliot** [comment]
@hypermoose it looks like dotnet is not installed on your Windows machine. Have you followed all instructions on https://github.com/davidortinau/WeatherTwentyOne ?

In particular the [Requirements](https://github.com/davidortinau/WeatherTwentyOne#requirements) section of running `maui-check` ?

The SDK teams does not work the Windows (IDE) integration, nor on that sample. For the previews your best option is to open an issue on the `WeatherTwentyOne` repo and describe what you have done (each step) and how it differs from the supplied instructions.

**Comment by hypermoose** [comment]
It absolutely is installed on the Windows PC and the windows sample runs fine.  That error is coming from the paired MacOS remote window which also has had maui-check run on it successfully.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
