### ISSUE TITLE
Xamarin - iOS App Crash Hot Reload

### ISSUE THREAD

**Issue by rubenribeiro123** [xamarin/xamarin-macios#11818]
VS 2019
iOS 14.6

When I try to use Hot reload, the application installs but doesn't even appear on the iphone until I restart it. After restart appears, when clicking it shows a splashscreen and automatically closes without any kind of error.

How to fix this issue?

**Comment by spouliot** [comment]
We need additional details to help you. Please look at our [issue template](https://github.com/xamarin/xamarin-macios/issues/new) and file the requested informations.

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
