### ISSUE TITLE
Document how to migrate items and properties from legacy Xamarin projects to .NET projects

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#11863]
See https://github.com/xamarin/xamarin-macios/wiki/Project-file-properties-dotnet-migration.

Upgrade assistant: https://github.com/dotnet/upgrade-assistant

**Comment by rolfbjarne** [comment]
@chamons  in d7c2a45ca9351106f83fcf7f08c1b09a8a5fb563 you added the `BundleDependentFiles` item group as an input to the _CompileToNative tasks, but it doesn't seem like we use that item group anywhere else (nor adding to it) - was there any specific reason for this addition? Can it be removed? Or described/documented?

**Comment by chamons** [comment]
@rolfbjarne - I have honestly no clue. I think they can be removed based upon reviewing the PR.

**Comment by rolfbjarne** [comment]
This is mostly documented now, at least indirectly, in https://github.com/xamarin/xamarin-macios/wiki/Project-file-properties.
