### ISSUE TITLE
Apps crash in the simulator on macOS 12 (Monterey) 

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#11894]
See https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1339933.

**Comment by spouliot** [comment]
Running our test on an Intel Mac (Book Pro) w/macOS 12.0 worked fine.

**Comment by Cameron-Stuart** [comment]
My best guess is that this is an M1 issue. I've seen a couple of reports for M1 Macs, but none for Intel Macs. Unfortunately I think the current solution is to downgrade macOS back down to the latest public release as this isn't exclusive to Xamarin but also affects Flutter and Swift (tested on VSCode, Xcode 12 and Xcode 13 Beta).

**Comment by rolfbjarne** [comment]
This works fine as far as I know, so I'm closing this.
