### ISSUE TITLE
Default Http_Message_Handler cannot be HttpClientHandler in .NET 6

### ISSUE THREAD

**Issue by steveisok** [xamarin/xamarin-macios#11904]
We are intending on defaulting the underlying handler to `NSUrlSessionHandler` for both `HttpClient` and `HttpClientHandler`.  In order to make that happen, we are using reflection to call `ObjCRuntime.RuntimeOptions.GetHttpMessageHandler`.  Therefore, `HttpClientHandler` should not be the default in order to avoid a circular dependency. 

https://github.com/xamarin/xamarin-macios/blob/2b7dc07d20fc06344d7f164af8934f5e755572c2/src/ObjCRuntime/RuntimeOptions.cs#L34

The available options, I think, should be the native handler(s) and `SocketsHttpHandler` from runtime.

**Comment by spouliot** [comment]
I have the changes stashed (and untested) for this. I'll test them asap for P6.

**Comment by spouliot** [comment]
https://github.com/xamarin/xamarin-macios/pull/11956
