### ISSUE TITLE
[dotnet] MonoAotCrossCompilerPath changed to MonoAotCrossCompiler

### ISSUE THREAD

**Issue by lambdageek** [xamarin/xamarin-macios#11905]
See https://github.com/dotnet/runtime/pull/53685#issuecomment-859807288

The runtime changed from definiing a single `$(MonoAotCrossCompilerPath)` property to defining an item `@(MonoAotCrossCompiler)` with all the cross compilers for various platforms.

---

Device builds fail with a message like:

```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-ci.upload-download-dotnettests.8/targets/Xamarin.Shared.Sdk.targets(516,3): error : The AOT compiler '' does not exist. [/Users/alklig/work/net6-mobile-samples/HelloiOS/HelloiOS.csproj]
```

**Comment by rolfbjarne** [comment]
Tentative fix, once we bump to the .NET version with this change: https://github.com/rolfbjarne/xamarin-macios/commit/1e33fae2441798b3fd4e77c7938933ee033213af

**Comment by dotMorten** [comment]
@rolfbjarne I'm seeing this with Preview 7. AFAIK I have the fix you added:

![image](https://user-images.githubusercontent.com/1378165/129642210-1a1262ec-e388-4c7e-addc-581f6a302dbd.png)

**Comment by rolfbjarne** [comment]
@dotMorten AOT compilation is currently broken on Windows (with this error message), we're working on fixing it for a future release.
