### ISSUE TITLE
[macos] Warnings with and without NativeReference.Kind metadata

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#11916]
### Steps to Reproduce

1. I added a .dylib @(NativeReference) to a net6.0-macos app
2. Tried with Kind=Dynamic, I get a warning about dynamic libs not supported  
    > /usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/11.3.100-preview.5.894/targets/Xamarin.Shared.Sdk.targets(688,3):  
    > Dynamic native references are not supported:  
    > '/Users/matthew/Projects/Testing/Maui/packages/skiasharp/2.88.0-pr.1707.28/runtimes/osx/native/libSkiaSharp.dylib'

3. Tried without Kind, I get warning about missing kind  
    > /usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/11.3.100-preview.5.894/targets/Xamarin.Shared.Sdk.targets(688,3):  
    > Unknown native reference type for  
    > '/Users/matthew/Projects/Testing/Maui/packages/skiasharp/2.88.0-pr.1707.28/runtimes/osx/native/libSkiaSharp.dylib'. 

4. Either way, the app **STILL** runs

### Expected Behavior

No warnings

### Actual Behavior

Warings.

### Environment

```
dotnet 6.0.100-preview.5.2130.5
macos sdk 11.3.100-preview.5.894
```

### Build Logs

[without-kind.zip](https://github.com/xamarin/xamarin-macios/files/6644026/without-kind.zip)
[incremental.zip](https://github.com/xamarin/xamarin-macios/files/6644027/incremental.zip)
[with-kind.zip](https://github.com/xamarin/xamarin-macios/files/6644028/with-kind.zip)

**Comment by rolfbjarne** [comment]
This has been solved, specifying `Kind=Dynamic` won't show a warning anymore.

It was probably fixed here: https://github.com/rolfbjarne/xamarin-macios/commit/a269eec46aea1a9916d1ac307fb2f65534853f43
