### ISSUE TITLE
.NET: 'dotnet new tvos' creates a project that doesn't build

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#11918]
### Steps to Reproduce

1. `dotnet new tvos`
2. Add a RuntimeIdentifier to the csproj (`<RuntimeIdentifier>tvos-x64</RuntimeIdentifier>`)
3. `dotnet build`

### Expected Behavior

Build succeeds

### Actual Behavior

```
Tool xcrun execution started with arguments: clang -g -mtvos-simulator-version-min=11.2 -arch x86_64 -isysroot /Applications/Xcode_13.0.0-beta.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator15.0.sdk -I/runtimes/tvos-x64/native -DDEBUG -o /Users/rolf/work/maccore/main/xamarin-macios/tests/dotnet/tvos/obj/Debug/net6.0-tvos/tvos-x64/nativelibraries/main.x86_64.o -c /Users/rolf/work/maccore/main/xamarin-macios/tests/dotnet/tvos/obj/Debug/net6.0-tvos/tvos-x64/linker-cache/main.x86_64.mm
         (TaskId:157)
Tool xcrun execution finished (exit code = 1).
         (TaskId:157)
/Users/rolf/work/maccore/main/xamarin-macios/tests/dotnet/tvos/obj/Debug/net6.0-tvos/tvos-x64/linker-cache/main.x86_64.mm:15:10: fatal error: 'xamarin/xamarin.h' file not found
#include "xamarin/xamarin.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
 (TaskId:157)
```

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/6646947/msbuild.binlog.zip)

xamarin-macios: f9d0159e07eda08eb03e0a72d969f18128b86ff1

**Comment by rolfbjarne** [comment]
The reason is that this clang argument is wrong:

> -I/runtimes/tvos-x64/native

part of the path is missing.

**Comment by akoeplinger** [comment]
`tvos-x64` is not a valid RID, it should be `tvossimulator-x64`.

**Comment by rolfbjarne** [comment]
> `tvos-x64` is not a valid RID, it should be `tvossimulator-x64`.

Yeah, that works 🤦 

We need RID validation sooner rather than later (which is a part of https://github.com/xamarin/xamarin-macios/issues/10861)
