### ISSUE TITLE
WKPreferences isTextInteractionEnabled is not correctly bound on xcode13.

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#11955]
There is a breaking change that has been reported to apple here: https://github.com/xamarin/maccore/issues/2460 

We are not doing the binding yet to see if apple reverts the change, else a manual binding will have to be done to use the correct selector according to the OS version.

**Comment by rolfbjarne** [comment]
Manual bindings were implemented here: https://github.com/xamarin/xamarin-macios/commit/ef3b05478e273ef33ee82ff3fae5e17e6e7f324d
