### ISSUE TITLE
.NET 6 packages do not appear to be signed

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-macios#11952]
### Steps to Reproduce

If I look at the latest NuGet packages from the release branch:

https://github.com/xamarin/xamarin-macios/tree/release/6.0.1xx-preview5

Such as:

https://dev.azure.com/azure-public/vside/_packaging?_a=package&feed=xamarin-impl%40Local&package=Microsoft.iOS.Sdk&protocolType=NuGet&version=14.5.100-preview.5.896%2Bsha.0c741e0b4&view=overview

NuGet.org rejects them under the Microsoft owner (here is the log from a previous version):

```
Response status code does not indicate success: 400 (This package must be signed with a registered certificate.).

Pushing Microsoft.MacCatalyst.Ref.14.5.100-preview.5.894.nupkg to 'https://www.nuget.org/api/v2/package'...

System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (This package must be signed with a registered certificate.).
```

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4874062&view=logs&j=b7af41d0-8bc5-55ff-39bd-8dfae8db1289&t=15ff3feb-dd8d-5446-6216-1f45522b9990&l=125

To get things working for .NET 6 Preview 5, I had our release pipeline sign the packages before uploading to NuGet.org. I'd like to remove this, and just push the packages as-is.

**Comment by rolfbjarne** [comment]
First attempt: https://github.com/xamarin/xamarin-macios/commit/55d10242703f0d91b342bf362d175bdb7f33c724
