### ISSUE TITLE
SymbolStrip calls strip with Windows path

### ISSUE THREAD

**Issue by OlaOsttveit** [xamarin/xamarin-macios#11950]
### Steps to Reproduce

1. Use Visual Studio 16.10.2
2. Create an iOS project
3. Build the project on Windows with msbuild

### Expected Behavior

The SymbolStrip build step calls strip with a relative mac server path

### Actual Behavior

The SymbolStrip build step calls strip with an absolute Windows path

### Environment

Microsoft Visual Studio Professional 2019
Version 16.10.2
VisualStudio.16.Release/16.10.2+31410.357
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA387
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

C# Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.231 (d16-10@8111164)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

Xamarin.iOS and Xamarin.Mac SDK   14.20.0.10 (0e35b2e0b)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```
```

### Build Logs

Using "SymbolStrip" task from assembly "c:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\..\iOS\Xamarin.iOS.Tasks.dll".
Task "SymbolStrip" (TaskId:517)
  Task Parameter:Executable=bin\iPhone\Ad-Hoc\<AppName>\PlugIns\<AppExtensionName>.appex\<AppExtensionName> (TaskId:517)
  Task Parameter:SessionId=e5361af486da597448c7a23de751d118b8012f62475d68605067ab991351dccc (TaskId:517)
  Task Parameter:IsFramework=False (TaskId:517)
  Task Parameter:SymbolFile=D:\Source\<ProjectName>\Source\<AppExtensionName>\obj\iPhone\Ad-Hoc\mtouch-symbols.list (TaskId:517)
  SymbolStrip: 2021-06-16T15:23:57.1905836+02:00 - Started (TaskId:517)
  SymbolStrip: 2021-06-16T15:23:57.1905836+02:00 - Initializing (TaskId:517)
  [xma]: Trying to get a Build Connection for Session 'e5361af486da597448c7a23de751d118b8012f62475d68605067ab991351dccc': Xamarin.Messaging.Build.Client.BuildConnection.e5361af486da597448c7a23de751d118b8012f62475d68605067ab991351dccc, Lifetime: Build (TaskId:517)
  SymbolStrip: 2021-06-16T15:23:57.1905836+02:00 - Initialized (TaskId:517)
  SymbolStrip: 2021-06-16T15:23:57.1905836+02:00 - There's no available inputs to copy to the Mac (TaskId:517)
  SymbolStrip: 2021-06-16T15:23:57.1905836+02:00 - Serializing intputs (TaskId:517)
  SymbolStrip: 2021-06-16T15:23:57.1955903+02:00 - Executing (TaskId:517)
  [xma]: Starting remote task execution for '<AppName>': Xamarin.MacDev.Tasks.SymbolStrip (TaskId:517)
  [xma]: Sending Request Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic xvs/build/execute-task/<AppName>/e5361af002fSymbolStrip (TaskId:517)
  [xma]: Received Response of Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic builde5361af486da597448c7a23de751d118b8012f62475d68605067ab991351dccc23956OlaOs/+/xvs/build/execute-task/<AppName>/e5361af002fSymbolStrip (TaskId:517)
  SymbolStrip: 2021-06-16T15:23:57.6115194+02:00 - Logging messages (TaskId:517)
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -i -s D:/<ProjectName>/Source/<AppExtensionName>/obj/iPhone/Ad-Hoc/mtouch-symbols.list bin/iPhone/Ad-Hoc/<AppName>/PlugIns/<AppExtensionName>.appex/<AppExtensionName>  (TaskId:517)
  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: can't open: D:/<ProjectName>/Source/<AppExtensionName>/obj/iPhone/Ad-Hoc/mtouch-symbols.list (No such file or directory) (TaskId:517)
c:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(1311,3): error MSB6006: "strip" exited with code 1. [D:\Source\<ProjectName>\Source\<AppName>\<AppName>.csproj]
  SymbolStrip: 2021-06-16T15:23:57.6155201+02:00 - Finished (TaskId:517)
Done executing task "SymbolStrip" -- FAILED. (TaskId:517)

**Comment by OlaOsttveit** [comment]
It looks like this was fixed in commit cd9a87cac67937b8286966f92bc81183bd6887a1, but I guess that did not make it to the 16.10.2 release? I assumed it would be by the way it was mentioned in issue [11817](https://github.com/xamarin/xamarin-macios/issues/11817), which was fixed in 16.10.2

**Comment by spouliot** [comment]
> but I guess that did not make it to the 16.10.2 release?

No, release dates are not directly under our control. This (and https://github.com/xamarin/xamarin-macios/issues/11817) will be part of 16.10.3.

**Comment by rolfbjarne** [comment]
> > but I guess that did not make it to the 16.10.2 release?
> 
> No, release dates are not directly under our control. This (and #11817) will be part of 16.10.3.

I'm closing this issue then, since this has been fixed.

**Comment by RobTF** [comment]
Hi,

Is there a workaround for this? We are currently blocked as we are on 16.10.2. Is it possible to downgrade Visual Studio 2019?

**Comment by OlaOsttveit** [comment]
[This workaround](https://github.com/xamarin/xamarin-macios/issues/11817#issuecomment-856236427) worked for me
