### ISSUE TITLE
 .NET 6 error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration

### ISSUE THREAD

**Issue by kdubau** [xamarin/xamarin-macios#12000]
### Steps to Reproduce

1. dotnet new macos
2. dotnet build

### Expected Behavior
Template should build out of the box

### Actual Behavior
```
Build FAILED.

/usr/local/share/dotnet/sdk/6.0.100-preview.5.21302.13/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(181,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [/Users/kylewhite/Workspace/net6p5xmcoreapp/net6p5xmcoreapp.csproj]
    0 Warning(s)
    1 Error(s)
 ```

### Environment

<details>
  <summary>About information</summary>

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.1 (build 71)
Installation UUID: 7b0e0bec-f420-490b-8cd2-547c0eff1d98
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/6.0.100-preview.5.21302.13/Sdks
SDK Versions:
	6.0.100-preview.5.21302.13
	6.0.100-preview.3.21202.5
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	5.0.100-preview.4.20227.5
	5.0.100-preview.3.20216.6
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.201
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.1.100-preview3-014645
	3.1.100-preview1-014459
	3.0.100
	3.0.100-rc1-014190
	3.0.100-preview9-014004
	3.0.100-preview8-013656
	3.0.100-preview5-011568
	2.2.203
	2.1.810
	2.1.701
	2.1.505
	2.1.500
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0-preview.5.21301.5
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	5.0.0-preview.4.20223.9
	5.0.0-preview.3.20214.6
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.3
	3.1.2
	3.1.1
	3.1.0
	3.1.0-preview3.19553.2
	3.1.0-preview1.19506.1
	3.0.3
	3.0.0
	3.0.0-rc1-19456-20
	3.0.0-preview9-19423-09
	3.0.0-preview5-27626-15
	2.2.7
	2.2.4
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.9
	2.1.6

=== .NET Core 3.1 SDK ===

SDK: 3.1.410

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Version: 7.14.0.1 (Visual Studio Enterprise)
Hash: fe0e2c518
Branch: d16-10
Build date: 2021-05-19 08:15:55-0400

=== Xamarin.iOS ===

Version: 14.20.0.1 (Visual Studio Enterprise)
Hash: fe0e2c518
Branch: d16-10
Build date: 2021-05-19 08:15:56-0400

=== Xamarin.Android ===

Version: 11.3.0.1 (Visual Studio Enterprise)
Commit: xamarin-android/d16-10/22fc2b3
Android SDK: /Users/kylewhite/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/kylewhite/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:34 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:52 UTC

=== Build Information ===

Release ID: 810010071
Git revision: 3664adb3ec17b7a29476110bb1c6f7083d43b1ab
Build date: 2021-06-08 13:22:15-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.5.0 Darwin Kernel Version 20.5.0
    Sat May  8 05:10:33 PDT 2021
    root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Feature Switch 0.2
AddinMaker 1.6.0

</details>

### Build Logs

[optimizing-error.binlog.zip](https://github.com/xamarin/xamarin-macios/files/6696155/optimizing-error.binlog.zip)

**Comment by kdubau** [comment]
Adding `<PublishTrimmed>false</PublishTrimmed>` makes the build successful.

**Comment by rolfbjarne** [comment]
Add `<RuntimeIdentifier>osx-x64</RuntimeIdentifier>` instead of disabling the linker.

This will be fixed when #10861 is fixed (so basically a dup that issue).

**Comment by kdubau** [comment]
@rolfbjarne this looks like still an issue in Preview 6 -- should it be in Preview 7?

**Comment by rolfbjarne** [comment]
> @rolfbjarne this looks like still an issue in Preview 6 -- should it be in Preview 7?

Yes, it didn't get in Preview 6, but it's certainly in Preview 7.
