### ISSUE TITLE
MacCatalyst intro tests crashing __TCC_CRASHING_DUE_TO_PRIVACY_VIOLATION__

### ISSUE THREAD

**Issue by rachelkang** [xamarin/xamarin-macios#12033]
### Description
MacCatalyst intro tests crashing https://gist.github.com/rachelkang/d44b277b3432843aba9712ddea901c8f with [__TCC_CRASHING_DUE_TO_PRIVACY_VIOLATION__ ](https://gist.github.com/rachelkang/d44b277b3432843aba9712ddea901c8f#file-crash-txt-L40)

Console.app reveals that `This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSAppleMusicUsageDescription key with a string value explaining to the user how the app uses this data.`

However, inspecting the Info.plist reveals that this key/value pair is already included:
```
Dict {
    CFBundleName = introspection
    NSHomeKitUsageDescription = Testing roofs
    DTSDKName = macosx12.0
    UILaunchStoryboardName = LaunchScreen
    NSAppleMusicUsageDescription = Testing tastes
    CFBundleVersion = 1.0
    BuildMachineOSBuild = 20F71
    DTPlatformName = maccatalyst
    CFBundlePackageType = APPL
    CFBundleShortVersionString = 1.0
    CFBundleSupportedPlatforms = Array {
        MacCatalyst
    }
    CFBundleInfoDictionaryVersion = 6.0
    CFBundleExecutable = introspection
    com.xamarin.ios = Dict {
        Version = 14.99.0.70 (xcode13.0-accessibility-b1: 6ee7efb97)
    }
    UIDeviceFamily = Array {
        2
    }
    CFBundleIdentifier = com.xamarin.introspection
    CFBundleSignature = ????
    LSMinimumSystemVersion = 10.15
    UISupportedInterfaceOrientations = Array {
        UIInterfaceOrientationPortrait
    }
    NSPhotoLibraryUsageDescription = Testing lens
}
```

### Steps to Reproduce

1. Checkout `xcode13.0-accessibility-b1`
2. Run introspection from terminal using `make runner`
3. Run Mac Catalyst > Debug
4. See crash report https://gist.github.com/rachelkang/d44b277b3432843aba9712ddea901c8f

### Expected Behavior

MacCatalyst intro tests crash via 'make runner'

### Actual Behavior

MacCatalyst intro tests should not be crashing via 'make runner'

### Workaround
Need to run introspection manually by launching `/Users/rachelkang/xamarin-ios/xcode13/xamarin-macios/tests/xharness/tmp-test-dir/introspection278/bin/iPhoneSimulator/Debug-maccatalyst/introspection.app`
and need to manually accept NSAppleMusicUsageDescription permissions dialog that pops up

Even after working through this manually, however, permissions don't get fixed afterwards and maccatalyst intro still fails via `test runner` with the same issues, despite privacy settings reflecting the permissions are given

<img width="666" alt="Screenshot 2021-06-28 at 1 31 38 PM" src="https://user-images.githubusercontent.com/21988533/123680809-1dc18000-d817-11eb-9476-bd355271bb61.png">

### Environment

MacBook Pro (16-inch, 2019)
macOS Big Sur version 11.4

### Build Logs

maccatalyst intro crash report https://gist.github.com/rachelkang/d44b277b3432843aba9712ddea901c8f

**Comment by rolfbjarne** [comment]
This error message is telling us exactly what we must do:

> The app's Info.plist must contain an NSAppleMusicUsageDescription key

I'll have a look.

**Comment by rachelkang** [comment]
@rolfbjarne we took a look at the Info.plist (pasted above) and saw that `NSAppleMusicUsageDescription = Testing tastes` is already included

**Comment by rolfbjarne** [comment]
> @rolfbjarne we took a look at the Info.plist (pasted above) and saw that `NSAppleMusicUsageDescription = Testing tastes` is already included

Did you look at the `Info.plist` that's inside the .app bundle? Or one from source? There are a lot of Info.plists in our repository, and in particular for tests it can be easy to get confused.

**Comment by rachelkang** [comment]
I believe it was from the .app bundle? @mandel-macaque can confirm

**Comment by rolfbjarne** [comment]
I just tried your branch, and the `NSAppleMusicUsageDescription` entry is there (but I didn't get the crash either, the test run completed fine (just with other errors)).

> need to manually accept NSAppleMusicUsageDescription permissions dialog that pops up

Does the "Testing tastes" text show up in that dialog?

**Comment by rachelkang** [comment]
yes, the "Testing tastes" text does show in the dialog

**Comment by rolfbjarne** [comment]
Closing, since this doesn't seem to be an issue anymore.
