### ISSUE TITLE
Deployment on Iphone

### ISSUE THREAD

**Issue by Paulpetta668** [xamarin/xamarin-macios#12063]
### Steps to Reproduce

I'm currently working on a simple app in Xamarin.Forms, I tested it on android and recently I moved to MacOs, when I try to deploy it on my iPhone I get that error.

I tried to change the provisioning profile to automatic, but nothing.

![Schermata 2021-07-01 alle 13 13 03](https://user-images.githubusercontent.com/48731892/124115536-34addf80-da6e-11eb-9a54-3b7b468e29cd.png)

### Expected Behavior

Deployment on the IPhone

### Actual Behavior

I got error mt1006 and failed deployment on the IPhone

### Environment

```
```

### Build Logs

 CopyingFile - PercentComplete: 99%
 CreatingStagingDirectory - PercentComplete: 5%
 ExtractingPackage - PercentComplete: 15%
 InspectingPackage - PercentComplete: 20%
 TakingInstallLock - PercentComplete: 20%
 PreflightingApplication - PercentComplete: 30%
 InstallingEmbeddedProfile - PercentComplete: 30%
 VerifyingApplication - PercentComplete: 40%
 ApplicationVerificationFailed: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.o3JNRs/extracted/MS Home.iOS.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)
error MT1006: Could not install the application '/Users/microsolution/Desktop/MS Home/MS Home/MS Home.iOS/bin/iPhone/Debug/device-builds/iphone6.1-12.5.4/MS Home.iOS.app' on the device 'iPhone': AMDeviceSecureInstallApplicationBundle returned: 0xe8008015.

**Comment by rolfbjarne** [comment]
Does it work if you create a new iOS project from a template and just try to run that?

**Comment by Paulpetta668** [comment]
I get the same error

**Comment by rolfbjarne** [comment]
What if you create a new project from a template in Xcode? Xcode will often fix problems automatically, so if that works, try using VSMac again and see if something has changed.

**Comment by Paulpetta668** [comment]
In Xcode I only get some errors about the iOS version of the phone. Can it be the iOS Version? The iPhone is currently updated to iOS 12.5.4.

**Comment by rolfbjarne** [comment]
You should fix any errors in Xcode first, and once you have an Xcode project successfully running on the phone, then try again with VSMac. I'm not sure exactly which kind of version error you're seeing, so I can't answer more specifically to that.

**Comment by mandel-macaque** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Comment by Paulpetta668** [comment]
Hi, I found out that the problem was related to the certificates installed on the device, i was missing the second one: 
![WhatsApp Image 2021-08-09 at 21 51 45](https://user-images.githubusercontent.com/48731892/128766069-586230ee-7e6b-4a51-8261-b24d21a0ab17.jpeg)
