### ISSUE TITLE
iOS/Mac project templates use latest C# language idioms

### ISSUE THREAD

**Issue by mhutch** [xamarin/xamarin-macios#12085]
In .NET 6, the included C# project templates will use the latest language idioms.

See the [parent Epic](https://github.com/dotnet/templating/issues/3359) for details.

Depends on:

- [x] https://github.com/dotnet/sdk/pull/18459
- [x] https://github.com/xamarin/xamarin-macios/issues/12084

**Comment by rolfbjarne** [comment]
From the list from the Epic:

* [ ] Top-level statements: needs to be implemented
* [ ] Global using directives (via SDK driven defaults): tracked in #12084
* [ ] File-scoped namespaces (compiler tracking issue): needs to be implemented
* [x] Target-typed new expressions: I couldn't find any applicable code in our templates
* [x] Nullable reference types: this will be enabled by default on a project level, so no change needed.
* [x] async Main: none of our Main methods are applicable, so no change needed.

**Comment by mhutch** [comment]
Re nulltable types, we need `<Nullable>enable</Nullable>` in the csproj files created by the templates. The SDK itself is not changing the default value (yet). And we need to verify that nothing in the templates produces nullability warnings.
