### ISSUE TITLE
sharpie binding error which could not locate the iphonesimulator 14.5

### ISSUE THREAD

**Issue by jingliancui** [xamarin/xamarin-macios#12138]
[LSTPopView.framework.zip](https://github.com/xamarin/xamarin-macios/files/6834833/LSTPopView.framework.zip)

Framework I have uploaded above is that arch:
`Architectures in the fat file: LSTPopView are: x86_64 arm64 `

sdks:
```
sdk: appletvos14.5     arch: arm64   
sdk: iphoneos14.5      arch: arm64   armv7   
sdk: ios14.5-macabi    arch: x86_64  
sdk: macosx11.3        arch: x86_64  
sdk: watchos7.4        arch: armv7k  
```

sharpie error message:
```
Done. Exiting with error code 1.
error: LSTPopView: framework requires SDK 'iphonesimulator14.5' which is not installed. You may need a newer Xcode.
```

sharpie version:
`3.5.45-0e5ab58b`

xcode version:
`Version 12.5.1 (12E507)`

machine:
`m1 mac`

**Comment by rolfbjarne** [comment]
@dalexsoto any idea about this?

**Comment by jingliancui** [comment]
And I forgot to add addition info that the machine is M1 Mac.

**Comment by mandel-macaque** [comment]
@dalexsoto have you had time for this?

**Comment by dalexsoto** [comment]
@jingliancui can you try removing the info.plist from the LSTPopView.framework and try sharpie again?

**Comment by jingliancui** [comment]
Thanks very much, I will try again this evening.

**Comment by jingliancui** [comment]
@dalexsoto Interesting. It's work after delete info.plist .

**Comment by rolfbjarne** [comment]
Closing as per last comment.
