### ISSUE TITLE
Properly concatenate $(DeviceSpecificOutputPath) in Xamarin.Mac.Common.targets

### ISSUE THREAD

**Issue by KirillOsenkov** [xamarin/xamarin-macios#12158]
When building an app where the `OutputPath` is set to an absolute path, the concatenation of `$(DeviceSpecificOutputPath)` doesn't work as it assumes the path ends with a slash, but the path doesn't end with the slash.

Here it's assigned to a relative path that doesn't end with a slash:
https://github.com/xamarin/xamarin-macios/blob/eea8142e6ba6a8c63f0fb1cc5493e1e0d923d24a/msbuild/Xamarin.Shared/Xamarin.Shared.props#L194

And here it's used assuming it ends with a slash:
https://github.com/xamarin/xamarin-macios/blob/eea8142e6ba6a8c63f0fb1cc5493e1e0d923d24a/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.Common.targets#L187

Every usage of `$(DeviceSpecificOutputPath)` needs to be audited and a slash needs to be added after it (or ideally use Path.Combine like so: `$([System.IO.Path]::Combine('$(DeviceSpecificOutputPath)', 'bundler.stamp'))`).

**Comment by rolfbjarne** [comment]
> Every usage of `$(DeviceSpecificOutputPath)` needs to be audited

Wouldn't it work to just make sure `DeviceSpecificOutputPath` always had a trailing slash?

```xml
<DeviceSpecificOutputPath>$([MSBuild]::EnsureTrailingSlash('$(DeviceSpecificOutputPath)'))</DeviceSpecificOutputPath>
```

**Comment by rolfbjarne** [comment]
That's what happens to OutputPath: https://github.com/dotnet/msbuild/blob/6dba77a45e3af8fe3058040b870bd5a5eb045962/src/Tasks/Microsoft.Common.CurrentVersion.targets#L157
