### ISSUE TITLE
"Please select a valid device before running the application." in Net6

### ISSUE THREAD

**Issue by arivoir** [xamarin/xamarin-macios#12227]
I'm trying to run a basic Xamarin.iOS Net6 application from Visual Studio preview for Windows.

I managed to build the project, but I can't run it.

> 2>------ Deploy started: Project: CoreExplorer, Configuration: Debug Any CPU ------
> ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
> ========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========
> Please select a valid device before running the application.

Unlike, previous Xamarin.iOs I don't get the list of emulators in visual studio

![image](https://user-images.githubusercontent.com/17496741/127010673-57297571-87b7-4b78-a459-71c88d1b8f79.png)

I wonder if this is an unfinished tool issue, or something else, and whether there is a workaround. 
I appreciate if you can help me understand what should I do to run the app in the emulator

> VS bug [#1364354](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1364354)

**Comment by mandel-macaque** [comment]
Tanks for the feedback, I'm going to ping te right teams since this project only focus on the bindings.

/cc @emaf @mauroa

**Comment by arivoir** [comment]
I just updated to preview 7. I see in visual studio 2022 the list of emulators is populated. But when I try to run the application it says

> There aren't any active launch profiles configured for this project.

**Comment by jered-as** [comment]
I have the same issue regarding "There aren't any active launch profiles configured for this project.". This is on a brand new install of Windows, with brand new install of VS 2022 Preview, brand new dotnet workload install android, brand new dotnet new android, open in visual studio, get all the android emulator stuff installed, try to run, and get "There aren't any active launch profiles configured for this project."

I tried dropping in a launchSettings.json with command of "Project" and whatever the new MSIX one is in the maui demo, and in both cases the error becomes that it doesn't know how to launch a project of type android.

Brand new install of VS 2019 has different, worse errors that indicate it has no idea how to deal with this kind of project at all.

**Comment by mauroa** [comment]
Hi everyone, this issue should already be fixed with the recently updated VS 2022 Preview 4. Please give it a try. Thanks
