### ISSUE TITLE
"Optimizing assemblies for size is not supported for the selected publish configuration" in Net6 iOS application

### ISSUE THREAD

**Issue by arivoir** [xamarin/xamarin-macios#12231]
I'm trying to get a iOS Net6 application to run in a device, but I'm getting this message.

> Error	NETSDK1102	Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app.	CoreExplorer	C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets	182	

What should I change to make it a self-contained app?

**Comment by arivoir** [comment]
I tried adding RuntimeIdentifier (because I saw it in one of the maui samples)

`<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>`

but this gives another error


> Error		error HE0003: Could not load the framework 'IBFoundation' (path: /Applications/Xcode.app/Contents/Frameworks/IBFoundation.framework/IBFoundation): not found.		 	0

**Comment by arivoir** [comment]
And effectively that folder is not in xcode application folder
![image](https://user-images.githubusercontent.com/17496741/127034905-49270f23-b294-4e23-8e74-31cd008ccc53.png)

I have Xcode 13 beta 3 installed. Am I missing something?

**Comment by rolfbjarne** [comment]
> I have Xcode 13 beta 3 installed. Am I missing something?

Preview 6 requires the first beta (beta 3 broke us, and was released too late for us to fix it for preview 6).

> I tried adding RuntimeIdentifier (because I saw it in one of the maui samples)

That's the correct workaround (this will be fixed in the next preview, preview 7).

I'm closing this as a dup of #10861, where this was fixed.

**Comment by arivoir** [comment]
Threre is a new beta 4 in the Apple site. 

I didn't find a way to get the beta 1. I guess I can't do other thing but wait untill the preview 7 is released.

**Comment by rolfbjarne** [comment]
> Threre is a new beta 4 in the Apple site.
> 
> I didn't find a way to get the beta 1. I guess I can't do other thing but wait untill the preview 7 is released.

You can find older betas here: https://developer.apple.com/download/all/

**Comment by arivoir** [comment]
Great. Thanks for pointing to it. Any idea when preview 7 will be released? I'm wondering whether I should wait to avoid the trouble of reinstalling everything again.

**Comment by arivoir** [comment]
Preview7 was released. What XCode version is compatible with?

**Comment by rolfbjarne** [comment]
> Preview7 was released. What XCode version is compatible with?

Xcode 13 beta 4.
