### ISSUE TITLE
Ensure `MinimumOSVersion` is is consistent with`SupportedOSPlatformVersion`

### ISSUE THREAD

**Issue by mhutch** [xamarin/xamarin-macios#12336]
We should ensure that the `MinimumOSVersion` property in the Info.plist is consistent with the `SupportedOSPlatformVersion` MSBuild property. `SupportedOSPlatformVersion` is a standardized across platforms and controls the SDK's platform analyzers.

https://github.com/dotnet/designs/search?q=SupportedOSPlatformVersion

A few options:
* emit a build error if the `MinimumOSVersion` property and the `SupportedOSPlatformVersion` MSBuild property do not match
* merge the `SupportedOSPlatformVersion` MSBuild property into the `MinimumOSVersion` plist value during app build
* set the `SupportedOSPlatformVersion` MSBuild property from the `MinimumOSVersion` plist property in a build target at start of build. the downside would be that it would not be available during evaluation.

**Comment by mhutch** [comment]
It appears we do emit the `SupportedOSPlatformAttribute` annotations, so the `SupportedOSPlatformVersion ` property *will* be used by the platform check analyzers when building in Mac/iOS projects.

**Comment by rolfbjarne** [comment]
1. Support a platform-specific version (iOSMinimumVersion, tvOSMinimumVersion, etc), and if set, use it to set SupportedOSPlatformVersion:

    ```xml
	<SupportedOSPlatformVersion Condition="'$(iOSMinimumVersion)'!=''">$(iOSMinimumVersion)</SupportedOSPlatformVersion>
    ```

	One question is which value should take precedence if both are specified: I feel that iOSMinimumVersion is more specific than SupportedOSPlatformVersion, and if I set both, I'd expect iOSMinimumVersion to be applied to iOS project (only).

	We do this before .NET defaults SupportedOSPlatformVersion to TargetPlatformVersion (in Xamarin.Shared.Sdk.props for instance),

2. This means that we'll always have a value for SupportedOSPlatformVersion. Now the question becomes what to do if the Info.plist specifies a value (where it's historically been set). Typically all current projects will have a value set, so this will be an issue for all legacy projects that have been upgraded to .NET.

    * Show an error if the values don't match.
    	* Con: this can be annoying for upgraded projects that already have a value in Info.plist, if that value doesn't happen to match whatever SupportedOSPlatformVersion ends up being.
    	* Pro: predictable behavior. We should be able to write a good error message that tells people what to do.
    * Make Info.plist override whatever is specified in SupportedOSPlatformVersion.
    	* Con: this can result in confusing/incorrect behavior if other build logic reads SupportedOSPlatformVersion before we can set it to the value from the Info.plist.
    	* Pro: this matches how other values in Info.plist work (whatever is set in the Info.plist takes precedence over any MSBuild properties).

    I lean towards the first option, because:

    * It's matches how other platforms work.
    * Any problems with upgraded projects is a one-time cost, and a good error message should mitigate any problems.
    * Less chance of random/confusing/incorrect behavior if someone reads SupportedOSPlatformVersion before we've been able to set it to the correct value.

**Comment by dalexsoto** [comment]
> I lean towards the first option
+1, while painful on migration it is a one time thing instead of the can of worms of option 2

**Comment by filipnavara** [comment]
This was [at least to some extent] addressed with #12516.

**Comment by rolfbjarne** [comment]
I've added a PR that implements support for SupportedOSPlatformVersion, where it writes it to the Info.plist: https://github.com/xamarin/xamarin-macios/pull/12638. If there are any existing values in the Info.plist, then we'll show an error if the two values don't match. That's basically my suggestion here: https://github.com/xamarin/xamarin-macios/issues/12336#issuecomment-903807129, except that it doesn't support platform-specific properties.

**Comment by rolfbjarne** [comment]
@Redth @jonathanpeppers @mattleibow  this change will probably affect existing MAUI tests, since existing projects will have to move any min OS version in the Info.plist to the `SupportedOSPlatformVersion` property in the project file.

**Comment by jonathanpeppers** [comment]
I made a similar change on Android for this: https://github.com/xamarin/xamarin-android/commit/a66013b5c042d2cec265ad0efc9957c315a1f1d0

Maybe we need to do something for dotnet/maui singleproject for this? Maybe dotnet/maui's MSBuild targets should supply the minimum OS versions by default, so you don't have to put them in the `.csproj` for each platform?

**Comment by rolfbjarne** [comment]
> Maybe we need to do something for dotnet/maui singleproject for this? Maybe dotnet/maui's MSBuild targets should supply the minimum OS versions by default, so you don't have to put them in the `.csproj` for each platform?

You don't have to add them to the `.csproj` unless you want a specific version, there's a default value. The problem is that most existing projects will specify a value in the Info.plist, so those will have to move that to the project file (or remove it to get the default). Our templates has this version as an input parameter, so customers will choose the value they want when creating a new project (iow not a problem in that case).

**Comment by rmarinho** [comment]
@rolfbjarne  what's the value we should put on `SupportedOSPlatformVersion ` ? @Redth  was trying but it can't make it work was asking for 15.0

**Comment by rolfbjarne** [comment]
@rmarinho try `14.2`. Things got complicated with Xcode 13 RC 1, because Apple dropped the macOS 12.0 SDK (which is what iOS 15.0 should map to).

**Comment by mattleibow** [comment]
I also notice that 13 is also missing :(
