### ISSUE TITLE
MTOUCH does not include second IOS extension in the app file if the msbuild OutputPath property is set

### ISSUE THREAD

**Issue by stalexig** [xamarin/xamarin-macios#12342]
### Steps to Reproduce

1. Create an IOS project with several extensions (Notification Service Extension and Share Extension in my case)
2. Build the project from the command line using msbuild with the OutputPath parameter.
3. Try to install the resulting app file on the simulator

### Expected Behavior
The application installs without errors

### Actual Behavior
An error occurred while installing on the simulator. The message appears:

Unable To Install “Sprinkler (DEV)”
Please try again later.
Failed to set unique install ID on plugin com.sprinkler.ct.dev.notification-service-extension
Underlying error (domain=MIInstallerErrorDomain, code=4):
	Failed to set unique install ID on plugin com.sprinkler.ct.dev.notification-service-extension

### Environment
msbuild -version = 16.9.0.22901

### Notes
I analyzed the logs and found that when building the main application, at step _CompileToNative, the MTOUCH utility is called. As I understand, MTOUCH should combine the main application and both extensions into one package. Judging by the logs, it constructs the appex file for the Share Extension twice and does not construct any for the Notification Service Extension. Looks like MTOUCH requires each extension to be in a separate folder. But when the OutputPath property is specified, both extensions are built in the specified folder

**Comment by rolfbjarne** [comment]
The problem is that the OutputPath is a global property, and apply to all the projects you're building, and we don't support using the same OutputPath for more than one project.

One way to work around this would be to do set a different property for  project, and then in project set OutputPath if that other property is set:

NotificationServiceExtension.csproj:

```xml
<PropertyGroup>
    <OutputPath Condition="'$(NotificationServiceExtensionOutputPath)' != ''">$(NotificationServiceExtensionOutputPath)</OutputPath>
</PropertyGroup>
```

ShareExtension.csproj:

```xml
<PropertyGroup>
    <OutputPath Condition="'$(ShareExtensionOutputPath)' != ''">$(ShareExtensionOutputPath)</OutputPath>
</PropertyGroup>
```

MainApp.csproj:

```xml
<PropertyGroup>
    <OutputPath Condition="'$(MainAppOutputPath)' != ''">$(MainAppOutputPath)</OutputPath>
</PropertyGroup>
```

and then you build like this:

```shell
$ msbuild /p:MainAppOutputPath=OriginalOutputPath /p:ShareExtensionOutputPath=AnotherPath /p:NotificationServiceExtensionOutputPath=YetAnotherPath
````

**Comment by stalexig** [comment]
The suggested solution solved the problem. Thank you!
