### ISSUE TITLE
dotnet-trace collection doesn't work on macOS

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#12366]
I suspect this could be an entitlement problem.

### Steps to Reproduce

1. Create an empty test application: `mkdir macos-debug; cd macos-debug; dotnet new macos`
2. Build the test application `dotnet build /p:RuntimeIdentifier=osx-x64`
3. Install the `dotnet-trace` tool: `dotnet tool install --global dotnet-trace`
4. Run the app to collect profiling trace: `dotnet-trace collect --profile cpu-sampling --format speedscope --show-child-io -- ./bin/Debug/net6.0-macos/osx-x64/macos-debug.app/Contents/MacOS/macos-debug`

### Expected Behavior

```
Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 

Launching: dotnet /Users/filipnavara/Projects/macos-debug-2/bin/Debug/net6.0/macos-debug-2.dll 
Process        : /usr/local/share/dotnet/dotnet
Output File    : /Users/filipnavara/Projects/macos-debug-2/dotnet_20210805_212528.nettrace

--- application runs here ---

Trace completed.
Writing:	/Users/filipnavara/Projects/macos-debug-2/dotnet_20210805_212528.speedscope.json
Conversion complete
Process exited with code '0'.
```

### Actual Behavior

```
Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 

Launching: ./bin/Debug/net6.0-macos/osx-x64/macos-debug.app/Contents/MacOS/macos-debug 
objc[30545]: Class NSURLSessionDelegate is implemented in both /System/Library/PrivateFrameworks/NetworkServiceProxy.framework/Versions/A/NetworkServiceProxy (0x7ff94bfdde30) and /Users/filipnavara/Projects/macos-debug/bin/Debug/net6.0-macos/osx-x64/macos-debug.app/Contents/MacOS/macos-debug (0x103142a00). One of the two will be used. Which one is undefined.
The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a Diagnostic Port.
DOTNET_DiagnosticPorts="dotnet-trace-30544-20210805_212215.socket"
DOTNET_DefaultDiagnosticPortSuspend=0
Unable to start tracing session - the target app failed to connect to the diagnostics port. This may happen if the target application is running .NET Core 3.1 or older versions. Attaching at startup is only available from .NET 5.0 or later.
[ERROR] System.TimeoutException: The operation has timed out.
   at Microsoft.Diagnostics.NETCore.Client.HandleableCollection`1.Handle(Handler handler, TimeSpan timeout) in /_/src/Microsoft.Diagnostics.NETCore.Client/HandleableCollection.cs:line 154
   at Microsoft.Diagnostics.NETCore.Client.ReversedDiagnosticsServer.Accept(TimeSpan timeout) in /_/src/Microsoft.Diagnostics.NETCore.Client/ReversedServer/ReversedDiagnosticsServer.cs:line 141
   at Microsoft.Internal.Common.Utils.DiagnosticsClientBuilder.Build(CancellationToken ct, Int32 processId, String diagnosticPort, Boolean showChildIO, Boolean printLaunchCommand) in /_/src/Tools/Common/ReversedServerHelpers/ReversedServerHelpers.cs:line 218
   at Microsoft.Diagnostics.Tools.Trace.CollectCommandHandler.Collect(CancellationToken ct, IConsole console, Int32 processId, FileInfo output, UInt32 buffersize, String providers, String profile, TraceFileFormat format, TimeSpan duration, String clrevents, String clreventlevel, String name, String diagnosticPort, Boolean showchildio, Boolean resumeRuntime) in /_/src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs:line 157
```

### Environment

.NET 6 Preview 6, both CoreCLR and Mono runtime

**Comment by filipnavara** [comment]
It's also possible that the temporary directory differs for app bundles and thus the two processes come up with different domain socket path.

**Comment by filipnavara** [comment]
Note that attaching to existing process works (`dotnet-trace collect -p <PID>`). The child process flow creates the domain socket in reverse and it seems to end up in current directory instead of the expected placement in temp directory.

**Comment by filipnavara** [comment]
@spouliot It happens for both MonoVM and CoreCLR identically (the code at the runtime side is shared).

**Comment by rolfbjarne** [comment]
@filipnavara do you happen to know how the two processes are supposed to communicate and how that communication is supposed to be set up?

**Comment by filipnavara** [comment]
It's documented [here](https://github.com/dotnet/diagnostics/blob/b1d8624ad0fd57b0e303ba2a32e73fbdfc6c15ff/documentation/design-docs/ipc-protocol.md) and [here](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/docs/design/mono/diagnostics-tracing.md) (the second document focusing on specific Mono implementation and mobile platforms).

The processes communicate using IPC protocol over Unix domain socket which is supposed to be created in the temp directory with a specific name derived from the process id. There are two different modes how the socket is setup.

The older one (that seems to work) is used for the attach flow. The child process (traced one) creates the domain socket on startup and `dotnet-trace` connects to it and sends the commands.

When starting the profile collection on new child process the flow is reversed. `dotnet-trace` is supposed to create the domain socket server and then tell the child process to connect to it. The information is passed through the `DOTNET_DiagnosticPorts` and `DOTNET_DefaultDiagnosticPortSuspend` environment variables. The child process should then connect to the domain socket created by `dotnet-trace` and once that happens the tracing host should give it a signal over IPC to resume the execution.

Apparently the information in the environment variables seems to be passed correctly and the child process tries to connect but fails with a timeout. It seems to me that there is some mismatch with the path/name for the socket that the processes try to use. I've had few of the files incorrectly created in current directory instead of the temp directory. However, on blank `net6.0` app the same tooling worked locally so there must be some difference.

**Comment by filipnavara** [comment]
From the document linked above:

> ...and the full path to a Unix domain socket on other platforms...

So, it seems that `dotnet-collect` actually sends relative path which becomes invalid if the working directory is changed during the startup. This seems like a bug to me in the diagnostic utilities.

However, even running from the root of the bundle (so the `chdir` in Xamarin startup would be no-op) seems to fail:
```
filipnavara@172-4-1-17 macos-debug.app % dotnet-trace collect --profile cpu-sampling --format speedscope --show-child-io -- ./Contents/MacOS/macos-debug

Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile 
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile 

Launching: ./Contents/MacOS/macos-debug 
objc[34582]: Class NSURLSessionDelegate is implemented in both /System/Library/PrivateFrameworks/NetworkServiceProxy.framework/Versions/A/NetworkServiceProxy (0x7ff94bfdde30) and /Users/filipnavara/Projects/macos-debug/bin/Debug/net6.0-macos/osx-x64/macos-debug.app/Contents/MacOS/macos-debug (0x10505ca00). One of the two will be used. Which one is undefined.
The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a Diagnostic Port.
DOTNET_DiagnosticPorts="dotnet-trace-34580-20210806_135803.socket"
DOTNET_DefaultDiagnosticPortSuspend=0
Unable to start tracing session - the target app failed to connect to the diagnostics port. This may happen if the target application is running .NET Core 3.1 or older versions. Attaching at startup is only available from .NET 5.0 or later.
[ERROR] System.TimeoutException: The operation has timed out.
   at Microsoft.Diagnostics.NETCore.Client.HandleableCollection`1.Handle(Handler handler, TimeSpan timeout) in /_/src/Microsoft.Diagnostics.NETCore.Client/HandleableCollection.cs:line 154
   at Microsoft.Diagnostics.NETCore.Client.ReversedDiagnosticsServer.Accept(TimeSpan timeout) in /_/src/Microsoft.Diagnostics.NETCore.Client/ReversedServer/ReversedDiagnosticsServer.cs:line 141
   at Microsoft.Internal.Common.Utils.DiagnosticsClientBuilder.Build(CancellationToken ct, Int32 processId, String diagnosticPort, Boolean showChildIO, Boolean printLaunchCommand) in /_/src/Tools/Common/ReversedServerHelpers/ReversedServerHelpers.cs:line 218
   at Microsoft.Diagnostics.Tools.Trace.CollectCommandHandler.Collect(CancellationToken ct, IConsole console, Int32 processId, FileInfo output, UInt32 buffersize, String providers, String profile, TraceFileFormat format, TimeSpan duration, String clrevents, String clreventlevel, String name, String diagnosticPort, Boolean showchildio, Boolean resumeRuntime) in /_/src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs:line 157
```

**Comment by filipnavara** [comment]
Ah, running from inside `Contents/MonoBundle` does work. The relative path finally matches the one passed in environment variable since `chdir` becomes a no-op.

This could either a) be fixed in the diagnostic tools which would pass the full path or b) need a rewrite of `DOTNET_DiagnosticPorts` from relative path to full path to make it work after the `chdir`. Due to the syntax in the environment variable being quite complex (optional parameters, TCP scokets, etc.) I think option a) is actually the way to go.

**Comment by filipnavara** [comment]
Fixed by change in diagnostic tools.
