### ISSUE TITLE
[hot reload] Setenv DOTNET_MODIFIABLE_ASSEMBLIES=debug automatically

### ISSUE THREAD

**Issue by lambdageek** [xamarin/xamarin-macios#12378]
Hot reload is enabled if:
1. we're a .net 6 project,
2. debug symbols are included,
3. the interpreter is enabled.

In that case, mtouch should `--setenv=DOTNET_MODIFIABLE_ASSEMBLIES=debug` to enable runtime hot reload support.

Corresponding Android logic: https://github.com/xamarin/xamarin-android/blob/a66013b5c042d2cec265ad0efc9957c315a1f1d0/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1540

**Comment by spouliot** [comment]
There's no `mtouch` for dotnet. I assume you meant `mlaunch` ?

**Comment by rolfbjarne** [comment]
Mac Catalyst apps aren't launched using mlaunch, so it might be better to set this at build time instead.

**Comment by lambdageek** [comment]
> so it might be better to set this at build time instead

yea that's what I was suggesting.  Right now I'm explicitly setting `<MtouchExtraArgs>--setenv=DOTNET_MODIFIABLE_ASSMBLIES=debug</MTouchExtraArgs>` in my .csproj
