### ISSUE TITLE
.NET: we don't support PublishTrimmed=false, so show an error or warning in that case

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#12372]
### Steps to Reproduce

```
dotnet build /p:PublishTrimmed=false
```

This doesn't produce a valid app bundle, so we should show a warning or error asking users to turn trimming on.

**Comment by slluis** [comment]
Also, when the linker crashes, this suggestion is given: "Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.", which won't work.
