### ISSUE TITLE
Workload installation with .NET Preview 7 consistently fails

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#12408]
Related to https://github.com/xamarin/xamarin-macios/pull/12355

### Steps to Reproduce

1. Install .NET 6 SDK Preview 7 (on a clean machine)
2. Run `sudo dotnet workload install maui` or `sudo dotnet workload install macos`

### Expected Behavior

Workloads get successfully installed.

### Actual Behavior

```
Workload installation failed: microsoft.ios.sdk::15.0.100-preview.7182 is not found in NuGet feeds https://api.nuget.org/v3/index.json".
```

**Comment by spouliot** [comment]
I don't have a clean machine and it did not fail (the same way on mine)

```
$ sudo dotnet workload install maui
Password:

Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Installing workload manifest microsoft.net.sdk.tvos version 15.0.100-preview.7.230.
Installing workload manifest microsoft.net.sdk.android version 30.0.100-preview.7.110.
Installing workload manifest microsoft.net.sdk.maui version 6.0.100-preview.7.1345.
Installing workload manifest microsoft.net.sdk.macos version 12.0.100-preview.7.230.
Installing workload manifest microsoft.net.sdk.maccatalyst version 15.0.100-preview.7.230.
Installing workload manifest microsoft.net.sdk.ios version 15.0.100-preview.7.230.
Installing workload manifest microsoft.net.workload.mono.toolchain version 6.0.0-preview.7.21377.19.
Workload installation failed, rolling back installed packs...
Installing workload manifest microsoft.net.sdk.tvos version 15.0.100-preview.6.63.
Installing workload manifest microsoft.net.sdk.android version 30.0.100-preview.6.62.
Installing workload manifest microsoft.net.sdk.maui version 6.0.100-preview.6.1003+sha.5c159aabf-azdo.4977641.
Installing workload manifest microsoft.net.sdk.macos version 12.0.100-preview.6.63.
Installing workload manifest microsoft.net.sdk.maccatalyst version 15.0.100-preview.6.63.
Installing workload manifest microsoft.net.sdk.ios version 15.0.100-preview.6.63.
Installing workload manifest microsoft.net.workload.mono.toolchain version 6.0.0-preview.6.21352.12.
Workload installation failed: Inconsistency in workload manifest 'microsoft.net.workload.mono.toolchain': missing dependency 'Microsoft.NET.Workload.Emscripten'
```

**Comment by spouliot** [comment]
https://github.com/dotnet/installer/blob/main/eng/Versions.props#L168 still refers to the 7xxx previews

c.c. @jonathanpeppers

**Comment by filipnavara** [comment]
The 7xxx previews are published in one of the feeds, so running the following commands is a workaround:
```
dotnet nuget add source https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json                    
dotnet nuget add source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json          
```

`maui-check` was completely botched after update from Preview 6 to Preview 7. It was giving me a lot of errors but I often ended up with something like this:
```
Workload update failed: Workload not found: microsoft-maccatalyst-sdk-full. Known workloads: tvos android android-aot maui maui-mobile maui-desktop maui-core maui-android maui-maccatalyst maui-ios maui-windows macos microsoft-net-sdk-emscripten maccatalyst ios wasm-tools microsoft-net-runtime-android microsoft-net-runtime-android-aot microsoft-net-runtime-ios runtimes-ios microsoft-net-runtime-maccatalyst runtimes-maccatalyst microsoft-net-runtime-macos microsoft-net-runtime-tvos runtimes-tvos microsoft-net-runtime-mono-tooling
update
```
or
```
Repairing workload installation for workloads: microsoft-maccatalyst-sdk-full microsoft-tvos-sdk-full maui microsoft-android-sdk-full microsoft-ios-sdk-full microsoft-macos-sdk-full
Workload repair failed: Workload not found: microsoft-maccatalyst-sdk-full. Known workloads: tvos android android-aot maui maui-mobile maui-desktop maui-core maui-android maui-maccatalyst maui-ios maui-windows macos microsoft-net-sdk-emscripten maccatalyst ios wasm-tools microsoft-net-runtime-android microsoft-net-runtime-android-aot microsoft-net-runtime-ios runtimes-ios microsoft-net-runtime-maccatalyst runtimes-maccatalyst microsoft-net-runtime-macos microsoft-net-runtime-tvos runtimes-tvos microsoft-net-runtime-mono-tooling
```
That's when I deleted everything and started with new installation.

**Comment by jonathanpeppers** [comment]
Yes, we ran into this yesterday. I tried submitting a the manifest package with a patched version number:

https://www.nuget.org/packages/Microsoft.NET.Sdk.iOS.Manifest-6.0.100/15.0.100-preview.7230

But it did not fix it for me.

I would recommend using `maui-check` to install Preview 7 until we have something resolved here.

https://github.com/Redth/dotnet-maui-check

**Comment by filipnavara** [comment]
> I would recommend using maui-check to install Preview 7 until we have something resolved here.

That's what I started with in the first place and it didn't go well. I wiped the whole installation so I cannot tell why it happened anymore.

It was a machine that had .NET 6 Preview 5 and 6 installed previously along with all the workloads installed through `maui-check`. It constantly tried to look for workload `microsoft-maccatalyst-sdk-full` that no longer exists (AFAIK). I wasn't able to track down where it got the reference to it.

**Comment by jonathanpeppers** [comment]
If you had previous .NET previews installed, I would start with this:

https://github.com/dotnet/maui/blob/main/src/Workload/README.md#cleanup-net-6-installs--workloads

Then try `maui-check`.

**Comment by filipnavara** [comment]
> If you had previous .NET previews installed, I would start with this:
> 
> https://github.com/dotnet/maui/blob/main/src/Workload/README.md#cleanup-net-6-installs--workloads
> 
> Then try `maui-check`.

I did that. In fact I wiped the whole `/usr/local/share/dotnet/` and `~/.dotnet` directories and that still was not enough. I think it went away when I also wiped the NuGet cache (`~/.nuget`).

**Comment by jonathanpeppers** [comment]
There is also a new `maui-check` that just came out and has fixes for Preview 7:

https://www.nuget.org/packages/Redth.Net.Maui.Check/0.7.3

**Comment by filipnavara** [comment]
I updated the `maui-check` tool first so I was already running the 0.7.3 version.

**Comment by jonathanpeppers** [comment]
@rolfbjarne @spouliot @filipnavara a regular `dotnet workload install maui` should work now. We were able to push a manifest package to solve the issue.

Let me know if it doesn't work for you, but I think we can close this, thanks.
