### ISSUE TITLE
Building universal macOS app may fail due to different .car file

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#12410]
I'll try to provide more details later but here's the gist of the problem:

- `net6.0-macos` application with several `ImageAsset` elements in .csproj and `<RuntimeIdentifiers>osx-x64;osx-arm64</RuntimeIdentifiers>` in .csproj
- Built using `dotnet build MailClient/MailClient.csproj`

The build failed with the following error:
```
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7228/targets/Xamarin.Shared.Sdk.targets(308,3): error : Unable to merge the file 'Contents/Resources/Assets.car', it's different between the input app bundles. [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7228/targets/Xamarin.Shared.Sdk.targets(308,3): error : App bundle file #1: /Users/filipnavara/Projects/emclient/MailClient/bin/Debug/net6.0-macos/osx-x64/MailClient.app/Contents/Resources/Assets.car [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-preview.7228/targets/Xamarin.Shared.Sdk.targets(308,3): error : App bundle file #2: /Users/filipnavara/Projects/emclient/MailClient/bin/Debug/net6.0-macos/osx-arm64/MailClient.app/Contents/Resources/Assets.car [/Users/filipnavara/Projects/emclient/MailClient/MailClient.csproj]
    354 Warning(s)
    3 Error(s)
```

The files in question have indentical size but the content differs by one byte:
![image](https://user-images.githubusercontent.com/1764393/129042879-4933b9cb-cc83-477b-adc9-8a1bfd075b06.png)

Note that the build takes quite a long time so the `.car` files were built roughly one minute apart from each other.

**Comment by spouliot** [comment]
_by one byte_ :(

what is shown if you run `assetutil -I Assets.car` on each file and diff them ?

**Comment by filipnavara** [comment]
```
diff -u x64-assets.txt arm64-assets.txt
--- x64-assets.txt	2021-08-11 16:21:12.000000000 +0200
+++ arm64-assets.txt	2021-08-11 16:21:25.000000000 +0200
@@ -35,7 +35,7 @@
     "PlatformVersion" : "10.14",
     "SchemaVersion" : 5,
     "StorageVersion" : 17,
-    "Timestamp" : 1628686749
+    "Timestamp" : 1628686414
   },
   {
     "AssetType" : "Color",
```

**Comment by rolfbjarne** [comment]
Yay timestamps 😒 

I see two options:

* Somehow parse the Assets.car files, determine that the differences are insignificant, and just pick one of them.
* Adjust our build logic to only build Assets.car once.

**Comment by spouliot** [comment]
> Somehow parse the Assets.car files, determine that the differences are insignificant, and just pick one of them.

It's a BOM file so the header's location would need quite a bit of parsing, at least versus a static offset into the files :(

https://blog.timac.org/2018/1018-reverse-engineering-the-car-file-format/

**Comment by spouliot** [comment]
```csharp
namespace Wales
{
    class Cardiff
```

well played sir! 😄 

wrt build performance I'd rather use option 2 (_Adjust our build logic to only build Assets.car once_) since building is not free and doing twice just to compare outputs only adds more time.

**Comment by rolfbjarne** [comment]
> build performance I'd rather use option 2

I agree, I'll figure out a way to do that.
