### ISSUE TITLE
.NET 6:  Set RUNTIME_IDENTIFIER and APP_CONTEXT_BASE_DIRECTORY values for AppContext

### ISSUE THREAD

**Issue by akoeplinger** [xamarin/xamarin-macios#12444]
These are used by the BCL.

`RUNTIME_IDENTIFIER` should be the usual`ios-arm64`, `ios-arm` etc. for devices and `iossimulator-x64` or `iossimulator-arm64` etc for simulator. The same applies to tvOS and MacCatalyst.

`APP_CONTEXT_BASE_DIRECTORY` should be the bundle path.

They can be set in https://github.com/xamarin/xamarin-macios/blob/fb63f2388ad740e52df4d3a4f80f43580443cf49/runtime/runtime.m#L2524-L2558

**Comment by rolfbjarne** [comment]
@akoeplinger just to make sure:

`APP_CONTEXT_BASE_DIRECTORY`: the directory where the managed assemblies are? (the "bundle path" is not really a well defined concept, and the correct directory depends on what you're looking for).

**Comment by rolfbjarne** [comment]
Also: is this only for Mono, or does it apply to CoreCLR as well?

**Comment by akoeplinger** [comment]
@rolfbjarne so the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=net-5.0) define it as `the file path of the base directory that the assembly resolver uses to probe for assemblies.` but that doesn't make a lot of sense on mobile because you can't influence the assembly resolution at runtime and Android doesn't even uncompress assemblies on disk.

So my idea was to use the bundle path instead, though I admit I was looking at this from the Android perspective where that is a pretty well-defined path. I guess since you _do_ have assemblies on disk it makes more sense to set it to that directory instead :)

**Comment by akoeplinger** [comment]
And yes, this is true both for Mono and CoreCLR (though not sure whether CoreCLR initializes this property to something internally).
