### ISSUE TITLE
Templates are broken because of changes to implicit namespace support

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#12457]
Ref: https://github.com/dotnet/sdk/issues/19521

I'm disabling the template tests, because there are outstanding questions before we can make it work:

* Do we have to implement different logic for C# vs VB? Ref: https://github.com/dotnet/sdk/issues/19521#issuecomment-900068396
* Do we keep our own property for disabling the implicit namespace support, or do we use a single one? https://github.com/dotnet/sdk/issues/19521#issuecomment-897231225

Ref: https://github.com/xamarin/xamarin-macios/commit/a688b92044c5059a675e4d0f17e6060e16abc5ed
Ref: https://github.com/xamarin/xamarin-macios/pull/12357

**Comment by jonathanpeppers** [comment]
If you want to compare with the Android side: https://github.com/xamarin/xamarin-android/pull/6118

You probably want to put these in `AutoImports.props`, and check that `$(TargetPlatformIdentifier)` matches:

```xml
<ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'iOS' and ('$(ImplicitUsings)' == 'true' or '$(ImplicitUsings)' == 'enable') ">
  <!-- Or what these actually should be -->
  <Using Include="Foundation" />
  <Using Include="UIKit" />
</ItemGroup>
```

The `<ItemGroup>` need to be evaluated before the user's `.csproj` file, so they can remove a single `<Using Remove="UIKit" />`, for example.
