### ISSUE TITLE
Investigate calendar removal by the linker for macOS

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#12468]
Investigate whether this difference for macOS is expected or not:

https://github.com/xamarin/xamarin-macios/blob/ef61ab51f6df015c21471e9c339b73f121d63195/tests/linker/mac/link%20all/LinkAllTest.cs#L32-L40

It's unclear how dotnet uses ICU (internally os system) on macOS, c.c. @steveisok

_Originally posted by @spouliot in https://github.com/xamarin/xamarin-macios/pull/12436#discussion_r689533524_

**Comment by filipnavara** [comment]
Ref: https://github.com/mono/mono/commit/42c8d96762d7d483fb45f2f87dbed043ea7af31a
Ref: https://github.com/mono/mono/blob/bdd772531d379b4e78593587d15113c37edd4a64/mcs/class/corlib/System.Globalization/CultureInfo.cs#L1058-L1083
Ref: https://github.com/dotnet/runtime/blob/cd1b4cff818a700b6ff82fde024c65b036979894/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureInfo.cs#L832-L862

Classic Mono used to do indirection on the calendar type and then loading it through reflection. This optimization is not present in dotnet/runtime but it's also a little bit more difficult to prove when it is possible to do it safely.
