### ISSUE TITLE
Plan for Xcode 14 preview packages for .NET 6+ 

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#12472]
Context: https://github.com/dotnet/designs/blob/main/accepted/2021/preview-features/preview-features.md

To opt into an iOS preview (say iOS 15.1) , a project would do:

```xml
<PropertyGroup>
  <TargetFramework>net6.0-ios15.1</TargetFramework>
  <EnablePreviewFeatures>True</EnablePreviewFeatures>
</PropertyGroup>
```

Right now we have packs such as:

* `Microsoft.iOS.Ref`
* `Microsoft.iOS.Runtime.[rid]`

We could produce additional "preview" packages:

* `Microsoft.iOS.Preview.Ref`
* `Microsoft.iOS.Preview.Runtime.[rid]`

The `Xamarin.iOS.dll` and other files inside the preview packs will have:

```csharp
[assembly: RequiresPreviewFeatures]
```

This way it is obvious you are opting into preview packages. You will get a C# compiler error if you simply put `net6.0-net14.1` without `$(EnablePreviewFeatures)`.

Android's proposal: https://github.com/xamarin/xamarin-android/issues/6176

**Comment by dalexsoto** [comment]
We did not manage to do previews.
