### ISSUE TITLE
UIFont.FromDescriptor does not respect traits

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#12505]
### Steps to Reproduce

Recently, after an update in maui (https://github.com/dotnet/maui/pull/1939), our tests started failing with this code:

```csharp
var descriptor = new UIFontDescriptor()
	.CreateWithFamily("Lobster Two")
	.CreateWithAttributes(new UIFontAttributes
	{
		Traits = new UIFontTraits
		{
			Weight = 0.40f,
			SymbolicTrait = UIFontDescriptorSymbolicTraits.Bold,
		},
	});

var result = UIFont.FromDescriptor(descriptor, 30);

var weight = result.FontDescriptor.SymbolicTraits; // <- NOT BOLD
```

I have attached a zip with both the classic xamarin app as well as the net6 app. This was working fine (like classic) before the last macios bump we had.

### Expected Behavior

The font preserves the font weight/traits.

### Actual Behavior

The font is just the default

### Environment

```
% iOS version: 15.0.100-rc.1.512

% dotnet --info 
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21418.8
 Commit:    78a1bc32ce

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-rc.1.21418.8/

Host (useful for support):
  Version: 6.0.0-rc.1.21417.1
  Commit:  14b34eb02b

.NET SDKs installed:
  3.1.411 [/usr/local/share/dotnet/sdk]
  3.1.412 [/usr/local/share/dotnet/sdk]
  5.0.302 [/usr/local/share/dotnet/sdk]
  5.0.400 [/usr/local/share/dotnet/sdk]
  6.0.100-rc.1.21418.8 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21417.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21417.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Example Project (If Possible)

[TestFonts.zip](https://github.com/xamarin/xamarin-macios/files/7024749/TestFonts.zip)

**Comment by spouliot** [comment]
It's a custom font bundled in the app. Since there's no code change between the legacy and net6 SDK I'm fairly sure this is due to some change inside the msbuild files.

**Comment by spouliot** [comment]
c.c. @jonathanpeppers I think you did the (original) font embedding changes right ?

**Comment by jonathanpeppers** [comment]
@spouliot I think you might be thinking of splash screens?

The diff has a lot of commits: https://github.com/xamarin/xamarin-macios/compare/8bd702c...0b01c40

@mattleibow if you look inside the `.app`, is the custom font file inside? Could something have changed with how files are copied into the bundle?

**Comment by spouliot** [comment]
> @spouliot I think you might be thinking of splash screens?

Could be :)
I remember those things changed for Single Project... and that you were involved... but I might be wrong about the scope

**Comment by mattleibow** [comment]
I just wanted to mention that this is happening with a plain iOS app. The sample is not a MAUI app.

**Comment by mattleibow** [comment]
I am looking at things closer and I got more info. The net6 app just put things in the Resources folder on disk, and did not add it to the csproj. I thought it was automatic with all under Resources is a BundleResource. Is this a bug?

Also, we are using the `_PartialAppManifest` item group, but that seems to have been replaced with `PartialAppManifest` (no `_`)? Is this a thing?

**Comment by mattleibow** [comment]
Opened an issue for the fonts not auto-copying: https://github.com/xamarin/xamarin-macios/issues/12536

**Comment by mattleibow** [comment]
Closing this due to a bug and a undetected change. Opened an issue for the bug.

Thanks for the packaging tip @jonathanpeppers !

**Comment by filipnavara** [comment]
> I thought it was automatic with all under Resources is a BundleResource.

[Nope](https://github.com/xamarin/xamarin-macios/blob/main/dotnet/DefaultCompilationIncludes.md). It would not even make sense to include everything since it's always been the default directory for managed .resx/.cs files.
