### ISSUE TITLE
[.NET 6] Merged app bundles lack information about app icon

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#12542]
### Steps to Reproduce

1. Create macOS application with `<RuntimeIdentifiers>osx-x64;osx-arm64</RuntimeIdentifiers>`
2. Set application icon using `XSAppIconAssets` in Info.plist
3. Build the application

### Expected Behavior

Both individual RID versions and merged universal version of the app have app icon.

### Actual Behavior

Merged app is missing the app icon because `Info.plist` lacks these values:
```
--- info-arm64.txt	2021-08-25 14:33:17.000000000 +0200
+++ info-merged.txt	2021-08-25 14:33:34.000000000 +0200
@@ -55,14 +55,12 @@
     CFBundleShortVersionString = 1.0
     NSSupportsAutomaticGraphicsSwitching = true
     MonoBundleExecutable = MailClient.exe
-    CFBundleIconFile = AppIcon
     NSAppTransportSecurity = Dict {
         NSAllowsArbitraryLoads = true
     }
     CFBundleInfoDictionaryVersion = 6.0
     NSAppleScriptEnabled = true
     CFBundleExecutable = MailClient
-    CFBundleIconName = AppIcon
     CFBundleURLTypes = Array {
         Dict {
             CFBundleURLName = Email Address URL
```

### Environment

.NET 6 RC 1 (6.0.0-rc.1.21414.4), up-to-date workloads from feed

**Comment by rolfbjarne** [comment]
This might fix it: #12516 (although adding a test case for this issue would be a good idea)

**Comment by filipnavara** [comment]
I'll check once it gets merged.

**Comment by filipnavara** [comment]
Confirmed to be fixed.
