### ISSUE TITLE
Cyber security issues - IPA Binary Analysis in Xamarin forms app

### ISSUE THREAD

**Issue by vallial** [xamarin/xamarin-macios#12613]
Hi All,

Recently our Xamarin.forms application has gone through a Cyber Security Analysis Certification(CSAC) and we got issues in Xamarin.iOS part in IPA Binary Analysis.

![image](https://user-images.githubusercontent.com/89967681/131809257-4bc4f1c8-d77d-4ad3-a447-bcdd6018891a.png)

Please help us to find the solution for above mentioned issues.

Thanks,
Valli.

**Comment by filipnavara** [comment]
Duplicate of https://github.com/xamarin/xamarin-macios/issues/12612.

**Comment by spouliot** [comment]
as mentioned, this is a dupe of #12612
