### ISSUE TITLE
[msbuild] Remove code related to `!IsXcode8`

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#12669]
I think it's safe to assume Xcode 7.x won't run on Big Sur developer's computers.
It's also unlikely that many other changes we had, recently, would still work on 7.x (or earlier)

```
$ git grep IsXcode8
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSdkLocationCoreTaskBase.cs:               public bool IsXcode8 {
msbuild/Xamarin.MacDev.Tasks.Core/Tasks/DetectSdkLocationCoreTaskBase.cs:                       IsXcode8 = AppleSdkSettings.XcodeVersion.Major >= 8;
msbuild/Xamarin.Shared/Xamarin.Shared.targets:                  Condition="'$(IsMacEnabled)' == 'true' and '$(_IsXcode8)' == 'false'"
msbuild/Xamarin.Shared/Xamarin.Shared.targets:                  <_ForgedMetal Condition="'$(_IsXcode8)' == 'false'" Include="$(DeviceSpecificIntermediateOutputPath)metal\default.metal-ar" />
msbuild/Xamarin.Shared/Xamarin.Shared.targets:                  <_ForgedMetal Condition="'$(_IsXcode8)' == 'true'" Include="@(_SmeltedMetal)" />
msbuild/Xamarin.Shared/Xamarin.Shared.targets:                  <Output TaskParameter="IsXcode8" PropertyName="_IsXcode8" />
```

**Comment by filipnavara** [comment]
Something like this: https://github.com/filipnavara/xamarin-macios/pull/new/IsXcode8 ?

**Comment by spouliot** [comment]
@filipnavara hit "Comment" too soon ? The link not working :)

**Comment by filipnavara** [comment]
Hmm, it is working for me. How about this one: https://github.com/xamarin/xamarin-macios/commit/e98c366a7c9c663180d3cf46ad2472458066f0dc ?

**Comment by spouliot** [comment]
works, the other one is likely working only for you (based on your fork branch name)

**Comment by filipnavara** [comment]
Actually I forgot to save couple of files, so both commits here: https://github.com/xamarin/xamarin-macios/compare/main...filipnavara:IsXcode8?expand=1

**Comment by spouliot** [comment]
@filipnavara yup, pretty much what I would have expected. Please PR so we can see if tests agrees :)
