### ISSUE TITLE
Generator issue when extension methods with Bind attribute

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#12727]
While digging into https://github.com/xamarin/xamarin-macios/issues/12708 I came across this:

Our code generator is generating this:

```
[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
 895     public static bool GetLowPower (this IMTLDevice This)
 896     {
 897       if (global::ObjCRuntime.Runtime.IsARM64CallingConvention) {
 898         return global::ObjCRuntime.Messaging.bool_objc_msgSend (This.Handle, Selector.GetHandle ("lowPower"));
 899       } else {
 900
900         return global::ObjCRuntime.Messaging.bool_objc_msgSend (This.Handle, Selector.GetHandle ("lowPower"));
 901       }
```

from:

```
[Export ("lowPower")]
bool LowPower { [Bind ("isLowPower")] get; }
```

Note lowPower vs isLowPower in the extension method. 

Discussions with @mandel-macaque leads me to believe this is a generator bug.

**Comment by chamons** [comment]
FYI @rolfbjarne @mandel-macaque

**Comment by rolfbjarne** [comment]
Yes, this is a generator bug, my guess is that our property -> Get/Set methods conversion for optional members for protocols aren't taking into account any Bind attributes.
