### ISSUE TITLE
[azdo] add a way to push packages to NuGet.org

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-macios#12726]
Context: https://github.com/xamarin/xamarin-android/pull/6279
Context: https://devdiv.visualstudio.com/DevDiv/_build?definitionId=14596&_a=summary

I have been using temporary pipeline for pushing all .NET 6 workload packs from xamarin-macios and xamarin-android to NuGet.org. I will keep this around, if we ever need it -- but I hope to stop using it going forward.

Going forward, we want to simply add a button to each repo's build, such as:

![image](https://user-images.githubusercontent.com/840039/133280234-cb1f6c54-13f5-46fb-b391-24c0c042d2c5.png)

![image](https://user-images.githubusercontent.com/840039/133280308-324cddf8-1a19-4044-b45f-1b1b94970765.png)

![image](https://user-images.githubusercontent.com/840039/133280378-819da092-86fa-4f90-89cc-686c1aca3e39.png)

We have a timeout of 30 minutes, but you can just rerun the stage to trigger it if needed.

I think the same workflow would work for xamarin-macios. And we could just push this button on release day going forward?

/cc @dalexsoto @mandel-macaque

**Comment by rolfbjarne** [comment]
@mandel-macaque has this been implemented now?

**Comment by dalexsoto** [comment]
This is done
