### ISSUE TITLE
Different results when calling GetINativeObject and GetNSObject when object is not owned by the caller but true parameter is specified.

### ISSUE THREAD

**Issue by awattar** [xamarin/xamarin-macios#12732]
When calling generic GetINativeObject and GetNSObject for the same pointer (that represents NSObject type) with owns parameter set to true (but the caller does not own the object) the first will return normally because it does not use owns in the below code path and just constructs a new object

https://github.com/xamarin/xamarin-macios/blob/2b7dc07d20fc06344d7f164af8934f5e755572c2/src/ObjCRuntime/Runtime.cs#L1471

or it does not try to release anything like generic GetNSObject tries right after getting the object

https://github.com/xamarin/xamarin-macios/blob/2b7dc07d20fc06344d7f164af8934f5e755572c2/src/ObjCRuntime/Runtime.cs#L1280

which throws in this scenario.

I believe it should be somehow unified.

**Comment by chamons** [comment]
Talked to Rolf. I can confirm this is an issue, and that the fix likely involves a change here

https://github.com/xamarin/xamarin-macios/blob/2b7dc07d20fc06344d7f164af8934f5e755572c2/src/ObjCRuntime/Runtime.cs#L1471

add if (owns) { // DangerousRelease on result} 

@awattar - How did you hit this case?
