### ISSUE TITLE
 Xamarin.iOS 15 download link?

### ISSUE THREAD

**Issue by amirvenus** [xamarin/xamarin-macios#12750]
### Steps to Reproduce

1. Download XCode 13 RC from Apple Developer website. 
2. Run a project and test it on an iOS 15 device such as iPhone 13. 

### Expected Behavior

It should run and deploy to the simulator

### Actual Behavior

It throws this error:

  Xamarin.iOS 14.20.0 does not support a deployment target of 15.0 for iOS (the maximum is 14.5). Please select an older deployment target in your project's Info.plist or upgrade to a newer version of Xamarin.iOS.

**Comment by amirvenus** [comment]
I was wondering if there is a direct link to download the Xamarin.iOS 15 version? 
As even choosing Preview channel on VS4M does not offer any new updates!

**Comment by filipnavara** [comment]
Apple made a last minute change by removing the macOS 12 SDK in the Xcode 13 RC. At the moment there's no release with the appropriate support.

**Comment by chamons** [comment]
We are actively in work in [this branch](https://github.com/xamarin/xamarin-macios/tree/xcode13-ios) as the macOS SDK removal has caused us to be unable to work in main (without reverting a large number of macOS changes).

As @filipnavara noted, we do not yet have a preview with support out for use.
