### ISSUE TITLE
Extra ImageAssets copy during build.

### ISSUE THREAD

**Issue by yaliashkevich** [xamarin/xamarin-macios#12783]
Assets clone logic introduced in https://github.com/xamarin/xamarin-macios/pull/1543 leads to redundant assets copy even if there is no "Link" metadata defined.

That happens due to improper check for "Link" existence. It should check for empty string instead as  [`TaskItem.GetMetadata(string metadataName)`](https://github.com/dotnet/msbuild/blob/main/src/Utilities/TaskItem.cs) always returns non-null value.
https://github.com/xamarin/xamarin-macios/blob/6f9a8ebbbdcd60aed71b39a11838d121edc26044/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ACToolTaskBase.cs#L224

**Comment by chamons** [comment]
Reviewing the code you linked, this does appear to be correct:

https://github.com/dotnet/msbuild/blob/main/src/Utilities/TaskItem.cs#L444

Do you have a example use case where this behavior is easily observed?

**Comment by yaliashkevich** [comment]
You can observe `cloned-assets` folder under project `obj`
Here is default project created from VS template:
[assetclone.zip](https://github.com/xamarin/xamarin-macios/files/7209688/assetclone.zip)
```
    <ItemGroup>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Contents.json">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon1024.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon167.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon120.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon152.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon180.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon29.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon40.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon58.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon76.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon80.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon87.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon20.png">
            <Visible>false</Visible>
        </ImageAsset>
        <ImageAsset Include="Assets.xcassets\AppIcon.appiconset\Icon60.png">
            <Visible>false</Visible>
        </ImageAsset>
    </ItemGroup>
```
<img width="435" alt="clone" src="https://user-images.githubusercontent.com/3542523/134324064-c92676b8-5ebd-4f93-b222-0c702e936ee6.png">

**Comment by chamons** [comment]
Sorry for the delay, I missed your response.

Here are binary logs of your project:

[logs.zip](https://github.com/xamarin/xamarin-macios/files/7384070/logs.zip)

In reviewing it, it seems we aren't duplicating this file on the (no-op) second build. 

Are you suggesting that the first build is incorrect, or something else. Sorry, I'm not tracking the specific behavior the issue is reporting.
