### ISSUE TITLE
Notarized FinderSync extension is not registered after installation

### ISSUE THREAD

**Issue by vincentSerrano** [xamarin/xamarin-macios#12785]
Hello !

I have been experiencing a problem for several weeks :
My extension works as expected in Visual Studio, but is not registered when I install the package 
I can't see what's wrong. Everything leads me to believe that the code works as expected (because when debugging in Visual Studio, I have the badges displayed) but that the problem is in the notarization process.

Does anybody have an idea to determine what kind of problem it can be ?

Thanks in advance.

### Steps to Reproduce

1. Generate my app with Visual studio 2019 (Cocoa app + FinderSync extension)
 * The main app writes a file in a shared location (via the application group)  
 * The extension read the file to determine the badge to display
2. Start in Debug
=> FinderSync extension is displayed as expected
4. Generate a notarized package (steps details juste bellow)
5. Install package 

```
codesign  --force --verify --verbose --sign "Developer ID Application:xxx" --options runtime --entitlements ../../../cpy.app.Badges/Entitlements.plist myapp.app/Contents/Plugins/cpy.myapp.Badges.appex/Contents/MonoBundle/libmono-native.dylib
codesign  --force --verify --verbose --sign "Developer ID Application: xxx" --options runtime --entitlements ../../../cpy.myapp.Badges/Entitlements.plist myapp/Contents/Plugins/app.myapp.Badges.appex/Contents/MonoBundle/libMonoPosixHelper.dylib
codesign --deep --force --verify --verbose --sign "Developer ID Application:xxx" --options runtime --entitlements ../../Entitlements.plist myapp.app
productbuild --sign "Developer ID Installer:xxx" --component myapp.app /Applications myapp.pkg
xcrun altool -type osx --notarize-app --primary-bundle-id "com.cpy.myapp" --username "xx@yyy" --password "something" --file myapp.pkg
xcrun altool --notarization-info $1 --username "xx@yyy" --password "something"
xcrun stapler staple -v app.pkg
```

### Expected Behavior
FinderSync extension is registered in system extensions 

### Actual Behavior
FinderSync extension isn't registered in system extensions 

### Environment

https://gist.github.com/chamons/d7854a7c537441b3ab7fa7b2a359d86e

### Build Logs

https://gist.github.com/chamons/0896d28ac6134772d99b80a47ef7a04f

### Example Project (If Possible)

If needed, I will try to isolate the behavior in a sample project.

**Comment by chamons** [comment]
Thanks for the report. I've edited it to replace some long sections with gists to make it easier to read. 

Have you tried launching your application and _then_ checking to see if it was registered. Last time I looked at extensions, things did not show up before first launch, and that was an Apple behavior.

**Comment by vincentSerrano** [comment]
Thanks @chamons for your answer !
I've done many manipulations but can't remember if I tried this !
I'll give a try and give a feedback thanks !

**Comment by rachelkang** [comment]
We will be closing this issue as it has been over 30 days since we have not received the requested information. If you are still experiencing this issue after trying the steps suggested above, please provide all the requested information and then click the Reopen Issue button. Thank you!
