### ISSUE TITLE
Add support for alternate app icons, and MSBuild items/properties to include them in Info.plist

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-macios#12790]
iOS Apps support the ability to [set alternate app icons](https://developer.apple.com/documentation/uikit/uiapplication/2806818-setalternateiconname?language=objc)

Currently there's an info.plist key `XSAppIconAssets` which specifies which icon is to be used as the primary/default app icon.

Can we modernize how we include these assets by allowing support for MSBuild items/properties, and also include the ability to include multiple icon assets and have them all registered properly in the info.plist?

Something like this:

```xml
<ItemGroup>
  <!-- One icon can be primary -->
  <BundleResource Include="Assets.xcassets/appicon.appiconset" RegisterPrimaryBundleIcon="True" />

  <!-- Zero or more alternate icons -->
  <BundleResource Include="Assets.xcassets/alternateappicon.appiconset" RegisterAlternateBundleIcon="True" />
  <BundleResource Include="Assets.xcassets/alternateappicon2.appiconset" RegisterAlternateBundleIcon="True" />
</ItemGroup>
```

In the Info.plist would generate something like this:

```xml
<key>CFBundleIcons</key>
<dict>
  <key>CFBundlePrimaryIcon</key>
  <dict>
    <key>CFBundleIconName>
    <string>appicon</string>
    <key>CFBundleIconFiles</key>
    <array><!-- ... --></array>
  </dictionary>
  
  <key>CFBundleAlternateIcons</key>
  <dict>
    <key>alternateappicon</key>
    <dict>
      <key>CFBundleIconFiles</key>
      <array><!-- ... --></array>
    </dict>
    <key>alternateappicon2</key>
    <dict>
      <key>CFBundleIconFiles</key>
      <array><!-- ... --></array>
    </dict>
  </dict>
</dict>
```

**Comment by yuriibabii** [comment]
Hey guys, I found a hackish way to do that. You might want to check it out:
https://stackoverflow.com/a/77050207/6157156

**Comment by lakhan-bairawat** [comment]
how we can achieved  this in android
like :- iOS Apps support the ability to [set alternate app icons]
