### ISSUE TITLE
.NET: Add support for iossimulator-arm64 and tvossimulator-arm64

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#12820]
Title says it all, they are currently not enabled in workload manifests and explicitly forbidden by MSBuild checks.

**Comment by rolfbjarne** [comment]
This needs runtime packs first (they might be available already, I haven't checked).

**Comment by filipnavara** [comment]
I think they are available because that's what I use for testing on the dotnet/runtime side.

**Comment by rolfbjarne** [comment]
Yes, looks like there are packages:

* https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.NETCore.App.Runtime.Mono.tvossimulator-arm64&protocolType=NuGet&version=6.0.0-rtm.21472.13
* https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64&protocolType=NuGet&version=6.0.0-rtm.21472.13

This still needs significant work on our side though, a list off the top of my head:

* Build for these new architectures in runtime/
* Run building and running existing tests suites using these new architectures.
    * Build for these new architectures in tests/tests-libraries
    * This probably means coming up with something in xharness to be able to execute these tests (maybe something similar to the current 32-bit/64-bit split logic we have now).
* Add them to the list of of RIDs we support.
