### ISSUE TITLE
My iPhone 12 can be debugged, but my iPad can't. is this because I'm not authorized?

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/xamarin-macios#12834]
VerifyingApplication - PercentComplete: 40%
 ApplicationVerificationFailed: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Ij6FVF/extracted/InnoADLMedical.iOS.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)
error MT1006: Could not install the application '/Users/xuzhibin/Downloads/InnoADLMedical-master/InnoADLMedical/InnoADLMedical.iOS/bin/iPhone/Debug/device-builds/ipad11.6-15.0/InnoADLMedical.iOS.app' on the device 'iPad': AMDeviceSecureInstallApplicationBundle returned: 0xe8008015.

**Comment by chamons** [comment]
Thanks for the report.

This error is expected if your provisioning profile is misconfigured, and comes from Apple's tooling.

Consider reading [this](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/), in particular [this](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/#provisioning-your-device) section for steps on how to proceed.
