### ISSUE TITLE
Error MT0180

### ISSUE THREAD

**Issue by RossAnderson55** [xamarin/xamarin-macios#12855]
### Steps to Reproduce

1. Compile the application
2. 
3. 

### Expected Behavior

Complete compile

### Actual Behavior

Failed

### Environment

/Users/ross/Projects/Evado.Mobile/Version 1/Evado.Mobile.iOS/MTOUCH: Error MT0180: This version of Xamarin.iOS requires the iOS 14.5 SDK (shipped with Xcode 12.5). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). (MT0180) (Evado.Mobile.iOS)

Error not listed in the MT error list.

**Comment by chamons** [comment]
Thanks for the feedback.

As noted in the error:

> This version of Xamarin.iOS requires the iOS 14.5 SDK (shipped with Xcode 12.5). 

Your choices are:

> Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs).

If you believe this report is in error, please create a new issue with a filled out template showing the build log, versions of software installed, and a sample showing the behavior in question.
