### ISSUE TITLE
error MT2001: Could not link assemblies. Reason: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ShenbagaPriya22** [xamarin/xamarin-macios#12862]
### Steps to Reproduce

1. Updated to iOS 13 Tool chain and installed Xamarin.iOS version 15.0.0.6.pkg
2. Built our Xamarin iOS project 
 - error MT2001: Could not link assemblies. Reason: Object reference not set to an instance of an object

### Expected Behavior
It should build successfully without any issue.

### Actual Behavior
Build is failing.
### Environment

Work:
I tried adding "-v -v -v -v" to the MTouch arguments to get additional details. After this got below inner exception details.

**error MT2001: Could not link assemblies. Reason: Object reference not set to an instance of an object**
1>  		 (TaskId:144)
1>  --- inner exception (TaskId:144)
1>  System.NullReferenceException: Object reference not set to an instance of an object (TaskId:144)
1>    at MonoTouch.Tuner.RegistrarRemovalTrackingStep.EndProcess () [0x0009f] in /Users/builder/azdo/_work/1/s/xamarin-ma
1>  cios/tools/linker/RegistrarRemovalTrackingStep.cs:188  (TaskId:144)
1>    at Mono.Linker.Steps.BaseStep.Process (Mono.Linker.LinkContext context) [0x00040] in /Users/builder/azdo/_work/1/s/
1>  xamarin-macios/builds/mono-ios-sdk-destdir/ios-sources/external/linker/src/linker/Linker.Steps/BaseStep.cs:63  (TaskI
1>  d:144)
1>    at Mono.Linker.Pipeline.ProcessStep (Mono.Linker.LinkContext context, Mono.Linker.Steps.IStep step) [0x0000f] in /U
1>  sers/builder/azdo/_work/1/s/xamarin-macios/builds/mono-ios-sdk-destdir/ios-sources/external/linker/src/linker/Linker/
1>  Pipeline.cs:134  (TaskId:144)
1>    at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x00011] in /Users/builder/azdo/_work/1/s/xamari
1>  n-macios/builds/mono-ios-sdk-destdir/ios-sources/external/linker/src/linker/Linker/Pipeline.cs:126  (TaskId:144)
1>    at MonoTouch.Tuner.Linker.Process (Mono.Linker.Pipeline pipeline, MonoTouch.Tuner.MonoTouchLinkContext context) [0x
1>  00002] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Tuning.cs:31  (TaskId:144)
1>  --- (TaskId:144)
1>    at MonoTouch.Tuner.Linker.Process (Mono.Linker.Pipeline pipeline, MonoTouch.Tuner.MonoTouchLinkContext context) [0x
1>  00020] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Tuning.cs:36  (TaskId:144)
1>    at MonoTouch.Tuner.Linker.Process (MonoTouch.Tuner.LinkerOptions options, MonoTouch.Tuner.MonoTouchLinkContext& con
1>  text, System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies) [0x000de] in /Users/builder/azdo/
1>  _work/1/s/xamarin-macios/tools/mtouch/Tuning.mtouch.cs:61  (TaskId:144)
1>    at Xamarin.Bundler.Target.LinkAssemblies (System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assembl
1>  ies, System.String output_dir, System.Collections.Generic.IEnumerable`1[T] sharedCodeTargets) [0x00256] in /Users/bui
1>  lder/azdo/_work/1/s/xamarin-macios/tools/mtouch/Target.mtouch.cs:517  (TaskId:144)
1>    at Xamarin.Bundler.Target.ManagedLink () [0x00719] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mtouch/Tar
1>  get.mtouch.cs:666  (TaskId:144)
1>    at Xamarin.Bundler.Target.ProcessAssemblies () [0x000c2] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mtou
1>  ch/Target.mtouch.cs:869  (TaskId:144)
1>    at Xamarin.Bundler.Application.ProcessAssemblies () [0x0002f] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools
1>  /mtouch/Application.mtouch.cs:927  (TaskId:144)
1>    at Xamarin.Bundler.Application.BuildManaged () [0x00001] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mtou
1>  ch/Application.mtouch.cs:363  (TaskId:144)
1>    at Xamarin.Bundler.Application+<>c.<BuildAll>b__44_1 (Xamarin.Bundler.Application v) [0x00000] in /Users/builder/az
1>  do/_work/1/s/xamarin-macios/tools/mtouch/Application.mtouch.cs:311  (TaskId:144)
1>    at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x0001e] in <36514b14425c4337b446653c5
1>  47aa9c3>:0  (TaskId:144)
1>    at Xamarin.Bundler.Application.BuildAll () [0x00050] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mtouch/A
1>  pplication.mtouch.cs:311  (TaskId:144)
1>    at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x00413] in /Users/builder/azdo/_work/1/s/xamarin-macios/to
1>  ols/mtouch/mtouch.cs:681  (TaskId:144)
1>    at Xamarin.Bundler.Driver.Main (System.String[] args) [0x0001b] in /Users/builder/azdo/_work/1/s/xamarin-macios/too
1>  ls/common/Driver.cs:52  (TaskId:144)
1>  Tool /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch execution finished. (TaskId:144)
1>  MTouch: 2021-09-28T19:39:58.2390359+05:30 - Finished (TaskId:144)
1>Done executing task "MTouch" -- FAILED. (TaskId:144)

**Comment by chamons** [comment]
Thanks for the feedback.

It looks like our linker is crashing while traversing your applications library tree:

> at MonoTouch.Tuner.RegistrarRemovalTrackingStep.EndProcess ()
at Mono.Linker.Steps.BaseStep.Process (Mono.Linker.LinkContext context) 
at Mono.Linker.Pipeline.ProcessStep (Mono.Linker.LinkContext context, Mono.Linker.Steps.IStep step) 

To move forward, we need to determine what library is causing trouble or create a repro case.

A few potential paths forward:
- Does your application use as obfuscated libraries or 3rd party assembly processing? If so, try removing those and see if it still occurs.
- Attach a sample project or binary log so I'm able to reproduce your issue.

**Comment by mlancione** [comment]
I am also experiencing this issue. The library causing the problem is MonoTouch.Dialog. 

I have attached a sample project. Building in Release for device reproduces the linker error.

[LinkerTest.zip](https://github.com/xamarin/xamarin-macios/files/7261041/LinkerTest.zip)

**Comment by mlancione** [comment]
This workaround seems to work:
Adding "--linkskip=MonoTouch.Dialog-1" to the mtouch additional arguments

**Comment by ShenbagaPriya22** [comment]
Thanks @mlancione . This workaround fixed issue in one of our test projects, but still other 3 project fails with same error.

@chamons mlancione has provided sample project with the similar error, could you please check and update us on this.

**Comment by wikes82** [comment]
having this same issue, and @mlancione workaround fixed it.

**Comment by chamons** [comment]
We strive to check our incoming and updated issues daily @ShenbagaPriya22.

I can confirm the repro case and work around.

**Comment by chamons** [comment]
I did a bit of poking. We are here when we NRE:

https://github.com/xamarin/xamarin-macios/blob/main/tools/linker/RegistrarRemovalTrackingStep.cs#L188

PlatformAssembly.MainModule is pointing to 

<img width="383" alt="image" src="https://user-images.githubusercontent.com/6392201/135678497-a8f9b36d-bb8b-4d26-a53e-c734030915e9.png">

for some reason, and thus returns null when we invoke .GetType ("ObjCRuntime.Runtime") on it.

Then we NRE, and report the error with a bit less detail. 

I assume the problem is why do we think the PlatformAssembly is MonoTouch.Dialog?

Any thoughts @rolf?

**Comment by chamons** [comment]
For safety, we should likely rewrite that code to null check `PlatformAssembly.MainModule.GetType ("ObjCRuntime.Runtime")` before moving forward.
