### ISSUE TITLE
VS for Mac "Generic Simulator"

### ISSUE THREAD

**Issue by Muhammad-Radwan** [xamarin/xamarin-macios#12874]
### Steps to Reproduce

Would the Xamario.iOS 15.0.0.6 solve the problem of "Generic Simulator Only"?

**Comment by filipnavara** [comment]
Yes, it is fixed by newer `mlaunch` tool which is included.

**Comment by Muhammad-Radwan** [comment]
Thank you Mr. Filip. This problem made me so frustrated

**Comment by chamons** [comment]
Thanks for your interest. It sounds like your question as answered, so I'm going to close this.
