### ISSUE TITLE
Support iOS 15 UITabBar scrollEdgeAppearance [Windows]

### ISSUE THREAD

**Issue by scarabdesign** [xamarin/xamarin-macios#12877]
New to iOS 15: https://developer.apple.com/documentation/uikit/uitabbar/3750912-scrolledgeappearance

I'm hoping this will resolve the issue with the tab bar being transparent.

### Environment
Xamarin iOS 15.0.0.6

### Example Code 
```
var appearance = new UITabBarAppearance();
appearance.ConfigureWithOpaqueBackground();
appearance.BackgroundColor = UIColor.Red();

tabBar.StandardAppearance = appearance;
tabBar.ScrollEdgeAppearance = appearance; //<-- needed
```

**Comment by chamons** [comment]
Thanks for your feedback.

We have bound that API in our Xcode 13 support, as you can see here:

https://github.com/xamarin/xamarin-macios/blob/main/src/uikit.cs#L12023-L12026

I'm uncertain what exactly you are requesting or reporting here.  Can you please clarify?

**Comment by scarabdesign** [comment]
Ah, so it is, however, although I've been give a link to download and install Xamarin iOS 15.0.0.6 on the mac, I'm coding in VS Windows. Is there an ETA for 15.0.0.6 for the windows side?

**Comment by chamons** [comment]
Xcode 13 support for Visual Studio on Windows is actively in work and coming soon, but I don't have a date I can share.

**Comment by scarabdesign** [comment]
Ok, I'll try installing VS on the Mac for the time being <yuck>. Keeping my eyes peeled for the update. Thanks!

**Comment by rachelkang** [comment]
We are closing this issue as Xcode 13 support has been released.
