### ISSUE TITLE
Xamarin SDK does not support all macos RIDs

### ISSUE THREAD

**Issue by trympet** [xamarin/xamarin-macios#12887]
### Steps to Reproduce

1. `dotnet new macos`
2. add `<RuntimeIdentifier>osx.11.0-arm64</RuntimeIdentifier>`
3. `dotnet build`

`
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk/12.0.100-rc.1.1534/targets/Xamarin.Shared.Sdk.targets(1065,3): error : The RuntimeIdentifier 'osx.11.0-arm64' is invalid. 
`

### Expected Behavior
The build should not fail.

### Actual Behavior
Xamarin SDK does not support the RID and the project fails to build. Considering there are version-specific TFMs (e.g. macos-10.15), a warning should be shown if there is a conflict.

### Environment
```
dotnet --list-sdks
3.1.411 [/usr/local/share/dotnet/sdk]
3.1.412 [/usr/local/share/dotnet/sdk]
3.1.413 [/usr/local/share/dotnet/sdk]
5.0.302 [/usr/local/share/dotnet/sdk]
5.0.400 [/usr/local/share/dotnet/sdk]
5.0.401 [/usr/local/share/dotnet/sdk]
6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]
6.0.100-rc.1.21458.32 [/usr/local/share/dotnet/sdk]
6.0.100-rc.1.21463.6 [/usr/local/share/dotnet/sdk]
```
```
uname -a
Darwin tryms-macmini.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64
```

```
```

### Build Logs
Send me an email (bio), and I'll provide logs if required.

**Comment by rolfbjarne** [comment]
If you want to set a specific target macOS version, you do it with the TargetFramework property, not the RID:

```xml
<TargetFramework>net6.0-macos11.0</TargetFramework>
```

We don't support any sort of version in the RID.
