### ISSUE TITLE
Hot Restart Prebuilt bundle is compiled with outdated SDK

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#12945]
VS 2022 Preview 4.1 shipped with .NET 6 RC1 SDK. However, it also shipped the prebuilt version of `Xamarin.PreBuilt.iOS.app` in `Microsoft.iOS.Windows.Sdk` workload pack that was compiled with Preview 7 SDK. This causes the application to load outdated version of some platform assemblies, such as System.Net.Http.dll. At very least I would expect the prebuilt version to match the shipped SDK. Ideally I would expect the workload pack to have up-to-date version on the dotnet6 feeds where I download the other workload packs.

Ref: https://github.com/xamarin/xamarin-macios/blob/2bc66b0cbebdebfb6ec1a71ff1713c101d66cdf0/msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Tasks.Windows.csproj#L33-L36

**Comment by rolfbjarne** [comment]
CC @mauroa I believe you've been working on this?
