### ISSUE TITLE
Xamarin.iOS version mismatch with build host

### ISSUE THREAD

**Issue by sami1971** [xamarin/xamarin-macios#12953]
### Steps to Reproduce

1. Update Visual Studio to latest version
2. Update Visual Studio for Mac to latest version
3. Connect to Mac build host

### Expected Behavior

Visual Studio connects to Mac build host

### Actual Behavior

Visual Studio prompts with the following message:

_The Xamarin.iOS SDK version '15.0.0.6' that is installed on the Mac is not compatible with this version of Visual Studio. Would you like us to install Xamarin.iOS '15.0.0.8' for you? This will overwrite any other existing Xamarin.iOS installation on your Mac._

When you click on Install the following message is displayed:

_There were problems installing Xamarin.iOS from: 'https://aka.ms/xvs/pkg/macios/15.0.0.8'. Please try again and if the problem persists, try installing directly on the Mac and connect again._

Visual Studio will connect but builds fail with this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The connection to the local Broker couldn't be established and the maximum allowed connection attempts have been reached.		 	0	

### Environment

Microsoft Visual Studio Community 2019
Version 16.11.4

Visual Studio for Mac
8.10.10 (build 8)

**Comment by me-to-you93** [comment]
Hello,

I had the same problem, but manually installing the package 15.0.0.8 did the trick.

**Comment by sami1971** [comment]
> Which version is the one that _should_ be installed? 15.0.0.6 or 15.0.0.8?

15.0.0.8 is the one on Windows.
