### ISSUE TITLE
APIs are marked as "unsupported" when in reality they are just deprecated

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#12968]
### Steps to Reproduce

1. Use the `EAGLContext` type in a macOS app project

![image](https://user-images.githubusercontent.com/1096616/136761008-3a2b4b72-7d81-46cb-805c-333437dadfeb.png)

### Expected Behavior
An obsolete warning vs an unsupported warning.

### Actual Behavior

The compiler says this is unsupported.

### Environment

```
```

**Comment by filipnavara** [comment]
That's how Apple defines the APIs and documentation though. Sure, the APIs are usually not removed from the system to keep some margin for app compatibility but Apple is free to do it at any moment and it can stop accepting the apps in App Store.
