### ISSUE TITLE
Xamarin project some changes not applied when deployed to App Store

### ISSUE THREAD

**Issue by sabels** [xamarin/xamarin-macios#12975]
This has started since we updated Visual Studio and upgraded XCode to 13. Our mobile app builds fine. We can see all out changes in the iPhone Simulator. When we deploy to the App Store and view the app via TestFlight, only some changes appear.

For example:

We removed a tab from a TabbedPage. This removal we can see in the simulator, but not when deployed to TestFlight.
We updated the build number in the info.plist. We can see this change after app is deployed to TestFlight.
We have cleared bin and obj folders.

Any ideas people?

Microsoft Visual Studio Community 2019 Version 16.11.4

XCode 13.0 (13A233)

(added here by request, originally posted https://stackoverflow.com/questions/69507421/xamarin-project-some-changes-not-applied-when-deployed-to-app-store)

**Comment by rachelkang** [comment]
We will be closing this issue as it has been over 30 days since we have heard from you. If you are still experiencing this issue, please provide all the requested information and then click the Reopen Issue button. Thank you!
