### ISSUE TITLE
The VerifyXcodeVersion warning always appears and without a error code to disable

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#12992]
### Steps to Reproduce

When building an iOS (or any Apple) library or app, I always get this warning and there is no error code to disable it:

> (_VerifyXcodeVersion target) ->
> C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.0.101-preview.10.165\tools\msbuild\iOS\Xamarin.Messaging.Apple.targets(31,3): warning : There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed

### Expected Behavior

A warning with an error code.

### Actual Behavior

No error code.

### Environment

```
```

**Comment by ispysoftware** [comment]
vs2022 + xamarin + mac os monterey is thoroughly broken
it's like every bug that has ever been fixed has risen from the dead in some kind of zombie apocalypse
i swear developing apps with xamarin is 2% coding, 98% rolling back to previous versions of everything and screaming abuse at your computer.

**Comment by mattleibow** [comment]
I was not connected to a mac and I was building via the CLI.
