### ISSUE TITLE
Cannot open Storyboard from Visual Studio via Xcode interface builder

### ISSUE THREAD

**Issue by sisaacks** [xamarin/xamarin-macios#13040]
### Steps to Reproduce

1. Follow the following tutorial to create a storyboard : https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/launch-screens?tabs=macos  (make sure XCode is closed)
2. Once created double click on the LaunchScreen.Storyboard 
3.  

### Expected Behavior
The storyboard should open

### Actual Behavior
A warning message:  Visual Studio could not communicate with XCode.  If XCode is still running, please ensure that all changes have been saved and Xcode has been exited before continuing, otherwise any new changes may be lost.  When you click OK you get the rainbow spinner of death and you have to force quite XCode.  

### Environment
Visual Studio 8.10.11
XCode 13
macOS Big Sur Version 11.6

```
```

**Comment by dpaulino** [comment]
I'm having this exact same issue :(
