### ISSUE TITLE
.NET: Use a different type than IntPtr for our handles

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#13126]
Current status is that we're using `IntPtr` for all our native handles. This is troublesome in .NET, because we won't be able to distinguish between pointer-sized numbers (`nint`) and plain pointers/handles, so as part of the breaking changes that are coming in .NET (#13087), we've decided to use a different type than `IntPtr` going forward.

Fundamentally there are two options:

1. A custom struct that contains a single IntPtr field - the purpose is for everything to behave the same, but have a different type than `IntPtr`.
2. A custom `SafeHandle` subclass (or more than one).

### Advantages

* No additional memory usage.
* Shouldn't have any memory management surprises, since it should behave the same.

### Disadvantages

* There might be marshaling problems on some platforms if we use the custom struct in P/Invokes, since a primitive type is not necessarily always marshaled the same way a struct. It'll be possible to avoid this though by always using IntPtr in P/Invokes.

### Advantages

* Allows for more advanced memory management scenarios.
* Seems to be the recommended solution in .NET.

### Disadvantages

* Since SafeHandle is a class, we'd double the number of managed instances (an additional SafeHandle instance for every NSObject instance).
* The memory management will be different, so there might be unpleasant surprises.

**Comment by rolfbjarne** [comment]
> One more item on the list of advantages for SafeHandle - or SafeHandle-like wrapper is that managed memory can be reclaimed earlier than the native memory itself.

We can't reclaim managed memory before the native memory (in fact we try quite hard to wait until a very specific moment to free the managed memory).

This is because of virtual functions and dealloc implementations being able to call them.

Scenario:

* A native type N subclasses NSObject, overrides the native `dealloc` function, and calls a selector `S` from that `dealloc` function.
* A managed type M subclasses N, and provides an implementation for the selector `S`.
* An instance of M is being deallocated. The N.dealloc method will call the `S` selector, which has been implemented by M. This is an instance method, which means that the Xamarin runtime needs to find the managed instance in order to call the method M.S (if we can't find the instance, we'll throw an exception, which will likely terminate the process).
* Consequently we must keep the managed instance alive until after the N.dealloc method has completed executing.

Unfortunately this means that we can't claim the managed memory before the native memory is _just_ about to be freed.

Along with a few other requirements:

* The call to the release selector has to happen on the main thread.
* Until the release has happened on the main thread, the managed instance must be resurrectable.

I don't see how we can do this with SafeHandle.

**Comment by Therzok** [comment]
> The call to the release selector has to happen on the main thread.

Not true for all the cases, see: https://github.com/xamarin/xamarin-macios/pull/8092

But understood. The exact scenario I was thinking of was when native refcounts reach 1 (toggleref only), so that means the managed object can be reclaimed immediately via WeakRef toggle and the native SafeHandle is the only one queued for finalizer release (on the UI thread if necessary).

Is there any way that users can configure resurrection expectations for objects? I'm not sure we even have virtual calls in dealloc in our case.

`Dispose` is not an option, as that just makes us deal with other problems.

**Comment by Therzok** [comment]
Also, this seems like possible to detect both at runtime and compiletime. If there is no dealloc override, it basically becomes quite straightforward :D

> A native type N subclasses NSObject, overrides the native dealloc function, and calls a selector S from that dealloc function.
> A managed type M subclasses N, and provides an implementation for the selector S.

**Comment by rolfbjarne** [comment]
> I'm not sure we even have virtual calls in dealloc in our case.

Apple does it in their types.

> Also, this seems like possible to detect both at runtime and compiletime.

Since Apple does it in their types, it doesn't necessarily happen in code we control. This means that:

* It can't be detected at compile time, because the dealloc implementation might change in an OS update, so the virtual call from dealloc might not even exist at compile time.
* Technically it might be somewhat possible to detect at runtime, but you'd have to decompile memory to figure out what every dealloc implementation up the class hierarchy does. That's not something we want to do.
