### ISSUE TITLE
xcframework project/code results with errors 

### ISSUE THREAD

**Issue by Atamanam** [xamarin/xamarin-macios#13138]
### Overview 
I am integrating a .xcframework with Xamarin iOS project & did not find much of documentation, Upon opening a question in a Microsoft Q&A I was referred to https://github.com/xamarin/xamarin-macios/pull/10046 where I found a sample xcframework with tests projects is also available https://github.com/spouliot/xcframework 

### Steps to Reproduce

1. Downloaded this code : https://github.com/spouliot/xcframework 
2. Build for an iOS Simulator 

### Expected Behavior
Successfully build the App 

### Actual Behavior
Building the App results a error 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(3,3): Error: ../../Universal.xcframework has an incorrect or unknown format and cannot be processed.

<img width="1680" alt="Screen Shot 2021-10-26 at 10 18 49 AM" src="https://user-images.githubusercontent.com/66333672/139117494-199c5957-9545-44f5-aa2c-d96d08595fc2.png">

### Example Project (If Possible)

https://github.com/xamarin/xamarin-macios/pull/10046

**Comment by rachelkang** [comment]
We will be closing this issue as it has been over 30 days since we have not received the requested information. If you are still experiencing this issue, please provide all the requested information and then click the Reopen Issue button. Thank you!
