### ISSUE TITLE
[VS2022 p7] Project 'xxxx.csproj' targets 'net6.0'. It cannot be referenced by a project that targets 'Xamarin.iOS,Version=v1.0'

### ISSUE THREAD

**Issue by aritchie** [xamarin/xamarin-macios#13201]
### Steps to Reproduce

1. In VS2022 preview 7, create an iOS application project 
2. Create net6.0 class library (TFM is net6.0)
3. Reference the class library in the iOS project

### Expected Behavior
References project fine and allows me to work with the code within that project

### Actual Behavior
Project '..\ClassLibrary1\ClassLibrary1.csproj' targets 'net6.0'. It cannot be referenced by a project that targets 'Xamarin.iOS,Version=v1.0'

NOTE: this class library can be referenced by a new Android project.	

[Test.zip](https://github.com/xamarin/xamarin-macios/files/7455674/Test.zip)

### Environment
Microsoft Visual Studio Enterprise 2022 Preview
Version 17.0.0 Preview 7.0
VisualStudio.17.Preview/17.0.0-pre.7.0+31825.309
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA391
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.0.786.62401
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.786.62401
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.786.62401
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.4000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.0.786.62401
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.4000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.0.0-6.21521.2+68d3c0e77ff8607adca62a883197a5637a596438
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IndentRainbowPackage Extension   1.0
IndentRainbowPackage Visual Studio Extension Detailed Info

Linux Core Dump Debugging   1.0.9.31808
Enables debugging of Linux core dumps.

Microsoft Azure Hive Query Language Service   2.6.4000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.4000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.0.11 (54f19d2)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.30901.1 Commit Hash:2ce65f585c66dbd15240cf57f8e995513c270b0b
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.4.236
2.4.236

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2150514+d9e17e7b7f06829e976f616716a987599c5c66e9
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.0-6.21521.2+68d3c0e77ff8607adca62a883197a5637a596438
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.31808
Visual C++ for Linux Development

Visual F# Tools   17.0.0-beta.21519.2+727a6abda5bb3276f3e8dd918b721c5d21464aac
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.331 (d17-0@4dde409)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.182 (remotes/origin/d17-0@ea204898d)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.13 (1bcd73e)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.0.5 (d17-0/6b0e6b2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d17-0@febb1367
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-0@a5194e9

Xamarin.iOS and Xamarin.Mac SDK   15.0.0.18 (577ff6329)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by chamons** [comment]
Thanks for your feedback.

This is expected behavior, as documented [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

If you want to use Xamarin.iOS,Version=v1.0, the current Xamarin.iOS, you can not use a net6 library. You can retarget (or use multi-targetting) to [build against netstandard 2.1](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#when-to-target-net50-vs-netstandard).

Another option is to look at the preview of iOS on net6, but that will not be stable for a number of months.
