### ISSUE TITLE
iPhone running iOS 15.1

### ISSUE THREAD

**Issue by angelru** [xamarin/xamarin-macios#13237]
### Steps to Reproduce

I can't install apps on iPhone with iOS 15.1. Works fine on iOS 15.0 and emulator.

### Expected Behavior
Run apps on iOS 15.1 and update the iOS SDK.

### Actual Behavior
Can't run apps on iOS 15.1

### Environment

Visual Studio: 2019 and 2022 17.0 RC

**Comment by chamons** [comment]
Thanks for the feedback.

However, you did not provide sufficient information for us to be able to help you. When you say "install apps", are you talking about deploying in Visual Studio for Mac or Visual Studio? If so, consider filing an issue [here](https://developercommunity.visualstudio.com/report?space=8&entry=problem).

If this is an issue with Xamarin.iOS application you are developing, please provide build logs, crash logs and/or a sample project.

**Comment by angelru** [comment]
I think the problem is that iOS 15.1 is already available:
https://support.apple.com/en-us/HT212788

And I can't deploy the application on a physical iPhone from Visual Studio (windows) because I have a smaller version of the sdk.

**Comment by angelru** [comment]
I can't debug applications on my physical iphone from windows:
https://developercommunity.visualstudio.com/t/iphone-ios-151-physical-debug/1572333

**Comment by chamons** [comment]
Thanks for the feedback.

I believe builds with support have been or will soon be release.

Please update to the latest, try again, and if it fails post details log as requested.

**Comment by angelru** [comment]
@chamons This is the problem
https://github.com/xamarin/GoogleApisForiOSComponents/issues/497
