### ISSUE TITLE
watchOS applications do not install on the simulator with latest Xcode

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#13290]
### Steps to Reproduce

1. Create new iOS Application project 
2. Right click sln -> Add new project
3. watchOS -> App -> WatchKit App
4. Add a name, done
5. Build debug for sim

### Workaround

In your WatchKit app extension set the supported architecture to x86_64

![image](https://user-images.githubusercontent.com/6392201/140557571-72fc5a2d-4b8e-426c-9843-0adc7c39d0a9.png)

### Expected Behavior

Successful build

### Actual Behavior

```
error HE0046: Failed to install the app 'com.hamons.iOSWatch2.watchkitapp' on the device 'watchOS 8.0 (19R345) - Apple Watch Series 7 - 45mm': ???TestWatch.WatchOSApp??? Needs To Be Updated
```

### Environment

https://gist.github.com/chamons/b0d5affcde7306b21290002f287b12ff

### Build Logs

https://gist.github.com/chamons/2b7ff347297d1e71892c8d7dde1c2b1a

### Example Project (If Possible)

[iOSWatch2.zip](https://github.com/xamarin/xamarin-macios/files/7486944/iOSWatch2.zip)

**Comment by dalexsoto** [comment]
in order to debug on Series 6/7 simulators (Pretty much Xcode 11+) you need to change the watchOS app arch to x86_64 from the project settings

<img width="692" alt="image" src="https://user-images.githubusercontent.com/204671/140543874-f6905186-d05a-43d6-abd6-f9a94715f8dc.png">

**Comment by EmilAlipiev** [comment]
very old issue but still valid i think today. I am not sure if I understand the answer from @dalexsoto Ui seems to be different on the latest VS for Mac. what is the suggested solution here?

**Comment by rolfbjarne** [comment]
Closing, since watchOS isn't supported in .NET, and Xamarin is not supported anymore.
