### ISSUE TITLE
MemoryWarning and crash using CGBitmapContext after upgrading to Xamarin.iOS 15.2.0.1

### ISSUE THREAD

**Issue by TomQv** [xamarin/xamarin-macios#13309]
We are using CGBitmapContext  in a kind of a game loop (pseudo code) :

```
While (running)
{
        var imageWidth = 2000;
	var imageHeight =3000;

	// create a new bitmap context.
	var space = CGColorSpace.CreateDeviceRGB();
	int bytesPerPixel = 4;
	int bytesPerRow = bytesPerPixel * imageWidth;
	int bitsPerComponent = 8;

	var image = new CGBitmapContext(null, imageWidth, imageHeight,
					bitsPerComponent, bytesPerRow,
					space, 
					CGBitmapFlags.PremultipliedFirst | CGBitmapFlags.ByteOrder32Big);
	image.SetFillColor(1, 1, 1, 1);
	image.FillRect(new CGRect(0, 0, imageWidth, imageHeight));

       ...  // drawing commands

       space.Dispose();
       image .Dispose();
}

this loop runs more or less once per second. All was fine with the past ios sdks 13 and 14.

After update Visual Studio Mac to current release (see below) this loop causes MemoryWarning after ca. 10-20 loops already and then the app is crashing. 

So my question, is CGBitmapContext handled different now with 15? Or is something broken with it?
Same code runs fine with 13 and 14.

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.12 (build 16)
Installation UUID: cbad260e-c107-47dc-8221-cfd4d7a0561d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.402/Sdks
SDK Versions:
	5.0.402
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.414
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.100
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.11
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.20
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13

=== .NET Core 3.1 SDK ===

SDK: 3.1.414

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 20:09:18 UTC

=== Apple Developer Tools ===

Xcode 13.1 (19466)
Build 13A1030d

=== Xamarin.Mac ===

Version: 8.2.0.1 (Visual Studio Community)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:55-0400

=== Xamarin.iOS ===

Version: 15.2.0.1 (Visual Studio Community)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:56-0400

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/tomflemming/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0_302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-28 20:47:12 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-28 20:47:30 UTC

=== Build Information ===

Release ID: 810120016
Git revision: e4f3f43ac50d8e0f83a71dbcb666bb1611a661d7
Build date: 2021-10-28 12:10:44-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Jun 23 00:26:31 PDT 2021
    root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

```

**Comment by rolfbjarne** [comment]
I can reproduce this and I'll have a look.

**Comment by rolfbjarne** [comment]
Fix is in progress.

A workaround is to use a different constructor to create the CGBitmapContext (the one that takes `CGImageAlphaInfo` instead of  `CGBitmapFlags`):

```csharp
var image = new CGBitmapContext(null, imageWidth, imageHeight,
			bitsPerComponent, bytesPerRow,
			space, 
			(CGImageAlphaInfo) CGBitmapFlags.PremultipliedFirst | CGBitmapFlags.ByteOrder32Big);
```

**Comment by TomQv** [comment]
That was a quick one :)
Workaround seems to be fine, thank you!

**Comment by rolfbjarne** [comment]
@TomQv there might be more bugs - if you can create a test project I can use to reproduce it, I'll fix it.

**Comment by TomQv** [comment]
@rolfbjarne I was trying to get some more information first, where the memory is consumed.
Unfortunate Instruments is not working properly with Xcode 13. Please see [here](https://github.com/xamarin/ios-samples/issues/420)

**Comment by TomQv** [comment]
>  if you can create a test project I can use to reproduce it, I'll fix it.

@rolfbjarne see here https://github.com/xamarin/xamarin-macios/issues/13432
