### ISSUE TITLE
Objective Sharpie showing Invalid Sdk iOS 15 #1300

### ISSUE THREAD

**Issue by SarthakGz** [xamarin/xamarin-macios#13352]
Objective Sharpie showing invalid sdk when trying to bind iOS framework targeting iOS 15

Objective Sharpie version : 3.5.45
XCode : 13.0

MacId:~ usernamen$ sharpie bind --sdk=iphoneos15.0 --output="$SWIFT_OUTPUT_PATH/XamarinApiDef" --namespace="Binding" --scope="$SWIFT_OUTPUT_PATH/$SWIFT_PROJECT_NAME.framework/Headers/" "$SWIFT_OUTPUT_PATH/$SWIFT_PROJECT_NAME.framework/Headers/$SWIFT_PROJECT_NAME-Swift.h"

error: invalid SDK 'iphoneos?15.0?'

Note : I am just trying to update this https://github.com/Csaba8472/WidgetCenterProxy binding to target iOS 15 currently it is build for iOS 14 but when I try to execute final command which generates api definition I get error: invalid SDK 'iphoneos?15.0?' by sharpie I guess

**Comment by rachelkang** [comment]
Hi, @SarthakGz - Thanks for opening this issue.

It seems like the latest released version of objective-sharpie may be a bit out of date. Can you try [this version here](https://download.visualstudio.microsoft.com/download/pr/0e9ecce4-10b6-46a4-ae06-ad031b25eafc/761cd868c5c27f5b68765e1fa53fd873/objectivesharpie-3.5.46.pkg) and let us know if that works for you?

Another thing to check is that the version of Xcode you have set is the one that you expect. You can do this by running `xcode-select -p`

If you continue to have issues, please run `sharpie xcode -sdks` and let us know what sdks there are, so we can investigate further.

**Comment by SarthakGz** [comment]
Hi @rachelkang  thanks for your response sure I will try sharpie version you shared and yes I have selected Xcode 13.0 using 
'**xcode-select -p**' and running '**sharpie xcode -sdks**' shows iphone and iphone simulator 15.0 sdk available

**Comment by rachelkang** [comment]
We will be closing this issue as it has been over 30 days since we have not received the requested information. If you try the sharpie version and find you are still experiencing this issue, please provide all the requested information and then click the Reopen Issue button. Thank you!
