### ISSUE TITLE
NoBindingEmbedding fails to copy resources folder back to windows

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#13393]
### Steps to Reproduce

1.  Setup a VS on Windows to a macOS host and open [MyBinding.zip](https://github.com/xamarin/xamarin-macios/files/7564338/MyBinding.zip)
2. Debug build
3. Note that the binding dll is copied back, and the .resources.stamp is, but the .resources folder with the native library/manifest is not

### Expected Behavior

Entire dll and supporting "sidecar" folder is copied over, or valid error message.

### Actual Behavior

Half of the files are copied over. 

### Environment

https://gist.github.com/chamons/c2733d2899c76aa9e6c6bec4944387c1

### Build Logs

https://gist.github.com/chamons/19da24f8d14b4016eef12393728c9f9c

### Example Project (If Possible)

https://github.com/xamarin/xamarin-macios/files/7564338/MyBinding.zip

**Comment by chamons** [comment]
Hey @rolfbjarne - I suspect this got fixed in the flurry of recent fixes. Thoughts?

**Comment by rolfbjarne** [comment]
@chamons probably not actually, but I've been looking at binding projects on Windows recently, and have a bunch of pending fixes, so I'll take over this issue.
