### ISSUE TITLE
net6: Calling ObjCRuntime.Runtime.OriginalWorkingDirectory triggers error about missing libxammac.dylib

### ISSUE THREAD

**Issue by sandyarmstrong** [xamarin/xamarin-macios#13392]
https://github.com/xamarin/xamarin-macios/blob/aa2f7c33d160b841da9ad0d8513b1d3b97a5ab43/src/ObjCRuntime/Runtime.mac.cs#L93

1. Using .NET 6.0.100 and macos workload 12.0.101-preview.10.249
2. Call `ObjCRuntime.Runtime.OriginalWorkingDirectory`

### Expected Results

Get original working directory.

### Actual Results

```
Exception thrown: 'System.DllNotFoundException' in Xamarin.Mac.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in System.Private.CoreLib.dll
Exception thrown: 'System.DllNotFoundException' in System.Private.CoreLib.dll
2021-11-18 07:50:08.045 macos6[69374:5315744] Could not find the runtime library libxammac.dylib
```

**Comment by rolfbjarne** [comment]
I can reproduce this.
