### ISSUE TITLE
CodeSignVerify uses incorrect path for PlugIns on macOS

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#13415]
The following code is missing the `Contents/` part of the path:
https://github.com/xamarin/xamarin-macios/blob/17e7f65b2cc0367125bb9defa71fbeae1cdedf3c/msbuild/Xamarin.Shared/Xamarin.Shared.targets#L1736-L1746

![image](https://user-images.githubusercontent.com/1764393/142742589-d97047ed-74ab-4811-92c6-96f592b6bae6.png)

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/7575447/msbuild.binlog.zip)

**Comment by filipnavara** [comment]
I suppose the fix would be to replace `$(_AppBundlePath)PlugIns\` with `$(_AppExtensionRoot)PlugIns\`.

**Comment by rolfbjarne** [comment]
I proposed a fix, but this should really be covered by tests too.
