### ISSUE TITLE
Nullability of UIViewController.View

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/xamarin-macios#13416]
Accessing the `View` property of a view controller for the first time causes it to be loaded. It can later be assigned `null` to free memory.

At the moment the property is declared as follows:

```csharp
public virtual UIView? View 
```

I believe it should be declared as:

```csharp
[NullAllowed]
public virtual UIView View 
```

I don't really know enough about how the bindings are generated to know if that is possible.

**Comment by chamons** [comment]
Thanks for the feedback.

I took at look at our binding and it [is defined as](https://github.com/xamarin/xamarin-macios/blob/main/src/uikit.cs#L14724-L14726):

```
		[Export ("view", ArgumentSemantic.Retain)]
		[NullAllowed]
		UIView View { get; set; }
```

So while we could improve the generated code, the binding is correct today.

**Comment by GalaxiaGuy** [comment]
@chamons Apologies, I got two different attributes confused.

I believe the output of the binding should be

```csharp
[AllowNull]
public virtual UIView View
```

(where `AllowNull` is the C# 8 nullability attribute here: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.allownullattribute?view=net-6.0)

This would allow `null` to be assigned to `View`, but it would assumed to be non-null when you `get` it.

I don't know whether support for adding C# nullability attributes to binding definitions and "passing then through" to generated bindings is the right move or not.

I also realise this is a bit of special case, but it is a special case that is used a lot - at the moment using `UIViewController.View` in a nullable context is awkward.

**Comment by chamons** [comment]
That makes more sense. I'm unsure at the moment if we can safely do this in a backwards compatible way, but I'll raise it to the rest of the team for consideration.
