### ISSUE TITLE
Hybrid AOT does not run on macOS 10.13.6

### ISSUE THREAD

**Issue by alataffective** [xamarin/xamarin-macios#13414]
### Steps to Reproduce
1. Download [CocoaApp.zip](https://github.com/xamarin/xamarin-macios/files/7574343/CocoaApp.zip)
2. On macOS 10.13.6, unzip to some location, say `/Users/admin/Desktop/`
3. Open a terminal
4. Execute `chmod +x "/Users/admin/Desktop/CocoaApp/4 WithHybridAot and MONO_CONSERVATIVE_HWCAP/CocoaAppWithHybridAot.app/Contents/MacOS/CocoaAppWithHybridAot"`
5. Execute `MONO_LOG_LEVEL=debug "/Users/admin/Desktop/CocoaApp/4 WithHybridAot and MONO_CONSERVATIVE_HWCAP/CocoaAppWithHybridAot.app/Contents/MacOS/CocoaAppWithHybridAot"`

### Expected Behavior
The app runs and a window is shown, as is the case for `1 WithoutAot` and `2 WithAot` on macOS 10.13.6 High Sierra and for all four builds on macOS 12.0.1 Monterey.

### Actual Behavior
The app does not run (or runs and exits) and the following output is produced: [4-WithHybridAot-and-MONO_CONSERVATIVE_HWCAP-debug-output.txt](https://github.com/xamarin/xamarin-macios/files/7574348/4-WithHybridAot-and-MONO_CONSERVATIVE_HWCAP-debug-output.txt)

Similar behaviour occurs with `3 WithHybridAot`.

### Environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.13 (build 11)
Installation UUID: 81cc1230-733f-44c7-8e62-dbbcc649f198
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.403/Sdks
SDK Versions:
	5.0.403
	5.0.301
	5.0.203
	5.0.202
	5.0.102
	5.0.101
	3.1.415
	3.1.410
	3.1.409
	3.1.408
	3.1.405
	3.1.404
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.300
	2.2.107
	2.1.505
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.12
	5.0.7
	5.0.6
	5.0.5
	5.0.2
	5.0.1
	3.1.21
	3.1.16
	3.1.15
	3.1.14
	3.1.11
	3.1.10
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.5
	2.2.4
	2.1.23
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.9

=== .NET Core 3.1 SDK ===

SDK: 3.1.415

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.1 (19466)
Build 13A1030d

=== Xamarin.Mac ===

Version: 8.2.0.1 (Visual Studio Community)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:55-0400

=== Xamarin.iOS ===

Version: 15.2.0.1 (Visual Studio Community)
Hash: 8fd9e6289
Branch: xcode13.1
Build date: 2021-10-26 10:13:56-0400

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 20:09:18 UTC

=== Xamarin.Android ===

Not Installed

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0_302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-28 20:47:12 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-28 20:47:30 UTC

=== Build Information ===

Release ID: 810130011
Git revision: 53e3946a0f6b630a1124eb7ff26c1b545d040d32
Build date: 2021-11-04 11:20:46-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 21.1.0 Darwin Kernel Version 21.1.0
    Wed Oct 13 17:33:23 PDT 2021
    root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
```

### Build Logs
[Build Output.txt](https://github.com/xamarin/xamarin-macios/files/7574379/Build.Output.txt)

### Example Project (If Possible)
See `CocoaAppWithHybridAot` in this zip file: [CocoaApp Projects.zip](https://github.com/xamarin/xamarin-macios/files/7574382/CocoaApp.Projects.zip)

### Additional Information
This issue may or may not have anything to do with this previously raised issue: https://github.com/xamarin/xamarin-macios/issues/7952

I did raise this issue in the mono repo in case that was the right place, however I've had no response in over a week and I'm not sure that was the right place for it anyway, so have raised it here instead. (See https://github.com/mono/mono/issues/21303.) Perhaps someone can give me some guidance on this. Thanks.

**Comment by chamons** [comment]
Thanks for the feedback. From reviewing the log, I believe mono/mono is the correct initial place for this issue:

```
Mono: AOT: image '/Users/admin/Desktop/CocoaApp/4 WithHybridAot and MONO_CONSERVATIVE_HWCAP/CocoaAppWithHybridAot.app/Contents/MonoBundle/mscorlib.dll.dylib' not found: dlopen(/Users/admin/Desktop/CocoaApp/4 WithHybridAot and MONO_CONSERVATIVE_HWCAP/CocoaAppWithHybridAot.app/Contents/MonoBundle/mscorlib.dll.dylib, 9): no suitable image found.  Did find:
	/Users/admin/Desktop/CocoaApp/4 WithHybridAot and MONO_CONSERVATIVE_HWCAP/CocoaAppWithHybridAot.app/Contents/MonoBundle/mscorlib.dll.dylib: cannot load 'mscorlib.dll.dylib' (load command 0x80000034 is unknown)
	/Users/admin/Desktop/CocoaApp/4 WithHybridAot and MONO_CONSERVATIVE_HWCAP/CocoaAppWithHybridAot.app/Contents/MonoBundle/mscorlib.dll.dylib: cannot load 'mscorlib.dll.dylib' (load command 0x80000034 is unknown)
Mono: AOT: image '/Users/builder/jenkins/workspace/archive-mono/2020-02/mac/release/sdks/out/mac-mac64-release/lib/mono/aot-cache/amd64/mscorlib.dll.dylib' not found: dlopen(/Users/builder/jenkins/workspace/archive-mono/2020-02/mac/release/sdks/out/mac-mac64-release/lib/mono/aot-cache/amd64/mscorlib.dll.dylib, 9): image not found
Mono: Unloading domain CocoaAppWithHybridAot.exe[0x7ffb25422630], assembly mscorlib[0x7ffb25424a30], ref_count=2
```

I'm going to close this issue and see if I can someone to look at your mono/mono version.

Thanks.

**Comment by alataffective** [comment]
Thanks Chris, much appreciated.

**Comment by alataffective** [comment]
I develop a Xamarin.Mac rich GUI app (https://affectivesound.com/playable), but I get the impression Mono isn't being so actively worked on. A reported issue on GitHub is not being answered (https://github.com/mono/mono/issues/21303#issuecomment-990965583).

Am I right to be concerned? Should I consider my options and look to move away from Xamarin.Mac? My main language C# and would like to continue develop my project using it, however I am thinking perhaps the safer thing to do is to write my application in Swift.

What are my long term options here?

**Comment by chamons** [comment]
Much of the work previously done in mono/mono is being done in dotnet/runtime in the move to NET5/NET6. You can read about that in https://devblogs.microsoft.com/dotnet/introducing-net-5/ and https://devblogs.microsoft.com/dotnet/announcing-net-6/#unified-and-extended-platform.

Xamarin.Mac is supported moving forward, and the team is actively working now on the NET6 transition.

**Comment by alataffective** [comment]
Apologies for continuing to ask questions related to my issue here, but I'm not sure where is better.

When Xamarin.Mac runs on .NET5/6, will there be equivalent support for obfuscation, using Hybrid AOT or some other mechanism?

Secondly, what's the best way to keep in touch with the progress of this project and expected release date?

Thank you.

**Comment by rolfbjarne** [comment]
> When Xamarin.Mac runs on .NET5/6, will there be equivalent support for obfuscation, using Hybrid AOT or some other mechanism?

No, not at release time (not enough time).

We might look into it for .NET 7 - there's an issue here you can follow: https://github.com/xamarin/xamarin-macios/issues/13873

**Comment by alataffective** [comment]
Is there information related to the current state of the work for Xamarin.Mac to run on .NET5+? When is it likely to be delivered, and what will I need to do to move to this version? I've had a look around but I've been unable to find the relevant information.

Thank you.

**Comment by rolfbjarne** [comment]
You can look for information about MAUI, it's the same timeline:

https://github.com/dotnet/maui/wiki/roadmap#net-maui-ga-q2-2022
https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-13/
