### ISSUE TITLE
visual studio 2022 unable to pair to mac (error code 134)

### ISSUE THREAD

**Issue by ispysoftware** [xamarin/xamarin-macios#13413]
### Steps to Reproduce

1.  Click to run project on remote device
2.  Select Mac
3. Click Connect

### Expected Behavior

Connects to Mac, builds project

### Actual Behavior

checks mono
checks xamarin ios installation
bugs out with error:
An error occurred while trying to connect to the Broker...
An error occurred while executing an SSH command. Error code: 134

running the command from the logs manually on the mac returns the error:
error 134: Service cannot load in requested session

### Environment

```
Microsoft Visual Studio Professional 2022
Version 17.0.0
VisualStudio.17.Release/17.0.0+31903.59
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA831
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.0.789.48259
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.789.48259
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.789.48259
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.4000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.0.789.48259
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.4000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.0.0-6.21526.21+c7d6f9fab845ffd943216da465022744e7d35f22
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Microsoft Azure Hive Query Language Service   2.6.4000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   17.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.4000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.0.11 (54f19d2)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2152201+3319c75f898522ff4dc9cf0c70035c284264a1de
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.0-6.21526.21+c7d6f9fab845ffd943216da465022744e7d35f22
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21522.2+6d626ff0752a77d339f609b4d361787dc9ca93a5
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   1.0.0.12
WiX Toolset Visual Studio Extension version 1.0.0.12
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   17.0.0.336 (d17-0@29731f2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.182 (remotes/origin/d17-0@ea204898d)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.17 (9e779b0)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.0.5 (d17-0/6b0e6b2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d17-0@febb1367
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-0@a5194e9


Xamarin.iOS and Xamarin.Mac SDK   15.0.0.18 (577ff6329)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

Logs on the windows machine contain:

Xamarin.Messaging.Ssh.SshCommands Information: 0 : A valid Mono installation has been found at '/Library/Frameworks/Mono.framework/Versions/Current/bin/mono64': 11/20/2021 08:11:08Z
    DateTime=2021-11-20T08:11:08.8546022Z: 11/20/2021 08:11:08Z
Xamarin.Messaging.Ssh.SshCommandRunner Warning: 0 : Failed to execute 'launchctl load -S Aqua "/tmp/com.xamarin.2021-11-20__16-09-47.22200.broker.212/app.plist"': ExitStatus = 134: 11/20/2021 08:11:08Z
    DateTime=2021-11-20T08:11:08.9367014Z: 11/20/2021 08:11:08Z
Xamarin.Messaging.Ssh.MessagingService Error: 0 : An error occurred while trying to connect to the Broker...: 11/20/2021 08:11:08Z
    DateTime=2021-11-20T08:11:08.9376998Z: 11/20/2021 08:11:08Z
Xamarin.Messaging.Ssh.MessagingService Error: 0 : !An error occurred while trying to connect to the Broker...: 11/20/2021 08:11:08Z
    DateTime=2021-11-20T08:11:08.9376998Z: 11/20/2021 08:11:08Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : Starting connection to 'Sean Mac'...: 11/20/2021 08:11:08Z
    DateTime=2021-11-20T08:11:08.9437013Z: 11/20/2021 08:11:08Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : !Starting connection to 'Sean Mac'...: 11/20/2021 08:11:08Z

**Comment by ispysoftware** [comment]
it's just randomly stopped doing this now after leaving it for 14 hours and not touching it
now it's connecting to the build host (when i click tools - ios - pair to mac) but when i try to deploy to my device i get:

Severity	Code	Description	Project	File	Line	Suppression State
Error		error MT1001: Could not find an application at the specified directory: /Users/sean/Library/Caches/Xamarin/mtbs/builds/MobileUI.iOS/1d03eed8f2e1b15d7e8a3a038388995b45d61e183c5603c7a134e865db393a84/bin/iPhone/Debug/Agent.app		 	0	

it's also saying
Severity	Code	Description	Project	File	Line	Suppression State
Warning		There is no available connection to the Mac. Task 'VerifyXcodeVersion' will not be executed	MobileUI.iOS			

but it is connected to the build host - it has the chain icon next to the mac in the pair to mac tool.

has anyone tested this? It's like loads of old bugs have re-emerged. Everything is running on latest versions. Mac OS Monterey 12.0.1 on M1, VS2022 on Win 11. Maybe some version check code isn't handling new version numbers?

**Comment by chamons** [comment]
Thanks for the feedback and apologies for the trouble you've hit.

Unfortunately, the team in question are not accessible from github issues here. You'll need to report an issue [here](https://developercommunity.visualstudio.com/report?space=8&entry=problem) to get it sent to the correct group.

Thanks again!
