### ISSUE TITLE
XAML Hot Reload can cause "System.MissingMethodException: Method not found" or "Attempting to JIT compile method while running in aot-only mode" or "System.TypeInitializationException: The type initializer" exceptions

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#13423]
In some cases XAML hot reload can cause a number of strange exception to occur in your Xamarin application.

Example:
- https://github.com/mono/mono/issues/20894
- https://developercommunity.visualstudio.com/t/bug-in-visual-studio-2022-xamarin-signalr-method-n/1528510#T-N1585923
- https://github.com/mono/mono/issues/20805 (the main current bug)

## Workaround

![image](https://user-images.githubusercontent.com/6392201/142946972-cda59585-d3b8-49f7-92c3-a845b320a636.png)

From [here](https://developercommunity.visualstudio.com/t/bug-in-visual-studio-2022-xamarin-signalr-method-n/1528510#T-N1585840). 

## Resolution

https://github.com/mono/mono/issues/20805 is the main bug tracking this problem currently. This issue is pinned just to increase visibility. Please post any comments and questions there.

**Comment by rolfbjarne** [comment]
This is a dup of #13365.
