### ISSUE TITLE
Memoryleak in CopyByStrokingPath

### ISSUE THREAD

**Issue by TomQv** [xamarin/xamarin-macios#13432]
This code is building up memory which is not released anymore causing memory warning sooner or later after some 100 calls.

```
using (CGPath haloPath = path.CopyByStrokingPath(haloRadius.Value, CGLineCap.Round, CGLineJoin.Round, 0))
{
    target.Target.CGContext.BeginPath();
    target.Target.CGContext.AddPath(haloPath);
    target.Target.CGContext.DrawPath(CGPathDrawingMode.Fill);
}
```
Versions:

https://gist.github.com/chamons/5ca4edf38220ac6fc88ce659c073d1ab

**Comment by chamons** [comment]
Thanks for the feedback. I believe this has been fixed in https://github.com/xamarin/xamarin-macios/commit/21475f7da6539a2ea796e628b5268b83a2997460 (2 weeks ago) but has not been released yet.

I'll let @rolfbjarne comment on potential work arounds.

Sorry for the trouble.

**Comment by chamons** [comment]
@TomQv A potential work around is to call `haloPath.DangerousRelease ()` at the end of your block before the using disposes of it.

That would fix your leak, however once you update to a Xamarin.iOS with a fix that workaround will start crashing your application, so remember to remove it (and test each update).

**Comment by TomQv** [comment]
@chamons   Thank you.

**Comment by TomQv** [comment]
@chamons Today we still had memory warnings. We are using many other CG functions with CGPath too. Are they maybe more bugs, where Dispose is not releasing memory? How do I know, when your fixes are released?
