### ISSUE TITLE
[.NET 6] Authorization.ExecuteWithPrivileges returns -60031 ToolExecuteError

### ISSUE THREAD

**Issue by mrward** [xamarin/xamarin-macios#13465]
### Steps to Reproduce

https://github.com/mrward/TestAuthMacOSNET6#readme

### Expected Behavior

Authorization.ExecuteWithPrivileges returns 0 to indicate success

### Actual Behavior

Authorization.ExecuteWithPrivileges returns -60031 [ToolExecuteFailure](https://developer.apple.com/documentation/security/1540004-authorization_services_result_co/errauthorizationtoolexecutefailure)

Same code works OK in a classic Xamarin.Mac project.

### Environment

```
Apple Developer Tools
Xcode 13.1 (19466)
Build 13A1030d

Operating System
Mac OS X 11.6.1
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Tue Oct 12 18:33:42 PDT 2021
    root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.100/Sdks
SDK Versions:
	6.0.100
	5.0.403
	3.1.415

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0
	5.0.12
	3.1.21
```

### Example Project

https://github.com/mrward/TestAuthMacOSNET6

**Comment by rolfbjarne** [comment]
It looks like this was a latent bug that recent changes uncovered.

The issue is that the arguments array must be null terminated, so adding a null entry at the end of the array makes things work:

```csharp
var args = new[] { "--help", null };
```

I'll modify our code to automatically do this.
