### ISSUE TITLE
Binary makes use of insecure API(s). Need official reports for it's Audit for Xamarin

### ISSUE THREAD

**Issue by sudhanshu079** [xamarin/xamarin-macios#13464]
We got Penetration tested for our application build in Xamarin.iOS by one of our important Clients and we got the analysis that our "Binary makes use of insecure API(s)".
![binary_analysis](https://user-images.githubusercontent.com/95129606/143680667-3eb958c6-ac4c-4437-a021-d68e86d1f802.PNG)

I have got it investigated and came to Conclusion that it is Xamarin.iOS which is using these functions at low level runtime. It is even giving this analysis for an empty project created in Xamarin.iOS.

I got some information about it on link below that Xamarin.iOS has been audited in past and got it correct for the usage of these functions.
https://docs.microsoft.com/en-us/answers/questions/525762/cyber-security-issues-ipa-binary-code-analysis-in.html

However we would need an official evidence for this Audit or an Official statement to be given to Client so that we can get it though. Can we Get some official documentation or any reports of this audit stating that the use of these InSecure functions and APIs are from Xamarin.iOS side and are proved correct?

I can be anytime reached out at my email id for any queries.

Looking for a positive acknowledgement. Thank you.

**Comment by filipnavara** [comment]
This was already answered before: https://github.com/xamarin/xamarin-macios/issues/12612

**Comment by sudhanshu079** [comment]
@filipnavara :- I Understand this was answered earlier. 

What I am asking in the description of my Issue is, We need to get an official report of Audit done for Xamarin.iOS that use of these APIs are from Xamarin side and are Secure.

We need to get through the process of Security Scan for an Important Client of us. So for their reference we require this Report or an official statement from Xamarin that these APIs are used at Xamarin runtime and are used correctly. Any help is appreciated . Thank You !

**Comment by filipnavara** [comment]
I suggest to read the previous answer completely. This automated tool is actually really vague at what it is checking and not helpful at all with the generic messages. Mono has been inspected by Coverity and manually in places where the APIs are used.

**Comment by chamons** [comment]
@filipnavara is absolutely correct and Sebastien's response [here](https://github.com/xamarin/xamarin-macios/issues/12612#issuecomment-911813349) is what you need to read.

We've reviewed a number of Coverity reports over the years and resolved legitimate concerns but pretty much any high performance runtime will trigger a number of those warnings no matter what.
