### ISSUE TITLE
The RuntimeIdentifier 'iossimulator-x64' is invalid. 

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#13482]
_From @arivoir on Wed, 15 Sep 2021 15:26:27 GMT_

After upgrading Visual Studio 2022 to preview 4. I can't complie iOS libraries.

> The RuntimeIdentifier 'iossimulator-x64' is invalid. 

What does this mean?

_Copied from original issue dotnet/maui#2495_

**Comment by rolfbjarne** [comment]
_From @arivoir on Wed, 15 Sep 2021 16:42:50 GMT_

Since iOS compilation is broken MAUI projects can not be compiled either. It would be interesting to have a way to disable iOS compilation. Now the only way to disable is to edit every single file and remove the TargetFramework

**Comment by rolfbjarne** [comment]
_From @drasticactions on Wed, 15 Sep 2021 18:08:45 GMT_

iOS Complication isn't broken, that specific iOS TargetFramework from an earlier version of the SDK package, and so workarounds that were in place in earlier maui templates are not needed.

In your csproj, you should be able to remove these lines

```
		<InvariantGlobalization Condition="$(TargetFramework.Contains('-maccatalyst'))">true</InvariantGlobalization>
		<RuntimeIdentifier Condition="$(TargetFramework.Contains('-ios'))">iossimulator-x64</RuntimeIdentifier>
		<RuntimeIdentifier Condition="$(TargetFramework.Contains('-maccatalyst'))">maccatalyst-x64</RuntimeIdentifier>
```

**Comment by rolfbjarne** [comment]
_From @arivoir on Thu, 16 Sep 2021 14:44:23 GMT_

That's the problem, after removing those lines, which I had removed before posting the issue, the problem is still there. Already deleted all "bin" and "obj" folder, what else should I remove?

**Comment by rolfbjarne** [comment]
_From @arivoir on Thu, 16 Sep 2021 14:59:29 GMT_

Some more things can help figure out the issue.

The project I'm not being able to compile targets both iOS and MacCatalyst

`<TargetFrameworks>net6.0-ios;net6.0-maccatalyst</TargetFrameworks>`

When clicking in the error in the "Error List" window of VS. it drives me to this
![image](https://user-images.githubusercontent.com/17496741/133635648-5cb5c3eb-e3f2-4ae0-ba14-40feed1c31f7.png)

So, apparently the problem is with mac-catalyst compilation

**Comment by rolfbjarne** [comment]
_From @arivoir on Thu, 16 Sep 2021 15:07:55 GMT_

Removing MacCatalyst from the TargetFramework's worked. What's the problem with targeting both platforms?

**Comment by rolfbjarne** [comment]
_From @arivoir on Thu, 16 Sep 2021 15:17:21 GMT_

Adding this workarounds the issue

```
  <PropertyGroup>
    <RuntimeIdentifier Condition="$(TargetFramework.Contains('-maccatalyst'))">maccatalyst-x64</RuntimeIdentifier>
  </PropertyGroup>
```
This wasn't needed in preview7. Looks like a regresion

**Comment by rolfbjarne** [comment]
_From @arivoir on Thu, 16 Sep 2021 15:42:21 GMT_

I compiled the project again, referencing it in another solution and the problem reappeared, even with the hard coded runtime-identifier. I went back to the original solution and now it also fails there.

**Comment by rolfbjarne** [comment]
_From @filipnavara on Thu, 02 Dec 2021 16:47:37 GMT_

It seems there's a funky glitch in how the runtime identifier is verified.

Let's say I have project A with `<TargetFramework>net6.0-ios</TargetFramework>` and project B with `<TargetFrameworks>netstandard2.1;net6.0-macos</TargetFrameworks>`. Project A references project B. I would expect that building project A succeeds but what seems to happen is that it tries to build both TFMs of project B while flowing `RuntimeIdentifier` from the parent project. That results in an attempt to build project B with TFM `net6.0-macos` and RID `iossimulator-x64` which is invalid combination.

cc @rolfbjarne

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Thu, 02 Dec 2021 18:03:50 GMT_

@filipnavara would you happen to have a test solution for those results, or a binlog from the build?

**Comment by rolfbjarne** [comment]
_From @filipnavara on Thu, 02 Dec 2021 19:25:12 GMT_

I tried to repro it on a smaller project but it didn't trigger so I guess it must be somewhat more complex. I should be able to make the binlog though (already had it and deleted it and then reinstalled .NET on the machine so let's hope it reproduces).

**Comment by rolfbjarne** [comment]
_From @filipnavara on Thu, 02 Dec 2021 19:48:26 GMT_

Here's a repro:
[Archive.zip](https://github.com/dotnet/maui/files/7644722/Archive.zip)

To trigger it you can either:
a) run `dotnet build exe /p:RuntimeIdentifier=iossimulator-x64`, or
b) run `dotnet run --project exe` (which in turn runs same sequence as a))

Running just `dotnet build exe` works.

**Comment by rolfbjarne** [comment]
I can reproduce, the problem is here:

https://github.com/xamarin/xamarin-macios/blob/135d6a982f1e74ae65dd336a7988a042deecadf8/dotnet/Microsoft.iOS.Sdk/targets/Microsoft.iOS.Sdk.targets#L13

the passed-in runtime identifier is a global property, and is set in all projects that are loaded.

OTOH I'm not sure we can even fix this, because somehow we have to pass the runtime identifier, otherwise doing this won't work:

> dotnet run --project exe --property RuntimeIdentifier=iossimulator-x64 

but we can't execute any tasks or targets... (due to https://github.com/dotnet/sdk/issues/18436).

**Comment by rolfbjarne** [comment]
heh, turns out it is possible to detect if a property is a global property or not without executing any tasks or targets:

```xml
    <PropertyGroup>
        <!-- store the current value of SomeProperty -->
        <CurrentPropertyValue>$(SomeProperty)</CurrentPropertyValue>
        <!-- try to change it -->
        <SomeProperty>$(SomeProperty)dummy</SomeProperty>
        <!-- if the property value didn't change, it's a global property -->
        <IsSomePropertyGlobal Condition="'$(SomeProperty)' == '$(CurrentPropertyValue)'">true</IsSomePropertyGlobal>
        <!-- otherwise it's not a global property -->
        <IsSomePropertyGlobal Condition="'$(IsSomePropertyGlobal)' == ''">false</IsSomePropertyGlobal>
        <!-- restore the property value in case it wasn't a global property (and we changed it) -->
        <CurrentPropertyValue>$(InputValue)</CurrentPropertyValue>
    </PropertyGroup>
```

**Comment by filipnavara** [comment]
Out of curiosity, what would be the use cases for using/checking `RuntimeIdentifier` in a class library?

**Comment by rolfbjarne** [comment]
> Out of curiosity, what would be the use cases for using/checking `RuntimeIdentifier` in a class library?

RuntimeIdentifier shouldn't be set in a class library (except when the class library is really an extension project, in which case there will be a RuntimeIdentifier, and it must be checked).
