### ISSUE TITLE
FSEvent Watcher is not working on Monterey 

### ISSUE THREAD

**Issue by matancoronet** [xamarin/xamarin-macios#13499]
### Description

I'm using FSEvent api which raise an event if any file on the system is changed.
The issue is happened when i updated my macOS version to  "Monterey"

I found that the "FSEvent" api is use "CoreServices" that located "System/Library/Frameworks/CoreServices.framework" , 
But "CoreServices" is NOT found on "Monterey" , So it the reason that my app is crashed.

### Expected Behavior
The api should works without crashing

### Actual Behavior
The app is crash when using "FSEvent" api.

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.10.14 (build 17)
Installation UUID: 98da6616-559d-4ca7-911d-561ee55b0cfc
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.403/Sdks
SDK Versions:
	5.0.403
	5.0.402
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.102
	5.0.101
	5.0.100
	3.1.415
	3.1.414
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.405
	3.1.404
	3.1.403
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.12
	5.0.11
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.2
	5.0.1
	5.0.0
	3.1.21
	3.1.20
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.11
	3.1.10
	3.1.9
	2.1.23

=== .NET Core 3.1 SDK ===

SDK: 3.1.415

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/matan/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Apple Developer Tools ===

Xcode 13.1 (19466)
Build 13A1030d

=== Xamarin.Mac ===

Version: 8.2.0.17 (Visual Studio Community)
Hash: 738fde344
Branch: xcode13.1
Build date: 2021-11-09 02:45:15-0500

=== Xamarin.iOS ===

Version: 15.2.0.17 (Visual Studio Community)
Hash: 738fde344
Branch: xcode13.1
Build date: 2021-11-09 02:45:16-0500

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 21:09:18 UTC

=== Build Information ===

Release ID: 810140017
Git revision: 6f93cf55df3b7747288286e2006057c7f088b838
Build date: 2021-11-12 09:50:18-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.1.0
Darwin 21.2.0 Darwin Kernel Version 21.2.0
    Tue Nov 16 23:24:19 PST 2021
    root:xnu-8019.61.4~4/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.51

```
```

**Comment by chamons** [comment]
Thanks for the feedback.

I believe this was reported already in https://github.com/xamarin/xamarin-macios/issues/13325, a fix has been created, and will hopefully be released soon.

If you need a work around until then, see []this comment](https://github.com/xamarin/xamarin-macios/issues/13325#issuecomment-971705899) for details.
