### ISSUE TITLE
Rename the properties in CGAffineTransform to match the one defined in iOS

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-macios#13494]
### Steps to Reproduce

CGAffineTransform has 6 properties xx, xy, yx, yy, x0, y0 that does not mean anything and are NOT DOCUMENTED AT ALL anywhere.

I had to look at Xamarin source code to finally find that comment in the CGAffineTransform class definition:

```
          //xx;    a
          //yx;    b 
          //xy;    c
          //yy;    d
          //x0;    tx
          //y0;    ty
```

### Expected Behavior

CGAffineTransform  should have properties called a,b,c,d,tx,ty exactly like iOS has.

### Actual Behavior

CGAffineTransform  have fancy property names that are not documented (ie: you don't know in which matrix cell goes which value).

### Environment

Xamarin.iOS

**Comment by rachelkang** [comment]
Hi, @softlion - thank you for the feedback. We unfortunately cannot modify the property names as it would be a breaking change for all our customers who use `CGAffineTransform`. 

However, I will look into options for documentation changes to see if we can make this more clear.

**Comment by chamons** [comment]
After discussions with the teams we've moved it to NET6 for consideration as a breaking change.

**Comment by softlion** [comment]
For SCNVector4, there is a constructor overload taking a SCNVector3.  
It does not exist on native iOS. And it is not documented on Xamarin.iOS.  
It seems to set the W value to 0. This should be written in the doc too :)
