### ISSUE TITLE
IEnumResolutionResult.NeedsValue cannot be cast to the class that implements the interface

### ISSUE THREAD

**Issue by Picao84** [xamarin/xamarin-macios#13500]
### Steps to Reproduce

1. Create a Siri Shortcut Intent where one of the parameters is an Enum
2. Create code for handling of intent
3. Implement the Resolve method
4. Cast IEnumResolution.NeedsValue to class that implements the interface

### Expected Behavior

Siri Shortcut execution should continue and ask for value for enum.

### Actual Behavior

Throws Specified cast is not valid Exception.

### More Details

I know that there is not a lot of information above, but from my research this seems to be an identical issue to https://bugzilla.xamarin.com/show_bug.cgi?id=43205, which was fixed and also dealt with a static NeedsValue property.

Could this be fixed or is there some way to work around it? Its blocking an implementation of Siri Shortcuts.

Thanks,
Tiago

**Comment by rachelkang** [comment]
Hi, @Picao84 - thank you for the feedback. It's possible that the issue may be related to the enum being used in your specific use case. As we don't have other examples reproducing this issue, would you please share your project or a sample reproducing the issue so that we can investigate further?

**Comment by Picao84** [comment]
Hi,

I got it fixed by changing the type from my "{myEnum}ResolutionResult" to the interface IEnumResolutionResult on the Obj-C Header file. Only have to do that every time after I build the Obj-C project where the intents are.

**Comment by rachelkang** [comment]
Hi, @Picao84 - does this mean you have found a solution? Or is it just a workaround?

**Comment by Picao84** [comment]
I think it's more of a work around because it requires changing the header file generated by Xcode, prior to running Objective Sharpie. I don't think that Objective Sharpie ever does any changes to the Objective-C files themselves? And since this is a class created by the developer, implementing the interface, maybe there is not much you can do?

**Comment by rachelkang** [comment]
@Picao84 could you share your project or a sample project reproducing the issue so that we can investigate this further? Thanks!

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
