### ISSUE TITLE
Visual Studio for Mac does not show warning for depreciated iOS API

### ISSUE THREAD

**Issue by RenjitGit** [xamarin/xamarin-macios#13520]
### Description

I am developing Xamarin Native application (Xamarin.iOS & Xamarin.Android). iOS app supports iOS 13 and above (iOS deployment target is set as 13). Source code is using few iOS API's that are depreciated and Visual studio for Mac does not show warning for those APIs.

Following are the example of depreciated API's

UIApplication.SharedApplication.KeyWindow (https://developer.apple.com/documentation/uikit/uiapplication/1622924-keywindow) 
ABAddressBook.GetAuthorizationStatus() (https://developer.apple.com/documentation/eventkit/abaddressbookref)

### Expected Behavior
Visual studio for Mac should show warning for depreciated APIs

### Actual Behavior
Visual studio for Mac not showing warning for depreciated APIs

<details>
  <summary>Environment</summary>
  
=== Visual Studio Community 2019 for Mac ===

        Version 8.10.5 (build 16)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.301/Sdks
SDK Versions:
	5.0.301
	5.0.100
	3.1.410
	3.1.402
	3.1.302
	3.1.301
	3.0.101
	2.1.700
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.7
	5.0.0
	3.1.16
	3.1.8
	3.1.6
	3.1.5
	3.0.1
	2.1.23
	2.1.22
	2.1.20
	2.1.19
	2.1.11

=== .NET Core 3.1 SDK ===

SDK: 3.1.410

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/ee210989/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.3
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/ee210989/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:34 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:52 UTC

=== Xamarin Designer ===

Version: 16.10.0.119
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Apple Developer Tools ===

Xcode 12.5.1 (18212)
Build 12E507

=== Xamarin.Mac ===

Version: 7.14.0.24 (Visual Studio Community)
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Build Information ===

Release ID: 810050016
Git revision: d6bd382154950cedf91ffdf19704a7c61888a3b4
Build date: 2021-07-02 06:38:37-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Android Signature Tool 2.2.0
</details>

**Comment by rachelkang** [comment]
Hi, @RenjitGit - thanks for the feedback!

This is an IDE issue, so please file it [here](https://developercommunity.visualstudio.com/report?space=41&entry=suggestion) so that the appropriate folks can hear your feedback.
