### ISSUE TITLE
MissingMethodException Microsoft.CodeAnalysis.CSharp.Syntax.SimpleLambdaExpressionSyntax 

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-macios#13539]
I created a simple app using some nuget packages.  
When building for Android with VS 2022 windows, it builds fine.  
When building for iOS with VS mac (2019) or appcenter build, it fails with this error.

![image](https://user-images.githubusercontent.com/190756/145724638-fc5e4d88-7f09-483e-b7bb-ba893f19cfa6.png)

Error:

`CSC : error RXMERR: Exception System.MissingMethodException: Method not found: Microsoft.CodeAnalysis.CSharp.Syntax.SimpleLambdaExpressionSyntax Microsoft.CodeAnalysis.CSharp.SyntaxFactory.SimpleLambdaExpression(Microsoft.CodeAnalysis.SyntaxList`1<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax>,Microsoft.CodeAnalysis.SyntaxTokenList,Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax,Microsoft.CodeAnalysis.SyntaxToken,Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax,Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax)`

Is it because VS19 mac does not support source generators ?

### Steps to Reproduce

1. Create an app with the above nugets
2. Build for iOS on mac 

### Expected Behavior
Build

### Actual Behavior
Fails to build

### Environment

```
Vs mac 2019
```

**Comment by softlion** [comment]
Note: it seems it IS because source generators are not supported by Xamarin on Mac yet  (ie: using msbuild 15).

**Comment by rachelkang** [comment]
@softlion yes, it appears that VS2019 for Mac does not currently support source generators.

In the future, with IDE issues, you're more likely to hear from the VSMac team by filing your issue here: https://developercommunity.visualstudio.com/report?space=41&entry=problem

**Comment by softlion** [comment]
> @softlion yes, it appears that VS2019 for Mac does not currently support source generators.
> 
> In the future, with IDE issues, you're more likely to hear from the VSMac team by filing your issue here: https://developercommunity.visualstudio.com/report?space=41&entry=problem

It's not an IDE issue. It's a xamarin iOS SDK issue.
