### ISSUE TITLE
[dotnet] NSUrlSessionHandler and .NET 6 methods called from HttpClientHandler

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#13579]
The methods implemented in this block seem to have couple of issues:

https://github.com/xamarin/xamarin-macios/blob/69015b3cecbb2c7f94c4cbafb37c3c5aa091f166/src/Foundation/NSUrlSessionHandler.cs#L535-L613

Firstly, the `Supports*` properties are not supposed to throw. They are discoverability properties to see if other members would throw. In the current implementation they should likely return `false`. 

In case of `AutomaticDecompression` / `SupportsAutomaticDecompression` it may make sense to lie since the underlying handler probably does the automatic decompression. Note that some libraries may get broken no matter how it is implemented. I remember some of our ActiveSync / EWS code depended on the automatic decompression mechanism removing the `Content-Encoding` header if the automatic decompression is performed. I am not sure how the `NSUrlSessionHandler` behaves here.

Xamarin.Android also [lies](https://github.com/xamarin/xamarin-android/blob/05dd813db4516ecd6767c97a6ed0fba630256b89/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L125) about `ServerCertificateCustomValidationCallback`. It doesn't throw and silently ignores it. It would be nice to have this unifed across platforms. It would be even nicer if the callback was actually implemented but that's separate issue. Old PRs/issues have the implementation already but it was not accepted at the time due to size issues caused by the `X509Certificate` dependency. That's no longer an issue on .NET 6 since the dependency exists anyway.

**Comment by dotMorten** [comment]
My main issue is a .NET Standard library doing this:
```cs
var handler = new System.Net.Http.HttpClientHandler()
{
    AutomaticDecompression = DecompressionMethods.GZip
};
```

I'd expect this standard code to "just work", but feel free to ignore the compression property. Throwing like Preview 11 started doing makes the 3rd party library unusable.

**Comment by dotMorten** [comment]
`PreAuthenticate` throws as well.

**Comment by mandel-macaque** [comment]
Easy fix, will take care of it.

**Comment by rolfbjarne** [comment]
I've proposed a PR for this: https://github.com/xamarin/xamarin-macios/pull/14484 - @filipnavara / @dotMorten could you review and see if my changes would work for you?
