### ISSUE TITLE
MergeAppBundles MSBuild task doesn't finish

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#13580]
### Steps to Reproduce

1. macOS app project with `net6.0-macos` TargetFramework
2. `<RuntimeIdentifiers>osx-x86_64</RuntimeIdentifiers>`

### Expected Behavior

MSBuild task completes

### Actual Behavior

MSBuild just stays stuck there. 

It works fine with `<RuntimeIdentifier>`

### Environment

6.0.101 .NET 6 SDK.

Will try and get a sample project

**Comment by Therzok** [comment]
Of course I can't reproduce it anymore...

**Comment by rolfbjarne** [comment]
It's a dup of #12422.
