### ISSUE TITLE
Ability to disable _DetectAppManifest

### ISSUE THREAD

**Issue by KirillOsenkov** [xamarin/xamarin-macios#13583]
For projects with a lot of `@(None)` items, the `_DetectAppManifest` runs even when there is no Info.plist and it's not needed. However it still takes time (>600ms for enough items), and there's no way to turn it off for projects where you don't need it.

Need to probably add a Condition on the target, something like `Condition="$(DisableDetectAppManifest) != true"`

**Comment by rolfbjarne** [comment]
How convenient that I implemented this just a couple of days ago: https://github.com/xamarin/xamarin-macios/pull/13550 😄 

For other reasons, but it's pretty much what you suggested (although the variable is called `AppManifestDetectionEnabled`).

**Comment by KirillOsenkov** [comment]
ZOMG Amazing :)
