### ISSUE TITLE
Port samples to .NET

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#13594]
We should port some of our samples to .NET.

Repositories with samples:

* https://github.com/xamarin/ios-samples
* https://github.com/xamarin/mac-ios-samples
* https://github.com/xamarin/mac-samples
* https://github.com/xamarin/mobile-samples
* https://github.com/xamarin/prebuilt-apps
* https://github.com/xamarin/xamarin-forms-samples
* https://github.com/xamarin/xamarin-forms-book-samples
* https://github.com/rolfbjarne/embedded-frameworks
* https://github.com/davidortinau/Xappy
* https://github.com/microsoft/SmartHotel360-Mobile

**Comment by rolfbjarne** [comment]
@dalexsoto @tj-devel709 @stephen-hawley what's the status of this? Which samples were ported, and were they all updated after the latest breaking changes (in RC 1)?

**Comment by dalexsoto** [comment]
@rolfbjarne we only ported samples from https://github.com/xamarin/ios-samples repository
* [DragAndDropDragBoard](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios11/DragAndDropDragBoard)
* [FaceIDSample](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios11/FaceIDSample)
* [MapKitSample](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios11/MapKitSample)
* [ARKitVision](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios12/ARKitVision)
* [ARMultiuser](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios12/ARMultiuser)
* [BreakfastFinder](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios12/BreakfastFinder)
* [ExceptionalAccessibility](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios12/ExceptionalAccessibility)
* [GroupedNotifications](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios12/GroupedNotifications)
* [MarsHabitatCoreMLTimer](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios12/MarsHabitatCoreMLTimer)
* [MarsHabitatPricePredictor](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios12/MarsHabitatPricePredictor)
* [RedGreenNotifications](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios12/RedGreenNotifications)
* [VisionObjectTrack](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios12/VisionObjectTrack)
* [XamarinNL](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios12/XamarinNL)
* [AdoptingIOSDarkMode](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios13/AdoptingIOSDarkMode)
* [DisablingPullingDownASheet](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios13/DisablingPullingDownASheet)
* [SupportingMultipleWindowsOniPad](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios13/SupportingMultipleWindowsOniPad)
* [UsingCollectionViewCompositionalLayoutsAndDiffableDataSources](https://github.com/xamarin/ios-samples/tree/dotnet/dotnet/ios/ios13/UsingCollectionViewCompositionalLayoutsAndDiffableDataSources)

IIRC @tj-devel709 did a pass on them with RC1 bits but he can confirm

**Comment by rolfbjarne** [comment]
We've ported some samples, so I'm closing this.
