### ISSUE TITLE
Pait to MAC failed due to dotnet sdk download failed

### ISSUE THREAD

**Issue by ZhibingGe** [xamarin/xamarin-macios#13609]
### Steps to Reproduce

1. Open VS2022 and a MAUI solution
2. Click pair to MAC and follow the step

### Expected Behavior
MAC should be added
### Actual Behavior
Mac cannot be added due to dotnet sdk cannot be downloaded

### Environment
Windows :VS: 17.1.0 preview 1.1
MAC: has already installed dotnet sdk 6.0.100

```
```

### Build Logs
Xamarin Log:
Downloading dotnet-install script...
dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100/dotnet-sdk-6.0.100-osx-x64.tar.gz
curl: (56) LibreSSL SSL_read: Connection reset by peer, errno 54
dotnet-install: Download attempt #1 has failed: 200 Unable to download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100/dotnet-sdk-6.0.100-osx-x64.tar.gz.
dotnet-install: Attempt #2 will start in 10 seconds.
curl: (56) LibreSSL SSL_read: Connection reset by peer, errno 54
dotnet-install: Download attempt #2 has failed: 200 Unable to download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.100/dotnet-sdk-6.0.100-osx-x64.tar.gz.
dotnet-install: Attempt #3 will start in 20 seconds.
curl: (56) LibreSSL SSL_read: Connection reset by peer, errno 54

### Example Project (If Possible)

Can the dotnet sdk installation step be skipped as the sdk has been installed in MAC

**Comment by rachelkang** [comment]
Hi, @ZhibingGe - thanks for opening this issue. Please reopen the issue via https://developercommunity.visualstudio.com/report?space=8&entry=problem so that your report can reach the appropriate team.
