### ISSUE TITLE
macos and ios workloads do not seem to ship API documentation

### ISSUE THREAD

**Issue by sandyarmstrong** [xamarin/xamarin-macios#13614]
1. Create a .NET 6 macos or ios project.
2. Open the project in VSMac Preview 4 (which runs on .NET 6, and temporarily cannot load the old monodoc-based help).
3. Open some source in the editor.
4. Hover over a type like `UIViewController` or `NSMutableDictionary`.

## Expected results

Editor tooltip shows descriptive help text for the type.

## Actual results

Editor only shows bare type information, no descriptive help text.

---

I am working on bringing back monodoc support to VSMac, which would allow loading help text from the documentation that ships in `/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/share/doc/`, but that isn't really correct.

Based on how it seems to work for the rest of the .NET 6 packs, I think workload API docs should be in XML files that ship alongside their DLLs. `System.*` types get descriptive help text in editor tooltips without issue.

**Comment by sandyarmstrong** [comment]
# Expected

<img width="536" alt="image" src="https://user-images.githubusercontent.com/155076/146813451-396e1440-615c-4ced-8598-0625469c1403.png">


# Actual

<img width="283" alt="image" src="https://user-images.githubusercontent.com/155076/146813412-054da51f-1758-4a31-9c37-bd66ee2cf1d5.png">

**Comment by rolfbjarne** [comment]
@jonathanpeppers how does XA handle API documentation in .NET? Do you handle documentation at all?

**Comment by jonathanpeppers** [comment]
If you look at: https://www.nuget.org/packages/Microsoft.Android.Ref.31/31.0.101-preview.11.117

We still have `Mono.Android.xml` inside, just like we had for Xamarin.Android.

**Comment by rolfbjarne** [comment]
This is partially fixed, in that we know ship the Microsoft.iOS.xml file in the ref pack in the workload.

This means that the IDE should show any documentation in the xml file - the problem is that the file is almost empty.

This last part will be handled in https://github.com/xamarin/xamarin-macios/issues/14372, so I'm considering this issue half done / half duplication of https://github.com/xamarin/xamarin-macios/issues/14372.
