### ISSUE TITLE
Xamarin.PreBuilt.iOS prevents building xamarin-macios completely without private provisioning profile

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#13630]
### Steps to Reproduce

1.  Try to build xamarin-macios on a new machine without Xamarin profiles/keys installed (and without maccore sync'ed down)
2. Follow instructions [here](https://github.com/xamarin/xamarin-macios/wiki/Build-&-Run)
3. Build error:

```
/Users/donblas/Programming/xamarin-macios/builds/downloads/dotnet-sdk-6.0.200-preview.21614.17-osx-x64/packs/Microsoft.iOS.Sdk/15.0.101-preview.12.722/tools/msbuild/iOS/Xamarin.Shared.targets(1566,3): error : Could not find any available provisioning profiles for Xamarin.PreBuilt.iOS on iOS. [/Users/donblas/Programming/xamarin-macios/msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj]
/Users/donblas/Programming/xamarin-macios/builds/downloads/dotnet-sdk-6.0.200-preview.21614.17-osx-x64/packs/Microsoft.iOS.Sdk/15.0.101-preview.12.722/tools/msbuild/iOS/Xamarin.Shared.targets(1566,3): error :          [/Users/donblas/Programming/xamarin-macios/msbuild/Xamarin.HotRestart.PreBuilt/Xamarin.PreBuilt.iOS/Xamarin.PreBuilt.iOS.csproj]
```

### Expected Behavior
Successful build

### Actual Behavior

https://gist.github.com/chamons/6ade342c882fe230be5b012a87e5940d

**Comment by chamons** [comment]
FYI @emaf @rolfbjarne

Does https://github.com/xamarin/xamarin-macios/blob/main/dotnet/Makefile#L412-L414 need to be behind a `ifdef ENABLE_XAMARIN` like https://github.com/xamarin/xamarin-macios/blob/main/Makefile#L179-L181?

**Comment by rolfbjarne** [comment]
Any wildcard provisioning profile with a certificate should work.

**Comment by rolfbjarne** [comment]
https://github.com/xamarin/xamarin-macios/pull/13387 might fix this.

**Comment by rolfbjarne** [comment]
I believe this has been fixed.
