### ISSUE TITLE
AudioUnit Input Callback will throw when triggered as gchandle is not set.

### ISSUE THREAD

**Issue by james-allison** [xamarin/xamarin-macios#13637]
https://github.com/xamarin/xamarin-macios/blob/3fe85ef24caffbf3405ae34cb10003ae1ec71ae5/src/AudioUnit/AudioUnit.cs#L647

gchandle is null unless SetRenderCallback has been called prior to this.

If SetInputCallback was called first, the app will crash as soon as the NotifyInputAvailable event is triggered with a 'GCHandle value cannot be zero' exception.

**Comment by rachelkang** [comment]
Hi, @james-allison - thanks for opening this issue. It seems like this may be related to recent refactoring efforts.

cc @rolfbjarne
