### ISSUE TITLE
MT5216 - Unable to build project for  iPhone (Error MT5216: Native linking failed)

### ISSUE THREAD

**Issue by santosh-qas** [xamarin/xamarin-macios#13640]
### Steps to Reproduce

1. Add Twilio.Video.XamarinBinding package to iOS project
2. Connect iPhone to Mac
3. Rebuild solution

### Expected Behavior
app should be deployed and run on debug mode in iPhone
### Actual Behavior
Getting error **Error MT5216: Native linking failed for '/Users/apple/Documents/Workspace/MYAPP/MYAPP.iOS/obj/iPhone/Debug/mtouch-cache/arm64/libTwilio.Video.iOS.dll.dylib'.
**
### Environment
**Macbook Pro 
OS : macOS BigSur 11.6.2 (20G314)**

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.16 (build 2)
Installation UUID: 5f002cad-a9c9-4cdc-9fd1-410e9117afdb
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/6.0.101/Sdks
SDK Versions:
	6.0.101
	5.0.404
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.1
	5.0.13
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.404

=== Xamarin.Profiler ===

Version: 1.7.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 15.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 21:09:18 UTC

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/apple/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810160002
Git revision: 6dbc7886fa608147f685a7df3912249400c84716
Build date: 2021-12-14 15:54:37-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 11.6.2
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Nov 10 22:23:07 PST 2021
    root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64

```

### Build Logs

arget _WriteAppManifest:
    Directory "bin/iPhone/Debug/MYAPP.iOS.app.dSYM" doesn't exist. Skipping.
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/apple/Documents/Workspace/MYAPP-v4/MYAPP/MYAPP.iOS/obj/iPhone/Debug/response-file.rsp 
    Xamarin.iOS 15.4.0.0 (xcode13.2: 8fc41ae82) using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk
    MTOUCH : warning MT0109: The assembly 'System.Security.Cryptography.Cng.dll' was loaded from a different path than the provided path (provided path: /Users/apple/.nuget/packages/system.security.cryptography.cng/4.5.0/runtimes/win/lib/netstandard1.6/System.Security.Cryptography.Cng.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/15.4.0.0/lib/mono/Xamarin.iOS/Facades/System.Security.Cryptography.Cng.dll).
    		
    Compilation failed with code 1, command:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -framework Foundation -framework CFNetwork -framework UIKit -Xlinker -rpath -Xlinker @executable_path/ /Users/apple/Documents/Workspace/MYAPP-v4/MYAPP/MYAPP.iOS/obj/iPhone/Debug/mtouch-cache/arm64/Twilio.Video.iOS.dll.o /Library/Frameworks/Xamarin.iOS.framework/Versions/15.4.0.0/SDKs/MonoTouch.iphoneos.sdk/lib/libmonosgen-2.0.dylib /Library/Frameworks/Xamarin.iOS.framework/Versions/15.4.0.0/SDKs/MonoTouch.iphoneos.sdk/lib/libxamarin-debug.dylib /Library/Frameworks/Xamarin.iOS.framework/Versions/15.4.0.0/SDKs/MonoTouch.iphoneos.sdk/lib/libmono-native-unified.dylib -lz -liconv -lz -gdwarf-2 -std=c++14 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/15.4.0.0/SDKs/MonoTouch.iphoneos.sdk/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk -Qunused-arguments -miphoneos-version-min=11.4 -arch arm64 -shared -lz -liconv -install_name @rpath/libTwilio.Video.iOS.dll.dylib -fapplication-extension -o /Users/apple/Documents/Workspace/MYAPP-v4/MYAPP/MYAPP.iOS/obj/iPhone/Debug/mtouch-cache/arm64/libTwilio.Video.iOS.dll.dylib -D DEBUG -u _OBJC_CLASS_$_TVIAppScreenSource -u _OBJC_CLASS_$_TVIAppScreenSourceOptions -u _OBJC_CLASS_$_TVIAppScreenSourceOptionsBuilder -u _OBJC_CLASS_$_TVIAudioCodec -u _OBJC_CLASS_$_TVIAudioFormat -u _OBJC_CLASS_$_TVIAudioOptions -u _OBJC_CLASS_$_TVIAudioOptionsBuilder -u _OBJC_CLASS_$_TVIAudioTrack -u _OBJC_CLASS_$_TVIAudioTrackPublication -u _OBJC_CLASS_$_TVIBandwidthProfileOptions -u _OBJC_CLASS_$_TVIBaseTrackStats -u _OBJC_CLASS_$_TVICameraPreviewView -u _OBJC_CLASS_$_TVICameraSource -u _OBJC_CLASS_$_TVICameraSourceOptions -u _OBJC_CLASS_$_TVICameraSourceOptionsBuilder -u _OBJC_CLASS_$_TVIConnectOptions -u _OBJC_CLASS_$_TVIConnectOptionsBuilder -u _OBJC_CLASS_$_TVIDataTrack -u _OBJC_CLASS_$_TVIDataTrackOptions -u _OBJC_CLASS_$_TVIDataTrackOptionsBuilder -u _OBJC_CLASS_$_TVIDataTrackPublication -u _OBJC_CLASS_$_TVIDefaultAudioDevice -u _OBJC_CLASS_$_TVIEncodingParameters -u _OBJC_CLASS_$_TVIG722Codec -u _OBJC_CLASS_$_TVIH264Codec -u _OBJC_CLASS_$_TVIIceCandidatePairStats -u _OBJC_CLASS_$_TVIIceCandidateStats -u _OBJC_CLASS_$_TVIIceOptions -u _OBJC_CLASS_$_TVIIceOptionsBuilder -u _OBJC_CLASS_$_TVIIceServer -u _OBJC_CLASS_$_TVIIsacCodec -u _OBJC_CLASS_$_TVILocalAudioTrack -u _OBJC_CLASS_$_TVILocalAudioTrackPublication -u _OBJC_CLASS_$_TVILocalAudioTrackStats -u _OBJC_CLASS_$_TVILocalDataTrack -u _OBJC_CLASS_$_TVILocalDataTrackPublication -u _OBJC_CLASS_$_TVILocalParticipant -u _OBJC_CLASS_$_TVILocalTrackPublicationOptions -u _OBJC_CLASS_$_TVILocalTrackStats -u _OBJC_CLASS_$_TVILocalVideoTrack -u _OBJC_CLASS_$_TVILocalVideoTrackPublication -u _OBJC_CLASS_$_TVILocalVideoTrackStats -u _OBJC_CLASS_$_TVINetworkQualityConfiguration -u _OBJC_CLASS_$_TVIOpusCodec -u _OBJC_CLASS_$_TVIParticipant -u _OBJC_CLASS_$_TVIPcmaCodec -u _OBJC_CLASS_$_TVIPcmuCodec -u _OBJC_CLASS_$_TVIRemoteAudioTrack -u _OBJC_CLASS_$_TVIRemoteAudioTrackPublication -u _OBJC_CLASS_$_TVIRemoteAudioTrackStats -u _OBJC_CLASS_$_TVIRemoteDataTrack -u _OBJC_CLASS_$_TVIRemoteDataTrackPublication -u _OBJC_CLASS_$_TVIRemoteParticipant -u _OBJC_CLASS_$_TVIRemoteTrackStats -u _OBJC_CLASS_$_TVIRemoteVideoTrack -u _OBJC_CLASS_$_TVIRemoteVideoTrackPublication -u _OBJC_CLASS_$_TVIRemoteVideoTrackStats -u _OBJC_CLASS_$_TVIRoom -u _OBJC_CLASS_$_TVIStatsReport -u _OBJC_CLASS_$_TVITrack -u _OBJC_CLASS_$_TVITrackPublication -u _OBJC_CLASS_$_TVIUserInterfaceTracker -u _OBJC_CLASS_$_TVIVideoBandwidthProfileOptions -u _OBJC_CLASS_$_TVIVideoBandwidthProfileOptionsBuilder -u _OBJC_CLASS_$_TVIVideoCodec -u _OBJC_CLASS_$_TVIVideoDimensions -u _OBJC_CLASS_$_TVIVideoFormat -u _OBJC_CLASS_$_TVIVideoFrame -u _OBJC_CLASS_$_TVIVideoRenderDimensions -u _OBJC_CLASS_$_TVIVideoTrack -u _OBJC_CLASS_$_TVIVideoTrackPublication -u _OBJC_CLASS_$_TVIVideoView -u _OBJC_CLASS_$_TVIVp8Codec -u _OBJC_CLASS_$_TVIVp9Codec -u _OBJC_CLASS_$_TwilioVideoSDK
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_TVIAppScreenSource", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIAppScreenSourceOptions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIAppScreenSourceOptionsBuilder", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIAudioCodec", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIAudioFormat", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIAudioOptions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIAudioOptionsBuilder", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIAudioTrack", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIAudioTrackPublication", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIBandwidthProfileOptions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIBaseTrackStats", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVICameraPreviewView", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVICameraSource", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVICameraSourceOptions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVICameraSourceOptionsBuilder", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIConnectOptions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIConnectOptionsBuilder", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIDataTrack", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIDataTrackOptions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIDataTrackOptionsBuilder", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIDataTrackPublication", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIDefaultAudioDevice", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIEncodingParameters", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIG722Codec", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIH264Codec", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIIceCandidatePairStats", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIIceCandidateStats", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIIceOptions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIIceOptionsBuilder", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIIceServer", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIIsacCodec", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalAudioTrack", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalAudioTrackPublication", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalAudioTrackStats", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalDataTrack", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalDataTrackPublication", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalParticipant", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalTrackPublicationOptions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalTrackStats", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalVideoTrack", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalVideoTrackPublication", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVILocalVideoTrackStats", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVINetworkQualityConfiguration", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIOpusCodec", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIParticipant", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIPcmaCodec", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIPcmuCodec", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRemoteAudioTrack", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRemoteAudioTrackPublication", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRemoteAudioTrackStats", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRemoteDataTrack", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRemoteDataTrackPublication", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRemoteParticipant", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRemoteTrackStats", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRemoteVideoTrack", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRemoteVideoTrackPublication", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRemoteVideoTrackStats", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIRoom", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIStatsReport", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVITrack", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVITrackPublication", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIUserInterfaceTracker", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVideoBandwidthProfileOptions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVideoBandwidthProfileOptionsBuilder", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVideoCodec", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVideoDimensions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVideoFormat", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVideoFrame", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVideoRenderDimensions", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVideoTrack", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVideoTrackPublication", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVideoView", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVp8Codec", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TVIVp9Codec", referenced from:
         -u command line option
      "_OBJC_CLASS_$_TwilioVideoSDK", referenced from:
         -u command line option
    ld: symbol(s) not found for architecture arm64
    clang : error : linker command failed with exit code 1 (use -v to see invocation)
    MTOUCH : error MT5216: Native linking failed for '/Users/apple/Documents/Workspace/MYAPP-v4/MYAPP/MYAPP.iOS/obj/iPhone/Debug/mtouch-cache/arm64/libTwilio.Video.iOS.dll.dylib'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
    		
Done building target "_CompileToNative" in project "MYAPP.iOS.csproj" -- FAILED.

Done building project "MYAPP.iOS.csproj" -- FAILED.

Build FAILED.

Resources/placeholder_avatar.png : warning : Warning: Input PNG does not have an 8 bit input depth.  Please convert your PNG to 8-bit for optimal performance on iPhone OS.
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277: Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved.
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277: There was a conflict between "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:     "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:     References which depend on "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Numerics.Vectors.dll].
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:         /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Numerics.Vectors.dll
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:           Project file item includes which caused reference "/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Numerics.Vectors.dll".
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:             System.Numerics.Vectors
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:     References which depend on "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:         /Users/apple/.nuget/packages/microsoft.aspnetcore.server.kestrel.core/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:           Project file item includes which caused reference "/Users/apple/.nuget/packages/microsoft.aspnetcore.server.kestrel.core/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll".
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:             /Users/apple/.nuget/packages/microsoft.aspnetcore.server.kestrel.core/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:             /Users/apple/.nuget/packages/microsoft.aspnetcore/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.dll
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:             /Users/apple/.nuget/packages/microsoft.aspnetcore.server.kestrel/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.dll
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3277:             /Users/apple/.nuget/packages/microsoft.aspnetcore.server.kestrel.https/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Https.dll
/Users/apple/Documents/Workspace/MYAPP-v4/MYAPP/MYAPP.iOS/Main.cs(17,13,17,58): warning CS0618: 'UIApplication.Main(string[]?, string?, string?)' is obsolete: 'Use the overload with 'Type' instead of 'String' parameters for type safety.'
/Users/apple/Documents/Workspace/MYAPP-v4/MYAPP/MYAPP.iOS/Services/IOService.cs(41,30,41,32): warning CS0168: The variable 'ex' is declared but never used
MTOUCH : warning MT0109: The assembly 'System.Security.Cryptography.Cng.dll' was loaded from a different path than the provided path (provided path: /Users/apple/.nuget/packages/system.security.cryptography.cng/4.5.0/runtimes/win/lib/netstandard1.6/System.Security.Cryptography.Cng.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/15.4.0.0/lib/mono/Xamarin.iOS/Facades/System.Security.Cryptography.Cng.dll).
clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5216: Native linking failed for '/Users/apple/Documents/Workspace/MYAPP-v4/MYAPP/MYAPP.iOS/obj/iPhone/Debug/mtouch-cache/arm64/libTwilio.Video.iOS.dll.dylib'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
    10 Warning(s)
    2 Error(s)

Time Elapsed 00:01:08.30

========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Also it is observed that the file **libTwilio.Video.iOS.dll.dylib'** is not created at the specified location.

**Comment by Phenek** [comment]
UP, I got the same issue!

**Comment by santosh-qas** [comment]
<img width="622" alt="setting" src="https://user-images.githubusercontent.com/92707343/147655043-d1387f13-c10c-4e89-b652-2b311781d9e1.png">
with attached setting it built successfully

**Comment by rachelkang** [comment]
Hi, @santosh-qas - thanks for opening this issue. What settings did you change to make it build successfully? 

From the logs you've shared
```
"_OBJC_CLASS_$_TwilioVideoSDK", referenced from:
     -u command line option
ld: symbol(s) not found for architecture arm64
clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5216: Native linking failed for '/Users/apple/Documents/Workspace/MYAPP-v4/MYAPP/MYAPP.iOS/obj/iPhone/Debug/mtouch-cache/arm64/libTwilio.Video.iOS.dll.dylib'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
```
it looks like `_TwilioVideoSDK` does not support `arm64` architecture. Consider reaching out to the vendor to confirm that they support it.

**Comment by santosh-qas** [comment]
> Hi, @santosh-qas - thanks for opening this issue. What settings did you change to make it build successfully?
> 
> From the logs you've shared
> 
> ```
> "_OBJC_CLASS_$_TwilioVideoSDK", referenced from:
>      -u command line option
> ld: symbol(s) not found for architecture arm64
> clang : error : linker command failed with exit code 1 (use -v to see invocation)
> MTOUCH : error MT5216: Native linking failed for '/Users/apple/Documents/Workspace/MYAPP-v4/MYAPP/MYAPP.iOS/obj/iPhone/Debug/mtouch-cache/arm64/libTwilio.Video.iOS.dll.dylib'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
> ```
> 
> it looks like `_TwilioVideoSDK` does not support `arm64` architecture. Consider reaching out to the vendor to confirm that they support it.
