### ISSUE TITLE
Correct mapping for AVCaptureVideoPreview layerRectConverted(fromMetadataOutputRect:)

### ISSUE THREAD

**Issue by Axemasta** [xamarin/xamarin-macios#13649]
I'm currently reproducing a swift sample in Xamarin.iOS and came across the following which I was unsure on how to map:

`let videoPreviewRect = previewLayer.layerRectConverted(fromMetadataOutputRect: CGRect(x: 0, y: 0, width: 1, height: 1))`
> full code [here](https://github.com/yamazaki8934/VisionFaceTrack/blob/84c55a565937c76e4746452307ca8a6323a60735/VisionFaceTrack/ViewController.swift#L340)

Apple docs for this [api](https://github.com/yamazaki8934/VisionFaceTrack/blob/84c55a565937c76e4746452307ca8a6323a60735/VisionFaceTrack/ViewController.swift#L340)

I had an older copy of this repo locally and saw the following in the [`osx.pending`](https://github.com/xamarin/xamarin-macios/blob/2dc06c712629feeb179ed112a590d9922caac6e7/tests/xtro-sharpie/osx.pending#L89) file:
`!missing-selector! AVCaptureVideoPreviewLayer::rectForMetadataOutputRectOfInterest: not bound`

Would it be possible to map this api? is there any equivalent we could use in the meantime?

**Comment by rachelkang** [comment]
Hi, @Axemasta - I looked into the selector you mentioned and it appears we already have it mapped as can be seen here: https://github.com/xamarin/xamarin-macios/blob/e49c11f99e6a75e01ca9b1f811e20ed99f5fa172/src/avfoundation.cs#L9459-L9461

Give that a go and let us know if you run into any issues!

**Comment by Axemasta** [comment]
Thats exactly what I was looking for thanks!
