### ISSUE TITLE
Metric Kit Not Calling Callbacks

### ISSUE THREAD

**Issue by mongosr2** [xamarin/xamarin-macios#13655]
### Steps to Reproduce

1. Create a class to receive metric kit callbacks.

```csharp
using System;
using Foundation;
using MetricKit;

namespace MetricsPlayground.iOS
{
    public class MetricsSubscriber : NSObject, IMXMetricManagerSubscriber
    {
        public MetricsSubscriber()
        {
            MXMetricManager.SharedManager.Add(this);
        }

        
        public void DidReceiveMetricPayloads(MXMetricPayload[] payloads)
        {
            
        }

        public void DidReceiveDiagnosticPayloads(MXDiagnosticPayload[] payloads)
        {
            
        }

     

    }
}
```

2. Register the class with the MetricKitManager in AppDelegate::DidFinishLaunching

```cs
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new App());

            _subscriber = new MetricsSubscriber();
            
            
            return base.FinishedLaunching(app, options);
        }

        private MetricsSubscriber _subscriber;
```

3. Attach to the process via Xcode and simulate metric kit collection

### Expected Behavior

The metric kit callbacks are called with the metric payload.

### Actual Behavior

Nothing happens.  The callbacks aren't called.

### Environment

```
```

**Comment by mandel-macaque** [comment]
Can you please provide a sample project? It will be very useful to see the code you have and be able to debug the issue. Also please provide the full details of your dev environment.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by mongosr2** [comment]
Here is the environment info.  Working on getting the sample project

=== Visual Studio Community 2019 for Mac ===

Version 8.10.16 (build 2)
Installation UUID: 8a752a3c-996c-40e9-b7c7-c7b3ae787187
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/5.0.402/Sdks
SDK Versions:
	5.0.402
	5.0.401
	5.0.400
	3.1.414
	3.1.413
	3.1.412
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.11
	5.0.10
	5.0.9
	3.1.20
	3.1.19
	3.1.18

=== .NET Core 3.1 SDK ===

SDK: 3.1.414

=== .NET 5.0 SDK ===

SDK: 5.0.402

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/03276061/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Apple Developer Tools ===

Xcode 13.2 (19585)
Build 13C90

=== Xamarin.Mac ===

Version: 8.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin.iOS ===

Version: 15.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 21:09:18 UTC

=== Build Information ===

Release ID: 810160002
Git revision: 6dbc7886fa608147f685a7df3912249400c84716
Build date: 2021-12-14 15:54:37-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 11.6.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Mon Aug 30 06:12:21 PDT 2021
    root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

**Comment by mandel-macaque** [comment]
@mongosr2 could we please get a small sample?

**Comment by mongosr2** [comment]
[MetricsPlayground.zip](https://github.com/xamarin/xamarin-macios/files/7990737/MetricsPlayground.zip)

**Comment by chamons** [comment]
Apologies for the delay in response.

You have a bug in your code:

```
        public void DidReceiveMetricPayloads(MXMetricPayload[] payloads)
```
is missing
```
        [Export("didReceiveMetricPayloads:")]
```
and the other one is missing
```
        [Export("didReceiveDiagnosticPayloads:")]
```

When you derive from a protocol using the interface and non base type, you need the matching export to make it callable from objective-c.

Once I added that, I then ran into a very strange set of Xcode behaviors. I was not able to attach and Simulate MetricKit Payloads, so I wrote a small Objective-C app, and that worked. It just had:

```
- (void)didReceiveMetricPayloads:(NSArray<MXMetricPayload *> * _Nonnull)payloads
{
    NSLog(@"didReceiveMetricPayloads");
}

- (void)didReceiveDiagnosticPayloads:(NSArray<MXDiagnosticPayload *> * _Nonnull)payloads
{
    NSLog(@"didReceiveDiagnosticPayloads");
}
```

After some head banging, I tried launching and attaching to the Objective-C version just like we are in C#, and _that_ starting showing the same exact behavior.

So from what I can tell, to make "Simulate MetricKit Payloads" work you need to be both:

- To be running on device
- Launched from Xcode, not attached to

Given this Xcode specific behavior seems to occur just as well in Objective-C, it is not a Xamarin bug, so I'm going to close this.

After fixing your exports, you should be getting calls every 24 hours or whenever MetricKid decides to call you.

**Comment by mongosr2** [comment]
No worries.  Thank you.
