### ISSUE TITLE
"Unable to open object file" and "no debug symbols in executable" warnings with common NuGet packages

### ISSUE THREAD

**Issue by stephanpalmer** [xamarin/xamarin-macios#13652]
When compiling common NuGet packages with the current Xamarin.iOS version, a large number (hundreds) of "unable to open object file" and "no debug symbols in executable" warnings appear. The warnings look like this example:

````
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(3,3): Warning: warning: (arm64) /Users/runner/runners/2.165.2/work/1/s/iOS/MaterialComponents/externals/build/Pods.build/Release-iphoneos/MDFTextAccessibility.build/Objects-normal/arm64/MDFColorCalculations.o unable to open object file: No such file or directory
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(3,3): Warning: warning: no debug symbols in executable (-arch arm64)
````
We reproduced this with the following Xamarin.iOS and XCode versions:

- The current Xamarin.iOS version 15.4.0.0, and XCode 13.2.1.
- The current Xamarin.iOS version 15.4.0.0, and XCode 13.1.

We reproduced this with the following NuGet packages:

- Xamarin.iOS.MaterialComponents 92.0.0
- Xamarin.Firebase.iOS.Core 5.2.0 and 6.10.4

Last known good versions:
- The warnings do not appear with Xamarin.iOS 15.2.0.17 and XCode 13.1
- For the same NuGet packages and NuGet package versions

It's unclear to me how to address these warnings. Do they indicate that something is broken? Everything we tested with the affected NuGet packages seemed to work. How can we fix these warnings? It is desirable that the warnings do no occur, especially because of the large number of warnings, and that they do not seem to have a warning number (with which the warning could be suppressed).

I'm not entirely sure if this is a bug of Xamarin.iOS or if the NuGet packages need to be updated for Xamarin.iOS 15.4.0.0. But since multiple of Xamarin's own NuGet packages seem to be affected, I assume this is a good place for this bug report.

### Steps to Reproduce

1. Create new Xamarin.Forms solution (e.g. using the Visual Studio "Blank app" template)
2. Add Xamarin.Forms.Visual.Material and Xamarin.iOS.MaterialComponents NuGet packages
3. Init visual material (add `global::Xamarin.Forms.FormsMaterial.Init();` in AppDelegate)
4. Use visual material (e.g. add `<Button Text="Test" Visual="Material" />` to MainPage.xaml)  
5. Clean and build the solution

These steps, as well as the example attached below, reproduce the problem with the Xamarin.iOS.MaterialComponents NuGet package. A similar behavior can be observed when using the Xamarin.Firebase.iOS.Core package.

### Expected Behavior

No "unable to open object file" or "no debug symbols in executable" warnings occur.

### Actual Behavior

A large number of "unable to open object file" and "no debug symbols in executable" warnings occur.

### Environment

[strangewarnings-systeminfo.txt](https://github.com/xamarin/xamarin-macios/files/7821713/strangewarnings-systeminfo.txt)

### Build Logs

[strangewarnings-buildlog.txt](https://github.com/xamarin/xamarin-macios/files/7822090/strangewarnings-buildlog.txt)
[strangewarnings-warnings.txt](https://github.com/xamarin/xamarin-macios/files/7821866/strangewarnings-warnings.txt)
![strangewarnings-warnings](https://user-images.githubusercontent.com/4060315/148384755-a0731114-e8c2-419f-937f-295a2f277be0.png)

### Example Project (If Possible)

[strangewarnings.zip](https://github.com/xamarin/xamarin-macios/files/7821704/strangewarnings.zip)

### Potentially related issue

We observed a separate warning issue with the Xamarin.Firebase.iOS packages with recent Xamarin.iOS versions. In case the two issues are related, here is the link to the other issue: https://github.com/xamarin/GoogleApisForiOSComponents/issues/514

----

[Edit: Add link to potentially related issue]
AB#1464824

**Comment by rolfbjarne** [comment]
The warning is harmless, it happens when we call `dsymutil` to create debug info (.dSYM directory) for the framework in question, and it's `dsymutil` telling us that it can't find some of the symbol information. The only problem that can occur with this warning is that crash reports that contain stack frames from the framework won't be fully symbolicated.

**Comment by rolfbjarne** [comment]
I believe the warning has been fixed now (we don't show it anymore).
