### ISSUE TITLE
UIApplication.KeyWindow is not marked as nullable

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/xamarin-macios#13683]
### Steps to Reproduce

1. Use the code `var window = UIApplication.SharedApplication.KeyWindow` with `#nullable enable`.

### Expected Behavior

`window` is marked as maybe null.

### Actual Behavior

`window` is marked as not null.

### More info

I believe it should be annotated with `[NullAllowed]`, although I couldn't actually find it in the binding source so I don't know if something more complicated is happening with it.

This is based on the Apple docs for `keyWindow`: https://developer.apple.com/documentation/uikit/uiapplication/1622924-keywindow, and also on the fact I've just had to fix a null reference bug due to accessing the key window too early.

**Comment by mandel-macaque** [comment]
I will be fixing the bindings, but do look at the fact that the property is deprecated and should not be used.
