### ISSUE TITLE
[net][proposal] Add assembly versions (matching associated .net versions) into product assemblies

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#13739]
The use of version `0.0.0.0` for `Xamarin.iOS.dll` was to ease back-n-forth compatibility when building bindings (or libraries) as it was not easy to re-install (at least side-by-side) older versions of the products. IOW using XI 7.0 to create/maintain bindings working on 5.x was simplified (a lot).

With .net 6+ this should not be an issue anymore, each project can use it's own version of the SDK. IOW bindings could be built with an older version (to maximize compatibility across projects) while an application could target the latest version. All without having tweak (like re-install, symlinks...) the developers computers.

So it would seems to the the _right_ time to include a version number into all (net-profile) `Xamarin.*.dll` product assemblies.

**Comment by rolfbjarne** [comment]
I like this idea!
