### ISSUE TITLE
Network extension fails to launch. ("doesn't have an entry point")

### ISSUE THREAD

**Issue by ericsink** [xamarin/xamarin-macios#13742]
### Steps to Reproduce

1. Start with the attached repro project
2. (Probably need to) Change the bundle IDs to something else 
3. Hook up an iOS device running iOS 15 or higher
4. Put the UDID in ne/app/run.sh
5. Setup the provisioning profiles, and change the .csproj files accordingly
6. cd ne/app/ and ./run.sh
7. Tap the INIT button and proceed to install the VPN profile
8. Either tap the CONNECT button, or go to the VPN area of Settings and activate the VPN from there

### Expected Behavior

Well, since the code in ne/ext/PacketTunnelProvider is untested and therefore probably buggy, I guess I expect to see some problem with it.

### Actual Behavior

The PacketTunnelProvider never gets called because the network extension fails to launch.  When attempting to connect the VPN from the Settings app, after tapping the button to ON, it immediately resets back to OFF.

In the device Console log, I see this:

Assembly '/private/var/containers/Bundle/Application/02197B0F-600C-4259-B71B-737A57354934/PublicStaging.app/PlugIns/ext.appex/ext.dll' doesn't have an entry point.

### Environment

```
% dotnet --version
6.0.101
```

I don't see a way to dump out the version of the iOS workload?  I updated it this morning, 14-Jan-2022.

### Build Logs

[build_log.txt](https://github.com/xamarin/xamarin-macios/files/7872136/build_log.txt)

### Example Project (If Possible)

[ios_ne_repro.tar.gz](https://github.com/xamarin/xamarin-macios/files/7872142/ios_ne_repro.tar.gz)

### Comments and Questions

If in fact the log message about "doesn't have an entry point" is a correct description of the cause of the problem, I wonder what entry point it is looking for and why it is not there.

For the moment, let's suppose it is looking for regular old `Main()`.  That doesn't make sense, since this an app extension, and setting the OutputType to Exe isn't possible.  I tried adding a `Main()`, but it doesn't get tagged as entry point in the resulting metadata.

A more likely theory is that the "entry point" problem is related to the specified class for the network extension.

The `NSExtensionPrincipalClass` key in the Info.plist file seems to be correct, and it matches the `Register` attribute on the PacketTunnelProvider subclass.  I've tried quite a few variations for the syntax of this value (namespace, swift-style module name, etc), and none of them make a difference. 

Looking through the repo here at `GenerateMain` and related things, I wonder if somehow the process startup is messed up because network extensions are a rather special case of app extensions.  I note that although there are quite a few app extensions in tests/common/TestProjects, none of them are network extensions, probably because network extensions cannot run in the simulator, so they would need special test infrastructure.

Note that the usual problem with a network extension and Xamarin is the memory limit, but that is not in play here.  First of all, with iOS 15 the memory limit for a network extension was increased from 15 MB to 50 MB (my test device is an iPad Mini5 running 15.2).  The console logs do not show any indication of the memory limit causing a problem with the launch, and I have verified what such a failure looks like by writing a Swift network extension that deliberately violates the limit.

Any tips, clues, or guidance would be appreciated.

**Comment by ericsink** [comment]
@mandel-macaque re: repro on pre-net6 xamarin -- I can try.  I had already pushed all the pre-net6 world out of my brain and my dev machine, so I'm just going to ask a dumb question or two.

To get the pre-net6 xamarin stuff, I install VS 2019?  When I try to do that, it says it detects an unsupported .NET version and wants to remove everything .NET before it proceeds.  Is this expected?  Can the old xamarin stuff co-exist with net6 workload stuff?

If memory serves, the only command-line experience for old xamarin was to use msbuild, not dotnet build.  Is that correct?

**Comment by ericsink** [comment]
I have a pre-net6 xamarin build, and it fails in a completely different way.  I'm gathering info, and will post another update soon.

**Comment by mandel-macaque** [comment]
@ericsink  appreciated

**Comment by ericsink** [comment]
OK, the behavior of the pre-net6 version is definitely different, and it seems like some kind of a regression, or perhaps a misconfigured build setup.

Attached is a pre-net6 version of the repro I posted previously.  I built it by creating a new app + extension in VS 2019 Mac, and then I copied over pieces from the original, and then I fixed a few issues like compiler errors for nullability stuff.

Both versions get the extension included in the bundle and successfully allow the VPN extension to be setup in iOS settings.

When trying to actually connect the VPN, the net6 version fails to launch the extension, as indicated in the top of this thread.  The pre-net6 version does get the extension launched.  It then proceeds to fail in other ways, but that's a separate issue.

The biggest difference between these two is the csproj files.  The pre-net6 versions are the longer, non-SDK style form, of course.  I constructed the net6 csproj files by looking at various examples.

The net6 csproj for the extension:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-ios15.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <CodesignProvision>Foo1</CodesignProvision>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <IsAppExtension>true</IsAppExtension>
    <MtouchLink>SdkOnly</MtouchLink>
  </PropertyGroup>
</Project>
```

The net6 csproj for the container app:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-ios15.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <CodesignProvision>Foo2</CodesignProvision>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ext\ext.csproj">
         <IsAppExtension>true</IsAppExtension>
        </ProjectReference>
  </ItemGroup>

</Project>
```

The `IsAppExtension` property seems to be necessary in the extension csproj as well as on the `ProjectReference` within the container app csproj.

Perhaps I am missing something?

[classic_ios_xamarin.tar.gz](https://github.com/xamarin/xamarin-macios/files/7916003/classic_ios_xamarin.tar.gz)

**Comment by ericsink** [comment]
FWIW, attached is an updated repro with a working implementation of the packet tunnel provider.

The tar file contains `new_ios_xamarin` (which uses net6) and `classic_ios_xamarin` (which uses the pre-net6 SDK).

The two `PacketTunnelProvider.cs` files are identical, and the classic Xamarin build "works", meaning it successfully installs on a real iOS 15 device and successfully talks to a trivial UDP server.

The net6 version still demonstrates the failure to launch described at the top of this issue.

[repro.tar.gz](https://github.com/xamarin/xamarin-macios/files/7971982/repro.tar.gz)

**Comment by rolfbjarne** [comment]
I'll have a look
