### ISSUE TITLE
How do I embed an Info.plist / add arbitrary linker args?

### ISSUE THREAD

**Issue by chucker** [xamarin/xamarin-macios#13795]
(I'm not quite sure if this repo or `dotnet/sdk` is right.)

I'm trying to make a single-file tool (no macOS bundle), but with an `Info.plist`. Therefore, it needs to be embedded. If I were to link the file manually, I could add `ld` args such as:

    -sectcreate __TEXT __info_plist MyInfo.plist -sectcreate

This would produce a Mach-O binary with the Info.plist already embedded at the right place. Adding this section after the fact doesn't appear to be supported.

### Steps to Reproduce

1. Make a new .NET 6 console project (`dotnet new console`).
2. Make it a single-file tool, including native libraries:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RuntimeIdentifier>osx.11.0-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

</Project>
```

3. Make a simple Info.plist:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>me.chucker.SomeTool</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>me.chucker.SomeTool</string>
</dict>
</plist>
```

4. build using `dotnet publish -c Release`
5. Use `otool -s __TEXT __info_plist` to verify that the binary does not include a plist

### Expected Behavior

I was hoping for some MSBuild property to either add manual `ld` flags, or to specify the name of a plist to be included. For the former, there appears to be `MtouchExtraArgs`, but it doesn't appear to be picked up for macOS .NET 6 builds. For the latter, [Xcode has a "Create Info.plist Section in Binary" build task.](
![](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Art/xcode_tool_infoplist.jpg)
) Ideally, the .NET toolchain would have something similar.

### Environment

```
~> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by chucker** [comment]
Small amendment: it probably makes more sense to target the platform:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-**macos**</TargetFramework>
    <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

</Project>
```

This _does_ seem to detect the Info.plist in `_DetectAppManifest`. However, something like `<EmbedManifest>true</EmbedManifest>` seems to have no effect.

**Comment by mandel-macaque** [comment]
@rolfbjarne  can you please take a look?

**Comment by rolfbjarne** [comment]
> I'm trying to make a single-file tool (no macOS bundle)

Using the `net6.0-macos` target framewore will create a macOS bundle (and this is handled in this repository).

In that case, you can try adding this property to your project file:

```xml
<MonoBundlingExtraArgs>--link_flags="-sectcreate __TEXT __info_plist MyInfo.plist -sectcreate"</MonoBundlingExtraArgs>
```

If you want a single-file/standalone executable, the correct place to report/ask about it is in the https://github.com/dotnet/runtime repository (I can move this issue there if that's what you want).

**Comment by rolfbjarne** [comment]
> Though I’m surprised runtime, not sdk, is the right repo.

I admit I might be wrong, but it's at least the correct org :)

**Comment by rolfbjarne** [comment]
This issue was moved to dotnet/runtime#64276
