### ISSUE TITLE
xamarin.mac Apple silicone support

### ISSUE THREAD

**Issue by simeon052** [xamarin/xamarin-macios#13803]
currently, I could create universal binary with ARM64 on xammacarch.

I’d like to know official support info against apple silicone.
7.13release notes says it is preview.
l can’t find any other official info for Apple silicone support.

do you have any info?

**Comment by dalexsoto** [comment]
Hello!

You can use Xamarin.Mac to create arm64 apps today and as far we know they work. That said as of today this is a preview tech, that means that you could run into issues. The real supported route is via dotnet6 which is also under Preview until later this year but this is the way we will support arm64 officially.
