### ISSUE TITLE
Cannot convert type 'ObjCRuntime.NativeHandle' to 'void*'

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#13867]
### Steps to Reproduce

```cs
IntPtr handle = (IntPtr)1;

// working
void* t1 = (void*)handle;

// error
void* t2 = (void*)(ObjCRuntime.NativeHandle)handle;
```

Related missing method: `IntPTr.ToInt64()`

### Expected Behavior

The code compiles.

### Actual Behavior

```
error CS0030: Cannot convert type 'ObjCRuntime.NativeHandle' to 'void*' 
```

### Environment

```
```

**Comment by rolfbjarne** [comment]
You can cast to `IntPtr` before casting to `void *`:

```csharp
void *t2 = (void*) (IntPtr) handle;
```

Also, what's the use-case scenario here? Why do you need a `void *`?

**Comment by mattleibow** [comment]
My use case was that I have a C++ API that wanted the handle to a Metal texture. I could use IntPtr on that, but right now my generator outputs void*. This is not a hard technical requirement, but not having to do anything is way better than doing something :)
