### ISSUE TITLE
CVDisplayLink throws an Exception when deal with Xamarin.Forms Animations

### ISSUE THREAD

**Issue by SeRgI1982** [xamarin/xamarin-macios#13911]
### Steps to Reproduce

It is hard to find steps to reproduce the bug but it happens randomly when Xamarin.Forms do an Animation on macOS

![image](https://user-images.githubusercontent.com/9572525/151254260-231454a4-abb0-44be-a045-375e370e0c33.png)

Xamarin.Forms code shows that parameterless constructor is used, so the issue probably exists here in Xamarin.Mac
https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.MacOS/CADisplayLinkTicker.cs#L40

### Expected Behavior

Animation succeed without Exception

### Actual Behavior

Exception happens which leads to app crash

### Environment

Xamarin.Forms 5.0.0.2012

Visual Studio Professional 2019 for Mac
Version 8.10.11 (build 8)
Installation UUID: da0195e3-f48e-46a6-99db-f4e7b1f0a286
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
	Package version: 612000158

Mono Framework MDK
Runtime:
	Mono 6.12.0.158 (2020-02/5ce143a1a88) (64-bit)
	Package version: 612000158

Apple Developer Tools
Xcode 13.1 (19466)
Build 13A1030d

Xamarin.Mac
Version: 8.2.0.17 (Visual Studio Professional)
Hash: 738fde344
Branch: xcode13.1
Build date: 2021-11-09 02:45:15-0500

Xamarin.iOS
Version: 15.2.0.17 (Visual Studio Professional)
Hash: 738fde344
Branch: xcode13.1
Build date: 2021-11-09 02:45:16-0500

macOS 11.6.2 (20G314)

**Comment by mandel-macaque** [comment]
Hello,

Can you please provide the full stack of the exception, is quite hard to track it and see everything in an image :) 

I should be able to see what is going on, can you tell me how is your setup? Number of screens etc? Since this is quite important when using this class.

Thanks in advance.

**Comment by SeRgI1982** [comment]
Sorry, for the image. It shows everything what I can present. Below there are our own lines of code. Just running the animation.

Yes, it can be related with external screen. 
I have one external screen (DELL U2515H) attached to my macbook pro (https://support.apple.com/kb/sp704).
This screen is shared across 2 computers:
- macbook - HDMI-to-HDMI,
- windows - DisplayPort-to-DisplayPort (Desktop machine with GeForce GTX 770)

When I want to switch the screen, I am changing signal source in OSD Menu

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
