### ISSUE TITLE
[net6.0-maccatalyst] `CoreTelephony` is missing

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#13931]
### Description

The following namespace is present in `xamarinios10` and `net6.0-ios` but is not present in `net6.0-maccatalyst`:

`CoreTelephony`

If I'm reading [this](https://developer.apple.com/documentation/coretelephony) properly, this namespaces is supposed to be available in Catalyst.

### Environment

VS 17.1 preview 4

**Comment by mandel-macaque** [comment]
Should be easy to verify in our side via the intro tests. I'll enable it and will get back to you.
