### ISSUE TITLE
Rejected from Appstore, MapKit framework but does not appear to include Maps functionality

### ISSUE THREAD

**Issue by Jijovkm** [xamarin/xamarin-macios#13978]
Hi, Recently my Mac application is rejected by appstore by saying “Your app links against the MapKit framework but does not appear to include Maps functionality”. We are not using this functionality. When i search with otool found that it exists in the build, I developed app with Link Behavior as Link framework SDKs only and i added mmp arguments with “–linkplatform”, because my app refer lots of third party libs and frameworks. Tried with --linkskip but not working, still otools shows map frameworks. 

### Steps to Reproduce

**Guideline 2.1 - Performance

Your app links against the MapKit framework but does not appear to include Maps functionality. 

Next Steps

If your app does include Maps functionality, please respond to this message in App Store Connect with steps on how to locate it within your app.

If you do not intend to use Maps, please unlink the MapKit framework. If you would like to use Maps, please add the "com.apple.developer.maps" entitlement and submit an updated binary for review.**

Nil

### Expected Behavior

Should Pass Appstore Review

### Actual Behavior

Your app links against the MapKit framework but does not appear to include Maps functionality

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.10 (build 8)
Installation UUID: ff69ed7e-6f7d-4e8a-970a-5109cbeacc7e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.401/Sdks
SDK Versions:
	5.0.401
	5.0.100
	3.1.413
	3.1.401
	3.1.302
	3.1.200
	3.1.102
	3.1.100
	3.0.101
	3.0.100
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.10
	5.0.0
	3.1.19
	3.1.7
	3.1.6
	3.1.2
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.21
	2.1.20
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13

=== .NET Core 3.1 SDK ===

SDK: 3.1.413

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.0 (19234)
Build 13A233

=== Xamarin.Mac ===

Version: 7.14.0.27 (Visual Studio Community)
Hash: 2566861a9
Branch: d16-10
Build date: 2021-07-27 02:34:12-0400

=== Xamarin.iOS ===

Version: 15.0.0.6 (Visual Studio Community)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:30:50 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:31:08 UTC

=== Build Information ===

Release ID: 810100008
Git revision: a3ff4b6e658e1f94623e1f3ed34ca94ed4fe78d8
Build date: 2021-09-23 19:50:51-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Mon Aug 30 06:12:21 PDT 2021
    root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64


```

**Comment by mandel-macaque** [comment]
Hello,

Can you please provide a min example and the bin logs of the application. What type of linking are you using? If you do not use the linker, this is expected. You should have the linker enabled to remove all references of not used APIs.

**Comment by Jijovkm** [comment]
I am working on a huge project. Sample doesn't have this issue. When i used linksdkonly it crashes the app due to some missing Microsoft library. So i used linkplatform as MMP arguments. Now it works but the MapKit still exists when i tested with otools.

**Comment by chamons** [comment]
Sorry for the delay in response:

While there is support for [customer linker configurations](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker) doing this to half-replicate linksdkonly is not supported in any way.

Without a sample project, I'm unable to look into this further. Please look to isolate your issue to a sample application that can be shared.
