### ISSUE TITLE
Dylibs acquired from NuGet no longer have install_name_tool run on them

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#13999]
### Steps to Reproduce

1. Build the attached project
2. Run `otool -L bin/Debug/net6.0-macos/osx-x64/dyliblinkissue.app/Contents/MacOS/dyliblinkissue`

### Expected Behavior

The SQLite library is linked with fixed path to `@rpath/libe_sqlite3.dylib`.

### Actual Behavior

The original dylib name is used:
```
./bin/e_sqlite3/mac/x86_64/libe_sqlite3.dylib (compatibility version 0.0.0, current version 0.0.0)
```

This is regression from the shipping SDKs (~preview 11).

### Environment

.NET 6.0.200 SDK nightly, macOS Workload 12.1.300-preview.14.101 acquired using `dotnet workload install macos`.

### Example Project (If Possible)

[Archive.zip](https://github.com/xamarin/xamarin-macios/files/7974536/Archive.zip)

The project is empty project created by `dotnet new macos` with added PackageReference to .csproj:
```
  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.0.7" PrivateAssets="None" />
  </ItemGroup>
```

**Comment by filipnavara** [comment]
Filled this on request by @rolfbjarne since it's a regression.

**Comment by sandyarmstrong** [comment]
I think this regression also exists in Preview 13. I was using `12.1.200-preview.12.4`. After upgrading to `12.1.301-preview.13.4` and getting it building again, I have similar crashes.

VSMac:

```
dyld: Library not loaded: ./bin/e_sqlite3/mac/x86_64/libe_sqlite3.dylib
  Referenced from: /Users/sandy/xam-git/vsmac/main/build/bin/VisualStudio.app/Contents/MacOS/VisualStudio
  Reason: image not found
```

VS-Platform standalone editor (calls itself MonoDevelop.Ide for IVT convenience):

```
Dyld Error Message:
dyld: Using shared cache: A9EB0E63-BFA0-348A-AB0E-091857CE7217
Library not loaded: */libe_sqlite3.dylib
Referenced from: /Users/USER/*/MonoDevelop.Ide.app/Contents/MacOS/MonoDevelop.Ide
Reason: image not found
```

**Comment by filipnavara** [comment]
Correct, it affect P13 as well. I have a [pending PR with workaround](https://github.com/ericsink/cb/pull/8) on the SQLitePCL side and private NuGet feed with binaries corresponding to that PR. I'd be happy to share it if there's a need to unblock something quickly.

**Comment by sandyarmstrong** [comment]
@filipnavara thanks, I'll let you know if we end up needing that. I'm hoping to avoid using a different sqlite version than Roslyn, but I'm glad to know there may be a workaround.
