### ISSUE TITLE
Xamarin Forms iOS app can't be deployed with too many BundleResource files

### ISSUE THREAD

**Issue by BlueRaja** [xamarin/xamarin-macios#14013]
### Steps to Reproduce

1. Attempt to deploy a Xamarin Forms iOS app with 13,000 small audio files bundled in (totaling only ~50MB), using the following syntax in the .csproj:
```
<ItemGroup>
    <BundleResource Include="Assets\Audio\*.mp3" />
</ItemGroup>
```

### Expected Behavior
App deploys correctly

### Actual Behavior
Deploy fails with the following error
```
    Xamarin.VisualStudio.IOS.IdbClient Error: 0 : Deploy failed. The app 'myApp' could not be deployed to the device 'My iPod touch'. Error: The post for client vs23920 on topic xvs/idb/deploy-app has been cancelled. Please check the logs for more details.
    System.OperationCanceledException: The operation was canceled.
       at System.Threading.CancellationToken.ThrowOperationCanceledException()
       at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__31.MoveNext() 
       ...
```

Note that **if we reduce the number of small files from 13,000 to a few hundred, it deploys correctly.**

### Environment

VS 2022 17.0.5
Xamarin Forms (latest)
Using iOS "Hot Restart" to develop for iOS without a paired mac

### Build Logs

http://www.blueraja.com/files/2022-01-30_15-51-04.11836.Ide.log

### Other
I also posted [here](https://docs.microsoft.com/en-us/answers/questions/715540/xamarin-forms-ios-app-can39t-be-deployed-with-too.html?childToView=717460#comment-717460) and [here](https://stackoverflow.com/questions/70920352/xamarin-forms-ios-app-cant-be-deployed-with-too-many-bundleresource-files?noredirect=1#comment125403234_70920352). I was directed here by an MSFT in the first link.

**Comment by chamons** [comment]
Thanks for the report and sorry for the delay in response.

Unfortunately this issue occurs within the IDE, and they are not reachable by github. 

Please create an issue using [these instructions](https://developercommunity.visualstudio.com/report?space=8&entry=problem).
