### ISSUE TITLE
dotnet new maui App Can't Be Published For iOS

### ISSUE THREAD

**Issue by eerhardt** [xamarin/xamarin-macios#14015]
### Steps to Reproduce

1. `dotnet new maui`
2. `dotnet publish -c Release -f net6.0-ios -r ios-arm64`

### Expected Behavior
The app should publish successfully.

### Actual Behavior
```
/Users/eerhardt/git/maui/bin/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.2.300-preview.13.1/targets/Xamarin.Shared.Sdk.targets(1538,3): The RuntimeIdentifier 'ios-arm64' is invalid. [/Users/eerhardt/DotNetTest/MauiTest/NoHosting/NoHosting.csproj]
```

From looking at the binlog, it appears that the `_GenerateRestoreGraph` target is running for each `TargetFramework` listed in `TargetFrameworks`. The default `dotnet new maui` .csproj has:

```xml
<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
```

And when the target is running for `net6.0-maccatalyst`, it is failing here:

https://github.com/xamarin/xamarin-macios/blob/a14712d6e3ece98351495048d7dd75a57d269bb9/dotnet/targets/Xamarin.Shared.Sdk.targets#L1540-L1547

### Environment

```
% dotnet --info                                                           
.NET SDK (reflecting any global.json):
 Version:   6.0.200-preview.22063.5
 Commit:    2d72e717b3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.2
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /Users/eerhardt/git/maui/bin/dotnet/sdk/6.0.200-preview.22063.5/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.200-preview.22063.5 [/Users/eerhardt/git/maui/bin/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/Users/eerhardt/git/maui/bin/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/Users/eerhardt/git/maui/bin/dotnet/shared/Microsoft.NETCore.App]
```

### Build Logs

Available on request. Shoot me an email.

cc @rolfbjarne

**Comment by rolfbjarne** [comment]
Turns out I've already filed this in the dotnet/sdk repo: https://github.com/dotnet/sdk/issues/21877, so I'm closing this one if favor of the dotnet/sdk one.
