### ISSUE TITLE
Unable to publish Xamarin.Forms iOS app to the AppStore TestFlight

### ISSUE THREAD

**Issue by evgenyKozlov1996** [xamarin/xamarin-macios#14026]
### Steps to Reproduce

1. Create empty Xamarin.Forms app.
2. Create and set up Provisioning profile.
3. Build and try to deliver your app to the AppStore TestFlight.

### Expected Behavior
App should be delivered and deployed successfully.

### Actual Behavior
You will receive the following error message:
![image](https://user-images.githubusercontent.com/29367189/152212188-5e06a640-da78-45c6-baca-d9fe647b2adc.png)

### Environment

1.
=== Visual Studio Community 2019 for Mac ===

Version 8.10.17 (build 2)
Installation UUID: bccf00db-7dc9-4eda-bf1a-d5a78accaa32
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/x64/sdk/6.0.101/Sdks
SDK Versions:
	6.0.101
	5.0.404
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.1
	5.0.13
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Version: 8.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin.iOS ===

Version: 15.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/evgenykozlov/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 31.0.0

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810170002
Git revision: 58f7763d4d64fcf005a474d25a5d9fd5ce46d7f5
Build date: 2022-01-05 12:51:28-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.1.0
Darwin 21.2.0 Darwin Kernel Version 21.2.0
    Sun Nov 28 20:29:10 PST 2021
    root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 x86_64

### Build Logs

Doesn't matter for this issue.

**Comment by jfversluis** [comment]
@evgenyKozlov1996 why did you close this again? Did you fix it?

I have a similar issue that mentions this in the Forms repo: https://github.com/xamarin/Xamarin.Forms/issues/15128

cc: @dalexsoto

**Comment by evgenyKozlov1996** [comment]
Hello, @jfversluis .

I just tried to publish an empty project again and didn't faced with any issues. I don't really know is it xamarin.ios problem or not. Maybe it is a problem with old versions, I don't know. So, I can't definitely say that this is Xamarin.IOS problem and closed the issue.

**Comment by evgenyKozlov1996** [comment]
@jfversluis Anyway, I think it will be great if we figure out the problem together and fix it. Maybe it is a problem with the Xamarin.IOS, maybe not, but it's a blocker. I am trying to remove all libraries from my work project and figure out which library is causing the issue.

**Comment by jfversluis** [comment]
@rutledmj mentioned in the linked issue that changing the Xamarin.iOS version made the issue go away?

@evgenyKozlov1996 I see your comment in the other issue, please let's try to centralize in this one :)

**Comment by rutledmj** [comment]
Hi, when I changed the Xamarin.iOS SDK version in AppCenter, the issue stayed, but the names of the non-public selectors changed. 

These are the selectors using v15.4: 

> accessibilityBrailleMapRenderRegion, accessibilityBrailleMapRenderer, accessibilityColumnRange, accessibilityRowRange, activePlayer, beginAuthorizationWithRequest:, cancelAuthorizationWithRequest:, errorForCHIPErrorCode:, errorToCHIPErrorCode:, playerId, serviceExtensionWillTerminate, session:didReceiveData:fromPlayer:, session:didReceiveMessage:withData:fromPlayer:, session:player:didChangeConnectionState:, session:player:didSaveData:, setAccessibilityBrailleMapRenderRegion:, setAccessibilityBrailleMapRenderer:.  

And these are the selectors when using an older version (v13.2):

> accessibilityColumnRange, accessibilityRowRange, activePlayer, advertisingSection, beginAuthorizationWithRequest:, behaviorTypes, canDisplayBannerAds, cancelAction, cancelAuthorizationWithRequest:, cancelBannerViewAction, cancelPreroll, convolutionState, currentContentSizeIdentifier, determineAppInstallationAttributionWithCompletionHandler:, discoverAllContactUserInfosWithCompletionHandler:, discoverAllContactsCompletionBlock, discoverUserInfoWithEmailAddress:completionHandler:, discoverUserInfoWithUserRecordID:completionHandler:, discoverUserInfosCompletionBlock, displayContact, drawableResizesAsynchronously, encodeToCommandBuffer:sourceImage:convolutionState:, encodeToCommandBuffer:sourceImage:destinationImage:state:, getProperty:onChannel:responseHandler:, hasProperty:onChannel:responseHandler:, initForInterstitialAd:, initWithAdType:, initWithEmailAddresses:userRecordIDs:, initWithMIDIEntity:dataReadyHandler:, initWithZoneID:options:, initWithZoneID:subscriptionID:options:, interstitialPresentationPolicy, isActionInProgress, isBannerLoaded, isBannerViewActionInProgress, isDisplayingBannerAd, isPresentingFullScreenAd, isPublicDatabase, lookupAdConversionDetails:, mouseUpAction, newDrawable, originalContentView, playPrerollAdWithCompletionHandler:, playerId, prepareInterstitialAds, preparePrerollAds, presentFromViewController:, presentInView:, propertyChangedCallback, removeAllAppearanceStreams, replaceTextStorage:, requestInterstitialAdPresentation, requiredContentSizeIdentifiers, retrieveConnectedPeripherals, retrievePeripherals:, session:didReceiveData:fromPlayer:, session:didReceiveMessage:withData:fromPlayer:, session:player:didChangeConnectionState:, session:player:didSaveData:, setAdvertisingSection:, setCanDisplayBannerAds:, setCurrentContentSizeIdentifier:, setDiscoverAllContactsCompletionBlock:, setDiscoverUserInfosCompletionBlock:, setDrawableResizesAsynchronously:, setEditedMask:, setInterstitialPresentationPolicy:, setMouseUpAction:, setProperty:onChannel:responseHandler:, setPropertyChangedCallback:, setRequiredContentSizeIdentifiers:, setTemporaryAttributes:forCharacterRange:, setUserRecordIDs:, shouldPresentInterstitialAd, shouldTestVisibilityAtPoint:, sizeFromBannerContentSizeIdentifier:, sourceOffset, subscriptionOptions, takeBackgroundColorFrom:,

**Comment by dalexsoto** [comment]
mmm interesting, I have not seen this in our own submission tests. I see `session:didReceiveData:fromPlayer:` for example, do you use GameKit at all? It seems that you are trying to submit an application with the [Don't Link](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=windows#dont-link) linker setting and that will definitely not fly under AppStore

**Comment by rutledmj** [comment]
I am not using GameKit.
Originally I had the Linker Behavior set to `Link Framework SDKs Only`. I tried `Don't Link` just to see what would happen.

**Comment by evgenyKozlov1996** [comment]
@rutledmj I fixed the issue for me. It was some checks in the build options for iOS. Please make sure that your build options the same as below:
![Screenshot 2022-02-10 at 21 53 04](https://user-images.githubusercontent.com/29367189/153476869-ffc7d6a8-fd3c-4134-ba96-a32e58cb3274.png)

CC @jfversluis
