### ISSUE TITLE
[net][msbuild] Release builds include `.pdb` inside the app bundle

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#14085]
Debugging symbols `.pdb` files are included inside the `.app` in release mode.

This is a regression from earlier previews.

# Steps

1. `cd tests/dotnet`
2. `make compare`
3. open the gist

## Example

https://gist.github.com/spouliot/2d707626fdc962a76eeafa145af79b64

**Comment by Therzok** [comment]
Would this be related? https://github.com/xamarin/xamarin-macios/issues/13128

What I was sugested is using embedded PDBs for this.
