### ISSUE TITLE
macos: NSTableViewColumnWidth delegate regression

### ISSUE THREAD

**Issue by sandyarmstrong** [xamarin/xamarin-macios#14107]
The `NSTableView.GetSizeToFitColumnWidth` property is an `NSTableViewColumnWidth` delegate.

[Previous definition](https://docs.microsoft.com/en-us/dotnet/api/appkit.nstableviewcolumnwidth?view=xamarin-mac-sdk-14) (still worked as of `12.0.101-preview.10.251`):

```csharp
public delegate nfloat NSTableViewColumnWidth(NSTableView tableView, nint column);
```

Regressed definition (as seen in `12.1.200-preview.12.4`):

```csharp
public delegate nfloat NSTableViewColumnWidth(NSTableView tableView, IntPtr column);
```

Our code that passes `int` values for `column` now fails to build with:

> error CS1503: Argument 2: cannot convert from 'int' to 'System.IntPtr'

**Comment by rolfbjarne** [comment]
Yeah, this isn't right, the delegate should have an `nint` parameter, not an `IntPtr` parameter.

**Comment by sandyarmstrong** [comment]
@rolfbjarne should we expect any runtime issues using the version of these delegates that take `IntPtr`?
