### ISSUE TITLE
Application could not be uploaded to device

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#14124]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Application-could-not-be-uploaded-to-dev/1654684)._

---
I have m Iphone 13 connected and when i try to debug or release i get the error “application could not ne iploaded to device”
I tried provisioning Manual as some guys told but with luck.
The app is runnning Ok in the simulator.
Is there anything i can do?
Thank you

---
#### Feedback Bot on 2/6/2022, 09:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by chamons** [comment]
Thank you for your feedback and apologies for the delay in response. 

For us to investigate this further, could you please provide your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!
