### ISSUE TITLE
[iOS/macOS][net6] Member renames to `CGAffineTransform` are error prone when upgrading from Xamarin.iOS to net6 preview 13.2

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#14125]
### Steps to Reproduce

Upgrade a piece of code which uses any member of `CGAffineTransform` to net6.

### Expected Behavior

Get indications on what to upgrade to, or have no breaking change.

### Actual Behavior

Members are missing as they have been renamed in https://github.com/xamarin/xamarin-macios/commit/209eca1fb7e6326f4a2782b30dd4539512f8e8a5.

### Environment

15.2.301-preview.13.2

**Comment by rolfbjarne** [comment]
> Upgrade a piece of code which uses any member of `CGAffineTransform` to net6.

I added new members with the new names to legacy Xamarin as well, and Obsolete attributes on the old names.

This means that before upgrading to .NET 6, you should build your project with the latest version of Xamarin.iOS/Xamarin.Mac, and fix these warnings. After that, your code will be ready to upgrade without changes.

There aren't any released version of Xamarin.iOS/Xamarin.Mac with these changes (yet), but in the meantime you can download nightly builds as described here: https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build

**Comment by jeromelaban** [comment]
Thanks @rolfbjarne.

It's a tough decision to make, and you're probably in a difficult spot, yet those are breaking change of small value to the existing developers, just for the sake of API cleanliness. I know it's not going to change your mind, though it's annoyances (a lot of them) for developers that are already in your ecosystem.

Keeping those members as obsolete, hidden from intellisense is **removing friction** for developers upgrading to net6.

**Comment by sandyarmstrong** [comment]
> Keeping those members as obsolete, hidden from intellisense is removing friction for developers upgrading to net6.

Agreed. As someone already using .NET 6 and Preview 10 of the macos workload, I don't have the option to go backwards and use a newer Mono-based Xamarin.Mac that has these members marked obsolete. I just have to manually adjust the properties and hope I didn't make a mistake.

**Comment by spouliot** [comment]
FWIW it should not be _very_ hard to generated a document based on the legacy `[Obsolete]` attributes since they (almost) all follow the same format it. It could be appended (and updated) to the existing `dotnet/BreakingChanges.md` document.

You still have to look for them - but it would remove most of the guessing and mistakes.

**Comment by filipnavara** [comment]
In theory, it would be possible to also add
```csharp
 		[Obsolete ("Use 'A' instead.")]
 		public /* CGFloat */ nfloat xx { get => A; set => A = value; }
 		[Obsolete ("Use 'B' instead.")]
 		public /* CGFloat */ nfloat yx { get => B; set => B = value; }
 		[Obsolete ("Use 'C' instead.")]
  		public /* CGFloat */ nfloat xy { get => C; set => C = value; }
  		[Obsolete ("Use 'D' instead.")]
  		public /* CGFloat */ nfloat yy { get => D; set => D = value; }
  		[Obsolete ("Use 'Tx' instead.")]
 		public /* CGFloat */ nfloat x0 { get => Tx; set => Tx = value; }
  		[Obsolete ("Use 'Ty' instead.")]
 		public /* CGFloat */ nfloat y0 { get => Ty; set => Ty = value; }
```
to ease porting existing code.

The overhead would likely be negligible for release builds with the linker. At this point it's probably too late for this to help anyone though.

**Comment by jeromelaban** [comment]
Thanks a lot @rolfbjarne !!
