### ISSUE TITLE
Can't create release archive due to MT2101

### ISSUE THREAD

**Issue by GaborPTungsram** [xamarin/xamarin-macios#14141]
### Steps to Reproduce

Our application is a cross-platform application for Android and iOS devices. Unfortunately I can not share the project with you, but the diagnostic log has plenty of information.

Building our IOS project for archiving, and get build error. Also get this error when build type is Release, and trying to deploy the app to device over USB.

Debug build for simulator is not affected, works perfectly. I tried to fix the error by adding Microsoft.AspNetCore.Authorization as a NuGet dependeny, without success.

### Expected Behavior

Archive build completes without errors.

### Actual Behavior

MTOUCH : error MT2101: Can't resolve the reference 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.AuthorizationServiceCollectionExtensions::AddAuthorization(Microsoft.Extensions.DependencyInjection.IServiceCollection)', referenced from the method 'System.Void Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions::AddAuthorizationServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)' in 'Microsoft.AspNetCore.Authorization, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### Environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.18 (build 11)
Installation UUID: c5037e85-f65e-4c5e-ac25-bd4dc20c9bb9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/5.0.405/Sdks
SDK Versions:
	5.0.405
	5.0.404
	5.0.403
	5.0.302
	5.0.301
	5.0.203
	3.1.416
	3.1.415
	3.1.411
	3.1.410
	3.1.402
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.14
	5.0.13
	5.0.12
	5.0.8
	5.0.7
	5.0.6
	3.1.22
	3.1.21
	3.1.17
	3.1.16
	3.1.8
	2.1.23
	2.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.405

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Version: 8.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin.iOS ===

Version: 15.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/gaborparadi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information:
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Build Information ===

Release ID: 810180011
Git revision: 5b68fe210d29028414f15a937514bdbd3178e774
Build date: 2022-01-31 14:47:37-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.2.1
Darwin 21.3.0 Darwin Kernel Version 21.3.0
    Wed Jan  5 21:37:58 PST 2022
    root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

```

### Build Logs
Switched to verbose diagnostic logging, and the log file exceeds the maximum size submittable. I've uploaded it to our file-sharing service, please contact me if you have problems accessing the log file.

[https://send.testserver.vintocon.com/SentLargeFiles/Xamarin_archive_build_error.txt.zip
](url)

**Comment by chamons** [comment]
Thanks for reach out and apologies for the delay in response.

The binary logs were too large to open in IDEs, but I was able to replay it via `dotnet build vsmac-failing.binlog /v:detailed > log.txt`

However, I was unable to find the error mentioned `MTOUCH : error MT2101` nor `AuthorizationServiceCollectionExtensions` in vsmac-failing.binlog.

The log file produced was exceptionally long, more than 13 million lines. 

I would also like to mention that it seems very strange to need types from a web server framework (Microsoft.AspNetCore.Authorization) in your application.

Can you please provide more detailed information and see what I'm missing.

**Comment by GaborPTungsram** [comment]
Hi Chris et al.

Yes, the dependency list is not a simple one in our app. The reason we’re using web related components is that this app uses Blazor for the UI.

Dependency list of our app:
System.ComponentModel.Annotations (5.0.0)
System.Net.Http.Json (6.0.0)
Xamarin.Essentials (1.7.1)
Xamarin.Forms (5.0.0.2401)
Blazored.LocalStorage (4.2.0)
Blazored.Toast (3.2.2)
Microsoft.AspNetCore.Localization (2.2.0)
Microsoft.AspNetCore.Mvc.RazorPages (2.2.5)
Microsoft.MobileBlazorBindings (0.5.50-review)
System.Net.Http.Json (6.0.0)

In last November I was able to build archive for iOS, and I was successfully released via TestFlight. This year I had no success anymore. The error appears only in release build, not in debug mode. As I need release build for Archiving the app for TestFlight, this error blocks me in iOS test releasing.

It is strange that you didn't find the MT2101 in the log. I'm sure that the build result was this error, as it is still appearing on iOS release build. If you need, if it helps, I can provide a less verbose build log.

Best regards,
Gabor

**Comment by chamons** [comment]
Please attach a non-verbose build log, or ideally a [binary build log](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2022#save-a-binary-log).

**Comment by MaximMikhisor** [comment]
Try to turn off Linker for Release build.
<img width="286" alt="image" src="https://user-images.githubusercontent.com/40904997/161188022-a8de2f33-b9c7-4fd0-9e74-dde0b5c83dc4.png">

**Comment by GaborPTungsram** [comment]
> 

Archive build log attached
[archive_build_log.txt](https://github.com/xamarin/xamarin-macios/files/8397415/archive_build_log.txt)
.

**Comment by GaborPTungsram** [comment]
> Try to turn off Linker for Release build.
> <img alt="image" width="286" src="https://user-images.githubusercontent.com/40904997/161188022-a8de2f33-b9c7-4fd0-9e74-dde0b5c83dc4.png">

Set to Do not link as you requested, archive build was clean but got IMTS-90122 when tries to upload the ipa to TestFlight
[transport_error.txt](https://github.com/xamarin/xamarin-macios/files/8397426/transport_error.txt)
.

**Comment by chamons** [comment]
It looks like with the linker disabled your app is too large for arm64:

```
ERROR ITMS-90122: "Invalid Executable Size. The size of your app's executable file 'ArchiFMMobileApp.iOS.app/ArchiFMMobileApp.iOS' is 85557248 bytes for architecture 'arm64', which exceeds the maximum allowed size of 60 MB."
```

The other build errors with:

```
    MTOUCH : error MT2101: Can't resolve the reference 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.AuthorizationServiceCollectionExtensions::AddAuthorization(Microsoft.Extensions.DependencyInjection.IServiceCollection)', referenced from the method 'System.Void Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions::AddAuthorizationServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)' in 'Microsoft.AspNetCore.Authorization, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

    --- inner exception
    Mono.Linker.MarkException: Error processing method: 'System.Void Microsoft.Extensions.DependencyInjection.MvcCoreMvcCoreBuilderExtensions::AddAuthorizationServices(Microsoft.Extensions.DependencyInjection.IServiceCollection)' in assembly: 'Microsoft.AspNetCore.Mvc.Core.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.AuthorizationServiceCollectionExtensions::AddAuthorization(Microsoft.Extensions.DependencyInjection.IServiceCollection)
      at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod (Mono.Cecil.MethodReference reference) [0x0001b] in /Users/builder/azdo/_work/2/s/xamarin-macios/builds/mono-ios-sdk-destdir/ios-sources/external/linker/src/linker/Linker.Steps/MarkStep.cs:2294
      at Mono.Linker.Steps.MarkStep.MarkMethod (Mono.Cecil.MethodReference reference) [0x00063] in /Users/builder/azdo/_work/2/s/xamarin-macios/builds/mono-ios-sdk-destdir/ios-sources/external/linker/src/linker/Linker.Steps/MarkStep.cs:1872

```

Digging into it more, it seems like you are linking 3.1.14:

`/Users/gaborparadi/.nuget/packages/microsoft.aspnetcore.authorization/3.1.14/lib/netstandard2.0/Microsoft.AspNetCore.Authorization.dll"` which according to [nuget](https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization/) was released April of 2021.

But according to the doucmentation the type being complained about:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.authorizationservicecollectionextensions?view=aspnetcore-6.0

was introduced in 6.0.

I would reach out to the blazor team and [file and issue with them](https://github.com/dotnet/aspnetcore/issues/new/choose).

From the outside, it seems some dependency in your tree depends on an older Microsoft.AspNetCore.Authorization but another needs a newer type. In non-linked land we can get away with this if the final binaries have all of the types, but the linker needs to be more specific to work correctly, and thus we fail.

**Comment by chamons** [comment]
If after discussion with the blazor team this is expected feel free to reopen this issue.
