### ISSUE TITLE
On Mac WKWebView keeps asking for permission on some websites (not on Xcode)

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#14167]
### Steps to Reproduce

Run the sample project provided below or:
1. Add a WKWebView
2. Navigate to "https://windowscentral.com" (and this happens on most sites this is just a sample)
3. 

### Expected Behavior
This should just navigate to the site as it does when the project is built with Xcode (sample project provided below too)

### Actual Behavior
I get a security prompt:
> webtest wants to use your confidential information stored in "webtest WebCrypto Master Key" in your keychain.

### Environment

```
Visual Studio Community 2019 for Mac
Version 8.10.19 (build 2)
Installation UUID: 0e5b2ac6-d5a3-45e5-94c5-b4906a732e38
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

Mono Framework MDK
Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

Xamarin Designer
Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

Roslyn (Language Service)
3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

NuGet
Version: 5.9.0.7134

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/5.0.405/Sdks
SDK Versions:
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11

Xamarin.Profiler
Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 13.2.1 (19586)
Build 13C100

Xamarin.Mac
Version: 8.6.0.3 (Visual Studio Community)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

Xamarin.iOS
Version: 15.6.0.3 (Visual Studio Community)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

Xamarin.Android
Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/ivanicin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

Android Device Manager
Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

Build Information
Release ID: 810190002
Git revision: 632b6ca654e2733a685bfc9c6a0686e0a317092b
Build date: 2022-02-09 13:38:14-05
Build branch: release-8.10

Operating System
Mac OS X 12.1.0
Darwin 21.2.0 Darwin Kernel Version 21.2.0
    Sun Nov 28 20:28:54 PST 2021
    root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
```

### Example Project (If Possible)

[webtest.zip](https://github.com/xamarin/xamarin-macios/files/8080528/webtest.zip)
[webtest xcode.zip](https://github.com/xamarin/xamarin-macios/files/8080533/webtest.xcode.zip)

**Comment by ivanicin** [comment]
@chamons @rolfbjarne I do understand that you are busy in finalising .NET 6 and MAUI. However releasing .NET 6 and MAUI with a web view that has a severe bug on the platform doesn't sound like a great idea, so possibly someone could look at this.

Assuming that the bug is reproducible of course, but I think the samples above should reproduce it.

**Comment by chamons** [comment]
Apologies for delay in response.

I see the same behavior when running from Xcode:

![image](https://user-images.githubusercontent.com/6392201/161098774-d480257e-5869-4932-ad4d-a6c227b609a9.png)

A brief search suggests this is code inside safari: https://opensource.apple.com/source/WebCore/WebCore-7603.1.30.1.33/crypto/mac/SerializedCryptoKeyWrapMac.mm.auto.html

And [others](https://discussions.apple.com/thread/251044534) have [hit this](https://talk.macpowerusers.com/t/safari-webcrypto-master-key-in-keychain/20322) who aren't using Xamarin.

Consider opening an [issue with Apple](https://developer.apple.com/bug-reporting/).

**Comment by ivanicin** [comment]
@chamons thanks for reaching back!

If you can reproduce on Xcode then I fully agree that this is not a Xamarin bug.

As I can't reproduce the issue on Xcode, I can't submit anything to Apple. While technically I know based on this that this is the Xcode bug, I can't prove it on my device and as such I am not a viable bug reporter for Apple.
