### ISSUE TITLE
[NET Attribute Conversion] Implied Introduced from conversion don't carry deprecated forward

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#14178]
There are cases where MacCatalyst was implied either by [iOS] introduced or no attribute at all, but later iOS was deprecated. MacCatalyst did not have a deprecation, so it was not carried forward.

Example: https://github.com/xamarin/xamarin-macios/pull/14128/files#diff-e2b730a5d734c647d967e2b6c2692165d2bc22b35710d3962d277eef322fcbe8R42

We need to write a test to look for cases where there is an iOS (or mac?) deprecation and no deprecation for Catalyst and reason about them? Or could we teach xtro to catch these in NET6?

**Comment by rolfbjarne** [comment]
@chamons should we postpone this to .NET 7?

**Comment by chamons** [comment]
Yes

**Comment by rolfbjarne** [comment]
We have this test now, which I believe covers this:

https://github.com/xamarin/xamarin-macios/blob/a26e3c57f4c993098a579c37780d16d91ec38a9f/tests/cecil-tests/ApiAvailabilityTest.cs#L18-L20
