### ISSUE TITLE
Xamarin Forms IOS app very very slow when debugger is connected

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#14247]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-Forms-IOS-app-very-very-slow-whe/1668123)._

---
Over the last couple of days I have noticed a serious degradation in performance of our app opn iOS when the debugger is connected.

If i run the same debug build with the debugger disconnected it runs fine.

When I say "slow" here are some headline numbers 45 seconds to new move to a new view, 15 seconds to respond to a scroll for a view that has a a TableView with 20 ViewCells in it!

Any idea what might be the cause of this? Whilst I appreciate this might be something stupid I have done the same build on the same device resopnds perfectly once the debugger is disconnected and the app started on the device

VS 2019 on Windows 16.11.7 connected to Macbook pro with Xcode 13.1 over a wired network

---
#### Feedback Bot on 2/16/2022, 11:40 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Pat Long on 2/18/2022, 08:23 AM: 

(private comment, text removed)
#### Patrick Long on 2/21/2022, 06:42 AM: 

<p>I have now upgraded to lastest VS2019 16.11.10. Still unusable with the debugger attached</p>

#### Patrick Long on 2/22/2022, 08:54 AM: 

<p>I also tried VS 2020 but the problem was still there. I followed the suggestion <a target='_blank' href="https://developercommunity.visualstudio.com/t/debugging-xamarin-ios-application-is-very-slow-vs/676129#T-N713077">here</a> to change the Link Behavior and that has allowed me to debug again, <a target='_blank' href="https://developercommunity.visualstudio.com/t/debugging-xamarin-ios-application-is-very-slow-vs/676129#T-N713077">https://developercommunity.visualstudio.com/t/debugging-xamarin-ios-application-is-very-slow-vs/676129#T-N713077</a></p>
<p>Obviously this is just a workaround rather than a fix</p>

---
### Original Solutions
(no solutions)

**Comment by chamons** [comment]
Sorry for the bouncing back and forth, but I've reopened the devcom issue and will close this in it's place, as it should be looked at by IDE debugger folks first. 

Given the changes in that stack, it is premature to have the SDK dig into this.
