### ISSUE TITLE
[net] The linker does not remove resources from `System.Runtime.InteropServices.dll`

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#14257]
The `System.Runtime.InteropServices.dll` assembly is now part of every application for its `NFloat` type forwarder.

It's linked (code is removed) but the resources files are not removed like other assemblies.

### Steps to Reproduce

1.  `cd tests/dotnet`
2. `make compare`

### Expected Behavior

Resources from `System.Runtime.InteropServices.dll` are removed.

### Actual Behavior

`System.Runtime.InteropServices.dll` still contains resources
* `FxResources.System.Runtime.InteropServices.SR.resources`
* `ILLink.Substitutions.xml`

The later resource has instructions to remove the former resource.

### Environment

`main`

**Comment by spouliot** [comment]
Looks like the substitution xml is never loaded.

I'm guessing that the code path that triggers this is never executed since all, but the type forwarder to `NFloat`, members are not marked.

So we end up keeping the assembly (for the forwarder) but not removing the resources.

**Comment by rolfbjarne** [comment]
Created a repro and filed a linker issue: https://github.com/dotnet/linker/issues/2661

**Comment by rolfbjarne** [comment]
It doesn't look like there's anything we need to do, this is entirely a linker bug, so I'm closing this issue.
