### ISSUE TITLE
C# Xamarin.iOS Collection objects are being agressively garbage collected in Debug

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#14273]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-XamariniOS-Collection-objects-are-be/1677878)._

---
[severity:It's more difficult to complete my work]
While examining List<x> or Dictionary<x,y> when the drop-down is clicked to view the individual items they are only available momentarily and quickly change to "The requested operation cannot be completed because the object has been garbage collected".

It sounds very much like the 4-year old (and closed) issue described here

https://developercommunity.visualstudio.com/t/objects-in-list-are-being-garbage-collected-during/210870

though one (important?) difference is that I'm running on actual devices and not on a simulator.

These are short collections (Count = 8 or 10) and in situations where there isn't any memory pressure.

Also, this seems to happen both to the values shown by "hovering" over a data member as well as to the values shown in the "Locals" panel. For hovering, if you hover over something else and then return to the list item, the values will again (briefly) be available before prematurely being GC'd away as well.

---
#### Feedback Bot on 2/27/2022, 11:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by gdignard** [comment]
Just to be 100% clear since the original tag didn't follow the ticket move, this is happening on Visual Studio Professional 2019 (v16.11.10) on Windows.

**Comment by gdignard** [comment]
Ping. Not being able to see member values while Debugging is a little debilitating. I understand that this may take a while to fix, but hopefully it could at least get triaged?

**Comment by chamons** [comment]
Sorry to bounce this around, but I've moved this back to dev community as I believe it is more IDE or debugger than SDK, and those issues are not accessible to github. Apologies.
