### ISSUE TITLE
How to use DCAppAttestService and DeviceCheck

### ISSUE THREAD

**Issue by developer9969** [xamarin/xamarin-macios#14272]
Hi
This is not an issue but a question on how to use DeviceCheck and DCAppAttestService .
I cannot find any example of usage anywhere and wondering if you could shed some light!.

I know its a long shot but just trying my luck!!

What I am trying to do?
Well I know it cannot be 100% proven that the device is jailbroken, however it would be nice if could verify the integrity of my app.

Any suggestions/ snippet / blog or repo?

**Comment by chamons** [comment]
I would follow Apple's documentation [here](https://developer.apple.com/documentation/devicecheck/establishing_your_app_s_integrity).

The examples are in swift, but it should be straight forward to translate to C#.

You can also find other Xamarin developer on the [DotNetEvolution discord](https://aka.ms/dotnet-discord) that might have experience with this specific API
