### ISSUE TITLE
[mlaunch] The mlaunch nugets are not being built/published

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#14304]
When looking at https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5831225&view=logs&j=600d49c6-e96b-5e8b-2c3a-9f351e2e5848&t=c05d7aeb-34b2-51cd-6481-b630559e2eae we noticed that the mlaunch nugets pkgs are not publish which are needed by donet/xharness

/cc @premun

**Comment by premun** [comment]
@mandel-macaque the build phase checks whether the nupkg is actually needed:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5831225&view=logs&j=600d49c6-e96b-5e8b-2c3a-9f351e2e5848&t=19f70131-47ab-533d-c4d8-29c0f5339828&l=137:
> nuget list -source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json -AllVersions -Prerelease Microsoft.DotNet.Mlaunch
grep 6e6b84249b
Microsoft.DotNet.Mlaunch 13.2.0-22110.16.6e6b84249b
Mlaunch revision 6e6b84249b is already published as nupkg
echo 'Mlaunch revision 6e6b84249b is already published as nupkg'

The NuGets seem to be flowing OK, last one on February 10th:
https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.DotNet.Mlaunch/13.2.0-22110.16.6e6b84249b/overview

**Comment by rolfbjarne** [comment]
We publish our own nugets for mlaunch now, so this doesn't apply anymore.
