### ISSUE TITLE
NuGet restore on Windows with macos workload yields "Illegal characters in path" error

### ISSUE THREAD

**Issue by sandyarmstrong** [xamarin/xamarin-macios#14331]
Seen while working on https://github.com/dotnet/roslyn/pull/59429#issuecomment-1043195174.

> ##[error]C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error : (NETCORE_ENGINEERING_TELEMETRY=Restore) The expression "[MSBuild]::MakeRelative(D:\a\_work\1\s\src\EditorFeatures\Core.Cocoa, *.plist)" cannot be evaluated. Illegal characters in path.  D:\a\_work\1\s\.dotnet\packs\Microsoft.macOS.Sdk\12.1.302-preview.14.6\targets\Microsoft.macOS.Sdk.DefaultItems.props

https://github.com/xamarin/xamarin-macios/blob/main/dotnet/targets/Microsoft.Sdk.DefaultItems.template.props#L23

Worked around by adding `<EnableDefaultmacOSItems>false</EnableDefaultmacOSItems>`, as the csproj in question is a fairly simple library project. Still, I was surprised to see this error and wonder if it was Windows-specific.

**Comment by rolfbjarne** [comment]
I can't reproduce on my Mac, although I wonder if it's a variation of https://github.com/dotnet/msbuild/issues/4056#issuecomment-1058471747.

**Comment by rolfbjarne** [comment]
We'll need a way to reproduce this in order to fix it and track it down.

**Comment by sandyarmstrong** [comment]
When I have a chance I'll get you a Roslyn branch that does this. I believe I saw it locally on Windows and not just in CI, but will have to confirm.

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
