### ISSUE TITLE
Could not install package 'Microsoft.EntityFrameworkCore 6.0.3'. with 'Xamarin.Mac,Version=v2.0',

### ISSUE THREAD

**Issue by NickTullos** [xamarin/xamarin-macios#14436]
### Steps to Reproduce
1. Create a Cocoa project using Visual Studio Mac preview 7
2. Add EntityFramework using nuget 

### Expected Behavior
3. nuget package installs properly and the world says hello...

### Actual Behavior
Could not install package 'Microsoft.EntityFrameworkCore 6.0.3'. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Environment

```
Visual Studio Community 2022 for Mac Preview
Version 17.0 Preview (17.0 build 8001)
Installation UUID: 9a57887e-b991-4e32-84b0-833971415609

Runtime
.NET 6.0.2-servicing.1.22101.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.1.0-3.22075.3+592501cbb9c9394072a245c15b3458ff88155d85

NuGet
Version: 6.0.0.262

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.201/Sdks
SDK Versions:
	6.0.201
	6.0.200
	6.0.101
MSBuild SDKs: /usr/local/share/dotnet/sdk/6.0.201/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.201
	6.0.200
	6.0.101
	5.0.406
	5.0.405
	3.1.417
	3.1.416

.NET Core Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.3
	6.0.2
	6.0.1

Xamarin.Profiler
Version: 1.7.0.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.2.0.23
Hash: ac7b2f4
Branch: remotes/origin/jonp-bump-at-c5729b16~1
Build date: 2022-03-11 17:26:01 UTC

Android Device Manager
Version: 0.0.0.1102
Hash: 70060c2
Branch: remotes/origin/HEAD~1
Build date: 2022-03-11 17:26:01 UTC

Apple Developer Tools
Xcode 13.2.1 (19586)
Build 13C100

Xamarin.Mac
Version: 8.6.0.3 (Visual Studio Community)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

Xamarin.iOS
Version: 15.6.0.3 (Visual Studio Community)
Hash: caa899d24
Branch: d17-1
Build date: 2022-01-16 21:16:56-0500

Xamarin Designer
Version: 17.1.5.29
Hash: 631c9091b
Branch: remotes/origin/d17-0-vsmac
Build date: 2022-03-11 17:25:57 UTC

Build Information
Release ID: 1700008001
Git revision: 64fe256db3b9f472065f8df46220cffb52a07cde
Build date: 2022-03-11 17:23:36+00
Build branch: release-17.0
Build lane: release-17.0

Operating System
Mac OS X 12.2.1
Darwin 21.3.0 Darwin Kernel Version 21.3.0
    Wed Jan  5 21:37:58 PST 2022
    root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

```

### Build Logs

NA

### Example Project (If Possible)

NA

**Comment by chamons** [comment]
Thanks for the feedback and apologies for the delay in response. 


I believe the error means what it says:

> You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework.

As documented here: https://docs.microsoft.com/en-us/xamarin/mac/platform/target-framework

The Xamarin.Mac target frameworks, also sometimes called 'Modern' or 'Mobile' is a slimmed down subset of the base class library that produces slim and linker safe applications. However, some libraries require more of the full base class library, and are not compatible with it.

As described in those docs, you can choose to swap to the 'Full' framework, but there are size and performance considerations (which is why it is not default.
