### ISSUE TITLE
[.NET] Regression: Compilation of .resx broken in Preview 14

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#14442]
### Steps to Reproduce

1. `git clone https://github.com/filipnavara/xam-p14-resx-dup`
2.  `dotnet build`

Any class library project with .resx files under "Resources" directory fails to compile.

### Expected Behavior

Project compiles.

### Actual Behavior

```
/usr/local/share/dotnet/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(3261,5): error MSB3577: Two output file names resolved to the same output path: "obj/Debug/net6.0-macos/lib.Resources.MailApp.resources"
```

### Environment

.NET 6.0.3, macOS workload P14

**Comment by rolfbjarne** [comment]
It might be enough to add *.resx to the Exclude files here: https://github.com/xamarin/xamarin-macios/blob/d3643414e7900134df13f1962f0ffba85965c25e/dotnet/targets/Microsoft.Sdk.DefaultItems.template.props#L87-L95

**Comment by filipnavara** [comment]
My current workaround is
```csharp
  <!-- Xamarin.Mac Preview 14 workaround -->
  <ItemGroup Condition=" '$(EnableDefaultmacOSItems)' == 'true' ">
    <BundleResource Remove="Resources/**/*.cs" />
    <BundleResource Remove="Resources/**/*.resx" />
  </ItemGroup>
```

**Comment by rolfbjarne** [comment]
@jonathanpeppers is this something Android can run into? If so, how do you handle it?

**Comment by rolfbjarne** [comment]
@jonathanpeppers did you test to see what happens on XA?

**Comment by rolfbjarne** [comment]
Potential solutions:

---

### 1. Don't automatically include `*.resx` files as `BundleResource` items

This is the solution I mentioned [above](https://github.com/xamarin/xamarin-macios/issues/14442#issuecomment-1070862877).

This has the downside of feeling somewhat random (there may be numerous types of resources that should behave like \*.resx files, why don't we have the same way for those?)

### 2. Keep doing what we're doing (adding everything in `Resources/**` as BundleResorce items).

There are a few ways for projects to do something else if this is not desired:

a. Remove the offending files from the `BundleResource` item group (like the workaround in https://github.com/xamarin/xamarin-macios/issues/14442#issuecomment-1070880882).
b. Set the `IPhoneResourcePrefix` / `XamMacResourcePrefix` property to something other than `"Resources"`, and add/move all the resources that should be bundled in the app in that directory. If no resources should be bundled, a non-existent directory can be used.
c. Set `EnableDefaultmacOSItems=false`

As a variation/improvement, we could detect the special case of \*.resx, and either remove them from any other item groups, or show a descriptive warning or error message.

---

I'm leaning towards the second solution, it seems simpler, and easier to explain.

**Comment by filipnavara** [comment]
> I'm leaning towards the second solution, it seems simpler, and easier to explain.

I'm leaning towards the first solution.

The reasoning is that most of the projects started as `net6.0` (or older versions) and the `Resources` directory is a convention used by Visual Studio (or at least it used to be). The error appeared as consequence of switching from `net6.0` TFM to `net6.0-macos` TFM which was done solely for the purpose of accessing few native APIs, not adding platform-specific resources, so it seems like unintuitive side effect.

Majority of the projects where we hit this are class libraries, so `EnableDefaultmacOSItems` could have been used, but for the remaining projects we would still need to use a different workaround (2a or 2b). In essence, we have exactly zero projects where it is desirable to include `.resx` files as iOS/macOS resources. I believe that's the majority use case for C# projects and treating `Resources/**/*.resx` differently than any other `**/*.resx` is the odd one out.

**Comment by jonathanpeppers** [comment]
> @jonathanpeppers did you test to see what happens on XA?

It seems like a `dotnet new android` builds successfully when you put a `.resx` file in `Assets/` or `Resources/raw/`:

[foo.zip](https://github.com/xamarin/xamarin-macios/files/8371873/foo.zip)

But I think it's because we aren't copying these files to output, and they are packaged up differently.
