### ISSUE TITLE
Latest update of Microsoft.MacCatalyst.Sdk does not work with Microsoft.Build.CentralPackageVersions

### ISSUE THREAD

**Issue by edoust** [xamarin/xamarin-macios#14452]
### Steps to Reproduce

1. Create a new .NET 6 app with target framework `net6.0-maccatalyst15.2`
2. Install latest workloads, etc. - I tested with `15.2.302-preview.14.117`
3. Reference `Microsoft.Build.CentralPackageVersions`, version `2.1.3`

### Expected Behavior

The build should work fine when using `Microsoft.Build.CentralPackageVersions` and target framework `net6.0-maccataalyst15.2`

### Actual Behavior

See the build fail with error `The package reference System.Runtime.InteropServices.NFloat.Internal should not specify a version. Please specify the version in 'xxx\Packages.props' or set VersionOverride to override the centrally defined version.`

### Further info

The issue is created by the package reference added to `System.Runtime.InteropServices.NFloat.Internal` as part of `Xamarin.Shared.Sdk.DefaultItems.targets`, this is the part I am talking about:

![19-03-2022_13-30-04](https://user-images.githubusercontent.com/6137595/159121216-40b8d7d2-4ee3-4f8a-8dad-514e8300f41c.png)

I also reported this for Microsoft.Build.CentralPackageVersions as issue [#346](https://github.com/microsoft/MSBuildSdks/issues/346)

**Comment by rolfbjarne** [comment]
I'm unable to reproduce this with the versions mentioned and this csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-maccatalyst15.2</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>15.2</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />
  </ItemGroup>
</Project>
```

Could you build from the command line like this:

    dotnet build /bl

and attach the resulting msbuild.binlog file here?

Alternatively we need a test project we can use to reproduce this.

**Comment by rolfbjarne** [comment]
I'm unable to reproduce this with the versions mentioned and this csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-maccatalyst15.2</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>15.2</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />
  </ItemGroup>
</Project>
```

Could you build from the command line like this:

    dotnet build /bl

and attach the resulting msbuild.binlog file here?

Alternatively we need a test project we can use to reproduce this.

**Comment by edoust** [comment]
You need to add an sdk reference to CentralPackageVersions, not a package reference, like [documented here](https://github.com/microsoft/MSBuildSdks/tree/main/src/CentralPackageVersions#centrally-managing-package-versions):
````xml
<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />

  <PropertyGroup>
    <TargetFramework>net6.0-maccatalyst15.2</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>15.2</SupportedOSPlatformVersion>
  </PropertyGroup>

</Project>
````

**Comment by rolfbjarne** [comment]
That built just fine too.

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/8335604/msbuild.binlog.zip)

Can you do `dotnet build /bl` and attach the resulting msbuild.binlog here so that I can figure out what the difference is between your build and mine?

**Comment by edoust** [comment]
You can use this project to repro (retested, this definitely does not build on most recent MacCatalyst preview workload)
[Repro.zip](https://github.com/xamarin/xamarin-macios/files/8350868/Repro.zip)

I can see from your log that your build is skipping the relevant target:
`Target "CheckPackageReferences" skipped, due to false condition; ( '$(EnableCentralPackageVersions)' != 'false' And '$(DesignTimeBuild)' != 'true' And @(PackageReference->Count()) > 0 ) was evaluated as ( 'false' != 'false' And '' != 'true' And 1 > 0 ).`

**Comment by dalexsoto** [comment]
Hello @edoust please can you also provide the requested the binlog?

thank you!

**Comment by edoust** [comment]
Of course, [Repro.binlog.zip](https://github.com/xamarin/xamarin-macios/files/8350985/Repro.binlog.zip)

**Comment by Cheesebaron** [comment]
Projects that target net6.0-* targetframeworks now implicitly get System.Runtime.InteropServices.NFloat.Internal NuGet package added.

When using Central Package Management feature of NuGet, it expects all package versions to be defined in `Directory.Packages.props`. However, the way System.Runtime.InteropServices.NFloat.Internal is added, makes Central Package Management think it was added directly to the project.

This throws errors like this for each TFM:

![image](https://user-images.githubusercontent.com/249719/160462367-1a5523bb-d770-423b-8fc6-83e8a09fb824.png)

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1008	Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: System.Runtime.InteropServices.NFloat.Internal.	MvvmCross.Plugin.Visibility	C:\git\MvvmCross\MvvmCross.Plugins\Visibility\MvvmCross.Plugin.Visibility.csproj	1	
```

This seems to have started to happening after updating my net6 workloads recently.

This can be seen on the `net6` branch in MvvmCross: https://github.com/MvvmCross/MvvmCross/tree/feature/net6

This is not only for the maccatalyst tfm, but also for net6.0 tfms.

**Comment by akoeplinger** [comment]
I wonder if we need to set `IsImplicitlyDefined="true"` on the PackageReference to bypass the NU1008 error.

https://github.com/xamarin/xamarin-macios/blob/15c17ddecec33b9fb76c1f3ed228f83ffe7ac25c/dotnet/targets/Xamarin.Shared.Sdk.DefaultItems.targets#L113-L114

/cc @JonDouglas

**Comment by akoeplinger** [comment]
Yeah looks like they're doing just that for FSharp.Core which had the same issue (https://github.com/microsoft/MSBuildSdks/blob/27d7541dc309cf7308611f92a6730bc2ddd5f2aa/src/CentralPackageVersions/Sdk/Sdk.targets#L59-L65).
