### ISSUE TITLE
Improve NSAttributedString ctors in foundation.cs

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#14489]
During the great breaking change API scrub, [one API was missed in foundation.cs](https://github.com/xamarin/xamarin-macios/blob/main/src/foundation.cs#L291-L310).

We have a sub-optimal API in `initWithURL:options:documentAttributes:error` due to issues in iOS 9, which we aren't supporting anymore.

I started a patch to fix this:

https://gist.github.com/e5bf4dae26f2accdaf4b6a9de76ed206

but ran into time box issues and it started getting complicated in a mechanical PR. I decided to punt it for now, thus this issue.

**Comment by chamons** [comment]
FYI @rolfbjarne @dalexsoto

**Comment by rolfbjarne** [comment]
I had a look at the NSAttributedString API, and there is _significant_ room for improvement. That said, it seems to be possible to do it without breaking anything, so I'm postponing to .NET 7.
