### ISSUE TITLE
"The app icon set has an unassigned child" warning in watchOS applications

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#14553]
Originally in internal issue https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1489282

### Steps to Reproduce

1. Create WatchOSApp
2. Tool->iOS ->Pair to MAC
3. Build with iPhoneSimulator or iPhone. 

### Expected Behavior
No warnings
### Actual Behavior
![image](https://user-images.githubusercontent.com/6392201/160635789-e3d717f4-c0d9-48b4-ae07-e00b50d376e6.png)

### Environment

VS 17.0.1 [31910.222.d17.0]

**Comment by rolfbjarne** [comment]
Closing, since watchOS isn't supported in .NET, and Xamarin is not supported anymore.
