### ISSUE TITLE
Parameter Protocolize Audit

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#14585]
As found in https://github.com/xamarin/ios-samples/issues/446 and fixed in once place in https://github.com/xamarin/xamarin-macios/pull/14582#issuecomment-1083495997 we have a number of Protocolize attributes in arguments that may be incorrect.

We need to do an audit and review them one by one.

**Comment by rolfbjarne** [comment]
We can probably just remove the `[Protocolize]` attribute, and add the `I` prefix to all the corresponding types to clean up our codebase.

`[Protocolize]` was used to build for both Classic and Unified profiles at the same time, but we're no longer building Classic, so we can update our code now.

**Comment by rolfbjarne** [comment]
This is an example of what we should do:

```diff
diff --git a/src/storekit.cs b/src/storekit.cs
index d84ef7fe9fb..82bb53890cd 100644
--- a/src/storekit.cs
+++ b/src/storekit.cs
@@ -241,10 +241,10 @@ namespace StoreKit {
                void FinishTransaction (SKPaymentTransaction transaction);

                [Export ("addTransactionObserver:")]
-               void AddTransactionObserver ([Protocolize]SKPaymentTransactionObserver observer);
+               void AddTransactionObserver (ISKPaymentTransactionObserver observer);

                [Export ("removeTransactionObserver:")]
-               void RemoveTransactionObserver ([Protocolize]SKPaymentTransactionObserver observer);
+               void RemoveTransactionObserver (ISKPaymentTransactionObserver observer);

                [Export ("transactions")]
                SKPaymentTransaction [] Transactions { get; }
diff --git a/src/uikit.cs b/src/uikit.cs
index db5672d1d39..1a849ede988 100644
--- a/src/uikit.cs
+++ b/src/uikit.cs
@@ -582,8 +582,7 @@ namespace UIKit {
                double UpdateInterval { get; set; }

                [Wrap ("WeakDelegate")]
-               [Protocolize]
-               UIAccelerometerDelegate Delegate { get; set; }
+               IUIAccelerometerDelegate Delegate { get; set; }

                [Export ("delegate", ArgumentSemantic.Assign)][NullAllowed]
                NSObject WeakDelegate { get; set; }
```

If the Protocolize attribute is only for !NET code, like this, then nothing needs to be done:

https://github.com/xamarin/xamarin-macios/blob/2d96d431459199ab1c0fc30c79bd631b2c14337f/src/appkit.cs#L2077-L2081
