### ISSUE TITLE
Platform annotation issues in Microsoft.iOS assembly

### ISSUE THREAD

**Issue by buyaa-n** [xamarin/xamarin-macios#14619]
While trying to [Fix Platform Compatibility Analysis Violations](https://github.com/dotnet/maui/issues/823) in MAUI repo found several annotations/attribute issues with in `Microsoft.iOS.dll` which causing false positive warnings.

The assembly annotated with
```cs
[assembly: SupportedOSPlatform("ios10.0")]
[assembly: SupportedOSPlatform("tvos10.0")]
[assembly: SupportedOSPlatform("macos10.14")]
[assembly: SupportedOSPlatform("maccatalyst13.1")]
[assembly: UnsupportedOSPlatform("watchos")] // this is redundant, but would not cause an issue
```
Which applies to all types/APIs inside it, unless they annotated individually. `[assembly: UnsupportedOSPlatform("watchos")]` attribute above is redundant as there is a list of `SupportedOSPlatforms`, the assemply is only supported on those and unsupported all other.

Annotations within child members could override parent annotation and narrow down parent support. For example `CMAccelerometerData` type within this assembly is annotated with `[SupportedOSPlatform("macos10.15")]` , this overrides all other parent support and makes the type only supported for `[SupportedOSPlatform("macos10.15")]`. It seems in most cases these child type/APIs attributes intended to change the version support only, if that is the case all other supported platforms need to have added along with the updated/supported version. i.e `CMAccelerometerData` should have the `SupportedOSPlatform("macos10.15")]` along with other support (`SupportedOSPlatform("ios10.0")], [SupportedOSPlatform("tvos10.0")], [SupportedOSPlatform("maccatalyst13.1")]) if the API still supports them

Below is the list of child type/APIs annotations that causing warnings in the MAUI build that looks suspicious and needs a review/update. 

CC @dalexsoto @Redth @jeffhandley

### APIs need check/update 

Warning message | Cause | Comment | Fix
-- | -- | -- | --
'CMAccelerometerData.Acceleration' is only supported on 'macOS/OSX' 10.15 and later.  | Type has [SupportedOSPlatform("macos10.15")]	means only for macos10.15 | If the annotation is correct, seems supported on iOS and others | Add attributes for other platforms
 'CLLocationManager.HeadingAvailable' is only supported on 'macOS/OSX' 11.0 and later.  | Property & getter has [UnsupportedOSPlatform(""tvos")],  [SupportedOSPlatform("macos11.0")] | [UnsupportedOSPlatform("tvos")] has no effect, is it only supported on macos11.0" or above?  | Add other platforms support
'CLLocationManager.HeadingAvailable.get' is only supported on 'macOS/OSX' 11.0 and later.   | Property & getter has [UnsupportedOSPlatform(""tvos")],  [SupportedOSPlatform("macos11.0")] 	| No need to repeat the same annotation for getter/setter | 
'CLLocationManager.HeadingFilter' is only supported on 'macOS/OSX' 11.0 and later.  	| Same as above |  Same as above | 
 'CLLocationManager.HeadingFilter.set' is only supported on 'macOS/OSX' 11.0 and later.  | Same as above |  Same as above | 
 'CLLocationManager.StartUpdatingHeading()' is only supported on 'macOS/OSX' 11.0 and later.  | Method has [UnsupportedOSPlatform("tvos")], [SupportedOSPlatform("macos11.0")] | is it only supported on macos11.0" or above? | Add other supported platforms
 'CLLocationManager.StopUpdatingHeading()' is only supported on 'macOS/OSX' 11.0 and later.  | Method has [UnsupportedOSPlatform("tvos")], [SupportedOSPlatform("macos11.0")] | is it only supported on macos11.0" or above? | Add other supported platforms	
 'UIViewController.DismissModalViewController(bool)' is only supported on 'macOS/OSX' 10.14 and later.  | Method has [UnsupportedOSPlatform("tvos")], [UnsupportedOSPlatform("ios6.0")]	 | it is used in call site reachable on ios 10 and above | Is the unsupported version correct?
 'UIApplication.StatusBarOrientation' is only supported on 'macOS/OSX' 10.14 and later. 	| Getter setter has [UnsupportedOSPlatform("tvos")], [UnsupportedOSPlatform("ios9.0")] | Reachable in call site ios 10 and above  | is unsupported from ios9.0 correct?
 'UIApplication.StatusBarOrientation.get' is unsupported on 'ios' 9.0 and later, 'maccatalyst' 9.0 and later. | Getter setter has [UnsupportedOSPlatform("tvos")], [UnsupportedOSPlatform("ios9.0")] | Reachable in call site ios 10 and above
 'AVCaptureDevice.GetDefaultDevice(AVMediaTypes)' is only supported on 'maccatalyst' 14.0 and later. | Type has [SupportedOSPlatform("maccatalyst14.0")], [UnsupportedOSPlatform("tvos")] | is it only available on maccatalyst14.0 and above? |	Add other supported platforms
 'AVCaptureDevice.HasFlash' is only supported on 'maccatalyst' 14.0 and later.   | Same as above |  Same as above | 
 'AVCaptureDevice.HasTorch' is only supported on 'maccatalyst' 14.0 and later. 	  | Same as above |  Same as above | 
 'AVCaptureDevice.LockForConfiguration(out NSError)' is only supported on 'maccatalyst' 14.0 and later. 	  | Same as above |  Same as above | 
  'AVCaptureDevice.MaxAvailableTorchLevel' is only supported on 'maccatalyst' 14.0 and later. 	  | Same as above |  Same as above | 
 'AVCaptureDevice.MaxAvailableTorchLevel.get' is only supported on 'macOS/OSX' 10.15 and later. 	  | Same as above |  Same as above | 
 'AVCaptureDevice.SetTorchModeLevel(float, out NSError)' is only supported on 'maccatalyst' 14.0 and later.   | Same as above |  Same as above | 
 'AVCaptureFlashMode.On' is only supported on 'maccatalyst' 14.0 and later.   | Same as above |  Same as above | 
 'AVCaptureDevice.FlashMode' is unsupported on 'maccatalyst' 10.0 and later. 	  | Same as above |  Same as above | 
 'AVCaptureDevice.FlashMode.set' is unsupported on 'ios' 10.0 and later, 'maccatalyst' 10.0 and later.   | Same as above |  Same as above | 
 'AVCaptureTorchMode.Off' is only supported on 'maccatalyst' 14.0 and later.   | Same as above |  Same as above | 
 'AVCaptureDevice.TorchMode' is only supported on 'maccatalyst' 14.0 and later.   | Same as above |  Same as above | 
 'AVCaptureDevice.UnlockForConfiguration()' is only supported on 'maccatalyst' 14.0 and later.   | Same as above |  Same as above | 
 'CLLocationManager.PausesLocationUpdatesAutomatically' is only supported on 'macOS/OSX' 11.0 and later. | getter & setter has [UnsupportedOSPlatform("tvos")], [SupportedOSPlatform("macos11.0")] | is it only for macOS11.0+? | Add other support
 'CLLocationManager.PausesLocationUpdatesAutomatically.set' is only supported on 'macOS/OSX' 11.0 and later. 	| Same as above | 
 'CMGyroData.RotationRate' is only supported on 'macOS/OSX' 10.15 and later. | Type has [SupportedOSPlatform("macos10.15")]	| Not supported any other? | Add other support
 'UIDocumentInteractionController' is only supported on 'maccatalyst' 14.0 and later.  | Type has [UnsupportedOSPlatform("tvos")],  [SupportedOSPlatform("maccatalyst14.0")] | Not supported any other? | Add other support
 'UIDocumentInteractionController.Name' is only supported on 'maccatalyst' 14.0 and later. | Same as above |  Same as above | 	
 'UIDocumentInteractionController.Url' is only supported on 'maccatalyst' 14.0 and later. 	| Same as above |  Same as above | 
 'UIDocumentInteractionController.Uti' is only supported on 'maccatalyst' 14.0 and later. 	| Same as above |  Same as above | 
 'UIDocumentInteractionController.PresentOpenInMenu(CGRect, UIView, bool)' is only supported on 'maccatalyst' 14.0 and later. 	| Same as above |  Same as above | 
 'CMMagnetometerData.MagneticField' is only supported on 'macOS/OSX' 10.15 and later. |Type has [SupportedOSPlatform("macos10.15")]	| No other support? | Add other support
 'CMMagneticField.X' is only supported on 'macOS/OSX' 10.15 and later. | Type has [SupportedOSPlatform("macos10.15")] | No any other support? | Add other support
 'CMMagneticField.Y' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as above | 
 'CMMagneticField.Z' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as above | 
 'PHAssetResource' is only supported on 'macOS/OSX' 10.15 and later.  | Type has [SupportedOSPlatform("macos10.15")] | Isn't the type is supported on iOS (maccatalyst) | add other supported platforms
 'PHAssetResource.GetAssetResources(PHAsset)' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as above |	
 'PHAssetResource.OriginalFilename' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as above | 
 'CMAttitude.Quaternion' is only supported on 'macOS/OSX' 10.15 and later. | Type has [SupportedOSPlatform("macos10.15")]	Determine if it is supported on iOS | and take action
 'CMDeviceMotion.Attitude' is only supported on 'macOS/OSX' 10.15 and later. | Type has [SupportedOSPlatform("macos10.15")]	| only for macos10.15+? | add other support
 'AVCaptureDevice.GetAuthorizationStatus(AVAuthorizationMediaType)' is only supported on 'maccatalyst' 14.0 and later. | Type has [SupportedOSPlatform("maccatalyst14.0")] | Only for maccatalyst14+?
 'AVAuthorizationStatus.Authorized' is only supported on 'maccatalyst' 14.0 and later. Enum has [SupportedOSPlatform("maccatalyst14.0")], [UnsupportedOSPlatform("watchos")], [UnsupportedOSPlatform("tvos")] | Only for maccatalyst14+?
 'AVAuthorizationStatus.Denied' is only supported on 'maccatalyst' 14.0 and later. | Same as above |  Same as above | 
 'AVAuthorizationStatus.Restricted' is only supported on 'maccatalyst' 14.0 and later. | Same as above |  Same as above | 
 'SFSpeechRecognizer.AuthorizationStatus' is only supported on 'macOS/OSX' 10.15 and later. 	| Type has [SupportedOSPlatform("macos10.15")]	| Only for macos10.15+?
 'SFSpeechRecognizer.RequestAuthorization(Action<SFSpeechRecognizerAuthorizationStatus>)' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as 
 'SFSpeechRecognizerAuthorizationStatus.Authorized' is only supported on 'macOS/OSX' 10.15 and later.  | Enum has [SupportedOSPlatform("macos10.15")]	| Only for macos10.15+?
 'SFSpeechRecognizerAuthorizationStatus.Denied' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as above | 
 'SFSpeechRecognizerAuthorizationStatus.Restricted' is only supported on 'macOS/OSX' 10.15 and later. 	| Same as above |  Same as above | 
 'CLLocationManager.RequestWhenInUseAuthorization()' is only supported on 'macOS/OSX' 11.0 and later. | API has [SupportedOSPlatform("macos11.0")] | Check annotation
 'CMMotionActivityManager.AuthorizationStatus' is only supported on 'ios' 11.0 and later, 'maccatalyst' 11.0 and later. | Property & getter has [SupportedOSPlatform("ios11.0")]	| Check annotation
 'CMMotionActivityManager.AuthorizationStatus.get' is only supported on 'ios' 11.0 and later, 'maccatalyst' 11.0 and later.  | Same as above |  Same as above |		
 'CMAuthorizationStatus.Authorized' is only supported on 'ios' 11.0 and later, 'maccatalyst' 11.0 and later, 'macOS/OSX' 10.15 and later. | Enum has [SupportedOSPlatform("macos10.15")], [SupportedOSPlatform("ios11.0")] | Within a condition reachable on WatchOS | check annotation
 'CMAuthorizationStatus.Denied' is only supported on 'ios' 11.0 and later, 'maccatalyst' 11.0 and later, 'macOS/OSX' 10.15 and later.  | Same as above |  Same as above |	
 'CMAuthorizationStatus.NotDetermined' is only supported on 'ios' 11.0 and later, 'maccatalyst' 11.0 and later, 'macOS/OSX' 10.15 and later.  | Same as above |  Same as above |
 'CMAuthorizationStatus.Restricted' is only supported on 'ios' 11.0 and later, 'maccatalyst' 11.0 and later, 'macOS/OSX' 10.15 and later.  | Same as above |  Same as above |
 'CLLocationManager.RequestAlwaysAuthorization()' is only supported on 'macOS/OSX' 10.15 and later. | Method has [SupportedOSPlatform("macos10.15")] | Check for other support
 'AVSpeechSynthesizer' is only supported on 'macOS/OSX' 10.15 and later. | The type has [SupportedOSPlatform("macos10.15")]	Determine if it is supported on iOS | and take action
 'AVSpeechSynthesisVoice' is only supported on 'macOS/OSX' 10.15 and later. | Type has [SupportedOSPlatform("macos10.15")] | Check for other support
 'AVSpeechSynthesisVoice.GetSpeechVoices()' is only supported on 'macOS/OSX' 10.15 and later.  | Same as above |  Same as above |	
 'AVSpeechSynthesisVoice.Language' is only supported on 'macOS/OSX' 10.15 and later. 	 | Same as above |  Same as above |
 'AVSpeechSynthesisVoice.Name' is only supported on 'macOS/OSX' 10.15 and later.  | Same as above |  Same as above |
 'AVSpeechSynthesisVoice.Identifier' is only supported on 'macOS/OSX' 10.15 and later.  | Same as above |  Same as above |
 'AVSpeechUtterance' is only supported on 'macOS/OSX' 10.15 and later. | Type has [SupportedOSPlatform("macos10.15")] | check for other support 
 'AVSpeechUtterance.Voice' is only supported on 'macOS/OSX' 10.15 and later. 	 | Same as above |  Same as above |
 'AVSpeechUtterance.PitchMultiplier' is only supported on 'macOS/OSX' 10.15 and later. 	Type has [SupportedOSPlatform("macos10.15")]	| Same as above |  Same as above |
 'AVSpeechUtterance.Volume' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as above |
 'AVSpeechSynthesisVoice.FromLanguage(string?)' is only supported on 'macOS/OSX' 10.15 and later. | Type has [SupportedOSPlatform("macos10.15")]	| Check for other support | Add missing support
 'AVSpeechSynthesisVoice.CurrentLanguageCode' is only supported on 'macOS/OSX' 10.15 and later.  | Same as above |  Same as above |
 'AVSpeechSynthesisVoice.FromLanguage(string?)' is only supported on 'macOS/OSX' 10.15 and later.  | Same as above |  Same as above |
 'AVSpeechSynthesizer' is only supported on 'macOS/OSX' 10.15 and later. | Type has [SupportedOSPlatform("macos10.15")]	| Check for other support | Add missing support
 'AVSpeechSynthesizer.DidFinishSpeechUtterance' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as above |
 'AVSpeechSynthesizer.SpeakUtterance(AVSpeechUtterance)' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as above |
 'AVSpeechSynthesizer.DidFinishSpeechUtterance' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as above |
 'AVSpeechSynthesizer.StopSpeaking(AVSpeechBoundary)' is only supported on 'macOS/OSX' 10.15 and later. | Same as above |  Same as above |
 'CLLocation.Course' is only supported on 'tvos' 13.0 and later. | Property & getter has [SupportedOSPlatform("tvos13.0")] | If it is supported on iOS? | add corresponding attribute
 'CLLocation.Course.get' is only supported on 'tvos' 13.0 and later. | Same as above |  Same as above |	
 'CLLocation.Speed' is only supported on 'tvos' 13.0 and later. | Property & getter has [SupportedOSPlatform("tvos13.0")] | check other support | Add missing support
 'CLLocation.Speed.get' is only supported on 'tvos' 13.0 and later. | Same as above |  Same as above |

### Steps to Reproduce

1. Clone the [MAUI repo](https://github.com/dotnet/maui)
2. Remove the dotnet_diagnostic.CA1416.severity = none rule from .editorconfig and build locally to see a list of platform compatibility code analysis violations.

### Environment

MAUI repo

**Comment by buyaa-n** [comment]
According to @mattleibow  https://github.com/dotnet/maui/pull/6237#discussion_r859636420  `'NSData.Save(string, bool)' is unsupported on: 'ios' 13.0 and later` also might be wrong

![image](https://user-images.githubusercontent.com/45579687/165624852-5ac3c634-2082-4316-b06f-639ca4cdaacf.png)

**Comment by chamons** [comment]
In the latest build of https://github.com/xamarin/xamarin-macios/pull/14779 I now generate this verbose, but more correct FWICT code:

```
		[Export ("writeToFile:atomically:")]
		#if __MACOS__
		[Advice ("Starting with macos10.15 Use 'Save (NSUrl,bool)' instead.")]
		#endif
		[UnsupportedOSPlatform ("macos10.15")]
		#if __IOS__
		[Advice ("Starting with ios13.0 Use 'Save (NSUrl,bool)' instead.")]
		#endif
		[UnsupportedOSPlatform ("ios13.0")]
		#if __TVOS__
		[Advice ("Starting with tvos13.0 Use 'Save (NSUrl,bool)' instead.")]
		#endif
		[UnsupportedOSPlatform ("tvos13.0")]
		#if __MACCATALYST__ && !__IOS__
		[Advice ("Starting with maccatalyst13.0.0 Use 'Save (NSUrl,bool)' instead.")]
		#endif
		[UnsupportedOSPlatform ("maccatalyst13.0.0")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("maccatalyst")]
		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		public virtual bool Save (string path, bool atomically)
```

Thoughts?

**Comment by buyaa-n** [comment]
> Thoughts?

As the assembly already has `[assembly: SupportedOSPlatform("ios10.0")], [assembly: SupportedOSPlatform("tvos10.0")], [assembly: SupportedOSPlatform("macos10.14")], [assembly: SupportedOSPlatform("maccatalyst13.1")]` the API level `SupportedOSPlatform ("ios")], [SupportedOSPlatform ("tvos")], [SupportedOSPlatform ("macos")], [SupportedOSPlatform ("maccatalyst")] ` attributes has no effect, will be ignored as child annotation cannot extend parent support (i.e. assembly supports only ios10.0+, then API cannot support below ios10.0)

Though what I get from your reply is `'NSData.Save(string, bool)' is really unsupported from 'ios' 13.0, and we should use 'Save (NSUrl,bool)' for ios 13.0+` CC @mattleibow

**Comment by buyaa-n** [comment]
Another case: `WKWebsiteDataStore.HttpCookieStore` has `[SupportedOSPlatform("ios11.0")]` might be missing tvOS support attribute as it is being called from tvOS context

**Comment by chamons** [comment]
This should be fixed in stable now.
