### ISSUE TITLE
[native] Question: Only use `runtimes/{rid}/native` without `NativeReference`? 

### ISSUE THREAD

**Issue by KiruyaMomochi** [xamarin/xamarin-macios#14622]
> It's a question and I find it's hard to fill that issue template...

I'm currently building a native package for MacCatalyst and iOS.

For .NET 6 desktop platform like Windows/macOS desktop, I know putting native library files in `runtimes/{rid}/native` just work. **However, Xamarin.iOS docs tells me that I must use `PackNativeLibrary` item to add them**, so I add a `.target` file to my packge and it works.

I also found that [SkiaSharp.NativeAssets.MacCatalyst](https://www.nuget.org/packages/SkiaSharp.NativeAssets.MacCatalyst) **doesn't use `PackNativeLibrary`**, it only put files in `runtimes`. After testing this works well for me too.

### Now is what confusing me

Another package [SkiaSharp.NativeAssets.iOS](https://www.nuget.org/packages/SkiaSharp.NativeAssets.iOS), doesn't like the one for catalyst, includes `.targets` files for `net6.0-ios13.6` and `xamarinios1.0`. But **it also works after removing these `.targets` files**. (Tested on simulator. I don't have any real iOS device, so I don't know if the behavior is the same on a real phone.)

### The question

By checking https://github.com/xamarin/xamarin-macios/issues/11667, I believe just put these native files in `runtimes/{rid}/native` is enough, and no `NativeReference` is required. Is that correct?

**Comment by rolfbjarne** [comment]
Yes, it's correct that you can put native files (.a, .framework, .dylib) in `runtimes/{rid}/native`, and they'll be picked up automatically (in .NET 6+).

However, if you have special requirements (such as additional linker flags for when we build the main executable), then you'll need a `NativeReference`.

> However, Xamarin.iOS docs tells me that I must use `PackNativeLibrary` item to add them

Can you point us to these docs so that we can update them?

**Comment by KiruyaMomochi** [comment]
It's not mentioned directly. I followed [Working with Embedded Frameworks](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/native-references?context=xamarin/ios#working-with-embedded-frameworks) and added reference using Visual Studio for Mac, then found out what is added to `.csproj` file.

There is also an older article, [Referencing Native Libraries in Xamarin.iOS](https://docs.microsoft.com/en-us/xamarin/ios/platform/native-interop#linking-your-library), telling me to add extra arguments.

I hope we have some documentation explaining this .NET 6 feature, but I can't even find a clear documentation in .NET 6 or NuGet docs. https://github.com/NuGet/Home/issues/8623 and [a StackOverflow answer](https://stackoverflow.com/a/40652794/5509659) explains some.

**Comment by KiruyaMomochi** [comment]
Please note that `runtimes/{rid}/native` is only granted to work **as a NuGet package**. In other words, if you including `runtimes/**` in your project directly, or use a package reference, **it will not work**. 

Instead, **you must create a NuGet package** for these native libraries, then use `PackageReference` to add them.

Releated: https://github.com/dotnet/sdk/issues/16381
