### ISSUE TITLE
Binding for ScreenCaptureKit

### ISSUE THREAD

**Issue by drasticactions** [xamarin/xamarin-macios#14634]
Hey folks,

I'm looking at ways of doing screen capture for VSCX tooling, specifically for app casting on the Mac. However, as far as I can tell, [it's not bound yet](https://github.com/xamarin/xamarin-macios/blob/main/tests/xtro-sharpie/api-annotations-dotnet/macOS-ScreenCaptureKit.todo)

Is there a timeline for when we could get this bound?

**Comment by rolfbjarne** [comment]
Do you need this for Mac Catalyst, or macOS?

**Comment by chamons** [comment]
See https://github.com/xamarin/xamarin-macios/pull/14644 @dalexsoto has at least some of it done.
