### ISSUE TITLE
Path too long exception when archiving iOS app

### ISSUE THREAD

**Issue by dealdiane** [xamarin/xamarin-macios#14648]
### Steps to Reproduce

1. Open and archive an iOS app

### Expected Behavior
Archives successfully with a fully working IPA file

### Actual Behavior
Errors with "There was an error unzipping the file X:\xxxx.zip: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."
### Environment

```
Microsoft Visual Studio Community 2022
Version 17.1.3
VisualStudio.17.Release/17.1.3+32328.378
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA235
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.1.358.51495
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2012   17.1.358.51495
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   17.1.358.51495
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.1.358.51495
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.1.358.51495
Azure Functions and Web Jobs Tools

C# Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.161+abc97ecc7d.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.1.10 (65f98f5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.5.238
2.5.238

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.

Razor (ASP.NET Core)   17.0.0.2206201+62a2c1d6162f828801565a7ca26d9d48b810a05b
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62203.25080
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.1229.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.21610.4+07b5673e4f2fa7630e78abe37f16b372353a7242
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Web Compiler   1.14.7
Compiler for LESS, Sass and CoffeeScript files

Xamarin   17.1.0.324 (d17-1@590ddb7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.1.0.87 (remotes/origin/main@d50fb5635)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.1.8 (590388a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.2.0.4 (d17-1/19b97b7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a5d1934
    Java.Interop: xamarin/java.interop/d17-1@7ac33610
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.37.1@0893b3b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7


Xamarin.iOS and Xamarin.Mac SDK   15.8.0.2 (79ddd0840)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```

This only started happening after updating Visual Studio 2022 to 17.1.3. I have tried various workarounds (e.g. setting `UseShortFileNames`, `ArchivePath`, etc.) but none worked. 

I did get to the bottom of it though and it's because the file is first extracted to a temporary directory which we don't have control over. Why is that needed? Why can't it just be extracted directly to the target directory?

Screenshot of `Xamarin.iOS.Tasks.Windows.Zip::Extract`
![image](https://user-images.githubusercontent.com/3430624/161744571-0f1078fe-c6b1-4764-92d8-decfbebee0dc.png)

**Comment by chamons** [comment]
Thanks for the feedback. 

To dig into this further, a [binary build log](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2022#save-a-binary-log) is exceptionally helpful, as it allows us to see each target in detail. 

Have you tried moving your project to a directory with a shorter path?

**Comment by dealdiane** [comment]
I'm more than happy to provide the log if you can tell me the exact msbuild command format that is used when archiving an iOS app. I also have the "Build Logging" window active but it does not show the build log (I pressed the play button). I'm not sure if I'm missing something. I could see the other logs (e.g. Design Time, Roslyn, etc) though.

I personally don't think that the log will add more value but happy to supply it if you think otherwise.

The root issue here is that this line `Path.Combine(Path.GetTempPath(), "Xamarin", "Extractions", Guid.NewGuid().ToString());` in `Xamarin.iOS.Tasks.Windows.Zip::Extract` produces a very long non-overridable and non-build-parameter-dependent value so that when `ZipFile.ExtractToDirectory` is called, it throws a "long-path" exception.

Locally, this line results in a 94-character length path. This is more than a third of the total max path length already and does not give much room to play with.

In theory, this line is unnecessary. We can just extract to the target directory (`destinationPath`), can't we? And/or better yet, use a zip library that works correctly with Windows' `LongPathEnabled` setting. And if it must be kept (unzipping to a temporary directory), at least give us the ability to override this via build properties.

**Comment by aliegeni** [comment]
Have exactly the same problem with VS 17.1.3. Nothing helps. Temporary went back to v17.1.2.

**Comment by rolfbjarne** [comment]
> I'm more than happy to provide the log if you can tell me the exact msbuild command format that is used when archiving an iOS app.

If you're calling msbuild from the command line, you can get a binary log by adding the "/bl" argument (and the binary log will be written as `msbuild.binlog` in the current directory).

**Comment by dealdiane** [comment]
@rolfbjarne I'm not but I'm pretty sure that running msbuild from command line will result in the same error. After all, archiving from Visual Studio just invokes the build process anyway. The previous post suggests that I try msbuild to get the binlog hence my reply. The other way that I know of is through Visual Studio through the "Build Logging" window but that does not give me anything useful at all.

Regardless, I have pin-pointed the exact issue so I doubt the binlog will add anything fruitful.

@aliegeni If you have to be in 17.1.3, I figured that this is the last step? anyway so you could just unzip the file manually yourself.

**Comment by rolfbjarne** [comment]
> The previous post suggests that I try msbuild to get the binlog hence my reply.

Something like this should work: https://stackoverflow.com/a/65049594/183422

**Comment by DuncWatts** [comment]
I've started getting similar when just trying to debug my project, using Visual Studio 17.2.0 Preview 2.1

1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(2068,3): error : PathTooLongException: The path '/Users/xxx/Library/Caches/Xamarin/mtbs/builds/xxx/e7bc91fb1a2dc4f862cfbfd84d91f25ea3635e74f385948e0db17d46af6b7fa9/obj\iPhone\Debug\device-builds\iphone8.1-15.2.1/codesign\\bin\iPhone\Debug\device-builds\iphone8.1-15.2.1\xxx\\Frameworks\ScanditBarcodeCapture.framework\ScanditBarcodeCapture.Substring(bin\iPhone\Debug\device-builds\iphone8.1-15.2.1\xxx\\Frameworks\ScanditBarcodeCapture.framework\ScanditBarcodeCapture.LastIndexOf('.app' is too long, or a component of the specified path is too long.

**Comment by jpacione** [comment]
I have the same issue.  any way around it that you have found, other than downgrading?

**Comment by dealdiane** [comment]
@jpacione you can just ignore the error and unzip the file yourself. I personally have created a custom task that extracts it to the destination directory without the need for a temporary directory and replaced Xamarin's one with that.

**Comment by JORGEGO** [comment]
> @jpacione you can just ignore the error and unzip the file yourself. I personally have created a custom task that extracts it to the destination directory without the need for a temporary directory and replaced Xamarin's one with that.

How did you do it? Could you share the steps? Thanks

**Comment by JORGEGO** [comment]
Found, I have extracted the files and it already appears in the file view and I can now deploy
