### ISSUE TITLE
Microsoft.iOS is using variable `AssemblyVersion`, causing build issues between versions

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#14718]
### Steps to Reproduce

1. Build a library with Preview 14, which uses any of the `UIKit` types
2. Build an app RC1, which uses the library built on Preview 14

### Expected Behavior

The build finishes properly.

### Actual Behavior

```
Error CS1705 Assembly 'Uno.UI' with identity 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' 
uses 'Microsoft.iOS, Version=15.2.303.55, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=15.2.302.122, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
```

Notice that the version `15.2.303.55` and `15.2.302.122` are very close but not quite the same, causing the compiler to complain.

It would be useful, for build reliability, that the version number be fixed to something that will not cause build issues between builds of the SDK, similar to the way Xamarin.iOS was versioned (0.0.0.0).

### Environment

Preview 14 and RC1.

### Example Project (If Possible)

Repro steps need to be used to create the scenario.

**Comment by spouliot** [comment]
I can't find it (might not be public) but I recall that @rolfbjarne has written a document about versions for net6+.

From memory, if the _band_ (build / 3rd item) changes (like `302` to `303`) then extra API are present and it's not safe to assume you can build with `303` and run with `302`. 

> It would be useful, for build reliability, that the version number be fixed to something that will not cause build issues between builds of the SDK, 

The theory is that net6 will make it a lot easier to have several versions to coexists and you can build against an older version to ensure your binaries will work with all future bands/versions.

OTOH the revision (4th item) should not be used to detect API compatibility.

> similar to the way Xamarin.iOS was versioned (0.0.0.0).

Over the years many people disliked/complained over that approach :-|

**Comment by dalexsoto** [comment]
Yes, this was addressed here https://github.com/xamarin/xamarin-macios/commit/92ee92eeb57f470eea28a2119f7d329be6a24030 and it is still pending release, we will use the first 3 digits.
