### ISSUE TITLE
Why don't we have async navigation methods in UINavigationController?

### ISSUE THREAD

**Issue by petro2050** [xamarin/xamarin-macios#14733]
In `UIViewController`, we have `PresentViewControllerAsync`, but there are no async methods for push, pop, pop to root, and pop to view operations in `UINavigationController`. I'd like to know why Xamarin decided not to add async methods for these.

**Comment by mandel-macaque** [comment]
The PresentViewController and PresentViewControllerAsync methods are wrappers around the selector "presentViewController:animated:completion:" which has a completion handler, meaning that the method is async. 

On the other hand the methods you refer do not have an async API from apple, but a sync one like https://developer.apple.com/documentation/uikit/uinavigationcontroller/1621886-popviewcontrolleranimated?language=objc which makes it impossible for us to provide an async API.

This is a limitation imposed by the Apple API.
