### ISSUE TITLE
[Bug] iOS 15.4 Crash on CollectionView with Grouping

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/xamarin-macios#14804]
This issue was first reported on Xamarin forms github page but as this is an iOS only issue I'm reposting here:
https://github.com/xamarin/Xamarin.Forms/issues/15230

Having a CollectionView with IsGrouped=True and the GroupHeaderTemplate with a Box that changes its visibility depending a condition (basically something that alters the height of the header dynamically thus resulting on non-fixed height for all headers) results in a crash when appearing or sometimes when scrolling.

Exception:

```csharp
SIGABRT: UICollectionView (<UICollectionView 0x1047ff200>) is stuck in its update/layout loop. This can happen for many reasons, including self-sizing views whose preferred attributes are not returning a consistent size. To debug this issue, check the Console app for logs in the "UICollectionViewRecursion"
```

**Steps to Reproduce**
Create a CollectionView with IsGrouped=True and add the GroupHeaderTemplate with a Box that has a visibility binding with some logic that, e.g. changes if it's the first item
Add two other templates for the items
Do NOT set any hardcoded values for the Height (setting a fixed HeightRequest seems to fix the issue)
Run the app and scroll the collection
It crashes.

**Expected Behavior**
The app should not crash

**Actual Behavior**
The app crashes

**Workaround**
Workaround 1:

Set a fixed height to every cell / GroupHeaderTemplate

Workaround 2:
Set on CollectionView -> ItemSizeStrategy to MeasureFirstItem

Workaround 3:
Remove any thing that can cause a dynamic change of height on the GroupHeaderTemplate like the visibility binding.

Workaround 4:
Remove the grouping and make a plain items collection

**SAMPLE**

[XamApp.-.Copy.zip](https://github.com/xamarin/xamarin-macios/files/8536347/XamApp.-.Copy.zip)

**Comment by chamons** [comment]
As CollectionView is a Xamarin.Forms type, this is a Forms bug unless otherwise proven. Given that folks are looking into it in https://github.com/xamarin/Xamarin.Forms/issues/15230 I am going to close this until someone from that team reaches out.
