### ISSUE TITLE
NET Attribute Conversion] Generator PR cleanup

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#14802]
This is the follow up work required after https://github.com/xamarin/xamarin-macios/pull/14779 lands

- [x] Remove and fix introspection tests disabled in the PR (search for "14802" in code).
    - #17421.
- [x] Cleanup attributes in src/AudioUnit/AUEnums.cs [here](https://github.com/xamarin/xamarin-macios/pull/14779#discussion_r853851373)
    - https://github.com/xamarin/xamarin-macios/pull/17267
- [ ] Limitations/Bugs in the generator to consider fixing (Remove cases in IgnoreElementsThatDoNotExistInThatAssembly if fixed):
    -  [x] Major: Protocols with one set of attributes [TV (9,0)] inlined in types that differ [NoTV] currently unconditionally use the attributes from the protocol, which is wrong. This has always been wrong, but never noticed given how few of them we generated in legacy due to the de-duplication logic and lack of tests. This was deemed too difficult to fix in time since the calls to GetPlatformAttributesToPrint did not pass the "target" type, and I'd have to do wider surgery to wire it through: https://github.com/xamarin/xamarin-macios/issues/17268, https://github.com/xamarin/xamarin-macios/pull/17381
        - https://github.com/xamarin/xamarin-macios/issues/14905
    -  [x] Major: Obsolete attributes prevent the "implied introduced" attribute from being created, causing some enums to not generate correct attributes.
    - [ ] PrintPlatformAttributes and GetPlatformAttributesToPrint have a soup of params and unnecessary attribute generation. One major problem is that PrintPlatformAttributes is invoked in many context:
        - For Methods/Props
        - For Enums
        - For inlined protocol items
        - For classes
        - Likely for other things I forgot
and knowing when we should be use what type as a parent context is a mess. I papered over it mostly in the first PR, but in some cases I guessed wrong and generated a lot of attributes that are correct but could be skipped.

**Comment by rolfbjarne** [comment]
@chamons should we postpone this to .NET 7?

**Comment by rolfbjarne** [comment]
I believe all the bugs have been fixed now, so I'm closing this.
