### ISSUE TITLE
[dotnet] ILStrip fails when building F# projects from Windows

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#14841]
Repro project: [fsharp.zip](https://github.com/xamarin/xamarin-macios/files/8584663/fsharp.zip)

Build:

    dotnet build dotnet/iOS/.fsproj -bl -p:RuntimeIdentifier=ios-arm64 -p:Configuration=Release -p:UseLlvm=true

Binlog: [msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/8584654/msbuild.binlog.zip)

    "C:\Users\rolf\source\fsharp\dotnet\iOS\fsharp.fsproj" (default target) (1:7) ->
    (_StripAssemblyIL target) ->
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/ko/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/ko/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/tr/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/tr/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/zh-Hant/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/zh-Hant/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/it/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/it/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/es/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/es/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/pt-BR/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/pt-BR/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/cs/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/cs/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/ru/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/ru/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/zh-Hans/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/zh-Hans/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/pl/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/pl/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/ja/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/ja/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/fr/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/fr/FSharp.Core.resources.dll' not found.
      C:\...\targets\Xamarin.Shared.Sdk.targets(739,3): error : ILStrip failed for C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/de/FSharp.Core.resources.dll: File '/Users/rolf/Library/Caches/Xamarin/mtbs/builds/fsharp/0a37d198e93da924afce6d66d7832fe80a3eb34fcfd38a4c15ff33390117d5a8/C:/Users/rolf/.nuget/packages/fsharp.core/6.0.4-beta.22178.3/lib/netstandard2.1/de/FSharp.Core.resources.dll' not found.

Workaround:

```xml
<PropertyGroup>
    <EnableAssemblyILStripping>false</EnableAssemblyILStripping>
</PropertyGroup>
```

**Comment by BioTurboNick** [comment]
Seems to be the same issue as https://github.com/dotnet/maui/issues/12296

So all localized iOS projects are blocked?

**Comment by rolfbjarne** [comment]
> So all localized iOS projects are blocked?

Yes, that might be the case.

We'll fix this for .NET 8 (and potentially a .NET 7 service release, depending on when it's fixed and the actual fix).

**Comment by divil5000** [comment]
We are blocked by this issue too, aside from the workaround. We have just ported from Xamarin to .net iOS (no forms/maui) and simply could not get release builds on a device to have all their resources left intact by the build process. Rolf's workaround to disable assembly IL stripping works, but this seems like a fairly major issue.

Are all projects that use localisation broken on netX.0-ios?
