### ISSUE TITLE
AOT compilation fails if the project directory contains a colon

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#14904]
Repro:

* Create a test project in a directory with a colon in it. Say ~/Projects/Colon/Test:App/
* Build it like this:

    msbuild Test:App/*.csproj /p:Platform=iPhone /r /bl /v:diag /p:ImportProjectExtensionProps=false /p:ImportProjectExtensionTargets=false

* Fails like this:

        MONO_PATH=/Users/rolf/Projects/Colon/Test:App/test-app/obj/iPhone/Debug/mtouch-cache/3-Build /Users/rolf/work/maccore/squashed-onedotnet/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=float32 --aot=mtriple=arm64-ios,data-outfile=/Users/rolf/Projects/Colon/Test:App/test-app/obj/iPhone/Debug/mtouch-cache/arm64/System.Core.aotdata.arm64,static,asmonly,direct-icalls,full,readonly-value=ObjCRuntime.Runtime.Arch=i4/0,dwarfdebug,no-direct-calls,direct-pinvoke,outfile=/Users/rolf/Projects/Colon/Test:App/test-app/obj/iPhone/Debug/mtouch-cache/arm64/System.Core.dll.s /Users/rolf/Projects/Colon/Test:App/test-app/obj/iPhone/Debug/mtouch-cache/3-Build/System.Core.dll
        '/Users/rolf/Projects/Colon/Test' in MONO_PATH doesn't exist or has wrong permissions.
        '/Users/rolf/Projects/Colon/Test:App/test-app/App/test-app/obj/iPhone/Debug/mtouch-cache/3-Build' in MONO_PATH doesn't exist or has wrong permissions.
        The assembly mscorlib.dll was not found or could not be loaded.
        It should have been installed in the `/Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/sdks/out/ios-cross64-release/lib/mono/4.5/mscorlib.dll' directory.
        AOT Compilation exited with code 1, command:

The reason is that MONO_PATH can be multiple paths, separated by colon, and there doesn't seem to be a way to escape the colon.

Ideas to fix:

* Figure out a way to pass MONO_PATH with colons (runtime fix).
* Maybe it could work if we changed the current directory to the desired path and not set MONO_PATH?

Mitigation if we wish to:

* Detect colons in the desired path, and show a better error (something like "AOT compilation is not supported for directories with colons").

Other notes:

* This happens if OutputPath or IntermediateOutputPath is set to a full path on Windows.
    * Ref: https://github.com/xamarin/xamarin-macios/issues/8352
    * Ref: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1525191

Binlog: [msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/8629257/msbuild.binlog.zip)

**Comment by huangjinshe** [comment]
Don't forget that: not only colon, It can't use the absolute output path(Windows) like:
```
<OutputPath>bin\iPhone\Debug\</OutputPath>
to
<OutputPath>G:\App1\App1\App1.iOS\bin\iPhone\Debug\</OutputPath>
```

**Comment by rolfbjarne** [comment]
@huangjinshe the reason that doesn't currently work is because of the colon in the absolute windows path.

**Comment by rolfbjarne** [comment]
This will become more important, because IntermediateOutputPath will be an absolute path by default when using the new artifacts path (which happens if there's a Directory.Build.props file somewhere).

**Comment by rolfbjarne** [comment]
Filed an issue for the AOT compiler: https://github.com/dotnet/runtime/issues/90422

**Comment by rolfbjarne** [comment]
This will be fixed in .NET 8.
