### ISSUE TITLE
.NET: warning : The file '~/.nuget/packages/fsharp.core/6.0.0/contentFiles/any/netstandard2.1/FSharp.Core.xml' does not specify a 'PublishFolderType' metadata, and a default value could not be calculated. The file will not be copied to the app bundle.

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#14939]
Repro:

* Build monotouch-test for macOS:

        cd tests/monotouch-test/dotnet/macOS
        make build
        ...
        [...]/xamarin-macios/builds/downloads/dotnet-sdk-6.0.301-[...]/packs/Microsoft.macOS.Sdk/12.3.0[...]/targets/Xamarin.Shared.Sdk.targets(1439,3): warning : The file '[...]/xamarin-macios/tests/dotnet/packages/fsharp.core/6.0.0/contentFiles/any/netstandard2.1/FSharp.Core.xml' does not specify a 'PublishFolderType' metadata, and a default value could not be calculated. The file will not be copied to the app bundle. [[...]/xamarin-macios/tests/monotouch-test/dotnet/macOS/monotouch-test.csproj]

Binlog: [build-2022-05-09-145149.binlog.zip](https://github.com/xamarin/xamarin-macios/files/8651906/build-2022-05-09-145149.binlog.zip)

The reason is that the FSharp.Core NuGet does this in its nuspec:

```xml
<contentFiles>
  <files include="**/FSharp.Core.xml" buildAction="None" copyToOutput="true" flatten="true" />
</contentFiles>
```

which seems to come from here: https://github.com/dotnet/fsharp/pull/10579 ("Following this change, build and publish will deploy the FSharp.Core.xml doc comment file to the output directory, without the build author having to do any extra work.")

It seems this could be a workaround (untested, from https://github.com/dotnet/fsharp/issues/11143#issuecomment-785571720)

```xml
<ItemGroup>
    <PackageReference Update="FSharp.Core" Version="5.0.1">
        <ExcludeAssets>contentFiles</ExcludeAssets>
    </PackageReference>
</ItemGroup>
```

An alternative solution would be to amend our logic that figures out what to do with files in ResolvedFileToPublish (https://github.com/xamarin/xamarin-macios/blob/main/dotnet/BundleContents.md), to say something like: "If an xml file matches the filename of any assembly, then treat that xml file as `PublishFolderType=Assembly`" - so FSharp.Core.xml would be placed next to FSharp.Core.dll (and no warning produced). The downside is that the app would ship a file it doesn't need.

See also https://github.com/xamarin/xamarin-macios/issues/15897#issuecomment-1240412823.

**Comment by mattjohnsonpint** [comment]
FYI, I have a slightly different issue with the same symptom, and was able to work around it.  See https://github.com/dotnet/maui/issues/7272#issuecomment-1136517167

**Comment by jwosty** [comment]
Potentially related to https://github.com/fsprojects/Paket/issues/4149
