### ISSUE TITLE
Missing attribute in class with <MtouchDebug>false</MtouchDebug>

### ISSUE THREAD

**Issue by entdark** [xamarin/xamarin-macios#14938]
### Steps to Reproduce

1. Check issues: https://github.com/MvvmCross/MvvmCross/issues/4364 and https://github.com/MvvmCross/MvvmCross/issues/4347#issuecomment-1118560630
there are some technical information about my hardware and reports from other users.
2. Try to build this project in `Release | iPhone` configuration with Xamarin.iOS 15 and deploy to a real device: https://github.com/entdark/JKChat/tree/mvvmcross_8.0.2
3. The app crashes (in other scenarios the app get stuck on the splash screen).
4. In the project `JKChat.iOS` into `Setup.cs` add the following:
```
public override void LoadPlugins(IMvxPluginManager pluginManager)
{
	System.Console.WriteLine("MvxPluginAttribute is defined for Messenger.Plugin: " + (System.Attribute.IsDefined(typeof(MvvmCross.Plugin.Messenger.Plugin), typeof(MvvmCross.Plugin.MvxPluginAttribute))));
	base.LoadPlugins(pluginManager);
}
```
5. Start Console app on Mac.
6. Start streaming logs for the device you will deploy to.
7. Build in `Release | iPhone` configuration and deploy to the device.
8. The app should crash.
9. Check logs in Console app and it should print "MvxPluginAttribute is defined for Messenger.Plugin: False".
10. Change `<MtouchDebug>true</MtouchDebug>` for the configuration `Release | iPhone`.
11. Repeat steps 7-9: the app won't crash and "MvxPluginAttribute is defined for Messenger.Plugin: True".

### Personal comment

After a lot of debugging I found out that the issue related to the fact that it cannot find `MvvmCross.Plugin.MvxPluginAttribute` for the class `MvvmCross.Plugin.Messenger.Plugin`. It is needed to create an instance of the class `MvvmCross.Plugin.Messenger.Plugin`.

It happens so because it seeks for all classes that have the attribute `MvvmCross.Plugin.MvxPluginAttribute` but it doesn't find any attribute for the class `MvvmCross.Plugin.Messenger.Plugin` when building in `Release | iPhone`, and to be more precise with `<MtouchDebug>false</MtouchDebug>`.

**It finds the attribute successfully if we set `<MtouchDebug>true</MtouchDebug>`.**

Creating an instance of `MvvmCross.Plugin.Messenger.Plugin` manually goes fine without issues. So the problem is in the automatic instance creation based on existence of `MvvmCross.Plugin.MvxPluginAttribute` above all the referenced classes.

The code that checks the existing attributes: https://github.com/MvvmCross/MvvmCross/blob/c67b77313c8d8b1f9901c56e881c1f8ae1620eed/MvvmCross/Core/MvxSetup.cs#L439
The attribute existence: https://github.com/MvvmCross/MvvmCross/blob/c67b77313c8d8b1f9901c56e881c1f8ae1620eed/MvvmCross.Plugins/Messenger/Plugin.cs#L8

I also tried other ways to check the attribute existence with `System.Attribute.IsDefined` or `System.Attribute.GetCustomAttribute` but they also failed with `<MtouchDebug>false</MtouchDebug>`.

This happens in the current version of MvvmCross 8.0.2.
The same code worked with MvvmCross 7.1.2 without issues.
So I think it's related to Xamarin.iOS version that it was compiled with.

### Expected Behavior
The app gets launched without crashes or freezes in the splash screen.

### Actual Behavior
The app gets crashed or stuck in the splash screen.

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.14 (build 17)
Installation UUID: 93972a0d-f79e-4945-b0ce-5b27fd4a64cf
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: Not installed
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: Not installed

=== .NET Core 3.1 SDK ===

SDK: Not installed

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Not Installed

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Apple Developer Tools ===

Xcode 13.1 (19466)
Build 13A1030d

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 15.2.0.17 (Visual Studio Community)
Hash: 738fde344
Branch: xcode13.1
Build date: 2021-11-09 02:45:16-0500

=== Xamarin Designer ===

Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 21:09:18 UTC

=== Build Information ===

Release ID: 810140017
Git revision: 6f93cf55df3b7747288286e2006057c7f088b838
Build date: 2021-11-12 09:50:18-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 11.3.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Fri Mar  5 01:14:14 PST 2021
    root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

SolutionCleaner 1.1
```

### Build Logs

https://gist.github.com/entdark/0820872ad8660fa210b64ec74b495a69

### Example Project (If Possible)

https://github.com/entdark/JKChat/tree/mvvmcross_8.0.2 (mentioned in reproduction steps)

**Comment by entdark** [comment]
According to this comment https://github.com/MvvmCross/MvvmCross/issues/4347#issuecomment-1087371151 it got reproduced in WPF .NET 5. Though they did not mention if it's related to the missing attribute but is is most likely so. So the issue maybe not related to Xamarin.iOS unless it uses something similar to .NET 5.

**Comment by entdark** [comment]
> Given that fact that it reproduces on WPF strongly to me suggested a bug in MvvmCross or a dependency. Is there a specific reason you believe this to be a Xamarin bug?

The fact that the attribute existence depends on a Xamarin.iOS specific flag which is `MtouchDebug`. I think I explained everything pretty detailed in the first post.

**Comment by chamons** [comment]
Can you explain this assertion:

>  But that is a bug somewhere in compiler/runtime for sure and has to be fixed.

From my perspective, this could realistically be a bug in one of four layers (lowest to highest):

- The user application (your test case)
- The library in question (MvvmCross)
- Packaging/SDK (xamarin.ios)
- The runtime (mono)

And in general, the further down you go in that stack, the more evidence you need to show it's not specific to your application/library, and the stronger any counter evidence that it isn't specific to that platform is.

Given the fact that others have seen it on WPF, **which does not share the runtime nor the packaging SDK**, I do not believe it is a reasonable assertion to claim that it obviously must be an SDK/runtime bug. 

If I did not have a data point saying it failed on WPF, then sure it would be reasonable to take a look (ignoring the discussions of race condition on the library level being discussed on that issue). However, right now, there is data that suggests that its a cross platform bug that belongs in MvvmCross, and no data that suggests that it belongs as a platform/runtime bug.

If there is something I am missing from reading this issue and https://github.com/MvvmCross/MvvmCross/issues/4347, please let me know.

**Comment by entdark** [comment]
> Can you explain this assertion:
> 
> > But that is a bug somewhere in compiler/runtime for sure and has to be fixed.

I think you should avoid looking at it as some library issue. The issue is the attribute is missing with certain conditions that affected by Xamarin.iOS specific. That is confirmed by at least 2 of my projects: I shared one of them, the 2nd is my company closed source one.
The right issue to look at is https://github.com/MvvmCross/MvvmCross/issues/4364 which is mine.
The WPF issue did not confirm it's related to the attribute - that is very important key here because then it's unrelated to this issue (https://github.com/xamarin/xamarin-macios/issues/14938) at all. Relation to WPF was just a hypothesis by me, not a confirmation. It's other user's issue. **And I am trying to fix the missing attribute issue.**
I am not trying to solve here an ability to run an app with MvvmCross for your information. I am trying to solve here the missing attribute issue. That is main key difference.

Please, look at this issue again (https://github.com/xamarin/xamarin-macios/issues/14938), and abstract from MvvmCross.
There is an attribute: https://github.com/MvvmCross/MvvmCross/blob/c67b77313c8d8b1f9901c56e881c1f8ae1620eed/MvvmCross.Plugins/Messenger/Plugin.cs#L8
Its existence hasn't changed since 2 last major versions.

Let's try "proof by contradiction" logic then.
Imagine you don't know it's related to MvvmCross. **And try to explain how would an attribute disappear from a class in general?** That is the main question.
**Okay, if you are telling it's a bug in MvvmCross then what kind of bug is that that removes the attribute?** I have no explanations, do you?
But actually it doesn't remove since ILSpy shows it's there; `<MtouchDebug>true</MtouchDebug>` shows it's there. But only `<MtouchDebug>false</MtouchDebug>` prevents having it there. So giving all that we can conclude that Xamarin.iOS specific compiling rules affect the existence of the attribute.

I could be wrong it's related to Xamarin.iOS but currently it's the only way to localize the issue at least.

**Comment by chamons** [comment]
Alright, assuming that it really is a linker optimization issue and not MvvMCross, then let's validate that 
by using the [XML custom linker configuration](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker) to explicit state what linking you want on that type.
