### ISSUE TITLE
interpreter->aot call cause crash on ios

### ISSUE THREAD

**Issue by gemSender** [xamarin/xamarin-macios#14930]
### Description

mono's hybird mode crash on ios

### Reproduction Steps

Run with mono's hybrid mode(MONO_AOT_MODE_INTERP), some assemblies are compiled with aot (parameters --aot=interp, full, ... have been added for all aot modules), when the interpreted assembly calls this aot-compiled method
![image](https://user-images.githubusercontent.com/6006458/166637712-fdba1d9f-1578-447d-856e-c9c214689b70.png)

, mono crashes, and The following logs are output:
![image](https://user-images.githubusercontent.com/6006458/166637546-0d87f012-1cc6-4fce-9b36-dfbb7558da54.png)

And when I add some unused parameters to this method, it didn't crash anymore
![image](https://user-images.githubusercontent.com/6006458/166638630-15b0a181-5517-4f8a-8cda-7a340a977c77.png)

### Expected behavior

should not crash

## Stacktrace
![image](https://user-images.githubusercontent.com/6006458/166641294-db08ff04-d506-4b31-a3b1-209948d6715f.png)

### Known Workarounds
Mono, Interp, Aot

### Configuration

runtime version: mono 12.0
platform: ios 14.2

**Comment by chamons** [comment]
Thank you for your feedback!

This looks like a limitation in either the interpreter or aot compiler.

For us to investigate this further, could you please provide a test case (to reproduce). 

We look forward to hearing from you!
