### ISSUE TITLE
Broadcast Extension Not debuggable

### ISSUE THREAD

**Issue by amrkamal1993** [xamarin/xamarin-macios#14933]
https://1drv.ms/u/s!AiLsd2NKfovHnPxRAVxfkoppzqLf0A

Sample code link above, Thanks.

_Originally posted by @jingliancui in https://github.com/xamarin/xamarin-macios/issues/11132#issuecomment-814917627_

**Comment by chamons** [comment]
![image](https://user-images.githubusercontent.com/6392201/167883116-1de50fb2-b871-43dd-8115-237f0c773394.png)

Please create a new issue, fill out the issue template, and validate your link works in a different browser that is not signed into your account, as this is not the first time we've had trouble accessing a sample project.
