### ISSUE TITLE
[net7] Microsoft.macOS.Bundle creates sdk-manifest/7.0.100-preview4 folder

### ISSUE THREAD

**Issue by mrward** [xamarin/xamarin-macios#14940]
### Steps to Reproduce

1. Download and install dotnet pkg used by latest commit from the net7 branch.
  i. https://dotnetbuilds.azureedge.net/public/Sdk/7.0.100-preview.4.22201.11/dotnet-sdk-7.0.100-preview.4.22201.11-osx-x64.pkg
  ii. [net6 documentation page](https://github.com/xamarin/xamarin-macios/wiki/.NET-6) says the url is of the format 'https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.100-&lt;version&gt;/dotnet-sdk-7.0.100-&lt;version&gt;-osx-x64.pkg' and this does not seem to be the case. Switched to dotnetbuilds and change the path to use Public instead of dotnet (this was based on the url from the dotnet/installer page)
3. Download and install latest macOS bundle from the net7 branch.
 i. https://bosstoragemirror.blob.core.windows.net/wrench/net7.0/86b14a77a24f7e26952d73ff43b33090f92722b6/6113471/package/Microsoft.macOS.Bundle.12.3.400-ci.net7-0.112.pkg 

### Expected Behavior

macos workload installed.

### Actual Behavior

macos workload sdk-manifest is installed into a 7.0.100-preview4 folder instead of the 7.0.100 folder which prevents dotnet workload from finding it.

![image](https://user-images.githubusercontent.com/372361/167418531-ae13b8ee-4dea-4199-9c26-96facceaa3aa.png)

### Environment

macOS 11.6.5

**Comment by rolfbjarne** [comment]
More info here: https://github.com/dotnet/sdk/pull/22446#issuecomment-959742472

**Comment by mrward** [comment]
I think this may be a bug in the .NET 7 pkg installer then.

The .NET 7 pkg installer that I have used (p3, p4 and alpha) all create an sdk-manifests/7.0.100 folder.

Debugging the dotnet workload code from the dotnet/sdk main branch and it looks for sdk manifests in a sdk-manifests/7.0.100-preview.4 folder when the sdk version is passed to dotnet workload install. This matches the design doc linked to.

**Comment by mrward** [comment]
Looks like there is a fallback. For known workloads (those defined in /usr/local/share/dotnet/sdk/7.0.100-preview.4.22201.11/IncludedWorkloadManifests.txt) the sdk-manifests/7.0.100 directory is tried as a fallback if the workload is not found in the sdk-manifests/7.0.100-preview.4 directory.

https://github.com/dotnet/sdk/blob/73a82165ed76e5c07c131f1a7b41c9b313f9c367/src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs#L145
