### ISSUE TITLE
Ability to see "AL.exe" error log

### ISSUE THREAD

**Issue by snorrk** [xamarin/xamarin-macios#14999]
Uploading archived iOS apps (.ipa) is done through the AL.exe tool on the Mac, which will do additional validation before uploading the IPA file to the Apple AppStore.

Those checks can fail for various reasons (e.g., not including the correct icon sizes in the bundle) but if they do the only error message shown in Visual Studio is "AL.exe exited with code 1", with no further explanation of what went wrong.

A quick web search will give the steps to either run the AL.exe tool manually or to use the Transporter app on the Mac to get the failure log, which includes a description of the issue.

It would be nice if that log would be available directly in Visual Studio.

---

Microsoft Visual Studio Enterprise 2022
Version 17.1.5
VisualStudio.17.Release/17.1.5+32414.318
Microsoft .NET Framework
Version 4.8.04161

**Comment by chamons** [comment]
Thanks for the feedback. 

I took a look at the msbuild task that I believe is invoked, and it looks like we are trying to output the errors reported:

https://github.com/xamarin/xamarin-macios/blob/45b5379d432d116468da59eb131bfbcab7a90c57/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/AlToolTaskBase.cs#L101-L122

I could imagine a few things being wrong:

- Apple could have changed the format of the output from altool and we're no longer getting the output we expect.
- Somehow the build host -> VS connection could be dropping the log on the floor. 
- A bug in our parsing logic itself

Could you please post a full build log, so I can take a look?
