### ISSUE TITLE
Mismatch between Xamarin.iOS SDK versions in VS and VSfM

### ISSUE THREAD

**Issue by ceasor** [xamarin/xamarin-macios#15035]
### Steps to Reproduce

1. install visual studio for mac community 8.10.22(build 11)
2. update visual studio 2019 to Microsoft Visual Studio Enterprise 2019
Version 16.11.14
3. connect to mac and get following message:
The Xamarin.iOS SDK version '15.8.0.3' that is installed on the Mac is not compatible with this version of Visual Studio. Would you like us to install Xamarin.iOS '15.2.0.17' for you? This will overwrite any other existing Xamarin.iOS installation on your Mac.

### Expected Behavior
I think the version should be same for both latest version

### Actual Behavior

latest version of visual studio 2019 doesn't carry the correct version Xamarin.iOS SDK.

What shall I do now? Ignore the error message or update mac with 15.2.0.17 xamarin.iOS? By the way when the visual studio 2019 will carry new Xamarin.iOS SDK?

**Comment by chamons** [comment]
So the version of Visual Studio you are running, "Microsoft Visual Studio Enterprise 2019", is outside of the supported platforms as noted [here](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin).

> Two years after initial release Or until a newer subsequent Current release

Please update to Visual Studio newer than 2019 to resolve this issue.
