### ISSUE TITLE
OpenGL doesn’t work on Mac Catalyst

### ISSUE THREAD

**Issue by praeclarum** [xamarin/xamarin-macios#15083]
For some reason, the OpenGL libraries are missing from MacCatalyst. They work fine on iOS.

I realize that Apple marked them as deprecated some years ago, they are still heavily used. Please make Mac Cat work like iOS and stop removing things.

This is affecting SkiSharp: https://github.com/mono/SkiaSharp/issues/2050

This is preventing me from porting *all* of my apps to .NET 6 - they all use OpenGL. 

### Steps to Reproduce

1. Port your OpenGL app to Mac Cat

### Expected Behavior

APIs that have existed since 2008 work.

### Actual Behavior

Tragedy.

### Environment

<details>
<summary>Version information</summary>
```
```
</details>

**Comment by rolfbjarne** [comment]
According to Apple's documentation, neither the OpenGLES nor the GLKit frameworks are available on Mac Catalyst:

* https://developer.apple.com/documentation/glkit?language=objc
* https://developer.apple.com/documentation/opengles?language=objc

Are there any other OpenGL-related frameworks that are?

**Comment by praeclarum** [comment]
@rolfbjarne OK weird. I think their dynamic linker must be forgiving or something because I had code using OpenGL just fine. But I will conceded to the docs. Thank you.
