### ISSUE TITLE
Building legacy iOS projects fails with latest Mono and .NET 6.0.300 SDK

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#15124]
### Steps to Reproduce

1. Get a .NET 6.0.300 SDK installed on a clean macOS machine along with legacy Mono SDKs (installed through VS4Mac for example)
2. Try to build legacy Xamarin.iOS app with `ProjectReference` to a `netstandard2.1;net6.0-macos` project.

### Expected Behavior

Build succeeds.

### Actual Behavior

```
"/Users/filipnavara/Projects/emclient-temp/MailClient.Mobile/MailClient.Mobile.iOS/MailClient.Mobile.iOS.csproj" (Restore target) (1) ->
(Restore target) -> 
  /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error : Invalid framework identifier ''. [/Users/filipnavara/Projects/emclient-temp/MailClient.Mobile/MailClient.Mobile.iOS/MailClient.Mobile.iOS.csproj]
```

### Environment

Mono 6.12.0.174 (particular version didn't seem to matter)
.NET SDK 6.0.300

NOTE: It works if any older SDK band, such as 6.0.203, is installed on the machine. It works even when both 6.0.203 and 6.0.300 are present. The failure happens only when 6.0.300 is the only SDK band installed.

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/8773580/msbuild.binlog.zip)

**Comment by filipnavara** [comment]
I'm still trying to reduce it to simple failing project, will post it here if I succeed.

**Comment by filipnavara** [comment]
cc @dsplaisted ... seems more like SDK and/or NuGet bug, to be honest. Did something change significantly for the 6.0.300 band?

**Comment by rolfbjarne** [comment]
I agree, this doesn't look like a bug in xamarin-macios.

I'm not sure where it should be moved to though, maybe dotnet/sdk?

**Comment by filipnavara** [comment]
> I'm not sure where it should be moved to though, maybe dotnet/sdk?

That's the difficult part. It could either be mono/mono because of the unusual interaction of the packaged old version of MSBuild, or dotnet/sdk. I'm leaning towards dotnet/sdk since part of the problem is the workload logic not triggering properly and resulting in unknown TFMs. The other part is the totally useless error message.

**Comment by rolfbjarne** [comment]
This issue was moved to dotnet/sdk#25651
