### ISSUE TITLE
[net6] Poor performance for macOS running on CoreCLR

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#15145]
### Steps to Reproduce

1. Run this [Xamarin.Mac sample](https://github.com/unoplatform/performance/tree/master/src/dopes/Uno-WinUI/DopeTestUno/DopeTestUno.macOS)
2. Run this [net6.0-macios sample](https://github.com/unoplatform/performance/tree/master/src/dopes/Uno-dotnet6/DopeTestUno/DopeTestUno.Mobile)
3. Compare the numbers

### Expected Behavior

Same or better performance from CoreCLR (versus Xamarin.Mac legacy running on Mono)

### Actual Behavior

Up to 4 times slower running on CoreCLR.

This is likely similar to https://github.com/unoplatform/uno/issues/8890 but the workaround (to disable ObjC exception marshalling) is not possible on CoreCLR.

### Environment

* Xamarin.Mac

```
Xamarin.Mac
Version: 8.11.0.288 (Visual Studio Community)
Hash: 5946727d0
Branch: main
Build date: 2022-05-23 19:40:52-0400
```

* net6.0

```
Installed Workload Ids      Installation Source
-----------------------------------------------
wasm-tools                  SDK 6.0.300
macos                       SDK 6.0.300
maui-maccatalyst            SDK 6.0.300
maui-ios                    SDK 6.0.300
maui-android                SDK 6.0.300
ios                         SDK 6.0.300
maccatalyst                 SDK 6.0.300
tvos                        SDK 6.0.300
android                     SDK 6.0.300
```

### Logs

[speedscope](https://github.com/jlfwong/speedscope/wiki/Importing-from-.NET-Core) logs from `dotnet trace`
[DopeTestUno.Mobile_20220526_215531.speedscope.json.zip](https://github.com/xamarin/xamarin-macios/files/8787393/DopeTestUno.Mobile_20220526_215531.speedscope.json.zip)

Logs shows 99+% time spend in unmanaged code (not surprising if related to #8890). However it also points out some places that are more costly than anticipated.

More details will be added in https://github.com/unoplatform/uno/issues/8890

#### ~~IsUserType~~

~~`IsUserType` takes 5.2% of the execution time (on the main thread). It is not cached (in `flags`) and does a few native calls. Also IIRC `Selector.GetHandle` is not optimized on macOS (at least is was not on mono, never checked with CoreCLR). Fixing this should be beneficial to all platforms/runtime.~~

Update: fixed with https://github.com/xamarin/xamarin-macios/pull/15149 - it was not really anything specific to CoreCLR, but found in that data

![Screen Shot 2022-05-27 at 10 16 52 AM](https://user-images.githubusercontent.com/260465/170726839-ef643b53-4858-47ca-8b7d-c5e6f887cda8.png)

**Comment by spouliot** [comment]
The attached data identified a problem with `CFArray` (used in bindings) and https://github.com/xamarin/xamarin-macios/pull/15146 should fix it. However it applies to both Mono and CoreCLR so it does not really change the performance regression reported here.

**Comment by spouliot** [comment]
cross-posting https://github.com/unoplatform/uno/issues/8890#issuecomment-1146636516

## Comparing p/invoke wrappers enabled

I had to hack around an [issue](https://github.com/xamarin/xamarin-macios/issues/15190#issuecomment-1146634438) (in quite an hackish way) but I was able to get the numbers

macOS 12.3.1 / arm64             | Build   | Change    | Reuse   | Grid    |
---------------------------------|--------:|----------:|--------:|--------:|
Xamarin.Mac Legacy (updated)     | 1594.97 | 465188.25 | 1903.63 | 6746.49 |
net-6.0 (w/pinvoke wrappers)     | 1460.71 | 376612.26 |     [1] |     [1] |
Impact (slowdown)                |   0.92x |     0.81x |     N/A |     N/A |

So the wrappers are helping a lot, net6.0-macos numbers are at best yet (see [previous numbers](https://github.com/unoplatform/uno/issues/8890#issuecomment-1142536411)) - but not quite what XM legacy was able to achieve.

We can also compare the **ratios** (other numbers can't be compared due to other fixes that were applied) with the original numbers

macOS 12.3.1 / arm64 | Build  | Change    | Reuse  | Grid    |
---------------------|-------:|----------:|-------:|--------:|	   
Xamarin.Mac Legacy   | 853.22 | 336635.53 | 909.64 | 5356.02 |
net6.0-macos         | 667.86 |  82385.28 |    [1] |     [1] |
Impact (slowdown)    |  0.78x |     0.24x |    N/A |     N/A |

The performance gap, between mono and coreclr runtimes, as narrowed considerably but still exists.

[1] Code is currently commented inside the repo, comparison is not possible

**Comment by rolfbjarne** [comment]
I just tried this with .NET 7, and the .NET numbers looked consistently a little bit higher than the Xamarin.Mac ones (they jump around a lot though, and are the tests supposed to run indefinitely, or am I just impatient?)

**Comment by spouliot** [comment]
Thanks for revisiting this issue @rolfbjarne :)

The test app does run indefinitely. 

Out of curiosity 
* Did you use Uno's `master` for the app ?
* Was it tested on `x64`, `arm64` or both ?

@jeromelaban I think we can close this issue and the one on our side https://github.com/unoplatform/uno/issues/8890 ?

**Comment by jeromelaban** [comment]
Thanks for the update! If the performance is improved, the issue can be closed at your convenience :)

**Comment by rolfbjarne** [comment]
> Thanks for revisiting this issue @rolfbjarne :)
> 
> The test app does run indefinitely.
> 
> Out of curiosity
> 
> * Did you use Uno's `master` for the app ?

This is the commit: https://github.com/unoplatform/performance/commit/46a79f2a9d8b64f59726a46bf48eb878d020ae15

> * Was it tested on `x64`, `arm64` or both ?

x64 on an M2 machine.

I had to disable the interpreter, since we don't support MonoVM on macOS anymore, only CoreCLR (in which case there's no interpreter):

https://github.com/unoplatform/performance/blob/46a79f2a9d8b64f59726a46bf48eb878d020ae15/src/dopes/Uno-dotnet6/DopeTestUno/DopeTestUno.Mobile/DopeTestUno.Mobile.csproj#L13
