### ISSUE TITLE
[dotnet][macOS] Incorrect registrar.h used when --require-pinvoke-wrappers:true is used

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#15190]
### Steps to Reproduce

1. build a dotnet6.0-macos project (default)
2. build the same dotnet6.0-macos project with `--require-pinvoke-wrappers:true`

### Expected Behavior

Both project should build without error and run correctly

### Actual Behavior

Native compilation failures happens when `--require-pinvoke-wrappers:true` is used

### Environment

Feature not yet released. Using xamarin-macios main 33b73a1fd6f2707558f820af884347b8d36f3b42

### Build Logs

https://gist.github.com/spouliot/cad06d79b61a4545981170c4131965bc

[macos.binlog.zip](https://github.com/xamarin/xamarin-macios/files/8824766/macos.binlog.zip)

#### registrar.h (working)

```c
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wtypedef-redefinition"
#pragma clang diagnostic ignored "-Wobjc-designated-initializers"
#pragma clang diagnostic ignored "-Wunguarded-availability-new"
#define CORECLR_RUNTIME
#include <stdarg.h>
#include <objc/objc.h>
#include <objc/runtime.h>
#include <objc/message.h>
#import <Foundation/Foundation.h>
#import <AppKit/AppKit.h>
#import <CoreGraphics/CoreGraphics.h>
#import <WebKit/WebKit.h>
#import <QuartzCore/QuartzCore.h>
#import <AuthenticationServices/AuthenticationServices.h>
#import <Intents/Intents.h>
#import <CoreImage/CoreImage.h>
#import <CoreImage/CIFilterBuiltins.h>
#import <CloudKit/CloudKit.h>
#import <AVFoundation/AVFoundation.h>

@class Microsoft_macOS__AppKit_NSApplicationDelegate;
@class UnoAppDelegate;
struct trampoline_struct_p {
	void *v0;
};
@class DopeTestUno_App;
...
```

#### registrar.h (non working)

```c
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wtypedef-redefinition"
#pragma clang diagnostic ignored "-Wobjc-designated-initializers"
#pragma clang diagnostic ignored "-Wunguarded-availability-new"
#define CORECLR_RUNTIME
#include <stdarg.h>
#include <objc/objc.h>
#include <objc/runtime.h>
#include <objc/message.h>
#import <WebKit/WebKit.h>
#import <AuthenticationServices/AuthenticationServices.h>
#import <Intents/Intents.h>
#import <CoreImage/CoreImage.h>
#import <CoreImage/CIFilterBuiltins.h>
#import <CloudKit/CloudKit.h>
#import <AVFoundation/AVFoundation.h>

@class Microsoft_macOS__AppKit_NSApplicationDelegate;
@class UnoAppDelegate;
@class DopeTestUno_App;
...
```

Note the lack of 
```c
struct trampoline_struct_p {
	void *v0;
};
```
which is the source of the compile time errors.

### Example Project (If Possible)

See https://github.com/xamarin/xamarin-macios/issues/15145 for the (dotnet) project being used

**Comment by spouliot** [comment]
The header file `pinvokes.h` contains the `trampoline_struct_p` definition (normal as it needs it too)

but there's a check not to duplicate the generation inside `StaticRegistrar.cs`

```csharp
n = "struct trampoline_struct_" + name.ToString ();
if (!structures.Contains (n)) {
	structures.Add (n);
	declarations.WriteLine ("{0} {{\n{1}}};", n, body.ToString ());
}
```

so it ends up using `trampoline_struct_p`, inside `registrar.mm`, without having it defined inside `registrar.h`

**Comment by rolfbjarne** [comment]
Yeah, the problem is that the pinvoke wrapper generation code uses a lot of logic from the static registrar, but doesn't properly clean up after itself, so when the static registrar runs it sees some leftover state from the pinvoke wrapper generation.
