### ISSUE TITLE
Mlaunch NuGet package publishing broken in xamarin-macios pipeline

### ISSUE THREAD

**Issue by premun** [xamarin/xamarin-macios#15204]
### Context
Previously, we were checking whether current hash of MACCORE in [xamarin.mk](https://github.com/xamarin/xamarin-macios/blob/ac97efd3953d3433a7eb17c6f94810d64702aeab/mk/xamarin.mk#L10) has its version of the [Mlaunch NuGet](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.DotNet.Mlaunch) published and if not, Mlaunch was built and pushed to the feed.

### Problem
The [xamarin-macios](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=14411&_a=summary) pipeline was refactored and this process is not working anymore for following reasons:
- The push step was moved later to **Prepare package**
- The push step is actually not executing now https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6113631&view=logs&j=24db099f-e6c4-5db4-d0ed-4d8b898c2636&t=c8034566-a43b-5966-dd66-d05c82ee6acb&l=1
- Even if it did run, it wouldn't do anything because the step expects the NuGet to be built in a folder that won't be there because mlaunch is built in a different stage
https://github.com/xamarin/xamarin-macios/blob/main/tools/devops/automation/templates/sign-and-notarized/publish-nugets.yml
The nupkg is then not published with build artifacts (I didn't find it) so it is not downloaded in the push step nor it is built there again.

I also found that his is broken for some time but the previous versions of mlaunch were being published by mistake from pipelines that still had the old form and they pushed the nuget from the PR actually.

**Comment by premun** [comment]
cc @mandel-macaque

**Comment by rolfbjarne** [comment]
We're looking into building/shipping mlaunch from the maccore repository directly (https://github.com/xamarin/xamarin-macios/issues/15209), so that might be the actual fix here.

**Comment by premun** [comment]
@rolfbjarne do you have some rough ETA? We could use new mlaunch so I would look into a workaround in the meantime

**Comment by rolfbjarne** [comment]
@premun packages will show up here: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.Tools.Mlaunch/versions (note that the NuGet name is different now).
