### ISSUE TITLE
Separate maccore/mlaunch build from xamarin-macios build

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#15209]
This involves:

* Build & ship mlaunch (as a nuget) from maccore.
* Remove maccore from xamarin-macios' dependencies (if possible).
* Changing the .NET workloads to consume the mlaunch nuget instead of shipping mlaunch.
* Changing the legacy packages to download the nuget & copy into .pkg instead of building mlaunch.

This is necessary so that we can select exactly which platforms to build for (mlaunch requires macOS, which means we could otherwise never disable macOS).

It will also save download space for .NET, since the mlaunch nuget would be shared between all platforms/workloads.

**Comment by spouliot** [comment]
Legacy SDK builds ? I guess it could be bundled from macios-binaries (or downloading the nuget and extracting the tool for the pkg).

**Comment by rolfbjarne** [comment]
> downloading the nuget and extracting the tool for the pkg

Yeah, that was my plan.

**Comment by rolfbjarne** [comment]
This is done now.
