### ISSUE TITLE
Stop building bitcode for watchOS / tvOS

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#15210]
Xcode 14's release notes say:

> Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer accepts bitcode submissions from Xcode 14.

We'll probably have to update our code accordingly.

* [ ] Show an error if using Xcode 14 and bitcode is enabled (or automatically disable + warning?)

**Comment by spouliot** [comment]
that's a very good news 🎉 🎉 🎉
