### ISSUE TITLE
Bump min OS versions to match Xcode 14

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#15216]
The release notes for Xcode 14 (beta 1) say:

"Xcode 14 supports building applications that target macOS 10.13, iOS 11, tvOS 11, watchOS 4, and later."

Should we do the same?

Note that the underlying SDKs shipped with Xcode 14 seem to support building for earlier OS versions just fine, so we might get away with not doing anything for a while (i.e. it _might_ be an IDE restriction only).

---

In general, we won't support anything lower than what the current stable version of Xcode does.

However, because:

* We don't want to change min OS versions in a minor release.
* Our major release schedules don't match up very well with Xcode's release schedules.

We'll bump the min OS versions a bit delayed compared to Xcode.

This means that we'll bump to the following OS versions only for .NET 8 (and not .NET 7, because by the time Xcode 14 is stable, it's very late in the .NET 7 release):

* iOS 11
* tvOS 11
* macOS 10.15 ([that's what .NET 6+ supports](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#macos)) [.NET may bump this to macOS 11 for .NET 8, in which case we'll have to follow suit)
* Mac Catalyst 13.1

Note:

* We're supporting macOS 10.15, but we're not testing on OS versions that Apple doesn't support anymore. At the time of this writing, this means macOS 11 is the lowest we test.
* The same applies to Mac Catalyst, we're only testing on Mac Catalyst 14.2, because that's the version in macOS 11 contains.

TODO:

* [x] Update release notes for .NET 8: https://github.com/xamarin/xamarin-macios/wiki/.NET-8-release-notes
* [x] Update our code. This is a significant change/simplification, because we can drop 32-bit support (armv7, armv7s).
* [x] Notify dotnet/runtime that they don't need to build earlier versions of iOS and tvOS anymore, as well as drop armv7+armv7s binaries/packs.

**Comment by rolfbjarne** [comment]
CC @davidortinau

**Comment by spouliot** [comment]
I wonder if that change removed the 32bits compilers...

Otherwise this is not the first time Apple bumped its requirements. Xcode 13.x can still build/install for older devices but can't launch them (you have to do it manually).

**Comment by rolfbjarne** [comment]
It doesn't look like we need to do this for Xcode 14.

IMHO we should still do it at some point though, so I'm moving to .NET 8.

**Comment by dalexsoto** [comment]
Resolution: Do it for .NET 8

**Comment by rolfbjarne** [comment]
This is complete now.
