### ISSUE TITLE
Native linking failed

### ISSUE THREAD

**Issue by sledderGIT** [xamarin/xamarin-macios#15258]
### Steps to Reproduce

1. Update Xcode and VS to the latest version.
2. Choose Debug | iPhone configuration
3. Connect your iPhone to your Mac
4. Clean Rebuild the project

### Expected Behavior
Project should be built

### Actual Behavior
Getting 
  linker command failed with exit code 1 (use -v to see invocation)
  Native linking failed for '...../src/OneSignalNotificationServiceExtension/obj/iPhone/Debug/device-builds/iphone13.2-15.5/mtouch-cache/arm64/libOneSignal.iOS.Binding.dll.dylib'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.10.23 (build 7)
Installation UUID: 72c3b31d-6c7c-47e1-a437-b15314796164
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 6.18.0.23 (d16-6/088c73638)

Package version: 612000174

===Mono Framework MDK===

runtime:
Mono 6.12.0.174 (2020-02/adf1bc4335d) (64-bit)
Package version: 612000174

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/5.0.408/Sdks
SDK versions:
6.0.203
5.0.408
5.0.403
5.0.402
5.0.400
5.0.301
5.0.202
5.0.103
5.0.101
5.0.100
3.1.419
3.1.415
3.1.414
3.1.412
3.1.410
3.1.408
3.1.406
3.1.404
3.1.403
3.1.402
3.1.300
3.1.200
3.0.100
2.1.701
2.1.505
2.1.302
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime versions:
6.0.5
5.0.17
5.0.12
5.0.11
5.0.9
5.0.7
5.0.5
5.0.3
5.0.1
5.0.0
3.1.25
3.1.21
3.1.20
3.1.18
3.1.16
3.1.14
3.1.12
3.1.10
3.1.9
3.1.8
3.1.4
3.1.2
3.0.0
2.1.23
2.1.22
2.1.18
2.1.16
2.1.13
2.1.12
2.1.9
2.1.2

=== .NET Core 3.1 SDK ===

SDK: 3.1.419

=== .NET 5.0 SDK ===

SDK: 5.0.408

===Xamarin.Profiler===

Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

===Apple Developer Tools===

Xcode 13.4.1 (20504)
Build 13F100

=== Xamarin.Mac ===

Version: 8.8.0.3 (Visual Studio Community)
Hash: eb7f8ed35
Branch: xcode13.3
Build date: 2022-03-30 03:16:09-0400

=== Xamarin.iOS ===

Version: 15.8.0.3 (Visual Studio Community)
Hash: eb7f8ed35
Branch: xcode13.3
Build date: 2022-03-30 03:16:09-0400

=== Xamarin.Android ===

Version: 12.2.4.3 (Visual Studio Community)
Commit: xamarin-android/d17-1/fc1125e
Android SDK: /Users/sledder/Library/Developer/Xamarin/android-sdk-macosx
Supported Android Versions:
5.0 (API level 21)
7.1 (API level 25)
8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK platform tools version: 33.0.1
SDK build tools version: 33.0.0 rc4

Build Details:
Mono: adf1bc4
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

=== Eclipse Temurin JDK ===

Java SDK: Not found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Build Information ===

Release ID: 810230007
Git revision: 7f00a2236acfde86feffbab606eefae32a9adbb3
Build date: 2022-05-05 09:46:09-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.1.0
Darwin 21.2.0 Darwin Kernel Version 21.2.0
    Sun Nov 28 20:28:54 PST 2021
    root:xnu-8019.61.5~1/RELEASE_X86_64x86_64

<details>
<summary>Version information</summary>

```
```

</details>

### Build Logs

[buildlog.txt](https://github.com/xamarin/xamarin-macios/files/8891412/buildlog.txt)

**Comment by sledderGIT** [comment]
Any updates? I still can't test on my devices.

**Comment by dalexsoto** [comment]
Hello,

I see from your logs 

```
Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_OSDeviceState", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSEmailSubscriptionState", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSEmailSubscriptionStateChanges", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSInAppMessage", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSInAppMessageAction", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSInAppMessageOutcome", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSInAppMessageTag", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSNotification", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSNotificationAction", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSNotificationOpenedResult", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSOutcomeEvent", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSPermissionState", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSPermissionStateChanges", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSSMSSubscriptionState", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSSMSSubscriptionStateChanges", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSSubscriptionState", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OSSubscriptionStateChanges", referenced from:
         -u command line option
      "_OBJC_CLASS_$_OneSignal", referenced from:
         -u command line option
      "_ONESIGNAL_VERSION", referenced from:
         -u command line option
    ld: symbol(s) not found for architecture arm64
```

This usually means that the library you are using does not contain the right architecture. Is there any chance you could share with us a sample app so we can reproduce this?

**Comment by sledderGIT** [comment]
Hello,
I figured out that the problem appeares only if I install OneSignalSDK.Xamarin nuget package to the ios notification extension. I reported a bug to them.

**Comment by chamons** [comment]
Thanks for the information @sledderGIT
