### ISSUE TITLE
iOS Simulator pid error

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#15285]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/iOS-Simulator-pid-error/10068790)._

---
error HE0042: Could not launch the app 'com.company.companydev' on the device 'iOS 15.4 (19E240) - iPhone 13 Pro Max': Application launch for 'com.company.companydev' did not return a valid pid nor a launch error.

This issue popped up a few weeks ago after an update, but I can’t remeber when. 

I’ve follow a few paths in all of the other issues related around this. Most recently this one:

https://github.com/xamarin/xamarin-macios/issues/14560

---
#### Feedback Bot on 6/13/2022, 10:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rolfbjarne** [comment]
This is probably https://github.com/xamarin/xamarin-macios/issues/14834, but could you provide the complete version information (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis) so we could confirm?
