### ISSUE TITLE
Error MT3001: Could not AOT the assembly - Assertion at method-to-ir.c:7848

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-macios#15310]
This error is occurring when trying to build my app for physical iOS device (no error when building for iOS simulator):
```
AOT Compilation exited with code 134, command:
MONO_PATH=/Users/MyUser/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/02e571208e54415ead9690e903f2fcb8c2b385e52067d1de0b0b6d60cf97bea2/obj/iPhone/Debug/device-builds/iphone8.1-15.5/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/15.10.0.5/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32 --aot=mtriple=arm64-ios,data-outfile=/Users/MyUser/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/02e571208e54415ead9690e903f2fcb8c2b385e52067d1de0b0b6d60cf97bea2/obj/iPhone/Debug/device-builds/iphone8.1-15.5/mtouch-cache/arm64/MyApp.Core.aotdata.arm64,static,asmonly,direct-icalls,full,readonly-value=ObjCRuntime.Runtime.Arch=i4/0,soft-debug,dwarfdebug,no-direct-calls,outfile=/Users/MyUser/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/02e571208e54415ead9690e903f2fcb8c2b385e52067d1de0b0b6d60cf97bea2/obj/iPhone/Debug/device-builds/iphone8.1-15.5/mtouch-cache/arm64/MyApp.Core.dll.s /Users/MyUser/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/02e571208e54415ead9690e903f2fcb8c2b385e52067d1de0b0b6d60cf97bea2/obj/iPhone/Debug/device-builds/iphone8.1-15.5/mtouch-cache/3-Build/MyApp.Core.dll
Mono Ahead of Time compiler - compiling assembly /Users/MyUser/Library/Caches/Xamarin/mtbs/builds/MyApp.iOS/02e571208e54415ead9690e903f2fcb8c2b385e52067d1de0b0b6d60cf97bea2/obj/iPhone/Debug/device-builds/iphone8.1-15.5/mtouch-cache/3-Build/MyApp.Core.dll
AOTID A8A477AB-DFC9-0488-F00D-ECA82DDBD525
* Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/mono/mini/method-to-ir.c:7848, condition `!called_is_supported_tailcall || tailcall_extra_arg == (vtable_arg || imt_arg || will_have_imt_arg || mono_class_is_interface (cmethod->klass))' not met
```

No error when adding this workaround in csproj:
```
<MtouchExtraArgs>--interpreter=MyApp.Core </MtouchExtraArgs>
<MtouchInterpreter>-all</MtouchInterpreter>
```

What is the meaning of this assert at method-to-ir.c:7848 ?
Is it something I can/should fix in my code, or is it a bug in mono ?
How can I get more details about the faulty code ?

Xamarin.iOS version 15.10.0.5
Mono JIT compiler version 6.12.0.179 (2020-02/dffa5ab9224 Mon May 16 08:38:30 EDT 2022)

**Comment by dalexsoto** [comment]
Hello @tranb3r looks like you are hitting a limitation of the AOT compiler that you are able to workaround using the interpreter. Would you be able to provide us with a sample project or steps to reproduce this?

Thank you!

**Comment by rolfbjarne** [comment]
Sorry about the late reply, this slipped through the cracks somehow.

I can reproduce the build failure using the repro project you provided.

However, I see that you're using a legacy Xamarin.iOS project, and I would highly suggest updating your project to a .NET project (this is a guide for projects using Xamarin.Forms, but many parts of it are still applicable even if you're not using Xamarin.Forms: https://github.com/dotnet/maui/wiki/Migrating-from-Xamarin.Forms-(Preview)).

The AOT compiler has received a lot of improvements in .NET, so it's quite possible your issue has been fixed.

**Comment by tranb3r** [comment]
I've migrated my app to maui a few months ago.
So as far as I'm concerned, you can close this issue.
