### ISSUE TITLE
bitcode_strip error on Apple M1 machine.

### ISSUE THREAD

**Issue by mike-normal13** [xamarin/xamarin-macios#15326]
### Steps to Reproduce

Ever since our team got new Apple M1 machines, we get this error:

"**Removing architecture x86_64** from /Users/i24054/xactimate/xactimate.ios/Xactimate.iOS/bin/iPhone/Debug/XactimateiOS.app/Frameworks/ARCapture.framework/ARCapture
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip /Users/i24054/xactimate/xactimate.ios/Xactimate.iOS/bin/iPhone/Debug/XactimateiOS.app/Frameworks/ARCapture.framework/ARCapture -r -o /Users/i24054/xactimate/xactimate.ios/Xactimate.iOS/bin/iPhone/Debug/XactimateiOS.app/Frameworks/ARCapture.framework/ARCapture
  Process exited with code 1, command:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip /Users/i24054/xactimate/xactimate.ios/Xactimate.iOS/bin/iPhone/Debug/XactimateiOS.app/Frameworks/ARCapture.framework/ARCapture -r -o /Users/i24054/xactimate/xactimate.ios/Xactimate.iOS/bin/iPhone/Debug/XactimateiOS.app/Frameworks/ARCapture.framework/ARCapture
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip : fatal error : file not in an order that can be processed (**link edit information does not fill the __LINKEDIT segment**): /Users/i24054/xactimate/xactimate.ios/Xactimate.iOS/bin/iPhone/Debug/XactimateiOS.app/Frameworks/ARCapture.framework/ARCapture [/Users/i24054/xactimate/xactimate.ios/Xactimate.iOS/Xactimate.iOS/Xactimate.iOS.csproj]
  
MTOUCH : error MT5309: Failed to execute the tool 'bitcode_strip', it failed with an error code '1'. Please check the build log for details. [/Users/i24054/xactimate/xactimate.ios/Xactimate.iOS/Xactimate.iOS/Xactimate.iOS.csproj]

at Xamarin.Bundler.Driver.RunXcodeTool (Xamarin.Bundler.Application app, System.String tool, System.Collections.Generic.IList`1[T] arguments) [0x0003c] in /Users/builder/azdo/_work/2/s/xamarin-macios/tools/common/Driver.cs:1161 
    at Xamarin.Bundler.Driver.RunBitcodeStrip (Xamarin.Bundler.Application app, System.Collections.Generic.IList`1[T] arguments) [0x00001] in /Users/builder/azdo/_work/2/s/xamarin-macios/tools/common/Driver.cs:1175 
    at Xamarin.Bundler.Application.StripBitcode (System.String macho_file) [0x00062] in /Users/builder/azdo/_work/2/s/xamarin-macios/tools/mtouch/Application.mtouch.cs:1253 
    at Xamarin.Bundler.Application.BuildBundle () [0x00832] in /Users/builder/azdo/_work/2/s/xamarin-macios/tools/mtouch/Application.mtouch.cs:1186 
    at Xamarin.Bundler.Application.BuildAll () [0x0009c] in /Users/builder/azdo/_work/2/s/xamarin-macios/tools/mtouch/Application.mtouch.cs:311 
    at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x00413] in /Users/builder/azdo/_work/2/s/xamarin-macios/tools/mtouch/mtouch.cs:677 
    at Xamarin.Bundler.Driver.Main (System.String[] args) [0x0001b] in /Users/builder/azdo/_work/2/s/xamarin-macios/tools/common/Driver.cs:52 
Done Building Project "/Users/i24054/xactimate/xactimate.ios/Xactimate.iOS/Xactimate.iOS/Xactimate.iOS.csproj" (Rebuild target(s)) -- FAILED.
Done Building Project "/Users/i24054/xactimate/xactimate.ios/Xactimate.iOS/Xactimate.iOS.sln" (Xactimate_iOS:rebuild target(s)) -- FAILED."
  
 ARCapture is a native iOS framework which is consumed as a nuget package by Xactimate.iOS. We've been dealing with this issue for quite some time, a few months. Depending on branches we use, sometimes it does not happen.
 
 I've looked in the build logs, but I'm not seeing anything about bitcode_strip in there.
 
 I've included the binding project we use to make our ARCapture dll. It contains a .dlll and .framework that the build is failing against. And also some build scripts we use to run against the ARCapture dll locally.

There does not seem to be anything recent on the internet about this issue.

We get around this by making nuget packages on our old Intel machines. We have to use xamarin.ios version 14.20.0.24 on the old machines.

Please let me know if I can provide any more information.

Thanks,

Mike

### Expected Behavior

The Xactimate.iOS project/solution should be able to build against our ARCapture framework/dll.

### Actual Behavior

The build fails with the error above on our new M1 machines most of the time. Sometimes it does not with certain branches, but very rarely.

### Environment

We're currently using VS for Mac 2019. We update VS for Mac and XCode semi regularly. Updates don't seem to have any positive affect.

<details>
<summary>Version information</summary>

```
```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/8960140/msbuild.binlog.zip)

### Example Project (If Possible)

[ARCapture.Binding.zip](https://github.com/xamarin/xamarin-macios/files/8960289/ARCapture.Binding.zip)
[Build Scripts.zip](https://github.com/xamarin/xamarin-macios/files/8960336/Build.Scripts.zip)

**Comment by rolfbjarne** [comment]
I can reproduce the problem by calling bitcode_strip on the framework in question:

```shell
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip ARCapture.Binding/ARCapture.Binding/ARCapture.framework/ARCapture -r -o outfile
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip: fatal error: file not in an order that can be processed (link edit information does not fill the __LINKEDIT segment): ARCapture.Binding/ARCapture.Binding/ARCapture.framework/ARCapture (for architecture x86_64)
```

so this does not look like a problem in Xamarin.iOS, but instead with this framework.

I would suggest contacting the vendor of the ARCapture framework, and let them know that `bitcode_strip` does not like their framework (maybe they can even provide a bitcode-free framework?)
