### ISSUE TITLE
Documentation for `dotnet trace` and `dotnet dsrouter` in .NET 6+

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-macios#15336]
On Android we have a guide for using `dotnet trace` and `dotnet dsrouter`, such as:

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md

I couldn't find instructions anywhere for doing this on iOS or other Apple platforms. So it might actually need a small change to work, no one actually knows.

Could we write some docs on this? I think this will help with MAUI performance efforts.

**Comment by spouliot** [comment]
FWIW `dotnet trace` works _as-is_ on `net6.0-macos` - unsurprisingly since it's CoreCLR based 😉 

I have not _yet_ tried on mono-based runtimes...

**Comment by jonathanpeppers** [comment]
@rolfbjarne I was just testing the instructions and we can probably close this.

How do I figure out what to put for:
```
--device :v2:runtime=com.apple.CoreSimulator.SimRuntime.iOS-15-4,devicetype=com.CoreSimulator.SimDeviceType.iPhone-11
```

I have Xcode 13.3.1, so maybe it doesn't have this same simulator available.

**Comment by rolfbjarne** [comment]
@jonathanpeppers 

> How do I figure out what to put for:

I added a section to explain it:

https://github.com/xamarin/xamarin-macios/wiki/Profiling#how-to-find-a-simulator-to-use

**Comment by jonathanpeppers** [comment]
Works, thanks!
<img width="596" alt="Screen Shot 2022-06-29 at 9 07 11 AM" src="https://user-images.githubusercontent.com/840039/176457153-e2087eb8-f17f-4825-b946-cba9ac9feb56.png">
