### ISSUE TITLE
Unable to build net6.0-ios in the .NET 7 SDK

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#15344]
### Steps to Reproduce

1. Make sure you have the .NET 7 SDK and iOS workloads installed
2. `donet new ios`
3. Edit the csproj to be net6.0-ios instead of net7.0-ios
4. Build
5. Observe error:
   > C:\Projects\maui\bin\dotnet\sdk\7.0.100-preview.6.22316.8\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(368,5): 
   > error NETSDK1073: The FrameworkReference 'Microsoft.iOS' was not recognized.

### Expected Behavior
Builds the app.

### Actual Behavior
Compiler error.

### Environment

<details>
<summary>Version information</summary>

```
```

</details>

### Build Logs
[msbuild.zip](https://github.com/xamarin/xamarin-macios/files/8977627/msbuild.zip)

**Comment by rolfbjarne** [comment]
Yes, this is currently work in progress.

**Comment by rolfbjarne** [comment]
Dup of #15672.
