### ISSUE TITLE
code object is not signed at all

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#15360]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/code-object-is-not-signed-at-all/10080517)._

---
\[severity:I’m unable to use this version\] \[regression\] \[worked-in:Visual Studio Version 17.3.0 Preview 1.1\]

After upgrading to Visual Studio Version 17.3.0 Preview 2.0 from Preview 1.1, I can’t create a \*.ipa for iOS anymore!

*   VS is connected to a MAC
*   I enter this command: dotnet publish -f:net6.0-ios -c:Release

Then after a long while the following error appears:

Tool /usr/bin/codesign execution finished (**exit code = 1**).

/Users/user111111/Library/Caches/Xamarin/mtbs/builds/OnesieMobile/4ec7a8728b5fa1e9205273ff25ba9492243ecbf302b59126254146e9ff1a7028/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app: **code object is not signed at all**  
In subcomponent: /Users/user111111/Library/Caches/Xamarin/mtbs/builds/OnesieMobile/4ec7a8728b5fa1e9205273ff25ba9492243ecbf302b59126254146e9ff1a7028/bin/Releas  
e/net6.0-ios/ios-arm64/OnesieMobile.app/CommunityToolkit.Mvvm.aotdata.arm64

C:\\Program Files\\dotnet\\packs\\Microsoft.iOS.Sdk\\15.4.414\\tools\\msbuild\\iOS\\Xamarin.Shared.targets(2067,3): error : /usr/bin/codesign **exited with code 1** \[C:\\Development\\OnesieMobile\\OnesieMobile\\OnesieMobile.csproj\]  
C:\\Program Files\\dotnet\\packs\\Microsoft.iOS.Sdk\\15.4.414\\tools\\msbuild\\iOS\\Xamarin.Shared.targets(2067,3): error : \[C:\\Development\\OnesieMobile\\OnesieMobile\\OnesieMobile.csproj\]  
C:\\Program Files\\dotnet\\packs\\Microsoft.iOS.Sdk\\15.4.414\\tools\\msbuild\\iOS\\Xamarin.Shared.targets(2067,3): error : **Failed to codesign** ‘/Users/user111111/Library/Caches/Xamarin/mtbs/builds/OnesieMobile/4ec7a8728b5fa1e9205273ff25ba9492243ecbf302b59126254146e9ff1a7028/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app’:/Users/user111111/Library/Caches/Xamarin/mtbs/builds/OnesieMobile/4ec7a8728b5fa1e9205273ff25ba9492243ecbf302b59126254146e9ff1a7028/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app: **code object is not signed at all** \[C:\\Development\\OnesieMobile\\OnesieMobile\\OnesieMobile.csproj\]  
C:\\Program Files\\dotnet\\packs\\Microsoft.iOS.Sdk\\15.4.414\\tools\\msbuild\\iOS\\Xamarin.Shared.targets(2067,3): error : In subcomponent: /Users/user111111/Library/Caches/Xamarin/mtbs/builds/OnesieMobile/4ec7a8728b5fa1e9205273ff25ba9492243ecbf302b59126254146e9ff1a7028/bin/Release/net6.0-ios/ios-arm64/OnesieMobile.app/CommunityToolkit.Mvvm.aotdata.arm64 \[C:\\Development\\OnesieMobile\\OnesieMobile\\OnesieMobile.csproj\]  
C:\\Program Files\\dotnet\\packs\\Microsoft.iOS.Sdk\\15.4.414\\tools\\msbuild\\iOS\\Xamarin.Shared.targets(2067,3): error : \[C:\\Development\\OnesieMobile\\OnesieMobile\\OnesieMobile.csproj\]  
C:\\Program Files\\dotnet\\packs\\Microsoft.iOS.Sdk\\15.4.414\\tools\\msbuild\\iOS\\Xamarin.Shared.targets(2067,3): error : \[C:\\Development\\OnesieMobile\\OnesieMobile\\OnesieMobile.csproj\]

---
#### Feedback Bot on 6/26/2022, 05:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dalexsoto** [comment]
Hello, Could you please provide us with a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs)?
