### ISSUE TITLE
About iOS Binding in MAUI

### ISSUE THREAD

**Issue by kinfey** [xamarin/xamarin-macios#15372]
I try to move my Xamarin.iOS Binding Project to MAUI, I use maui binding for iOS , it always give me 

ld: warning: pointer not aligned at address 

d: unaligned pointer(s) for architecture arm64
 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Steps to Reproduce

1.  dotnet build
2.  vs 2022 for mac preview build

### Expected Behavior

![Screen Shot 2022-06-29 at 18 10 55](https://user-images.githubusercontent.com/93169410/176411834-df61f34a-8918-4d1a-aeeb-d510c5d26257.png)

### Actual Behavior

Xamarin Binding for iOS is Okay , but MAUI Binding for iOS is failed

### Environment

Visual Studio Enterprise 2022 for Mac Preview
Version 17.3 Preview (17.3 build 1038)
Installation UUID: 0b9dc7d6-1e50-49c1-8723-6f32b7a792f4

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.3.0-2.22307.14+b91fc5b06135deb5bd72c105a1b96ce278ad6beb

NuGet
Version: 6.0.0.262

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.301/Sdks
SDK Versions:
	6.0.301
	6.0.300
	6.0.201
	6.0.101
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	3.1.420
	3.1.419

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.6
	6.0.5
	6.0.3
	6.0.1

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	3.1.26
	3.1.25

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin Designer
Version: 17.3.0.110
Hash: 01d90a6c4
Branch: remotes/origin/d17-3
Build date: 2022-06-17 20:44:52 UTC

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Enterprise)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin.Android
Version: 12.3.99.95 (Visual Studio Enterprise)
Commit: xamarin-android/main/5432886
Android SDK: /Users/lokinfey/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		11.0 (API level 30)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 32.1.0 rc1

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/main@1f27ab55
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@fc3c2ac

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.2.0.47
Hash: d6dd135
Branch: remotes/origin/dev/tondat/main-menues~3
Build date: 2022-06-17 20:44:58 UTC

Android Device Manager
Version: 0.0.0.1127
Hash: 4bb4d48
Branch: remotes/origin/dev/tondat/main-1536295~1
Build date: 2022-06-17 20:44:58 UTC

Build Information
Release ID: 1703001038
Git revision: ab015cef741e20e3cc212648659ecbd4ed089d5a
Build date: 2022-06-17 20:41:33+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.4.0
Darwin 21.5.0 Darwin Kernel Version 21.5.0
    Tue Apr 26 21:08:37 PDT 2022
    root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

<details>
<summary>Version information</summary>

![Screen Shot 2022-06-29 at 18 09 18](https://user-images.githubusercontent.com/93169410/176411523-747bf71b-ddee-4682-b198-7b6db7b1a394.png)

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/9009505/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
This seems to be a problem in the native library in question (MAMapKit.a), although that doesn't explain why it worked with an old-style Xamarin.iOS project. Could you provide a working Xamarin.iOS sample so I could compare what happens there?

**Comment by kinfey** [comment]
I have solved it. This is a dependency problem of the simulator environment. I added the original field in .csproj to solve the problem, thank you!

![Screen Shot 2022-07-02 at 06 39 57](https://user-images.githubusercontent.com/93169410/176974927-a78bfa00-4a92-4d99-b06a-4e009dca2891.png)

**Comment by kinfey** [comment]
> This seems to be a problem in the native library in question (MAMapKit.a), although that doesn't explain why it worked with an old-style Xamarin.iOS project. Could you provide a working Xamarin.iOS sample so I could compare what happens there?

Hi 

I have published samples for Binding Navite library in my GitHub https://github.com/kinfey/AMapMAUIControls

**Comment by rolfbjarne** [comment]
I'm glad you were able to figure it out!

I'm closing this then, since it doesn't seem like a problem in our product.
