### ISSUE TITLE
MTOUCH: Error MT4109: Failed to compile the generated registrar code. (MT4109) 

### ISSUE THREAD

**Issue by fsumma** [xamarin/xamarin-macios#15371]
Visual Studio Community 2022 for Mac
Version 17.0.5 (build 6)
Installation UUID: c6f41bc8-4478-45d1-9552-7ea3287b983c

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.1.0-3.22075.3+592501cbb9c9394072a245c15b3458ff88155d85

NuGet
Versione: 6.0.0.262

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.301/Sdks
Versioni SDK:
	6.0.301
	5.0.408
	3.1.420
SDK di MSBuild: /var/folders/7f/yzx_3zxd6w38r678mkfq2nz00000gn/T/AppTranslocation/5A2AF872-DC8F-4695-83E6-EB1033BC5DD5/d/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

Runtime .NET (x64)
Runtime: /usr/local/share/dotnet/dotnet
Versioni runtime:
	6.0.6
	5.0.17
	3.1.26

Xamarin.Profiler
Versione: 1.8.0.19
Percorso: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Versione: 11

Xamarin Designer
Version: 17.1.5.90
Hash: 53f47efde
Branch: remotes/origin/d17-0-vsmac
Build date: 2022-06-23 13:04:47 UTC

Apple Developer Tools
Xcode 14.0 (21257.0.0.0.25)
Build 14A5229c

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin.Android
Non installato

Microsoft Build of OpenJDK
Java SDK: Non trovato

Eclipse Temurin JDK
Java SDK: Non trovato

Android SDK Manager
Version: 17.2.0.37
Hash: 7f5a6ef
Branch: remotes/origin/d17-2
Build date: 2022-06-23 13:04:52 UTC

Android Device Manager
Version: 0.0.0.1116
Hash: e47e6c8
Branch: remotes/origin/d17-2
Build date: 2022-06-23 13:04:52 UTC

Build Information
Release ID: 1700050006
Git revision: 6b4784739a2f1a96c570a5f7c945170a8445bcf1
Build date: 2022-06-23 13:02:17+00
Build branch: release-17.0
Build lane: release-17.0

Operating System
Mac OS X 13.0.0
Darwin 22.0.0 Darwin Kernel Version 22.0.0
    Thu Jun 16 20:32:32 PDT 2022
    root:xnu-8792.0.92.121.3~2/RELEASE_X86_64 x86_64

iPhone 12 pro Max (iOS 15.5)

I have a small project that builded fine in the previous versions of Visual Studio/Xamarin/Xcode.

In this new configuration of the environment I get the following errors during the deployment on my iPhone:

/.../obj/iPhone/Debug/device-builds/iphone13.4-15.5/mtouch-cache/registrar.h(54,54): Error GEFA3BEAC: type argument 'GKPeerPickerControllerDelegate' must be a pointer (requires a '*') (GEFA3BEAC) 

/.../obj/iPhone/Debug/device-builds/iphone13.4-15.5/mtouch-cache/registrar.h(45,45): Error GA3D0CE9E: type arguments cannot be applied to non-parameterized class 'NSObject' (GA3D0CE9E)

**Comment by rolfbjarne** [comment]
> Xcode 14.0 (21257.0.0.0.25)

You're using Xcode 14, which is a beta version and which will require an updated version of Xamarin.iOS.

We working on getting the first preview out, and when Xcode 14 becomes stable in the fall we'll fully support it.

**Comment by rolfbjarne** [comment]
Until we've released support for Xcode 14, you can download Xcode 13 from Apple and use that instead (you can have both Xcode 14 and Xcode 13 installed at the same time).
