### ISSUE TITLE
iOS/macOS project doesn't ever display that release build is completed in latest VS2022

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#15379]
### Steps to Reproduce

1. Open any macOS project (or create a new one)
2. Switch to Release
3. Click on Rebuild

### Expected Behavior
It should build
### Actual Behavior
It shows some progress but then it stops and stands for hours there. After some examination it seems that the build is actually completed but it displays like it is still building and even output is not as usual when it is completed.
### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.0.5 (build 6)
Installation UUID: 4997af0c-f5c4-4569-93fc-cabbf30bda85

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.1.0-3.22075.3+592501cbb9c9394072a245c15b3458ff88155d85

NuGet
Version: 6.0.0.262

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.301/Sdks
SDK Versions:
	6.0.301
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.6
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 12.3.3.3 (Visual Studio Community)
Commit: xamarin-android/d17-2/4e061b7
Android SDK: /Users/ivanicin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-2@9760f0a9
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.38.2@7b1e016
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-2@fc3c2ac

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.2.0.37
Hash: 7f5a6ef
Branch: remotes/origin/d17-2
Build date: 2022-06-23 13:04:52 UTC

Android Device Manager
Version: 0.0.0.1116
Hash: e47e6c8
Branch: remotes/origin/d17-2
Build date: 2022-06-23 13:04:52 UTC

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin Designer
Version: 17.1.5.90
Hash: 53f47efde
Branch: remotes/origin/d17-0-vsmac
Build date: 2022-06-23 13:04:47 UTC

Build Information
Release ID: 1700050006
Git revision: 6b4784739a2f1a96c570a5f7c945170a8445bcf1
Build date: 2022-06-23 13:02:17+00
Build branch: release-17.0
Build lane: release-17.0

Operating System
Mac OS X 12.4.0
Darwin 21.5.0 Darwin Kernel Version 21.5.0
    Tue Apr 26 21:08:22 PDT 2022
    root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64


```

</details>

### Build Logs

Building MyApp (Release)
Build started 6/29/2022 10:36:08 PM.
__________________________________________________
Project "/Users/ivanicin/Projects/MyApp/MyApp/MyApp.csproj" (Build target(s)):

Target _BeforeCoreCompileImageAssets:
    Directory "obj/Release/actool" doesn't exist. Skipping.
Target _DetectSigningIdentity:
    Detected signing identity:
            
      Bundle Id: com.labsii.MyApp
      App Id: com.labsii.MyApp
Target _CoreCompileImageAssets:
    Tool /usr/bin/xcrun execution started with arguments: actool --errors --warnings --notices --output-format xml1 --output-partial-info-plist /Users/ivanicin/Projects/MyApp/MyApp/obj/Release/actool/partial-info.plist --app-icon AppIcon --minimum-deployment-target 12.3 --platform macosx --compile /Users/ivanicin/Projects/MyApp/MyApp/obj/Release/actool/bundle /Users/ivanicin/Projects/MyApp/MyApp/obj/Release/actool/cloned-assets/Assets.xcassets
            
Target _CoreCompileInterfaceDefinitions:
    Tool /usr/bin/xcrun execution started with arguments: ibtool --errors --warnings --notices --output-format xml1 --minimum-deployment-target 12.3 --sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk --compilation-directory /Users/ivanicin/Projects/MyApp/MyApp/obj/Release/ibtool /Users/ivanicin/Projects/MyApp/MyApp/Main.storyboard
            
      BundleResources Output:
        obj/Release/ibtool/Main.storyboardc/MainMenu.nib
        obj/Release/ibtool/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib
        obj/Release/ibtool/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib
        obj/Release/ibtool/Main.storyboardc/Info.plist
      OutputManifests Output:
        obj/Release/ibtool-manifests/Main.storyboardc
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _CoreCompileSceneKitAssets:
  Skipping target "_CoreCompileSceneKitAssets" because it has no inputs.
Target _CoreCompileColladaAssets:
  Skipping target "_CoreCompileColladaAssets" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _CoreCompileTextureAtlases:
  Skipping target "_CoreCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileCoreMLModels:
    Directory "obj/Release/coremlc" doesn't exist. Skipping.
Target CoreCompile:
    /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Roslyn/csc.exe /noconfig /nowarn:1701,1702,2008 /fullpaths /nostdlib+ /errorreport:prompt /warn:4 /define:__MACOS__;__UNIFIED__ /errorendlocation /preferreduilang:en-US /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/mscorlib.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/System.Core.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/System.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Facades/System.Drawing.Common.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Xamarin.Mac.dll /debug:pdbonly /optimize+ /out:obj/Release/MyApp.exe /target:exe /utf8output /langversion:7.3 Main.cs AppDelegate.cs ViewController.cs ViewController.designer.cs "obj/Release/Xamarin.Mac,Version=v2.0.AssemblyAttributes.cs"
    CompilerServer: server - server processed compilation - 14ac8c81-6ce5-4cf9-967f-ef70a0d7f1a9
Target CopyFilesToOutputDirectory:
    Copying file from "/Users/ivanicin/Projects/MyApp/MyApp/obj/Release/MyApp.exe" to "/Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.exe".
    MyApp -> /Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.exe
    Copying file from "/Users/ivanicin/Projects/MyApp/MyApp/obj/Release/MyApp.pdb" to "/Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.pdb".
Target _CopyResourcesToBundle:
    Creating directory '/Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.app/Contents/Resources'
            
    Copying file from '/Users/ivanicin/Projects/MyApp/MyApp/obj/Release/actool/bundle/AppIcon.icns' to '/Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.app/Contents/Resources/AppIcon.icns'
            
    Copying file from '/Users/ivanicin/Projects/MyApp/MyApp/obj/Release/actool/bundle/Assets.car' to '/Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.app/Contents/Resources/Assets.car'
            
    Creating directory '/Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.app/Contents/Resources/Main.storyboardc'
            
    Copying file from '/Users/ivanicin/Projects/MyApp/MyApp/obj/Release/ibtool/Main.storyboardc/MainMenu.nib' to '/Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.app/Contents/Resources/Main.storyboardc/MainMenu.nib'
            
    Copying file from '/Users/ivanicin/Projects/MyApp/MyApp/obj/Release/ibtool/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib' to '/Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib'
            
    Copying file from '/Users/ivanicin/Projects/MyApp/MyApp/obj/Release/ibtool/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib' to '/Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib'
            
    Copying file from '/Users/ivanicin/Projects/MyApp/MyApp/obj/Release/ibtool/Main.storyboardc/Info.plist' to '/Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.app/Contents/Resources/Main.storyboardc/Info.plist'
            
Target _WriteAppManifest:
    Directory "bin/Release/MyApp.app.dSYM" doesn't exist. Skipping.
Target _CompileToNative:
    /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp @/Users/ivanicin/Projects/MyApp/MyApp/obj/Release/response-file.rsp 
    Creating "bin/Release/bundler.stamp" because "AlwaysCreate" was specified.
Target _CopyAppExtensionsToBundle:
  Skipping target "_CopyAppExtensionsToBundle" because it has no inputs.
Target _GenerateDSym:
  Skipping target "_GenerateDSym" because it has no outputs.
Target _NativeStripFiles:
  Skipping target "_NativeStripFiles" because it has no outputs.
Target _NotifySpotlight:
    /usr/bin/mdimport bin/Release/ 
Target _CodesignAppBundle:
    Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign - /Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.app/Contents/MonoBundle/libmono-native.dylib
            
Target _CreateInstaller:
    Creating installer package
    /usr/bin/productbuild --product /Users/ivanicin/Projects/MyApp/MyApp/obj/Release/Product.plist --component /Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp.app /Applications /Users/ivanicin/Projects/MyApp/MyApp/bin/Release/MyApp-1.0.pkg 

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:13.59

========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Build successful.

**Comment by dalexsoto** [comment]
Hello

I am unable to repro this with the steps outlined, the status bar reports the right thing.
![image](https://user-images.githubusercontent.com/204671/176804203-a8e7001f-9bad-414e-94bc-55961497c2a2.png)

This looks like it could be a problem with VS Mac so please if you continue to have issues use the `Report a problem` function within VSMac from the `help` menu to reach out the VSMac team.

![image](https://user-images.githubusercontent.com/204671/176804434-bdfbc4e0-9769-4840-b1d9-c9bcf67873ee.png)

Thank you!
