### ISSUE TITLE
Missing ARM64 support for iOS simulators on Apple silicon hardware leads to unexpected and unsupported behavior

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#15393]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Missing-ARM64-support-for-iOS-simulators/10075557)._

---
Preface
=======

Let’s assume you are running Visual Studio for Mac (2022 Preview) on Apple silicon hardware (eg. M1 Pro-powered MacBook Pro), and you are developing iOS applications with Xamarin.iOS and/or Xamarin.Forms (possibly also MAUI), as well as debugging them with Xcode’s iOS Simulators.

Since iOS Simulators and/or apps you build and run with it, are inherently native on Apple silicon, they run and/or are expected to run as `ARM64` binaries/bundles.

However, at least in the latest Visual Studio for Mac 2022 Preview (version 17.3 Preview (17.3 build 1028) at the time of writing this), the configuration dialogs in the IDE only allow you to choose `x86_64 as` the architecture when targeting the iOS Simulator.

Description
===========

A few of my applications utilize features such as iOS’s QuickLook Preview, which allows you to easily open eg. a PDF file and view it, without having to implement your own viewer for it.

Now say you attempt to access iOS’s QuickLook Preview inside an iOS Simulator, while running on an Apple silicon Mac, as well as building your iOS Simulator app/bundle with only the `x86_64` target.  
It will run under Rosetta 2, while the iOS Simulator runs natively and/or expects any applications inside it to be running native, `ARM64` binaries.

What ends up happening here (I presume) is that the iOS Simulator is unable to find the right APIs, as the iOS application is unknowingly running under Rosetta 2, so it actually ends up trying to launch the QuickLook Preview on the host machine (Preview.app), which of course fails and the application hard crashes.

Details
=======

This is apparently entirely unsupported and known to cause unexpected behavior, and I was absolutely surprised that I couldn’t find an existing issue for this yet, as this has been an issue for quite a few months now.

Below is a link to Apple’s Developer Forums, where an Apple engineer confirms both the issue and the underlying reason for it: running `x86_64` applications in the iOS Simulator, that’s running on `ARM64` hardware, is in fact unsupported and prone to breaking issues like this.

[https://developer.apple.com/forums/thread/702933](https://developer.apple.com/forums/thread/702933)

Workarounds
===========

While you can manually edit the project configuration file, replacing `x86_64` with `ARM64`, which does build, however the application simply crashes on startup and/or the debugger doesn’t work.

As the method above doesn’t work, I’m not aware of any viable workarounds at this time, apart from running directly on a device instead, which can be much slower to work with, compared to the iOS Simulator.

---
#### Feedback Bot on 6/21/2022, 02:28 AM: 

(private comment, text removed)
#### Qiana Jiao (CSI Interfusion Inc) [MSFT] on 6/21/2022, 03:58 AM: 

(private comment, text removed)
#### Pauli Jokela on 6/27/2022, 09:58 AM: 

(private comment, text removed)
#### Roi Chen -MSFT [MSFT] on 7/1/2022, 05:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rolfbjarne** [comment]
We support ARM64 in the simulator when using .NET.

If the IDE doesn't support selecting ARM64, you can do so manually by editing the project file and setting the runtime identifier:

```xml
<PropertyGroup>
    <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
</PropertyGroup>
```

**Comment by dalexsoto** [comment]
It is worth nothing that this is **only** fully supported in .NET 6/7+ projects and not for Xamarin.iOS (Legacy), I see the sample provided here https://github.com/Dids/XF-QuickLookCrashTest is using Xamarin.iOS (Legacy) so your only two options is either continue development using just the phone or moving your app to .NET 6.

Please feel free to reopen if you further assistance!

Alex
