### ISSUE TITLE
native reference error on xamarin.ios

### ISSUE THREAD

**Issue by llzz19851985** [xamarin/xamarin-macios#15394]
I use visual studio 2022 compiled a fat static library named libHelloIos.a and than to use in xamarin.ios demo,now the problem is the library can work in iphone simulator but cannot work on ios device in xamarin ios,the library information as below:
![fat lib](https://user-images.githubusercontent.com/1481403/177020277-c192178b-f15a-4119-ac0f-ce733b1eefa3.png)
the error in xamarin.ios as below:
![image](https://user-images.githubusercontent.com/1481403/177020345-516ea664-652b-4cec-9d54-570b61d9f3e2.png)

than i copied the static library to xcode project and run on device,but it can work perfect:
![截屏2022-07-03 08 33 15](https://user-images.githubusercontent.com/1481403/177020284-4f1e852e-a525-434a-8d17-7ce2626a4b10.png)

I do not know why ,please help,thank you !

### Expected Behavior
native reference can work in xamarin ios on device.

### Actual Behavior
native reference can not work in xamarin ios on device.

### Environment
![image](https://user-images.githubusercontent.com/1481403/177020388-1bef43e1-7fc6-4ad6-96e5-4c9e11d55083.png)

![image](https://user-images.githubusercontent.com/1481403/177020420-e36a24fc-f310-410f-aaf3-2816fe3bf3a4.png)

### Build Logs
build successful!

### Example Project (If Possible)

**HelloIos.h:**
#pragma once

#define VCL_MEMORY_API

#ifdef __cplusplus
extern "C" {
#endif

	VCL_MEMORY_API int SayHelloIos(int a ,int b);

#ifdef __cplusplus
}
#endif

**HelloIos.cpp:**
#include "HelloIos.h"

int SayHelloIos(int a ,int b) 
{
	return a + b;
}

**Comment by chamons** [comment]
Thanks for the report.

From an initial look at the images and text included, I don't see why this wouldn't work. However, there is a lot of project specific configuration that might change things.

Please attach a sample project that shows the isuse.

**Comment by llzz19851985** [comment]
thanks for your reply，the sample project as below,I test again and than found the reason is I run the device is connect with my windows 10,not the device connect with the macos:
![image](https://user-images.githubusercontent.com/1481403/177442489-5c1e651f-f4e4-4789-b3b9-adda6117376d.png)

[IOS_Native_Demo.zip](https://github.com/xamarin/xamarin-macios/files/9050597/IOS_Native_Demo.zip)

**Comment by llzz19851985** [comment]
Is now the device connect with window10 cannot debug for xamarin ios?

**Comment by chamons** [comment]
Hmmm, there should be no difference between remote and local device builds at all, we build the same bundle and then deploy it one way or the other.

Please clean your project, and then attach a build log for both local device and remote device builds (showing the issue) with a clean in between.

**Comment by llzz19851985** [comment]
**remote build log :**
已启动生成...
1>------ 已启动生成: 项目: IOS_Native_Demo, 配置: Debug Any CPU ------
已还原 F:\workspace\xamarin_forms\IOS_Native_Demo\IOS_Native_Demo\IOS_Native_Demo.csproj (用时 12 毫秒)。
已还原 F:\workspace\xamarin_forms\IOS_Native_Demo\IOS_Native_Demo.iOS\IOS_Native_Demo.iOS.csproj (用时 15 毫秒)。
1>IOS_Native_Demo -> F:\workspace\xamarin_forms\IOS_Native_Demo\IOS_Native_Demo\bin\Debug\netstandard2.0\IOS_Native_Demo.dll
2>------ 已启动生成: 项目: IOS_Native_Demo.iOS, 配置: Debug iPhone ------
2>  Executing SayHello Task to establish a connection to a Remote Server. 
2>  			Properties: 
2>  				SessionId=fe124bc45f2bb6159d425f84d3b72ad6ea01afdfb542cf132d1f2ea40e378c78, 
2>  				Addresss=192.168.1.43, 
2>  				SshPort=22, 
2>  				TcpPort=55900, 
2>  				User=vinno, 
2>  				AppName=IOS_Native_Demo.iOS,
2>  				VisualStudioProcessId=14260,
2>  				ContinueOnDisconnected=False
2>  Executing SayHello Task to establish a connection to a Remote Server. 
2>  			Properties: 
2>  				SessionId=fe124bc45f2bb6159d425f84d3b72ad6ea01afdfb542cf132d1f2ea40e378c78, 
2>  				Addresss=192.168.1.43, 
2>  				SshPort=22, 
2>  				TcpPort=55900, 
2>  				User=vinno, 
2>  				AppName=IOS_Native_Demo.iOS,
2>  				VisualStudioProcessId=14260,
2>  				ContinueOnDisconnected=False
2>  检测到的签名标识:
2>  
2>    Code Signing Key: "Apple Development: Zheng Luo (UWJK5UM5CK)" (AFB1313B2F736DCD5B66C75BB7C306E3153CDC38)
2>    Provisioning Profile: "VS: WildCard Development" (6ca9ad11-627f-401f-a50e-313a509ed681)
2>    Bundle Id: com.companyname.IOS_Native_Demo
2>    App Id: W88YJSAFQ5.com.companyname.IOS_Native_Demo
2>  IOS_Native_Demo.iOS -> F:\workspace\xamarin_forms\IOS_Native_Demo\IOS_Native_Demo.iOS\bin\iPhone\Debug\IOS_Native_Demo.iOS.exe
2>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/vinno/Library/Caches/Xamarin/mtbs/builds/IOS_Native_Demo.iOS/fe124bc45f2bb6159d425f84d3b72ad6ea01afdfb542cf132d1f2ea40e378c78/obj/iPhone/Debug/device-builds/iphone14.6-15.4/response-file.rsp "--gcc_flags=-force_load \"Native References/libHelloIos.a\"" 
2>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(235,3): warning : warning: object file (Native References/libHelloIos.a(HelloIos.o)) was built for newer iOS version (8.1) than being linked (8.0)
2>  /usr/bin/mdimport bin/iPhone/Debug/device-builds/iphone14.6-15.4/ 
2>  /usr/bin/codesign --verify -vvvv "-R=anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.1] exists and (certificate leaf[field.1.2.840.113635.100.6.1.2] exists or certificate leaf[field.1.2.840.113635.100.6.1.4] exists)" bin/iPhone/Debug/device-builds/iphone14.6-15.4//IOS_Native_Demo.iOS.app 
========== “生成”: 2 成功，0 失败，0 更新，0 已跳过 ==========

**Comment by llzz19851985** [comment]
**windows10 local build log:**
已启动生成...
1>------ 已启动生成: 项目: IOS_Native_Demo, 配置: Debug Any CPU ------
已还原 F:\workspace\xamarin_forms\IOS_Native_Demo\IOS_Native_Demo\IOS_Native_Demo.csproj (用时 12 毫秒)。
已还原 F:\workspace\xamarin_forms\IOS_Native_Demo\IOS_Native_Demo.iOS\IOS_Native_Demo.iOS.csproj (用时 29 毫秒)。
1>IOS_Native_Demo -> F:\workspace\xamarin_forms\IOS_Native_Demo\IOS_Native_Demo\bin\Debug\netstandard2.0\IOS_Native_Demo.dll
2>------ 已启动生成: 项目: IOS_Native_Demo.iOS, 配置: Debug iPhone ------
2>  Detected signing identity:
2>    Code Signing Key: "Apple Development: Zheng Luo (UWJK5UM5CK)" (C:\Users\vinno\AppData\Local\Xamarin\iOS\Provisioning\Certificates\3359BF2AE4500282522C6A4BD6ED1BC4.p12)
2>    Provisioning Profile: "VS: WildCard Development" (C:\Users\vinno\AppData\Local\Xamarin\iOS\Provisioning\Profiles\6ca9ad11-627f-401f-a50e-313a509ed681.mobileprovision)
2>  IOS_Native_Demo.iOS -> F:\workspace\xamarin_forms\IOS_Native_Demo\IOS_Native_Demo.iOS\bin\iPhone\Debug\IOS_Native_Demo.iOS.exe
========== “生成”: 2 成功，0 失败，0 更新，0 已跳过 ==========

**Comment by llzz19851985** [comment]
@chamons the second log is cleaned and than rebuild!!can you try the sample directly?

**Comment by llzz19851985** [comment]
@chamons thanks for you reply,the log file as below:
[clean.log](https://github.com/xamarin/xamarin-macios/files/9106764/clean.log)
[rebuild.log](https://github.com/xamarin/xamarin-macios/files/9106766/rebuild.log)

**Comment by chamons** [comment]
I am unable to build your zip'ed project:
```
CSC : error CS2015: '/Users/donblas/Downloads/IOS_Native_Demo/IOS_Native_Demo/App.xaml.cs' is a binary file instead of a text file [/Users/donblas/Downloads/IOS_Native_Demo/IOS_Native_Demo/IOS_Native_Demo.csproj]
CSC : error CS2015: '/Users/donblas/Downloads/IOS_Native_Demo/IOS_Native_Demo/MainPage.xaml.cs' is a binary file instead of a text file [/Users/donblas/Downloads/IOS_Native_Demo/IOS_Native_Demo/IOS_Native_Demo.csproj]
```

However, I was able to build a small sample app locally on my mac:

[NativeExample.zip](https://github.com/xamarin/xamarin-macios/files/9115257/NativeExample.zip)

Can you try my project on your Windows machine, to see if it works for you on sim and device?

If so, then we can figure out what's special about your project (that won't build for me

**Comment by llzz19851985** [comment]
@chamons I can not run the demo with local device ,VS2022 can not find the local device :
![image](https://user-images.githubusercontent.com/1481403/179121425-9398a5bb-775e-49f0-911b-b5e285770927.png)
but on xamarin form project,it can be found:
![image](https://user-images.githubusercontent.com/1481403/179121505-5b373718-c1aa-4b7a-bc8f-07f848f993cb.png)
so please try again my demo again ,the file App.xaml.cs and MainPage.xaml.cs content as below:
`using System;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace IOS_Native_Demo
{
    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();

            MainPage = new MainPage();
        }

        protected override void OnStart()
        {
        }

        protected override void OnSleep()
        {
        }

        protected override void OnResume()
        {
        }
    }
}
`

`using System;
using System.Runtime.InteropServices;
using Xamarin.Forms;

namespace IOS_Native_Demo
{
    public partial class MainPage : ContentPage
    {
        [DllImport("__Internal")]
        private static extern int SayHelloIos(int a, int b);
        public MainPage()
        {
            InitializeComponent();
            //int cal = SayHelloIos(100, 188);
            int cal = 990;
            YYText.Text = $"Hello Native Result : {cal}";
        }
    }
}
`

**Comment by chamons** [comment]
It appears other files are also corrupted after fixing those:

```
CSC : error CS1504: Source file '/Users/donblas/Downloads/IOS_Native_Demo/IOS_Native_Demo.iOS/Properties/AssemblyInfo.cs' could not be opened -- GetCPInfoExW assembly:<unknown assembly> type:<unknown type> member:(null)
CSC : error CS1504: Source file '/Users/donblas/Downloads/IOS_Native_Demo/IOS_Native_Demo.iOS/Main.cs' could not be opened -- GetCPInfoExW assembly:<unknown assembly> type:<unknown type> member:(null)
CSC : error CS1504: Source file '/Users/donblas/Downloads/IOS_Native_Demo/IOS_Native_Demo.iOS/AppDelegate.cs' could not be opened -- GetCPInfoExW assembly:<unknown assembly> type:<unknown type> member:(null)
```

Please attach a new sample with all files usable.

**Comment by llzz19851985** [comment]
@chamons Can you recreate a xamarin forms project and try?not the xamarin ios project.because my computer is encrypted ,all project files is encrypted ，so Even though I provided the required files, maybe you still can't compile them ！

**Comment by chamons** [comment]
@llzz19851985 - I already did that, [here](https://github.com/xamarin/xamarin-macios/issues/15394#issuecomment-1184883857). It was a iOS application instead of a forms one, but there is no difference when it comes to how native libraries are loaded.

Please take a look, without more details this issue will be closed.

**Comment by llzz19851985** [comment]
@chamons the vs2022 can not recognized device in  IOS native sample,you sample is develop in mac so may have no probleam,but I develop in window10,it cannot find device!

**Comment by chamons** [comment]
Alright, it sounds like your issue is VS Windows specific in that case.

Unfortunately the team there is not accessible via github. 

Please file an issue via [these instructions](https://developercommunity.visualstudio.com/report?space=8&entry=problem).

**Comment by llzz19851985** [comment]
@chamons why this problem is closed????is it resolved?

**Comment by dalexsoto** [comment]
@llzz19851985 no, this was closed because the team that needs to look at you issue is not reachable via GitHub, please file an issue via Visual Studio for Windows following the instructions outlined here:

> Alright, it sounds like your issue is VS Windows specific in that case.
> 
> Unfortunately the team there is not accessible via github. 
>
> Please file an issue via [these instructions](https://developercommunity.visualstudio.com/report?space=8&entry=problem).

**Comment by llzz19851985** [comment]
@dalexsoto I don't think so is vs2022 problem , can you support a xamarin forms demo for IOS?

**Comment by dalexsoto** [comment]
@llzz19851985 This seems not to be an issue in Xamarin.iOS or Xamarin.Forms but with the Visual Studio for Windows integration and the team is not reachable via GitHub please use the outlined steps to reach the team via the IDE.
