### ISSUE TITLE
Support "app icons" in the csproj

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#15398]
### Android application type

iOS for .NET (net6.0-ios, net6.0-maccatalyst, net6.0-macos, etc.)

### Affected platform version

All

### Description

Right now we are almost there with resizetizer (icon generation) for mobile apps. We have tasks that generate all the assets and add it to the app, but the final step the user has to go edit the info.plist and link the assets to the xml file.

It would be great to be able to get resizetizer to output some build item/property and have the ios build insert the values into the plist.

@jonathanpeppers mentioned that editing the manifest from a build task may break incremental builds and/or fast deploy processes.

This is also consistent with Windows and Tizen which support automatic manifest updates.

### Steps to Reproduce

1. File | New | Maui
2. Replace the icon file with one with a new name (or rename)
3. Fix the csproj with the new name
4. Observe the build log shows the new images (and see in the obj dir)
5. Observe the build fails because the manifest also needs updating

### Did you find any workaround?

Editing the manifest, but this is the issue.

### Android Issue

 - https://github.com/xamarin/xamarin-android/issues/7147
 - Context: https://github.com/dotnet/maui/pull/8063

**Comment by rolfbjarne** [comment]
Looks related to this: #12790.

**Comment by mattleibow** [comment]
Correct. Closing in favour of that one.
