### ISSUE TITLE
App with WatchApp Fails to Archive/Build Error: strip exited with code 1

### ISSUE THREAD

**Issue by lilleydnSub** [xamarin/xamarin-macios#15400]
### Steps to Reproduce

1. Build the Attached Solution ( NOT Simulator), It should fail to build
(This is a fresh sample straight from Xamarin Templates)
The App will compile when the Watch App is not attached.

### Expected Behavior
It builds/ Archives

### Actual Behavior
Fails to build with error 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(3,3): Error: strip exited with code 1
### Environment

<details>
<summary>Version information</summary>

```
```

</details>
[Version information.txt](https://github.com/xamarin/xamarin-macios/files/9046443/Version.information.txt)

[Build.txt](https://github.com/xamarin/xamarin-macios/files/9046444/Build.txt)

### Example Project (If Possible)

[ExampleProject.zip](https://github.com/xamarin/xamarin-macios/files/9046455/ExampleProject.zip)

**Comment by lilleydnSub** [comment]
Can I downgrade to previous version iOS, I can no longer find the older versions ?

**Comment by rolfbjarne** [comment]
This is a duplicate of #15046, and has already been fixed. It will be included in the next service release.

There are a couple of potential workarounds here: https://github.com/xamarin/xamarin-macios/issues/15046#issuecomment-1135099724

> Can I downgrade to previous version iOS, I can no longer find the older versions ?

https://github.com/xamarin/xamarin-macios/blob/main/DOWNLOADS.md

**Comment by samhouts** [comment]
Duplicate of #15046
