### ISSUE TITLE
Document how to measure iOS startup times

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-macios#15416]
Just like the amazing doc here:

* https://github.com/xamarin/xamarin-macios/wiki/Profiling

I think we need one on measuring iOS startup times? And perhaps other Apple platforms?

We have this document from Apple using instruments:

* https://developer.apple.com/documentation/xcode/reducing-your-app-s-launch-time

But I think there is some slowdown once you attach instruments to an iOS app (as seen in https://github.com/dotnet/maui/issues/7687).

We did this for the measurements at https://aka.ms/dotnetperfstatus 

* https://github.com/dotnet/performance/pull/2355
* https://github.com/dotnet/performance/pull/2404

If we make a new doc, we can link to it from:

* https://github.com/dotnet/maui/wiki/Profiling-.NET-MAUI-Apps

**Comment by jonathanpeppers** [comment]
Also probably want MacCatalyst included here, too. But that might be a completely different topic?

**Comment by art-denisov** [comment]
I've tried to follow your instructions on the [blog](https://github.com/xamarin/xamarin-macios/wiki/Profiling)

But when I try to run dotnet-trace in a following way: 

`dotnet-trace collect --diagnostic-port /tmp/maui-app,connect --format speedscope `

I've got an error:
![Screenshot 2022-09-01 at 15 02 05](https://user-images.githubusercontent.com/105646856/187899010-7434b6e8-4ba2-46d5-9cbd-ac9f2873f4e8.png)

Do you have some advice for me? What have I done wrong?

**Comment by art-denisov** [comment]
Also, I've tried to do steps like in [the guide  for android](https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md)
1. Start dotnet-dsrouter
`dotnet-dsrouter client-server -tcps 127.0.0.1:9001 -ipcc /tmp/maui-app --forward-port iOS`
2. Start dotnet-trace without a connection
`dotnet-trace collect --diagnostic-port /tmp/maui-app --format speedscope`
3. Run the iOS app on a physical device
`mtouch --launchdev TestMauiPerf.app  --wait-for-exit --argument --connection-mode --argument none '--setenv:DOTNET_DiagnosticPorts=/tmp/maui-app'`

So, when I run dotnet-trace I've got a message like for an android session:
![Screenshot 2022-09-01 at 15 14 47](https://user-images.githubusercontent.com/105646856/187901103-37fb1503-ed16-4727-88d1-aa56fd693f27.png)

Then I launched iOS app and it just runs on my iPhone, but dotnet-trace hasn't caught any data and is still waiting for a connection.

How could I profile maui iOS apps?

**Comment by art-denisov** [comment]
@jonathanpeppers can you comment on my questions somehow?

**Comment by rolfbjarne** [comment]
@art-denisov try following this guide for profiling iOS apps: https://github.com/xamarin/xamarin-macios/wiki/Profiling

**Comment by art-denisov** [comment]
I have already tried it. But, as I described above, I got an error on the last step. 

When I ran the following command
`dotnet-trace collect --diagnostic-port /tmp/maui-app,connect --format speedscope`

What have I missed?

**Comment by rolfbjarne** [comment]
@art-denisov two things:

1. You have to launch the app first, wait for certain output, then execute the `dotnet-trace collect ...` command.
2. Your `DOTNET_DiagnosticPorts` variable is wrong, it should be:

    > mtouch --launchdev TestMauiPerf.app --wait-for-exit --argument --connection-mode --argument none '--setenv:DOTNET_DiagnosticPorts=127.0.0.1:9001,suspend,listen'

**Comment by rolfbjarne** [comment]
A doc about how to measure startup on iOS is up: https://github.com/xamarin/xamarin-macios/wiki/Profiling-App-Launch

> If we make a new doc, we can link to it from:
> [dotnet/maui/wiki/Profiling-.NET-MAUI-Apps](https://github.com/dotnet/maui/wiki/Profiling-.NET-MAUI-Apps)

Done.

**Comment by art-denisov** [comment]
@rolfbjarne 
I've tried to follow your recommendations and unfortunately, it doesn't work still

I use the command that you correct
`mtouch --launchdev TestMauiPerf.app --wait-for-exit --argument --connection-mode --argument none '--setenv:DOTNET_DiagnosticPorts=127.0.0.1:9001,suspend,listen'`
and wait for the output

> The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a Diagnostic Port

but it didn't show up. My terminal looked like 
![Screenshot 2022-09-06 at 17 47 36](https://user-images.githubusercontent.com/105646856/188651802-2826b524-33e2-4f4d-add3-b2f094f30531.png)

**Comment by rolfbjarne** [comment]
@art-denisov did the app launch/show up on the device and if so, can you use it/interact with it?

**Comment by art-denisov** [comment]
The app launches on the device and hangs on the start splash screen. I can't interact with it. It seems like the app waits for something.

If I remove `suspend,listen` at the end of the command the launches normally and I can use it.

**Comment by rolfbjarne** [comment]
@art-denisov which version of `dotnet-dsrouter` do you have?

```shell
$ dotnet-dsrouter --version
6.0.345601+f73f09031cebfc6256a9029ce9285a52fdad7380
```

If you have an earlier version, you need to update it like this: https://github.com/dotnet/diagnostics/pull/3134#issuecomment-1239216915

Also, once the app is running (and non-responsive), what happens if you execute the dotnet-trace command?

```shell
$ dotnet-trace collect --diagnostic-port /tmp/maui-app,connect --format speedscope
???
```

**Comment by art-denisov** [comment]
I checked the version of dotnet-dsrouter and dotnet-trace. It's equal to the version in your answer
![Screenshot 2022-09-07 at 17 08 23](https://user-images.githubusercontent.com/105646856/188886059-04c022bc-76fb-416c-be6f-ed39a52f1ae9.png)

So, I tried to follow your instruction:
1. Run dotnet-dsrouter
![Screenshot 2022-09-07 at 17 09 54](https://user-images.githubusercontent.com/105646856/188886367-ca71d77d-7730-4a89-9b6b-ca16f21b48cd.png)

2. Launch the app on the physical device
![Screenshot 2022-09-07 at 17 11 12](https://user-images.githubusercontent.com/105646856/188886628-1dc8539f-d447-4bd8-b371-74bbf71664ff.png)
As I wrote before, the app has launched successfully and waited on the splash screen.

3. Run dotnet-trace
![Screenshot 2022-09-07 at 17 14 20](https://user-images.githubusercontent.com/105646856/188887275-0f5beeca-4ba7-408e-ac83-780d1aaf89b0.png)
It didn't collect data, just the error as I marked in my first comment.

**Comment by rolfbjarne** [comment]
@art-denisov looks like there's a copy-paste error in the instructions, try using the following dotnet-dsrouter command instead:

```shell
dotnet-dsrouter server-client -tcpc 127.0.0.1:9001 -ipcs /tmp/maui-app --forward-port iOS
```

(and then the other commands stay the same)

**Comment by art-denisov** [comment]
So, it helped.
But it still works strangely.

When I run the command
`dotnet-trace collect --diagnostic-port /tmp/maui-app,connect --format speedscope`
It collects some data but immediately completes the tracing. Although, I haven't pressed <Ender> or <Ctrl+C>.
![Screenshot 2022-09-07 at 17 34 00](https://user-images.githubusercontent.com/105646856/188892526-4e7f8743-d9fd-49a3-b9a4-977db96f6dd8.png)

The app on the phone becomes fully interactive.

If I try to execute the command again without relaunching the app, I've got the error.
![Screenshot 2022-09-07 at 17 43 35](https://user-images.githubusercontent.com/105646856/188893677-b0557ce6-a5e7-4852-9781-6df07c6977f1.png)

**Comment by rolfbjarne** [comment]
That looks like a problem in `dotnet-trace`. Maybe try not passing `--format speedscope`, since it looks like that might be related:

```
dotnet-trace collect --diagnostic-port /tmp/maui-app,connect
```

**Comment by art-denisov** [comment]
It still completes the tracing immediately but without errors.
![Screenshot 2022-09-07 at 17 57 39](https://user-images.githubusercontent.com/105646856/188897011-c221eaac-89ee-4b99-a970-696cbb915137.png)

**Comment by rolfbjarne** [comment]
That's weird

* Does the resulting trace file contain anything?
* Is anything printed in the tab running `mlaunch --launchdev ...`?
