### ISSUE TITLE
How to access UITabBarItem Trait Collection

### ISSUE THREAD

**Issue by Axemasta** [xamarin/xamarin-macios#15486]
I am looking to override the `UITraitCollection` for a `UITabBarItem` so that I can set the appearance on iPad to always show the icon vertically above the label.

On iOS we always get this appearance:
<img width="56" alt="image" src="https://user-images.githubusercontent.com/33064621/178713011-40e5271e-3c93-4194-976f-bfdb96e12c8c.png">

On iPad we get an alternative appearance:
![image](https://user-images.githubusercontent.com/33064621/178713092-ce2304c1-e173-4919-9426-718855cd0b1c.png)

This is to be expected since this is the default appearance for these buttons on iPad.

Following [this stackoverflow post](https://stackoverflow.com/a/70804043/8828057) I was able to override this behaviour in a swift project by subclassing `UITabBarItem` and overriding the `UITraitCollection`

If I bring this over to xamarin, I can't see the `UITraitCollection` api having been exposed to `UITabBarItem` so I'm wondering if its possible to set?

I've had a look at setting via `UITabBarItem.GetAppearance` but this throws an object disposed exception:
```csharp
try
{
    var traits = UITraitCollection.FromHorizontalSizeClass(UIUserInterfaceSizeClass.Compact);

    using (var appearance = UITabBarItem.GetAppearance(traits))
    {
        if (appearance != null)
        {
            if (appearance.StandardAppearance != null)
            {
                tab.StandardAppearance = appearance.StandardAppearance;
            }
        }
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
```

This throws the following exception when trying to access the `StandardAppearance` property:
```
2022-07-13 16:52:09.604810+0100 MyApp.iOS[24088:10619184] System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'UIKit.UITabBarItem+UITabBarItemAppearance'.
  at ObjCRuntime.ThrowHelper.ThrowObjectDisposedException (System.Object o) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:40 
  at Foundation.NSObject.get_SuperHandle () [0x00012] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:559 
  at UIKit.UITabBarItem+UITabBarItemAppearance.get_StandardAppearance () [0x0002a] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/UIKit/UITabBarItem.g.cs:721 
  at MyApp.iOS.Renderers.SpicyTabsRenderer.ViewWillAppear (System.Boolean animated) [0x0006e] in /Users/alex.duffell/Documents/Civica/civica-blue/MyApp/MyApp/MyApp/MyApp.iOS/Renderers/SpicyTabsRenderer.cs:50
```

**Comment by chamons** [comment]
The example in the linked SO post shows:

```
class CompactTabBar: UITabBar {
    
    override var traitCollection: UITraitCollection {
        guard UIDevice.current.userInterfaceIdiom == .pad else {
            return super.traitCollection
        }
        
        let compactTrait = UITraitCollection(horizontalSizeClass: .compact)
        let tabTrait = UITraitCollection(traitsFrom: [super.traitCollection, compactTrait])
        
        return tabTrait
    }
}
```

which involves subclassing UITabBar and overriding the TraitCollection. The equivalent in C# would look something like (compiles but untested):

```csharp
	class MyTabBar : UITabBar {
        public override UITraitCollection TraitCollection
        {
			get
            {
                if (UIDevice.CurrentDevice.UserInterfaceIdiom != UIUserInterfaceIdiom.Pad) {
					return base.TraitCollection;
                }
				var compactTrait = UITraitCollection.FromHorizontalSizeClass(UIUserInterfaceSizeClass.Compact);
				var tabTrait = UITraitCollection.FromTraitsFromCollections(new UITraitCollection[] { base.TraitCollection, compactTrait });
				return tabTrait;
            }				
		}
    }
```

The declaration of `UITraitCollection TraitCollection` is in UITabBar's base class UIView which has the protocol UITraitEnvironment. 

Take a look at that and let me know if it works, because at this moment this does not appear to be an issue in the SDK.
