### ISSUE TITLE
"Not a valid framework" (MM0140 / MT0140) build error when binding ScriptingBridge system framework for net6-macos

### ISSUE THREAD

**Issue by snechaev** [xamarin/xamarin-macios#15485]
### Steps to Reproduce

1. Unzip a project attached: 
[net6nativeBindingsError-master.zip](https://github.com/xamarin/xamarin-macios/files/9102378/net6nativeBindingsError-master.zip)
2. Try to build ./net6/net6BindingTest.sln (or app.csproj to be more precise) with VS Mac or with `dotnet build` 
3. Observe the build errors

### Expected Behavior
Project is built without errors and application can use binded API.

### Actual Behavior
Build errors MM0140:
```
ILLink : MacOSX error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [/Users/sergey/Downloads/net6nativeBindingsError-master/net6/app/app.csproj]
ILLINK : error MM0140: File '/Users/sergey/Downloads/net6nativeBindingsError-master/net6/app/obj/Debug/net6.0-macos/osx-x64/linker-cache/NativeBindingsLib.resources/ScriptingBridge.framework/ScriptingBridge' is not a valid framework. [/Users/sergey/Downloads/net6nativeBindingsError-master/net6/app/app.csproj]
  		
ILLINK : error MM2342: The linker step 'Extract Binding Libraries' failed during processing: File '/Users/sergey/Downloads/net6nativeBindingsError-master/net6/app/obj/Debug/net6.0-macos/osx-x64/linker-cache/NativeBindingsLib.resources/ScriptingBridge.framework/ScriptingBridge' is not a valid framework. [/Users/sergey/Downloads/net6nativeBindingsError-master/net6/app/app.csproj]

```

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Professional 2022 for Mac
Version 17.0.6 (build 4)
Installation UUID: 95c022be-c8d0-4de3-981d-e89982bc8bfa

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.1.0-3.22075.3+592501cbb9c9394072a245c15b3458ff88155d85

NuGet
Version: 6.0.0.262

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.302/Sdks
SDK Versions:
	6.0.302
	6.0.301
	3.1.421
	3.1.420
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.7
	6.0.6
	3.1.27
	3.1.26

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.10.0.5 (Visual Studio Professional)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Professional)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin Designer
Version: 17.1.5.90
Hash: 53f47efde
Branch: remotes/origin/d17-0-vsmac
Build date: 2022-07-07 17:07:58 UTC

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.2.0.37
Hash: 7f5a6ef
Branch: remotes/origin/d17-2
Build date: 2022-07-07 17:08:03 UTC

Android Device Manager
Version: 0.0.0.1116
Hash: e47e6c8
Branch: remotes/origin/d17-2
Build date: 2022-07-07 17:08:03 UTC

Build Information
Release ID: 1700060004
Git revision: 056076d45137bf76b73f62f871524da8890deb05
Build date: 2022-07-07 17:06:08+00
Build branch: release-17.0
Build lane: release-17.0

Operating System
Mac OS X 12.4.0
Darwin 21.5.0 Darwin Kernel Version 21.5.0
    Tue Apr 26 21:08:22 PDT 2022
    root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/9102477/msbuild.binlog.zip)

### Example Project (If Possible)

[net6nativeBindingsError-master.zip](https://github.com/xamarin/xamarin-macios/files/9102378/net6nativeBindingsError-master.zip)

### Additional information
I'm trying to migrate my xamarin.mac project from old mono/net48 runtime to the new net6-macos.
I have working native bindings library targeting old xamarin.mac (xamarin.full net framework 4.8) built with mono (see `mono` folder in the attached example project).
It is binding `ScritptingBridge.framework`, not a static library. It is builds and works as expected.

Now I'm trying to migrate to newest net6-macos. To do so I do the following
* converted main app project to the sdk style and target net6-macos.
* converted native bindings project to the sdk style and perform the following fixes suggested by the comiler errors
  * changed version to avoid wildcards
  * replaced `[assembly: LinkerSafe]` with `AssemblyMetadata("IsTrimmable", "True")]`
  * added explicit `NativeReferecnce` to the framework I'm trying to bind.
* no changes were performed in the `ApiDefinition.cs` or `StructsAndEnums.cs`

Final csproj content:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net6-macos</TargetFramework>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<RootNamespace>NativeBindingsLib</RootNamespace>
	<AssemblyName>NativeBindingsLib</AssemblyName>
	<IsPackable>false</IsPackable>
	<AllowUnsafeBlocks>false</AllowUnsafeBlocks>
	<IsBindingProject>true</IsBindingProject>
	<NoBindingEmbedding>true</NoBindingEmbedding>
  </PropertyGroup>
  <ItemGroup>
	<ObjcBindingApiDefinition Include="ApiDefinition.cs" />
	<ObjcBindingCoreSource Include="StructsAndEnums.cs" />
	<NativeReference Include="/System/Library/Frameworks/ScriptingBridge.framework" Kind="Framework" />
  </ItemGroup>
</Project>
```

When I trying to build the only bindings library with `dotnet build` it builds without errors.

But when I try to build the application project, which is referencing (via the 'ProjectReference') the binding library, I got the errors described above.

Also during the googling for the problem I found, that the current MM0140 error is very similar to the old mtouch MT0140 error, so I adding this note to help others in the further searching.

**Comment by chamons** [comment]
I'm looking into the question of "how are NativeReferences expected to interact with system wide frameworks", but setting that aside for a second, why are you binding ScriptingBridge by hand, as we have a [binding for it already](https://github.com/xamarin/xamarin-macios/blob/main/src/scriptingbridge.cs) it appears?

**Comment by snechaev** [comment]
Thank you for looking into the issue! 
I'm binding by hand because I need the app-specific API for exact application (Finder in the attached sample and Photoshop in the real life), so the ready-to-use bindings, which is limited by `Activate`, `IsRunning` and other common things, is not enaugh for my tasks.
Am I missed some better method to call app-specific things, for example, `version` property of 'finder'?

**Comment by chamons** [comment]
So if I understand your use case, you are interacting with ScriptingBridge objects and need to call arbitrary selectors on them that are specific to your app.

The sample hasn't been updated for awhile, but take a look at [this sample](https://github.com/xamarin/xamarin-macios/blob/main/tests/scriptingbridge/finder.cs), which I wrote many years ago.

You don't need to redefine ScriptingBridge to call these selectors, you declare derived classes specific to your application object, and then use [casts like](https://github.com/xamarin/xamarin-macios/blob/main/tests/scriptingbridge/test.cs):

```
FinderApplication app = SBApplication.FromBundleIdentifier<FinderApplication> ("com.apple.finder");
FinderItem item = app.Trash.Items.GetItem <FinderItem> ((nuint)i);
```
To "cast" the object you get to your derived class, which should know how to call each selector.

Try that out and report back, I think you can avoid reshipping all of ScriptingBridge.

**Comment by snechaev** [comment]
You are absolutely correct about my case.
As for your suggestion - did you mean just to remove `NativeReference` from binding project and leave all declarations of `FinderApplication` as is (they are very similar to your sample)? I started exactly from this and I have exactly this solution for old mono-based project.
But for the new project I got the compilation error
```
MSBuild : error MM7068: Can't create a binding resource package unless there are native references in the binding project. [/Users/sergey/Downloads/net6nativeBindingsError-master/net6/NativeBindingsLib/NativeBindingsLib.csproj]
```

**Comment by chamons** [comment]
Great 🎉 - let me create an issue noting the requirement to have a NativeReference is too strict, but I'm happy you were able to solve your issue in a better way.

**Comment by chamons** [comment]
As we have a solution to the specific issue (use a binding project and don't copy all of ScriptingBridge into your app), an [issue](https://github.com/xamarin/xamarin-macios/issues/15489) describing a current limitation of the NET6 binding project, and a work around (include an arbitrary dylib), I believe this issue is resolved.

Please reopen if I've missed something.

**Comment by chamons** [comment]
The problem with NativeReference'ing system frameworks is that it implicitly copies the entire framework into your bundle, which is not what you want.

I don't think binding projects are in scope for adding/extending system frameworks, unless i'm missing something @rolfbjarne  (since you re-implemented them for NET6).

**Comment by rolfbjarne** [comment]
> I don't think binding projects are in scope for adding/extending system frameworks, unless i'm missing something @rolfbjarne (since you re-implemented them for NET6).

It's a bit unusual, but I don't think it's an unreasonable scenario to create a binding project to bind system libraries.

Using a `NativeReference` is the wrong approach though, since that will copy the framework into the binding project's output, which is not what you want. Just fixing the error when there are no `NativeReference` items should be enough to make the scenario work (#15489).

That said, maybe we should detect it if someone tries to add a system framework to `NativeReference`, and give a better error message?
