### ISSUE TITLE
Home screen icon shows default Xamarin icon... until phone is restarted

### ISSUE THREAD

**Issue by BlueRaja** [xamarin/xamarin-macios#15529]
### Steps to Reproduce

1. Install any Xamarin-iOS app for the first time _(might be specific to Xamarin Forms, but I don't see how it could be)_
2. Open the app
3. Double-click the physical 'home' button on the device

### Expected Behavior
The icon shown in the task screen is the one that is set in the asset catalog

### Actual Behavior
The icon shown in the task screen is the default Xamarin one... until the phone is restarted.  After restarting the correct icon is shown.

### More info
[Here](https://stackoverflow.com/questions/61895597/xamarin-forms-ios-wrong-task-icon) is a stackoverflow post I found of someone with the same issue and workaround.  They came to the conclusion that it had something to do with their environment or debug build.  However I am seeing the same thing in the release version of [my app](https://apps.apple.com/us/app/ringotan/id1633001064), after downloading it from the App Store and installing it on a fresh phone.

**Comment by chamons** [comment]
Thanks for the feedback.

I am not seeing this behavior locally, please restart your phone, clean your project and see if it reproduces. If it does, please attach a sample project showing the behavior.
