### ISSUE TITLE
After update to VS 16.11.17 getting iOS build warning MT0136 followed by error MT2002 for SQLite 

### ISSUE THREAD

**Issue by Chris-Marassovich** [xamarin/xamarin-macios#15564]
After updating VS to 16.11.17 from 16.11.16 I am getting the following error (only on iOS as Droid works fine):

**I have replaced sensitive data with XXX**

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT0136: Cannot find the assembly 'SQLitePCLRaw.lib.e_sqlite3.ios, Version=2.0.4.976, Culture=neutral, PublicKeyToken=e4ad490600e2234c' referenced from '/Users/XXX/Library/Caches/Xamarin/mtbs/builds/XXX.XXX.XXX.iOS/a1fba5470b0c5888a5369c9af7b42531e3458c28c323c860c4c35cb8eebc00ad/bin/iPhoneSimulator/Debug/SQLitePCLRaw.batteries_v2.dll'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT0136: Cannot find the assembly 'SQLitePCLRaw.provider.internal, Version=2.0.4.976, Culture=neutral, PublicKeyToken=89ae75803b2c608d' referenced from '/Users/XXX/Library/Caches/Xamarin/mtbs/builds/XXX.XXX.XXX.iOS/a1fba5470b0c5888a5369c9af7b42531e3458c28c323c860c4c35cb8eebc00ad/bin/iPhoneSimulator/Debug/SQLitePCLRaw.batteries_v2.dll'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT2002: Failed to resolve assembly: 'SQLitePCLRaw.lib.e_sqlite3.ios, Version=2.0.4.976, Culture=neutral, PublicKeyToken=e4ad490600e2234c'

I am posting here based on the recommendation in the below link (Issue 1702) from @mattleibow.  Additionally the situation in this issue (link below) is almost identical to mine if you simply replace SkiaSharp references with SQLIte.  The issue was with VS and a later update to VS resolved the issue.

https://github.com/mono/SkiaSharp/issues/1702

I cannot provide a repo case.  In my Solution I have two XF projects.  One is working perfectly and the other is showing this issue after the update of VS.

What is strange is that while I have the Target Platform of the project set to "iPhoneSimulator" I get the above error but if I simply change the Target Platform to "iPhone" it works fine.  One person noted this also in issue 1702.

Note I have cleared all my /bin /obj folders as well as the Xcode $HOME/Library/Caches/Xamarin/mtbs folders.

In the morning before taking the VS update I was nicely building for iOS and as soon as I applied the VS update this issue arose.
No XF updates, no NuGet updates and no Xcode updates performed by me.

### Steps to Reproduce

1. If the Target Platform is set to iPhoneSimulator.

### Expected Behavior
I can compile for iOS.

### Actual Behavior
Error above is raised.

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Professional 2019
Version 16.11.17
VisualStudio.16.Release/16.11.17+32630.194
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA554
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.110.1451
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.110.1451
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.110.1451
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.11.110.1451
Azure Functions and Web Jobs Tools

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Markdown Editor   1.12.253
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.126+g11d4cf0d0c.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62205.05200
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   1.0.0.18
WiX Toolset Visual Studio Extension version 1.0.0.18
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   16.11.000.197 (d16-11@6934992)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@476bb5b
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b


Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

**Comment by Chris-Marassovich** [comment]
Another interesting observation which I cannot make any sense of is:
I set the Target Platform to iPhone and choose "Local Device" from the list available and I get a successful build.

But if I choose an actual device, an iPhone that is connected to the mac, I get the compilation error from the post above.

**Comment by chamons** [comment]
Thanks for the feedback.

This appears to be an IDE specific issue, or at least one that will require IDE logs to look into. 

Unfortunately that team is not accessible via Github. You will need to file a bug at developer community using [these instructions](https://developercommunity.visualstudio.com/report?space=8&entry=problem) to get them everything they need to look into this.
