### ISSUE TITLE
Missing NullAllowed attribute in NSSavePanel.AllowedFileTypes

### ISSUE THREAD

**Issue by aconcagua21** [xamarin/xamarin-macios#15565]
According to the [documentation](https://developer.apple.com/documentation/appkit/nssavepanel/1534419-allowedfiletypes?language=objc) and experiments, null should be allowed in [NSSavePanel.AllowedFileTypes](https://github.com/xamarin/xamarin-macios/blob/0b872a1683538697549b56d3fcbb6fcfbc483166/src/appkit.cs#L13323-L13325).

**Comment by chamons** [comment]
Fixed, thanks for the report with documentation link!

**Comment by chamons** [comment]
If you happen to need a work around to call it will null let me know.
