### ISSUE TITLE
Couldn't connect to remote Mac: DER length is '122' and cannot be more than 4 bytes.

### ISSUE THREAD

**Issue by KuzonCode** [xamarin/xamarin-macios#15574]
Exact same issue as [#9591](https://github.com/xamarin/xamarin-macios/issues/9591) Tried deleting content of %LOCALAPPDATA%\Xamarin\MonoTouch to no avail. 

### Steps to Reproduce

1. Try and connect to Xamarin Profile from Windows machine building on a mac for iOS builds

### Expected Behavior
Profiler to work

### Actual Behavior
Crashes with the following error:
```
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Error: 0 : [2022-07-26 13:51:15.3947] Sorry, something went wrong trying to run AppnIOS.app: couldn't connect to remote Mac: Invalid data type, INTEGER(02) is expected, but was DD
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Error: 0 : [2022-07-26 13:51:15.3947] Sorry, something went wrong trying to run AppnIOS.app: couldn't connect to remote Mac: Invalid data type, INTEGER(02) is expected, but was DD
XamarinProfiler.Windows.ViewModels.ProgressReport.ReportViewModel Information: 0 : [2022-07-26 13:51:15.3947] Sorry, something went wrong trying to run AppnIOS.app: couldn't connect to remote Mac: Invalid data type, INTEGER(02) is expected, but was DD
XamarinProfiler.Windows.MainWindow Information: 0 : [2022-07-26 13:51:15.3947] StartRecording for AppnIOS.app
XamarinProfiler.Windows.MainWindow Error: 0 : [2022-07-26 13:51:15.4017] Error occured on run AppnIOS.app: couldn't connect to remote Mac: Invalid data type, INTEGER(02) is expected, but was DD
XamarinProfiler.Windows.MainWindow Error: 0 : [2022-07-26 13:51:15.4017] Error occured on run AppnIOS.app: couldn't connect to remote Mac: Invalid data type, INTEGER(02) is expected, but was DD
```

### Environment

<details>
<summary>Version information</summary>

![image](https://user-images.githubusercontent.com/8284579/180917377-5590012f-5ff3-4193-947f-dfa39f4ed718.png)
![image](https://user-images.githubusercontent.com/8284579/180920016-722ac7ed-7720-4957-bce9-9775de5de560.png)

</details>

**Comment by chamons** [comment]
Thanks for the feedback, unfortunately anything related to remote connection like `couldn't connect to remote Mac` needs to be handled by another team.

Please report it using [these instructions](https://developercommunity.visualstudio.com/report?space=8&entry=problem) and it'll get over to the folks who can look at it.
