### ISSUE TITLE
Debugging on iPhone simulator with M1 chip

### ISSUE THREAD

**Issue by sledderGIT** [xamarin/xamarin-macios#15580]
### Steps to Reproduce

1. Create an iOS project or use an existent one
2. Choose Debug | iPhoneSimulator configuration
3. Check the parametres of the project
4. for Debug | iPhoneSimulator it's possible to chose only x86 or x64  

### Expected Behavior

On Apple with m1 chip should be possible to chose ARM64 configuration for iPhoneSimulator

### Actual Behavior

for iPhoneSimulator it's possible to chose only x86 or x64  

### Environment

Visual Studio Community 2022 for Mac Preview
Version 17.3 Preview (17.3 build 2012)
Installation UUID: 4c0150cc-40b0-46da-9ab6-59caab85958d

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Версия: 6.2.1.2

Пакет SDK .NET (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.400-preview.22330.6/Sdks
Версия пакета SDK: 6.0.400-preview.22330.6
Пакеты MSBuild SDK: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

Пакет SDK .NET (x64)
Версия пакета SDK: 3.1.421

Среда выполнения (Arm64) .NET
Среда выполнения: /usr/local/share/dotnet/dotnet
Версия среды выполнения: 6.0.6

Среда выполнения .NET (x64)
Среда выполнения: /usr/local/share/dotnet/x64/dotnet
Версия среды выполнения: 3.1.27

Xamarin.Profiler
Версия: 1.8.0.19
Расположение: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Версия: 11

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin Designer
Version: 17.3.0.204
Hash: f5da0100a
Branch: remotes/origin/d17-3
Build date: 2022-07-14 20:16:42 UTC

Xamarin.Android
Версия: 13.0.0.0 (Visual Studio Community)
Фиксация: xamarin-android/d17-3/030cd63
Android SDK: /Users/alexeyshavrukov/Library/Developer/Xamarin/android-sdk-macosx
	Поддерживаемые версии Android:
		12.0 (уровень API 31)

Версия инструментов командной строки SDK: 7.0
Версия инструментов платформы SDK: 33.0.2
Версия инструментов сборки SDK: 32.0.0

Сведения о сборке: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Код EPL Android Designer доступен здесь:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Код EPL Android Designer доступен здесь:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.21
Hash: 91e34a0
Branch: remotes/origin/d17-3
Build date: 2022-07-14 20:16:47 UTC

Android Device Manager
Version: 0.0.0.1168
Hash: 4b9aaa3
Branch: 4b9aaa3
Build date: 2022-07-14 20:16:47 UTC

Build Information
Release ID: 1703002012
Git revision: f6bf6fa9b2a092abfd87672666c59e4ac2317b6c
Build date: 2022-07-14 20:14:11+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.3.0
Darwin 21.4.0 Darwin Kernel Version 21.4.0
    Mon Feb 21 20:35:58 PST 2022
    root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64

**Comment by chamons** [comment]
Thanks for the feedback. However, this is very clearly a question/bug on the IDE element of Visual Studio for Mac.

The team that can look into that is not accessible from Github.

Please follow [these instructions](https://developercommunity.visualstudio.com/report?space=41&entry=problem) to file an issue on Developer Community.
