### ISSUE TITLE
 Xamari.iOS 16.x release date or any beta version available to support iOS 16 Beta

### ISSUE THREAD

**Issue by mollea3** [xamarin/xamarin-macios#15581]
Hi Team,

We are working on the xamarin application which requires the latest toolchain along with the latest iOS Release, So the issue is the xamarin.iOS is not supported to create the IPA file for the iOS 16 Beta 

Please support us by knowing the Release date of the Xamarin.iOS or a Beta Version to Support the Xcode 14 Beta.

[https://docs.microsoft.com/en-us/xamarin/ios/release-notes/] is not updating with the latest version updates any more.

![image](https://user-images.githubusercontent.com/110099038/181305844-6c985e2d-60cc-4e78-a013-bce544209149.png)

Thanks,
Ajay M.

**Comment by ivanicin** [comment]
I was here only because I was interested in the same information, so I can't provide you with some official information.

But according to the https://github.com/xamarin/xamarin-macios/wiki/Xcode-Summer-Expectations the current situation is generally expected and you should expect iOS 16 beta releases soon on the preview channel. Also you need to install preview  edition of VS, currently option to use the preview channel for updates doesn't work: https://visualstudio.microsoft.com/vs/mac/preview/

**Comment by chamons** [comment]
Thanks @ivanicin - That is exactly the documentation I was going to link. 

We do the best we can to get previews throughout the summer but so far this year we have not had any released yet. It is actively being worked on, but beyond that I don't have anything I can share.

**Comment by dalexsoto** [comment]
Hello, you do not need to wait for our support packages, you can follow the work on our [xcode14](https://github.com/xamarin/xamarin-macios/commits/xcode14) branch and click on the GitHub status 

![image](https://user-images.githubusercontent.com/204671/181771824-24402d7c-336a-49ca-a797-5f663f2751bf.png)

Look for the `[CI] PKG-Xamarin.iOS-notarized` and `[CI] PKG-Xamarin.Mac-notarized` and you will be able to download the pkgs if you click on the `details` link.

You can also find details on what is bound here: https://github.com/xamarin/xamarin-macios/wiki/xcode14.0-Bindings-Status

**Comment by PavlosMavris** [comment]
Do we have any updates on this topic?

Yesterday, I downloaded the XCode 14 beta and connected it with Xamarin.iOS but I don't see any available simulators to run iOS 16. Do we know when it's going to be available?

**Comment by ivanicin** [comment]
@PavlosMavris this is marked as closed which means that you have all necessary information above. Based on your question, I don’t think that you have read them.

**Comment by PavlosMavris** [comment]
> @PavlosMavris this is marked as closed which means that you have all necessary information above. Based on your question, I don’t think that you have read them.

Thank you for replying, but I did read the above which were a few days ago and iOS 16 might be available from day to day on Xamarin that's why I asked if it's available yet, because I couldn't find any more related post than that.

**Comment by mollea3** [comment]
@dalexsoto 

> Hello, you do not need to wait for our support packages, you can follow the work on our [xcode14](https://github.com/xamarin/xamarin-macios/commits/xcode14) branch and click on the GitHub status
> 
> ![image](https://user-images.githubusercontent.com/204671/181771824-24402d7c-336a-49ca-a797-5f663f2751bf.png)
> 
> Look for the `[CI] PKG-Xamarin.iOS-notarized` and `[CI] PKG-Xamarin.Mac-notarized` and you will be able to download the pkgs if you click on the `details` link.
> 
> You can also find details on what is bound here: https://github.com/xamarin/xamarin-macios/wiki/xcode14.0-Bindings-Status

I Cannot see the Details link on the page which you asked me to refer to, 
![image](https://user-images.githubusercontent.com/110099038/182585826-9f19f48a-c8a6-41bc-8b47-4c3178a26dd4.png)
and another link **https://github.com/xamarin/xamarin-macios/wiki/xcode14.0-Bindings-Status**   which you have given is not opening and it is displaying Sorry about that. Please try refreshing and contact us if the problem persists. 
![image](https://user-images.githubusercontent.com/110099038/182586107-b9558239-0927-43e4-8724-55d29c55ec1b.png)


**Help me to download those Packages files to test with the Xcode 16 Beta 1, 2 & 3.**

**Comment by ivanicin** [comment]
@PavlosMavris then I don't think that you understood. First it is available if you want to follow @dalexsoto advice. Second if you install VS 2022 preview it will be available in the update as soon as update is published (I think it should be labeled iOS 15.99).

There is no thing like release date it will be released whenever it is ready. If you ask they can only tell you that at the moment it is not ready and that is the conclusion you can already make based on this thread that's why I have suggested you to read it.

**Comment by mollea3** [comment]
> @PavlosMavris then I don't think that you understood. First it is available if you want to follow @dalexsoto advice. Second if you install VS 2022 preview it will be available in the update as soon as update is published (I think it should be labeled Xamarin.iOS 15.99).
> 
> There is no thing like release date it will be released whenever it is ready. If you ask they can only tell you that at the moment it is not ready and that is the conclusion you can already make based on this thread that's why I have suggested you to read it.

@ivanicin  Is there any direct link to download the packages of the Xamarin.iOS 15.99.

**Comment by chamons** [comment]
The details link on say https://github.com/xamarin/xamarin-macios/commits/xcode14

![image](https://user-images.githubusercontent.com/6392201/182619959-560f8c54-8325-46c3-ac4e-c6f7c41b94fc.png)

Would be the red X's (since one test failed)

![image](https://user-images.githubusercontent.com/6392201/182620025-e7b89ca4-f4c8-4b46-a0a8-7dd97aeb8737.png)

**Comment by PavlosMavris** [comment]
So basically, there isn't any valid package at this moment

**Comment by mollea3** [comment]
> The details link on say https://github.com/xamarin/xamarin-macios/commits/xcode14
> 
> ![image](https://user-images.githubusercontent.com/6392201/182619959-560f8c54-8325-46c3-ac4e-c6f7c41b94fc.png)
> 
> Would be the red X's (since one test failed)
> 
> ![image](https://user-images.githubusercontent.com/6392201/182620025-e7b89ca4-f4c8-4b46-a0a8-7dd97aeb8737.png)

Thank and can we assume it's a Beta version of the Xamarin.iOS 16 ?

**Comment by ivanicin** [comment]
@chamons  While I asked all fellow developers for patience, at the moment I am not sure whether there will be any betas?

The exact date may vary, but based on the previous year the version of XCode that can be used to publish iOS 16 apps to App Store should be available in less than two weeks.

While I understand that you have declined to comment on the future availability of betas and I fully supported that standing month ago, at this point I think some communication is needed. Whatever is the plan there is very little time and developers should be informed to try to prepare for it ahead.

**Comment by davidortinau** [comment]
We are in the process of producing a beta for distribution in addition to the self-service CI builds. That release is imminent within weeks. Note that this will be Xcode 14 Beta 6 as of today, and only includes iOS as it appears Apple is delaying iPadOS and macOS.

**Comment by rafal-zielinski** [comment]
When can we expect an update?

**Comment by PavlosMavris** [comment]
> When can we expect an update?

Today Apple release the official Xcode 14 supporting iOS 16, so probably in the upcoming weeks we will have a Xamarin update too

**Comment by t9mike** [comment]
I've been using the bot releases of Xamarin.iOS for TestFlight Betas for weeks and also released my official version yesterday. No issues. Now I don't use anything iOS16 new in my core (Xamarin.iOS) app so I just needed Xamarin to support complication against Xcode14. I use Xcode/Swift/SwiftUI for my Apple watch app and widgets. 

I don't understand why Xamarin stopped having a pre-release channel for new Xcode and publish a blog post. Just makes life difficult and for more newbie Xamarin developers.

**Comment by skubo** [comment]
There was a time, when we had next day releases...

**Comment by Phenek** [comment]
Visual Studio should warn us to not update Xcode.
Regards,

**Comment by 3wcircus** [comment]
> Visual Studio should warn us to not update Xcode. Regards,

**Indeed**. Once my Dev team and I get a bit of breathing room, we are going to start making the move away from Xamarin/MAUI as once again we find ourselves in a situation where we can't even build on Mac after the official, and 'stable' update(s). 

I know all teams involved are working hard, but this has become a repetitive and costly occurrence for us and I am sure others. 

As @Phenek noted. Please do not recommend Xamarin/VS update without warning us about updating Xcode or other core components that may break our builds. 

We are on day 2 of trying to solve build issues introduced post the most recent update and now looks like the dev team and I will just have to manually revert to older versions of stuff just to proceed. That's costly and just plain lame imho. thx
