### ISSUE TITLE
INSTextInputClient causes crashes on Apple M1 systems

### ISSUE THREAD

**Issue by dvincent-devolutions** [xamarin/xamarin-macios#15591]
Using custom text view (that is not derived from NSTextView or NSText) which implements INSTextInputClient causes hang or crash.

I can pin point the problem to these 2 methods:
NSAttributedString GetAttributedSubstring(NSRange proposedRange, out NSRange actualRange)
CGRect GetFirstRect(NSRange characterRange, out NSRange actualRange)
 
### Steps to Reproduce

1. Set keyboard focus to a custom text view.
2. Long press a key for which there are accented versions ('a' for example). Alternatively: set the keyboard to pinyin mode and type.

### Expected Behavior

A popup for character selection is displayed.

### Actual Behavior

The app either hangs or crashes.

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Professional 2022 for Mac
Version 17.0.6 (build 4)
Installation UUID: 87fe0c2d-8649-4130-a05a-51403c93ecce

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.1.0-3.22075.3+592501cbb9c9394072a245c15b3458ff88155d85

NuGet
Version: 6.0.0.262

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.302/Sdks
SDK Versions:
	6.0.302
	6.0.300
	5.0.408
	5.0.407
	5.0.406
	3.1.421
	3.1.419
	3.1.418
	3.1.417
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.7
	6.0.5
	5.0.17
	5.0.16
	5.0.15
	3.1.27
	3.1.25
	3.1.24
	3.1.23

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 13.3 (20102)
Build 13E113

Xamarin.Mac
Version: 8.10.0.5 (Visual Studio Professional)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Professional)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin Designer
Version: 17.1.5.90
Hash: 53f47efde
Branch: remotes/origin/d17-0-vsmac
Build date: 2022-07-07 17:07:58 UTC

Xamarin.Android
Version: 12.3.3.3 (Visual Studio Professional)
Commit: xamarin-android/d17-2/4e061b7
Android SDK: /Users/Denis/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-2@9760f0a9
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.38.2@7b1e016
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-2@fc3c2ac

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.2.0.37
Hash: 7f5a6ef
Branch: remotes/origin/d17-2
Build date: 2022-07-07 17:08:03 UTC

Android Device Manager
Version: 0.0.0.1116
Hash: e47e6c8
Branch: remotes/origin/d17-2
Build date: 2022-07-07 17:08:03 UTC

Build Information
Release ID: 1700060004
Git revision: 056076d45137bf76b73f62f871524da8890deb05
Build date: 2022-07-07 17:06:08+00
Build branch: release-17.0
Build lane: release-17.0

Operating System
Mac OS X 12.4.0
Darwin 21.5.0 Darwin Kernel Version 21.5.0
    Tue Apr 26 21:08:22 PDT 2022
    root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/9213923/msbuild.binlog.zip)

### Example Project (If Possible)

[TextInputTest.zip](https://github.com/xamarin/xamarin-macios/files/9213925/TextInputTest.zip)

**Comment by chamons** [comment]
Hmm, I am having trouble reproducing your issue:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/6392201/181764811-7c7576f0-85e1-45dd-a0f3-d16941dc8207.png">

I'm holding down 'e' until that popup shows up, and then selecting a letter with a number:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/6392201/181764713-81cb0252-19ca-4377-b719-2d826ac65817.png">

I am on:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/6392201/181764945-d60ac0fd-6aeb-4221-835a-fbcc61b7429c.png">

Can you please confirm these are the steps to reproduce?

Also, having a crash report would be super useful here.
