### ISSUE TITLE
MT4109 error compiling registrar.h with Xcode 14 beta 4

### ISSUE THREAD

**Issue by dsmitchell** [xamarin/xamarin-macios#15596]
### Steps to Reproduce
1. Attempt to deploy app with Xcode 14 beta 4
2. Observe error

### Expected Behavior
No error

### Actual Behavior
MT4109

### Environment
Visual Studio for Mac Preview 3

### Build Logs
It seems Apple has completely removed GKPeerPickerControllerDelegate from iOS 16 SDK (it was deprecated a while ago)

While I am not allowed to paste the contents of the build logs, the error is here in registrar.m:

		@protocol (GKPeerPickerControllerDelegate), /* GameKit.IGKPeerPickerControllerDelegate */

And in registrar.h:

@interface GKPeerPickerControllerDelegate : NSObject<GKPeerPickerControllerDelegate> {
}
	-(id) init;
@end

**Comment by dsmitchell** [comment]
Ok, so after a few days of research I discovered that this is not really a problem. Apparently I need to be scanning the Xcode14 branch for artifacts (which were not generated for the latest commit), and btw also not allow the 15.1.0.5 build to update over this special Xcode14 version.

Speaking of which, as a developer only now looking to add iOS 16 support to a suite of Xamarin apps, it is very unclear what the path is -- at least I cannot google articles or find other resources that explain the plan for iOS 16 development in Visual Studio... Will I be forced to update all apps to .NET6 in order to fully support iOS 16? Or will there be a Xamarin.iOS v16 or something that will let me get by for a little while?

Thanks and best

**Comment by chamons** [comment]
As described by [this document](https://github.com/xamarin/xamarin-macios/wiki/Xcode-Summer-Expectations) usually by this point in the summer we would have a public preview channel for Xcode, but that has not been completed yet. 

Unfortunately we don't have written documentation on legacy/NET6 support for Xcode 14 yet, they are in the works, but I can tell you we are planning on releasing support for **both** this fall.

**Comment by dsmitchell** [comment]
Thank you @chamons for letting me know that I will still be able to use the Xamarin.iOS SDK. While I would love to eventually convert everything to NET6, I'm glad I have a shorter path in the meantime
