### ISSUE TITLE
Bug error MT5202: Native linking failed (iPhone Debug)

### ISSUE THREAD

**Issue by Stensan** [xamarin/xamarin-macios#15603]
In reply to this: https://github.com/xamarin/xamarin-macios/issues/10884#issuecomment-1125786846
I hope you can reproduce the problem with my sample project.

### Steps to Reproduce

1. Build my sample project in Debug Mode on an iPhone

### Expected Behavior
Should not fail with linking errors

### Actual Behavior
Fails with linking errors

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Enterprise 2019 (2)
Version 16.11.17
VisualStudio.16.Release/16.11.17+32630.194
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00433-90050-23218-AA372
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.110.1451
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.11.110.1451
Azure App Service Tools v3.0.0

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.197 (d16-11@6934992)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@476bb5b
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b


Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs

1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error : warning: '/Users/user/Library/Caches/Xamarin/mtbs/builds/App1/991bbf5377a496fa3d878fef9e85ac0bf48467b1b3c44e8f1b0919f3a8bdf7f4/obj/iPhone/Debug/device-builds/iphone10.4-15.5/mtouch-cache/arm64/Xamarin.iOS.dll.o' was built with class_ro_t pointer signing enabled, but previous .o files were not
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _NCryptSetProperty. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _NCryptGetProperty. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _HeapFree. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _GetProcessHeap. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CertNameToStrW. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _FormatMessageW. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptGetProvParam. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _HeapAlloc. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CertGetPublicKeyLength. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptDestroyHash. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CertGetCertificateContextProperty. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptMsgClose. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptFindOIDInfo. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptAcquireContextW. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptReleaseContext. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptMsgOpenToEncode. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptMsgGetParam. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CertDuplicateCertificateContext. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptEncodeObject. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptMsgControl. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptSetProvParam. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptDecodeObject. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _NCryptFreeObject. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptMsgUpdate. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptMsgOpenToDecode. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CertFreeCertificateContext. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CertCreateCertificateContext. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptAcquireCertificatePrivateKey. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5210: Native linking failed, undefined symbol: _CryptDestroyKey. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT5215: References to 'System.Net.Security' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT5215: References to 'crypt32' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT5215: References to 'advapi32' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning MT5215: References to 'ncrypt' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT5202: Native linking failed. Please review the build log.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): warning : '/Users/user/Library/Caches/Xamarin/mtbs/builds/App1/991bbf5377a496fa3d878fef9e85ac0bf48467b1b3c44e8f1b0919f3a8bdf7f4/obj/iPhone/Debug/device-builds/iphone10.4-15.5/mtouch-cache/arm64/Xamarin.iOS.dll.o' was built with class_ro_t pointer signing enabled, but previous .o files were not
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error : linker command failed with exit code 1 (use -v to see invocation)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

### Example Project (If Possible)

[App1.zip](https://github.com/xamarin/xamarin-macios/files/9242993/App1.zip)

**Comment by chamons** [comment]
So I can "reproduce" the error you are seeing, however it is not a bug in mtouch. Let me explain:

```
MTOUCH : warning MT5215: References to 'crypt32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'advapi32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'ncrypt' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : error MT5210: Native linking failed, undefined symbol: _NCryptSetProperty. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
```

Your application is attempting to link against many Windows only native libraries, which do not exist on iOS.

You can easily see this in your nuget references:
```
    <PackageReference Include="Microsoft.Win32.Primitives">
      <Version>4.3.0</Version>
    </PackageReference>
```
Anything using Win32 is not going to work on iOS.

Remove your Windows only dependencies and find replacements.
