### ISSUE TITLE
AOT MT3001 build error on System.ComponentModel.Composition.dll

### ISSUE THREAD

**Issue by zandhaai** [xamarin/xamarin-macios#15617]
### Steps to Reproduce

1. Install 'Visual Studio Preview 17.3.0 Preview 6.0' 
2. Pair to a Mac with Xamarin version 15.12.0.2 installed
3. Build the Xamarin application targeting iOS and Android

### Expected Behavior

Clean build.

## AOT build error
Could not AOT the assembly '/Users/<user>/Library/Caches/Xamarin/mtbs/builds/PSExampleApp.iOS/88726f8cb7d9087be428a54f01ab2154e4a4aa7b0edbfe41a7dc6d45616f77ed/obj/iPhone/Debug/mtouch-cache/3-Build/System.ComponentModel.Composition.dll'	PSExampleApp.iOS			

error MT1006: Could not install the application '/Users/palm/Library/Caches/Xamarin/mtbs/builds/PSExampleApp.iOS/88726f8cb7d9087be428a54f01ab2154e4a4aa7b0edbfe41a7dc6d45616f77ed/bin/iPhone/Debug/PSExampleApp.iOS.app' on the device 'Palm???s iPhone': AMDeviceSecureInstallApplicationBundle returned: 0xe8000067 (kAMDAPIInternalError).		 	0	

## Detailed Log

AOT Compilation exited with code 1, command: (TaskId:823)
MONO_PATH=/Users/palm/Library/Caches/Xamarin/mtbs/builds/PSExampleApp.iOS/88726f8cb7d9087be428a54f01ab2154e4a4aa7b0edbfe41a7dc6d45616f77ed/obj/iPhone/Debug/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/15.12.0.2/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32 --aot=mtriple=arm64-ios,data-outfile=/Users/palm/Library/Caches/Xamarin/mtbs/builds/PSExampleApp.iOS/88726f8cb7d9087be428a54f01ab2154e4a4aa7b0edbfe41a7dc6d45616f77ed/obj/iPhone/Debug/mtouch-cache/arm64/System.ComponentModel.Composition.aotdata.arm64,static,asmonly,direct-icalls,interp,full,readonly-value=ObjCRuntime.Runtime.Arch=i4/0,dwarfdebug,no-direct-calls,outfile=/Users/palm/Library/Caches/Xamarin/mtbs/builds/PSExampleApp.iOS/88726f8cb7d9087be428a54f01ab2154e4a4aa7b0edbfe41a7dc6d45616f77ed/obj/iPhone/Debug/mtouch-cache/arm64/System.ComponentModel.Composition.dll.s /Users/palm/Library/Caches/Xamarin/mtbs/builds/PSExampleApp.iOS/88726f8cb7d9087be428a54f01ab2154e4a4aa7b0edbfe41a7dc6d45616f77ed/obj/iPhone/Debug/mtouch-cache/3-Build/System.ComponentModel.Composition.dll (TaskId:823)
 Mono Ahead of Time compiler - compiling assembly /Users/palm/Library/Caches/Xamarin/mtbs/builds/PSExampleApp.iOS/88726f8cb7d9087be428a54f01ab2154e4a4aa7b0edbfe41a7dc6d45616f77ed/obj/iPhone/Debug/mtouch-cache/3-Build/System.ComponentModel.Composition.dll (TaskId:823)
AOTID B642F94E-6199-B397-DB37-63F80CE52EB2 (TaskId:823)
Could not load signature of System.ComponentModel.Composition.Hosting.CompositionContainer:ReleaseExports due to: Could not resolve type with token 0100003e from typeref (expected class 'System.Lazy`2' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Lazy`2 member:(null) (TaskId:823)
Failed to load method 0x60001b4 from '/Users/palm/Library/Caches/Xamarin/mtbs/builds/PSExampleApp.iOS/88726f8cb7d9087be428a54f01ab2154e4a4aa7b0edbfe41a7dc6d45616f77ed/obj/iPhone/Debug/mtouch-cache/3-Build/System.ComponentModel.Composition.dll' due to Could not resolve signature of method System.ComponentModel.Composition.Hosting.CompositionContainer:ReleaseExports. (TaskId:823)
Run with MONO_LOG_LEVEL=debug for more information. (TaskId:823)
AOT of image /Users/palm/Library/Caches/Xamarin/mtbs/builds/PSExampleApp.iOS/88726f8cb7d9087be428a54f01ab2154e4a4aa7b0edbfe41a7dc6d45616f77ed/obj/iPhone/Debug/mtouch-cache/3-Build/System.ComponentModel.Composition.dll failed. (TaskId:823)
8>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(235,3): error MT3001: Could not AOT the assembly '/Users/palm/Library/Caches/Xamarin/mtbs/builds/PSExampleApp.iOS/88726f8cb7d9087be428a54f01ab2154e4a4aa7b0edbfe41a7dc6d45616f77ed/obj/iPhone/Debug/mtouch-cache/3-Build/System.ComponentModel.Composition.dll'
8>  		 (TaskId:823)

### Environment

```
Microsoft Visual Studio Professional 2022
Version 17.3.0 Preview 6.0
VisualStudio.17.Preview/17.3.0-pre.6.0+32728.150
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA984
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.3.375.53775
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.375.53775
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.3.375.53775
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.3.0-3.22375.15+456937d952ad5c0930293ef32c4fbf8c844a9fef
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.20 (3f4cb00)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

OzCodePackage Extension   1.0
OzCodePackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22375.15+456937d952ad5c0930293ef32c4fbf8c844a9fef
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.3.0.295 (d17-3@321c85a)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.208 (remotes/origin/d17-3@e4f67afef)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.28 (9b3d244)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6


Xamarin.iOS and Xamarin.Mac SDK   15.12.0.2 (87f98a75e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Example Project (If Possible)

See: https://github.com/PalmSens/PSExampleApp.git
Branch: feature/iOSSupport

It is still a WIP version because the focus was first in getting the Android version up and running.

**Comment by chamons** [comment]
Building the example project (PSExampleApp.iOS) for Debug / Generic Device I was able to reproduce this.

The specific AOT error:

```
MONO_PATH=/Users/donblas/Projects/PSExampleApp/PSExampleApp/PSExampleApp.iOS/obj/iPhone/Debug/mtouch-cache/3-Build /Users/donblas/Programming/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/git/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32 --aot=mtriple=arm64-ios,data-outfile=/Users/donblas/Projects/PSExampleApp/PSExampleApp/PSExampleApp.iOS/obj/iPhone/Debug/mtouch-cache/arm64/System.ComponentModel.Composition.aotdata.arm64,static,asmonly,direct-icalls,interp,full,readonly-value=ObjCRuntime.Runtime.Arch=i4/0,dwarfdebug,no-direct-calls,outfile=/Users/donblas/Projects/PSExampleApp/PSExampleApp/PSExampleApp.iOS/obj/iPhone/Debug/mtouch-cache/arm64/System.ComponentModel.Composition.dll.s /Users/donblas/Projects/PSExampleApp/PSExampleApp/PSExampleApp.iOS/obj/iPhone/Debug/mtouch-cache/3-Build/System.ComponentModel.Composition.dll
    Mono Ahead of Time compiler - compiling assembly /Users/donblas/Projects/PSExampleApp/PSExampleApp/PSExampleApp.iOS/obj/iPhone/Debug/mtouch-cache/3-Build/System.ComponentModel.Composition.dll
    AOTID C2E3C537-69CD-C5CC-B261-C49B88213CD1
    Could not load signature of System.ComponentModel.Composition.Hosting.CompositionContainer:ReleaseExports due to: Could not resolve type with token 0100003e from typeref (expected class 'System.Lazy`2' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Lazy`2 member:(null)
    Failed to load method 0x60001b4 from '/Users/donblas/Projects/PSExampleApp/PSExampleApp/PSExampleApp.iOS/obj/iPhone/Debug/mtouch-cache/3-Build/System.ComponentModel.Composition.dll' due to Could not resolve signature of method System.ComponentModel.Composition.Hosting.CompositionContainer:ReleaseExports.
    Run with MONO_LOG_LEVEL=debug for more information.
    AOT of image /Users/donblas/Projects/PSExampleApp/PSExampleApp/PSExampleApp.iOS/obj/iPhone/Debug/mtouch-cache/3-Build/System.ComponentModel.Composition.dll failed.
```

Earlier in the PR I see:

```
    Encountered conflict between 'Reference:/Users/donblas/.nuget/packages/system.componentmodel.composition/6.0.0/lib/netstandard2.0/System.ComponentModel.Composition.dll' and 'Platform:System.ComponentModel.Composition.dll'. Choosing 'Reference:/Users/donblas/.nuget/packages/system.componentmodel.composition/6.0.0/lib/netstandard2.0/System.ComponentModel.Composition.dll' because AssemblyVersion '4.0.0.0' is greater than '2.0.5.0'.
...
    Encountered conflict between 'Reference:/Users/donblas/.nuget/packages/system.componentmodel.composition/6.0.0/lib/netstandard2.0/System.ComponentModel.Composition.dll' and 'Platform:System.ComponentModel.Composition.dll'. Choosing 'Reference:/Users/donblas/.nuget/packages/system.componentmodel.composition/6.0.0/lib/netstandard2.0/System.ComponentModel.Composition.dll' because AssemblyVersion '4.0.0.0' is greater than '2.0.5.0'.
```

So there is a conflict between The `System.ComponentModel.Composition.dll` library shipped in iOS and the one you are getting from nuget. 

If you dig into the project.assets.json files generated, which is a good way to checkout dependency chain, you'll see:

```
      "Microsoft.Windows.Compatibility/6.0.0": {
        "type": "package",
        "dependencies": {
          "Microsoft.Win32.Registry": "5.0.0",
          "Microsoft.Win32.Registry.AccessControl": "6.0.0",
          "Microsoft.Win32.SystemEvents": "6.0.0",
          "System.CodeDom": "6.0.0",
          "System.ComponentModel.Composition": "6.0.0",
```

And then you can see that you depend on that nuget directly:

```

  <ItemGroup>
    <PackageReference Include="LiteDB" Version="5.0.11" />
    <PackageReference Include="LiteDB.Async" Version="0.1.0" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="6.0.6" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0" />
    <PackageReference Include="PdfSharpCore" Version="1.3.32" />
  </ItemGroup>
```

These libraries are unlikely to work on iOS, and it seems like at least one failed to AOT.

I would suggest working to remove `Microsoft.Windows.Compatibility` and likely the rest will fix themselves. You may need to work with your 3rd party dependencies to get mobile friendly versions.

This may work on Android, as it is JIT compiled, and if you don't actively call the code that invokes Microsoft.Windows.Compatibility then you'll get away with it. Due to iOS preventing the use of JIT on device, this is not an option here.
