### ISSUE TITLE
Consider default `$(RuntimeIdentifier)` for MacCatalyst apps?

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-macios#15620]
### Steps to Reproduce

1. `dotnet new maccatalyst`
2. `dotnet build` or `dotnet build -c Release`

Even on an M1, I get a `maccatalyst-x64` app.

### Expected Behavior

I'm thinking it should do:

1. `Debug` - pick the RID on the machine you're building with. So an M1 gets a `maccatalyst-arm64` and Intel gets `maccatalyst-x64`, and this would help the developer loop? No Rosetta when your app launches for debugging/development?
2. `Release` - defaults to `RuntimeIdentifiers=maccatalyst-x64;maccatalyst-arm64` so `Release` builds get an app that supports both by default.

Users can override these defaults in their `.csproj`.

### Actual Behavior

It seems like it just defaults to `maccatalyst-x64`? Always?

### Environment

I was testing with the latest .NET 6 builds.

**Comment by chamons** [comment]
This seems like a good idea, adding to NET7 for consideration. 

FYI @dalexsoto @rolfbjarne

**Comment by jonathanpeppers** [comment]
This might also apply to `net6.0-macos` apps, but I didn't try one of those. I was testing MacCatalyst for a customer's MAUI app.

**Comment by spouliot** [comment]
> This might also apply to net6.0-macos apps,

Yes, I can confirm that this is the behaviour for `net6.0-macos` too.

IIRC @rolfbjarne wanted to ensure consistent output whatever the arch of the bots that build the app. The same logic would also apply to Catalyst apps.

**Comment by jonathanpeppers** [comment]
For now (maybe for .NET 7), I would consider just changing the default for `Release` builds and leave `Debug` builds as-is.

**Comment by rolfbjarne** [comment]
This is fixed now.
