### ISSUE TITLE
marshal-ilgen component must be included

### ISSUE THREAD

**Issue by naricc** [xamarin/xamarin-macios#15668]
After this change to mono, marshal-ilgen has been moved to a component: https://github.com/dotnet/runtime/pull/71203. This is a step in eventually allowing the component to be dropped when not needed (reducing the runtime size by around 100kb). For now, it must be available to the runtime. So it needs to be added here before this change is consumed by xamarin-macios.

@dalexsoto

**Comment by dalexsoto** [comment]
Thanks @naricc, can you work with @rolfbjarne on this?

Thanks!

**Comment by rolfbjarne** [comment]
Fixed here: https://github.com/xamarin/xamarin-macios/commit/62055c56fb6eb151ff9713a36e4ff8601f3438cc
