### ISSUE TITLE
Binding project error: "XXXXX.framework" is not a valid framework when building a MAUI app

### ISSUE THREAD

**Issue by dominic7125** [xamarin/xamarin-macios#15673]
### Steps to Reproduce
0. Use PC to connect to Mac via Visual Studio
1. Creata a iOS binding library, and add a framework.
2. Create a MAUI app then reference the binding project.
3. Build the iOS app

### Expected Behavior
Build success

### Actual Behavior
Build error

### Environment
PC side - 
Visual Studio 2022 
Version 17.3.0 Preview 6.0

Mac side - 
Xamarin.iOS 15.11.0.308

### Build Logs

[buildlog.zip](https://github.com/xamarin/xamarin-macios/files/9315717/buildlog.zip)
2>Build FAILED.
2>
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\15.4.446-ci.-release-6-0-4xx.446\tools\msbuild\iOS\Xamarin.Shared.targets(143,3): warning : Expected a 'manifest' file in the directory D:\Projects\Xamarins\MAUI\MauiApp1\iOSBinding1\bin\Debug\net6.0-ios\iOSBinding1.resources.
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.4.446-ci.-release-6-0-4xx.446\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(327,3): warning MT1302: Could not extract the native library 'XamarinTest.framework' from '/Users/dominic/Library/Caches/Xamarin/mtbs/builds/MauiApp1/2167a7a3d930cd394f4a24fa19b952447e1f67b8fc4e2d210c5522bba8a914ab/obj/Debug/net6.0-ios/ios-arm64/linker-cache/XamarinTest.framework.zip'. Please ensure the native library was properly embedded in the managed assembly (if the assembly was built using a binding project, the native library must be included in the project, and its Build Action must be 'ObjcBindingNativeLibrary').
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.4.446-ci.-release-6-0-4xx.446\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(327,3): error MT0140: File '/Users/dominic/Library/Caches/Xamarin/mtbs/builds/MauiApp1/2167a7a3d930cd394f4a24fa19b952447e1f67b8fc4e2d210c5522bba8a914ab/obj/Debug/net6.0-ios/ios-arm64/linker-cache/XamarinTest.framework/XamarinTest' is not a valid framework.
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.4.446-ci.-release-6-0-4xx.446\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(327,3): error MT2342: The linker step 'Extract Binding Libraries' failed during processing: File '/Users/dominic/Library/Caches/Xamarin/mtbs/builds/MauiApp1/2167a7a3d930cd394f4a24fa19b952447e1f67b8fc4e2d210c5522bba8a914ab/obj/Debug/net6.0-ios/ios-arm64/linker-cache/XamarinTest.framework/XamarinTest' is not a valid framework.
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.4.446-ci.-release-6-0-4xx.446\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(327,3): error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information.
2>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\15.4.446-ci.-release-6-0-4xx.446\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(368,3): error MSB3371: The file "obj\Debug\net6.0-ios\ios-arm64\linked\Link.semaphore" cannot be created. Could not find a part of the path 'D:\Projects\Xamarins\MAUI\MauiApp1\MauiApp1\obj\Debug\net6.0-ios\ios-arm64\linked\Link.semaphore'.
2>    2 Warning(s)
2>    4 Error(s)

### Example Project (If Possible)

[MauiApp1.zip](https://github.com/xamarin/xamarin-macios/files/9315718/MauiApp1.zip)

**Comment by dalexsoto** [comment]
Hello, the problem seems to be with the Visual Studio on Windows integration, unfortunately that team is not accesible via GitHub. You will need to file an issue using Visual Studio itself so please file an issue via [these instructions](https://developercommunity.visualstudio.com/report?space=8&entry=problem), by doing so VS will collect the necessary logs and you can provide the info to the team that can assist you with your issue.
