### ISSUE TITLE
Build net6.0-ios apps with .NET 7 SDK

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/xamarin-macios#15672]
Sister issue to https://github.com/xamarin/xamarin-android/issues/7252

### Affected platform version

.NET 6 / .NET 7

### Description

Context: https://github.com/dotnet/maui/issues/9192

We will have to likely do something in our Manifest template files:

https://github.com/xamarin/xamarin-macios/blob/main/dotnet/targets/WorkloadManifest.MacCatalyst.template.json

https://github.com/xamarin/xamarin-macios/blob/main/dotnet/targets/WorkloadManifest.iOS.template.json

https://github.com/xamarin/xamarin-macios/blob/main/dotnet/targets/WorkloadManifest.macOS.template.json

https://github.com/xamarin/xamarin-macios/blob/main/dotnet/targets/WorkloadManifest.tvOS.template.json

We might have to do something to bring in .NET 6 packs appropriately from dotnet/runtime.

**Comment by rolfbjarne** [comment]
This is already in progress here: https://github.com/xamarin/xamarin-macios/pull/15469

**Comment by rolfbjarne** [comment]
This is fixed now.
