### ISSUE TITLE
Native linking failed, undefined symbol: xxxxxxxx. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in

### ISSUE THREAD

**Issue by dominic7125** [xamarin/xamarin-macios#15674]
The iOS app build fail when using a iOS binding project with static framework.
(It has no problem to build with dynamic framework)

### Steps to Reproduce

1. Create iOS Blinding Library(Xamarin)
2. Add static framework (Mach-O static)
3. Create Xamarin.Form App
4. Reference the binding project in the iOS app project

### Expected Behavior
Build success

### Actual Behavior
Build fail

### Environment
Visual Studio 2022 Version 17.2.6
Xamarin.iOS on Mac Version 15.10.0.5

### Build Logs
[build_log_xamarin_ios_binding_static_framework.txt](https://github.com/xamarin/xamarin-macios/files/9316266/build_log_xamarin_ios_binding_static_framework.txt)

### Example Project (If Possible)
[Sample.zip](https://github.com/xamarin/xamarin-macios/files/9316276/Sample.zip)

**Comment by dalexsoto** [comment]
I am able to repro the issue using VSMac and console ruling out VS Win, this is a problem with the way the static library is build, it seems like the static library is building against swift libraries which are not getting linked in, have you tried using https://www.nuget.org/packages/Xamarin.iOS.SwiftRuntimeSupport? or manually linking the swift libraries that you rely on? 

Also what version of Xcode are you using?

**Comment by dominic7125** [comment]
@dalexsoto 

1. I installed Xamarin.iOS.SwiftRuntimeSupport, it doesn't work.
2. I just created a blank swift library and set MachO-type to static, I didn't link any swift library.
Here is the xcode project.
[XamarinTest.zip](https://github.com/xamarin/xamarin-macios/files/9337304/XamarinTest.zip)
3. The version of Xcode is 13.4.1

**Comment by dominic7125** [comment]
I added this in the link flags of the binding project, it didn't work.
`-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos -Wl,-rpath -Wl,@executable_path/Frameworks`

**Comment by maxgrig** [comment]
@dominic7125 Had a similar issue. I was able solve it by providing linker runtime path for swift libraries.

Try following Linker Flags:
`-L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos -Wl,-rpath -Wl,/usr/lib/swift -Wl,-rpath -Wl,@executable_path/Frameworks`

**Comment by dominic7125** [comment]
@maxgrig Yes I did already have the path for Linker Flags in the sample code.
May I ask what's the version of your Visual studio?
Were you using a static swift framework too?

**Comment by rolfbjarne** [comment]
Looks like there are a couple of solutions here:

* https://github.com/xamarin/xamarin-macios/issues/15674#issuecomment-1243713674
* https://github.com/xamarin/xamarin-macios/issues/17179#issuecomment-1397065430

So I'm going to close this.
