### ISSUE TITLE
[illink] Turn on serialization discovery in .NET 7

### ISSUE THREAD

**Issue by sbomer** [xamarin/xamarin-macios#15676]
https://github.com/dotnet/linker/pull/2929 made serialization heuristics opt-in. To preserve the .NET 6 behavior, the Xamarin SDK should opt in to the old behavior by setting `<_ExtraTrimmerArgs>--enable-serialization-discovery</_ExtraTrimmerArgs>`. This can be done once using an SDK with https://github.com/dotnet/sdk/pull/26993 (which will be part of rc1).

**Comment by rolfbjarne** [comment]
Fixed here: https://github.com/xamarin/xamarin-macios/commit/62055c56fb6eb151ff9713a36e4ff8601f3438cc
