### ISSUE TITLE
Attempting to JIT compile method while running in aot-only mode

### ISSUE THREAD

**Issue by rogerbriggen** [xamarin/xamarin-macios#15681]
### Steps to Reproduce

1.  Get the example from https://github.com/rogerbriggen/mauiAotProblem or the .zip below
2. Compile in Release mode for iOS for a real device
3. Run app on device
4. Press Automap button -> see exception

### Expected Behavior

The automap function should be executed without exception

### Actual Behavior

System.ExecutionEngineException (Attempting to JIT compile method xxx while running in aot-only mode.). See also Readme.md for screenshots and the stacktrace

### Environment

VS 2022 17.4.0 Preview 1.0 
iOS 15.6

### Example Project (If Possible)

[mauiAotProblem.zip](https://github.com/xamarin/xamarin-macios/files/9333532/mauiAotProblem.zip)

**Comment by chamons** [comment]
Starting off, this sounds like a bug for the 3rd party automapper library being used, but ignoring that for a moment, taking a look at the source code for that library I see:

```
src/AutoMapper/Execution/ProxyGenerator.cs:using System.Reflection.Emit;
src/AutoMapper/Execution/ProxyGenerator.cs:        private static readonly LockingConcurrentDictionary<TypeDescription, Type> ProxyTypes = new(EmitProxy);
src/AutoMapper/Execution/ProxyGenerator.cs:        private static Type EmitProxy(TypeDescription typeDescription)
src/AutoMapper/Execution/ProxyGenerator.cs:                Debug.WriteLine(typeName, "Emitting proxy type");
src/AutoMapper/Execution/ProxyGenerator.cs:                addIl.Emit(OpCodes.Ldarg_0);
```

So we are code generating proxy objects with Reflection.Emit. As [documented](https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations#systemreflectionemit) this is restricted by the iOS kernel from Apple.

In theory this use case is solved by the interpreter, but when I enable that the applications crashes on launch. 

The crash report is not very enlightening:

https://gist.github.com/chamons/61fb48f248cd906c6e94d678fb779935

@rolfbjarne - Any thoughts? What is the status of interpreter on NET6?

**Comment by rolfbjarne** [comment]
The interpreter works. Try adding this to the csproj:

```xml
<PropertyGroup>
    <UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```

**Comment by chamons** [comment]
Turns out my crash was because the build was stale, a clean made it go away.

After that, I was able to hit the automapper button successfully..

So in short:

- The library in question using Reflection.Emit to do it's dependency injection
- That is not supported on iOS by default, which is why you are seeing the JIT error
- We have a feature, the interpreter, which enables this at a mild performance hit (why it isn't on by default)
- Add this to your project and it should work:

```
<PropertyGroup>
    <UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```
