### ISSUE TITLE
Other -> Custom -> macOS Application doesn't allow adding new UI designer component (.xib/.storyboard)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#15691]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Other---Custom---macOS-Application-doe/10118455)._

---
I’m in the process of attempting to migrate our macOS Cocoa application to .Net 6. For libraries (not executable application), this seems to work pretty well with some tweeking of the csproj. For applications, I’m encountering some issues.

The first issue is as described in the title. If you create a .Net 6 macOS Application from the Other -> Custom category (see macOS Application.png attachment), said application will not allow adding new UI designer component (View/ViewController, Window/WindowController, be it .xib or .storyboard).

I’ve attached two other screenshots to show what category I would expect to be present (New File - Mac Category.png) but is not (New File - No Mac Category.png).

The second issue is that when you open, for instance, the Main.storyboard file that is created by default, the Xcode project is not generated, this makes it impossible to create new Outlets or Action on UI elements (buttons, text field, etc.).

The last issue is that, for a view/window that already existed (for instance, with a project that you convert, instead of being created from scratch), the outlet do not seem to be properly linked at run time. Their properties remains null, breaking all sort of important behavior.

Is any of those issues already known? Is there any plan to work on those? I realize that this is all in a Preview state, I just want to be sure I know what to expect for the future.

---
#### Feedback Bot on 8/11/2022, 07:55 PM: 

(private comment, text removed)
#### Feedback Bot on 8/15/2022, 02:09 AM: 

(private comment, text removed)
#### Theresa Zhang[MSFT] on 8/15/2022, 02:37 AM: 

(private comment, text removed)
#### Xavier Fortin on 8/15/2022, 05:55 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by chamons** [comment]
This is being tracked in internal bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1592649/?triage=true

**Comment by xfortin-devolutions** [comment]
@chamons I can't view, let alone track, the ticket you've linked. Is there a way for me to get updated when this is fixed?

**Comment by chamons** [comment]
That is a valid concern, let me see if there is anything I can do.

**Comment by snechaev** [comment]
Here is a public tracking available for almost the same issues
* https://developercommunity.visualstudio.com/t/Cant-add-xib-into-net6-sdk-style-projec/10119150
* https://developercommunity.visualstudio.com/t/Xcode-integration-in-Visual-Studio-2022/1615783

I'm unsure it's 100%  the same, but looks pretty similar.

**Comment by chamons** [comment]
https://github.com/xamarin/xamarin-macios/issues/15836 will be where we track this, as it has been bounced from the IDE (where it must be tracked in Developer Community) to the SDK (where we use Issues).
