### ISSUE TITLE
[msbuild] Build/publish of projects with native references with multiples periods in the framework name copies them into the bundle with an incorrect path

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#15727]
### Steps to Reproduce

1.  Create a new MAUI (or iOS) project with a native reference named `Library.Document.Test.framework` (or use the private sample from https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1589209
2. Build
3. Look inside the bundle, it will be copied in as `Library.Document.framework` incorrectly. 

### Work Around

As the defect appears to be in _ComputeFrameworkFilesToPublish [here](https://github.com/xamarin/xamarin-macios/blob/main/dotnet/targets/Xamarin.Shared.Sdk.targets#L656-L659) I was able to correct it with this hack:

```
   <Target Name="HackNativeReferenceTargetDirecotry" AfterTargets="_ComputeFrameworkFilesToPublish">
      <ItemGroup>
         <_DirectoriesToPublish Update="@(_DirectoriesToPublish)">
            <TargetDirectory>$(_RelativePublishDir)$(_AppBundleFrameworksDir)\Library.Document.Test.framework</TargetDirectory>
         </_DirectoriesToPublish>
      </ItemGroup>
   </Target>
```

It seems that `%(Filename)` is not doing us any favors with directories with additional dots in their file name. 

### Expected Behavior

Copied in as Library.Document.Test.framework

### Actual Behavior

Name is truncated.

### Environment

https://gist.github.com/chamons/bb1f6cc72ae2b3e8c490c3c244c3a2bf

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/9396888/msbuild.binlog.zip)

### Example Project (If Possible)

See https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1589209

**Comment by chamons** [comment]
Adding to NET7 for consideration. FYI @rolfbjarne as you wrote this logic originally.

**Comment by TamerIrdais** [comment]
I tried the workaround in the bug description and it worked for single framework, but how do I do it for multiple frameworks because when I tried to add my other frameworks after duplicating your code with different framework name it took the last updated framework path and copied all frameworks inside it, so it didn’t work for me unless I can’t figure out the correct syntax to do it, can you please help?

**Comment by chamons** [comment]
It took a bit of hacking, but I believe this will work:

```

   <Target Name="PreHackNativeReferenceTargetDirecotry" BeforeTargets="_ComputeFrameworkFilesToPublish">
      <ItemGroup>
         <_FrameworkNativeReference Update="@(_FrameworkNativeReference)">
            <_OriginalName>$([System.IO.Path]::GetFileName('%(_FrameworkNativeReference.Identity)'))</_OriginalName>
         </_FrameworkNativeReference>
      </ItemGroup>
   </Target>

   <Target Name="HackNativeReferenceTargetDirecotry" AfterTargets="_ComputeFrameworkFilesToPublish">
      <ItemGroup>
         <_DirectoriesToPublish Update="@(_DirectoriesToPublish)">
            <TargetDirectory>$(_RelativePublishDir)$(_AppBundleFrameworksDir)%(_DirectoriesToPublish._OriginalName)</TargetDirectory>
         </_DirectoriesToPublish>
      </ItemGroup>
   </Target>
```

I tested it with:

```
   <ItemGroup Condition="$(TargetFramework.StartsWith('net6.0-ios'))">
      <NativeReference Include="Native References/Library.Document.Test.framework" Kind="Framework"/>
      <NativeReference Include="Native References/Other.Library.Document.Test.framework" Kind="Framework"/>
   </ItemGroup>
```

and both ended up correct in the bundle.

**Comment by TamerIrdais** [comment]
Thank you @chamons your workaround worked, but when do you expect this to be fixed the right way without the need for this workaround?

**Comment by chamons** [comment]
Given the fact that we are in the middle of Xcode 14 work right now, I suspect the earliest we would be able to look at it will be in .NET 7 timeframe.
