### ISSUE TITLE
[macOS] Cannot create custom NSTextList any more in .NET6

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#15766]
The bindings for the [initWithMarkerFormat:options:](https://developer.apple.com/documentation/uikit/nstextlist/1526123-initwithmarkerformat?language=objc) method of `NSTextList` &  [NSTextListMarkerFormat](https://developer.apple.com/documentation/uikit/nstextlistmarkerformat?language=objc) has been changed in .NET6:
`NSTextListMarkerFormat` was bounds as string in legacy Xamarin, now it is an enum. This prevents me from using code that used to work in legacy Xamarin, e.g. creating `NSTextLists` with a custom format or checking if a given `NSTextList` is representing an unordered or ordered list.

### Steps to Reproduce

```
bool makeUnorderedList = false;
var textList = new NSTextList(makeUnorderedList ? "•" : "{decimal}.", (NSTextListOptions)0);
var isUnorderedList = textList.MarkerFormat.Contains("•");
var isOrderedList = textList.MarkerFormat.Contains("{decimal}.");
```

### Expected Behavior

Compiles and works (as it did in legacy Xamarin)

### Actual Behavior

Compiler error - requires `NSTextListMarkerFormat` enum instead of string.

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac Preview
Version 17.4 Preview (17.4 build 715)
Installation UUID: df2eb712-7703-4919-aeb8-0288506f2dbe

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-1.22371.1+c07f2571612b471671c809b5b0db59b0c37aab57

NuGet
Version: 6.2.1.2

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.400/Sdks
SDK Version: 6.0.400
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.8
	6.0.0

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Version: 6.0.8

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 17.4.0.32
Hash: 439b92ed7b
Branch: remotes/origin/d17-4
Build date: 2022-08-04 16:29:17 UTC

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.4.0.24
Hash: b3b6672
Branch: remotes/origin/HEAD~1
Build date: 2022-08-04 16:29:21 UTC

Android Device Manager
Version: 0.0.0.1179
Hash: 0f220c0
Branch: main
Build date: 2022-08-04 16:29:21 UTC

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 15.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:55-0400

Build Information
Release ID: 1704000715
Git revision: 09071dadfc1b81e4f0e2c9505cd8a5ef0b41d312
Build date: 2022-08-04 16:26:39+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 12.5.1
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Wed Aug 10 14:28:35 PDT 2022
    root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64

```

</details>

**Comment by chamons** [comment]
The smart enum it was replaced with not not support the arbitrary values [noted in the documentation](https://developer.apple.com/documentation/uikit/nstextlist/1526123-init?changes=l_4_1_4__9_5):

```
The marker format is specified as a constant string, except for a numbering specifier, which takes the form {keyword}. 

The currently supported values for keyword include:
    box
    check
    circle
    diamond
    disc
    hyphen
    square
    lower-hexadecimal
    upper-hexadecimal
    octal
    lower-alpha or lower-latin
    upper-alpha or upper-latin
    lower-roman
    upper-roman
    decimal

Thus, for example, @"({decimal})" would specify the format for a list numbered (1), (2), (3), and so on, and @"{upper-roman}" would specify the format for a list numbered I, II, III, IV, and so on. (All of these keywords are included in the Cascading Style Sheets level 3 specification.)
```

Normally you'd use NSTextListMarkerFormatsExtensions.GetValue(NString) to get an enum value, but that won't work here.

I'll try to hack out a work around for you shortly.

**Comment by chamons** [comment]
This bug is extra bad, because just reading the MarkerFormat property will crash if you have the NSTextList setup in one of the non-enum formats. 

@tipa - Try this work around and let me know if it works for you: https://gist.github.com/chamons/4ced15b70e5a12cfbd80b0f13f9b2ca1

**Comment by tipa** [comment]
@chamons thanks for the workaround. In a quick test, it appears to work correctly after fixing the typo here:
https://gist.github.com/chamons/4ced15b70e5a12cfbd80b0f13f9b2ca1#file-patch-cs-L13
It should be `var fmt = NSString.CreateNative(format);`, 

However, I will not use/test the workaround in production yet because of this blocking issue: https://github.com/xamarin/xamarin-macios/issues/15744
