### ISSUE TITLE
issue quit unexpectedly net maui on MAC

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#15789]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/issue-quit-unexpectedly-net-maui-on-MAC/10123513)._

---
Hi all
I just install leastet VS for MAC version and when I run my app appear this error message.
quit unexpectedly .
Click Reopen to open this application again. Click Report to see more detailed information and send a report to Apple.

And when I click on Reopen and show me again the same message, then click on report to.. and I try again and same result

---
#### Javier Florian on 8/17/2022, 09:35 AM: 

(private comment, text removed)
#### Feedback Bot on 8/17/2022, 06:51 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by chamons** [comment]
Moving back to DevCom.
