### ISSUE TITLE
Framework package from an unidentified developer

### ISSUE THREAD

**Issue by bbreak** [xamarin/xamarin-macios#15806]
### Steps to Reproduce

1. Download the Mono framework package.
2. Double-click the package to open it.

### Expected Behavior
Installer opens.

### Actual Behavior
An error dialog appears saying the package can't be opened because it is from an unidentified developer, and it may contain malware. The user must manually bypass Gatekeeper using the context menu in the Finder.

What obstacles prevent notarizing this framework package?

### Environment

<details>
<summary>
Mono Framework MDK
Runtime:
	Mono 6.12.0.185 (2020-02/a96bde9730e) (64-bit)
	Package version: 612000185</summary>
</details>
MacOS "Monterey" 12.5.1

### Build Logs

n/a

### Example Project (If Possible)

n/a

**Comment by bbreak** [comment]
And now I realize I may have opened this issue on the wrong project. I'm trying to file against the primary Mono framework that gets downloaded when you're trying to install Visual Studio for MacOS. This project is specifically the framework for Mono integration with native Apple APIs, isn't it?

**Comment by rolfbjarne** [comment]
Correct, you want this: https://github.com/mono/mono/issues.

**Comment by bbreak** [comment]
Got it. Thanks, rolfbjarne!
