### ISSUE TITLE
Can't add xib into net6 sdk style project

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#15807]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cant-add-xib-into-net6-sdk-style-projec/10119150)._

---
\[severity:I’m unable to use this version\] \[regression\] \[worked-in:2019\]  
When working with cocoa app project, created with `dotnet new macos` I can’t add any mac-specific files like xib/window controller/etc.

Steps

*   create new cocoa app project with CLI `dotnet new macos` (you may need to install appropriate project template to do this)
*   open project into VS for Mac
*   int the solution explorer right-click the project (exactly the project, not a solution) and select Add - New file.
*   Observer that it’s no `Mac` folder in the list + there is no xib and other mac-specific items in any groups available.

Note: if I will create a old-style mono-based non-sdk style cocoa app project with VSfM, I will be able to add mac-specific items.

Screenshot of current "New File" dialog - no mac specific items present
![screenshot.png](https://aka.ms/dc/image?name=B3bb7e4145c484df7b73923db664b04f2637959035965030052_screenshot.png&tid=3bb7e4145c484df7b73923db664b04f2637959035965030052)

---
#### Feedback Bot on 8/14/2022, 06:50 PM: 

(private comment, text removed)
#### Feedback Bot on 8/25/2022, 00:52 AM: 

(private comment, text removed)
#### Feedback Bot on 8/25/2022, 09:09 AM: 

(private comment, text removed)

---
#### Feedback Bot solved on 8/26/2022, 03:31 PM, 0 votes: 

<p>Thanks for taking the time to report this issue! It seems to us that it’s describing the same thing as <a target='_blank' href="https://github.com/xamarin/xamarin-macios/issues/1569">another one</a>. We’ve closed this one as a duplicate and transferred all votes from this ticket to the other one. Please follow along on the linked ticket to communicate with the team, see updates on status, and help provide any needed diagnostic info. For more information, see our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines">issue reporting guidelines</a>.</p>
<p>Happy coding!</p>

#### Sergey Nechaev on 8/28/2022, 10:53 PM: 

(private comment, text removed)

**Comment by snechaev** [comment]
It looks weird that this report of mine was moved from the VS feedback to xamarin issues. Doubly weird as it is already similar issues here and on the VS feedback, which are closed in favour of https://developercommunity.visualstudio.com/t/Xcode-integration-in-Visual-Studio-2022/1615783

**Comment by chamons** [comment]
We have multiple duplicate issues floating around, some of them from Developer Community. I've created https://github.com/xamarin/xamarin-macios/issues/15836 as the single issue to track.

Sorry for the trouble.
