### ISSUE TITLE
Binding to xcframework for net6.0-maccatalyst requires special packaging

### ISSUE THREAD

**Issue by mattjohnsonpint** [xamarin/xamarin-macios#15810]
This is more of an FYI of an ecosystem issue that impacts Xamarin users rather than a bug report.  I wanted to bring it to your attention in case there's something more that can be done.

When building a binding project that targets `net6.0-maccatalyst` and includes a `<NativeReference Include="..." Kind="Framework" />` that points to an xcframework,  there must be a platform target of `ios-arm64_x86_64-maccatalyst` built and included in the xcframework.

Unfortunately, if that package is built with [Carthage](https://github.com/Carthage/Carthage) (and many are), such output doesn't currently exist.  There is a PR in progress to add support, but it needs some help before it can be merged in.  See https://github.com/Carthage/Carthage/pull/3235.  Perhaps someone can lend a hand there?

See https://github.com/getsentry/sentry-cocoa/issues/2031 for my experiences related to this while authoring Xamarin bindings for [sentry-cocoa](https://github.com/getsentry/sentry-cocoa) to [sentry-dotnet](https://github.com/getsentry/sentry-dotnet).

Thanks.

**Comment by chamons** [comment]
That's good to know, we'll keep it in mind for triage if others run into it. We don't have any contacts with the Carthage team, and that PR appears to be open for a year at this point. Consider reaching out to the Carthage team directly and asking what's needed to move the PR forward.
