### ISSUE TITLE
[net6/7] No macOS binding library template

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#15839]
There is no template for macOS binding projects from what I can tell:
```
 dotnet new --list | grep Binding
Android Java Library Binding                  android-bindinglib  [C#]        Android/Mobile                                           
iOS Binding Library                           iosbinding          [C#]        iOS/Mobile                                               
MacCatalyst Binding Library                   maccatalystbinding  [C#]        macOS/Mac Catalyst 
```

Though maccatalystbinding has a description of macOS it in, the generated project has:

```    <TargetFramework>net6.0-maccatalyst</TargetFramework>```

**Comment by chamons** [comment]
FYI @dalexsoto as another potential issue to fix while we're working on templates this fall.

**Comment by rolfbjarne** [comment]
Doesn't look like there's a tvOS binding library template either.
