### ISSUE TITLE
[net6/7] Templates for "Add File" feature in VSfM

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#15836]
As discussed in many places:

https://developercommunity.visualstudio.com/t/Other---Custom---macOS-Application-doe/10118455
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1592649
https://github.com/xamarin/xamarin-macios/issues/15807
https://github.com/xamarin/xamarin-macios/issues/15691

The move to .NET 6 broken "Add File" for non-MAUI projects.

Discussions with the IDE team have stated there is support for adding these to the workload, and MAUI does that today, though some of the format may be inconsistently documented. 

We should do this in the .NET 7 timeframe if not sooner. 

## Expected Behavior

See these examples from legacy XI/XM projects:

![image](https://user-images.githubusercontent.com/6392201/187779957-28eecca4-e9c9-4249-a1e2-214e5bbf9ccb.png)

![image](https://user-images.githubusercontent.com/6392201/187780052-e1dc71fc-dc0a-4d78-96dd-1f1a17627a0e.png)

(This is is same for XI and XM)
![image](https://user-images.githubusercontent.com/6392201/187779971-87028bc3-9254-4e67-9389-e5ca9dff0ef3.png)

(This is is also same for XI and XM)
![image](https://user-images.githubusercontent.com/6392201/187779992-bccec8a7-de44-4881-bed5-a6e3814f3ee6.png)

**Comment by rolfbjarne** [comment]
See this issue for where the VS(Mac) templates are: https://github.com/xamarin/xamarin-macios/issues/10747#issue-819116282

**Comment by rolfbjarne** [comment]
Related PRs for xamarin-android: https://github.com/xamarin/xamarin-android/pull/7349, https://github.com/xamarin/xamarin-android/pull/7366

**Comment by rolfbjarne** [comment]
We're going to start with a few templates:

* Storyboard
* View
* View Controller
* Window
