### ISSUE TITLE
Crash with custom menu Item

### ISSUE THREAD

**Issue by yevgeny-sotnikov** [xamarin/xamarin-macios#15865]
After update Xamarin.Mac to version 8.12.0.2(d17-3) app crashes on call             

NSApplication.SharedApplication.SendAction(Action, Target, this);

Text of exception:

Failed to marshal the Objective-C object 0x6000000f2760 (type: Crashapp_MyMenuItem). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Crashapp.MyMenuItem' does not have a constructor that takes one IntPtr argument).

Seems like Xamarin.Mac starts to create copy of NSMenuItem instace with pre-defined constructor. Xamarin.Mac version 8.10.0.5(d17-2) does not have such issue - it simply send a reference to menu items which allready exists
### Steps to Reproduce

1. Click by button
2. Click by one of menu items
3. Got crash

### Expected Behavior
App must receive call to ViewController.MenuItemSelected
### Actual Behavior
Crash happens
### Environment

<details>
<summary>Version information</summary>

```
Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400
```

</details>

### Example Project (If Possible)

[Crashapp.zip](https://github.com/xamarin/xamarin-macios/files/9489513/Crashapp.zip)

**Comment by chamons** [comment]
So, I believe this is something that has always been wrong, but a recent changes appears to be making is crash.

The top level issue is that your MyMenuItem doesn't have an IntPtr constructor, so it can't be surfaced in the callback.

See https://gist.github.com/chamons/28ca27ed3bba30f7a2133a8e032b2c0b for an example that doesn't crash.

However, that does provide this print on use:

2022-09-06 12:56:35.029 Crashapp[61709:13026115] Tried to create a managed reference from an object that already has a managed reference (type: Crashapp.MyMenuItem)

So something isn't exactly correct still. 

Honestly though, much of the time you need to reach for Actions and Selectors you are doing something the hard way. I believe your use case can be solved without a custom NSMenuitem subclass, selectors, or actions:

```
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

            for (int i = 0; i < 5; i++)
            {
                var item = new NSMenuItem();
                item.Activated += Item_Activated;
                _myMenu.AddItem(item);
            }

            // Do any additional setup after loading the view.
        }

        private void Item_Activated(object sender, EventArgs e)
        {
            // the menu item has been selected, call the action with the appropriate data
            int i = 0;
            Console.WriteLine("Item_Activated");
        }
```

**Comment by Therzok** [comment]
Unless you end up with the event handlers causing leaks, as the `NSMenuItem` now references the view controller - so, a ref cycle

**Comment by chamons** [comment]
@Therzok  - Does VSfM commonly use the Action/Selector pattern? If it is more common for large applications I can dig into this more (rework the example to not use the event and not report a message).

**Comment by Therzok** [comment]
Yes, we do use Action/Selector a lot of the time, as there is not always a way to unsubscribe event handlers, and the static registrar generates reasonable code for that.

I actually did file an issue about the managed fields that Xamarin.Mac generates for what is supposed to be weak references.

**Comment by yevgeny-sotnikov** [comment]
> Honestly though, much of the time you need to reach for Actions and Selectors you are doing something the hard way. I believe your use case can be solved without a custom NSMenuitem subclass, selectors, or actions:
> 
> ```
> 		public override void ViewDidLoad ()
> 		{
> 			base.ViewDidLoad ();
> 
>             for (int i = 0; i < 5; i++)
>             {
>                 var item = new NSMenuItem();
>                 item.Activated += Item_Activated;
>                 _myMenu.AddItem(item);
>             }
> 
>             // Do any additional setup after loading the view.
>         }
> 
>         private void Item_Activated(object sender, EventArgs e)
>         {
>             // the menu item has been selected, call the action with the appropriate data
>             int i = 0;
>             Console.WriteLine("Item_Activated");
>         }
> ```

@chamons can we setup NSMenuItem.View property to provide to the user custom view of menu item at this case?
