### ISSUE TITLE
NSInvalidArgumentException when sending multipart content over HTTP

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#15860]
### Steps to Reproduce

1. Download example project: [test.zip](https://github.com/xamarin/xamarin-macios/files/9487690/test.zip)
2. Register Client app in Google console & enter client ID in example project in "ViewController.cs"
3. Execute app & authorise client

### Expected Behavior
No exception, file upload succeeds

### Actual Behavior
`2022-09-05 09:34:20.133318+0200 test[4083:85862] Xamarin.iOS: Received unhandled ObjectiveC exception: NSInvalidArgumentException *** -streamStatus only defined for abstract class.  Define -[System_Net_Http_NSUrlSessionHandler_WrappedNSInputStream streamStatus]!
`

### Additional comments
- The crash only happens when the Linker is enabled
- The crash does not happen when sending a `StringContent` instead of a `JsonContent` as part of the `MultipartFormDataContent` in the example project
- A similar issue has been reported previously here: https://github.com/xamarin/xamarin-macios/issues/11996
- A similar issue has been discussed here (indicating it could be related to multipart contents): https://github.com/AFNetworking/AFNetworking/issues/2300

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac Preview
Version 17.4 Preview (17.4 build 715)
Installation UUID: 77c9a8af-734f-4ecb-bc80-fd2b65c91026

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-1.22371.1+c07f2571612b471671c809b5b0db59b0c37aab57

NuGet
Version: 6.2.1.2

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.400/Sdks
SDK Version: 6.0.400
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.8
	6.0.0

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Version: 6.0.8

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 17.4.0.32
Hash: 439b92ed7b
Branch: remotes/origin/d17-4
Build date: 2022-08-04 16:29:17 UTC

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.4.0.24
Hash: b3b6672
Branch: remotes/origin/HEAD~1
Build date: 2022-08-04 16:29:21 UTC

Android Device Manager
Version: 0.0.0.1179
Hash: 0f220c0
Branch: main
Build date: 2022-08-04 16:29:21 UTC

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 15.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:55-0400

Build Information
Release ID: 1704000715
Git revision: 09071dadfc1b81e4f0e2c9505cd8a5ef0b41d312
Build date: 2022-08-04 16:26:39+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 12.5.1
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Wed Aug 10 14:28:35 PDT 2022
    root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64


```

</details>

**Comment by tipa** [comment]
Bug is still present when building a .NET7 iOS app

**Comment by navi121** [comment]
I am facing same issue. I have attached screenshot for your reference. 
<img width="312" alt="image" src="https://user-images.githubusercontent.com/110674156/234920493-ff0af13d-a96b-4de7-b2bb-c4415f914413.png">

I am using Xamarin Forms - 5.0.0.2578
TargetFramework - netstandard2.1

**Comment by navi121** [comment]
May I know when this resolved version is been released?

**Comment by rolfbjarne** [comment]
> This has been blocking my work. May I know when this resolved version is been released?

I believe this will be shipped together with our support for Xcode 14.3 - and see this issue for that: https://github.com/xamarin/xamarin-macios/issues/17561

**Comment by cesit-nav** [comment]
Is there any estimated date for release to that issue?

**Comment by navi121** [comment]
Is there any estimated date for release to that issue ?

**Comment by tipa** [comment]
This crash is still happening with the latest versions of .NET / Xamarin / VS4Mac

**Comment by rolfbjarne** [comment]
@tipa can you [show the exact versions you used](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#version-information)?

**Comment by tipa** [comment]
```
Visual Studio Community 2022 for Mac Preview
Version 17.6 Preview (17.6 build 1496)
Installation UUID: 92d6c149-e164-4fec-8974-dd98b072279c

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.203/Sdks
SDK Versions:
	7.0.203
	7.0.202
	7.0.201
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.5
	7.0.4
	7.0.3

Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found

Updater
Version: 11

Apple Developer Tools
Xcode: 14.3 21812
Build: 14E222b

Xamarin.Mac
Version: 9.3.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:35-0400

Xamarin.iOS
Version: 16.4.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-04-27 00:18:22 UTC

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-04-27 00:18:27 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-04-27 00:18:27 UTC

Build Information
Release ID: 1706001496
Git revision: 7673a20cf2d7409180fbdc86d3fd9fc7cc17a1e9
Build date: 2023-04-27 00:16:36+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.3.1
Darwin 22.4.0 Darwin Kernel Version 22.4.0
    Mon Mar  6 21:00:41 PST 2023
    root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64

```

**Comment by rolfbjarne** [comment]
> This crash is still happening with the latest versions of .NET / Xamarin / VS4Mac

Just to confirm: you saw this error with an app built with legacy Xamarin.iOS?

**Comment by tipa** [comment]
No, I fully transitioned to "new .NET 7 for iOS". I don't know if it also happens on legacy Xamarin

**Comment by rolfbjarne** [comment]
> No, I fully transitioned to "new .NET 7 for iOS". I don't know if it also happens on legacy Xamarin

OK, that makes sense then, because we haven't published packages with the fix for .NET 7 yet.

**Comment by navi121** [comment]
Is this issue is been fixed and released? I have been blocked for a long time

**Comment by rolfbjarne** [comment]
> Is this issue is been fixed and released? I have been blocked for a long time

Yes, it's been released now. It's included in this release for .NET: https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-7.0.2xx-xcode14.3-7060

**Comment by tipa** [comment]
@rolfbjarne that's great news - thanks!
How can I make sure that I have this servicing update installed? When building a "normal" iOS app with .NET (not MAUI), I don't reference these `Microsoft.iOS.Sdk` NuGet packages, or should I?

**Comment by rolfbjarne** [comment]
> How can I make sure that I have this servicing update installed?

`dotnet workload list` should show something like this:

> ios                        16.4.7060/7.0.100              SDK 7.0.100

(the important part is the first version, `16.4.7060`).

> When building a "normal" iOS app with .NET (not MAUI), I don't reference these `Microsoft.iOS.Sdk` NuGet packages, or should I?

Yes, when building for iOS with .NET (with or without MAUI), you'll reference the `Microsoft.iOS.Sdk` NuGet package.
