### ISSUE TITLE
iOS binding library project template 

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-macios#15896]
### Description

For android, we can create the `android-bindinglib` project to build the binding library. For ios, we also need a project template to build the binding library. This project template should be based on .net 6 maui, not xamarin.

Moved [from .NET MAUI](https://github.com/dotnet/maui/issues/3688)

### Public API Changes

none.

### Intended Use-Case

In my maui app, I need to integrate the ios sdk of other mobile vendors.

**Comment by rolfbjarne** [comment]
The `iosbinding` template already exists:

```shell
$ dotnet new --list | grep binding
iOS Binding Library                           iosbinding      [C#]        iOS/Mobile
```

You'll need to install the iOS workload first though (`dotnet workload install ios`)
