### ISSUE TITLE
Xcode 14 support? Or a way to determine compatibility of ANY Xcode?

### ISSUE THREAD

**Issue by Adam-Langley** [xamarin/xamarin-macios#15946]
Hi,

This seems to come up at every major iOS release...
Where is the definitive source of truth, a page that is kept up to date, indicating compatibility with Xcode?

iOS 16 is out - and as such, Xcode 14.0 is required. So I installed it - now Visual Studio Mac does not list any simulators. I'm assuming I needed to update it - so I did, updated to the latest 17.4 b 175 - to no avail.

The web page that seems to be prevalent in google searches and forum posts (https://docs.microsoft.com/en-gb/xamarin/mac/release-notes/) hasnt been updated since 2021 - perhaps get rid of them?

I am guessing that Xcode 14 is not supported yet (even though its gone RTM) - but can we have a web page that lets us know what the latest supported version of XCode is? And keep it up to date? Am I missing something obvious?

Apologies for the exasperation in my tone - but I remember doing this dance several times before - usually resulting in having to roll back the Xcode update.

**Comment by NikitaRaki** [comment]
You can just download https://developer.apple.com/download/all/?q=xcode Xcode 13.4.1 and unpack it in application folder with Xcode name, and rename 14 xcode to xcodenew for example

**Comment by Adam-Langley** [comment]
Sorry how does that answer my question? How do I know when a Xamarin
release supports a specific Xcode version?

**Comment by danmiser** [comment]
Some kind of notification within VS itself would be ideal.

**Comment by dmoodz** [comment]
+1

**Comment by dalexsoto** [comment]
Hello, Xcode 14 was released yesterday, we are still ironing out some issues. Please refer to https://github.com/xamarin/xamarin-macios/issues/15954 for additional steps. 

Thanks a lot for opening this issue. I'll lock it down to avoid confusion and be redirected to the one above.
