### ISSUE TITLE
Error MT4109: Failed to compile the generated registrar code.

### ISSUE THREAD

**Issue by idzikovski** [xamarin/xamarin-macios#15951]
My Xamarin.iOS application fails to build after an automatic Xcode update. This issue seems to be the same as these two: #7049 and #7047. Is there a Xamarin.iOS preview version available already that would allow me to be able to build Xamarin.iOS applications?

### Steps to Reproduce

1. Install Xamarin.iOS Version: 15.12.0.2 
2. Install Xcode version 14.0

### Expected Behavior

Xamarin.iOS Application builds successfully.

### Actual Behavior

The build fails with `Error MT4109: Failed to compile the generated registrar code.`
### Environment

<details>
<summary>Version information</summary>

```
Xamarin.iOS Version: 15.12.0.2 

Xcode version 14.0
```

</details>

**Comment by linnkrb** [comment]
Happens to me to :-(

**Comment by lagmac** [comment]
The same error happens to me too. Is there a release date for Xamarin iOS 16 or a schedule (one week, two week, 3 days, 1 month)?

**Comment by KevinJalais** [comment]
Got the same error here too. I have the exact same versions as @idzikovski.
@rolfbjarne, are you still around? Any information would be really appreciated.
Thx.

**Comment by MrtnSys** [comment]
Oh man. Every major update you have to fear destroyment of your development environment.

My Xamarin Forms Apps are affected by the bug  [Shell TitleView Not Working in iOS 16 [Bug] #15512](https://github.com/xamarin/Xamarin.Forms/issues/15512) on iOS 16 now. To investigate the problem I updated MacOS to v12.6 Monterey, afterwards Xcode to v14.0, then Visual Studio 2022 to v17.3.3 and Xamarion iOS to v15.12.0.2

Now the iOS Simulators are not visible in Visual Studio anymore and I get these two errors when trying to start my project on a local iPhone:

Error MT4109: Failed to compile the generated registrar code.

Error HE0004: Could not load the framework 'DVTITunesSoftwareServiceFoundation' (path: /Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/DVTITunesSoftwareServiceFoundation)

**Comment by MateuszLas421** [comment]
The same error

**Comment by it11111111** [comment]
Same error here

**Comment by dmoodz** [comment]
Same here. Does anyone have a workaround, even if it's painful? Or are we screwed if XCode is updated?

**Comment by Confusedfish** [comment]
I uninstalled XCode from the Mac, downloaded the previous version and installed that. My simulators are back in VS but not had time to test on a physical device yet but so far signs are good.

**Comment by adam-russell** [comment]
@idzikovski You can download an automated build of Xamarin.iOS that will work with Xcode 14. On this page: https://github.com/xamarin/xamarin-macios/issues/15581

See the first comment by dalexsoto.

The package name will look something like xamarin.ios-15.99.0.464.pkg when you download it.

I'm using Xamarin.iOS from the current top change there locally (9a839d6c4a4c31a2b524fcdb721457900b396b84) and seems OK for me.

@MrtnSys I would try the custom renderer I posted on that issue for TitleView. I've had it in production for a while now, and it seems OK so far (no crashes that point to it or anything, and no users have complained). I wouldn't expect a fix in Xamarin Forms soon, though hopefully I'm wrong (I agree that should be a critical issue.. because it's also broken in iOS 16 if you built using old tools).

**Comment by it11111111** [comment]
> Same here. Does anyone have a workaround, even if it's painful? Or are we screwed if XCode is updated?

I uninstalled Xcode 14.0 and rolled back to the previous version. You can find it here: 
https://developer.apple.com/download/all/?q=xcode

Wont upgrade to 14.0 until I know it's working for everyone else lol

**Comment by filipkristo** [comment]
> @idzikovski You can download an automated build of Xamarin.iOS that will work with Xcode 14.
> 
> On this page: #15581
> 
> See the first comment by dalexsoto.
> 
> The package name will look something like xamarin.ios-15.99.0.464.pkg when you download it.
> 
> I'm using Xamarin.iOS from the current top change there locally ([9a839d6](https://github.com/xamarin/xamarin-macios/commit/9a839d6c4a4c31a2b524fcdb721457900b396b84)) and seems OK for me.
> 
> @MrtnSys I would try the custom renderer I posted on that issue for TitleView. I've had it in production for a while now, and it seems OK so far (no crashes that point to it or anything, and no users have complained). I wouldn't expect a fix in Xamarin Forms soon, though hopefully I'm wrong (I agree that should be a critical issue.. because it's also broken in iOS 16 if you built using old tools).

It worked for me!! iOS simulator is shown, but I still have the same error if I want to deploy to the physical device...
Did anyone else ecpiriced the same issue? Deploying from Mac to iPhone.

**Comment by dalexsoto** [comment]
Hello, Xcode 14 was released yesterday, we are still ironing out some issues. Please refer to https://github.com/xamarin/xamarin-macios/issues/15954 for additional steps. 

Thanks a lot for opening this issue. I'll lock it down to avoid confusion and be redirected to the one above.
