### ISSUE TITLE
Failed to compile the generated registrar code

### ISSUE THREAD

**Issue by Zwarthoed** [xamarin/xamarin-macios#15963]
### Steps to Reproduce

1. no special steps, problem always present
2. 
3. 

### Environment

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by rolfbjarne** [comment]
Hello, Xcode 14 was released earlier this week, we are still ironing out some issues. Please refer to https://github.com/xamarin/xamarin-macios/issues/15954 for additional steps. 

Thanks a lot for opening this issue. I'll lock it down to avoid confusion and be redirected to the one above.
