### ISSUE TITLE
Unable to Build iOS Project 

### ISSUE THREAD

**Issue by StacyCMay** [xamarin/xamarin-macios#15978]
### Steps to Reproduce

1. Plug in physical device to Mac M1 Laptop for the purpose of debugging iOS App 
2. Build Solution
3. Error

### Expected Behavior

Since building the solution using a simulator works without issue, it's assumed that building the solution in debug mode targeting a physical device will also work. 

### Actual Behavior

Solution fails to build with the following error: 
/../JSI.Mobile.iOS/obj/iPhone/Debug/device-builds/iphone11.6-15.6.1/mtouch-cache/registrar.h(1421,79): error GE71D2E27: no type or protocol named 'BADownloadManagerDelegate'
MTOUCH : error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new

### Environment

<details>
<summary>Version information</summary>

```
Version: 15.99.0.310 (Visual Studio Enterprise)
Hash: a3310342f
Branch: xcode14
Build date: 2022-08-23 10:46:10-0400
```

</details>

**Comment by dalexsoto** [comment]
You are using Xcode 14 which its support is being worked out, please visit https://github.com/xamarin/xamarin-macios/issues/15954 for more information.
