### ISSUE TITLE
SWHighlightCenter constructor doesn't work [XCode 14]

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#15983]
### Steps to Reproduce

Run this code:
`var center = new SWHighlightCenter();`

### Expected Behavior
This should work. For example this works properly in swift:
`self.highlightCenter = SWHighlightCenter()`
### Actual Behavior
You get this exception:

> ObjCRuntime.RuntimeException has been thrown
> Can't register the class SharedWithYou.SWHighlightCenter when the dynamic registrar has been linked away.

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.3.4 (build 4)
Installation UUID: eba40ff5-e9f3-4b51-94fa-5b2b5e4cbe41

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.1.2

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.400/Sdks
SDK Versions:
	6.0.400
	6.0.302
	6.0.301
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.8
	6.0.7
	6.0.6
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.0 (21335)
Build 14A309

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 15.99.0.464 (Visual Studio Community)
Hash: 9a839d6c4
Branch: xcode14
Build date: 2022-09-13 05:38:29-0400

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-09-01 17:18:13 UTC

Xamarin.Android
Version: 13.0.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-3/030cd63
Android SDK: /Users/ivanicin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.23
Hash: 965bf40
Branch: remotes/origin/d17-3
Build date: 2022-09-01 17:18:18 UTC

Android Device Manager
Version: 0.0.0.1169
Hash: fafb1d5
Branch: fafb1d5
Build date: 2022-09-01 17:18:18 UTC

Build Information
Release ID: 1703040004
Git revision: 5ec72d3a5e7c84e88be448c0ff9e58839e0913e9
Build date: 2022-09-01 17:16:20+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:17:10 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64


```

</details>

**Comment by ivanicin** [comment]
This appears to be widespread in this namespace, there is the same problem in this constructor:
`var attributionView = new SharedWithYou.SWAttributionView();`

**Comment by tj-devel709** [comment]
Thank you for your feedback, @ivanicin. SharedWithYou is a new framework in Xcode 14. As you tagged the issue [here](https://github.com/xamarin/xamarin-macios/issues/15954), SharedWithYou and other new Xcode 14 features will be available as soon. You can follow that issue I mentioned to know the latest updates. Thank you.

Please see Alex's post [here](https://github.com/xamarin/xamarin-macios/issues/15954#issue-1372052546) at the top of the issue with instructions with different options on moving forward in the meantime.

**Comment by tj-devel709** [comment]
My apologies, it seems that you are using Xcode14 with xamarin.ios from our xcode14 branch. I will reopen this one

**Comment by ivanicin** [comment]
@tj-devel709 I appreciate your dedication. I have started to write that I see that you have put some effort in answer but that you still missed most relevant information. It is great that you have picked it up that quickly!

I think that you’ll be a great addition to the Xamarin team assuming that I am right that you have started to work there fairly recently - just reading your short bio here so it could be I am wrong regarding that 🙂.

**Comment by tj-devel709** [comment]
Hi @ivanicin, my bio is a little outdated as I have been here for a bit but thanks for the reminder to update it!
Could you tell me if you are using legacy Xamarin or if you are using dotnet? It appears that using a legacy xamarin.ios project with xamarin.ios version 15.99.0.464 builds successfully when calling `var center = new SWHighlightCenter();`.

If you are using a .NET6 project, we will need to make sure you are using the correct workloads. Could you list the workloads you have installed by running `dotnet workload list` and telling me where you got the nuget packages from?

**Comment by ivanicin** [comment]
@tj-devel709 this is a runtime exception. Yes it is on Xamarin.iOS. 

I have linker on as it was suggested that keeping it off may cause some Registrar bugs, though I would guess it refers to compile errors.

**Comment by tj-devel709** [comment]
@ivanicin it seems that this issue only occurs when using the linker. It appears that the linker is not catching SharedWithYou. We will continue to look into this issue, but as a workaround, you should be able to add `--weak-framework=SharedWithYou` to the "additional mtouch arguments" without any exceptions.

**Comment by ivanicin** [comment]
> you should be able to add `--weak-framework=SharedWithYou` to the "additional mtouch arguments" without any exceptions.

@tj-devel709 that did the trick. I haven't further tested whether it actually works yet, but the exception is not raised anymore.

**Comment by tj-devel709** [comment]
Awesome, I'll go ahead and close this issue now. Feel free to open back up or create a new one if there is any other issues with SharedWithYou.
