### ISSUE TITLE
Bundle signature window for apple project is empty (no interface)

### ISSUE THREAD

**Issue by nissaba** [xamarin/xamarin-macios#15987]
The window to set the iOS bundle signature is empty. So we can not set the information 
project I am working of is Xamarin Forms
works ok under VS 1.3

![Capture d’écran, le 2022-09-16 à 11 17 34](https://user-images.githubusercontent.com/3584506/190674477-203d0b57-e834-4027-855e-6b539bf5b0c4.png)

was not able to get this from a newly created project. 

### Steps to Reproduce
using Visual Code 17.4
use a project that was created before the latest updates. 
r-click on solution and select options, then go to the apple bundle signature. 

### Expected Behavior

should shot the interface to set the information

### Actual Behavior

empty view see attached image

### Environment

Visual Studio Community 2022 for Mac Preview
Version 17.4 Preview (17.4 build 1552)
Installation UUID: d38c8ec5-3b61-4b23-b7f5-018425a407dd

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-2.22419.1+ae5663806be933515723b2d5a85faf5d378f460d

NuGet
Version : 6.3.0.128

SDK .NET (Arm64)
SDK : /usr/local/share/dotnet/sdk/6.0.401/Sdks
Versions du SDK :
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
	6.0.202
	6.0.201
	6.0.200
	6.0.101
SDK MSBuild : /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

Kit de développement logiciel (SDK) .NET (x64)
Versions du SDK :
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
	6.0.202
	6.0.201
	6.0.200
	6.0.105
	6.0.102
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416

Runtime .NET (Arm64)
Runtime : /usr/local/share/dotnet/dotnet
Versions du runtime :
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5
	6.0.4
	6.0.3
	6.0.2
	6.0.1

Runtime .NET (x64)
Runtime : /usr/local/share/dotnet/x64/dotnet
Versions du runtime :
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5
	6.0.4
	6.0.3
	6.0.2
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22

Xamarin.Profiler
Version : 1.8.0.19
Emplacement : /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version : 11

Apple Developer Tools
Xcode 14.0 (21335)
Build 14A309

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin Designer
Version: 17.4.0.107
Hash: d549bb251b
Branch: remotes/origin/d17-4
Build date: 2022-09-08 23:42:26 UTC

Xamarin.Android
Version : 13.0.99.81 (Visual Studio Community)
Commiter : xamarin-android/main/7c9c24b
Android SDK: /Users/pascale/Library/Android/sdk
	Versions Android prises en charge :
		12.1(Niveau d’API 32)
		12.0(Niveau d’API 31)
		8.1 (Niveau d’API 27)
		11.0(Niveau d’API 30)
		10.0(Niveau d’API 29)

Version des outils de ligne de commande du SDK : 7.0
Version des outils de plateforme du SDK : 33.0.1
Version des outils de génération du SDK : 33.0.0

Informations de build : 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/main@2c8b0a8f
SQLite: xamarin/sqlite/3.39.2@40e8743
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@29f11f2

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer code EPL disponible ici :
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer code EPL disponible ici :
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.45
Hash: 8cac7ea
Branch: remotes/origin/HEAD
Build date: 2022-09-08 23:42:31 UTC

Android Device Manager
Version: 0.0.0.1196
Hash: b2faf27
Branch: main~1
Build date: 2022-09-08 23:42:31 UTC

Xamarin.iOS
Version: 15.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:55-0400

Build Information
Release ID: 1704001552
Git revision: 76bf82d791519696ccb2096861e855d516710187
Build date: 2022-09-08 23:40:22+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:19:52 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

Enabled user installed extensions
CSharp Interactive 0.4
NuGet Package Explorer 0.10
NuGet Package Management Extensions 0.32
.NET Core Extensions 0.4

**Comment by tj-devel709** [comment]
Thanks for the feedback. This looks like and IDE issue, and unfortunately the team that owns that is not accessible on github. Please file an issue at https://developercommunity.visualstudio.com/
