### ISSUE TITLE
Is Xamarin support CarPlay business apps ?

### ISSUE THREAD

**Issue by XamarinRPMTeam** [xamarin/xamarin-macios#16015]
Team , This is to ask you about the CarPlay Support in Xamarin . Is Xamarin Support CarPlay? .If yes Could you please get the official documentation on how to do it . We found one and only sample which is music app . Our requirement is to develop a business app which is very much required to do .

**Comment by dalexsoto** [comment]
Hello!

We do not limit CarPlay support on any way and while we do not have any examples available, the community has stepped up and created some around it like https://github.com/Suplanus/Xamarin.Demo.Carplay. So creating a business app or whatever CarPlay app is indeed possible.

**Comment by XamarinRPMTeam** [comment]
Thanks for the response . Do we have any official documentation / guideline in Xamarin with relate to CarPlay .

**Comment by dalexsoto** [comment]
Unfortunately no
