### ISSUE TITLE
VS 17.3.5 cannot add Apple Developer account

### ISSUE THREAD

**Issue by znelson32** [xamarin/xamarin-macios#16025]
### Steps to Reproduce

1. Open VS 17.3.5
2. Tools, Preferences, Publishing, Apple Developer Accounts
3. Add Individual Account
4. Enter Name, Issuer Id, Key Id, and PK (_developer role_) from https://appstoreconnect.apple.com/access/api
5. Click Add

### Expected Behavior
Apple Developer account is added, or error message is shown

### Actual Behavior
Nothing happens. Account not added, no error message.

### Environment
MacOS 12.6

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by tj-devel709** [comment]
Thanks for the feedback. This looks like and IDE issue, and unfortunately the team that owns that is not accessible on github. Please file an issue at https://developercommunity.visualstudio.com/

**Comment by znelson32** [comment]
Thanks! This appears to be resolved in 17.4 Preview (_confirmed_)
