### ISSUE TITLE
Error MT4109: Failed to compile the generated registrar code

### ISSUE THREAD

**Issue by gfelberbaum** [xamarin/xamarin-macios#16041]
### Steps to Reproduce

1. Upgraded on macOS to VS-pre 17.4 (build 1552)
2. Upgraded Xcode to 14 (14A309) 
3. Build iOS app

### Expected Behavior
prior to the upgrade app built with no errors

### Actual Behavior
Unable to build without above errors

### Environment
Visual Studio Community 2022 for Mac Preview
Version 17.4 Preview (17.4 build 1552)
Installation UUID: 14c9561d-1d99-4ed6-a1fb-db88377b8b49

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-2.22419.1+ae5663806be933515723b2d5a85faf5d378f460d

NuGet
Version: 6.3.0.128

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.401/Sdks
SDK Versions:
	6.0.401
	6.0.400
	6.0.400-preview.22330.6
	6.0.301
	6.0.300
	6.0.203
	6.0.202
	6.0.201
	6.0.200
	6.0.102
	6.0.101
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.401
	6.0.400
	6.0.400-preview.22330.6
	6.0.301
	6.0.300
	6.0.203
	6.0.202
	6.0.201
	6.0.200
	6.0.106
	6.0.105
	6.0.101
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.9
	6.0.8
	6.0.6
	6.0.5
	6.0.4
	6.0.3
	6.0.2
	6.0.1

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.9
	6.0.8
	6.0.6
	6.0.5
	6.0.4
	6.0.3
	6.0.2
	6.0.1
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.0 (21335)
Build 14A309

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.Android
Version: 13.0.99.81 (Visual Studio Community)
Commit: xamarin-android/main/7c9c24b
Android SDK: /Users/gary/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		8.1  (API level 27)
		11.0 (API level 30)
		7.1  (API level 25)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/main@2c8b0a8f
SQLite: xamarin/sqlite/3.39.2@40e8743
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@29f11f2

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.45
Hash: 8cac7ea
Branch: remotes/origin/HEAD
Build date: 2022-09-08 23:42:31 UTC

Android Device Manager
Version: 0.0.0.1196
Hash: b2faf27
Branch: main~1
Build date: 2022-09-08 23:42:31 UTC

Xamarin.iOS
Version: 15.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:55-0400

Xamarin Designer
Version: 17.4.0.107
Hash: d549bb251b
Branch: remotes/origin/d17-4
Build date: 2022-09-08 23:42:26 UTC

Build Information
Release ID: 1704001552
Git revision: 76bf82d791519696ccb2096861e855d516710187
Build date: 2022-09-08 23:40:22+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:19:52 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by squiffed** [comment]
Encountered this error as well.

**Comment by gfelberbaum** [comment]
Were you able to find a work-around?

Gary Felberbaum
President

AdvancedDecisions.com
203 929-1400



On Sep 20, 2022, at 3:26 PM, James Beck ***@***.***> wrote:

﻿

Encountered this error as well.

**Comment by squiffed** [comment]
I am able to drag the .ipa file onto the Xcode Devices/Simulator window and test it that way.  Not ideal.

Here most people suggest rolling back to Xcode 13.4:  https://github.com/xamarin/xamarin-macios/issues/15951

Good luck.

James Beck
***@***.***

**Comment by gfelberbaum** [comment]
Thanks James,  I was hoping not to have to rollback but probably will.

Good Luck to youl.

From: James Beck ***@***.***>
Date: Tuesday, September 20, 2022 at 5:55 PM
To: xamarin/xamarin-macios ***@***.***>
Cc: Gary Felberbaum ***@***.***>, Author ***@***.***>
Subject: Re: [xamarin/xamarin-macios] Error MT4109: Failed to compile the generated registrar code (Issue #16041)
I am able to drag the .ipa file onto the Xcode Devices/Simulator window and test it that way. Not ideal.

Here most people suggest rolling back to Xcode 13.4: https://github.com/xamarin/xamarin-macios/issues/15951

Good luck.

James Beck
***@***.***

**Comment by stalohadj** [comment]
Have you found any other work around?

**Comment by tj-devel709** [comment]
Hello @gfelberbaum, we are tracking this issue inside of this issue: https://github.com/xamarin/xamarin-macios/issues/15954. Updates will be posted on that issue.

It looks like you are using Xcode14, but you do not have the Xamarin.iOS preview version as Alex lists in the issue description. If you download that Xamarin.iOS version, you may also have to set the linker to "Link SDK Assemblies only" as well. https://github.com/xamarin/xamarin-macios/issues/15954#issuecomment-1247253701

**Comment by gfelberbaum** [comment]
Ok, Thanks for the help.

I just downloaded Xcode 13.4 and set the xcode cmd line tools to that version.  See ms to work well.


I hope you guys can get an update out so I can move forward with xcode 14.

Thanks you for getting back to me.
gary

From: TJ Lambert ***@***.***>
Date: Wednesday, September 21, 2022 at 12:08 PM
To: xamarin/xamarin-macios ***@***.***>
Cc: Gary Felberbaum ***@***.***>, Mention ***@***.***>
Subject: Re: [xamarin/xamarin-macios] Error MT4109: Failed to compile the generated registrar code (Issue #16041)

Hello @gfelberbaum<https://github.com/gfelberbaum>, we are tracking this issue inside of this issue: #15954<https://github.com/xamarin/xamarin-macios/issues/15954>. Updates will be posted on that issue.

It looks like you are using Xcode14, but you do not have the Xamarin.iOS preview version as Alex lists in the issue description. If you download that Xamarin.iOS version, you may also have to set the linker to "Link SDK Assemblies only" as well. #15954 (comment)<https://github.com/xamarin/xamarin-macios/issues/15954#issuecomment-1247253701>

**Comment by gfelberbaum** [comment]
Happy to report I just had to download and opened xcode 13.4.1 .xip file and put it in a folder on my drive (not my application folder) so I don’t get confused with V14 (still in my Application folder)


Opened Xcode 14, preferences, Locations, and on Command Line Tolls able to select Xcode 12.41.

Closed xcode ad went back to VS 2022 or VS 2019 on my mac and all is well.

Hope this helps.

From: Stalo Hadjittofi ***@***.***>
Date: Wednesday, September 21, 2022 at 3:38 AM
To: xamarin/xamarin-macios ***@***.***>
Cc: Gary Felberbaum ***@***.***>, Author ***@***.***>
Subject: Re: [xamarin/xamarin-macios] Error MT4109: Failed to compile the generated registrar code (Issue #16041)

Have you found any other work around?

**Comment by gfelberbaum** [comment]
I am about till back xcode to 13.4.

Gary Felberbaum
President

AdvancedDecisions.com
203 929-1400



On Sep 21, 2022, at 3:38 AM, Stalo Hadjittofi ***@***.***> wrote:

﻿

Have you found any other work around?

**Comment by squiffed** [comment]
I had success with this approach as well.

thx!

James Beck
***@***.***
