### ISSUE TITLE
Cannot see ios simulators on VS mac

### ISSUE THREAD

**Issue by srivatsamarichi** [xamarin/xamarin-macios#16056]
### Steps to Reproduce

1. Install VS Mac Preview
2. Run any sample ios app
3. Deploy to ios simulators

### Expected Behavior

To see the ios simuators inside VS mac.

### Actual Behavior

Unable to see the ios simulators inside VS Mac. This was tried on the stable version of VS MAc, the outcome is same.

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Enterprise 2022 for Mac Preview
Version 17.4 Preview (17.4 build 1583)
Installation UUID: 28b8cc3d-22cf-450e-a1ad-4e407a3f006f

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.4.0-2.22419.1+ae5663806be933515723b2d5a85faf5d378f460d

NuGet
Version: 6.3.0.128

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.401/Sdks
SDK Versions:
	6.0.401
	6.0.400
	6.0.400-preview.22330.6
	6.0.301
	6.0.101
	6.0.100
	5.0.408
	5.0.404
	5.0.403
	5.0.401
	5.0.301
	5.0.203
	5.0.202
	5.0.103
	5.0.101
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.416
	3.1.415
	3.1.413
	3.1.410
	3.1.409
	3.1.408
	3.1.406
	3.1.404
	3.1.402
	3.1.302
	3.1.300
	3.1.202
	3.1.200
	3.1.100
	2.1.810
	2.1.505
	2.1.504
	2.1.302
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.9
	6.0.8
	6.0.6
	6.0.1
	6.0.0
	5.0.17
	5.0.13
	5.0.12
	5.0.10
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.22
	3.1.21
	3.1.19

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 17.4.0.124
Hash: ffbba0c031
Branch: remotes/origin/d17-4
Build date: 2022-09-15 15:36:29 UTC

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Enterprise)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 13.4.0.2 (Visual Studio Enterprise)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

Xamarin.Android
Version: 13.0.99.81 (Visual Studio Enterprise)
Commit: xamarin-android/main/7c9c24b
Android SDK: /Users/srivatsa/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		11.0 (API level 30)
		10.0 (API level 29)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/main@2c8b0a8f
SQLite: xamarin/sqlite/3.39.2@40e8743
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@29f11f2

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.45
Hash: 8cac7ea
Branch: remotes/origin/HEAD~1
Build date: 2022-09-15 15:36:33 UTC

Android Device Manager
Version: 0.0.0.1196
Hash: b2faf27
Branch: main~1
Build date: 2022-09-15 15:36:33 UTC

Build Information
Release ID: 1704001583
Git revision: 70322329919c72a11d9795a3cb403fe4115a5878
Build date: 2022-09-15 15:34:34+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:17:10 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
```

</details>

### Build Logs

[Build Output.txt](https://github.com/xamarin/xamarin-macios/files/9618110/Build.Output.txt)

### Example Project (If Possible)

Project can be found here - https://github.com/CanarysPlayground/mob-devops-demo

**Comment by tj-devel709** [comment]
Hello @srivatsamarichi. Thank you for your feedback. This may be an IDE issue, but would you be able to run 
```
xcode-select -p
```
 in your terminal and let us know what the result is? Could you also give us a copy of your IDE.log?
 Resources on how to access the IDE.log can be found [here](https://learn.microsoft.com/en-us/visualstudio/mac/troubleshooting?view=vsmac-2022#viewing-logs-in-visual-studio-for-mac).

**Comment by srivatsamarichi** [comment]
@tj-devel709 yes si am able to run the above command form my terminall and here is the output for the same.

<img width="511" alt="Screenshot 2022-09-21 at 11 12 13 PM" src="https://user-images.githubusercontent.com/13433045/191574180-97f11c78-d275-4805-a487-0e1b6e5bad2a.png">

**Copy of IDE.log**

[VSMonitor-2022-09-21-20-45-38-821a6f7.log](https://github.com/xamarin/xamarin-macios/files/9619149/VSMonitor-2022-09-21-20-45-38-821a6f7.log)

**Comment by spouliot** [comment]
Looks like it's time to update your Xamarin.iOS version from 2019.

```
Xamarin.iOS
Version: 13.4.0.2 (Visual Studio Enterprise)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400
```

or stop updating VSfM :)

**Comment by srivatsamarichi** [comment]
> Looks like it's time to update your Xamarin.iOS version from 2019.
> 
> 
> 
> ```
> 
> Xamarin.iOS
> 
> Version: 13.4.0.2 (Visual Studio Enterprise)
> 
> Hash: e37549bc
> 
> Branch: xcode11.1
> 
> Build date: 2019-10-07 22:43:23-0400
> 
> ```
> 
> 
> 
> or stop updating VSfM :)

No luck even after updating to 2019. Guess it's time to stop using vsfm.

**Comment by samukbg** [comment]
Same issue here, no simulators are available. The iOS SDK is linked, the minimum system version is already low at v10 and no simulators whatsoever

**Comment by tj-devel709** [comment]
@srivatsamarichi Could you try, as @spouliot, mentioned, updating your Xamarin.iOS version? The current version you are using is from 2019 and could potentially be causing issues with your simulators.

https://learn.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/old-version-xcode#use-of-new-xcode-with-older-xamarinios

**Comment by srivatsamarichi** [comment]
@tj-devel709 I am able to see the simulators now in my VS. I did update my xamarin.ios to **[15.12.0.2](https://download.visualstudio.microsoft.com/download/pr/e81e04d3-768a-4310-9c9b-f32e8ba00eaa/0e27caf0877adb5c6fe6d634d26da40a/xamarin.ios-15.12.0.2.pkg)** and it works like a charm. Many thanks 🙏 to @spouliot for the suggestions.

**Comment by tj-devel709** [comment]
Awesome! Thanks for the update!
