### ISSUE TITLE
Issue building my old application code ealier built on visualstudio19mac

### ISSUE THREAD

**Issue by AnjaneyuluUppalapati** [xamarin/xamarin-macios#16098]
### Steps to Reproduce

1. Im trying to build my old code ,updated other packages
2. 
3. 

### Environment

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by tj-devel709** [comment]
Hello @AnjaneyuluUppalapati. In order for us to look into the issue, we would need a more specific error/issue you are running into. If you have a specific issue, feel free to reopen this issue and please fill in the template with the steps to reproduce, the expected and actual behavior, your environment information, logs, and a sample. Thank you.
