### ISSUE TITLE
Exception thrown when calling RequestGeometryUpdate on iOS 15 using Xamarin 16.0.0.72

### ISSUE THREAD

**Issue by vouksh** [xamarin/xamarin-macios#16113]
Testing the new build of Xamarin posted in #15954 
We have a couple of views that needs to be landscape-oriented. Before XCode 14 and Xamarin/iOS 16, we used the overrides and UIApplication.SharedApplication.SetStatusBarOrientation() to force the orientation. 
That no longer works in iOS 16. I found a thread on the Apple Developer forums with others experiencing the same issue. https://developer.apple.com/forums/thread/707735
I was able to implement the RequestGeometryUpdate method which fixes the rotation on iOS 16. However, we still need to support iOS 15, so when testing the same code on iOS 15, the app was crashing. I captured the exception, which seems to be a problem with the linking or binding? `Can't register the class UIKit.UIWindowSceneGeometryPreferencesIOS when the dynamic registrar has been linked away.`

In addition, if I wrap all of the code needed to get the screen orientation working in 16 in a CheckSystemVersion block and use the same code that worked on XCode 13.4.1 and Xamarin 15.x, the screen orientation is broken and only half of the screen ends up rotated. I included screenshots below to show what I'm talking about. Both screenshots are built using the same code, only with the UpdateGeometry method removed when building under XCode 13 and Xamarin 15

Here's the full initialization code that we use: https://pastebin.com/GCq7t72J

### Steps to Reproduce

1. Reference the first scene as a UIWindowScene `var windowScene = (UIApplication.SharedApplication.ConnectedScenes.ToArray()[0] as UIWindowScene);`
2. Call RequestGeometryUpdate method. 
  ```
            try
            {
                var windowScene = (UIApplication.SharedApplication.ConnectedScenes.ToArray()[0] as UIWindowScene);
                windowScene.RequestGeometryUpdate(
                    new UIWindowSceneGeometryPreferencesIOS(UIInterfaceOrientationMask.LandscapeLeft),
                    error =>
                    {
                        Helper.Log($"Error orienting screen: {error.LocalizedDescription}");
                        Helper.Log(error.LocalizedRecoverySuggestion);
                    });
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error updating geometry: {ex.Message}");
            }
```
4. Deploy to iOS 15 device
5. Navigate to page. 
6. Console outputs "Can't register the class UIKit.UIWindowSceneGeometryPreferencesIOS when the dynamic registrar has been linked away."

### Expected Behavior
Screen rotates to specified orientation
<img width="667" alt="PNG image 2" src="https://user-images.githubusercontent.com/3097831/192003491-63621387-695e-47e9-b9b2-c3a27bef2124.png">

### Actual Behavior
Screen is only partially rotated. Controls are only on half of the screen. 
<img width="667" alt="PNG image" src="https://user-images.githubusercontent.com/3097831/192003465-6480424f-1952-4d79-87c2-d8e97776edca.png">

### Environment
<details>
<summary>Version information</summary>

```=== Visual Studio Community 2019 for Mac ===

Version 8.10.22 (build 11)
Installation UUID: ab97f3a5-ba34-4764-8bdf-d90229559398
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000182

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.182 (2020-02/6051b710727) (64-bit)
	Package version: 612000182

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/6.0.401/Sdks
SDK Versions:
	7.0.401
	6.0.300
	6.0.202
	6.0.201
	6.0.104
	6.0.101
	5.0.408
	5.0.407
	5.0.404
	5.0.400
	5.0.302
	3.1.423
	3.1.419
	3.1.418
	3.1.416
	3.1.412
	3.1.411
MSBuild SDKs: /Applications/Visual Studio (2019).app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.9
	6.0.5
	6.0.4
	6.0.3
	6.0.1
	5.0.17
	5.0.16
	5.0.13
	5.0.9
	5.0.8
	3.1.29
	3.1.25
	3.1.24
	3.1.22
	3.1.18
	3.1.17

=== .NET Core 3.1 SDK ===

SDK: 3.1.423

=== .NET 5.0 SDK ===

SDK: 5.0.408

=== Xamarin.Profiler ===

Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

=== Apple Developer Tools ===

Xcode 14.0 (21335)
Build 14A309

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

=== Xamarin.Android ===

Not Installed

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Build Information ===

Release ID: 810220011
Git revision: 16b49eb779f7def4523bbc8f4407628cf8dbb4b5
Build date: 2022-04-07 05:04:03-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.5.1
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Wed Aug 10 14:25:27 PDT 2022
    root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64
```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/9634779/msbuild.binlog.zip)

**Comment by ivanicin** [comment]
You have the suggestion here that works around the problem with nearly the same exception: https://github.com/xamarin/xamarin-macios/issues/15983#issuecomment-1254290489

**Comment by tj-devel709** [comment]
Hello @vouksh thank you for the feedback. UIKit.UIWindowSceneGeometryPreferencesIOS is a new class that is introduced in iOS 16, so this behavior of it not working on iOS 15 is actually expected. However, the error message should be more descriptive of that scenario and we will look more into that. It also appears that UIApplication.SetStatusBarOrientation was deprecated in iOS 9 so this method is no longer supported by us or by Apple. The post you linked with the Apple Developer Forums shows that many other people have this issue with Apple so this does not appear to be a Xamarin issue so we will be closing this. If you believe that this is a Xamarin specific issue unrelated to Apple's changes, feel free to reopen this issue. Thanks!
