### ISSUE TITLE
Use the .NET 8 linker only for .NET 8

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#16125]
Currently .NET's linker is implemented so that if you're using .NET 7 to build a project, you'll get the .NET 7 linker, even if the project is building for .NET 6 (say using the `net6.0-ios` TargetFramework).

This is unfortunate for a couple of reasons:

* The .NET 6 codebase (sdk, ref, runtime packs) was not tested with the .NET 7 linker (we'd need a time machine for that). Testing the .NET 7 linker with .NET 6 projects is more feasible, except that it increases our testing matrix quite a lot (will we have to test the .NET 8 linker with .NET 6 + .NET 7 + .NET 8 projects?) In any case our tests won't cover every scenario, and it's entirely possible that customers will run into issues with the .NET 7 linker that isn't covered by our tests.
* In order to support building from Windows, we poke into the internals of the linker's MSBuild logic:
    https://github.com/xamarin/xamarin-macios/blob/0a78bba081a1d47288d5c4d1af07063cce44d0a8/msbuild/Xamarin.iOS.Tasks.Windows/Xamarin.iOS.Common.After.targets#L307-L370
    This leads to bugs when the linker's internals changes in .NET 7, and we're still using poking logic from .NET 6 (because we still haven't invented a time machine). Example: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1621047?src=WorkItemMention&src-action=artifact_link

I believe Android found an issue with the .NET 7 linker as well (iirc Cecil fixed a bug that turned out to not be backwards bug-compatible).

The fix seems easy: we should look into whether the linker can be used from the target .NET version (i.e. when building a `net6.0-ios` app use the .NET 6 linker). This is something the linker/runtime team should do, so this issue is just a tracking issue for our side.

**Comment by marek-safar** [comment]
This should be address in linker with https://github.com/dotnet/linker/issues/3029

**Comment by rolfbjarne** [comment]
This has been addressed in the linker.
