### ISSUE TITLE
HOTRESTART preprocessor symbol not working in XF

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/xamarin-macios#16148]
### Steps to Reproduce

1. Create blank XF Solution with 
2. Insert !HOTRESTART preprocessor command in shared projekt
3. Set breakpoint
4. Start local iPhone via Hot Restart

### Expected Behavior
If we use a physical iPhone and run via Hot Restart the HOTRESTART preprocessor symbol should be recognized. (https://learn.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart#use-xamarin-hot-restart) Code like this, should not be executed if we use hot restart:
```C#
    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();
#if !HOTRESTART
            Console.WriteLine("App ctor");
            Test();
#endif
            MainPage = new MainPage();
        }
        private void Test()
        {

        }
    }
```

### Actual Behavior
The code is executed:
![image](https://user-images.githubusercontent.com/6727366/192451366-9c4b8368-db67-4102-8c90-da8a156e67a9.png)

If i switch to the android project, the code block is still grey, but executing.
![image](https://user-images.githubusercontent.com/6727366/192453729-d8a468d6-00a3-487a-aea0-022e78c30b56.png)

### Environment
Testet also with VS 17.3.4

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Enterprise 2022
Version 17.4.0 Preview 2.1
VisualStudio.17.Preview/17.4.0-pre.2.1+32916.344
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

ASP.NET and Web Tools   17.4.210.756
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.210.756
Azure App Service Tools v3.0.0

C# Tools   4.4.0-2.22430.14+2f760738cb92f32f50c981b68ba04ac3c8b7ee48
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.1 (main@2ee106a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.4.19 (8c0a575)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2243101+64a0117763b8eb085c75bdb80329e16e5a2c65a5
Provides languages services for ASP.NET Core Razor.

TypeScript Tools   17.0.10901.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-2.22430.14+2f760738cb92f32f50c981b68ba04ac3c8b7ee48
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.4.0-beta.22429.6+22514929f2e903ea8c14947bea7c2b242886e1ee
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.4.0.171 (d17-4-net7@4d0f4c0)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.4.0.124 (remotes/origin/d17-4@ffbba0c031)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.4.2 (c457c97)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.0.99.81 (main/7c9c24b)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/main@2c8b0a8f
    SQLite: xamarin/sqlite/3.39.2@40e8743
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@29f11f2


Xamarin.iOS and Xamarin.Mac SDK   15.13.0.65 (409c80dd9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

**Comment by tj-devel709** [comment]
@AlleSchonWeg, would you be able to provide us a binlog?
https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#build-logs

**Comment by AlleSchonWeg** [comment]
@tj-devel709 
I created a binlog. But i don't want to upload here, because it contains private informations. Like username, folder structure etc.

**Comment by AlleSchonWeg** [comment]
> @AlleSchonWeg, would you be able to provide us a binlog? [xamarin/xamarin-macios/wiki/Diagnosis#build-logs](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#build-logs)

Can i send you an email?

**Comment by tj-devel709** [comment]
@AlleSchonWeg Yes, you can send it to antlambe@microsoft.com

**Comment by AlleSchonWeg** [comment]
> @AlleSchonWeg Yes, you can send it to [antlambe@microsoft.com](mailto:antlambe@microsoft.com)

Done...

**Comment by rolfbjarne** [comment]
It looks like the `IsHotRestartBuild` variable isn't `true` (which I believe the IDE should set):

> Target "_DetectHotRestartSigningIdentity" skipped, due to false condition; ('$(_CanOutputAppBundle)' == 'true' And '$(IsHotRestartBuild)' == 'true' And '$(IsHotRestartEnvironmentReady)' == 'true') was evaluated as ('true' == 'true' And '' == 'true' And '' == 'true').

**Comment by AlleSchonWeg** [comment]
VS Feedback created: https://developercommunity.visualstudio.com/t/HOTRESTART-preprocessor-symbol-not-worki/10236192
