### ISSUE TITLE
Xcode 14.0 / ios 16 - Still not completely fixed

### ISSUE THREAD

**Issue by pasha-o** [xamarin/xamarin-macios#16165]
@dalexsoto The latest fix,  [Xcode 14.0 Support #15954](https://github.com/xamarin/xamarin-macios/issues/15954), on real apple device ios 16, compiles and deployes but visual studio debugger stops working with the message**The app has been terminated.**
The app gets deployed correctly and functions, but the ability to debug is lost.

### Steps to Reproduce

1. Install [xamarin.ios-16.0.0.72.pkg] on mac xcode 14
2. Visual studio 2022 for windows, set the linker to not linking , compile and deploy to apple ios 16 real device
3. the app is deployed , but the IDE terminates with the message "The app has been terminated"
4. the app indeed is deployed and works

### Expected Behavior
the iDE should keep the debugging session open
### Actual Behavior
he iDE doesnt keep the debugging session open
### Environment
Visual studio

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by LeoJHarris** [comment]
I can also confirm this, works on a mac when deploying and the debugger attaches but on VS just keeps giving this issue:

`
The application 'SampleApp.iOS' cannot be launched or debugged because it's not installed
The app has been terminated.
`

**Comment by IngweLand** [comment]
New update does not work for me as well. Still have same issue as before when using real device.
`Error running 'MyApp.iOS': Failed to install application on device mydevice ios 2: error HE0004: Could not load the framework 'DVTITunesSoftwareServiceFoundation' (path: /Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/DVTITunesSoftwareServiceFoundation): dlopen(/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/DVTITunesSoftwareServiceFoundation, 0x0001): Library not loaded: '@rpath/ContentDelivery.framework/Versions/A/ContentDelivery' Referenced from: '/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/DVTITunesSoftwareServiceFoundation' Reason: tried: '/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Library/Frameworks/Xamarin.iOS.framework/Versions/15.12.0.2/lib/mlaunch/mlaunch.app/Contents/MacOS/../Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/usr/lib/swift/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Library/Frameworks/Xamarin.iOS.framework/Versions/15.12.0.2/lib/mlaunch/mlaunch.app/Contents/MacOS/../Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/Versions/A/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file), '/System/Library/Frameworks/ContentDelivery.framework/Versions/A/ContentDelivery' (no such file)`

**Comment by rolfbjarne** [comment]
@IngweLand not sure what's happened, but you don't have the new version installed:

> /Library/Frameworks/Xamarin.iOS.framework/Versions/15.12.0.2

you have version 15.12.0.2, not 16.0.*

**Comment by LeoJHarris** [comment]
@rolfbjarne 

I have installed version 16.0.0.75 and still have the issue.

![image](https://user-images.githubusercontent.com/5468757/192893691-3ca5ef15-4801-42e6-8c69-890a3d6af189.png)

**Comment by IngweLand** [comment]
> @rolfbjarne
> 
> I have installed version 16.0.0.75 and still have the issue.
> 
> ![image](https://user-images.githubusercontent.com/5468757/192893691-3ca5ef15-4801-42e6-8c69-890a3d6af189.png)

Just overwrite as proposed. This issue happens every once in a while.

**Comment by LeoJHarris** [comment]
@IngweLand I did overwrite and still have the same issue. Did this resolve for you?

**Comment by IngweLand** [comment]
> @IngweLand not sure what's happened, but you don't have the new version installed:
> 
> > /Library/Frameworks/Xamarin.iOS.framework/Versions/15.12.0.2
> 
> you have version 15.12.0.2, not 16.0.*

Shame on me 😒 I have not investigated the error... Apparently, the update process did not fully succeed - VS updated, but Xamarin.iOS did not. Now, after the update, it's working. Thanks!

**Comment by IngweLand** [comment]
> @IngweLand I did overwrite and still have the same issue. Did this resolve for you?

What issue you are still having? You mean that this popup continue to appear even after you clicked Yes?
I do not have this issue right now because I am on MacOS. I just remember that I had it pretty much often before, when I was working on Windows. Also, please note, that it does take some time for that update process to finish - it's not instant after you click on Yes.

**Comment by LeoJHarris** [comment]
@IngweLand Yup I am aware the download and install can take time but on my windows still having the same issue with app crashing and debugger detaches on windows VS. Mac is fine, its the windows machine that is being problematic.
`
The application 'SampleApp.iOS' cannot be launched or debugged because it's not installed The app has been terminated.
`

Did you try on a windows machine?

**Comment by IngweLand** [comment]
> @IngweLand Yup I am aware the download and install can take time but on my windows still having the same issue with app crashing and debugger detaches on windows VS. Mac is fine, its the windows machine that is being problematic. `The application 'SampleApp.iOS' cannot be launched or debugged because it's not installed The app has been terminated.`
> 
> Did you try on a windows machine?

I do not have Windows machine now, unfortunately. You can try to investigate build logs to get more details what exectly went wrong (you may also try to add -v-v-v-v to cmd-line build input)

**Comment by tj-devel709** [comment]
@LeoJHarris Would you be able to provide us a binlog?
https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#build-logs

**Comment by LeoJHarris** [comment]
@tj-devel709 

Bin log:
[XamApp.iOS_CWHDebug_iPhone_Build_2022-09-30T09_06_17.7275870+13_00.zip](https://github.com/xamarin/xamarin-macios/files/9678773/XamApp.iOS_CWHDebug_iPhone_Build_2022-09-30T09_06_17.7275870%2B13_00.zip)

Build output:
[Output-Build.txt](https://github.com/xamarin/xamarin-macios/files/9678699/Output-Build.txt)

Exported logs:
[Logs.zip](https://github.com/xamarin/xamarin-macios/files/9678740/Logs.zip)

**Comment by tj-devel709** [comment]
Thank you for the logs. We will continue to look into this issue!

**Comment by tranb3r** [comment]
I'm getting this error in VS 17.3.5 (xamarin.ios 16.0.0.75):
```The Xcode version installed on the Mac (14.0) is not compatible with this version of Visual Studio. This may cause unexpected warnings or errors when building and deploying iOS projects. Please install Xcode '13.3'. To download a specific version of Xcode, visit: https://developer.apple.com/downloads.```

I thought xcode 14.0 was now supported. 
What's going on? What should I do? Why do you lock the main issue (#15954) if it's not fixed?

**Comment by digitalprj** [comment]
just saw that an update of Visual Studio (17.3.6) was released yesterday.
I installed the update now:
1. iOS simulators are available
2. iOS devices debugging is working

**Comment by dalexsoto** [comment]
As @digitalprj pointed out Visual Studio 17.3.6 was released yesterday which includes support for Xcode 14.0 on .NET 6 please give this a shot and if issues continue please re-open or file a new issue with the details.

**Comment by amirvenus** [comment]
There seems to be similar issues with Xcode 14.1

**Comment by mackayn** [comment]
Seeing the exact same thing with VS2022 17.2, M1 build host running XCode 14.1 & Ventura 13.0.1. Tested against an iPad 7th gen running iOS 1.6.1.1 and an iPhone 12 running 16.1.1.

This is a Xamarin Forms 5.0 (latest) app.
