### ISSUE TITLE
AL1012: 'arm64' is not a valid setting for option 'platform' thrown when localized resources are available and debugging on remote iOS device

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#16193]
---
**Issue moved from dotnet/maui#10342**
- Please respond to @ewerspej.

---

_From @ewerspej on Tuesday, September 27, 2022 10:30:08 AM_

### Description

When I try to debug an app on a remote iOS device (iPhone X running iOS 15.5) that is attached to my MacBook Pro, I keep receiving this error message in the console: 

AL1012: 'arm64' is not a valid setting for option 'platform'

**This only occurs when localized resources are available** (e.g. _resources.de.resx_)

### Steps to Reproduce

1. Use VS 17.4 Preview 2.1 for Windows
2. Create a .NET MAUI App project with .NET 6.0 or .NET 7.0
3. Add translations for strings, e.g. _resources.de.resx_
4. Attach an iPhone X running iOS 15.5 to your Mac
5. Connect to Mac
6. Start debugging on the remote device

Expected result: App runs on remote device
Actual result: AL1012: 'arm64' is not a valid setting for option 'platform'

### Link to public reproduction project repository

https://github.com/ewerspej/dotnet-maui-bug-repro-ios-arm64

### Version with bug

7.0.100-rc.1.22431.12
_(not working with previous version, either)_

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.5

### Did you find any workaround?

No

### Relevant log output

```shell
Build started...
1>------ Build started: Project: VisualCountDown, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
1>Executing SayHello Task to establish a connection to a Remote Server. 
1>			Properties: 
1>				SessionId=98293d747ad47ec5798b143b8f1f5246fe28a7ddf0ca91ed602593262c492f64, 
1>				Addresss=192.168.30.24, 
1>				SshPort=22, 
1>				TcpPort=59112, 
1>				User=Julian Ewers-Peters, 
1>				AppName=VisualCountDown,
1>				VisualStudioProcessId=11908,
1>				ContinueOnDisconnected=False
1>Executing SayHello Task to establish a connection to a Remote Server. 
1>			Properties: 
1>				SessionId=98293d747ad47ec5798b143b8f1f5246fe28a7ddf0ca91ed602593262c492f64, 
1>				Addresss=192.168.30.24, 
1>				SshPort=22, 
1>				TcpPort=59112, 
1>				User=Julian Ewers-Peters, 
1>				AppName=VisualCountDown,
1>				VisualStudioProcessId=11908,
1>				ContinueOnDisconnected=False
1>Detected signing identity:
1>  Code Signing Key: "Apple Development: Julian Ewers-Peters (H4YNPVSAM5)" (54D2880D911F98DEECF603395F14A9C0A6AAFCE1)
1>  Provisioning Profile: "VS: WildCard Development" (1fa321df-dcb0-4c46-95ac-3ce18f82f3fc)
1>  Bundle Id: com.companyname.visualcountdown
1>  App Id: P9BACKA8J2.com.companyname.visualcountdown
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>C:\Users\ewers\source\repos\VisualCountDown\VisualCountDown\Helpers\ServiceHelper.cs(5,25,5,26): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
1>ALINK : error AL1012: 'arm64' is not a valid setting for option 'platform'
1>Done building project "VisualCountDown.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:10,664 ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
========== Elapsed 00:10,664 ==========
```

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#10342**
- Please respond to @ewerspej.

---

_From @ewerspej on Tuesday, September 27, 2022 1:23:17 PM_

Adding this to the `<PropertyGroup>` where the _TargetFrameworks_ are set (temporarily) resolves the issue:

`<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>`

From:
https://stackoverflow.com/questions/71378075/publish-to-arm64-not-working-when-cultured-resx-file-added

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#10342**
- Please respond to @PureWeen.

---

_From @PureWeen on Tuesday, September 27, 2022 6:13:55 PM_

@rolfbjarne  thoughts?

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#10342**
- Please respond to @rolfbjarne.

---

_From @rolfbjarne on Wednesday, September 28, 2022 5:12:50 AM_

Would it be possible to get a build [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) of the failure?

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#10342**
- Please respond to @ewerspej.

---

_From @ewerspej on Wednesday, September 28, 2022 2:38:58 PM_

> Would it be possible to get a build [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) of the failure?

@rolfbjarne I will create an example project in a repo and I'll upload everything there. Then, you can also play around with the solution and try out the temporary fix above.

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#10342**
- Please respond to @ewerspej.

---

_From @ewerspej on Wednesday, September 28, 2022 3:17:21 PM_

@rolfbjarne the build succeeds when I use the console to build the project using the following command:

`dotnet build myproject.csproj /bl:msbuild.binlog`

I only receive the error when I use Visual Studio 17.4 Preview 2.1 to build. The console build probably doesn't use the connected Mac Agent, I suppose?

I've created a repo here: https://github.com/ewerspej/dotnet-maui-bug-repro-ios-arm64

**Comment by rolfbjarne** [comment]
@ewerspej:

You can get a binlog for a build in VS (Windows) like this: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#visual-studio-for-windows

You can also build remotely using the command line this: https://learn.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/#build-ios-apps-from-the-windows-command-line

**Comment by ewerspej** [comment]
> 

I will try that

**Comment by ewerspej** [comment]
> @ewerspej:
> 
> You can get a binlog for a build in VS (Windows) like this: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#visual-studio-for-windows
> 
> You can also build remotely using the command line this: https://learn.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/#build-ios-apps-from-the-windows-command-line

I will try that

**Comment by rolfbjarne** [comment]
> Is it possible to enable the _/bl:msbuild.binlog_ switch from within Visual Studio?

Kind of, you have to install an extension that allows you to save a binlog: https://github.com/dotnet/project-system-tools#project-system-tools

**Comment by ewerspej** [comment]
I will only be able to install the plugin and create a binlog after the weekend. Sorry about that

**Comment by ewerspej** [comment]
@rolfbjarne I've added a binlog to the repository: https://github.com/ewerspej/dotnet-maui-bug-repro-ios-arm64/blob/main/bug-ios-arm64/bug-ios-arm64_Debug_AnyCPU_net7.0-ios_Build_2022-10-10T09_34_03.0519455%2B02_00.zip

**Comment by rolfbjarne** [comment]
OK, I think I know what's going on.

When building using either VSMac or the command line (either from Windows or Mac), the `MSBuildRuntimeType` property is set to `Core`.

as a result, the default value for `GenerateSatelliteAssembliesForCore` is `true`:

```xml
<GenerateSatelliteAssembliesForCore Condition=" '$(GenerateSatelliteAssembliesForCore)' == '' and '$(MSBuildRuntimeType)' == 'Core' ">true</GenerateSatelliteAssembliesForCore>
```

Ref: https://github.com/dotnet/sdk/blob/00100960bf06cb595daba647673cd0329be896f4/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L41

Looks like this logic comes from here:

https://github.com/dotnet/sdk/commit/2506af1b3b24e53ac03bde81dbdb3f2bbead5d28

However, when building from inside Visual Studio (for Windows), the `MSBuildRuntimeType` property is set to `Full`, and thus `GenerateSatelliteAssembliesForCore` is not set to `true`, and we end up executing al.exe to generate satellite assemblies, which is wrong.

It seems to me that the problem is the logic to determine whether al.exe should be used or not.

**Comment by softlion** [comment]
Is it released in Version 17.4.0 Preview 6.0 ?

**Comment by rolfbjarne** [comment]
@softlion can you show your full version information (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#version-information)?

**Comment by softlion** [comment]
![image](https://user-images.githubusercontent.com/190756/200271413-3d2a155a-59b3-440e-9ee7-c33a6655f1a7.png)

**Comment by rolfbjarne** [comment]
@softlion no, the fix is not in those workloads. It will only be in the final .NET 7 release.
