### ISSUE TITLE
Change in behavior between Xamarin.Mac 7.x and 8.x relating to the shared target _CodesignAppBundle

### ISSUE THREAD

**Issue by somasekhar44** [xamarin/xamarin-macios#16197]
### Steps to Reproduce

1. Have Xamarin.mac ``7.4.0.4`` and ``8.10.0.5`` versions in ``/Library/Frameworks/Xamarin.Mac.framework/Versions``
2. Ensure signing is disabled at 'Project Options -> Build -> Mac Signing '
3. Set 7.4.0.4 as the current framework
4. Create a simple Xamarin.Mac project
5. Build it from Visual Studio
6. Exit Visual Studio and set 8.10.0.5 as the current framework
7. Open Visual Studio and build the project again

### Expected Behavior
Since signing is disabled, codesign is not run during the build with both 7.x and 8.x

### Actual Behavior
As expected, codesign is not run with 7.4.0.4 and I see the following in the log:
``Target "_CodesignAppBundle" skipped, due to false condition; ('$(_RequireCodeSigning)') was evaluated as ('false').``

But with 8.x, codesign is run:
```
Target "_CodesignAppBundle" in file "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Shared.targets":
  Using "ComputeCodesignItems" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Tasks.dll".
  Task "ComputeCodesignItems"
```

### Environment

<details>
<summary>Version information</summary>

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.10.25 (build 2)
Installation UUID: 8fb4b6e6-822f-414f-8759-473a64f05a5b
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000182

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.182 (2020-02/6051b710727) (64-bit)
	Package version: 612000182

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/5.0.408/Sdks
SDK Versions:
	5.0.408
	5.0.103
	5.0.102
	3.1.420
	3.1.406
	3.1.302
	3.1.301
	3.1.102
	3.1.101
	3.1.100
	3.0.100
	3.0.100-preview8-013656
	2.2.402
	2.1.701
	2.1.700
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.17
	5.0.3
	5.0.2
	3.1.26
	3.1.12
	3.1.6
	3.1.5
	3.1.2
	3.1.1
	3.1.0
	3.0.0
	3.0.0-preview8-28405-07
	2.2.7
	2.1.23
	2.1.20
	2.1.19
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11

=== .NET Core 3.1 SDK ===

SDK: 3.1.420

=== .NET 5.0 SDK ===

SDK: 5.0.408

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 14.0.1 (21336)
Build 14A400

=== Xamarin.Mac ===

Version: 8.10.0.5 (Visual Studio Professional)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

=== Xamarin.iOS ===

Version: 15.10.0.5 (Visual Studio Professional)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

=== Xamarin.Android ===

Version: 12.2.8.3 (Visual Studio Professional)
Commit: xamarin-android/d17-1/fafdba7
Android SDK: /Users/vggandha/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Build Information ===

Release ID: 810250002
Git revision: 0620af530b5800e0eada4882ce1c3d4dad7e53d3
Build date: 2022-06-15 13:41:26-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:17:10 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64


```

</details>

### Example Project (If Possible)

[HelloMacXamarinMac7.log](https://github.com/xamarin/xamarin-macios/files/9675786/HelloMacXamarinMac7.log)
[HelloMacXamarinMac8.log](https://github.com/xamarin/xamarin-macios/files/9675796/HelloMacXamarinMac8.log)

**Comment by somasekhar44** [comment]
With 8.x, some of our internal builds are failing with the following error. :

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Shared.targets(2045,3): error : /usr/bin/codesign exited with code 1
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Shared.targets(2045,3): error :         
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Shared.targets(2045,3): error : Failed to codesign '<path to file>.dylib': <path to file>.dylib: replacing existing signature
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Shared.targets(2045,3): error : <path to file>.dylib: No such file or directory
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Shared.targets(2045,3): error : 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Shared.targets(2045,3): error :   
```

However, file is present at the path specified.
Also, I can run the corresponding app from the terminal by going to ``bin/Debug/myApp.app/Contents/MacOs/myapp``

**Comment by tj-devel709** [comment]
Thank you for the feedback @somasekhar44.
Would you be able to provide a binlog?
https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#build-logs

**Comment by somasekhar44** [comment]
[Hello_Mac_Debug_Build_2022-09-29T19_03_43.3871990Z.binlog.zip](https://github.com/xamarin/xamarin-macios/files/9678327/Hello_Mac_Debug_Build_2022-09-29T19_03_43.3871990Z.binlog.zip)

Please find the binlog file. 

Also, I have attached diagnostic logs to the ticket in the ticket.

**Comment by somasekhar44** [comment]
With Xamarin.Mac 7.4.0.4
![Xamarin Mac 7](https://user-images.githubusercontent.com/7722978/193122737-daac5f77-35a2-4ff3-a6f1-64c683b8f527.png)

---

With Xamarin.Mac 8.10.0.5
![Xamarin Mac 8](https://user-images.githubusercontent.com/7722978/193122746-bd515012-90c8-4c0d-a2fd-1d00f474095d.png)

**Comment by rolfbjarne** [comment]
This looks like an oversight in our code.

Can you try setting the following property as a workaround until we can release a fix?

```xml
<PropertyGroup>
    <_CodesignAppBundleCondition>false</_CodesignAppBundleCondition>
</PropertyGroup>
```

**Comment by somasekhar44** [comment]
For now, I have reversed lines 2053 and 2054 at https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.Shared/Xamarin.Shared.targets#L2053

As I am developing only for mac, this is a temp change that worked for me. Line #2054 will not run if the project is for a macos app.

I can also try setting ``_CodesignAppBundleCondition`` to false as per the suggestion.
