### ISSUE TITLE
Native linking still fails on net6.0-ios. (duplicate symbols for architecture x86_64)

### ISSUE THREAD

**Issue by gdar91** [xamarin/xamarin-macios#16208]
When trying to build an app on .NET 6.0 Xamarin with native references to a static library (.a) I get native linking errors. The binding project and native references are set up according to the documentation. I've also tried specifying the full path and runtime identified as suggested [here](https://github.com/xamarin/xamarin-macios/issues/13503#issuecomment-987618861) but the problem persists.
The library I'm trying to link is [PortSIP SDK for Xamarin](https://www.portsip.com/download-portsip-voip-sdk/). The code is available on GitHub [here](https://github.com/gdar91/PortSip-iOS) and it requires ``-lresolv`` flag to build. I have contacted the PortSIP company, thinking their binaries are corrupted, but they confirmed, it builds well with older Xamarin and XCode 13.

### Steps to Reproduce

1. Clone this [reporitory](https://github.com/gdar91/PortSip-iOS).
2. Try to build for iPhone or iPhone simulator.

### Expected Behavior
The build should complete successfully and it should produce linked binaries.

### Actual Behavior
The build process fails with native linking errors:

``
ld: warning: ignoring file /Users/*****/PortSip-iOS/Bindings/bin/Debug/net6.0-ios/PortSip-iOS.Bindings.dll, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00 0x04 0x00 0x00 0x00 0xFF 0xFF 0x00 0x00 )
``

``
ld: 975 duplicate symbols for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation
``

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.3.6 (build 20)
Installation UUID: 63727473-b9e8-496b-803a-02f6b42ee519

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.1.2

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.401/Sdks
SDK Versions:
	7.0.100-rc.1.22431.12
	6.0.401
	6.0.400
	6.0.400-preview.22330.6
	6.0.302
	6.0.301
	6.0.300
	6.0.202
	6.0.201
	6.0.102
	6.0.101
	6.0.100
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Version: 3.1.423

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.0-rc.1.22426.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5
	6.0.4
	6.0.3
	6.0.2
	6.0.1
	6.0.0

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Version: 3.1.29

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-09-22 15:21:44 UTC

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin.Android
Version: 13.0.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-3/030cd63
Android SDK: /Users/gdar91/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		13.0 (API level 33)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 33.0.1
SDK Build Tools Version: 33.0.0 rc3

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.23
Hash: 965bf40
Branch: remotes/origin/d17-3
Build date: 2022-09-22 15:21:49 UTC

Android Device Manager
Version: 0.0.0.1169
Hash: fafb1d5
Branch: fafb1d5
Build date: 2022-09-22 15:21:49 UTC

Build Information
Release ID: 1703060020
Git revision: f7a6334599543f127e737d6de1f362bbe36cebca
Build date: 2022-09-22 15:19:46+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:19:52 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/9699018/msbuild.binlog.zip)

[Diagnostic build logs.txt](https://github.com/xamarin/xamarin-macios/files/9687144/Diagnostic.build.logs.txt)

### Example Project (If Possible)
[https://github.com/gdar91/PortSip-iOS](https://github.com/gdar91/PortSip-iOS)

**Comment by tj-devel709** [comment]
Thank you for your feedback @gdar91. Are you able to attach a binlog of the issue? 
https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#build-logs

**Comment by gdar91** [comment]
> Thank you for your feedback @gdar91. Are you able to attach a binlog of the issue?
> https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#build-logs

Done.

**Comment by tj-devel709** [comment]
Thanks for the build log @gdar91. Sorry for the miscommunication, I was referring to the binary build log (binlog) which can be found here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs. Please provide the binlog so we can take a closer look

**Comment by gdar91** [comment]
> Thanks for the build log @gdar91. Sorry for the miscommunication, I was referring to the binary build log (binlog) which can be found here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs. Please provide the binlog so we can take a closer look

Done. Added above the regular build logs.

**Comment by rolfbjarne** [comment]
The problem is that the native library was not built correctly.

There are at least two problems:

1. It defines a main method, a native library should _never_ have a `main` method:

```
$ nm -arch arm64 -gU PortSIPVoIPSDK.a
[...]
PortSIPVoIPSDK.a(makeCert.o):
---------------- T _main
```

2. Some object files are included twice. This is the main reason you get duplicate symbols: these symbols are literally duplicated in the library.

```
$ nm -arch arm64 -gU PortSIPVoIPSDK.a
[...]
PortSIPVoIPSDK.a(ExternalStreamFlow.o):
---------------- T __ZN7PortSIP11RTPDataSink12OnReadPacketEPcm
---------------- T __ZN7PortSIP11RTPDataSink12OnSendPacketEPcm
[...]
PortSIPVoIPSDK.a(ExternalStreamFlow.o):
---------------- T __ZN7PortSIP11RTPDataSink12OnReadPacketEPcm
---------------- T __ZN7PortSIP11RTPDataSink12OnSendPacketEPcm
[...]
```

You need to contact the vendor of the library and get a properly built library.
