### ISSUE TITLE
[BUG]Production App Crashes on ANY iPad but works fine on ANY iPhone since last update

### ISSUE THREAD

**Issue by norton287** [xamarin/xamarin-macios#16209]
### Steps to Reproduce

1. Build release for upload to TestFlight
2. Let App Be Updated Once Approved
3. Launch App on iPad with immediate crash, launch app on iPhone works perfectly

Also, the app debugs fine on a physical iPad perfectly, it is only in release mode this occurs.  I'm at a loss at what to try with a new VS and Xamarin.iOS and XCode as well.

### Expected Behavior

App has had no changes in the last month just doing a nuget update release (I did uninstall the nugets to check that as well) and I have never experienced this behavior before.

### Actual Behavior

Instant crash to desktop on iPad, I have tested this on 6 physical different iPads with the same result.  It works perfectly on the 4 different iPhones I have tested it on as well.  Which does not make sense to me.

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Enterprise 2022
Version 17.3.5
VisualStudio.17.Release/17.3.5+32922.545
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Enterprise

Visual C++ 2022   00482-10000-00261-AA779
Microsoft Visual C++ 2022

.NET Reactor   1.0
.NET Reactor Visual Studio Automation Package

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.376.3011
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22179.3
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.20 (3f4cb00)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.40629.1 Commit Hash:3f5cc0329815af3ffb948f08857446d206a9af36
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Django support   17.0.22179.3
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.22179.3
Profiling support for Python projects.

Python with Pylance   17.0.22179.3
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

ResX Resource Manager   ResXManager
Manage localization of all ResX-based resources in one place. Shows all resources of a solution and lets you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   17.0.32708.82
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.3.0.308 (d17-3@56b9f7e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.217 (remotes/origin/d17-3@b81db1dcc0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.28 (9b3d244)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6


Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs

[build log.txt](https://github.com/xamarin/xamarin-macios/files/9687773/build.log.txt)

**Comment by norton287** [comment]
Its something to do with setting the Minimum iOS version to 15 that is causing it.  Here is a crash output from the app:

Beta Identifier:     012DDA9A-CC52-4C5C-9B02-51E3A73B5BF8
Hardware Model:      iPad13,4
Process:             myapp.iOS [11599]
Path:                /private/var/containers/Bundle/Application/A2422A82-0B8D-4F1A-B946-5408470E8109/myapp.iOS.app/myapp.iOS
Identifier:          com.spec.myapp
Version:             1.3.13 (10)
AppStoreTools:       14A305
AppVariant:          1:iPad13,4:15
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.spec.myapp [478]

Date/Time:           2022-09-29 16:59:41.3955 -0500
Launch Time:         2022-09-29 16:59:41.3916 -0500
OS Version:          iPhone OS 15.6.1 (19G82)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: DYLD 1 Library missing
Library not loaded: '/System/Library/Frameworks/SensorKit.framework/SensorKit'
Referenced from: '/Volumes/VOLUME/*/myapp.iOS.app/myapp.iOS'
Reason: tried: '/System/Library/Frameworks/SensorKit.framework/SensorKit' (no such file)
(terminated at launch; ignore backtrace)

Triggered by Thread:  0

Thread 0 Crashed:
0   dyld                          	       0x10a440b14 __abort_with_payload + 8
1   dyld                          	       0x10a4466cc abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x10a446700 abort_with_payload + 16
3   dyld                          	       0x10a416a00 dyld4::halt(char const*) + 580
4   dyld                          	       0x10a413a20 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3560
5   dyld                          	       0x10a411d84 start + 488


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016d8f6cf8   x3: 0x00000000000000cd
    x4: 0x000000016d8f68f8   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000dc0
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x000000016d8f69ee  x11: 0x000000000000012e
   x12: 0x0000000000000000  x13: 0x0000000000000031  x14: 0x0000000215f14700  x15: 0x0000000000000000
   x16: 0x0000000000000209  x17: 0x000000010a43b1c8  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016d8f68f8  x21: 0x00000000000000cd  x22: 0x000000016d8f6cf8  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016d8f68f8  x26: 0x0000000000000400  x27: 0x0000000000000400
   x28: 0x00000000000000f6   fp: 0x000000016d8f68c0   lr: 0x000000010a4466cc
    sp: 0x000000016d8f6880   pc: 0x000000010a440b14 cpsr: 0x00001000
   far: 0x000000010a2a0000  esr: 0x56000080  Address size fault

Binary Images:
       0x10a3f8000 -        0x10a44ffff dyld arm64e  <66e1fb2668f8379ba052eb8b8291b5e1> /usr/lib/dyld

EOF

**Comment by norton287** [comment]
Think it is actually the Fingerprint plugin, testing

**Comment by norton287** [comment]
Nope, not that I had to lower the iOS requirement to 14 and then it loaded without crashing.  Found an old GitHub ticket that referenced this issue and they put in a fix for iOS 14.

**Comment by norton287** [comment]
See Here

[https://github.com/xamarin/xamarin-macios/issues/9938](https://github.com/xamarin/xamarin-macios/issues/9938)

**Comment by rolfbjarne** [comment]
Yes, this looks like #9938, so closing as a duplicate.
