### ISSUE TITLE
Visual Studio 2019 and XCode 14

### ISSUE THREAD

**Issue by mobilinked** [xamarin/xamarin-macios#16212]
Is there a new update for Visual Studio 2019 to support XCode 14? I know that VS 2022 supports XCode 14, but I have not found the new update for VS 2019 for XCode 14 support.

**Comment by dalexsoto** [comment]
Hello, 

The tooling for VS 2019 is currently out of support by our [current support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) so no, there is no plan to support Xcode 14 on VS 2019 at this point in time.
