### ISSUE TITLE
A DateTime.ToString with CultureInfo("nb-NO") gives the wrong datetime string output on iOS

### ISSUE THREAD

**Issue by jfversluis** [xamarin/xamarin-macios#16217]
---
**Issue moved from dotnet/maui#10441**
- Please respond to @sith-ikjetil.

---

_From @sith-ikjetil on Saturday, October 1, 2022 2:39:32 PM_

### Description

If you compile a .NET MAUI project for iOS, you get the wrong datetime format string for Norwegian output.
If you compile a .NET MAUI project for Windows or Android, you get the correct datetime format string for Norwegian output.

I use dotnet --version 6.0.401

### Steps to Reproduce

1. Create a new .NET MAUI APP and compile for iOS.
2. Anywhere like in 'MauiProgram.cs' do something like:
3. var dt = DateTime.Now.ToString( new CultureInfo("nb-NO"));
4. dt will look like: 10/1/2022 4:00:28 PM
5. dt should look like: 01.10.2022 16:00:286

### Link to public reproduction project repository

https://github.com/sith-ikjetil/maui-cultureinfo-no-bug

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

**Comment by jfversluis** [comment]
---
**Issue moved from dotnet/maui#10441**
- Please respond to @drasticactions.

---

_From @drasticactions on Monday, October 3, 2022 4:43:21 AM_

I doubt this is an issue specific with MAUI (The UI Framework) and (probably) more to do with either the runtime or SDK.

@rolfbjarne @dalexsoto Does that sound correct?

**Comment by jfversluis** [comment]
---
**Issue moved from dotnet/maui#10441**
- Please respond to @sith-ikjetil.

---

_From @sith-ikjetil on Monday, October 3, 2022 12:36:33 PM_

CurrentUICulture: Name: nb-US NativeName: 'nb (US)' DisplayName: 'nb (US)' EnglishName: 'nb (US)'
CurrentCulture: Name: nb-US NativeName: 'nb (US)' DisplayName: 'nb (US)' EnglishName: 'nb (US)'

@rolfbjarne This is what i got.

**Comment by sith-ikjetil** [comment]
I would like to point out that I forward a CultureInfo(“nb-NO”) to DateTime ToString method, so the current thread culture and uiculture should not matter. FYI.

**Comment by rolfbjarne** [comment]
Looks like we're not shipping culture info at all for Norwegian (nor a bunch of other languages).

These languages do not show in `CultureInfo.GetCultures (CultureTypes.AllCultures)`.

Some test code: https://gist.github.com/rolfbjarne/cd23c871acb6bfd6fab9acb75c285fa3#file-appdelegate-cs

Shows that there are [238 cultures for Mac Catalyst](https://gist.github.com/rolfbjarne/cd23c871acb6bfd6fab9acb75c285fa3#file-maccatalyst-md) (and likely the same for iOS and tvOS), while there are [940 cultures for macOS](https://gist.github.com/rolfbjarne/cd23c871acb6bfd6fab9acb75c285fa3#file-macos-md) - including Norwegian (and the date is also formatted as expected)

The culture data is shipped from the runtime, so I'm moving this bug there.

**Comment by rolfbjarne** [comment]
This issue was moved to dotnet/runtime#76596
