### ISSUE TITLE
Xcode 14.0 Simulators Support on Windows

### ISSUE THREAD

**Issue by taublast** [xamarin/xamarin-macios#16242]
This issue is related to https://github.com/xamarin/xamarin-macios/issues/15954 that has been closed. 
The closed issue 15954 fix resolves everything between VS ***for Mac*** and xcode 14.
The problem is the still broken compatibility between VS ***for Windows*** and xcode 14.

### Environment

Xamarin.iOS 16.0.0.75 installed on mac 

***WINDOWS***
Microsoft Visual Studio Community 2022
Version 17.3.5, VisualStudio.17.Release/17.3.5+32922.545
VisualStudio.Mac   1.0
Xamarin   17.3.0.308 (d17-3@56b9f7e)
Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7)

### Steps to Reproduce

We have the following compatibility action points:

1 - Pair with mac
- cannot auto-detect remote mac, need manually find with via entering IP or network name.
- ssh connect ok, but shows warning "this version of xcode (14) is not compatible with this version of vs please install 13.4"

2 - Remote build on mac
- works..

3 - Use remote iOS simulators
- shows an empty simulators list, only Generic Simulator is present

At the same time what is interesting is that the latest VS PREVIEW 2022 for windows auto detects remote mac fine, without the need to manually enter its ip. The rest is not working as it comes with an older Xamarin.iOS 15.xx.
The final tested setup was: preview uninstalled, vs 2022 stable repaired,  manually deleted
AppData\Local\Temp\Xamarin\XMA
AppData\Local\Xamarin\MonoTouch

**Comment by MartinZikmund** [comment]
Have the same issue, no Simulators and no devices showing up either

**Comment by tj-devel709** [comment]
Hello @taublast. This issue would be best handled by following the instructions [here](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) and reporting the issue through Visual Studio. 
I will be closing this issue here but feel free to re-open it later to discuss more.
Thank you!
