### ISSUE TITLE
Annotate `CheckSystemVersion` with `[Supported|Unsupported]OSPlatformGuard` attribute

### ISSUE THREAD

**Issue by Youssef1313** [xamarin/xamarin-macios#16250]
See https://github.com/dotnet/roslyn-analyzers/issues/6189#issuecomment-1268638533 for info

**Comment by chamons** [comment]
Turns out this actually is a roslyn-analzyer bug after discussing it with the engineer, filing shortly.

**Comment by chamons** [comment]
Moved to https://github.com/dotnet/roslyn-analyzers/issues/6204

**Comment by rolfbjarne** [comment]
Reopening because:

* The required support has been implemented in .NET 7 (although it won't ship in the initial .NET 7 release): https://github.com/dotnet/roslyn-analyzers/issues/6204
* We also need changes on our side.
