### ISSUE TITLE
AOT Compiler removes all attributes from some properties

### ISSUE THREAD

**Issue by juwens** [xamarin/xamarin-macios#16296]
AOT compiler strips away ColumnAttribute from entity classes when i run release AOT build on physical iphone.

Or:
- the AOT compiler makes something wrong when translating the attributes into AOT reflection-capable native code
- the reflection-code to retrieve attributes in AOT is flawed

I had issues with EF (column not found, because EF used the name of the property for the select, and not the via ColumnAttribute provided acutal column-name).

So i tried to read the property programatic via reflection without DbContext, and discovered: that there are zero attributes at the property in AOT release mode.

Does not happen anywhere else, not on Simulator, not with enabled interpreter.

I excluded other issues by setting.
- MtouchLink=None
- Optimize=False
- disable LLVM compilation 

```
public class MyEntity
{
    [Key]
    public int Id {get; set;}

    [Column("foo-bar")]
    public int FooBar {get; set;}
}
```

```
var type = typeof(MyEntity);
var prop = type.GetProperty(nameof(MyEntity.FooBar));

// null with AOT-release on physical device
// actual attribute in all other scenarios
var colAttr = prop.GetCustomAttribute<System.ComponentModel.DataAnnotations.Schema.ColumnAttribute>();

// zero elements with AOT-release on physical device
// one element in all other scenarios
var propAttributes = prop.GetCustomAttributes().ToArray();
```

[vs_details.txt](https://github.com/xamarin/xamarin-macios/files/9737592/vs_details.txt)

**Comment by chamons** [comment]
Thanks for the feedback. It seems more likely the linker is removing elements required by Entity Frameworks. 

As the issue does not include a sample project, I can't see what version of Entity Framework you are using, nor if this is a legacy or NET6 project. 

It is possible that changing [linker settings](https://learn.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=macos) might be helpful, but without more information I'm guessing at best.

**Comment by juwens** [comment]
@chamons thanks for looking into the issue.

I'm pretty sure that this is a mtouch problem, it happens with other attributes (for example "Newtonsoft.Json.JsonIgnoreAttribute") too.  
Theoratically it could be a xamarin SDK problem too, if it does not forward the MtouchLink property through the msbuild/target files.

`It seems more likely the linker is removing elements required by Entity Frameworks.`

It looks like that, but as i've pointed out: that i disabled linking with `MtouchLink=None`, this does not solve the problem. I also tried `linkskip` with all EF assemblies.
To follow your idea would mean: despite i've set `MtouchLink=None`, mtouch is linking anyway.

I'll try to create a sample project as soon as possible.

PS: am i correct, that MAUI uses the same mtouch, so the problem would also exist in MAUI? Or did the MAUI team write a new aot compiler for ios?

**Comment by juwens** [comment]
[**@chamons**](https://github.com/chamons)  
  
```
I can't see what version of Entity Framework you are using (EF3 = Entity Framework Core 3 possibly?), nor if this is a legacy or NET6 project.
```

it's Entity Framework Core 3, specificaly [3.1.30](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/3.1.30). This is the latest version which can be used with xamarin. because the highest common .net version in Xamarin is netstandard 2.0 (android + ios + **uwp**)

**Comment by juwens** [comment]
@chamons it's worse than i thought.    
The SAME attribute is removed from some properties, but kept on others.

```c#
public partial class ModInspectionResultPart : VehicleResultPart
{
    [JsonIgnore] // is present durring release+aot execution
    public IFoo<ModelA?> PropertyOne { get; }

    [JsonIgnore] // is NOT present durring release+aot execution
    public IFoo<ModelB?> PropertyTwo { get; }

}
```

**Comment by juwens** [comment]
How can i get the interim linker-output-dll from mtouch before aot-ing. I would like to inspect it with ILSpy, and see if the problem is a already there.

**Comment by rolfbjarne** [comment]
@juwens you can find the assemblies inside the project's obj directory.

**Comment by juwens** [comment]
@rolfbjarne please reopen it, at this is really an issue and i don't see  any solution on the horizon.  
  
i'm still diagnosing the issue. Sadly i was not able to reproduce the issue in a minimal sample.    
If you like we can have a zoom/teams meeting about it.  
  
I've read all attributes from all properties from all types of in our code, and it shows the issue again:  

*    physical-iphone+release+aot build on x86 mac (our build machine):  **3879** properties with at least one attribute
*    physical-iphone+release+aot build on m1 mac (my dev machine):  **3880** properties with at least one attribute
*    other builds (windows, android+jit, ios+release+interpreted): **3881** properties with at least one attribute

The interesting thing is, that ALL attributes get dropped from the affected property. 

So we can again rule out the the idea of your colleague, that the linker strips away the attribute-type.

Maybe it has something to do with the total amount of properties/attributes.    
Weird is, that the affected property, is completely identical to its neighbouring properties. \<- they have the same attributes and the same type.

**Comment by rolfbjarne** [comment]
@juwens I've reopened this, but we really need a way to reproduce it ourselves in order to track it down and figure out what's happening (i.e. we need a test project we can use to reproduce).

**Comment by juwens** [comment]
@rolfbjarne i can totally understand that. Sadly we cannot attach or inhouse LOB application source code on github.
What is your procedure for inhouse LOB app with strong intelectual property concerns?

**Comment by rolfbjarne** [comment]
@juwens there are a few options:

1. You can narrow the issue down to a test project that doesn't have any private source code.
2. You can file an issue here: https://developercommunity.visualstudio.com/VisualStudioMac/report, and once you've filed an issue, you can add private attachments that are only visible to Microsoft employees. An alternative some clients have done, and if your source code is stored in a private GitHub repository, is to invite the Microsoft employee to that repository.
3. In theory it's possible to get an NDA signed, but this means lawyers will get involved, and that will take a _long, long_ time (if there's ever success).

**Comment by juwens** [comment]
> * You can file an issue here: https://developercommunity.visualstudio.com/VisualStudioMac/report, and once you've filed an issue, you can add private attachments that are only visible to Microsoft employees. An alternative some clients have done, and if your source code is stored in a private GitHub repository, is to invite the Microsoft employee to that repository.

@rolfbjarne thanks, i will try my best to match the first two points.

**Comment by bryuho** [comment]
We had the similar issue in release builds for device. One particular attribute randomly dissappeared from one or another property. We found out a workaround which solves our issue. May be it helps somehow in this case too. We add the --nostrip flag in additional mtouch arguments.

**Comment by rolfbjarne** [comment]
Marked as need-info as explained here: https://github.com/xamarin/xamarin-macios/issues/16296#issuecomment-1288752718
