### ISSUE TITLE
VS for Mac Build Configuration

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/xamarin-macios#16300]
### Steps to Reproduce

1. Create blank XF project
2. Create/Copy new solution configuration (Any CPU). Debug2 for example:
![image](https://user-images.githubusercontent.com/6727366/194832920-43db4b24-24ab-4321-a69d-df25053892cf.png)
3. Change to newly created configuration:
![image](https://user-images.githubusercontent.com/6727366/194833174-2386f361-a20d-48f4-8b83-7d5430f492be.png)

### Expected Behavior
Not only simulators should be shown. Also physical devices, like debug config:
![image](https://user-images.githubusercontent.com/6727366/194833543-25526d42-5346-4a0e-8f81-943621699cf5.png)

### Actual Behavior
Only simulators are visible. 
### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac Preview
Version 17.3 Preview (17.3 build 1972)
Installation UUID: 8f9ec485-c3e1-4ec3-9e8d-45d0402aa368

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.1.2

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.302/Sdks
SDK Versions:
	6.0.302
	6.0.301
	6.0.300
	6.0.203
	6.0.202
	6.0.103
	6.0.102
	6.0.101
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.202
	5.0.103
	5.0.102
	5.0.101
	3.1.421
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	3.1.415
	3.1.408
	3.1.406
	3.1.405
	3.1.404
	3.1.301
	3.0.101
	3.0.100
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.7
	6.0.6
	6.0.5
	6.0.4
	6.0.3
	6.0.2
	6.0.1
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.5
	5.0.3
	5.0.2
	5.0.1
	3.1.27
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.14
	3.1.12
	3.1.11
	3.1.10
	3.1.5
	3.0.1
	3.0.0
	2.1.23
	2.1.19
	2.1.14
	2.1.13

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 13.4.1 (20504)
Build 13F100

Xamarin.Mac
Version: 8.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin Designer
Version: 17.3.0.201
Hash: 94069a36b
Branch: remotes/origin/d17-3
Build date: 2022-07-12 19:09:25 UTC

Xamarin.Android
Version: 12.3.3.3 (Visual Studio Community)
Commit: xamarin-android/d17-2/4e061b7
Android SDK: Not found

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.18
Hash: 59267e9
Branch: remotes/origin/main
Build date: 2022-07-12 19:09:30 UTC

Android Device Manager
Version: 0.0.0.1163
Hash: 3f16765
Branch: main
Build date: 2022-07-12 19:09:30 UTC

Build Information
Release ID: 1703001972
Git revision: 8eb3c1bb0f14a8e54ee7c227c7047c46cff6ee8c
Build date: 2022-07-12 19:07:34+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.3.1
Darwin 21.4.0 Darwin Kernel Version 21.4.0
    Fri Mar 18 00:45:05 PDT 2022
    root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64


```

</details>

**Comment by bnoffer** [comment]
Looks like you are on VS 2022 for Mac Preview 17.3, 17.3.6 stable is already out, so perhaps try updating to the latest VS first.

**Comment by AlleSchonWeg** [comment]
I'm using managed macincloud. So i can't update. But i think it worked now. For each platform (any cpu/iphone/iphone simluator) i have to set the correct target configuration for ios solution item:
Any Cpu -->Debug|Iphone Simulator
iPhone --> Debug|Iphone
Iphone Simulator --> Debug|Iphone Simulator
![image](https://user-images.githubusercontent.com/6727366/195016439-970d8775-8ac9-4681-9165-2b02a903927d.png)
But i need to set it under VS for Windows. Because changes in the configuration section are not saved in VS for Mac.

**Comment by chamons** [comment]
Thanks for your feedback, glad you were able to find a work around, though it sounds like it might have been fixed in a newer version.

In any case, the Visual Studio for Mac team is not accessible by github unfortunately. If you believe this still to be an issue, please [file a developer community ticket](https://developercommunity.visualstudio.com/report?space=41&entry=problem).
