### ISSUE TITLE
Xcode 14.0 still not working in VS 2022 17.3.6

### ISSUE THREAD

**Issue by AndreasReitberger** [xamarin/xamarin-macios#16319]
@dalexsoto

I just updated VS Studio 2022 (and Preview) to the latest version. Both still saying that XCode 14 is not supported.
I thought this was fixed?

> That said Visual Studio 2022 version 17.3.6 is now live and this brings Xcode 14 support to .NET 6 and MAUI. Sorry for all the inconveniences! Please let us know if you run into any issues!

https://github.com/xamarin/xamarin-macios/issues/16164

![image](https://user-images.githubusercontent.com/2952443/195379520-e061aa23-de56-44bc-a21f-54ac181a6ed2.png)

```
Microsoft Visual Studio Community 2022
Version 17.3.6
VisualStudio.17.Release/17.3.6+32929.385
Microsoft .NET Framework
Version 4.8.04084

Installierte Version: Community

Visual C++ 2022   00476-80000-00000-AA789
Microsoft Visual C++ 2022

Allgemeine Azure-Tools   1.10
Bietet allgemeine Dienste für die Verwendung durch Azure Mobile Services und Microsoft Azure-Tools.

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

Azure App Service-Tools v3.0.0   17.3.376.3011
Azure App Service-Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

C#-Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Cookiecutter   17.0.22179.3
Stellt Tools zum Suchen, Instanziieren und Anpassen von Vorlagen im Cookiecutter-Format bereit.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.20 (3f4cb00)
Support for debugging Mono processes with Visual Studio.

NuGet-Paket-Manager   6.3.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

Python – Unterstützung für die Profilerstellung   17.0.22179.3
Profilerstellungsunterstützung für Python-Projekte.

Python mit Pylance   17.0.22179.3
Stellt IntelliSense, Projekte, Vorlagen, Debuggen, interaktive Fenster und weitere Unterstützung für Python-Entwickler bereit.

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Stellt Sprachdienste für ASP.NET Core Razor bereit.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

TypeScript-Tools   17.0.10701.2001
TypeScript-Tools für Microsoft Visual Studio

Visual Basic-Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
KI-gestützte Entwicklung für Visual Studio.

VisualStudio.DeviceLog   1.0
Informationen zum Paket

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage-Erweiterung   1.0
Detaillierte Informationen zur VSPackage Visual Studio-Erweiterung

Xamarin   17.3.0.308 (d17-3@56b9f7e)
Visual Studio-Erweiterung, um Entwicklung für Xamarin.iOS und Xamarin.Android zu ermöglichen.

Xamarin Designer   17.3.0.217 (remotes/origin/d17-3@b81db1dcc0)
Visual Studio-Erweiterung zum Aktivieren der Xamarin Designer-Tools in Visual Studio.

Xamarin Templates   17.2.28 (9b3d244)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6


Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by AndreasReitberger** [comment]
Hi @dalexsoto 
Thanks for your respone.
Yes, I already have started XCode on my Mac. I also tried to repair VS studio via Visual Studio Installer.
It still keeps saying that the installed version (14.0) is not compatible, I should install 13.3.

![image](https://user-images.githubusercontent.com/2952443/195618730-96050c16-d7bf-40ad-9820-dba05fa337e2.png)

I only have one version installed on my mac, and this is 14.0.1.

**Comment by dalexsoto** [comment]
VS 2022 Preview does not have Xcode 14 support just yet, But VS 17.3.6 does, I wonder if the VS Extension has some sort of bug checking the Xcode version, can you try downloading Xcode 14.0.0 (note not 14.0.1) from here? https://developer.apple.com/download/all/

**Comment by AndreasReitberger** [comment]
At the moment I've removed both, VS 2022 and the Preview version from my computer. I'll only install the stable version and try again. If this is not working, I'll download XCode 14.
Just for the note XCode 14.0.1 is available since 26.09.2022.. Was there no tests with the latest versions of XCode?

I'll report back once I made the tests.

**Comment by AndreasReitberger** [comment]
So, I downloaded and installed XCode 14 on my mac.
At the XCode preferences I changed to 14.0

![image](https://user-images.githubusercontent.com/2952443/195641059-27f49a9d-0e8a-4fa4-a6b2-5514944ea805.png)
![image](https://user-images.githubusercontent.com/2952443/195641137-e6a4fde5-374b-4f9b-b52f-5e78cc8d15c5.png)

At VS 2022 I changed the default location for XCode.
![image](https://user-images.githubusercontent.com/2952443/195641389-6fdd6c47-4600-4a21-b24e-0e1023a94dd0.png)

And I still get the message that Xcode 14 is not supported...

**Comment by dalexsoto** [comment]
Unfortunately we do not manage the VS extension and that team is not reachable via GitHub, could you please file a bug using [Visual Studio Help menu](https://developercommunity.visualstudio.com/report?entry=problem)? This way you can reach out to the right team.

Sorry for the inconvenience.
