### ISSUE TITLE
MT4109: Failed to compile the generated registrar code.

### ISSUE THREAD

**Issue by kellogga** [xamarin/xamarin-macios#16372]
### Steps to Reproduce

1. Load solution into IDE
2. Compile
3. Unexpected error is thrown

### Expected Behavior
Successful compile

### Actual Behavior
Error MT4109

### Environment

<details>
<summary>Version information</summary>

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.25 (build 2)
Installation UUID: 04fadb56-def7-4c40-9178-39006ed32f44
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000182

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.182 (2020-02/6051b710727) (64-bit)
	Package version: 612000182

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/5.0.408/Sdks
SDK Versions:
	5.0.408
	5.0.405
	5.0.403
	5.0.402
	5.0.401
	5.0.202
	5.0.201
	5.0.102
	5.0.100
	3.1.420
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.408
	3.1.407
	3.1.405
	3.1.402
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.17
	5.0.14
	5.0.12
	5.0.11
	5.0.10
	5.0.5
	5.0.4
	5.0.2
	5.0.0
	3.1.26
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.14
	3.1.13
	3.1.11
	3.1.8
	2.1.23
	2.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.420

=== .NET 5.0 SDK ===

SDK: 5.0.408

=== Xamarin.Profiler ===

Version: 1.8.0.22
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 12.2.8.3 (Visual Studio Enterprise)
Commit: xamarin-android/d17-1/fafdba7
Android SDK: /Users/andrewkellogg/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

=== Apple Developer Tools ===

Xcode 14.0.1 (21336)
Build 14A400

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 15.10.0.5 (Visual Studio Enterprise)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

=== Build Information ===

Release ID: 810250002
Git revision: 0620af530b5800e0eada4882ce1c3d4dad7e53d3
Build date: 2022-06-15 13:41:26-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.5.1
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Wed Aug 10 14:25:27 PDT 2022
    root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

```

</details>

### Build Logs

Project "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/MobileTeleprompter.iOS.csproj" (Build target(s)):

Target _DetectDebugNetworkConfiguration:
      DebugIPAddresses: 192.168.2.44;fe80::aede:48ff:fe00:1122;fe80::1455:3bbf:c4c7:24;fe80::f8a4:d1ff:fe4b:836f;fe80::f8a4:d1ff:fe4b:836f;fe80::69d4:8e97:6aab:10ed;fe80::122:24d:9dfa:fbd5
Target _BeforeCoreCompileImageAssets:
  Skipping target "_BeforeCoreCompileImageAssets" because all output files are up-to-date with respect to the input files.
Target _DetectSigningIdentity:
    Detected signing identity:
            
      Code Signing Key: "iPhone Distribution: Société Radio-Canada" (8CB86A2E9AE32DF95E538CD682ACB4C27164C04E)
      Provisioning Profile: "Mobile Teleprompter - Distribution (2021-2022)" (2985c3df-8aec-4ca3-b503-bad5235cf3c8)
      Bundle Id: ca.radiocanada.mobileteleprompter
      App Id: 2S376Q6VJ2.ca.radiocanada.mobileteleprompter
Target _CoreCompileImageAssets:
  Skipping target "_CoreCompileImageAssets" because all output files are up-to-date with respect to the input files.
Target _BeforeCoreCompileInterfaceDefinitions:
  Skipping target "_BeforeCoreCompileInterfaceDefinitions" because all output files are up-to-date with respect to the input files.
Target _CoreCompileInterfaceDefinitions:
  Skipping target "_CoreCompileInterfaceDefinitions" because all output files are up-to-date with respect to the input files.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _CoreCompileSceneKitAssets:
  Skipping target "_CoreCompileSceneKitAssets" because it has no inputs.
Target _CoreCompileColladaAssets:
  Skipping target "_CoreCompileColladaAssets" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _CoreCompileTextureAtlases:
  Skipping target "_CoreCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileCoreMLModels:
  Skipping target "_BeforeCompileCoreMLModels" because all output files are up-to-date with respect to the input files.
Target _CoreCompileCoreMLModels:
  Skipping target "_CoreCompileCoreMLModels" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizePngImages:
  Skipping target "_CoreOptimizePngImages" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizePropertyLists:
  Skipping target "_CoreOptimizePropertyLists" because it has no inputs.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because it has no inputs.
Target _GetProjectReferenceTargetFrameworkProperties:
    __________________________________________________
    Project "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/MobileTeleprompter.iOS.csproj" is building "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter/MobileTeleprompter.csproj" (GetTargetFrameworks target(s)):

    __________________________________________________
    Project "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/MobileTeleprompter.iOS.csproj" is building "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter.IOS.LightningSerialCable/MobileTeleprompter.IOS.LightningSerialCable.csproj" (GetTargetFrameworks target(s)):

Target ResolveProjectReferences:
    __________________________________________________
    Project "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/MobileTeleprompter.iOS.csproj" is building "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter/MobileTeleprompter.csproj" (GetTargetPath target(s)):

    __________________________________________________
    Project "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/MobileTeleprompter.iOS.csproj" is building "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter.IOS.LightningSerialCable/MobileTeleprompter.IOS.LightningSerialCable.csproj" (GetTargetPath target(s)):

    __________________________________________________
    Project "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/MobileTeleprompter.iOS.csproj" is building "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter/MobileTeleprompter.csproj" (GetNativeManifest target(s)):

    __________________________________________________
    Project "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/MobileTeleprompter.iOS.csproj" is building "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter.IOS.LightningSerialCable/MobileTeleprompter.IOS.LightningSerialCable.csproj" (GetNativeManifest target(s)):

Target ResolveAssemblyReferences:
    Consider app.config remapping of assembly "SQLitePCLRaw.core, Culture=neutral, PublicKeyToken=1488e028ca7ab535" from Version "1.1.11.121" [] to Version "1.1.14.520" [/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/packages/SQLitePCLRaw.core.1.1.14/lib/Xamarin.iOS10/SQLitePCLRaw.core.dll] to solve conflict and get rid of warning.
    Consider app.config remapping of assembly "SQLitePCLRaw.batteries_v2, Culture=neutral, PublicKeyToken=8226ea5df37bcae9" from Version "1.1.11.121" [] to Version "1.1.14.520" [/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/packages/SQLitePCLRaw.bundle_green.1.1.14/lib/Xamarin.iOS10/SQLitePCLRaw.batteries_v2.dll] to solve conflict and get rid of warning.
    Consider app.config remapping of assembly "System.Reactive.Interfaces, Culture=neutral, PublicKeyToken=94bc3704cddfc263" from Version "3.0.0.0" [/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter/bin/Debug/System.Reactive.Interfaces.dll] to Version "3.0.6000.0" [/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/packages/System.Reactive.Interfaces.4.1.5/lib/netstandard2.0/System.Reactive.Interfaces.dll] to solve conflict and get rid of warning.
    Consider app.config remapping of assembly "System.Reactive.Core, Culture=neutral, PublicKeyToken=94bc3704cddfc263" from Version "3.0.1000.0" [/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter/bin/Debug/System.Reactive.Core.dll] to Version "3.0.6000.0" [/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/packages/System.Reactive.Core.4.1.5/lib/netstandard2.0/System.Reactive.Core.dll] to solve conflict and get rid of warning.
    Consider app.config remapping of assembly "System.Reactive.Linq, Culture=neutral, PublicKeyToken=94bc3704cddfc263" from Version "3.0.1000.0" [/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter/bin/Debug/System.Reactive.Linq.dll] to Version "3.0.6000.0" [/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/packages/System.Reactive.Linq.4.1.5/lib/netstandard2.0/System.Reactive.Linq.dll] to solve conflict and get rid of warning.
    /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2218,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
Done building target "ResolveAssemblyReferences" in project "MobileTeleprompter.iOS.csproj".
Target _UnpackLibraryResources:
        Up to date: packages.config
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target XamlG:
  Skipping target "XamlG" because it has no outputs.
Target CssG:
  Skipping target "CssG" because it has no outputs.
Target CssG:
  Skipping target "CssG" because it has no outputs.
Target XamlG:
  Skipping target "XamlG" because it has no outputs.
Target CoreCompile:
  Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
Target XamlC:
  Skipping target "XamlC" because all output files are up-to-date with respect to the input files.
Target _CopyFilesMarkedCopyLocal:
    Touching "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/obj/iPhone/Debug/MobileTeleprompter.iOS.csproj.CopyComplete".
Target GetCopyToOutputDirectoryItems:
    Target _GetCopyToOutputDirectoryItemsFromTransitiveProjectReferences:
        __________________________________________________
        Project "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/MobileTeleprompter.iOS.csproj" is building "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter/MobileTeleprompter.csproj" (GetCopyToOutputDirectoryItems target(s)):

        __________________________________________________
        Project "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/MobileTeleprompter.iOS.csproj" is building "/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/MobileTeleprompter.IOS.LightningSerialCable/MobileTeleprompter.IOS.LightningSerialCable.csproj" (GetCopyToOutputDirectoryItems target(s)):

Target _CopyAppConfigFile:
  Skipping target "_CopyAppConfigFile" because all output files are up-to-date with respect to the input files.
Target CopyFilesToOutputDirectory:
    MobileTeleprompter.iOS -> /Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/bin/iPhone/Debug/MobileTeleprompter.iOS.exe
Target _CopyResourcesToBundle:
  Skipping target "_CopyResourcesToBundle" because all output files are up-to-date with respect to the input files.
Target _WriteAppManifest:
  Skipping target "_WriteAppManifest" because all output files are up-to-date with respect to the input files.
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/obj/iPhone/Debug/device-builds/ipad5.3-15.7/response-file.rsp 
    Xamarin.iOS 15.10.0.5 (d17-2: 96b3edb6d) using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk
    MTOUCH : warning MT0178: Debugging symbol file for '/Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/packages/Xamarin.Forms.4.1.0.581479/lib/Xamarin.iOS10/Xamarin.Forms.Platform.iOS.dll' is not valid and was ignored.
            
    Compilation failed with code 1, command:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wno-receiver-forward-class -Wno-objc-missing-super-calls -Wno-unguarded-availability-new -stdlib=libc++ -gdwarf-2 -std=c++14 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/15.10.0.5/SDKs/MonoTouch.iphoneos.sdk/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk -Qunused-arguments -miphoneos-version-min=7.0 -arch arm64 -c -o /Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/obj/iPhone/Debug/device-builds/ipad5.3-15.7/mtouch-cache/arm64/registrar.o -x objective-c++ -D DEBUG /Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/obj/iPhone/Debug/device-builds/ipad5.3-15.7/mtouch-cache/registrar.m
    In file included from /Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/obj/iPhone/Debug/device-builds/ipad5.3-15.7/mtouch-cache/registrar.m:3:
    /Users/andrewkellogg/Projects/mets-apps-mase-mobile-teleprompter/mets-apps-mase-mobile-teleprompter/iOS/obj/iPhone/Debug/device-builds/ipad5.3-15.7/mtouch-cache/registrar.h:111:9: fatal error: 'CHIP/CHIP.h' file not found
    #import <CHIP/CHIP.h>
            ^~~~~~~~~~~~~
    1 error generated.
    MTOUCH : error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
Done building target "_CompileToNative" in project "MobileTeleprompter.iOS.csproj" -- FAILED.

Done building project "MobileTeleprompter.iOS.csproj" -- FAILED.

**Comment by marcinbinczyk** [comment]
Same problem, ends with missing "CHIP/CHIP.h" file

**Comment by marcinbinczyk** [comment]
Works again using latest preview channel libraries and VS2022 preview

**Comment by kellogga** [comment]
Thank you Marcin, upgrading to VS2022 worked.

*Andrew Kellogg*
Senior Developer
Technology & Infrastructure
*Cell: 647.267.9829*

**Comment by dalexsoto** [comment]
You are using version 15 of our products, please update to the latest stable (16.x) or our latest previews and try again.
