### ISSUE TITLE
Don't process assemblies over and over again in the UnpackLibraryResources target 

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#16377]
The `UnpackLibraryResources` target does not specify Inputs/Outputs, so it has to re-process every assembly every time the target is executed.

We can make this better, by adding Inputs/Outputs and using stamp files, which will make the target only have to re-process files that have actually changed.

**Comment by rolfbjarne** [comment]
CC @dellis1972

**Comment by jonathanpeppers** [comment]
Here was a target that does run completely partially:

https://github.com/xamarin/xamarin-android/blob/91669a4e489104668fdd07382e40cf070aa559ac/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1428-L1452

If you look at a `.binlog` for it, MSBuild runs the `<LinkAssembliesNoShrink/>` task once, and MSBuild magically only puts the changed items in `SourceFiles` and `DestinationFiles`.
