### ISSUE TITLE
[net7.0-rc2] Creating a cross-targeted library with net6.0-mac fails with an obscure error

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#16400]
### Steps to Reproduce
Without having the macos SDK installed, build the following:
```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net6.0-macos</TargetFrameworks>
	</PropertyGroup>
</Project>
```

### Expected Behavior

An error from .NET SDK to flag that a workload is missing.

### Actual Behavior

```
1>C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1220,3): 
error MSB4019: The imported project "C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.NET.Sdk\12.3.1186-rc.2\targets\Xamarin.Shared.Sdk.MultiTarget.targets" was not found. 
Confirm that the expression in the Import declaration ";..\12.3.1186-rc.2\targets\Xamarin.Shared.Sdk.MultiTarget.targets" is correct, and that the file exists on disk.
```

### Environment

```
dotnet --version
7.0.100-rc.2.22477.23
```
```
dotnet workload list

Installed Workload Id      Manifest Version                         Installation Source
---------------------------------------------------------------------------------------
ios                        16.0.1271-rc.2-xcode14/7.0.100-rc.2      VS 17.4.33015.44
maui-android               7.0.0-rc.2.6866/7.0.100-rc.2             VS 17.4.33015.44
maui-windows               7.0.0-rc.2.6866/7.0.100-rc.2             VS 17.4.33015.44
maui-maccatalyst           7.0.0-rc.2.6866/7.0.100-rc.2             VS 17.4.33015.44
android                    33.0.0-rc.2.202/7.0.100-rc.2             VS 17.4.33015.44
maccatalyst                15.4.1186-rc.2/7.0.100-rc.2              VS 17.4.33015.44
maui-ios                   7.0.0-rc.2.6866/7.0.100-rc.2             VS 17.4.33015.44

Use `dotnet workload search` to find additional workloads to install.
```

**Comment by rolfbjarne** [comment]
Can you get a binlog from a command line build?

> $ dotnet build /bl:msbuild.binlog

That will tell us exactly what you have installed and what's loaded during the build.

**Comment by jeromelaban** [comment]
I wish I had taken the binlog before creating the issue and fixing it :) I'll see if I can remove the workload to repro.

**Comment by jeromelaban** [comment]
Here's some update.

The above message only happens when built from VS windows, not on the CLI.

Here's the binlog captured from VS: [issue16400.zip](https://github.com/xamarin/xamarin-macios/files/9832361/issue16400.zip) and the CLI: [16400-msbuild-cli.zip](https://github.com/xamarin/xamarin-macios/files/9832379/16400-msbuild-cli.zip)

**Comment by rolfbjarne** [comment]
Looks like this happens when the IDE executes the `_SdkGetRidsPerTargetFramework` target. It should be fairly easy to work around on our side (check if the corresponding file exists before trying to import it), but this is in a rather sensitive code path, and since it seems to be easy enough to work around (install the macOS workload), I'm going to target .NET 8 for the fix.

**Comment by rolfbjarne** [comment]
Tentative fix: https://github.com/rolfbjarne/xamarin-macios/commit/af47d23c4748524bc7f6e587f6ce36bf36be7c18 (for .NET 8).

**Comment by steowens** [comment]
This happens with most of the visual studio templates. About the only thing that works is the WSP.  The other stuff is just vaporware.

**Comment by lukasf** [comment]
I am hitting this error message, even though the macos workload is installed:

```
Installierte Workload-ID      Manifestversion        Installationsquelle
-----------------------------------------------------------------------------------
android                       33.0.4/7.0.100         SDK 7.0.100, VS 17.4.33213.308
ios                           16.1.1477/7.0.100      SDK 7.0.100, VS 17.4.33213.308
maccatalyst                   16.1.1477/7.0.100      SDK 7.0.100, VS 17.4.33213.308
macos                         13.0.2032/7.0.100      SDK 7.0.100
maui-windows                  7.0.52/7.0.100         VS 17.4.33213.308
maui-maccatalyst              7.0.52/7.0.100         VS 17.4.33213.308
maui-ios                      7.0.52/7.0.100         VS 17.4.33213.308
maui-android                  7.0.52/7.0.100         VS 17.4.33213.308
```

Build error:

`1>C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1226,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\13.0.2032\targets\Xamarin.Shared.Sdk.MultiTarget.targets" was not found. Confirm that the expression in the Import declaration ";..\13.0.2032\targets\Xamarin.Shared.Sdk.MultiTarget.targets" is correct, and that the file exists on disk.
`

I am trying to create a new cross-platform UNO library, but hitting this bug. Any ideas? How can I work around this?

**Comment by jeromelaban** [comment]
@lukasf this generally happens because VS does not install the macos workload by default (among some other unknown parts).

You can try going into the `.Mobile` folder, then run `dotnet workload install macos`.

**Comment by lukasf** [comment]
Thank you. This solved my problem. It is a bit weird though, that I have to install the macos workload when it is already shown in the list of installed workloads. When running the command, I even got a warning that it is already installed, but then it started installing a whole lot of stuff and now it builds correctly.
