### ISSUE TITLE
App crashes ONLY in "release && real-iphone && interpreter" for no apparent reason, even with try-catch around the call 

### ISSUE THREAD

**Issue by juwens** [xamarin/xamarin-macios#16413]
### Steps to Reproduce

1. Start app
2. Press the "continue"-button in our app, which in essence will result in a navigation to the next page
3. crash

### Expected Behavior
- app should not crash, because the app works fine in any other configuration/platform. It not even crashes on "release && real-iphone && aot"
  - i even added a try-catch around the call, to catch a potential exception which is not there. the app crashes anyway

### Actual Behavior
app crashes every thimne

### Environment

- Autofac: 6.4.0
- Autofac.Extensions.DependencyInjection: 8.0.0

```
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhone' ">
    <DebugType>none</DebugType>
    <Optimize>false</Optimize> <!-- default is true. i tried that. same crash. -->
    <OutputPath>bin\iPhone\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <MtouchArch>ARM64</MtouchArch>
    <CodesignKey>iPhone Developer</CodesignKey>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <MtouchLink>None</MtouchLink>
    <MtouchInterpreter>-all</MtouchInterpreter>
  </PropertyGroup>
```
<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.3.7 (build 11)
Installation UUID: 2e6f795b-91b4-451c-bcf8-68a38fa23194

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.2.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.402/Sdks
SDK Versions:
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.300
	6.0.101
	6.0.100
MSBuild SDKs: /Applications/Visual Studio Stable.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.300
	6.0.105
	6.0.104
	6.0.102
	6.0.101
	5.0.408
	5.0.407
	5.0.405
	5.0.404
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.419
	3.1.418
	3.1.416

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.5
	6.0.1
	6.0.0

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.5
	6.0.4
	6.0.2
	6.0.1
	5.0.17
	5.0.16
	5.0.14
	5.0.13
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.25
	3.1.24
	3.1.22

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.0.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-3/030cd63
Android SDK: /Users/jjaehrig/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.23
Hash: 965bf40
Branch: remotes/origin/d17-3
Build date: 2022-10-05 17:23:04 UTC

Android Device Manager
Version: 0.0.0.1169
Hash: fafb1d5
Branch: fafb1d5
Build date: 2022-10-05 17:23:04 UTC

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-10-05 17:22:59 UTC

Apple Developer Tools
Xcode 14.0.1 (21336)
Build 14A400

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Build Information
Release ID: 1703070011
Git revision: b625496a1b9780a50e1935e641beecf8979c795b
Build date: 2022-10-05 17:21:01+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:20:05 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64

```

</details>

### Build Logs

[build_log.txt](https://github.com/xamarin/xamarin-macios/files/9845480/build_log.txt)

### Example Project (If Possible)

[crash_log.txt](https://github.com/xamarin/xamarin-macios/files/9845484/crash_log.txt)

**Comment by juwens** [comment]
@rolfbjarne can you please take a look at this, after fighting with issue https://github.com/xamarin/xamarin-macios/issues/16296, i decided to enable the interpreter in release build, and now i stumble upon an even worse bug :-/  

What's going on with mono for iOS? This is really frustrating. :-/

**Comment by bnoffer** [comment]
I am currently fighting an issue on Xamarin.iOS with Xamarin.Forms where on iOS the App just freezes after it has finished launching. Does not crash or anything. This sounds similar. With sentry.io I was able to pinpoint to a System.NullReferenceException that is marked as UnobservedTaskException, but I am unable to capture it in order to get more information and it provides 0 information for the cause. You can see the full story here: https://stackoverflow.com/questions/73926385/xamarin-forms-app-locks-up-for-no-apparent-reason

Reading this and your previous issue I probably will try migrating the App to .NET MAUI now that the XCode 14 Support is out and MAUI is then using .NET 6 instead of Mono.

**Comment by juwens** [comment]
@bnoffer you fell into a marketing trap here.  
maui uses .Net 6 library (.Net BCL), but still the mono compiler and runtime and interpreter.

**Comment by bnoffer** [comment]
Thanks for the correction and I should have remembered that. Got onto the wrong track since sentry.io is labeling .NET MAUI to be running on .NET 6 instead of Mono. Funny how quickly you get off track by a tool showing the wrong thing.

**Comment by rolfbjarne** [comment]
@juwens could you please attach your project so that we can reproduce this ourselves?

**Comment by juwens** [comment]
@rolfbjarne of course i cannot attach my inhouse LOB application source code on github.
What is your procedure for inhouse LOB app with strong intelectual property concerns?

**Comment by dalexsoto** [comment]
Hello @juwens if you can create a separated repro project that you can post here that would be useful otherwise you will need to go via this link https://support.serviceshub.microsoft.com/supportforbusiness

**Comment by juwens** [comment]
@dalexsoto @rolfbjarne i've invited you to a private repo, for this ticket.

**Comment by rolfbjarne** [comment]
OK, thanks for the repro case, and I can reproduce.

This is the assertion that fails:

> error: * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/mono/mini/interp/interp.c:2339, condition `is_ok (error)' not met, function:do_jit_call, Attempting to JIT compile method '(wrapper other) void object:gsharedvt_out_sig (object&,object&,double&,intptr)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
 assembly:<unknown assembly> type:<unknown type> member:(null)

**Comment by juwens** [comment]
Thanks for taking a look into it 👍

**Comment by rolfbjarne** [comment]
@juwens I see you've enabled the interpreter, but then disabled it for all assemblies. Is there any particular reason for this configuration?

I tried enabling the interpreter for all assemblies, and this makes the app not crash anymore.

Diff for your project file:

```diff
@@ -59,7 +59,7 @@
     <CodesignKey>iPhone Developer</CodesignKey>
     <MtouchDebug>true</MtouchDebug>
     <MtouchLink>None</MtouchLink>
-    <MtouchInterpreter>-all</MtouchInterpreter>
+    <MtouchInterpreter>all</MtouchInterpreter>
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhone' ">
     <DebugType>none</DebugType>
@@ -72,7 +72,7 @@
     <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
     <MtouchLink>None</MtouchLink>
     <CodesignProvision>Automatic</CodesignProvision>
-    <MtouchInterpreter>-all</MtouchInterpreter>
+    <MtouchInterpreter>all</MtouchInterpreter>
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Ad-Hoc|iPhone' ">
     <DebugType>none</DebugType>
```

**Comment by juwens** [comment]
Thanks a lot, I understand what you did there. 

We were totally not aware, that „enable interpreter“ in the iOS App via VS4Mac (which set’s the `-all`) interprets only this single project.  
I falsely assumed the dash was necessary, because it is used 1:1 as a commandline parameter.

I was searching for docs for MtouchInterpreter, but did not find any real docs.

Only this old Blog Post, about experimental! support for the interpreter. And it’s not explained there either.

And now, that I know what to look for, I found one! explanation in a repo which subtitle is `Quick and dirty experiments with Xamarin.iOS and the IL interpreter` 😄 
https://github.com/spouliot/interpreter  
FAQ.4: `Enable the *experimental* interpreter. […] if prefixed with a minus sign, the assembly will be AOT-compiled`.

Anyway, thanks a lot and have a nice Halloween (if you are into it).  
And consider adding an explicit subpage in the Maui docs for this build property :)


Cheers, Jens

**Comment by juwens** [comment]
Thanks for the link.  

That might be another thing, that there are different docs for xamarin with different information. The "official" docs (i usually look at): https://learn.microsoft.com/en-us/xamarin/ and the wiki pages in the project.

The google/github-wiki indexing issue also does not help :-/

**Comment by juwens** [comment]
@rolfbjarne one last question. if i check! "enable mono interpreter" in vs4mac, it puts `<MtouchInterpreter>-all</MtouchInterpreter>` into the matching PropertyGroup. Which by your explanation disables the interpreter for all assemblies.    
Is this a bug, which i should report to vs4mac, or is this correct? 🤔

<img width="441" alt="image" src="https://user-images.githubusercontent.com/11560817/198629212-7afb2af0-3009-49fa-aebf-26b6a97a8976.png">

**Comment by rolfbjarne** [comment]
> Is this a bug, which i should report to vs4mac, or is this correct? 🤔

It's expected, but it seems you've run into a corner case where it doesn't work.

The idea behind it (from many years ago), was to able the interpreter (which some features require), while at the same time AOT as much as possible (because that's faster).
