### ISSUE TITLE
The application cannot be launched or debugged because it's not installed The app has been terminated.

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/xamarin-macios#16474]
When the app launches in debug mode the app immediately crashes with the output:

`
The application 'Sample.iOS' cannot be launched or debugged because it's not installed
The app has been terminated.
`

### Build Logs

See logs from this comment where mentioned this problem from a previous issue:

https://github.com/xamarin/xamarin-macios/issues/16165#issuecomment-1262760001

**Comment by LeoJHarris** [comment]
This is still very much happening. App crashes as soon as launched and not longer able to debug from windows paired to a mac....

**Comment by LeoJHarris** [comment]
Any update at all.....

**Comment by rolfbjarne** [comment]
Does it happen with a specific project, or all projects? (i.e. does it work if you create a new project from a template?)
