### ISSUE TITLE
Binding Swift Library Walkthrough errors at step 11.

### ISSUE THREAD

**Issue by dannyatger** [xamarin/xamarin-macios#16512]
### Steps to Reproduce
Follow the walkthrough steps as documented in: 
https://learn.microsoft.com/en-us/xamarin/ios/platform/binding-swift/walkthrough
[last update was 7/14/2022 as of posting this issue]

1. Follow the walkthrough as best as possible.
2. For steps 2-5, they failed to work for me, so I replaced them with:
3. Go to File -> Add Package and use the Gigya URL: https://github.com/SAP/gigya-swift-sdk.git and add 3 frameworks in this git repository.
4. When I do build inside Xcode, it builds without error.  However when I tried to build via command line per step 11, I get errors.

### Expected Behavior
no error
### Actual Behavior

see error logs files attached. 
[err.build1.log](https://github.com/xamarin/xamarin-macios/files/9898285/err.build1.log)
[err.build2.log](https://github.com/xamarin/xamarin-macios/files/9898286/err.build2.log)

### Environment

I'm on MacBook Pro M1 Max macOS 12.6.1
Xcode 14.0.1 with command line for 13.4.1.

xcodebuild -version outputs:
Xcode 13.4.1
Build version 13F100

xcodebuild -showsdks outputs:
2022-10-31 14:22:46.821 xcodebuild[68394:1345218] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-10-31 14:22:46.821 xcodebuild[68394:1345218] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
DriverKit SDKs:
	DriverKit 21.4                	-sdk driverkit21.4

iOS SDKs:
	iOS 15.5                      	-sdk iphoneos15.5

iOS Simulator SDKs:
	Simulator - iOS 15.5          	-sdk iphonesimulator15.5

macOS SDKs:
	macOS 12.3                    	-sdk macosx12.3

tvOS SDKs:
	tvOS 15.4                     	-sdk appletvos15.4

tvOS Simulator SDKs:
	Simulator - tvOS 15.4         	-sdk appletvsimulator15.4

watchOS SDKs:
	watchOS 8.5                   	-sdk watchos8.5

watchOS Simulator SDKs:
	Simulator - watchOS 8.5       	-sdk watchsimulator8.5

<details>
<summary>Version information</summary>

```
```

</details>

### Build Logs

[SwiftFrameworkProxy.zip](https://github.com/xamarin/xamarin-macios/files/9898291/SwiftFrameworkProxy.zip)

**Comment by rolfbjarne** [comment]
This issue was moved to MicrosoftDocs/xamarin-docs#3520
