### ISSUE TITLE
iOS app failing to hit OnStart with .NET MAUI

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#16532]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/iOS-app-failing-to-hit-OnStart-with-NET/10157436)._

---
I have an application which seems to have hit a snag. The app never hits the .NET MAUI application in App.xaml.cs. If I set a breakpoint on the first line of the App.xaml.cs file, it is never reached. The splash screen appears, disapeears and then nothing - dead black screen and the application just hangs.

I have removed the code that starts the Firebase ininitalisation as well as disabing the remote notifications in the info.plist file and get the same result. This issue is repeatable for the simulators and on my iPhone (doesn't matter if it's attaced to the mac or the PC, I get the same black screen result)

---
#### Feedback Bot on 9/26/2022, 08:15 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rolfbjarne** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide your [full build logs](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs), [crash reports](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#crash-reports) (if any), test case (to reproduce) and all your [version information](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#version-information).

We look forward to hearing from you!
