### ISSUE TITLE
Hot Restart does not support xcframeworks or binding resource packages

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#16571]
It seems Hot Restart does not support neither xcframeworks nor binding resource packages.

Ref: https://github.com/dotnet/maui/issues/10800#issuecomment-1289004212
Ref: https://github.com/dotnet/maui/issues/10800#issuecomment-1301564278

Note that this is a mirror issue for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1656382.

**Comment by mattjohnsonpint** [comment]
I notice this has been labeled for .NET 8.  Should I expect then that the fix won't be released for .NET 6 or 7 then?  I need to know, so I can decide whether or not I should include a custom build target in my own nuget package as a workaround in the meantime.  Thanks.

**Comment by rolfbjarne** [comment]
@mattjohnsonpint once it's fixed, we'll decide exactly where to backport it. However, it's certainly not going to be in the initial .NET 7 release (since packages are already public at NuGet.org).

My recommendation would be to include a workaround with your NuGet if that's possible (just make sure that the workaround is compatible with the fix too).
