### ISSUE TITLE
AOT build fails if a specific NuGet package is referenced in MacCatalyst app

### ISSUE THREAD

**Issue by edoust** [xamarin/xamarin-macios#16604]
Not sure if this issue is with Xamarin or Microsoft Graph is just too large for AOT build, also opened an issue here: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1550

### Steps to Reproduce

1. Reference Microsoft Graph SDK preview 15
2. Set `RuntimeIdentifier` to `maccatalyst-arm64`
3. See the build fail with this error message: `/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.4.465/targets/Xamarin.Shared.Sdk.targets(3,3): Error: Failed to AOT compile Microsoft.Graph.dll, the AOT compiler exited with code 134 (repro-aot)`

### Expected Behavior
AOT compilation of arm64 catalyst apps should succeed no matter what nuget package I reference

### Actual Behavior
Build fails

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.3.8 (build 5)
Installation UUID: 6f8589da-df46-44e0-956d-f527ce55361b

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.2.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.402/Sdks
SDK-Versionen:
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.300
MSBuild-SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK-Versionen:
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.419

.NET Runtime (Arm64)
Laufzeit: /usr/local/share/dotnet/dotnet
Laufzeitversionen:
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.5

.NET Runtime (x64)
Laufzeit: /usr/local/share/dotnet/x64/dotnet
Laufzeitversionen:
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.25

Xamarin.Profiler
Version: 1.8.0.19
Speicherort: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin.Android
Nicht installiert

Microsoft Build of OpenJDK
Java SDK: Nicht gefunden

Eclipse Temurin JDK
Java SDK: Nicht gefunden

Android SDK Manager
Version: 17.3.0.23
Hash: 965bf40
Branch: remotes/origin/d17-3
Build date: 2022-10-13 22:08:57 UTC

Android Device Manager
Version: 0.0.0.1169
Hash: fafb1d5
Branch: fafb1d5
Build date: 2022-10-13 22:08:57 UTC

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-10-13 22:08:53 UTC

Build Information
Release ID: 1703080005
Git revision: 6a0d8af1de04f96af57762154da284796414cdd2
Build date: 2022-10-13 22:06:30+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 13.0.0
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:15:09 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/9944339/msbuild.binlog.zip)

### Example Project (If Possible)

[repro-aot.zip](https://github.com/xamarin/xamarin-macios/files/9944337/repro-aot.zip)

**Comment by dalexsoto** [comment]
> AOT compilation of arm64 catalyst apps should succeed no matter what nuget package I reference

There are [limitations](https://learn.microsoft.com/en-us/xamarin/ios/internals/limitations) on what the AOT compiler can do, that said you may be able to workaround these using the interpreter. 

```xml
<UseInterpreter>True</UseInterpreter>
```

Can you please give this a try?

**Comment by edoust** [comment]
@dalexsoto Thanks you, it is working now

Is the performance of a native AOT compiled app better than one that uses the interpreter approach? Is there documentation on this?

**Comment by rolfbjarne** [comment]
> Is the performance of a native AOT compiled app better than one that uses the interpreter approach? Is there documentation on this?

The performance difference really depends on what your app does. In the vast majority of cases you won't notice a difference with the interpreter, but if you're a game doing a lot of math and trying to get as many fps as possible, then you might start seeing a significant difference.

In any case, it seem it works for you now, so I'm closing this.
