### ISSUE TITLE
NSArray methods are missing in latest SDK-9.0.0.20

### ISSUE THREAD

**Issue by anoopvaidya** [xamarin/xamarin-macios#16639]
### Steps to Reproduce

1.  I updated the package to get it going on Venture with Xcode14.1 [xamarin.mac-9.0.0.20.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/xcode14.1/fe316785a8fd4315dd8989631821d765159702a1/6928581/package/notarized/xamarin.mac-9.0.0.20.pkg)
2. Now the Clang issue is gone, but I am seeing the NSArray's methods like ToList(), FirstOrDefault(), GetEnumerator, Where, are throwing compilation errors.

### Expected Behavior
All these were working earlier. I should be able to able to convert NSArray objects to List and perform all the action on it.

### Actual Behavior
The project is not compiling and giving errors ".... does not contain a definition of....and no accessible extension method..."

### Environment
macOS 13
Xcode 14.1
Visual Studio For mac 17.3.8
Xamarin mac 9.0.0.20

<details>
<summary>Version information</summary>
Visual Studio Community 2022 for Mac
Version 17.3.8 (build 5)
Installation UUID: cd30de58-7a55-4ff2-a82b-2b8622ba4dff

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.2.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/6.0.402/Sdks
SDK Versions:
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.420

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.26

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Version: 9.0.0.20 (Visual Studio Community)
Hash: fe316785a
Branch: xcode14.1
Build date: 2022-11-07 02:59:20-0500

Xamarin.Android
Version: 13.0.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-3/030cd63
Android SDK: /Users/anoopvaidya/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.23
Hash: 965bf40
Branch: remotes/origin/d17-3
Build date: 2022-10-13 22:08:57 UTC

Android Device Manager
Version: 0.0.0.1169
Hash: fafb1d5
Branch: fafb1d5
Build date: 2022-10-13 22:08:57 UTC

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-10-13 22:08:53 UTC

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Build Information
Release ID: 1703080005
Git revision: 6a0d8af1de04f96af57762154da284796414cdd2
Build date: 2022-10-13 22:06:30+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 13.0.0
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:15:09 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

</details>

### Build Logs

Create a new mac project.
Create an NSArray or NSMutableArray.
Try to invoke all the aforementioned methods and properties on the NSArray.
You will get this error

 "WindowManager.cs(25,111,25,117): error CS1061: 'NSArray<NSWindow>' does not contain a definition for 'ToList' and no accessible extension method 'ToList' accepting a first argument of type 'NSArray<NSWindow>' could be found (are you missing a using directive or an assembly reference?)"

"error CS1061: 'NSArray<NSWindow>' does not contain a definition for 'Where' and no accessible extension method 'Where' accepting a first argument of type 'NSArray<NSWindow>' could be found (are you missing a using directive or an assembly reference?)"

"error CS1061: '?' does not contain a definition for 'GetEnumerator' and no accessible extension method 'GetEnumerator' accepting a first argument of type '?' could be found (are you missing a using directive or an assembly reference?)"

"'NSArray<NSWindow>' does not contain a definition for 'FirstOrDefault' and no accessible extension method 'FirstOrDefault' accepting a first argument of type 'NSArray<NSWindow>' could be found (are you missing a using directive or an assembly reference?)"

**Comment by rolfbjarne** [comment]
This works for me once I add a `using System.Linq;` in the file. Can you please attach a complete test project we can use to reproduce this?

**Comment by anoopvaidya** [comment]
[Ventura.zip](https://github.com/xamarin/xamarin-macios/files/9958676/Ventura.zip)
Here's the same project with a sample NSArray conversion using ToList( ).
Please make sure, you are in the same configuration.

I am using M1 Pro running Ventura, Xcode14.1, VS & Xamarin SDK details already in the first comment.

**Comment by rolfbjarne** [comment]
We made `NSArray` implement the `IEnumerable<NSObject>` interface, and this is an unfortunate side-effect of that.

There's a more in-depth explanation here: https://github.com/xamarin/xamarin-macios/wiki/.NET-7-release-notes#iterating-over-a-generic-nsarray-may-require-a-cast

You can fix it in your source code by doing something like this:

```diff
diff --git a/Ventura/AppDelegate.cs b/Ventura/AppDelegate.cs
index c7197dc..9e1e291 100644
--- a/Ventura/AppDelegate.cs
+++ b/Ventura/AppDelegate.cs
@@ -13,7 +13,7 @@ namespace Ventura
         {
         }

-        protected virtual List<NSWindow> DangerousWindows => NSApplication.SharedApplication.DangerousWindows.ToList();
+        protected virtual List<NSWindow> DangerousWindows => NSApplication.SharedApplication.DangerousWindows.ToList<NSWindow>();

         public override void DidFinishLaunching(NSNotification notification)
         {
```

This code didn't work in the previous version of Xamarin.Mac either (8.12.0.2), so I'm not sure what it's supposed to do:

```cs
var arr = new NSMutableArray();
arr.Add((NSString)"1");
arr.Add((NSString)"2");
List<String> lsts = arr.ToList();
```

But this compiles:

```cs
var arr = new NSMutableArray();
arr.Add((NSString)"1");
arr.Add((NSString)"2");
var lsts = arr.ToList();
```

**Comment by anoopvaidya** [comment]
I directly updated from some lower version to this, that's the reason I did not catch it earlier.
Thanks for the guidance and I will keep an eye on every release-notes...
