### ISSUE TITLE
NSFileManager.DefaultManager.GetContainerUrl Not working in iOS 16

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#16632]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NSFileManagerDefaultManagerGetContaine/10174437)._

---
Curently we use 

NSFileManager.DefaultManager.GetContainerUrl(MessageConstants.AppGroupIdentifier);

to get the url of group's shared directory in the file system. It’s not working in iOS16 simulator.

This function is not deprecated, so it’s the bug of xamarin.ios?

---
#### Feedback Bot on 10/17/2022, 00:30 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by causerm** [comment]
GetContainerUrl() works for me when using VS for Mac 2019 even when I am running an iOS16 simulator. This problem has been around since the launch of VS for Mac 2022.
