### ISSUE TITLE
Cecil tests to verify that we don't throw exceptions in property getters

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#16669]
Ref: https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/property?redirectedfrom=MSDN

In particular:

> ❌ AVOID throwing exceptions from property getters.

The idea is to add a cecil tests that verifies that we don't throw exceptions (this can probably just check for the `throw` IL code in the IL for the method) in property getters.

There will probably be a few cases where exceptions are acceptable/expected/we can't change (yet), so a skip mechanism would be needed.

**Comment by marek-safar** [comment]
I guess the getters can still can another method(s) which makes it more compilicated
