### ISSUE TITLE
Double availability warning for properties in .NET 7

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#16683]
.NET 7 SDK on our CI machine:
```
Error: /Users/teamcity/actions-runner/_work/emclient/emclient/MailClient.Common.UI/Themes/ColorThemes/SystemColorTheme.Mac.cs(155,22): error CA1422: This call site is reachable on: 'macOS/OSX' 10.14 and later. 'NSColor.WindowFrame.get' is obsoleted on: 'macOS/OSX' 11.0 and later (Use 'NSVisualEffectMaterial.Title' instead.). [/Users/teamcity/actions-runner/_work/emclient/emclient/MailClient.Common.UI/MailClient.Common.UI.csproj::TargetFramework=net7.0-macos]
Error: /Users/teamcity/actions-runner/_work/emclient/emclient/MailClient.Common.UI/Themes/ColorThemes/SystemColorTheme.Mac.cs(155,22): error CA1422: This call site is reachable on: 'macOS/OSX' 10.14 and later. 'NSColor.WindowFrame' is obsoleted on: 'macOS/OSX' 11.0 and later (Use 'NSVisualEffectMaterial.Title' instead.). [/Users/teamcity/actions-runner/_work/emclient/emclient/MailClient.Common.UI/MailClient.Common.UI.csproj::TargetFramework=net7.0-macos]
```

Older SDK on my local machine (also happens with .NET 6 SDK):
```
/Users/filipnavara/Projects/emclient-temp/MailClient.Common.UI/Themes/ColorThemes/SystemColorTheme.Mac.cs(155,22): warning CA1416: This call site is reachable on: 'macOS/OSX' 10.14 and later. 'NSColor.WindowFrame.get' is unsupported on: 'macOS/OSX' 11.0.0 and later. [/Users/filipnavara/Projects/emclient-temp/MailClient.Common.UI/MailClient.Common.UI.csproj::TargetFramework=net7.0-macos]
```

**Comment by filipnavara** [comment]
I suppose this may be analyzer issue, so pinging @buyaa-n

**Comment by buyaa-n** [comment]
I could not say for sure because I don't know what attributes applied for `NSColor.WindowFrame`.

From the messages it looks like they started using the new `[ObsoletedOSPlatform[("macOS11.0.0", "Use 'NSVisualEffectMaterial.Title' instead.")]` attribute we added in 7.0 instead of `[UnsupportedOSPlatform[("macOS11.0.0")]`. It seems they not only changed the attribute, but they might have added the same attribute to the getter which is probably caused the double warning:

```diff
public partial class NSColor
{
-   [UnsupportedOSPlatform[("macOS11.0.0")]
+   [ObsoletedOSPlatform[("macOS11.0.0", "Use 'NSVisualEffectMaterial.Title' instead.")]
    public static NSColor WindowFrame
    {
+       [ObsoletedOSPlatform[("macOS11.0.0", "Use 'NSVisualEffectMaterial.Title' instead.")]
        get
        {
            // ...
        }
    }
}
```
If that is not the case, then it could be analyzer issue (needs a repro as I could not repro it)
CC @rolfbjarne

**Comment by filipnavara** [comment]
Ah, right. That makes sense. So I guess the double warning is something that should be fixed. The changed warning code is probably something that should be mentioned in release notes (breaks WarningsNotAsError exclusions).

**Comment by rolfbjarne** [comment]
> The changed warning code is probably something that should be mentioned in release notes (breaks WarningsNotAsError exclusions).

Done: https://github.com/xamarin/xamarin-macios/wiki/.NET-7-release-notes#changed-availability-attributes

**Comment by rolfbjarne** [comment]
I'm keeping this open for the double warning.

**Comment by rolfbjarne** [comment]
Seems like this is fixed, I only get one warning now:

> /Users/rolf/test/dotnet/macos/AppDelegate.cs(8,22): warning CA1422: This call site is reachable on: 'macOS/OSX' 10.14 and later. 'NSColor.WindowFrame' is obsoleted on: 'macOS/OSX' 11.0 and later (Use 'NSVisualEffectMaterial.Title' instead.).

for this code:

```cs
Console.WriteLine (NSColor.WindowFrame);
```
