### ISSUE TITLE
Investigate removal of string resources for the BCL

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#16684]
The old Mono BCL did not really use string resources - that’s not true anymore for the .NET BCL.

Whenever an assembly is present we get all the resource strings, even if they are not used by the application.

note: needs to be verified against a newer version of ILLink - and this is an optimization that should be made inside ILLink (for everyone)

**Comment by marek-safar** [comment]
This should be enabled by default already with UseSystemResourceKeys property set to false

**Comment by rolfbjarne** [comment]
> This should be enabled by default already with UseSystemResourceKeys property set to false

Looks like this is
