### ISSUE TITLE
Investigate if the linker can remove more metadata

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#16682]
## Backing fields

```cs
public sealed class RuntimeException : Exception
{
    private int <Code>k__BackingField;
    private bool <Error>k__BackingField;
```

these names provide little value for release builds, so they can usually be simplifed/removed.

## String deduplication

* Running `strings` (mac and gnu versions for unicode) is a good way to find duplicates
* Some could be made UTF8 to save space, some source generators do that
    * selectors determined to not be worth it (https://github.com/xamarin/xamarin-macios/issues/10462)

## Parameter string removal

There’s a lot of them, unique, that don’t help much in release builds. They could be replaced by the parameter location (which would be shared across multiple methods).

Example:

Pattern:

    ldstr "parameterName"
    newobj instance void [mscorlib]System.ArgumentException::.ctor(string)
    throw

if `"parameterName"` is one of the method's parameter name then we can re-write this as

    ldstr "#0"
    newobj instance void [mscorlib]System.ArgumentException::.ctor(string)
    throw

where `0` would be the parameter position inside the method. This optimization can be applied on all assemblies being linked (in general all the SDK).

* ArgumentException
* ArgumentNullException
* ArgumentOutOfRangeException
* ...

This won't change the native executable size but it will further reduce the string tables* in the assemblies.

--- 

Note: many of these should probably be implemented in the linker instead.

Ref: https://github.com/xamarin/xamarin-macios/blob/2d9f9c3d1f3e4c4a9ec7f068428a5d5084f220b2/tools/linker/MonoTouch.Tuner/MetadataReducerSubStep.cs

**Comment by marek-safar** [comment]
We prototyped Parameter string removal and it didn't really save anything noticeable (I think it was like 4k)

**Comment by rolfbjarne** [comment]
Closing; this is something for the linker team to.
