### ISSUE TITLE
net7.0-maccatalyst15.4 extremely slow build (target: _RunILLink)

### ISSUE THREAD

**Issue by edoust** [xamarin/xamarin-macios#16741]
Starting with .NET 7, building large apps (tested for `net7.0-maccatalyst15.4`) is taking an enormous amount of time (> 30 minutes on a current M1 MacBook Pro), that time is spent while executing the target `_RunILLink` (with .NET 6 it took less than 30 seconds to build)

I set `TrimMode` to `partial` and `TrimmerRootAssembly` to my main assembly's name

Is this related to trimming, and if so is there a way to fully disable trimming for .NET 7 Xamarin apps?

It is happening for both x64 and arm64 builds. Will there be a fix for this, or will it stay this way?

**Comment by rolfbjarne** [comment]
This sounds very much like a bug, but we'll need to be able to reproduce it ourselves in order to figure out what's going on.

Would it be possible to get access to your project, or for you to create a test project we can use to reproduce this?
