### ISSUE TITLE
Try to show a helpful error message with an invalid OS version in the TFM

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#16802]
Ref: https://github.com/dotnet/maui/issues/11333

Customer used `net7.0-15.4` and the app crashes at launch.

We should look into whether it's possible to detect this scenario, and show a build error instead (and maybe even list the valid versions).

**Comment by jasonleach** [comment]
This same error showed up using net7.0-15.2 as well for me. or net7.0-14.5 or about anything else I tried.

**Comment by rolfbjarne** [comment]
@jasonleach just use `net7.0` (without `-<version>`), that should work fine.

**Comment by tranb3r** [comment]
Why is it crashing when we specify a TFM version for net7.0-ios ?
How do we know which version is used if we do not specify it ?
https://learn.microsoft.com/en-us/dotnet/standard/frameworks#os-version-in-tfms

**Comment by rolfbjarne** [comment]
> Why is it crashing when we specify a TFM version for net7.0-ios ?

We don't support all possible OS versions, just a very limited set. If you pick one we don't support, things won't work.

> How do we know which version is used if we do not specify it?

Typically it's the latest OS version that's been released by Apple (with some delay as we implement and release support for that version). It's also possible to find the exact version in the build log, although it's usually not necessary. Do you have a specific reason for wanting to know?

**Comment by rolfbjarne** [comment]
This will be fixed with https://github.com/xamarin/xamarin-macios/issues/16802.

**Comment by rolfbjarne** [comment]
Fixed with https://github.com/xamarin/xamarin-macios/pull/18931.
