### ISSUE TITLE
Enabling "incremental builds" causes build errors

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-macios#16808]
### Steps to Reproduce

1.  Create a xamarin forms project, on the ios project enable incremental build.
2.  Add Emgu.CV to the common project and Emgu.CV.runtime.xamarin.ios to the ios project (this last lib requires a licence)
3. Add CvInvokeIOS.Init() to FinishLaunching
4. Build and deploy on a test ios device

### Expected Behavior
1st build: success and deploy

### Actual Behavior
1st build: fails to compile with tons of missing symbols. It looks like those symbols are originally in a C lib coming from the Emgu.CV.runtime.xamarin.ios nuget

If "incremental build" is disabled, the app builds and runs correctly.

### Environment

<details>
<summary>Version information</summary>

```
VS mac 17.4 (2406) (xamarin ios sdk 16.0.0.72)
Same behavior on VS windows 2022 v17.4.1 (xamarin ios sdk 16.0.0.92)
```
</details>

**Comment by rolfbjarne** [comment]
Could you please get a binary build log (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) for both the successful and the failing build? Thanks!

**Comment by softlion** [comment]
> Could you please get a binary build log (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) for both the successful and the failing build? Thanks!

Here they are

[binlogs.zip](https://github.com/xamarin/xamarin-macios/files/10040412/binlogs.zip)

**Comment by rolfbjarne** [comment]
Unfortunately it's possible to run into scenarios in Xamarin.iOS with incremental builds that don't work, and are very hard to fix properly with how we implemented incremental builds.

The good news is that this is no longer a problem in .NET. Until you can migrate to .NET, just disable incremental builds.
