### ISSUE TITLE
Provide an alternative F# project for the default iOS template

### ISSUE THREAD

**Issue by TimLariviere** [xamarin/xamarin-macios#16822]
Since I could not find any official F# templates for mobile development, I created my own package with those [F# templates](https://github.com/fsharp-mobile/FSharp.Mobile.Templates).
@jonathanpeppers suggested I contribute back some of those to be directly integrated into the workloads.
https://twitter.com/JonathanPeppers/status/1592957572746973186

Would you accept a new template for F# for the basic `ios` template?
I will make a pull request. Please correct me if I'm missing anything.

**Comment by jonathanpeppers** [comment]
The only thing tricky I was thinking of, is we need them to live alongside the C# templates.

I think you can pivot based on language? So you might inspect the contents of:

    "C:\Program Files\dotnet\templates\7.0.0\microsoft.dotnet.common.projecttemplates.7.0.7.0.100.nupkg"

Not sure where the source for this is.
