### ISSUE TITLE
marshal-ilgen component must be included 

### ISSUE THREAD

**Issue by naricc** [xamarin/xamarin-macios#16836]
After reverting, marshal-ilgen has been moved to again component: https://github.com/dotnet/runtime/pull/75542. This is a step in eventually allowing the component to be dropped when not needed (reducing the runtime size by around 100kb). For now, it must be available to the runtime. So it needs to be added here before this change is consumed by xamarin-macios.

@dalexsoto @rolfbjarne

**Comment by rolfbjarne** [comment]
This is the issue for the first attempt: https://github.com/xamarin/xamarin-macios/issues/15668

**Comment by rolfbjarne** [comment]
This is probably the fix: https://github.com/rolfbjarne/xamarin-macios/commit/83370b05327f89d01826cdc379ca332e81d2f7db, but waiting for the dotnet/runtime bump containing the marshal-ilgen component for now.

**Comment by rolfbjarne** [comment]
This is complete now.
