### ISSUE TITLE
[NetSDKE2E][Loc]With VS 17.5 preview 2 + .NET 7.0.200-preview.22558.7 installed on Loc OS, the template names for IOS and Mac are unlocalized after running "dotnet new --list" in CLI .

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#16830]
_From @v-ainigao on Thu, 10 Nov 2022 09:46:31 GMT_

Steps:
1.install it on locale OS Version 17.5.0 preview 2.0[33109.214.main] from https://ddweb/Dashboard/vsbuild + .net 7.0.200-preview.22558.7(runtime-7.0.0-rtm.22505.15) from https://github.com/dotnet/installer

2.Below workloads are installed in vs:

- .NET desktop development
- ASP.NET and web development
- Universal Windows Platform development
- Visual Studio extension development
- .NET Multi-platform App Ul development--check Xamarin
- Mobile development with C++

3.Run “dotnet new --list” in CLI

4.Check if output contents are localized well.

Expected result:
Template names are localized.

Actual Result:
Some template names are not localized.

e.g
EN:
<img width="556" alt="MicrosoftTeams-image (8)" src="https://user-images.githubusercontent.com/106054229/201056578-f5b89905-41ba-45ef-8f3f-1ea29bc4e06f.png">

SC:
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/106054229/201054857-a7289697-4f45-453a-90ee-c34f937902dd.png)
DE:
![Untitled](https://user-images.githubusercontent.com/106054229/201055364-e1f91178-dca6-403e-bf9f-ea2506e2c2be.png)

note：
The same is reproduced in vs.
![1](https://user-images.githubusercontent.com/106054229/202595443-ed6e74eb-c260-46fe-a757-8135bbe5a490.png)

dotnet info:
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/106054229/201057219-a759dc64-6633-4eed-a62d-c843628517dc.png)

_Copied from original issue dotnet/sdk#28997_

**Comment by rolfbjarne** [comment]
_From @dotnet-issue-labeler[bot] on Thu, 10 Nov 2022 09:46:37 GMT_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by rolfbjarne** [comment]
_From @nagilson on Tue, 15 Nov 2022 23:13:58 GMT_

@dotnet/templating-engine-maintainers Where should we go to, to get these translated?

**Comment by rolfbjarne** [comment]
_From @vlada-shubina on Wed, 16 Nov 2022 09:43:12 GMT_

This looks like Xamarin templates.
https://github.com/xamarin/xamarin-android/tree/main/src/Microsoft.Android.Templates
https://github.com/xamarin/xamarin-macios/tree/main/dotnet/package

both were actually localized, it might be some packaging issues:
https://github.com/xamarin/xamarin-macios/pull/14213
https://github.com/xamarin/xamarin-android/pull/7248

**Comment by rolfbjarne** [comment]
_From @nagilson on Wed, 16 Nov 2022 20:37:43 GMT_

@marcpopMSFT  who do we go to for packaging issues, Matt?

**Comment by rolfbjarne** [comment]
_From @marcpopMSFT on Thu, 17 Nov 2022 19:02:53 GMT_

Wouldn't we go to the Xamarin folks to see how these flow in?  @jonathanpeppers do you know who to talk to about these?

**Comment by rolfbjarne** [comment]
_From @jonathanpeppers on Thu, 17 Nov 2022 20:48:03 GMT_

Ok, I don't understand how the same templates in VS are translated, but not at the command-line?

Look at "iOS Binding Library", for example. @v-ainigao are some of the templates in your screenshot Xamarin.iOS projects, or are all of them .NET 6+ iOS templates?

**Comment by rolfbjarne** [comment]
_From @v-ainigao on Fri, 18 Nov 2022 01:29:00 GMT_

All IOS and MacOS template in CLI are not localized, and in VS, these templates are also untranslated. @jonathanpeppers 
![1](https://user-images.githubusercontent.com/106054229/202595807-563fb2dc-feb5-4c59-97ca-f78b2bc3f8c5.png)
![2](https://user-images.githubusercontent.com/106054229/202595875-5acc32d3-d4d6-47c6-9134-46cac9911095.png)

**Comment by rolfbjarne** [comment]
_From @jonathanpeppers on Fri, 18 Nov 2022 15:06:54 GMT_

Ok, so it is the titles?

![image](https://user-images.githubusercontent.com/840039/202735654-67678ec6-7afb-4ce7-aa93-8f8dd46928bc.png)

And then some of the descriptions aren't translated:

![image](https://user-images.githubusercontent.com/840039/202735829-9689a215-1279-49d0-bbe6-78db66433b27.png)

It's not a packaging issue, if some things are localized -- I think everything would be English if that were the case?

/cc @rolfbjarne

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Fri, 18 Nov 2022 15:24:50 GMT_

Looks like the MAUI and the Android ones are OK, so moving to xamarin-macios.

**Comment by rolfbjarne** [comment]
@tj-devel709 is this something you could look at?

**Comment by tj-devel709** [comment]
Jotting down some notes here:

It appears that the template strings are translated in main: https://github.com/xamarin/xamarin-macios/tree/main/dotnet/Templates/Microsoft.iOS.Templates/ios-controller/.template.config/localize

and looking in the release/7.0.1xx-xcode14.2 branch it is not translated: https://github.com/xamarin/xamarin-macios/tree/release/7.0.1xx-xcode14.2/dotnet/Templates/Microsoft.iOS.Templates/ios-storyboard/.template.config/localize

Perhaps these files just need to be backported

**Comment by rolfbjarne** [comment]
Looks like this is fixed in .NET 8:

```
$ LANG=es_ES dotnet new list | grep ios
Aplicación con pestañas de iOS                             ios-tabbed                  [C#]        iOS/Mobile
Aplicación de iOS                                          ios                         [C#],F#,VB  iOS/Mobile
Biblioteca de clases de iOS                                ioslib                      [C#],VB     iOS/Mobile
Biblioteca de enlaces de iOS                               iosbinding                  [C#]        iOS/Mobile
Controlador de iOS                                         ios-controller              [C#]        iOS/Mobile
Controlador de vista de iOS                                ios-viewcontroller          [C#]        iOS/Mobile
Guion gráfico de iOS                                       ios-storyboard              [C#]        iOS/Mobile
Vista de iOS                                               ios-view                    [C#]        iOS/Mobile

$ LANG=es_ES dotnet new list | grep macca
Aplicación Mac Catalyst                                    maccatalyst                 [C#],VB     macOS/Mac Catalyst
Biblioteca de clases de Mac Catalyst                       maccatalystlib              [C#],VB     macOS/Mac Catalyst
Biblioteca de enlace de Mac Catalyst                       maccatalystbinding          [C#]        macOS/Mac Catalyst
Controlador de vista de Mac Catalyst                       maccatalyst-viewcontroller  [C#]        macOS/Mac Catalyst
Controlador Mac Controller                                 maccatalyst-controller      [C#]        macOS/Mac Catalyst
Un guion gráfico de Mac Catalyst                           maccatalyst-storyboard      [C#]        macOS/Mac Catalyst
Vista de Mac Catalyst                                      maccatalyst-view            [C#]        macOS/Mac Catalyst

$ LANG=es_ES dotnet new list | grep macos
Aplicación macOS                                           macos                       [C#],VB     macOS
Biblioteca de clases de macOS                              macoslib                    [C#],VB     macOS
Biblioteca de enlaces de macOS                             macosbinding                [C#]        macOS
Controlador de macOS                                       macos-controller            [C#]        macOS
Controlador de vista de macOS                              macos-viewcontroller        [C#]        macOS
Guion gráfico de macOS                                     macos-storyboard            [C#]        macOS
Vista de macOS                                             macos-view                  [C#]        macOS

$ LANG=es_ES dotnet new list | grep tvos
Aplicación tvOS                                            tvos                        [C#],VB     tvOS/Mobile
Biblioteca de clases de tvOS                               tvoslib                     [C#],VB     tvOS/Mobile
Biblioteca de enlaces de tvOS                              tvosbinding                 [C#]        tvOS/Mobile
Controlador de tvOS                                        tvos-controller             [C#]        tvOS/Mobile
Controlador de vista de tvOS                               tvos-viewcontroller         [C#]        tvOS/Mobile
Guion gráfico de tvOS                                      tvos-storyboard             [C#]        tvOS/Mobile
Vista de tvOS                                              tvos-view                   [C#]        tvOS/Mobile
```
