### ISSUE TITLE
Make it an error to try to use the server GC in macOS

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#16853]
Customer's should have to run into random issues due to this:

https://github.com/xamarin/xamarin-macios/blob/main/runtime/coreclr-bridge.m#L203-L210

we should just make this a build-time error.

It's probably enough to check for the `ServerGarbageCollection` property:

https://github.com/dotnet/runtime/pull/78280#issuecomment-1322340864

**Comment by AustinWise** [comment]
There is also the [`GC.GetConfigurationVariables()`](https://learn.microsoft.com/en-us/dotnet/api/system.gc.getconfigurationvariables?view=net-7.0) API. It returns a dictionary with a key `ServerGC` that can be checked. This API was added in .NET 7.

**Comment by jkotas** [comment]
`GCSettings.IsServerGC` is more straightforward to test for server GC at runtime (this API existed since forever).

**Comment by slluis** [comment]
@rolfbjarne is there a possibility of adding Server GC support and short/mid term?

**Comment by rolfbjarne** [comment]
@slluis it could probably be implemented, is it something that would be interesting for VSMac? It's not trivial though, because this is a rather complex area of the runtime.
