### ISSUE TITLE
Using WinExe as OutputType in a macos project causes a build error

### ISSUE THREAD

**Issue by ylatuya** [xamarin/xamarin-macios#16865]
### Steps to Reproduce

1. dotnet new macos
2. Change `OutputType` from `Win`  to `WinExe`
3. dotnet build

```
➜  test dotnet build
MSBuild version 17.3.2+561848881 for .NET
  Determining projects to restore...
  Restored /Users/andoni/Downloads/test/test.csproj (in 331 ms).
/usr/local/share/dotnet/sdk/6.0.403/Microsoft.Common.CurrentVersion.targets(885,7): error MSB4057: The target "_CollectBundleResources" does not exist in the project. [/Users/andoni/Downloads/test/test.csproj]

Build FAILED.

/usr/local/share/dotnet/sdk/6.0.403/Microsoft.Common.CurrentVersion.targets(885,7): error MSB4057: The target "_CollectBundleResources" does not exist in the project. [/Users/andoni/Downloads/test/test.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.06
```

### Expected Behavior

There is an error explaining that `WinExe` is not a supported `OutputType`

### Actual Behavior

The build throws an error that is impossible to identify with the root issue

**Comment by rolfbjarne** [comment]
Thanks for the report! We'll look into improving the error message here, but since it's not an urgent issue, it might take a while.

**Comment by ylatuya** [comment]
I am trying to provide a fix myself, but I am still navigating through all the targets to find the correct place to do it :)
