### ISSUE TITLE
iOS build: the "-gcc_flags -dead_strip" Mtouch argument doesn't work

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#16861]
_From @vasile135 on Fri, 18 Nov 2022 15:04:29 GMT_

### Description

Have a working Xamarin Forms application that relies on some iOS native static libraries.
Trying to migrate the solution to .NET MAUI.
When adding the same static libraries with the same configurations and the same gcc flag, the MAUI application build fails with:
`Error: clang++ exited with code 1:
duplicate symbol '_crypto_onetimeauth_verify' in:
    /Users/hetzner/Desktop/TestIndyLibraries/iOSBindingLibrary/bin/Debug/net7.0-ios/iOSBindingLibrary.resources/libsodium.a(libsodium_la-crypto_onetimeauth.o)
    /Users/hetzner/Desktop/TestIndyLibraries/iOSBindingLibrary/bin/Debug/net7.0-ios/iOSBindingLibrary.resources/libzmq.a(src_libzmq_la-tweetnacl.o)`
In Xamarin, I believe that the error is addressed by the following Mtouch extra argument:
<MtouchExtraArgs>-gcc_flags -dead_strip -v</MtouchExtraArgs>

### Steps to Reproduce

1. In order to add native references, added an iOS Binding project to the MAUI solution. 

2. Added native references (one of it is C++):
![image](https://user-images.githubusercontent.com/58006892/202736561-386fe476-fcff-4c91-83ec-a9ea845a0606.png)

3. Added an additional Mtouch argument to the application project:
<MtouchExtraArgs>-gcc_flags -dead_strip -v</MtouchExtraArgs>

4. Installed the nuget package that uses these native libraries (Hyperledger.Aries).

5. When trying to build, the following error occurs:
`Error: clang++ exited with code 1:
duplicate symbol '_crypto_onetimeauth_verify' in:`

From here I conclude that the gcc flag was not applied.

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 16

### Did you find any workaround?

No

_Copied from original issue dotnet/maui#11477_

**Comment by rolfbjarne** [comment]
_From @jsuarezruiz on Mon, 21 Nov 2022 15:29:54 GMT_

cc @rolfbjarne

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Mon, 21 Nov 2022 20:38:49 GMT_

@vasile135 could you get a [binary build log](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) and attach it here?

**Comment by rolfbjarne** [comment]
@vasile135: can you try adding an equals sign after `-gcc_flags` like this instead:

```xml
<MtouchExtraArgs>-gcc_flags=-dead_strip -v</MtouchExtraArgs>
```

**Comment by rolfbjarne** [comment]
> > @vasile135: can you try adding an equals sign after `-gcc_flags` like this instead:
> > ```
> > <MtouchExtraArgs>-gcc_flags=-dead_strip -v</MtouchExtraArgs>
> > ```
> 
> Tried, doesn't work either.

Can you get a new binlog then?

**Comment by vasile135** [comment]
However, with the "<MtouchExtraArgs>-gcc_flags=-dead_strip -v</MtouchExtraArgs>" I already see the "-dead_strip" in the bilog file:
![image](https://user-images.githubusercontent.com/58006892/203292072-bf0c1226-1aad-4872-8928-9cde438f9653.png)
![image](https://user-images.githubusercontent.com/58006892/203292089-1cbd6d92-af58-456b-aecc-af1ffe324f47.png)

**Comment by vasile135** [comment]
The new binlog:
[msbuild (1).zip](https://github.com/xamarin/xamarin-macios/files/10066518/msbuild.1.zip)

**Comment by vasile135** [comment]
Just to ensure that the "-dead_strip" flag affects the linking in my case, tried to remove it from the working Xamarin Forms application, and then the build fails with:
`/Users/hetzner/Projects/TestIndyXamarin/TestXAmarinIndy.iOS/MTOUCH: Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: Libraries/libcrypto.a Libraries/libindy.a Libraries/libsodium.a Libraries/libssl.a Libraries/libzmq.a (MT5201) (TestIndyXamarin.iOS)`

**Comment by rolfbjarne** [comment]
@vasile135 did you upload the wrong zip file? Because that binlog is from a build that still has:

`<MtouchExtraArgs>-gcc_flags -dead_strip -v</MtouchExtraArgs>`

**Comment by vasile135** [comment]
> @vasile135 did you upload the wrong zip file? Because that binlog is from a build that still has:
> 
> `<MtouchExtraArgs>-gcc_flags -dead_strip -v</MtouchExtraArgs>`

Sorry, if messed up. Double checked. Here is the one with
`<MtouchExtraArgs>-gcc_flags=-dead_strip -v</MtouchExtraArgs>`
[msbuild-new.zip](https://github.com/xamarin/xamarin-macios/files/10070739/msbuild-new.zip)

**Comment by vasile135** [comment]
> 
[msbuild_Xamarin.zip](https://github.com/xamarin/xamarin-macios/files/10074304/msbuild_Xamarin.zip)

Sure, here it is:

**Comment by rolfbjarne** [comment]
Ok, I think I figured out what's happening, and this is a problem on our side. I've proposed a fix, but it may take a while until it's released. In the meantime I believe adding this to your main (executable) project file will work as a workaround:

```xml
<Target Name="FixBindingLibraries" BeforeTargets="_LinkNativeExecutable" AfterTargets="_LoadLinkerOutput">
	<ItemGroup>
		<_BindingLibraryLinkWith Update="@(_BindingLibraryLinkWith)" ForceLoad="false" />
	</ItemGroup>
</Target>
```

if it doesn't, please attach an updated binlog.

**Comment by vasile135** [comment]
> Ok, I think I figured out what's happening, and this is a problem on our side. I've proposed a fix, but it may take a while until it's released. In the meantime I believe adding this to your main (executable) project file will work as a workaround:
> 
> ```
> <Target Name="FixBindingLibraries" BeforeTargets="_LinkNativeExecutable" AfterTargets="_LoadLinkerOutput">
> 	<ItemGroup>
> 		<_BindingLibraryLinkWith Update="@(_BindingLibraryLinkWith)" ForceLoad="false" />
> 	</ItemGroup>
> </Target>
> ```
> 
> if it doesn't, please attach an updated binlog.

@rolfbjarne , thank you. Now it successfully builds, but when calling a method from the native library, it throws:
`System.DllNotFoundException: indy
   at Hyperledger.Indy.PoolApi.Pool.CreatePoolLedgerConfigAsync(String configName, String config)`
The indy library is called from a nuget package as following:
![image](https://user-images.githubusercontent.com/58006892/203601239-5e45fd38-1cc0-46ce-ad92-f20a8c12d573.png)
The updated binlog:
[msbuild-3.zip](https://github.com/xamarin/xamarin-macios/files/10077518/msbuild-3.zip)

**Comment by rolfbjarne** [comment]
@vasile135 can you try cleaning your project and rebuild? That build log didn't do much, because:

> Skipping target "_LinkNativeExecutable" because all output files are up-to-date with respect to the input files.

**Comment by vasile135** [comment]
> @vasile135 can you try cleaning your project and rebuild? That build log didn't do much, because:
> 
> > Skipping target "_LinkNativeExecutable" because all output files are up-to-date with respect to the input files.

Understood. 
[msbuild-4.zip](https://github.com/xamarin/xamarin-macios/files/10077723/msbuild-4.zip)

**Comment by rolfbjarne** [comment]
I believe that to be a difference in behavior in .NET: the library `indy` doesn't actually exist in the app bundle, but in legacy Xamarin.iOS (and Xamarin.Forms) that happened to work if the symbol in question was already loaded in the process (which would be the case if the native library was a static library linked into the main executable - i.e. is your case). In .NET we look for the library first, before trying to load the symbol, and we never get to look for the symbol because we fail to find the native library.

There are a couple of ways to fix this:

* If you have access to the managed library with the P/Invokes in question, use `__Internal` (that's two underscores) as the library name instead of `indy`.
* If not, you might be able to set a callback to be called when the runtime tries to resolve the native library:

https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver?view=net-7.0#system-runtime-interopservices-nativelibrary-setdllimportresolver(system-reflection-assembly-system-runtime-interopservices-dllimportresolver)

And then possibly return `new IntPtr (-5)` from the callback (this is the `RTLD_MAIN_ONLY` flag, which is a special flag to the `dlsym` function which the runtime uses to resolve native functions - see [`man dlsym`](http://www.polarhome.com/service/man/?qf=dlsym&tf=2&of=Darwin&sf=) for more information).

**Comment by vasile135** [comment]
> I believe that to be a difference in behavior in .NET: the library `indy` doesn't actually exist in the app bundle, but in legacy Xamarin.iOS (and Xamarin.Forms) that happened to work if the symbol in question was already loaded in the process (which would be the case if the native library was a static library linked into the main executable - i.e. is your case). In .NET we look for the library first, before trying to load the symbol, and we never get to look for the symbol because we fail to find the native library.
> 
> There are a couple of ways to fix this:
> 
> * If you have access to the managed library with the P/Invokes in question, use `__Internal` (that's two underscores) as the library name instead of `indy`.
> * If not, you might be able to set a callback to be called when the runtime tries to resolve the native library:
> 
> https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver?view=net-7.0#system-runtime-interopservices-nativelibrary-setdllimportresolver(system-reflection-assembly-system-runtime-interopservices-dllimportresolver)
> 
> And then possibly return `new IntPtr (-5)` from the callback (this is the `RTLD_MAIN_ONLY` flag, which is a special flag to the `dlsym` function which the runtime uses to resolve native functions - see [`man dlsym`](http://www.polarhome.com/service/man/?qf=dlsym&tf=2&of=Darwin&sf=) for more information).

@rolfbjarne , thank you for the effort. 
Found the "#if __IOS__" condition in the managed library, to set the name at compile time:
![image](https://user-images.githubusercontent.com/58006892/204861977-73a56b1a-3891-412f-8c68-026076f02ccc.png)
The same condition is used to apply the MonoPInvokeCallback attribute:
![image](https://user-images.githubusercontent.com/58006892/204863446-2348fe26-c829-4347-b118-f450e60dbc03.png)
But here is a problem:
- When I decompiled the DLL of the managed library, found that the "#if __IOS__" doesn't work in MAUI. The code that is in the "if" block is not present in the DLL. The "indy" name is still used instead of "__Internal".
Ensured that the Conditional Symbol is present in the startup project properties:
![image](https://user-images.githubusercontent.com/58006892/204864383-c4716d8c-c3a2-461e-bc65-fa8710c036af.png)
Is this another bug?

**Comment by rolfbjarne** [comment]
That's weird. Can you get a binlog?

**Comment by vasile135** [comment]
> That's weird. Can you get a binlog?
Sure
[msbuild-5.zip](https://github.com/xamarin/xamarin-macios/files/10127088/msbuild-5.zip)

**Comment by rolfbjarne** [comment]
> * When I decompiled the DLL of the managed library,

What's the name of the assembly you decompiled?

**Comment by vasile135** [comment]
> > * When I decompiled the DLL of the managed library,
> 
> What's the name of the assembly you decompiled?

Hyperledger.Indy.Sdk.dll
Here is its source code: https://github.com/hyperledger/indy-sdk/tree/main/wrappers/dotnet/indy-sdk-dotnet

**Comment by rolfbjarne** [comment]
> > > * When I decompiled the DLL of the managed library,
> > 
> > 
> > What's the name of the assembly you decompiled?
> 
> Hyperledger.Indy.Sdk.dll Here is its source code: [hyperledger/indy-sdk@`main`/wrappers/dotnet/indy-sdk-dotnet](https://github.com/hyperledger/indy-sdk/tree/main/wrappers/dotnet/indy-sdk-dotnet?rgh-link-date=2022-11-30T21%3A09%3A32Z)

The build the binlog is from doesn't compile `Hyperledger.Indy.Sdk.dll`, it seems that assembly comes from a NuGet:

> /Users/hetzner/.nuget/packages/hyperledger.indy.sdk/1.11.1/lib/netstandard2.0/Hyperledger.Indy.Sdk.dll

**Comment by vasile135** [comment]
> > > > * When I decompiled the DLL of the managed library,
> > > 
> > > 
> > > What's the name of the assembly you decompiled?
> > 
> > 
> > Hyperledger.Indy.Sdk.dll Here is its source code: [hyperledger/indy-sdk@`main`/wrappers/dotnet/indy-sdk-dotnet](https://github.com/hyperledger/indy-sdk/tree/main/wrappers/dotnet/indy-sdk-dotnet?rgh-link-date=2022-11-30T21%3A09%3A32Z)
> 
> The build the binlog is from doesn't compile `Hyperledger.Indy.Sdk.dll`, it seems that assembly comes from a NuGet:
> 
> > /Users/hetzner/.nuget/packages/hyperledger.indy.sdk/1.11.1/lib/netstandard2.0/Hyperledger.Indy.Sdk.dll

Understood. There are 2 assemblies in the .nuget folder. One targeting xamarinios10 and the second netstrandard2.0.
![image](https://user-images.githubusercontent.com/58006892/204913749-c3295841-c3e1-41ba-86c8-da88c832b654.png)
The one for xamarin has the right "__Internal" library name.
Does it mean that this nuget isn't compatible with a MAUI app?

**Comment by vasile135** [comment]
> 

Placed the DLL from xamarinios10 folder to netstandard2.0 one and it worked.
@rolfbjarne , thank you very much!

**Comment by rolfbjarne** [comment]
> Does it mean that this nuget isn't compatible with a MAUI app?

Correct, `xamarinios10` libraries aren't compatible with MAUI/.NET apps, the NuGet will have to be built for `net7.0-ios` as well.
