### ISSUE TITLE
iOS ListView fails to display cell content intermittently

### ISSUE THREAD

**Issue by petermauger** [xamarin/xamarin-macios#16883]
[This is the detailed issue](https://github.com/dotnet/maui/issues/11598) (MAUI repo allows bug submission with sample repository).

I suspect at least part of the problem is inside the native handling around cell reuse. I don't see how anyone can release an app on the App Store with this, fairly consistent, issue occurring.

In summary, every now and then a cell re-use occurs that fails to render the correct (new) content. It can occur while scrolling down a ListView with a large number of uneven rows, or scrolling up and down a short ListView with uneven rows repeatedly.

### Steps to Reproduce

1. Pull repository linked at MAUI project issue (link to issue above, has link to repository)
2. Build and run on iOS Simulator or iPhone
3. Scroll the three tabs' list views up and down until you see blue (listview background color) instead of red (simple cell) or green (scrollable cell)

### Expected Behavior
ViewCell always renders current subviews when displayed on device screen

### Actual Behavior
ViewCell intermittently renders no new content, or (depending on implementation) content from 'old' cell (before re-use)

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Professional 2022 for Mac Preview
Version 17.5 Preview (17.5 build 437)
Installation UUID: 0710b57b-1f3f-4279-80df-9ae89d17f083

Runtime
.NET 7.0.0 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-3.22461.4+8ab250290a4010c11a21521f78dbc87dbb7aac81

NuGet
Version: 6.3.1.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.100/Sdks
SDK Versions:
	7.0.100
	6.0.403
	6.0.402
	6.0.401
	6.0.400
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	3.1.425
	3.1.424
	3.1.423
	3.1.422

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.0
	6.0.11
	6.0.10
	6.0.9
	6.0.8

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	3.1.31
	3.1.30
	3.1.29
	3.1.28

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Professional)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin Designer
Version: 17.5.1.13
Hash: 14bdde937f
Branch: remotes/origin/d17-5
Build date: 2022-11-02 21:36:49 UTC

Xamarin.Android
Version: 13.1.0.1 (Visual Studio Professional)
Commit: xamarin-android/d17-4/13ba222
Android SDK: /Users/Mauger/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0  (API level 26)
		12.0 (API level 31)
		8.1  (API level 27)
		5.0  (API level 21)
		11.0 (API level 30)
		10.0 (API level 29)
		7.1  (API level 25)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: a96bde9
Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
SQLite: xamarin/sqlite/3.39.3@23e1ae7
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.8
Hash: 6f27afd
Branch: remotes/origin/HEAD
Build date: 2022-11-02 21:36:54 UTC

Android Device Manager
Version: 0.0.0.1217
Hash: 6175224
Branch: main
Build date: 2022-11-02 21:36:54 UTC

Build Information
Release ID: 1705000437
Git revision: a5d0fb913c1ff781c80fe725a3e0511c34e26a08
Build date: 2022-11-02 21:34:22+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:19:52 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

```

</details>

### Build Logs

No build errors, warnings or failures that affect this issue. Runtime issue only.

### Example Project (If Possible)
Clone https://github.com/petermauger/MAUIiOSBug

**Comment by rolfbjarne** [comment]
I _highly_ suspect this is a problem in MAUI, because

* There are a lot of existing apps without MAUI that works just fine with regards to cell reuse (especially with legacy Xamarin.iOS projects).
* In your original MAUI issue you say there are problems on Android too.

So I'm going to tentatively close this until either:

* The MAUI team has diagnostics this and determined that it's not a problem with MAUI.
* We get at test project that's just a plain iOS project (without MAUI).
