### ISSUE TITLE
Always get the crash report after deploy App to App Store Connect

### ISSUE THREAD

**Issue by mfchung2010** [xamarin/xamarin-macios#16912]
Hi all, I am a new developer for Xamarin IOS. My app can deploy into physical device and work fine. But when I deploy into App Store, the Apple always send and inform me the App has crashed. Please help and thanks! below is the crash log detail:

Incident Identifier: 4BC77DA5-4EE6-44CD-8E31-2A1D57B9B2BB
CrashReporter Key: b30c9a133d5490d4beedff9ac4558a369ac2b345
Hardware Model: iPhone11,8
Process: ABC_Forms [8988]
Path: /private/var/containers/Bundle/Application/12A7D9F3-28C5-4C01-8F92-B0A12512113B/ABC_Forms.app/ABC_Forms
Identifier: com.abc
Version: 1.14.8 (1)
AppStoreTools: 14B44
Code Type: ARM-64 (Native)
Role: Foreground
Parent Process: launchd [1]
Coalition: com.abc [1836]

Date/Time: 2022-11-30 05:06:12.0049 +1100
Launch Time: 2022-11-30 05:06:07.4085 +1100
OS Version: iPhone OS 16.1.1 (20B101)
Release Type: User
Baseband Version: 5.01.01
Report Version: 104

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread: 0

Application Specific Information:
abort() called

Kernel Triage:
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage
VM - pmap_enter retried due to resource shortage

Thread 0 name: tid_103 Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0 libsystem_kernel.dylib    0x1d74ac200 __pthread_kill + 8
1 libsystem_pthread.dylib    0x1e790e1ac pthread_kill + 268
2 libsystem_c.dylib    0x1a1f3d3e4 abort + 128
3 libsystem_c.dylib    0x1a1ee5c98 abort + 192
4 ABC_Forms    0x103938528 xamarin_find_protocol_wrapper_type + 25445672 (runtime.m:1177)
5 ABC_Forms    0x103851b98 mono_invoke_unhandled_exception_hook + 24501144 (exception.c:1299)
6 ABC_Forms    0x1037f36c8 mono_handle_exception_internal + 24114888 (mini-exceptions.c:2783)
7 ABC_Forms    0x1037f209c mono_handle_exception + 24109212 (mini-exceptions.c:3107)
8 ABC_Forms    0x1037e9318 mono_arm_throw_exception + 24072984 (exceptions-arm64.c:403)
9 ABC_Forms    0x10251e6cc throw_exception + 172
10 ABC_Forms    0x102c3ceb8 0x1020f4000 + 11833016
11 ABC_Forms    0x102c3ce00 System_Net_Sockets_Socket_Receive_byte + 11832832 (Socket.cs:1763)
12 ABC_Forms    0x10213e9f4 ABC_Forms_HKOTime_GetHKOTime + 305652 (/:1)
13 ABC_Forms    0x10213fc68 ABC_Forms_LoginPage_CountDownInitial + 310376 (/:1)
14 ABC_Forms    0x10213faf8 ABC_Forms_LoginPage__ctor + 310008 (/:1)
15 ABC_Forms    0x10212d334 ABC_Forms_App__ctor + 234292 (/:1)
16 ABC_Forms    0x10212d284 ABC_Forms_AppDelegate_FinishedLaunching_UIKit_UIApplication_Foundation_NSDictionary + 234116 (/:1)
17 ABC_Forms    0x1024e0620 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 272
18 ABC_Forms    0x103803ba8 mono_jit_runtime_invoke + 24181672 (mini-runtime.c:3191)
19 ABC_Forms    0x10389a20c mono_runtime_invoke_checked + 24797708 (object.c:3220)
20 ABC_Forms    0x10389d690 mono_runtime_invoke + 24811152 (object.c:3107)
21 ABC_Forms    0x1020fac54 native_to_managed_trampoline_16(objc_object*, objc_selector*, _MonoMethod**, objc_object*, objc_object*, unsigned int) + 27732 (registrar.m:775)
22 ABC_Forms    0x1020fb2e8 -[AppDelegate application:didFinishLaunchingWithOptions:] + 29416 (registrar.m:7974)
23 UIKitCore    0x19cdbf888 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 300
24 UIKitCore    0x19cdbefac -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 2848
25 UIKitCore    0x19cdbdf88 -[UIApplication _runWithMainScene:transitionContext:completion:] + 856
26 UIKitCore    0x19cdbdbd4 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 132
27 UIKitCore    0x19cb03600 _UIScenePerformActionsWithLifecycleActionMask + 108
28 UIKitCore    0x19ce45918 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 216
29 UIKitCore    0x19ccf5fa4 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 220
30 UIKitCore    0x19ccf5dcc -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 620
31 UIKitCore    0x19ccf597c -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 252
32 UIKitCore    0x19ccf5848 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 148
33 UIKitCore    0x19d3d7fa8 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:] + 736
34 UIKitCore    0x19d470f98 _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion + 224
35 UIKitCore    0x19cba1958 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 316
36 UIKitCore    0x19d0147a8 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.214 + 556
37 UIKitCore    0x19cc740b8 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 216
38 UIKitCore    0x19cc73f28 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 244
39 UIKitCore    0x19cc7347c -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 520
40 UIKitCore    0x19cc73208 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 288
41 FrontBoardServices    0x1b04cd500 -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 344
42 FrontBoardServices    0x1b050c51c __92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke.78 + 120
43 FrontBoardServices    0x1b04d1294 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 168
44 FrontBoardServices    0x1b050c154 __92-[FBSWorkspaceScenesClient createSceneWithIdentity:parameters:transitionContext:completion:]_block_invoke + 360
45 libdispatch.dylib    0x1a1e81fdc _dispatch_client_callout + 20
46 libdispatch.dylib    0x1a1e85a5c _dispatch_block_invoke_direct + 264
47 FrontBoardServices    0x1b04db3b0 FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK + 52
48 FrontBoardServices    0x1b04daf4c -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
49 FrontBoardServices    0x1b04dd72c -[FBSSerialQueue _performNextFromRunLoopSource] + 28
50 CoreFoundation    0x19a97df54 CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION + 28
51 CoreFoundation    0x19a98a32c __CFRunLoopDoSource0 + 176
52 CoreFoundation    0x19a90e210 __CFRunLoopDoSources0 + 244
53 CoreFoundation    0x19a923ba8 _CFRunLoopRun + 836
54 CoreFoundation    0x19a928ed4 CFRunLoopRunSpecific + 612
55 GraphicsServices    0x1d3c26368 GSEventRunModal + 164
56 UIKitCore    0x19ce073d0 -[UIApplication run] + 888
57 UIKitCore    0x19ce07034 UIApplicationMain + 340
58 ABC_Forms    0x103287eb8 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 344
59 ABC_Forms    0x1031ffdf0 UIKit_UIApplication_Main_string___string_string + 17874416 (UIApplication.cs:75)
60 ABC_Forms    0x10212d214 ABC_Forms_Application_Main_string + 234004 (/:1)
61 ABC_Forms    0x1024e0620 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 272
62 ABC_Forms    0x103803ba8 mono_jit_runtime_invoke + 24181672 (mini-runtime.c:3191)
63 ABC_Forms    0x10389a20c mono_runtime_invoke_checked + 24797708 (object.c:3220)
64 ABC_Forms    0x10389f2d4 mono_runtime_exec_main_checked + 24818388 (object.c:5288)
65 ABC_Forms    0x1037e8e84 mono_jit_exec + 24071812 (driver.c:1328)
66 ABC_Forms    0x10393fcb4 xamarin_main + 25476276 (monotouch-main.m:0)
67 ABC_Forms    0x10212d05c main + 233564 (main.m:126)
68 dyld    0x1b8f90960 start + 2528

Thread 1:
0 libsystem_pthread.dylib    0x1e7907b90 start_wqthread + 0

Thread 2 name: SGen worker
Thread 2:
0 libsystem_kernel.dylib    0x1d74a641c __psynch_cvwait + 8
1 libsystem_pthread.dylib    0x1e790f06c _pthread_cond_wait + 1232
2 ABC_Forms    0x103915840 thread_func + 25303104 (sgen-thread-pool.c:196)
3 libsystem_pthread.dylib    0x1e79086cc _pthread_start + 148
4 libsystem_pthread.dylib    0x1e7907ba4 thread_start + 8

Thread 3 name: Finalizer
Thread 3:
0 libsystem_kernel.dylib    0x1d74a5ac4 semaphore_wait_trap + 8
1 ABC_Forms    0x103853da4 finalizer_thread + 24509860 (gc.c:965)
2 ABC_Forms    0x1038cbd10 start_wrapper_internal + 25001232 (threads.c:1289)
3 ABC_Forms    0x1038cbb94 start_wrapper + 25000852 (threads.c:1310)
4 libsystem_pthread.dylib    0x1e79086cc _pthread_start + 148
5 libsystem_pthread.dylib    0x1e7907ba4 thread_start + 8

Thread 4 name: Dispatch queue: com.apple.UIKit.KeyboardManagement
Thread 4:
0 libsystem_kernel.dylib    0x1d74a6680 __ulock_wait + 8
1 libdispatch.dylib    0x1a1e829cc _dlock_wait + 56
2 libdispatch.dylib    0x1a1e82780 _dispatch_thread_event_wait_slow + 56
3 libdispatch.dylib    0x1a1e91860 DISPATCH_WAIT_FOR_QUEUE + 368
4 libdispatch.dylib    0x1a1e9140c _dispatch_sync_f_slow + 144
5 UIKitCore    0x19ce076a4 __37-[_UIRemoteKeyboards startConnection]block_invoke_3 + 156
6 CoreFoundation    0x19a91c704 invoking + 148
7 CoreFoundation    0x19a8c8b6c -[NSInvocation invoke] + 428
8 Foundation    0x194d35b08 NSXPCCONNECTION_IS_CALLING_OUT_TO_REPLY_BLOCK + 16
9 Foundation    0x194d06ef0 -[NSXPCConnection _decodeAndInvokeReplyBlockWithEvent:sequence:replyInfo:] + 520
10 Foundation    0x1952e02e4 __88-[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:]_block_invoke_5 + 188
11 libxpc.dylib    0x1e7968f1c _xpc_connection_reply_callout + 124
12 libxpc.dylib    0x1e795bfb4 _xpc_connection_call_reply_async + 88
13 libdispatch.dylib    0x1a1e8205c _dispatch_client_callout3 + 20
14 libdispatch.dylib    0x1a1e9ff58 _dispatch_mach_msg_async_reply_invoke + 344
15 libdispatch.dylib    0x1a1e8956c _dispatch_lane_serial_drain + 376
16 libdispatch.dylib    0x1a1e8a214 _dispatch_lane_invoke + 436
17 libdispatch.dylib    0x1a1e94e10 _dispatch_workloop_worker_thread + 652
18 libsystem_pthread.dylib    0x1e7907df8 _pthread_wqthread + 288
19 libsystem_pthread.dylib    0x1e7907b98 start_wqthread + 8

Thread 5:
0 libsystem_pthread.dylib    0x1e7907b90 start_wqthread + 0

Thread 6:
0 libsystem_pthread.dylib    0x1e7907b90 start_wqthread + 0

Thread 7:
0 libsystem_pthread.dylib    0x1e7907b90 start_wqthread + 0

Thread 8 name: com.apple.uikit.eventfetch-thread
Thread 8:
0 libsystem_kernel.dylib    0x1d74a5b48 mach_msg2_trap + 8
1 libsystem_kernel.dylib    0x1d74b8008 mach_msg2_internal + 80
2 libsystem_kernel.dylib    0x1d74b8248 mach_msg_overwrite + 388
3 libsystem_kernel.dylib    0x1d74a608c mach_msg + 24
4 CoreFoundation    0x19a922af0 __CFRunLoopServiceMachPort + 160
5 CoreFoundation    0x19a923d34 __CFRunLoopRun + 1232
6 CoreFoundation    0x19a928ed4 CFRunLoopRunSpecific + 612
7 Foundation    0x194cd6334 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8 Foundation    0x194cd621c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9 UIKitCore    0x19cf3c33c -[UIEventFetcher threadMain] + 436
10 Foundation    0x194cef808 NSThread__start + 716
11 libsystem_pthread.dylib    0x1e79086cc _pthread_start + 148
12 libsystem_pthread.dylib    0x1e7907ba4 thread_start + 8

Thread 9:
0 libsystem_pthread.dylib    0x1e7907b90 start_wqthread + 0

Thread 10:
0 libsystem_kernel.dylib    0x1d74a641c __psynch_cvwait + 8
1 libsystem_pthread.dylib    0x1e790f06c _pthread_cond_wait + 1232
2 libc++.1.dylib    0x1a8e6bacc std::__1::condition_variable::wait(std::_1::unique_lockstd::__1::mutex&) + 28
3 ArcGIS-arm64    0x10bb165c0 Esri_runtimecore::Common::Condition::wait() + 64
4 ArcGIS-arm64    0x10bb164b8 Esri_runtimecore::Common::Thread::thread_proc(Esri_runtimecore::Common::Thread*) + 60
5 ArcGIS-arm64    0x10bb17650 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void ()(Esri_runtimecore::Common::Thread), Esri_runtimecore::Common::Thread*> >(void*) + 44
6 libsystem_pthread.dylib    0x1e79086cc _pthread_start + 148
7 libsystem_pthread.dylib    0x1e7907ba4 thread_start + 8

Thread 11:
0 libsystem_kernel.dylib    0x1d74a641c __psynch_cvwait + 8
1 libsystem_pthread.dylib    0x1e790f06c _pthread_cond_wait + 1232
2 libc++.1.dylib    0x1a8e6bacc std::__1::condition_variable::wait(std::_1::unique_lockstd::__1::mutex&) + 28
3 ArcGIS-arm64    0x10bb165c0 Esri_runtimecore::Common::Condition::wait() + 64
4 ArcGIS-arm64    0x10bb164b8 Esri_runtimecore::Common::Thread::thread_proc(Esri_runtimecore::Common::Thread*) + 60
5 ArcGIS-arm64    0x10bb17650 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void ()(Esri_runtimecore::Common::Thread), Esri_runtimecore::Common::Thread*> >(void*) + 44
6 libsystem_pthread.dylib    0x1e79086cc _pthread_start + 148
7 libsystem_pthread.dylib    0x1e7907ba4 thread_start + 8

Thread 12:
0 libsystem_kernel.dylib    0x1d74a641c __psynch_cvwait + 8
1 libsystem_pthread.dylib    0x1e790f06c _pthread_cond_wait + 1232
2 libc++.1.dylib    0x1a8e6bacc std::__1::condition_variable::wait(std::_1::unique_lockstd::__1::mutex&) + 28
3 ArcGIS-arm64    0x10bb165c0 Esri_runtimecore::Common::Condition::wait() + 64
4 ArcGIS-arm64    0x10bb164b8 Esri_runtimecore::Common::Thread::thread_proc(Esri_runtimecore::Common::Thread*) + 60
5 ArcGIS-arm64    0x10bb17650 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void ()(Esri_runtimecore::Common::Thread), Esri_runtimecore::Common::Thread*> >(void*) + 44
6 libsystem_pthread.dylib    0x1e79086cc _pthread_start + 148
7 libsystem_pthread.dylib    0x1e7907ba4 thread_start + 8

Thread 13:
0 libsystem_kernel.dylib    0x1d74a641c __psynch_cvwait + 8
1 libsystem_pthread.dylib    0x1e790f06c _pthread_cond_wait + 1232
2 libc++.1.dylib    0x1a8e6bacc std::__1::condition_variable::wait(std::_1::unique_lockstd::__1::mutex&) + 28
3 ArcGIS-arm64    0x10bb165c0 Esri_runtimecore::Common::Condition::wait() + 64
4 ArcGIS-arm64    0x10bb164b8 Esri_runtimecore::Common::Thread::thread_proc(Esri_runtimecore::Common::Thread*) + 60
5 ArcGIS-arm64    0x10bb17650 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void ()(Esri_runtimecore::Common::Thread), Esri_runtimecore::Common::Thread*> >(void*) + 44
6 libsystem_pthread.dylib    0x1e79086cc _pthread_start + 148
7 libsystem_pthread.dylib    0x1e7907ba4 thread_start + 8

Thread 14:
0 libsystem_kernel.dylib    0x1d74a641c __psynch_cvwait + 8
1 libsystem_pthread.dylib    0x1e790f06c _pthread_cond_wait + 1232
2 libc++.1.dylib    0x1a8e6bacc std::__1::condition_variable::wait(std::_1::unique_lockstd::__1::mutex&) + 28
3 ArcGIS-arm64    0x10bb165c0 Esri_runtimecore::Common::Condition::wait() + 64
4 ArcGIS-arm64    0x10bb164b8 Esri_runtimecore::Common::Thread::thread_proc(Esri_runtimecore::Common::Thread*) + 60
5 ArcGIS-arm64    0x10bb17650 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void ()(Esri_runtimecore::Common::Thread), Esri_runtimecore::Common::Thread*> >(void*) + 44
6 libsystem_pthread.dylib    0x1e79086cc _pthread_start + 148
7 libsystem_pthread.dylib    0x1e7907ba4 thread_start + 8

Thread 15:
0 libsystem_kernel.dylib    0x1d74a641c __psynch_cvwait + 8
1 libsystem_pthread.dylib    0x1e790f06c _pthread_cond_wait + 1232
2 libc++.1.dylib    0x1a8e6bacc std::__1::condition_variable::wait(std::_1::unique_lockstd::__1::mutex&) + 28
3 ArcGIS-arm64    0x10bb165c0 Esri_runtimecore::Common::Condition::wait() + 64
4 ArcGIS-arm64    0x10bb164b8 Esri_runtimecore::Common::Thread::thread_proc(Esri_runtimecore::Common::Thread*) + 60
5 ArcGIS-arm64    0x10bb17650 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void ()(Esri_runtimecore::Common::Thread), Esri_runtimecore::Common::Thread*> >(void*) + 44
6 libsystem_pthread.dylib    0x1e79086cc _pthread_start + 148
7 libsystem_pthread.dylib    0x1e7907ba4 thread_start + 8

Thread 16:
0 libsystem_kernel.dylib    0x1d74a641c __psynch_cvwait + 8
1 libsystem_pthread.dylib    0x1e790f06c _pthread_cond_wait + 1232
2 libc++.1.dylib    0x1a8e6bacc std::__1::condition_variable::wait(std::_1::unique_lockstd::__1::mutex&) + 28
3 ArcGIS-arm64    0x10bb165c0 Esri_runtimecore::Common::Condition::wait() + 64
4 ArcGIS-arm64    0x10bb164b8 Esri_runtimecore::Common::Thread::thread_proc(Esri_runtimecore::Common::Thread*) + 60
5 ArcGIS-arm64    0x10bb17650 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void ()(Esri_runtimecore::Common::Thread), Esri_runtimecore::Common::Thread*> >(void*) + 44
6 libsystem_pthread.dylib    0x1e79086cc _pthread_start + 148
7 libsystem_pthread.dylib    0x1e7907ba4 thread_start + 8

Thread 0 crashed with ARM Thread State (64-bit):
x0: 0x0000000000000000 x1: 0x0000000000000000 x2: 0x0000000000000000 x3: 0x0000000000000000
x4: 0x0000000000000000 x5: 0x0000000000989680 x6: 0x0000000000000800 x7: 0xffffffff00005b00
x8: 0x42da9d799b9333a1 x9: 0x42da9d786b62aaa1 x10: 0x00000000000003e8 x11: 0x0000000000000000
x12: 0x000000010500a370 x13: 0x0000000105107fcb x14: 0x0000000000000060 x15: 0x0000000080000000
x16: 0x0000000000000148 x17: 0x00000001f0f19900 x18: 0x0000000000000000 x19: 0x0000000000000006
x20: 0x0000000000000103 x21: 0x00000001f0f199e0 x22: 0x0000000000000000 x23: 0x000000010482ce00
x24: 0x0000000105107fc8 x25: 0x000000016dd07990 x26: 0x0000000000000002 x27: 0x0000000103b54150
x28: 0x0000000000ffffff fp: 0x000000016dd06b50 lr: 0x00000001e790e1ac
sp: 0x000000016dd06b30 pc: 0x00000001d74ac200 cpsr: 0x40000000
far: 0x00000002395e4004 esr: 0x56000080 Address size fault

Binary Images:
0x1d74a5000 - 0x1d74dbffb libsystem_kernel.dylib arm64e /usr/lib/system/libsystem_kernel.dylib
0x1e7907000 - 0x1e7912fff libsystem_pthread.dylib arm64e <1aa3a4b6f9e730568c8b4e4dd81312a4> /usr/lib/system/libsystem_pthread.dylib
0x1a1ec5000 - 0x1a1f44ff7 libsystem_c.dylib arm64e /usr/lib/system/libsystem_c.dylib
0x1020f4000 - 0x103a23fff ABC_Forms arm64 /private/var/containers/Bundle/Application/12A7D9F3-28C5-4C01-8F92-B0A12512113B/ABC_Forms.app/ABC_Forms
0x19ca65000 - 0x19e242fff UIKitCore arm64e <179501b60fc2344ab969b4e3961ebe10> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
0x1b04ca000 - 0x1b056ffff FrontBoardServices arm64e <65e92d01137f3e1698a6a33706699695> /System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices
0x1a1e7e000 - 0x1a1ec4fff libdispatch.dylib arm64e /usr/lib/system/libdispatch.dylib
0x19a8a8000 - 0x19ac8dfff CoreFoundation arm64e <5cdc5d9ae5063740b64ebb30867b4f1b> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x1d3c25000 - 0x1d3c2dfff GraphicsServices arm64e /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x1b8f7b000 - 0x1b8ffe00f dyld arm64e /usr/lib/dyld
0x194c94000 - 0x1955ddfff Foundation arm64e /System/Library/Frameworks/Foundation.framework/Foundation
0x1e794b000 - 0x1e798bfff libxpc.dylib arm64e <7a0ca8d2728537ddae972efaa1de763e> /usr/lib/system/libxpc.dylib
0x1a8e5f000 - 0x1a8ec5ff3 libc++.1.dylib arm64e <64c24b16049731bb8db53b5f6c74ec6b> /usr/lib/libc++.1.dylib
0x109b9c000 - 0x10d347fff ArcGIS-arm64 arm64 <682b85c62b633c5e9ba98ea1516a5a3a> /private/var/containers/Bundle/Application/12A7D9F3-28C5-4C01-8F92-B0A12512113B/ABC_Forms.app/Frameworks/ArcGIS-arm64.framework/ArcGIS-arm64

EOF

**Comment by RANSoftRA** [comment]
I am experiencing the same issue with my flutter app: 

- https://github.com/flutter/flutter/issues/118303.

What kind of libraries do you use? Maybe it has something to do with Firebase, Google Maps, etc. - You can see my project dependencies here: https://stackoverflow.com/questions/75016349/flutter-ios-app-crash-on-launch-only-during-apple-app-store-review-ios-16-2.

**Comment by rolfbjarne** [comment]
This indicates there was an unhandled exception in your app:

> 5 ABC_Forms    0x103851b98 mono_invoke_unhandled_exception_hook + 24501144 (exception.c:1299)

and this gives you an idea where the exception occurred:

> 11 ABC_Forms    0x102c3ce00 System_Net_Sockets_Socket_Receive_byte + 11832832 (Socket.cs:1763)
> 12 ABC_Forms    0x10213e9f4 ABC_Forms_HKOTime_GetHKOTime + 305652 (/:1)
> 13 ABC_Forms    0x10213fc68 ABC_Forms_LoginPage_CountDownInitial + 310376 (/:1)
> 14 ABC_Forms    0x10213faf8 ABC_Forms_LoginPage__ctor + 310008 (/:1)
> 15 ABC_Forms    0x10212d334 ABC_Forms_App__ctor + 234292 (/:1)
> 16 ABC_Forms    0x10212d284 ABC_Forms_AppDelegate_FinishedLaunching_UIKit_UIApplication_Foundation_NSDictionary + 234116 (/:1)

it seems you're doing a network request on the main thread as part of the startup sequence: this is a bad idea for multiple reasons:

* The device might not be connected to a network.
* If connected to a network, it might be very slow, meaning that your app will be slow to load (possibly too slow and will be killed by iOS).

First I would try to debug locally to see what happens if you launch the app with no internet, that would be my guess for the reason for the crash.

Second, I would fix the app to not do any network requests on the main thread, and instead do them on background threads.
