### ISSUE TITLE
Parallel library builds on Windows causes mtbs to disconnect randomly

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#17005]
### Steps to Reproduce

1. In VS 17.4.2 or 17.5 Pre1 Create a solution which contains many C# projects using net7.0-ios
2. Make sure projects build in parallel
3. Observe that SayHello or SayGoodbye may randomly report errors

### Expected Behavior

The build succeeds.

### Actual Behavior

The build fails with connection errors. (bin log is coming)

### Workaround

Prevent mac connections for libraries:

```xml
<Project>
	<Target Name="_DisableRemoteBuildForLibraries" BeforeTargets="_SayHello" Condition="'$(OutputType)'=='Library'">
		<PropertyGroup>
			<IsRemoteBuild>false</IsRemoteBuild>
			<ServerAddress></ServerAddress>
		</PropertyGroup>
	</Target>
</Project>
```

### Environment

17.4.4

This issue is also reported [here](https://developercommunity.visualstudio.com/t/Building-an-net-iOS-project-which-conta/10225786?entry=myfeedback). 

</details>

### Build Logs

```
Target Name=_SayGoodbye Project=XXX.csproj
    SayGoodbye
        Assembly = C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.0.1478\targets\..\tools\msbuild\iOS\Xamarin.iOS.Tasks.dll
        Parameters
            DeviceSpecificOutputPath = bin\XXX\Debug\net7.0-ios\
            SessionId = 6650fae8eaf2e19c01f702d96d87d1b967ed385717a11cdf3ae03c8a48bfc134
            SignatureFile = obj\XXX\Debug\net7.0-ios\build-signature\signature
        [xma][info]: Trying to get a Build Connection...
        [xma][info]: Creating and registering a new Build Connection. Key: Xamarin.Messaging.Build.Client.BuildConnection.18004, Lifetime: AppDomain
        [xma][info]: The Build Connection 'Xamarin.Messaging.Build.Client.BuildConnection.18004' is not active and needs to be connected with the proper host and user information
        Computing signature for bin\XXX\Debug\net7.0-ios\
        [xma][info]: Getting 'bin\XXX\Debug\net7.0-ios\' checksum for ''...
        [xma][err]: An error occurred getting directory checksum for App 
        [xma][info]: An error occurred while executing the operation. Trying to reestablish the connection...
        [xma][info]: There's no enough information to try a re-connection. Host and credentials information are required
        Warnings
            C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.0.1478\tools\msbuild\iOS\Xamarin.Messaging.Build.targets(146,3): One or more errors occurred. [C:\s\nv.github\uno-3\src\AddIns\Uno.UI.MSAL\XXX.csproj]
        [xma][info]: Starting disconnection...
        [xma][info]: Disposing Messaging service references...
    FileWrites
        obj\XXX\Debug\net7.0-ios\build-signature\signature
```

**Comment by jeromelaban** [comment]
So this issue is considered to not be a bug by the triaging team at dev community: https://developercommunity.visualstudio.com/t/Building-an-net-iOS-project-which-conta/10225786. 

Yet, I hope the .NET team will consider that differently as it impact the reliability of building iOS apps using .NET 6/7, adding to the frustration of the ".NET iOS/Android error bingo" that developers have been playing 😐

**Comment by rolfbjarne** [comment]
> bin log is coming

Marking as need-info until then.

**Comment by jeromelaban** [comment]
This issue is reproducible inside VS (connecting to the mac from the CLI is not necessarily easy), which means the binlog files are separate.

For the same top-level build, here are some projects failing, other working:
- [works-Uno.Foundation.netcoremobile_Debug_AnyCPU_net7.0-ios_DesignTimeBuild_2022-12-13T11_00_33.0527444-05_00.binlog.zip](https://github.com/xamarin/xamarin-macios/files/10219809/works-Uno.Foundation.netcoremobile_Debug_AnyCPU_net7.0-ios_DesignTimeBuild_2022-12-13T11_00_33.0527444-05_00.binlog.zip)
- [fails-Uno.UI.Dispatching.netcoremobile_Debug_AnyCPU_Build_2022-12-13T11_00_38.5818039-05_00.binlog.zip](https://github.com/xamarin/xamarin-macios/files/10219811/fails-Uno.UI.Dispatching.netcoremobile_Debug_AnyCPU_Build_2022-12-13T11_00_38.5818039-05_00.binlog.zip)

For the failed build (and most of the subsequent projects in the same solution build), the error is similar.

There's also that warning which is of interest:
![image](https://user-images.githubusercontent.com/5839577/207383599-353f852a-4c9d-4648-ad3e-46fafad06353.png)

Applying the workaround above is preventing the parallel mac connections, making the build succeed as there's only the app project that connects to the mac.

**Comment by rolfbjarne** [comment]
I wonder if this is related: https://developercommunity.visualstudio.com/t/Unable-to-build-Xamarin-iOS-project-with/10224055 - which happens when building an iOS executable project that depends on another iOS class library project.

(internal ref: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1684986)

In any case I've reopened the original feedback ticked you've filed, it seems to me it was closed in error.

**Comment by jeromelaban** [comment]
Thanks @rolfbjarne!
