### ISSUE TITLE
ILStrip failed for ... resources.dll' not found

### ISSUE THREAD

**Issue by GioviQ** [xamarin/xamarin-macios#17009]
I experience the same issue  as https://github.com/xamarin/xamarin-macios/issues/13922

Differences

MAUI net7.0-ios

Visual Studio 17.4.2

**Comment by rolfbjarne** [comment]
Please attach a [binary build log](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) we can use to diagnose this, since #13922 is fixed and you're probably running into something different (although it looks the same).

**Comment by rolfbjarne** [comment]
Thanks!

For future self: the binlog named `CentralNode_devenv_PID=15944_x64_BuildManager_Unnamed_9.binlog` shows the error.

This is probably the underlying reason (note that the `it` subdirectory got lost):

```
[ILStrip] obj/Release/net7.0-ios/ios-arm64/it/QRCodeGenerator.resources.dll to obj/Release/net7.0-ios/ios-arm64//stripped/QRCodeGenerator.resources.dll
```

This the input item:

```
obj\Release\net7.0-ios\ios-arm64\it\QRCodeGenerator.resources.dll
    CopyToPublishDirectory = PreserveNewest
    Culture = it
    OutputPath = obj/Release/net7.0-ios/ios-arm64//stripped/QRCodeGenerator.resources.dll
    PublishFolderType = Assembly
    RelativePath = ..\QRCodeGenerator.app\\it\QRCodeGenerator.resources.dll
    TargetPath = it\QRCodeGenerator.resources.dll
```

I'm guessing we'll have to take TargetPath into account here:

https://github.com/xamarin/xamarin-macios/blob/1db1f4869812a693c753f8c40a341b84e0525e0e/dotnet/targets/Xamarin.Shared.Sdk.targets#L743-L746

**Comment by GioviQ** [comment]
In the meanwhile how can I publish?

**Comment by rolfbjarne** [comment]
@GioviQ adding this to your project file should do it:

```xml
<PropertyGroup>
    <EnableAssemblyILStripping>false</EnableAssemblyILStripping>
</PropertyGroup>
```

**Comment by rolfbjarne** [comment]
This might be a dup of #17009.
