### ISSUE TITLE
MTOUCH: Error MT4109: Failed to compile the generated registrar code. 

### ISSUE THREAD

**Issue by Karteeka18** [xamarin/xamarin-macios#17029]
###Steps to Reproduce

Try to build an iOS project

###Expected Behavior

Build is successful and deployed onto attached iPhone.

###Actual Behavior

/Users//Documents/repos//Sources/.iOS/MTOUCH: Error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new (MT4109) (*.iOS)

### Environment
iPhone11 - 16.1.2

=== Visual Studio Community 2019 for Mac ===

Version 8.10.25 (build 2)
Installation UUID: e7cb56e8-1f82-413b-8bf9-0c0cd9b2dde7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000182

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.182 (2020-02/6051b710727) (64-bit)
	Package version: 612000182

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/5.0.408/Sdks
SDK Versions:
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.201
	3.1.420
	3.1.418
	3.1.417
	3.1.416
	3.1.407
	3.1.8
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.4
	5.0.3
	3.1.26
	3.1.24
	3.1.23
	3.1.22
	3.1.13
	3.1.12
	3.1.4
	2.1.23
	2.1.18

=== .NET Core 3.1 SDK ===

SDK: 3.1.420

=== .NET 5.0 SDK ===

SDK: 5.0.408

=== Xamarin.Profiler ===

Version: 1.8.0.22
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 12.2.8.3 (Visual Studio Community)
Commit: xamarin-android/d17-1/fafdba7
Android SDK: /Users/macadmin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Apple Developer Tools ===

Xcode 14.1 (21534.1)
Build 14B47b

=== Xamarin.Mac ===

Version: 8.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

=== Xamarin.iOS ===

Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

=== Build Information ===

Release ID: 810250002
Git revision: 0620af530b5800e0eada4882ce1c3d4dad7e53d3
Build date: 2022-06-15 13:41:26-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.6.1
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Thu Sep 29 20:12:57 PDT 2022
    root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64

<details>
<summary>Version information</summary>

```
```

</details>

### Build Logs

```

Compilation failed with code 1, command:
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -Wno-receiver-forward-class -Wno-objc-missing-super-calls -Wno-unguarded-availability-new -stdlib=libc++ -gdwarf-2 -std=c++14 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/15.10.0.5/SDKs/MonoTouch.iphoneos.sdk/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.1.sdk -Qunused-arguments -miphoneos-version-min=10.0 -arch arm64 -c -o /Users/macadmin/Projects/Mobile Programmer/aclara_meters.iOS/obj/iPhone/Debug/device-builds/iphone12.1-16.1.2/mtouch-cache/arm64/registrar.o -x objective-c++ -D DEBUG /Users/macadmin/Projects/Mobile Programmer/aclara_meters.iOS/obj/iPhone/Debug/device-builds/iphone12.1-16.1.2/mtouch-cache/registrar.m
    In file included from /Users/macadmin/Projects/Mobile Programmer/aclara_meters.iOS/obj/iPhone/Debug/device-builds/iphone12.1-16.1.2/mtouch-cache/registrar.m:3:
    /Users/macadmin/Projects/Mobile Programmer/********.iOS/obj/iPhone/Debug/device-builds/iphone12.1-16.1.2/mtouch-cache/registrar.h:111:9: fatal error: 'CHIP/CHIP.h' file not found
    #import <CHIP/CHIP.h>
            ^~~~~~~~~~~~~
    1 error generated.
    MTOUCH : error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
Done building target "_CompileToNative" in project "*****.csproj" -- FAILED.

Done building project "*******.iOS.csproj" -- FAILED.

Build FAILED.

```

**Comment by Karteeka18** [comment]
What is the version of Xamarin.iOS that is compatible with XCode 14.1? I want to update Xamarin.iOS.

**Comment by rolfbjarne** [comment]
I can update to Visual Studio for Mac 2022, and then VS will just update to the latest stable release (which supports Xcode 14.1).

Alternatively you can download and install the latest package here: https://github.com/xamarin/xamarin-macios/blob/main/DOWNLOADS.md

**Comment by Karteeka18** [comment]
It worked. Thank you
