### ISSUE TITLE
maui lib build ios dll as x64 instead of msil

### ISSUE THREAD

**Issue by roubachof** [xamarin/xamarin-macios#17075]
## Description

I have an issue with the packaging of my maui lib, on ios, it builds it in x64 instead of msil:
I tried also with the dotnet cli, same result
![image](https://user-images.githubusercontent.com/596903/207997450-0b871ee0-2921-4dd9-a8f7-ccd8c73ecb2d.png)
![image](https://user-images.githubusercontent.com/596903/207997477-63a49c1a-e69e-46d0-96b8-1c2b3b0a2c4c.png)

## Version

Windows 10

VS version:
![image](https://user-images.githubusercontent.com/596903/207997505-ef9e23e9-04db-4cd7-a1f2-4ae6b952634b.png)

Maui worload:

```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               7.0.52/7.0.100         VS 17.4.33205.214
maui-maccatalyst           7.0.52/7.0.100         VS 17.4.33205.214
maccatalyst                16.1.1477/7.0.100      VS 17.4.33205.214
android                    33.0.4/7.0.100         VS 17.4.33205.214
maui-ios                   7.0.52/7.0.100         VS 17.4.33205.214
ios                        16.1.1477/7.0.100      VS 17.4.33205.214
maui-android               7.0.52/7.0.100         VS 17.4.33205.214
```

## Reproduction

The csproj of the lib is here: https://github.com/roubachof/Sharpnado.Tabs/blob/main/Maui.Tabs/Maui.Tabs.csproj
Just run dotnet pack on it or simply build with Release on VS.

## BinLog for diagnostic

[msbuild.zip](https://github.com/xamarin/xamarin-macios/files/10246759/msbuild.zip)

**Comment by rolfbjarne** [comment]
It's because of the `PlatformTarget=x64` line in Maui.Tabs.csproj.user:

```xml
  <PropertyGroup Condition="'$(TargetPlatformIdentifier)'=='iOS'">
    <RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
```

Delete that line (or the entire file), and the iOS assembly should be MSIL like the other ones.

**Comment by roubachof** [comment]
well that's embarrassing sorry !
