### ISSUE TITLE
MT2101: Can't resolve the reference in Firebase.CloudMessaging

### ISSUE THREAD

**Issue by Ramkumar-Paramathman** [xamarin/xamarin-macios#17077]
I am trying to use Firebase for push notifications in Xamarin.iOS. Am ended with below error.

Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/***.Forms.iOS/obj/iPhone/Release/response-file.rsp --registrar:static "--gcc_flags=-ObjC -ObjC -ObjC -lc++ -lz -ObjC -lc++ -lsqlite3 -lz -lsqlite3 -force_load /*/Library/Caches/XamarinBuildDownload/GAnlytcs-3.17/Libraries/libGoogleAnalytics.a -ObjC -lz -lsqlite3" 
    Xamarin.iOS 16.0.0.72 (release/6.0.4xx-xcode14: 6756a1146) using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.0.sdk
    MTOUCH : error MT2101: Can't resolve the reference 'System.Void Firebase.CloudMessaging.Messaging::SendMessage(Foundation.NSDictionary,System.String,System.String,System.Int64)', referenced from the method 'System.Void Plugin.FirebasePushNotification.FirebasePushNotificationManager::SendDeviceGroupMessage(System.Collections.Generic.IDictionary`2<System.String,System.String>,System.String,System.String,System.Int32)' in 'Firebase.CloudMessaging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

I have installed all the dependent Nuget packages. Still ended up with this error.

**Comment by rolfbjarne** [comment]
Looks like this is a mismatched set of assemblies, code in one assembly tries to use a method that doesn't exist (in another assembly).

If you could get a binary build log (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs), we might be able to figure out what's going on.
