### ISSUE TITLE
UICollectionViewFlowLayout collectionViewContentSize thrown an exception

### ISSUE THREAD

**Issue by saiganesh-sakthivel** [xamarin/xamarin-macios#17099]
### Steps to Reproduce

1. We have crash exception thrown when new item at a NSIndexPath. 
Objective-C exception thrown.  Name: NSRangeException Reason: *** -[__NSArrayM objectAtIndexedSubscript:]: index 1 beyond bounds [0 .. 0]
Native stack trace:
    0   CoreFoundation                      0x000000010ef95af6 __exceptionPreprocess + 242
    1   libobjc.A.dylib                     0x0000000116358e78 objc_exception_throw + 48
    2   CoreFoundation                      0x000000010f01277f _CFThrowFormattedException + 194
    3   CoreFoundation                      0x000000010ee94825 -[__NSArrayM removeAllObjects] + 0
    4   UIKitCore                           0x00000001277c4fcb -[UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:] + 1554
    5   UIKitCore                           0x00000001277c6bcf -[UICollectionViewFlowLayout _fetchItemsInfoForRect:] + 226
    6   UIKitCore                           0x00000001277bfc31 -[UICollectionViewFlowLayout collectionViewContentSize] + 49
    7   UIKitCore                           0x00000001277b7f07 -[UICollectionViewData _validateContentSize] + 170
    8   UIKitCore                           0x00000001277ba546 __45-[UICollectionViewData validateLayoutInRect:]_block_invoke.126 + 37
    9   UIKitCore                           0x00000001277b8c80 -[UICollectionViewData validateLayoutInRect:] + 405
    10  UIKitCore                           0x000000012777da4d -[UICollectionView layoutSubviews] + 240
    11  UIKitCore                           0x00000001285f4504 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2924
    12  QuartzCore                          0x00000001150adc2b -[CALayer layoutSublayers] + 258
    13  QuartzCore                          0x00000001150b419d _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 575
    14  QuartzCore                          0x00000001150bff3f _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 65
    15  QuartzCore                          0x0000000114fff44c _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 496
    16  QuartzCore                          0x0000000115036233 _ZN2CA11Transaction6commitEv + 783
    17  QuartzCore                          0x00000001150373ef _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 79
    18  CoreFoundation                      0x000000010ef031f8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    19  CoreFoundation                      0x000000010eefda77 __CFRunLoopDoObservers + 547
    20  CoreFoundation                      0x000000010eefe01a __CFRunLoopRun + 1113
    21  CoreFoundation                      0x000000010eefd6d6 CFRunLoopRunSpecific + 567
    22  UIFoundation                        0x000000012a21157c -[NSHTMLReader _loadUsingWebKit] + 1847
    23  UIFoundation                        0x000000012a2124b1 -[NSHTMLReader attributedString] + 22
    24  UIFoundation                        0x000000012a192d3a _NSReadAttributedStringFromURLOrData + 9439
    25  UIFoundation                        0x000000012a1907e6 -[NSAttributedString(NSAttributedStringUIFoundationAdditions) initWithData:options:documentAttributes:error:] + 144
    26  KanbanXamarin.iOS                   0x000000010ebad429 xamarin_dyn_objc_msgSend + 217
    27  ???                                 0x00000001591d3c7e 0x0 + 5790055550

### Expected Behavior
It should not thrown the exception.

### Actual Behavior
It thrown the exception

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.4.2
iOS 16.1 version
```

</details>

### Example Project (If Possible)

issue replicate when insert the new item
PerformBatchUpdates(
                            delegate
                            {
                                InsertItems(new NSIndexPath[] { indexPath });
                            },
                            delegate
                            {
                                UpdateData();
                            });

**Comment by rolfbjarne** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide a complete test project (to reproduce) and all your [version information](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#version-information).

We look forward to hearing from you!

**Comment by saiganesh-sakthivel** [comment]
Hi @rolfbjarne,

I have create the sample to replicate the issue, 
[KanbanXamarin.zip](https://github.com/xamarin/xamarin-macios/files/10286735/KanbanXamarin.zip)

**Steps to reproduce**
1. Run the Sample.
2. Drag the card from one column to another column.
3. The reported crash exception will thrown.

Regards,
SaiGanesh Sakthivel

**Comment by rolfbjarne** [comment]
Thanks for the test project, I'm able to reproduce the issue.

Then I updated the Xamarin.Forms packages in the project, and the problem went away, so it seems this is fixed already.
