### ISSUE TITLE
Failed to compile the generated rigistrar code

### ISSUE THREAD

**Issue by RemcoVBl** [xamarin/xamarin-macios#17121]
### Steps to Reproduce

1.  Update VS and Xamarin iOS
2.  Rebuild project
3. 

### Expected Behavior

succesful build

### Actual Behavior

Error MT4109

### Environment

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.25 (build 2)
Installation UUID: 03f63ce3-6b0d-417c-9932-e06585375356
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000182

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.182 (2020-02/6051b710727) (64-bit)
	Package version: 612000182

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/5.0.408/Sdks
SDK Versions:
	7.0.101
	7.0.100
	6.0.404
	6.0.403
	6.0.401
	6.0.400
	6.0.302
	5.0.408
	3.1.426
	3.1.425
	3.1.423
	3.1.422
	3.1.420
MSBuild SDKs: /Applications/Visual Studio (2019).app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.1
	7.0.0
	6.0.12
	6.0.11
	6.0.9
	6.0.8
	6.0.7
	5.0.17
	3.1.32
	3.1.31
	3.1.29
	3.1.28
	3.1.26

=== .NET Core 3.1 SDK ===

SDK: 3.1.426

=== .NET 5.0 SDK ===

SDK: 5.0.408

=== Xamarin.Profiler ===

Version: 1.8.0.22
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 14.2 (21534)
Build 14C18

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 15.10.0.5 (Visual Studio Enterprise)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

=== Xamarin.Android ===

Version: 12.2.8.3 (Visual Studio Enterprise)
Commit: xamarin-android/d17-1/fafdba7
Android SDK: /Users/remcovanblarcum/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

=== Eclipse Temurin JDK ===

Java SDK: Not Found

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Build Information ===

Release ID: 810250002
Git revision: 0620af530b5800e0eada4882ce1c3d4dad7e53d3
Build date: 2022-06-15 13:41:26-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 13.0.0
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:14:54 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by rolfbjarne** [comment]
You're using a new version of Xcode:

> Xcode 14.2 (21534)

With an old version of Xamarin.iOS:

> === Xamarin.iOS ===
> Version: 15.10.0.5 (Visual Studio Enterprise)

You need to update to the latest version of Xamarin.iOS (which supports Xcode 14.*).

The best way is to update to Visual Studio for Mac 2022, I see you have Visual Studio for Mac 2019:

> === Visual Studio Enterprise 2019 for Mac ===

Alternatively you can try the latest build here: https://github.com/xamarin/xamarin-macios/blob/main/DOWNLOADS.md

**Comment by RemcoVBl** [comment]
Hello,

 

Thank you very much for the quick reply.

 

I have upgraded to a new version of Xamarin.ios and the problem is solved.

 

I am not able to upgrade to VS2022 for mac, because on that version my Xamarin.Uitest scripts does not run. Engineers from Microsoft are investigating this problem at the moment.



Thanks and best regards,

Remco van Blarcum
Senior Medewerker Informatievoorziening
Lead Tester MCC (Mobile Competence Center)
Trombonist Nederlands Douane Orkest


........................................................................
Generieke Voorzieningen - MCC Ontvangen & Mededelen
IV Organisatie Belastingdienst
John F. Kennedylaan 8 | 7314 PS | Apeldoorn | Gebouw G0.18
........................................................................

M 06 11 7775 34
T 055 528 6854
E ***@***.***

......................................................................................................


 

 

----- Oorspronkelijk bericht -----
Van: "Rolf Bjarne Kvinge" ***@***.***>
Aan: "xamarin/xamarin-macios" ***@***.***>
Cc: "RemcoVBl" ***@***.***>, "Author" ***@***.***>
Onderwerp: Re: [xamarin/xamarin-macios] Failed to compile the generated rigistrar code (Issue #17121)
Datum: vr 23 dec. 2022 10:45
 
[EXTERNE E-MAIL] Dit bericht is afkomstig van een externe afzender. Wees voorzichtig met het openen van linkjes en bijlagen.

 

 

Closed #17121 as not planned.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>


 


------------------------------------------------------------------------De Belastingdienst stelt e-mail niet open voor aanvragen, aangiften, bezwaarschriften, verzoeken, klachten, ingebrekestellingen en soortgelijke formele berichten. Dit bericht is uitsluitend bestemd voor de geadresseerde. Het bericht kan vertrouwelijke informatie bevatten waarvoor de fiscale geheimhoudingsplicht geldt. Als u dit bericht per abuis hebt ontvangen, wordt u verzocht het te verwijderen en de afzender te informeren. 
The Dutch Tax Administration does not accept filings, requests, appeals, complaints, notices of default or similar formal notices, sent by email. This message is solely intended for the addressee. It may contain information that is confidential and legally privileged. If you are not the intended recipient please delete this message and notify the sender.
