### ISSUE TITLE
MacCatalyst applications do not generate dSYM file

### ISSUE THREAD

**Issue by arivoir** [xamarin/xamarin-macios#17134]
I can not load symbols from instruments for a MacCatalyst application, and apparently is because dSYM file is not created when building the mac-catalyst application.

- Create new application
- Build the application
- dSYM file is not created

[TestMacApp.zip](https://github.com/xamarin/xamarin-macios/files/10337944/TestMacApp.zip)

dotnet --version 7.0.101

PS: The dSYM is created for a normal iOS application in the same environment

**Comment by rolfbjarne** [comment]
Can you try adding this to your csproj and see if that works for you?

```xml
<PropertyGroup>
    <NoDSymUtil>false</NoDSymUtil>
</PropertyGroup>
```

**Comment by rolfbjarne** [comment]
On x64 Mac Catalyst the app will use the JIT, which creates executable at runtime, and thus the dSYM won't contain the information required to symbolicate memory addresses.

If you build for ARM64 (and if you have an M1/M2 machine), we'll use the AOT compiler, which should provide better information.

Adding this to the csproj will build form ARM64:

```xml
<PropertyGroup>
    <RuntimeIdentifier>maccatalyst-arm64</RuntimeIdentifier>
</PropertyGroup>
```

**Comment by arivoir** [comment]
I don't have a mac with M1/M2 chip, I have an Intel one, is there any way of using AOT and produce debuggable dSym's for this scenario?

**Comment by rolfbjarne** [comment]
> I don't have a mac with M1/M2 chip, I have an Intel one, is there any way of using AOT and produce debuggable dSym's for this scenario?

Unfortunately there isn't at the moment.

Is there any particular problem you're trying to diagnose with Instruments? In the past, I've done built iOS apps and profiled them with Instruments on an iOS device, and that works.

**Comment by arivoir** [comment]
I'm improving the performance of a data-grid control https://www.grapecity.com/componentone/maui-ui-controls/flexgrid-maui-datagrid, The code is mostly the same for iOS and MacCatalyst, but I noticed the performance is rather different in one platform or the other, and was trying to see whether it is a general difference or some of the native calls takes more time in MacCatalyst

**Comment by rolfbjarne** [comment]
> I'm improving the performance of a data-grid control [grapecity.com/componentone/maui-ui-controls/flexgrid-maui-datagrid](https://www.grapecity.com/componentone/maui-ui-controls/flexgrid-maui-datagrid), The code is mostly the same for iOS and MacCatalyst, but I noticed the performance is rather different in one platform or the other, and was trying to see whether it is a general difference or some of the native calls takes more time in MacCatalyst

OK, I see why you'd need to profile the Mac Catalyst version then. Unfortunately that's not easy to do if you don't have an ARM64 machine :/

Have you looked into this: https://github.com/dotnet/maui/wiki/Profiling-.NET-MAUI-Apps?

**Comment by arivoir** [comment]
Not yet, thanks for the tip!
