### ISSUE TITLE
Xcode Simulators gone with update to MacOS 13.1

### ISSUE THREAD

**Issue by NLGhofman** [xamarin/xamarin-macios#17133]
### Steps to Reproduce

1. Update Xcode to 14.1 + Visual studio for Mac 17.4.2 (most recent)
2. Update MacOS to 13.1

### Expected Behavior
Can select a iOS simulator to build apps (standard generated template)

### Actual Behavior
No simulators available - Lower 'Deployment Target'

### Environment

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by Awdos** [comment]
same problem, any solutions?

**Comment by NLGhofman** [comment]
@Awdos we found the problem by looking at the installed elements inside the "About Visual Studio" -> "Show Details".

Apparently the other department didn't have the right Xamarin.iOS (16.1.1.27) it didn't show up when checking "Check for Updates". But after updating that we got the simulators back.
