### ISSUE TITLE
Latest releases do not include .pkg for Xamarin.iOS

### ISSUE THREAD

**Issue by MDThomsen** [xamarin/xamarin-macios#17141]
The latest releases at [https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-7.0.1xx-1477](https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-7.0.1xx-1477) and [https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-6.0.4xx-xcode14.1-228](https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-6.0.4xx-xcode14.1-228) do not include .pkg files for Xamarin.iOS

Is there any way of downloading the .pkg files for those releases?

**Comment by dalexsoto** [comment]
Happy new year!

You can find it here https://github.com/xamarin/xamarin-macios/releases/tag/xamarin-ios-16.1.1.28
