### ISSUE TITLE
Setting UIMenu.PreferredElementSize crashes Xamarin.iOS apps

### ISSUE THREAD

**Issue by haavamoa** [xamarin/xamarin-macios#17156]
### Steps to Reproduce
I've created a UIMenu in a Xamarin.Forms UIButtonRenderer to achieve the native Context Menu option for my UIButton. I want to set the `PreferredElementSize` so the menu gets a nice size that corresponds to my needs in my application. When I do, the app crashes.

When I've read the Apple documentation it looks like `PreferredElementSize` `UIMenu.ElementSize` enum is in fact a `int`, while the Xamarin.iOS `UIMenuElementSize` looks like its a `long`. Might that be why it fails?

1. Create a UIMenu and attach it to a UIButton
2. Set the UIMenus PreferredElementSize
3. Observe that it crashes with the following error:

```
Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[UIMenu setPreferredElementSize:]: unrecognized selector sent to instance 0x600003271860
Native stack trace:
	0   CoreFoundation                      0x000000010b260bb4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x0000000117f73be7 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b26f821 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x000000010b2650bc ___forwarding___ + 1433
	4   CoreFoundation                      0x000000010b2671e8 _CF_forwarding_prep_0 + 120
	5   DIPS.Xamarin.UI.Samples.iOS         0x00000001011dd309 xamarin_dyn_objc_msgSend + 217
	6   ???                                 0x0000000160a54c40 0x0 + 5916412992
```

### Expected Behavior
The size of the UIMenu changes like [the documentation](https://developer.apple.com/documentation/uikit/uimenu/4013313-preferredelementsize?changes=_6)

### Actual Behavior
The app crashes

### Environment

<details> 
<summary>Version information</summary>

```
Visual Studio Enterprise 2022 for Mac
Version 17.4.1 (build 28)
Installation UUID: 37e8d7e2-d19b-4e45-9cd9-181e506b75aa

Runtime
.NET 6.0.9 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-6.22578.12+3c6ab8e1715e5b080fb7bb77070810ab71e09387

NuGet
Version: 6.3.1.1

.NET SDK (Arm64)
SDK: Not installed

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.6
	6.0.3
	6.0.2
	6.0.1
	5.0.17 (x64 – Unsupported)
	5.0.15 (x64 – Unsupported)
	5.0.14 (x64 – Unsupported)
	5.0.13 (x64 – Unsupported)
	3.1.29 (x64 – Unsupported)
	3.1.26 (x64 – Unsupported)
	3.1.23 (x64 – Unsupported)
	3.1.22 (x64 – Unsupported)

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2022-12-02 15:36:20 UTC

Apple Developer Tools
Xcode 14.2 (21534)
Build 14C18

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Enterprise)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Enterprise)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin.Android
Version: 13.1.0.1 (Visual Studio Enterprise)
Commit: xamarin-android/d17-4/13ba222
Android SDK: /Users/hmo/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: a96bde9
Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
SQLite: xamarin/sqlite/3.39.3@23e1ae7
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2022-12-02 15:36:24 UTC

Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2022-12-02 15:36:24 UTC

Build Information
Release ID: 1704010028
Git revision: f17dcd4436244cc06ed14dc5238c4d3fa788144f
Build date: 2022-12-02 15:34:08+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 13.0.1
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:14:30 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64


```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/10363050/msbuild.binlog.zip)
### Example Project (If Possible)
Here is my UX library that I use for my apps, where my [button renderer class is](https://github.com/DIPSAS/DIPS.Xamarin.UI/blob/783806e6f3adbfc4d8606e89b1942bd09c8ad805/src/DIPS.Xamarin.UI.iOS/ContextMenu/ContextMenuButtonRenderer.cs#L64). Fork the project, run the Samples app on a iOS simulator and navigate to Controls > Context Menu. Tap an item to open the context menu.
If you modify UIMenu [here](https://github.com/DIPSAS/DIPS.Xamarin.UI/blob/783806e6f3adbfc4d8606e89b1942bd09c8ad805/src/DIPS.Xamarin.UI.iOS/ContextMenu/ContextMenuButtonRenderer.cs#L64) and set the `PreferredElementSize`, the page samples Context Menu page crashes.

**Comment by GalaxiaGuy** [comment]
From the docs:

https://developer.apple.com/documentation/uikit/uimenuelementsize?changes=_6&language=objc

`UIMenuElementSize` is `NSInteger`, which is 64 bit on 64 bit systems, and 32 bit on 32 bit systems. I don't think that is the problem.

What version of iOS were you trying it on? This API is only on iOS 16 and above.

**Comment by GalaxiaGuy** [comment]
It's also possible the API has not been bound in Xamarin yet.

**Comment by haavamoa** [comment]
Tested on iOS 16 👍

**Comment by haavamoa** [comment]
Oh no, never mind me. I was testing on iOS 15 with a simulator :( My bad.
Tested on iOS 16 and it works :)
