### ISSUE TITLE
[MacCatalyst][MAUI] `Authorization.ExecuteWithPrivileges` returns -60031 

### ISSUE THREAD

**Issue by nor0x** [xamarin/xamarin-macios#17168]
i have the issue that a call to `Authorization.ExecuteWithPrivileges` returns -60031 in a new MAUI app. I have seen this issue in the xamarin-macios repository and was wondering if this is also fixed for MAUI (.NET 7) 

https://github.com/xamarin/xamarin-macios/issues/13465
There is a workaround described in the comment (https://github.com/xamarin/xamarin-macios/issues/13465#issuecomment-982791080) but i had no luck with it. 
I have already tried null terminating the args array manually `var args = new[] { "--help", null };` but i still get a -60031

### Steps to Reproduce

1. call `ExecuteWithPrivileges` in a .NET 7 MAUI app (MacCatalyst) 
2. enter credentials in the Auth dialog
3. result is `AuthorizationStatus.ToolExecuteFailure`

a repro project is here:
https://github.com/nor0x/maui-mac-13465

### Expected Behavior
result should be 0 if credentials are correct

### Actual Behavior
result is `AuthorizationStatus.ToolExecuteFailure`

### Environment

<details>
<summary>Version information</summary>

Visual Studio Community 2022 for Mac Preview
Version 17.5 Preview (17.5 build 1095)
Installation UUID: 26593f12-c343-4f44-874b-81759b4b2587

Runtime
.NET 7.0.1 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.4.0-6.22578.12+3c6ab8e1715e5b080fb7bb77070810ab71e09387

NuGet
Version: 6.4.0.117

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.101/Sdks
SDK Versions:
	7.0.101
	7.0.100
	6.0.404
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	5.0.408
	3.1.426
	3.1.425
	3.1.424
	3.1.423
	3.1.422
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.1
	7.0.0
	6.0.12
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	5.0.17
	3.1.32
	3.1.31
	3.1.30
	3.1.29
	3.1.28

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

Xamarin.Mac
Version: 9.0.0.28 Visual Studio Community
Hash: 6714e055b
Branch: xcode14.1
Build date: 2022-11-29 11:45:28-0500

Xamarin.iOS
Version: 16.1.1.28 Visual Studio Community
Hash: 6714e055b
Branch: xcode14.1
Build date: 2022-11-29 11:45:29-0500

Xamarin Designer
Version: 17.5.2.64
Hash: 627f860876
Branch: remotes/origin/d17-5
Build date: 2022-12-13 00:32:24 UTC

Xamarin.Android
Version: 13.1.99.61 (Visual Studio Community)
Commit: xamarin-android/main/2e10309
Android SDK: /Users/johnny/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		7.0  (API level 24)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/main@984711a3
SQLite: xamarin/sqlite/3.40.0@fdc1e34
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@fa3711b

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.20
Hash: 1d9661c
Branch: main
Build date: 2022-12-13 00:32:28 UTC

Android Device Manager
Version: 0.0.0.1230
Hash: 3e7c0ce
Branch: main
Build date: 2022-12-13 00:32:28 UTC

Build Information
Release ID: 1705001095
Git revision: ed096e87770693cb1e098be503c65861dbe08474
Build date: 2022-12-13 00:30:33+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 13.0.1
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:14:54 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

</details>

### Example Project (If Possible)
https://github.com/nor0x/maui-mac-13465

PS: i had this issue here in the maui repo - which was probably the wrong place to open it.

**Comment by rolfbjarne** [comment]
The first argument to `ExecuteWithPrivileges` is the path to the executable, but you're passing in "echo hello world!", which isn't an executable:

https://github.com/nor0x/maui-mac-13465/blob/6ea8caaf1589a290342cccc991e3fa14d9daa676/MacCat_Auth/MainPage.xaml.cs#L18

Changing that line to just say "echo" doesn't work either, because "echo" isn't actually an executable:

```shell
$ which echo
echo: shell built-in command
```

However, if I use an actual executable, like this:

```cs
RunAsRoot("/usr/bin/true");
```

then your sample project works as expected for me.

Can you try and see if that works for you too?

**Comment by nor0x** [comment]
@rolfbjarne my bad i thought i could directly pass a command. passing a path to the executable works fine.


THANK YOU
