### ISSUE TITLE
Binding project errors:  MT5209 : Native linking error relating to standard swift libraries.

### ISSUE THREAD

**Issue by dk-jlew** [xamarin/xamarin-macios#17179]
Context: large Xamarin Forms 5 in which I'm trying to bind a native (xc)framework along with a bunch of dependencies (also xcframeworks which are included in the bundle but not bound).  These are all delivered via a nuget-packaged Xamarin.iOS binding project.  This has been working fine, but the native code is now pulling in a Swift Package which (either itself or one of its dependencies) is leading to multiple errors when building the app, like:
```
error MT5209 : Native linking error : warning: Could not find or use auto-linked library 'swiftCoreGraphics'
error MT5209 : Native linking error : warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
...etc...
```
...followed by many "symbol not found" linker errors which are presumably a consequence of the `MT5209` errors above.   I have followed the [Microsoft guidance here](https://learn.microsoft.com/en-us/xamarin/ios/platform/binding-swift/walkthrough#build-a-binding-library) and added the following to my `NativeReference's` `<LinkerFlags>`: (there are multiple native references, and I add this to *each* of them since I am not sure which ones might be the problem, but this redundancy seems(?) harmless):

```
L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/ -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Wl,-rpath -Wl,@executable_path/Frameworks
```
IMPORTANT: A bare-bones Xamarin.iOS project **builds/runs successfully** when referencing/using the same nuget binding package.  My real XF app has other binding projects as well, I'm not sure if there could be a conflict here, or what the difference might be.

### Steps to Reproduce

1.  Build my big XF 5.0 solution, in the  `Debug` | `iPhoneSimulator` configuration.

### Expected Behavior

App builds sucessfully

### Actual Behavior

iOS app project fails to build with the errors mentioned above

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac Preview
Version 17.5 Preview (17.5 build 437)
Installation UUID: 92d59e15-2ada-4ba7-870a-cadfaf4a5a3c

Runtime
.NET 7.0.0 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-3.22461.4+8ab250290a4010c11a21521f78dbc87dbb7aac81

NuGet
Version: 6.3.1.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.100/Sdks
SDK Versions:
	7.0.100
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	6.0.301
	6.0.300
	6.0.202
	6.0.201
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	6.0.301
	6.0.300
	6.0.105
	6.0.103
	5.0.408
	5.0.406
	3.1.425
	3.1.424
	3.1.423
	3.1.422
	3.1.420
	3.1.419
	3.1.418
	3.1.417

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.0
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	6.0.6
	6.0.5
	6.0.4
	6.0.3

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	6.0.6
	6.0.5
	6.0.3
	5.0.17
	5.0.15
	3.1.31
	3.1.30
	3.1.29
	3.1.28
	3.1.26
	3.1.25
	3.1.24
	3.1.23

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Version: 8.12.0.2 (Visual Studio Community)
Hash: 87f98a75e
Branch: d17-3
Build date: 2022-07-25 20:18:54-0400

Xamarin Designer
Version: 17.5.1.13
Hash: 14bdde937f
Branch: remotes/origin/d17-5
Build date: 2022-11-02 21:36:49 UTC

Xamarin.Android
Version: 13.1.0.1 (Visual Studio Community)
Commit: xamarin-android/d17-4/13ba222
Android SDK: /Users/jlew/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		11.0 (API level 30)
		13.0 (API level 33)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 33.0.1

Build Information: 
Mono: a96bde9
Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
SQLite: xamarin/sqlite/3.39.3@23e1ae7
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.8
Hash: 6f27afd
Branch: remotes/origin/HEAD
Build date: 2022-11-02 21:36:54 UTC

Android Device Manager
Version: 0.0.0.1217
Hash: 6175224
Branch: main
Build date: 2022-11-02 21:36:54 UTC

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Build Information
Release ID: 1705000437
Git revision: a5d0fb913c1ff781c80fe725a3e0511c34e26a08
Build date: 2022-11-02 21:34:22+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 12.6.1
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Thu Sep 29 20:13:56 PDT 2022
    root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64
```

</details>

### Build Logs
Can't post these on github, available through secure channel on request.

### Example Project (If Possible)

The full project is difficult to provide... I can provide the problematic nuget package and bare-bones Xamarin.iOS project which *does* build easily enough.

**Comment by dk-jlew** [comment]
This seems extremely similar to [this issue](https://github.com/facebookarchive/react-native-fbsdk/issues/755) from React Native, but I have no way to try their solution since we don't have direct control of the Xcode project.

**Comment by dk-jlew** [comment]
@rolfbjarne Do you have any insight into this, or can I provide more info?

**Comment by rolfbjarne** [comment]
@dk-jlew could you get a binary build log (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs)?

**Comment by dk-jlew** [comment]
Sure, here you go:
[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/10446337/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
@dk-jlew can you try adding `-gcc_flags "-L /usr/lib/swift"` in the additional mtouch arguments in the project's iOS Build properties? If that doesn't work, please attach another build log.

**Comment by dk-jlew** [comment]
@rolfbjarne That didn't work by itself (though it seemed to reduce the # of errors).  BUT, this did:
`-gcc_flags "-L /usr/lib/swift -L /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(Platform)"`

It seems like you need both, for reasons I don't understand.
Do you know if there's an msbuild property that points to the xcode toolchain root that the rest of the build process is using?  Thanks!

**Comment by rolfbjarne** [comment]
The property `_SdkDevPath` will be set to `/Applications/Xcode.app/Contents/Developer`, so you could add this to the csproj:

> -gcc_flags "-L /usr/lib/swift -L $(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(Platform)"

**Comment by dk-jlew** [comment]
Seems like `_SdkDevPath` may not exist until after `DetectSdkLocations` task runs, I’ll try hooking into that.  Thanks for your assistance!

From: Rolf Bjarne Kvinge ***@***.***>
Date: Thursday, January 19, 2023 at 8:54 AM
To: xamarin/xamarin-macios ***@***.***>
Cc: Jeremy Lew ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [xamarin/xamarin-macios] Binding project errors: MT5209 : Native linking error relating to standard swift libraries. (Issue #17179)
The property _SdkDevPath will be set to /Applications/Xcode.app/Contents/Developer, so you could add this to the csproj:-gcc_flags "-L /usr/lib/swift -L $(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(Platform)"—Reply to this email directly, view it on Gi ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌

[https://alert-dg01.redatatech.com/onprem_security_warning_fetch?r=1&dep=9opi0uqgI0zvpLM%2F27gJbw%3D%3DkLGbDhaZrl4hE7txnJV%2BWtZFsZM6XxbxSl%2B1dESq8Aiizn17btTWqZyRvsarFoInv0qhvpBxXXwafScIYzQkeG1hszhRffDRcim8wGFAqd1JVRKU36jmXRgTmuGiNrWucyjNnfWG6CFeCI3XFeKaLMUQYlScG70g1b%2BEn4VV1bI7LXTkF3bHwEA445DvJiUxqYYbZwRT%2BreXbJPPTrg07T0slspzdfeNtOwpqtSIV9p9dIz%2Fon6rl68rTDufPbEb%2BlyX3gImGoEjafQgjzd6jV5yFcv8wggSmwPLkbSkWzhQrIZNvd7ZpAd3p7ko6f46yiNhgF%2B%2BD19LywtmlCZ%2BtPrP3eKRoBBOheaFANl73edV6nXFYry9ypw6iIZH1pJpfM%2B8shHxWl8n6AvDF36fKLawTYinCNssen67%2BLVFXupUaTF4vG5AiCDbyQEMglA3ndkIzGAU20CM1kCZPZ3cx237jJkhqVzO%2BBkFs1vbUPSP6jf%2Btkxjbq%2BJZXigvA57V65ltf1GjVkJVG7VgPOfG4bI2YDUXCUNxp6wF1X%2Bae2ibDG4aevd4YVMu2pmObbIwnVnHDl5BXSxdLbMCbu7ksQWrq77mO23o9%2F4yJyCjoNX68ntUxyyOiFq4K9Cjujv%2Fzaxid8o4lTCT71WulhCPilkL%2BMkmWZu1zy%2B2rTuWBy4v8f%2BEGVfYqE9IP2kVagLIRJ7tNz0oo7AHtu%2FTwHCWHkLah1KIvcPMM4gMThylY0bb2rhZ94687U%2FlsfhDJPN%2BG40D0hxeavMdaeoUt2Y2yimRO%2B6b8VZdjo2B6rpfq8WKhk4w6Vdk1P%2FZURre5w5UAkw30HW%2BxFFupUmkGjSgy6w3M8xIYUFnZDHL%2FLlLwZNPHBIYPg1NtG4Fff%2B1oj7]<https://protect-us.mimecast.com/s/tiIlCXDwN7U9p758I69tEB?domain=us.report.cybergraph.mimecast.com>

The property _SdkDevPath will be set to /Applications/Xcode.app/Contents/Developer, so you could add this to the csproj:

-gcc_flags "-L /usr/lib/swift -L $(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(Platform)"

**Comment by dk-jlew** [comment]
I had to do this due to the way` MtouchExtraArgs` and `_BundlerArguments` are intertwined.  Kinda ugly, but it works:
```
<Target Name="CreateMtouchExtraArgs" AfterTargets="_DetectSdkLocations">
        <PropertyGroup>
            <MtouchExtraArgs>$(MtouchExtraArgs) -v -v -v -v -gcc_flags "-L /usr/lib/swift -L $(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(Platform)"</MtouchExtraArgs>
            <_BundlerArguments Condition="'$(_PlatformName)' != 'macOS'">$(MtouchExtraArgs)</_BundlerArguments>
        </PropertyGroup>
        <Message Importance="high" Text="MtouchExtraArgs is $(MtouchExtraArgs)" />
 </Target>
```
