### ISSUE TITLE
Pair To Mac: Error when connecting to Mac from Windows VS2022: "One or more errors occurred, SSH keys cannot be used from any known location"

### ISSUE THREAD

**Issue by vilinet** [xamarin/xamarin-macios#17184]
### Steps to Reproduce

Just simply try to connect to the MAC from Windows PC On Mac via SSH using my proper user/pass.

### Expected Behavior

It should just connect i assume.

### Actual Behavior

I get this error: "One or more errors occurred, SSH keys cannot be used from any known location"

![image](https://user-images.githubusercontent.com/13279531/211758530-c16d12a1-79a2-4be7-8d73-6af170e6032c.png)

### Other
In the Settings->Connection Manager i was able to add the Mac to the list but it is still not working, still shows me the Pair To Mac dialog, even though i have that in the Connection Manager, so still i cannot build anything Apple related.

I enabled Remote Diagnostic logging, but the log files are empty. (Connection Manager was logging properly, but not the Pair to Mac dialog)

### Environment

macOS Venture 13.1
Windows 10 22H2
Latest VS 2022 on both platform: 17.4.2 on Mac, 17.4.4 on Windows

**Comment by CmdrFigrow** [comment]
I can also confirm that I'm experiencing the same issue, same replication steps.
### Environment
macOS Ventura 13.1
Xcode 14.2
Windows 11 21H2
VS 2022 17.4.4

**Comment by RobjDickinson** [comment]
Same here, on our build server (win 2016) , works fine on my local PC (win 10pro). Latest VS on both.

**Comment by AlleSchonWeg** [comment]
Delete the content of this folder: C:\Users\xxx\AppData\Local\Xamarin\MonoTouch. Backup files first. 
Then you can try again. You have to add the mac again.

**Comment by vilinet** [comment]
> Delete the content of this folder: C:\Users\xxx\AppData\Local\Xamarin\MonoTouch. Backup files first. Then you can try again. You have to add the mac again.

I tried it now, i have tried it earlier as well, but it does not help at all.

**Comment by RobjDickinson** [comment]
> Delete the content of this folder: C:\Users\xxx\AppData\Local\Xamarin\MonoTouch. Backup files first. Then you can try again. You have to add the mac again.

Yes this doesnt work.

I connect tot he mac fine, I can see what simulators or what physical iPhones are on the mac. Then I go to build and I get the SSH error. Ever time.

**Comment by Christophe06410** [comment]
> 

This worked for me with VS 2022 17.4.4 Community, thanks.

**Comment by RobjDickinson** [comment]
complete????

**Comment by vilinet** [comment]
I raised it on the MS DEV channel, come here :) 

https://developercommunity.visualstudio.com/t/Pair-To-Mac:-Error-when-connecting-to-Ma/10260474?port=1025&fsid=1f054ad4-4474-4f8d-9c17-5e46021d2f26&ref=native&refTime=1674553429595&refUserId=24bc7f7a-f68c-6592-8080-53a5bded196c
