### ISSUE TITLE
MAUI 6/7: clang++ exited with code 1: Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by amittapelly11** [xamarin/xamarin-macios#17196]
### Steps to Reproduce

1. Created MAUI iOS class library Project & added native frameworks
2. Create MAUI app and added the reference of MAUI iOS class Library created in step 1
3. Compile MAUI app

### Expected Behavior
MAUI app created in step 2 should compile
### Actual Behavior
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.0.523/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GCCustomFields", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_GCError", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_GCMyIpError", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_GeoComplyClient", referenced from:
      objc-class-ref in registrar.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
### Environment
Visual Studio Community 2022 for Mac 17.4.2
.Net SDK 7.0.101
.Net Runtime(x64) 7.0.7
Xamarin.iOS
Version: 16.1.1.27
I referred this github link - https://github.com/xamarin/xamarin-macios/issues/16223 - didn't find any solution.
Thanks in Advance!

**Comment by ertan2002** [comment]
I have the same issue 

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1007/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ComboBarcodeApi", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_ComboNFCApi", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_ComboRFIDApi", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_CommonDevice", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_CommonReaderInfo", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_RcpApi", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_SDeviceApi", referenced from:
      objc-class-ref in registrar.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation) (TestMauiApp)


Is there any dirty solution at least?

**Comment by rolfbjarne** [comment]
@ertan2002 please file a new issue and attach a test project we can use to reproduce the issue (in order to figure out what's going on, so that we can provide any solutions).

**Comment by ertan2002** [comment]
> @ertan2002 please file a new issue and attach a test project we can use to reproduce the issue (in order to figure out what's going on, so that we can provide any solutions).

Thank you for your reply. I am opening a new issue now

**Comment by ertan2002** [comment]
@rolfbjarne  I've created new issue now  and added my sample project for test. More than several days I am working on it but did not find out the way

https://github.com/xamarin/xamarin-macios/issues/17527
