### ISSUE TITLE
Localization completely broken in IOS apps

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#17262]
_From @nevse on Mon, 16 Jan 2023 08:09:54 GMT_

### Description

It's impossible to add more than one additional language to an ios app.

Localization resx files are ignored for 2 and more additional languages when an ios app was built in release and run on device.

I created a simple app, source code available [here](https://github.com/nevse/maui-tests-iosreleaselocalization). It contains three resx files (Resources/MyLocalization.resx, Resources/MyLocalization.de.resx, Resource/MyLocailzation.es.resx) which I use to obtain the localized string "MyString" in the following way:
```
        Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture = new CultureInfo("de");
        CultureStringLabel.Text = resourceManager.GetString("MyString");
```
It works fine when I build my app in release for an iphone simulator, but it doesn't work when I build it in release for a real device. It works only for one additional resx file.

### Steps to Reproduce

1. create an app from the default template: `dotnet new maui`
2. add three buttons and create handlers for them
```xaml
 <ScrollView>
      <VerticalStackLayout
          Spacing="25"
          Padding="30,0"
          VerticalOptions="Center">

          <Button Text="Set Eng Culture" Clicked="OnSetEngCulture" />
          <Button Text="Set De Culture" Clicked="OnSetDeCulture" />
          <Button Text="Set Es Culture" Clicked="OnSetEsCulture" />
          <Label x:Name="CultureStringLabel" />
      </VerticalStackLayout>
  </ScrollView>
```
```cs
private void OnSetEngCulture(object sender, EventArgs e)
{
      Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
      CultureStringLabel.Text = resourceManager.GetString("MyString");
}
private void OnSetDeCulture(object sender, EventArgs e)
{
Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture = new CultureInfo("de");
      CultureStringLabel.Text = resourceManager.GetString("MyString");
  }
  private void OnSetEsCulture(object sender, EventArgs e)
  {
      Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture = new CultureInfo("es");
      CultureStringLabel.Text = resourceManager.GetString("MyString");
  }
```
3. build the app in release and run on the real iphone device

Press each button - you should see different strings (string from eng, string from de, string from es).

Press "Set Eng Culture" to see "string from eng".
Press "Set De Culture" you should see the "string from de", but this string is "string from eng". It's wrong behaviour.
Press "Set Es Culture" to see "string from es".

### Link to public reproduction project repository

https://github.com/nevse/maui-tests-iosreleaselocalization

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

ios 16

_Copied from original issue dotnet/maui#12684_

**Comment by rolfbjarne** [comment]
_From @jfversluis on Mon, 16 Jan 2023 13:02:44 GMT_

Is this maybe related or the same as https://github.com/xamarin/xamarin-macios/issues/16847? 

@rolfbjarne ?

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Mon, 16 Jan 2023 13:52:28 GMT_

> Is this maybe related or the same as [xamarin/xamarin-macios#16847](https://github.com/xamarin/xamarin-macios/issues/16847)?
> 
> @rolfbjarne ?

No, this is something different, and I can reproduce it.

Add this to the project file to work around it:

```xml
<PropertyGroup>
    <EnableAssemblyILStripping>false</EnableAssemblyILStripping>
</PropertyGroup>
```

**Comment by rolfbjarne** [comment]
This might be a dup of #17009 / #14841.

**Comment by softlion** [comment]
@rolfbjarne Is this one related too https://github.com/dotnet/maui/discussions/13456 ?

**Comment by rolfbjarne** [comment]
@softlion if the workaround [above](https://github.com/xamarin/xamarin-macios/issues/17262#issuecomment-1384092802) works, then it is.

**Comment by softlion** [comment]
> @softlion if the workaround [above](https://github.com/xamarin/xamarin-macios/issues/17262#issuecomment-1384092802) works, then it is.

The workaround does fix the issue with the translations, but breaks the grouped CollectionView (which is perfectly working without the workaround).

**Comment by softlion** [comment]
> > > @softlion if the workaround [above](https://github.com/xamarin/xamarin-macios/issues/17262#issuecomment-1384092802) works, then it is.
> > 
> > 
> > The workaround does fix the issue with the translations, but breaks the grouped CollectionView (which is perfectly working without the workaround). The collectionview appears correctly the 1st time it is opened, but after a child page is opened and closed, the main page displays a broken collectionview with tons of funky group headers instead of a few group and a bunch of normal items. Very very curious breaking.
> > Without the workaround the collectionview has no such issue.
> 
> That's indeed a very strange break, because the work around turns off an optimization only done in release builds (this means that the workaround is effectively in place for debug builds, which I assume are working fine?).
> 
> I'm inclined to believe something else is going on.

You are right. It's something else.

**Comment by SoftArea-srl** [comment]
I have the same issue described by @nevse 
The work around mentioned [here](https://github.com/xamarin/xamarin-macios/issues/17262#issuecomment-1384092802) does not work for me. Tested with real device iPhone 12 iOS 16.4.

**Comment by divil5000** [comment]
It is unbelievable that this isn't the highest-priority item on Microsoft's agenda right now. They are basically saying that localised apps cannot be built using the latest and greatest .net 6/7 for iOS. Localised apps includes all major international apps.

**Comment by marwalsch** [comment]
`System.Globalization.CultureInfo.DefaultThreadCurrentCulture` still doesn't work properly on .NET 8. Is this a separate issue?

**Comment by rolfbjarne** [comment]
@marwalsch yes, that's a separate issue. Please file it in the dotnet/runtime repository.
