### ISSUE TITLE
libc.dylib DllNotFoundException when building with macos workload on Linux

### ISSUE THREAD

**Issue by sandyarmstrong** [xamarin/xamarin-macios#17287]
### Steps to Reproduce

1. Build a simple `net6.0-macos10.15` library on Linux

### Expected Behavior

Build succeeds.

### Actual Behavior

Build fails with:

```
Xamarin.Shared.targets(1372,3): error MSB4018: The "FindItemWithLogicalName" task failed unexpectedly. [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
Xamarin.Shared.targets(1372,3): error MSB4018: System.DllNotFoundException: Unable to load shared library '/usr/lib/libc.dylib' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:  [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
Xamarin.Shared.targets(1372,3): error MSB4018: /opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App/7.0.0//usr/lib/libc.dylib: cannot open shared object file: No such file or directory [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
Xamarin.Shared.targets(1372,3): error MSB4018:  [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
Xamarin.Shared.targets(1372,3): error MSB4018:    at Xamarin.Utils.PathUtils.realpath(String path, IntPtr buffer) [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
Xamarin.Shared.targets(1372,3): error MSB4018:    at Xamarin.Utils.PathUtils.ResolveSymbolicLinks(String path) in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/PathUtils.cs:line 50 [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
Xamarin.Shared.targets(1372,3): error MSB4018:    at Xamarin.MacDev.BundleResource.GetVirtualProjectPath(String projectDir, ITaskItem item, Boolean isVSBuild) in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/BundleResource.cs:line 93 [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
Xamarin.Shared.targets(1372,3): error MSB4018:    at Xamarin.MacDev.BundleResource.GetLogicalName(String projectDir, IList`1 prefixes, ITaskItem item, Boolean isVSBuild) in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/BundleResource.cs:line 110 [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
Xamarin.Shared.targets(1372,3): error MSB4018:    at Xamarin.MacDev.Tasks.FindItemWithLogicalNameTaskBase.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/FindItemWithLogicalNameTaskBase.cs:line 39 [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
Xamarin.Shared.targets(1372,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
Xamarin.Shared.targets(1372,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/vsts/work/1/s/src/Xunit.StaFact/Xunit.StaFact.csproj::TargetFramework=net6.0-macos10.15]
```

### Environment

Ubuntu 20.04.5 via Azure DevOps pipeline
.NET 7.0.100
macOS workload 12.3.2372

### Build Logs

[build_logs-Linux.zip](https://github.com/xamarin/xamarin-macios/files/10452053/build_logs-Linux.zip)

### Example Project (If Possible)

* https://github.com/AArnott/Xunit.StaFact/pull/68
* https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=7629&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5494183b-801e-5084-3b4b-5451c6a14ee1

**Comment by rolfbjarne** [comment]
We don't support building on Linux, only macOS and Windows (and then only remotely, you still need a Mac).

That said, we should probably show a better error message, so I've filed #17289 to get that improved.

**Comment by sandyarmstrong** [comment]
@rolfbjarne last I checked, building macos _library_ projects worked fine on Windows without a Mac, so I was surprised it did not work on Linux. I'm not too concerned about Linux but I have a vested interest in being able to build macos library projects on Windows. Is that supported?

**Comment by rolfbjarne** [comment]
@sandyarmstrong yes, building macOS library projects should work on Windows I believe, since that's just a C# compilation. Note that _binding projects_ won't work, those need to do stuff on a Mac.

**Comment by AArnott** [comment]
> building macOS library projects should work on Windows I believe, since that's just a C# compilation. Note that binding projects won't work, those need to do stuff on a Mac.

@rolfbjarne Is that just expected to work on Windows then? Why couldn't Linux build a macos library project on the same basis (that it's just C# compilation)?

**Comment by rolfbjarne** [comment]
Actually wait, I see that the original issue is a library project too, I thought it was an executable project.

For library projects we've done some work to make sure their build don't fail on Windows when there's no connection to a Mac, even though that might result in an incomplete build.	However there might be some assumptions in our code base where we check for "windows" instead of "!mac". In any case Linux is not a priority for us at the moment (this is the first time anyone's ever mentioned building on Linux), so it's unlikely we'll prioritize this over other tasks we have, at least in the foreseeable future.

**Comment by AArnott** [comment]
Ok. Thanks for writing back. Sad news, but I understand priorities.

**Comment by AArnott** [comment]
Nice find. Given these property definitions respect an existing value for IsMacEnabled, maybe we can help test out the fix and workaround the bug at the same time by adding the updated definition to our own project that otherwise fails on linux. It seems the two lines could ultimately be replaced with just one, BTW:

```xml
 <IsMacEnabled Condition="'$(IsMacEnabled)' == ''">$([MSBuild]::IsOSPlatform('macOS'))</IsMacEnabled> 
```

**Comment by sandyarmstrong** [comment]
Good point, I'll give it a try.

**Comment by sandyarmstrong** [comment]
No such luck. If I have time I'll pull the binlog and poke around.

https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=7640&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5494183b-801e-5084-3b4b-5451c6a14ee1
