### ISSUE TITLE
Missing Xamarin.Mac.VB.Targets file (Win 11: dotnet publish to macOS from a .NET 6 Winforms app in VB.NET)

### ISSUE THREAD

**Issue by lepete11** [xamarin/xamarin-macios#17290]
### Steps to Reproduce

1. Use Win 11, VS 2022 Pro, .NET 6 Winform app developed in VB.NET
2. Publish to macOS
3. 
4. 

### Expected Behavior
A successful publish with no errors.

### Actual Behavior
It appears that in line 1840 of Xamarin.Shared.Sdk.targets, there is a "C#" in the logical statements (if-then), but not a "VB".   Thus, when using the DOS command: dotnet publish -c Release -r osx-x64 MyAppName.vbproj, it seems that this line is supposed to generate (?) another file called Xamarin.Mac.VB.targets, but without the "VB" parameter in the if-statement, this fails.  The error message provided in Details below indicates that the file was not found.  Also, there is a double "\\" in the error code.   I am wondering if this exception fell through the cracks only because no one who has tried to publish via .NET for the macOS based on a VB.NET Winforms app has reported it yet.

### Environment

<details>
<summary>Version information</summary>

```
C:\Program Files\dotnet\packs\Microsoft.macOS.Sdk\13.0.784\targets\Xamarin.Shared.Sdk.targets(1840,2): error MSB4019: T
he imported project "C:\Program Files\dotnet\packs\Microsoft.macOS.Sdk\13.0.784\tools\msbuild\macOS\Xamarin.Mac.VB.targ
ets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\packs\Microsoft.macO
S.Sdk\13.0.784\\tools\msbuild\macOS\Xamarin.Mac.VB.targets" is correct, and that the file exists on disk. [D:\Leifuse\V
BNet 2022\NXGLOGIC Explorer Desktop - .NET\Explorer\ExplorerWorkflow.vbproj]
```

</details>

**Comment by rolfbjarne** [comment]
Could you attach the project file (I don't think we need any source code) + a binary build log (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) so that we can diagnose this? Thanks!

**Comment by lepete11** [comment]
[MyProject.txt](https://github.com/xamarin/xamarin-macios/files/10459565/MyProject.txt)

Attached is the Project file.  Can't upload msbuild.binlog, since I don't know what's in it.  Project is not open source, strictly all IP with obfuscation.  Basically, from a design perspective of the Xamarin.Shared.Sdk.targets file, what is the answer to the question: Why is there a "C#" parameter in the if statement on line 1840, but not a "VB" parameter?  In theory, ask someone who knows that file, and I am sure they will reply "Yes, I would expect the same exception that the user received when compiling VB forms/files."  Instead, you're asking a lot about what the user is doing, instead of asking: why isn't there a "VB" parameter in the if-statement.  It's not the user/developer, it's the person who wrote that Xamarin.Shared.Sdk.targets file.

**Comment by rolfbjarne** [comment]
There are two issues in your project:

1. We don't support Visual Basic at the moment - but this might be fixed: https://github.com/xamarin/xamarin-macios/issues/17321.
2. The bigger issue is that Windows.Forms is not supported on macOS, it's a Windows-only part of .NET. If you want a cross-platform UI toolkit, you might want to have a look at MAUI: https://learn.microsoft.com/en-us/dotnet/maui/what-is-maui?view=net-maui-7.0

**Comment by lepete11** [comment]
Thanks for the rapid reply.  I will look at MAUI, as I have noticed that a lot in new features of .NET.  Thx!
