### ISSUE TITLE
MTKTextureLoaderOptions.GenerateMipMaps property lacks a setter

### ISSUE THREAD

**Issue by AndrewTriesToCode** [xamarin/xamarin-macios#17383]
### Steps to Reproduce

1.  Create a new Mac project.
2. Create an instance of `MTKTextureLoaderOptions` from the `MetalKit` namespace.
3. Observe that the `GenerateMipMaps` property has no setter.

### Expected Behavior
Expect to be able to set this property to have MetalKit automatically create mipmaps for me per [Metal docs](https://developer.apple.com/documentation/metalkit/mtktextureloader/option/1645867-generatemipmaps).

### Actual Behavior
Cannot set the property.

### Environment

IDE: Rider 2023.3.1
.NET SDK: 7.0.102

**Comment by rolfbjarne** [comment]
Thanks for the report! We'll fix this asap.

**Comment by rolfbjarne** [comment]
You can do something like this as a workaround:

```cs
var dict = new NSMutableDictionary();
var v = new MTKTextureLoaderOptions(dict);
var key = (NSString)"MTKTextureLoaderOptionGenerateMipmaps";
Console.WriteLine($"GenerateMipMaps: {v.GenerateMipmaps}");
dict[key] = NSNumber.FromBoolean(true);
Console.WriteLine($"GenerateMipMaps: {v.GenerateMipmaps}");
dict[key] = NSNumber.FromBoolean(false);
Console.WriteLine($"GenerateMipMaps: {v.GenerateMipmaps}");
dict.Remove (key);
Console.WriteLine($"GenerateMipMaps: {v.GenerateMipmaps}");
```

that prints this for me:

```
GenerateMipMaps:
GenerateMipMaps: True
GenerateMipMaps: False
GenerateMipMaps:
```

**Comment by AndrewTriesToCode** [comment]
Thanks!
