### ISSUE TITLE
[Question] Link.semaphor error (MSB3371) if pair to Mac from command line

### ISSUE THREAD

**Issue by JaneySprings** [xamarin/xamarin-macios#17393]
Hello. I'm trying to build a net 7.0-ios project on Windows via the command line. Following the [Microsoft documentation](https://learn.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/#build-ios-apps-from-the-windows-command-line) I added options:
```
-p:ServerAddress=XXXX -p:ServerUser=macmini -p:ServerPassword=XXXX
```
The '_SayHello' task was completed successfully, but the '_RunILLink' task returned an error:
```
C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.1.1481\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(373,3): error MSB3371: The file "obj 
\Debug\net7.0-ios\ios-arm64\linked\Link.semaphore" cannot be created. Could not find a part of the path 'c:\Users\romanov.nikita\Repos\MauiApp1\obj\Debug 
\net7.0-ios\ios-arm64\linked\Link.semaphore'. [c:\Users\romanov.nikita\Repos\MauiApp1\MauiApp1.csproj::TargetFramework=net7.0-ios]
```
This is because msbuild is trying to find the version of dotnet (7.0.200-preview), but on Mac only dotnet (7.0.102):
```
Could not execute because the specified command or file was not found.
  Possible reasons for this include:
    * You misspelled a built-in dotnet command.
    * You intended to execute a .NET program, but dotnet-/usr/local/share/dotnet/sdk/7.0.200-preview.22628.1/Sdks/Microsoft.NET.ILLink.Tasks/build/../too 
  ls/net7.0/illink.dll does not exist.
```

Can I specify the version of dotnet that msbuild will look for on Mac or should both devices have the same version of dotnet?

**Comment by rolfbjarne** [comment]
> Can I specify the version of dotnet that msbuild will look for on Mac or should both devices have the same version of dotnet?

When building remotely from Windows, we don't use the global version of .NET on the Mac, but instead a custom version that's installed here: `~/Library/Caches/Xamarin/XMA/SDKs/dotnet`. When building from the IDE, this version is automatically updated to the correct version based on the project you're building, but this does not happen when building from the command line, in which case you need to make sure yourself that the correct version of .NET is installed in that directory.

**Comment by rolfbjarne** [comment]
One easy workaround is to build the project first using Visual Studio, which will make sure the correct version of .NET is installed in that directory.

If you still have problems afterwards, please attach a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) from the command line build.
