### ISSUE TITLE
Matter and MatterSupport Framework Bindings Missing

### ISSUE THREAD

**Issue by dwightbennett** [xamarin/xamarin-macios#17475]
### Steps to Reproduce

1. Install latest Xamarin iOS 16.2 and VS for mac 17.4.4.12
2. Attempt to Reference Matter or MatterSupport with using statements

### Expected Behavior
I should be able to use the Matter and MatterSupport Sdks. 
### Actual Behavior
Framework is missing
### Environment
Visual Studio For Mac version 17.4.4.12 
Xamarin iOS 16.2

### Question
Is there a plan to do bindings for Matter and MatterSupport? The frameworks were added as apple sdks in xcode in 16.1.  What would be the lift to bind these frameworks with something like sharpie and a bindings library? Thank you for any information you can provide on this.

**Comment by dalexsoto** [comment]
Hello thanks for reaching out!

As of today we have no plans to bind Matter or MatterSupport frameworks until after Xcode 15 release, if you look at the history this framework, it was previously known as CHIP.Framework and it had breaking changes on every release which made it really hard to bind without breaking compatibility, then Apple decided to rename it entirely into Matter (huge breaking change) so we want to wait for Apple to actually stabilize Matter before us providing a wrapper for it.

What you could do today is create a binding project using Visual Studio and **only bind** the APIs that you need manually. Take the work we did for [ExposureNotification](https://github.com/xamarin/XamarinComponents/tree/main/iOS/ExposureNotification/source) as an example, you can only bind the objects and methods you need from Matter and Matter support the same way. Also if you are new to bindings I would encourage you to read our [bindings documentation](https://github.com/xamarin/xamarin-macios/blob/main/docs/website/binding_objc_libs.md#binding-objective-c-libraries). Hope this helps.
