### ISSUE TITLE
Adding a Native iOS Library to a MAUI Project and use in a MAUI App Project

### ISSUE THREAD

**Issue by ertan2002** [xamarin/xamarin-macios#17527]
The problem is that when I add an a native library into a maui class library project, I cannot use it in my maui app project.

### Steps to Reproduce

1. Create a .NET MAUI Class Library Project
2. Delete all platforms except ios
3.  Add a native ios library (an a  file) to this project.  (optional: you can also set this file as BindingNativeLibrary)
		<ObjcBindingNativeLibrary Include="libAreteUart\a" />
5. Use Register attribuate in your export class. (I shared a sample code piece below and also a test Project)
6. Compile the project
7. Create a .NET MAUI App
8. Delete all platforms except iOS
9. Add your maui class library as a project reference
10. Try to build the app project 

### Expected Behavior
I expect that the app proje compile and run.

### Environment
I have a build error

`/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1007/targets/Xamarin.Shared.Sdk.targets(3,3): 
Error: clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ComboBarcodeApi", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_ComboNFCApi", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_ComboRFIDApi", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_CommonDevice", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_CommonReaderInfo", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_RcpApi", referenced from:
      objc-class-ref in registrar.o
  "_OBJC_CLASS_$_SDeviceApi", referenced from:
      objc-class-ref in registrar.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation) (TestMauiApp)
`

Information

Visual Studio Professional 2022 for Mac
Version 17.4.3 (build 21)
Installation UUID: aeb37331-c54e-472e-81b7-870439f80c4c

Runtime
.NET 6.0.12 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.4.0-6.22578.12+3c6ab8e1715e5b080fb7bb77070810ab71e09387

NuGet
Version: 6.3.1.1

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.102/Sdks
SDK Versions:
	7.0.102
	6.0.405
	6.0.400
	3.1.426
	3.1.422
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.2
	6.0.13
	6.0.8
	3.1.32
	3.1.28

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 14.2 (21534)
Build 14C18

Xamarin.Mac
Version: 9.0.0.27 (Visual Studio Professional)
Hash: 933c6c2c9
Branch: xcode14.1
Build date: 2022-11-22 02:00:36-0500

Xamarin.iOS
Version: 16.1.1.27 (Visual Studio Professional)
Hash: 933c6c2c9
Branch: xcode14.1
Build date: 2022-11-22 02:00:37-0500

Xamarin.Android
Version: 13.1.0.1 (Visual Studio Professional)
Commit: xamarin-android/d17-4/13ba222
Android SDK: /Users/erda/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		12.0 (API level 30)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: a96bde9
Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
SQLite: xamarin/sqlite/3.39.3@23e1ae7
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2023-01-12 19:21:16 UTC

Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2023-01-12 19:21:16 UTC

Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2023-01-12 19:21:10 UTC

Build Information
Release ID: 1704030021
Git revision: 26eac6764d85f12fe50ee0d45a7cd0b266be7b23
Build date: 2023-01-12 19:19:02+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:17:10 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

A code sample that makes problem
`
```
	[Register("ComboBarcodeApi", true)]
	public class ComboBarcodeApi : SDeviceApi
	{
		// Token: 0x17000001 RID: 1
		// (get) Token: 0x06000059 RID: 89 RVA: 0x0000206E File Offset: 0x0000026E
		public override NativeHandle ClassHandle
		{
			get
			{
				return ComboBarcodeApi.class_ptr;
			}
		}
             .....
          }
````

### Example Project (If Possible)
I added a sample project that you can try to build. There is no extra code in the maui app project from the library. Even though I cannot build the project.

[TestApp.zip](https://github.com/xamarin/xamarin-macios/files/10726082/TestApp.zip)

**Comment by rolfbjarne** [comment]
You need to add the `IsBindingProject` property to indicate that a project is a binding project:

```diff
 $ git diff
diff --git a/ComboSDKMaui/ComboSDKMaui.csproj b/ComboSDKMaui/ComboSDKMaui.csproj
index ea14043..08e9ac7 100644
--- a/ComboSDKMaui/ComboSDKMaui.csproj
+++ b/ComboSDKMaui/ComboSDKMaui.csproj
@@ -5,6 +5,7 @@
                <UseMaui>true</UseMaui>
                <SingleProject>true</SingleProject>
                <ImplicitUsings>enable</ImplicitUsings>
+               <IsBindingProject>true</IsBindingProject>

                <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
        </PropertyGroup>
```

And then you need to add an api definition file that describes the API in your native library. This process is described here:
https://learn.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-c-libraries?context=xamarin%2Fios&tabs=windows

**Comment by ertan2002** [comment]
@rolfbjarne thank you for your reply.

If you look at the project, there is already an API definition.

I also see that one project of the manufacturer, has an api definition which they use BaseType, Static etc attributes.

But I cannot find these attributes in MAUI. 

The documentation that you provide, also uses these Xamarin attributes. How can I use them in MAUI? Because Foundation namespace does not have those attributes.

**Comment by rolfbjarne** [comment]
> But I cannot find these attributes in MAUI.

These attributes are only used in binding projects, to compile the api definition, which is then used to generate the actual binding code.

You need to create a file called `ApiDefinition.cs` in your binding project, and add the api definition there. In that case, you can use these attributes in that file.

**Comment by ertan2002** [comment]
> > But I cannot find these attributes in MAUI.
> 
> These attributes are only used in binding projects, to compile the api definition, which is then used to generate the actual binding code.
> 
> You need to create a file called `ApiDefinition.cs` in your binding project, and add the api definition there. In that case, you can use these attributes in that file.

I ceated an ApiDefinition.cs and even I created a xamarin binding library and copied from there etc but still BaseType does not exist.

Is there any native binding example that is in a MAUI Class library? Then I can build my code upon it.

**Comment by rolfbjarne** [comment]
You can do `dotnet new iosbinding` to create a new binding project from a template, and start from there.

Note that intellisense doesn't quite work for binding projects, so make sure to build your project to test for any build problems.

**Comment by ertan2002** [comment]
> 

Ok I'll try it. I think, it will create a xamarin based project and probably will not work with MAUI but I'll test it.

thank you
