### ISSUE TITLE
Custom Forms renderer in class library breaks on device in RELEASE after adding more outlets to other files in the same project

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/xamarin-macios#17592]
This issue was triggered by Xamarin Forms, but I don’t _think_ it is a Forms specific issue.

We have a Xamarin iOS app primarily not using Xamarin Forms, but embedding Xamarin Forms in various views. We are using 5.0.0.2478. There is an iOS app project and an iOS class library project in the same solution.

In the class library we created a custom renderer. During development everything was fine. RELEASE builds on a physical device however just showed a blank space where the renderer should be.

After some investigation we discovered if we called `Platform.CreateRenderer` on the Forms element we were getting `DefaultViewRenderer` instead of our custom renderer. Manually invoking the constructor of the custom renderer worked.

We then went through history to find out when it was introduced and it was on a commit changing something unrelated - an iOS designer view in which some outlets were added. Removing those outlets fixed it.

After some more fiddling, removing any outlets seemed to fix it. Removing outlets from the app project, or from other projects did not fix it. For reference, the app worked with 72 outlets in the class library project and failed with 83 outlets. There are hundreds of outlets in the app project.

For reference, the custom renderer also includes a .xib and a designer file with outlets.

So far I’ve been unable to create a smaller reproduction, so my main request is how we can further diagnose the problem, or if you know of any limitations regarding outlet count in class libraries.

### Steps to Reproduce

1. Create an iOS solution with an iOS class library referenced by the app project
2. Add lots of outlets to the class library
3. Add a Xamarin Forms custom renderer to the library

### Expected Behavior

The renderer works.

### Actual Behavior

The renderer does not work (`Platform.CreateRenderer` returns `DefaultViewRenderer`).

### Environment

Xamarin.iOS 15.10 / Xamarin.iOS 15.12
Xamarin Forms 5.0.0.2478

**Comment by rolfbjarne** [comment]
This sounds like something that related to the linker.

Is the linker configured differently in the Release configuration (you can look at the `MtouchLink` property in the csproj)?

**Comment by GalaxiaGuy** [comment]
That was our first thought too. We tried with the linker disabled and saw no difference.

Additionally, the time we tried constructing the renderer manually (which worked and so was not linked away) we still had the code to call Platform.CreateRenderer and it was still returning DefaultViewRenderer.

**Comment by rolfbjarne** [comment]
> That was our first thought too. We tried with the linker disabled and saw no difference.
> 
> Additionally, the time we tried constructing the renderer manually (which worked and so was not linked away) we still had the code to call Platform.CreateRenderer and it was still returning DefaultViewRenderer.

That's quite weird. Would it be possible to get access to your project so that we can reproduce it ourselves?

**Comment by GalaxiaGuy** [comment]
That should be possible. It will take me a little time to organise.
