### ISSUE TITLE
[templates] Add comments to help developers 

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#17591]
It can be difficult to get everything correctly aligned for publishing, so we might want to add comments to templates to show developers what they need to do depending on what they want to do.

A list of problems for Mac Catalyst are described here: https://github.com/dotnet/maui/issues/12293

* [ ] App rejected because: `The product archive package's signature is invalid. Ensure that it is signed with your "3rd Party Mac Developer Installer" certificate.` A commented section in csproj explaining what they need to do might help here.
* [ ] App rejected because: `The product archive is invalid. The Info.plist must contain a LSApplicationCategoryType key, whose value is the UTI for a valid category. For more details, see "Submitting your Mac apps to the App Store".` A commented section in the Info.plist might be helpful.
* [ ] App rejected because: `Invalid bundle. The bundle supports arm64 but not Intel-based Mac computers. Your build must include the x86_64 architecture to support Intel-based Mac computers.` A commented section in csproj explaining that if only x64 or arm64+x64 (but not just arm64) is valid for publishing would help.
* [ ] App rejected because: `Invalid Bundle. The key UIDeviceFamily in the app's Info.plist file contains one or more unsupported values '1'. We should probably validate this at build time.
* [ ] App rejected because: `App sandbox not enabled. The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list [...]`. A commented section in the Entitlements.plist might be helpful. Alternatively we could default to include this entitlement by default for release builds (but verify that we don't end up with builds that won't execute locally).
* [ ] "I had to add <key>ITSAppUsesNonExemptEncryption</key><false/> to Info.plist." A commented section in the Info.plist might be helpful.

**Comment by UrbanSowaLabs** [comment]
Another comment that would help developers when publishing MAUI Blazor: `com.apple.security.network.client`

Details are here: https://github.com/dotnet/maui/issues/13094
