### ISSUE TITLE
Pass linker flag to set __THUNKS permission for NativeAOT

### ISSUE THREAD

**Issue by akoeplinger** [xamarin/xamarin-macios#17629]
https://github.com/dotnet/runtime/pull/82317 implemented marshalled delegate support for NativeAOT via generating thunk pages.
We need the `-Wl,-segprot,__THUNKS,rx,rx` linker flag to set the correct permissions on the segment.

Note: depending on how we'll integrate the NativeAOT targets into xamarin-macios this might be automatically handled, filing this just so we don't forget it if we don't use the NativeAOT targets.

**Comment by rolfbjarne** [comment]
@akoeplinger I believe we don't need to do anything here, the logic to pass these linker flags was implemented in dotnet/runtime here: https://github.com/dotnet/runtime/commit/75a32b8561cb2c2e9a5e1aebaf28c36ce20d2315

**Comment by filipnavara** [comment]
Yep, we can close this. As long as the linker flags are inherited from the NativeAOT logic we should be fine.
