### ISSUE TITLE
Binding project: show an error if NoBindingEmbedding=false and trying to bind an xcframework

### ISSUE THREAD

**Issue by dodikk** [xamarin/xamarin-macios#17700]
### Steps to Reproduce

1. Download the sample project https://github.com/dodikk/themis-maui-prototype
2. Build the ThemisMauiSample.sln which includes native iOS bindings created from the `xcframework`

### Expected Behavior
The build succeeds.

### Actual Behavior
The build fails with `Undefined symbols for architecture arm64`

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac Preview
Version 17.6 Preview (17.6 build 402)
Installation UUID: d6a788ca-554a-4551-8917-6d245de44b3d

Runtime
.NET 7.0.1 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.200/Sdks
SDK Versions:
	7.0.200
	7.0.103
	7.0.100
	6.0.406
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	3.1.426
	3.1.425
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.3
	6.0.14
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	3.1.32
	3.1.31
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.0.6 (Visual Studio Community)
Commit: xamarin-android/d17-5/a200af1
Android SDK: /Users/dodd/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		8.1  (API level 27)
		5.0  (API level 21)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 32.1.0 rc1

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.7
Hash: 466abb5
Branch: remotes/origin/main~1
Build date: 2023-02-13 22:38:42 UTC

Android Device Manager
Version: 0.0.0.1246
Hash: 0dd943a
Branch: main~1
Build date: 2023-02-13 22:38:42 UTC

Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

Xamarin.Mac
Version: 9.1.0.2 Visual Studio Community
Hash: 956a059ba
Branch: xcode14.2
Build date: 2022-12-15 06:15:43-0500

Xamarin.iOS
Version: 16.2.0.2 Visual Studio Community
Hash: 956a059ba
Branch: xcode14.2
Build date: 2022-12-15 06:15:44-0500

Xamarin Designer
Version: 17.6.0.17
Hash: 0180199186
Branch: remotes/origin/main
Build date: 2023-02-13 22:38:37 UTC

Build Information
Release ID: 1706000402
Git revision: b0c291c78f94c725a2270217416e45dc810f5b26
Build date: 2023-02-13 22:36:42+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.1.0
Darwin 22.2.0 Darwin Kernel Version 22.2.0
    Fri Nov 11 02:03:51 PST 2022
    root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/10885530/msbuild.binlog.zip)

### Example Project (If Possible)

https://github.com/dodikk/themis-maui-prototype

**Comment by rolfbjarne** [comment]
The fix is to remove the line enabling embedded binding https://github.com/dodikk/themis-maui-prototype/blob/78b0426acd05c66b127f58ac0b4e13d71254008f/lib-bindings/themis-maui/Themis.Maui.iOS/Themis.Maui.iOS.csproj#L8:

```diff
diff --git a/lib-bindings/themis-maui/Themis.Maui.iOS/Themis.Maui.iOS.csproj b/lib-bindings/themis-maui/Themis.Maui.iOS/Themis.Maui.iOS.csproj
index 6dd8d6f..20f9b53 100644
--- a/lib-bindings/themis-maui/Themis.Maui.iOS/Themis.Maui.iOS.csproj
+++ b/lib-bindings/themis-maui/Themis.Maui.iOS/Themis.Maui.iOS.csproj
@@ -5,7 +5,6 @@
     <ImplicitUsings>true</ImplicitUsings>
     <IsBindingProject>true</IsBindingProject>
     <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
-    <NoBindingEmbedding>false</NoBindingEmbedding>
   </PropertyGroup>

   <ItemGroup>
```

**Comment by rolfbjarne** [comment]
I'm keeping this open, since we should show an error when trying to embed an xcframework like this (i.e. for a binding project binding xcframeworks and NoBindingEmbedding=false), because it won't work later when consuming the binding project.

**Comment by dodikk** [comment]
@rolfbjarne thanks for fast reply. I've tried your fix but now I am getting a build error like this:

```
Getting restore information for project /Users/dodd/projects/work/cps/themis/themis-maui-prototype/lib-bindings/themis-maui/themis.ios.wrapper.maui/themis.ios.wrapper.maui.csproj
/usr/local/share/dotnet/sdk/7.0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(112,5) : error NETSDK1139: The target platform identifier ios was not recognized.
/usr/local/share/dotnet/sdk/7.0.200/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(112,5) : error NETSDK1139: The target platform identifier ios was not recognized.
Unable to create package spec for project. '/Users/dodd/projects/work/cps/themis/themis-maui-prototype/lib-bindings/themis-maui/themis.ios.wrapper.maui/themis.ios.wrapper.maui.csproj'
```

**Comment by dodikk** [comment]
@rolfbjarne here we go:
[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/10911686/msbuild.binlog.zip)

A bit more info:
* I've tried to re-install the VisualStudio but the error still reproduces. 
* Even MAUI template hello-world project fails to build actually.

**Comment by dodikk** [comment]
So I've solved the `platform identifier not recognized` by uninstalling `all .net runtimes` using  https://github.com/dotnet/cli-lab/releases

**Comment by dodikk** [comment]
* Good news: Now the app builds
* Bad news: but it fails to run and debug on ios simulator

```
xcrun simctl launch --stdout=/dev/ttys003 --stderr=/dev/ttys004 --terminate-running-process AD1BE2BE-E77A-4E93-BAC4-C8FC0BA5B364 <bundle id of my app> -monodevelop-port 10000
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Application launch for <bundle id of my app> did not return a valid pid nor a launch error.
No such process
error HE0042: Could not launch the app <bundle id of my app> on the device 'iOS 16.2 (20C52) - iPhone SE (3rd generation)': simctl returned exit code 3
```
These are the visual studio's `Application Output`. 

When tapping the app icon on the simulator - it fails to start. Seems to be crashing (but I am unable to get the logs).
@rolfbjarne any ideas please?

**Comment by rolfbjarne** [comment]
@dodikk are there any crash reports in `~/Library/Logs/DiagnosticReports`?

Also what happens if you execute that command in a terminal yourself:

```
xcrun simctl launch --stdout=/dev/ttys003 --stderr=/dev/ttys004 AD1BE2BE-E77A-4E93-BAC4-C8FC0BA5B364 <bundle id of my app>
```

**Comment by dodikk** [comment]
@rolfbjarne ok I've done the factory reset and here are the answers:


> are there any crash reports in ~/Library/Logs/DiagnosticReports

No, it is empty.
```
✗ ls -a1 ~/Library/Logs/DiagnosticReports
.
..

```


> Also what happens if you execute that command in a terminal yourself:

No idea why but the `No such process` error happens. See the details below:
P.S. The HelloWorld maui template app without native bindings runs ok on the ios simulator.

```
✗ xcrun simctl launch --stdout=/dev/ttys001 --stderr=/dev/ttys002 --terminate-running-process A8855736-898A-4341-AA9B-4248A5EFF56B net.coinpayments.orion.mobile -monodevelop-port 10000
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Application launch for 'net.coinpayments.orion.mobile' did not return a valid pid nor a launch error.
No such process
```

**Comment by dodikk** [comment]
@rolfbjarne [UPD]: the native lib works both on `real iPad` (not simulator) and on `Android`. **iOS simulator crashes on start**. Probably the desktop `arm64` slice has failed to link properly. However, I am unable to find any diagnostics to proof that guess.

**Comment by dodikk** [comment]
@rolfbjarne it does not

```
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Application launch for 'net.coinpayments.orion.mobile' did not return a valid pid nor a launch error.
No such process
```

**Comment by rolfbjarne** [comment]
Did you make any other changes to the test project than the one I suggested (https://github.com/xamarin/xamarin-macios/issues/17700#issuecomment-1457074399)?

**Comment by dodikk** [comment]
> Did you make any other changes to the test project than the one I suggested (https://github.com/xamarin/xamarin-macios/issues/17700#issuecomment-1457074399)?

@rolfbjarne no other changes

**Comment by rolfbjarne** [comment]
This is rather puzzling. Can you launch any other project in the simulator from VSMac (say if you create a new project from a template)?

**Comment by dodikk** [comment]
> Can you launch any other project in the simulator from VSMac (say if you create a new project from a template)?

@rolfbjarne as I have already mentioned, `yes I can`. The template runs ok on the iOS simulator.

**Comment by dodikk** [comment]
> This is rather puzzling.

Indeed it is.
My guess is that simulator's `arm64` "slice" has failed to link properly despite being part of `themis.xcframework`. As long as that framework has arm64 binaries for MacOS desktop and for iOS devices (real ones) I am suspecting some kind of a collision. 
But again, I am unable to collect any diagnostics or logs to prove it yet as I do not know "where else to look".

**Comment by rolfbjarne** [comment]
> > This is rather puzzling.
> 
> Indeed it is. My guess is that simulator's `arm64` "slice" has failed to link properly despite being part of `themis.xcframework`. As long as that framework has arm64 binaries for MacOS desktop and for iOS devices (real ones) I am suspecting some kind of a collision. But again, I am unable to collect any diagnostics or logs to prove it yet as I do not know "where else to look".

You should get a crash report if that were the case :/

Can you try adding this to ThemisMauiSample.csproj:

```xml
<PropertyGroup>
    <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
</PropertyGroup>
```

and see if that changes something?

**Comment by dodikk** [comment]
@rolfbjarne it does helps.

Actually I already had this in my `ThemisMauiSample.csproj`.  Which had been added when native bindings were failing to build and link. Once removed - the build started to work both on the device and the simulator
```
<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
        <RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
</PropertyGroup>
```

**Comment by dodikk** [comment]
So the fix was
1. remove the `<NoBindingEmbedding>false</NoBindingEmbedding>` from `Themis.Maui.iOS.csproj`
2. remove (do not add rather) the `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` to the `ThemisMauiSample.csproj`

@rolfbjarne I am closing the issue. Thanks for troubleshooting.
