### ISSUE TITLE
"System.ExecutionEngineException: Attempting to JIT compile method" with .Net7 but not with Xamarin.iOS

### ISSUE THREAD

**Issue by joduss** [xamarin/xamarin-macios#17758]
### Steps to Reproduce

1. Create 2 projects: one .Net7-iOS project and another Xamarin.iOS using Visual Studio for Mac.
2. Add the Dynamic Data (7.13.1) nuget package.
3. Create a class implementing `INotifyPropertyChanged` having 1 virtual property.
4. In another class, create an instance of that class and observe changes using `WhenValueChanged(observed_object => observed_object.observed_property)`. See below for full code example.
5. Run the app on an iOS device.

```csharp
public class MyController : UIViewController
{
	public override void ViewDidLoad()
	{
		View = new UIView
		{
			BackgroundColor = UIColor.Red,
		};

		base.ViewDidLoad();

		DataClass d = new DataClass();
		var obs = d.WhenValueChanged(obj => obj.Value).Subscribe(); # Exception thrown here

		Console.WriteLine(obs);
		// Perform any additional setup after loading the view
	}
}

public class DataClass : INotifyPropertyChanged
{
	public event PropertyChangedEventHandler? PropertyChanged;

	// public int Value { get; set; } // All Good
	public virtual int Value { get; set; } // Crashes.
}
```

### Expected Behavior

Both applications should work no matter if using Xamarin.iOS or .Net 7 for iOS.

### Actual Behavior

The .Net 7 iOS application crashes at `d.WhenValueChanged(obj => obj.Value)` due to the exception

```
System.ExecutionEngineException has been thrown
Attempting to JIT compile method '(wrapper delegate-invoke) int <Module>:invoke_callvirt_int_DataClass (JitProject.DataClass)' while running in aot-only mode.
```

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.5.1 (build 23)
Installation UUID: 7a0af782-4ca9-4fd3-bd17-3d88c485a7e9

Runtime
.NET 7.0.1 (64-bit)
Architecture: X64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.201/Sdks
SDK Versions:
	7.0.201
	7.0.200
	7.0.103
	7.0.102
	7.0.101
	7.0.100
	7.0.406
	6.0.405
	6.0.404
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
	6.0.200
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	3.1.426
	3.1.425
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	2.1.818
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	8.0.3
	7.0.2
	7.0.1
	7.0.0
	6.0.14
	6.0.13
	6.0.12
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5
	6.0.2
	6.0.0-preview.5.21301.5
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.32
	3.1.31
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	2.1.30
	2.1.23
	2.1.22

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.33
Hash: f0c0c52
Branch: remotes/origin/d17-5~2
Build date: 2023-03-02 06:08:31 UTC

Android Device Manager
Version: 0.0.0.1245
Hash: 7f8a990
Branch: 7f8a990
Build date: 2023-03-02 06:08:31 UTC

Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

Xamarin.Mac
Version: 9.1.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:14-0500

Xamarin.iOS
Version: 16.2.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:15-0500

Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 2023-03-02 06:08:27 UTC

Build Information
Release ID: 1705010023
Git revision: 4ea4e8aba0157d7f608399614482546551c0ee08
Build date: 2023-03-02 06:06:42+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 13.2.0
Darwin 22.3.0 Darwin Kernel Version 22.3.0
    Thu Jan  5 20:53:49 PST 2023
    root:xnu-8792.81.2~2/RELEASE_X86_64 x86_64
```

</details>

### Build Logs
[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/10933111/msbuild.binlog.zip)

### Example Project (If Possible)

[Reproduction Projects.zip](https://github.com/xamarin/xamarin-macios/files/10933072/Reproduction.Projects.zip)

**Comment by joduss** [comment]
> Your sample works if you enable the interpreter:
> 
> ```
> <PropertyGroup>
>     <UseInterpreter>true</UseInterpreter>
> </PropertyGroup>
> ```
> 
> Could you confirm if that works for you as well?

I confirm this works for me, at the cost of a major slow down of the application. It is 60-80% slower with the interpreter and impacts the user experience. 

I have in the meantime found a possible solution to enable the interpreter only for the System.Linq.Expression assembly, which has a much lower impact on the performance :

```
<MtouchInterpreter>-all,System.Linq.Expressions</MtouchInterpreter>
```

Could you tell me if this is a solution that is officially supported?


Generally, I see that in the .Net 7 iOS app, there are many more System.* dll's compared to a Xamarin app. Notably, there is System.Linq.Expression in the .Net 7 iOS app which was not in the Xamarin app. Which results in an app that is 25% larger.

**Comment by rolfbjarne** [comment]
> Could you tell me if this is a solution that is officially supported?

Yes, this is supported.

> Generally, I see that in the .Net 7 iOS app, there are many more System.* dll's compared to a Xamarin app. Notably, there is System.Linq.Expression in the .Net 7 iOS app which was not in the Xamarin app. Which results in an app that is 25% larger.

Size measurements are very specific to each project (a side effect of the linker removing unused code is that it can go the opposite way: a single line of code can bring in a lot of dependencies and increase the app size significantly), so in order for us to have a look at any size differences, we'll need access to a complete project we can use to reproduce the app size (preferably a before and an after version). Also please report this in a new issue, so that things don't get confusing here.

**Comment by joduss** [comment]
As you can see, both projects have a simple code and the xamarin one compiles without issue and the .Net 7 doesn't work without trick (that still slows down the app by ~10%).

So what did change between Xamarin.iOS and .Net 7? Why is such a performance costing trick suddenly needed and was not necessary before?

If I inspect the compiled app, I see that the .Net7-ios  app has a System.Linq.Expression.dll but the Xamarin.iOS does not.
But in the Xamarin.iOS, there is a System.dll much larger than in the .Net7 app. In both case, neither have .aotdata.arm64 file, so are interpreted. Is it possible that the Xamarin System.dll contains actually the Linq library etc?

I'm trying to understand the difference and the reason for the need to use MtouchInterpreter in .Net7.

**Comment by rolfbjarne** [comment]
> As you can see, both projects have a simple code and the xamarin one compiles without issue and the .Net 7 doesn't work without trick (that still slows down the app by ~10%).
> 
> So what did change between Xamarin.iOS and .Net 7? Why is such a performance costing trick suddenly needed and was not necessary before?
> 
> If I inspect the compiled app, I see that the .Net7-ios app has a System.Linq.Expression.dll but the Xamarin.iOS does not. But in the Xamarin.iOS, there is a System.dll much larger than in the .Net7 app. In both case, neither have .aotdata.arm64 file, so are interpreted. Is it possible that the Xamarin System.dll contains actually the Linq library etc?
> 
> I'm trying to understand the difference and the reason for the need to use MtouchInterpreter in .Net7.

These are all questions for the https://github.com/dotnet/runtime repository - I can move this issue there if you want, or you can file a new issue.

**Comment by joduss** [comment]
I'll fill a new issue in the dotnet runtime repo.
