### ISSUE TITLE
.Net 7 Maui canvas.DrawImage from originally CVPixelBuffer is not visible

### ISSUE THREAD

**Issue by DiebBlue** [xamarin/xamarin-macios#17839]
Hello,
I would like to display a picture that I took with the iPhone camera. The image comes as a CVPixelBuffer (CVPixelFormatType.CV32BGRA) and I convert that to a Microsoft.Maui.Graphics.IImage so that I can write it to the canvas.
Everything goes through without error, but the image is not visible on the ContentPage.
Images loaded from the resource using `UIImage.FromResource(assembly,...)` work fine. The CVPixelBuffer also seems to be ok, because some image processing operations are performed on it, which give correct results. Does anyone have an idea what could be the reason for this?

Here is a debug information about the apparently good CVPixelBuffer included in the Microsoft.Maui.Graphics.PlatformImage image just before drawing to the canvas.
![grafik](https://user-images.githubusercontent.com/33460604/226031946-0b4a13b7-d17a-4c2f-92f6-ea0a268187b1.png)

### Steps to Reproduce

1. make a Microsoft.Maui.Graphics.Platform.PlatformImage from a CVPixelBuffer 

```
// the CVPixelBuffer cvPixelBuffer comes from a captured image
CIImage cIImage = new CIImage(cvPixelBuffer);
var uIImage = UIImage.FromImage(cIImage);
var image = new Microsoft.Maui.Graphics.Platform.PlatformImage(uIImage);
```

2. Draw the Microsoft.Maui.Graphics.IImage to a canvas in a  IDrawable-Class
```
public void Draw(ICanvas canvas, RectF dirtyRect)
{
    var image = GetImage();
    if (image != null)
    {
     canvas.DrawImage(image, 0, 0, image.Width, image.Height);
    }
}
```

### Expected Behavior
the image will be drawn at the canvas

### Actual Behavior
nothing is visible on the page

### Environment
Microsoft Visual Studio Community 2022 (64-Bit) - Current Version 17.5.2
Xamarin.iOS and Xamarin.Mac SDK 16.2.0.5
.Net 7

**Comment by rolfbjarne** [comment]
If you save the image to disk, do you get a file with the correct image data? In any case, we'll need a test project in order to look into this.

**Comment by DiebBlue** [comment]
@rolfbjarne Thanks for your suggestion to try to save the image to disc. When saving the image, there is an error that the operation could not be completed. It seems that the problem lies elsewhere. I think the topic can be closed.
