### ISSUE TITLE
Use the app container's icudt.dat file in app extensions

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#17877]
The icudt.dat file is copied to all app extensions as well as the app container.

This is rather useless, we only need one copy, and we can use the one in the app container.

This should save ~1.9mb per app extension.

**Comment by rolfbjarne** [comment]
@akoeplinger were you looking at hardcoding the path to the icudt.dt file for NativeAOT? Once we fix this issue, the icudt.dt file might not be inside the app bundle anymore for app extensions (we'll still know the path to the icudt.dat file, relative to the root of the app bundle, at build time).

**Comment by akoeplinger** [comment]
Right now we use this fallback path if the `ICU_DAT_FILE_PATH` AppContext key isn't set:

https://github.com/dotnet/runtime/blob/e56db76481726cc451b8fcf499500f9f3218de63/src/native/libs/System.Globalization.Native/pal_locale.m#L32

I think we could easily modify this to always pass in a path via that key and just assume it is relative to the bundle root.

**Comment by akoeplinger** [comment]
The runtime change to support a relative ICU_DAT_FILE_PATH was merged and will show up in 8.0-preview6

**Comment by akoeplinger** [comment]
.NET 9 uses "hybrid globalization" which doesn't rely on bundling ICU with the app anymore so this should no longer be needed going forward.

**Comment by rolfbjarne** [comment]
Closing as per last comment.
