### ISSUE TITLE
Split up dotnet tests

### ISSUE THREAD

**Issue by haritha-mohan** [xamarin/xamarin-macios#17882]
Currently, the dotnet tests in the CI take ~4 hours to run. When debugging and testing changes, this slows down our workflow significantly. So, split the dotnet tests into more manageable categories to improve efficiency and ease- similar to how other test categories in the CI run.

Inspired by #17840

**Comment by rolfbjarne** [comment]
We've split the .NET tests into 5 per-platform runs, so this is done.
