### ISSUE TITLE
error HE0042: Could not launch the app 'com.xxx.xxx' on the device 'iOS 14.4 (18D46) - iPhone 12 mini'

### ISSUE THREAD

**Issue by mknotzer** [xamarin/xamarin-macios#17897]
I installed in addition to VS 2019 parallel VS 2022 on my MacBook

VS 2019: 8.10.25 (build 2)
VS 2022: 17.5 (build 1802)
MacOS: 10.15.7
XCode: 12.4
Xamarin.iOS: 14.14.2.5

VS 2019 still works fine, VS 2022 starts the simulator but debugging fails (but works with old iPhone)

**Comment by mknotzer** [comment]
For several reasons I have to stick to Catalina (and I am not the only one). Why is SV 2022 not backward compatible?

**Comment by mknotzer** [comment]
Visual Studio 2019 still works like charm! Which means that working code was removed for no reasons. Why did you guys invested resources into removing existing code and features? Please put the 2019 code back into 2022. This should be an easy and quick task. Thanks.

**Comment by dalexsoto** [comment]
> Visual Studio 2019 still works like charm! Which means that working code was removed for no reasons. Why did you guys invested resources into removing existing code and features? Please put the 2019 code back into 2022. This should be an easy and quick task. Thanks.

Unfortunately is not as easy as it sounds, VS 2022 is a complete native macOS App rewrite, if you have feedback to the VSMac team I would advise filling it via the IDE's help menu https://learn.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2022#how-to-report-a-problem

**Comment by mknotzer** [comment]
Thanks for the info, I reported this issue right now via the VS menu :-)
