### ISSUE TITLE
Why doesn't WKWebView have a method to receive messages from the Web?

### ISSUE THREAD

**Issue by SF-Simon** [xamarin/xamarin-macios#17960]
Apple API: https://developer.apple.com/documentation/webkit/wkscriptmessagehandler

For example, a Web Editor notifies the client to save data and pass the current content.
Without this delegation, we cannot complete this process. 
Even, it makes it impossible for us to know what messages the web has sent.

**Comment by Sam-IExpress** [comment]
You can use `WebConfig.UserContentController.AddScriptMessageHandler`

**Comment by rolfbjarne** [comment]
@SF-Simon: we've bound the `WKScriptMessageHandler` protocol in C# (https://learn.microsoft.com/es-es/dotnet/api/webkit.wkscriptmessagehandler?view=xamarin-mac-sdk-14), so I'm unsure what you need. Can you explain a bit more, please?
