### ISSUE TITLE
Generic Simulator option

### ISSUE THREAD

**Issue by jmartienzCobec** [xamarin/xamarin-macios#18004]
Hello, I work on a Xamarin.IOS project and after recently updating VS for Mac 2022 and Xcode and MacOS the only option in my simulator list in VS For Mac 2022 is "generic simulator". I'll attach the response of what I get when I run dotnet --info, along with the software versions of vs for Mac 2022 and Xcode below.

`dotnet --info
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.202/

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  6.0.407 [/usr/local/share/dotnet/sdk]
  7.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
`

![image](https://user-images.githubusercontent.com/129321524/230746388-051e8153-d5dc-4bd1-b206-26a0a2e1dbb5.png)

![image](https://user-images.githubusercontent.com/129321524/230746403-f51b7b3f-f7cb-454e-91c9-bc8b07b3be18.png)

![image](https://user-images.githubusercontent.com/129321524/230746416-6ac72f79-b87f-4058-a679-ca6ebff58255.png)

![image](https://user-images.githubusercontent.com/129321524/230746429-35698eed-833c-46a0-9064-52605f0bd5f7.png)

### Steps to Reproduce

1. create new Xamarin.ios Project/Open existing project
2. select debug | iPhone simulator
3. See "generic simulator" option
4. If the simulator list is available, run the application
5. see it runs and stops no errors no apparent explanation, does not hit main

### Expected Behavior
Seeing a list of simulators, being able to select one and have the project load on the simulator

### Actual Behavior
Either only "generic simulator" option is available OR simulators are present but effectively "nothing" happens. Project just runs for a second and stops, no build errors.
### Environment

<details>
<summary>Version information</summary>

```
```

</details>

### Build Logs
I am having trouble getting the build logs since the application won't run long enough for me to see the build log tab in debug mode. Maybe I am misunderstanding how to access the build logs.

### Example Project (If Possible)
Creating a blank Xamarin.IOS project on visual studio for Mac along with using the existing project both only show "generic simulator option"

**Comment by dalexsoto** [comment]
You need to use Xcode 14.2 until we release support for Xcode 14.3, please refer to this thread for more info. https://github.com/xamarin/xamarin-macios/issues/17561

**Comment by jmartienzCobec** [comment]
Hello, downloading Xcode 14.2 brought back my simulator options but now "nothing" happens, I deploy the application but it just starts and stops.

**Comment by jmartienzCobec** [comment]
was getting a simctl returned exit code 72 error; found this article https://stackoverflow.com/questions/74128227/error-he0046-failed-to-install-the-app-simctl-returned-exit-code-72 reselecting the command line tools worked for me.
