### ISSUE TITLE
Is it possible to build Maui app for iOS using XCode 13.4.1?

### ISSUE THREAD

**Issue by balintn22** [xamarin/xamarin-macios#18063]
It is not a bug report, more a question.
I'm buildin a Maui app, got to the point, where I'd like to build the iPhone version.
My environment is VS 2022, details below:
----------------- Begin VS Environment -----------------------
Microsoft Visual Studio Community 2022
Version 17.5.3
VisualStudio.17.Release/17.5.3+33516.290
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA347
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.5.318.41597
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.318.41597
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.5.318.41597
Azure Functions and Web Jobs Tools

C# Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   6.5.0+76d4669002
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.5.2.2316603+9f1b6856460af1e592d387ebef416eadddac453f
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.2.40119.0
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

WiX Toolset Visual Studio Extension   1.0.0.18
WiX Toolset Visual Studio Extension version 1.0.0.18
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.5.41 (ba80d05)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77

Xamarin.iOS and Xamarin.Mac SDK   16.2.0.5 (7738c90c9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
----------------- End VS Environment -----------------------

I have a Mac Mini, but it is quite old, I can only upgrade it to Monterey (13), which only allows upgrading Xcode to 13.4.1 (but not to 14).

When I connect the VS to Mac, I get a warning, when I build the app, I get some errors:
-------------------- Begin Error Messages ------------------------
Severity	Code	Description	Project	File	Line	Suppression State
Error	IL7000	An error occured while executing the custom linker steps. Please review the build log for more information.	YAShoppingList.Maui	C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.2.19\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets	332	
Error	MSB3371	The file "obj\Debug\net6.0-ios\iossimulator-x64\linked\Link.semaphore" cannot be created. Could not find a part of the path 'C:\_Src\Balint\YAShoppingList\YAShoppingList\YAShoppingList.Maui\obj\Debug\net6.0-ios\iossimulator-x64\linked\Link.semaphore'.	YAShoppingList.Maui	C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.2.19\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets	373	
Error	MT2301	The linker step 'Setup' failed during processing: This version of Microsoft.iOS requires the iOS 16.2 SDK (shipped with Xcode 14.2). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs).	YAShoppingList.Maui	C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.2.19\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets	332	
Error	MT0180	This version of Microsoft.iOS requires the iOS 16.2 SDK (shipped with Xcode 14.2). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs).	YAShoppingList.Maui	C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.2.19\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets	332	
-------------------- End Error Messages ------------------------

The question is, is it possible to build an iOS app with my tools (Mac and Xcode), maybe by downgrading the iOS dotnet target version or any other way?

**Comment by balintn22** [comment]
Oh, current target frameworks:
<TargetFrameworks>net6.0-ios;net6.0-android33.0</TargetFrameworks>

**Comment by MateuszLas421** [comment]
https://github.com/xamarin/xamarin-macios/issues/17561

**Comment by rolfbjarne** [comment]
You can try using the `net6.0-ios15.4` target framework, but it might not work (we have a few known issues with regards to using older versions this way).

Note that you won't be able to submit apps built with Xcode 13, because Apple will very soon require app submissions to be built with Xcode 14.1: https://developer.apple.com/news/?id=jd9wcyov
