### ISSUE TITLE
Missing bindings for SMAppService

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#18084]
My intention is to use [SMAppService](https://developer.apple.com/documentation/servicemanagement/smappservice?language=objc) API however it does not seem to be bound to be used in a .NET project. Or am I missing something?

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.5.4 (build 8)
Installation UUID: 4a01325a-4094-4e96-a53f-ac12891a073e

Runtime
.NET 7.0.1 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.203/Sdks
SDK Versions:
	7.0.203
	7.0.202
	7.0.201
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.5
	7.0.4
	7.0.3

Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found

Updater
Version: 11

Apple Developer Tools
Xcode: 14.3 21812
Build: 14E222b

Xamarin.Mac
Version: 9.3.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:35-0400

Xamarin.iOS
Version: 16.4.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400

Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 2023-04-05 15:58:40 UTC

Xamarin.Android
Not Installed

Microsoft Build of OpenJDK
Java SDK: Not Found

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 17.5.0.33
Hash: f0c0c52
Branch: remotes/origin/d17-5~2
Build date: 2023-04-05 15:58:45 UTC

Android Device Manager
Version: 0.0.0.1245
Hash: 7f8a990
Branch: 7f8a990
Build date: 2023-04-05 15:58:45 UTC

Build Information
Release ID: 1705040008
Git revision: 9a2f0e1a7e2107e6b1174c241a1ca232cde57c49
Build date: 2023-04-05 15:56:57+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 13.3.1
Darwin 22.4.0 Darwin Kernel Version 22.4.0
    Mon Mar  6 21:00:41 PST 2023
    root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64

```

</details>

**Comment by rolfbjarne** [comment]
You're correct, we haven't bound the `SMAppService` API (nothing in the `ServiceManagement` framework actually).

**Comment by Hooterr** [comment]
Is DLL import an option here? I don't know enough, but I think since `SMAppService` is a class we can't import instance method that way. Am I correct?

**Comment by rolfbjarne** [comment]
> Is DLL import an option here? I don't know enough, but I think since `SMAppService` is a class we can't import instance method that way. Am I right?

No, unfortunately it's rather more complex than a DllImport.

However, I've bound this framework now, so we'll eventually ship bindings for it. This will be at the latest in .NET 8, and potentially earlier depending on whether Apple releases new Xcode versions before then

**Comment by Hooterr** [comment]
Awesome. Does that mean this will not be available in Xamarin.Mac?

Wait a second, are Xamarin.Mac and Microsoft.macOS.Sdk two different things? When I saw that MAUI uses MacCatalyst I thought that building fully featured mac apps wouldn't be possible. So what, when I target net7-macos I can build a regular Xamarin.Native style app without MAUI?

**Comment by rolfbjarne** [comment]
> Awesome. Does that mean this will not be available in Xamarin.Mac?

Xamarin.Mac will be [discontinued](https://devblogs.microsoft.com/xamarin/xamarin-ios-16-android-13-updates/) for the next major version of Xcode, so it's possible it won't be available in Xamarin.Mac.

> Oh no... I just realised Xamarin.Mac and Microsoft.macOS.Sdk are two different things. When I saw that MAUI uses MacCatalyst I thought that building fully featured mac apps wouldn't be possible. So what, when I target net7-macos I can build a regular Xamarin.Native style app without MAUI?

Correct, you can use the `net7.0-macos` TargetFramework and build a regular Xamarin-style app without MAUI.

Note that that applies to the other platforms as well, you can use the `net7.0-ios` target framework and not use MAUI if you don't want to.
