### ISSUE TITLE
NEHotspotConfiguration Internal error

### ISSUE THREAD

**Issue by mfranc28** [xamarin/xamarin-macios#18097]
### Steps to Reproduce

1.  Create a blank app
2. Create a class and use NEHotspotConfiguration

NEHotspotConfigurationManager wifiManager = new NEHotspotConfigurationManager();
        String ssid;
        public WifiConnector()
        {
        }

        async void IWifiConnector.ConnectToWifi(string ssid, string password, WifiNetworkCallback networkCallback)
        {
            try
            {
              
                this.ssid = ssid;
                try
                {
                    wifiManager.RemoveConfiguration(this.ssid);
                }
                catch
                {

                }
                var wifiConfig = new NEHotspotConfiguration(ssid, password, false);
                wifiConfig.JoinOnce = false;
 wifiManager.ApplyConfiguration(wifiConfig, (error) =>
                {
                    if (error != null)
                    {
                        Console.WriteLine($"Error while connecting to WiFi network {ssid}: {error}");
                        networkCallback.NetworkUnavailable();
                    }
                    else
                    {
                        networkCallback.NetworkAvailable();
                    }
                });

4. Run and try to connect to a hotspot 

### Expected Behavior
Connection successful 
### Actual Behavior
Internal Error
### Environment
Xcode 13.4 or 14.3
Xamarin iOS 16.2.0.5

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.5.4 (build 8)
Installation UUID: 2742e159-121c-4343-a36e-d01153dfa812

Runtime
.NET 7.0.1 (64-bit)
Architecture: X64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.402/Sdks
SDK Versions:
	6.0.402
	3.1.424
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.10
	3.1.30

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.0.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-3/030cd63
Android SDK: /Users/michelangelo/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.33
Hash: f0c0c52
Branch: remotes/origin/d17-5~2
Build date: 2023-04-05 15:58:04 UTC

Android Device Manager
Version: 0.0.0.1245
Hash: 7f8a990
Branch: 7f8a990
Build date: 2023-04-05 15:58:04 UTC

Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 2023-04-05 15:57:59 UTC

Apple Developer Tools
Xcode: 13.4 20503
Build: 13F17a

Xamarin.Mac
Not Installed

Xamarin.iOS
Version: 16.2.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:15-0500

Build Information
Release ID: 1705040008
Git revision: 9a2f0e1a7e2107e6b1174c241a1ca232cde57c49
Build date: 2023-04-05 15:56:22+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:17:10 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64


```

</details>

**Comment by mfranc28** [comment]
@rolfbjarne Which info do you need?

**Comment by rolfbjarne** [comment]
@mfranc28 ah sorry, I lost my comment: please attach a complete test project we can use to reproduce the issue, that way we're certain we're testing the same thing.
