### ISSUE TITLE
Missing AVCaptureSession property

### ISSUE THREAD

**Issue by saamerm** [xamarin/xamarin-macios#18155]
### Steps to Reproduce

1. Create a new AVCaptureSession object in a class
2. Try to access the isMultitaskingCameraAccessEnabled property

### Expected Behavior

We should be able to access it and update it

### Actual Behavior

Not able to access oroperty

### Environment

Latest Xamarin iOS version 

```
AVCaptureSession.isMultitaskingCameraAccessEnabled = true;
```

### Build Logs

Doesn’t build

### Example Project (If Possible)

None. Code block shared

link to Apple documentation 
https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_for_video_calls

**Comment by saamerm** [comment]
It seems like it may not be too difficult to fix this issue. Please let me know if there’s any reference of how I can contribute to this fix (Eg: similar PR, or classes where change is needed )

**Comment by rolfbjarne** [comment]
I can confirm this issue, and I'm working on a fix.

In the meantime, something like this should work as a workaround:

```cs
using System.Runtime.InteropServices;
using ObjCRuntime;

[DllImport ("/usr/lib/libobjc.dylib", EntryPoint = "objc_msgSend")]
public extern static void void_objc_msgSend_bool (IntPtr receiver, IntPtr selector, bool value);

AVCaptureSession session = ...;
void_objc_msgSend_bool (session.Handle, Selector.GetHandle ("setMultitaskingCameraAccessEnabled:"), true);
```

**Comment by saamerm** [comment]
@rolfbjarne as soon as you find out what version of Xamarin this will go into, please share with me!

**Comment by rolfbjarne** [comment]
> @rolfbjarne as soon as you find out what version of Xamarin this will go into, please share with me!

That actually depends on Apple, due to how we're versioning our product we can only release new APIs whenever Apple releases new API (even if the API we're adding has nothing to do with the API Apple creates at the time). At this moment that would likely be when (if) Apple releases Xcode 14.4 (or latest Xcode 15 in the fall).
