### ISSUE TITLE
Build system Could not parse TargetArchitectures 'x64'

### ISSUE THREAD

**Issue by CamJN** [xamarin/xamarin-macios#18189]
### Steps to Reproduce

Reproducing this will be a pain in the backside, however I'll try and help. You will need a mac with dotnet 7 & the macOS CLT package installed.

1. `git clone https://github.com/CamJN/stub-getargv.git`
2. `git clone https://github.com/getargv/getargv.cs.git`
3. `make && make install` the `stub-getargv` project. This may require `sudo` to install.
4. `dotnet workload restore && dotnet restore && dotnet build --no-restore` the `getargv.cs` project.

### Expected Behaviour

The build system can parse the TargetArchitectures

### Actual Behaviour

The build system cannot parse the TargetArchitectures

### Environment

I do not use the Visual Studio IDE, just the cli tools so the instructions for gathering the environment info don't work in this case. Also, since the version of dotnet shipped by homebrew is broken at the moment all of this is run on Github actions instead of my local laptop and is thus using their installed tools, so the versions I'm aware of are the ones that appear in the logs.

<details>
<summary>Version information</summary>

```
dotnet SDK Version: 7.0.203
MSBuild version 17.5.1+f6fdcf537 for .NET
Microsoft.macOS.Sdk: 13.1.2054
Microsoft.macOS.Sdk: 13.1.46
Microsoft.macOS.Ref version 13.1.2054
Microsoft.macOS.Runtime.osx-x64 version 13.1.2054
Microsoft.macOS.Runtime.osx-arm64 version 13.1.2054
Microsoft.macOS.Templates version 13.1.2054
Microsoft.NET.Runtime.MonoAOTCompiler.Task version 7.0.5
Microsoft.NET.Runtime.MonoTargets.Sdk version 7.0.5
Microsoft.NET.Runtime.MonoAOTCompiler.Task version 6.0.16
Microsoft.NET.Runtime.MonoTargets.Sdk version 6.0.16
```

</details>

### Build Logs

https://github.com/getargv/getargv.cs/actions/runs/4833187089/jobs/8612879014

### Example Project (If Possible)

https://github.com/getargv/getargv.cs/

**Comment by filipnavara** [comment]
`x64` is not a valid value, `x86_64` would be. Then again, since you are targeting modern .NET you should probably use `<RuntimeIdentifier>` or `<RuntimeIdentifiers>` with the values like `osx-x64` or `osx-arm64`.

**Comment by CamJN** [comment]
Thanks, are there any docs on this? I tried searching the csharp docs website but keep coming up empty handed.

As to why i was doing it this way, I was just trying to fix the errors that were reported, my previous run said:

`/Users/runner/.dotnet/packs/Microsoft.macOS.Sdk/13.1.2054/targets/Xamarin.Shared.Sdk.targets(1545,3): error MSB4044: The "ResolveNativeReferences" task was not given a value for the required parameter "Architectures". [/Users/runner/work/getargv.cs/getargv.cs/getargv.cs/Getargv.Tests/Getargv.Tests.csproj]`

And when I looked up the Architectures parameter in ResolveNativeReferences, it was populated by `"$(TargetArchitectures)"`, so I was trying to set that.

**Comment by CamJN** [comment]
Apparently the syntax for listing multiple `TargetArchitectures` is different from the syntax for multiple `IncludeAssets`:
`/Users/runner/.dotnet/packs/Microsoft.macOS.Sdk/13.1.2054/tools/msbuild/macOS/Xamarin.Shared.targets(532,3): error : Could not parse TargetArchitectures 'x86_64;arm64' [/Users/runner/work/getargv.cs/getargv.cs/getargv.cs/Getargv.Tests/Getargv.Tests.csproj]`

**Comment by filipnavara** [comment]
`RuntimeIdentifier(s)` is the documented standard way. `TargetArchitectures` dates back to the old Xamarin/Mono SDKs. You can search this repository for examples of the acceptable values but I don't really recommend relying on it.

**Comment by CamJN** [comment]
ok switching to RuntimeIdentifiers does seem to have populated TargetArchitectures, so that works. however I then get this:

`/Users/runner/.dotnet/sdk/7.0.203/Sdks/Microsoft.NET.ILLink.Tasks/build/Microsoft.NET.ILLink.targets(196,5): error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app. [/Users/runner/work/getargv.cs/getargv.cs/getargv.cs/Getargv.Tests/Getargv.Tests.csproj]`

which is apparently supposed to be fixed already: https://github.com/xamarin/xamarin-macios/issues/12000

**Comment by filipnavara** [comment]
I think the root of the issue is that you are trying to use `net7.0-macos` TFM for something where plain `net7.0` would have sufficed.

The `-macos` part brings in the API bindings for Apple frameworks but it also makes the app build as bundles that inject native runtime code necessary for the bindings to work.

Out of the box `net7.0-macos` is not compatible with the standard Xunit/Nunit runners. These runners are built just as regular `net7.0` with no native shims, then load the test assembly, and execute methods in it. However, without the native shim any references to the Apple bindings won't work anyway.

If you really need both Xunit and the Apple bindings (which are implied by the `net7.0-macos` TFM) then you would need to use a different Xunit runner specific for that scenario, like dotnet/xharness.

**Comment by CamJN** [comment]
As you noticed I don't need the extra APIs provided by `net7.0-macos`, but at the same time my classlib will only ever work on macos, so is there a better way to indicate that? I've seen https://github.com/dotnet/designs/blob/main/accepted/2020/platform-checks/platform-checks.md but that seems to be compile-time and optional, I'd really prefer to add it to the package metadata somehow.

**Comment by filipnavara** [comment]
> so is there a better way to indicate that?

That's outside my area of expertise. There's `SupportedOSPlatform` attribute, as you already figured out, and by default that would warn anyone that tries to use the referenced APIs on a different platform. If someone decides to override that warning then they are on their own...

Note that packaging as `net7.0-macos` would prevent using the library in a multi-platform app even if all the call were properly guarded with `if (OperatingSystem.IsMacOS())`, so it would only make the life harder for people consuming the library in this fashion.

**Comment by CamJN** [comment]
Good point, thanks
