### ISSUE TITLE
GetTitleTextAttributes in Microsoft.IOS return is different than in Xamarin.IOS

### ISSUE THREAD

**Issue by jamesingreersc** [xamarin/xamarin-macios#18195]
Both below methods reside in UISegmentedControl

### Steps to Reproduce

1.  Attempt to convert a Xamarin.IOS project to .Net Microsoft.IOS project
2.  try converting this method from Xamarin.IOS to Microsoft.IOS .Net6
      UITextAttributes routeSegmentControlAttributes = segmentSaleType.GetTitleTextAttributes(UIControlState.Selected);

### Expected Behavior
Method should return a UITextAttributes object like in Xamarin.IOS

### Actual Behavior
Actual return value is a UIStringAttributes object

### Environment
Visual studio 2022 preview. Windows 10. Microsoft IOS .Net 6

<details>
<summary>Version information</summary>

```
```

</details>

### Build Logs
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'UIKit.UIStringAttributes' to 'UIKit.UITextAttributes'	DSDRouteManager.IOS

**Comment by rolfbjarne** [comment]
Can you explain exactly why it's a problem that the `GetTitleTextAttributes` method returns a `UIStringAttributes` instead of a `UITextAttributes` object? `UIStringAttributes` should be a more accurate type.

As to your code, this should work:

```cs
var routeSegmentControlAttributes = segmentSaleType.GetTitleTextAttributes(UIControlState.Selected);
```

**Comment by jamesingreersc** [comment]
@rolfbjarne The biggest problem with the return type is that it breaks the existing code. UIStringAttributes doesn't contain a TextColor property. I'm just trying to convert to .Net as close as possible to the existing code base.
`            UITextAttributes routeSegmentControlAttributes =routeSegmentControl.GetTitleTextAttributes(UIControlState.Selected);
            if (routeSegmentControlAttributes == null) routeSegmentControlAttributes = 
                routeSegmentControl.GetTitleTextAttributes(UIControlState.Normal);
            if (routeSegmentControlAttributes == null) routeSegmentControlAttributes = new UITextAttributes()
            {
                Font = UIFont.FromName("System", 16),
                TextColor = UIColor.White
            };
            routeSegmentControlAttributes.Font = UIFont.SystemFontOfSize(16, UIFontWeight.Regular);
            routeSegmentControlAttributes.TextColor = UIColor.White;`

**Comment by rolfbjarne** [comment]
> UIStringAttributes doesn't contain a TextColor property.

You can use the ForegroundColor property instead.

According to Apple's documentation, `UITextAttributeTextColor` (the underlying field for UITextAttributes.TextColor) is deprecated in favor of `NSForegroundColorAttributeName` instead (the underlying field for UIStringAttributes.ForegroundColor).

**Comment by jamesingreersc** [comment]
@rolfbjarne Awesome. Just tried that and it works great. Thanks for your help!
James
