### ISSUE TITLE
Copy .dSYM files to output path on publish

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-macios#18190]
### Steps to Reproduce

`dotnet public -f net7.0-ios -o ./artifacts` causes the .ipa to output correctly, however it would be good to also get the .dSYM files copied here (or if that seems weird by default, perhaps another property to specify the path to copy them to).

**Comment by Redth** [comment]
Looks like `MonoSymbolArchive=True` needs to be set to actually produce them, and then they might output there?  Perhaps we should consider defaulting that to true for publish with release configs?

**Comment by filipnavara** [comment]
Related: https://github.com/xamarin/xamarin-macios/issues/17807#issuecomment-1473369893

**Comment by rolfbjarne** [comment]
Dup of #15384.
