### ISSUE TITLE
macOS microphone access request consistently crashes the application

### ISSUE THREAD

**Issue by msioen** [xamarin/xamarin-macios#18194]
### Steps to Reproduce

1. Create a new macOS Application (net7.0-macos)
2. Call AVCaptureDevice.RequestAccessForMediaType after application launch
3. => application crashes on following error message: `This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an com.apple.security.device.audio-input key with a string value explaining to the user how the app uses this data.`

I tested several variants with different versions of signing / Info.plist values and Entitlements.plist values but I never got it to work.
I created a small test swift application as well with the same plist values which works perfectly fine (allthough maybe they do signing somewhat different under the hood?)

### Expected Behavior

The call should either just work or return an error in some way - now it just crashes the full application.

### Actual Behavior

<img width="1369" alt="Screenshot 2023-05-01 at 16 34 26" src="https://user-images.githubusercontent.com/1830018/235468657-5cd5e251-e4c0-4200-8600-8d4b4b74237d.png">

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.5.4 (build 8)
Installation UUID: 31c61115-13d7-4078-8a73-c6e33a5d7f1b

Runtime
.NET 7.0.1 (64-bit)
Architecture: X64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.203/Sdks
SDK Versions:
	7.0.203
	7.0.201
	7.0.200
	7.0.103
	6.0.408
	6.0.406
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.5
	7.0.3
	6.0.16
	6.0.14

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/797e2e1
Android SDK: /Users/michielsioen/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/main@149d70fe
SQLite: xamarin/sqlite/3.40.0@fdc1e34
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.33
Hash: f0c0c52
Branch: remotes/origin/d17-5~2
Build date: 2023-04-05 15:58:04 UTC

Android Device Manager
Version: 0.0.0.1245
Hash: 7f8a990
Branch: 7f8a990
Build date: 2023-04-05 15:58:04 UTC

Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

Xamarin.Mac
Version: 9.1.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:14-0500

Xamarin.iOS
Version: 16.2.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:15-0500

Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 2023-04-05 15:57:59 UTC

Build Information
Release ID: 1705040008
Git revision: 9a2f0e1a7e2107e6b1174c241a1ca232cde57c49
Build date: 2023-04-05 15:56:22+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 13.2.1
Darwin 22.3.0 Darwin Kernel Version 22.3.0
    Mon Jan 30 20:42:11 PST 2023
    root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64

```

</details>

### Example Project (If Possible)

[Net7MicTest.zip](https://github.com/xamarin/xamarin-macios/files/11365976/Net7MicTest.zip)

**Comment by msioen** [comment]
After posting this I also tried to just run the generated .app without Visual Studio as the crash reporter does report vsdbg-ui as parent process.
Surprisingly the code seems to work fine in that case. ie macOS correctly asks for microphone permission and doesn't crash.

=> Should the debugger be launched in some special way to support this? How can I debug applications that need microphone functionality / extended permissions?

**Comment by rolfbjarne** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/80727.
