### ISSUE TITLE
Localization completely broken in IOS apps even with workaround

### ISSUE THREAD

**Issue by SoftArea-srl** [xamarin/xamarin-macios#18239]
### Description

It's impossible to add more than one language to an ios app.

Localization resx files are ignored for 2 and more additional languages when an iOS app is built in debug or release and run on iOS local device (iPhone 12 iOS 16.4). Differently from local devices, the localization works on iOS simulators.

Based on the original work from @nevse [here](https://github.com/nevse/maui-tests-iosreleaselocalization), which first highlited this issue on 16 Jan 2023, and adding  the workaround suggested [here](https://github.com/xamarin/xamarin-macios/issues/17262#issuecomment-1384092802), I created a simple app, source code available [here](https://github.com/SoftArea-srl/MAUI-iOS-Localization-Issue.git). It contains three resx files (Resources/MyLocalization.resx, Resources/MyLocalization.de.resx, Resource/MyLocailzation.es.resx) which I use to obtain the localized string "MyString" in the following way:

```
    Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
    CultureStringLabel.Text = resourceManager.GetString("MyString");
```
Moreover, in the project file, it has been included what was suggested as workarount:

```
<PropertyGroup>
    <EnableAssemblyILStripping>false</EnableAssemblyILStripping>
</PropertyGroup>
```
It works fine when I build my app in debug or release for an iphone simulator, but it doesn't work when I build it in debug or release for a real device. It works only for the default resx file.

### Steps to Reproduce

1. create an app from the default template: dotnet new maui
2. add three labes and three buttons and create handlers for them

```
    <ScrollView>
        <VerticalStackLayout
            Padding="30,0"
            Spacing="25"
            VerticalOptions="Center">
            <Button Clicked="OnSetEngCulture" Text="Set Eng Culture" />
            <Button Clicked="OnSetDeCulture" Text="Set De Culture" />
            <Button Clicked="OnSetEsCulture" Text="Set Es Culture" />
            <Label x:Name="CultureStringLabel" />
            <Label x:Name="CurrentCultureLabel" />
            <Label x:Name="CurrentUICultureLabel" />
        </VerticalStackLayout>
    </ScrollView>
```
```
    private void OnSetEngCulture(object sender, EventArgs e)
    {
        Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
        CultureStringLabel.Text = resourceManager.GetString("MyString");
        CurrentCultureLabel.Text = "Current Culture: " + Thread.CurrentThread.CurrentCulture;
        CurrentUICultureLabel.Text = "Current UI Culture: " + Thread.CurrentThread.CurrentUICulture;
    }
    private void OnSetDeCulture(object sender, EventArgs e)
    {
        Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture = new CultureInfo("de");
        CultureStringLabel.Text = resourceManager.GetString("MyString");
        CurrentCultureLabel.Text = "Current Culture: " + Thread.CurrentThread.CurrentCulture;
        CurrentUICultureLabel.Text = "Current UI Culture: " + Thread.CurrentThread.CurrentUICulture;
    }
    private void OnSetEsCulture(object sender, EventArgs e)
    {
        Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture = new CultureInfo("es");
        CultureStringLabel.Text = resourceManager.GetString("MyString");
        CurrentCultureLabel.Text = "Current Culture: " + Thread.CurrentThread.CurrentCulture;
        CurrentUICultureLabel.Text = "Current UI Culture: " + Thread.CurrentThread.CurrentUICulture;
    }
```
3. build the app in debug or release and run on the real iphone device

### Expected Behavior
Press each button - you should see different strings: "string from DEFAULT resource file", "string from DE resource file", "string from ES resource file".

### Actual Behavior
Press "Set Eng Culture" to see "string from DEFAULT resource file".
Press "Set De Culture" you should see the " string from DE resource file", but this string is "string from DEFAULT resource file". It's wrong behaviour.
Press "Set Es Culture" to see "string from ES resource file", but this string is "string from DEFAULT resource file". It's wrong behaviour.

### Link to public reproduction project repository
[https://github.com/SoftArea-srl/MAUI-iOS-Localization-Issue.git](https://github.com/SoftArea-srl/MAUI-iOS-Localization-Issue.git)

### Environment

Visual Studio 17.5.4 for Windows
Windows 11 PRO 22H2 Connected to MAC MINI with macOS Ventura 13.2.1
Built for .NET 7
device used: iPhone 12 iOS 16.4.1 and iPhone 11 iOS 15.2

### Last version that worked well
Unknow/Other

### Affected platform versions
iOS 15 and 16

### Did you find any workaround?
No

**Comment by rolfbjarne** [comment]
Your test project works for me on device when executing on a Mac, but I see you're on Windows. Can you try (for diagnostic purposes) running from the Mac to see if that works for you?
