### ISSUE TITLE
Consicutive run crashes on debugging on iOS device with Maui App

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#18309]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Consicutive-run-crashes-on-debugging-on-/10365041)._

---
I have a Maui App that i am migrating from Xamarin to MAUI, I was able to run the Application in my iOS device without any issue for multiple time, but after the recent visual studio update I am facing one issue : when try to run/ debugg for consicutive/multiple time it crashes with fetal error. As a workaround every time before running i have to clean the solution and then run it, which takes lot’s of time.

Here is the error i am getting: 

2023-05-16 23:09:07.460 MyApp.iOS[6186:9760501] error: Failed to load AOT module 'MyApp.iOS' while running in aot-only mode because a dependency cannot be found or it is out of date.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10c6d3894 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10c6bc7dc - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10c861084 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10c6d30a8 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x1f1043c10 - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x1f1051378 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x18b484f50 - /usr/lib/system/libsystem_c.dylib : abort
	0x10c36df50 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : xamarin_find_protocol_wrapper_type
	0x10c70f044 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10c70f178 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10c6aad80 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10c57656c - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10c576088 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10c577d00 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10c36d124 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : xamarin_locate_assembly_resource
	0x10c36ce80 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : xamarin_get_block_descriptor
	0x10c36d318 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : xamarin_locate_assembly_resource
	0x10c382388 - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : xamarin_get_original_working_directory_path
	0x10c75acfc - /private/var/containers/Bundle/Application/E6D4F095-C5DB-4A25-94E5-5F27EF1642DF/MyApp.iOS.app/MyApp.iOS : _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode
	0x10d891aa4 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1b7b19964):0x1b7b19954  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .. _..._..) ......
0x1b7b19964  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ... T.#... {......
0x1b7b19974  34 ee ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  4........ {...._.
0x1b7b19984  c0 03 5f d6 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  .. _.. #... {......

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================

---
#### Feedback Bot on 5/17/2023, 01:03 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by rolfbjarne** [comment]
Please provide a binlog of a working build (right after clean), and another binlog of a build that crashes.

This explains how to get a binlog: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs
