### ISSUE TITLE
Investigate/implement `__LINKEDIT` size reduction

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18332]
See https://github.com/dotnet/runtime/issues/86707 for background information.

Basically we want to look into whether we can produce smaller binaries by passing the exported functions to the native linker (as opposed to stripping them away later).

The referenced issue only talks about this in the context of NativeAOT, but this might benefit us on all platforms, not just NativeAOT.

**Comment by ivanpovazan** [comment]
This was also noticed with Mono (to much smaller extent), where the `__LINKEDIT    Export Info` takes up `20313368` bytes of zeros with MAUI iOS template app: https://gist.github.com/ivanpovazan/97ec573836caca3f8347b8eafa2cad14
