### ISSUE TITLE
Set the `IsDynamicCodeSupported` feature to false when using FullAOT

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18340]
We need to set the `System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported` feature to `false` when using FullAOT (i.e. AOT + no interpreter).

This is done by setting the `DynamicCodeSupport` property to `false`:

https://github.com/dotnet/sdk/blob/9ca8336afab6247a22e745c2de4960e9b660d164/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L529-L532

The NativeAOT compiler does that here:

https://github.com/dotnet/sdk/blob/9ca8336afab6247a22e745c2de4960e9b660d164/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L27

We need to do the same when using MonoAOT + no interpreter.

**Comment by ivanpovazan** [comment]
I can look into this.

**Comment by ivanpovazan** [comment]
As the dotnet/runtime side has been merged in, we should try it out on xamarin .net8 branch once we start referencing the version including the change via something like:
```xml
<DynamicCodeSupport Condition="'$(DynamicCodeSupport)' == '' and '$(UseInterpreter)' != 'true'">false</DynamicCodeSupport>
```

**Comment by ivanpovazan** [comment]
When: https://github.com/dotnet/runtime/pull/88539 gets merged in it should additionally bring some size savings as more code will depend on the feature switch in question.

**Comment by ivanpovazan** [comment]
Fixed by https://github.com/xamarin/xamarin-macios/issues/18340
