### ISSUE TITLE
How does MtouchInterpreter property get used by these targets?

### ISSUE THREAD

**Issue by NickDarvey** [xamarin/xamarin-macios#18380]
The [`AOTCompile` task](https://github.com/xamarin/xamarin-macios/blob/2606b2341e1014bdf0549b264fe07d9b572fb6f7/dotnet/targets/Xamarin.Shared.Sdk.targets#L1049-L1062) is failing for me as described in https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1530

I'm trying to use the workaround as described in:
- https://github.com/xamarin/xamarin-macios/issues/17981#issuecomment-1510864263
- https://github.com/dotnet/docs-maui/issues/1438#issue-1672601910

However, my `MtouchInterpreter` property is not having an effect and I'm trying to diagnose why.

I can see in my binlog that this property is never used (except for me declaring it) and the only place I can see that property used in this repo is 

https://github.com/xamarin/xamarin-macios/blob/2606b2341e1014bdf0549b264fe07d9b572fb6f7/msbuild/Xamarin.Shared/Xamarin.iOS.Common.targets#L261

which is in a target which has a condition which is not met (because `UsingAppleNETSdk == true`).

https://github.com/xamarin/xamarin-macios/blob/2606b2341e1014bdf0549b264fe07d9b572fb6f7/msbuild/Xamarin.Shared/Xamarin.iOS.Common.targets#L218-L219

Where is the MtouchInterpreter property actually used?

### Environment

<details>
<summary>Version information</summary>

```
dotnet 7.0.100
Microsoft.iOS.Sdk 16.2.1024
```

</details>

### Build Logs

Edit: Pending. Will upload soon.

**Comment by rolfbjarne** [comment]
For .NET projects, the `$(MtouchInterpreter)` property is consumed in the Xamarin.Shared.Sdk.targets file:

https://github.com/xamarin/xamarin-macios/blob/2606b2341e1014bdf0549b264fe07d9b572fb6f7/dotnet/targets/Xamarin.Shared.Sdk.targets#L487

However, please file an issue about the crash as well, because the AOT compiler shouldn't crash like that.

**Comment by NickDarvey** [comment]
> However, please file an issue about the crash as well, because the AOT compiler shouldn't crash like that.

#18388 18388
