### ISSUE TITLE
How do I print to system.log in release configuration?

### ISSUE THREAD

**Issue by NickDarvey** [xamarin/xamarin-macios#18403]
I'm seeing unexpected behaviour at runtime only in release configuration. How can I write to the iOS simulator `system.log` logs? Or otherwise, what other debugging tools are at my disposal in release configuration?

I've tried searching for "system.log" in this repo and dotnet/maui.

### System info

- dotnet 7.0.302
- maui-ios 7.0.86/7.0.100

**Comment by rolfbjarne** [comment]
You can use Console.WriteLine statements, and they'll go to the system log.

Then you can view the system log from the device using the Console app on your Mac - select the device on the left, and click "Start" to start collecting log statements.

There's more documentation about the Console app here: https://support.apple.com/fr-fr/guide/console/cnsl1012/mac

**Comment by NickDarvey** [comment]
Thanks @rolfbjarne!
