### ISSUE TITLE
How to develop on VSCode

### ISSUE THREAD

**Issue by petro2050** [xamarin/xamarin-macios#18457]
Is it possible to use VSCode (instead of VS for Mac) to develop a Xamarin.iOS app? I'd also like to deploy to a physical device. When I auto-gen launch.json, it seems to target a simulator by default.

**Comment by dalexsoto** [comment]
Hello,

As of today the only supported way of developing apps is using VS for Mac and VS for Windows, unfortunately VSCode would require manual integration of mlaunch and different tools that the VS add-ins handle today, so it may be possible but it requires a lot of work to setup and I am not even sure how other things like the debugger support would work in that scenario.

**Comment by narciszait** [comment]
considering the Microsoft announcement from August 31, that Visual Studio for Mac is not updated from August 2024, it would be interesting to see how this will work

**Comment by rolfbjarne** [comment]
There's an extension that supports MAUI: https://devblogs.microsoft.com/visualstudio/announcing-the-dotnet-maui-extension-for-visual-studio-code/

And technically Xamarin.iOS shouldn't be that hard from there on.

If the extension doesn't work for Xamairn.iOS projects, I'd suggest filing an issue at their repo here: https://github.com/microsoft/vscode-dotnettools/issues, to see if they're willing to add support for it.

**Comment by vrad-joshuamckelvey** [comment]
What is the plan going forward with the deprecation of Visual Studio for Mac? Many of us support Xamarin Forms applications that are not ready to be moved to MAUI.

**Comment by Inaganti97** [comment]
how to create xamarin.iOS using VS code code to support .net 8.0 version.

**Comment by ThiagoFrancischini** [comment]
My visual studio for mac just stopped working, but now I can't download it again because Microsoft removed the download from the website, and I have to maintain some Xamarin Apps that cannot be migrated yet. Now I cannot develop because the VS Code for mac ( that was supposed to be the official alternative ) doesnt work, thank you Microsoft!!!

**Comment by taublast** [comment]
At present date we can use Jetbrains Rider for Mac to still edit and compile Xamarin on Mac.

**Comment by ThiagoFrancischini** [comment]
I am currently using Rider, its been really good actually, but good to know, thanks
