### ISSUE TITLE
NativeAOT: implement better logic for finding the icu data file

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18471]
Ref: [`6d2e0b5` (#17374)](https://github.com/xamarin/xamarin-macios/pull/17374/commits/6d2e0b5de8820a29a4e0dc95dbdb04143c6a2bd8)

Once this dotnet/runtime fix reaches us:

    https://github.com/dotnet/runtime/pull/87813

We should revert it, and instead set the ICU_DAT_FILE_PATH property in the runtime config to the relative path inside the app bundle.

That would probably be something like:

```xml
<ItemGroup>
    <RuntimeHostConfigurationOption Include="ICU_DAT_FILE_PATH" Value="Contents/MonoBundle/icudt.dat" />
</RuntimeHostConfigurationOption>
```

We could probably do that for all architectures, and remove the current ICU_DAT_FILE_PATH logic in runtime.m

**Comment by lemonmojo** [comment]
@rolfbjarne @filipnavara

I'm the maintainer of [Beyond.NET](https://github.com/royalapplications/beyondnet) and am currently looking into [fixing this](https://github.com/royalapplications/beyondnet/issues/53).

Now I am able to get a NativeAOT'd library to correctly locate the icudt.dat in an iOS app bundle.
However, I can't get it to work when running an XCTest bundle. Looking at [the fix](https://github.com/dotnet/runtime/pull/87813/files) you mentioned this seems to be implemented using `-[NSBundle mainBundle]`. So while this works for an app bundle, it unfortunately yields an incorrect path in a XCTest bundle and in turn fails to load the icudt.dat.

```swift
let mainPath = Bundle.main.bundlePath
// /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Agents

let testPath = Bundle(for: SomeTypeInTheTestBundle.self).bundlePath
// ~/Library/Developer/Xcode/DerivedData/TestBundle/Build/Products/Variant-ASan/Debug-iphonesimulator/TestBundle.xctest
```

So while the current fix is good, it's not a silver bullet.
Unfortunately I currently have no good idea for how this can be implemented in a generic way that also supports XCTest bundles.

**Comment by ivanpovazan** [comment]
Fixed with https://github.com/xamarin/xamarin-macios/commit/bf77022512b4b23c02dfee72abe88dd0304006b0
