### ISSUE TITLE
NativeAOT: investigate whether we still need separate min OS versions

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18477]
Check if this:

https://github.com/xamarin/xamarin-macios/pull/17374/commits/6b3d62b84d78ea2a94b3de578fa78318a9524421

is still needed after:

https://github.com/dotnet/runtime/commit/f42efaa182270c101e9a39d0ffb38357c8bfbcb5

Ref: https://github.com/xamarin/xamarin-macios/pull/17374#discussion_r1235540708

**Comment by ivanpovazan** [comment]
Fixed by https://github.com/xamarin/xamarin-macios/commit/d576b4d988b39bf118e0468915692b25f3c2b263
