### ISSUE TITLE
NativeAOT: stop shipping assemblies

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18472]
From: https://github.com/xamarin/xamarin-macios/pull/17374#issuecomment-1591862632:

I know this is still WIP but wanted to draw attention to one thing.

- With the current setup the bundle still includes all the assemblies, which are not needed with NativeAOT.
As we do not use NativeAOT targets from https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Publish.targets we have to manually exclude those files. For reference I achieved this with a custom target: 
https://github.com/ivanpovazan/xamarin-macios/commit/98a8f4e9c6feb7883ba220d4200c3015f67a5ad2#diff-2e24f1b6f44df7580244d00f106fa1a9e2257536fbca9d7bbdc74571549324a9R1172-R1178
but there is probably a cleaner way of doing it.

- Additionally, once assemblies are removed from the bundle additional changes have to be done in the native part of the runtime as it currently follows codepaths which assume assemblies are present in the bundle causing the app to crash  during early startup. To be more specific:
    - `xamarin_bridge_register_product_assembly` has to be guarded in `coreclr-bridge.m` for example: https://github.com/ivanpovazan/xamarin-macios/commit/98a8f4e9c6feb7883ba220d4200c3015f67a5ad2#diff-6e15dd2bc3a656eafdaed8fc01cf1bc69efd7acd459e13680956adebf661366fR563-R567
    - prevent `xamarin_open_and_register` of being called from `xamarin_main`:
https://github.com/ivanpovazan/xamarin-macios/commit/98a8f4e9c6feb7883ba220d4200c3015f67a5ad2#diff-463ea10e390971f1d926d16f4dd9ed5bbfac4fd81d942b4f17eb0476d1c2d4e6R444-R467

**Comment by ivanpovazan** [comment]
Fixed by: https://github.com/xamarin/xamarin-macios/commit/bcb8e5cfd3bc80fb05a30ac01fec67e582e77cb2
