### ISSUE TITLE
NativeAOT: investigate whether setting IlcKeepManagedDebuggerSupport is still needed

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18478]
Check if this is needed:

[`fb1f26b` (#17374)](https://github.com/xamarin/xamarin-macios/pull/17374/commits/fb1f26b58144fb57eeb8c842f6c578187b05e5fe)

after:

https://github.com/dotnet/runtime/commit/652433bfe9858f7f4d6f6ffcf0c994cb9b91e482

Ref: https://github.com/xamarin/xamarin-macios/pull/17374#discussion_r1235547251

**Comment by ivanpovazan** [comment]
Fixed with https://github.com/xamarin/xamarin-macios/commit/53ff85f67cc020f8a0897d581e67afe2c13083fc
