### ISSUE TITLE
NativeAOT: investigate whether we still need workaround for tvOS

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18481]
Investigate whether we still need:

[`573ef2e` (#17374)](https://github.com/xamarin/xamarin-macios/pull/17374/commits/573ef2ece3c5c0680c171e4f33be2c5e9415a260)

after:

https://github.com/dotnet/runtime/pull/87605

Ref: https://github.com/xamarin/xamarin-macios/pull/17374#discussion_r1235755406

**Comment by ivanpovazan** [comment]
Fixed by: https://github.com/xamarin/xamarin-macios/commit/29f8bd7a904adb5a77f4fbb6968829dce21f6098
