### ISSUE TITLE
NativeAOT: investigate whether we want to pull in linker features from ILC build logic and pass to ILLinker

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18480]
Ref: https://github.com/xamarin/xamarin-macios/pull/17374#discussion_r1235730787

We might want to pass the following options to ILLinker:

https://github.com/dotnet/runtime/blob/0b263953a25136283d3ac45a174b82e49a562aa1/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L271-L273

**Comment by ivanpovazan** [comment]
This has been fixed on dotnet/runtime side via: 
- https://github.com/dotnet/runtime/commit/57aeadb897fbb75d0e8c772220565f62a335dc57
- https://github.com/dotnet/runtime/commit/8c96dd2f12a9ac57abb40e9c2c8539535dc1f824

The remaining `CanEmitObjectArrayDelegate` private feature switch is automatically passed to ILLink, as it is now being added to `RuntimeHostConfigurationOption` by importing NativeAOT build integration targets
