### ISSUE TITLE
Investigate whether we can set ILC/ILLinker feature flags using RuntimeHostConfigurationOption

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18483]
Ref: https://github.com/xamarin/xamarin-macios/pull/17374#discussion_r1236308687

Look into whether we can change this:

```xml
<PropertyGroup>
	<!-- Set the features for ILLink -->
	<_ExtraTrimmerArgs>$(_ExtraTrimmerArgs) --feature ObjCRuntime.Runtime.Arch.IsSimulator $(_IsSimulatorFeature)</_ExtraTrimmerArgs>
	<_ExtraTrimmerArgs>$(_ExtraTrimmerArgs) --feature ObjCRuntime.Runtime.IsManagedStaticRegistrar $(_IsManagedStaticRegistrarFeature)</_ExtraTrimmerArgs>
	<_ExtraTrimmerArgs>$(_ExtraTrimmerArgs) --feature ObjCRuntime.Runtime.IsNativeAOT $(_IsNativeAOTFeature)</_ExtraTrimmerArgs>
</PropertyGroup>

<ItemGroup>
	<!-- Set the features for ILC -->
	<IlcArg Include="--feature:ObjCRuntime.Runtime.Arch.IsSimulator=$(_IsSimulatorFeature)" />
	<IlcArg Include="--feature:ObjCRuntime.Runtime.IsManagedStaticRegistrar=$(_IsManagedStaticRegistrarFeature)" />
	<IlcArg Include="--feature:ObjCRuntime.Runtime.IsNativeAOT=$(_IsNativeAOTFeature)" />
</ItemGroup>
```

from here: [`f39d80b` (#17374)](https://github.com/xamarin/xamarin-macios/pull/17374/commits/f39d80bb626ef68b35a2467a56aaeab6b2c75536)

to using RuntimeHostConfigurationOption items:

https://github.com/dotnet/sdk/blob/20b2949041a3cb8ab5f4a4c030ed280540b94e4f/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L485-L488

and that should hopefully work for both ILC and ILLinker.

**Comment by ivanpovazan** [comment]
Fixed with https://github.com/xamarin/xamarin-macios/commit/fa0600133576beeaa945f811873ab4b4a1901a3f
