### ISSUE TITLE
Compilation against Xcode 15 / iOS 17 -> missing NewsstandKit.h

### ISSUE THREAD

**Issue by vogtadi** [xamarin/xamarin-macios#18493]
Tried to compile an existing iOS Project to be tested on iOS 17, using Xcode 15.

No compatible Xamarin iOS found, so using 16.4.0.6, which is probably the issue (due to changes in the iOS API´s).

Any way to compile an app against Xcode 15 / iOS 17 for now?

### Steps to Reproduce

1. Install Xcode 15 b2
2. Load an Existing VS Project for iOS
3. Compile

### Expected Behavior

Code compiles to a working binary

### Actual Behavior

Received Error
MTOUCH : error MT4109: Failed to compile the generated registrar code. 

### Environment

<details>
<summary>Version information</summary>
Visual Studio Community 2022 for Mac
Version 17.6 (build 1575)
Installation UUID: cafc4817-6d04-4ab4-844c-ab870874bc81

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.304/Sdks
SDK Versions:
	7.0.304
	6.0.410
	6.0.407
	6.0.302
	6.0.300
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.410
	6.0.407
	6.0.302
	6.0.300
	6.0.105
	6.0.104
	6.0.103
	6.0.102
	6.0.101
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	3.1.426
	3.1.421
	3.1.419
	3.1.418
	3.1.417
	3.1.416

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.7
	6.0.18
	6.0.15
	6.0.7
	6.0.5

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.18
	6.0.15
	6.0.7
	6.0.5
	6.0.4
	6.0.3
	6.0.2
	6.0.1
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	3.1.32
	3.1.27
	3.1.25
	3.1.24
	3.1.23
	3.1.22

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-06-14 17:05:55 UTC

Xamarin.Android
Version: 13.2.0.6 (Visual Studio Community)
Commit: xamarin-android/d17-5/a200af1
Android SDK: /Users/handycash/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		11.0 (API level 30)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 33.0.1

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.362
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-06-14 17:06:00 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-06-14 17:06:00 UTC

Apple Developer Tools
Xcode: 15.0 22181.22
Build: 15A5161b

Xamarin.Mac
Version: 9.3.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:35-0400

Xamarin.iOS
Version: 16.4.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400

Build Information
Release ID: 1706001575
Git revision: d32bcc352feed2f1f54e237e23e5c375d86eaf9e
Build date: 2023-06-14 17:04:07+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.4.1
Darwin 22.5.0 Darwin Kernel Version 22.5.0
    Thu Jun  8 22:22:19 PDT 2023
    root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64

</details>

### Build Logs

relevant section (Note: i am NOT actually using the NewsstandKit in the project):

<details>
<summary>Build Output (with reference to NewsstandKit.h)</summary>

Target _WriteAppManifest:
    Directory "bin/iPhone/Debug/Handycash.iOS.app.dSYM" doesn't exist. Skipping.
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/handycash/Development/handycash/hc_mobile_app/App/Regular-Phone/iOS/obj/iPhone/Debug/response-file.rsp 
    Xamarin.iOS 16.4.0.6 (xcode14.3: 97731c92c) using framework: /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk
    		
    		
    		
    		
    		
    Compilation failed with code 1, command:
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wno-receiver-forward-class -Wno-objc-missing-super-calls -Wno-unguarded-availability-new -stdlib=libc++ -gdwarf-2 -std=c++14 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.6/SDKs/MonoTouch.iphoneos.sdk/include -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk -Qunused-arguments -miphoneos-version-min=11.0 -arch arm64 -c -o /Users/handycash/Development/handycash/hc_mobile_app/App/Regular-Phone/iOS/obj/iPhone/Debug/mtouch-cache/arm64/registrar.o -x objective-c++ -D DEBUG /Users/handycash/Development/handycash/hc_mobile_app/App/Regular-Phone/iOS/obj/iPhone/Debug/mtouch-cache/registrar.m
    In file included from /Users/handycash/Development/handycash/hc_mobile_app/App/Regular-Phone/iOS/obj/iPhone/Debug/mtouch-cache/registrar.m:3:
    /Users/handycash/Development/handycash/hc_mobile_app/App/Regular-Phone/iOS/obj/iPhone/Debug/mtouch-cache/registrar.h:32:9: fatal error: 'NewsstandKit/NewsstandKit.h' file not found
    #import <NewsstandKit/NewsstandKit.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    MTOUCH : error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
Done building target "_CompileToNative" in project "Handycash.iOS.csproj" -- FAILED.

</details>

### Example Project (If Possible)
NA

**Comment by rolfbjarne** [comment]
> Any way to compile an app against Xcode 15 / iOS 17 for now?

It _might_ work if you enable the linker by adding this into your project file:

```xml
<MtouchLink>Full</MtouchLink>
```

If that doesn't work, you'll have to use Xcode 14.3 (or earlier).

We're working on shipping preview packages that support Xcode 15, but it still some ways off.

**Comment by JohnHSE** [comment]
@rolfbjarne did I read that correctly, MS will update Xamarin to support Xcode 15? That's going to make a lot of people very, very happy if so.

**Comment by rolfbjarne** [comment]
> @rolfbjarne did I read that correctly, MS will update Xamarin to support Xcode 15? That's going to make a lot of people very, very happy if so.

No, as Alex Soto explained [here](https://github.com/xamarin/xamarin-macios/issues/18409#issuecomment-1599201944), only .NET will get Xcode 15 support.

**Comment by RobTF** [comment]
@JohnHSE in the thread @rolfbjarne has linked to there is an ongoing discussion about this - you might want to add your thoughts there to keep the discussion going as your experience is similar to many others in said thread.

**Comment by RobSchoenaker** [comment]
Use MTouch arguments:

`--weak-framework=NewsstandKit.framework/NewsstandKit`

**Comment by vogtadi** [comment]
Thanks. Adding the ''--weak-framework'' worked to have it start up on iOS 17 again.

To address potential misunderstandings. You have to compile using Xcode 14 and deploy. Compiling using Xcode 15 still results in the missing NewsstandKit.h

**Comment by gfelberbaum** [comment]
Unable to compile after adding the above  Mtouch arguments.  I am  now getting error. /Users/gary/Documents/Projects/Midpoint/Midpoint.iOS/MTOUCH: Error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new (MT4109) (Midpoint.iOS)

**Comment by MiKayule** [comment]
According to official [iOS & iPadOS 17 Release Notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-17-release-notes#Newsstand), NewsstandKit is a deprecated feature and has been removed.
