### ISSUE TITLE
NativeAOT: IlcRPath gets incorrectly quoted

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#18531]
The final executable gets LC_RPATH set to `'@executable_path'` because LinkerArg from NativeAOT is `-Wl,-rpath,'$(IlcRPath)'` and the [de-quoting logic](https://github.com/xamarin/xamarin-macios/blob/7ed8c08ab0c2080124e171da835506fcfc21c967/dotnet/targets/Xamarin.Shared.Sdk.targets#L1243-L1314) doesn't seem to handle it well.

**Comment by rolfbjarne** [comment]
This would be fixed with the fix for https://github.com/xamarin/xamarin-macios/issues/18819.

**Comment by rolfbjarne** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/commit/88b009288d2057fdd8bccdd9e5d55127c18a2568.
