### ISSUE TITLE
MvvmCross(7.1.2, 8.0.2), Plugin.Permissions(6.0.1) are not working with .Net6.0, Microsoft.iOS.SDK MAUI

### ISSUE THREAD

**Issue by devikarna** [xamarin/xamarin-macios#18534]
Getting [This functionality is not implemented in the portable version of this assembly](https://stackoverflow.com/questions/50706824/xamarin-forms-xam-plugin-media-throwing-error-this-functionality-is-not-implem)

**Comment by beeradmoore** [comment]
Unless you are asking something else and I am not following, you need to file that issue with the respective repositories.

MvvmCross you can find them [here](https://github.com/MvvmCross/MvvmCross).
Plugin.Permissions you can find them [here](https://github.com/jamesmontemagno/PermissionsPlugin), however that library is now archived and the functionality is built directly into MAUI. There is some notes on the above repo, but also docs on that [here](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/permissions).

**Comment by dalexsoto** [comment]
> Unless you are asking something else and I am not following, you need to file that issue with the respective repositories.
> 
> MvvmCross you can find them [here](https://github.com/MvvmCross/MvvmCross). Plugin.Permissions you can find them [here](https://github.com/jamesmontemagno/PermissionsPlugin), however that library is now archived and the functionality is built directly into MAUI. There is some notes on the above repo, but also docs on that [here](https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/appmodel/permissions).

As @beeradmoore mentioned this doesn't seem to be an in issue on the SDK itself, please open an issue in the appropriate repo.
