### ISSUE TITLE
Remote archiving failed (Visual Studio, Windows)

### ISSUE THREAD

**Issue by alex-dubatov** [xamarin/xamarin-macios#18540]
### Steps to Reproduce

1. Remote building Xamarin Ios project ends successful.

2. Remote archiving Xamarin Ios project failed, got error (ServerUser and ServerAddress replaced with fakes):

```
Build properties for C:\Users\Admin\Documents\repositories\ff\FF.Mobile\FF.Mobile\FF.Mobile.iOS\FF.Mobile.iOS.csproj: VisualStudioProcessId: 35356, SolutionPath: C:\Users\Admin\Documents\repositories\ff\FF.Mobile\FF.Mobile.sln, SolutionName: FF.Mobile, RunConfiguration: Default, ArchiveOnBuild: False, ArchivePath: , IsAppDistribution: False, DeviceSpecificBuild: false, TargetiOSDevice: , IsHotRestartBuild: False, MessagingVersion: 17.6.0.251, _DotNetRootRemoteDirectory: /Users/user123456\Library\Caches\Xamarin\XMA\SDKs\dotnet/, ServerSshPort: 22, ServerTcpPort: 51470, ServerUser: user123456, ContinueOnDisconnected: False, ServerAddress: 12.34.56.78
Cannot create an IOS archive 'FF.Mobile.iOS'. Process cannot be executed on XMA server.
Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
```

Preisously archived commits also failed to archive now.

### Expected Behavior
Remote archiving Xamarin Ios project ends successful

### Actual Behavior
Got error

### Environment

Windows: 
* Visual Studio 17.6.4 (17.6.2)

MacOs Ventura 13.4.1 (remote):
* Visual Studio 17.6.0.1575
* Xcode 14.3.1 (14E300c)

Note that on remote mac I have many versions of XCode:
14.0, 14.0.1, 14.1, 14.2, 14.3, 14.3.1

**Comment by dalexsoto** [comment]
Thanks for the report, this seems to be an issue in the extension, could you please follow the steps above so it can reach the right team? Thank you!
