### ISSUE TITLE
Record Video use AVAssetWriterInput contruct error [AVAssetWriterInput initWithMediaType:outputSettings:sourceFormatHint:] Output settings dictionary is valid

### ISSUE THREAD

**Issue by xufeitt** [xamarin/xamarin-macios#18550]
App record video.

Use AVCaptureSession + AVAssetWriter

#if IOS  
     try
        {
            AVVideoSettingsCompressed videoSettings = new AVVideoSettingsCompressed()
            {
                Width = 720,
                Height = 1080,
                Codec = AVVideoCodec.H264,
                CodecSettings = new AVVideoCodecSettings
                {
                    AverageBitRate = 6 * 1080 * 720
                }

            };
            AVAssetWriterInput assetVideoInput = new AVAssetWriterInput("video", videoSettings);
        }
        catch (Exception ex) 
        {
            string err = ex.Message;
        }
#endif
when AVAssetwriterInput construct will raise exception

[AVAssetWriterInput initWithMediaType:outputSettings:sourceFormatHint:] Output settings dictionary is valid

I had try many method, i have no ideal now. any useful help ?

If follow the exception Output settings dictionary is valid

AVAssetWriterInput(String, NSDictionary) is protected, so i can't use it.

AVAssetWriterInput(String, NSDictionary)

[Foundation.Export("initWithMediaType:outputSettings:")] protected AVAssetWriterInput (string mediaType, Foundation.NSDictionary outputSettings);

[https://learn.microsoft.com/zh-cn/dotnet/api/avfoundation.avassetwriterinput.-ctor?view=xamarin-ios-sdk-12#avfoundation-avassetwriterinput-ctor(system-string-foundation-nsdictionary)](https://learn.microsoft.com/en-us/dotnet/api/avfoundation.avassetwriterinput.-ctor?view=xamarin-ios-sdk-12#avfoundation-avassetwriterinput-ctor(system-string-foundation-nsdictionary))

**Comment by BleuBleu** [comment]
In case someone else has this issue. 

The problem is that OP is passing `"video"` as the media type. The actual value should be `"vide"`. 

To avoid this kind of error, its probably better to get the constant from :
```
var mediaType = AVMediaTypesExtensions.GetConstant(AVMediaTypes.Video).ToString(); // Will be "vide"
```
