### ISSUE TITLE
M1 Mac Abort Problems

### ISSUE THREAD

**Issue by PolandballMaster** [xamarin/xamarin-macios#18592]
### Steps to Reproduce

1. Do cd downloads/UnityModManagerInstaller
2. Run mono UnityModManager.exe
3. 

### Expected Behavior

Run the exe file

### Actual Behavior
Aborts the whole thing instead. Last message is: zsh: abort      mono UnityModManager.exe

So the problem I have is that I can't run an .exe file because it always aborts when I run it. There is also another message that appears before the abort, which reads: WARNING: The Carbon driver has not been ported to 64bits, and very few parts of Windows.Forms will work properly, or at all

Also, mono-sgen64 crashes after the abort message. Anyone know how to fix this?

**Comment by rolfbjarne** [comment]
This issue was moved to mono/mono#21689
