### ISSUE TITLE
NativeAOT: re-enable dead stripping

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18605]
We've disabled passing -dead_strip to ld for NativeAOT:

* https://github.com/xamarin/xamarin-macios/issues/18552
* https://github.com/xamarin/xamarin-macios/pull/18553

It should be re-enabled once this is fixed:

* https://github.com/dotnet/runtime/issues/88032

**Comment by ivanpovazan** [comment]
Once https://github.com/dotnet/runtime/commit/d9a66070026c9133fade4e61a60d00aec170bfc4 flows in, we should try enable `-dead_strip` by default with NativeAOT.

**Comment by ivanpovazan** [comment]
> Is xamarin-macios still using ld_classic? then I assume it'd still be affected by https://github.com/dotnet/runtime/issues/88032

Yes `ld_classic` is still used (this will have to be fixed as the option is getting removed by Apple in XCode 16).

https://github.com/dotnet/runtime/issues/88032 reported an issue that occasionally `monotouch-test` crashes the platform linker. However, at that time object file produced by NativeAOT was not marking all symbols as non-strippable.

The idea is try turning `-dead_strip` back on and track if it is going to cause failures.

**Comment by rolfbjarne** [comment]
Fixed in #20796.
