### ISSUE TITLE
NET7.0: Accessing ObjCRuntime namespace for native library wrappers

### ISSUE THREAD

**Issue by projectgoav** [xamarin/xamarin-macios#18615]
This is more of a question rather than an issue.

Currently, we build a C# wrapper around our native library. This is built with mono using the following command line options:
```
mono_lib_dir=/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS
mcs .... /define:IOS /r:$(mono_lib_dir)/Xamarin.iOS.dll
```

Obviously this is referencing the old Xamarin.iOS framework which can't be used in a `net6.0-ios`+ application. 

I have found `Microsoft.iOS.dll` which seems to be the replacement which lives at `<dotnet_dir>/packs/Microsoft.iOS.Ref/<version>/ref/net7.0`. This path seems pretty brittle as it will change with every dotnet and workflow update. 

Is there such a thing as the `Versions/Current....` path like before or are there recommendations for the best path to use?

I mainly need access to the `ObjCRuntime` namespace specifically for some `PInvoke` (`MonoPInvokeCallback`) stuff. Knowing this, is there a better solution to my problem rather than pointing towards the whole Microsoft.iOS.dll?

**Comment by rolfbjarne** [comment]
Any reason you can't build your C# code using a library project (with the `net7.0-ios` TargetFramework)?

**Comment by projectgoav** [comment]
Hmm...

A lot of the C# code is auto-generated. I think we didn't have a csproj before as it had to list all the required files which could change each time we build.

With the newer SDK style projects, we could have a project file that picks up all the generated stuff in a directory and build with the required target. 

Think that should work... Sorry, I seem to have used you as a sounding board.
