### ISSUE TITLE
.NET7.0: The using alias 'nfloat' appeared previously in this namespace

### ISSUE THREAD

**Issue by projectgoav** [xamarin/xamarin-macios#18628]
Say you have a project - Project2.
This project relies on another - Project1 - which is found in the parent directory. 

The directory structure looks like:

```
Project
|- Proj1.csproj
|- ....
|- ProjectTwo
    |- Proj2.csproj
    |- .....
```

`dotnet build Proj1.csproj --framework=net7.0-ios` => Completes successfully
`dotnet build ProjectTwo/Proj2.csproj --framework=net7.0-ios` => Fails.

```
Proj1.nfloat.g.cs(2,14): error CS1537: The using alias 'nfloat' appeared previously in this namespace [/Users/ewanm/Projects/NFloat/Proj1.csproj::TargetFramework=net7.0-ios]
```

[NFloat.zip](https://github.com/xamarin/xamarin-macios/files/12250079/NFloat.zip)

[NFloat.msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/12250087/NFloat.msbuild.binlog.zip)

**Comment by projectgoav** [comment]
Seem like it's a problem relating to nested `obj/` folders. Adding `<IntermediateOutputPath>../obj</IntermediateOutputPath>` to `Proj2` fixes the issue.

Is this a known limitation of `dotnet build` ?

**Comment by rolfbjarne** [comment]
> Is this a known limitation of `dotnet build` ?

It's a consequence of how files are [automatically included in the project](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#default-item-inclusion-properties).

Any \*.cs files are included in the build, except files in bin/\* and obj/\*. This means that Proj1.csproj will include files in ProjectTwo/obj/**/*.cs, and that's not expected, so in this case that ends up with a compiler error.

There are two potential solutions:

1. Don't put a project directory inside another, always make them sibling directories.
2. [Disable default item inclusion](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enabledefaultitems), by setting `EnableDefaultItems=false` in your csproj.
