### ISSUE TITLE
[Bug] Wrong print size error when using the PrintToPrinter function for the second time

### ISSUE THREAD

**Issue by hauvudinh24** [xamarin/xamarin-macios#18639]
Currently we are using the Xamarin iOS app to print from 1 existing html text. But when using Air Printer, the first print is perfect until the second print is not as expected. The print is white and has a very long stretch

### Steps to Reproduce

1. Open a binding project
2. Add the following code

  ```
void IPrinter.PrintFromHtml()
        {
            var uiPrinter = UIPrinter.FromUrl(new NSUrl("ipp://BRW8CC84B1C9733.local.:631/ipp/print"));
            var page = "<html>\n  <head>\n    <style>\n      @font-face {\n     just: exact;\n        font-family: \"Manrope\";\n  ";
            var formatter = new UIMarkupTextPrintFormatter(page);
            formatter.PerPageContentInsets = UIEdgeInsets.Zero;

            var renderer = new UIPrintPageRenderer();
            renderer.AddPrintFormatter(formatter,  0);

            var controller = UIPrintInteractionController.SharedPrintController;
            var printInfo = UIPrintInfo.PrintInfo;
            printInfo.JobName = "Print";
            printInfo.OutputType = UIPrintInfoOutputType.General;

            controller.PrintInfo = printInfo;
            controller.PrintPageRenderer = renderer;
            controller.ShowsPaperSelectionForLoadedPapers = true;

          
            controller.PrintToPrinter(uiPrinter, (printInteractionController, completed, error) =>
                    {
                        printInfo?.Dispose();
                        uiPrinter?.Dispose();
                    });

        }
```

### Expected Behavior

The printout is not stretched

### Actual Behavior

The printout is stretched from the 2nd printing onwards

![image 56](https://github.com/xamarin/xamarin-macios/assets/128805320/5ad69a51-6631-4c9d-8f89-cc1934f5f673)

### Environment

> Visual Studio Community 2022 for Mac
> Version 17.6.1 (build 452)
> Installation UUID: 2c19f436-a0f4-4405-b059-1206816fd6f6
> 
> Runtime
> .NET 7.0.3 (64-bit)
> Architecture: X64
> Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2
> 
> Roslyn (Language Service)
> 4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa
> 
> NuGet
> Version: 6.4.0.117
> 
> .NET SDK (x64)
> SDK: /usr/local/share/dotnet/sdk/7.0.306/Sdks
> SDK Versions:
> 	7.0.306
> 	6.0.412
> MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks
> 
> .NET Runtime (x64)
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Versions:
> 	7.0.9
> 	6.0.20
> 
> Xamarin.Profiler
> Version: 1.8.0.49
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> Updater
> Version: 11
> 
> Apple Developer Tools
> Xcode: 14.3.1 21815
> Build: 14E300c
> 
> Xamarin.Mac
> Not Installed
> 
> Xamarin.iOS
> Version: 16.4.0.6 Visual Studio Community
> Hash: 97731c92c
> Branch: xcode14.3
> Build date: 2023-04-11 22:38:36-0400
> 
> Xamarin Designer
> Version: 17.6.3.9
> Hash: 2648399ae8
> Branch: remotes/origin/d17-6
> Build date: 2023-07-06 12:50:50 UTC
> 
> Xamarin.Android
> Not Installed
> 
> Microsoft Build of OpenJDK
> Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
> 11.0.16.1
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> Eclipse Temurin JDK
> Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
> 1.8.0.302
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> Android SDK Manager
> Version: 17.6.0.50
> Hash: a715dca
> Branch: HEAD
> Build date: 2023-07-06 12:50:55 UTC
> 
> Android Device Manager
> Version: 0.0.0.1309
> Hash: 06e3e77
> Branch: HEAD
> Build date: 2023-07-06 12:50:55 UTC
> 
> Build Information
> Release ID: 1706010452
> Git revision: 9c61cec4d4c4498378f5878b08459d6fd258659d
> Build date: 2023-07-06 12:49:21+00
> Build branch: release-17.6
> Build lane: release-17.6
> 
> Operating System
> Mac OS X 13.4.0
> Darwin 22.5.0 Darwin Kernel Version 22.5.0
>     Mon Apr 24 20:51:50 PDT 2023
>     root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

**Comment by hauvudinh24** [comment]
Can you double-check the printToPrinter function of Xamarin.iOS? I find it quite different from Swift's print function. You can check this GitHub [link](https://github.com/DavBfr/dart_pdf/blob/master/printing/ios/Classes/PrintJob.swift). The Flutter demo project is working pretty well using Swift's print function. I have attached an HTML file for printing. Hope this can help you.

**Comment by rolfbjarne** [comment]
> Can you double-check the printToPrinter function of Xamarin.iOS? I find it quite different from Swift's print function.

Are you talking about the call to print here:

https://github.com/DavBfr/dart_pdf/blob/90ad7680b75d53fce3ef9793d2b46c2eb1f30c9f/printing/ios/Classes/PrintJob.swift#L208

```swift
controller.print(to: selectedPrinters[printerURLString]!, completionHandler: self.completionHandler)
```

vs your call to PrintToPrinter:

```cs
controller.PrintToPrinter(uiPrinter, (printInteractionController, completed, error) => { ... });
```

?

In any case, please attach a complete test project we can use to reproduce the issue, so that we can make sure to test the exact same setup you're using.

**Comment by hauvudinh24** [comment]
> In any case, please attach a complete test project we can use to reproduce the issue, so that we can make sure to test the exact same setup you're using.

Hi. Hope you're well.
I have created a sample project [here](https://github.com/hauvudinh24/demo-print/blob/main/test/test.iOS/Service/PrintJob.cs). In the sample project, I used the Present function so you can visually see the problem: Before you format the information from the printer, the print sample when reviewing the preview from the printer is very accurate. But then the preview from the printer is a stretch of blank space. I guess it also has something to do with the printToPrinter function when printing over the top it's correct but from the 2nd it doesn't work as expected.
Thank you. Hope this information helps you.

**Comment by rolfbjarne** [comment]
I tried your sample project, but I'm not sure what you expect.

I get a single page in the preview when printing:

![Screenshot 2023-08-17 at 13 51 25](https://github.com/xamarin/xamarin-macios/assets/249268/eee574f0-5015-43d9-94b2-66d5f786374d)

**Comment by hauvudinh24** [comment]
> I tried your sample project, but I'm not sure what you expect.
Hi.
Please select the printer. And the error will start from here. Before you choose the printer, the print format will be correct, but when the printer is selected, the print format will be wrong.
Than you.

**Comment by rolfbjarne** [comment]
I don't really see much of a difference:

![Screenshot 2023-08-22 at 13 42 03](https://github.com/xamarin/xamarin-macios/assets/249268/89de4666-c59c-4f7a-8113-2cebe7ca7c4f)

Can you attach screenshots of before and after choosing a printer?

**Comment by hauvudinh24** [comment]
![Group 43305](https://github.com/xamarin/xamarin-macios/assets/128805320/5ad3418e-883a-40fa-ac4a-54f24658540a)

Yes, I can. But I saw your screenshots have many options like print color, double-sided, etc. Do you run my demo?

**Comment by rolfbjarne** [comment]
> But I saw your screenshots have many options like print color, double-sided, etc. Do you run my demo?

Yes, I ran your demo. I'm guessing my additional options show up because I have a different printer (that supports color and double-sided printing).

I noted that your printer's preview doesn't have an option for "Paper Size" - and I wonder if that has something to do with the problem (if iOS picks a weird default size, it could explain the narrow preview you're seeing).

Do you get an option to select "Paper Size" when trying to print to the same printer anywhere else in iOS?

**Comment by hauvudinh24** [comment]
> Do you get an option to select "Paper Size" when trying to print to the same printer anywhere else in iOS?

No, I don't.

**Comment by rolfbjarne** [comment]
> > Do you get an option to select "Paper Size" when trying to print to the same printer anywhere else in iOS?
> 
> No, I don't.

I'm not sure what we can do here, since this seems specific to your printer.

* Do you have another printer you can try with?
* Do you get the same behavior both in the simulator and on a device?
* Have you tried from another Mac and/or iOS device?

**Comment by hauvudinh24** [comment]
> * Do you have another printer you can try with?
> * Do you get the same behavior both in the simulator and on a device?
> * Have you tried from another Mac and/or iOS device?

- Yes, I have tried another printer but it does not work as expected
- Yes, I do. I have tried in device iPhone and iPad
- Yes

I think issues make by the default paper size. When I tried Project Flutter I saw it can auto-selected paper size When I selected printer

**Comment by rolfbjarne** [comment]
> I think issues are made by the default paper size. When I tried Project Flutter I saw it can auto-select paper size When I selected printer. Can I set the default paper size after selecting a printer?

I don't know the printing API, so unfortunately I don't know.

I think the next step would be to try to create an Xcode sample, and if that works correctly, attach it here so that I can compare with the C# code to see where we go differently.

**Comment by hauvudinh24** [comment]
> I think the next step would be to try to create an Xcode sample, and if that works correctly, attach it here so that I can compare with the C# code to see where we go differently.

Hi, I have created a [sample project](git@github.com:hauvudinh24/Demo-printer-swift.git) with Swift in Xcode. 
Hope may this help you. Thank you

**Comment by hauvudinh24** [comment]
reopen

**Comment by rolfbjarne** [comment]
Is this the sample project: https://github.com/hauvudinh24/Demo-printer-swift?

**Comment by hauvudinh24** [comment]
> Is this the sample project: https://github.com/hauvudinh24/Demo-printer-swift?

Yes, correct.

**Comment by rolfbjarne** [comment]
You never call UIPrintPageRenderer.DrawPage in your Xamarin project, while you do in the Swift project, maybe that makes a difference?

I've modified the Xamarin project slightly to be more like the Swift project, can you try the closer-to-swift branch here to see if it still fails for you?

https://github.com/rolfbjarne/demo-print/commits/closer-to-swift

**Comment by hauvudinh24** [comment]
> I've modified the Xamarin project slightly to be more like the Swift project, can you try the closer-to-swift branch here to see if it still fails for you?

Thank you. In our sample project, we also use that function but it doesn't seem to work as expected. We are trying the next method. If it is stable we will get back to you.

**Comment by hauvudinh24** [comment]
> I think the next step would be to try to create an Xcode sample, and if that works correctly, attach it here so that I can compare with the C# code to see where we go differently.

Hi. Hope you are well.
I have updated the Xamarin code [here](https://github.com/hauvudinh24/demo-print). I use WKWebview to load the HTML file and listen to it when the HTML is done loading and when I have the printer data from WKWebview I have done the printing. This is the result:
When I try using the Current function to print three times, it works correctly. And the print preview is the same when I print.
When I try to use the PrintToPrinter function to print it doesn't work correctly. In the second printing, the print had gaps and was very long.
So I think the PrintToPrinter function has a big problem.

Thank you.

**Comment by rolfbjarne** [comment]
> So I think the PrintToPrinter function has a big problem.

That might be, but since the only thing the managed PrintToPrinter function does is to call into the native [printToPrinter](https://developer.apple.com/documentation/uikit/uiprintinteractioncontroller/1618174-printtoprinter?language=objc) function, I'm inclined to believe this is a bug in iOS itself then, and not Xamarin.

I see you didn't update the Swift sample: can you do that to have the exact same logic as the Xamarin sample, and see if that works or not?

**Comment by hauvudinh24** [comment]
Hi.
Yes, I will. But can I ask you something? Can you help me convert this code from Swift to Xamarin? I saw him delay 500 milliseconds after print. I think he added it to wait for the format done after printing. You can see the code [here](https://github.com/DavBfr/dart_pdf/blob/master/printing/ios/Classes/PrintJob.swift).
Thank you.

<img width="1220" alt="Screenshot 2023-09-15 at 16 34 22" src="https://github.com/xamarin/xamarin-macios/assets/128805320/5fa23016-c527-4d28-8856-c76bd31cd701">

**Comment by rolfbjarne** [comment]
You can do something like this:

```cs
NSTimer.CreateScheduledTimer (0.5, (v) => {
    // assign the print formatter to the print page renderer
    // ...
});

**Comment by hauvudinh24** [comment]
Hi.
We have updated the Xamarin sample project [here](https://github.com/hauvudinh24/demo-print). So, it is useful to use WKWebview to display HTML and stream the print to the printer.
Thank you
