### ISSUE TITLE
ios binding project with xcframework fails to link

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18688]
_From @dodikk on Tue, 07 Mar 2023 20:05:04 GMT_

### Description

Steps to Reproduce
* Download the sample project https://github.com/dodikk/themis-maui-prototype
* Build the ThemisMauiSample.sln which includes native iOS bindings created from the xcframework

Expected Behavior
The build succeeds.

Actual Behavior
The build fails with Undefined symbols for architecture arm64

### Steps to Reproduce

Steps to Reproduce
* Download the sample project https://github.com/dodikk/themis-maui-prototype
* Build the ThemisMauiSample.sln which includes native iOS bindings created from the xcframework

### Link to public reproduction project repository

 https://github.com/dodikk/themis-maui-prototype

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

ios 16

### Did you find any workaround?

No

### Relevant log output

```shell
Building target "_LinkNativeExecutable" completely.   
        Tool xcrun execution finished (exit code = 1).
                
        Undefined symbols for architecture arm64:
          "_OBJC_CLASS_$_TSCell", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellContextImprint", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellSeal", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellToken", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellTokenEncryptedData", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellTokenEncryptedResult", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSComparator", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSKeyGen", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSMessage", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSSession", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSSessionTransportInterface", referenced from:
              objc-class-ref in registrar.o
          "_TSGenerateSymmetricKey", referenced from:
             -u command line option
        ld: symbol(s) not found for architecture arm64
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```


_Copied from original issue dotnet/runtime#89633_

**Comment by rolfbjarne** [comment]
_From @dotnet-issue-labeler[bot] on Thu, 09 Mar 2023 18:19:30 GMT_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

**Comment by rolfbjarne** [comment]
_From @msftbot[bot] on Fri, 21 Jul 2023 12:49:00 GMT_

Tagging subscribers to 'os-ios': @steveisok, @akoeplinger, @kotlarmilos
See info in area-owners.md if you want to be subscribed.
<details>
<summary>Issue Details</summary>
<hr />

### Description

Steps to Reproduce
* Download the sample project https://github.com/dodikk/themis-maui-prototype
* Build the ThemisMauiSample.sln which includes native iOS bindings created from the xcframework

Expected Behavior
The build succeeds.

Actual Behavior
The build fails with Undefined symbols for architecture arm64

### Steps to Reproduce

Steps to Reproduce
* Download the sample project https://github.com/dodikk/themis-maui-prototype
* Build the ThemisMauiSample.sln which includes native iOS bindings created from the xcframework

### Link to public reproduction project repository

 https://github.com/dodikk/themis-maui-prototype

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

ios 16

### Did you find any workaround?

No

### Relevant log output

```shell
Building target "_LinkNativeExecutable" completely.   
        Tool xcrun execution finished (exit code = 1).
                
        Undefined symbols for architecture arm64:
          "_OBJC_CLASS_$_TSCell", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellContextImprint", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellSeal", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellToken", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellTokenEncryptedData", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellTokenEncryptedResult", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSComparator", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSKeyGen", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSMessage", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSSession", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSSessionTransportInterface", referenced from:
              objc-class-ref in registrar.o
          "_TSGenerateSymmetricKey", referenced from:
             -u command line option
        ld: symbol(s) not found for architecture arm64
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```


<table>
  <tr>
    <th align="left">Author:</th>
    <td>dodikk</td>
  </tr>
  <tr>
    <th align="left">Assignees:</th>
    <td>-</td>
  </tr>
  <tr>
    <th align="left">Labels:</th>
    <td>

`untriaged`, `area-VM-meta-mono`, `os-ios`

</td>
  </tr>
  <tr>
    <th align="left">Milestone:</th>
    <td>-</td>
  </tr>
</table>
</details>

**Comment by rolfbjarne** [comment]
_From @steveisok on Fri, 21 Jul 2023 12:50:49 GMT_

@dalexsoto I believe this needs transferred to the xam ios repo.

**Comment by rolfbjarne** [comment]
_From @SamMonoRT on Fri, 28 Jul 2023 13:42:56 GMT_

Transferring back to runtime repo (since Xamarin isn't the correct repo to move this issue to).

**Comment by rolfbjarne** [comment]
_From @msftbot[bot] on Mon, 31 Jul 2023 15:28:49 GMT_

Tagging subscribers to 'os-ios': @steveisok, @akoeplinger, @kotlarmilos
See info in area-owners.md if you want to be subscribed.
<details>
<summary>Issue Details</summary>
<hr />

### Description

Steps to Reproduce
* Download the sample project https://github.com/dodikk/themis-maui-prototype
* Build the ThemisMauiSample.sln which includes native iOS bindings created from the xcframework

Expected Behavior
The build succeeds.

Actual Behavior
The build fails with Undefined symbols for architecture arm64

### Steps to Reproduce

Steps to Reproduce
* Download the sample project https://github.com/dodikk/themis-maui-prototype
* Build the ThemisMauiSample.sln which includes native iOS bindings created from the xcframework

### Link to public reproduction project repository

 https://github.com/dodikk/themis-maui-prototype

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

ios 16

### Did you find any workaround?

No

### Relevant log output

```shell
Building target "_LinkNativeExecutable" completely.   
        Tool xcrun execution finished (exit code = 1).
                
        Undefined symbols for architecture arm64:
          "_OBJC_CLASS_$_TSCell", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellContextImprint", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellSeal", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellToken", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellTokenEncryptedData", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSCellTokenEncryptedResult", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSComparator", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSKeyGen", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSMessage", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSSession", referenced from:
              objc-class-ref in registrar.o
          "_OBJC_CLASS_$_TSSessionTransportInterface", referenced from:
              objc-class-ref in registrar.o
          "_TSGenerateSymmetricKey", referenced from:
             -u command line option
        ld: symbol(s) not found for architecture arm64
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```


<table>
  <tr>
    <th align="left">Author:</th>
    <td>dodikk</td>
  </tr>
  <tr>
    <th align="left">Assignees:</th>
    <td>-</td>
  </tr>
  <tr>
    <th align="left">Labels:</th>
    <td>

`untriaged`, `area-VM-meta-mono`, `os-ios`

</td>
  </tr>
  <tr>
    <th align="left">Milestone:</th>
    <td>-</td>
  </tr>
</table>
</details>

**Comment by rolfbjarne** [comment]
_From @SamMonoRT on Mon, 31 Jul 2023 23:21:07 GMT_

> > Transferring back to runtime repo (since Xamarin isn't the correct repo to move this issue to).
> 
> Did you find this is something we can fix in runtime?

No, moved it to xamarin repo and not the right XI repo. Not sure how to do so.

**Comment by rolfbjarne** [comment]
_From @SamMonoRT on Mon, 31 Jul 2023 23:22:05 GMT_

@dalexsoto @mandel-macaque - please take a look again. Doesn't seem like a runtime issue.

**Comment by rolfbjarne** [comment]
@dodikk 

The provided test project builds fine for me, both for device and the simulator.

Could you please provide a binlog that shows the build error on your side?

See https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs for how to get a binlog.

**Comment by kapilntt** [comment]
For the people encountering this issue, here is my observation that will take you one step forward till you encounter the next thing.
In my opinion, the issue is related to the binding project not compiling (linking) all external frameworks into the binding DLL. Earlier in Xamarin, the binding DLL used to be 12MB which is now 45KB. 

As a temporary step, you should copy all the following three into your Maui project 
* yourbinding.dll
* yourbinding.resources
* yourbidning.resources.stamp

This will at least allow you to compile your head projects. Once you go through this, you may encounter https://github.com/xamarin/xamarin-macios/issues/18761

**Comment by Youssef1313** [comment]
@rolfbjarne Not sure if this is the same issue, but https://github.com/unoplatform/uno/issues/13416 has a binlog.

**Comment by rolfbjarne** [comment]
@Youssef1313 no, that's a different issue (I commented on that issue).

Re-marking as need-info, re: https://github.com/xamarin/xamarin-macios/issues/18688#issuecomment-1672589130

**Comment by akghasemi** [comment]
I have the same issue with binding xcframework library, when building the library everything works fine but as I want to use it in my project, I get the same error above, is there any workaround for this ?

**Comment by rolfbjarne** [comment]
@akghasemi please file a new issue and attach an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) and we'll have a look.

**Comment by akghasemi** [comment]
@rolfbjarne Thanks for your response . I have created #21142
