### ISSUE TITLE
[Xcode 15] Check if we still need to force the classic/ld64 linker

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18693]
As description says.

Ref:

* [`4669ae9` (#18440)](https://github.com/xamarin/xamarin-macios/pull/18440/commits/4669ae95dd3e57deae6b2829bbd88edb1728a52c)
* https://github.com/xamarin/xamarin-macios/pull/18719

**Comment by filipnavara** [comment]
JFYI https://github.com/dotnet/runtime/issues/97745#issuecomment-1925915381

**Comment by rolfbjarne** [comment]
Fixed.
