### ISSUE TITLE
Hot Restart is not automatically including .frameworks

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#18729]
### Steps to Reproduce

1. File | New | Maui project
2. Install SkiaSharp.Views.Maui.Controls
3. Build
4. Observe the final app does not have the libSkiaSharp.framework

Looking at the log, I think the code is in the `ComputeBundleLocation` task: 

https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.MacDev.Tasks/Tasks/ComputeBundleLocationTaskBase.cs#L172

However, this is not run in hot restart situations:

> Task "ComputeBundleLocation" skipped, due to false condition; ('$(IsMacEnabled)' == 'true') was evaluated as ('false' == 'true').

### Expected Behavior

Framework is present

### Actual Behavior

Framework is not present

### Environment

Windows & VS

### Build Logs

[ios hot restart.zip](https://github.com/xamarin/xamarin-macios/files/12340142/ios.hot.restart.zip)

### Example Project (If Possible)
[MauiProgram.zip](https://github.com/xamarin/xamarin-macios/files/12340153/MauiProgram.zip)

**Comment by mattleibow** [comment]
Looking closer, even with NativeReference and some more hacks to see things, the frameworks never make it to the device:

[MauiApp116_Debug_AnyCPU_net7.0-ios_Build_2023-08-15T02_05_43.4479187+02_00.binlog.zip](https://github.com/xamarin/xamarin-macios/files/12340313/MauiApp116_Debug_AnyCPU_net7.0-ios_Build_2023-08-15T02_05_43.4479187%2B02_00.binlog.zip)

**Comment by rolfbjarne** [comment]
This should be fixed in .NET 8:

https://github.com/xamarin/xamarin-macios/blob/f24a016302747ccc32ee5fa450b99a78c3924b2e/dotnet/targets/Xamarin.Shared.Sdk.targets#L1537

can you try and see if using .NET 8 works?

**Comment by mattleibow** [comment]
I am unable to test net8 because the hot restart app is invalid. It deploys an app that my device does not install and I just get the empty app icon and the app is not installed.

**Comment by rolfbjarne** [comment]
> I am unable to test net8 because the hot restart app is invalid. It deploys an app that my device does not install and I just get the empty app icon and the app is not installed.

Does that happen with a new project from a template as well?

**Comment by mattleibow** [comment]
I was testing with a File | New | Maui app. Should this also work with a plain iOS app? I can try that.

**Comment by rolfbjarne** [comment]
Reopening since this still needs verification.

**Comment by rolfbjarne** [comment]
> I was testing with a File | New | Maui app. Should this also work with a plain iOS app? I can try that.

I'm not sure if Hot Restart works with a plain iOS app.

In any case, can you try again with RC1?
