### ISSUE TITLE
Problem with embedding p12 certificate

### ISSUE THREAD

**Issue by mancda** [xamarin/xamarin-macios#18725]
### Steps to Reproduce

1.  Add p12 certificate to project as an embedded resource.
2.  Build application
3. Results in Codesign error exited with code 1

### Expected Behavior
Certificate would embed as it does when using Android.
### Actual Behavior
Error produced.

### Environment

Visual Studio Community 2022 for Mac
Version 17.6.3 (build 421)
Installation UUID: f17aa0ba-f8f4-416f-8fb4-02d5b685b1f6

Runtime
.NET 7.0.3 (64-bit)
Architecture: X64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.307/Sdks
SDK Versions:
	7.0.307
	7.0.100
	6.0.413
	6.0.403
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.10
	7.0.0
	6.0.21
	6.0.11

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.1.2 (Visual Studio Community)
Commit: xamarin-android/d17-5/a8a26c7
Android SDK: /Users/danielmanchester/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-08-02 19:04:28 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-08-02 19:04:28 UTC

Apple Developer Tools
Xcode: 14.3 21812
Build: 14E222b

Xamarin.Mac
Version: 9.3.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:35-0400

Xamarin.iOS
Version: 16.4.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-08-02 19:04:23 UTC

Build Information
Release ID: 1706030421
Git revision: c90350679f1b9295edc584519320b13d06489853
Build date: 2023-08-02 19:02:50+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.4.1
Darwin 22.5.0 Darwin Kernel Version 22.5.0
    Thu Jun  8 22:22:22 PDT 2023
    root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by rolfbjarne** [comment]
I tried adding a dummy p12 file as a bundle resource and the app built just fine.

Could you please attach a build log (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs)? A test project would also be very helpful.

**Comment by mancda** [comment]
Hi Rolf,

Should I be using a bundle resource instead of an embedded resource ?

Thanks for your help

**Comment by mancda** [comment]
Sorry for the wrongs steps.  I am able to get past the build it is when I publish my app with a pfx certificate as an embedded resource does the app crash when launched.

Thanks for your help

**Comment by rolfbjarne** [comment]
> Hi Rolf,
> 
> Should I be using a bundle resource instead of an embedded resource ?
> 
> Thanks for your help

Either way should work jus fine.

> I am able to get past the build it is when I publish my app with a pfx certificate as an embedded resource does the app crash when launched.

Crash how? Do you get a crash report? Stack trace? Exception message?

**Comment by mancda** [comment]
Here is the crash report.[](url)
[testflight_feedback (2).zip](https://github.com/xamarin/xamarin-macios/files/12343402/testflight_feedback.2.zip)

**Comment by rolfbjarne** [comment]
> Here is the crash report. [testflight_feedback (2).zip](https://github.com/xamarin/xamarin-macios/files/12343402/testflight_feedback.2.zip)

That might be an issue with incremental builds not working properly.

Can you remove the bin+obj directories and try again?

**Comment by mancda** [comment]
Hi Rolf,

Removing bin/obj did not help.  I have found a workaround and do not have time to further pursue this.  I think there is a problem with publishing for iOS when the project contains a signed pfx file as an embedded resource.

Thanks for your help.  You can close the ticket.
________________________________
