### ISSUE TITLE
Warnings from AppCenter when building iOS project with NativeAOT

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18736]
_From @charlesroddie on Thu, 10 Aug 2023 15:30:35 GMT_

Build a Xamarin.IOS app using NativeAOT gives these warnings:
```
ILLINK : warning MT2387: It's not safe to remove the dynamic registrar, because Microsoft.AppCenter references 'ObjCRuntime.BlockLiteral.SetupBlockUnsafe (System.Delegate, System.Delegate)'. [/Users/runner/work/1/s/Platforms/iOS/50iOS.csproj]
ILLINK : warning MT2387: It's not safe to remove the dynamic registrar, because Microsoft.AppCenter.Crashes references 'ObjCRuntime.BlockLiteral.SetupBlockUnsafe (System.Delegate, System.Delegate)'. [/Users/runner/work/1/s/Platforms/iOS/50iOS.csproj]
```

From discord

> @filipnavara For the SetupBlockUnsafe it likely needs to be converted to UnmanagedCallersOnly and the BlockLiteral constructor pattern...
(If it's generated code then it may be just a matter of rebuilding it.)
I just had to do this today in our codebase 😅

_Copied from original issue microsoft/appcenter#2570_

**Comment by rolfbjarne** [comment]
_From @DmitriyKirakosyan on Tue, 15 Aug 2023 11:44:56 GMT_

Hi @charlesroddie , thank you for the report!

If I understand it correctly, the warning is coming from the .NET IL Linker, right? We are not referencing `SetupBlockUnsafe` directly in code, so I believe it can come from some generated code or dependencies.
We will file an item on our board and will look into it.

Is it a blocker for you? Does the project build and run well with these warnings? Does the AppCenter SDK work correctly?
In case you find more details, context or a possible root cause, please share with us.

**Comment by rolfbjarne** [comment]
_From @filipnavara on Tue, 15 Aug 2023 11:55:57 GMT_

We should move this issue to xamarin/xamarin-macios repo. This is result of not running the `OptimizeGeneratedCode` linker step, and we are discussing how to fix it.

**Comment by rolfbjarne** [comment]
I believe this should be fixed now, because we default to trim all assemblies (and the trimmer will rewrite the code that triggers the warning in question so that the code works fine).

**Comment by charlesroddie** [comment]
Hello. I am getting some posts that I can't understand in this issue: https://github.com/microsoft/appcenter/issues/2586#issuecomment-1893164159 . That post is about different trim warnings in AppCenter, and the warnings indicate that they are issue in AppCenter code, but I am getting directed back to this thread. Assuming this is the case, can you mention this thread that this is an AppCenter issue rather than a runtime/macios issue?
