### ISSUE TITLE
Need help with accessing native objects that conform to protocol from bindings

### ISSUE THREAD

**Issue by wfhm** [xamarin/xamarin-macios#18753]
Hi, I am fairly new to C# and I am trying to create bindings for the iOS library and I hit this issue. 

I have an interface I want to expose to C#:

```
@interface PWInbox : NSObject
/**
 @param completion - if successful, return the collection of the InboxMessages. Otherwise, return error
 */
+ (void)loadMessagesWithCompletion:(void (^)(NSArray<NSObject<PWInboxMessageProtocol> *> *messages, NSError *error))completion;
@end
```

The `PWInboxMessageProtocol` here is a protocol with that looks like below:

```
@protocol PWInboxMessageProtocol <NSObject>

@required

@property (readonly, nonatomic) NSString *code;
@property (readonly, nonatomic) NSString *message;

@end
```

In Objective-C, you receive an NSArray of objects of an internal class `PWInboxMessageInternal` that conforms to `PWInboxMessageProtocol`. That internal class is not exposed publicly, but you can still access those objects and its properties via the protocol:

```
    [PWInbox loadMessagesWithCompletion:^(NSArray<NSObject<PWInboxMessageProtocol> *> *messages, NSError *error) {
        if (!error && messages.count) {
            NSLog(@"First Inbox Message: %@", messages.firstObject.message); // prints message successfully
        }
    }];
```

Generated bindings for this class look like below:

```
// @protocol PWInboxMessageProtocol <NSObject>
[Protocol, Model]
    [BaseType (typeof(NSObject))]
    interface PWInboxMessageProtocol
    {
        // @required @property (readonly, nonatomic) NSString * code;
        [Abstract]
        [Export ("code")]
        string Code { get; }

        // @required @property (readonly, nonatomic) NSString * message;
        [Abstract]
        [Export ("message")]
        string Message { get; }
    }


// @interface PWInbox : NSObject
    [BaseType (typeof(NSObject))]
    [DisableDefaultCtor]
    interface PWInbox
    {
        // +(void)loadMessagesWithCompletion:(void (^)(NSArray<NSObject<PWInboxMessageProtocol> *> *, NSError *))completion;
        [Static]
        [Export ("loadMessagesWithCompletion:")]
        void LoadMessagesWithCompletion (Action<NSArray<PWInboxMessageProtocol>, NSError> completion);
    }
```

Then, I subclass PWInboxMessageProtocol and call `LoadMessagesWithCompletion` from C# like below:

```
public class PWInboxMessage : PWInboxMessageProtocol
{
    public PWInboxMessage(NativeHandle handle) : base(handle)
    {
    }
}
```

```
PWInbox.LoadMessagesWithCompletion((messages, error) => { PrintInboxMessages(messages); });

private void PrintInboxMessages(NSArray<PWInboxMessageProtocol> messages)
{
    var message = messages.GetItem<PWInboxMessage>(0); // var message after this line becomes of type PWInboxMessageInternal 
}
```
I can see that `base` in the constructor of `PWInboxMessage` is of type `PWInboxMessageInternal`, and `var message` is assigned with the same type, but trying to access parameters of `base` actually throw MethodNotImplemented exception. 

So, if I understand it correctly, this happens because no type definition for `PWInboxMessageInternal` was provided in my ApiDefinitions.cs. If so, is there a way to declare this internal class if it is not present in headers of the iOS framework? Or is there a better way to access the original objects?

**Comment by rolfbjarne** [comment]
Try this ApiDefinition.cs:

```cs
// @protocol PWInboxMessageProtocol <NSObject>
[Protocol]
[BaseType (typeof(NSObject))]
interface PWInboxMessageProtocol
{
    // @required @property (readonly, nonatomic) NSString * code;
    [Abstract]
    [Export ("code")]
    string Code { get; }

    // @required @property (readonly, nonatomic) NSString * message;
    [Abstract]
    [Export ("message")]
    string Message { get; }
}

interface IPWInboxMessageProtocol {}

// @interface PWInbox : NSObject
[BaseType (typeof(NSObject))]
[DisableDefaultCtor]
interface PWInbox
{
    // +(void)loadMessagesWithCompletion:(void (^)(NSArray<NSObject<PWInboxMessageProtocol> *> *, NSError *))completion;
    [Static]
    [Export ("loadMessagesWithCompletion:")]
    void LoadMessagesWithCompletion (Action<NSArray<IPWInboxMessageProtocol>, NSError> completion);
}
```

Changes:

1. Removed `[Model]` from the `PWInboxMessageProtocol` (the `[Model]` attribute is useful when you're supposed to create a class that implements the protocol in question, but it doesn't seem like that's what you're supposed to do, you're only consuming an internal implementation of the protocol).
2. We will generate an C# interface to represent the Objective-C protocol (the protocol name prefixed with `I` - `IPWInboxMessageProtocol` in this case), and that's the type you want the `LoadMessageWithCompletion` method to use - so change the signature to use to `IPWInboxMessageProtocol` interface.
3. Added a placeholder`IPWInboxMessageProtocol` interface - this fixes a chicken-and-egg problem where you want to use this interface, but it doesn't exist yet because it hasn't been generated.

Now you don't need to subclass `PWInboxMessageProtocol`, you can do this:

```cs
PWInbox.LoadMessagesWithCompletion((messages, error) => { PrintInboxMessages(messages); });

private void PrintInboxMessages(NSArray<IPWInboxMessageProtocol> messages)
{
    var message = messages.GetItem<IPWInboxMessageProtocol>(0);
	// and here you can use "message" to call the members on the PWInboxMessageProtocol
}
```

Can you try this and see if it works?

**Comment by wfhm** [comment]
@rolfbjarne That's what I tried to do first, but I guess I missed something important, so it didn't work then. Also, using `NSArray<IPWInboxMessageProtocol>` in `LoadMessageWithCompletion` method threw another exception:

```
Error CS0311: The type 'Com.Pushwoosh.iOS.IPWInboxMessageProtocol' cannot be used as type parameter 'TKey' in the generic type or method 'NSArray<TKey>'. There is no implicit reference conversion from 'Com.Pushwoosh.iOS.IPWInboxMessageProtocol' to 'ObjCRuntime.INativeObject'. (CS0311) (PushwooshSDK.DotNet.iOS.Bindings)
```
But using  `IPWInboxMessageProtocol[]` did the trick. It seems to be working fine now.

Thanks a lot!
