### ISSUE TITLE
Issue binding iOS native library

### ISSUE THREAD

**Issue by espritm** [xamarin/xamarin-macios#18774]
### Steps to Reproduce

1. Create a iOS binding project
2. Add the native library and the generated files from Sharpie
3. Create a MAUI test project that references the iOS binding project
4. Build and run the Test project > Following build errors occurs
```
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.2054/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
ld: warning: Could not find or use auto-linked library 'swiftCompatibility56'
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility50'
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftSwiftOnoneSupport'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility51'
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency'
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
```

### Expected Behavior
We should not get build error and no crash at runtime

### Actual Behavior
We have build errors

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.6.3 (build 421)
Installation UUID: a6ec5228-8b38-4a7c-92eb-c3ccac4ab76d

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.307/Sdks
SDK Versions:
	7.0.307
	7.0.101
	6.0.413
	6.0.401
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	7.0.307
	7.0.202
	6.0.413
	6.0.407
	6.0.404
	3.1.426
	3.1.423

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.10
	7.0.4
	7.0.1
	7.0.0
	6.0.21
	6.0.15
	6.0.12
	6.0.11
	6.0.9

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	7.0.10
	7.0.4
	6.0.21
	6.0.15
	6.0.12
	3.1.32
	3.1.29

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.1.2 (Visual Studio Community)
Commit: xamarin-android/d17-5/a8a26c7
Android SDK: /Users/ubp/Library/Android/sdk
	Supported Android versions:
		12.1 (API level 32)
		8.0  (API level 26)
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-08-02 19:06:47 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-08-02 19:06:47 UTC

Apple Developer Tools
Xcode: 14.3 21812
Build: 14E222b

Xamarin.Mac
Version: 9.3.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:35-0400

Xamarin.iOS
Version: 16.4.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-08-02 19:06:42 UTC

Build Information
Release ID: 1706030421
Git revision: c90350679f1b9295edc584519320b13d06489853
Build date: 2023-08-02 19:05:00+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.2.1
Darwin 22.3.0 Darwin Kernel Version 22.3.0
    Mon Jan 30 20:38:37 PST 2023
    root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

```

</details>

### Build Logs

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/12394245/msbuild.binlog.zip)

### Example Project (If Possible)

[Archive.zip](https://github.com/xamarin/xamarin-macios/files/12394279/Archive.zip)

**Comment by rolfbjarne** [comment]
Can you try adding this to your main app's project file:

```xml
<Target Name="LinkWithSwift" DependsOnTargets="_ParseBundlerArguments;_DetectSdkLocations" BeforeTargets="_LinkNativeExecutable">
	<PropertyGroup>
		<_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('iossimulator-'))">iphonesimulator</_SwiftPlatform>
		<_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('ios-'))">iphoneos</_SwiftPlatform>
	</PropertyGroup>
	<ItemGroup>
		<_CustomLinkFlags Include="-L" />
		<_CustomLinkFlags Include="/usr/lib/swift" />
		<_CustomLinkFlags Include="-L" />
		<_CustomLinkFlags Include="$(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(_SwiftPlatform)" />
	</ItemGroup>
</Target>
```

and see if that works?

**Comment by espritm** [comment]
Thank you @rolfbjarne , it builds but the crash at startup with following error : 
```
dyld[16998]: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: <12D03890-AF6B-3448-9FDC-764076895501> /Users/ubp/Library/Developer/CoreSimulator/Devices/57CBAF43-9FCC-4DAD-8EBD-472875B11708/data/Containers/Bundle/Application/B7D65CEE-FE12-4400-85C5-36A09D09BD3D/Test.app/Test
  Reason: tried: '/Users/ubp/Library/Developer/CoreSimulator/Devices/57CBAF43-9FCC-4DAD-8EBD-472875B11708/data/Containers/Bundle/Application/B7D65CEE-FE12-4400-85C5-36A09D09BD3D/Test.app/libswiftCore.dylib' (no such file), '/Users/ubp/Library/Developer/CoreSimulator/Devices/57CBAF43-9FCC-4DAD-8EBD-472875B11708/data/Containers/Bundle/Application/B7D65CEE-FE12-4400-85C5-36A09D09BD3D/Test.app/Frameworks/libswiftCore.dylib' (no such file), '/Users/ubp/Library/Developer/CoreSimulator/Devices/57CBAF43-9FCC-4DAD-8EBD-472875B11708/data/Containers/Bundle/Application/B7D65CEE-FE12-4400-85C5-36A09D09BD3D/Test.app/libswiftCore.dylib' (no such file), '/Users/ubp/Library/Developer/CoreSimulator/Devices/57CBAF43-9FCC-4DAD-8EBD-472875B11708/data/Containers/Bundle/Application/B7D65CEE-FE12-4400-85C5-36A09D09BD3D/Test.app/Frameworks/libswiftCore.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libswiftCore.dylib' (no such file)
```

After some googling I tryied to add swift support libraries (Xamarin.iOS.SwiftRuntimeSupport nuget) as mentionned [here](https://learn.microsoft.com/en-us/xamarin/ios/platform/binding-swift/#consume-the-xamarin-binding-library)
But it does not help.

Any idea please ?

**Comment by rolfbjarne** [comment]
Two more linker flags are needed, "-Wl,-rpath" and "-Wl,/usr/lib/swift":

```xml
<Target Name="LinkWithSwift" DependsOnTargets="_ParseBundlerArguments;_DetectSdkLocations" BeforeTargets="_LinkNativeExecutable">
	<PropertyGroup>
		<_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('iossimulator-'))">iphonesimulator</_SwiftPlatform>
		<_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('ios-'))">iphoneos</_SwiftPlatform>
	</PropertyGroup>
	<ItemGroup>
		<_CustomLinkFlags Include="-L" />
		<_CustomLinkFlags Include="/usr/lib/swift" />
		<_CustomLinkFlags Include="-L" />
		<_CustomLinkFlags Include="$(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(_SwiftPlatform)" />
		<_CustomLinkFlags Include="-Wl,-rpath" />
		<_CustomLinkFlags Include="-Wl,/usr/lib/swift" />
	</ItemGroup>
</Target>
```

This now results in this at startup, which I believe comes from the native library:

> FATAL ERROR - Getting device UUID from global keychain failed: Error Domain=com.sysmosoft.ios.keychain Code=-34018 "Not able to return keychain item for the service 58b7ff21-2608-4074-90da-dd8f8bacfe8d and group com.companyname.test" UserInfo={NSLocalizedDescription=Not able to return keychain item for the service 58b7ff21-2608-4074-90da-dd8f8bacfe8d and group com.companyname.test}

**Comment by espritm** [comment]
Thank a lot @rolfbjarne  ! 

I confirm it is an error related to the native library I'm trying to bind. 
It means I have now access to the native classes and go ahead to a successfull and compelte binding project.

Do you have any url, page or documentation about those linker flags please ? I would be happy to learn and understand theses settings from hell

**Comment by rolfbjarne** [comment]
> Do you have any url, page or documentation about those linker flags please ? I would be happy to learn and understand theses settings from hell

What I did was to build a Swift project in Xcode and check the compiler/linker flags Xcode uses.

**Comment by rolfbjarne** [comment]
> I confirm it is an error related to the native library I'm trying to bind.
> It means I have now access to the native classes and go ahead to a successfull and compelte binding project.

Great, I'll close this then.

**Comment by kpespisa** [comment]
>What I did was to build a Swift project in Xcode and check the compiler/linker flags Xcode uses.

Could you please explain how this is done? The LinkWithSwift target removes most of the errors I see, but I don't understand where the list of flags comes from.

**Comment by leonedev** [comment]
Can you reopen this issue please? It is not working right now and my project is not binding to iOS native libraries (that I understand)

I will list the error below:

Xamarin.Shared.Sdk.targets(1564, 3): clang++ exited with code 1:
  ld: warning: Could not find or use auto-linked library 'swiftCore'
  ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
  ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
  ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
  ld: warning: Could not find or use auto-linked library 'swiftOSLog'
  ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
  ld: warning: Could not find or use auto-linked library 'swiftFoundation'
  ld: warning: Could not find or use auto-linked library 'swiftUIKit'
  ld: warning: Could not find or use auto-linked library 'swiftDarwin'
  ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
  ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
  ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency'
  ld: warning: Could not find or use auto-linked library 'swiftMetal'
  ld: warning: Could not find or use auto-linked library 'swiftDispatch'
  
  Any help is highly appreciated.

**Comment by rolfbjarne** [comment]
> Can you reopen this issue please? It is not working right now and my project is not binding to iOS native libraries (that I understand).
> 
> I'm using nuget packages for Firebase from AdamE.Firebase.* (maybe these are related to the native bindings?)
> 
> I will list the error below:
> 
> Xamarin.Shared.Sdk.targets(1564, 3): clang++ exited with code 1: ld: warning: Could not find or use auto-linked library 'swiftCore' ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics' ld: warning: Could not find or use auto-linked library 'swiftCoreImage' ld: warning: Could not find or use auto-linked library 'swiftFileProvider' ld: warning: Could not find or use auto-linked library 'swiftOSLog' ld: warning: Could not find or use auto-linked library 'swiftObjectiveC' ld: warning: Could not find or use auto-linked library 'swiftFoundation' ld: warning: Could not find or use auto-linked library 'swiftUIKit' ld: warning: Could not find or use auto-linked library 'swiftDarwin' ld: warning: Could not find or use auto-linked library 'swiftQuartzCore' ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers' ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency' ld: warning: Could not find or use auto-linked library 'swiftMetal' ld: warning: Could not find or use auto-linked library 'swiftDispatch'
> 
> Any help is highly appreciated, since I'm not able to deliver my app to the customer.

Please file a new issue, providing an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) (which will show the complete error message).

**Comment by morisgateno-appsflyer** [comment]
Thanks!
@rolfbjarne
