### ISSUE TITLE
NativeAOT: Do not root the framework assembly

### ISSUE THREAD

**Issue by ivanpovazan** [xamarin/xamarin-macios#18779]
Once all identified work regarding ILLink+ILC trimming compatibility has been completed rooting the framework assembly should not be needed anymore.

This means that we should remove the following lines and verify there are no regression when we do so:
https://github.com/xamarin/xamarin-macios/blob/596304e281c64c737c6b7a0f97fea2b0706671ae/dotnet/targets/Xamarin.Shared.Sdk.targets#L1235-L1236

**Comment by rolfbjarne** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/pull/18885.
