### ISSUE TITLE
Improve error message when targeting net6.0-ios and net6.0-macos from net 8

### ISSUE THREAD

**Issue by haritha-mohan** [xamarin/xamarin-macios#18790]
Recently when trying to fix our sample submissions in maccore using the net8.0-xcode15 branch of macios, I was running into the following issue for the dotnet apps:

`error NETSDK1147: To build this project, the following workloads must be installed: wasm-tools-net6`
`error NETSDK1147: To install these workloads, run the following command: dotnet workload restore`

..which doesn't make much sense why wasm is needed for these projects. Turns out this is the error displayed when targeting net6 from net8. The android SDK team faced a similar issue and addressed it and I think we can follow suit.

we dropped net6 support for net8 here: https://github.com/xamarin/xamarin-macios/pull/17901
XA issue: https://github.com/xamarin/xamarin-android/issues/8003
XA fix: https://github.com/xamarin/xamarin-android/pull/8047

Wondering if we could do the same? I can implement the fix, just want to check if this is the correct course of action.

**Comment by rolfbjarne** [comment]
I'm already working on something like this (as part of a fix for https://github.com/dotnet/sdk/issues/30103), so I can do this.

**Comment by rolfbjarne** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/pull/18931.
