### ISSUE TITLE
Future native dotnet mobile development

### ISSUE THREAD

**Issue by stefan89** [xamarin/xamarin-macios#18805]
Currently I am working on several **native** Xamarin projects (xib files and axml files for layout) that are already migrated to dotnet 7.

On several forums I read that Microsoft will stop supporting Xamarin in the near future
https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin#microsoft-support

What does this mean for native ios and native android projects which are in dotnet 7 format?

Do we need to rewrite these whole apps to dotnet MAUI (a.k.a. cross platform solution) or are we future proof since we are already migrated to dotnet 7?

**Comment by rolfbjarne** [comment]
Native iOS and Android projects (ported to .NET 7+) will continue to work, we won't require anybody to use MAUI.

Technically MAUI is just an addition on top of native iOS/Android projects, you don't have to use it if you don't want to.

I hope that answers your question!

**Comment by stefan89** [comment]
Thanks for your response. That answers my question.
