### ISSUE TITLE
.p8 certificate for remote messaging (azure notifications hub) problems?

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/xamarin-macios#18867]
Running into an problems setting up remote messaging: 

We have followed this guide: https://learn.microsoft.com/en-us/azure/notification-hubs/xamarin-notification-hubs-ios-push-notification-apns-get-started which includes setting up a .p8 certificates on the apple from token-based authentication, benefits include they do not expire as opposed to the traditional .p12 push certificates. We have upload the .p8 file on azure notifications hub and when debugging the app remote notifications works perfectly. 

The problem is trying to build and deploy an `Adhoc` build is giving us an some problems, firstly we cannot deploy the app as its giving us a `MT1006` error that is when we include the following in the entitlements. as we normally would do with a .p12 certificate setup 

```csproj
<dict>
	<key>aps-environment</key>
	<string>production</string>
</dict>
```

But when we remove the above from entitlements, the app builds & deploys fine for `Adhoc` build but we cannot get any notifications received and some tracing uncovered the following:

```csharp
public override void FailedToRegisterForRemoteNotifications(
            UIApplication application,
            NSError error)
        {
            Debug.WriteLine(error.Description);
            Trace.WriteLine($"APP_REMOTE_FAILED: {error}");
        }
```

From device log:

```logcat
Time	Device Name	Type	PID	Tag	Message
Aug 30 13:56:05	Test-iPhone	Notice	1985	SampleAPP.iOS	APP_REMOTE_FAILED: no valid \M-b\M^@\M^\aps-environment\M-b\M^@\M^] entitlement string found for application
```

We understand the problem `entitlement string not found` error but when we try to add it we cannot build and deploy which I assume (correct me if wrong) is because we are using the token-based authentication with the .p8 file as created per below.

![image](https://github.com/xamarin/xamarin-macios/assets/5468757/96967448-1446-4847-9a1a-4d6b42b0470a) 

I would be interested to know if this option is supported and if so is there some additional configuration required, this is the first app we are trying with the token-based authentication and also first time we are having this issue and assume the two might be related.

**Comment by LeoJHarris** [comment]
Okay so in addition to all of this, I finally have this working... kind of. What I found was archiving an trying to distribute through appcenter with an archive saved locally, when I used apple transporter it worked okay for the app store build.

Also trying to deploy an adhoc build directly from VS it was throwing the error as mentioned above

**Comment by rolfbjarne** [comment]
> The problem is trying to build and deploy an `Adhoc` build is giving us an some problems, firstly we cannot deploy the app as its giving us a `MT1006` error that is when we include the following in the entitlements.

This is because an `AdHoc` build (really any build you deploy to your device locally instead of going through Apple's servers) is a development build, it's not a production build, and as such the app installation fails on the device.

This means that you need to set aps-environment=development for any such builds:

```xml
<dict>
	<key>aps-environment</key>
	<string>development</string>
</dict>
```
