### ISSUE TITLE
Failed to compile the generated registrar code

### ISSUE THREAD

**Issue by aschaefen** [xamarin/xamarin-macios#18869]
My Xamarin application fails to build. This issue seems to be the same as these two: https://github.com/xamarin/xamarin-macios/issues/7049 and https://github.com/xamarin/xamarin-macios/issues/7047. Is there a Xamarin.iOS preview version available already that would allow me to be able to build Xamarin (iOS) applications?

Steps to Reproduce
Install Xamarin  Version: 16.11.000.204
Install Xamarin.IOS Version: 15.2.0.17
Install Xcode version 14.1
Expected Behavior
Xamarin.iOS Application builds successfully.

Actual Behavior
The build fails with Error MT4109: Failed to compile the generated registrar code.

Environment
Xamarin  Version: 16.11.000.204
Xamarin.IOS Version: 15.2.0.17
Xcode version 14.1

**Comment by rolfbjarne** [comment]
> Xamarin.IOS Version: 15.2.0.17
> Xcode version 14.1

These are older versions, not the latest stable release.

Please try downloading Xamarin.iOS 16.4.0.6 here: https://github.com/xamarin/xamarin-macios/blob/main/DOWNLOADS.md, and then Xcode 14.3.1 from Apple's Developer site.
