### ISSUE TITLE
Cannot pair to a mac from a windows

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/xamarin-macios#18866]
Hi trying to pair with a mac from a windows the IDE freezes and an error shows the following:

![image](https://github.com/xamarin/xamarin-macios/assets/5468757/a8513520-e9a9-4f05-8a61-6d2d7465aaf4)

**Comment by LeoJHarris** [comment]
Seems to be working again but begs to wonder how these types of problem surface...

**Comment by GO74** [comment]
> 

I've got the same issue as you described. Interestingly this seems to be an issue with this specific project I'm currently trying to work on. If I open another project/solution it's all working fine.

**Comment by GO74** [comment]
I believe it might have something to do with the bundle signature.

**Comment by LeoJHarris** [comment]
@GO74 that worked
