### ISSUE TITLE
Can't build binding projects on Windows even connected to a Mac

### ISSUE THREAD

**Issue by LITTOMA** [xamarin/xamarin-macios#18886]
### Steps to Reproduce

1. Create a Xamarin iOS binding project.
2. Add native framework reference.
3. Build it.

### Expected Behavior
Build successfully.

### Actual Behavior
VS2022 shows a warning "It's currently not supported to build a binding project from Windows unless a connection to a Mac is available." However, I have already connected to a Mac.

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Enterprise 2022 (64 bit) - Current
Version 17.7.1
```

</details>

**Comment by steve3p0** [comment]
This is still an issue.  Where can I vote on the feedback.

C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8319\tools\msbuild\iOS\Xamarin.Shared.targets(1753,3): warning : It's currently not supported to build a binding project from Windows unless a connection to a Mac is available.

I'm connected to a Mac
