### ISSUE TITLE
VS4Mac: Reitrement / Migration Questions

### ISSUE THREAD

**Issue by projectgoav** [xamarin/xamarin-macios#18890]
I have just read the following article announcing that Visual Studio for Mac is being discontinued sometime in the near future: https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/

There is some talk of moving to VSCode for iOS/Mac development and lists a number of solutions for building MAUI apps. However there is nothing mentioning how we can continue to maintain native iOS/Mac apps using UIKit & AppKit APIs.

Is there a VSCode setup that would allow for this or something planned in the future? Does MSFT already rely on a VSCode setup and if so, how does that work? 

With Azure Pipelines / Github actions providing iOS builds using VS4Mac, what's the migration plan there? Should we be moving our builds to `dotnet build ....` and `dotnet publish ...`? Is is even possible to get a signed IPA out the other end using this method? (I appreciate this might be a question for the Pipelines team).

**Comment by rolfbjarne** [comment]
> Should we be moving our builds to `dotnet build ....` and `dotnet publish ...`?

Probably yes (there might be other ways, but I'm certain this will work).

> Is is even possible to get a signed IPA out the other end using this method?

Yes, it's certainly possible to get signed IPAs using the command line (`dotnet build/publish`):

This document is geared towards MAUI, but the exact same process works for plain iOS (non-MAUI) projects as well:

https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-cli

> However there is nothing mentioning how we can continue to maintain native iOS/Mac apps using UIKit & AppKit APIs.
> 
> Is there a VSCode setup that would allow for this or something planned in the future?

I believe some people have had success using VSCode with plain iOS projects, but I can't really speak for any future plans in this area. My recommendation would be to try it out and file issues for any problems you run into. Engineering effort is based on customer demand, so if enough people say they want it, we'll make it happen.

I hope that answers your questions!
