### ISSUE TITLE
Building watchOS apps using net8.0-xcode15

### ISSUE THREAD

**Issue by haritha-mohan** [xamarin/xamarin-macios#18902]
For Xcode 15, we removed the armv7k arch (aka 32 bit support) for watchOS. This impacts only legacy as watchOS is not supported on dotnet.

Refs:
https://github.com/xamarin/xamarin-macios/pull/18413/commits/89d6091096c2998b70247cb35abcb59daa5759c2
https://github.com/xamarin/xamarin-macios/commit/44b2342e9ec109bca6d82347878d82342c3bcb66

However, recently when investigating failures in our submission tests using the net8.0-xcode15 branch, this change resulted in some issues. 

The alternative arch to use for watchOS builds is arm64_32. But when using it standalone, although our build succeeds, validation to the App Store fails when using OS versions < 9.0: 

`Error: Asset validation failed Missing architecture. The “MainApp.app/Watch/MainAppWatchApp.app/PlugIns/MainAppWatchAppExtension.appex” bundle must contain [armv7k] because it is built with the watchOS 5.0 SDK or later.`

[Test Log](https://gist.github.com/haritha-mohan/52b97abab9cf86604cdfeab09af330a9)

So, workaround is to set the MinimumOSVersion in the Info.plist to a version >= 9.0 due to it being the first version of watchOS to have only 64 bit support. But because of the gray area for lower versions, we might need to re-think supporting armv7k arch for compatibility with Apple.

[Xcode support policy](https://developer.apple.com/support/xcode/)

**Comment by rolfbjarne** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/pull/18947.
