### ISSUE TITLE
Error NETSDK1144: Optimising assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. (NETSDK1144)

### ISSUE THREAD

**Issue by Wilson8125** [xamarin/xamarin-macios#18928]
Getting the following error after the Xamarin iOS project is migrated to MAUI (Net 7.0 ) on deploying to the iphone device

Error NETSDK1144: Optimising assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. (NETSDK1144)

Error IL1030: Invalid argument for '--feature' option. (IL1030)

**Comment by Wilson8125** [comment]
> Could you get a [binlog](https://aka.ms/binlog) from the build and attach it here? Thanks!

Hi Took this from the build output. Could you please guide me to take the binlog in Visual Studio MAC
[VS_Logs.txt](https://github.com/xamarin/xamarin-macios/files/12535842/VS_Logs.txt)

**Comment by rolfbjarne** [comment]
I'm guessing this is the problem:

> --feature System.Net.Http.UseNativeHttpHandler NSUrlSessionHandler\

I'm also guessing you have something like this in your project file:

```xml
<UseNativeHttpHandler>NSUrlSessionHandler</UseNativeHttpHandler>
```

However, `UseNativeHttpHandler` is a boolean property. If you want to use `NSUrlSessionHandler`, do this:

```xml
<UseNativeHttpHandler>true</UseNativeHttpHandler>
```

This is the default anyway on iOS, so you can just remove the whole line.

If that doesn't work, this describes how to get a binlog: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs

**Comment by rolfbjarne** [comment]
I believe you're trying to use a third-party native library, but it's not getting linked correctly for some reason.

**Comment by Wilson8125** [comment]
> I believe you're trying to use a third-party native library, but it's not getting linked correctly for some reason.

Yes, Correct Third Party DLL is used and it is used using DLL Import

**Comment by rolfbjarne** [comment]
We'll need a test project we can use to reproduce the problem then in order to diagnose it.
