### ISSUE TITLE
Xamarin CarPlay InformationTemplate Custom Back Button Handle Problem

### ISSUE THREAD

**Issue by msandikli** [xamarin/xamarin-macios#18934]
Our xamarin forms project supported CarPlay and has a information template. I want to use custom back button on information template but handle function not working. Back button create function codes:

        private CPBarButton GetBackButton()
        {
            return new CPBarButton("Back", handler =>
            {
                try
                {
                    if (interfaceController != null && interfaceController.Templates != null && interfaceController.Templates.Length > 1)
                    {
                        interfaceController.PopTemplate(true);
                    }
                }
                catch { }
            });
        }
        
 Visual Studio version: Visual Studio 2022 17.7.3

**Comment by rolfbjarne** [comment]
I'm not sure if I understand the problem - is it that the handler is never called when the user taps on the Back button? What actually happens - nothing at all, or something else?

**Comment by msandikli** [comment]
> I'm not sure if I understand the problem - is it that the handler is never called when the user taps on the Back button? What actually happens - nothing at all, or something else?

Nothing. "Handle Section" is not called.

**Comment by msandikli** [comment]
> Can you try creating a custom `CPBarButton` subclass and use that instead?
> 
> ```cs
> class MyBarButton : CPBarButton {
>     public MyBarButton (string title, CPBarButtonHandler handler)
>         : base (title, handler)
>     {
>     }
> }
> 
> // ...
> 
>     private CPBarButton GetBackButton()
>     {
>         return new MyBarButton("Back", handler =>
>         {
>             try
>             {
>                 if (interfaceController != null && interfaceController.Templates != null && interfaceController.Templates.Length > 1)
>                 {
>                     interfaceController.PopTemplate(true);
>                 }
>             }
>             catch { }
>         });
>     }
> ```

This code cause to this exception with used information template.

Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: Unsupported object <ABCProject_MyBarButton: 0x285f89920> {UUID: E12EEF2B-0261-40E9-A4C9-769C8E81536F, enabled: YES} passed to setBackButton:. Allowed classes: {(
    CPBarButton
)}
Native stack trace:
	0   CoreFoundation                      0x00000001889f0cc0 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 40128
	1   libobjc.A.dylib                     0x0000000181a983d0 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000188ade224 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 1012260
	3   CarPlay                             0x00000001f0b717d8 0C8F03F9-B099-3512-9003-D375538E0B7F + 206808
	4   ABCProject                 0x000000010786f4a8 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 79550108
	5   ABCProject                 0x0000000106fefd88 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 70639484
	6   ABCProject                 0x0000000102e33230 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 1709092
	7   ABCProject                 0x00000001074a3a28 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 75570204
	8   ABCProject                 0x0000000107981dd8 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 80674764
	9   CarPlay                             0x00000001f0b4159c 0C8F03F9-B099-3512-9003-D375538E0B7F + 9628
	10  libdispatch.dylib                   0x000000018feb5320 BB347F0E-F21C-3607-82E6-C8D750FDBF8C + 8992
	11  libdispatch.dylib                   0x000000018feb6eac BB347F0E-F21C-3607-82E6-C8D750FDBF8C + 16044
	12  libdispatch.dylib                   0x000000018fec56a4 BB347F0E-F21C-3607-82E6-C8D750FDBF8C + 75428
	13  libdispatch.dylib                   0x000000018fec52f4 _dispatch_main_queue_callback_4CF + 44
	14  CoreFoundation                      0x0000000188a7fc28 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 625704
	15  CoreFoundation                      0x0000000188a61560 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 501088
	16  CoreFoundation                      0x0000000188a663ec CFRunLoopRunSpecific + 612
	17  GraphicsServices                    0x00000001c3f2b35c GSEventRunModal + 164
	18  UIKitCore                           0x000000018adf36e8 B3834960-244B-34E4-9EA0-CA4BB44EF0F3 + 3790568
	19  UIKitCore                           0x000000018adf334c UIApplicationMain + 340
	20  ABCProject                 0x000000010c154440 xamarin_UIApplicationMain + 60
	21  ABCProject                 0x0000000107863b58 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 79502668
	22  ABCProject                 0x000000010707467c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 71182448
	23  ABCProject                 0x00000001070747a0 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 71182740
	24  ABCProject                 0x0000000102e40320 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 1762580
	25  ABCProject                 0x000000010374c480 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 11249268
	26  ABCProject                 0x000000010bfcc838 mono_pmip + 28164
	27  ABCProject                 0x000000010c087004 mono_pmip + 792016
	28  ABCProject                 0x000000010c08d30c mono_pmip + 817368
	29  ABCProject                 0x000000010bfaab48 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 154242364
	30  ABCProject                 0x000000010c1950c0 xamarin_get_original_working_directory_path + 4496
	31  ABCProject                 0x0000000102e2affc _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 1675760
	32  dyld                                0x00000001a7f66dec 8A423F3F-B318-315E-99C7-05EE532E9C0D + 89580

**Comment by msandikli** [comment]
> Never seen that before!
> 
> But ok, here's another idea:
> 
> ```cs
>     static List<CPBarButton> buttons = new List<CPBarButton> ();
>     private CPBarButton GetBackButton()
>     {
>         var button = new CPBarButton("Back", handler =>
>         {
>             try
>             {
>                 if (interfaceController != null && interfaceController.Templates != null && interfaceController.Templates.Length > 1)
>                 {
>                     interfaceController.PopTemplate(true);
>                 }
>             }
>             catch { }
>         });
>         buttons.Add (button);
>         return button;
>     }
> ```
> 
> This will add the button to a static list, to ensure the GC doesn't collect it. This is a wild guess, and I have no idea if this is an issue, but the fact that we can't reproduce this ourselves (due to the special carplay entitlement that's required from Apple) makes it rather difficult to diagnose :/

I tried this workaround but nothing has changed.

**Comment by rolfbjarne** [comment]
Do the other two methods from the CPBarButtonProviding protocol work (LeadingNavigationBarButtons / TrailingNavigationBarButtons)?

**Comment by msandikli** [comment]
> Do the other two methods from the CPBarButtonProviding protocol work (LeadingNavigationBarButtons / TrailingNavigationBarButtons)?

I tried do the other methods but nothing has changed.

**Comment by rolfbjarne** [comment]
> > Do the other two methods from the CPBarButtonProviding protocol work (LeadingNavigationBarButtons / TrailingNavigationBarButtons)?
> 
> I tried do the other methods but nothing has changed. @rolfbjarne

I'm not sure I understand: were you able to add these buttons, and do those buttons work?
