### ISSUE TITLE
Xamarin carplay supported ios app crashes when starting

### ISSUE THREAD

**Issue by msandikli** [xamarin/xamarin-macios#18933]
Our app crashes as soon as it is launched after carplay integration. if i install directly (from ipa) it works. But if I install from testflight it crashes. If you remove

   ```
 <key>UIApplicationSceneManifest</key>

<dict>

<key>UISceneConfigurations</key>

<dict>

<key>UIApplicationSupportsMultipleScenes</key>

<true/>

<key>UIWindowSceneSessionRoleApplication</key>

<array>

<dict>

<key>UISceneClassName</key>

<string>UIWindowScene</string>

<key>UISceneConfigurationName</key>

<string>__ABC_DEFAULT_SCENE_CONFIGURATION__</string>

<key>UISceneDelegateClassName</key>

<string>DeviceSceneDelegate</string>

</dict>

</array>

<key>CPTemplateApplicationSceneSessionRoleApplication</key>

<array>

<dict>

<key>UISceneClassName</key>

<string>CPTemplateApplicationScene</string>

<key>UISceneConfigurationName</key>

<string>ABC-Car</string>

<key>UISceneDelegateClassName</key>

<string>CarPlaySceneDelegateABC</string>

</dict>

</array>

</dict>

</dict>

<key>CFBundleName</key>

<string>ABC</string>
```

from Info.plist problem is solved but carplay is disabled.

I tried delete this code below and problem is solved but carplay disabled.

**Comment by rolfbjarne** [comment]
> Our app crashes as soon as it is launched after carplay integration

Can you get:

1. A device log from when the app crashes (https://support.apple.com/en-in/guide/console/cnsl1012/mac)
2. A crash report from Xcode (the View Device Logs button here: https://help.apple.com/xcode/mac/current/#/dev7b20475ba)

That will hopefully give more clues as to why the app is crashing.

**Comment by msandikli** [comment]
> > Our app crashes as soon as it is launched after carplay integration
> 
> Can you get:
> 
> 1. A device log from when the app crashes (https://support.apple.com/en-in/guide/console/cnsl1012/mac)
> 2. A crash report from Xcode (the View Device Logs button here: https://help.apple.com/xcode/mac/current/#/dev7b20475ba)
> 
> That will hopefully give more clues as to why the app is crashing.

```
<key>UIApplicationSceneManifest</key>

<dict>

<key>UIApplicationSupportsMultipleScenes</key>

<true/>

<key>UISceneConfigurations</key>

<dict>

<key>UIWindowSceneSessionRoleApplication</key>

<array>

<dict>

<key>UISceneClassName</key>

<string>UIWindowScene</string>

<key>UISceneConfigurationName</key>

<string>__ABC_DEFAULT_SCENE_CONFIGURATION__</string>

<key>UISceneDelegateClassName</key>

<string>DeviceSceneDelegate</string>

</dict>

</array>

<key>CPTemplateApplicationSceneSessionRoleApplication</key>

<array>

<dict>

<key>UISceneClassName</key>

<string>CPTemplateApplicationScene</string>

<key>UISceneConfigurationName</key>

<string>ABC-Car</string>

<key>UISceneDelegateClassName</key>

<string>CarPlaySceneDelegateABC</string>

</dict>

</array>

</dict>

</dict>

<key>CFBundleName</key>

<string>ABC</string>
```

UIApplicationSupportsMultipleScenes key is wrong position in xml. It should out the UISceneConfigurations key. Problem solved! Thanks.
