### ISSUE TITLE
Mac Catalyst Binding Project does not work with MAUI without manual edit of project file

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-macios#18948]
---
**Issue moved from dotnet/maui#17217**
- Please respond to @scottkdavis.

---

_From @scottkdavis on Tuesday, September 5, 2023 3:39:46 PM_

### Description

After creating a new (blank) MAUI application and adding a new (blank) Mac Catalyst binding project I receive this error.

Project [csproj file] targets 'net7.0-maccatalyst'. It cannot be referenced by a project that targets '.NETCoreApp,Version=v7.0'.

However, this is the target of my MAUI app (default from VS, not changed)

`		<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		
		
`

By default, binding projects should be excluded from the platforms to which they do not apply, or the error message should be improved to indicate which platforms are a problem.

### Steps to Reproduce

1. Create new MAUI app. Select .Net 7.0 framework
2. Add new project, Mac Catalyst Binding Library
3. Reference binding library from MAUI app
4. Build

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Mac OS Ventura 13.5

### Did you find any workaround?

You must manually edit the project file to include the condition to only include the binding library if TargetFramework is maccatalyst, or remove android and ios targets from the top of the file.

`	<ItemGroup>
	  <ProjectReference Condition="'$(TargetFramework)'=='net7.0-maccatalyst'" Include="..\TestMauiMacCatBinding\TestMauiMacCatBinding.csproj" />
	</ItemGroup>
`

**Comment by rolfbjarne** [comment]
This is the error I get when building from the command line:

```
/Users/rolf/test/dotnet/maui/theapp/theapp.csproj : error NU1201: Project thelib is not compatible with net7.0-ios16.1 (.NETCoreApp,Version=v7.0). Project thelib supports: net7.0-maccatalyst16.1 (.NETCoreApp,Version=v7.0)
/Users/rolf/test/dotnet/maui/theapp/theapp.csproj : error NU1201: Project thelib is not compatible with net7.0-ios16.1 (.NETCoreApp,Version=v7.0) / iossimulator-x64. Project thelib supports: net7.0-maccatalyst16.1 (.NETCoreApp,Version=v7.0)
/Users/rolf/test/dotnet/maui/theapp/theapp.csproj : error NU1201: Project thelib is not compatible with net7.0-ios16.1 (.NETCoreApp,Version=v7.0) / maccatalyst-x64. Project thelib supports: net7.0-maccatalyst16.1 (.NETCoreApp,Version=v7.0)
```

While the wording is somewhat complex, it says that the net7.0-ios target framework doesn't support the library project, which is net7.0-maccatalyst.

That said, I agree that it might be an improvement if the IDE automatically added the target framework condition on the project reference item - unfortunately the IDE uses a different issue tracker.
