### ISSUE TITLE
Implement SourceLink support

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#18968]
Android did this: https://github.com/xamarin/xamarin-android/pull/7298

We should implement this as well.

Ref: https://github.com/xamarin/xamarin-macios/issues/11879

As part of this we should make sure the Health tab in the NuGet Package Explorer says we're OK:

![Screenshot 2023-09-19 at 07 19 52](https://github.com/xamarin/xamarin-macios/assets/249268/6eafbad4-1780-4e74-b96a-85dd377d1b82)

from: https://nuget.info/packages/Microsoft.iOS.Runtime.ios-arm64/16.4.8825-net8-rc1

**Comment by haritha-mohan** [comment]
Looks like dotnet 8 might have handled this for us:
https://github.com/dotnet/sourcelink/commit/10b97bb7abadaa1f6ca937cfbc4bba245437ff8e

![Screenshot 2023-11-29 at 5 03 58 PM](https://github.com/xamarin/xamarin-macios/assets/110641567/4a8ed9eb-75b4-40a2-a0ef-4a426ce57e47)

ref: https://nuget.info/packages/Microsoft.macOS.Sdk/14.0.8478
