### ISSUE TITLE
error MT0000: Unexpected error deploying to IOS device

### ISSUE THREAD

**Issue by CameronVetter** [xamarin/xamarin-macios#19004]
### Steps to Reproduce

1. Open a previously deployable project
2. Pair to Mac
3. Select iOS Remote device as target  
4. Click Start with Debugging
5. After waiting for compiling, project deploys to device, but fails to launch debugging with errors.

There is no rhyme or reason to this error, after many successful debugging sessions suddenly this error happens with no code or environment changes.  To resolve the issue I clean the build, restart the device, uninstall the app, reboot the mac, reboot the windows machine, and just keep flailing until it starts to work again.  

### Expected Behavior

Debugging sessions starts with app launching on physical device attached to mac.

### Actual Behavior

`
Error		error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new		 	0	
`

App is installed and can be launched on device.

### Environment
```

Microsoft Visual Studio Enterprise 2022
Version 17.7.3
VisualStudio.17.Release/17.7.3+34024.191
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA866
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.273.65229
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.273.65229
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.273.65229
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.23189.3
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.23189.3
Profiling support for Python projects.

Python with Pylance   17.0.23189.3
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.10.1
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20628.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.7.0.216 (d17-7@133ddef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

```

<details>
<summary>Version information</summary>

```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-maccatalyst           7.0.92/7.0.100         VS 17.7.34024.191
maccatalyst                16.4.7098/7.0.100      VS 17.7.34024.191
maui-windows               7.0.92/7.0.100         VS 17.7.34024.191
maui-ios                   7.0.92/7.0.100         VS 17.7.34024.191
ios                        16.4.7098/7.0.100      VS 17.7.34024.191
maui-android               7.0.92/7.0.100         VS 17.7.34024.191
android                    33.0.68/7.0.100        VS 17.7.34024.191
wasm-tools                 7.0.10/7.0.100         VS 17.7.34024.191
```

</details>

### Build Logs

```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>device</key>
	<dict>
		<key>architecture</key>
		<string>ARMv6, ARMv7, ARMv7s, ARM64</string>
		<key>model</key>
		<string>iPhone12,8</string>
		<key>os-version</key>
		<string>16.6</string>
		<key>os</key>
		<string>iOS</string>
	</dict>
</dict>
</plist>
, _iOSRuntimeIdentifier: ios-arm64, IsHotRestartBuild: False, MessagingVersion: 16.4.7098, _DotNetRootRemoteDirectory: /Users/cameronvetter\Library\Caches\Xamarin\XMA\SDKs\dotnet/, ServerSshPort: 22, ServerTcpPort: 59206, ServerUser: cameronvetter, ContinueOnDisconnected: False, ServerAddress: 192.168.0.155: 09/12/2023 15:57:03Z
    DateTime=2023-09-12T15:57:03.7744677Z: 09/12/2023 15:57:03Z
Xamarin.VisualStudio.IOS.PropertyProviders.BuildPropertiesProvider Information: 0 : Build properties for E:\Zecil\Board Game Copilot\frontend-blazor\Board Game Copilot\Board Game Copilot.csproj: VisualStudioProcessId: 15884, SolutionPath: E:\Zecil\Board Game Copilot\frontend-blazor\Board Game Copilot.sln, SolutionName: Board Game Copilot, RunConfiguration: Default, ArchiveOnBuild: False, ArchivePath: , IsAppDistribution: False, DeviceSpecificBuild: true, TargetiOSDevice: <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>device</key>
	<dict>
		<key>architecture</key>
		<string>ARMv6, ARMv7, ARMv7s, ARM64</string>
		<key>model</key>
		<string>iPhone12,8</string>
		<key>os-version</key>
		<string>16.6</string>
		<key>os</key>
		<string>iOS</string>
	</dict>
</dict>
</plist>
, _iOSRuntimeIdentifier: ios-arm64, IsHotRestartBuild: False, MessagingVersion: 16.4.7098, _DotNetRootRemoteDirectory: /Users/cameronvetter\Library\Caches\Xamarin\XMA\SDKs\dotnet/, ServerSshPort: 22, ServerTcpPort: 59206, ServerUser: cameronvetter, ContinueOnDisconnected: False, ServerAddress: 192.168.0.155: 09/12/2023 15:57:16Z
    DateTime=2023-09-12T15:57:16.5462331Z: 09/12/2023 15:57:16Z
Xamarin.VisualStudio.IOS.PropertyProviders.BuildPropertiesProvider Information: 0 : !Build properties for E:\Zecil\Board Game Copilot\frontend-blazor\Board Game Copilot\Board Game Copilot.csproj: VisualStudioProcessId: 15884, SolutionPath: E:\Zecil\Board Game Copilot\frontend-blazor\Board Game Copilot.sln, SolutionName: Board Game Copilot, RunConfiguration: Default, ArchiveOnBuild: False, ArchivePath: , IsAppDistribution: False, DeviceSpecificBuild: true, TargetiOSDevice: <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>device</key>
	<dict>
		<key>architecture</key>
		<string>ARMv6, ARMv7, ARMv7s, ARM64</string>
		<key>model</key>
		<string>iPhone12,8</string>
		<key>os-version</key>
		<string>16.6</string>
		<key>os</key>
		<string>iOS</string>
	</dict>
</dict>
</plist>
, _iOSRuntimeIdentifier: ios-arm64, IsHotRestartBuild: False, MessagingVersion: 16.4.7098, _DotNetRootRemoteDirectory: /Users/cameronvetter\Library\Caches\Xamarin\XMA\SDKs\dotnet/, ServerSshPort: 22, ServerTcpPort: 59206, ServerUser: cameronvetter, ContinueOnDisconnected: False, ServerAddress: 192.168.0.155: 09/12/2023 15:57:16Z
    DateTime=2023-09-12T15:57:16.5462331Z: 09/12/2023 15:57:16Z
Xamarin.Messaging.Client.MessagingClient Error: 0 : An error occurred on the receiver while executing a post for topic xvs/idb/launch-app and client vs15884camer
Xamarin.Messaging.Exceptions.MessagingRemoteException: An error occurred on client IDB1770216 while executing a reply for topic xvs/idb/launch-app ---> Xamarin.Messaging.Exceptions.MonotouchException: error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new

  at Xamarin.Messaging.IDB.MTouch.RunAsync (System.Collections.Generic.IList`1[T] parameters, System.Threading.CancellationToken cancellationToken, System.Func`2[T,TResult] exitCondition, Xamarin.Messaging.IDB.MTouchProcessType processType, System.Action`1[T] reportProgress, System.Action`1[T] handleOutput) [0x00256] in <7c86b7c1a1494c50b2a2a41dd5b8d140>:0 
  at Xamarin.Messaging.IDB.MTouch.LaunchAsync (Xamarin.Messaging.IDB.Contracts.AppInfo appInfo, Xamarin.Messaging.IDB.Contracts.AppleDevice device, System.Boolean debugging, System.Int32 port, System.Action`1[T] reportProgress) [0x0023a] in <7c86b7c1a1494c50b2a2a41dd5b8d140>:0 
  at Xamarin.Messaging.IDB.MTouch.LaunchAsync (Xamarin.Messaging.IDB.Contracts.AppInfo appInfo, Xamarin.Messaging.IDB.Contracts.AppleDevice device, System.Boolean debugging, System.Int32 port, System.Action`1[T] reportProgress) [0x00341] in <7c86b7c1a1494c50b2a2a41dd5b8d140>:0 
  at Xamarin.Messaging.IDB.LaunchAppMessageHandler.RunMTouchAsync (Xamarin.Messaging.IDB.Contracts.LaunchAppMessage message, System.Int32 port) [0x000e2] in <7c86b7c1a1494c50b2a2a41dd5b8d140>:0 
  at Xamarin.Messaging.IDB.LaunchAppMessageHandler.RunMTouchAsync (Xamarin.Messaging.IDB.Contracts.LaunchAppMessage message, System.Int32 port) [0x001a1] in <7c86b7c1a1494c50b2a2a41dd5b8d140>:0 
  at Xamarin.Messaging.IDB.LaunchAppMessageHandler.ExecuteOnPhysicalDeviceWithoutAssetsAsync (Xamarin.Messaging.IDB.Contracts.LaunchAppMessage message) [0x00091] in <7c86b7c1a1494c50b2a2a41dd5b8d140>:0 
  at Xamarin.Messaging.IDB.LaunchAppMessageHandler.ExecuteOnPhysicalDeviceAsync (Xamarin.Messaging.IDB.Contracts.LaunchAppMessage message) [0x003a7] in <7c86b7c1a1494c50b2a2a41dd5b8d140>:0 
  at Xamarin.Messaging.IDB.LaunchAppMessageHandler.ExecuteAsync (Xamarin.Messaging.IDB.Contracts.LaunchAppMessage message) [0x00104] in <7c86b7c1a1494c50b2a2a41dd5b8d140>:0 
  at Xamarin.Messaging.Client.RequestHandler`2[TMessage,TResult].HandleAsync (TMessage message) [0x0010e] in <48222b7d2f4e4881ae9ae3d7c4e56687>:0 
  at Xamarin.Messaging.Client.MessageHandlerManager+<>c__DisplayClass16_1`2[TMessage,TResult].<RegisterHandlerAsync>b__2 () [0x00084] in <48222b7d2f4e4881ae9ae3d7c4e56687>:0 
  at Xamarin.Messaging.Client.MessagingClient.ReplyAsync[TRequest,TResponse] (Xamarin.Messaging.Client.IRequest`1[T] request, Xamarin.Messaging.MessagePriority priority, System.Func`1[TResult] replyFunctionAsync) [0x000c5] in <48222b7d2f4e4881ae9ae3d7c4e56687>:0 
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.ApplicationMessageExtensions.<>c__DisplayClass10_0`1.<OfResponse>b__1(MqttApplicationMessage m) in D:\a\_work\1\s\src\Xamarin.Messaging.Client\Extensions\ApplicationMessageExtensions.cs:line 194
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__21`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 190: 09/12/2023 15:57:22Z
    DateTime=2023-09-12T15:57:22.2760457Z: 09/12/2023 15:57:22Z
Xamarin.Messaging.Ssh.MessagingClientPro Warning: 0 : An error occurred while executing the operation. The host connection is active and running so no retries will be attempted.: 09/12/2023 15:57:22Z
    DateTime=2023-09-12T15:57:22.2790459Z: 09/12/2023 15:57:22Z
```

**Comment by rolfbjarne** [comment]
Can you zip up and attach the logs in the `~/Library/Logs/Xamarin.Messaging*` directories on the Mac?

I believe this command should do it, if executed from the terminal:

```
zip -9r logs.zip ~/Library/Logs/Xamarin.Messaging*
```

**Comment by CameronVetter** [comment]
> Can you zip up and attach the logs in the `~/Library/Logs/Xamarin.Messaging*` directories on the Mac?
> 
> I believe this command should do it, if executed from the terminal:
> 
> ```
> zip -9r logs.zip ~/Library/Logs/Xamarin.Messaging*
> ```
[logs.zip](https://github.com/xamarin/xamarin-macios/files/12599022/logs.zip)

Here you go, let me know if anything else is needed...

**Comment by rolfbjarne** [comment]
Looks like this is the underlying cause:

> USB connect timeout (ENODATA), likely because the app failed to launch. Please review device logs and/or crash reports for more information.

Not sure why that happens.

A few ideas how to narrow this down:

* Can you launch the app by tapping on it?
* Can you launch a different project (by creating one from a template for instance)?
* Can you launch from VSMac (by creating a new project from a template for instance)?
* Can you launch from Xcode (by creating a new project)?

**Comment by CameronVetter** [comment]
> Looks like this is the underlying cause:
> 
> > USB connect timeout (ENODATA), likely because the app failed to launch. Please review device logs and/or crash reports for more information.
> 
> Not sure why that happens.
> 
> A few ideas how to narrow this down:
> 
> * Can you launch the app by tapping on it?
Yes it works fine but the debugger isn't connected.

> * Can you launch a different project (by creating one from a template for instance)?
Same result.

> * Can you launch from VSMac (by creating a new project from a template for instance)?
I do not have VSMac installed

> * Can you launch from Xcode (by creating a new project)?
Yes I did this and it worked fine.  I basically created hello world, built and debugged it in xcode with no changes to hardware or software.

**Comment by rolfbjarne** [comment]
> * Can you launch from VSMac (by creating a new project from a template for instance)?
>   I do not have VSMac installed

Can you try installing it to see if that works?

https://visualstudio.microsoft.com/vs/mac/

**Comment by CameronVetter** [comment]
> > * Can you launch from VSMac (by creating a new project from a template for instance)?
> >   I do not have VSMac installed
> 
> Can you try installing it to see if that works?
> 
> https://visualstudio.microsoft.com/vs/mac/

I installed vsmac and created a new xamarin project, since I didn't see Maui hybrid as being available.  It built fine and deployed to the phone, but sat with a spinner "waiting to connect on port 10000" or something like that.  Eventually, it gave an error saying the attempt to connect to the debugger timed out.  I went to the physical device and was able to run the xamarin app and it appears to have deployed and installed correctly.  So very similar problem to what is happening on my windows machine.

**Comment by rolfbjarne** [comment]
> > > * Can you launch from VSMac (by creating a new project from a template for instance)?
> > >   I do not have VSMac installed
> > 
> > 
> > Can you try installing it to see if that works?
> > [visualstudio.microsoft.com/vs/mac](https://visualstudio.microsoft.com/vs/mac/)
> 
> I installed vsmac and created a new xamarin project, since I didn't see Maui hybrid as being available. It built fine and deployed to the phone, but sat with a spinner "waiting to connect on port 10000" or something like that. Eventually, it gave an error saying the attempt to connect to the debugger timed out. I went to the physical device and was able to run the xamarin app and it appears to have deployed and installed correctly. So very similar problem to what is happening on my windows machine.

OK, that's progress, it means it's not a problem between Windows and Mac.

Next, could you try executing the following in a terminal on the Mac and attach the output here:

```shell

# Install the app on the device.
# Remember to replace the path to the actual .app bundle inside the project directory.
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch -vvvv --installdev path/to/project/bin/Debug/*.app

# Launch the app on the device
# Remember to replace the path to the actual .app bundle inside the project directory.
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch -vvvv --launchdev path/to/project/bin/Debug/*.app --wait-for-exit
```

Sidenote: if you have multiple devices connected, it might try to install/launch from the wrong one. In that case, execute this to list all the devices:

```shell
# This will list all the devices connected to the Mac
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch --listdev
```

and then add the `--devname NAME` to the two mlaunch commands above.

**Comment by CameronVetter** [comment]
Here they are, it did actually launch this time.  As I mentioned there is no obvious reason when it suddenly starts and stops working.
[output2.txt](https://github.com/xamarin/xamarin-macios/files/12629215/output2.txt)
[output1.txt](https://github.com/xamarin/xamarin-macios/files/12629216/output1.txt)

I tried then deployed from real Visual Studio and it worked fine.  So I guess what I'm saying is the state has likely switched to working for a bit and the output probably doesn't demo the issue.

**Comment by rolfbjarne** [comment]
> Here they are, it did actually launch this time. As I mentioned there is no obvious reason when it suddenly starts and stops working. [output2.txt](https://github.com/xamarin/xamarin-macios/files/12629215/output2.txt) [output1.txt](https://github.com/xamarin/xamarin-macios/files/12629216/output1.txt)
> 
> I tried then deployed from real Visual Studio and it worked fine. So I guess what I'm saying is the state has likely switched to working for a bit and the output probably doesn't demo the issue.

OK, I guess we'll have to wait until it happens again then. When it does, please re-execute those commands to try from the command line and attach the output here.

I'm marking as need-info until then - if the issue ends up closed, feel free to reopen (or as us to) once you have the updated output with the failure.

**Comment by CameronVetter** [comment]
I'm back in the same bad state so I just ran these two commands:

`/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch -vvvv --installdev Projects/teset/teset/bin/iPhone/Debug/device-builds/iphone12.8-16.6.1/teset.app > output1new.txt`

`/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch -vvvv --launchdev Projects/teset/teset/bin/iPhone/Debug/device-builds/iphone12.8-16.6.1/teset.app --wait-for-exit > output2new.txt`

Here are the output files:

[output2new.txt](https://github.com/xamarin/xamarin-macios/files/12679063/output2new.txt)
[output1new.txt](https://github.com/xamarin/xamarin-macios/files/12679064/output1new.txt)

**Comment by rolfbjarne** [comment]
Is the "Connect via Network" checkbox checked for you device? This is from Xcode (Window -> Devices and Simulators).

![Screenshot 2023-09-21 at 14 41 11](https://github.com/xamarin/xamarin-macios/assets/249268/e9d8bcb0-1b00-4bb6-882b-e2504d637f0d)

Does toggling this check box change anything?

**Comment by rolfbjarne** [comment]
OK, I have an updated mlaunch executable that should print more info (once the problem resurfaces)

Please go here:

https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.Tools.Mlaunch/overview/1.0.72-ci.pr.gh2710.72%20abe31eb035

and hit the Download button (upper right).

Then execute the following commands (this is assuming that the file ended up in your ~/Downloads directory):

```shell
xattr -s -c -r ~/Downloads/Microsoft.Tools.Mlaunch.1.0.72-ci.pr.gh2710.72.nupkg
unzip -d ~/Downloads/mlaunch-nupkg ~/Downloads/Microsoft.Tools.Mlaunch.1.0.72-ci.pr.gh2710.72.nupkg
chmod +x ~/Downloads/mlaunch-nupkg/mlaunch/bin/mlaunch
chmod +x ~/Downloads/mlaunch-nupkg/mlaunch/lib/mlaunch/mlaunch.app/Contents/MacOS/mlaunch
~/Downloads/mlaunch-nupkg/mlaunch/bin/mlaunch --version
```

The last command is just to verify everything went right, and it should print:

> Xamarin.Launcher 1.0.72 (ci.pr.gh2710: abe31eb035)

And then finally execute (the new) mlaunch to run on device:

> ~/Downloads/mlaunch-nupkg/mlaunch/bin/mlaunch -vvvv --launchdev Projects/teset/teset/bin/iPhone/Debug/device-builds/iphone12.8-16.6.1/teset.app --wait-for-exit > output2updatedmlaunch.txt

**Comment by CameronVetter** [comment]
> OK, I have an updated mlaunch executable that should print more info (once the problem resurfaces)
> 
> And then finally execute (the new) mlaunch to run on device:
> 
> > ~/Downloads/mlaunch-nupkg/mlaunch/bin/mlaunch -vvvv --launchdev Projects/teset/teset/bin/iPhone/Debug/device-builds/iphone12.8-16.6.1/teset.app --wait-for-exit > output2updatedmlaunch.txt

I was able to successfully do these steps and reproduce with the new mlaunch, here is the output:

[output2updatedmlaunch.txt](https://github.com/xamarin/xamarin-macios/files/12728491/output2updatedmlaunch.txt)

**Comment by CameronVetter** [comment]
Any updates on this @rolfbjarne ?  I had to return the mac laptop I was working on and bought a brand new mac mini.  I got everything setup and working reliably.  After a bunch of good development and debugging sessions I'm back in the exact same state on the new mac with the new install.  This is a huge blocker.

**Comment by rolfbjarne** [comment]
I'm sorry about the late reply.

I've created a updated version of the mlaunch tool, can you try and see if it makes a difference?

Here's the new link: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.Tools.Mlaunch/overview/1.0.81-ci.pr.gh2720.81%200ebc51cdbb

The instructions are the same as last time (except updated as needed because the version is different): https://github.com/xamarin/xamarin-macios/issues/19004#issuecomment-1729960150
