### ISSUE TITLE
Question: Xamarin.Mac + FileProvider migration path

### ISSUE THREAD

**Issue by AndirNotes** [xamarin/xamarin-macios#19040]
Sorry I wasn't able to find the answer anywhere.
Due to future planned deprecation of Xamarin.Mac and replacement it with .Net 7/8 + MAUI. What is the suggested migration path for non-UI related frameworks like FileProvider and FinderSync? Is anywhere a .Net-based alternative?

**Comment by rolfbjarne** [comment]
That shouldn't be very complicated, you can easily create a macOS-based .NET project:

```shell
$ dotnet new macos
```

It's a .NET project where `TargetFramework=net7.0-macos`. As for the migration itself, you can follow the MAUI migration documentation, it'll be very similar.

Just for reference: MAUI is similar to Xamarin.Forms, in that MAUI is added on top of the platform-specific project, it's not a requirement (just like you can create a Xamarin.iOS project and not use Xamarin.Forms, you can create an iOS project using .NET and not use MAUI).

I hope this helps!

**Comment by AndreyRusyaev** [comment]
> I hope this helps!

Hi, thank you for your answer! But could you please reopen the issue due to it's not answered.

I do understand migration path for UI Framework like Xamarin.Forms -> MAUI, but what about non-ui wrappers like MacOS FileProvider API (https://developer.apple.com/documentation/fileprovider)? Does it supported by .Net 7 or MAUI? I haven't found any mention in documentation.

**Comment by AndirNotes** [comment]
Hi @rolfbjarne,  thank you for your answer! 

I do understand migration path for UI Framework like Xamarin.Forms -> MAUI, but what about non-ui wrappers like MacOS FileProvider API (https://developer.apple.com/documentation/fileprovider)? Does it supported by .Net 7 or MAUI? I haven't found any mention in documentation.

Could you please reopen the issue due to it's not answered.

**Comment by rolfbjarne** [comment]
> Hi @rolfbjarne, thank you for your answer!
> 
> I do understand migration path for UI Framework like Xamarin.Forms -> MAUI, but what about non-ui wrappers like MacOS FileProvider API ([developer.apple.com/documentation/fileprovider](https://developer.apple.com/documentation/fileprovider))? Does it supported by .Net 7 or MAUI? I haven't found any mention in documentation.

Code using non-UI frameworks should work pretty much as-is (in fact, the only thing _not_ supported is Xamarin.Forms - which you'd have to upgrade to MAUI - but if you built your UI using AppKit directly for instance, that should work as well).

There be minor code changes required (we fixed numerous typos for instance), but that should be all.

**Comment by rolfbjarne** [comment]
> Great! Thank you! Do I understand correctly that all those Apple framework wrappers (except UI-related) were completely migrated from Xamarin.Mac to net7.0-macos framework as first-member libraries?

Correct.

> As far as I understand those wrappers generally were mostly generated for Xamarin.Mac from XCode SDK, does this also apply for net7.0-macos (and newer) target?

Correct.
