### ISSUE TITLE
System.DllNotFoundException on HttpWebRequest.SendRequest()

### ISSUE THREAD

**Issue by xfortin-devolutions** [xamarin/xamarin-macios#19111]
Sorry for skipping the template, but I really just need a confirmation to establish how to proceed on my side.

So my main question would be, is Xamarin.Mac (i.e. not .Net) still being updated? I've recently updated to macOS Sonoma to investigate a user issues which forced me to update to Xcode 15. With this version of Xcode, I get the error on the title on and HttpWebRequest (the missing DLL being /System/Library/Frameworks/CoreServices.framework/Frameworks/CFNetwork.framework/CFNetwork).

I do have a branch to implement .Net 7, but we sidelined this for a while since we were waiting for https://github.com/xamarin/xamarin-macios/issues/13873.

I'm wondering if, to build with Xcode 15, I will be forced to update to .Net 7?

**Comment by dalexsoto** [comment]
Can you give these packages a try? 

* Make sure you are using at least [xamarin.ios-16.4.0.18.pkg](https://download.visualstudio.microsoft.com/download/pr/de7f727f-243c-4429-8773-eebd735eb1bb/da4a65f27ace7f805914ef63661e0efd/xamarin.ios-16.4.0.18.pkg) / [xamarin.mac-9.3.0.18.pkg](https://download.visualstudio.microsoft.com/download/pr/de7f727f-243c-4429-8773-eebd735eb1bb/ad75896c1d3c57af522e9802c1d477a3/xamarin.mac-9.3.0.18.pkg) in your Mac build host. 

These should support Xcode 15 tooling just no new API bindings.

About Sonoma, can you give us more details on how to actually reproduce this issue?

**Comment by xfortin-devolutions** [comment]
Hi @dalexsoto,

Updating to 9.3.0.18 doesn't seem to have changed much. That being said, I think you can close the ticket. While I can still catch the exception (which is not the case when running with Xcode 14.3), I think it's not necessarily the causes of my main issue.

To make a short story, after updating to Xcode 15, most of the UI of my app has stopped rendering (see screenshot). I thought initially that this error, which was happening relatively early, stopped the building of the UI, but it's actually not the case, the UI is built properly, it simply does not render (i.e. I can "click" on buttons even if I don't see them). I have this issue even with .Net 7, so I really don't know what's going on.

For now, since it's a bit too much to investigate this (while I have a release incoming) I've rollbacked to Xcode 14.3 which, while I cannot launch it, can still be used in the building process for Rider/VS for Mac. So for now, this will have to do.

If I get a chance, I might try to create a small project reproducing my issues, although it might not be straight forward.

![NoRendering](https://github.com/xamarin/xamarin-macios/assets/13787434/1178c4a4-762c-40d9-9b84-8f8f10bb0fcc)

**Comment by rolfbjarne** [comment]
Closing as per last comment.
