### ISSUE TITLE
XCode 15 iOS 17 Support / April 2024 Deadline

### ISSUE THREAD

**Issue by dev2442422** [xamarin/xamarin-macios#19123]
### Question

Are you able to comment on if building Xamarin apps against Xcode 15 and Xamarin.iOS 16.4.0.18 will work to meet the April 2024 Xcode 15 / iOS 17 build requirement? I am having challenges migrating to .NET Maui, and hoping to buy some time before the deadline. Thanks!

**Comment by LennoxP90** [comment]
I am dead in the water and have to reinstall everything as I woke up this morning to a freshly update macOS sonoma, since Xamarin will never support xcode 15 i have to downgrade everything.

**Comment by omarhagoche** [comment]
> I am dead in the water and have to reinstall everything as I woke up this morning to a freshly update macOS sonoma, since Xamarin will never support xcode 15 i have to downgrade everything.

Same Here

**Comment by LeoJHarris** [comment]
> I am dead in the water and have to reinstall everything as I woke up this morning to a freshly update macOS sonoma, since Xamarin will never support xcode 15 i have to downgrade everything.

Yikes that one of the few things I dread in life a mac OS update and a broken Xcode as a result 😱 I suggest you disable automatic OS updates on your mac.

**Comment by LennoxP90** [comment]
I can tell you, after developing with Xamarin/MAUI for about 6 years now I really hate the entire Apple ecosystem. Whether it be some small update to Xamarin forms that breaks the UI, or the insane limitations they put on their devices wrt background processing. rant over. 

Side note I didn't need to  downgrade the mac yet... since I am able to debug using Xamarin.iOS 16.4.0.18 with Xcode15. #18409

**Comment by dev2442422** [comment]
@dalexsoto @rolfbjarne any update on this?

**Comment by thefex** [comment]
> LennoxP90
If you are on sonoma
1. Backup your xcode 14
2. Install xcode 15
3. Change Rider/Visual studio Xcode path to Xcode 14
4. Download https://github.com/xamarin/xamarin-macios/issues/18964 xamarin.ios from here

You can't open Xcode 14 - but you can build and debug to device and use Xamarin now.

**Comment by giuseppenovielli** [comment]
https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in-dotnet-8-rc-2/#bonus-2-xcode-15-and-android-api-34

**Comment by rolfbjarne** [comment]
Yes, we'll support using Xcode 15 with Xamarin.iOS 16.

Note that this does not include any new APIs shipped in Xcode 15, it's just tooling support.

**Comment by dev2442422** [comment]
@rolfbjarne does this mean we will now be safe to use Xamarin until the Xcode 16 requirement comes around in April 2025? i.e. We can continue to rely on Xamarin for our app until April 2025?

**Comment by rolfbjarne** [comment]
> @rolfbjarne does this mean we will now be safe to use Xamarin until the Xcode 16 requirement comes around in April 2025? i.e. We can continue to rely on Xamarin for our app until April 2025? What are the risks if we remain on Xamarin through April 2025?

Apple can change requirements whenever they want to. Historically, we've had issues where the App Store has started flagging private APIs we've unintentionally used (or sometimes they flag deprecated APIs we still have bindings for), and if that happens after Xamarin support has ended, you're only choice will be to migrate to .NET (an additional painpoint here is that you'll only find out at the worst possible moment: when you're ready to publish your app).

**Comment by jordi-additio** [comment]
I understand your answer @rolfbjarne, but I think that @dev2442422 was just asking if with Xamarin.IOS (and the same with Xamarin.Android in the future) we will be able to compile the app using iOS17 once Apple decides that this is a requirement (likely May 2024) or the only choice to compile with iOS17 will be to migrate to .net-ios.

**Comment by rolfbjarne** [comment]
> I understand your answer @rolfbjarne, but I think that @dev2442422 was just asking if with Xamarin.IOS (and the same with Xamarin.Android in the future) we will be able to compile the app using iOS17 once Apple decides that this is a requirement (likely May 2024) or the only choice to compile with iOS17 will be to migrate to .net-ios.

I can't speak for Xamarin.Android, but for Xamarin.iOS:

* Until support ends (currently May 2024), we'll make sure you can use Xcode 15.0 to build your apps, and that your apps will work on the latest stable version of iOS. Example: if apps built with Xamarin.iOS don't work with iOS 17.1 (and iOS 17.1 was released before our support ends), we'll fix Xamarin.iOS so that you can rebuild your apps to work with iOS 17.1. 
* We don't guarantee that we'll add support for new minor versions of Xcode (say Xcode 15.1), unless Apple starts requiring that new Xcode version before support ends (example: if Apple requires apps to be built with Xcode 15.1 in April 2024, we'll add support for Xcode 15.1).

After support ends, we won't do anything to break your projects, but Apple eventually will, one way or another. That may be in 2025 when they start requiring apps to be built with Xcode 16, or it may be earlier for some other reason.

**Comment by robertmaxted** [comment]
Hi All,

Anyone know what I need to do to env to deploy to iOS 17 device? 

Using visual studio for Mac

Xamarin.iOS
Version: 16.4.0.18 Visual Studio Community
Hash: https://github.com/xamarin/xamarin-macios/commit/9d266025eb8b10166e0844519f0b214ede83463b
Branch: xcode14.3
Build date: 2023-09-06 19:52:27-0400

Xcode:
Version 15.0.1 (15A507)

Any advice greatly appreciated.

**Comment by rolfbjarne** [comment]
> Hi All,
> 
> Anyone know what I need to do to env to deploy to iOS 17 device?
> 
> Using visual studio for Mac
> 
> Xamarin.iOS Version: 16.4.0.18 Visual Studio Community Hash: [9d26602](https://github.com/xamarin/xamarin-macios/commit/9d266025eb8b10166e0844519f0b214ede83463b) Branch: xcode14.3 Build date: 2023-09-06 19:52:27-0400
> 
> Xcode: Version 15.0.1 (15A507)
> 
> Any advice greatly appreciated.

@robertmaxted that should work. If it doesn't, please file a new issue and we'll have a look.

**Comment by robertmaxted** [comment]
> > Hi All,
> > Anyone know what I need to do to env to deploy to iOS 17 device?
> > Using visual studio for Mac
> > Xamarin.iOS Version: 16.4.0.18 Visual Studio Community Hash: [9d26602](https://github.com/xamarin/xamarin-macios/commit/9d266025eb8b10166e0844519f0b214ede83463b) Branch: xcode14.3 Build date: 2023-09-06 19:52:27-0400
> > Xcode: Version 15.0.1 (15A507)
> > Any advice greatly appreciated.
> 
> @robertmaxted that should work. If it doesn't, please file a new issue and we'll have a look.

Hi @rolfbjarne thank you for getting back to me. Here is the link for the new issue - https://github.com/xamarin/xamarin-macios/issues/19393

**Comment by munkii** [comment]
Should the XCode 15 support for Xamarin Forms be available when building in Azure Devops with a YAML pipeline? 

We are trying to build our app against XCode 15 so we are ready for the Spring 2024 deal;ine for needing apps compiled with XCode15.

I am assuming we would use the vmImage macOS-13 but that is failing.

**Comment by domneedham** [comment]
Has the Xamarin.Mac dependency been updated to match the Xcode version change? We are having a problem getting our .pkg accepted by the transporter app, which is trying to deploy to TestFlight. We are trying to identify if this is a build issue with the xcarchive or if this an issue with the signing. 

Any help would be appreciated.

**Comment by rolfbjarne** [comment]
@domneedham please file a new issue with the information you have and we'll have a look
