### ISSUE TITLE
Failed to compile the generated registrar code

### ISSUE THREAD

**Issue by ekrogh** [xamarin/xamarin-macios#19138]
### Steps to Reproduce

1. Open xamarin solution that hasn't been touched since 20-04-2023.
2. Rebuild .iOS project.

### Expected Behavior
Would build w.o. problems
### Actual Behavior
Build ends with message:
"
Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new	TimeDateCalculator.iOS	D:\Program_Files\Microsoft_Visual_Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	223	
"
### Environment

<details>
<summary>Version information</summary>

`Microsoft Windows Version 22H2 (OS Build 22621.2361)`
`Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.7.4`
`macOS 14.0'
`XCode 15.0`
' Visual Studio for mac NOT installed. Mono is installed on the mac'

</details>

### Build Logs

[CentralNode_devenv_PID=27464_x64_BuildManager_Default.zip](https://github.com/xamarin/xamarin-macios/files/12838893/CentralNode_devenv_PID.27464_x64_BuildManager_Default.zip)

**Comment by rolfbjarne** [comment]
This is the compilation failure:

        Compilation failed with code 1, command:
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wno-receiver-forward-class -Wno-objc-missing-super-calls -Wno-unguarded-availability-new -stdlib=libc++ -gdwarf-2 -std=c++14 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.15/SDKs/MonoTouch.iphoneos.sdk/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk -Qunused-arguments -miphoneos-version-min=11.2 -arch arm64 -c -o /Users/eks/Library/Caches/Xamarin/mtbs/builds/TimeDateCalculator.iOS/8b4b3095f11e95fa64d20f4f80b16220e27835bf1a23073de82b558aa6ef1aad/obj/iPhone/Debug/mtouch-cache/arm64/registrar.o -x objective-c++ /Users/eks/Library/Caches/Xamarin/mtbs/builds/TimeDateCalculator.iOS/8b4b3095f11e95fa64d20f4f80b16220e27835bf1a23073de82b558aa6ef1aad/obj/iPhone/Debug/mtouch-cache/registrar.m
        In file included from /Users/eks/Library/Caches/Xamarin/mtbs/builds/TimeDateCalculator.iOS/8b4b3095f11e95fa64d20f4f80b16220e27835bf1a23073de82b558aa6ef1aad/obj/iPhone/Debug/mtouch-cache/registrar.m:2:
        /Users/eks/Library/Caches/Xamarin/mtbs/builds/TimeDateCalculator.iOS/8b4b3095f11e95fa64d20f4f80b16220e27835bf1a23073de82b558aa6ef1aad/obj/iPhone/Debug/mtouch-cache/registrar.h:29:9: fatal error: 'NewsstandKit/NewsstandKit.h' file not found
        #import <NewsstandKit/NewsstandKit.h>

This is because you've updated to Xcode 15.

We just released a fix for this yesterday, so if you update the build should work again.
