### ISSUE TITLE
Lower the 'Deployment Target' to see older simulators or check your Apple SDK path"

### ISSUE THREAD

**Issue by yaj806** [xamarin/xamarin-macios#19135]
mac os ：14.0
xcode ：15
vs for mac：17.6.4

Cannot be debugged

**Comment by ithiredguns** [comment]
Same here 
<img width="371" alt="image" src="https://github.com/xamarin/xamarin-macios/assets/27841167/b8d3a73f-db90-4ced-a0f9-9a60d6b78942">
<img width="995" alt="image" src="https://github.com/xamarin/xamarin-macios/assets/27841167/1f0cb56c-3b54-464f-9ca6-4fbe596652ea">
<img width="529" alt="image" src="https://github.com/xamarin/xamarin-macios/assets/27841167/2d4a86e2-e4dd-4c1b-a640-81a02e6891b0">

**Comment by rolfbjarne** [comment]
Can you open "Xcode -> Settings -> Platforms" and make sure the iOS 17 platform is downloaded?

![Screenshot 2023-10-12 at 12 14 58](https://github.com/xamarin/xamarin-macios/assets/249268/233b4b30-dba0-46f3-a952-67a0a81a44e2)

Once you have the iOS 17 platform, also open "Xcode -> Window -> Devices and Simulators" and check whether you have any iOS 17 simulators:

![Screenshot 2023-10-12 at 12 16 29](https://github.com/xamarin/xamarin-macios/assets/249268/dc8995a6-5aac-4bd2-9404-e38a40f9a75a)
