### ISSUE TITLE
Library binding issue

### ISSUE THREAD

**Issue by avanzsistemas** [xamarin/xamarin-macios#19146]
I'm having problems with a native library and Firebase. I can't share the library due to confidentiality issues, but it's an iOS binding library.

The problem arises when both libraries coexist in the project. If they are separate, both work fine.

The Firebase library I am using is Firebase.iOS.CloudMessaging.

When I install it, there are many missing errors during native reference compilation of libswiftCore.dylb.

This can be corrected with the following, which I've seen in other forums:

```xml
<Target Name="CreateMtouchExtraArgs" AfterTargets="_DetectSdkLocations">      
	<PropertyGroup>         
		<MtouchExtraArgs>$(MtouchExtraArgs) -v -v -v -v -gcc_flags "-L /usr/lib/swift -L $(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos"</MtouchExtraArgs>         
		<_BundlerArguments Condition="'$(_PlatformName)' != 'macOS'">$(MtouchExtraArgs)</_BundlerArguments>     
	</PropertyGroup>     
	<Message Importance="high" Text="MtouchExtraArgs is $(MtouchExtraArgs)" />  
</Target>
```

With this, the app compiles, but when debugging the app crashes as soon as it opens. Looking at the analytics on the device, it says it can't find the libswiftCore.dlyb library. I fixed this problem by installing the Xamarin.Swift nuget which includes the necessary libraries, but the app still crashes with the following error:

"This copy of libswiftCore.dylib requires an OS version prior to 12.2.0."

### Steps to Reproduce

1.  Having Firebase.iOS.CloudMessage and a binding native library 
2. Deploy in physical device

### Expected Behavior
Being able to open the app and use it

### Actual Behavior
Crash and log "This copy of libswiftCore.dylib requires an OS version prior to 12.2.0."

**Comment by rolfbjarne** [comment]
Can you provide a [binary build log](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs)?
