### ISSUE TITLE
[macOS] PublishAot / NativeAOT not working

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#19206]
According to the [docs](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net8plus%2Cwindows#platformarchitecture-restrictions), NativeAOT is supported for macOS apps since .NET8. However I am having problems getting it to work

 ### Steps to Reproduce

1. `dotnet new macos`
2. Add  `<PublishAot>true</PublishAot>` to csproj
3. `dotnet publish`

### Expected Behavior
App builds with NativeAOT for both x64 and arm64 architectures

### Actual Behavior
`/usr/local/share/dotnet/sdk/8.0.100-rc.2.23502.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(224,5): error NETSDK1191: A runtime identifier for the property 'PublishAot' couldn't be inferred. Specify a rid explicitly. [/Users/tipa/Desktop/test/test.csproj]
`

### Workaround
I can specify an rid (like `osx-arm64`) explicitly, as stated in the error message, but I want to publish the app for both arm64 and x64

### Environment
8.0.100-rc.2.23502.2

### Example Project (If Possible)
[test.zip](https://github.com/xamarin/xamarin-macios/files/12905186/test.zip)

**Comment by rolfbjarne** [comment]
Support for universal builds (both x64 + arm64) wasn't ready for RC2, but we should get it in the final release (https://github.com/xamarin/xamarin-macios/pull/19183).

**Comment by tipa** [comment]
@rolfbjarne with rc2.1 I can now build the app without errors, but it no longer produces a "combined" .pkg file in the `Release/.net8.0-macos/publish` folder, but two separate .pkg files in the `osx-arm64/publish/ `and `os-x64/Publish/` subfolders. This isn't the expected behavior, or is it?

**Comment by rolfbjarne** [comment]
> @rolfbjarne with rc2.1 I can now build the app without errors, but it no longer produces a "combined" .pkg file in the `Release/.net8.0-macos/publish` folder, but two separate .pkg files in the `osx-arm64/publish/` and `osx-x64/publish/` subfolders. This isn't the expected behavior, or is it?

No, that's not the expected behavior, I filed a new issue here: https://github.com/xamarin/xamarin-macios/issues/19391.

Can you try adding this to your csproj to see if it fixes the problem for you?

```xml
<PropertyGroup>
    <UseCurrentRuntimeIdentifier>false</UseCurrentRuntimeIdentifier>
</PropertyGroup>
```

If that doesn't work, can you attach a binlog?

**Comment by tipa** [comment]
Thank you - that does work and produces a .pkg file.

Now I face a slightly related problem/question:
When I have built my iOS app with `NativeAot` enabled, I received this warning:
`/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.0.8465-net8-rc2.1/targets/Xamarin.Shared.Sdk.targets(505,3): warning : All assemblies must be processed by the linker when using NativeAOT. Please don't set neither the 'MtouchLink' nor the 'TrimMode' property, so that the build can default to linking all assemblies. `
I have removed `<TrimMode>full</TrimMode>`, the warning disappeared and the app was very small - perfect!

Now, I assumed I had to remove the `TrimMode` property in the csproj of my macOS app as well, so I did remove it. The resulting .pkg was massive in size (`pgk` file 82 MB, `app` file 236 MB) - even though I use barely any dependencies in this app! The `Microsoft.macOS.dll` file alone is 27.6 MB large. So it seems like there is no linking/trimming happening. I added back the `TrimMode=True` property and re-built the app:
- The app was much smaller again (`pkg` file 24 MB, `app` file 71 MB) - `Microsoft.macOS.dll` at 1.4 MB
- There was no warning like in the iOS app

So NativeAot has different requirements/defaults on macOS compared to iOS? Shouldn't NativeAOT also trim all assemblies by default on macOS?

**Comment by rolfbjarne** [comment]
The default trimming is different for NativeAOT, it's `TrimMode=full` for all platforms.

When not using NativeAOT, the default varies depending on the platform, it's `MtouchLink=SdkOnly` when building for device (either iOS or tvOS) or when building a release build for Mac Catalyst, otherwise (simulator/Debug Mac Catalyst/any configuration macOS), the default is `MtouchLink=None`.

Ref: https://github.com/xamarin/xamarin-macios/blob/1f41b82a3080e931c7c3f58dcdd4fc2eb015ad32/dotnet/targets/Xamarin.Shared.Sdk.targets#L1623-L1629

At least this is how it should work. Can you get a binlog of the NativeAOT macOS build where no trimming happened?

**Comment by tipa** [comment]
Apologies, I had a typo in the `PublishAot` property 🤦 Working as expected now
