### ISSUE TITLE
Incorrect SupportedOSPlatform attributes on various properties

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#19209]
Similar bug report as here: https://github.com/xamarin/xamarin-macios/issues/19066

### Steps to Reproduce

Use `NSMutableParagraphStyle.TextLists` in a project with MinimumOSVersion < 16.0

### Expected Behavior
No warning

### Actual Behavior
`/Users/tipa/GitHub/diarium/Diarium/Classes/Helper_macios.cs(99,25): warning CA1416: This call site is reachable on: 'iOS' 15.0 and later, 'maccatalyst' 15.0 and later. 'NSParagraphStyle.TextLists' is only supported on: 'ios' 16.0 and later, 'maccatalyst' 16.0 and later, 'tvos' 16.0 and later. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416) 
`

### Comments

Documented to be available since iOS 7:
https://developer.apple.com/documentation/uikit/nsparagraphstyle/1534193-textlists?language=objc

https://github.com/xamarin/xamarin-macios/blob/343699204a3ff1f591e861e046baa672fc7e6626/src/xkit.cs#L1797-L1799
I haven't tested functionality yet, but at least setting & getting the property does not crash on iOS 15:

```
var xx = new NSMutableParagraphStyle();
xx.TextLists = new[] { new NSTextList(NSTextListMarkerFormats.Circle) };
var yy = xx.TextLists[0];
```

Documented to be available since iOS 9:
https://developer.apple.com/documentation/uikit/nsparagraphstyle/3667463-linebreakstrategy?language=objc

https://github.com/xamarin/xamarin-macios/blob/343699204a3ff1f591e861e046baa672fc7e6626/src/xkit.cs#L1811-L1814

There's probably even more properties for which Apple changed their min API level with the last SDK...

### Environment
.NET 8 RC2

**Comment by rolfbjarne** [comment]
Apple's attributes are interesting to say the least...

The `NSLineBreakStrategy` enum is available in iOS 14+: https://developer.apple.com/documentation/uikit/nslinebreakstrategy?language=objc

But the `NSLineBreakStrategy.PushOut` enum value is available in iOS 9+: https://developer.apple.com/documentation/uikit/nslinebreakstrategy/nslinebreakstrategypushout?language=objc

**Comment by tipa** [comment]
Not sure if this is related or fixed with the changes you made, but I still get warnings when accessing the property even when guarded by `OperatingSystem.IsIOSVersionAtLeast`

```
var p = new NSMutableParagraphStyle();
if (OperatingSystem.IsIOSVersionAtLeast(17))
{
    p.TextLists = new[] { new NSTextList("{decimal}.") };
}
```

However no warnings when using NSParagraphStyle
```
var p = new NSParagraphStyle();
if (OperatingSystem.IsIOSVersionAtLeast(17))
{
    p.TextLists = new[] { new NSTextList("{decimal}.") };
}
```

And also this works
```
var p = new NSMutableParagraphStyle();
if (OperatingSystem.IsIOSVersionAtLeast(17))
{
  ((NSParagraphStyle)p).TextLists = new[] { new NSTextList("{decimal}.") };
}
```

Maybe also worth noting that [textLists  of NSParagraphStyle doesn't has a setter](https://developer.apple.com/documentation/uikit/nsparagraphstyle/1534193-textlists), but the .NET bindings do

**Comment by rolfbjarne** [comment]
That's because the fix didn't get in in time for the initial .NET 8 release. We'll probably ship it when we ship Xcode 15.1 support.

**Comment by tipa** [comment]
@rolfbjarne I am using Xcode 15.2 and the latest .NET versions, but the warning is still there. Has this change been shipped yet?

**Comment by rolfbjarne** [comment]
@tipa no, I just checked, this fix hasn't been released yet. Our release supporting Xcode 15.1 turned out to be a minimal service release, with very few changes. Xcode 15.2 didn't really change anything for us (just added the visionOS SDK, which we don't support), so that didn't necessitate any release for us. At this point we might release this fix when we add support for Xcode 15.3.

**Comment by rolfbjarne** [comment]
Your project works fine for me, I difference between the down and the up timestamps are way less than one second, unless I hold for a while.

Does this happen in both the simulator and on device for you? Exactly which device do you have, and which iOS version does it have?

**Comment by rolfbjarne** [comment]
NVM my last comment, that was for a different issue.
