### ISSUE TITLE
[Xcode15] Add missing binding in WebKit

### ISSUE THREAD

**Issue by haritha-mohan** [xamarin/xamarin-macios#19259]
A new API added in WebKit requires support from the Network framework:

`requires OS_nw_proxy_config type which has not been bound yet, part of Xcode 15 Network binding`
`!missing-selector! WKWebsiteDataStore::proxyConfigurations not bound`
`!missing-selector! WKWebsiteDataStore::setProxyConfigurations: not bound`

from https://github.com/xamarin/xamarin-macios/pull/19237

part of https://github.com/xamarin/xamarin-macios/issues/18556

**Comment by thenextman** [comment]
Is there anything blocking this now that `NWProxyConfig` is bound? I would love to see this added.
