### ISSUE TITLE
Clang++ exited with code 1 - Duplicate Symbols

### ISSUE THREAD

**Issue by vouksh** [xamarin/xamarin-macios#19378]
I'm encountering an issue while trying to build a project that's referencing a native binding library. 
The binding project was created with .NET 7, and builds an runs with a .NET 7 project. However, in a .NET 8 project, the build fails due to "duplicate symbols" and "duplicate libraries"

I have verified that the library does not contain duplicate symbols using the method from [Xamarin.iOS Errors](https://learn.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#mt5212-native-linking-failed-duplicate-symbol-)
Here is the fgrep output for one of the symbols the log says is duplicated:
```
jackaardal@*** BlueRadioBrsp64 % nm lib_brsp_1.3.1.arm64.a | fgrep '_isDataModeSupported'
000000000000c9a8 S _OBJC_IVAR_$_Brsp._isDataModeSupported
jackaardal@*** BlueRadioBrsp64 %
```
The output is reporting that literally every symbol in the library is a duplicate. 
It seems like it's trying to link from both the local path on my Windows laptop and from the remote path on the MacBook, as it's listed twice in the clang++ arguments. 

I've tried multiple solutions presented in various other issues, and nothing changes. 

### Steps to Reproduce

1. Create an iOS binding library 
2. Set the native reference to Static, don't enable SmartLink, and enable ForceLoad
3. Reference binding project from .NET 8.0 RC2 MAUI app
4. Pair to a MacBook from Windows
5. Attempt to build.

### Expected Behavior
App builds and is able to utilize native library
### Actual Behavior
Build fails with false duplicate symbol errors. 
```
duplicate symbol '_OBJC_IVAR_$_Brsp._serviceDiscoveryCount' in:
    D:/Nuget/blueradiobrsp64/1.1.0-preview1017/lib/net7.0-ios16.1/BlueRadioBrsp64.resources/lib_brsp_1.3.1.a(Brsp.o)
    /Users/jackaardal/Library/Caches/Xamarin/mtbs/builds/KinesiaOne/7669fae6a0e78117d3638e4eb3145c6038ab08ffdc3d331766a0d10d73a8f661/D:/Nuget/blueradiobrsp64/1.1.0-preview1017/lib/net7.0-ios16.1/BlueRadioBrsp64.resources/lib_brsp_1.3.1.a(Brsp.o)
```
### Environment

<details>
<summary>Windows Development Environment</summary>

``` 
[System Summary]

Item	Value	
OS Name	Microsoft Windows 11 Business	
Version	10.0.22621 Build 22621	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Name	***
System Manufacturer	Dell Inc.	
System Model	Precision 7550	
System Type	x64-based PC	
System SKU	09C3	
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)	
BIOS Version/Date	Dell Inc. 1.21.0, 2/13/2023	
SMBIOS Version	3.2	
Embedded Controller Version	255.255	
BIOS Mode	UEFI	
BaseBoard Manufacturer	Dell Inc.	
BaseBoard Product	04JGVR	
BaseBoard Version	A01	
Platform Role	Mobile	
Secure Boot State	On	
PCR7 Configuration	Elevation Required to View	
Windows Directory	C:\WINDOWS	
System Directory	C:\WINDOWS\system32	
Boot Device	\Device\HarddiskVolume1	
Locale	United States	
Hardware Abstraction Layer	Version = "10.0.22621.1413"	
User Name	***
Time Zone	Eastern Daylight Time	
Installed Physical Memory (RAM)	32.0 GB	
Total Physical Memory	31.6 GB	
Available Physical Memory	13.4 GB	
Total Virtual Memory	63.6 GB	
Available Virtual Memory	36.1 GB	
```
</details>
<details>
<summary>MacOS Development Environment</summary>

```
Model: MacBook Pro 17
CPU: Apple M1
RAM: 16GB
OS: macOS Sonoma 14.1
```
</details>
<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Community 2022
Version 17.8.0 Preview 5.0
VisualStudio.17.Preview/17.8.0-pre.5.0+34219.65
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA965
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.8.345.5765
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.8.345.5765
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.8.345.5765
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.8.0-3.23517.14+be69ebdb4e1da91e51c83fce238cf107c1d5bc15
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.23262.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.8.17 (957fbed)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.6.34024.01
Microsoft Office Developer Tools for Visual Studio

Python - Profiling support   17.0.23262.1
Profiling support for Python projects.

Python with Pylance   17.0.23262.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.8.3.2351103+cc267329450bc99a027494153251905b45ede2a3
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.8.117.1
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20920.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.8.0-3.23517.14+be69ebdb4e1da91e51c83fce238cf107c1d5bc15
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.8.0-beta.23475.2+10f956e631a1efc0f7f5e49c626c494cd32b1f50
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   17.8.0.151 (d17-8@5ca38ed)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.8.3.6 (remotes/origin/d17-8@eccf46a291)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.8.16 (830b56a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d


Xamarin.iOS and Xamarin.Mac SDK   16.4.0.18 (9d266025e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs

[msbuild-asnuget.zip](https://github.com/xamarin/xamarin-macios/files/13227268/msbuild-asnuget.zip)
[msbuild-asproject.zip](https://github.com/xamarin/xamarin-macios/files/13227269/msbuild-asproject.zip)

### Example Project (If Possible)
I'm unable to provide an example project, as the library is proprietary, and we don't have permission to share it.

**Comment by rolfbjarne** [comment]
Would you be able to share the BlueRadioBrsp64 NuGet (.nupkg file) with us?

**Comment by vouksh** [comment]
@rolfbjarne Do you have a way I can send it directly to you? I am not allowed to share it publicly, but I have permission to send it to you for support. It's a binding library to communicate with a proprietary Bluetooth sensor.

**Comment by rolfbjarne** [comment]
> I am not allowed to share it publicly, but I have permission to send it to you for support.

If you create a new feedback ticket here: https://developercommunity.visualstudio.com/VisualStudioMac/report, you can add private attachments afterwards. Explain in the ticket that you're just adding private information to this issue, and post a link here to the feedback ticket so I can link them up.

**Comment by vouksh** [comment]
Submitted and attached the files.
As a bit of extra background, this library has worked previously. I'm in the process of rewriting one of our Xamarin.iOS native apps into MAUI. It is currently working in production with no issues, and the duplicate symbol errors seem to be unique to .NET 8.

**Comment by rolfbjarne** [comment]
Can you try adding setting `CompressBindingResourcePackage=true` in the binding project to see if that makes it work?

```xml
<PropertyGroup>
    <CompressBindingResourcePackage>true</CompressBindingResourcePackage>
</PropertyGroup>
```

**Comment by vouksh** [comment]
That allows me to build, but now when accessing the library the app crashes.
```
11:42:20:081	=================================================================
11:42:20:081		Native Crash Reporting
11:42:20:081	=================================================================
11:42:20:081	Got a SIGABRT while executing native code. This usually indicates
11:42:20:081	a fatal error in the mono runtime or one of the native libraries 
11:42:20:081	used by your application.
11:42:20:081	=================================================================
11:42:20:081	
11:42:20:081	=================================================================
11:42:20:081		Native stacktrace:
11:42:20:081	=================================================================
11:42:20:081	
11:42:20:874	The app has been terminated.
11:42:20:874	1f31173d8  c0 03 5f d6 d0 03 80 d2 01 10 00 d4 03 01 00 54  .._............T
11:42:20:874	
11:42:20:874		0x10050a95c - /private/var/containers/Bundle/Application/78603BED-58BD-4DD4-968D-37507F8C5307/KinesiaOne.app/KinesiaOne : AppleCryptoNative_X509ImportCollection
11:42:20:874		0x1004f2384 - /private/var/containers/Bundle/Application/78603BED-58BD-4DD4-968D-37507F8C5307/KinesiaOne.app/KinesiaOne : AppleCryptoNative_X509ImportCollection
11:42:20:874		0x1006450a4 - /private/var/containers/Bundle/Application/78603BED-58BD-4DD4-968D-37507F8C5307/KinesiaOne.app/KinesiaOne : AppleCryptoNative_X509ImportCollection
11:42:20:874		0x10050a14c - /private/var/containers/Bundle/Application/78603BED-58BD-4DD4-968D-37507F8C5307/KinesiaOne.app/KinesiaOne : AppleCryptoNative_X509ImportCollection
11:42:20:874		0x215611888 - /usr/lib/system/libsystem_platform.dylib : <redacted>
11:42:20:874		0x1f313dee0 - /usr/lib/system/libsystem_kernel.dylib : <redacted>
11:42:20:874		0x1f313df14 - /usr/lib/system/libsystem_kernel.dylib : 
11:42:20:874		0x1cc7d7910 - /System/Library/PrivateFrameworks/TCC.framework/TCC : <redacted>
11:42:20:874		0x1cc7d3ebc - /System/Library/PrivateFrameworks/TCC.framework/TCC : <redacted>
11:42:20:874		0x1cc7db210 - /System/
11:42:20:874	Library/PrivateFrameworks/TCC.framework/TCC : <redacted>
11:42:20:874		0x215716b44 - /usr/lib/system/libxpc.dylib : <redacted>
11:42:20:874		0x2157094b4 - /usr/lib/system/libxpc.dylib : <redacted>
11:42:20:874		0x1b445b380 - /usr/lib/system/libdispatch.dylib : <redacted>
11:42:20:874		0x1b4478b04 - /usr/lib/system/libdispatch.dylib : <redacted>
11:42:20:874		0x1b446dd40 - /usr/lib/system/libdispatch.dylib : <redacted>
11:42:20:874		0x1b446d628 - /usr/lib/system/libdispatch.dylib : <redacted>
11:42:20:874		0x2156b699c - /usr/lib/system/libsystem_pthread.dylib : _pthread_wqthread
11:42:20:874		0x2156b6a04 - /usr/lib/system/libsystem_pthread.dylib : start_wqthread
11:42:20:874	
11:42:20:874	=================================================================
11:42:20:874		Basic Fault Address Reporting
11:42:20:874	=================================================================
11:42:20:874	Memory around native instruction pointer (0x1f31173b8):0x1f31173a8  ff 0f 5f d6 c0 03 5f d6 30 41 80 d2 01 10 00 d4  .._..._.0A......
11:42:20:874	0x1f31173b8  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
11:42:20:874	0x1f31173c8  01 d5 ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  .........{...._.
11:42:20:874	0x
```

When looking back through the build logs, I now see this warning:
```
6>C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.0.8465-net8-rc2.1\tools\msbuild\iOS\Xamarin.iOS.Common.After.targets(364,3): warning MT1308: Could not extract the native library 'lib_brsp_1.3.1.a' from the assembly '/Users/jackaardal/Library/Caches/Xamarin/mtbs/builds/KinesiaOne/7669fae6a0e78117d3638e4eb3145c6038ab08ffdc3d331766a0d10d73a8f661/D:/repos/KinesiaOne-Maui/DeviceAPIs/BlueRadioBrsp64/bin/Debug/net8.0-ios/BlueRadioBrsp64.dll', because it doesn't contain the resource 'lib_brsp_1.3.1.a'.
```

**Comment by rolfbjarne** [comment]
> /System/Library/PrivateFrameworks/TCC.framework/TCC : <redacted>

That looks like a missing entry in your Info.plist for some feature iOS will show a permission dialog about.

You should get a somewhat better crash report if you disable stripping in your csproj:

```xml
<PropertyGroup>
    <NoSymbolStrip>true</NoSymbolStrip>
</PropertyGroup>
```

that might reveal a bit more.

**Comment by vouksh** [comment]
I had to examine the device log, but you were correct, I was missing a few lines from my Info.plist. I'm able to build, deploy, and access the native library again. Perhaps there should be some documentation about potentially needing 
```
<PropertyGroup>
    <CompressBindingResourcePackage>true</CompressBindingResourcePackage>
</PropertyGroup>
``` 
in the csproj file? 

Either way, your help is greatly appreciated as I've spent the last several days trying to figure this out.

**Comment by rolfbjarne** [comment]
> I had to examine the device log, but you were correct, I was missing a few lines from my Info.plist. I'm able to build, deploy, and access the native library again. Perhaps there should be some documentation about potentially needing
> 
> ```
> <PropertyGroup>
>     <CompressBindingResourcePackage>true</CompressBindingResourcePackage>
> </PropertyGroup>
> ```
> 
> in the csproj file?

It shouldn't be needed, it's a bug on our side somewhere.

I'll look into it.

**Comment by vouksh** [comment]
Thanks. Let me know if I can provide any more information.

**Comment by vouksh** [comment]
@rolfbjarne I just wanted to let you know, I was incorrect. The app doesn't crash, but I'm unable to actually interact with the library. Everything is blank/null when trying to reference anything from the library. For example, we scan for Bluetooth devices using a CBUUID from the library, but the property is empty, I'm still seeing the MT1308 warning I mentioned before, so it's like it's linking, but not including the native library. Hard to really describe. I can provide the intermediate project that we use to interact with the sensors if that would help.

**Comment by rolfbjarne** [comment]
@vouksh can you add this to the csproj:

```xml
<PropertyGroup>
    <MtouchExtraArgs>-v -v -v -v</MtouchExtraArgs>
</PropertyGroup>
```

and then a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs)?

**Comment by vouksh** [comment]
Here's a binlog with that added: [binlogs.zip](https://github.com/xamarin/xamarin-macios/files/13268339/binlogs.zip)

**Comment by vouksh** [comment]
No change, still null references. 
[nobindingembedding-false.zip](https://github.com/xamarin/xamarin-macios/files/13268738/nobindingembedding-false.zip)

**Comment by rolfbjarne** [comment]
Ah sorry I was unclear, the NoBindingEmbedding=false property goes in the binding project.

**Comment by vouksh** [comment]
Sadly, still no change. 
[MSBuild_Logs.zip](https://github.com/xamarin/xamarin-macios/files/13288804/MSBuild_Logs.zip)

**Comment by rolfbjarne** [comment]
The native library `lib_brsp_1.3.1.a` is linked into the native executable, so that's good.

However, I looked at your ApiDefinition.cs, and it looks like the interface definition for the Brsp type is wrong: it doesn't look like a protocol, in which case you should remove the [Protocol] attribute. Can you try that and see if it makes a difference?

**Comment by vouksh** [comment]
No change, unfortunately. It's odd because the ApiDefinition and StructsAndEmums are direct copy-paste from the original Xamarin.iOS binding project which works perfectly.

**Comment by rolfbjarne** [comment]
Can you create a test project that shows the problem and attach it to the feedback ticket you created earlier?

**Comment by vouksh** [comment]
Here's an interesting development: I copied the BlueRadioBrsp64 project into a new MAUI solution, added the project reference, and copied the bare minimum of files from the intermediate library I was using, and the fresh MAUI solution was able to properly utilize the native library. 

So there's something messed up in my current solution. I'm going to do some digging to figure out what's going on and will update later.

**Comment by vouksh** [comment]
Ok, after cleaning up my entire environment (including removing the .vs folder and csproj.user files), updating Visual Studio, then copying all of the changes you've suggested into the Nuget solution and rebuilding, I'm now able to utilize the library in the app. 

Thank you so much for the assistance, and let me know if I can provide any more information.
