### ISSUE TITLE
.NET 7.0 iOS Notification extension service error MSB4057: The target "GetBundleTargetPath" does not exist in the project.

### ISSUE THREAD

**Issue by acespedes451** [xamarin/xamarin-macios#19385]
### Steps to Reproduce

1. Create a .NET iOS application for .NET 7. MinOSVersion 13.0 and deviceFamily iphone
2. Add a notification extension service:
Currently does not exist a template for adding a notification extension service for .NET 7, so you can do easily by downloading this template:
https://www.nuget.org/packages/VladislavAntonyuk.DotNetTemplates
a- Add a new project and select the new installed template (iOS Notification Service Extension -Vladislav Antonyuk-)
3. On the main iOS project edit the .csproj file and add the following line in order to add the reference to the notification service extension) -replace ..\Project1\Project1.csproj with your path-:
```
	<ItemGroup>
		<ProjectReference Include="..\Project1\Project1.csproj">
			<IsAppExtension>true</IsAppExtension>
			<IsWatchApp>false</IsWatchApp>
		</ProjectReference>
	</ItemGroup>
```
4. That's all. Build.

### Expected Behavior
Build should success

### Actual Behavior
When I try to build the entire solution, i get the following error:
"error MSB4057: The target "GetBundleTargetPath" does not exist in the project."

### Environment
<details>
Microsoft Visual Studio Community 2022
Version 17.7.6
VisualStudio.17.Release/17.7.6+34221.43
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.274.37181
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2012   17.7.274.37181
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.7.274.37181
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.274.37181
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.7.0-3.23517.17+9d4cc0304792762c34f41cbbec67a1fcd2dc764f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub Copilot   1.129.0.0 (v1.129.0.0@14216f256)
GitHub Copilot is an AI pair programmer that helps you write code faster and with less work.

GitHub Copilot Agent   1.129.0

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.50628.1 Commit Hash:f9e713b25f69afd3ced63d934e0722003b73c121
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.12.0
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20829.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23517.17+9d4cc0304792762c34f41cbbec67a1fcd2dc764f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.7.0.223 (d17-7@c374b3e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.7.21 (150ec9f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.18 (9d266025e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
</details>

### Build Logs

[iOSApp1_Debug_AnyCPU_Build_2023-11-02T10_29_26.4399728-03_00.zip](https://github.com/xamarin/xamarin-macios/files/13239355/iOSApp1_Debug_AnyCPU_Build_2023-11-02T10_29_26.4399728-03_00.zip)

### Example Project (If Possible)

[iOSApp1.zip](https://github.com/xamarin/xamarin-macios/files/13239351/iOSApp1.zip)

**Comment by rolfbjarne** [comment]
Can you try connecting to a remote mac to see if that works?

**Comment by acespedes451** [comment]
Hi @rolfbjarne.
I'm testing on my Windows PC, connected to a remote mac.
Now I tested directly on my mac with VS and got the same error.
I have Xcode v. 15.0.1
Here is the mac's build output:
[macLog.txt](https://github.com/xamarin/xamarin-macios/files/13240894/macLog.txt)

**Comment by rolfbjarne** [comment]
OK, I can reproduce, this only happens from within the IDE.

It works if you change use `TargetFramework` (singular) instead of `TargetFrameworks` (plural) in the app extension csproj:

```xml
<PropertyGroup>
    <TargetFramework>net7.0-ios</TargetFramework>
</PropertyGroup>
```

Can you try that and see if it works for you?

**Comment by acespedes451** [comment]
Thank you so much!!. It's working now, on my mac and PC.
It Would be great if the VS dev team adds the iOS extension's templates for .NET, because nowadays the only way to use the template is working with Xamarin.

**Comment by rolfbjarne** [comment]
> It would be great if the VS dev team adds the iOS extension's templates for .NET

It's on our TODO list already, hopefully we'll get it done in .NET 9.

**Comment by ispysoftware** [comment]
I also have a service extension project on IOS - using TargetFramework resolved the error when building the extensionbut when I build the project that references it I end up back with the same error.

extension project on it's own:
1>AgentServiceExtension -> D:\Projects\agent-service\MAUI\AgentServiceExtension\bin\iPhone\Release\net7.0-ios\ios-arm64\AgentServiceExtension.dll
1>Done building project "AgentServiceExtension.csproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

when building the main app:

2>D:\Projects\agent-service\MAUI\AgentServiceExtension\AgentServiceExtension.csproj : error MSB4057: The target "GetBundleTargetPath" does not exist in the project.
2>Done building project "AgentServiceExtension.csproj" -- FAILED.

The main app has 
`<TargetFrameworks>net7.0-ios</TargetFrameworks>`

The extension project has:
`<TargetFramework>net7.0-ios</TargetFramework>`

any ideas?
