### ISSUE TITLE
App with notification extension service fails to deploy inside an iPhone: "App cannot be installed because it's integrity could not be verified"

### ISSUE THREAD

**Issue by acespedes451** [xamarin/xamarin-macios#19395]
### Steps to Reproduce
This is an example app with a notification service extension to add the push notification's support

1.  Download the example app
2. Go to developers.apple.com and:
a. Create the app identifier (in this case, com.test.mobileapp).
In this case, you must check the "app groups" option and put this: group.com.test.mobileapp.onesignal.
Besides, you must check "push notifications".
b. Create the app certificate
c. Create the iOS development profile
3. On the example project "test2" inside bundle signing, put the created profile and inside the "Project1" (extension service), leave it on automatic signin.
4. Select debug and deploy into an iPhone.
NOTE: If i deploy into an emulator or if I remove the notification service extension reference from the main project and deploy into my iPhone device, works perfectly.

### Expected Behavior
App should be initiated in my iphone

### Actual Behavior
VS gets stuck with the following message "waiting for the debugger to connect to iPhone X on port 10000 via USB".
If I proceed to open the app on my iPhone, I get the following message "Click on app: "App cannot be installed because it's integrity could not be verified"

### Environment
<details>
Visual Studio Community 2022 for Mac
Version 17.6.6 (build 408)
Installation UUID: dbb44e39-e3ec-46fe-8d24-744c27951155
Runtime
.NET 7.0.3 (64-bit)
Architecture: X64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2
Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa
NuGet
Version: 6.4.0.117
Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-10-23 17:40:07 UTC
.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.310/Sdks
SDK Versions:
	7.0.310
	7.0.309
	7.0.308
	7.0.202
	7.0.200
	6.0.416
	6.0.415
	6.0.414
	6.0.407
	6.0.406
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks
.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.13
	7.0.12
	7.0.11
	7.0.4
	7.0.3
	6.0.24
	6.0.23
	6.0.22
	6.0.15
	6.0.14
Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
Updater
Version: 11
Xamarin.Android
Not Installed
Microsoft Build of OpenJDK
Java SDK: Not Found
Eclipse Temurin JDK
Java SDK: Not Found
Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-10-23 17:40:12 UTC
Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-10-23 17:40:12 UTC
Apple Developer Tools
Xcode: 15.0.1 22266
Build: 15A507
Xamarin.Mac
Not Installed
Xamarin.iOS
Version: 16.4.0.18 Visual Studio Community
Hash: 9d266025e
Branch: xcode14.3
Build date: 2023-09-06 19:52:27-0400
Build Information
Release ID: 1706060408
Git revision: 3912eca6712af97335aa3a782abaa75ff86ec74a
Build date: 2023-10-23 17:38:20+00
Build branch: release-17.6
Build lane: release-17.6
Operating System
Mac OS X 14.0.0
Darwin 23.0.0 Darwin Kernel Version 23.0.0
    Fri Sep 15 14:42:42 PDT 2023
    root:xnu-10002.1.13~1/RELEASE_X86_64 x86_64
Enabled user installed extensions
Project System Tools 0.13
</details>

### Build Logs
[Build logs.zip](https://github.com/xamarin/xamarin-macios/files/13267893/Build.logs.zip)

### Example Project (If Possible)
[Application test (1).zip](https://github.com/xamarin/xamarin-macios/files/13268035/Application.test.1.zip)

**Comment by acespedes451** [comment]
Anybody?

**Comment by rolfbjarne** [comment]
This is a problem with your provisioning profiles / signing configuration.

It seems these are the provisioning profiles used:

* App Project: `Provisioning Profile: "iOS Team Provisioning Profile: *" (ec915f22-0716-433b-ad24-54ee9a27271a)`
* Extension project: `Provisioning Profile: "VS: WildCard Development" (af452265-85af-43c4-b7b4-b87e43b73f17)`

Which is not correct, you need provisioning profiles specific to each project.

I'd recommend manually creating a provisioning profile for the app extension project as well, disable automatic signing, and selecting the provisioning profile in both the main and app extension projects to make sure the right one is picked at build time.

That works for me with your test project, can you try and see if it works for you too?

**Comment by rolfbjarne** [comment]
> So, now I have to create a new App ID identifier (com.test.mobileapp.OneSignalNotificationServiceExtension), then a new certificate, and then a new profile in order to sign in the extension service, right?

You don't need a new certificate, just app id identifier + (provisioning) profile.

**Comment by acespedes451** [comment]
OK. I did it.
Now I have a one certificate, two app identifiers and two provisioning profiles, but  i'm still having this error:

```
CreatingStagingDirectory - PercentComplete: 5%
 ExtractingPackage - PercentComplete: 15%
 InspectingPackage - PercentComplete: 20%
 PreflightingApplication - PercentComplete: 30%
 VerifyingApplication - PercentComplete: 40%
 ApplicationVerificationFailed: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.SdmcK2/extracted/test2.app/PlugIns/Project1.appex : 0xe8008015 (A valid provisioning profile for this executable was not found.)
error MT1006: Could not install the application '/Users/admin/Desktop/Application test/test2/test2/bin/Debug/net7.0-ios/ios-arm64/test2.app' on the device 'iPhone X': AMDeviceSecureInstallApplicationBundle returned: 0xe8008015.
```


It's really frustrating

**Comment by rolfbjarne** [comment]
Did you enable the `group.com.test.mobileapp.onesignal` app group for the app id for the extension?

**Comment by acespedes451** [comment]
Nop, that was the main problem. I forgot adding it.
Thank you so much!!
If it wasn't for your help, I would have been working on this all week.
I appreciate it
