### ISSUE TITLE
[NativeAOT] Publishing a universal project doesn't produce a universal pkg

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#19391]
Repro: `dotnet publish` a macOS project with `RuntimeIdentifiers=osx-arm64;osx-x64`

The resulting package is here:

> ./bin/Release/net8.0-macos/osx-arm64/publish/MySimpleApp.pkg

instead of here:

> ./bin/Release/net8.0-macos/publish/MySimpleApp-3.14.pkg

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/13265377/msbuild.binlog.zip)

Seems like this fixes the problem:

```xml
<PropertyGroup>
    <UseCurrentRuntimeIdentifier>false</UseCurrentRuntimeIdentifier>
</PropertyGroup>
```

**Comment by rolfbjarne** [comment]
This was fixed here: 5633f4e89050a853f5aa7c0b760b6b7933638691

**Comment by tipa** [comment]
Is this fixed in .NET RC2? I still don't get universal packages if I don't set the `UseCurrentRuntimeIdentifier` property.

**Comment by rolfbjarne** [comment]
@tipa the fix is in RC 2. Can you get a binlog?

**Comment by rolfbjarne** [comment]
Ah, I think I see what's happening, we correctly set `UseCurrentRuntimeIdentifier=false` if the project file sets RuntimeIdentifiers, but not if the default RuntimeIdentifiers is used, because it's set a few lines further down the file:

Setting `UseCurrentRuntimeIdentifier=false` on line 99:

https://github.com/xamarin/xamarin-macios/blob/d2937441250b40b0b3848cdbee8d9abd05105851/dotnet/targets/Xamarin.Shared.Sdk.props#L99

Setting `RuntimeIdentifiers=false` on line 133:

https://github.com/xamarin/xamarin-macios/blob/d2937441250b40b0b3848cdbee8d9abd05105851/dotnet/targets/Xamarin.Shared.Sdk.props#L133

**Comment by rolfbjarne** [comment]
Fix is in progress.
