### ISSUE TITLE
Binding request: CTFontDescriptor.MatchFontDescriptors

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#19397]
Would it be possible to bind/fix the `CoreText.CTFontDescriptor.MatchFontDescriptors` method?
https://github.com/xamarin/xamarin-macios/blob/6f45caa84db8e45df6866d564603930f1cac9d64/src/CoreText/CTFontDescriptor.cs#L756-L766

My goal is to download fonts dynamically
- https://developer.apple.com/library/archive/samplecode/DownloadFont/Listings/DownloadFont_ViewController_m.html
- https://medium.com/@chunkyguy/downloading-fonts-on-ios-ad97977308b5

### Steps to Reproduce
`var success = CoreText.CTFontDescriptor.MatchFontDescriptors(new CoreText.CTFontDescriptor[0], null, null);
`

### Expected Behavior
no crash, API works

### Actual Behavior
`NotImplementedException`

### Environment
.NET 8 RC2.1

**Comment by rolfbjarne** [comment]
I've created a PR implementing this API.

It might take a while until we release this though, so I believe you can use something like this in your project:

```cs
using System.Runtime.InteropServices;
using ObjCRuntime;
namespace CoreText {
	public static class CTFontDescriptorHelper {
		[DllImport (Constants.CoreTextLibrary)]
		static unsafe extern byte CTFontDescriptorMatchFontDescriptorsWithProgressHandler (IntPtr descriptors, IntPtr mandatoryAttributes, BlockLiteral* progressBlock);

		public delegate bool CTFontDescriptorProgressHandler (CTFontDescriptorMatchingState state, NSDictionary progress);

		[UnmanagedCallersOnly]
		static byte MatchFontDescriptorsHandler (IntPtr block, CTFontDescriptorMatchingState state, IntPtr progress)
		{
			var del = BlockLiteral.GetTarget<CTFontDescriptorProgressHandler> (block);
			if (del is not null) {
				var progressDictionary = Runtime.GetNSObject<NSDictionary> (progress)!;
				var rv = del (state, progressDictionary);
				return rv ? (byte) 1 : (byte) 0;
			}
			return 0;
		}

		public static bool MatchFontDescriptors (CTFontDescriptor [] descriptors, NSSet? mandatoryAttributes, CTFontDescriptorProgressHandler progressHandler)
		{
			if (descriptors is null)
				ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (descriptors));

			if (progressHandler is null)
				ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (progressHandler));

			unsafe {
				delegate* unmanaged<IntPtr, CTFontDescriptorMatchingState, IntPtr, byte> trampoline = &MatchFontDescriptorsHandler;
				using var block = new BlockLiteral (trampoline, progressHandler, typeof (CTFontDescriptor), nameof (MatchFontDescriptorsHandler));
				using var descriptorsArray = NSArray.FromNSObjects (descriptors);
				var rv = CTFontDescriptorMatchFontDescriptorsWithProgressHandler (descriptorsArray.GetHandle (), mandatoryAttributes.GetHandle (), &block);
				return rv != 0;
			}
		}
	}
}
```

The API in the PR is a bit better because the `progress` parameter in the callback is strongly typed, but it should be possible to make this work too, there will just be a bit more manual code to get stuff out of the `progress` NSDictionary.

**Comment by tipa** [comment]
Wow - thanks so much for the quick response and the code!
Just had to replace `typeof (CTFontDescriptor)` with `typeof(CTFontDescriptorHelper)`.
You're awesome!

**Comment by tipa** [comment]
@rolfbjarne Is it possible that this workaround is not compatible with NativeAOT? Is there any way to use it with NativeAOT?

```
This API is not supported when using NativeAOT. (System.Diagnostics.UnreachableException)
   at ObjCRuntime.BlockLiteral.FindTrampoline(Type, String) + 0x10
   at MyApp.CTFontDescriptorHelper.MatchFontDescriptors(CTFontDescriptor[], NSSet, CTFontDescriptorHelper.CTFontDescriptorProgressHandler) + 0x30
   ...
   at MyApp!<BaseAddress>+0x29e3f4
```

**Comment by rolfbjarne** [comment]
@tipa try adding the `[BindingImpl (BindingImplOptions.Optimizable)]` attribute on the MatchFontDescriptors method to see if that works.

**Comment by tipa** [comment]
That worked! Thanks so much

**Comment by tipa** [comment]
Well, it works most of the times. But occasionally, the crash is still happening

**Comment by rolfbjarne** [comment]
You _occasionally_ get `This API is not supported when using NativeAOT.`? That's not something that should be randomly happening... do you have a stack trace?

**Comment by tipa** [comment]
I can't reproduce it any more now. Maybe it was caused by something else and I attributed the crash reports I received to the wrong app version.
