### ISSUE TITLE
Cannot deploy app to iOS 17.0.3 iPhone.

### ISSUE THREAD

**Issue by robertmaxted** [xamarin/xamarin-macios#19393]
The issue I have is trying to deploy Xamarin.forms application to iOS device. Below are the versions of my environment(s).

Mac OS - 14.1 (23B74).
iOS OS - 17.0.3.
Xcode version - Version 15.0.1 (15A507).

Visual studio for Mac 2022 - 17.6 Preview (17.6 build 1569):
Visual Studio Community 2022 for Mac Preview
Version 17.6 Preview (17.6 build 1569)
Installation UUID: d653a191-5346-4d6f-ab3e-7a091284e90e

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.310/Sdks
SDK Versions:
	7.0.310
	7.0.309
	7.0.308
	7.0.307
	7.0.306
	7.0.304
	7.0.302
	7.0.203
	6.0.416
	6.0.415
	6.0.414
	6.0.413
	6.0.412
	6.0.410
	6.0.408
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.13
	7.0.12
	7.0.11
	7.0.10
	7.0.9
	7.0.7
	7.0.5
	6.0.24
	6.0.23
	6.0.22
	6.0.21
	6.0.20
	6.0.18
	6.0.16

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.0.6 (Visual Studio Community)
Commit: xamarin-android/d17-5/a200af1
Android SDK: /Users/robertmaxted/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		11.0 (API level 30)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-06-07 19:09:51 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-06-07 19:09:51 UTC

Apple Developer Tools
Xcode: 15.0.1 22266
Build: 15A507

Xamarin.Mac
Not Installed

Xamarin.iOS
Version: 16.4.0.18 Visual Studio Community
Hash: 9d266025e
Branch: xcode14.3
Build date: 2023-09-06 19:52:27-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-06-07 19:09:46 UTC

Build Information
Release ID: 1706001569
Git revision: c51ed514fc64c7e298fdb6e199ffec2133ae500c
Build date: 2023-06-07 19:07:58+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 14.1.0
Darwin 23.1.0 Darwin Kernel Version 23.1.0
    Mon Oct  9 21:27:24 PDT 2023
    root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64

Build output:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(874,3): error : arch exited with code 1
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(874,3): error :         
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(874,3): error : actool exited with code 1
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(874,3): error :         
/Users/MyNameHidden/Github/MyAppNameHidden/MyAppNameHidden.iOS/obj/iPhone/Debug/device-builds/iphone15.3-17.0.3/actool/cloned-assets/Assets.xcassets : actool error : The operation couldn’t be completed. Failed to locate any simulator runtime matching options: {
/Users/MyNameHidden/Github/MyAppNameHidden/MyAppNameHidden.iOS/obj/iPhone/Debug/device-builds/iphone15.3-17.0.3/actool/cloned-assets/Assets.xcassets : actool error :     BuildVersionString = 21A326;
/Users/MyNameHidden/Github/MyAppNameHidden/MyAppNameHidden.iOS/obj/iPhone/Debug/device-builds/iphone15.3-17.0.3/actool/cloned-assets/Assets.xcassets : actool error :     Platforms =     (
/Users/MyNameHidden/Github/MyAppNameHidden/MyAppNameHidden.iOS/obj/iPhone/Debug/device-builds/iphone15.3-17.0.3/actool/cloned-assets/Assets.xcassets : actool error :         "com.apple.platform.iphonesimulator"
/Users/MyNameHidden/Github/MyAppNameHidden/MyAppNameHidden.iOS/obj/iPhone/Debug/device-builds/iphone15.3-17.0.3/actool/cloned-assets/Assets.xcassets : actool error :     );
/Users/MyNameHidden/Github/MyAppNameHidden/MyAppNameHidden.iOS/obj/iPhone/Debug/device-builds/iphone15.3-17.0.3/actool/cloned-assets/Assets.xcassets : actool error :     VersionString = "17.0";
/Users/MyNameHidden/Github/MyAppNameHidden/MyAppNameHidden.iOS/obj/iPhone/Debug/device-builds/iphone15.3-17.0.3/actool/cloned-assets/Assets.xcassets : actool error : }

<img width="1354" alt="Screenshot 2023-11-06 at 12 42 09" src="https://github.com/xamarin/xamarin-macios/assets/62593169/e76780ce-df2e-432d-97c0-bc07e3ee48b9">

### Steps to Reproduce

1. Copy above environment.
2. Try to deploy Application.
3. See it fail.

### Expected Behavior
It should deploy successfully.
### Actual Behavior
It fails to deploy

Please help! We are aiming to launch at the end of this month and currently cannot. Many thanks.

Kind regards,
Rob

**Comment by rolfbjarne** [comment]
Can you open "Xcode -> Settings -> Platforms" and make sure the iOS 17 platform is downloaded?

![Screenshot 2023-10-12 at 12 14 58](https://github.com/xamarin/xamarin-macios/assets/249268/233b4b30-dba0-46f3-a952-67a0a81a44e2)

Once you have the iOS 17 platform, also open "Xcode -> Window -> Devices and Simulators" and check whether you have any iOS 17 simulators:

![Screenshot 2023-10-12 at 12 16 29](https://github.com/xamarin/xamarin-macios/assets/249268/dc8995a6-5aac-4bd2-9404-e38a40f9a75a)

**Comment by robertmaxted** [comment]
@rolfbjarne Thank you!! I didn't have iOS 17 platform downloaded!! You hero! Cheers again.

**Comment by Rubayat26** [comment]
@rolfbjarne Thanks for the solution. I also had the same issue. I also noticed that the newest iOS was not installed in my platform.

**Comment by BillFulton** [comment]
Thanks for that!! It worked for me, but only after I re-started MacOS.
