### ISSUE TITLE
Cannot Debug Maui iOS  HotReload  - App Terminated  VS 17.8.0 Preview 7.0

### ISSUE THREAD

**Issue by gabsamples6** [xamarin/xamarin-macios#19405]
### Steps to Reproduce

1. When launching our app in .net 8 (see environment pic below) attached to an iPhone
2. We get app Terminated
3. Looking at the output there are quite a few "Could not load file or assembly Xamarin.HotReload.Contracts.dll' Microsoft.VisualStudio.DesignTools.TapContract.dll "

In .net 7 it works most of the time, its not perfect but works. in net 8 I have never ever managed to get the app running.

### Environment
![image](https://github.com/xamarin/xamarin-macios/assets/109357537/addbb365-3b5f-4a46-8b6b-7f7fab256f7a)

<details>
<summary>Version information</summary>

```
```

</details>

### Build Logs
below is the output when building.
[HotReloadIssue.txt](https://github.com/xamarin/xamarin-macios/files/13295126/HotReloadIssue.txt)

Any suggestions? Is this a known issue? 

thanks

**Comment by rolfbjarne** [comment]
I believe some of these errors in the logs are unrelated and benign (I've seen some of them before myself).

Could you try a couple of things:

* Does the app launch if you connect to a remote Mac?
* Does it work if you create a new app from a template?

**Comment by gabsamples6** [comment]
Hi - 
I agree those errors are benign as I get them even when it loads successfully in .net 7.

- New app from template loads both .net 7 and net 8 (win 11 attached to phisycal iPhone)  
- Our production app - loads successfully remoting to a simulator to a mac or mac mini.
- Template works
- Our production app does not load in net 8 only  (win 11 attached to phisycal iPhone) 

also we are never able to run the app with full exception on - unless has already started.

I wish it gave us more info on why it terminated. - Woud the bin log help?

**Comment by rolfbjarne** [comment]
I'm assuming that if you put a breakpoint or Console.WriteLine statement in the FinishedLaunching method it's not hit?

Unfortunately we'll need to reproduce this in order to figure out what's going on, which means we'll need a test project we can use ourselves that shows the problem.
