### ISSUE TITLE
security issues - Enabling ARC (Automatic Reference Counting) in Xamarin. iOS project not working

### ISSUE THREAD

**Issue by RagibNoor** [xamarin/xamarin-macios#19413]
I've enabled ARC (Automatic Reference Counting) using the following setting in the "Additional mtouch arguments" field on the iOS Build tab: -gcc_flags "-fobjc-arc". However, when I analyze my resulting IPA file using the tool https://mobsf.live/, I'm getting a false result for the ARC flag.

### Expected Behavior
I understand that the ARC memory management option is designed for Objective-C, and Xamarin.iOS primarily involves working with C# rather than Objective-C. Is it possible to enable ARC for a Xamarin? iOS project and have it recognized correctly when analyzing the IPA file with tools like mobsf. live.

Has anyone successfully configured ARC for Xamarin.iOS project, or is there a different approach or tool I should be using to ensure that the ARC flag is correctly identified in the IPA file? Any suggestions or insights would be greatly appreciated.
https://learn.microsoft.com/en-us/xamarin/ios/internals/newrefcount
### Actual Behavior
![scanning_report](https://github.com/xamarin/xamarin-macios/assets/21287489/1188fad1-6716-4582-b19a-0ff6c5c1cf78)

**Comment by rolfbjarne** [comment]
Objective-C's ARC doesn't really apply to Xamarin.iOS projects, because the developer's code isn't compiled into Objective-C.

That said, we might be able to implement something that makes mobsf's detection think we've enabled ARC, so keeping open this issue for that.

**Comment by RagibNoor** [comment]
Hi @rolfbjarne 

Thank you for addressing the issue . Could you please provide information on the fix version or when users can expect this fix to be included in a release?
