### ISSUE TITLE
No Replacement for deprecated TraitCollectionDidChange

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#19410]
I was using [traitcollectiondidchange](https://developer.apple.com/documentation/uikit/uitraitenvironment/1623516-traitcollectiondidchange) to detect changes of the dark/light theme. That method has been deprecated with iOS 17

![Screenshot 2023-11-08 at 1 27 24 PM](https://github.com/xamarin/xamarin-macios/assets/2863198/f8a3bd41-d6d7-47e3-812d-ad61205ff27d)

The suggested alternative by Apple is [registerfortraitchanges](https://developer.apple.com/documentation/uikit/uitraitchangeobservable/4138524-registerfortraitchanges), which can be called on objects that implement `UITraitChangeObservable` (`IUITraitChangeObservable` interface in C#). `UIView` and `UIViewController` seem to implement that interface, but this isn't reflected in the C# bindings - the method RegisterForTraitChanges doesn't exist for `UIView` and `UIViewController`. How can I use this new API in .NET?

![Screenshot 2023-11-08 at 1 25 32 PM](https://github.com/xamarin/xamarin-macios/assets/2863198/02c2e3b0-0b11-42e4-bd74-c7aea19571e6)

### Environment
.NET 8 RC2.2

**Comment by rolfbjarne** [comment]
If you have a `UIView` or `UIViewController` instance, you can get an object that implements `IUITraitChangeObservable` like this:

```cs
using ObjCRuntime;

UIView view = ...;
var observable = Runtime.GetINativeObject<IUITraitChangeObservable> (view.Handle, false);
observable.RegisterForTraitChanges (...);
```

**Comment by tipa** [comment]
Thanks. I tried the following but it crashes with a `SIGSEGV` at `RegisterForTraitChanges`:
```
var observable = Runtime.GetINativeObject<IUITraitChangeObservable>(Handle, false);
observable.RegisterForTraitChanges(new[] { new UITraitUserInterfaceStyle() }, (env, coll) =>
{

});
```

I am not sure if I translated the `UITraitUserInterfaceStyle.self` part into C# code correctly.

**Comment by rolfbjarne** [comment]
Could you create a test project that shows the crash?

**Comment by tipa** [comment]
[crash.zip](https://github.com/xamarin/xamarin-macios/files/13297734/crash.zip)


```
=================================================================
	Native stacktrace:
=================================================================
	0x10c5a61d5 - /Users/timopartl/Library/Developer/CoreSimulator/Devices/C5E39504-07E4-4553-9FD3-20AA0931CCE8/data/Containers/Bundle/Application/5CFBD26F-9ED1-4CAF-8F35-A52D31FD1275/crash.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x10c544b6e - /Users/timopartl/Library/Developer/CoreSimulator/Devices/C5E39504-07E4-4553-9FD3-20AA0931CCE8/data/Containers/Bundle/Application/5CFBD26F-9ED1-4CAF-8F35-A52D31FD1275/crash.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x10c497aff - /Users/timopartl/Library/Developer/CoreSimulator/Devices/C5E39504-07E4-4553-9FD3-20AA0931CCE8/data/Containers/Bundle/Application/5CFBD26F-9ED1-4CAF-8F35-A52D31FD1275/crash.app/libmonosgen-2.0.dylib : mono_sigsegv_signal_handler_debug
	0x121ea55ed - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x0 - Unknown
	0x1191dc256 - /Library/Developer/CoreSimulator/Volumes/iOS_21A342/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation : NSStringFromClass
	0x130b46536 - /Library/Developer/CoreSimulator/Volumes/iOS_21A342/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : _UITraitTokenForTraitLocked
	0x1305ee729 - /Library/Developer/CoreSimulator/Volumes/iOS_21A342/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : __64+[UITraitCollection _traitTokensIncludingPlaceholdersForTraits:]_block_invoke
	0x130b450a3 - /Library/Developer/CoreSimulator/Volumes/iOS_21A342/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : _UIPerformWithTraitLock
	0x1305ee666 - /Library/Developer/CoreSimulator/Volumes/iOS_21A342/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : +[UITraitCollection _traitTokensIncludingPlaceholdersForTraits:]
	0x1301be0e8 - /Library/Developer/CoreSimulator/Volumes/iOS_21A342/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIViewController registerForTraitChanges:withHandler:]
	0x10b96f069 - /Users/timopartl/Library/Developer/CoreSimulator/Devices/C5E39504-07E4-4553-9FD3-20AA0931CCE8/data/Containers/Bundle/Application/5CFBD26F-9ED1-4CAF-8F35-A52D31FD1275/crash.app/libxamarin-dotnet-debug.dylib : xamarin_dyn_objc_msgSend
	0x179ab3c3a - Unknown

```

**Comment by rolfbjarne** [comment]
Our bindings are wrong :/ The first argument to `RegisterForTraitChanges` is a list of types, not objects.

**Comment by rolfbjarne** [comment]
This might work as a workaround (at least it doesn't crash anymore, although the callback isn't called):

```cs
	IUITraitChangeRegistration RegisterForTraitChanges (UIViewController vc)
	{
		var traits = new Type [] {
			typeof (UITraitVerticalSizeClass),
			typeof (UITraitHorizontalSizeClass),
		};
		return RegisterForTraitChanges (vc, traits);
	}

	IUITraitChangeRegistration RegisterForTraitChanges (UIViewController vc, params Type[] traits)
	{
		var classes = new Class [traits.Length];
		for (var i = 0; i < classes.Length; i++)
			classes [i] = new Class (traits [i]);
		using var traitArray = NSArray.FromNSObjects (classes);

		var registrationHandle = NativeHandle_objc_msgSend_NativeHandle_NativeHandle_NativeHandle (vc.Handle, Selector.GetHandle ("registerForTraitChanges:withTarget:action:"), traitArray.Handle, this.Handle, Selector.GetHandle ("traitChangeCallback:collection:"));
		return Runtime.GetINativeObject<IUITraitChangeRegistration> (registrationHandle, false);
	}

	[DllImport ("/usr/lib/libobjc.dylib", EntryPoint="objc_msgSend")]
	extern static NativeHandle NativeHandle_objc_msgSend_NativeHandle_NativeHandle_NativeHandle (IntPtr receiver, IntPtr selector, NativeHandle arg1, NativeHandle arg2, NativeHandle arg3);

	[Export ("traitChangeCallback:collection:")]
	void TraitChangeCallback (NSObject sender, UITraitCollection collection)
	{
		Console.WriteLine ($"TraitChangeCallback");
	}
```

Full AppDelegate.cs file: https://gist.github.com/rolfbjarne/042dc7b97e97c458ae08290a80e301df

Note that more workarounds are likely needed for other API, any new API that takes a `UITrait` in the signature is likely wrong (we bound using `UIKit.IUITraitDefinition`, while we should have bound using `ObjCRuntime.Class`).

**Comment by tipa** [comment]
Thanks a lot! For me, your workaround code works and the callback is called when a trait changes (e.g. dark/light theme switch when using `typeof(UITraitUserIntertfaceStyle)`. Or when the device is rotated in your example with `typeof(UITraitVerticalSizeClass)`

**Comment by tipa** [comment]
@marcoburato-ecutek I did something like this (simply not calling the base implementation):

```
public override void TraitCollectionDidChange(UITraitCollection oldTraits)
{
        if (OperatingSystem.IsIOSVersionAtLeast(17)) return;
        base.TraitCollectionDidChange(oldTraits);
        if (TraitCollection.UserInterfaceStyle != oldTraits.UserInterfaceStyle) { UpdateTheme(); }
}
```

**Comment by marcoburato-ecutek** [comment]
@tipa I don't think that's a good idea. We don't know what the base implementation does, not calling it may or may not cause problems.

For instance, Apple's documentation says:
> At the beginning of your implementation, call super to ensure that interface elements higher in the view hierarchy have an opportunity to adjust their layout first.

I imagine that, if there are nested view controllers (basically always the case with UIKit nav controller, tab controller, etc) the parent could not get notified if it still relies on the deprecated method.

I'd rather be safe and always call the base method.

**Comment by priyank459** [comment]
Hi @rolfbjarne ,
Along with **registerForTraitChanges** I also need to use **viewDidLayoutSubviews**. 
Can you please help me with exporting logic for the same.

 Thanks for the workaround on **registerForTraitChanges** , it helped me to solve part of the issue.

**Comment by rolfbjarne** [comment]
@priyank459 we've already bound `[UIViewController viewDidLayoutSubviews]` as `UIViewController.ViewDidLayoutSubviews`, so I'm not sure what you need? Can you show a code sample of what doesn't work?

**Comment by priyank459** [comment]
Thank you @rolfbjarne and @dalexsoto. I am able to solve my issue.

**Comment by tipa** [comment]
I just updated to the new version and observing a probably unintended behavior. Something like this (written in a Viewcontroller or View) fails to build:

`RegisterForTraitChanges<UITraitUserInterfaceStyle>((env, traits) => { });
`

![Screenshot 2024-01-18 at 11 12 18 AM](https://github.com/xamarin/xamarin-macios/assets/2863198/bb5c1fa4-cd49-4055-bcab-07e7f6217a6d)

I need to specifically cast to `IUITraitChangeObservable` in order to get it to work

`((IUITraitChangeObservable)this).RegisterForTraitChanges<UITraitUserInterfaceStyle>((env, traits) => { });
`

Probably not obvious to new developers. Wouldn't it be best to just remove the old methods, which were non-functional anyways? It would be a breaking change API-wise but I doubt that any developers used those methods as they were crashing

**Comment by rolfbjarne** [comment]
> I just updated to the new version and observing a probably unintended behavior. Something like this (written in a Viewcontroller or View) fails to build:
> 
> `RegisterForTraitChanges<UITraitUserInterfaceStyle>((env, traits) => { }); `
> 
> ![Screenshot 2024-01-18 at 11 12 18 AM](https://private-user-images.githubusercontent.com/2863198/297703345-bb5c1fa4-cd49-4055-bcab-07e7f6217a6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNjAyMTAsIm5iZiI6MTcwNjI1OTkxMCwicGF0aCI6Ii8yODYzMTk4LzI5NzcwMzM0NS1iYjVjMWZhNC1jZDQ5LTQwNTUtYmNhYi0wN2U3ZjYyMTdhNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMDkwNTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODUxNTlhYjc3ZTFmOGRkYjY5NzA5ZWJmMjcxOWI3NWJiYmNlOTM0MzZhZjIwZjZiNTRkZDZlMjQ5MzdmOGUwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LKKgk8Wh_pTUfLGp9EtExkCXDV3TJcEVeUrjKsvqFgY)
> 
> I need to specifically cast to `IUITraitChangeObservable` in order to get it to work
> 
> `((IUITraitChangeObservable)this).RegisterForTraitChanges<UITraitUserInterfaceStyle>((env, traits) => { }); `

Good catch, I think I know how to fix this.

> Probably not obvious to new developers. Wouldn't it be best to just remove the old methods, which were non-functional anyways? It would be a breaking change API-wise but I doubt that any developers used those methods as they were crashing

We try very hard to not make breaking changes, because we've run into trouble before removing APIs that were 100% incorrect and never called (because it would crash the process). It turned out third-party libraries had references to said API in code paths that were never executed - and when we removed that API, we suddently got a lot of bug reports about breaking the build for consumers of the third-party library - it turned out the linker will fail if running into a reference to a method that doesn't exist.

In any case it doesn't look like removing the old API will fix the problem, because this isn't a failure to find a specific method overload - the problem is that methods on an interface are not directly accessible from types that implement that interface. The fix would be to add proxy implementations on all the types that implement the interface.

**Comment by rolfbjarne** [comment]
> In any case it doesn't look like removing the old API will fix the problem, because this isn't a failure to find a specific method overload - the problem is that methods on an interface are not directly accessible from types that implement that interface. The fix would be to add proxy implementations on all the types that implement the interface.

For several reasons this turned out to be cumbersome to implement at this point, but it looks like it'll be much easier once we add support for default interface members in the generator (https://github.com/xamarin/xamarin-macios/issues/13294), so I'm postponing until then.
