### ISSUE TITLE
iOS Project Fails to build on xcode 15.0.1 /usr/bin/xcrun exited with code 1

### ISSUE THREAD

**Issue by lilleydnSub** [xamarin/xamarin-macios#19489]
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
Build an App and Deploy to Phone
### Actual Behavior

Trying to build an iOS project that works on xcode 15.0.0 but fails on 15.0.1

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(874,3): error : /usr/bin/xcrun exited with code 1
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(874,3): error :         
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(874,3): error : actool exited with code 1
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(874,3): error :         
/Users/davidlilley/Projects/ScratchiOS/ScratchiOS/obj/iPhone/Release/actool/cloned-assets/Assets.xcassets : actool error : Failed to launch AssetCatalogSimulatorAgent via CoreSimulator spawn
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:00.71

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 3 errors, 0 warnings
### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Community 2022 for Mac
Version 17.6.7 (build 417)
Installation UUID: d871a199-6cd2-4493-9661-74ebd7c780a2

Runtime
.NET 7.0.3 (64-bit)
Architecture: X64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.403/Sdks
SDK Versions:
	7.0.403
	7.0.310
	7.0.309
	7.0.308
	7.0.307
	7.0.304
	7.0.302
	7.0.203
	7.0.202
	7.0.201
	7.0.200
	7.0.103
	7.0.102
	7.0.101
	7.0.100
	6.0.417
	6.0.416
	6.0.415
	6.0.414
	6.0.413
	6.0.410
	6.0.408
	6.0.407
	6.0.406
	6.0.405
	6.0.404
	6.0.403
	6.0.402
	5.0.408
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.426
	3.1.425
	3.1.424
	3.1.417
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.13
	7.0.12
	7.0.11
	7.0.10
	7.0.7
	7.0.5
	7.0.4
	7.0.3
	7.0.2
	7.0.1
	7.0.0
	6.0.25
	6.0.24
	6.0.23
	6.0.22
	6.0.21
	6.0.18
	6.0.16
	6.0.15
	6.0.14
	6.0.13
	6.0.12
	6.0.11
	6.0.10
	5.0.17
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.32
	3.1.31
	3.1.30
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 15.0.1 22266
Build: 15A507

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-11-10 12:19:21 UTC

Xamarin.Mac
Version: 9.3.0.23 Visual Studio Community
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:14:59-0400

Xamarin.iOS
Version: 16.4.0.23 Visual Studio Community
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:15:00-0400

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: /Users/davidlilley/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-11-10 12:19:27 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-11-10 12:19:27 UTC

Build Information
Release ID: 1706070417
Git revision: 179aa48a5702754e41a8218d0403ddc3be46706f
Build date: 2023-11-10 12:17:47+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 14.1.1
Darwin 23.1.0 Darwin Kernel Version 23.1.0
    Mon Oct  9 21:27:27 PDT 2023
    root:xnu-10002.41.9~6/RELEASE_X86_64 x86_64


```

</details>

### Example Project (If Possible)

[ScratchiOS.zip](https://github.com/xamarin/xamarin-macios/files/13416878/ScratchiOS.zip)

**Comment by rolfbjarne** [comment]
> Failed to launch AssetCatalogSimulatorAgent via CoreSimulator spawn

This looks like something's happening with Xcode.

Can you try:

a) Create a new project in Xcode and build it.
b) Reboot the machine

and see if any of these fixes the problem?

**Comment by EveNaari** [comment]
Exact same issue here, after updating xcode to version 15

@rolfbjarne in xcode there's no issues with build, restart also doesn't help

**Comment by rolfbjarne** [comment]
@EveNaari does it work if you create a new .NET project from a template?

**Comment by lilleydnSub** [comment]
Apparently the simulators were missing and needed to be downloaded, strange as i was deploying to my phone.

It now compiles and deploys to the phone. Thankyou.

**Comment by tpitman** [comment]
What do you mean by "the simulators were missing and needed to be downloaded". How do I trigger this? I don't see anywhere talking about this.

**Comment by tpitman** [comment]
Thank you for the quick response. That is so crazy. Never had to do that before. How is a regular dev supposed to know about this kind of thing?

I am sure glad that people like you find solutions and post the answers so we can find them.

**Comment by rolfbjarne** [comment]
> Never had to do that before.

It's new in Xcode 15 (released this fall).

> How is a regular dev supposed to know about this kind of thing?

Read Xcode release notes I guess? Apple changes stuff every year :/

**Comment by ericgyamfi11** [comment]
I encountered the same problem recently when I updated my XCode. If you have an old simulator installed, you have to first remove it before installing the new one. This 
[Link](https://github.com/xamarin/xamarin-macios/issues/19141#issuecomment-1759339013) helped me a lot
