### ISSUE TITLE
DllNotFoundException __Internal when calling c++ function exposed through extern c

### ISSUE THREAD

**Issue by trampster** [xamarin/xamarin-macios#19497]
### Steps to Reproduce

1. Create a native lib which has a c++ function exposed using extern c
2. Create a BindingProject which includes it as a NativeReference
3. Try and pinvoke to the exposed method

(see attached minimal reproduction example which reproduces this.

Note:
-  A straight c function defined in a .c file works, but a c++ function exposed via extern c doesn't work.
- Prior to migrating to .net maui the same native .a file worked using the following args:
```
<MtouchExtraArgs>
-v -v -v -v -nolinkaway -dlsym:System.Memory.dll -dlsym:system.buffers.dll -dlsym:mscorlib.dll -dlsym:SkiaSharp.dll -dlsym:SQLitePCLRaw.nativelibrary.dll -dlsym:false -nolinkaway -cxx -gcc_flags " -L${ProjectDir}/../../../iOS-PTToX/main/build/OS64/Debug -lpttox-client -force_load ${ProjectDir}/../../../iOS-PTToX/main/build/OS64/Debug/libpttox-client.a -framework SystemConfiguration"
</MtouchExtraArgs>
```

The new NativeReference in the binding project csproj (which doesn't work) is as follows:
```
<NativeReference Include="libpttox-client.a">
      <Kind>Static</Kind>
      <SmartLink>False</SmartLink>
      <ForceLoad>True</ForceLoad>
      <Frameworks>SystemConfiguration</Frameworks>
      <IsCxx>True</IsCxx>
</NativeReference>
```

### Expected Behavior
Can pinvoke to the native function

### Actual Behavior
DllNotFoundException __Internal

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Professional 2022 for Mac
Version 17.6.7 (build 417)
Installation UUID: a4ed1628-2d47-4e9a-9fcb-58e3bd069516

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.400/Sdks
SDK Versions:
	7.0.400
	7.0.307
	6.0.417
	6.0.413
	6.0.408
	6.0.100
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.10
	6.0.25
	6.0.21
	6.0.16
	6.0.0

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Professional)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: /Users/hughesd/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-11-10 12:19:52 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-11-10 12:19:52 UTC

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-11-10 12:19:46 UTC

Apple Developer Tools
Xcode: 14.3.1 21815
Build: 14E300c

Xamarin.Mac
Not Installed

Xamarin.iOS
Version: 16.4.0.23 Visual Studio Professional
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:15:00-0400

Build Information
Release ID: 1706070417
Git revision: 179aa48a5702754e41a8218d0403ddc3be46706f
Build date: 2023-11-10 12:18:09+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.5.0
Darwin 22.6.0 Darwin Kernel Version 22.6.0
    Wed Jul  5 22:21:53 PDT 2023
    root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64

Enabled user installed extensions
Project System Tools 0.13
```

</details>

### Build Logs
[buildlog.txt](https://github.com/xamarin/xamarin-macios/files/13421087/buildlog.txt)

### Example Project (If Possible)

[ExternCPinvokeIssue.zip](https://github.com/xamarin/xamarin-macios/files/13421089/ExternCPinvokeIssue.zip)

**Comment by trampster** [comment]
Runing nm on the native .a assembly gives:
```
---------------- T _eua_stop
```

Running nm on the after after Xamarin.iOS does it's linking gives
```
0000000100004000 t _eua_stop
```

We think that lowercase t after linking is the issue. Lowercase t means that it's not assessable externally.

If we add a .c function which does work then after linking it has a capitial T.

**Comment by rolfbjarne** [comment]
You're correct, when the native code is compiled as C++ (and exposed using extern "C") the default visibility is private, while it's public when compiled as C. As you've found out, this is the capital "T" vs lowercase "t" difference shown with the `nm` tool.

There are two options:

* Make the symbols public in the native library. This can be done on a per-symbol basis by adding the `visibility` attribute:

```c
extern "C" {
	int DoSomething () __attribute__((visibility("default")));
}
int DoSomething () {
	return 42;
}
```

```
 $ clang++ test.cpp -otest -fvisibility=hidden && nm test | grep DoSomething
0000000100003f90 T _DoSomething
```

* Emit a direct reference to the P/Invoke from the AOT-compiled code.
    * This requires disabling the interpreter when running on device:
        ```xml
        <PropertyGroup>
             <UseInterpreter>false</UseInterpreter>
        </PropertyGroup>
        ```
    * It requires passing -dlsym:false as an additional mtouch argument (which you were already doing in the legacy Xamarin project)
    * Your project also requires dlsym for a few assemblies, so the full additional mtouch arguments are:
        ```xml
        <PropertyGroup>
             <MtouchExtraArgs>-v -v -v -v -dlsym:SkiaSharp.dll -dlsym:SQLitePCLRaw.nativelibrary.dll -dlsym:SQLitePCLRaw.provider.sqlite3.dll --dlsym:false</MtouchExtraArgs>
        </PropertyGroup>
        ```
    * It doesn't work in the simulator.

**Comment by rolfbjarne** [comment]
Closing, since as far as I can tell this isn't a bug on our side.

**Comment by trampster** [comment]
I tried your second approach but now the test app fails to launch. Note this is before even trying to call the native method.

error: * Assertion at /Users/runner/work/1/s/src/mono/mono/metadata/appdomain.c:193, condition `is_ok (error)' not met, function:create_domain_objects, Attempting to JIT compile method 'void System.OutOfMemoryException:.ctor (string)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
 assembly:<unknown assembly> type:<unknown type> member:(null)

**Comment by rolfbjarne** [comment]
@trampster that's weird, it worked for me. Can you:

1. Clean your project and try again.
2. If that doesn't work, attach your updated csproj here.

**Comment by trampster** [comment]
I managed to get it working after updating my xcode and disabling hot reload.
