### ISSUE TITLE
[iOS][.NET8] Task not found for Xamarin.MacDev.Tasks.GetFullPaths

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#19492]
_From @RomanDrechsel on Mon, 20 Nov 2023 12:06:15 GMT_

### Description

Hi,

i just updated my app from .net7 to .net8

Android works just fine, but i can't build my iOS app.
I always get the following error:

>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : MessagingException: An error occurred on client Build1708478 while executing a reply for topic xvs/build/17.0.8478/execute-task/AIMessenger/72af58c002fGetFullPaths
>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : ArgumentException: Task not found for 'Xamarin.MacDev.Tasks.GetFullPaths'
>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : Parameter name: taskName
>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : 

I didn't find any solution yet.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

### Relevant log output

```shell
12:52:05:574	1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : MessagingException: An error occurred on client Build1708478 while executing a reply for topic xvs/build/17.0.8478/execute-task/AIMessenger/72af58c002fGetFullPaths
12:52:05:574	1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : ArgumentException: Task not found for 'Xamarin.MacDev.Tasks.GetFullPaths'
12:52:05:574	1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error : Parameter name: taskName
12:52:05:574	1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.0.8478\targets\Xamarin.Shared.Sdk.targets(761,3): error :
```

_Copied from original issue dotnet/maui#18900_

**Comment by rolfbjarne** [comment]
_From @jsuarezruiz on Mon, 20 Nov 2023 15:09:59 GMT_

@rolfbjarne Thoughts?

**Comment by rolfbjarne** [comment]
_From @RomanDrechsel on Mon, 20 Nov 2023 15:17:41 GMT_

Hi,

fyi:
it seems that i find a workaround.

I remembered having a similar problem with GoogleAppMeasurement.xcframework a few month ago.
So i checked the Xamarin.Shared.Sdk.targets file and removed the line
> SessionId="$(BuildSessionId)

in the block

> <GetFullPaths

Now it seems to work.
I have no idea why this is happening.

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Mon, 20 Nov 2023 16:15:47 GMT_

We'd need a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) to figure out what's going on here.

@RomanDrechsel would you be able to get a binlog for us?

In any case, this is an issue for the xamarin-macios repository, so I'm moving it there.

**Comment by RomanDrechsel** [comment]
Hi,

i created 2 binlogs.
First, i created a binlog with msbuild, but this seems to work.
Then i created a binlog with the Project System Tools Extension. The error occurs when I deploy the app on my iPhone.

[binlog.zip](https://github.com/xamarin/xamarin-macios/files/13424444/binlog.zip)

**Comment by rolfbjarne** [comment]
Can you zip up and attach all the log files in the `~/Library/Logs/Xamarin.Messaging-*` as well?

Executing this from a terminal should do it (and create Xamarin.Messaging.zip):

> zip -9r Xamarin.Messaging.zip ~/Library/Logs/Xamarin.Messaging-*

**Comment by rolfbjarne** [comment]
That shows the error with a better stack trace, but doesn't explain why the problem occurs :/

Can you paste the output of this command after executing it on the Mac?

> md5 ~/Library/Caches/Xamarin/XMA/Agents/Build/17.0.8478/*.dll

**Comment by RomanDrechsel** [comment]
ok that's strange.
I didn't actually change anything, it all came with Visual Studio Community.
Where can I get a "working" SDK?

**Comment by rolfbjarne** [comment]
> Where can I get a "working" SDK?

It should have just worked, so I'll need to figure out what went wrong first.

**Comment by RomanDrechsel** [comment]
PS C:\Users\roman.drechsel> Get-FileHash "C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\*\tools\msbuild\iOS\*.zip" -Algorithm md5

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             AC3E836F6F73001E6169132C9EA99FBA                                       C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.4.7125\tools\msbuild\iOS\Broker.zip
MD5             6EB14D0FAB1142C32774E0003B0D43EF                                       C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.4.7125\tools\msbuild\iOS\Build.zip
MD5             00F053119938CC8F429AB44B990B53CB                                       C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\16.4.7125\tools\msbuild\iOS\Xamarin.PreBuilt.iOS.app.zip
MD5             31E67A5679724D957C0F5C0E1D8C071D                                       C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.0.8478\tools\msbuild\iOS\Broker.zip
MD5             C8A7043414909CFEF92A7A4AEFFB5780                                       C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.0.8478\tools\msbuild\iOS\Build.zip
MD5             40A1BADA444A1A7D2CBC97049F328D94                                       C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.0.8478\tools\msbuild\iOS\Xamarin.PreBuilt.iOS.app.zip

**Comment by rolfbjarne** [comment]
OK, that looks correct.

Could you please try this then:

1. Close VS on Windows.
2. Delete the `~/Library/Caches/Xamarin` directory on the Mac:

```
rm -rf ~/Library/Caches/Xamarin
```

3. Open VS again and pair to the Mac.
4. Try to build again.

**Comment by RomanDrechsel** [comment]
Well i did remove ~/Library/Caches/Xamarin
Now i can't build anymore :)

`MSBuild was unable to connect to the Mac with Address='XXX.XXX.XXX.XXX' and User='XXX'. This connection is separate from Visual Studio and without it the project can't build. Please try building again or report this problem if the issue persists	
C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.0.8478\tools\msbuild\iOS\Xamarin.Messaging.Build.targets
`

ssh connection is working, Visual Studio can connect too, but somehow msbuild can't.
I'll get a completely new windows installation tomorrow and let you know if it works then.
What do i have to remove on the mac in order to get a completely clean environment?

**Comment by rolfbjarne** [comment]
> What do i have to remove on the mac in order to get a completely clean environment?

It's documented here:

* https://learn.microsoft.com/en-us/xamarin/get-started/installation/uninstalling-xamarin
* https://learn.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2022

**Comment by Manish-Pradhan-FP** [comment]
I have the same exact issue. I followed up to https://github.com/xamarin/xamarin-macios/issues/19492#issuecomment-1840653946 and then deleted the ~/Library/Caches/Xamarin directory on the Mac and now VS can not connect to the Mac. I get the exact same error as OP posted after. "MSBuild was unable to connect...". Any ideas?

**Comment by rolfbjarne** [comment]
@Manish-Pradhan-FP did you try cleaning your mac as in these links: https://github.com/xamarin/xamarin-macios/issues/19492#issuecomment-1841000336?

**Comment by Manish-Pradhan-FP** [comment]
@rolfbjarne Yes I did. If I change the TargetPlatform back to .net7-ios then everything works but .net8-ios does not. It seems all the bug fixes and enhancements are being prioritized on .net8 so this really makes things difficult for development using this platform.

**Comment by rolfbjarne** [comment]
@Manish-Pradhan-FP 

Can you paste the output of this command after executing it on the Mac?

> md5 ~/Library/Caches/Xamarin/XMA/Agents/Build/17.0.8478/*.dll

**Comment by Manish-Pradhan-FP** [comment]
If I using a win machine to do the iOS build while connecting to a MAC then I dont really need .Net8-iOS on the MAC, correct?

**Comment by rolfbjarne** [comment]
@Manish-Pradhan-FP you don't need to install anything on the Mac, the remote build will install what's needed (in particular .NET + the required workloads will be installed in a private location).

**Comment by rolfbjarne** [comment]
OK, I'll close this again then.

**Comment by ronaldderooij1997** [comment]
> `MSBuild was unable to connect to the Mac with Address='XXX.XXX.XXX.XXX' and User='XXX'. This connection is separate from Visual Studio and without it the project can't build. Please try building again or report this problem if the issue persists C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\17.0.8478\tools\msbuild\iOS\Xamarin.Messaging.Build.targets `
> 
I had the same issue and tried everything, uninstalling vs studio & updating to new version, reinstalling workloads, clearing the mac xamaring cache folders and much more. 

What eventually fixed it for me was clearing the folder:
 C:\Users\xxxx \AppData\Local\Temp directory folder

**Comment by ronaldderooij1997** [comment]
To solve it I tried various things, I believe what solved it was clearing:

C:\Users\xxxx \AppData\Local\Temp directory folder

I never had the problem again since I solved it, so I cannot reproduce it.

**Comment by JORGEGO** [comment]
I didn't want to do this option because I thought the problem wasn't there... but in the end thanks to your answer, I do it and don't tell me why (I imagine there would be temporary files) but now it has allowed me to generate a version... Now it is in the App Strore Connect that fails and does not allow uploading versions, but that is another problem...
