### ISSUE TITLE
[NativeAOT] Fix AOT analysis warning IL3050

### ISSUE THREAD

**Issue by simonrozsival** [xamarin/xamarin-macios#19505]
This issue is a follow-up to #19043

When building apps with NativeAOT, the ILC prints an AOT analysis warning IL3050: _<Module>..cctor(): Using member 'System.Enum.GetValues(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling._

The problem is caused by the `[DynamicDependency]` attributes we generate in the `ApplyPreserveAttributeBase` custom linker step when we're transforming `[Preserve(AllMembers = true)]`. There are two cases in which we get this warning:
- the `[Preserve(AllMembers = true)]` is applied to an enum
- the class with the attribute contains a nested enum

We transform the attribute by generating a `[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(T))]` attribute on the module cctor. This will pull all members of `T`, but also all members of its base types. In the case of enums, this unfortunately includes the `GetValues(Type)` static method which is annotated with `RequiresDynamicCode`.

I see some potential solutions, each of them has a different trade-off:
- Do not preserve nested types
    - We change the `DynamicDependency` attribute from `All` to `All ^ PublicNestedTypes ^ NonPublicNestedTypes` for classes and to `PublicFields` for enums. This doesn't seem to be a problem in the xamarin-macios codebase (all tests are passing locally with this change), but it will be a breaking change.
- Deprecate `[Preserve]`
    - We remove all nested enums that cause this problem (`NSObject_Disposer -> NSObject -> Flags, XamarinGCHandleFlags`) and make `[Preserve]` attribute obsolete. We would still keep the custom linker steps that transform Preserve into DynamicDependency, but customers won't get this warning unless they have nested enums in their classes. On our end, we would need to remove all uses of `[Preserve]` especially in tests (~1200 uses) and in MAUI. The Preserve attributes are baked into bgen-generated binding libraries which could be a problem.
- Suppress the warning
    - I think it can be argued that nobody expects `Enum.GetValues(Type)` method to be preserved when the `[Preserve]` attribute is applied to an enum. We might want to simply suppress `IL3050` on the module initializer that we generate. I'm not a fan of this solution since we can't suppress just the warning for `GetValues` and we could miss some other warning with the same ID.

What other solutions should we consider?

/cc @rolfbjarne @ivanpovazan @vitek-karas

### Steps to Reproduce

1. Build the MySingleView test app with NativeAOT:
```
dotnet publish -f net8.0-ios -r ios-arm64 \
    -p:PublishAot=true -p:PublishAotUsingRuntimepack=true \
    -p:EnableTrimAnalyzer=true -p:TrimmerSingleWarn=false \
    tests/dotnet/MySingleView/
```
2. Inspect warnings

### Expected Behavior
There are no build warnings.

### Actual Behavior
ILC prints this warning:
```
ILC : AOT analysis warning IL3050: <Module>..cctor(): Using member 'System.Enum.GetValues(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. It might not be possible to create an array of the enum type at runtime. Use the GetValues<TEnum> overload or the GetValuesAsUnderlyingType method instead. [/.../xamarin-macios/tests/dotnet/MySingleView/MySingleView.csproj]
```

**Comment by vitek-karas** [comment]
I want to note that `All` annotation doesn't really act like a union of all the other annotations. It does "more". The `All` annotation will preserve all members on the type and all of its base types and interfaces. For methods, for example, this is not equivalent to `PublicMethod | NonPublicMethods` as those will not preserve private methods on base types (or interfaces). 
I don't know about the `Preserve` attribute and how it operated in the past, so I can't comment on which behavior is needed here.

Also - ignoring the warning doesn't meant the `GetValues` method is not there, in fact it's the opposite, it will be kept, but calling it might produce unexpected results (either throw, or return different results).

I would obviously prefer the approach which removes the need for this (option 2), but I understand it's a lot of work. If the chance of somebody calling GetValues, through reflection, on an enum is low enough, I think going with the suppression would be OK for now. And we should have a plan how to remove this need over time (so start incremental improvements toward option 2).

**Comment by simonrozsival** [comment]
@vitek-karas thanks for the clarification, I didn't know that `All` has this special behavior.

I can't find a proper specification of `[Preserve]`, the best I can find is https://learn.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=macos#preserving-code and almost identical Android version https://learn.microsoft.com/en-us/xamarin/android/deploy-test/linker#preserving-code. I assumed that `AllMembers` should include nested types, but in my testing it doesn't. I think the first option will be best after all. It should align the behavior of Mono and NativeAOT apps.

**Comment by simonrozsival** [comment]
> If it does preserve them, then there's no annotation which would do that and avoid marking nested types currently.

It seems that the only base class members that we preserve are fields (both private and public). Everything else is gone including public methods and properties.

If we needed to preserve private members on base types though we could generate the `[DynamicDependency]` attributes for all base classes to avoid the limitation you mention.

**Comment by rolfbjarne** [comment]
> * The Preserve attributes are baked into bgen-generated binding libraries which could be a problem.

I've filed https://github.com/xamarin/xamarin-macios/issues/19524 to see if we can get bgen to stop generating the Preserve attribute at least.
