### ISSUE TITLE
[Windows build perf] ExpandNativeReferences should consume .NET assemblies from the Mac installation

### ISSUE THREAD

**Issue by emaf** [xamarin/xamarin-macios#19513]
This is the same as https://github.com/xamarin/xamarin-macios/issues/19511. As `ExpandNativeReferences` runs after `UnpackLibraryResources`, it does not copy the .NET assemblies to the Mac, but it still runs checks on those ~150 files unnecesarily to assess if they need to be copied, and that adds ~500ms to each build.

![image](https://github.com/xamarin/xamarin-macios/assets/3286258/3a6876cd-07e3-4df0-9d43-d75ca3c78b71)

### Build Logs
[Binlogs.zip](https://github.com/xamarin/xamarin-macios/files/13444866/Binlogs.zip)

**Comment by rolfbjarne** [comment]
This task must execute on a Mac (because native references can contain symlinks), but I believe it should be possible to filter out any assemblies that don't have any native references on Windows, so that we only copy assemblies with native references.

**Comment by emaf** [comment]
Yeah, that's a good one, but we still should avoid analyzing/copying "SDK files", since those should already exist on the Mac's SDK installation
![image](https://github.com/xamarin/xamarin-macios/assets/3286258/f504c2bd-5e09-4c7b-8d69-a99fdb3126e3)

**Comment by rolfbjarne** [comment]
Yes, my point is that no SDK assembly will have native references, so by filtering to assemblies with native references (on Windows) we'll indirectly also exclude all SDK assemblies.
