### ISSUE TITLE
[AppKit] Add new NSBezelStyle names and deprecate old ones

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#19555]
The NSBezelStyle values have been updated with the macOS Sonoma SDK: https://developer.apple.com/videos/play/wwdc2023/10054/?time=179

Would it be possible to update the corresponding C# enum as well?
I understand that simply changing the names would be a breaking change, but as C# values support multiple names per value one could deprecate the old names ([Apple did the same](https://developer.apple.com/documentation/appkit/nsbutton/bezelstyle/deprecated_symbols)) and add the new names to the enum

**Comment by tipa** [comment]
@rolfbjarne I just noticed that I was using some bezel styles that are annotated as deprecated, but it didn't show a warning:

<img width="900" height="141" alt="Image" src="https://github.com/user-attachments/assets/fc2cf818-3d30-431b-8895-a8c8d265e244" />

Should I open a new issue for this?

**Comment by rolfbjarne** [comment]
> [@rolfbjarne](https://github.com/rolfbjarne) I just noticed that I was using some bezel styles that are annotated as deprecated, but it didn't show a warning:
> 
> <img alt="Image" width="900" height="141" src="https://private-user-images.githubusercontent.com/2863198/495399587-fc2cf818-3d30-431b-8895-a8c8d265e244.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkyMzM4NjksIm5iZiI6MTc1OTIzMzU2OSwicGF0aCI6Ii8yODYzMTk4LzQ5NTM5OTU4Ny1mYzJjZjgxOC0zZDMwLTQzMWItODg5NS1hOGM4ZDI2NWUyNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MzBUMTE1OTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkxMTcxYTU3YjE3MmQ0NTliNDVhZGQ2NjMxOGM2MTdjZjEwZTQxZTI1ZDU4NTdkMjViMzI4ZDA4NGFhMzg5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Cw1DxfHRQogEVBAmFkw4mmWLmncZfqnl3vIhGvdRD00">
> Should I open a new issue for this?

Yes, please!
