### ISSUE TITLE
Xamarin iOS SDK is not compatible with xcode

### ISSUE THREAD

**Issue by sajidsheik** [xamarin/xamarin-macios#19574]
### Steps to Reproduce

1. Trying to build release build for iOS in Mac Os 12.7 with xcode 4.1
2. It is working for dev build
3. But for release build it is not building 

### Expected Behavior
Generate a new build
### Actual Behavior
MTOUCH : error MT0180: This version of Xamarin.iOS requires the iOS 16.4 SDK (shipped with Xcode 14.3). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs).

Tried but updating the iOS build to linksdks only mtouch option but it is still failing

I can't update the mac os 

What options I have to make it work

### Environment
Release

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by rolfbjarne** [comment]
> or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior

Did you enabling the linker for your Release build? You can also do that in your project file by setting:

```xml
<PropertyGroup>
    <MtouchLink>SdkOnly</MtouchLink>
</PropertyGroup>
```

**Comment by sajidsheik** [comment]
<PropertyGroup>
    <MtouchLink>SdkOnly</MtouchLink>
</PropertyGroup>

Yes I tried this configuration but it still gives the same error

**Comment by rolfbjarne** [comment]
Is this a .NET project or a Xamarin.iOS project?

**Comment by sajidsheik** [comment]
It is a Xamarin iOS prorect

**Comment by rolfbjarne** [comment]
You can try downloading an earlier version of Xamarin.iOS by getting the version that introduced support for Xcode 14.1: https://github.com/xamarin/xamarin-macios/releases/tag/xamarin-ios-16.1.1.28

There are more versions available for download here if needed: https://github.com/xamarin/xamarin-macios/blob/main/DOWNLOADS.md
