### ISSUE TITLE
DllImport resolution via .config file fails in newer net7/8-ios targets

### ISSUE THREAD

**Issue by kiddkaffeine** [xamarin/xamarin-macios#19599]
library resolution via an external config file to an internal library fails in net8-ios or net7-ios but works in older Xamarin targets.

### Steps to Reproduce
1. Build a project using FNA-XNA for iOS (https://github.com/FNA-XNA/FNA)
2. Run the project

### Expected Behavior
Applications loads

### Actual Behavior
System.DllNotFoundException when native libraries are invoked.  (See details below.)

### Environment
Broken in net7.0-ios and net8.0-ios; works in older Xamarin targets.

### Details
This library uses tons of the following types of entries, for several different libraries:

		[DllImport("SDL2", EntryPoint = "SDL_SetHint", CallingConvention = CallingConvention.Cdecl)]
		private static extern unsafe SDL_bool INTERNAL_SDL_SetHint(
			byte* name,
			byte* value
		);

And relies on FNA.dll.config to map libraries:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<dllmap dll="SDL2"          os="osx" target="__Internal"/>
	<dllmap dll="FNA3D"         os="osx" target="__Internal"/>
	<dllmap dll="FAudio"        os="osx" target="__Internal"/>
	<dllmap dll="libtheorafile" os="osx" target="__Internal"/>
</configuration>

See https://github.com/flibitijibibo/SDL2-CS/blob/e4afbb848586fca530b6538320f799f81a18b941/src/SDL2.cs#L45
and https://github.com/flibitijibibo/SDL2-CS/blob/e4afbb848586fca530b6538320f799f81a18b941/src/SDL2.cs#L832
and https://github.com/FNA-XNA/FNA/wiki/Appendix-A:-FNA-on-iOS-and-tvOS

On legacy Xamarin targets, this works fine.  On newer targets, it will produce System.DllNotFoundException.

However, if the DllImport's are changed to "__Internal", then it will run on newer net7/8-ios targets, i.e.:
		[DllImport("SDL2", EntryPoint = "SDL_SetHint", CallingConvention = CallingConvention.Cdecl)]

### Build Logs
N/A

**Comment by kiddkaffeine** [comment]
As this would not paste correctly:
[FNA.dll.config.zip](https://github.com/xamarin/xamarin-macios/files/13612303/FNA.dll.config.zip)

**Comment by rolfbjarne** [comment]
Remapping P/Invoke to a different native library using a config file (dllmap) is not supported in .NET.

There are two potential solutions:

* Use the correct name for the native library in the P/Invoke.
* Use a custom DllImport resolver at runtime: https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver?view=netcore-3.0

I've updated our doc about breaking changes to include this: https://github.com/xamarin/xamarin-macios/wiki/Breaking-changes-in-.NET#remapping-pinvoke-to-a-different-native-library-using-a-config-file-dllmap-is-no-longer-supported
