### ISSUE TITLE
Unable to use Maui.Essentials APIs in class library for NET 8 iOS app

### ISSUE THREAD

**Issue by AlexNik4** [xamarin/xamarin-macios#19613]
### Steps to Reproduce

1. Create net .NET 8 iOS app
2. Create a .NET 8 class library
3. Add package reference \<PackageReference Include="Microsoft.Maui.Essentials" Version="8.0.3" /\> in the class library
4. Access some Maui.Essentials API in the class library
5. Reference the class library and the code that uses the Maui.Essentials API in the iOS project
6. Run the iOS application

**Notes:** 
- This works fine when downgrading the target framework to .NET 7. In .NET 7 you can use either the package reference or the old \<UseMauiEssentials\> csproj property.
- This also works fine when referencing in .NET 8 Android app.
- Adding the \<PackageReference Include="Microsoft.Maui.Essentials" Version="8.0.3" /\> in the iOS project does not fix anything.

### Expected Behavior
Should be able to reference and use the Maui.Essentials APIs in .NET 8

### Actual Behavior
Exception has occurred: Microsoft.Maui.ApplicationModel.NotImplementedInReferenceAssemblyException
This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
at at Microsoft.Maui.ApplicationModel.MainThread.get_PlatformIsMainThread() at at Microsoft.Maui.ApplicationModel.MainThread.get_IsMainThread() at ClassLibrary.SharedClass.IsMain() in /Users/xxx/Projects/Net8iOSMauiEssentials/ClassLibrary/Class1.cs:7 at Net8iOSMauiEssentials.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions) in /Users/xxx/Projects/Net8iOSMauiEssentials/Net8iOSMauiEssentials/AppDelegate.cs:34

### Environment
Apple M2 Mac
VS Code
Version: 1.85.0 (Universal)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T18:18:04.614Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

Extensions:
.NET MAUI v0.5.50
C# Dev Kit v1.1.16
C# v2.13.10

dotnet --version
8.0.100

### Build Logs
 *  Executing task: dotnet build -t:Build -p:Configuration=Debug -r iossimulator-arm64 -p:CustomAfterMicrosoftCSharpTargets="/Users/xxx/.vscode/extensions/ms-dotnettools.dotnet-maui-0.5.50-darwin-arm64/dist/resources/Custom.After.Microsoft.CSharp.targets" -p:MauiVSCodeBuildOutputFile=/var/folders/_d/4ny48chd42b1qps_dzj8g0qh0000gn/T/dotnet-maui/maui-vsc-9e09f440-4008-444c-8905-034bea03a540.json /Users/xxx/Projects/Net8iOSMauiEssentials/Net8iOSMauiEssentials/Net8iOSMauiEssentials.csproj

MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  Restored /Users/xxx/Projects/Net8iOSMauiEssentials/ClassLibrary/ClassLibrary.csproj (in 153 ms).
  Restored /Users/xxx/Projects/Net8iOSMauiEssentials/Net8iOSMauiEssentials/Net8iOSMauiEssentials.csproj (in 153 ms).
  Detected signing identity:
         
    Bundle Id: com.companyname.Net8iOSMauiEssentials
    App Id: com.companyname.Net8iOSMauiEssentials
  ClassLibrary -> /Users/xxx/Projects/Net8iOSMauiEssentials/ClassLibrary/bin/Debug/net8.0/ClassLibrary.dll
  Net8iOSMauiEssentials -> /Users/xxx/Projects/Net8iOSMauiEssentials/Net8iOSMauiEssentials/bin/Debug/net8.0-ios/iossimulator-arm64/Net8iOSMauiEssentials.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Optimizing assemblies for size. This process might take a while.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:34.69

### Example Project (If Possible)
https://github.com/AlexNik4/Net8iOSMauiEssentials

**Comment by snechaev** [comment]
From the error message, it appears that you also need to reference the same nuget package in the main project (`Net8iOSMauiEssentials.csproj`).

> You should reference the NuGet package from your main application project to reference the platform-specific implementation.

At the same time I'm not sure if this behavior is intended or if it's a regression (since you claim it works on net7).

**Comment by rolfbjarne** [comment]
This is weird, and I can't reproduce with the test project, so there's probably something else going on.

Can you try to build & launch project from the command line to see if this is something related to VSCode?

```shell
dotnet clean # make sure we start from a clean slate
dotnet build /bl:build.binlog
dotnet build /bl:run.binlog -t:Run
```

If that doesn't work, please zip up and attach the *.binlog files the build produced.

**Comment by AlexNik4** [comment]
Thanks for hinting that this was just my system. I had installations of VS Mac and used that Mac to remotely build iOS app for a Windows box. I wasn't able to fix the exception no matter what I tried, so I decided to factory reset the Mac. After reinstalling everything I am able to execute that code now. Thank you and sorry for taking your time.
