### ISSUE TITLE
Binding request: NSImage.SymbolConfiguration.applying()

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#19620]
I have already reported this 2 years ago in the past (https://github.com/xamarin/xamarin-macios/issues/13340) and just realize now, that [NSImageSymbolConfiguration.applying](https://developer.apple.com/documentation/appkit/nsimage/symbolconfiguration/3852560-applying) doesn't seem to be bound yet - unless I am missing something again / the C# API uses a different method name.

I would like to use this API to create an NSImage with both a custom size & tint color. There is no `NSImageSymbolConfiguration` constructor (or `NSImageSymbolConfiguration.Create` method) that takes both a scale and a color parameter.

### Environment
.NET8

**Comment by rolfbjarne** [comment]
It's `NSImageSymbolConfiguration.Create`: https://github.com/xamarin/xamarin-macios/blob/5cac237b84cb130109d94f22291838dae95ab2b6/src/appkit.cs#L28037-L28038
