### ISSUE TITLE
test.fail() then failed expect() does not close browsers for parameterized tests until all are done.

### ISSUE THREAD

**Issue by super-brian** [xamarin/xamarin-macios#19625]
### Steps to Reproduce
I don't know if this is how it is supposed to be, but I think it could be better:
Note that test.fail() is used since there is currently a bug on the website: here, just simple expect() is used.

1. Run the following
```
for (let i = 0; i < 4; i++) {
        test.only(`Develop: does context close when scenario fails ${i}/ 4`, async ({ browser }) => {
	        const page = await browser.newPage();
	        await page.goto('http://google.com')
	        const page2 = await browser.newPage();
	        await page2.goto('http://bing.com')
        
	        test.fail();
	        expect(1).toBe(0);
        
	        await page.close();
	        await page2.close();
        });
}
```
### Expected Behavior
There are four tests running, and at the end of each test, browser should close.
When those two lines (test.fail(); and expect(1).toBe(0);) are removed, it works like that.

### Actual Behavior
there are four tests running, but all four browsers are showing until the fourth scenario finished at which time all are closed.

### Environment
Windows 10, playwright 1.40.1
VSCode:
Version: 1.85.0 (user setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by rolfbjarne** [comment]
This doesn't look related to this repository at all, why do you think this is an issue in the iOS SDK for .NET?

**Comment by super-brian** [comment]
My apologies. This was posted to the wrong project. It was for Playwright. Sorry.
