### ISSUE TITLE
[META] Xcode 15.1 Support for .NET 8 and MAUI

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/xamarin-macios#19623]
Hello!

Xcode 15.1 was released on Dec 11, 2023. We are in the process of updating our bindings and our infra in order to support this release.

As of the time of this post, Xcode 15.1 is not recommended to be used with our .NET MAUI or Xamarin SDKs so our advise is not to install it just yet and **keep using Xcode 15.0** for the time being.

[If you need to download Xcode 15.0 you can get it from the Apple Developer portal.](https://developer.apple.com/download/all/?q=xcode%2015)

We'll keep this post updated as we learn more.

Thank you!

-The macios team

**Comment by Sestav-si-svuj-svet** [comment]
Hello, how long does this usually take? :)

**Comment by tipa** [comment]
I'm assuming [the new Journaling Suggestions API](https://developer.apple.com/documentation/journalingsuggestions) will not be available in the new bindings as it requires SwiftUI?

**Comment by rolfbjarne** [comment]
> I'm assuming [the new Journaling Suggestions API](https://developer.apple.com/documentation/journalingsuggestions) will not be available in the new bindings as it requires SwiftUI?

That's correct, anything that requires SwiftUI or Swift won't be bound.

**Comment by MateuszLas421** [comment]
Xcode 15.2

**Comment by AndrewMaisey** [comment]
I saw an update for Visual Studio 2022 for Windows this morning mentioning support being added for XCode 15.1.

Does that also include XCode 15.2 or would it be best to be version specific to match Visual Studio for Windows?

I work in an environment which for security compliance reasons requires the latest software with patches to be applied so 15.2 support onwards would be helpful.

If there an official link to more information on this patch and cross-systems requirements/recommendation please.

Thank you in advance.

**Comment by tipa** [comment]
@AndrewMaisey the [release notes](https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-8.0.1xx-xcode15.1-8004) mention "15.2 support" and from what I saw today during my tests, all worked perfectly well (however I don't use VS on Windows together with XCode)

**Comment by dalexsoto** [comment]
This is correct, we released yesterday a new version of our workloads that support both Xcode 15.1 and Xcode 15.2, these are included inside [Visual Studio 2022 version 17.8.5](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes) and [Visual Studio 2022 version 17.9 Preview 3](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview). You can find the release notes here [release notes](https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-8.0.1xx-xcode15.1-8004).

**Comment by Grzesik** [comment]
Visual Studio 2022 works fine with XCode 15.2. Unfortunatelly the azure pipeline with the latest vm   -> vmImage: 'macOS-13'  doesn't. It seems to be so, that it works only with XCode 14. Could you update the vm to XCode 15.2.

Log in the pipeline:


ILLINK : warning MT0079: The recommended Xcode version for Microsoft.iOS 17.2.8004 is Xcode 15.1 or later. The current Xcode version (found in /Applications/Xcode_14.3.1.app/Contents/Developer) is 14.3.1. [/Users/runner/work/1/s/Museum2goMaui/Museum2goQA/Museum2goQA.csproj::TargetFramework=net8.0-ios]
ILLink : unknown error IL7000: An error occured while executing the custom linker steps. Please review the build log for more information. [/Users/runner/work/1/s/Museum2goMaui/Museum2goQA/Museum2goQA.csproj::TargetFramework=net8.0-ios]
ILLINK : error MT0180: This version of Microsoft.iOS requires the iOS 17.2 SDK (shipped with Xcode 15.1). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/Museum2goMaui/Museum2goQA/Museum2goQA.csproj::TargetFramework=net8.0-ios]
ILLINK : error MT2301: The linker step 'Setup' failed during processing: This version of Microsoft.iOS requires the iOS 17.2 SDK (shipped with Xcode 15.1). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/Museum2goMaui/Museum2goQA/Museum2goQA.csproj::TargetFramework=net8.0-ios]
/Users/runner/.nuget/packages/microsoft.net.illink.tasks/8.0.1/build/Microsoft.NET.ILLink.targets(87,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/runner/work/1/s/Museum2goMaui/Museum2goQA/Museum2goQA.csproj::TargetFramework=net8.0-ios]

**Comment by scottkuhl** [comment]
What about if you are developing just on a Mac and do not use Visual Studio 2022?  Rider and VS Code will not find the Xcode Simulators in XCode past 15.0.

**Comment by Grzesik** [comment]
As I said, Visual Studio 2022 with XCode 15.2 works well. I don't have here any problem, since the last update. The problem is the Azure Pipelines to create a CI/CD pipeline for .Net Maui. Android Pipeline works, the iOS one has a problem, because of the lack of the newest updates needed for XCode 15.2. I can't update it myself, it can do only Microsoft.

**Comment by rolfbjarne** [comment]
> As I said, Visual Studio 2022 with XCode 15.2 works well. I don't have here any problem, since the last update. The problem is the Azure Pipelines to create a CI/CD pipeline for .Net Maui. Android Pipeline works, the iOS one has a problem, because of the lack of the newest updates needed for XCode 15.2. I can't update it myself, it can do only Microsoft.

Looks like that's in progress: https://github.com/actions/runner-images/issues/9139

**Comment by ramtechjoe** [comment]
@Grzesik 

In order to use xcode 15.2 in Azure pipeline you need to select it using a script command in the pipeline.  By default it will use 14.3

`- script: |
    sudo xcode-select -s /Applications/Xcode_15.2.app
  displayName: Selects a specific version of Xcode
`

**Comment by Grzesik** [comment]
It works! Thanks!. I couldn't find this tip in the Microsoft documentation. 

I have one another problem with my Android .Net Maui pipeline. Maybe you know the solution. I use the android.keystore file for signing an Android app as a "secure file". It has all polices for any pipeline. Unfortunatelly the pipeline can't use the file and I get an error like this:

C:\hostedtoolcache\windows\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.52\tools\Xamarin.Android.Common.targets(2386,2): error XA4310: `$(AndroidSigningKeyStore)` file `D:a_temp***.keystore` could not be found. [D:\a\1\s\Museum2goMaui\***\***.csproj::TargetFramework=net8.0-android]

My pipeline has following tasks:

- task: DownloadSecureFile@1
   displayName: 'Download Android Key Store file'
   name: keystore
   inputs:
      secureFile: 'Museum2goQA.keystore'

.....
- task: Bash@3
        displayName: Build Android App
        inputs:
          targetType: inline
          script: |
            cd Museum2goMaui/Museum2goQA/
            dotnet publish -f net8.0-android -c Release -p:AndroidKeyStore=true -**p:AndroidSigningKeyStore=$(keystore.secureFilePath)** -p:AndroidSigningKeyAlias=$(museum2go_qa_store_alias) -p:AndroidSigningKeyPass=$(museum2go_qa_store_password) -p:AndroidSigningStorePass=$(museum2go_qa_store_password)


When I have the file Museum2goQA.keystore in the project, it works fine, but I have to use the name directly.
I see also, that the 'secure file' will be downloaded (echo Installing $(keystore.secureFilePath)):
D:\a\_temp\***.keystore

Do you have any tip for me , how to use the "secure file" to sign an Android app?

**Comment by ramtechjoe** [comment]
@Grzesik I only do iOS at this point

**Comment by thomasgalliker** [comment]
@Grzesik I had the same error. Use double-quotes around $(keystore.secureFilePath)
`-p:AndroidSigningKeyStore="$(keystore.secureFilePath)"`
