### ISSUE TITLE
Does xamarin-mac support NSUserInterfaceItemSearching now?

### ISSUE THREAD

**Issue by lisalisal** [xamarin/xamarin-macios#19649]
We are using xamarin-mac, and  trying to use 'NSUserInterfaceItemSearching(https://developer.apple.com/documentation/appkit/nsuserinterfaceitemsearching?language=objc)' to add Spotlight for Help for our own custom help data. But we couldn't found corresponding implementation for NSUserInterfaceItemSearching in xamarin-mac.

So we wonder if xamarin-mac supports NSUserInterfaceItemSearching now?

**Comment by rolfbjarne** [comment]
No, we've not bound `NSUserInterfaceItemSearching` yet, but I'll get a pull request adding support for it soon.

**Comment by lisalisal** [comment]
Thanks a lot for the quick response.
by the way, when is the next release that would include this fix?

**Comment by rolfbjarne** [comment]
I'm not quite sure, it depends a bit on Apple's release schedule as well.
