### ISSUE TITLE
Add a NativeAOT variation to the submission tests.

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#19647]
As the title says.

**Comment by rolfbjarne** [comment]
CC @dalexsoto

**Comment by haritha-mohan** [comment]
@rolfbjarne on it! are we trying to get this in by the next release?

cc @dalexsoto

**Comment by dalexsoto** [comment]
@haritha-mohan Before our next .NET 9 release would be ideal
