### ISSUE TITLE
Enable Stack Canaries for Xamarin.iOS builds

### ISSUE THREAD

**Issue by jeremy-bridges** [xamarin/xamarin-macios#19657]
### Steps to Reproduce

1. Build an Xamarin.iOS app in release mode using the LLVM option
2. Run otool on the .app file to discover stack checks in place in the app
(command: "otool -Iv appName | grep stack_chk")

### Expected Behavior

Otool shows stack_chk_fail or stack_chk_guard flags have been set.

### Actual Behavior

Neither of these flags are set.

### Environment

<details>
<summary>Version information</summary>

Visual Studio Community 2022 for Mac
Version 17.6.7 (build 417)
Installation UUID: c782d982-3710-497b-ae6f-1f229c6fffe1

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/8.0.100/Sdks
SDK Versions:
	8.0.100
	7.0.311
	7.0.309
	7.0.307
	7.0.306
	7.0.302
	7.0.203
	7.0.202
	7.0.101
	7.0.100
	6.0.417
	6.0.415
	6.0.413
	6.0.412
	6.0.408
	6.0.407
	6.0.404
	6.0.403
	6.0.402
	6.0.401
	6.0.400
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	3.1.426
	3.1.425
	3.1.424
	3.1.423
	3.1.422

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	8.0.0
	7.0.14
	7.0.12
	7.0.10
	7.0.9
	7.0.5
	7.0.4
	7.0.1
	7.0.0
	6.0.25
	6.0.23
	6.0.21
	6.0.20
	6.0.16
	6.0.15
	6.0.12
	6.0.11
	6.0.10
	6.0.9
	6.0.8

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	3.1.32
	3.1.31
	3.1.30
	3.1.29
	3.1.28

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: /Users/jeremybridges/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.1
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-11-10 12:19:52 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-11-10 12:19:52 UTC

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-11-10 12:19:46 UTC

Apple Developer Tools
Xcode: 14.3 21812
Build: 14E222b

Xamarin.Mac
Version: 9.3.0.23 Visual Studio Community
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:14:59-0400

Xamarin.iOS
Version: 16.4.0.23 Visual Studio Community
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:15:00-0400

Build Information
Release ID: 1706070417
Git revision: 179aa48a5702754e41a8218d0403ddc3be46706f
Build date: 2023-11-10 12:18:09+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.6.0
Darwin 22.6.0 Darwin Kernel Version 22.6.0
    Fri Sep 15 13:41:28 PDT 2023
    root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64

</details>

### Build Logs

Can provide build log if needed. The Project System Tools extension no longer works in VS for Mac. So, can't capture them as stated in the issue template.

**Comment by jeremy-bridges** [comment]
This is part of usual security recommendations:

https://github.com/nowsecure/secure-mobile-development/blob/master/en/ios/implement-protections-against-buffer-overflow-attacks.md

**Comment by rolfbjarne** [comment]
> 2\. otool -Iv appName | grep stack_chk

That doesn't display any stack checks, it prints the Mach-O load commands (and the grep finds nothing, since load commands are unrelated to stack checks).

Do this instead:

> nm appName | grep stack_chk

and you should see something like this:

```
$ nm bin/iPhone/Release/MySingleView.app/MySingleView|g stack_chk
                 U ___stack_chk_fail
                 U ___stack_chk_guard
```
