### ISSUE TITLE
Could not find file AssetPackManifestTemplate.plist in "WriteAssetPackManifest" task when run in DevOps

### ISSUE THREAD

**Issue by rlasker-b2w** [xamarin/xamarin-macios#19669]
In a .Net Maui project that was migrated from Xamarin, I can run the exact same dotnet publish command on my local Mac and the command completes successfully but when I run the same publish command in Azure DevOps using the DotNetCLI@2 task then I get an error that it cannot find the AssetPackManifestTemplate.plist file during the execution of the [WriteAssetPackManifest](https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.iOS.Tasks/Tasks/WriteAssetPackManifest.cs) task.

### Steps to Reproduce

1. create an .Net Maui app
2. create a Azure DevOps build using the DotNetCoreCLI@2
3. command: "publish"
4. arguments: -c "$(BuildConfiguration)" -f "net7.0-ios" -o $(build.artifactstagingdirectory) -r ios-arm64 --self-contained
5. vmImage: macos-13
6. DotNetVersion: 7.0.403
7. xcode version 15.0.1

### Expected Behavior
UseDotNet@2 task completes successfully

### Actual Behavior
error MSB4018: The "WriteAssetPackManifest" task failed unexpectedly.
error MSB4018: System.IO.FileNotFoundException: Could not find file '/Users/runner/work/1/s/Inform.Forms/obj/Test/net7.0-ios/ios-arm64/ipa/Payload/Inform.Forms.app/AssetPackManifestTemplate.plist'. 

### Environment
Pool: [Azure Pipelines](https://dev.azure.com/b2wsoftware/8be93b52-3f2e-4e86-b29f-4ec214a84418/_settings/agentqueues?poolId=&queueId=40)
Image: macos-13
Agent: Hosted Agent

Starting: Build iOS App

Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.221.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli

/Users/runner/hostedtoolcache/dotnet/dotnet publish /Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj -c Test -f net7.0-ios -o /Users/runner/work/1/a -r ios-arm64 --self-contained
MSBuild version 17.7.3+4fca21998 for .NET

/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018: The "WriteAssetPackManifest" task failed unexpectedly. [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018: System.IO.FileNotFoundException: Could not find file '/Users/runner/work/1/s/Inform.Forms/obj/Test/net7.0-ios/ios-arm64/ipa/Payload/Inform.Forms.app/AssetPackManifestTemplate.plist'. [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018: File name: '/Users/runner/work/1/s/Inform.Forms/obj/Test/net7.0-ios/ios-arm64/ipa/Payload/Inform.Forms.app/AssetPackManifestTemplate.plist' [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError) [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException) [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access) [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at Xamarin.MacDev.PObject.FromFile(String fileName, Boolean& isBinary) in /Users/builder/azdo/_work/1/s/xamarin-macios/external/Xamarin.MacDev/Xamarin.MacDev/PListObject.cs:line 336 [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at Xamarin.MacDev.PDictionary.FromFile(String fileName, Boolean& isBinary) in /Users/builder/azdo/_work/1/s/xamarin-macios/external/Xamarin.MacDev/Xamarin.MacDev/PListObject.cs:line 751 [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at Xamarin.MacDev.PDictionary.FromFile(String fileName) in /Users/builder/azdo/_work/1/s/xamarin-macios/external/Xamarin.MacDev/Xamarin.MacDev/PListObject.cs:line 739 [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at Xamarin.iOS.Tasks.WriteAssetPackManifestTaskBase.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Tasks/WriteAssetPackManifestTaskBase.cs:line 28 [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at Xamarin.iOS.Tasks.WriteAssetPackManifest.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Tasks/WriteAssetPackManifest.cs:line 11 [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]
/Users/runner/hostedtoolcache/dotnet/packs/Microsoft.iOS.Sdk/16.4.7129/tools/msbuild/iOS/Xamarin.iOS.Common.targets(534,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj::TargetFramework=net7.0-ios]

**Comment by rolfbjarne** [comment]
Can you get a binlog from the failing build in Azure DevOps?

You can get a binlog by adding `-bl:msbuild.binlog` to the build command, like this:

> -c "$(BuildConfiguration)" -f "net7.0-ios" ... -bl:msbuild:binlog

and then attach the resulting msbuild.binlog here.

**Comment by rlasker-b2w** [comment]
I thought perhaps using the output parameter in the publish command ("-o $(build.artifactstagingdirectory)") could have resulted in why the missing file could not be found since the task was looking in the source ("work/1/s") directory and the output parameter was sending it to the artifacts directory ("work/1/a").

> Could not find file '/Users/runner/work/1/s/Inform.Forms/obj/Test/net7.0-ios/ios-arm64/ipa/Payload/Inform.Forms.app/AssetPackManifestTemplate.plist'.

I realized, though, that even when I had removed that parameter in order to do the binlog I still got the same error.

> /Users/runner/hostedtoolcache/dotnet/dotnet publish /Users/runner/work/1/s/Inform.Forms/Inform.Forms.csproj -c Test -f net7.0-ios -r ios-arm64 --self-contained -bl:msbuild.binlog

**Comment by rolfbjarne** [comment]
The difference is that the codesigning profile is an AdHoc profile, and that enters a different codepath during the build, which ends up failing.

**Comment by rlasker-b2w** [comment]
If I am following you, it is the "Codesign" task that was skipped due to the following false condition?

> Task "Codesign" skipped, due to false condition; 
('$(IsMacEnabled)' == 'true' And '@(_AssetPack)' != '' And '$(_DistributionType)' == 'AppStore') 
was evaluated as 
('true' == 'true' And 'obj/Test/net7.0-ios/ios-arm64/ipa/Payload/Inform.Forms.app/OnDemandResources/com.b2wsoftware.inform.ICON_TOOLBAR__MENU_ALERT.assetpack/' != '' And 'AdHoc' == 'AppStore').

I'm curious why it would work in my local environment then since it would be using the same AdHoc profile? The Xamarin iOS version on my environment is 16.4.0.23.

**Comment by rolfbjarne** [comment]
No, this is executed when it fails (and normally isn't executed):

https://github.com/xamarin/xamarin-macios/blob/2eccd8810c615f2695531e9ad5277cf4c0cd269a/msbuild/Xamarin.Shared/Xamarin.iOS.Common.targets#L534-L541

Can you try adding this to your csproj to see if it works around the problem?

```xml
<Target Name="InvokeTarget_CreateAssetPackManifest" DependsOnTargets="_CreateAssetPackManifest" AfterTargets="_CopyResourcesToBundle" />
```

**Comment by rolfbjarne** [comment]
Note to self: I can reproduce using the iTravel submission sample with an AdHoc profile.
