### ISSUE TITLE
Xcode 15 build in ADO fails on Xamarin.Google.iOS.MobileAds / FirebaseCore

### ISSUE THREAD

**Issue by JohnHDev** [xamarin/xamarin-macios#19713]
I am able to create release builds of Xamarin.IOS/XF apps with Xcode 15 (although having to nuget restore for several projects directly, don't know why...), but not able to create release builds of any apps that contain Xamarin.Google.iOS.MobileAds / Firebase.

The purpose is to ensure we have a contingency plan in case we haven't been able to migrate to .NET MAUI by May 2024.

### Steps to Reproduce

1. Create a release build of a Xamarin iOS app that uses the Xamarin.Google.iOS.MobileAds nuget and Firebase
2. Build fails with various similar errors:
  MTOUCH : error MT5214: Native linking failed, undefined symbol: _CGSizeFromGADAdSize. This symbol was referenced by the managed member Google.MobileAds.AdSizeCons.GetCGSize. Please verify that all the necessary frameworks have been referenced and native libraries linked. [/Users/runner/work/1/s/xxx.iOS/xxx.iOS.csproj]

### Expected Behavior
Should be able to build successfully

### Actual Behavior
Build fails

### Environment
Xcode 15, Azure Dev Ops build host MacOS-13. xamarin.ios-16.4.0.23, Xamarin.Google.iOS.MobileAds 8.13.0.3

### Build Logs

MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -Xlinker -ld_classic -ObjC -lc++ -lsqlite3 -lz [/Users/runner/work/1/s/xxx.iOS/xxx.iOS.csproj]
  		
  /Applications/Xcode_15.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -F /Users/runner/Library/Caches/XamarinBuildDownload/GAppM-8.9.1/GoogleAppMeasurement-8.9.1/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7 -framework GoogleAppMeasurement -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/FirebaseCore.xcframework/ios-arm64 -framework FirebaseCore -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/FirebaseCoreDiagnostics.xcframework/ios-arm64 -framework FirebaseCoreDiagnostics -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/GTMSessionFetcher.xcframework/ios-arm64 -framework GTMSessionFetcher -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/GoogleAPIClientForREST.xcframework/ios-arm64 -framework GoogleAPIClientForREST -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/GoogleDataTransport.xcframework/ios-arm64 -framework GoogleDataTransport -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/FBLPromises.xcframework/ios-arm64 -framework FBLPromises -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/GoogleToolboxForMac.xcframework/ios-arm64 -framework GoogleToolboxForMac -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/GoogleUtilities.xcframework/ios-arm64 -framework GoogleUtilities -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/GoogleUtilitiesComponents.xcframework/ios-arm64 -framework GoogleUtilitiesComponents -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/nanopb.xcframework/ios-arm64 -framework nanopb -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/leveldb.xcframework/ios-arm64 -framework leveldb -F /Users/runner/.nuget/packages/xamarin.firebase.ios.core/8.10.0.3/lib/xamarinios10/Firebase.Core.resources/Protobuf.xcframework/ios-arm64 -framework Protobuf -F /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/SDKs/MonoTouch.iphoneos.sdk/Frameworks -framework Mono -framework CoreFoundation -framework Security -framework CFNetwork -framework SafariServices -framework ContactsUI -framework UserNotifications -framework StoreKit -framework Photos -framework OpenGLES -framework MessageUI -framework MediaPlayer -framework Intents -framework ImageIO -framework GLKit -framework WebKit -framework Foundation -framework EventKitUI -framework EventKit -framework CoreVideo -framework CoreText -framework CoreSpotlight -framework CoreLocation -framework CoreGraphics -framework QuartzCore -framework Contacts -framework AuthenticationServices -framework UIKit -framework AddressBook -framework CoreTelephony -framework SystemConfiguration -F /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache -framework WidgetCenterProxy -framework GSS -weak_framework AppTrackingTransparency -weak_framework StoreKit -weak_framework Foundation -weak_framework UIKit -weak_framework SystemConfiguration -weak_framework CoreTelephony -weak_framework Security -weak_framework WidgetKit -Xlinker -rpath -Xlinker @executable_path/Frameworks /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/registrar.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/main.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/xxx.iOS.exe.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/mscorlib.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Utils.Standard.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Core.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Mono.Security.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Xml.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Numerics.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Data.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Drawing.Common.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.ComponentModel.Composition.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Net.Http.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.iOS.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Runtime.Serialization.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.ServiceModel.Internals.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Web.Services.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Xml.Linq.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/AppDev.Base.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Newtonsoft.Json.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Autofac.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.Bcl.AsyncInterfaces.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Diagnostics.DiagnosticSource.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.Analytics.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.iOS.Bindings.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.Analytics.iOS.Bindings.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Calendar.Standard.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/xxxx.Translations.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/xxxx.iOS.Common.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/AutoMapper.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.CSharp.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Calendar.Standard.XF.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Utils.XF.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.Forms.Core.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.Forms.Platform.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.Forms.Platform.iOS.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/AppDev.XF.Controls.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/AppDev.XF.Fluent.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Reminder.Standard.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.Essentials.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/OpenTK-1.0.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Reminders.Standard.XF.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Utils.iOS.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/AppDev.XF.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Plugin.InAppBilling.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/AppDev.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Calendar.iOS.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Contacts.Standard.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.Crashes.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.Crashes.iOS.Bindings.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/NativeLibrary.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Contacts.iOS.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Eventium.XF.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Reminders.iOS.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/AddressBook.IOS.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Google.MobileAds.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Firebase.Core.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/Utils.Ads.iOS.dll.o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/AppCenter.a /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/AppCenterAnalytics.a /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/SDKs/MonoTouch.iphoneos.sdk/lib/libxamarin.a /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/SDKs/MonoTouch.iphoneos.sdk/lib/libmono-native-unified.a -force_load /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/AppCenterCrashes.a -force_load /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/SDKs/MonoTouch.iphoneos.sdk/lib/libapp.a -lsqlite3 -lc++ -Wl,-pie -arch arm64 -miphoneos-version-min=12.2 -isysroot /Applications/Xcode_15.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.2.sdk -lz -liconv -lz -o /Users/runner/work/1/s/myCal.iOS/obj/iPhone/Release/mtouch-cache/arm64/myCal.iOS -Xlinker -ld_classic -ObjC -lc++ -lsqlite3 -lz -u _xamarin_log -u _xamarin_release_managed_ref -u _xamarin_set_gchandle_with_flags_safe -u _xamarin_UIApplicationMain -u _xamarin_find_protocol_wrapper_type -u _xamarin_release_block_on_main_thread -u _xamarin_get_block_descriptor -u _xamarin_IntPtr_objc_msgSend_IntPtr_exception -u _xamarin_IntPtr_objc_msgSendSuper_IntPtr_exception -u _GADCustomNativeAdMediaViewKey -u _GADSimulatorID -u _GADPortraitInlineAdaptiveBannerAdSizeWithWidth -u _GADLandscapeInlineAdaptiveBannerAdSizeWithWidth -u _GADCurrentOrientationInlineAdaptiveBannerAdSizeWithWidth -u _GADInlineAdaptiveBannerAdSizeWithWidthAndMaxHeight -u _GADPortraitAnchoredAdaptiveBannerAdSizeWithWidth -u _GADLandscapeAnchoredAdaptiveBannerAdSizeWithWidth -u _GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth -u _GADAdSizeFromCGSize -u _GADAdSizeFullWidthPortraitWithHeight -u _GADAdSizeFullWidthLandscapeWithHeight -u _GADAdSizeEqualToSize -u _CGSizeFromGADAdSize -u _IsGADAdSizeValid -u _GADAdSizeIsFluid -u _NSStringFromGADAdSize -u _NSValueFromGADAdSize -u _GADAdSizeFromNSValue -u _GADAdSizeBanner -u _GADAdSizeFluid -u _GADAdSizeFullBanner -u _GADAdSizeInvalid -u _GADAdSizeLargeBanner -u _GADAdSizeLeaderboard -u _GADAdSizeMediumRectangle -u _GADAdSizeSkyscraper -u _kGADAdSizeSmartBannerLandscape -u _kGADAdSizeSmartBannerPortrait -u _GADAdLoaderAdTypeCustomNative -u _GADAdLoaderAdTypeGAMBanner -u _GADAdLoaderAdTypeNative -u _GADMaxAdContentRatingGeneral -u _GADMaxAdContentRatingMatureAudience -u _GADMaxAdContentRatingParentalGuidance -u _GADMaxAdContentRatingTeen -u _GADNativeAdChoicesViewAsset -u _GADNativeAdvertiserAsset -u _GADNativeBodyAsset -u _GADNativeCallToActionAsset -u _GADNativeHeadlineAsset -u _GADNativeIconAsset -u _GADNativeImageAsset -u _GADNativeMediaViewAsset -u _GADNativePriceAsset -u _GADNativeStarRatingAsset -u _GADNativeStoreAsset -u _GADCustomEventAdNetworkClassName -u _GADErrorUserInfoKeyResponseInfo -u _GADGoogleAdNetworkClassName -u _FIRFirebaseVersion
  Undefined symbols for architecture arm64:
    "_CGSizeFromGADAdSize", referenced from:
       -u command line option
    "_GADAdLoaderAdTypeCustomNative", referenced from:
       -u command line option
    "_GADAdLoaderAdTypeGAMBanner", referenced from:
       -u command line option
    "_GADAdLoaderAdTypeNative", referenced from:
       -u command line option
    "_GADAdSizeBanner", referenced from:
       -u command line option
    "_GADAdSizeEqualToSize", referenced from:
       -u command line option
    "_GADAdSizeFluid", referenced from:
       -u command line option
    "_GADAdSizeFromCGSize", referenced from:
       -u command line option
    "_GADAdSizeFromNSValue", referenced from:
       -u command line option
    "_GADAdSizeFullBanner", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GADNativeMuteThisAdLoaderOptions", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GADRequest", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GADRequestConfiguration", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GADResponseInfo", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GADRewardedAd", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GADRewardedInterstitialAd", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GADSearchBannerView", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GADServerSideVerificationOptions", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GADVideoController", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GADVideoOptions", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GAMBannerView", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GAMBannerViewOptions", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GAMInterstitialAd", referenced from:
        objc-class-ref in registrar.o
    "_OBJC_CLASS_$_GAMRequest", referenced from:
        objc-class-ref in registrar.o
    "_kGADAdSizeSmartBannerLandscape", referenced from:
       -u command line option
    "_kGADAdSizeSmartBannerPortrait", referenced from:
       -u command line option
  ld: symbol(s) not found for architecture arm64
clang : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/runner/work/1/s/xxx.iOS/xxx.iOS.csproj]
   
Done Building Project "/Users/runner/work/1/s/xxx.iOS/xxx.iOS.csproj" (default targets) -- FAILED.

And various instances of the following on different symbols:
MTOUCH : error MT5214: Native linking failed, undefined symbol: _CGSizeFromGADAdSize. This symbol was referenced by the managed member Google.MobileAds.AdSizeCons.GetCGSize. Please verify that all the necessary frameworks have been referenced and native libraries linked. [/Users/runner/work/1/s/xxx.iOS/xxx.iOS.csproj]

**Comment by rolfbjarne** [comment]
Could attach a binlog? 
This describes how to get a binlog: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs

**Comment by JohnHDev** [comment]
@rolfbjarne thanks, would have done that but:
In my efforts to get a local release build I found that I needed to remove projects, add them back in, and add references, as well as tidied up some old packages.config projects (12 year old Xamarin app). I was then able to build release builds locally, committed to my branch, and the pipeline builds now work! So I will close this for now, I still need to investigate why Im having to nuget restore on each project, if that's still an issue I'll raise a separate ticket if that's ok. Closing this.

**Comment by JohnHDev** [comment]
@rolfbjarne I resolved the nuget restore issue, I had 2 legacy Xamarin projects that failed to nuget restore and then stopped the restore for the rest of the projects. Removed the legacy Xamarin Android and Xamarin Mac projects, nuget restore now works as expected.
So my hobby XF projects are now fully buildable on Xcode 15 on Azure DevOps. We can now proceed with our work Xcode 15 upgrade too.

**Comment by rolfbjarne** [comment]
Thanks for letting us know what the problem was!
