### ISSUE TITLE
Ambiguity Between 'Microsoft.iOS, Version=17.0.0.0 and 'Xamarin.iOS' 

### ISSUE THREAD

**Issue by mollea3** [xamarin/xamarin-macios#19777]
Hi Team, 

I'm developing an application using **Xamarin.iOS** and the latest .Net 8.0(Microsoft.iOS) and I want to refer **Microsoft.iOS.dll**  in the Xamarin Project then the application is throwing the compile time errors as Below.
![image](https://github.com/xamarin/xamarin-macios/assets/110099038/2790d23a-b3b0-4bc3-b53f-5a36784c88a5)

**Following are the references for the project.**

![image](https://github.com/xamarin/xamarin-macios/assets/110099038/dcdadff5-98e7-4e49-b01a-9583d8d9f9ca)

![image](https://github.com/xamarin/xamarin-macios/assets/110099038/6d1b6760-1e13-4230-ba3c-297b19deb9d6)

Please suggest how to resolve these compile time errors.

Thanks in Advance !

**Comment by rolfbjarne** [comment]
> I'm developing an application using **Xamarin.iOS** and the latest .Net 8.0(Microsoft.iOS)

You can't do that, you'll have to choose, either Xamarin.iOS or .NET (Microsoft.iOS).

> I want to refer **Microsoft.iOS.dll** in the Xamarin Project

That won't work; you need to upgrade your project to a .NET project in order to use Microsoft.iOS.dll.
