### ISSUE TITLE
App is rejected with: The XXXX.app/libe_sqlite3.dylib" binary file is not permitted

### ISSUE THREAD

**Issue by borrmann** [xamarin/xamarin-macios#19910]
[following on issue](https://github.com/xamarin/xamarin-macios/issues/18751)

### Steps to Reproduce

1. publish a MAUI (ios) project with some Nuget libraries and a project reference with Nuget libraried via CLI: 
`dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:CodesignKey="Apple Distribution:  XXXXXX" -p:CodesignProvision="XXXX" -p:MtouchLink=Full -p:MtouchUseLlvm=true  -p:LinkMode=Full`
2. Create IPA and publish to AppStore

### Expected Behavior
App should be accepted

### Actual Behavior
App is rejected with:
The XXXX.app/libe_sqlite3.dylib" binary file is not permitted

### Environment
this link below does not show how to get the version-information from VS Code on a Mac. 
I use net8.0-ios SR1 from MAUI and latest MAUI controls from Nuget (8.0.6)

<details>
<summary>Version information</summary>

```
```

</details>

### Build Logs
This is a build log created with 
dotnet build meitiMaui.csproj -c Release /bl:msbuild.binlog

[msbuild.binlog.zip](https://github.com/xamarin/xamarin-macios/files/14050399/msbuild.binlog.zip)

**Comment by borrmann** [comment]
@rolfbjarne Thank you, I appreciate the quick response. I was able to upload the App to the AppStore with the extra line!
Since you added the Future milestone, I will leave this ticket open, but feel free to close this issue if you consider this issue as resolved.

**Comment by rolfbjarne** [comment]
I'll close this then, thanks or confirming it worked!

**Comment by borrmann** [comment]
Just in case anyone ever runs into this issue.
Sqlite pcl-net should probably not be updated to 1.8.116 due to [this issue](https://github.com/praeclarum/sqlite-net/issues/1067), at least not when AOT is enabled in production.
instead use 1.7.335 (as mentioned in the linked issue)

`
<PackageReference Include="sqlite-net-pcl" Version="[1.7.335]" />		
`
