### ISSUE TITLE
Support for Privacy Manifest

### ISSUE THREAD

**Issue by phillippschmedt** [xamarin/xamarin-macios#19966]
Starting in fall 2024 a privacy manifest will be mandatory for all iOS apps: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

Will this be supported by xamarin iOS?

**Comment by rolfbjarne** [comment]
I'm not entirely sure what will happen with Xamarin.iOS (support for Xamarin will end on May 1st: https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), but there probably won't be support for privacy manifests in Xamarin.iOS.

In .NET, we'll support it.

**Comment by phillippschmedt** [comment]
@rolfbjarne Thank you. Please consider to extend the support for xamarin atleast to the point where we can complying with apple/google requirements. It's not that we do not want to migrate to .NET MAUI, in fact we have migrated all of our code but .NET MAUI is still unstable and not production ready. There is multiple open issues in the .NET MAUI tracker that need to be solved until we can even consider releasing it.

**Comment by gabsamples6** [comment]
@rolfbjarne  I would like to add my concern here, we are migrating to Maui and we are nearly there , but some Maui bugs are preventing us to be ready for April, and we are concerned that if we need to release a Xamarin fix  in April because we are not maui ready we will be in trouble as it will require this privacy manifest.  I do hope this gets the relevant attention as I guess there will be thousands of apps that might face this issue. Many thanks

**Comment by djunod** [comment]
Same issues as the folks above mentioned.  We definitely need support for this in Xamarin.  Maui is unfortunately still not there.

**Comment by todorsp** [comment]
Same as the others. Asking here - would it be possible to add this by ourselves in our existing Xamarin Forms projects? From what I understand the is just another plist file to integrate in the build process. Am I wrong?
Thanks

**Comment by jasonleach** [comment]
This is me begging for help. Same issue as others above.
I don't see any support for a privacy manifest in Maui either.  It needs to be there, and it needs to be soon.
Please work this out in both xamarin and maui, especially before you abandon all of us xamarin users and leave us with Maui which right now is  the most undependable buggy thing produced in many years.  practically windows millenial.

**Comment by todorsp** [comment]
> Just adding my vote. My MAUI migration is moving along slowly due to missing 3rd party library support and issues with deploying to Windows. The Ios Privacy manifest will be required soon and hopefully will be supported by Xamarin.
> 
> I am being warned about the following... NSPrivacyAccessedAPICategorySystemBootTime NSPrivacyAccessedAPICategoryFileTimestamp NSPrivacyAccessedAPICategoryDiskSpace NSPrivacyAccessedAPICategoryUserDefaults
> 
> Does anyone know which libraries are triggering these warning? My guess is Xamarin or Xamarin Essentials. If so then it would be nice to have them provide the privacyinfo.xcprivacy file

Hi, I have had exactly these warnings when submitting to the App Store for review.
What I have tried to do is 'compose' my own privacyinfo.xcprivacy (it's just a text file, similar to info.plist) including these fields and added it to the build process as bundle resource. I have resubmitted a new version of our app with this privacyinfo.xcprivacy included and am waiting for the Apple review.
I will post here the 'results' of this review (whether warnings still exist)...

**Comment by jasonleach** [comment]
> Hi, I have had exactly these warnings when submitting to the App Store for review. What I have tried to do is 'compose' my own privacyinfo.xcprivacy (it's just a text file, similar to info.plist) including these fields and added it to the build process as bundle resource. I have resubmitted a new version of our app with this privacyinfo.xcprivacy included and am waiting for the Apple review. I will post here the 'results' of this review (whether warnings still exist)...

I tried this as well. I stuctured it as a plist, which is what XCode does.  It still returned the same warning.  it seems xamarin did not see it as a plist file that needed to be included in the ipa.  I did not add it as a bundle resource, because info.plist is not added that way.  I hope your method works!

**Comment by jasonleach** [comment]
[todorsp] comment above: My attempt to use your method WORKED! this is a valid workaround.  I got an email back from apple that the file was parsed, and one of my values was unacceptable. (typo in the file) but the others were good.
so steps to remedy:  

- Create a plist file.
- rename it Privacyinfo.xcprivacy. (I had the uppercase P, as apple does.  don't know if it is case sensitive, but accepted the file like this so i am going with it)
- set the build process to "bundle resource"
- edit it to look like this: (change the accessed api types to the ones you need, obviously)
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
	  <key>NSPrivacyTracking</key>
	  <false/>
	  <key>NSPrivacyTrackingDomains</key>
	  <array/>
	  <key>NSPrivacyCollectedDataTypes</key>
	  <array/>
	  <key>NSPrivacyAccessedAPITypes</key>
	  <array>
		  <dict>
			  <key>NSPrivacyAccessedAPIType</key>
			  <string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
			  <key>NSPrivacyAccessedAPITypeReasons</key>
			  <array>
				  <string>C617.1</string>
			  </array>
		  </dict>
		  <dict>
			  <key>NSPrivacyAccessedAPIType</key>
			  <string>NSPrivacyAccessedAPICategorySystemBootTime</string>
			  <key>NSPrivacyAccessedAPITypeReasons</key>
			  <array>
				  <string>8FFB.1</string>
			  </array>
		  </dict>
	  </array>
  </dict>
</plist>`

find your reason codes (the C617.1 nonsense) here:[https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

**Comment by giuseppenovielli** [comment]
> [todorsp] comment above: My attempt to use your method WORKED! this is a valid workaround. I got an email back from apple that the file was parsed, and one of my values was unacceptable. (typo in the code string) but the others were good. so steps to remedy:
> 
> * Create a plist file.
> * rename it Privacyinfo.xcprivacy. (I had the uppercase P, as apple does.  don't know if it is case sensitive, but accepted the file like this so i am going with it)
> * set the build process to "bundle resource"
> * edit it to look like this: (change the accessed api types to the ones you need, obviously)
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
>   <dict>
> 	  <key>NSPrivacyTracking</key>
> 	  <false/>
> 	  <key>NSPrivacyTrackingDomains</key>
> 	  <array/>
> 	  <key>NSPrivacyCollectedDataTypes</key>
> 	  <array/>
> 	  <key>NSPrivacyAccessedAPITypes</key>
> 	  <array>
> 		  <dict>
> 			  <key>NSPrivacyAccessedAPIType</key>
> 			  <string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
> 			  <key>NSPrivacyAccessedAPITypeReasons</key>
> 			  <array>
> 				  <string>C617.1</string>
> 			  </array>
> 		  </dict>
> 		  <dict>
> 			  <key>NSPrivacyAccessedAPIType</key>
> 			  <string>NSPrivacyAccessedAPICategorySystemBootTime</string>
> 			  <key>NSPrivacyAccessedAPITypeReasons</key>
> 			  <array>
> 				  <string>8FFB.1</string>
> 			  </array>
> 		  </dict>
> 	  </array>
>   </dict>
> </plist>
> ```
> 
> find your reason codes (the C617.1 nonsense) here:https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

Does it works with Xamarin.Forms?

**Comment by todorsp** [comment]
@jsonleach - great news :-). I am still waiting for review in the App Store but not warnings up to now.
@giuseppenovielli - yes, this all is for Xamarin Forms (no Idea about Maui)...

**Comment by djunod** [comment]
Can verify that [todorsp](https://github.com/todorsp) and [jasonleach](https://github.com/jasonleach) method of including it as a bundled resource worked for me as well.

**Comment by gabsamples6** [comment]
Hi I have  added below to the proj file but when I view the Build Action in file properties **BundleResource** is not there! What Am I missing? thanks

```
  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
    <BundleResource Include="Platforms\iOS\PrivacyInfo.xcprivacy" LogicalName="PrivacyInfo.xcprivacy" />
  </ItemGroup>
```

**Comment by solomonfried** [comment]
> <key>NSPrivacyTracking</key>
> 	  <false/>
> 	  <key>NSPrivacyTrackingDomains</key>
> 	  <array/>
> 	  <key>NSPrivacyCollectedDataTypes</key>
> 	  <array/>

Are the empty sections required?

**Comment by jeanpierrep1972** [comment]
> I'm not entirely sure what will happen with Xamarin.iOS (support for Xamarin will end on May 1st: https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), but there probably won't be support for privacy manifests in Xamarin.iOS.
> 
> In .NET, we'll support it.

Hello may I ask why it not supported in Xamarin iOS? It's not a simple file like PrivacyInfo.xcprivacy to put in the project root?

**Comment by Markus2807** [comment]
This solution does not work for me.

> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/FBLPromises.framework/FBLPromises”, which includes FBLPromises, an SDK that was identified in the documentation as a commonly used third-party SDK. If a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/FirebaseCore.framework/FirebaseCore”, which includes FirebaseCore, an SDK that was identified in the documentation as a commonly used third-party SDK. If a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/FirebaseCoreDiagnostics.framework/FirebaseCoreDiagnostics”, which includes FirebaseCoreDiagnostics, an SDK that was identified in the documentation as a commonly used third-party SDK. If a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher”, which includes GTMSessionFetcher, an SDK that was identified in the documentation as a commonly used third-party SDK. If a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/GoogleDataTransport.framework/GoogleDataTransport”, which includes GoogleDataTransport, an SDK that was identified in the documentation as a commonly used third-party SDK. If a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac”, which includes GoogleToolboxForMac, an SDK that was identified in the documentation as a commonly used third-party SDK. If a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/GoogleUtilities.framework/GoogleUtilities”, which includes GoogleUtilities, an SDK that was identified in the documentation as a commonly used third-party SDK. If a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/Protobuf.framework/Protobuf”, which includes Protobuf, an SDK that was identified in the documentation as a commonly used third-party SDK. If a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/leveldb.framework/leveldb”, which includes leveldb, an SDK that was identified in the documentation as a commonly used third-party SDK. If a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/nanopb.framework/nanopb”, which includes nanopb, an SDK that was identified in the documentation as a commonly used third-party SDK. If a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements.

I added a custom Privacyinfo.xcprivacy file as BundleResource.

I also added all the Privacyinfo files directly from the Firebase Repo. But none of them worked.

Here a part of my csproj file

```
    <BundleResource Include="PrivacyManifest\FBLPromises.xcprivacy" >
      <LogicalName>Frameworks/FBLPromises.framework/FBLPromises.xcprivacy</LogicalName>
    </BundleResource>
    <BundleResource Include="PrivacyManifest\GoogleToolboxForMac.xcprivacy" >
      <LogicalName>Frameworks/GoogleToolboxForMac.framework/GoogleToolboxForMac.xcprivacy</LogicalName>
    </BundleResource>
    <BundleResource Include="PrivacyManifest\GoogleUtilities.xcprivacy" >
      <LogicalName>Frameworks/GoogleUtilities.framework/GoogleUtilities.xcprivacy</LogicalName>
    </BundleResource>
    <BundleResource Include="PrivacyManifest\GTMSessionFetcher.xcprivacy" >
      <LogicalName>Frameworks/GTMSessionFetcher.framework/GTMSessionFetcher.xcprivacy</LogicalName>
    </BundleResource>
    <BundleResource Include="PrivacyManifest\leveldb.xcprivacy" >
      <LogicalName>Frameworks/leveldb.framework/leveldb.xcprivacy</LogicalName>
    </BundleResource>
    <BundleResource Include="PrivacyManifest\nanopb.xcprivacy">
      <LogicalName>Frameworks/nanopb.framework/nanopb.xcprivacy</LogicalName>
    </BundleResource>
    <BundleResource Include="PrivacyManifest\Protobuf.xcprivacy" >
      <LogicalName>Frameworks/Protobuf.framework/Protobuf.xcprivacy</LogicalName>
    </BundleResource>
    <BundleResource Include="PrivacyManifest\Privacyinfo.xcprivacy" />
```

Updated all the Firebase.nuget files to the latest version.
Now i am stuck and can't publish a new version.

Is there anything i can try.
I know Xamarin is no longer maintained, but the change from Xamarin to MAUI takes longer as expected and there are many new bugs with MAUI and missing nugets.

**Comment by rolfbjarne** [comment]
> I also added all the Privacyinfo files directly from the Firebase Repo. But none of them worked.

My guess is that the \*.xcprivacy files for some reason didn't make it into the app bundle.

The .ipa you upload to the App Store is just a zip file - you can inspect it using any unzip tool (might have to change the extension) - and then see if the \*.xcprivacy files are where they should be.
