### ISSUE TITLE
Derived Class Type is lost on real iOS device, but not on iOS simulator

### ISSUE THREAD

**Issue by markusbeermann** [xamarin/xamarin-macios#19999]
### Description
I am working on a binding project for our own Objective-C library. In the Objective-C API, we use specific types like `PIXBarcodeLeserResult` that derive from a common base type `PIXLeserResult`. 
After running `sharpie` and manual cleanup, the `ApiDefinition.cs` contains the following:
```    
    // @interface PIXLeserResult : NSObject
    [Protocol]
    [BaseType (typeof(NSObject))]
    [DisableDefaultCtor]
    interface PIXLeserResult
    {
        ...
    }
    ...
    // @interface PIXBarcodeLeserResult : PIXLeserResult
    [BaseType (typeof(PIXLeserResult))]
    [DisableDefaultCtor]
    [Protocol]
    interface PIXBarcodeLeserResult
    {
        ...
    }
    ...
```

So I can see that `sharpie` is picking up the class hierarchy well. In my test project for this binding, I have the following code:
```
public override void DidGetResults(PIXLeserResult[] leserResults)
{
    foreach (var leserResult in leserResults)
    {
        if (leserResult is PIXBarcodeLeserResult barcodeLeserResult)
        {
            Console.WriteLine("Received Barcode Result");
            ...
        } else {
            Console.WriteLine("Received Mystery Result");
        }
        ...
```

### Expected Behavior

same behavior on iOS simulator and iOS real device: to see *Received Barcode Result* on the console.

### Actual Behavior

On an iOS simulator, I see *Received Barcode Result* on the console.
On an iOS real device, I see *Received Mystery Result* on the console.

### Environment

iOS 17.2
net7.0-ios
VisualStudio for Mac 17.6.8
sharpie 3.5.73

### Details

I checked all files of the project(s): there is no configured differentiation (in terms of `Condition=""`) between simulator and device. 

The project hierarchy is the following:
1.) The .xcframework is wrapped in a Xamarin Wrapper Library project and consists merely of the xcframework and the output of `sharpie`: ApiDefinition.cs, Constants.cs, StructsAndEnums.cs. Output is a `.dll`
2.) The iOS-`.dll` as well as its Android counter part are included into a .NET MAUI wrapper library project. It is using `IPropertyMapper` and `CommandMapper` to achieve platform independence. Output is a `.dll`. It is in this platform specific ViewHandler class where the unexpected behavior occurs.
3.) The `.dll`s are collected into a `.nuget`. This is going to be the product to be shipped.
4.) The `.nuget` is used in a MAUI test App project for Android and iOS. Which is mostly doing what it is supposed to be doing! Just not on a real iOS device.

Where would I even start to look into details? Any help much appreciated!

**Comment by rolfbjarne** [comment]
What's the type you're actually getting?

In other words, what does this print:

```cs
Console.WriteLine($"Received Result: {leserResult.GetType ()}");
```

**Comment by markusbeermann** [comment]
On iPhone Simulator, it is a `PIXBarcodeLeserResult`.
On iPhone Device , it is a `PIXLeserResult`.

**Comment by markusbeermann** [comment]
I added a short description of the project hierarchy. Which admittedly, is not quite flat. Suggestions are very welcome

**Comment by rolfbjarne** [comment]
Can you try printing the Objective-C type as well?


```cs
Console.WriteLine($"Received Result: {leserResult.GetType ()} Objective-C Type: {leserResult.Class.Name}");
```

**Comment by markusbeermann** [comment]
Absolutely!
On Simulator: `Received Result: PixometerSDK_IOS.PIXBarcodeLeserResult Objective-C Type: PIXBarcodeLeserResult`
On a Device: `Received Result: PixometerSDK_IOS.PIXLeserResult Objective-C Type: PIXBarcodeLeserResult`

So glad you are looking into this!
So this could be used to determine the right class, then! Iff I can do the cast to the derived c# class without crashing

**Comment by rolfbjarne** [comment]
Hm, this is getting interesting!

New stuff to try:

1. Please enable the static registrar in the simulator, and see if it makes it behave like a device, by adding this to your csproj:

```xml
<PropertyGroup>
    <Registrar>static</Registrar>
</PropertyGroup>
```

2. If the first point doesn't change anything, then enable the linker in the simulator, and see if that makes the simulator break:

```xml
<PropertyGroup>
    <MtouchLink>SdkOnly</MtouchLink>
</PropertyGroup>
```

**Comment by markusbeermann** [comment]
Just to be sure
1.) I have a csproj merely containing the xcframework and the output of sharpie and 
2.) I have another csproj using the resulting dll that contains actual code. This is where I put the `Console.WriteLine()`s 

The "new stuff to try" should go into the first, right? Or maybe both?

**Comment by rolfbjarne** [comment]
The Registar=static and MtouchLink=SdkOnly properties should go in the executable project (so the MAUI project).

**Comment by markusbeermann** [comment]
No, this doesnt change anything. I tried each individually and both. In all cases: Simulator produces the derived class type, device just the base type.

**Comment by markusbeermann** [comment]
Should I move forward to .Net8 first? See if the situation is the same there?

**Comment by markusbeermann** [comment]
Ah, now I broke the simulator!
I added the `<Registrar>static</Registrar>` property to the MAUI app project **and** the MAUI handler library project and got the `Received Result: PixometerSDK_IOS.PIXLeserResult Objective-C Type: PIXBarcodeLeserResult` also on the simulator!

**Comment by markusbeermann** [comment]
I need to catch up on a few other things first. Meaning:
1. I may be able to provide a private-to-you test project. But it is going to take a few weeks :-/
2. Would you have a suggestion for a quick workaround?

**Comment by rolfbjarne** [comment]
> 2\. Would you have a suggestion for a quick workaround?

If you post your entire `ApiDefinition.cs`, I may see something obvious you can try to change.
