### ISSUE TITLE
iOS binding library for .NET MAUI Not Working

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#20024]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/iOS-binding-library-for-NET-MAUI-Not-Wo/10528911)._

---
Same Question I had uploaded on Stackoverflow https://stackoverflow.com/questions/77512199/ios-binding-library-for-net-maui

Sample code : https://github.com/Bohdandn/MAUI.WebRTC.Demo

I have a .NET MAUI app which needs to use native iOS and Android libraries. I created the Android binding library without any issue.

When trying to create the iOS binding library, However, after the binding library project to MAUI App, I found that the project structure is a bit different than Xamarin.Forms: There is no "Native Library" option under Frameworks (net8.0-ios).

Thus after some R&D, I had manually copy and paste some code in MAUI Proj file. Screen shot attached.

After all this affords, My Code works fine in MAC Machine But iOS project doesnot work in Windows Environments.

Please someone guide which addition configuration/code I have to write to resolve this issue? Any help is greatly appreciated! I use Visual Studio 2022 Latest update Nov-2023.

Some Screen shots attached as reference.

![image.png](https://aka.ms/dc/image?name=B473c88b32bc74343b70d210ce3f20e68638368573430004280_20231129-175219-image.png&tid=473c88b32bc74343b70d210ce3f20e68638368573430004280)

![image.png](https://aka.ms/dc/image?name=B18c901520d9a437098966b2b5cdcc6b7638368573684828816_20231129-175245-image.png&tid=18c901520d9a437098966b2b5cdcc6b7638368573684828816)

![image.png](https://aka.ms/dc/image?name=Be52cc44482f247568a1338dccaa8b546638368573823991650_20231129-175259-image.png&tid=e52cc44482f247568a1338dccaa8b546638368573823991650)

---
#### Feedback Bot on 11/29/2023, 07:13 PM: 

(private comment, text removed)
#### Kapil Dave on 12/11/2023, 05:13 AM: 

(private comment, text removed)
#### Rolf Kvinge [MSFT] on 12/22/2023, 06:05 AM: 

(private comment, text removed)
#### Kapil Dave on 12/25/2023, 02:30 PM: 

(private comment, text removed)
#### Rolf Kvinge [MSFT] on 1/2/2024, 04:10 AM: 

(private comment, text removed)
#### Kapil Dave on 1/4/2024, 03:53 AM: 

(private comment, text removed)
#### Rolf Kvinge [MSFT] on 1/16/2024, 02:54 AM: 

(private comment, text removed)
#### Kapil Dave on 1/18/2024, 03:55 AM: 

(private comment, text removed)
#### Kapil Dave on 1/18/2024, 03:56 AM: 

(private comment, text removed)
#### Kapil Dave on 1/26/2024, 02:37 AM: 

(private comment, text removed)
#### Rolf Kvinge [MSFT] on 1/28/2024, 11:03 PM: 

(private comment, text removed)
#### Kapil Dave on 1/31/2024, 10:54 AM: 

(private comment, text removed)

---
#### Kapil Dave solved on 12/4/2023, 08:43 AM, 0 votes: 

<p>Hello</p>
<p>Any update on above question ?</p>

**Comment by rolfbjarne** [comment]
Yes, I've tried this in the specified environment.

Please provide the exact test solution you're using so that we can avoid + a binary build log (as described here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) in order to ensure we're testing the same thing.
