### ISSUE TITLE
.NET 8 iOS binding to `NSString` returns `null`

### ISSUE THREAD

**Issue by akravch** [xamarin/xamarin-macios#20061]
### Steps to Reproduce

1. Get a static `.a` library that has an `NSString` field in code: `NSString *Foo = @"Bar";`.
2. Create an iOS binding project that binds to the static lib and to the field:
   
   ```c#
    [Static]
    interface Constants
    {
        // extern NSString * Foo;
        [Field("Foo", "__Internal")]
        NSString Foo { get; }
    }
   ```
4. Create a .NET 8 iOS project that would reference the binding project.
5. Log `Constants.Foo`.

### Expected Behavior
`Constants.Foo` returns `"Bar"`.

### Actual Behavior
`Constants.Foo` returns `null`.

If we change the target framework of the consumer project from .NET 8 to .NET 7, `"Bar"` is returned as expected. Also, from what I can see, it doesn't matter if the binding project is .NET 7 or .NET 8.

### Environment

.NET 8.0.101
iOS workload 17.2.8004/8.0.100
XCode 15.2
iOS Simulator with iOS 17.2
macOS Sonoma 14.3
Apple Silicon M1

### Build Logs

[log.binlog.zip](https://github.com/xamarin/xamarin-macios/files/14208108/log.binlog.zip)

### Example Project

https://github.com/akravch/IosNet8Binding

I bind to https://github.com/microsoft/plcrashreporter/releases/tag/1.11.1 and log [`PLCrashReporterException`](https://github.com/microsoft/plcrashreporter/blob/c071a07986a527d961383558e0604a456fb64b92/Source/CrashReporter.m#L35) field.

I chose the PLCrashReporter library simply because it was the first thing that came to my mind I could find already compiled, but the behavior is the same regardless of the library.

**Comment by akravch** [comment]
> I can reproduce this.
> 
> As a workaround you can add this to your consuming csproj:
> 
> ```
> <PropertyGroup>
>     <_ExportSymbolsExplicitly>false</_ExportSymbolsExplicitly>
> </PropertyGroup>
> ```

Apparently it only helps with the simulator build. When I deploy the app the a real device, those fields remain null. It may be a different issue though, because in this case switching to .NET 7 doesn't help either.

Any thoughts on a workarounds that would work for a device?

**Comment by rolfbjarne** [comment]
Try adding the following to your csproj:


```xml
<PropertyGroup>
    <_ExportSymbolsExplicitly>false</_ExportSymbolsExplicitly>
    <NoSymbolStrip>true</NoSymbolStrip>
</PropertyGroup>
<ItemGroup>
    <_MainLinkerFlags Include="-u" />
    <_MainLinkerFlags Include="_PLCrashReporterException" />
</ItemGroup>
```
