### ISSUE TITLE
UIScrollView.ScrollIndicatorInsets not correctly annotated as deprecated

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#20083]
### Steps to Reproduce

`new UIScrollView().ScrollIndicatorInsets = new UIEdgeInsets(0, 0, 0, 0);
`

### Expected Behavior
Usage of [UIScrollView.ScrollIndicatorInsets](https://developer.apple.com/documentation/uikit/uiscrollview/1619427-scrollindicatorinsets) is being marked as deprecated / obsolete in the IDE

### Actual Behavior
No such warning

### Environment
.NET 8
VS for Mac
Rider IDE

**Comment by rolfbjarne** [comment]
Actually only the getter is deprecated, the setter isn't.

From Apple's headers:

```objective-c
@property(nonatomic)         UIEdgeInsets                 scrollIndicatorInsets; // use the setter only, as a convenience for setting both verticalScrollIndicatorInsets and horizontalScrollIndicatorInsets to the same value. if those properties have been set to different values, the return value of this getter (deprecated) is undefined.
- (UIEdgeInsets)scrollIndicatorInsets API_DEPRECATED("The scrollIndicatorInsets getter is deprecated, use the verticalScrollIndicatorInsets and horizontalScrollIndicatorInsets getters instead.", ios(2.0, 13.0), tvos(9.0, 13.0)) API_UNAVAILABLE(visionos);
```

Does the getter show a deprecation warning for you?

**Comment by tipa** [comment]
The getter shows the deprecation warning. When trying in Swift/XCode also only the getter shows the deprecation warning. So it appears to work as intended. Apologies.
