### ISSUE TITLE
[iOS/Catalyst] error: Failed to load AOT module 'System.Private.CoreLib'

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-macios#20112]
### Steps to Reproduce

1. Install .NET SDK 8.0.100
1. Build a MAUI app, using the CLI
2. Debug the app
1. Make sure to not clean the app's bin/obj 
3. Install .NET SDK 8.0.200
4. Build and debug the app (no rebuild)

### Expected Behavior

The app starts

### Actual Behavior

```
error: Failed to load AOT module 'System.Private.CoreLib' while running in aot-only mode: doesn't match assembly.
```

(Actual stack trace got lost by the original user)

### Environment

macOS 13, .NET 8.0.100 and 8.0.200

### Build Logs

Unavailable at this time, but reproducing _may_ be straightforward.

### Workaround

Clean the bin/obj folders.

**Comment by dalexsoto** [comment]
Probably related https://github.com/dotnet/maui/issues/20600

**Comment by rolfbjarne** [comment]
Closing as dup of https://github.com/dotnet/sdk/issues/38769.

**Comment by jeromelaban** [comment]
@rolfbjarne just to make a precision around the installed version, here's what was installed when 8.0.200 was run: 

![image](https://github.com/xamarin/xamarin-macios/assets/5839577/ba1c0442-602c-4609-baae-ead54524787a)

Which I believe are the right ones (at least they match what VS windows is installing), as they were installed through a rollback file.

I would tend to think that this issue is rather a cache issue, where the bin/obj make a copy of some of the runtime files which are not refreshed when the workloads are updated.

**Comment by rolfbjarne** [comment]
OK, that makes sense.

**Comment by rolfbjarne** [comment]
> reproducing _may_ be straightforward.

It wasn't, I couldn't reproduce with a simple test project.

This may depend on the code in a project and which references it has :/

I certainly believe you when you say there's an issue here, but without a way to reproduce it (or at least see exactly what's happening in the build - a binlog might have enough information to understand what's happening), there's unfortunately not much we can do about it, so I'll mark this as needing a test case.

**Comment by jeromelaban** [comment]
@rolfbjarne Agreed, I don't see how you may be able to fix this without a repro, I mentioned it as it may be related to something you knew about. I don't have a way to reproduce from the original repo, I do not have access to it either.

Thanks for the update!

**Comment by rolfbjarne** [comment]
> I get this 100% of the time when our app launches on iOS12 built under .NET 7.
> 
> Same app runs fine on iOS13+. Not sure if it could be related. Will attempt to get more logs & details

That's probably unrelated, so please file a new issue with your logs & details to avoid making this one confusing. It's much easier to merge them later on if it turns out to be the same problem!

**Comment by Ashishkumar5699** [comment]
Hi I found the same issue on iOS 18.5, macOS26
after delete bin obj and rebuild the project it works fine for me

**Comment by ivmirx** [comment]
Yup, was running into the crash below for Release mode on iOS simulator 18.5, but cleaning bin/obj + removing the app from the simulator (just in case) fixed it

	=================================================================
		Native Crash Reporting
	=================================================================
	Got a SIGABRT while executing native code. This usually indicates
	a fatal error in the mono runtime or one of the native libraries 
	used by your application.
	=================================================================

	=================================================================
		Native stacktrace:
	=================================================================
	…
	=================================================================
		Managed Stacktrace:
	=================================================================
		  at <unknown> <0xffffffff>
	=================================================================
	2025-08-04 22:30:42.022880-0400 iOS[6490:117424377] error: Failed to load AOT module 'Nito.AsyncEx.Tasks' while running in aot-only mode because a dependency cannot be found or it is out of date.
