### ISSUE TITLE
"Codesign exited with code 1" issue when try to build an iOS app using visual studio 2022 for mac, Rider and VS Code

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#20113]
_From @mmuresan on Mon, 12 Feb 2024 19:57:51 GMT_

### Description

I am running Visual Studio for Mac, Rider and VS Code on an M2 Mac laptop.
The Maui application I have is not building, when selecting an attached iPad and then build.
The error I get is "Codesign exited with code 1"
This is NOT tooling related, as I get exactly the same error building from Visual Studio for Mac, Rider and VS Code.
I saw in the past multiple people reporting this bug, but they were dismissed and redirected to VS for Mac team and this is definitely not related to any IDE we are using.
This is not happening with newly created applications.

### Steps to Reproduce

Unfortunately, the application is very complex and the only thing that I can produce is a build log, or anything that the team might need to be able to unblock this.

### Version with bug

8.0.6

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

iOS 15

### Did you find any workaround?

I tried quite a lot of things and no workaround yet.

_Copied from original issue dotnet/maui#20530_

**Comment by rolfbjarne** [comment]
_From @drasticactions on Tue, 13 Feb 2024 01:56:32 GMT_

This is a tooling issue. This repo is for the MAUI UI project and it doesn't control the bundling and deployment of applications to devices. That's handled by the .NET SDK and/or IDE tooling. Whatever issue you are hitting is, most likely, not something that can be fixed within this repo. That's why they get redirected elsewhere, so teams with more knowledge of it can address it and help.

Here are some steps to help debug this further:

- Try building an iOS app that doesn't use the MAUI UI framework (`dotnet new ios`). Can you build and deploy that?
- Try building a new template MAUI app, does that deploy?
- Can you deploy an app with Xcode to that device? Just to make sure you can deploy at all.

@rolfbjarne Would you know of other ways to debug this?

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Tue, 13 Feb 2024 06:49:52 GMT_

The first step would be to get a build log, preferrably a binlog (https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs). The codesigning task will output more information than just `"Codesign exited with code 1"`, you can inspect the binlog to see this. Alternatively you can upload it here and we can have a look at it.

**Comment by rolfbjarne** [comment]
_From @mmuresan on Tue, 13 Feb 2024 12:18:52 GMT_

To answer to all of your questions/suggestions, on the same Mac M2 laptop:
"Try building an iOS app that doesn't use the MAUI UI framework (dotnet new ios). Can you build and deploy that?"
- it works with the old Xamarin app (the one I have converted to Maui), build and deploy to Simulator and iPad
"Try building a new template MAUI app, does that deploy?"
- I can build and deploy a new Maui app, both on Simulator and on iPad
"Can you deploy an app with Xcode to that device? Just to make sure you can deploy at all."
- any app I create with XCode it builds and gets deployed to iPad and Simulator

This particular error is strictly related to the upgraded Maui app from Xamarin.

Just to reiterate, I get exactly the same error when I use any of these tools, installed on my Mac:
- Visual Studio for Mac
- Rider
- VS Code
This is the reason I think it is really not likely tooling related, but some setting in the Maui app that makes this happening.

I can create and deploy an Android app from the same Solution/set of projects, from both Mac and Windows development machines, so it is not the app/libraries, but some settings inside the app that makes the building going sideways.

**Comment by rolfbjarne** [comment]
@mirceamuresanse I've seen something like this before, but I don't think we ever figured out what the problem was before it went away for the customer in question, so I don't know what's happening.

So can you provide the following to try to track:

1. A complete list of the files in the app bundle. You can do this by executing something like this from a terminal:

    ```shell
    ls -laR /Users/mirceamuresan/Documents/SEMaui/SE.Geospatial.Mobile.Viewer/SE.Geospatial.Mobile.Viewer/bin/Debug/net8.0-ios/ios-arm64/SE.Geospatial.Mobile.Viewer.app > filelist.txt
    ```

    and then attaching the `filelist.txt` file here.

2. Your csproj (all of them if you have multiple projects in the solution).

**Comment by mirceamuresanse** [comment]
[filelist.txt](https://github.com/xamarin/xamarin-macios/files/14313251/filelist.txt)

Here it is.
There is only one main Maui project in my solution. All other are project dependencies for the main project.

**Comment by rolfbjarne** [comment]
@mirceamuresanse I see you have a `Resources/Images/moveicon.png` file in the app bundle, can you try removing that png file from your csproj to see if that fixes it? IIRC having a `Resources` subfolder in the app bundle can cause signing trouble.

**Comment by mmuresan** [comment]
Good news. After removing the MoveIcon from the project resources and changed all the images in the Resources\Images folder to Maui Image, Embedded Resources, the app is finally compiling. No more Codesigning errors.

So apparently, as rule of thumb, for iOS ONLY rules:
- no embedded resources of type file, image and so on, in the project Properties folder
- no image should be set as EmbeddedResource in the Resources\Images folder

This is weird, and definitely a bug, as it works fine in Windows and Android platforms.

I'm not sure which Microsoft team should this bug be addressed by, as I got so dizzy already getting moved from one team to another :-)

**Comment by rolfbjarne** [comment]
That's great! I'll close this then.

FWIW I've filed an issue to see if we can at least show a better error message here (https://github.com/xamarin/xamarin-macios/issues/20135).

**Comment by jay-intercake** [comment]
I recently moved my SQLite file from the Raw folder with no compile type to EmbeddedResource for Android and saw no issues there and felt that was an elegant solution. when I tried this on iOS I started seeing this issue. What is the best way to load an SQLite file for MAUI that works well with both platforms?
