### ISSUE TITLE
Detect the presence of the "Resources" folder when signing and show an helpful error.

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#20135]
If an iOS or tvOS app contains a `Resources` folder, codesigning fails with a very unhelpful message:

```
  Tool /usr/bin/codesign execution finished (exit code = 1).

  bin/Release/net8.0-ios/ios-arm64/SomeApp.app: code object is not signed at all
  In subcomponent: bin/Release/net8.0-ios/ios-arm64/SomeApp.app/System.Security.Cryptography.aotdata.arm64
```

And this causes a lot of confusion (ref: https://github.com/dotnet/maui/issues/20640).

We should detect the presence of a `Resources` folder before trying to sign, and show an error (we should probably allow the user to opt out of the error in case we get something wrong or Apple changes their logic at some point).

References:

* https://github.com/xamarin/xamarin-macios/issues/20113
* https://github.com/xamarin/xamarin-macios/issues/20555

**Comment by anupniit** [comment]
I am getting same issue. I have tried all soloutions provided but no luck. I really dont know why this is happening. I moved to MAUI for easyness of coading. Now its getting nightmare.

**Comment by rolfbjarne** [comment]
> Warning: unable to build chain to self-signed root for signer

This might help: https://blog.verslu.is/app-publishing/unable-to-build-chain-for-self-signed-root/
