### ISSUE TITLE
using C/C++ library for iOS in maui project

### ISSUE THREAD

**Issue by jfversluis** [xamarin/xamarin-macios#20136]
---
**Issue moved from dotnet/maui#20688**
- Please respond to @CherryBu.

---

_From @CherryBu on Monday, February 19, 2024 7:45:22 AM_

I was able to use a (.a) library from my xamarin project. There ara many .a library in lib folder,
i used to add these .a library this way in the iOS project .csproj

![1708328063506](https://github.com/dotnet/maui/assets/43232870/ae03008c-ba6e-4d7e-84ac-697d9f2d0f03)

```xml
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhone' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\iPhone\Debug</OutputPath>
		<DefineConstants>DEBUG</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
		<MtouchArch>ARM64</MtouchArch>
		<CodesignKey>xxxxxx</CodesignKey>
		<MtouchDebug>true</MtouchDebug>
		<CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
		<MtouchLink>None</MtouchLink>
		<MtouchInterpreter>-all</MtouchInterpreter>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<MtouchExtraArgs>-cxx -gcc_flags "-L${ProjectDir}/lib -L${ProjectDir}/lib/autofreeze -L${ProjectDir}/lib/qtlib -L${ProjectDir}/lib/inviwo -L${ProjectDir}/lib/lung -L${ProjectDir}/lib/mnnnzmrds -L${ProjectDir}/lib/autoef -L${ProjectDir}/lib/autobladder -lbasecontrols -lbeamformer -lbfiodevice -lbuffer -lcolormap -ldatabase -lexamodemodel -lglyphs -lglyphscontrol -lglyphscontrol_interface -lhardware -limt -ljsonreader -llayoutcalculator -llineimagedatacommonunit -llogger -lmeasurementapi -lmeasurementmodel -lmeasurementtool -lmodeglyphswidget -lmodeglyphswidget_interface -lmouseaction -lmuparser -lobtablemodel -lopengladapter -lpatientapi -lserialization -lpreset -lprobeselectionmodel -lpwtrace -lreportmodel -lresource -lsimplestatemachine -lsupport -lsysteminfo -lusapi -luscontextapi -lutilitymodel -lfunctionmodel -labstractdscadapter -ldatatransfer -lrender -linviwoadapter -lqios -lQt5GraphicsSupport -lQt5FontDatabaseSupport -lQt5ClipboardSupport -lqtlibpng -lQt5OpenGL -lqtfreetype -lQt5Script -lQt5Xml -lqtharfbuzz -lqtpcre2 -lQt5Core -lQt5Gui -lQt5Widgets -lQt5Sql -lQt5Network -lqsqlite -lqgif -lqico -lqtga -lqicns -lqjpeg -lopencv_world490 -lqtiff -lqwbmp -lqwebp -lqmacjp2 -lqmacheif -lqgenericbearer -lGLEW -lIrrXML -lchisonultrasoundimageprocess -lfmt -linviwo-core -linviwo-module-base -linviwo-module-chisonus -linviwo-module-glfm -linviwo-module-opengl -lticpp -ladminmodel -lpline -lbline -lnzmrdv2 -llvsec -lautobladder -lautofreeze -lchengine -lmedia -lqtaudio_coreaudio -lQt5Multimedia -Wall  -Wno-unused-label -Wunused-function -dead_strip -Wl, -force_load ${ProjectDir}/lib/libutilitymodel.a   ${ProjectDir}/lib/libmeasurementapi.a ${ProjectDir}/lib/libpatientapi.a ${ProjectDir}/lib/libusapi.a ${ProjectDir}/lib/libuscontextapi.a ${ProjectDir}/lib/libexamodemodel.a ${ProjectDir}/lib/libbasecontrols.a ${ProjectDir}/lib/libbeamformer.a ${ProjectDir}/lib/libbfiodevice.a ${ProjectDir}/lib/libcolormap.a ${ProjectDir}/lib/libdatabase.a ${ProjectDir}/lib/libglyphs.a ${ProjectDir}/lib/libglyphscontrol_interface.a ${ProjectDir}/lib/libglyphscontrol.a ${ProjectDir}/lib/libhardware.a ${ProjectDir}/lib/libimt.a ${ProjectDir}/lib/libjsonreader.a ${ProjectDir}/lib/liblayoutcalculator.a ${ProjectDir}/lib/liblogger.a ${ProjectDir}/lib/libmeasurementmodel.a ${ProjectDir}/lib/libmeasurementtool.a ${ProjectDir}/lib/libmodeglyphswidget_interface.a ${ProjectDir}/lib/libmodeglyphswidget.a ${ProjectDir}/lib/libmouseaction.a ${ProjectDir}/lib/libmuparser.a ${ProjectDir}/lib/libobtablemodel.a ${ProjectDir}/lib/libpwtrace.a ${ProjectDir}/lib/libreportmodel.a ${ProjectDir}/lib/libresource.a ${ProjectDir}/lib/libsimplestatemachine.a ${ProjectDir}/lib/libsupport.a ${ProjectDir}/lib/libsysteminfo.a ${ProjectDir}/lib/libbuffer.a ${ProjectDir}/lib/liblineimagedatacommonunit.a ${ProjectDir}/lib/libopengladapter.a ${ProjectDir}/lib/libpreset.a ${ProjectDir}/lib/libprobeselectionmodel.a ${ProjectDir}/lib/libabstractdscadapter.a ${ProjectDir}/lib/libdatatransfer.a  ${ProjectDir}/lib/liblicensetool.a ${ProjectDir}/lib/librender.a ${ProjectDir}/lib/libinviwoadapter.a  ${ProjectDir}/lib/libmedia.a ${ProjectDir}/lib/qtlib/libqios.a ${ProjectDir}/lib/qtlib/libQt5GraphicsSupport.a ${ProjectDir}/lib/qtlib/libQt5FontDatabaseSupport.a ${ProjectDir}/lib/qtlib/libQt5ClipboardSupport.a ${ProjectDir}/lib/qtlib/libqtlibpng.a ${ProjectDir}/lib/qtlib/libQt5OpenGL.a ${ProjectDir}/lib/qtlib/libqtfreetype.a ${ProjectDir}/lib/qtlib/libQt5Script.a ${ProjectDir}/lib/qtlib/libQt5Xml.a ${ProjectDir}/lib/qtlib/libqtharfbuzz.a ${ProjectDir}/lib/qtlib/libqtpcre2.a ${ProjectDir}/lib/qtlib/libQt5Core.a ${ProjectDir}/lib/qtlib/libQt5Gui.a ${ProjectDir}/lib/qtlib/libQt5Widgets.a ${ProjectDir}/lib/qtlib/libQt5Sql.a ${ProjectDir}/lib/qtlib/libQt5Network.a  ${ProjectDir}/lib/qtlib/libqsqlite.a ${ProjectDir}/lib/qtlib/libqgif.a ${ProjectDir}/lib/qtlib/libqico.a ${ProjectDir}/lib/qtlib/libqtga.a ${ProjectDir}/lib/qtlib/libqicns.a ${ProjectDir}/lib/qtlib/libqtiff.a ${ProjectDir}/lib/qtlib/libqwbmp.a ${ProjectDir}/lib/qtlib/libqwebp.a ${ProjectDir}/lib/qtlib/libqmacjp2.a ${ProjectDir}/lib/qtlib/libqmacheif.a ${ProjectDir}/lib/qtlib/libqgenericbearer.a ${ProjectDir}/lib/qtlib/libqtaudio_coreaudio.a ${ProjectDir}/lib/qtlib/libQt5Multimedia.a ${ProjectDir}/lib/inviwo/libGLEW.a ${ProjectDir}/lib/inviwo/libIrrXML.a ${ProjectDir}/lib/inviwo/libchisonultrasoundimageprocess.a ${ProjectDir}/lib/inviwo/libfmt.a ${ProjectDir}/lib/inviwo/libinviwo-core.a ${ProjectDir}/lib/inviwo/libinviwo-module-base.a ${ProjectDir}/lib/inviwo/libinviwo-module-chisonus.a ${ProjectDir}/lib/inviwo/libinviwo-module-glfm.a ${ProjectDir}/lib/inviwo/libinviwo-module-opengl.a ${ProjectDir}/lib/inviwo/libticpp.a ${ProjectDir}/lib/autofreeze/libautofreeze.a ${ProjectDir}/lib/inviwo/libchengine.a ${ProjectDir}/MNN.framework/MNN ${ProjectDir}/lib/inviwo/libuspipeline.a ${ProjectDir}/lib/libdcmtk.a ${ProjectDir}/lib/libdicomapi.a ${ProjectDir}/lib/libfunctionmodel.a ${ProjectDir}/lib/libadminmodel.a ${ProjectDir}/lib/lung/libpline.a ${ProjectDir}/lib/lung/libbline.a ${ProjectDir}/lib/autoef/liblvsec.a ${ProjectDir}/lib/mnnnzmrds/libnzmrdv2.a ${ProjectDir}/lib/autobladder/libautobladder.a ${ProjectDir}/lib/elementtest/libwafertest.a ${ProjectDir}/lib/qtlib/libqjpeg.a ${ProjectDir}/lib/libopencv_world490.a -framework Accelerate"</MtouchExtraArgs>
		<OptimizePNGs>false</OptimizePNGs>
		<IpaPackageName>sonoeye_version_yyyymmdd</IpaPackageName>
		<MtouchI18n>cjk,mideast,other,rare,west</MtouchI18n>
		<MtouchHttpClientHandler>NSUrlSessionHandler</MtouchHttpClientHandler>
		<CrashReportingDelay>-1</CrashReportingDelay>
		<OnDemandResourcesPrefetchOrder>
		</OnDemandResourcesPrefetchOrder>
		<MtouchHttpClientHandler>NSUrlSessionHandler</MtouchHttpClientHandler>
		<OnDemandResourcesPrefetchOrder>
		</OnDemandResourcesPrefetchOrder>
		<CodesignProvision>xxxxxx</CodesignProvision>
	</PropertyGroup>
```
It works fine in my xamarin.Forms,I try to migrate this project to Maui, I add lib folder that contain some .a library in project-platform-ios folder, but it shows error and cannot compile

![1708328595604](https://github.com/dotnet/maui/assets/43232870/4db1c0ef-eae9-4b22-9be6-a2d8d5f6b22f)

**Comment by jfversluis** [comment]
---
**Issue moved from dotnet/maui#20688**
- Please respond to @drasticactions.

---

_From @drasticactions on Monday, February 19, 2024 8:01:10 AM_

This is the MAUI UI repo and the tooling you're working with is dealing with bindings, which would be under [xamarin/xamarin-macios](https://github.com/xamarin/xamarin-macios).

To the best of my memory `ProjectDir` is for Non-SDK style CSProj files (What previous Xamarin/Xamarin.Forms projects were), and don't work under SDK projects (What .NET Mobile/MAUI projects are now). This is independent of the running frameworks, it's build and SDK differences. 

I think the correct value would now be `MSBuildProjectDirectory`

@rolfbjarne Do you know of other things to help this user?

**Comment by jfversluis** [comment]
---
**Issue moved from dotnet/maui#20688**
- Please respond to @CherryBu.

---

_From @CherryBu on Monday, February 19, 2024 8:28:34 AM_

@drasticactions Thank you for your reply, I replace `ProjectDir ` using `MSBuildProjectDirectory `, and I still have same error message: **clang: error: no such file or directory: '${MSBuildProjectDirectory}/lib/libmeasurementapi.a'**.

**Comment by rolfbjarne** [comment]
> I think the correct value would now be `MSBuildProjectDirectory`

That's partially correct: you also need to use normal parenthesis instead of curly braces.

So this: `$(MSBuildProjectDirectory)` instead of `${ProjectDir}`

@CherryBu can you try and see if that fixes it?

**Comment by CherryBu** [comment]
@rolfbjarne Thank you for your reply, I replace ${ProjectDir} using $(MSBuildProjectDirectory), The project can be compiled successfully, but it cannot be deployed to the device and crashes directly. Please check the following screenshot

![Uploading WechatIMG1113.png…]()


 I don't know what's wrong, please help me look into it

**Comment by rolfbjarne** [comment]
> `@rolfbjarne` Thank you for your reply, I replace `${ProjectDir}` using `$(MSBuildProjectDirectory)`, The project can be compiled successfully, but it cannot be deployed to the device and crashes directly. Please check the following screenshot and code

Crashes how? Is there anything printed to the Application Output? Can you get a [crash report](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#crash-reports) or the [device log](https://support.apple.com/en-in/guide/console/cnsl1012/mac)?

**Comment by CherryBu** [comment]
@rolfbjarne Thank you for your reply, now cannot be deployed to the device and crashes directly, please check the following screenshot about output info

![Uploading 1708415583974.jpg…]()

![Uploading 1708415590130.jpg…]()

**Comment by rolfbjarne** [comment]
> Application 'com.companyname.testpro' terminated (with exit code '' and/or crashing signal '11).

This should produce a crash report, can you see if you got any?

See: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#crash-reports

**Comment by CherryBu** [comment]
@rolfbjarne Please help me to check crash report

[MauiCrashReport.docx](https://github.com/xamarin/xamarin-macios/files/14352700/MauiCrashReport.docx)

**Comment by CherryBu** [comment]
@rolfbjarne I delete this App from iphone device, and want to deploy on iphone device again. But it keeps deploying, and don't install this app on iphone device sucessfully.

**Comment by rolfbjarne** [comment]
This is the significant part of the crash report:

```
Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   CoreFoundation                	       0x18b4585c0 CF_IS_OBJC + 24
1   CoreFoundation                	       0x18b4997c4 CFURLCopyPath + 31
2   FirstMaui                     	       0x10300c840 0x100b10000 + 38783040
3   FirstMaui                     	       0x10300ca60 0x100b10000 + 38783584
4   dyld                          	       0x1adc84944 invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const + 167
```

It seems the native library has an initializer function which crashes.

Can you add this to your csproj, execute again and get an updated crash report? This change will make the stack trace show the actual function names instead of memory addresses for the initializer function:

```xml
<PropertyGroup>
    <NoSymbolStrip>true</NoSymbolStrip>
</PropertyGroup>
```

**Comment by CherryBu** [comment]
@rolfbjarne Thank you for your help,It may be that the library I used before was initialized and some resources were not found, causing this problem.
 I use the libCLib.iOS.a library [downloaded from this sample](https://github.com/lothrop/XamarinNative/tree/master) in maui  ios app, Maui app is created on .net 7.0,  There is no problem compiling and deploying on 17.3, but can not deplying on 14.1, please check seceenshot about error message:

![1708594167171](https://github.com/xamarin/xamarin-macios/assets/43232870/32492a2b-1e95-410c-ac28-e984f80ab22c)

I can not change target ios version in visual studio for mac 2022 17.6.9, it always 16.1

![WechatIMG399](https://github.com/xamarin/xamarin-macios/assets/43232870/a03f5a3b-9cec-4e6d-b588-69c8e9f539bd)

Thanks again for your help.

**Comment by CherryBu** [comment]
@rolfbjarne Thank you for your help, now I can solve this problem.

I right-click this project and choose edit Edit project file, replace this .csproj file using new empty maui project, then I maybe check or uncheck Android Targets or iOS targets or Mac Cat Targets on Target Platforms, please check the following screenshot:

![WechatIMG405](https://github.com/xamarin/xamarin-macios/assets/43232870/35c2e595-a724-4c08-a22f-262fe8e5ad78)
 
Sometimes there are problems with TargetFrameworks，I don’t know why this problem occurs. I always correct it manually.

![1708666135717](https://github.com/xamarin/xamarin-macios/assets/43232870/6553e86d-d500-423a-bd89-89db007b88b9)

Now it can deply on ios  device 14.1, I don't know if this is a bug for Visual Studio for Mac?
  
Thank you again for your help.

**Comment by rolfbjarne** [comment]
> Now it can deply on ios device 14.1, I don't know if this is a bug for Visual Studio for Mac?

Not sure if I understand; do you mean you *can't* deploy?

> But for this case, I think you can close.

Ok.
