### ISSUE TITLE
[AVAudioRecorder] Stopped working after .NET8 migration

### ISSUE THREAD

**Issue by mcocaroUX** [xamarin/xamarin-macios#20159]
We are currently working on a project targeting MacCatalyst, where we developed audio recording functionality by using AVAudioRecorder. But after updating .NET from 7 to 8, it creates an audio file with the correct duration but no sound is recorded on it. I created a repro where you can check this behavior

### Steps to Reproduce

1. Run app
2. Start recording
3. Stop recording

### Expected Behavior
Media player should play recorded audio

### Actual Behavior
Created audio file is mute

### Environment

<details>
<summary>Version information</summary>

```
Version: 1.86.2 (Universal)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:42:13.651Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 23.2.0
```

</details>

### Example Project (If Possible)

[MauiApp1.zip](https://github.com/xamarin/xamarin-macios/files/14350894/MauiApp1.zip)

**Comment by rolfbjarne** [comment]
I converted your test project to .NET 7 and it doesn't work there either. Could you attach a working .NET 7 project as well?
