### ISSUE TITLE
Add ability to setup iOS Alternate App Icons for product page optimization

### ISSUE THREAD

**Issue by Alexandr-Gurinovich** [xamarin/xamarin-macios#20182]
### Steps to Reproduce
iOS Apps support the ability to [set alternate app icons](https://developer.apple.com/documentation/xcode/configuring_your_app_to_use_alternate_app_icons) for [product page optimization](https://developer.apple.com/app-store/product-page-optimization/). 

I followed apple instruction:

1.  added Icon Assets for the Alternate Icons
2.  tried configure the Asset Catalog Compiler by adding entry CFBundleAlternateIcons in info.plist
3.  could not set [Include all app icon assets](https://developer.apple.com/documentation/xcode/configuring-your-app-icon#Change-the-default-app-icon-set) from Xamarin project. `If you don’t select the Include all app icon assets option, Xcode only includes the app icon set you specify in the App Icons Source pop-up menu when it builds your app. `

### Expected Behavior

1. be able to set [Include all app icon assets](https://developer.apple.com/documentation/xcode/configuring-your-app-icon#Change-the-default-app-icon-set) from Xamarin project
2. AlternateIcons appear in build catalog and can be used for [product page optimization](https://developer.apple.com/app-store/product-page-optimization/). 

### Actual Behavior
1. in the resulting build there is no alternate icons and the file obj/iPhone/Release/actool/partial-info.plist does not contain description of Alternate Icons

P.S. When use [instruction for Xamarin.iOS](https://learn.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/alternate-app-icons) the alternate icons are still not recognized by the store. 

### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Professional 2022 for Mac
Version 17.6.1 (build 452)
Installation UUID: ae61014b-58a1-41d5-8cb9-64104b7d65d9
 
Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2
 
Roslyn (Language Service)
5.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa
 
NuGet
Version: 6.4.0.117
 
.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.306/Sdks
SDK Versions:
	8.0.101
	7.0.306
	6.0.412
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks
 
.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	8.0.1
	7.0.9
	6.0.20
 
Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
 
Updater
Version: 11
 
Apple Developer Tools
Xcode: 15.2 22503
Build: 15C500b
 
Xamarin.Mac
Version: 9.3.0.6 Visual Studio Professional
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:35-0400
 
Xamarin.iOS
Version: 16.4.0.6 Visual Studio Professional
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400
 
Xamarin.Android
Version: 13.2.0.6 (Visual Studio Professional)
Commit: xamarin-android/d17-5/a200af1
Android SDK: /Users/alexandergu/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0  (API level 21)
		11.0 (API level 30)
		9.0  (API level 28)
		13.0 (API level 33)
 
SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.3
SDK Build Tools Version: 32.0.0
 
Build Information:
Mono: 6dd9def
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77
 
Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
 
Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
 
Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-07-06 12:51:55 UTC
 
Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-07-06 12:51:55 UTC
 
Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-07-06 12:51:51 UTC
 
Build Information
Release ID: 1706010452
Git revision: 9c61cec4d4c4498378f5878b08459d6fd258659d
Build date: 2023-07-06 12:50:14+00
Build branch: release-17.6
Build lane: release-17.6
 
Operating System
Mac OS X 14.1.1
Darwin 23.1.0 Darwin Kernel Version 23.1.0
    Mon Oct  9 21:27:24 PDT 2023
    root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64
```

</details>

**Comment by rolfbjarne** [comment]
> P.S. When use [instruction for Xamarin.iOS](https://learn.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/alternate-app-icons) the alternate icons are still not recognized by the store.

Can you attach a test project with this solution that doesn't work for you?

**Comment by Alexandr-Gurinovich** [comment]
> > P.S. When use [instruction for Xamarin.iOS](https://learn.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/alternate-app-icons) the alternate icons are still not recognized by the store.
> 
> Can you attach a test project with this solution that doesn't work for you?

Hi, @rolfbjarne. Here is the test project.
[iOSIconsSample.zip](https://github.com/user-attachments/files/16963169/iOSIconsSample.zip)

**Comment by rolfbjarne** [comment]
> > > P.S. When use [instruction for Xamarin.iOS](https://learn.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/alternate-app-icons) the alternate icons are still not recognized by the store.
> > 
> > 
> > Can you attach a test project with this solution that doesn't work for you?
> 
> Hi, @rolfbjarne. Here is the test project. [iOSIconsSample.zip](https://github.com/user-attachments/files/16963169/iOSIconsSample.zip)

There's a bug in the test case, this line:

```cs
if (name == null && supportsAlternateIcons)
```

should be:

```cs
if (name != null && supportsAlternateIcons)
```

And then you get a dialog saying the app icon changed if you run the app.

However, the app icon is the default iOS app icon, not your green one. I believe this is because you need to put the alternate icon in an Asset catalog, and reference it like this from the Info.plist:

```xml
<key>CFBundleIcons</key>
<dict>
    <key>CFBundleAlternateIcons</key>
    <dict>
        <key>AppIcon-Green</key>
        <dict>
            <key>CFBundleIconName</key>
            <string>AppIcon-Green</string>
        </dict>
    </dict>
</dict>
```

Please try this, and if it doesn't work, attach your updated test project.

**Comment by Alexandr-Gurinovich** [comment]
> However, the app icon is the default iOS app icon, not your green one. I believe this is because you need to put the alternate icon in an Asset catalog, and reference it like this from the Info.plist:
> 
> `<key>CFBundleIcons</key>`
> `<dict>`
>  `   <key>CFBundleAlternateIcons</key>`
>  `   <dict>`
>   `      <key>AppIcon-Green</key>`
>   `      <dict>`
>    `         <key>CFBundleIconName</key>`
>    `         <string>AppIcon-Green</string>`
>  `       </dict>`
>  `   </dict>`
> `</dict>`
> Please try this, and if it doesn't work, attach your updated test project. 

Hi @rolfbjarne 
I put assets icon to Assets catalog and updated the Info.plist. Here is an updated sample:
[iOSIconsSample2.zip](https://github.com/user-attachments/files/17260734/iOSIconsSample2.zip)

With this approach alternate icons are not included in Assets.car. You can check it using next commands:
```
cd /iOSIconsSample/obj/Debug/net7.0-ios/ios-arm64/actool/bundle
xcrun --sdk iphoneos assetutil --info Assets.car
```
I've mentioned about this problem in the description - could not set [Include all app icon assets](https://developer.apple.com/documentation/xcode/configuring-your-app-icon#Change-the-default-app-icon-set) from Xamarin project. `If you don’t select the Include all app icon assets option, Xcode only includes the app icon set you specify in the App Icons Source pop-up menu when it builds your app.`
____
When I take a [sample pure xcode project](https://docs-assets.developer.apple.com/published/ba6fbde5c8/ConfiguringYourAppToUseAlternateAppIcons.zip) with alternate icons and build it all icons persist in Assets.car:
[Assets.car.zip](https://github.com/user-attachments/files/17260891/Assets.car.zip)
____

Please check if I'm doing something wrong.

**Comment by rolfbjarne** [comment]
OK, I see what's going on, I'll have a look.

**Comment by Alexandr-Gurinovich** [comment]
hi @rolfbjarne 
Did you get a chance to look into this?

**Comment by rolfbjarne** [comment]
Yes, I'm looking at it, but I haven't figured it out quite yet (still working on it though).

**Comment by rolfbjarne** [comment]
This turned out to be rather complicated to fix - but I'm working on a fix, and it'll be included in a future release (it's not complete yet, so I can't say exactly which release will have the fix).

**Comment by Alexandr-Gurinovich** [comment]
hi @rolfbjarne 
 I’m reaching out to inquire about the progress on the fix. I understand that it can take time and sometimes unexpected challenges can arise.

**Comment by rolfbjarne** [comment]
> hi @rolfbjarne I’m reaching out to inquire about the progress on the fix. I understand that it can take time and sometimes unexpected challenges can arise.

I'm hoping to get this out when we release support for Xcode 16.1, which should come soon after the first .NET 9 release.

**Comment by Alexandr-Gurinovich** [comment]
hi @rolfbjarne  
I see that fix was released with https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-9.0.1xx-xcode16.1-9163. Thanks a lot.
Is there a chance that this fix will also be released for .Net 8?

**Comment by dalexsoto** [comment]
Hello @Alexandr-Gurinovich  unfortunately .NET 8 versions of our SDKs are now in security fixes only mode and it is not getting any new features so in order to get this and Xcode 16.1 support you will need to upgrade to .NET 9.
