### ISSUE TITLE
.NET 8 IOS Native Binding XcFramework (Static library Wrapper) FAILED

### ISSUE THREAD

**Issue by gnibloop** [xamarin/xamarin-macios#20195]
### Steps to Reproduce

1. Create a new Net 8 IOS Application project
2. Add a IOS Native binding project into same solution and add Native reference of a XcFramework library (Attached zebra printer official SDK which wrap static library for different architecture and platform ), modify the Apidefinition.cs and Structandenums.cs according to sharpie result.  Build release.
3. Add reference of above built assembly into main IOS app project and build and run.

### Expected Behavior
The native library should be linked using different platform library and run at all platforms and build configurations.

### Actual Behavior
1, when the Binding project's setting set "<Kind>Static</Kind>",  the project can be built but when running ,  throw exception of " the native class hasn't been loaded".
2, when the Binding project's setting set "<Kind>Framework</Kind>", the project can't build successfully, with a error: "framework not found ios-arm64_x86_64-simulator", Clang++ exit 

### Environment
Microsoft Visual Studio Professional 2022
Version 17.9.0
VisualStudio.17.Release/17.9.0+34607.119
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.9.195.45391
ASP.NET and Web Tools

Automatic Versions   3.1.1
Provides tools for managing assembly versions.

Azure App Service Tools v3.0.0   17.9.195.45391
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.9.195.45391
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.9.0-3.24081.11+989117396f26e5453ff157df610d22ce45b6b0a9
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.9.0 (b3bca6f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.9.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.9.2.2408002+5aec2f1744a2273d3e7157cc4cc1986f87f524d4
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.9.51.1
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.30103.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-3.24081.11+989117396f26e5453ff157df610d22ce45b6b0a9
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.9.0.138 (d17-9@60c2b9b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.9.3.0 (remotes/origin/d17-9@f174974f91)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

### Build Logs

[iOSApp2_Debug_AnyCPU_Build_2024-02-24T18_57_30.6147050-08_00.zip](https://github.com/xamarin/xamarin-macios/files/14395094/iOSApp2_Debug_AnyCPU_Build_2024-02-24T18_57_30.6147050-08_00.zip)

### Example Project (If Possible)

https://github.com/gnibloop/Net8NativeBindingTest

**Comment by rolfbjarne** [comment]
I can reproduce the problem.

The correct Kind value is `Static`, since it's a static library inside the xcframework, but there's a bug preventing things from working.

Can you try adding the following to the test app's csproj to see if it fixes the problem for you?

```xml
<ItemGroup>
  <_CustomLinkFlags Include="-u" />
  <_CustomLinkFlags Include="_OBJC_CLASS_$_NetworkDiscoverer" />
  <_CustomLinkFlags Include="-u" />
  <_CustomLinkFlags Include="_OBJC_CLASS_$_PrinterStatus" />
  <_CustomLinkFlags Include="-u" />
  <_CustomLinkFlags Include="_OBJC_CLASS_$_TcpPrinterConnection" />
  <_CustomLinkFlags Include="-u" />
  <_CustomLinkFlags Include="_OBJC_CLASS_$_ZebraPrinterFactory" />
</ItemGroup>
```

**Comment by rolfbjarne** [comment]
Note to self:

The problem is that `has_linkwith_attributes` is false here:

https://github.com/xamarin/xamarin-macios/blob/69bb4ac1fb4dbea862fdc64aacaf600d850620e5/tools/linker/MonoTouch.Tuner/ListExportedSymbols.cs#L149-L153

The HasLinkWithAttribute property is set here:

https://github.com/xamarin/xamarin-macios/blob/69bb4ac1fb4dbea862fdc64aacaf600d850620e5/tools/common/Assembly.cs#L239

but that's not hit, becuase there's a binding resource package for the assembly, so this code path prevents it:

https://github.com/xamarin/xamarin-macios/blob/69bb4ac1fb4dbea862fdc64aacaf600d850620e5/tools/common/Assembly.cs#L162C21-L162C70

**Comment by gnibloop** [comment]
> I can reproduce the problem.
> 
> The correct Kind value is `Static`, since it's a static library inside the xcframework, but there's a bug preventing things from working.
> 
> Can you try adding the following to the test app's csproj to see if it fixes the problem for you?
> 
> ```
> <ItemGroup>
>   <_CustomLinkFlags Include="-u" />
>   <_CustomLinkFlags Include="_OBJC_CLASS_$_NetworkDiscoverer" />
>   <_CustomLinkFlags Include="-u" />
>   <_CustomLinkFlags Include="_OBJC_CLASS_$_PrinterStatus" />
>   <_CustomLinkFlags Include="-u" />
>   <_CustomLinkFlags Include="_OBJC_CLASS_$_TcpPrinterConnection" />
>   <_CustomLinkFlags Include="-u" />
>   <_CustomLinkFlags Include="_OBJC_CLASS_$_ZebraPrinterFactory" />
> </ItemGroup>
> ```

Hi, Thanks for the help. I currently successfully ran the test program. Since we are upgrading a big project form .Net 7 (built by VS Mac), we are facing a lot of same nativebinding library issues. Are we supposed to put all those exposed interface as the same  format into project ("_OBJ_CLASS_.xxxx")?  Or should we wait for next patch fix this bug? (when will this fix be available?)

**Comment by rolfbjarne** [comment]
> Are we supposed to put all those exposed interface as the same format into project ("_OBJ_CLASS_.xxxx")? Or should we wait for next patch fix this bug? (when will this fix be available?)

I can't say how long it'll take to fix this, so I believe your best approach would be to implement the workaround for all Objective_C interfaces.

**Comment by gnibloop** [comment]
Thanks a lot.
Now i moved to another native library binding project with TRUE xcFramework (not static library wrapper).  The build was failed with error message such as:

error : clang++ exited with code 1:
error : Undefined symbols for architecture arm64:
error :   "_BeginCheckedBlock", referenced from:
error :      -exported_symbol[s_list] command line option
error :   "_BeginCheckedBlockEx", referenced from:
error :      -exported_symbol[s_list] command line option
error :   "_ClosePort", referenced from:

Do i need to create another ticket?  or this can be fixed by the same solution (adding OBJ reference in csproject itemgroups)?

**Comment by rolfbjarne** [comment]
> Do i need to create another ticket? or this can be fixed by the same solution (adding OBJ reference in csproject itemgroups)?

Please create a new issue, it may or may not have the same solution, and in case it doesn't, it'll get very confusing here (it's much easier to merge two separate issues than to split one issue in two later on).

**Comment by ToolmakerSteve** [comment]
> Do i need to create another ticket? or this can be fixed by the same solution (adding OBJ reference in csproject itemgroups)?

Did you create a new ticket? Having the same problem. `.a` static library works in a `Xamarin.iOS` project, but not in a `.Net 8 iOS` project. Similar error messages with undefined symbols starting with `_`.

**Comment by rolfbjarne** [comment]
> > Do i need to create another ticket? or this can be fixed by the same solution (adding OBJ reference in csproject itemgroups)?
> 
> Is this covered by issue #19624? [I think not, since the symptom is different.]
> 
> I am having the same problem. `.a` static library works in a `Xamarin.iOS` project, but not in a `.Net 8 iOS` project. Similar error messages with undefined symbols starting with `_`.

When in doubt, it's always safe to file a new issue :)

It might the be same problem as this issue, but I can't say without a test project I can use to reproduce the problem.

**Comment by cjrvdev** [comment]
@rolfbjarne Sorry to reopen this topic but is this fixed right now or is it only available for .NET 9? Im trying to bind Lottie for iOS but fullbind and not slim-binding. Is this possible and could you point me to a guide on how to do it please? I see a lot of official guides and feels somewhat contradictory

Thanks!

**Comment by rolfbjarne** [comment]
> @rolfbjarne Sorry to reopen this topic but is this fixed right now or is it only available for .NET 9?

We're planning to release this fix in our next service release for .NET 8.

**Comment by cjrvdev** [comment]
We are a bit in a hurry not gonna lie. Wanted to migrate to Net8 (from
Xamarin) but lottie iOS is being a stopper. A full binding was going to be
our salvation, I assumed this would work by now :(

Thanks for the update. Hope to see it hit the market ASAP please 🙏

**Comment by rolfbjarne** [comment]
> We are a bit in a hurry not gonna lie. Wanted to migrate to Net8 (from Xamarin) but lottie iOS is being a stopper. A full binding was going to be our salvation, I assumed this would work by now :(

Good thing the next service release shipped yesterday, just a few hours after my comment :)

So please test, and let us know if it still doesn't work.

**Comment by cjrvdev** [comment]
> > We are a bit in a hurry not gonna lie. Wanted to migrate to Net8 (from Xamarin) but lottie iOS is being a stopper. A full binding was going to be our salvation, I assumed this would work by now :(
> 
> Good thing the next service release shipped yesterday, just a few hours after my comment :)
> 
> So please test, and let us know if it still doesn't work.

Thanks again for the reply! Dont know if I might be looking at the wrong site but I think the latest version is still 8.0.7 (8.0.303) released early July? Do you see something I can't see? 😋
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

**Comment by rolfbjarne** [comment]
> > > We are a bit in a hurry not gonna lie. Wanted to migrate to Net8 (from Xamarin) but lottie iOS is being a stopper. A full binding was going to be our salvation, I assumed this would work by now :(
> > 
> > 
> > Good thing the next service release shipped yesterday, just a few hours after my comment :)
> > So please test, and let us know if it still doesn't work.
> 
> Thanks again for the reply! Dont know if I might be looking at the wrong site but I think the latest version is still 8.0.7 (8.0.303) released early July? Do you see something I can't see? 😋 [dotnet.microsoft.com/en-us/download/dotnet/8.0](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)

Workloads (such as the iOS SDK) are sometimes shipped separately, here are the release notes: https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-8.0.1xx-xcode15.4-8018

**Comment by cjrvdev** [comment]
Did the update as you suggested thanks
On the other side I tried to do full-binding again and no luck. I uploaded the binding project to a repo and I would be really happy if you could give it a quick look

Steps as suggested: generate sharpie files, add them to the project and link the native xcframework to the project.
Error: "Lottie namespace not found" (apidefinition has "using Lottie")

Im pretty much blocked and confused now so if you could give me a hand.. please? 🙃
Repo https://github.com/cjrvdev/Cjrv.Lottie.iOS 

Sharpie command: 
`sharpie bind --sdk=iphoneos17.5 --output="XamarinApiDef" --namespace="Crjv.Lottie.iOS" --scope="/Users/carlosrodriguez/Desktop/charpi/Lottie.xcframework/ios-arm64/Lottie.framework/Headers/" "/Users/carlosrodriguez/Desktop/charpi/Lottie.xcframework/ios-arm64/Lottie.framework/Headers/Lottie-Swift.h"   `

**Comment by rolfbjarne** [comment]
> Did the update as you suggested thanks On the other side I tried to do full-binding again and no luck. I uploaded the binding project to a repo and I would be really happy if you could give it a quick look
> 
> Steps as suggested: generate sharpie files, add them to the project and link the native xcframework to the project. Error: "Lottie namespace not found" (apidefinition has "using Lottie")
> 
> Im pretty much blocked and confused now so if you could give me a hand.. please? 🙃 Repo [cjrvdev/Cjrv.Lottie.iOS](https://github.com/cjrvdev/Cjrv.Lottie.iOS)

Please file a new issue, otherwise things can get really confusing with this one.
