### ISSUE TITLE
MethodName(out IntPtr variableName) send null values for out parameter from the iOS Binding dll in .NET 8

### ISSUE THREAD

**Issue by jfversluis** [xamarin/xamarin-macios#20236]
---
**Issue moved from dotnet/maui#20978**
- Please respond to @ad5742.

---

_From @ad5742 on Monday, March 4, 2024 7:03:42 AM_

### Description

GeList(out IntPtr variableName) send null values for out parameter from the iOS Binding dll in .NET 8 .NET 8 iOS binding library project . Method in ApiDefinition class.

```cs
//iOS Binding Library Project ApiDefinition.cs 
// @required -(RESULT)getList:(NSMutableArray **)availableList; 
[Export("getList:")] Result getList(out IntPtr availableList);
```

in .NET 7 if we call above method in MAUI SAMPLE APP the availableList will received.

```cs
// MAUI app 
//Get avilable List 
NSMutableArray availableList = new NSMutableArray(); 
IntPtr availableHandle = availableList.Handle; 
Result availableListResult = apiInstance.getList(out availableHandle); 
availableList = ObjCRuntime.Runtime.GetNSObject<NSMutableArray>(availableHandle); 
if (availableListResult == Result.Success) 
{ 
System.Diagnostics.Debug.WriteLine("Success " + availableList);
 } 
```

But in .NET 8 if we call above method in MAUI SAMPLE APP the availableList will get Null , but not in .Net 7 (can get availableList ). Any solution for .Net 8 ?.  

### Version with bug

8.0.6 SR1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

iOS

**Comment by rolfbjarne** [comment]
I don't know what can cause this difference between .NET 7 and .NET 8, so we'd need a test project we can use to reproduce this in order to investigate what might be the cause (in this case we'd need both a working .NET 7 project and a failing .NET 8 project).

**Comment by ad5742** [comment]
Our iOS SDK (Objective C) has several API calls which contain double pointer( variable name**) parameter .
Ex:
-(RESULT)getList:(NSMutableArray **)availableList;
-(RESULT)getActiveList:(NSMutableArray **)availableList;
-(RESULT)getStatus:(NSMutableArray **)status;

So, we creating iOS binding library project to create DLL for MAUI.
In iOS Binding Library Project ApiDefinition.cs  we have following C# method for objective C method( -(RESULT)getList:(NSMutableArray **)availableList; )

`//iOS Binding Library Project ApiDefinition.cs 
// @required -(RESULT)getList:(NSMutableArray **)availableList; 
[Export("getList:")] Result getList(out IntPtr availableList);
`
in .NET 7 if we call above method in MAUI SAMPLE APP the availableList will received. But in .NET 8 if we call above method in MAUI SAMPLE APP the availableList will get Null , but not in .Net 7 (can get availableList ). 

`// MAUI app 
//Get avilable List 
NSMutableArray availableList = new NSMutableArray(); 
IntPtr availableHandle = availableList.Handle; 
Result availableListResult = apiInstance.getList(out availableHandle); 
availableList = ObjCRuntime.Runtime.GetNSObject<NSMutableArray>(availableHandle); 
if (availableListResult == Result.Success) 
{ 
System.Diagnostics.Debug.WriteLine("Success " + availableList);
 } `

Any solution for .Net 8 ?

**Comment by rolfbjarne** [comment]
> Any solution for .Net 8 ?

It should work just fine in .NET 8.

Something else is going on, so we need a test project that reproduces the problem in order to diagnose the problem.

**Comment by ad5742** [comment]
Actually this iOS SDK is to get Bluetooth Reader List, Without this Bluetooth readers you can't diagnose the problem. What we can do is we will send another sample iOS binding library project and Maui App which can reproduce above issue.Please give some couple of days. Thanks!

**Comment by ad5742** [comment]
[https://github.com/xamarin/xamarin-macios/issues/20299]
Hi @rolfbjarne  I have attached test project in above link
