### ISSUE TITLE
NET8 iOS build fail - System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by thefex** [xamarin/xamarin-macios#20282]
### Steps to Reproduce
Upgraded one of legacy apps from net7.0-ios into net8.0-ios and now I receive bunch of build errors related to the System.Private.CoreLib.dll
I have UseInterpreter as true in csproj.

I am unable to submit any sample project as this is enterprise app and I dont know how to reproduce issue in isolation

### Expected Behavior
App builds as it used to on net7.0-ios.
### Actual Behavior
Long list of build errors related to the System.Private.CoreLib.dll. App cannot be installed on simulator.

.../net8.0-ios/iossimulator-arm64/nativelibraries/aot-output/x86_64/System.Private.CoreLib.dll.s:63801:7: error: out of range literal value
.word 0x100000010
... as above -> error invalid instruction mnemonic 'br', 'adrp'
### Environment
Xcode 15.1, net8.0.201 runtime

**Comment by rolfbjarne** [comment]
Please provide a binary build log as described here: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs

**Comment by thefex** [comment]
I had to add <RuntimeIdentifier>iossimulator-x64 in csproj and it builds now. Closing issue
