### ISSUE TITLE
MethodName(out IntPtr variableName) send null values for out parameter from the iOS Binding dll in .NET 8

### ISSUE THREAD

**Issue by ad5742** [xamarin/xamarin-macios#20299]
Issue Link : [https://github.com/xamarin/xamarin-macios/issues/20236]
Please refer  "test project"  in the attachment.
[Maui_Net8_Issue.zip](https://github.com/xamarin/xamarin-macios/files/14585180/Maui_Net8_Issue.zip)

This "test project"  will reproduces the problem in .Net 8 .
Note: We follow same steps for .Net 7 . It's working fine in  .Net 7  .

 The attachment  contains following projects:

- TestiOSsdkObjectiveC ( Xcode project for static Library )
- MAUIiOSBindingLibrary (Maui iOS Binding Library Project)
- MauiTestNet8 (Maui Demo App which uses iOS binding dll)

**Comment by rolfbjarne** [comment]
Your binding is wrong, you need to use `ref`, not `out` in the method signature:

```cs
string MethodTestDoublePointer(ref IntPtr nameList);
```

with that change (and the corresponding change when calling the method), the sample project works fine.

**Comment by ad5742** [comment]
@rolfbjarne Thank you. Currently, it's working with .Net 8.
