### ISSUE TITLE
.NET 8 IOS native binding Link Error (can't build for Simulator-Arm64) 

### ISSUE THREAD

**Issue by gnibloop** [xamarin/xamarin-macios#20305]
### Steps to Reproduce

1.   Build Native binding project on CloverRemotePay official's iOS SDK successfully.
2.   Link with  .NET IOS 8 APP (a large project we are now migrating from IOS 7 VS Mac)
3.   Under ios-Simulator (arm64) configuration  build the project, it stopped with error.

NOTE: I can't put the failed project on github for reproduce. I 'll just put the simple IOS project with this specific Native binding library but weirdly it can be built without problem for that simple project.

### Expected Behavior
Built successfully under both simulator and device configuration

### Actual Behavior

Very weird behavior:

The error is like: 

Error	MSB3021	Unable to copy file "G:\dev\PosApp_NET8\iOS.CloverRemotePay\bin\Release\net8.0-ios\iOS.CloverRemotePay.resources\CloverConnector.xcframework\ios-arm64_x86_64-simulator\CloverConnector.framework\Modules\CloverConnector.swiftmodule\x86_64-apple-ios-simulator.private.swiftinterface" to "bin\Debug\net8.0-ios\iossimulator-arm64\iOS.CloverRemotePay.resources\CloverConnector.xcframework\ios-arm64_x86_64-simulator\CloverConnector.framework\Modules\CloverConnector.swiftmodule\x86_64-apple-ios-simulator.private.swiftinterface". Could not find a part of the path 'bin\Debug\net8.0-ios\iossimulator-arm64\iOS.CloverRemotePay.resources\CloverConnector.xcframework\ios-arm64_x86_64-simulator\CloverConnector.framework\Modules\CloverConnector.swiftmodule\x86_64-apple-ios-simulator.private.swiftinterface'.	PosApp.Ios	C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	4967	

1, It can be built successfully for device ( iOS-Arm64) but failed under simulator (ios-simulator-Arm64)
2, It can be built successfully for simulator if it's a simple iOS App (created from standard template , see shared code github link below)
3, looks like copy file to target folder:

 "bin\Debug\net8.0-ios\iossimulator-arm64\iOS.CloverRemotePay.resources\CloverConnector.xcframework\ios-arm64_x86_64-simulator\CloverConnector.framework\Modules\CloverConnector.swiftmodule\x86_64-apple-ios-simulator.private.swiftinterface" 

failed, it's from a batch command inside Microsft.Common.Versions.Target (code below)

    <Copy
        SourceFiles="@(ReferenceCopyLocalPaths)"
        DestinationFiles="@(ReferenceCopyLocalPaths->'$(OutDir)%(DestinationSubDirectory)%(Filename)%(Extension)')"
        SkipUnchangedFiles="$(SkipCopyUnchangedFiles)"
        OverwriteReadOnlyFiles="$(OverwriteReadOnlyFiles)"
        Retries="$(CopyRetryCount)"
        RetryDelayMilliseconds="$(CopyRetryDelayMilliseconds)"
        UseHardlinksIfPossible="$(CreateHardLinksForCopyLocalIfPossible)"
        UseSymboliclinksIfPossible="$(CreateSymbolicLinksForCopyLocalIfPossible)"
        Condition="'$(UseCommonOutputDirectory)' != 'true'"
            >

      <Output TaskParameter="DestinationFiles" ItemName="FileWritesShareable"/>
      <Output TaskParameter="CopiedFiles" ItemName="ReferencesCopiedInThisBuild"/>
      <Output TaskParameter="WroteAtLeastOneFile" PropertyName="WroteAtLeastOneFile"/>

    </Copy>

**** I checked Source file, it exists. 

4, I suspect it's because copy command is too long ? (exceed maximum characters). If so, i have to change the name to work around.

### Environment

<details>
<summary>Version information</summary>

```
Microsoft Visual Studio Professional 2022
Version 17.9.3
VisualStudio.17.Release/17.9.3+34701.34
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.9.199.22661
ASP.NET and Web Tools

Automatic Versions   3.1.1
Provides tools for managing assembly versions.

Azure App Service Tools v3.0.0   17.9.199.22661
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.9.199.22661
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.9.0 (b3bca6f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.9.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.

Razor (ASP.NET Core)   17.9.2.2412004+684740676513b3b208d5bd5b7f8786dab8d287b7
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.9.54.7
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.30103.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.9.0-3.24121.1+a98c90d56455379836dd5c845b35fa932b00cfa3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.9.0-beta.23614.3+a521e1cd420beb56c15faf6836184fadd2b7937a
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.9.0.138 (d17-9@60c2b9b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.9.3.0 (remotes/origin/d17-9@f174974f91)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

```

</details>

### Build Logs

[PosApp.Ios_Debug_AnyCPU_Build_2024-03-13T13_05_52.0241090-07_00.zip](https://github.com/xamarin/xamarin-macios/files/14593438/PosApp.Ios_Debug_AnyCPU_Build_2024-03-13T13_05_52.0241090-07_00.zip)

NOTE: this file above contains two logs under two different configuration (one failed one succeed)

### Example Project (If Possible)

https://github.com/gnibloop/Net8NativeBindingTest

**Comment by rolfbjarne** [comment]
This certainly looks like a problem with max path length.

I have a few questions:

* Do you have long paths enabled in Windows (https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry)?
* Does the project build successfully if you build from the command line on a Mac?

**Comment by gnibloop** [comment]
Hi, @rolfbjarne , I enabled long path reg, the build went through successfully. Thanks for the help.
