### ISSUE TITLE
Compression.CompressionAlgorithm enum missing BROTLI & LZBITMAP values

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#20319]
Compression.CompressionAlgorithm enum is missing [BROTLI](https://developer.apple.com/documentation/compression/compression_algorithm/compression_brotli) + [LZBITMAP](https://developer.apple.com/documentation/compression/compression_algorithm/compression_lzbitmap)

https://github.com/xamarin/xamarin-macios/blob/87953eda87eabdcbf487579ac7d5b441db872c0f/src/Compression/Enums.cs#L9-L15

### Steps to Reproduce

```
using var compressedStream = new MemoryStream();
using (var compressionStream = new CompressionStream(compressedStream, CompressionAlgorithm.Brotli, true))
{
    compressionStream.Write(data);
}
```

### Expected Behavior
Builds and works

### Actual Behavior
Doesn't build

### Workaround
`using (var compressionStream = new CompressionStream(compressedStream, (CompressionAlgorithm)0xb02, true))
`

### Environment
.NET 8

**Comment by rolfbjarne** [comment]
Adding `Brotli` is easy, but `Lzbitmap` is a bit more work, because according to the documentation it only works with the `compression_encode_buffer` and `compression_decode_buffer` functions, which we haven't bound yet.
