### ISSUE TITLE
iOS: Breakpoint not hit in classes containing static fields that are initialized inline

### ISSUE THREAD

**Issue by prollin** [xamarin/xamarin-macios#20315]
### Steps to Reproduce

1. create a new ios project: `dotnet new iOS`
2. in `AppDelegate.cs` add a new field: `private static int foo = 42;`
3. add a breakpoint in `FinishedLaunching()`
4. launch app 

### Expected Behavior

Breakpoint is hit

### Actual Behavior

Breakpoint not hit

### Environment

Visual Studio Code 1.87.2 + .NET MAUI 0.9.7 + C# Dev Kit 1.4.29 

<details>
<summary>Version information</summary>

```
Version: 1.87.2 (Universal)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:21:31.043Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.1.0
```

</details>

<details>
<summary>dotnet --info</summary>
```

.NET SDK:
 Version:           8.0.202
 Commit:            25674bb2f4
 Workload version:  8.0.200-manifests.a7f084b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.202/

.NET workloads installed:
 [ios]
   Installation Source: SDK 8.0.200
   Manifest Version:    17.2.8043/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.ios/17.2.8043/WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 8.0.200
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.7/WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: SDK 8.0.200
   Manifest Version:    34.0.85/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.android/34.0.85/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.3
  Architecture: arm64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  8.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

```
</details>

**Comment by rolfbjarne** [comment]
This issue was moved to microsoft/vscode-dotnettools#1001

**Comment by prollin** [comment]
@rolfbjarne just had a chance to confirm that this also happens in Visual Studio Professional (tested on 17.9.4 as well as 17.10.0 Preview 2.0) with a mac build host so it is not exclusive to VSCode.

This problem seem to be at the core of our inability to properly debug our app on iOS (both simulator and device) since we use static classes/variables extensively. With such a simple repro case, could this be escalated? AFAIK this has been an issue since at least net8 release for us.

**Comment by rolfbjarne** [comment]
I can reproduce, and since it's happening in VS as well, I believe dotnet/runtime is probably a more correct place for this issue.

**Comment by rolfbjarne** [comment]
FWIW I can reproduce the problem.

**Comment by rolfbjarne** [comment]
This issue was moved to dotnet/runtime#100243
