### ISSUE TITLE
Xamarin.Forms App support - update the app store after April 29th with iOS SDK 17? 

### ISSUE THREAD

**Issue by KathirveluM** [xamarin/xamarin-macios#20331]
Hi Team, 

We are getting a message from Apple that it will only allow us to deploy apps with target versions 17.0 after April 29, 2024. but with Visual Studio Mac, we are able to target only version 16.4. Visual Studio Mac is not allowing us to target 17.0 and our app was developed using Xamarin. Forms. 

We received this warning from Apple stating that, ITMS-90725: SDK version issue This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution. **

Is it feasible to publish the Xamarin.Forms app to the App Store after April 29th with version 17.0?

**Comment by rolfbjarne** [comment]
You need to update your Xcode to Xcode 15, and then you'll be able to target version 17 in Visual Studio for Mac.
