### ISSUE TITLE
.NET 8 NuGet of MonoTouch.Dialog

### ISSUE THREAD

**Issue by caz162** [xamarin/xamarin-macios#20380]
Previously there was a idea about moving MonoTouch.Dialog to a nuget package allow it to be used in .Net6 https://github.com/xamarin/xamarin-macios/issues/11941.

This didn't appear to get any traction due to lack of interest from customers. I would like to raise my interest in this, we are migrating a very old Xamarin.iOS app to .Net for iOS (.Net 8). The app relies on MonoTouch.Dialog quite heavily.

It would be great if we could get that nuget package so we do not have to re-write most of the app.

**Comment by dalexsoto** [comment]
Unfortunately is no longer planned at the moment, you can always fork the repo and add it as a submodule https://github.com/migueldeicaza/MonoTouch.Dialog or publish your own version of the NuGet.
