### ISSUE TITLE
Issue binding iOS native library

### ISSUE THREAD

**Issue by MnaishMAUIDeveloper** [xamarin/xamarin-macios#20395]
### Reproducible steps

1- Create a iOS binding project
2- Add the native library and the generated files from Sharpie
3- Create a MAUI test project that references the iOS binding project
4- Build and run the Test project > Following build errors occurs

Getting below error

**/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.4.7141/targets/Xamarin.Shared.Sdk.targets(4,4): Error MSB4028: The "ReadItemsFromFile" task's outputs could not be retrieved from the "Items" parameter. Parameter "includeEscaped" cannot have zero length. (MSB4028)**

**Comment by dalexsoto** [comment]
Hello, I was not able to reproduce the issue, could you please provide us a repro or a [binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#build-logs)? Also having all your [version information](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#version-information) would be handy.

**Comment by MnaishMAUIDeveloper** [comment]
I am sharing build log with you.

[BUILDLog.txt](https://github.com/xamarin/xamarin-macios/files/14881368/BUILDLog.txt)

**Comment by MnaishMAUIDeveloper** [comment]
I am sharing build log and binary log with you.

[BinLog.txt](https://github.com/xamarin/xamarin-macios/files/14881383/BinLog.txt)

[iOSBindingTestApp_Debug_Build_2024-04-05T09_49_43.2527070Z.msbuild.log](https://github.com/xamarin/xamarin-macios/files/14883413/iOSBindingTestApp_Debug_Build_2024-04-05T09_49_43.2527070Z.msbuild.log

[iOSBindingTestApp_Debug_DesignTimeBuild_2024-04-05T10_02_50.9391580Z.log](https://github.com/xamarin/xamarin-macios/files/14883414/iOSBindingTestApp_Debug_DesignTimeBuild_2024-04-05T10_02_50.9391580Z.log)



**Visual studio 2022 MAC(Version 17.6.10 (build 428))**
**iOS binding Library[using for bind native framework]** 

**Version Information**

Visual Studio Community 2022 for Mac
Version 17.6.10 (build 428)
Installation UUID: 038bd4f8-26d8-4a7d-be31-a2f9a136e56b

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.314/Sdks
SDK Versions:
	7.0.314
	7.0.313
	7.0.312
	6.0.420
	6.0.419
	6.0.418
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.17
	7.0.16
	7.0.15
	6.0.28
	6.0.27
	6.0.26

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 15.2 22503
Build: 15C500b

Xamarin.Mac
Not Installed

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2024-03-07 20:35:36 UTC

Xamarin.iOS
Version: 16.4.0.23 Visual Studio Community
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:15:00-0400

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: /Users/manishsingh/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2024-03-07 20:35:42 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2024-03-07 20:35:42 UTC

Build Information
Release ID: 1706100428
Git revision: a5d4aa3648baa4a3f6bff645886bd51ad16c07a7
Build date: 2024-03-07 20:33:40+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 14.1.0
Darwin 23.1.0 Darwin Kernel Version 23.1.0
    Mon Oct  9 21:32:11 PDT 2023
    root:xnu-10002.41.9~7/RELEASE_ARM64_T6030 arm64

Enabled user installed extensions
Log Monitor 0.8
Project System Tools 0.13

**Comment by rolfbjarne** [comment]
I've never seen this error before, and the term "includeEscaped" does not originate from this repository, so I have no idea what could cause this.

Most likely it's related to something with the native library and what Objective-Sharpie produced.

Could you please create a test project we can use to reproduce the problem?

Thanks!
