### ISSUE TITLE
Xamarin iOS Build Errors After Updating Mac to Sonoma and Xcode to 15.3

### ISSUE THREAD

**Issue by ctokunaga-reichert** [xamarin/xamarin-macios#20396]
After upgrading my Mac to Sonoma and Xcode 15.3, my Xamarin iOS app is now failing to build with errors that were not present before the upgrade. Xamarin app fails during build in Visual Studio Mac when Xcode 15.3 and iOS 17.4 are installed. 4 errors are present that are preventing the build. The NewsstandKit issue was referenced in #18606, but the fix does not seem to be working here (fix was working previously when iOS 17 was first released). Code built without issue when Mac was running on Ventura with Xcode 14.3.1. Code will also build without issue from an Azure DevOps pipeline where the VM image is set to macOS-latest. After Mac was updated to Sonoma and Xcode was updated to 15.3 is when builds started to fail. Have tried downgrading Xcode to 15.2 as suggested in #20257, and even as low as 15.0.1 but still get the same errors. 

![image](https://github.com/xamarin/xamarin-macios/assets/92599778/b6237c85-944d-41da-95c8-28797b65e065)

### Steps to Reproduce

1. Upgraded Mac to Sonoma
2. Download and install Xcode 15.3
3. Attempt to build iOS project
4. Build fails

### Expected Behavior
Build succeeds and allows for debugging on iPhone Simulator or connected iPhone device
### Actual Behavior
Build fails
### Environment

<details>
<summary>Version information</summary>

```
Visual Studio Enterprise 2022 for Mac
Version 17.6.10 (build 428)
Installation UUID: 101cdc88-4384-4ebb-b1a4-52b7c153186e

Runtime
.NET 7.0.3 (64-bit)
Architecture: X64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
5.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.314/Sdks
SDK Versions:
	7.0.314
	7.0.312
	7.0.311
	7.0.309
	7.0.307
	7.0.306
	7.0.304
	7.0.203
	7.0.202
	7.0.102
	7.0.100
	6.0.420
	6.0.418
	6.0.417
	6.0.415
	6.0.413
	6.0.412
	6.0.410
	6.0.408
	6.0.407
	6.0.405
	6.0.403
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.17
	7.0.15
	7.0.14
	7.0.12
	7.0.10
	7.0.9
	7.0.7
	7.0.5
	7.0.4
	7.0.2
	7.0.0
	6.0.28
	6.0.26
	6.0.25
	6.0.23
	6.0.21
	6.0.20
	6.0.18
	6.0.16
	6.0.15
	6.0.13
	6.0.11

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 15.3 22618
Build: 15E204a

Xamarin.Mac
Not Installed

Xamarin.iOS
Version: 16.4.0.23 Visual Studio Enterprise
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:15:00-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2024-03-07 20:35:07 UTC

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Enterprise)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: /Users/315402/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.1 (API level 32)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2024-03-07 20:35:14 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2024-03-07 20:35:14 UTC

Build Information
Release ID: 1706100428
Git revision: a5d4aa3648baa4a3f6bff645886bd51ad16c07a7
Build date: 2024-03-07 20:33:17+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 14.4.1
Darwin 23.4.0 Darwin Kernel Version 23.4.0
    Fri Mar 15 00:11:05 PDT 2024
    root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
Project System Tools 0.13
```

</details>

### Build Logs

Binlog information for DevOps pipeline that builds as expected:
 - MTouch Task parameters:
 
![image](https://github.com/xamarin/xamarin-macios/assets/92599778/2031dece-3903-4705-b7ca-ff44b3c789b6)

 - MTouch Command Line arguments:
 ```
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/runner/work/1/s/appName.MobileApp.UI/appName.MobileApp.UI.iOS/obj/iPhone/DEV/response-file.rsp --weak-framework=NewsstandKit.framework/NewsstandKit "--gcc_flags=-ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -lsqlite3" 
```

Binlog information for Visual Studio for Mac build that fails:
 - MTouch Task parameters:
 
![image](https://github.com/xamarin/xamarin-macios/assets/92599778/a535ff39-32b2-4837-8e54-d22f2512a693)

 - MTouch Command Line arguments:
 ```
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/username/Projects/Git/appName.MobileApp.UI/appName.MobileApp.UI/appName.MobileApp.UI.iOS/obj/iPhone/Debug/response-file.rsp --argument=-FIRAnalyticsDebugEnabled --weak-framework=NewsstandKit.framework/NewsstandKit "--gcc_flags=-ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -lsqlite3" 
```

 - Xamarin message received only during build on Mac:
 ```
Xamarin.iOS 16.4.0.23 (xcode14.3: 9defd91b3) using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk
```

 - Warnings:
 
![image](https://github.com/xamarin/xamarin-macios/assets/92599778/6208813e-e4e3-49d0-8a0e-42e59357a059)

 - Errors:
 ```
error MT5209 warning: ignoring duplicate libraries: '-lc++', '-lsqlite3', '-lz' [/Users/username/Projects/Git/appName.MobileApp.UI/appName.MobileApp.UI/appName.MobileApp.UI.iOS/appName.MobileApp.UI.iOS.csproj]
error MT5209 framework 'NewsstandKit' not found [/Users/username/Projects/Git/appName.MobileApp.UI/appName.MobileApp.UI/appName.MobileApp.UI.iOS/appName.MobileApp.UI.iOS.csproj]
MTOUCH error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -lc++ -lsqlite3 -lz -ObjC -lc++ -lsqlite3 -lz -lsqlite3 [/Users/username/Projects/Git/appName.MobileApp.UI/appName.MobileApp.UI/appName.MobileApp.UI.iOS/appName.MobileApp.UI.iOS.csproj]
clang linker command failed with exit code 1 (use -v to see invocation) [/Users/username/Projects/Git/appName.MobileApp.UI/appName.MobileApp.UI/appName.MobileApp.UI.iOS/appName.MobileApp.UI.iOS.csproj]
```

 - Potentially relevant portion of build log:
 
[iosBuildLog.txt](https://github.com/xamarin/xamarin-macios/files/14877934/iosBuildLog.txt)

**Comment by dalexsoto** [comment]
Unfortunately at this moment [Xcode 15.3 is not supported ](https://github.com/xamarin/xamarin-macios/issues/20257) please use Xcode 15.2 for now as listed [here](https://github.com/xamarin/xamarin-macios/issues/20257)

**Comment by dalexsoto** [comment]
I see Xcode 14.2 being referenced here

<img width="441" alt="image" src="https://github.com/xamarin/xamarin-macios/assets/204671/aebc8c16-7ced-4cc5-a7b1-67e95b459296">

Any chance you can test using Xcode 15.2 making sure that xcode-select points to it? also do you have Visual Studio installed on these machines? if so please make sure that it is also pointing to the right version of Xcode usually there is a file in this location `~/Library/Preferences/Xamarin/Settings.plist`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>AppleSdkRoot</key>
    <string>/Applications/Xcode_15.2.0.app</string>
</dict>
</plist>
```

I have not been able to repro this myself, do you see this with a blank project? Also I think Xcode 15.3 no longer has NewsStandKit so you probably want to get rid of `--weak-framework=NewsstandKit.framework/NewsstandKit`

**Comment by ctokunaga-reichert** [comment]
@dalexsoto I have tested with Xcode 15.2. I saw issue #20257 before making this but was still unable to build. The Xcode 14.2 reference you mentioned is from the Azure DevOps pipeline when the build is ran through there, and that builds fine. It's only on a physical Mac with Xcode 15 and higher that the build is failing. I will try with Xcode 15.2 again and see if anything changes. I will also try removing the NewsStandKit workaround.

**Comment by ctokunaga-reichert** [comment]
I was finally able to get the project to build. After downgrading Xcode back to 15.2, I also removed the ```--weak-framework=NewsstandKit.framework/NewsstandKit``` argument, and that seemed to resolve the errors. Even though NewsStandKit was only referenced in 1 of the 4 errors I was seeing, it looks like all 4 were connected to it. It seems that with Xcode 15.2, the NewsStandKit workaround referenced in #18606 is no longer needed, and is in fact detrimental to the build itself, as it was causing the errors that I was seeing.

**Comment by rolfbjarne** [comment]
I believe there's nothing to do here for us then, so I'll close this.

FWIW Xcode 15.3 support is tracked here: https://github.com/xamarin/xamarin-macios/issues/20257.
