### ISSUE TITLE
TextBox still has the focus when we put another app on foreground

### ISSUE THREAD

**Issue by lisalisal** [xamarin/xamarin-macios#20390]
I use avalonia sample https://github.com/AvaloniaUI/ControlCatalogStandalone on macOS.

**Repro Setps**
(1)Run ControlCatalogStandalone project on macos 14.1
(2) Navigate to textbox page, set a textbox in focus.
(3) at this time, we put another app in foreground.

**Problems**
**Expected:** When main window is deactived, The textbox should lost focus. 
**Actually behavior:** Textbox still has the focus, cursor is still blinking, could refer attached video and use attached code project.

**Device Info:**
(1)Macos 14.1
(2)dotnet --list-sdks
6.0.414 [/usr/local/share/dotnet/sdk]
7.0.308 [/usr/local/share/dotnet/sdk]
7.0.401 [/usr/local/share/dotnet/sdk]
8.0.100-rc.1.23463.5 [/usr/local/share/dotnet/sdk]
8.0.203 [/usr/local/share/dotnet/sdk]
(3)dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

[ControlCatalogStandalone-master 2.zip](https://github.com/xamarin/xamarin-macios/files/14835711/ControlCatalogStandalone-master.2.zip)

https://github.com/xamarin/xamarin-macios/assets/89184738/adc071c8-f9ed-409c-8d44-ca6d590571f0

**Comment by dalexsoto** [comment]
Hello, this issue should go into https://github.com/AvaloniaUI/ControlCatalogStandalone instead, we are not doing anything that would trigger this behavior, Xamarin and .NET for iOS/macOS are just a thin layer of interop code to project the Objective-C Apple SDKs into .NET.

**Comment by lisalisal** [comment]
Hi, sorry, I don't make myself clear. Actually I just use  https://github.com/AvaloniaUI/ControlCatalogStandalone  as a sample for you guys to investigate the issue easily, I actually hit the issue in our project. If necessary, I could give a more simple test project that only contains textbox.

And I tried some system apps, seems they doesn't have the issue. When the app is deactivated, the textbox is unfocused and no cursor blinks in the textbox.

**Comment by lisalisal** [comment]
anyway I will also open a issue in https://github.com/AvaloniaUI/ControlCatalogStandalone.
