### ISSUE TITLE
App was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution

### ISSUE THREAD

**Issue by praveenchaswi** [xamarin/xamarin-macios#20397]
I'm using azure hosted agent, VM-image: macos-lates, so i changed it to macos-13 to fix this SDK issue but when i change to macos-13 i'm getting runner error 

error MSB4226: The imported project "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/xbuild/Xamarin/iOS/Xamarin.iOS.CSharp.targets" was not found. Also, tried to find "Xamarin/iOS/Xamarin.iOS.CSharp.targets" in the fallback search path(s) for $(MSBuildExtensionsPath) - "/Library/Frameworks/Mono.framework/External/xbuild/" . These search paths are defined in "/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/MSBuild.dll.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.

pls help me to fix this SDK issue

**Comment by rolfbjarne** [comment]
I believe you need to install Xamarin.iOS on the image.

See https://github.com/actions/runner-images/issues/8528 for more info.

**Comment by praveenchaswi** [comment]
i use azure hosted agent in my project how do i install Xamarin.iOS on the mac0s-13. i'm trying this in azure devops pipeline.
Here's my yml file looks like , please assist

trigger:
  - master
  - Development
  - release/*
  - hotfix/*
  - QA
  - UAT
  - PreProd

pr:
  - master
  - Development
  - release/*

variables:
  SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  SolutionFile: "SMARTS2.Mobile.sln"
  ZipProjects: "SMARTS2.iOS="
  StartUpProject: ""
  DomainProject: ""
  DomainOutputSql: ""
  DbContext: ""  

pool:
  vmImage: 'macOS-13'

stages:
- stage: BuildApp
  jobs:
  - job: Checkout
    steps:
      - checkout: self
        clean: true
  - job: Build
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk 5.0.x'
        inputs:
          version: 5.0.x
          performMultiLevelLookup: true
      - task: PowerShell@2
        displayName: 'PowerShell Script'
        inputs:
          targetType: filePath
          filePath: 'build/build_cake.ps1'
          arguments: '--Target=Deploy --Configuration=Store --Platform=iPhone --ZipProjects "$(ZipProjects)" --SolutionFilePath "$(SolutionFile)" --StartUpProject "$(StartUpProject)" --DomainProject "$(DomainProject)" --DomainOutputSql "$(DomainOutputSql)" --DbContext "$(DbContext)" --BranchProject "MobileFieldOps"'
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          NUGET_AUTH_TOKEN: $(NUGET_AUTH_TOKEN)
      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        inputs:
          testResultsFormat: 'VSTest' # Options: JUnit, NUnit, VSTest, xUnit, cTest
          testResultsFiles: '**/TestResults*.xml' 
          failTaskOnFailedTests: true
          testRunTitle: 'StarTrax Online2 Test Results'

**Comment by praveenchaswi** [comment]
Hello,

I have asked for a query on the ticket. please assist

Thanks,
Praveen
