### ISSUE TITLE
MacCat Incremental builds show warning requiring "Open Anyway" button to be clicked

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-macios#20469]
### Steps to Reproduce

1.  Create a new MAUI app
2.  Debug it on MacCatalyst target
3.  Make a change to the c# or XAML
4. Debug again, observe the error

<img width="372" alt="Screenshot 2024-04-18 at 12 19 59 PM" src="https://github.com/xamarin/xamarin-macios/assets/271950/494a6f28-3838-4aa8-a413-257dc6aff035">

Clicking "Open Anyway" does work fine, but it's an extra step of friction in the dev loop.

### Expected Behavior

No extra dialog / step / click

### Environment

macOS Sonoma 14.4.1
.NET MAUI latest public workloads

**Comment by rolfbjarne** [comment]
I wonder if this could be related to signing and exactly which certificates / provisioning profiles were used.

Can you get a binlog which would show this?
