### ISSUE TITLE
Unexpected error (MT0000) in release mode xamarin forms in platform macos

### ISSUE THREAD

**Issue by AdrianMoraMonge** [xamarin/xamarin-macios#20495]
### Steps to Reproduce

In the macos project I have Apple login implemented, but as soon as I add the following line it fails when compiling:
request.RequestedScopes = new[] { ASAuthorizationScope.Email, ASAuthorizationScope.FullName };

The error only occurs in release mode

### Environment

Visual Studio Community 2022 for Mac
Versión 17.6.10 (build 428)
UUID de instalación: 80045c3c-3c26-45de-b907-d1bb8db0da80

Runtime
.NET 7.0.3 (64-bit)
Architecture: X64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Versión: 6.4.0.117

SDK de .NET (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.314/Sdks
Versiones del SDK:
	8.0.203
	7.0.314
	7.0.310
	7.0.307
	7.0.101
	7.0.100
	6.0.420
	6.0.416
	6.0.413
	6.0.404
	6.0.403
	5.0.408
	3.1.426
	3.1.201
	3.1.200
	3.1.102
	3.0.103
	3.0.100
SDK de MSBuild: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Versiones de tiempo de ejecución:
	8.0.3
	7.0.17
	7.0.13
	7.0.10
	7.0.1
	7.0.0
	6.0.28
	6.0.24
	6.0.21
	6.0.12
	6.0.11
	5.0.17
	3.1.32
	3.1.3
	3.1.2
	3.0.3
	3.0.0
	2.1.16

Xamarin.Profiler
Versión: 1.8.0.49
Ubicación: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Versión: 11

Herramientas de desarrollo de Apple
Xcode: 15.3 22618
Compilación: 15E204a

Xamarin.Android
Versión: 13.2.2.0 (Visual Studio Community)
"Commit": xamarin-android/d17-5/45b0e14
Android SDK: /Users/desarrollo/Library/Android/sdk
	Versiones de Android admitidas:
		8.1  (nivel de API 27)
		11.0 (nivel de API 30)
		10.0 (nivel de API 29)
		9.0  (nivel de API 28)
		13.0 (nivel de API 33)

Versión de herramientas de la línea de comandos del SDK: 7.0
Versión de las herramientas de plataforma del SDK: 34.0.3
Versión de las herramientas de compilación del SDK: 33.0.2

Información de compilación: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer código EPL disponible aquí:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer código EPL disponible aquí:
https://github.com/xamarin/AndroidDesigner.EPL

Administrador de Android SDK
Versión: 17.6.0.50
Hash: a715dca
Rama: HEAD
Fecha de la compilación: 2024-03-07 20:35:14 UTC

Administrador de dispositivos Android
Versión: 0.0.0.1309
Hash: 06e3e77
Rama: HEAD
Fecha de la compilación: 2024-03-07 20:35:14 UTC

Xamarin.Mac
Versión: 9.3.0.23 Visual Studio Community
Hash: 9defd91b3
Rama: xcode14.3
Fecha de la compilación: 2023-10-23 16:14:59-0400

Xamarin.iOS
Versión: 16.4.0.23 Visual Studio Community
Hash: 9defd91b3
Rama: xcode14.3
Fecha de la compilación: 2023-10-23 16:15:00-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2024-03-07 20:35:07 UTC

Información de compilación
Release ID: 1706100428
Git revision: a5d4aa3648baa4a3f6bff645886bd51ad16c07a7
Build date: 2024-03-07 20:33:17+00
Build branch: release-17.6
Calle de compilación: release-17.6

Sistema operativo
Mac OS X 14.4.1
Darwin 23.4.0 Darwin Kernel Version 23.4.0
    Fri Mar 15 00:11:05 PDT 2024
    root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64

### Build Logs

MMP : error MM0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
    System.NullReferenceException: Object reference not set to an instance of an object
      at Registrar.Registrar.RegisterAssembly (Mono.Cecil.AssemblyDefinition assembly) [0x00135] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Registrar.cs:2527 
      at Registrar.StaticRegistrar.Generate (Xamarin.Bundler.MonoMacResolver resolver, System.Collections.Generic.IEnumerable`1[T] assemblies, System.String header_path, System.String source_path, System.String& initialization_method) [0x0006d] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/StaticRegistrar.cs:5178 
      at Registrar.StaticRegistrar.Generate (System.Collections.Generic.IEnumerable`1[T] assemblies, System.String header_path, System.String source_path, System.String& initialization_method) [0x00001] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/StaticRegistrar.cs:5164 
      at Xamarin.Bundler.Driver.Compile () [0x00088] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mmp/driver.cs:797 
      at Xamarin.Bundler.Driver.Pack (System.Collections.Generic.IList`1[T] unprocessed) [0x00592] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mmp/driver.cs:584 
      at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x009ca] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/mmp/driver.cs:323 
      at Xamarin.Bundler.Driver.Main (System.String[] args) [0x0001b] in /Users/builder/azdo/_work/1/s/xamarin-macios/tools/common/Driver.cs:52 
Compilación terminada del destino "_CompileToNative" en el proyecto "DimoiCorreos.MacOS.csproj" -- ERROR.

### Example Project (If Possible)
var appleIdProvider = new ASAuthorizationAppleIdProvider();
var request = appleIdProvider.CreateRequest();
request.RequestedScopes = new[] { ASAuthorizationScope.Email, ASAuthorizationScope.FullName }; // line that causes the error
var controller = new ASAuthorizationController(new[] { request });
this.presentationContext = presentationContext;
controller.Delegate = this;
controller.PerformRequests();

**Comment by AdrianMoraMonge** [comment]
var appleIdProvider = new ASAuthorizationAppleIdProvider();
            var request = appleIdProvider.CreateRequest();
            request.RequestedScopes = new[] { ASAuthorizationScope.Email, ASAuthorizationScope.FullName }; // line that causes the error
            var controller = new ASAuthorizationController(new[] { request });
            this.presentationContext = presentationContext;
            controller.Delegate = this;

            controller.PerformRequests();

**Comment by rolfbjarne** [comment]
I wasn't able to reproduce with the code snippet, so something else is also going on.

Could you please create a complete test project we can use to reproduce this?
