### ISSUE TITLE
The Pipeline of Xamarin forms is failing in Xamarin IOS project

### ISSUE THREAD

**Issue by RamAndyDev** [xamarin/xamarin-macios#20597]
### Steps to Reproduce

1. Running Pipleline of Xamarin forms app in Azure
2. 
3. 

### Expected Behavior

The pipeline should be successful

### Actual Behavior
Getting this error.
error MT0099 : Internal error : 'can't process a mix of dylibs and frameworks: /Users/runner/.nuget/packages/skiasharp.nativeassets.ios/2.88.8/runtimes/ios/native/libSkiaSharp.framework, 

I have this issue in ios.csproj file while running pipeline in Azure.
I am building the App in Xamarin Forms. It is deploying properly while debugging the app in my device. 

### Environment
Visual Studio 2022

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by dalexsoto** [comment]
Unfortunately Xamarin support ended on May 1st https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin, That said I would suggest to check if all the versions you are using in your local dev box matches the one in your pipeline.
