### ISSUE TITLE
[iOS] Attempting to JIT compile method while running in aot-only mode when using AutoMapper on iOS with .NET 8

### ISSUE THREAD

**Issue by thomaschenato** [xamarin/xamarin-macios#20611]
Hello,

I'm working on a Xamarin.iOS migration to .NET 8. However encounter a runtime crash "JIT compile method while running in aot-only mode"

I've read up a few past issues / articles around JIT/AOT crashes in Xamarin / Xamarin.Form and the workaround solution in the past e.g.

https://github.com/xamarin/xamarin-macios/issues/15681
```
<PropertyGroup>
    <UseInterpreter>true</UseInterpreter>
</PropertyGroup>
```

However this workaround doesn't seem to work in .NET 8 as it trigger a crash at app launching.

Please see the detail below and wonder if there is fix in .NET 8 with AutoMapper on iOS

### Steps to Reproduce

1.  Create an basica iOS project targeting .NET 8 from template
2. With AutoMapper 13.0.1, .NET 8 SDK 8.0.203, XCode 15.1
3. `TargetObject targetObject = mapper.Map<TargetObject>(info);`
4.  iOS throw exception during runtime on both **simulator** or **physical iPhone**. Exception detail listed in the Actual Behaviour section

### Expected Behavior
Target object can be created

### Actual Behavior

```
System.ExecutionEngineException: Attempting to JIT compile method '(wrapper dynamic-method) mapper_ios.AppDelegate/TargetObject object:Thunk1ret_TargetObject_Object_TargetObject_ResolutionContext (System.Func`2<object[], object>,object,mapper_ios.AppDelegate/TargetObject,AutoMapper.ResolutionContext)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
```

### Environment

<details>
<summary>Version information</summary>

```
macOS Sonoma 14.1
XCode 15.1
.NET 8 SDK 8.0.203
```

</details>

**Comment by rolfbjarne** [comment]
Please provide a complete test project we can use to reproduce the problem, that way we can be sure we're testing the same thing.

**Comment by jingo0** [comment]
https://github.com/dotnet/macios/issues/15757 The workaround actually works. It crashes app on launch due to improper clean.
