### ISSUE TITLE
Ios Maui sample app uses Chinese Simplified when Chinese Traditional is set in phone preferences

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-macios#20626]
---
**Issue moved from dotnet/runtime#102560**
- Please respond to @Czapek83.

---

_From @Czapek83 on Tuesday, May 21, 2024 11:12:47 AM_

### Description

Created new maui project. Created Strings.resx, Strings.zh.resx, Strings.zh-Hans.resx, and Strings.zh-Hant.resx files with below values of SampleText:
![image](https://github.com/dotnet/maui/assets/11677674/398a7ba0-b16f-4d52-bb9a-97008af50144)

On MainPage.xaml added label that will display proper text according to current language:
![image](https://github.com/dotnet/maui/assets/11677674/46413552-15c7-454e-a3dd-3fb11c4355bc)

And now, when setting Iphone Region to "China mainland" and language to "Chinese Traditional", the SampleText is taken from Chinese, Simplified, but should be taken from Chinese, Traditional:
![image](https://github.com/dotnet/maui/assets/11677674/5e86213e-8714-4c4a-8cd7-efba74c2b7d7)

### Steps to Reproduce

1. Create new maui project.
2. Create localized strings in Resources (Strings.zh-Hans.resx for Chinese Simplified and Strings.zh-Hant for Chinese Traditional) with different strings in it.
3. Use localized string in one of your screens
4. Change your Iphone region to "China mainland" and language to "Chinese Traditional".
5. Run your application and you can see that Chinese Simplified string is used.

### Link to public reproduction project repository

https://github.com/Czapek83/Chinese_LanguageIssue

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 16.7.7, IOS 17.4.1

### Did you find any workaround?

Unfortunatelly, not at all.

**Comment by PureWeen** [comment]
---
**Issue moved from dotnet/maui#22547**
- Please respond to @github-actions[bot].

---

_From @github-actions[bot] on Tuesday, May 21, 2024 11:13:11 AM_

Hi I'm an AI powered bot that finds similar issues based off the issue title.

Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!

### Open similar issues:

- [Localization rendering issue when language is right to left [iOS] (#17934)](https://github.com/dotnet/maui/issues/17934),  similarity score: 0.78

### Closed similar issues:
- [Localization completely broken in IOS apps (#12684)](https://github.com/dotnet/maui/issues/12684),  similarity score: 0.80
- [MAUI Blazor Hybrid does not respect device language on iOS for datetime (#15364)](https://github.com/dotnet/maui/issues/15364),  similarity score: 0.72
- [Localization not work under iOS and Mac arm64 (#11474)](https://github.com/dotnet/maui/issues/11474),  similarity score: 0.71
- [[iOS] Localisation not working (#7362)](https://github.com/dotnet/maui/issues/7362),  similarity score: 0.71

> Note: You can give me feedback by thumbs upping or thumbs downing this comment.

**Comment by rolfbjarne** [comment]
This is a problem for dotnet/runtime, so I moved the original dotnet/maui issue there.
