### ISSUE TITLE
NativeAOT doesn't work with app extensions

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#20653]
NativeAOT doesn't work with app extensions:

```
 System.Exception: No entrypoint module
     at ILCompiler.Program.Run() + 0x26bc
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass227_0.<.ctor>b__0(ParseResult result) + 0x304
```

from https://github.com/xamarin/xamarin-macios/issues/19381#issuecomment-2133653239.

We should try to make this happen.

It might require changes to NativeAOT if NativeAOT requires an entry point (since app extensions don't have an entry point).

**Comment by ivanpovazan** [comment]
Fixed in: https://github.com/xamarin/xamarin-macios/commit/374e9020756bdae22835b65d28a1f32e755b905d
