### ISSUE TITLE
iOS Binding Library Errors: Undefined symbols for Architecture arm64 (also x86_64) 

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-macios#20673]
---
**Issue moved from dotnet/maui#22770**
- Please respond to @BrandanN21.

---

_From @BrandanN21 on Friday, May 31, 2024 7:39:28 PM_

### Description

I am working to get the Stripe iOS SDK available to work with maui in order to support Apple Pay using Stripe and am having trouble getting the project to build erroring out on an unsupported symbols error sometimes for arm64 and others for the x86_64 architecture. 

I have followed Microsoft Documentation for migrating from xamarin -> maui using native iOS bindings and consistently get this error. Has anyone done this before with Stripe? Or am I missing something with the setup and referencing of the native library? 

iOS Binding Library csproj:
![Screenshot 2024-05-31 at 2 33 30 PM](https://github.com/dotnet/maui/assets/47616844/001558ad-07bf-4346-888a-ef3c6a874d06)

Maui csproj reference:
![Screenshot 2024-05-31 at 2 34 45 PM](https://github.com/dotnet/maui/assets/47616844/a7179d05-56d2-4902-b8b2-e191f15beea3)

### Steps to Reproduce

1. Create MAUI app
2. Create iOS Binding Library
3. Add Native Framework (Stripe)
4. Add Api Definitions / StructsAndEnums
5. Reference the dll in MAUI 
6. Use classes from the Library
7. Run app agains iOS simulators OR Physical device
8. see errors

### Version with bug

8.0.10 SR3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No work arounds found

### Relevant log output

```shell
Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_STPAPIClient", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPAddCardViewController", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPAddress", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPApplePayPaymentOption", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPBankAccount", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPBankAccountParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPCard", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPCardParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPCardValidator", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPConnectAccountParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPCoreScrollViewController", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPCoreTableViewController", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPCoreViewController", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPCustomer", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPCustomerContext", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPCustomerDeserializer", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPFile", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPImageLibrary", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPLegalEntityParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentActivityIndicatorView", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentCardTextField", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentConfiguration", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentContext", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentIntent", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentIntentAction", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentIntentActionRedirectToURL", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentIntentParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethod", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodAddress", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodBillingDetails", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodCard", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodCardChecks", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodCardParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodCardPresent", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodCardWallet", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodCardWalletMasterpass", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodCardWalletVisaCheckout", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodThreeDSecureUsage", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodiDEAL", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentMethodiDEALParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentOptionsViewController", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPaymentResult", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPPersonParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPShippingAddressViewController", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPSource", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPSourceCardDetails", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPSourceOwner", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPSourceParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPSourceReceiver", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPSourceRedirect", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPSourceSEPADebitDetails", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPSourceVerification", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPTheme", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPToken", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPUserInformation", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_STPVerificationParams", referenced from:
           in registrar.o
      "_OBJC_CLASS_$_Stripe", referenced from:
           in registrar.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by PureWeen** [comment]
---
**Issue moved from dotnet/maui#22770**
- Please respond to @github-actions[bot].

---

_From @github-actions[bot] on Friday, May 31, 2024 7:39:51 PM_

Hi I'm an AI powered bot that finds similar issues based off the issue title.

Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one and thumbs upping the other issue to help us prioritize it. Thank you!


### Closed similar issues:
- [App Crash on starting - iOS Binding library - DYLD: Symbol not found (#16811)](https://github.com/dotnet/maui/issues/16811),  similarity score: 0.76
- [Maui failed to reference ios binding library (#10344)](https://github.com/dotnet/maui/issues/10344),  similarity score: 0.75
- [clang++ exited with code 1 (#18072)](https://github.com/dotnet/maui/issues/18072),  similarity score: 0.74
- [Duplicate symbol build error (#21483)](https://github.com/dotnet/maui/issues/21483),  similarity score: 0.73
- [iOS Binding Library - Cannot find types declared (#13283)](https://github.com/dotnet/maui/issues/13283),  similarity score: 0.73

> Note: You can give me feedback by thumbs upping or thumbs downing this comment.

**Comment by rolfbjarne** [comment]
Thanks for letting us know!

**Comment by PeterMorrison250** [comment]
@BrandanN21 Could you elaborate further on what you did to resolve this? I am getting the exact same issue, but am unsure how you resolved it when you mention your dll references were incorrect. Thank you

**Comment by BrandanN21** [comment]
@PeterMorrison250 I was having issues with how I was referencing the dll locally when working to get this set up. When you build your bindings project you should then see an dll outputted in the bin folder for example. `MauiSandbox/[binding project name]/bin/debug/net8.0-ios/[project name].dll`

You should double check your bindings project csproj to ensure that you are importing the native reference correctly. When I resolved this it looked like:

```
<!-- this should match your bindings path for where the framework lives within the project -->
<NativeReference Include="Frameworks/[FrameworkName]"> 
<Kind>Framework</Kind>
<SmartLink>False</SmartLink>
</NativeReference>
```

When referencing in your maui projects csproj you want to ensure that you are referencing the dll properly. 

```
<!-- The name iOSBindings is how you will reference it in other parts of your maui app -->
<Reference Include="iOSBindings" Condition="'$(TargetFramework)' == 'net8.0-ios'">
<HintPath>[full path to your dll]</HintPath>
</Reference>
```

Once I was able to confirm this worked locally you can keep the bindings project as a part of your entire solution or you could move it to a nuget feed and consume it similarly.

Hope this helps! Feel free to post some more details if you are having trouble and I can try to see if anything stands out.

**Comment by ahoffmandevelopment** [comment]
In case any one else runs into this, sharpie did not generate the Name attributes for the interfaces in the ApiDefinition.cs file, and I had to go through and add them manually. The name can be found in the headers file.

Before:

```
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
interface BTAPIClient
```

After:

```
[BaseType(typeof(NSObject), Name="_TtC13BraintreeCore11BTAPIClient")]
[DisableDefaultCtor]
interface BTAPIClient
```
