### ISSUE TITLE
why there is no xamarin.ios?

### ISSUE THREAD

**Issue by ljzj2** [xamarin/xamarin-macios#20706]
just question. there is xamarin.android but no xamarin.ios why?

**Comment by rolfbjarne** [comment]
I'm not sure I understand your question, but Xamarin.iOS (and Xamarin.Android) has been discontinued: https://devblogs.microsoft.com/xamarin/xamarin-ios-16-android-13-updates/

**Comment by ljzj2** [comment]
actually I want use .net android and .net ios is that the startup time is smaller. than MAUI. right? in MAUI you need to use CreateMauiApp is that the reason? and I find that I can use some control in .net android.

**Comment by rolfbjarne** [comment]
> actually I want use .net android and .net ios is that the startup time is smaller. than MAUI. right? in MAUI you need to use CreateMauiApp is that the reason? and I find that I can use some control in .net android.

Yes, the startup time with .NET iOS is typically faster than using MAUI. This is because MAUI contains a lot of extra code to be able to use most of the same code across multiple platforms. If you create the UI yourself in code, you'll have to write completely different implementations between iOS and Android.

**Comment by ljzj2** [comment]
thank you for your answer. but why not MAUI do it during complilation time?
If I compile to android then create the UI to android? so can do not do it when I start the APP?

another question is that the .net iOS still in support?

**Comment by rolfbjarne** [comment]
> thank you for your answer. but why not MAUI do it during complilation time?
> If I compile to android then create the UI to android? so can do not do it when I start the APP?

If you have questions about MAUI, you should ask the MAUI team (https://github.com/dotnet/maui/issues).

> another question is that the .net iOS(not xamarin ios) still in support?

Yes, .NET iOS is still very much supported.
