### ISSUE TITLE
Figure out what the problem is with removing '-ld_classic'

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#20711]
Apple is deprecating `-ld_classic`. From Xcode 16's release notes (https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes):

    -ld_classic linker option is deprecated and will be removed in a future release. 

We need to stop passing -ld_classic to the native linker, and figure out and fix why we currently can't.

**Comment by filipnavara** [comment]
Ref: https://github.com/dotnet/runtime/issues/97745

**Comment by rolfbjarne** [comment]
Fixed.
