### ISSUE TITLE
Add full ruport form reflection in AOT enabling Asp.NEt Core AOT Controlers and DataAnottations Validators with AOT

### ISSUE THREAD

**Issue by CastelloBrancoTecnologia** [xamarin/xamarin-macios#20737]
Please incorparate https://github.com/byme8/Apparatus.AOT.Reflection to AOT profile and enable dataannotation Attributes validation and Asp.Net Controlers in AOT scenarios

**Comment by rolfbjarne** [comment]
This looks interesting, but I think it would be a better idea to file this in the dotnet/runtime repository, where the code for the base class library and the AOT compiler lives.
