### ISSUE TITLE
Binding request for URLPathAllowedCharacterSet

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#20745]
### Steps to Reproduce

Try to use [stringByAddingPercentEncodingWithAllowedCharacters:](https://developer.apple.com/documentation/foundation/nsstring/1411946-stringbyaddingpercentencodingwit?language=objc) with [URLPathAllowedCharacterSet](https://developer.apple.com/documentation/foundation/nscharacterset/1416804-urlpathallowedcharacterset?language=objc)

### Expected Behavior

Works

### Actual Behavior

URLPathAllowedCharacterSet not bound
https://github.com/xamarin/xamarin-macios/blob/6c2a7a9eac6168910e59134fc5e452b758675f2c/tests/xtro-sharpie/common-Foundation.ignore#L293-L298

### Environment

.NET8

**Comment by rolfbjarne** [comment]
Fix in progress: https://github.com/xamarin/xamarin-macios/pull/20747
