### ISSUE TITLE
XCode 16 stores provisioning profiles in new location

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#20771]
Provisioning profiles are no longer located in `~/Library/MobileDevice/Provisioning Profiles/`. The directory is not necessarily wiped during Xcode update but it's no longer updated from the Xcode UI. The new location is `~/Library/Developer/Xcode/UserData/Provisioning Profiles`.

Any code that probes the location should be updated.

I found only this one so far:
https://github.com/xamarin/Xamarin.MacDev/blob/94c2c8c9884d14eee5eb2ffa93707638c314ad9a/Xamarin.MacDev/MobileProvision.cs#L60

**Comment by rolfbjarne** [comment]
CC @emaf @mauroa

**Comment by mauroa** [comment]
CC @jstedfast as well

**Comment by Saccomani** [comment]
any workaround? I can't sign my app...

**Comment by jstedfast** [comment]
You could either copy the provisioning profiles into the old location or you could delete the old location and make it a symlink to the new location (not on a mac right now, so the paths might be reversed):

```
ln -s ~/Library/MobileDevice/Provisioning Profiles ~/Library/Developer/Xcode/UserData/Provisioning Profiles
```

**Comment by rolfbjarne** [comment]
We need to bump Xamarin.MacDev in xamarin-macios before we can close this (in progress already).

**Comment by jstedfast** [comment]
Yea, that seemed to get auto-closed by GitHub rules

**Comment by rolfbjarne** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/pull/21010.

**Comment by jadenrogers** [comment]
> You could either copy the provisioning profiles into the old location or you could delete the old location and make it a symlink to the new location (not on a mac right now, so the paths might be reversed):
> 
> ```
> ln -s ~/Library/MobileDevice/Provisioning\ Profiles ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles
> ```

This is backwards

```
ln -s ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles ~/Library/MobileDevice/Provisioning\ Profiles
```
