### ISSUE TITLE
Xamarin framework support for net8.0-ios?

### ISSUE THREAD

**Issue by ljzj2** [xamarin/xamarin-macios#20817]
I created `net8.0-ios` and Want to use `GPUImage` framework it is using `objective-c `.
I can not compile it to `net-ios-binding` since there is too many errors.
then I find that there is `Xamarin.GPUImage` is for xamarinios not netios
please support it to net-ios

I want to use it for camera picking and edge detecting. you may say I should use VisionKit but it not support ios13.
So I have to use this.

what I want to do is to take photos of ticket.

**Comment by ljzj2** [comment]
@rolfbjarne  thank you 
I am not mac developper so it may be difficult to me.
Now I am  `Compile the library into an xcframework`
how to Compile the library into an xcframework?

I tried and compile `libGPUImage.a` but I do not know is it the right file. and do not know how to combine iphoneos and iphonesimulator

**Comment by ljzj2** [comment]
[GPUImage.zip](https://github.com/user-attachments/files/16114573/GPUImage.zip)
this is the `.a`file

**Comment by ljzj2** [comment]
[GPUImage.zip](https://github.com/user-attachments/files/16114573/GPUImage.zip)
this is the `.a`file

**Comment by ljzj2** [comment]
after 3 days of search I still has this error :`cryptexDiskImage' is an unknown content type` when I was creating the framework.

`com.apple.platform.xros' is an unknown platform identifier`

**Comment by rolfbjarne** [comment]
> after 3 days of search I still has this error :`cryptexDiskImage' is an unknown content type` when I was creating the framework.
> 
> `com.apple.platform.xros' is an unknown platform identifier`

Can you explain exactly what you're doing?

**Comment by ljzj2** [comment]
thank you for your help.
1.```
xcodebuild archive 
    -project GPUImage.xcodeproj
    -scheme GPUImage
    -destination "generic/platform=iOS"
    -archivePath "archives/GPUImage"
```
2.```
xcodebuild archive 
    -project GPUImage.xcodeproj
    -scheme GPUImage
    -destination "generic/platform=iOS Simulator"
    -archivePath "archivessimulator/GPUImage"
```
3.```
xcodebuild -create-xcframework
    -archive archives/GPUImage.xcarchive -framework GPUImage.framework
    -archive archivessimulator/GPUImage.xcarchive -framework GPUImage.framework
    -output xcframeworks/GPUImage.xcframework
```

I execute the 3 commands then there is error.

I searched and find that may I need to change the xcode version?

**Comment by rolfbjarne** [comment]
That looks correct to me, although I'm no expert.

> I searched and find that may I need to change the xcode version?

Maybe, which version are you using?

In any case, creating an xcframework is not something we're the best at helping with.

You'd be better off asking for help in Apple's [Developer Forums](https://developer.apple.com/forums/) or [StackOverflow](https://stackoverflow.com/questions/tagged/xcframework).

**Comment by ljzj2** [comment]
I can not solve it and there is no response in the forums I think I have to give it up.
