### ISSUE TITLE
Please update xamarin-macios to consume zlib-ng from dotnet/runtime

### ISSUE THREAD

**Issue by carlossanlop** [xamarin/xamarin-macios#20811]
The dotnet/runtime repo has migrated from consuming madler/zlib and zlib-intel to consuming zlib-ng. We merged this PR on 7/2 to achieve that: https://github.com/dotnet/runtime/issues/101465

The main issue tracking this migration effort is https://github.com/dotnet/runtime/issues/101465

In consequence, xamarin-macios and xamarin-android might need to make changes to ensure they retarget their dependencies appopriately.

Note: We ensured that mobile platforms find and consume the system-installed zlib, but are going to delete the zlib and zlib-intel references from the repo. So please help determine if you need to take actions on this repo.

This needs to be done before .NET 9 gets published.

Please let @carlossanlop or @akoeplinger know if you have any questions.

**Comment by rolfbjarne** [comment]
We don't consume zlib ourselves, we only link with it:

https://github.com/xamarin/xamarin-macios/blob/7e615b07ade4d395b9b5a8f904e9d15734f83209/dotnet/targets/Xamarin.Shared.Sdk.targets#L1524-L1525

so I don't think we'll have to do much, if anything, here.

Leaving open until we've gotten the change from .NET though.

**Comment by rolfbjarne** [comment]
Closing, everything seems to be working fine.
