### ISSUE TITLE
clang++ exited with code 1: Undefined symbols for architecture arm64:  "_OBJC_CLASS_$_CoreAPI", referenced from:  objc-class-ref in registrar.o ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by 15mgm15** [xamarin/xamarin-macios#20884]
### Steps to Reproduce

There aren't steps to reproduce, the Xamarin.iOS bindings are working but the .NET MAUI bindings are not. I am using the VS For Mac template to create the .NET iOS Bindings.

### Expected Behavior
The .NET iOS Binding should work as expected

### Actual Behavior
The .NET iOS Binding is complaining about the symbols

### Environment
Mac OS Sonoma 14.5

Xamarin.iOS
Version: 16.4.0.23 Visual Studio Community

Runtime
.NET 7.0.3 (64-bit)

Visual Studio Community 2022 for Mac
Version 17.6.13 (build 424)

<details>
<summary>Version information</summary>
The bindings are compiling correctly but, when trying to use them, I am getting a bunch of this errors from most of the classes, I just want to point out that the Xamarin.iOS bindings are working flawlessly on a production app. But the .NET MAUI version are giving these types of errors.
[Implementation - MAUI.zip](https://github.com/user-attachments/files/16184060/Implementation.-.MAUI.zip)
[Bindings.zip](https://github.com/user-attachments/files/16184065/Bindings.zip)

</details>

### Build Logs

Error: clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CoreAPI", referenced from:
      objc-class-ref in registrar.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Example Project

cc
@rolfbjarne

**Comment by 15mgm15** [comment]
[Implementation - MAUI.zip](https://github.com/user-attachments/files/16184068/Implementation.-.MAUI.zip)

[Bindings.zip](https://github.com/user-attachments/files/16184072/Bindings.zip)

Attaching the projects to reproduce.

**Comment by 15mgm15** [comment]
I have run the same example project using .NET 8.X on VS Code and I am getting this warning: "Could not extract the native framework 'xxx.framework' from the assembly"

**Comment by 15mgm15** [comment]
Adding this:
```
<PropertyGroup>
	<NoBindingEmbedding>false</NoBindingEmbedding>
</PropertyGroup>
```
Seems to have solved the issue.

**Comment by rolfbjarne** [comment]
> [Implementation - MAUI.zip](https://github.com/user-attachments/files/16184068/Implementation.-.MAUI.zip)
> 
> [Bindings.zip](https://github.com/user-attachments/files/16184072/Bindings.zip)
> 
> Attaching the projects to reproduce.

The zips don't contain the native frameworks, but I think I know the issue: you copied the binding assembly, but didn't also copy the \*.resource directory with it. The native frameworks aren't embedded in the binding assembly anymore (unless you set NoBindingEmbedding=false), they're stored next to the binding assembly, in a \*.resource directory.

I would also recommend that you reference the `*.xcframework` instead of `*.framework` directories, because otherwise your bindings won't work on arm64 in the simulator.

So instead of this:

```xml
<ItemGroup>
  <NativeReference Include="..\..\..\..\Desktop\1000007353-101-Web\MTUSDK_Sample\MTUSDK_Sample\Frameworks\MTUSDK.xcframework\ios-arm64\MTUSDK.framework">
    <Kind>Framework</Kind>
    <SmartLink>False</SmartLink>
  </NativeReference>
  <NativeReference Include="..\..\..\..\Desktop\1000007353-101-Web\MTUSDK_Sample\MTUSDK_Sample\Frameworks\MTSCRA.xcframework\ios-arm64\MTSCRA.framework">
    <Kind>Framework</Kind>
    <SmartLink>False</SmartLink>
  </NativeReference>
</ItemGroup>
```

do this:

```xml
<ItemGroup>
  <NativeReference Include="..\..\..\..\Desktop\1000007353-101-Web\MTUSDK_Sample\MTUSDK_Sample\Frameworks\MTUSDK.xcframework">
    <Kind>Framework</Kind>
    <SmartLink>False</SmartLink>
  </NativeReference>
  <NativeReference Include="..\..\..\..\Desktop\1000007353-101-Web\MTUSDK_Sample\MTUSDK_Sample\Frameworks\MTSCRA.xcframework">
    <Kind>Framework</Kind>
    <SmartLink>False</SmartLink>
  </NativeReference>
</ItemGroup>
```

Can you try that and see if it works?

**Comment by 15mgm15** [comment]
Working as expected @rolfbjarne thanks for the help!
