### ISSUE TITLE
Xamarin iOS Archive and Create distribution IPA extremely slow on Windows

### ISSUE THREAD

**Issue by yasserjarouf** [xamarin/xamarin-macios#20937]
![image](https://github.com/user-attachments/assets/0bbbb19b-2a5a-4259-8df1-4fd1561c7deb)

### Steps to Reproduce
1. Setup the certificate on MacOS as normal, connect the VS to the MacOS, setup the VS Release to use the certificate and Ad-Hoc profile and select iPhone and remote device for the project build.
2. Clean the solution, build the iOS project (finishes in couple of minutes, not bad).
3. Click iOS project Archive, which takes forever!

### Expected Behavior
Should be finishing under couple of minutes.

### Actual Behavior
Takes too long time, the zip being created in 'AppData\Local\Xamarin\iOS\Archives' is like few KBs per second, too slow creating the archive.

### Environment
1. Visual Studio 2022 on Windows.
2. MacOS Sonoma on a vmware workstation.
3. XCode 15 with xamarin.ios-16.4.0.18.pkg installed.

**Comment by dalexsoto** [comment]
Unfortunately Xamarin.iOS is [out of support](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin#microsoft-support) so we won't be releasing any new fixes for it. Please migrate your project to either .NET for iOS or .NET MAUI.
