### ISSUE TITLE
MAUI iOS project on Mac crashes on open, no errors reported

### ISSUE THREAD

**Issue by jerodmotley** [xamarin/xamarin-macios#20935]
[

### Steps to Reproduce

1. Created MAUI iOS project VS for Macbu
2. Added binding library
3. App crashes on open. When debugging, stops before app loads with nothing reported
4. App works when binding library is not included

### Expected Behavior
App loads up
### Actual Behavior
App crashes with no errors reported. When connected to Mac in debug mode, debugging simply stops with no errors.
### Environment
Visual Studio for Mac 17.6.12 (build 410)
.NET SDK (Arm64) 8.0.302
.NET Runtime (Arm64) 8.0.6

<details>
<summary>Version information</summary>

```
```

</details>

**Comment by jerodmotley** [comment]
[Archive 1.zip](https://github.com/user-attachments/files/16353796/Archive.1.zip)

**Comment by jerodmotley** [comment]
[Archive 2.zip](https://github.com/user-attachments/files/16353798/Archive.2.zip)

**Comment by jerodmotley** [comment]
[Archive 3.zip](https://github.com/user-attachments/files/16353803/Archive.3.zip)

**Comment by jerodmotley** [comment]
Linked from issue https://github.com/xamarin/xamarin-macios/issues/20809

**Comment by rolfbjarne** [comment]
It looks like there's a project missing, I get this warning when building BessamerTrust.csproj:

> warning : The referenced project '../Maui.PDFView/Maui.PDFView.csproj' does not exist.

and then a few errors:

```
BessemerTrust/MauiProgram.cs(11,7): error CS0246: The type or namespace name 'Maui' could not be found (are you missing a using directive or an assembly reference?)
BessemerTrust/Views/PDFViewerPage.xaml.cs(2,7): error CS0246: The type or namespace name 'Maui' could not be found (are you missing a using directive or an assembly reference?)
BessemerTrust/Views/PDFViewerPage.xaml.cs(9,12): error CS0246: The type or namespace name 'PdfView' could not be found (are you missing a using directive or an assembly reference?)
```
