### ISSUE TITLE
Some networking tests are failing for tvOS on x64 when using NativeAOT

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#20972]
See https://github.com/xamarin/xamarin-macios/pull/20949.

I've ignored the corresponding tests, since this only seems to effect x64 (so no devices) + limited to tvOS.

**Comment by rolfbjarne** [comment]
CC @ivanpovazan

**Comment by amirvenus** [comment]
Does that mean we cannot build net9.0-tvos for tvOS simulators?

**Comment by ivanpovazan** [comment]
@amirvenus this only affects x64 tvOS simulators. tvOS devices and tvOS simulators on arm Macs are not affected.

**Comment by ivanpovazan** [comment]
> @amirvenus this only affects x64 tvOS simulators. tvOS devices and tvOS simulators on arm Macs are not affected.

After investigation it turned out to be a codegen bug, I failed an issue for it.

**Comment by ivanpovazan** [comment]
Fixed in: https://github.com/xamarin/xamarin-macios/commit/22b5933ebb490b90f1ec13da4aa6b3c222f09e27
