### ISSUE TITLE
CS0616 error with NSPasteboard.NSPasteboardTypeString on latest workloads

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#20993]
_From @kevcrooks on Wed, 07 Aug 2024 08:41:21 GMT_

### Description

After updating my workloads to the latest versions, I now have an error:
`error CS0618: 'NSPasteboard.NSPasteboardTypeString' is obsolete: 'Use the 'NSPasteboardType' enum instead.`

This comes from the following lines:
```
var pb = NSPasteboard.GeneralPasteboard;
pb.DeclareTypes([NSPasteboard.NSPasteboardTypeString], null);
```

However I cannot see an available `NSPasteboardType` enum to use inside `AppKit`.

The build previously worked fine until the latest `dotnet workload update`, so my current packages are:
```
macos                      14.5.8018/8.0.100      SDK 8.0.300
maui                       8.0.71/8.0.100         SDK 8.0.300
```
I think it's likely to be a change to one of these that caused the CS0616.

### Steps to Reproduce

Ran `dotnet workload update` to the latest versions of `macos` and `maui` - I'm not sure how to determine which of these specifically causes the error.

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

_Copied from original issue dotnet/maui#24060_

**Comment by rolfbjarne** [comment]
_From @jfversluis on Wed, 07 Aug 2024 09:13:02 GMT_

Just to be clear this is something in your code right? 

It looks like this should be available: https://github.com/xamarin/xamarin-macios/pull/20643, but only from .NET 9 preview 6. I'm not sure if this will be backported to net8 at this time @rolfbjarne? But I think you'll have enough time during the .NET 9 cycle to get this done.

Looks like there is nothing to be done here right now, so closing this for now.

**Comment by rolfbjarne** [comment]
_From @kevcrooks on Wed, 07 Aug 2024 09:21:12 GMT_

> Just to be clear this is something in your code right?

Yes the example above was from my code, but also used in this repo here, however perhaps you're right it's a case of updating to .NET 9 to remove the error.

https://github.com/dotnet/maui/blob/698f64dd21954fd321bb78c90b5cd22fed0924cf/src/Essentials/src/Clipboard/Clipboard.macos.cs#L10

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Wed, 07 Aug 2024 12:24:11 GMT_

Reopening, this is an issue in xamarin-macios.

**Comment by rolfbjarne** [comment]
Apple says NSPasteboardTypeString isn't available on Mac Catalyst: https://developer.apple.com/documentation/appkit/nspasteboardtypestring (which is why the `NSPasteboardType` enum isn't available on Mac Catalysts), but it seems that's not true.

We'll fix this, but in the meantime you can avoid this by ignoring the compiler warning:

```cs
#pragma warning disable CS0681
pb.DeclareTypes([NSPasteboard.NSPasteboardTypeString], null);
#pragma warning restore CS0681
```

**Comment by rolfbjarne** [comment]
> Apple says NSPasteboardTypeString isn't available on Mac Catalyst: [developer.apple.com/documentation/appkit/nspasteboardtypestring](https://developer.apple.com/documentation/appkit/nspasteboardtypestring) (which is why the `NSPasteboardType` enum isn't available on Mac Catalysts), but it seems that's not true.

I misunderstood something: I thought your app was a Mac Catalyst app (MAUI doesn't support macOS apps, only Mac Catalyst, so I assumed your app was a Mac Catalyst app).

For a macOS app, the `AppKit.NSPasteboardType` enum exists, and this code builds fine for me:

```cs
var pb = NSPasteboard.GeneralPasteboard;
pb.DeclareTypes([NSPasteboardType.String.GetConstant ()], null);
```

**Comment by kevcrooks** [comment]
@rolfbjarne can you share a slimmed down .csproj file for this, so I can compare?

I'm not getting the intellisense for the enum type in my project, so I wonder if I need to update a package or target framework? If I understood correctly this might only be available from dotnet9 preview onwards?

**Comment by rolfbjarne** [comment]
Here's the full project: 
[macos-ac7911f.zip](https://github.com/user-attachments/files/16541446/macos-ac7911f.zip)

**Comment by rolfbjarne** [comment]
> If I understood correctly this might only be available from dotnet9 preview onwards?

No, it's available in our latest .NET 8 workload as well.
