### ISSUE TITLE
What is the alternative for GoogleApisForiOSComponents?

### ISSUE THREAD

**Issue by FANMixco** [xamarin/xamarin-macios#21059]
### Apple platform

iOS, macOS

### Framework version

net8.0-*, net9.0-*

### Affected platform version

VS 2022

### Description

Fellows, this project was archived without any notification or warning:

https://github.com/xamarin/GoogleApisForiOSComponents

![image](https://github.com/user-attachments/assets/7ed5aa6b-de76-4341-b7fe-c41a9b9aaf94)

![image](https://github.com/user-attachments/assets/e4bcd45d-9ea5-4d19-a5e6-e5c5d97c0a27)

Pretty much, it impacts the .NET for iOS developers. Can someone explain if there will be a MAUI project? Or what shall the iOS devs do? Thanks.

### Steps to Reproduce

https://github.com/xamarin/GoogleApisForiOSComponents/issues/628

**Comment by snechaev** [comment]
See here for the related discussion: https://github.com/dotnet/maui/discussions/20359

**Comment by rolfbjarne** [comment]
> See here for the related discussion: [dotnet/maui#20359](https://github.com/dotnet/maui/discussions/20359)

Please see this discussion, in particular the responses by our PM (David Ortinau).
