### ISSUE TITLE
RequiredMemberAttribute Ambiguous reference

### ISSUE THREAD

**Issue by jamescrosswell** [xamarin/xamarin-macios#21073]
### Apple platform

iOS, Mac Catalyst

### Framework version

net8.0-*

### Affected platform version

.net 9.0.100-preview.7.24407.12

### Description

When building the bindings projects for the Sentry SDK targeting net8-ios or net8-maccatalyst using .net 9.0.100-preview.7.24407.12, I'm seeing numerous ambiguous reference exceptions related to the `[RequiredMember]` attribute that is used to decorate various types in the generated bindings.

The ambiguity is  between 'Foundation.RequiredMemberAttribute' and 'System.Runtime.CompilerServices.RequiredMemberAttribute'.

### Steps to Reproduce

I've tried to create a minimal reproducible example of the problem at:
- https://github.com/jamescrosswell/ambiguous-reference

That repo includes instructions on how to run the build that generates these ambiguous reference errors. 

I don't have a clean machine that I can use to try to test that though so I'm not entirely sure what dependencies you'll need to install before being able to run that:
- Some of the things that I've installed on my machine are detailed in the [Contributing.md file for the Sentry .NET SDK](https://github.com/getsentry/sentry-dotnet/blob/main/CONTRIBUTING.md). 
- In addition to that, I've installed `.net 9.0.100-preview.7.24407.12`
- Lots of dotnet workloads need to be installed... worth noting that `dotnet workload restore` does not seem to be sufficient... I also had to run `dotnet workload install maui`

Hopefully the above is enough to be able to reproduce the problem. If not, I'll see what I can do. The problem itself seems pretty obvious though.

### Did you find any workaround?

None

### Build logs

See build logs attached: 
[msbuild-log.zip](https://github.com/user-attachments/files/16667177/msbuild-log.zip)

**Comment by rolfbjarne** [comment]
> * jamescrosswell/ambiguous-reference

I get a 404, is it a private repository?

**Comment by jamescrosswell** [comment]
> I get a 404, is it a private repository?

Argh... sorry about that. It's public now.
