### ISSUE TITLE
Small implementation improvement of the NSUrlSessionHandler (custom proxy)

### ISSUE THREAD

**Issue by adospace** [xamarin/xamarin-macios#21132]
Not an issue just a small improvement of how NSUrlSessionHandler handles custom web proxy.

I'm using the Azure DevOps SDK library under Maui/iOS, specifically the `VssConnection` class.
Under the hood, it set to null the property WebProxy of a HttpClientHandler:

![image](https://github.com/user-attachments/assets/c332f5d2-5c1f-4b43-959e-59a63eeca5fd)

In my use case (and I guess almost always under mobile environment) `DefaultWebProxy` is null.

The problem is that, given the implementation of the WebProxy property, it throws NSE even if the caller is setting `null` value:
https://github.com/xamarin/xamarin-macios/blob/0924eb4ef11f509e48a132c22ec1ad8fdc7be3c1/src/Foundation/NSUrlSessionHandler.cs#L625

![image](https://github.com/user-attachments/assets/c7679252-2e20-4558-ad33-55f73c257421)

Right now we can't use the VssConnection class for this issue and the entire SDK under iOS (under Android it works perfectly fine).

I could create a PR that simply checks the incoming value for `null` value and throws the NRE only if the value is different.

Do you see any issue?

**Comment by rolfbjarne** [comment]
I think this is a great idea, please go ahead and create a PR!

**Comment by rolfbjarne** [comment]
Thanks for your contribution!
