### ISSUE TITLE
Incomplete console output when debugging MAUI app on iOS device

### ISSUE THREAD

**Issue by thisisthekap** [xamarin/xamarin-macios#21180]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

8.0.401

### Description

After installing  `AppsFlyerXamarinBinding`, no console output is shown when debugging on device, but shown in simulator.

### Important notes:

* The same applies to other third party dependencies. Appsflyer is just an example to showcase the issue.
* The issue was reproduced using Visual Studio Code, but is reproducible as well using JetBrains Rider.
* Edit: This issue is present using several different iOS versions on devices (e.g. 17.6.1, 17.5, ...)

## Repository with reproduction

https://github.com/thisisthekap/mauiiosloggingissue

## Repro Steps

1. `dotnet new maui`
2. `dotnet add package AppsFlyerXamarinBinding`
3. Add that code to the simulator:

```csharp
  public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
  {
	AppsFlyerLib.Shared.IsDebug = true;
	AppsFlyerLib.Shared.Start();

      return base.FinishedLaunching(application, launchOptions);
  }
```

4. Run on simulator
5. Output like `[AppsFlyerSDK] [com.appsflyer.serial] [START] Initial start of the application` is shown on the debug console
6. Run on device
7. No output like `[AppsFlyerSDK] [com.appsflyer.serial] [START] Initial start of the application` is shown on the debug console

**Comment by thisisthekap** [comment]
A note on the severity of this issue: Having the full console output just on Simulator breaks MAUI development for us. We need to have reliable console output on devices, specifically iOS, in order to test device specific stuff such as IDFA constent and purchase related stuff.

**Comment by rolfbjarne** [comment]
This is due to the fact that last year (in iOS 17 / Xcode 15), Apple completely rewrote their libraries to interact with devices, and in the process didn't leave us any way to capture stdout/stderr from the process on device.

The good news is that they've fixed this for iOS 18 / Xcode 16, so once we've released .NET 9 (with support for iOS 18) this will work.

**Comment by thisisthekap** [comment]
@rolfbjarne Is there any way to backport this to the current stable?

**Comment by rolfbjarne** [comment]
> @rolfbjarne Is there any way to backport this to the current stable?


No, because you also need to update to iOS 18 on your device and use Xcode 16.

Uou can view the output in the Console app though: https://support.apple.com/en-in/guide/console/cnsl1012/mac

**Comment by thisisthekap** [comment]
@rolfbjarne Thank you for your assistance!

**Comment by thisisthekap** [comment]
@rolfbjarne An additional finding: On initial deployment to a device, there seems to be no output at all (no loggers, no stdout, nothing in console). This makes me believe that this issue might be related to #21186

**Comment by rolfbjarne** [comment]
Closing since this will be fixed once we release Xcode 16 support.

In the end I discovered that it won't be necessary to upgrade any _device_, as long as you're using Xcode 16, it'll still work for devices with only iOS 17 installed.
