### ISSUE TITLE
ios binding library with xcframework/framework cannot be referenced in the main .NET MAUI project

### ISSUE THREAD

**Issue by wwen0** [xamarin/xamarin-macios#21189]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

.NET6, .NET7, .NET8

### Description

I created an iOS binding project with iOS xcframework (I also tried framework). The project built without any errors. I conditionally (iOS) referenced the binding project in my main project. But the namespace and the classes that were generated in the binding project's obj/Debug/net8/0-ios/iOS. I tried different ways to reference the binding project in the main project like these:
<ItemGroup>
  <Reference Include="MauiDemoApp.Binding.iOS" Condition=" '$(TargetPlatformIdentifier)' == 'ios' ">
	<HintPath>..\MauiDemoApp.Binding.iOS\bin\debug\net8.0-ios\MauiDemoApp.Binding.iOS.dll</HintPath>
  </Reference>
</ItemGroup>
	
or:
<ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'ios' ">
  <ProjectReference Include="..\MauiDemoApp.Binding.iOS\MauiDemoApp.Binding.iOS.csproj" />
</ItemGroup>

But when I tried referencing the namespace and the classes in the main project's Platforms/iOS/AppDelegate.cs, they were not recognized.

I created a GitHub repo for this: https://github.com/wwen0/MauiDebug

### Steps to Reproduce

1. Create the binding project, add in the xcframework, modify the ApiDefinition.cs and StructsAndEnums.cs to match the xcframework content.
2. Build the binding project.
3. After successful build of the binding project, conditionally add the binding project reference in the main project.
4. Build the main project.
5. In the main project's Platforms/iOS/AppDelegate.cs, try referencing the namespace defined in ApiDefinition.cs and StructsAndEnums.cs, and the classes in the xcframework.  Red lines appear under the namespace and the class names, indicating they are not recognized.

**Comment by rolfbjarne** [comment]
> 5\. Red lines appear under the namespace and the class names, indicating they are not recognized.

This is a known issue (https://github.com/xamarin/xamarin-macios/issues/10148).

It's only intellisense that doesn't work, if you build the project, it'll build just fine.

Referencing the binding project directly, something like this from your main project, should work though:

```xml
<ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'ios' ">
	<Reference Include="../MauiDemoApp.Binding.iOS/bin/Debug/net8.0-ios/Com.SAS.CI360.dll" />
</ItemGroup>
```

Note that in this case you'll have to build the binding project manually first, it won't be built automatically when you're building the main project.

Additionally, in your binding project, you should reference the .xcframework (and not the .framework inside the .xcframework):

```xml
<NativeReference Include="SASCollector.xcframework">
```

Can you try that and see if it works for you?

**Comment by wwen0** [comment]
> > 5. Red lines appear under the namespace and the class names, indicating they are not recognized.
> 
> This is a known issue (#10148).
> 
> It's only intellisense that doesn't work, if you build the project, it'll build just fine.
> 
> Referencing the binding project directly, something like this from your main project, should work though:
> 
> ```
> <ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'ios' ">
> 	<Reference Include="../MauiDemoApp.Binding.iOS/bin/Debug/net8.0-ios/Com.SAS.CI360.dll" />
> </ItemGroup>
> ```
> 
> Note that in this case you'll have to build the binding project manually first, it won't be built automatically when you're building the main project.
> 
> Additionally, in your binding project, you should reference the .xcframework (and not the .framework inside the .xcframework):
> 
> ```
> <NativeReference Include="SASCollector.xcframework">
> ```
> 
> Can you try that and see if it works for you?

I tried, and the project ran without errors. However, even though the native methods' corresponding C# methods were called, there was no effect. It seemed that the native code was not invoked. Is there still something missing in my project? Do I need to add LinkWith in ApiDefinition.cs? The ApiDefinition.cs and StructsAndEnums.cs were copied from a previous Xamarin project. The Xamarin project worked without any issue.

**Comment by rolfbjarne** [comment]
> > > 5. Red lines appear under the namespace and the class names, indicating they are not recognized.
> > 
> > 
> > This is a known issue (#10148).
> > It's only intellisense that doesn't work, if you build the project, it'll build just fine.
> > Referencing the binding project directly, something like this from your main project, should work though:
> > ```
> > <ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'ios' ">
> > 	<Reference Include="../MauiDemoApp.Binding.iOS/bin/Debug/net8.0-ios/Com.SAS.CI360.dll" />
> > </ItemGroup>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note that in this case you'll have to build the binding project manually first, it won't be built automatically when you're building the main project.
> > Additionally, in your binding project, you should reference the .xcframework (and not the .framework inside the .xcframework):
> > ```
> > <NativeReference Include="SASCollector.xcframework">
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you try that and see if it works for you?
> 
> I tried, and the project ran without errors. However, even though the native methods' corresponding C# methods were called, there was no effect. It seemed that the native code was not invoked. Is there still something missing in my project? Do I need to add LinkWith in ApiDefinition.cs? The ApiDefinition.cs and StructsAndEnums.cs were copied from a previous Xamarin project. The Xamarin project worked without any issue.

Can you update your GitHub project with exactly what you did?

**Comment by wwen0** [comment]
I already updated my Github project, with the exception of a plist file that is not essential to test. This line "**SASLogger.SetLevel(SASLoggerLevel.All);**" in AppDelegate.cs should provide logs such as: INFO:..., DEBUG:...

I also changed xcframework to framework, because if I run with xcframework it will complain that I cannot do it on a simulator. So I get out the framework from xcframework that is for a simulator.

**Comment by rolfbjarne** [comment]
I get this message:

> WARN: SASCollector initialization requested without full setup

Note that some types of messages from native code might not show up in the IDE (ref #21180), so you might have to use the iOS Device Log to see them (https://support.apple.com/en-in/guide/console/cnsl1012/mac)

Can you do that and check if you see anything?

**Comment by wwen0** [comment]
I got the same warning. That is from the native library. So that confirms there is still log. It's just that I wasn't expect to see this. The reason that I got this warning even though I have the plist file is because the native library didn't find it. This is what I added in csproj file:

_<ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'iOS' ">
   <BundleResource Include="./Platforms/iOS/SASCollector.plist" />
</ItemGroup>_

Is it correct?

**Comment by rolfbjarne** [comment]
Where is this plist supposed to be located in the app bundle? In the root directory?

**Comment by wwen0** [comment]
In native app, it should be in the main bundle

**Comment by rolfbjarne** [comment]
Try this:

```xml
<ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'iOS' ">
   <BundleResource Include="./Platforms/iOS/SASCollector.plist" Link="SASCollector.plist" />
</ItemGroup>
```

**Comment by wwen0** [comment]
> Try this:
> 
> ```
> <ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'iOS' ">
>    <BundleResource Include="./Platforms/iOS/SASCollector.plist" Link="SASCollector.plist" />
> </ItemGroup>
> ```

Adding "Link" attribute solved the problem. Thank you very much @rolfbjarne 
One thing I noticed is that unlike in iOS,  in Android as long as I put the .properties file in Platforms/Android/Assets folder, it worked without any issue. I do not even need to add BundleResource. In Android, the file has .properties extension.

**Comment by rolfbjarne** [comment]
> One thing I noticed is that unlike in iOS, in Android as long as I put the .properties file in Platforms/Android/Assets folder, it worked without any issue. I do not even need to add BundleResource. In Android, the file has .properties extension.

This might also have worked if you put the SASCollector.plist in the `Platforms/iOS/Resources` directory.

In any case, I'm glad it's working for you now.

**Comment by borrmann** [comment]
I seem to have similars issues both with BranchSDK and AppsFlyerSDK when building with an Intel (amd no problem).

`
<PackageReference Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'" Include="AppsFlyerXamarinBinding" Version="6.13.1" />
`
leads to
`
C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\tools\msbuild\iOS\Xamarin.Shared.targets(154,3): error : The xcframework C:\Users\MaxBorrmann\.nuget\packages\appsflyerxamarinbinding\6.13.1\lib\net6.0-ios16.1\AppsFlyerBinding.iOS.resources.zip has an incorrect or unknown format and cannot be processed.
`

@rolfbjarne do you have any idea what I could do about that?

**Comment by smartdataAS** [comment]
It wont work without dll 	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-ios'">
		<ProjectReference Include="..\Twilio.Voice\Twilio.Voice.csproj" />
	</ItemGroup>
