### ISSUE TITLE
Version 8.0.401 release broke ability to run app with WebDriverAgent from Appium on iOS

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#21234]
_From @Joost-Jens-Luminis on Fri, 13 Sep 2024 07:26:42 GMT_

We have been creating tests using Appium for a few months now for our app on Windows, Android and iOS.
Unfortunately, with the release of .Net 8.0.401 and the released iOS workload it broke our ability to test on iOS.

When the WebDriverAgent from Appium is running, it takes to long for the App to start now and it gets killed by the iOS watchdog.
If the WebDriverAgent from Appium is not running, the app is starting up fine and working properly.

With .Net version 8.0.300 (and related workloads) it is still working properly. Unfortunately, as we are using a release version, build in Azure Pipelines, to run the tests we cannot downgrade to an earlier version of the workloads.

The following installation is still working fine with Appium testing on iOS (This is from my PC):
![image](https://github.com/user-attachments/assets/32179b54-1447-423f-b400-2a11496af7b8)

Is there any information on what has changed in net8.0-ios that could have caused this? And how we could work around this issue?

Note: We are a 100% sure Appium didn't cause this, as we hadn't update Appium when the problems started. 
Of course we did try updating Appium and it's drivers to the latest version but to no avail.

_Copied from original issue dotnet/runtime#107781_

**Comment by rolfbjarne** [comment]
_From @vitek-karas on Fri, 13 Sep 2024 11:29:09 GMT_

@rolfbjarne maybe you have some context.
Should we move this to xamarin-macios?

**Comment by rolfbjarne** [comment]
@Joost-Jens-Luminis it's not clear from your description, but can you reproduce this locally, or does it only happen on CI?

To start diagnosing this, it would be good to get any crash reports from the device: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#crash-reports

That would reveal what the app is actually doing when it's being terminated.

**Comment by Joost-Jens-Luminis** [comment]
@rolfbjarne Yes, this can be reproduced locally. A colleague of mine has updated his installation and with his builds (both debug and release builds) the takes to long to start.
To be extra clear, the splashscreen becomes visible, but then the app stops responsing and gets closed by the watchdog on iOS after about 19 seconds.

This also means that there is no crash. It just gets closed.

**Comment by Joost-Jens-Luminis** [comment]
This is a video of what happens. It's boring, but give you an idea
https://github.com/user-attachments/assets/98f03e76-f922-4fcb-b64f-078fc3c93134

The first document is de console log from the iOS device regarding what is going on at the time for our App (Bronkhorst FlowcontrolApp). The second one is the full log unfiltered (in cases the filter filters something out that is important)
[Filtered console log.txt](https://github.com/user-attachments/files/16993694/Filtered.console.log.txt)
[Full console log.txt](https://github.com/user-attachments/files/16993695/Full.console.log.txt)


I hope this provides enough information to get a clue as to what is going on here.

**Comment by rolfbjarne** [comment]
> This also means that there is no crash. It just gets closed.

iOS will still create a crash report. This is from the device log:

> ReportCrash	Formulating fatal 309 report for corpse[379] Bronkhorst.FlowControl.iOS

**Comment by Joost-Jens-Luminis** [comment]
You are correct, this is a crash log I got from the phone. I generated it this morning though as I couldn't find the crashlogs from last Friday. But I assume it's the same crash.

[Crash log.txt](https://github.com/user-attachments/files/17009969/Crash.log.txt)

**Comment by Joost-Jens-Luminis** [comment]
Here is the file with NoSymbolStrip enabled:
[Bronkhorst.FlowControl.iOS-2024-09-17-081344.txt](https://github.com/user-attachments/files/17023746/Bronkhorst.FlowControl.iOS-2024-09-17-081344.txt)

**Comment by Joost-Jens-Luminis** [comment]
Here is the file:

[Bronkhorst.FlowControl.iOS-2024-09-17-084529.txt](https://github.com/user-attachments/files/17024040/Bronkhorst.FlowControl.iOS-2024-09-17-084529.txt)

**Comment by Joost-Jens-Luminis** [comment]
Maybe that was because it was a release build. I made one with debug, there is a bit more information in here.
[Crash report from debug build.txt](https://github.com/user-attachments/files/17039885/Crash.report.from.debug.build.txt)


Unfortunately I spend yesterday trying to update my systems (Windows and Mac) so I can reproduce this while debugging, unfortunately that prevented me from debugging al to gather (VS can't connect to my Mac anymore due to a null reference exception), so this is still a build from the Azure Devops Pipeline but with debugging set instead of release. I hope this is enough.

**Comment by rolfbjarne** [comment]
Yes, that's a bit more helpful at least.

Can you try turning the interpreter off to see if that changes anything?

```xml
<PropertyGroup>
    <UseInterpreter>false</UseInterpreter>
</PropertyGroup>
```

if it still fails the same way, please get an updated crash report.

**Comment by Joost-Jens-Luminis** [comment]
Still doesn't work. So here is a new crash report.

[Bronkhorst.FlowControl.iOS-2024-09-18-111358.txt](https://github.com/user-attachments/files/17041679/Bronkhorst.FlowControl.iOS-2024-09-18-111358.txt)

**Comment by rolfbjarne** [comment]
> Still doesn't work. So here is a new crash report.
> 
> [Bronkhorst.FlowControl.iOS-2024-09-18-111358.txt](https://github.com/user-attachments/files/17041679/Bronkhorst.FlowControl.iOS-2024-09-18-111358.txt)

Correct, but the stack trace reveals what the main thread is waiting for:

```
15  System_Runtime_CompilerServices_TaskAwaiter_GetResult + 120
16  MvvmCross_ViewModels_MvxAppStart_Start_object + 224
17  MvvmCross_Platforms_Ios_Core_MvxApplicationDelegate_RunAppStart_object + 456
18  MvvmCross_Platforms_Ios_Core_MvxApplicationDelegate_FinishedLaunching_UIKit_UIApplication_Foundation_NSDictionary + 524
19  Bronkhorst_FlowControl_iOS_AppDelegate_FinishedLaunching_UIKit_UIApplication_Foundation_NSDictionary + 1240
```

Your FinishedLaunching method calls MvvmCross' FinishedLaunchingMethod, which runs MvxAppliationDelegate.RunAppStart, which eventually does a "task.GetResult ()", which doesn't return, presumably because the task doesn't complete.

I'm guessing this is the GetResult call in MvvmCross:

https://github.com/MvvmCross/MvvmCross/blob/9f39b77f60255c57a0c542bbe36b3d2237980973/MvvmCross/ViewModels/MvxAppStart.cs#L30

and the problem is that the call to NavigateToFirstViewModel never completes:

https://github.com/MvvmCross/MvvmCross/blob/9f39b77f60255c57a0c542bbe36b3d2237980973/MvvmCross/ViewModels/MvxAppStart.cs#L45

That's as far as I can get from the crash report, to continue diagnosing I'd probably need a test project I can use to reproduce this myself.

**Comment by Joost-Jens-Luminis** [comment]
I have made a sample app. The problem is in that path but it is the following line:

`StartAsync().GetAwaiter().GetResult();`

What "StartAsync" does is less relevant it seems.

I have made a new iOS Application, the default App that Visual studio creates.
![image](https://github.com/user-attachments/assets/4279656a-2a23-4961-a087-31e4e5db4cdf)


The only change I made was in the AppDelegate.cs file. I modified the FinishedLaunching method as follows:
```
        public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
        {
            ...
            StartAsync().GetAwaiter().GetResult(); // THIS IS NEWLY ADDED

            return true;
        }

```

The StartAsync() method looks like this (Modelled after wat MvvmCross did here):
```
        private int _startHasCommenced;
        public async Task StartAsync(object? hint = null)
        {
            // Check whether Start has commenced, and return if it has
            if (Interlocked.CompareExchange(ref _startHasCommenced, 1, 0) == 1)
                return;

            int applicationHint = await Task.Run(async () =>
            {
                await Task.Delay(1000);
                return 0;
            });

            await Task.Run(async () =>
            {
                await Task.Delay(1000);
                return applicationHint;
            });
        }
```

This seems to be causing the issues. Crash files coming in a next post.

**Comment by Joost-Jens-Luminis** [comment]
This is the first crash file containing the code mentioned above.
[iOSApp1-2024-09-19-111807.txt](https://github.com/user-attachments/files/17057029/iOSApp1-2024-09-19-111807.txt)

For sake of testing, I have made a test run with "Interlocked.CompareExchange" commented out to see if that was the issue. This is that log file:
[iOSApp1-2024-09-19-114321.txt](https://github.com/user-attachments/files/17057053/iOSApp1-2024-09-19-114321.txt)

**Comment by Joost-Jens-Luminis** [comment]
[iOSApp1.zip](https://github.com/user-attachments/files/17057813/iOSApp1.zip)

And the project itself.

**Comment by Joost-Jens-Luminis** [comment]
oh? That is interesting. Yet the .Net version is the only variable that changed in that time. There not been an MvvmCross update in the mean time either.

And I also see the deadlock now without Appium on my test version (Sorry I didn't test that before hand).
So why is that working normally just fine, but not in this test version? And why has that started causing issues normally when running Appium?

Could this be as a result of an SDK change between SDK 8.0.300 and SDK 8.0.400and and not related to Xamarin directly?

**Comment by rolfbjarne** [comment]
> oh? That is interesting. Yet the .Net version is the only variable that changed in that time. There not been an MvvmCross update in the mean time either.
> 
> And I also see the deadlock now without Appium on my test version (Sorry I didn't test that before hand). So why is that working normally just fine, but not in this test version? And why has that started causing issues normally when running Appium?
> 
> Could this be as a result of an SDK change between SDK 8.0.300 and SDK 8.0.400and and not related to Xamarin directly?

It could be a result of many things, but it would just be speculation.

I can do a proper investigation with confirmed results if I could get a test project that reproduces the regression - i.e. it works on the older workload, but not on the newer workload.

**Comment by Joost-Jens-Luminis** [comment]
Hi @rolfbjarne I just wanted to give an update on this. As I had updated my computer and only have 1 mac I have been unable to get a working setup that shows regression here. 
What is strange is that the code which seems to be causing the deadlock just doesn't work in my test setup, but it does work in de main application.(assuming the WDA isn't running) in all instances. To me this indicates .Net does some really weird stuff when it comes to async functions and I guess I don't understand this.

I will keep trying to reproduce this using a VM with an older installation, of .Net, but this is a slow process.

**Comment by rolfbjarne** [comment]
> I will keep trying to reproduce this using a VM with an older installation, of .Net, but this is a slow process.

Thanks!

It truly sounds like something weird is going on, but that just makes it so much more important for us to actually have a way to reproduce the problem, otherwise we'll just be fumbling in the dark.

**Comment by Joost-Jens-Luminis** [comment]
I have a small update on this. While attempting to recreate the original situation of our App working while the WebDriverAgent is working by having a Windows VM with only the .net 8.0.303 SDK installed, we noticed that we need the following workload for it to work. Newer workloads fail:
`dotnet workload restore --version 17.2.8078`   

I am still looking for the specific code that causes the deadlock so I can reproduce it.

**Comment by Joost-Jens-Luminis** [comment]
I have more information. 
We are running into an issue when using MvvmCross and the WebDriverAgent from Appium. All of a sudden ViewModels are not created anymore on iOS. This causes the App to deadlock during startup. I am trying to pinpoint the cause of the issue but the exception we are getting is as follows:

```
**System.NullReferenceException:** 'Object reference not set to an instance of an object'

   at MvvmCross.ViewModels.MvxViewModelLoader.LoadViewModel(MvxViewModelRequest request, IMvxBundle savedState, IMvxNavigateEventArgs navigationArgs)
   at MvvmCross.Platforms.Ios.Views.MvxViewControllerExtensions.LoadViewModel(IMvxIosView iosView)
   at MvvmCross.Views.MvxViewExtensions.OnViewCreate(IMvxView view, Func`1 viewModelLoader)
   at MvvmCross.Platforms.Ios.Views.MvxViewControllerExtensions.OnViewCreate(IMvxIosView iosView)
   at MvvmCross.Platforms.Ios.Views.MvxViewControllerAdapter.HandleViewDidLoadCalled(Object sender, EventArgs e)
   at MvvmCross.Base.MvxDelegateExtensions.Raise(EventHandler eventHandler, Object sender)
   at MvvmCross.Platforms.Ios.Views.Base.MvxEventSourceViewController.ViewDidLoad()
   at MvvmCross.Platforms.Ios.Views.MvxViewController.ViewDidLoad()
   at Bronkhorst.FlowControl.iOS.Views.DevicesView.ViewDidLoad() in C:\Work\Flowsuite\Bronkhorst.FlowControl.iOS\Views\DevicesView.cs:line 29
```

This was working before (on ios workload 17.2.8078) but stopped working. I Have asked MvvmCross developer as to why it's happening but they have no idea either at this time.

THe file it is failing is this: https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross/Platforms/Ios/Views/MvxViewControllerExtensions.cs

**Comment by Joost-Jens-Luminis** [comment]
I think I have found the problem.
On the old workload (Workload 17.2.8078) the DevicesView constructor gets called only once. 

On the latest workload the DevicesView constructor gets called twice. One time correctly (it seems) and the second time not. This also means the ViewDidLoad function gets called twice. I think somewhere the workload is trying to load something it shouldn't.

See attached the stack trace of the  3 constructor calls. Old workload is working properly, Call 1 of the new workload seems fine but Call 2 does not.
[Old workload Constuctor Call.txt](https://github.com/user-attachments/files/17210212/Old.workload.Constuctor.Call.txt)
[New workload Constuctor Call 1.txt](https://github.com/user-attachments/files/17210213/New.workload.Constuctor.Call.1.txt)
[New workload Constuctor Call 2.txt](https://github.com/user-attachments/files/17210214/New.workload.Constuctor.Call.2.txt)

Could the new workload have caused this?

**Comment by rolfbjarne** [comment]
That's really interesting, but I have no idea what might be causing this.

Would you be able to create a test project I can use to reproduce this myself now?

**Comment by Joost-Jens-Luminis** [comment]
I think so yes, but that will probably by the end of the week. It's end of sprint tomorrow and that has priority :(

**Comment by Joost-Jens-Luminis** [comment]
I had more time then expected today, so please find here the sample app:
[Bronkhorst app crash sample.zip](https://github.com/user-attachments/files/17230470/Bronkhorst.app.crash.sample.zip)

It is probably a bit bigger then you would prefer, as it includes the MvvmCross core library and some plugins as well as a very stripped down version of our app. It does show the problem though so I hope it's enough.

In the "Bronkhorst" folder you would see the iOS app which you can compile and run to show the problem.
If you would put a breakpoint in the DevicesView constructor (which can be found in the Views folder) you can see it's called/started twice and if you would let it run you will see the exceptions start appearing and the app is hanging.

We have also found what we believe to be the cause of the issue though:
The "Main.storyboard" file has a property called "initialViewController" which is set to the DevicesView (via it's storyboard ID). If we remove that property, it appears to fix the problem we are having. (This hasn't been tested in the full app yet though, only in this sample version).

**Comment by rolfbjarne** [comment]
Exactly which workload versions can you reproduce the failure with? What's the output of `dotnet --info`?

**Comment by Joost-Jens-Luminis** [comment]
You can use the latest workload to see it go wrong. 
 
On iOS Workload 17.2.8078 everything is working as expected.

**Comment by rolfbjarne** [comment]
This works for me, which is the latest as of today:

```
$ dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-tizen                 8.0.82/8.0.100         SDK 8.0.300
ios                        18.0.8303/8.0.100      SDK 8.0.300
```

**Comment by Joost-Jens-Luminis** [comment]
That is interesting.
With this is was failing:
![image](https://github.com/user-attachments/assets/c6c47b24-e04f-4673-b225-39f5a8f09a52)


But you have a newer workload so maybe it's fixed with that?

**Comment by rolfbjarne** [comment]
Even those versions work for me :/

A few more questions:

* Can you reproduce on both simulator and device, or only one of them?
* Do you see the same broken behavior when you tap on the app (as opposed to launching from within the IDE)?
* Do you see the same broken behavior if you use VSCode on macOS directly to run the app?

**Comment by Joost-Jens-Luminis** [comment]
1) I am only working on a real device
2) Yes
3) I haven't tested that yet. I have always used VS on windows to debug versions. I have used release builds as well.


Do you have the WDA from Appium installed on your test device? Without that installed it works for me as well, but with that installed is when these problems occur.

**Comment by rolfbjarne** [comment]
> Do you have the WDA from Appium installed on your test device? Without that installed it works for me as well, but with that installed is when these problems occur.

No, I don't; how do I get that installed?

**Comment by Joost-Jens-Luminis** [comment]
The following are the instructions I follow when I installed it (They are from our own internal wiki).
```
A good tutorial can be found here: https://www.youtube.com/watch?v=kvNnF4Zpgmo&t=2s  Note: it is a bit out of date as you no longer need to install the WDA from the commandline.

Source: https://www.33rdsquare.com/the-complete-step-by-step-guide-to-appium-ios-test-automation/ 

Homebrew is a must-have package manager for any Mac device. Open your Mac terminal and install Homebrew: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Next, use Homebrew to install Node.js and the Appium server:

brew install node
npm install -g appium
Appium requires some additional iOS-focused dependencies like ios-deploy and Carthage:
brew install ideviceinstaller 
npm install -g ios-deploy
brew install carthage
Install the Appium driver: appium driver install xcuitest
https://appium.github.io/appium-xcuitest-driver/latest/ 

Configure and install the WDA on the mobile device:\You can open the WDA using the following command:
appium driver run xcuitest open-wda
Make sure to set codesign for all packages (else it may not build).

Use "Product -> destination" to select your device.
Use "Product -> Scheme -> WebDriverAgentRunner" to select the package to install.
Use "Product -> Test" to install the agent on your phone. Source: https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/#using-xcode 
```

**Comment by rolfbjarne** [comment]
OK, I can reproduce it now, the WDA app must also be running from inside Xcode in order to reproduce.

**Comment by rolfbjarne** [comment]
I've finally figured out what's happening, and it's an unintended side effect of a new feature we added.

The problem is in with the `Window` property in the class `MvxApplicationDelegate`, and how it's declared `new`:

```cs
public abstract class MvxApplicationDelegate : UIApplicationDelegate, IMvxApplicationDelegate
{
    public new virtual UIWindow Window { get; set; }
	// ...
}
```

Prior to when this broke, this `Window` property was not exported to Objective-C (it doesn't have an `[Export]` attribute, and doesn't override a property that does either).

In one of our latest updates, we implemented improved support for binding protocols by taking advantage of default interface members in C#. The consequence is that the `Window` property is now exported to Objective-C, because:

1. The Objective-C protocol `UIApplicationDelegate` has a `Window` property.
2. This `Window` property is optional, so it's technically not necessary to implement it.
3. The `MvxApplicationDelegate` class implements the `IMvxApplicationDelegate` interface, which implements the `IUIApplicationDelegate` interface (which represents the Objective-C protocol `UIApplicationDelegate`).
4. We see that `MvxApplicationDelegate`'s `Window` property matches the `Window` property on the `IUIApplicationDelegate` interface (which has an `[Export]` attribute), and export it to Objective-C.
5. The presence in Objective-C of the `Window` property makes iOS take a very different code path internally, and that eventually ends up instantiating the `DevicesView` class twice (the storyboard where the `DevicesView` class is used is instantiated twice).

Sidenote: it's possible to get replicate the broken behavior with the older version of the workload by making the `Window` property override the `Window` property from `UIApplicationDelegate` (in this case the property is exported to Objective-C, because `UIApplication.Window` has an `[Export]` attribute):

```cs
public abstract class MvxApplicationDelegate : UIApplicationDelegate, IMvxApplicationDelegate
{
    public override UIWindow Window { get; set; }
	// ...
}
```

Going forward, I don't think this is something we'll fix/change on our side, because it's such an incredible rare set of circumstances that leads to the eventual deadlock at startup.

I believe the best fix is on your end, by making the `DevicesView` class not fail when it's instantiated more than once.

Alternatively it might be possible to just rename the `Window` property, to say `MainWindow`:

```cs
public abstract class MvxApplicationDelegate : UIApplicationDelegate, IMvxApplicationDelegate
{
    public UIWindow MainWindow { get; set; }
    /* Update all the Window references in this class to use MainWindow instead as well! */
}
```

I'll close this now, but feel free to comment if you disagree or have any further problems, and I'll see what I can do.

FWIW this was one of the most interesting issues I've had to diagnose in a while, so thanks a lot for taking the time to create a test project I could use to reproduce it!

**Comment by rolfbjarne** [comment]
> Wow, thanks for the explanation. I am happy you have figured out what went wrong (and that you enjoyed it :D ).
> 
> One final question though, is our work around fine? Or will that cause issues in the future?
> 
> ```
> The "Main.storyboard" file has a property called "initialViewController" which is set to the DevicesView (via it's storyboard ID).
>  If we remove that property, it appears to fix the problem we are having. 
> ```
> 
> edit: spelling

Yes, that should work fine too I believe.

**Comment by Joost-Jens-Luminis** [comment]
In that case I consider this issue resolved. Thank you so much for your hard work on this, it's much appreciated.
