### ISSUE TITLE
"clang++ Undefined symbols" build error when building bindings library with latest workload version 

### ISSUE THREAD

**Issue by snechaev** [xamarin/xamarin-macios#21242]
### Apple platform

macOS

### Framework version

net8.0-*

### Affected platform version

.net 8.0.401/macos 14.5.8030

### Description

After macos workload update I can't build the simple binding project, based on the [`finder` sample](https://github.com/xamarin/xamarin-macios/blob/cfcfd42947c3b5d06b1351372c237e39a8b0f3e6/tests/scriptingbridge/finder.cs) from this repo. I get the following errors:
```
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk.net8.0_14.5/14.5.8030/targets/Xamarin.Shared.Sdk.targets(1641,3): error : clang++ exited with code 1: [/Users/sergey/work/macOSApp1/macOSApp1/macOSApp1.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk.net8.0_14.5/14.5.8030/targets/Xamarin.Shared.Sdk.targets(1641,3): error : Undefined symbols for architecture x86_64: [/Users/sergey/work/macOSApp1/macOSApp1/macOSApp1.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk.net8.0_14.5/14.5.8030/targets/Xamarin.Shared.Sdk.targets(1641,3): error :   "_OBJC_CLASS_$_FinderApplication", referenced from: [/Users/sergey/work/macOSApp1/macOSApp1/macOSApp1.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk.net8.0_14.5/14.5.8030/targets/Xamarin.Shared.Sdk.targets(1641,3): error :      -exported_symbol[s_list] command line option [/Users/sergey/work/macOSApp1/macOSApp1/macOSApp1.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk.net8.0_14.5/14.5.8030/targets/Xamarin.Shared.Sdk.targets(1641,3): error : ld: symbol(s) not found for architecture x86_64 [/Users/sergey/work/macOSApp1/macOSApp1/macOSApp1.csproj]
/usr/local/share/dotnet/packs/Microsoft.macOS.Sdk.net8.0_14.5/14.5.8030/targets/Xamarin.Shared.Sdk.targets(1641,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation) [/Users/sergey/work/macOSApp1/macOSApp1/macOSApp1.csproj]
    0 Warning(s)
    1 Error(s)
```

The same project without any changes builds successfully with the oldest macos workload `14.2.8078/8.0.100`.

### Steps to Reproduce

Download and build the project `macOSApp1.csproj`
[macOSApp1.zip](https://github.com/user-attachments/files/17013644/macOSApp1.zip)

### Did you find any workaround?

As a workaround I downgraded to the older `macos` workload with the following steps
1. Create the `workload.json` with the following contents:
   ```
   {
     "microsoft.net.sdk.macos": "14.2.8078/8.0.100"
   }
   ```
2. Run `sudo dotnet workload install macos --from-rollback-file workload.json`
3. Clean all build artifacts for both app & binding projects (including `bin & obj` folders)
4. Build the project.

### Build logs

[msbuild.binlog.zip](https://github.com/user-attachments/files/17013734/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
> After macos workload update I can't build the simple binding project, based on the [`finder` sample](https://github.com/xamarin/xamarin-macios/blob/cfcfd42947c3b5d06b1351372c237e39a8b0f3e6/tests/scriptingbridge/finder.cs) from this repo.

That sample code is quite old, and not correct unfortunately.

I got the code to work by:

1. Changing the binding project to define protocols instead (in particular make sure to *not* have the BaseType attribute):

    ```cs
    [Protocol]
    interface FinderApplication
    {
        [Export("version")]
        string Version { get; }
    }
    ```

2. In you main project, define a class that inherits from `SBApplication`, implements the protocol, and has a NativeHandle constructor:

    ```cs
    class FinderApplication : SBApplication, IFinderApplication
    {
        protected FinderApplication (NativeHandle handle)
            : base (handle) {}
    }
    ```

3. Cast the return value from the `SBApplication.GetApplication` method to the protocol, and use that:

    ```cs
    var finder = (IFinderApplication?) SBApplication.GetApplication<FinderApplication>("com.apple.finder");
    var v = $"Finder is null: {finder is null}\nVersion: {finder?.Version ?? "null"}";
    Console.WriteLine (v);
    ```

    On my machine, this prints:

    ```shell
    Finder is null: False
    Version: 14.6
    ```

Complete working project: 
[macOSApp1-99add4f.zip](https://github.com/user-attachments/files/17015693/macOSApp1-99add4f.zip)

**Comment by snechaev** [comment]
Many thanks for your help! I can confirm that the updated version works with the latest workload for both the simple `finder` bindings project and for the more complicated `SBApplication` binding in my real project.

Sorry for the false alarm, it looks like I missed some announcement about the changes in the binding system.
