### ISSUE TITLE
[Github issue templates] Unable to attach a build log in the new issue form

### ISSUE THREAD

**Issue by snechaev** [xamarin/xamarin-macios#21243]
### Apple platform

macOS

### Framework version

Other

### Affected platform version

not applicable

### Description

When creating the new issue, it is impossible to attach the zipped build log by drag & drop into the corresponding input field. Looks like there is wrong input type in the form. 

Environment: Chrome 128 under the macOS Sonoma.

### Steps to Reproduce

1. Click "new issue" on github, select the issue type (let's say "Other")
2. Try to drag&drop the .zip file (zipped binlog) into the "relevant log output" field. 

### Did you find any workaround?

It is possible to drag & drop the `zip` file into the other field (like this one, dedicated to a workaround) and then copy the link into the "log output" field. However, the link will be not clickable.

**Comment by rolfbjarne** [comment]
Thanks for the report!

This should be fixed once https://github.com/xamarin/xamarin-macios/pull/21245 is merged.
