### ISSUE TITLE
clang++ exited with code 1: Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_CYFMonitor", referenced from:      -exported_symbol[s_list] command line option ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)	TestApp4Binding	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_17.5\17.5.8030\targets\Xamarin.Shared.Sdk.targets	1641

### ISSUE THREAD

**Issue by Al-Mos** [xamarin/xamarin-macios#21283]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

VS 17.11.3, Xcode 15.4, VS for Mac 17.6.14, Sonoma 14.6.1

### Description

When binding an Obj C library on a project being migrated from Xamarin to MAUI, we have worked through the required changes, reviewed these support forums and applied the suggested resolutions to similar issues seen by others, but no resolution as yet. We have created an example solution with the binding library, and a test app included.  Both referencing the library directly and creating a package show the same issue, and it's consistent now on both VS for Windows and VS for Mac.

[Ak.zip](https://github.com/user-attachments/files/17094459/Ak.zip)

### Steps to Reproduce

A solution has been provided showing the build issue referencing the binding library. 

### Did you find any workaround?

None.

**Comment by LeadAssimilator** [comment]
I don't believe you can embed different runtime platforms of the same Framework with different NativeReference tags like you are attempting.  The name of the resource for both NativeReference tags evaluates to AkamaiBMP.framework in your case. Because they have the same name, only one of them is included as an embedded resource with NoBindingEmbedding=false or as a directory resource if true, while the other is silently discarded, and thus the wrong runtime platform can be used in the link step, leading to the error you are seeing.

While there are other ways, since you already have an xcframework, you could just reference it directly and set NoBindingEmbedding=true (embedded xcframeworks seeming still don't work for some reason, nor does referencing a .zip of them, making it impossible to avoid path limits on windows when doing remote builds or target maccatalyst with dynamic xcframeworks because they have symlinks, without creating a nuget, but I digress). You are also missing referenced Frameworks required to complete the link. If you use the following, everything should work:

```XML
  <PropertyGroup>
    <NoBindingEmbedding>true</NoBindingEmbedding>
  </PropertyGroup>

  <ItemGroup>
    <NativeReference Include="AkamaiBMP.xcframework">
      <Kind>Framework</Kind>
      <SmartLink>False</SmartLink>
      <LinkerFlags>-ObjC</LinkerFlags>
      <Frameworks>Accelerate CoreMotion CoreTelephony QuartzCore WebKit</Frameworks>
    </NativeReference>
  </ItemGroup>
```

**Comment by rolfbjarne** [comment]
> nor does referencing a .zip of them, making it impossible to avoid path limits on windows when doing remote builds or target maccatalyst with dynamic xcframeworks because they have symlinks, without creating a nuget, but I digress

You can set `CompressBindingResourcePackage=true` to create a zipped version of the .resources directory we otherwise create next to the binding assembly.

Otherwise we'll automatically set `CompressBindingResourcePackage=true` if the native reference contains a symlink.

There's also a way to reference a zipped xcframework from an executable project:

```xml
<None Include="path/to/MyFramework.xcframework.zip" CopyToOutputDirectory="PreserveNewest" />
```

But you're correct in that it's not possible to reference a zipped xcframework from a binding project. Feel free to submit an issue if you're interested, and we can look into implementing it.

**Comment by rolfbjarne** [comment]
@Al-Mos as @LeadAssimilator already said, don't reference the individual .framework directories inside the .xcframework, just reference the .xcframework itself (once).

This diff makes your projects compile for me:

```diff
diff --git a/AkamaiBMP.iOSCore/AkamaiBMP.iOSCore.csproj b/AkamaiBMP.iOSCore/AkamaiBMP.iOSCore.csproj
index bcfcaf3..3e85cec 100644
--- a/AkamaiBMP.iOSCore/AkamaiBMP.iOSCore.csproj
+++ b/AkamaiBMP.iOSCore/AkamaiBMP.iOSCore.csproj
@@ -13,7 +13,6 @@
     <AssemblyVersion>3.4.0</AssemblyVersion>
     <ImplicitUsings>enable</ImplicitUsings>
        <IsBindingProject>true</IsBindingProject>
-    <NoBindingEmbedding>false</NoBindingEmbedding>
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
     <OutputPath>bin\Debug</OutputPath>
@@ -36,15 +35,11 @@
     <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
   </ItemGroup>
   <ItemGroup>
-    <NativeReference Include="AkamaiBMP.xcframework\ios-arm64_x86_64-simulator\AkamaiBMP.framework">
-      <Kind>Framework</Kind>
-      <SmartLink>False</SmartLink>
-      <LinkerFlags>-ObjC</LinkerFlags>
-    </NativeReference>
-    <NativeReference Include="AkamaiBMP.xcframework\ios-arm64_arm64e\AkamaiBMP.framework">
+    <NativeReference Include="AkamaiBMP.xcframework">^M
       <Kind>Framework</Kind>
       <SmartLink>False</SmartLink>
       <LinkerFlags>-ObjC</LinkerFlags>
+      <Frameworks>Accelerate CoreMotion CoreTelephony QuartzCore WebKit</Frameworks>^M
     </NativeReference>
   </ItemGroup>
   <ItemGroup>
```

Can you try this and see if it works for you?

**Comment by Al-Mos** [comment]
> I don't believe you can embed different runtime platforms of the same Framework with different NativeReference tags like you are attempting. The name of the resource for both NativeReference tags evaluates to AkamaiBMP.framework in your case. Because they have the same name, only one of them is included as an embedded resource with NoBindingEmbedding=false or as a directory resource if true, while the other is silently discarded, and thus the wrong runtime platform can be used in the link step, leading to the error you are seeing.
> 
> While there are other ways, since you already have an xcframework, you could just reference it directly and set NoBindingEmbedding=true (embedded xcframeworks seeming still don't work for some reason, nor does referencing a .zip of them, making it impossible to avoid path limits on windows when doing remote builds or target maccatalyst with dynamic xcframeworks because they have symlinks, without creating a nuget, but I digress). You are also missing referenced Frameworks required to complete the link. If you use the following, everything should work:
> 
> ```
>   <PropertyGroup>
>     <NoBindingEmbedding>true</NoBindingEmbedding>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <NativeReference Include="AkamaiBMP.xcframework">
>       <Kind>Framework</Kind>
>       <SmartLink>False</SmartLink>
>       <LinkerFlags>-ObjC</LinkerFlags>
>       <Frameworks>Accelerate CoreMotion CoreTelephony QuartzCore WebKit</Frameworks>
>     </NativeReference>
>   </ItemGroup>
> ```

Hi, thanks for the pointer. I am sure I had previously read we needed to use NoBindingEmbedding, but that has made a difference.

**Comment by Al-Mos** [comment]
> @Al-Mos as @LeadAssimilator already said, don't reference the individual .framework directories inside the .xcframework, just reference the .xcframework itself (once).
> 
> This diff makes your projects compile for me:
> 
> ```diff
> diff --git a/AkamaiBMP.iOSCore/AkamaiBMP.iOSCore.csproj b/AkamaiBMP.iOSCore/AkamaiBMP.iOSCore.csproj
> index bcfcaf3..3e85cec 100644
> --- a/AkamaiBMP.iOSCore/AkamaiBMP.iOSCore.csproj
> +++ b/AkamaiBMP.iOSCore/AkamaiBMP.iOSCore.csproj
> @@ -13,7 +13,6 @@
>      <AssemblyVersion>3.4.0</AssemblyVersion>
>      <ImplicitUsings>enable</ImplicitUsings>
>         <IsBindingProject>true</IsBindingProject>
> -    <NoBindingEmbedding>false</NoBindingEmbedding>
>    </PropertyGroup>
>    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
>      <OutputPath>bin\Debug</OutputPath>
> @@ -36,15 +35,11 @@
>      <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
>    </ItemGroup>
>    <ItemGroup>
> -    <NativeReference Include="AkamaiBMP.xcframework\ios-arm64_x86_64-simulator\AkamaiBMP.framework">
> -      <Kind>Framework</Kind>
> -      <SmartLink>False</SmartLink>
> -      <LinkerFlags>-ObjC</LinkerFlags>
> -    </NativeReference>
> -    <NativeReference Include="AkamaiBMP.xcframework\ios-arm64_arm64e\AkamaiBMP.framework">
> +    <NativeReference Include="AkamaiBMP.xcframework">^M
>        <Kind>Framework</Kind>
>        <SmartLink>False</SmartLink>
>        <LinkerFlags>-ObjC</LinkerFlags>
> +      <Frameworks>Accelerate CoreMotion CoreTelephony QuartzCore WebKit</Frameworks>^M
>      </NativeReference>
>    </ItemGroup>
>    <ItemGroup>
> ```
> 
> Can you try this and see if it works for you?

Hi, thanks for this assistance, appreciated. Whilst I have attempted several approaches to the Native reference, and added <Frameworks> previously I had always kept NoBindingEmbedding set as I recalled reading it was needed in MAUI. However, with that change, I can reference it as a project library in a solution. I attempted creating a NUGET package and whilst it creates the package successfully, when installed in an app, it again fails to link with the same error. 

I have a tight timeline this week, but will try again with the NUGET package next week, and come back with any further findings, but if you do have any suggestions as to why it still fails, would be grateful to hear them.

**Comment by rolfbjarne** [comment]
> I have a tight timeline this week, but will try again with the NUGET package next week, and come back with any further findings, but if you do have any suggestions as to why it still fails, would be grateful to hear them.

Can you provide an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) for the failure?

**Comment by Al-Mos** [comment]
> > I have a tight timeline this week, but will try again with the NUGET package next week, and come back with any further findings, but if you do have any suggestions as to why it still fails, would be grateful to hear them.
> 
> Can you provide an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) for the failure?

[TestApp4Binding_Debug_AnyCPU_Build_2024-10-03T15_11_26.9216093+01_00.zip](https://github.com/user-attachments/files/17245593/TestApp4Binding_Debug_AnyCPU_Build_2024-10-03T15_11_26.9216093%2B01_00.zip)


Thanks.
