### ISSUE TITLE
Request for binding NSToolbarItemVisibilityPriority

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#21298]
### Apple platform

macOS

### Framework version

net8.0-*

### Affected platform version

.NET 8

### Description

It looks like [NSToolbarItemVisibilityPriority](https://developer.apple.com/documentation/appkit/nstoolbaritemvisibilitypriority?language=objc) is not bound. It would be nice if it was, similar to [NSStackViewVisibilityPriority](https://developer.apple.com/documentation/appkit/nsstackviewvisibilitypriority?language=objc).

This is used to assign [visibilityPriority](https://developer.apple.com/documentation/appkit/nstoolbaritem/1527947-visibilitypriority?language=objc)

### Steps to Reproduce

```
var toolbarItem = new NSMenuToolbarItem("id");
toolbarItem.VisibilityPriority = NSToolbarItemVisibilityPriority.Low;
```

### Did you find any workaround?

I can still assign an integer, but using an enum or constant would be more explanatory.

**Comment by rolfbjarne** [comment]
Unfortunately we can't change the property type of the "VisibilityProperty" in order to keep binary compatibility (unless we introduce a different property, but that's somewhat clunky).

However, I can add some documentation to the property, so hopefully that alleviates the problem.

**Comment by tipa** [comment]
No, the property type is fine (just like `NSStackView.VisibilityPriority` also is of type `float`), but maybe the constants could be specified somewhere, like this:
```
public const int VisibilityPriorityStandard = 0;
public const int VisibilityPriorityLow = -1000;
public const int VisibilityPriorityHigh = 1000;
public const int VisibilityPriorityUser = 2000;
```
