### ISSUE TITLE
Xamarin ios push notification not working

### ISSUE THREAD

**Issue by Vice95** [xamarin/xamarin-macios#21300]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

Vs 2022 For MAC

### Description

I have a problem with push notifications on a xamarin project

situation: I have a working xamarin android / ios code with bundle id com.xxxx.abc.

### Steps to Reproduce

 I have to republish the same app with a different brand, I created a new plist, new registration on firebase, new google-service.plist file, but the notifications do not arrive as on the first app. Does anyone have similar experiences?

**Comment by rolfbjarne** [comment]
It's likely there's something wrong with the configuration in the new projects somehow.

I would compare the app bundles (the .app directory) between the Xamarin app and the .NET app, to see if there are any differences that look suspicious. In particular pay attention to the Info.plist file in each app bundle, and any other plist files.

**Comment by Vice95** [comment]
I checked the plist files are practically the same, even the project configurations (I created different configurations to change the themes, import the appropriate plist).
I inserted a pop up when registering firebase and I get the fcmtoken even on apps that do not receive notifications

**Comment by rolfbjarne** [comment]
Can you upload an .ipa we can use to investigate?
