### ISSUE TITLE
Device freezes and not able to hit breakpoints when disconnecting USB and reattaching it while debugging.

### ISSUE THREAD

**Issue by haavamoa** [xamarin/xamarin-macios#21310]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

.NET 8.0.100

### Description

I upgraded to Xcode 16 last week, but after reading [this](https://github.com/xamarin/xamarin-macios/issues/20802) post I removed it and installed Xcode 15.4. After doing so, I started noticing that debugging my app with a device sometimes freezes the app and I loose breakpoints.

Setup:
- 2x devices, iOS 17.5.1 and iOS 18.0. Same issue for both.
- Using Intellij Rider and VS Code + Meteor.  Same issue for both.
- Debugging using USB. 

It seems like this is a known issue from [Xcode 16 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes#Devices)

I want to create this issue so others can comment on their workarounds if others are experiencing the same behaviour as me.

### Steps to Reproduce

1. Connect a iPhone to your Mac. 
2. Debug a MAUI app, make sure you can set breakpoints and they are hit.
3. Disconnect the USB
4. Connect the USB
5. Start debugging after it was connected.
6. Notice that breakpoints is not hit and the app randomly freezes for a couple of minutes.

### Did you find any workaround?

- It seems like rebooting my device stops the issue, but once I disconnect the USB and reattach it, the bug seem to come back.

- It seems like this is a known issue from [Xcode 16 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes#Devices), and the workaround mentioned by Apple seems to work for me.

**Comment by rolfbjarne** [comment]
This is interesting, and I don't really have any ideas what might be causing it, except the Xcode issue you linked to.

* Did your colleague who can also reproduce this ever install Xcode 16?
* Can you try adding this to your csproj to see if it makes a difference (this might only work with VS, not VSCode, nor any other IDEs):

    ```xml
    <PropertyGroup>
        <IOSDebuggerConnectOverUsb>false</IOSDebuggerConnectOverUsb>
		<IOSDebugOverWiFi>true</IOSDebugOverWiFi>
    </PropertyGroup>
    ```

**Comment by haavamoa** [comment]
> * Did your colleague who can also reproduce this ever install Xcode 16?

Yes.

> * Can you try adding this to your csproj to see if it makes a difference (this might only work with VS, not VSCode, nor any other IDEs):
>   ```
>   <PropertyGroup>
>       <IOSDebuggerConnectOverUsb>false</IOSDebuggerConnectOverUsb>
>   	<IOSDebugOverWiFi>true</IOSDebugOverWiFi>
>   </PropertyGroup>
>   ```

I tried it running Intellij Rider, there is no difference.

--- 
Unfortunately, it now happened again and I tried following my own workarounds, none of them works :( 

In this scenario, I lost breakpoints from a USB disconnect. I tried to turn off Wifi on Mac and Airplane mode on device. I disconnected the USB and reattached it. Cleaned my bin folders, and started debugging. No breakpoints is hitting.
I tried rebooting the device, start cleaned my bin folders and started debugging. No breakpoints is hit.

I closed the app, and Intellij Rider still thinks my app is running, with breakpoints disabled:
![image](https://github.com/user-attachments/assets/3586ac01-4ab2-41ba-91f3-e88d93b66082)

:( So now I am completely stuck debugging my iOS app.

**Comment by rolfbjarne** [comment]
Do you see the same behavior if you create a new project?

**Comment by haavamoa** [comment]
I can try a brand new project, but I see the same behaviour for all of my three app project I work on in my day job. I'll test a new one now.

**Comment by haavamoa** [comment]
Just created a new project, no breakpoints are hit :(
![image](https://github.com/user-attachments/assets/d62c0c34-2324-4d67-867b-9bbb6cc0d34d)

**Comment by haavamoa** [comment]
Tried my workaround for the new project when this bug appeared:  

I just turned off Wifi + enabled Airplane mode, then redeployed, it now hits my breakpoint.
Once I noticed it hit my breakpoint, I turn on Wifi + disable Airplane mode, then redeployed, it now hits my breakpoint again.

I then headed over to DIPS.Mobile.UI (original project I had issue with), it still has issues and no breakpoint is hit.

This is confusing...

**Comment by rolfbjarne** [comment]
This is quite puzzling, but here's an idea to try to fully revert to Xcode 15.4, which involves re-installing the packages from Xcode 15.4 that installs stuff into the system (replacing the ones that were installed by Xcode 16.0).

The packages are in `/Applications/Xcode.app/Contents/Resources/Packages`, and I believe they have to be installed in a certain order to not fail.

Here's a shell script to do it (make sure to update the path to Xcode):

```shell
XCODE=/Applications/Xcode_15.4.0.app
PKGS="MobileDevice.pkg MobileDeviceDevelopment.pkg XcodeSystemResources.pkg"
for pkg in $PKGS; do
	echo "Installing $pkg"
	sudo /usr/sbin/installer -dumplog -verbose -pkg "$XCODE/Contents/Resources/Packages/$pkg" -target /
	echo "Installed $pkg"
done
```

Warning: I believe this to be safe, but it may leave your system in a confused state where things work worse than before.

**Comment by haavamoa** [comment]
Fortunately, [you decided to launch Xcode 16 support with .NET 8](https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-8.0.1xx-xcode16.0-8303), for me this means that I can upgrade to it. Hopefully it will fix things for me :)
I will report back here once I've done so.

**Comment by haavamoa** [comment]
Alright, good news. This looks like it god resolved.
So I had issues with DIPS.Mobile.UI project yesterday. Today I upgraded to Xcode 16 and the new Workloads. When I started the app, it failed to connect to debugger instantly. I cleaned my bin folders and redeployed. Now it works like it should.
Even disconnecting and reconnecting USB works like before.

I will force this into our pipeline for my colleagues and give feedback here if we notice problems with the new update :) 

Have a nice weekend!

**Comment by rolfbjarne** [comment]
> Alright, good news. This looks like it got resolved. So I had issues with DIPS.Mobile.UI project yesterday. Today I upgraded to Xcode 16 and the new Workloads. When I started the app, it failed to connect to debugger instantly. I cleaned my bin folders and redeployed. Now it works like it should. Even disconnecting and reconnecting USB works like before.
> 
> I will force this into our pipeline for my colleagues and give feedback here if we notice problems with the new update :)
> 
> Have a nice weekend!

That's great news! Hoping it will stay working 🤞

**Comment by Vetle444** [comment]
@rolfbjarne I still have issues after upgrading to xcode 16 and xamarin.ios 8303. However, it appears it is only reproduced when I am at the office, and not when I am working from home, where I do not have access to our internal network.

**Comment by haavamoa** [comment]
I just realised that I had to downgrade iOS workload due to this issue:
https://github.com/dotnet/maui/issues/25139#issuecomment-2403007524

Which might be why I suddenly started getting this issues again.

**Comment by timothyhead** [comment]
I had a similar problem, just running the app on the simulator in Xcode 16. unchecking Debug executable, running the app and then checking it again is working for the time being.
