### ISSUE TITLE
Builds auto selecting dotnet-8.0.1xx-xcode16.0-8303, but not ready for Xcode 16

### ISSUE THREAD

**Issue by justin-caldicott** [xamarin/xamarin-macios#21316]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

dotnet-8.0.1xx-xcode16.0-8303, 8.0.402.1

### Description

We're building an iOS app using dotnet8 without MAUI. In our pipeline (Azure pipelines, `macOS-14` image), we first:
- UseDotNet@2, 8.0.x
- workload install ios

The builds have swapped to using dotnet-8.0.1xx-xcode16.0-8303 since its release recently. Our builds have started failing, and reading the release notes it requires Xcode 16. We're not ready to swap to Xcode 16 yet as we're doing a patch release. The error probably doesn't matter if the issue is simply that Xcode 16 is required, but for completeness the error using Xcode 15.4 is:
```
/Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UITextView.g.cs(3343): error MT4162: The type 'UIKit.UITextFormattingViewController' (used as a parameter in UIKit.UITextView/_UITextViewDelegate.DidBeginFormatting) is not available in iOS 17.5 (it was introduced in iOS 18.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode).
```

I did try selecting Xcode 16 anyway, [but hit another issue](https://github.com/xamarin/xamarin-macios/issues/19157).

**How can we run our builds against the previous `dotnet-8.0.1xx-xcode15.4-8030` release?** It was working great for us. I note that the _was_ an `--sdk-version` flag when installing a workload, [but that's now removed](https://github.com/dotnet/sdk/issues/36018).

### Steps to Reproduce

Presumably, though I've only tried with our app:

1. Make a simple app containing a UITextView
2. Build it with dotnet-8.0.1xx-xcode16.0-8303 and Xcode 15.4 selected.

### Did you find any workaround?

None yet, our release is blocked.

**Comment by richardfric** [comment]
There is a workaround:
`workload install ios --version 8.0.401`

however it won't install Microsoft.iOS.Sdk [8.0.30](https://www.nuget.org/packages/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8030) but older [8.0.20](https://www.nuget.org/packages/Microsoft.iOS.Sdk.net8.0_17.5/17.5.8020)

**Comment by justin-caldicott** [comment]
Thanks @richardfric - I was just trying similar things (TIL what a workload set is), tried `8.0.402` but it says Workload ID not recognized. Maybe 17.5.8030 is not in a workload set. Open to suggestions @rolfbjarne!

**Comment by justin-caldicott** [comment]
OK, strike that last comment. I messed up the command line. 🤦 

There _is_ an 8.0.402 workload set and it does include `Microsoft.NET.Sdk.iOS` `17.5.8030`.

`sudo dotnet workload install ios --version 8.0.402`

As per [a related discussion here](https://github.com/dotnet/maui/issues/24940#issuecomment-2377426461), it's possible to [see what's inside a workload set](https://nuget.info/packages/Microsoft.NET.Workloads.8.0.400/8.402.0).

**Comment by justin-caldicott** [comment]
Closing as it is possible to pin the version using workloads sets. The grouping of version numbers like this is quite opaque, so it'd be nice to see that improved, but that's not an issue with this repo and I believe it's already tracked.
