### ISSUE TITLE
Visual Studio for Mac can't use Xcode 16

### ISSUE THREAD

**Issue by Zhangos** [xamarin/xamarin-macios#21326]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

.Net8.0.402

### Visual Studio for Mac can't use Xcode 16

I can't deploying to iOS in the environment below。

- VisualStudio for Mac:
17.6.14 (build 413)

- SDK:
.Net8.0.402
 
- Microsoft.iOS:
18.0.8303

- Xcode:
16.0(16A242d)
 
- Error:
Could not load the framework 'IDEDistribution' (path: /Applications/Xcode.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/IDEDistribution):
dlopen(/Applications/Xcode.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/IDEDistribution, 0x0001): Library not loaded: @rpath/AppThinning.framework/Versions/A/AppThinning

### Steps to Reproduce

1. create iOS project
2. deploying 

- VisualStudio for Mac:
17.6.14 (build 413)

- SDK:
.Net8.0.402
 
- Microsoft.iOS:
18.0.8303

- Xcode:
16.0(16A242d)

**Comment by rolfbjarne** [comment]
This is correct, Visual Studio for Mac won't work with Xcode 16.

Note that Visual Studio for Mac has been retired (https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/), so no more updates will be done.
