### ISSUE TITLE
[BrowserEngineKit] inappropriately referenced in .NET 8 MAUI build

### ISSUE THREAD

**Issue by bengavin** [xamarin/xamarin-macios#21324]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

.NET 8.0.402

### Description

After the most recent update to support Xcode 16 with .NET 8 projects, our submissions to the AppStore are now being flagged with the following error:

TMS-91017: Invalid SDK usage - The following frameworks aren’t permitted for apps using an alternative web browser engine: [BrowserEngineKit].

### Steps to Reproduce

1. Take an existing .NET 8 MAUI app, built using Xcode 15.4 set of tooling
2. Update Azure DevOps hosted build pipeline to point to Xcode 16 [to allow the build to complete]
3. Note that your submitted application fails with the BrowserEngineKit error

---

# Workaround

Add this to your project file (csproj):

```xml
<Target Name="DoNotLinkWithBrowserEngineKit" AfterTargets="_ComputeLinkNativeExecutableInputs">
	<ItemGroup>
		<_NativeExecutableFrameworks Remove="BrowserEngineKit" />
	</ItemGroup>
</Target>
```

**Comment by rolfbjarne** [comment]
Would you be able to provide us with the .ipa you uploaded to the App Store?

**Comment by bengavin** [comment]
> Would you be able to provide us with the .ipa you uploaded to the App Store?

@rolfbjarne -
I would think so, but I'll verify internally here.  Is there an email address I can forward it over to?

**Comment by rolfbjarne** [comment]
You can send it to Rolf.Kvinge@microsoft.com

**Comment by bengavin** [comment]
Sent, it's not quite an IPA, but it's all the unsigned contents of what becomes the IPA.  I can build the IPA by hand if necessary, just let me know.

**Comment by yalamandarao** [comment]
I am currently experiencing issues while uploading my macOS app to the App Store. Previously, I was able to upload the application without any issues, and it was working fine. After I updated the .NET workload, I started encountering this problem.

Error : Invalid SDK usage. The following frameworks aren’t permitted for apps using an alternative web browser engine: [BrowserEngineKit]. (91017)

How to exclude the this package "BrowserEngineKit" ?

**Comment by yalamandarao** [comment]
> Would you be able to provide us with the .ipa you uploaded to the App Store?

MacOS can generate only .pkg file not ipa. Issue only in MacOS .NET 8 (macos -15.0.8303/8.0.100 - SDK 8.0.400).   Issue only release release for macOS

**Comment by ronanj2** [comment]
@rolfbjarne , I have the same issue, and can send an IPA. Will share via google drive in a few minutes.

**Comment by ejhg** [comment]
Same issue here.

**Comment by rolfbjarne** [comment]
I believe it's possible to work around this by adding the following to the main project file (csproj):

```xml
<Target Name="DoNotLinkWithBrowserEngineKit" AfterTargets="_ComputeLinkNativeExecutableInputs">
	<ItemGroup>
		<_NativeExecutableFrameworks Remove="BrowserEngineKit" />
	</ItemGroup>
</Target>
```

Can you try and see if that works?

**Comment by ValentinDutartreAdapt** [comment]
Hello,
I also encountered this problem today.
And this solution from rolfbjarne does work and, in the first tests, didn't affect my application. Thank you very much.

**Comment by bengavin** [comment]
I can also confirm this workaround is working for at least one of our apps.

**Comment by ejhg** [comment]
Thank you for the workaround!

**Comment by onlinefabster** [comment]
Tested the workaround and can confirm it works. Build a new release and submit to testflight, tested the application and everything seems to work alright.

**Comment by maroy1986** [comment]
I do confirm the workaround works on my end as well. Keeping an eye on this thread for a not "temporary" solution :)
