### ISSUE TITLE
VNVisionVersionNumber binding missing

### ISSUE THREAD

**Issue by tuanchien** [xamarin/xamarin-macios#21342]
### Apple platform

iOS, Mac Catalyst

### Framework version

net8.0-*

### Affected platform version

.NET 8

### Description

Is there any plan to add the `VNVisionVersionNumber` binding?

### Steps to Reproduce

n/a

### Did you find any workaround?

n/a

### Relevant log output

n/a

**Comment by rolfbjarne** [comment]
Confirmed; PR in progress.

**Comment by rolfbjarne** [comment]
It's bound as `VNUtils.VisionVersionNumber` (it won't be shipped until we add Xcode 16.1 support though).
