### ISSUE TITLE
UITraitCollection bindings

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#21377]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

.NET 8

### Description

Issue 1:
The [`traitCollectionWithTraitsFromCollections:` method](https://developer.apple.com/documentation/uikit/uitraitcollection/1623512-traitcollectionwithtraitsfromcol) is deprecated since iOS 17, but in the .NET bindings the method `FromTraitsFromCollections` is not marked as obsolete.

Issue 2:
I want to use the [`traitCollectionByModifyingTraits:` method](https://developer.apple.com/documentation/uikit/uitraitcollection/4134886-traitcollectionbymodifyingtraits) (which I think is the "replacement" for the deprecated method mentioned above) as demonstrated here: https://developer.apple.com/wwdc23/10057?time=146. The bindings do have `GetTraitCollectionByModifyingTraits` methods, but it does not provide an instance of `IUIMutableTraits` in the closure.

**Comment by rolfbjarne** [comment]
I can confirm our bindings are wrong, fix is in progress.

**Comment by rolfbjarne** [comment]
PR in progress.

Do you need a workaround until this is released (which will probably be together with Xcode 16.1 support, whenever that happens).

**Comment by tipa** [comment]
Thanks for the fix. I don't need a workaround, using the deprecated method seems to be working fine for now
