### ISSUE TITLE
clang++ framework 'DeviceDiscoveryExtension' not found

### ISSUE THREAD

**Issue by elias-ik** [xamarin/xamarin-macios#21395]
### Apple platform

Mac Catalyst

### Framework version

net8.0-*

### Affected platform version

dotnet 8.0.402,  workload: maui 8.0.82/8.0.100 SDK 8.0.400

### Description

We are unable to compile and get this error message. 

Error:
```
Error  : clang++ exited with code 1:
ld: framework 'DeviceDiscoveryExtension' not found
```

I have attached a sample repo (the default one created by Rider) which reproduces the error. 

This issue appeared with the latest workload release. My assumption these are the source #21175 & #20870 but not the cause.

Used Versions: 
MacOS: 15.1 Beta (24B5070a)
xCode: 16.0 beta 3 (16A5202i)
```
elias$ xcodebuild -version
Xcode 16.0
Build version 16A5202i
```
dotnet: 8.0.402
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-maccatalyst           8.0.82/8.0.100         SDK 8.0.100        
ios                        18.0.8303/8.0.100      SDK 8.0.100        
android                    34.0.143/8.0.100       SDK 8.0.100        
```

### Steps to Reproduce

1. Clone: https://github.com/elias-ik/Maui-Sample-Build-Fail
2. Make sure versions match described above
3. `dotnet run --project MauiApp1`

### Did you find any workaround?

I assume downgrading the workload to the previous release would mitigate the issue, sadly I am unaware how to do so. 
From [8303](https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-8.0.1xx-xcode16.0-8303) to [8033](https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-8.0.1xx-xcode15.4-8030)

### Relevant log output

[msbuild.binlog.zip](https://github.com/user-attachments/files/17305488/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
> xCode: 16.0 beta 3 (16A5202i)

The `DeviceDiscoveryExtension` framework was only added to Mac Catalyst in beta 6.

The fix is to update your Xcode 16 to the stable release.

**Comment by elias-ik** [comment]
thanks, i must have missed that
