### ISSUE TITLE
Assets file ‘C:\*\obj\project.assets.json' doesn't have a target for 'net9.0-ios'. Ensure that restore has run and that you have included 'net9.0-ios' in the TargetFrameworks for your project.

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-macios#21496]
Moved here from https://github.com/dotnet/maui/issues/25431
### Description

I have a solution with 6 projects and when i try to run a specific project in ios simulator(vs 2022 .net 9 rc2 sdk & maui workload) i get the error
Assets file ‘C:\*\obj\project.assets.json' doesn't have a target for 'net9.0-ios'. Ensure that restore has run and that you have included 'net9.0-ios' in the TargetFrameworks for your project.
all other projects runs okey.

i can build from problem succesfully usint dotnet cli.

### Steps to Reproduce

I have a solution with 6 projects and when i try to run a specific project in ios simulator(vs 2022 .net 9 rc2 sdk & maui workload) i get the error
Assets file ‘C:\*\obj\project.assets.json' doesn't have a target for 'net9.0-ios'. Ensure that restore has run and that you have included 'net9.0-ios' in the TargetFrameworks for your project.
all other projects runs okey.

The project should run in the ios simulator.

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

**Comment by last-Programmer** [comment]
Submitted feddback to Visual Studio

https://developercommunity.visualstudio.com/t/Cant-have-ApplicationDisplayVersion-Cond/10774775
