### ISSUE TITLE
Public symbols in native library become private in a resulting binary with .net 8

### ISSUE THREAD

**Issue by lexboss777** [xamarin/xamarin-macios#21495]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

VS for mac 17.6.14, .net 8

### Description

Hello, I've noticed a problem with .net 8 in iOS application (.net 7 runs fine).

The app uses native library included this way (the same issue with Frameworks):

```csproj
<MtouchExtraArgs>--nosymbolstrip -gcc_flags "-force_load SignFile.o"</MtouchExtraArgs>
```

In the repro project this native library has one method `my_native_test_method`.

```
$ nm SignFile.o
0000000000000000 T _my_native_test_method
                 U _printf
```

Notice the uppercase `T` in the output.

After app compilation with .net 8 the uppercase `T` becomes lowercase `t`.
```
$ nm bin/Debug/net8.0-ios/iossimulator-x64/SymbolsTest.app/SymbolsTest | grep my_native_test_method
0000000100005be0 t _my_native_test_method
```

With .net 7 this is not the case.
```
$ nm bin/Debug/net7.0-ios/iossimulator-x64/SymbolsTest.app/SymbolsTest | grep my_native_test_method
0000000100004a00 T _my_native_test_method
```

Adding explicit DllImport for .net 8 seems to be a workaround, but in the real project I have too many native methods, that I wouldn't want to write import for each.
```cs
[DllImport("__Internal")]
public static extern int my_native_test_method();
```

Also, the same happens with `S` type of symbols (i.e. `S` becomes `s`).

This behaviour is the problem because it breaks some internal logic for the native library (we use third-party library). I would want to know if this intended change?

### Steps to Reproduce

The repro project (you can checkout different commits to quickly switch between .net):
https://github.com/lexboss777/symbols_test

### Did you find any workaround?

Yes, explicit DllImport

**Comment by rolfbjarne** [comment]
Can you try adding this to your csproj:

```xml
<PropertyGroup>
    <_ExportSymbolsExplicitly>false</_ExportSymbolsExplicitly>
</PropertyGroup>
```

and see if that works?

> Adding explicit DllImport for .net 8 seems to be a workaround, but in the real project I have too many native methods, that I wouldn't want to write import for each.

Note that if you're not calling the P/Invokes, the signatures don't have to be correct.

This means it's fairly easy to create the DllImports using a script:

```shell
$ for symbol in $(nm -jgU SignFile.o | sed 's/^_//'); do printf "[DllImport (\"__Internal\")] static extern void $symbol () { }\n"; done

[DllImport ("__Internal")] static extern void my_native_test_method () { }
```

(if you've enabled full trimming, then you might have to add a Preserve attribute so that the trimmer doesn't trim the P/Invokes away)

**Comment by lexboss777** [comment]
Yes, with adding `_ExportSymbolsExplicitly` it works in the repro project, thanks! I'll try it out in the work project tomorrow. 

ㅤ
> This means it's fairly easy to create the DllImports using a script:
> 
> ```shell
> $ for symbol in $(nm -jgU SignFile.o | sed 's/^_//'); do printf "[DllImport (\"__Internal\")] static extern void $symbol () { }\n"; done
> 
> [DllImport ("__Internal")] static extern void my_native_test_method () { }
> ```

Oh, that's cool! 😎

**Comment by lexboss777** [comment]
> I'll try it out in the work project tomorrow.

In production project it works too!

**Comment by rolfbjarne** [comment]
> > I'll try it out in the work project tomorrow.
> 
> In production project it works too!

That's great!

I'm not sure there's anything to do for us here - the change in behavior was unintentional, but on the other hand your use case is not common (call into native functions without a DllImport), and the workaround works fine (and there's another workaround too - generate the DllImports), so I'm closing this.
