### ISSUE TITLE
question on .NET API documentation

### ISSUE THREAD

**Issue by AndrewTriesToCode** [xamarin/xamarin-macios#21514]
### Framework version

net8.0-*

### Affected platform version

up-to-date API documentation?

### Description

In browsing .NET documentation it is very confusing what is current and what is not supported. For example the API pages seem to reference that this SDK if for iOS12 =L
https://learn.microsoft.com/en-us/dotnet/api/?view=xamarin-ios-sdk-12

It seems a lot of documentation material from the old Xamarin branded stuff is marked out of support but there is no equivalent for the latest .NET for iOS supported stuff.

### Steps to Reproduce

browser around the .NET pages and you'll hit areas like https://learn.microsoft.com/en-us/previous-versions/xamarin/ios/ and in the API browser areas like https://learn.microsoft.com/en-us/dotnet/api/?view=xamarin-ios-sdk-12

**Comment by rolfbjarne** [comment]
This is a known issue, and we're tracking it here: #17396.
