### ISSUE TITLE
CultureInfo on iOS doesn't have all the information that Windows or Android have.

### ISSUE THREAD

**Issue by Joost-Jens-Luminis** [xamarin/xamarin-macios#21567]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

8.0.402

### Description

I am creating a language select UI in our app. On WIndows and Android I can use "CultureInfo.NativeName" to show the name in the native language. On iOS it just shows the language code.

Screentshots for maximum effect: (Using Korean to clearly show it, but it applies to all cultures).
Windows:
![image](https://github.com/user-attachments/assets/c7ac5cd8-c36c-41b8-88f2-2bb06eb7e4a9)

Android:
![image](https://github.com/user-attachments/assets/541b13b8-55b9-4e18-b003-31afa27f754a)

iOS:
![image](https://github.com/user-attachments/assets/e4b7c6b6-cc8b-4e41-8eed-d05233a3088d)

### Steps to Reproduce

I use the following code to get all the cultures:
```C#
                var allCultures = CultureInfo.GetCultures(CultureTypes.AllCultures);
                foreach (var c in allCultures)
                {
                    if (c.Name.StartsWith("ko-"))
                    {
/// Breakpoint here to see the culture info :)
                    }
                }
```

**Comment by rolfbjarne** [comment]
This issue was moved to dotnet/runtime#109444
