### ISSUE TITLE
Alternatives for StoreKit 1 deprecation in iOS 18.0

### ISSUE THREAD

**Issue by RamType0** [xamarin/xamarin-macios#21565]
### Apple platform

iOS, macOS, Mac Catalyst, tvOS

### Framework version

net8.0-*

### Affected platform version

.NET 8.0

### Description

According to [Apple Developer Documentation](https://developer.apple.com/documentation/storekit/skproductsresponse?language=objc)

Most of StoreKit 1 APIs are deprecated in iOS 18.0, macOS 15.0, Mac Catalyst 18.0, and tvOS 18.0.

But I am recognizing that StoreKit 2 bindings does not exist in MAUI.

How can we continue support of App Store purchase in MAUI ?

### Steps to Reproduce

1. Reference `SKProductsRequest` in code.
2. CA1422 warnings will be emitted.

**Comment by rolfbjarne** [comment]
Closing as a duplicate of #16893.

**Comment by RamType0** [comment]
You maybe mistaking what I mean with the word "deprecation".

For many years, StoreKit 1 has been marked as not recommended way, and we SHOULD use StoreKit 2 instead.

But as of iOS 18.0, StoreKit 1 is no longer working, and we MUST use StoreKit 2 instead.

**Comment by anose001** [comment]
Hi @RamType0 , have you found a workaround/solution for this?  I saw that [Microsofts recommended approach](https://learn.microsoft.com/en-us/samples/dotnet/maui-samples/cross-platform-billing-service/) for MAUI is StoreKit 1. Is it really not working anymore?

**Comment by NikKovIos** [comment]
@RamType0 
Storekit 1 is still working now. It deprecated, not removed.
