### ISSUE TITLE
Binding projects don't work in .NET 9 RC 2

### ISSUE THREAD

**Issue by ArunaYarra** [xamarin/xamarin-macios#21588]
### Apple platform

iOS

### Framework version

net9.0-*

### Affected platform version

.NET 9.0

### Description

We still face "dotnet" exited with code 150 issue though we installed the .NET 9 RTM (https://aka.ms/dotnet/9.0.2xx/daily/dotnet-sdk-osx-arm64.pkg).

AXAiOSBindings_MAUI net9.0-ios failed with 1 error(s) (0.5s)
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net9.0_18.0/18.0.9600-net9-rc2/tools/msbuild/iOS/Xamarin.Shared.targets(1776,3): error MSB6006: "dotnet" exited with code 150.

Please help me to overcome this issue.

Thanks,
Aruna

### Steps to Reproduce

Binding projects don't work in .NET 9

**Comment by rolfbjarne** [comment]
Can you get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) for the failure? That should show the exact versions of everything you have installed, in addition to a bit more about the actual failure.
