### ISSUE TITLE
[Nullability] NSView.Window & SuperView should be allowed to be null

### ISSUE THREAD

**Issue by snechaev** [xamarin/xamarin-macios#21598]
https://github.com/xamarin/xamarin-macios/blob/9ea3cff36c86b1c3c46fb0872543165046b507a8/src/appkit.cs#L16088-L16097

The current implementation of the `NSView.Window` marked as non-nullable. But the [Apple docs](https://developer.apple.com/documentation/appkit/nsview/1483301-window) states that:
> The value of this property is `nil` if the view is not currently installed in a window.

 The same thing with a `NSView.SuperView` - the [docs](https://developer.apple.com/documentation/appkit/nsview/1483737-superview): 
> The value of this property is nil when the view is not installed in a view hierarchy.

**Comment by tipa** [comment]
This change would finally resolve the false-positive warnings I get in Rider (at least partly): https://youtrack.jetbrains.com/issue/RSRP-494672

**Comment by snechaev** [comment]
> I believe the launchOptions parameter for [application:didFinishLaunchingWithOptions:](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application) should also be annotated as nullable.

I don't see this declaration anywhere except in the templates 
https://github.com/xamarin/xamarin-macios/blob/9ea3cff36c86b1c3c46fb0872543165046b507a8/dotnet/Templates/Microsoft.iOS.Templates/ios-tabbed/AppDelegate.cs#L10-L11

So it looks like this can be manually annotated when creating the project (the template should be fixed to avoid manual fixes in the future). @tipa, am I missing some use case (I have no experience with iOS)?

**Comment by snechaev** [comment]
by the way, the #21599 will only fix this for macos, not ios. I can add commits in the existing PR or create the new one.

**Comment by rolfbjarne** [comment]
> by the way, the #21599 will only fix this for macos, not ios. I can add commits in the existing PR or create the new one.
> 
> [`9ea3cff`/src/uikit.cs#L16921-L16929](https://github.com/xamarin/xamarin-macios/blob/9ea3cff36c86b1c3c46fb0872543165046b507a8/src/uikit.cs#L16921-L16929)

I've created a PR for iOS as well.
