### ISSUE TITLE
AOT+LLVM crashes starting with iOS 18_8303 workloads / Xcode 16

### ISSUE THREAD

**Issue by alexanderdibenedetto** [xamarin/xamarin-macios#21604]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

8.0.401, iOS 18_8303 workloads

### Description

When building then running a .NET MAUI 8 project after updating to Xcode 16 / iOS 18_8303 workloads (and confirming the latest workloads released today for iOS has the same issue), the app crashes on start with an "Address size fault". Many libraries seem to face issues using LLVM after updating to XCode 16 / compatible workloads; the previous version using Xcode 15.4 worked without issue using LLVM.

### Steps to Reproduce

1. File > New Project
2. Add libraries like System.Web.HttpUtility, System.Text.Json, etc (it affects dozens of libraries that I tested)
3. Add to CSPROJ:
	  ``` 
	  <MtouchUseLlvm>true</MtouchUseLlvm>
	  <MtouchLink>SdkOnly</MtouchLink>
	  <Optimize>true</Optimize>
	  <MtouchInterpreter>-all</MtouchInterpreter>
4. Observe a crash on app launch (see attached)
[crash-ios18-8303.log](https://github.com/user-attachments/files/17722535/crash-ios18-8303.log)

### Did you find any workaround?

You must downgrade to Xcode 15.4 / last supported workloads for 15.4 in order to use AOT, OR disable AOT (no LLVM, 	  <MtouchInterpreter>all</MtouchInterpreter> instead of -all). I tried finding libraries one by one that cause the crash and stopped after finding over 30 that cause crashes on launch - I'm not excluding a massive list one by one.

For performance reasons, it is incredibly important to not be forced into not aoting any libraries.


### Relevant logs

_No response_

**Comment by alexanderdibenedetto** [comment]
Here's a list of all the ones I found published by Microsoft alone that can have this issue:

System.Web.HttpUtility,System.Threading,System.Threading.Channels,System.Text.RegularExpressions,System.Text.Json,System.Text.Encodings.Web,System.Security.Cryptography,System.Security.Claims,System.Runtime.Serialization.Primitives,System.Runtime.Numerics,System.Private.Xml,System.Private.Uri,System.ObjectModel,System.Net.WebProxy,System.Net.WebHeaderCollection,System.Net.Sockets,System.Net.ServicePoint,System.Net.Security,System.Net.Requests,System.Net.NetworkInformation,System.Net.NameResolution,System.Net.Mail,System.Net.Http,System.Net.Http.Json,System.Memory,System.Linq,System.Linq.Expressions,System.IO.Compression,System.Drawing.Primitives,System.Diagnostics.TraceSource,System.Diagnostics.Process,System.Diagnostics.DiagnosticSource,System.Console,System.ComponentModel,System.ComponentModel.TypeConverter,System.ComponentModel.Primitives,System.Collections,System.Collections.Specialized,System.Collections.NonGeneric,System.Collections.Immutable,System.Collections.Concurrent,Microsoft.CSharp

**Comment by rolfbjarne** [comment]
I'm not able to reproduce this; could you attach a complete test project I can use?

**Comment by alexanderdibenedetto** [comment]
@rolfbjarne  here you go! thank you for all your help btw - I've always appreciated your responsiveness on this repository. If you deploy Release to iOS you can reproduce the crash. I should have mentioned you need to actually make use of one of the affected libraries; I've chosen the Microsoft.Extensions.Resilience library as the example. I used your tip about stripping symbols on another question in order to see that it is the same issue.
[llvmCrashDemo.zip](https://github.com/user-attachments/files/17742500/llvmCrashDemo.zip)

**Comment by rolfbjarne** [comment]
That project works for me when I run from the command line like this:

> dotnet build -t:Run /p:Configuration=Release /p:RuntimeIdentifiers=ios-arm64 /p:_DeviceName="Rolf's iPhone 15"

Are you using VS or VS Code?

**Comment by alexanderdibenedetto** [comment]
I can reliably reproduce this using the repository I uploaded. I'm building it using dotnet publish for Release mode, then uploading using Apple Configurator 2. I'm not sure what command you are doing; my dotnet installation for .NET 8 SDK doesn't include a -t:Run. Can you try again please? I uploaded stack traces of the crash above also.

**Comment by alexanderdibenedetto** [comment]
I'm still able to reproduce this with our app in the store, but having issues with creating a sample project that reliably reproduces it. Can I somehow private message you our IPA with this issue reproduced? 

I am still trying to nail what part of our production app causes the LLVM issue in a sample project. I for some reason was able to reproduce it earlier but now my sample project doesn't - only the production app project does.

**Comment by rolfbjarne** [comment]
> I'm still able to reproduce this with our app in the store, but having issues with creating a sample project that reliably reproduces it. Can I somehow private message you our IPA with this issue reproduced?

Yes, feel free to use a file-sharing service and send the link to Rolf.Kvinge@microsoft.com
