### ISSUE TITLE
"MsBuild was unable to connect to the Mac with Address=[...]"

### ISSUE THREAD

**Issue by abenadar** [xamarin/xamarin-macios#21602]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

17.11.5

### Description

> MSBuild was unable to connect to the Mac with Address='fe80::[...]' and User='[...]'. This connection is separate from Visual Studio and without it the project can't build. Please try building again or report this problem if the issue persists.

I wiped and re-installed MacOS to rollback to Sequoia a while ago and started running into the issue above. While pairing itself works, I cannot build or run my project anymore. 

Among the things I tried are:
- Repairing VS;
- Reinstalling Xcode 16.01 from the App Store rather than using the mancually installed version;
- Deleting the Xamarin caches on both devices;
- Removing the SessionId from the SDK.targets file as suggested in some comments from similar issues;

I attached the verbose build logs and the ones created on the Mac during the pairing process containing errors, but they are rather puzzling to me.

This is hindering me to upload some urgent updates to the App Store so any help would be much appreciated.

### Steps to Reproduce

Occurs when building or running the project.

### Did you find any workaround?

No.

### Build logs

[logs.zip](https://github.com/user-attachments/files/17703192/logs.zip)

**Comment by sabrigo** [comment]
the issue is not only related to mac, even in Windows after upgrading to .net 9.0 

Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.12.3

**Comment by ondrejnovotny** [comment]
Hi, my problem was ipv6 as seen in the error message. I have disabled ipv6 on both win and mac and restarted mac. Then added mac again with ipv4 address. Then it showed as name(ipaddress) Now i can connect.
