### ISSUE TITLE
Debugger not attaching Xcode 16 & .NET MAUI

### ISSUE THREAD

**Issue by jsabiometric** [xamarin/xamarin-macios#21644]
### Apple platform

iOS

### Framework version

net9.0-*

### Affected platform version

.NET 9.0.100

### Description

When running on a physical device, the debugger is not attaching correctly and we can't see `Console.WriteLine(...)`. Works fine on an iOS Simulator

The last line we see from the debug console is the following:

```
.../net9.0-ios/ios-arm64/BioSnap.app/Microsoft.Maui.Controls.HotReload.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

### Versions

Xcode version: Version 16.1 (16B40)
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
ios                        18.0.9617/9.0.100      SDK 9.0.100        
maui-tizen                 9.0.0/9.0.100          SDK 9.0.100        
```

### Steps to Reproduce

1. Create new MAUI project via Visual Studio Code
2. Debugger not attaching on physical Startup Device.

### Did you find any workaround?

Unfortunately not.

**Comment by rolfbjarne** [comment]
Do breakpoints work for you?

I can reproduce a problem with Console.WriteLine not showing up in VSCode, and a fix is coming for that, however the debugger works fine for me.

**Comment by jsabiometric** [comment]
> Do breakpoints work for you?
> 
> I can reproduce a problem with Console.WriteLine not showing up in VSCode, and a fix is coming for that, however the debugger works fine for me.

Hey!
I can confirm the debugger is working and break-points are running, it's just `Console.WriteLine` that's broken. Would be very appreciated if you took a look at it,
Thanks!
Kind regards.

**Comment by rolfbjarne** [comment]
OK, great, I've fixed that part, it'll be included in a future service release (probably not the first one, since it's rather imminent and it's too late, but it should be in the next one, whenever that happens to be).

**Comment by Felix-Dev** [comment]
@rolfbjarne Is it possible the issue reported here is the same issue causing debugging an iOS app on a physical device (haven't yet tested simulator) using Visual Studio on Windows to only work on first attempt in a VS session?

**Comment by rolfbjarne** [comment]
> @rolfbjarne Is it possible the issue reported here is related to the issue causing debugging an iOS app on a physical device (haven't yet tested simulator) using Visual Studio on Windows to only work on first attempt in a VS session?
> 
> [developercommunity.visualstudio.com/t/After-Installing-VS-1712-iOS-Debugging/10791670?sort=newest&topics=visual+studio+2019](https://developercommunity.visualstudio.com/t/After-Installing-VS-1712-iOS-Debugging/10791670?sort=newest&topics=visual+studio+2019)

No, that's something else.
