### ISSUE TITLE
Missing CFRunLoopSource constructor available for public

### ISSUE THREAD

**Issue by jpiechowiak** [xamarin/xamarin-macios#21640]
### Apple platform

Mac Catalyst

### Framework version

net8.0-*

### Affected platform version

All .Net

### Description

I'm trying to make some code for app written with .Net 8.0 and MAUI (MacCatalyst) which suppose to be published to AppStore with Sandbox. 
I would like to use some `IOKit` code to operate on USB.
I've found nice bindings here https://github.com/CartBlanche/IOKit-Sharp for Xamarin.Mac and sample project is working as expected. 

I was trying to convert it to the .Net version and I've issue with following piece of code: 

```csharp
var runLoopSource = new CFRunLoopSource (notificationRunLoopSource);
var runloop = NSRunLoop.Current;
var cfRunLoop = runloop.GetCFRunLoop ();
cfRunLoop.AddSource (runLoopSource, NSRunLoop.NSDefaultRunLoopMode);
```

There are two issues. One in first, second one in fourth line. 
I was able to easily fix enumeration issue:

```csharp
cfRunLoop.AddSource(runLoopSource, CFRunLoop.ModeDefault);
```

Unfortunately constructor is more challenging... 
According to history, it was changed by @rolfbjarne  in this commit https://github.com/xamarin/xamarin-macios/commit/67ac3eb4e4b5e4c09944a486a27023fa8d4dd078#diff-00726927aaa3219f32d0125a19fac0787d315fe20fb8415a78ff34b65977e0c0 and now it is internal when `NET` constant is defined: 

```csharp
#if NET
		internal CFRunLoopSource (IntPtr handle, bool owns)
#else
		public CFRunLoopSource (IntPtr handle, bool owns)
#endif
```

So in terms of `TargetFramework` defined like this:

```xml
<TargetFramework>net8.0-maccatalyst</TargetFramework>
```

I can't create instance of an object `CFRunLoopSource`. 

Is there a way to make this constructor public or any workaround? 

### Steps to Reproduce

Create new project with TargetFramework `net8.0-maccatalyst` and try to create instance of `CFRunLoopSource`

### Did you find any workaround?

No

**Comment by rolfbjarne** [comment]
This should work:

```cs
using ObjCRuntime;

var runLoopSource = Runtime.GetINativeObject<CFRunLoopSource> (notificationRunLoopSource, owns: false);
...
```

can you try this and see if it works for you?

**Comment by jpiechowiak** [comment]
@rolfbjarne
It works :) If it won't be added to bindings, then it could be closed with these workaround.

**Comment by rolfbjarne** [comment]
I'm glad it worked!

Calling `Runtime.GetINativeObject` is the supported way of creating such instances, so I'm closing this.

Happy coding!
