### ISSUE TITLE
App will not install on device with Sign in with Apple capability in the provisioning profile and com.apple.developer.applesignin key is in Entitlements.plist after publishing.

### ISSUE THREAD

**Issue by jfversluis** [xamarin/xamarin-macios#21645]
---
**Issue moved from dotnet/maui#25923**
- Please respond to @amilici.

---

_From @amilici on Monday, November 18, 2024 2:47:30 PM_

### Description

I'm not sure this is the correct place to report this.

App will not install on device when com.apple.developer.applesignin key is in Entitlements.plist after publishing. It is unable to find a valid provisioning profile. The Sign In with Apple capability is in the provisioning profile and it is valid. If I remove the com.apple.developer.applesignin key from the Entitlements.plist and publish again the app will install on a device.

### Steps to Reproduce

[msbuild.binlog.zip](https://github.com/user-attachments/files/17801994/msbuild.binlog.zip)
1. Have an app with the Sign in with Apple capability enabled on the Developer portal.
2. Make sure the provisioning profile for the app is updated and downloaded to the computer that will publish the app.
3. Add the key 
`<key>com.apple.developer.applesignin</key>
	<array>
		<string>Default</string>
	</array>`

 to the Entitlements.plist file.

1. Run the command dotnet publish with the configuration that uses the provisioning profile "dotnet publish -f net8.0-ios -c AdHoc -v n "
2. try to install the resulting *.ipa file.

App cannot be installed because its integrity could not be verified. The relevant console output is

-[IXSDataPromise cancelForReason:client:error:]: <IXSPromisedOutOfBandTransfer(0xbf8341e00) Name:security-promise Creator:App Store UUID:A5EB49F0-64B5-4743-A091-86B09C5C7C43 PercentComplete:1.000000 IsComplete:Y DiskUsageBytes:0> : canceled by client 17 for reason Error Domain=IXUserPresentableErrorDomain Code=14 "This app was not installed because its integrity could not be verified." UserInfo={NSUnderlyingError=0xbf82b7750 {Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ULxVAa/extracted/Payload/Guess81.app : 0xe8008015 (A valid provisioning profile for this executable was not found.)" UserInfo={NSLocalizedDescription=Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.ULxVAa/extracted/Payload/Guess81.app : 0xe8008015 (A valid provisioning profile for this executable was not found.), LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=79, FunctionName=

If I remove the com.apple.developer.applesignin from Entitlements.plist and run publish again I am able to install the resulting *.ipa.

Note: The app contains a Notification Service Extension.

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

iOS

### Affected platform versions

iOS 18.2, iOS 17.6

### Relevant log output

```shell
Detected signing identity:
                 
           Code Signing Key: "iPhone Distribution: GUESS/ INC (9P4GQ95Q3N)" (7AC26FB3E6F57E0027F48FE0BF8CE51EFAF83370)
           Provisioning Profile: "Guess NSE Ad-Hoc Distribution" (6fd235d1-9fdf-4b78-a291-a6c5ac43aadb)
           Bundle Id: com.guess.alert.GuessNSE
           App Id: 9P4GQ95Q3N.com.guess.alert.GuessNSE

//...

   _CodesignAppBundle:
         Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign 7AC26FB3E6F57E0027F48FE0BF8CE51EFAF83370 --entitlements /Users/amilici/Projects/guess/GuessNSE/obj/Release/net8.0-ios/iossimulator-arm64/net8.0-ios/ios-arm64/Entitlements.xcent /Users/amilici/Projects/guess/Guess81/bin/AdHoc/net8.0-ios/ios-arm64/Guess81.app/PlugIns/GuessNSE.appex
                 
         Tool /usr/bin/codesign execution started with arguments: -v --force --timestamp=none --sign 7AC26FB3E6F57E0027F48FE0BF8CE51EFAF83370 --entitlements /Users/amilici/Projects/guess/Guess81/obj/AdHoc/net8.0-ios/ios-arm64/Entitlements.xcent /Users/amilici/Projects/guess/Guess81/bin/AdHoc/net8.0-ios/ios-arm64/Guess81.app
                 
       _CodesignVerify:
         /usr/bin/codesign --verify -vvvv "-R=anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.1] exists and (certificate leaf[field.1.2.840.113635.100.6.1.2] exists or certificate leaf[field.1.2.840.113635.100.6.1.4] exists)" bin/AdHoc/net8.0-ios/ios-arm64/Guess81.app/PlugIns/GuessNSE.appex 
         bin/AdHoc/net8.0-ios/ios-arm64/Guess81.app/PlugIns/GuessNSE.appex: valid on disk
         bin/AdHoc/net8.0-ios/ios-arm64/Guess81.app/PlugIns/GuessNSE.appex: satisfies its Designated Requirement
         bin/AdHoc/net8.0-ios/ios-arm64/Guess81.app/PlugIns/GuessNSE.appex: explicit requirement satisfied
         /usr/bin/codesign --verify -vvvv "-R=anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.1] exists and (certificate leaf[field.1.2.840.113635.100.6.1.2] exists or certificate leaf[field.1.2.840.113635.100.6.1.4] exists)" bin/AdHoc/net8.0-ios/ios-arm64/Guess81.app 
         bin/AdHoc/net8.0-ios/ios-arm64/Guess81.app: valid on disk
         bin/AdHoc/net8.0-ios/ios-arm64/Guess81.app: satisfies its Designated Requirement
         bin/AdHoc/net8.0-ios/ios-arm64/Guess81.app: explicit requirement satisfied
```

**Comment by rolfbjarne** [comment]
Does it work if you use a developer certificate + developer provisioning profile?

And can you still reproduce if you create a new project from a template, copy over the bundle identifier + Entitlements.plist + codesigning properties? If not, please attach this project.

**Comment by amilici** [comment]
@rolfbjarne The behavior is the same with both the Development profile and the AdHoc profile.

I'll try to reproduce it with a new project with the same bundle id and Entitlements.plist.

**Comment by amilici** [comment]
I can reproduce it with a test project using the same bundle id and entitlements.plist: 
[TestApp.zip](https://github.com/user-attachments/files/17830834/TestApp.zip)

**Comment by LeoJHarris** [comment]
I think I am having the same issue, trying to deploy onto any device including emulators gets stuck with the following in the build output:

(omitting sensitive information)

```
1>Detected signing identity:
1> Code Signing Key: “” (-)
1> Provisioning Profile: “XXXXXXXXXX” (XXXXX)
1> Bundle Id: XXXX
1> App Id: XXXX
```

I've waited over 30 mins and still stuck. Started happening after adding an Apple Account using the new method.

**Comment by LeoJHarris** [comment]
Ran the command `dotnet build -f net8.0-ios -c Debug` and its been running for roughly 98 minutes

![image](https://github.com/user-attachments/assets/f77d7696-9726-484c-802d-75114de1f260)

**Comment by rolfbjarne** [comment]
@LeoJHarris that's most likely something different, so please file a new issue.

**Comment by rolfbjarne** [comment]
@amilici your project worked for me once I created a provisioning profile with the "Sign In with Apple" entitlement, and referenced it from the csproj.

Can you get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) for a build that doesn't install? The binlog will show which certificate + provisioning profile was chosen to sign the app, maybe the build ends up using the wrong one for some reason.

**Comment by amilici** [comment]
There is a binlog already attached to the issue.

**Comment by rolfbjarne** [comment]
That looks good as far as I can tell.

Can you:

1. Remove all entitlements except the `com.apple.developer.applesignin` entitlement, and see if that works (using the test project).
2. If it doesn't, could you zip up and send me the app bundle:

    ```
    zip -9r TestApp.zip TestApp/bin/Debug/net9.0-ios/ios-arm64/TestApp.app
    ```

**Comment by amilici** [comment]
@rolfbjarne It still does not install with all the entitlements removed except com.apple.developer.applesignin.
[TestApp.zip](https://github.com/user-attachments/files/18014513/TestApp.zip)

**Comment by rolfbjarne** [comment]
That's weird, I re-created a provisioning profile with exactly like you have, and my test app has the exact same entitlements, and it still works for me.

Is the device you're trying to deploy to included in the provisioning profile?

Can you try to create an Xcode project with the same bundle identifier, Entitlements.plist, and provisioning profile and see if that works?

**Comment by amilici** [comment]
An app built with Xcode using that provisioning profile and the Sign in with Apple entitlement does install

**Comment by rolfbjarne** [comment]
@amilici can you zip up and attach the app bundle built by Xcode?

**Comment by rolfbjarne** [comment]
The .NET app (from [here](https://github.com/xamarin/xamarin-macios/issues/21645#issuecomment-2518621475) has these entitlements:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>application-identifier</key>
    <string>9P4GQ95Q3N.com.guess.alert</string>
    <key>aps-environment</key>
    <string>production</string>
    <key>com.apple.developer.applesignin</key>
    <array>
      <string>Default</string>
    </array>
    <key>com.apple.developer.pass-type-identifiers</key>
    <array>
      <string>9P4GQ95Q3N.*</string>
    </array>
    <key>com.apple.developer.team-identifier</key>
    <string>9P4GQ95Q3N</string>
    <key>get-task-allow</key>
    <false/>
  </dict>
</plist>
```

while the Xcode app has these:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "https://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>application-identifier</key>
    <string>9P4GQ95Q3N.com.guess.alert</string>
    <key>com.apple.developer.applesignin</key>
    <array>
      <string>Default</string>
    </array>
    <key>com.apple.developer.team-identifier</key>
    <string>9P4GQ95Q3N</string>
    <key>get-task-allow</key>
    <false/>
  </dict>
</plist>
```

I'm guessing some of the extra ones for .NET (`aps-environment` or `com.apple.developer.pass-type-identifiers`) are the ones to blame.

You can list the entitlements yourself for an app by executing the following (remember to update the path of the app):

```
codesign -d --entitlements - --xml /path/to/myapp.app 2>&1 | tail -1 | xmllint --pretty 1 -
```

**Comment by amilici** [comment]
Interesting. The aps-environment entitlement I need for push notifications but I think I can get rid of the com.apple.developer.pass-type-identifiers one, we don't use the Wallet any more. I'll try that and let you know.
