### ISSUE TITLE
Failed to compile the generated registrar code in deploying Xamarin iOS app in iPAD

### ISSUE THREAD

**Issue by Parthi12-tech** [xamarin/xamarin-macios#21651]

**Comment by Parthi12-tech** [comment]
@rolfbjarne  Please find the attached screenshot for the reference.

![Uploading Screenshot 2024-11-19 at 6.27.51 PM.png…]()

**Comment by Parthi12-tech** [comment]
@rolfbjarne Please find the updated image for your reference. 

![Uploading Screenshot 2024-11-19 at 6.27.51 PM.png…]()

**Comment by rolfbjarne** [comment]
This is a Xamarin.iOS project, which is not supported anymore. Please upgrade the project to a .NET project.

For more information, please see https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin.
