### ISSUE TITLE
Unable to deploy or build the Xamarin App. 

### ISSUE THREAD

**Issue by Parthi12-tech** [xamarin/xamarin-macios#21650]
Unable to deploy / build the Xamarin App. Attached the below screenshot for the reference. 

![Uploading Screenshot 2024-11-15 at 4.14.09 PM.png…]()

**Comment by rolfbjarne** [comment]
Looks like the upload of the screenshot was cut short, can you try again?

**Comment by Parthi12-tech** [comment]
@rolfbjarne Please find the attached image for your reference.

Xamarin iOS : 16.4.0.23

<img width="1197" alt="Screenshot 2024-11-15 at 4 14 09 PM" src="https://github.com/user-attachments/assets/da07bb16-6628-42fa-a60b-2e92642d2c83">

**Comment by Parthi12-tech** [comment]
@rolfbjarne  Can you please provide quick update on this ?
