### ISSUE TITLE
Failed to AOT compile aot-instances.dll, the AOT compiler exited with code 134

### ISSUE THREAD

**Issue by mlancione** [xamarin/xamarin-macios#21663]
### Apple platform

iOS

### Framework version

net9.0-*

### Affected platform version

.NET 9.0.100

### Description

Getting a failed to AOT compile error when building the below repro project.

It seems that adding Microsoft.Maui.Essentials and Microsoft.Extensions.DependencyInjection NuGet packages and referencing a Microsoft.Extensions.DependencyInjection type in code causes the build error.

Note: The build error only happens when UseInterpreter=false and TrimMode=partial.

### Steps to Reproduce

Build repro project:

[AOTBuildError.zip](https://github.com/user-attachments/files/17825188/AOTBuildError.zip)

### Did you find any workaround?

Setting either UseInterpreter=true or TrimMode=full will avoid the build error.

### Build logs

[msbuild.binlog.zip](https://github.com/user-attachments/files/17825181/msbuild.binlog.zip)

**Comment by rolfbjarne** [comment]
This issue was moved to dotnet/runtime#110003
