### ISSUE TITLE
Publishing to net9.0-ios never completes

### ISSUE THREAD

**Issue by PureWeen** [xamarin/xamarin-macios#21698]
---
**Issue moved from dotnet/maui#26090**
- Please respond to @jamescrosswell.

---

_From @jamescrosswell on Monday, November 25, 2024 8:35:51 AM_

### Description

When I try to publish a brand new MAUI app targeting net9.0-ios to an iPhone 16 Pro Simulator (running iOS 18.1), the publish task never completes. 

Eventually I have to hit `Ctrl + C` to cancel the process. 

If I don't cancel the process, it seems to get stuck on `_InstallMobile` forever... here's an example run that's still going after 40 minutes:
![Image](https://github.com/user-attachments/assets/efc62c19-4677-423a-bc77-0111019804f5)

I left another attempt running over the weekend and after almost 2 days it was still spinning.
 

### Steps to Reproduce

In zsh (on macOS):
```
% dotnet new maui -n MyMauiApp
The template ".NET MAUI App" was created successfully.

Processing post-creation actions...
Restoring /MyMauiApp/MyMauiApp.csproj:
Restore succeeded.


% cd MyMauiApp 
% dotnet publish -c Release --framework net9.0-ios /t:Run /p:_DeviceName=1BB5ADFA-8F69-41EC-9173-45F919B7387A
  MyMauiApp net9.0-ios failed with 1 error(s) (159756.7s) → bin/Release/net9.0-ios/ios-arm64/MyMauiApp.dll
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net9.0_18.0/18.0.9617/targets/Xamarin.Shared.Sdk.targets(2225,3): error MSB3073: The command "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk.net9.0_18.0/18.0.9617/tools/bin/mlaunch --installdev bin/Release/net9.0-ios/ios-arm64/MyMauiApp.app/ --devname 1BB5ADFA-8F69-41EC-9173-45F919B7387A --wait-for-exit:false" exited with code 130.
```

The error is because after **159756.7s** (about 1.8 days) I hit `Ctrl + C` to cancel the task. 

### Version with bug

9.0.10 SR1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18.1

### Did you find any workaround?

No

### Relevant log output

```shell

```

**Comment by jamescrosswell** [comment]
After running the command with `-v diag` and spitting the results out to a log file, I found this was the last line before going into the black hole of forever:
```
Please connect the device '1BB5ADFA-8F69-41EC-9173-45F919B7387A'... (TaskId:367)
```

Which is odd, since the simulator is powered on and sitting there waiting. 

I was able to publish to a physical iOS device connected to the machine though... so something odd about the simulator.

**Comment by rolfbjarne** [comment]
`dotnet publish` builds for device by default, so it's waiting for you to connect the device `1BB5ADFA-8F69-41EC-9173-45F919B7387A` (which obviously won't happen, because that's a simulator).

In any case, `dotnet publish` is probably not what you should be using, "publish" is intended to create an .ipa for publishing to the App Store.

To run an app, just use `dotnet build /t:Run`, or `dotnet run` instead.

**Comment by jamescrosswell** [comment]
> In any case, `dotnet publish` is probably not what you should be using, "publish" is intended to create an .ipa for publishing to the App Store.
> 
> To run an app, just use `dotnet build /t:Run`, or `dotnet run` instead.

Thanks @rolfbjarne - the reason I was using publish (and maybe unecessarily) is that I wanted to ensure the app was AOT compiled and or trimmed/linked (to reproduce [this error](https://github.com/getsentry/sentry-dotnet/issues/3280#issuecomment-2399290672)).

Maybe this is something that can only be done on a physical device, however.

**Comment by rolfbjarne** [comment]
> > In any case, `dotnet publish` is probably not what you should be using, "publish" is intended to create an .ipa for publishing to the App Store.
> > To run an app, just use `dotnet build /t:Run`, or `dotnet run` instead.
> 
> Thanks @rolfbjarne - the reason I was using publish (and maybe unecessarily) is that I wanted to ensure the app was AOT compiled and or trimmed/linked (to reproduce [this error](https://github.com/getsentry/sentry-dotnet/issues/3280#issuecomment-2399290672)).
> 
> Maybe this is something that can only be done on a physical device, however.

Ah, I see.

I think this might work:

> dotnet build /p:RuntimeIdentifier=iossimulator-arm64 /p:_IsPublishing=true /p:PublishAot=true --framework net9.0-ios /t:Run /p:_DeviceName=1BB5ADFA-8F69-41EC-9173-45F919B7387A

Note that this won't work on an Intel Mac - if you only have an Intel Mac, you'll need to run on device instead (we only AOT compile on arm64, never on x64).

**Comment by Marini88** [comment]
I'm having this same issue trying to run it on a physical device but on a mac intel. It was working fine in .net8.0, any change in .net9.0?

**Comment by rolfbjarne** [comment]
@Marini88 please file a new issue with an exact description of what you're doing and we'll have a look
