### ISSUE TITLE
Can't launch iOS simulator - could not load the framework IDEDistribution

### ISSUE THREAD

**Issue by beeradmoore** [xamarin/xamarin-macios#21706]
### Apple platform

iOS

### Framework version

net9.0-*

### Affected platform version

.NET iOS 18.1.9163 (.NET 9.0.100)

### Description

Attempting to run iOS simulator (18.1) from JetBrains Rider (2024.3), it attempts to run

```
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch --launchsim /Users/beeradmoore/myApp/bin/Debug/net9.0-ios/iossimulator-arm64/myApp.app --device=:v2:udid=96341221-B2F5-40B8-9515-E947A256F60F -sdk 18.1 --argument=-monodevelop-port --argument=10000 --setenv=__XAMARIN_DEBUG_PORT__=10000 --sdkroot /Applications/Xcode-16.1.0.app/Contents/Developer
```

which results in the following error

```
error HE0004: Could not load the framework 'IDEDistribution' (path: /Applications/Xcode-16.1.0.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/IDEDistribution): 
dlopen(/Applications/Xcode-16.1.0.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/IDEDistribution, 0x0001): Library not loaded: @rpath/AppThinning.framework/Versions/A/AppThinning
  Referenced from: <92872593-91F4-31C4-86DF-8AB9691CAE03> /Applications/Xcode-16.1.0.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/IDEDistribution
  Reason: tried: '/Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/lib/mlaunch/mlaunch.app/Contents/Frameworks/AppThinning.framework/Versions/A/AppThinning' (no such file), '/Applications/Xcode-16.1.0.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/Frameworks/AppThinning.framework/Versions/A/AppThinning' (no such file), '/Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/lib/mlaunch/mlaunch.app/Contents/Frameworks/AppThinning.framework/Versions/A/AppThinning' (no such file), '/Applications/Xcode-16.1.0.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/Frameworks/AppThinning.framework/Versions/A/AppThinning' (no such file), '/Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/lib/mlaunch/mlaunch.app/Contents/MonoBundle/AppThinning.framework/Versions/A/AppThinning' (no such file)
```

This error was reported in #20802, but this is using Xcode 16.1 with the latest iOS .NET SDK which should support Xcode 16.1.

I am using macOS Sequoia 15.1.1 and the latest SDK and iOS versions.

```
> dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
android                    35.0.7/9.0.100         SDK 9.0.100        
ios                        18.1.9163/9.0.100      SDK 9.0.100        
maui                       9.0.0/9.0.100          SDK 9.0.100     
```

Looking at the log I do see

```
Reason: tried: '/Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/...
```

which would be my old Xamarin.iOS release which is used to debug Xamarin.Forms projects as I port them to MAUI. I will see if I can see why it wants to use those for my .NET 9 MAUI application.

EDIT: This may be a JetBrains Rider issue. Changing to VSCode I can launch the project correctly.

### Steps to Reproduce

1. Create new MAUI application
2. Attempt to debug on iOS simulator

Above error displays and no simulator is launched.

### Did you find any workaround?

Some are mentioned in other threads, but I have not attempted any yet. Most appear talk about downgrading macOS version or downgrading Xcode version. But as far as I am aware with the [.NET 9 - Xcode 16.1 support (9163)](https://github.com/xamarin/xamarin-macios/releases/tag/dotnet-9.0.1xx-xcode16.1-9163) this should no longer be required.

**Comment by beeradmoore** [comment]
Closing this.

It is a JetBrains rider [issue](https://youtrack.jetbrains.com/issue/RIDER-117599/Could-not-load-the-framework-IDEDistribution-on-MacOS-15.0).

Using nightly (JetBrains Rider 2024.3 EAP 6 D, Build #RD-243.22830, built on November 25, 2024) fixed the issue for me.

**Comment by Meekohi** [comment]
This is happening to me in Visual Studio as well.
