### ISSUE TITLE
iOS App Extensions does not work with .NET 8/9 project types

### ISSUE THREAD

**Issue by winstonpang** [xamarin/xamarin-macios#21717]
### Apple platform

iOS

### Framework version

net8.0-*, net9.0-*

### Affected platform version

VS2022 17.12.2

### Description

I have been trying to add an intent extension to our existing .NET 8 iOS application.

In the past with Xamarin.iOS in VS, you would simply add an extension project and the template would append the GUID with the IsAppExtension to the ProjectRefence type.

This does not seem to work. 

Some existing issues that are a few months old seem to indicate it works and then it doesn't work then repeat

https://github.com/xamarin/xamarin-macios/issues/18846

https://github.com/xamarin/xamarin-macios/issues/21119

The moment we add the IsAppExtension tag to the ProjectReference inside the project, the ProjectReference becomes invalid.  Invalid meaning, the usages of types from the Main App's project to the Extension's Project can no longer resolve types and namespaces.

Within VS2022, the project reference shows an exclamation mark icon. We have also tried this in Jetbrains Rider 2024.3, but the Project reference does not appear in the Dependencies node. It appears only when IsAppExtension is removed.

### Steps to Reproduce

This is the main application's project file content

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0-ios</TargetFramework>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
        <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <CodesignKey>iPhone Developer</CodesignKey>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
      <CreatePackage>false</CreatePackage>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
      <CreatePackage>false</CreatePackage>
    </PropertyGroup>
    <ItemGroup>
		<ProjectReference Include="..\SmokeBallIntents\SmokeBallIntents.csproj">
			<IsAppExtension>true</IsAppExtension>
		</ProjectReference>
    </ItemGroup>
</Project>
```

This is the extension's project file

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0-ios</TargetFramework>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
        <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
        <IsAppExtension>true</IsAppExtension>	
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <CreatePackage>false</CreatePackage>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <CreatePackage>false</CreatePackage>
    </PropertyGroup>
    <ItemGroup>
      <BundleResource Include="AddSmokeBallContactIntent.intentdefinition" />
    </ItemGroup>
</Project>
```

### Did you find any workaround?

No work arounds found

### Build logs

[JetBrainsLog.ReSharperBuild_2024_11_28_22_04_08_8591.log](https://github.com/user-attachments/files/17954919/JetBrainsLog.ReSharperBuild_2024_11_28_22_04_08_8591.log)

This is a build log output from Rider that shows the details when we attempt to build the project.

**Comment by rolfbjarne** [comment]
> Invalid meaning, the usages of types from the Main App's project to the Extension's Project can no longer resolve types and namespaces.

If I understand you correctly, I think there might be a misunderstanding here: any code from the extension project is *not* accessible from the main app's project (this is by design). If this worked in a Xamarin project, it was by accident.

If you want to share code between a main project and an extension project, you need to create a class library project for the code to share, and then reference that class library project from both the main project and the extension project.

Would this work for you?
