### ISSUE TITLE
DOWNLOADS.md file not updated with latest builds to download

### ISSUE THREAD

**Issue by letscodewithkalyan** [xamarin/xamarin-macios#21744]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

Microsoft.iOS 16.4

### Description

https://github.com/xamarin/xamarin-macios/blob/main/DOWNLOADS.md File Not updating from long back

### Steps to Reproduce

https://github.com/xamarin/xamarin-macios/blob/main/DOWNLOADS.md
File last update in 2024 year.

**Comment by rolfbjarne** [comment]
The .NET workloads aren't installable from a package, so we don't provide download links.

In fact, the DOWNLOADS page is only applicable to Xamarin.iOS and Xamarin.Mac, which both have been discontinued.

I'll add a note about this to the DOWNLOADS page.
