### ISSUE TITLE
[Workloads] Publish a WorkloadDependencies file inside each manifest pack

### ISSUE THREAD

**Issue by Redth** [xamarin/xamarin-macios#21768]
For any given version of any of the ios/maccat/tvos/macos workloads, this repository is the source of truth for knowledge such as "which XCode version is compatible".

We are beginning to include this type of information inside of the workload manifest packs so that the metadata can be later inferred by things like tooling (eg: vscode) to validate the correctness of developer environments, as well as to help automate publishing accurate and up to date release information in docs.

The file should be a json file inside of the workload package in the path:
  - `/data/WorkloadDependencies.json`
 
Mac/iOS does not have a lot of information to describe, but an example of what this should look like for these workloads is:

```json
{
  "microsoft.net.sdk.ios" : {
    "workload": {
        "alias": [ "ios" ],
        "version": "18.0.8316"
    },
    "xcode": {
      "version": "[16.0,)",
      "recommendedVersion": "16.0"
    },
    "sdk": {
      "version": "18.0"
    }
  }
}
```

We should publish one of these files for each manifest package with the relevant information (so there would be one for maccat, tvos, macos as well).

The workload identifier is used as a top level key so that these files may be eventually merged into one json file when the workload version set package is built.
  
Note that some version fields can be described as [NuGet version ranges](https://learn.microsoft.com/nuget/concepts/package-versioning?tabs=semver20sort#version-ranges) where it makes sense (eg: xcode version) to describe a known compatible set of ranges (this can be used to _block_ scenarios like xcode 17.0 being considered 'supported').  The recommended version should indicate which version to install if we were going to suggest picking one.

We should add any other useful information that could help describe things such as versions of tools used/recommended to developers to setup consistent and reliable CI/CD and development environments with.  For example, Android's file will describe the desired JDK version along with versions of emulators to use and the appropriate source id to install via sdk manager for each.

[Ref (loop)](https://loop.cloud.microsoft/p/eyJ1IjoiaHR0cHM6Ly9taWNyb3NvZnQuc2hhcmVwb2ludC1kZi5jb20vc2l0ZXMvYzIyZmVjMDMtN2I4OS00OTJhLTgzNzQtZmZjMTI4YjMwMWRhP25hdj1jejBsTWtaemFYUmxjeVV5Um1NeU1tWmxZekF6TFRkaU9Ea3RORGt5WVMwNE16YzBMV1ptWXpFeU9HSXpNREZrWVNaa1BXSWxNakZXTUhSeU9XY3dRbk5WYlhVdFJWUjNRVEZNY0dOSmQwdG1VVEZUZFVFeFRuRk5XbVZ3TUhVd1dUaEhkVVpKVlRSUGIxWnlVMWxoZFRaT2RFODRTamhISm1ZOU1ERlhSelkwU0RNMU56TlZRbEpITWs1TU1rSkdTemRZV1ZCWFJqSlNTRVJQVENaalBTVXlSaVpoUFV4dmIzQkJjSEFtZUQwbE4wSWxNakozSlRJeUpUTkJKVEl5VkRCU1ZGVkllSFJoVjA1NVlqTk9kbHB1VVhWak1taG9ZMjFXZDJJeWJIVmtRekZyV21rMWFtSXlNVGhaYVVaWFRVaFNlVTlYWTNkUmJrNVdZbGhWZEZKV1VqTlJWRVpOWTBkT1NtUXdkRzFWVkVaVVpGVkZlRlJ1Ums1WGJWWjNUVWhWZDFkVWFFaGtWVnBLVmxSU1VHSXhXbmxWTVd4b1pGUmFUMlJGT0RSVGFtaElaa1JCZUZZd1l6Sk9SV2Q2VG5wT1NsUXhVVEJYYTNSR1VYcGFTMU5HYkZsVk1GcFJWRlZvVkZaRlJrTlhiRVVsTTBRbE1qSWxNa01sTWpKcEpUSXlKVE5CSlRJeU9UZzBaREZqWm1FdE9EVmxaQzAwWmpaakxXSTRObUl0TkdZek5qVXdNREptTTJZM0pUSXlKVGRFIn0%3D?ct=1733765705848&)

**Comment by rolfbjarne** [comment]
@Redth is this a .NET 10 task, or do you want it earlier?

**Comment by Redth** [comment]
@rolfbjarne we are hoping to start this as soon as possible so we can begin to look at using it in tooling scenarios, so net 9 :)

**Comment by rolfbjarne** [comment]
PR is up: https://github.com/xamarin/xamarin-macios/pull/21779, please review!
