### ISSUE TITLE
Error MSB4086: A numeric comparison was attempted on "$(_XcodeVersion)" that evaluates to "" instead of a number

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/xamarin-macios#21795]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

Version 17.12.3

### Description

Getting the following error when I try publish my app:

```
C:\.nuget\packages\microsoft.dotnet.ilcompiler\8.0.11\build\Microsoft.NETCore.Native.Unix.targets(179,24): error MSB4086: A numeric comparison was attempted on "$(_XcodeVersion)" that evaluates to "" instead of a number, in condition "'$(_XcodeVersion)' >= '15'".
```

I've checked and Xcode has the correct version setup as 16.1

### Steps to Reproduce

Run the cmd line `dotnet publish -f net8.0-ios -c XXXXX -p:ArchiveOnBuild=true -r ios-arm64 -p:CodesignKey="XXXX" -p:CodesignProvision="XXX"`

**Comment by LeoJHarris** [comment]
Any update? this is blocking our ability to get a release build.

**Comment by rolfbjarne** [comment]
Can you add `-bl:msbuild.binlog` to your command line, and zip up and attach the resulting msbuild.binlog file?

> dotnet publish -f net8.0-ios -c XXXXX -p:ArchiveOnBuild=true -r ios-arm64 -p:CodesignKey="XXXX" -p:CodesignProvision="XXX" -bl:msbuild.binlog

**Comment by LeoJHarris** [comment]
@rolfbjarne I had since update to iOS-net9.0 and that issue has gone away although I am currently getting the following now

```
C:\.nuget\packages\microsoft.dotnet.ilcompiler\9.0.0\build\Microsoft.NETCore.Native.Unix.targets(115,5): error : 'xcrun' not found in PATH. Make sure 'xcrun' is available in PATH.

Build failed with 1 error(s) and 4 warning(s) in 1.3s
```

I can confirm I have Xcode correctly setup using the correct cmd line tools, I've tried with both Xcode 16.1 and 16.2

I've tried some ways to install the cmd line tools which I think its having an issue with, with the following

`xcode-select --install`

But says Command line tools are already installed.

**Comment by LeoJHarris** [comment]
Maybe the download via Xcodes has screwed something up, I'm not too sure.

**Comment by rolfbjarne** [comment]
Not finding `xcrun` is strange, that's shipped with the OS I believe.

Can you get an msbuild.binlog file for this failure?

**Comment by LeoJHarris** [comment]
@rolfbjarne can I share this with you directly as it contains sensitive information to our signing

**Comment by rolfbjarne** [comment]
Sure, you can send it to Rolf.Kvinge@microsoft.com

**Comment by LeoJHarris** [comment]
Done thanks

**Comment by rolfbjarne** [comment]
Can you send me an updated binlog for that failure?

**Comment by rolfbjarne** [comment]
> Can you send me an updated binlog for that failure?

Actually I believe the problem is that you need to specify a few other properties to enable the remote build work, see https://learn.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac?view=net-maui-9.0#build-ios-apps-from-the-windows-command-line for more details

**Comment by LeoJHarris** [comment]
@rolfbjarne thanks for the assistance, that resolved it for me and I could get a build, I'm only ever done the publishing for iOS & Android using Visual Studio GUI publishing when right clicking the project. Ill close this off.
