### ISSUE TITLE
Wrong result from CultureInfo.CurrentCulture.Name in iOS

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#21806]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Wrong-result-from-CultureInfoCurrentCul/10793671)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.12.0]

Put this in a Maui app:
Debug.WriteLine($"CultureInfo.CurrentCulture.Name: {CultureInfo.CurrentCulture.Name}");

In iOs is the result: en (wrong)
In Android and Windows is the result: en-US (correct)

In .NET 8 was the result correct for iOS.

Visual Studio 17.12.0
.NET 9
Microsoft.Maui.Controls Version 9.0.10

---
#### Feedback Bot on 11/18/2024, 11:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Geert Geerits on 11/20/2024, 03:17 AM: 

<p>Link to the repository: <a target='_blank' href="https://github.com/geertgeerits/MauiBugCurrentCulture">https://github.com/geertgeerits/MauiBugCurrentCulture</a></p>
<p>I like to change the severity to: I’m unable to use this version<br>
I need the country code to retrieve the ISOCurrencySymbol for that country.</p>

**Comment by rolfbjarne** [comment]
This issue was moved to dotnet/runtime#110680
