### ISSUE TITLE
Error creating instance of a class from a binded library.

### ISSUE THREAD

**Issue by jeroen-corteville** [xamarin/xamarin-macios#21823]
### Apple platform

iOS

### Framework version

net8.0-*

### Affected platform version

VS2022 .NET8 Microsoft.iOS.sdk 18.0.8316

### Description

I'm trying to bind a static objective-c library to connect to a bluetooth card reader. 
The library is provided in a static .a file, and I have no control over the content.
I had the project working for Xamarin Forms, but I haven't managed to make it work with the MAUI rewrite of our app.

I have already looked at a couple of issues here, and I tried all sort of combinations of extra arguments in my csproj (smartlink / forceload/ etc.) but I still haven't been able to make it work.

I'm building for a device (so not a simulator build because I know the library doesn't support that)

[ExampleBluetoothCardReaderApp.iOSBinding.zip](https://github.com/user-attachments/files/18179767/ExampleBluetoothCardReaderApp.iOSBinding.zip)

### Steps to Reproduce

I have included a sample app with my .a file included in it.
For this example i'm just calling the reader code in the AppDelegate.

### Did you find any workaround?

No workaround found

**Comment by rolfbjarne** [comment]
The problem is that `Reader` isn't an Objective-C protocol, it's an Objective-C class, so it shouldn't have the `[Protocol]` attribute:

```diff
diff --git a/ExampleBluetoothCardReaderApp.iOSBinding/ApiDefinition.cs b/ExampleBluetoothCardReaderApp.iOSBinding/ApiDefinition.cs
index b316017..233257d 100644
--- a/ExampleBluetoothCardReaderApp.iOSBinding/ApiDefinition.cs
+++ b/ExampleBluetoothCardReaderApp.iOSBinding/ApiDefinition.cs
@@ -296,7 +296,6 @@ namespace ExampleBluetoothCardReaderApp.iOSBinding
     // @interface Reader : NSObject <ReaderProtocol>

     [BaseType(typeof(NSObject))]
-    [Protocol]
     [NullAllowed]
     interface Reader : ReaderProtocol
     {
```

you'll probably also want to turn ForceLoad off:

```diff
diff --git a/ExampleBluetoothCardReaderApp.iOSBinding/ExampleBluetoothCardReaderApp.iOSBinding.csproj b/ExampleBluetoothCardReaderApp.iOSBinding/ExampleBluetoothCardReaderApp.iOSBinding.csproj
index d894bf2..1829d4d 100644
--- a/ExampleBluetoothCardReaderApp.iOSBinding/ExampleBluetoothCardReaderApp.iOSBinding.csproj
+++ b/ExampleBluetoothCardReaderApp.iOSBinding/ExampleBluetoothCardReaderApp.iOSBinding.csproj
@@ -19,7 +19,7 @@
        <ItemGroup>
                <NativeReference Include="libeID-SDK.a">
                        <Kind>Static</Kind>
-                       <ForceLoad>True</ForceLoad>
+                       <ForceLoad>false</ForceLoad>
                        <Frameworks>CoreBluetooth ExternalAccessory</Frameworks>
                </NativeReference>
        </ItemGroup>
```

otherwise you'll run into a problem with duplicate symbols (because the native library wasn't built correctly).

Can you try that and see if it works for you?

**Comment by jeroen-corteville** [comment]
Hi @rolfbjarne, thanks for taking the time to help me. It worked!
I can't believe it was something so simple.
