### ISSUE TITLE
iOS app runs fail on MAC

### ISSUE THREAD

**Issue by shknazeer** [xamarin/xamarin-macios#21837]
the build was successful. I tried building it using the command line, and it showed the build as successful and generated the MSBuild file successfully. However, when we connected a Mac and tried to run it, the error occurred.

here is the link to the issue
https://github.com/dotnet/maui/issues/26660

**Comment by rolfbjarne** [comment]
Closing as dup of https://github.com/xamarin/xamarin-macios/issues/21817#issuecomment-2554620911.

**Comment by chrmeehansr** [comment]
With all the references to different github threads, I'm not sure where to ask if someone got this resolved. I'm encountering the same challenge. dotnet build on Windows device, no errors.. deploy to mac paired and get the same error. Hoping someone has a solution and or thread with latest I can read. Thank you.

-C
