### ISSUE TITLE
CGPath.Copy releases the original handle

### ISSUE THREAD

**Issue by espresso3389** [xamarin/xamarin-macios#3089]
[CGPath.Copy](https://github.com/xamarin/xamarin-macios/blob/master/src/CoreGraphics/CGPath.cs#L601) is supposed to create a mutable copy of the original CGPath.

The current implementation calls [CGPath.MakeMutable](https://github.com/xamarin/xamarin-macios/blob/master/src/CoreGraphics/CGPath.cs#L560) to create such a copy, and the function also release the CGPath handle passed to it.

I think the behavior is not expected; it should create a copy but should not release the original handle.

**Comment by mandel-macaque** [comment]
@espresso3389 I think we need to look at apple documentation to see if the handle is released or not after the mutable copy so that we match their behaviour. Let me dig for it and I'll get back to you.

PS: If you have a objc sample with similar code that does work and has the unexpected behaviour in xamarin I would greatly appreciate it to be added in the bug report.

**Comment by espresso3389** [comment]
I think it's just a Xamarin.iOS issue and not related to any iOS specifics.
Imagine that one write code like the following one:

```cs
using (var path = new CGPath())
{
  var copy = path.Copy();
  ...
}
```

The code does not seem harmful (at least we don't except crash with it).
In my case, the code above crashes because of double-release of the handle owned by the original CGPath object.

[CGPath.Dispose](https://github.com/xamarin/xamarin-macios/blob/master/src/CoreGraphics/CGPath.cs#L134) does null-checking on the handle value but it does not expect the case of non-null-handle value that is already released by [CGPath.MakeMutable](https://github.com/xamarin/xamarin-macios/blob/master/src/CoreGraphics/CGPath.cs#L560).

**Comment by mandel-macaque** [comment]
Makes perfect sense (I did expect something like the case you posted). Will get you a fix asap.
