### ISSUE TITLE
The localization doesn't work

### ISSUE THREAD

**Issue by MarianXXL** [xamarin/xamarin-macios#3107]
### Steps to Reproduce

1. Use iOS 11.2 and the Visual Studio 15.5.2
2. Setup the iPhone to German language (real phone or the emulator)

### Expected Behavior
The CultureInfo.CurrentUICulture and Thread.CurrentThread.CurrentCulture should be like "de-DE"

### Actual Behavior
The CultureInfo.CurrentUICulture and Thread.CurrentThread.CurrentCulture is always "en-US"

The localization stoped to work, because of the problem.

### Environment
Windows 10 Fall Creator Update

```
```

**Comment by spouliot** [comment]
iOS 11 changed how it reports the current locale, which makes it default to `en-US` more often that previous (iOS 10 and earlier) versions.

There's a workaround documented in https://bugzilla.xamarin.com/show_bug.cgi?id=59596#c19
