### ISSUE TITLE
"None" Linking Causes Xamarin.Forms to Break iOS Extension Google Analytics Librarie

### ISSUE THREAD

**Issue by rmarinho** [xamarin/xamarin-macios#3115]
Initially open by @kspearrin at @xamarin/xamarin-forms 

### Description

I had originally opened this issue in the [GoogleApisForiOSComponents](https://github.com/xamarin/GoogleApisForiOSComponents/issues/116#event-1394496748) repo since it did not seem relevant to XF, but upon investigation I was directed by @SotoiGhost to move it here.

> After playing with some iOS configuration and different kind of projects, I have come to the conclusion that this is an odd scenario caused by Xamarin.Forms, NetStandard, and the linker that affects only G.Analytics, I tried using Firebase.Analytics and everything worked as expected. Please, if you can, file an issue in Xamarin.Forms GitHub repo, explaining what's happening.

Reference original issue for full history here: https://github.com/xamarin/GoogleApisForiOSComponents/issues/116

### Steps to Reproduce

1. Download test Xamarin.Forms project with iOS and iOS Action Extension here: https://github.com/kspearrin/BuildDownloadTest
2. Run iOS extension on a test device (I am using an iPhone 6S). This problem is not present on the simulator.
3. Set breakpoint in [LoadingViewController](https://github.com/kspearrin/BuildDownloadTest/blob/master/src/iOS.Extension/LoadingViewController.cs#L20)
4. Observe `GaiConstants` values.

### Expected Behavior

`GaiConstants` will have property values.

### Actual Behavior

`GaiConstants` are all null.

Changing the iOS Extension project from `<MtouchLink>None</MtouchLink>` to `<MtouchLink>Full</MtouchLink>` or `<MtouchLink>SdkOnly</MtouchLink>` seems to resolve the problem.

### Basic Information

- Version with issue: 2.4.0.91020
- Last known good version: n/a
- IDE: VS 2017 Windows or Mac
- Platform Target Frameworks: 
  - iOS:  11.6.1.2
- Nuget Packages: Xamarin.Google.iOS.Analytics v3.17.0.2
- Affected Devices: iPhone

### Screenshots

![screen shot 2017-12-16 at 9 59 22 am](https://user-images.githubusercontent.com/1190944/34072664-803f3c7a-e259-11e7-9838-c1e4eaa90f63.png)

### Reproduction Link

https://github.com/kspearrin/BuildDownloadTest

**Comment by kspearrin** [comment]
Any update on this issue? Seems it hasn't even been acknowledged yet.

**Comment by timrisi** [comment]
I'm seeing the same behavior.  Null values with Don't Link, but correct values with Link Framework SDKs.

**Comment by kspearrin** [comment]
@timrisi Is there any solution? This is stopping is from updating many of our dependencies.

**Comment by kspearrin** [comment]
Are there any updates for this problem?

**Comment by rolfbjarne** [comment]
Xamarin isn't supported anymore (https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), and this issue applies to Xamarin only, so closing.
