### ISSUE TITLE
Create XM version of "link sdk", "link all" and "dont link" tests

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3135]
This PR does not have an auto test https://github.com/xamarin/xamarin-macios/pull/3134

and in general we don't have a grand spot for one.

We should do the infrastructure work to create one, possibly porting any relevant iOS tests as we go.

**Comment by spouliot** [comment]
Most of the *mmp regression tests* are for the linker, but they are based on classic so they need to be updated. Ideally they would be moved, as much as possible, into those new test projects.

**Comment by rolfbjarne** [comment]
The projects themselves are created here: https://github.com/xamarin/xamarin-macios/pull/3234 (but no tests have been moved/ported to unified)

**Comment by spouliot** [comment]
Closing (pas per last comment)
The test projects now exists and https://github.com/xamarin/xamarin-macios/issues/4975 was filed to move (and kill) mmp regression tests.
