### ISSUE TITLE
Unable to launch app on device connected via network

### ISSUE THREAD

**Issue by emaf** [xamarin/xamarin-macios#3139]
This issue does not always happen, I was able to run apps on devices connected via network before. 
While I wasn't able to run apps on device wirelessly, it did work using USB. @spouliot asked me to try running an app from Xcode and it fixed the issue, after that, I was able to run apps on a device connected via network from VS.

This issue happened on both VS and VSfM.

### Steps to Reproduce
Try to run an iOS app on a device connected via network

### Expected Behavior
The app is launched on the device connected via network

### Actual Behavior
mlaunch throws an error:
error HE0032: Could not mount developer tools on 'Ema's iPhone': Object reference not set to an instance of an object

### Environment
Runtime:
	Mono 5.4.1.6 (2017-06/1f4613aa1ac) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010006

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.1.0.555 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.0.2 (Visual Studio Community)
Hash: 76ea46e3
Branch: master
Build date: 2017-12-22 10:25:26-0500

### Build Logs
https://gist.github.com/emaf/7066a9098c9822fb55380aac0000b37a

**Comment by therealjohn** [comment]
I also experience this with a new project. 

## Steps to Reproduce

1. Create a new iOS application
2. Start Debugging for the iPhone configuration (my device was already recognized wirelessly)

## Actual Results

```
warning MT1043: Failed to launch the application using the instruments service. Will try launching the app using gdb service.
Launching 'com.microsoft.TestingWirelessDeploy' on the device 'John's iPhone'
error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
error HE0032: Could not mount developer tools on 'John's iPhone': Object reference not set to an instance of an object
```

## Version Info

```
=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.4 Preview (7.4 build 837)
Installation UUID: b968d862-551c-4a33-ab4e-9666400e357c
Runtime:
	Mono 5.8.0.105 (2017-10/e70439f1868) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000105

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0-preview2-25407-01
SDK: /usr/local/share/dotnet/sdk/2.0.0-preview2-006497/Sdks
SDK Version: 2.0.0-preview2-006497
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.0.0.214 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.8.0.1 (Visual Studio Enterprise)
Hash: 82e38cd1
Branch: d15-6
Build date: 2017-12-22 14:23:52-0500

=== Xamarin.Android ===

Version: 8.1.0.25 (Visual Studio Enterprise)
Android SDK: /Users/johnmiller/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.0
SDK Build Tools Version: 26.0.2

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0-beta1+69
Hash: 4012b4e
Branch: master
Build date: Thu, 07 Dec 2017 16:20:26 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704000837
Git revision: 25501fe5d2c2ec23ad62c5948c3de8bbd43c03e7
Build date: 2017-12-22 15:33:11-05
Xamarin addins: ab5481dab9e5672c100ce1569a12cb124ee45df4
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.1
Darwin 17.2.0 Darwin Kernel Version 17.2.0
    Fri Sep 29 18:27:05 PDT 2017
    root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

MicroFramework 1.0.1
Prism Template Pack 1.6.1
Internet of Things (IoT) development (Preview) 7.1
```

**Comment by VincentDondain** [comment]
Hi, I cannot reproduce this (never experienced the issue) and your repro steps are not specific enough to help reproduce consistently.

@emaf @therealjohn for device issues like this (HE0032) please always include the native device logs. Either VSMac > View > Pads > Device Log or Xcode > Window > Device and Simulators (hit the small arrow at the bottom to reveal the console).

**Comment by therealjohn** [comment]
@VincentDondain 

I'll try and get the logs for you but right now it's way too long and spammed with:

```
Info (5486) / lockdownd: set_response_error: <private>
Info (5486) / lockdownd: handle_get_value: <private>
```

In the meantime, I was able to reproduce this by connecting my device and opening Xcode > Windows > Devices and Simulators. Select my device and uncheck the Connect via Network setting. Then, when I try and wireless deploy I see this error again. 

```
warning MT1043: Failed to launch the application using the instruments service. Will try launching the app using gdb service.
Launching 'com.microsoft.TestingWirelessDeploy' on the device 'John’s iPhone'
error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
error HE0032: Could not mount developer tools on 'John’s iPhone': Object reference not set to an instance of an object
```

Maybe that will help you reproduce it.

**Comment by rolfbjarne** [comment]
It looks like we're failing to mount the developer tools when doing wifi deploy. I'll have a look.
