### ISSUE TITLE
VNDetectBarcodesRequest is incorrectly tagged as `[Abstract]` in binding

### ISSUE THREAD

**Issue by sushihangover** [xamarin/xamarin-macios#3140]
### Steps to Reproduce

Try to instance a VNDetectBarcodesRequest class

Re: https://stackoverflow.com/a/48004821/4984832

> var detectBarcodesRequest = new VNDetectBarcodesRequest((request, error) => { });
 
### Expected Behavior

Compiles and creates Instance var.

### Actual Behavior

Abstract compile error due to  `[Abstract]` attribute : [vision.cs#L156](https://github.com/xamarin/xamarin-macios/blob/1690ccbc991ab59835f76a15ef510cd182259915/src/vision.cs#L156)

Apple Docs: [VNDetectBarcodesRequest](https://developer.apple.com/documentation/vision/vndetectbarcodesrequest) 

### Environment

```
Xamarin.iOS Version: 11.6.1.2
```

**Comment by spouliot** [comment]
It sure does not match the current documentation. It's possible this changed in later betas (it was added with beta2) and since this is not part of objc metadata it's hard to detect the change. @dalexsoto can you double check ? thanks!

**Comment by dalexsoto** [comment]
Thanks @sushihangover!!

This was incorrectly added by me in 89071bc19dafc2e7c0d714709866de8d90f35441
I could not find why this was added by checking headers nor I can
recall why I added it so I'll just say it was a honest mistake :) Oops... 🙈

**Comment by spouliot** [comment]
@dalexsoto that's safe (and still within the window) to back port to `d15-6`
once done please update the milestone, thanks!
