### ISSUE TITLE
`SceneKit.SCNPhysicsWorld.ConvexSweepTest` method doesn't work

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#3146]
### Steps to Reproduce

1. Download a [project](https://github.com/mykyta-bondarenko-gl/private-samples/tree/fox-2-scenekit/ios11/Fox2)
2. Open a `Fox2.Shared/Character.cs` file and look at the line 260.
3. Uncomment this line.
4. Run the project
5. Tap to the `A` button on the rignt corner (iOS application) (a bounce animation)

### Expected Behavior
The application doesn't crash and the handler is invoked after the animation is finished 

### Actual Behavior
The applications crashes. 
You can find output results in `Supplemental info`.

### Environment
-  Visual Studio for Mac 7.3.2 (build 12)
   https://gist.github.com/mykyta-bondarenko-gl/c51a63a6e38fdd09e5743096b9774e3d

# Supplemental info (logs, images, videos)
- Output
   https://gist.github.com/mykyta-bondarenko-gl/53a75b238a603fa3c36f5286884bb491

### Frequency of Reproduction
Happens every time

### Example Project
[Link to the project](https://github.com/mykyta-bondarenko-gl/private-samples/tree/fox-2-scenekit/ios11/Fox2)

**Comment by dalexsoto** [comment]
@mykyta-bondarenko-gl Could you give me access to your repo?

**Comment by migueldeicaza** [comment]
Just granted access
