### ISSUE TITLE
Privacy Strings Not Localized for Location Service

### ISSUE THREAD

**Issue by jamchengms** [xamarin/xamarin-macios#3159]
### Steps to Reproduce

* I have attached a sample project for your convenience. Just unzip, open solution and run the iOS project on a simulator.

1. Create UI with a button to access the user's location. Create a CLLocationManager and call RequestWhenInUseAuthorization.
2. Add NSLocationAlwaysAndWhenInUseUsageDescription and NSLocationWhenInUseUsageDescription to Info.plist. Add localized value in fr-CA for the two values in Info.plist by adding the localization strings in Resources/fr_CA.lproj/InfoPlist.strings. Also, for testing purposes, also setup Resources/en.lproj/InfoPlist.strings with different strings.
3. Switch OS to French (Canada). Open the app and click on the button that prompts user for using their Location when in use.
4. To get the same prompt to show up again, you MUST delete the app from your device/simulator and install the app again.

### Expected Behavior
See localized value in Resources/fr_CA.lproj/InfoPlist.strings
### Actual Behavior
See localized value in Resources/en.lproj/InfoPlist.strings
### Environment

```
```

### Example Project (If Possible)
[TestLocationPrivacyLocalization.zip](https://github.com/xamarin/xamarin-macios/files/1605208/TestLocationPrivacyLocalization.zip)
![screen shot 2018-01-04 at 4 41 28 pm](https://user-images.githubusercontent.com/31945079/34590911-93aab252-f16e-11e7-9171-85f7ed252999.png)

**Comment by therealjohn** [comment]
Updated the localization string in the info.plist from `fr-CA` to `fr_CA`. That will allow it to work as expected. `fr_CA` is the correct localization code. Hope that helps!

**Comment by dalexsoto** [comment]
You have a little typo if you turn `fr-CA` into `fr_CA ` it should work. All credit goes to @therealjohn 👍  for figuring this up.

```
<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
		<string>fr_CA</string>
	</array>
```
