### ISSUE TITLE
Unable to pin UISplitView to superView (ignore safe areas)

### ISSUE THREAD

**Issue by dparizek00** [xamarin/xamarin-macios#3164]
### Steps to Reproduce

1. Enable "Use safe areas" in storyboard
2. Add UISplitView to the storyboard
3. Add UITableView into splitView
4. Try to pin UITableView left and right to the superView (not to the safeAreas to follow iPhone X design pattern). 

### Expected Behavior
Will be able to choose the SuperView or SafeArea in Xamarin interface builder while adding new constraints (same like in Xcode).

### Actual Behavior
Unable to choose superView. It's always pinned to the safeArea so there is a white space on the left and right side when the device (iPhone X) is in landscape mode

### Workaround
There was a workaround to open the storyboard in XCode, but according to the Xamarin docs, this is not recommended anymore. It also breaks my storyboard so I am not able to compile the project after opening it in XCode (it break's the storyboard XML so it's not readable for the compiler anymore)

### Environment
iOS 11.2, iPhone X - landscape mode
Visual Studio For Mac - 7.3.2 - build 12
iOS Designer Extension - 7.3
iOS development Extension - 7.3.2

### Build Logs
No problem with the build - this issue is interface designer related - unable to select the parent while pinning (or change it in constraint preferences like in XCode)

**Comment by therealjohn** [comment]
@dparizek00 I'm not able to reproduce this. Could you create a screen recording of this and/or upload a sample project that has the constraints in it? 

Thanks!

**Comment by therealjohn** [comment]
Unfortunately, right now we don't have enough information to investigate this issue and find a solution. If this is still an issue for you, please update to our latest version. If you are still able to reproduce the problem, please provide us with more info!
