### ISSUE TITLE
Build crash with generated code in .NET Standard library

### ISSUE THREAD

**Issue by breyed** [xamarin/xamarin-macios#3177]
### Description

I created a .NET Standard class library, added a simple .proto file to it, and added a target in the .csproj to run the Protobuf code generator. I then referenced the class library from an Xamarin iOS project and instantiated the generated class from `Main`. This caused the iOS build to crash.

### Steps to Reproduce

1. Build [repro](https://github.com/breyed/xamarin-macios-netstandard-build-crash).

### Expected Behavior
It builds.

### Actual Behavior
This build error:
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Could not link assemblies. Reason: Object reference not set to an instance of an object

### Environment

[Visual Studio installed products](https://gist.github.com/breyed/f66145df3af9588a3c55dd0af7b939e0)

### Build Logs

[Diagnostic build output](https://gist.github.com/breyed/402a01a9e996d707a90b49e5f255d8a4)

> VS bug [#1089495](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1089495)

**Comment by mandel-macaque** [comment]
Hello,

I have forked the project to fix it to be able to compile the project on MacOS X (simple change pointing to the correct tool in the nuget) https://github.com/mandel-macaque/xamarin-macios-netstandard-build-crash

With the above small change and the following [environment](https://gist.github.com/mandel-macaque/e2c825fb6bdce0204410c86120280c6d) I was able to [build](https://gist.github.com/mandel-macaque/c5b170316f887db784144198532bc335) the project.

As you can see in the logs, I'm using Xamarin iOS Version: 11.9.0.27 while you are using 11.6.1.2. Reverting my system to 11.6.1.2 (stable) I'm able to build the project without issues. Can you access your building mac machine and test the forked version of your project?

**Comment by breyed** [comment]
There are two different scenarios to consider:
1. Building both projects with Visual Studio for Mac.
2. Building both projects with Visual Studio for Windows. In this case, if I understand correctly, ClassLibrary1 is built on Windows only and IOS is built with VS for Windows using the VS Mac agent. (Correct?)

This issue only concerns the second scenario. In the production project, the equivalent of ClassLibrary1 is a shared library created with VS for Windows, which is used by Xamarin, web, and other projects. In some cases, we work on ClassLibrary1 without the Mac even being connected. Changing the Protobuf tooling to use macOS executable would break those builds (and slow them down considerably even if they did work).

The problem seems to related to how the agent handles working with a DLL that was built on Windows, though I don't know why it would matter. In case it helps, the reason I put this repro together to begin with was to narrow down a different bug I've experienced, which is that the class constructor for the Protobuf generated class `TestReflection` throws an exception, but only on iOS (not on UWP, .NET Core, etc.)

**Comment by mandel-macaque** [comment]
@breyed ok, so this is clearly a bug in the VS Windows agent, let me find out where are those bug currently being tracked so that someone from their team can take a look. 

Regarding the iOS exception, could you show me the error? The fact that it only happens on iOS might, just might, be related to the linker which is something that UWP, .Net Core, Android etc.. do not have since on iOS with AOT and we try to make the dlls as small as possible. If not told explicitly to keep certain methods they are removed and if used via reflection they will throw a runtime exception.

PS: I'm just mentioning the linker because of the "Reflection" in the method which points to something of the "linker removed it but is used" kind of bugs.

**Comment by mandel-macaque** [comment]
After talking with the VS team they would like to know if you have the same failure via the command line, would you mind trying and posting the results in this issue @breyed ?

**Comment by breyed** [comment]
The Protobuf error is System.ArgumentException: Invalid embedded descriptor for "Test.proto". The debugger shows a string value for `descriptor`. The linker doesn't seem to be removing it (which would be nice, since I don't think I need it), but instead altering it in some way, or maybe some context change is interfering.

I tried building from the command line by executing `msbuild` on the Windows computer. It failed because it couldn't find the Mac build agent (even though Visual Studio can).

**Comment by mandel-macaque** [comment]
Ok, here we have a build from the command line from a windows machine:

https://gist.github.com/emaf/0481fdb699d974fbf97ff035b161d61e#file-gistfile1-txt

Setting the bug to future cycle as confirmed.

**Comment by mandel-macaque** [comment]
@emaf Can you take a closer look into this since it is just hapenning.
