### ISSUE TITLE
Our build doesn't support PATH containing paths with spaces

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#3183]
Repro:

```shell
PATH="$PATH:/some/path/with spaces" make all
```

result:

```shell
Making all in builds
/bin/sh: spaces: No such file or directory
make[1]: *** [.stamp-configure-watchsimulator] Error 127
make: *** [all-recurse] Error 1
```

Marek ran into this with workbooks: https://gist.github.com/marek-safar/796929c2194726b7f8b8c34bd7b39579 (where `PATH=/Users/marek/mono/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin`)

**Comment by jgold6** [comment]
I just ran into this as well. Had to remove "workbooks" from /etc/paths.d to build XI/XM

**Comment by lewurm** [comment]
I cannot reproduce it anymore with current `master`, most likely due to the switch to the Mono SDK for building the runtimes.

**Comment by mandel-macaque** [comment]
I can confirm the comments from @lewing The error does not happen in master.

**Comment by rolfbjarne** [comment]
OK, closing then.

Easiest bugs are those that are already fixed :smile:
