### ISSUE TITLE
UIView.DisplayLayer(CALayer) raises NSInvalidArgumentException yet it implements the CALayerDelegate protocol

### ISSUE THREAD

**Issue by lobrien** [xamarin/xamarin-macios#3189]
### Steps to Reproduce

1. Create a new Xam.iOS app
2. In `ViewController.ViewDidLoad` add:
```
    var l = new CALayer();
    this.View.DisplayLayer(l);
```

3. Run and receive an `NSInvalidArgumentException` with Reason "Unrecognized selector" `UIView displayLayer:` 

### Expected Behavior

No exception. BUT I actually think this is a binding mistake and `DisplayLayer(CALayer)` should not be in `UIView`, as there is not a corresponding Obj-C / Swift method. (There _is_ such a method in `CALayerDelegate`). 

### Actual Behavior

Exception thrown

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.3.2 (build 12)
Installation UUID: 6b94f136-026d-4a5a-bf6d-af2c0d8dc019
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.3/Sdks
SDK Versions:
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13768)
Build 9C34b

=== Xamarin.iOS ===

Version: 11.6.1.2 (Visual Studio Community)
Hash: 6857dfcc
Branch: xcode9.2
Build date: 2017-12-04 21:20:41-0500

=== Xamarin.Android ===

Version: 8.1.0.25 (Visual Studio Community)
Android SDK: /Users/larryobrien/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 25.0.3
SDK Build Tools Version: 26.0.2

Java SDK: /usr
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 4.0.0.214 (Visual Studio Community)

=== Xamarin Inspector ===

Version: 1.4.0-rc1
Hash: 7f3bf81
Branch: master
Build date: Fri, 22 Dec 2017 22:04:38 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703020012
Git revision: 7d0c9d7ad46b125cf4b7bbf9532c0531b6433ce6
Build date: 2017-12-12 14:03:18-05
Xamarin addins: 6dddaa49fbecb2695fcdcd6b712eb269e288518c
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1


```

### Example Project (If Possible)

[UIView0.zip](https://github.com/xamarin/xamarin-macios/files/1617187/UIView0.zip)

**Comment by mandel-macaque** [comment]
This is quite interesting, as per Apple headers UIView is a CALayerDelegate which contains the displayLayer method -> https://developer.apple.com/documentation/uikit/uiview#relationships and https://developer.apple.com/documentation/quartzcore/calayerdelegate/2097261-displaylayer?language=objc

Yet, it is correct that the application crashes, in my case with the following env:

=== Visual Studio Community 2017 for Mac ===

Version Preview - Internal Dogfood (7.3.3 build 5)
Installation UUID: 8d12e55e-3489-463f-ac52-8cb4573c5a81
Runtime:
	Mono 5.8.0.39 (2017-10/99db2351979) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000039

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.0
	1.1.2
	1.0.5
	1.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Versions:
	2.0.0
	1.0.4
	1.0.0-preview2-003121
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.9.0.27 (Visual Studio Community)
Hash: f9ceb5c3
Branch: uiview-display-layer
Build date: 2018-01-10 12:10:36+0100

=== Xamarin.Android ===

Version: 8.1.0.25 (Visual Studio Community)
Android SDK: /Users/mandel/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.3   (API level 18)
		4.4   (API level 19)
		5.0   (API level 21)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.4
SDK Build Tools Version: 25.0.1

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 4.3.0.27 (Visual Studio Community)

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703030005
Git revision: b1c2982e201e71ef758866c9ade05f253a8c6f47
Build date: 2017-12-21 11:06:49-05
Xamarin addins: f397ddfbacfb39e60c9cc8d9e410f73faf8c2cbc
Build lane: monodevelop-lion-dogfood-vNext

=== Operating System ===

Mac OS X 10.13.1
Darwin 17.2.0 Darwin Kernel Version 17.2.0
    Fri Sep 29 18:27:05 PDT 2017
    root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

**Comment by mandel-macaque** [comment]
After closer inspection, I can confirm that this is what happens:

1. The binding is correct, the UIView class implemented the CALayerDelegate protocol which contains the displayLayer method.
2. The CALayerDelefate displayLayer method is optional as per the Apple headers: https://gist.github.com/mandel-macaque/52410c16d37f8a839d11708ef567a95c
3. We cannot, at compile time, tell you if the method is implemented by the UIView subclass you are dealing with, that cannot only be found at runtime.

So, although the app crashes this is the expected behaviour and the same one that you would have in a swift/objc similar sample.
