### ISSUE TITLE
SetSelectedDomRange throws exception when range passed is null.

### ISSUE THREAD

**Issue by aconcagua21** [xamarin/xamarin-macios#3206]
### Steps to Reproduce
Call WebKit.WebView.SetSelectedDomRange(range, affinity) with range = null.

### Expected Behavior
WebView should clear current selection.

### Actual Behavior
Throws ArgumentNullException exception

**Comment by mandel-macaque** [comment]
Could you please provide the full environment that was used to see the error. 

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by aconcagua21** [comment]
Sure, see below.

However, the problem is in binding of SetSelectedDomRange: The "range" parameter is probably lacking the NullAllowed attribute. See the [documentation](https://developer.apple.com/documentation/webkit/webview/1408363-setselecteddomrange).

=== Visual Studio Community 2017 for Mac ===

Version 7.3.2 (build 12)
Installation UUID: 7b37c015-e264-4afb-8a25-3143fd201145
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Version: 2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.0.0.214 (Visual Studio Community)

=== Xamarin.Android ===

Version: 8.1.0.25 (Visual Studio Community)
Android SDK: Not found

=== Xamarin.iOS ===

Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703020012
Git revision: 7d0c9d7ad46b125cf4b7bbf9532c0531b6433ce6
Build date: 2017-12-12 14:03:18-05
Xamarin addins: 6dddaa49fbecb2695fcdcd6b712eb269e288518c
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Wed Oct  4 00:17:00 PDT 2017
    root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1
