### ISSUE TITLE
[XI] MPSImageHistogramEqualizationTest failure on 9.3.5 device

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3237]
### Steps to Reproduce

1. Update System to XI, xamarin.ios-11.8.0.9.pkg
2. Checkout 0059e3e5b5519ac96070916453b2f7a8dab26ef0
3. Build and execute monotouch-test on an iOS 9.3.5 device

### Expected Behavior
Tests should pass on device

### Actual Behavior
[FAIL] MPSImageHistogramEqualizationTest.Constructors : System.ArgumentNullException : Value cannot be null.
[FAIL] MPSImageHistogramSpecificationTest.Constructors : System.ArgumentNullException : Value cannot be null.
[FAIL] MPSImageHistogramTest.Constructors : System.ArgumentNullException : Value cannot be null.

### Environment
```
xamarin.ios-11.8.0.9.pkg 
```

### Build Logs

1. Build Log: 
http://xqa.blob.core.windows.net/gist/report-415de76c50e14ab184430a363ca7f01e.txt
2.Test Log: 
http://xqa.blob.core.windows.net/gist/monotouchtest-ios04-51-090c3a0d1d60fbd11401f1d6ca33518e9a31bafab404-51-09-6e29a551645641da992e51adf30d089e.zip

**Comment by spouliot** [comment]
@GouriKumari what type of device is `XQAiPad2b` ? is it an iPad 2 ? because those don't support Metal (and the tests don't check for that)

**Comment by GouriKumari** [comment]
Yes, it is an older iPad and is connected to the bots.
