### ISSUE TITLE
[XI] System test failure on iOS 11.0.3 device

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3239]
### Steps to Reproduce

Update System to XI, xamarin.ios-11.8.0.9.pkg
Checkout 0059e3e
Build and execute system test on an iOS 11.0.3 device

### Expected Behavior
Tests should pass
### Actual Behavior
Observed that SocketTest.TestSelect1 :   #02 and  TcpListenerTest.TcpListener :   Expected: True failed on device .  WebClientTest.DownloadTwice : System.Net.WebException : Error getting response stream (ReadDone1): ReceiveFailure
This is also observed on a single device. 
### Environment

```
Tested with xamarin.ios-11.8.0.9.pkg
```

### Build Logs

Test Log: https://gist.github.com/GouriKumari/035ceea8be6d34d8a9f94d281b7ca0ad, http://xqa.blob.core.windows.net/gist/System-ios11-45-3739069454ce55ce4ce9c138fb43719ef6a66ca48811-45-37-f50bee4b05b54014b4884966744398c4.zip
Build Log: https://gist.github.com/GouriKumari/46835be3097e6db0f1d9490c42c0a5f4

**Comment by timrisi** [comment]
@GouriKumari Do you get those failures every time?  On an 11.0.2 device I ran the tests with no failures.  Testing on an 11.1 device I am getting a few failures, but not the same failures every time.  (For instance, I got the SocketTest.TestSelect1 failure the first time, but not the TcpListenerTest.TcpListener failures.  Second time, I got the TcpListenerTest.TcpListener  failure, but not the SocketTest.TestSelect1  one)

**Comment by GouriKumari** [comment]
I could reproduce this issue on only one device and both the tests failed locally and from CI Failures are also not consistent. I did see the behaviour that you mentioned while running tests from CI.

**Comment by chamons** [comment]
Moved to https://github.com/xamarin/maccore/issues/1069
