### ISSUE TITLE
[rfc] Simpler fix for missing [DesignatedInitializer] for default constructors

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#3247]
### Steps to Reproduce

Check xtro results, e.g. https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/5958/Extrospection_Report/

### Expected Behavior

No entry with `!missing-designated-initializer!` :)

### Actual Behavior

Many entries, but largely ones for default `.ctor` (or `init`), e.g.

```
!missing-designated-initializer! NSCell::init is missing an [DesignatedInitializer] attribute
```

This, right now, takes a bit of time to fix because it requires more work like https://github.com/xamarin/xamarin-macios/pull/3142/files i.e. disabling the default constructor, defining it manually and add `[DesignatedInitializer]` (4 line change per type).

### Potential Solution

Modify the `[DesignatedInitializer]` attributes, as used in bindings (not the platform assemblies), to be usable on types, e.g. bindings like:

```
	[BaseType (typeof (NSObject))]
	[DesignatedInitializer]
	interface NSCell { ... }
```

would generate a:

```
		[Export ("init")]
		[DesignatedInitializer]
		public NSCell () : base (NSObjectFlag.Empty) { ... }
```

instead of the current:

```
		[Export ("init")]
		public NSCell () : base (NSObjectFlag.Empty) { ... }
```

### Notes

The `DesignatedInitializerAttribute` attribute (in the platform assemblies) would still remain decorated with:

```
[AttributeUsage (AttributeTargets.Constructor | AttributeTargets.Method)]
```

only the version used for bindings/generator would accept the attribute on types.

**Comment by spouliot** [comment]
@dalexsoto @rolfbjarne comments please ? :)

**Comment by rolfbjarne** [comment]
I like the idea :smile:

Although it seems weird to say the type is the designated initializer. Adding (yet!) another (generator only) attribute could make it more self-documenting: (`[DesignateDefaultInitializer]`, `[DefaultConstructorIsDesignatedInitializer]`, `[DesignateDefaultConstructor]`, or something else).

**Comment by dalexsoto** [comment]
Yup, I like the idea too and agree with @rolfbjarne comments having

```
[BaseType (typeof (NSObject))]
[DesignatedInitializer]
interface NSCell { ... }
```

Feels a bit weird, but maybe instead of having another Attribute for this, we can have something like this `[DesignatedInitializer (DefaultCtor = true)]` or `[DesignatedInitializer (EmptyCtor = true)]`

```
[BaseType (typeof (NSObject))]
[DesignatedInitializer (DefaultCtor = true)]
interface NSCell { ... }
```

**Comment by spouliot** [comment]
We already have `[DisableDefaultCtor]` so maybe `[DesignatedDefaultCtor]` ?

Even if, from scratch, I would prefer if we had `[DefaultCtor (Disable = true, Designated = true)]` instead of a proliferation of attributes.

Of course the case above does not make sense :)

**Comment by dalexsoto** [comment]
> [DefaultCtor (Disable = true, Designated = true)]
XAMCORE_4_0? :D

`[DesignatedDefaultCtor]` sounds great to me! 👍

**Comment by rolfbjarne** [comment]
👍 to `[DesignatedDefaultCtor]`
