### ISSUE TITLE
Getting malloc: *** error for object 0x610006830320: Non-aligned pointer being freed (2) error while running application on Mac OS with Xamarin

### ISSUE THREAD

**Issue by msyuyigit** [xamarin/xamarin-macios#3254]
### Steps to Reproduce

1. Run test application with 10 instances on one single box for 2 hrs
- Test application uses Xamarin platform to test business scenarios related to our product

### Expected Behavior
No crash

### Actual Behavior
Test app crashes with no logs except the log in system log which tells us there was an unaligned pointer being freed. This doesn't repro on a specific test or any specific time, it tends to happen once per test run. Recently, a change which just added logging to the app caused this to happen much more regularly with the same setup. We've investigated potential issue with that modified code - but couldn't find any. To be more explicit, it was System.Data.Sqlite dll which we thought as root cause, but it happened with earlier versions as well.

We're seeing the below log in /var/log/system.log:

Jan 18 02:09:00 BaeMacPro10-1 BAEMacShellLibTestApplication[60429]: BAEMacShellLibTestApplication(60429,0x70000b2b2000) malloc: *** error for object 0x610006830320: Non-aligned pointer being freed (2)
        *** set a breakpoint in malloc_error_break to debug
Jan 18 02:09:00 BaeMacPro10-1 syslogd[46]: ASL Sender Statistics
Jan 18 02:09:01 BaeMacPro10-1 com.apple.xpc.launchd[1] (com.microsoft.MerpForMono.MerpGUIAgent.699904[67524]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]
Jan 18 02:09:01 BaeMacPro10-1 com.apple.xpc.launchd[1] (com.apple.ReportCrash[67525]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
Jan 18 02:09:22 BaeMacPro10-1 com.apple.xpc.launchd[1] (com.apple.quicklook[68891]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook

### Environment

```
Xamarin Studio Community 6.2.1 (build 3)
Runtime: Mono 4.8.0.520
Apple Developer Tools: Xcode 8.3.3 (12175.1)
Xamarin.Mac 3.0.0.398
```

### Example Project (If Possible)
We can't share the binaries unfortunately, but we can provide logs with a suggested methodology if provided.

**Comment by chamons** [comment]
This should be filed on https://bugzilla.xamarin.com/ with the example project inline and is related more to runtime anyway.
