### ISSUE TITLE
AVAudioUnitComponentManager default .ctor can crash on macOS 10.13.3

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#3303]
### Steps to Reproduce

1. Run introspection on mac

### Expected Behavior

It works.

### Actual Behavior

It crash on bots - but I have not see this locally.
https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/6079/Test_Report/

It looks like this should not have been bound since there's a singleton-like static property to use the type. It needs to be removed while keeping binary compatibility.

**Comment by VincentDondain** [comment]
Yes I didn't (and still don't) get this crash locally.

**Comment by spouliot** [comment]
@VincentDondain this seems to be an issue on the bots (after they were updated). I'm not sure why neither you or I could duplicate it. However it needs to be committed to `master` too since it still fails there. It can be closed afterward (it was not automatically).

**Comment by spouliot** [comment]
Comments from last PR mention it's fixed (but it was not closed automatically)
