### ISSUE TITLE
Missing bindings in AVCapturePhoto

### ISSUE THREAD

**Issue by peterringset** [xamarin/xamarin-macios#3324]
### Steps to Reproduce

1. Try to capture a photo using the new `AVCapturePhotoOutput` class
2. Implement interface method `public void DidFinishProcessingPhoto(AVCapturePhotoOutput output, AVCapturePhoto photo, NSError error)` to get the finished photo
3. Extract photo data from `AVCapturePhoto` to use.

### Expected Behavior
The class doesn't bind all ObjC properties and methods, so that photo capture is only possible when using an uncompressed format. When using an uncompressed format it is possible to get image data through `pixelBuffer` property, but when using e.g. JPEG the image data is only accessible through `CGImageRepresentation` property, which is not bound in C#.

### Actual Behavior
Missing binding for `CGImageRepresentation` (amongst others)

### Environment
iOS

```
```

**Comment by VincentDondain** [comment]
Hi,

Yes we do have some missing iOS 11 bindings for AVFoundation. You can see them here: https://github.com/xamarin/xamarin-macios/blob/master/tests/xtro-sharpie/iOS-AVFoundation.ignore

We're also missing (and it's not reported by xtro): `@interface AVCapturePhoto (AVCapturePhotoConversions)`.

This is where: `- (nullable CGImageRef)CGImageRepresentation NS_AVAILABLE_IOS(11_0);` is reported.

Apple [documentation](https://developer.apple.com/documentation/avfoundation/avcapturephoto/2873963-cgimagerepresentation?language=objc) of the API as reference.

**Comment by spouliot** [comment]
@mandel-macaque there a few things already in 15.6 or master that might also need to be back ported.

**Comment by mandel-macaque** [comment]
@peterringset @spouliot on it.

**Comment by mandel-macaque** [comment]
PR landed. Closing bug.
