### ISSUE TITLE
IOS Deploy Issue

### ISSUE THREAD

**Issue by pritamwalpole** [xamarin/xamarin-macios#3329]
I am using the Xamarin Live Player to deploy the Xamarin.forms to Ipad. I am getting the Unhandled Error Launching Soft debugger and bunch of errors below that and in the next dialog box i am getting the Exception: Mono.Debugging.Soft.ConnectionException: could not connect to the debugger and bunch of erros below that at the same time i am able to see that I am seeing Vizualization error on my ipad saying Exception of Type 'Foundation.ModelNotImplementedException' was thrown.
Looking forward to hear from Xamarin.

**Comment by VincentDondain** [comment]
Hi,

This in the repository for the **Xamarin.iOS and Xamarin.Mac SDKs**. For a bunch against the Xamarin Live Player, please use bugzilla: https://bugzilla.xamarin.com/describecomponents.cgi?product=Live%20Player

Also, as a reminder, for any new bug please include your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).
