### ISSUE TITLE
mono-symbolicate isn't working as expected

### ISSUE THREAD

**Issue by gonzalonm** [xamarin/xamarin-macios#3338]
`mono-symbolicate` command replaces an obfuscated stacktrace into a readable stacktrace with lines number of classes. An existing [bug](https://bugzilla.xamarin.com/show_bug.cgi?id=43417) is related with this one.

### Steps to Reproduce

1. Download [iOS.app.mSYM.zip](https://github.com/xamarin/xamarin-macios/files/1668855/iOS.app.mSYM.zip) and [err.log](https://github.com/xamarin/xamarin-macios/files/1668858/err.log) files.
2. Unzip iOS.app.mSYM.zip (it contains a folder named `iOS.app.mSYM`)
3. Make sure you are in the same location that the downloaded files. Then, execute by command line: `mono-symbolicate iOS.app.mSYM err.log`
4. See output

### Expected Behavior
The output should have a readable stacktrace with class name and lines number

### Actual Behavior
The output contains `MonoSymStandard.MyClass.GetData () [0x00008] in <46e1e10f68bd4599bbf09881e27fea56>:0 `

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.3.3 (build 5)
Installation UUID: 3c00bde1-c9f9-4c06-a934-964537f86a3e
Runtime:
	Mono 5.8.0.111 (2017-10/ba9ca156eaa) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000111

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.2/Sdks
SDK Version: 2.0.2
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.5.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.4.0.84 (Visual Studio Community)
Hash: 697f665b
Branch: d15-5
Build date: 2017-10-09 19:11:38-0400

=== Xamarin.Android ===

Version: 8.2.0.6 (Visual Studio Community)
Android SDK: /Users/gonzalo/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3    (API level 10)
		4.0.3  (API level 15)
		4.1    (API level 16)
		4.2    (API level 17)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.2.0
Hash: 62c17e6
Branch: d15-1
Build date: Mon, 20 Mar 2017 02:36:23 GMT

=== Xamarin.Mac ===

Version: 4.0.0.84 (Visual Studio Community)

=== Build Information ===

Release ID: 703030005
Git revision: b1c2982e201e71ef758866c9ade05f253a8c6f47
Build date: 2017-12-21 11:04:40-05
Xamarin addins: f397ddfbacfb39e60c9cc8d9e410f73faf8c2cbc
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Mon Nov 13 21:56:25 PST 2017
    root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

```

### Example Project (If Possible)

I'm creating the sample. For this cause, I'm attaching the related files in order to reproduce this issue. If you want to test it using the related project, you can download it: [MonoSymStandard.zip](https://github.com/xamarin/xamarin-macios/files/1668866/MonoSymStandard.zip)
This is a **net standard project**, so make sure have installed the proper components to open it.

**Comment by VincentDondain** [comment]
Hi,

This is a mono issue, not a Xamarin.iOS / Xamarin.Mac (SDK) one (:

Would you mind opening the exact same issues against mono? https://github.com/mono/mono/issues/new

_Note: unfortunately we don't have yet the ability to move issues between repos (soon)._

**Comment by gonzalonm** [comment]
Sure, I will file it in mono issues. Thanks
