### ISSUE TITLE
Add a StrongDictionary to SecKey.GenerateKeyPair

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#3359]
While [PR 3350](https://github.com/xamarin/xamarin-macios/pull/3350): "[Security] Refactoring Sec-keys" is a good step toward making `SecKey.GenerateKeyPair` more usable (by making some internal keys public), I believe we should consider adding an API with a strong dictionary.

The discussion in https://developer.apple.com/documentation/security/1395339-seckeygeneratepair?language=objc explains exactly which keys and also which keys of the `kSecPublicKeyAttrs` and `kSecPrivateKeyAttrs`'s respective dictionaries must be used.

We should map those to a StrongDictionary which provides intelliSense and help use the right keys.

Security framework method to improve: https://github.com/xamarin/xamarin-macios/blob/master/src/Security/Certificate.cs#L531-L545

**Comment by spouliot** [comment]
it was also mentioned in https://bugzilla.xamarin.com/show_bug.cgi?id=34135
@VincentDondain please close (and cross-link) the old/bugzilla one since it's name does not make it easy to identify

**Comment by VincentDondain** [comment]
@spouliot I don't see where it was mentioned in https://bugzilla.xamarin.com/show_bug.cgi?id=34135. As far as I can tell that bug was only asking for the keys to be exposed. Which is the point of https://github.com/xamarin/xamarin-macios/pull/3350. I was thinking I'll close the bug when that PR lands (:

**Comment by spouliot** [comment]
@VincentDondain did you not merge this one yet ?

**Comment by VincentDondain** [comment]
Yes fixed in https://github.com/xamarin/xamarin-macios/pull/3438, I forgot to add this issue's number in my commit message.
