### ISSUE TITLE
[XI]MonoDataSqlite failures on a 32 bit device with Release+llvm config

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3370]
### Steps to Reproduce

1. Execute MonoDataSQLite tests on 32 bit device with Release+llvm config

### Expected Behavior
All tests should pass successfully.

### Actual Behavior
Tests failed.
Test Log: https://gist.github.com/GouriKumari/41e7bc778c0f9020bbf124ee919c0bde

### Environment
Xamarin.iOS
Version: 11.8.0.18 (Visual Studio Community)
Hash: 4c56cbbf
Branch: d15-6

Device: iPad2 9.3.5
Tests passed on 64 bit devices.

### Build Logs

Build Log: https://gist.github.com/GouriKumari/8981e719d23dd0f095f083d188dab8fa
Test Log: https://gist.github.com/GouriKumari/41e7bc778c0f9020bbf124ee919c0bde

###Regression: yes
d15-5
Build log: https://gist.github.com/GouriKumari/a391ef66e8240c653a59b570d863e6bd
Tets Log: https://gist.github.com/GouriKumari/54fd77fbc7fac8f7796a22057b08a244

**Comment by dalexsoto** [comment]
I can reproduce this in iPhone 5, can't repro in iPhone 6 Plus using latest d15-6 branch 4c56cbbf025378220b7fa46d66aad9b40d5eb90a

Test log: https://gist.github.com/dalexsoto/fc8bf0fc9d78f723203712189fcfa837

/cc @spouliot @vargaz

**Comment by rolfbjarne** [comment]
This test succeeds if I apply the fix for #3241, so I'm closing as a dup of that one.
