### ISSUE TITLE
[XI]MetalPerformance Shaders test failures on an iPadAir 

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3389]
### Steps to Reproduce

1. Build and Execute monotouch-test on an iPad Air 11.2.5  device. 
The device version of iPadAir is 11.2.5 and not 8.4. 

### Expected Behavior
All tests pass

### Actual Behavior
[FAIL] KernelTest.MPSKernelCopyTest : System.Exception : Could not initialize an instance of the type 'MetalPerformanceShaders.MPSKernel': the native 'initWithDevice:' method returned nil.
	[FAIL] KernelTest.MPSRnnImageInferenceLayerCopyTest : System.Exception : Could not initialize an instance of the type 'MetalPerformanceShaders.MPSRnnImageInferenceLayer': the native 'initWithDevice:rnnDescriptor:' method returned nil.
	[FAIL] KernelTest.MPSRnnMatrixInferenceLayerTest : System.Exception : Could not initialize an instance of the type 'MetalPerformanceShaders.MPSRnnMatrixInferenceLayer': the native 'initWithDevice:rnnDescriptor:' method returned nil.
	[FAIL] MPSImageHistogramEqualizationTest.Constructors : System.Exception : Could not initialize an instance of the type 'MetalPerformanceShaders.MPSImageHistogramEqualization': the native 'initWithDevice:histogramInfo:' method returned nil.
	[FAIL] MPSImageHistogramSpecificationTest.Constructors : System.Exception : Could not initialize an instance of the type 'MetalPerformanceShaders.MPSImageHistogramSpecification': the native 'initWithDevice:histogramInfo:' method returned nil.
	[FAIL] MPSImageHistogramTest.Constructors : System.Exception : Could not initialize an instance of the type 'MetalPerformanceShaders.MPSImageHistogram': the native 'initWithDevice:histogramInfo:' method returned nil.

### Environment

Observed on both d15-6 and master build
d15-6: Build Revision: 5b1f71685029d90d5e626fdbf6e38e429e15cff0

master: bec116c273ab119c648522a28c3f650881ed4d9e 

### Build Logs

http://xqa.blob.core.windows.net/gist/report-81276d9069974b2ca22fd8ead58b2e60.txt

**Comment by spouliot** [comment]
That's quite weird since those tests have:
```
TestRuntime.AssertXcodeVersion (9, 0);
```
so they should be ignored on iOS 8.4 and you should see something like
```
2018-02-06 11:04:25.051 monotouchtest[34611:8056336] 	[IGNORED] KernelTest.MPSKernelCopyTest : Requires the platform version shipped with Xcode 9.0
2018-02-06 11:04:25.051 monotouchtest[34611:8056336] 		  at TestRuntime.AssertXcodeVersion (System.Int32 major, System.Int32 minor) [0x0000f] in /Users/poupou/git/master/xamarin-macios/tests/common/TestRuntime.cs:97 
2018-02-06 11:04:25.051 monotouchtest[34611:8056336] 		  at MonoTouchFixtures.MetalPerformanceShaders.KernelTest.MPSKernelCopyTest () [0x00001] in /Users/poupou/git/master/xamarin-macios/tests/monotouch-test/MetalPerformanceShaders/KernelTest.cs:55 
2018-02-06 11:04:25.051 monotouchtest[34611:8056336] 		  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
2018-02-06 11:04:25.051 monotouchtest[34611:8056336] 		  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/poupou/git/master/xamarin-macios/external/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305 
```

Are you sure your tests revision were _in sync_ ?

**Comment by GouriKumari** [comment]
I rechecked the device-version. The device version on which this issue is happening is on iPadAir 11.2.5.

Test Log: https://gist.github.com/GouriKumari/05d9c12b3e1f09f74f92d792303568e9

GitRevison and XI version installed are same in bot: https://gist.github.com/GouriKumari/f92070a2d2038a4fe1338369bd168dca

**Comment by mandel-macaque** [comment]
@GouriKumari I have ran the tests with an iPad Air 2 with iOS 11.2 Build version 15C5092b with master 6f59487700ec9af031e2940209bdd4d803cf9286 and those tests do pass. On the other hand, I have a new failure:

[FAIL] PassTest.BoardingPass :   LocalizedName

**Comment by mandel-macaque** [comment]
@GouriKumari  also tested with d15-6 with the same device as the previous comment with hash 1c6f300ef26ff1fb06965a8accae473eb5f96ec3 and had no failures.

**Comment by spouliot** [comment]
@GouriKumari that makes no sense on that device/version. It's like MPS is not available
Please reboot the device and try again

**Comment by GouriKumari** [comment]
I retested manually. I could reproduce the issue before and after restart. 
## Logs:

Build log: https://gist.githubusercontent.com/GouriKumari/738bdba07f475b997370787d90102172/raw/f889b9f8e7cd02a159aeb1376f9f9d20dbd3575c/gistfile1.txt
Test Log: https://gist.github.com/GouriKumari/df21ec37645a7eb0836cadb293ce140a

iPad Air (MD785LL/A) Version 11.2.5 (15D60)

Test passes on an iPhone8 11.2.5 (15D60)

**Comment by mandel-macaque** [comment]
@spouliot I'm not an expert in Metal, but initWithDevice can fail if the device is not supported [docs](https://developer.apple.com/documentation/metalperformanceshaders/mpskernel/1618763-initwithdevice?language=objc). 

@GouriKumari you can confirm you tested with an iPad Air and not with an iPad Air 2, correct? It might be the case that the device is not longer supported and we need to modify the test to query if the device is supported via [MPSSupportsMTLDevice](https://developer.apple.com/documentation/metalperformanceshaders/1618849-mpssupportsmtldevice?language=objc).

I'll create a PR for @GouriKumari  to test in such a device (since I do not have one), that might solve the issue, I've got the feeling hat simply checking for the device to be null might not be sufficient.

**Comment by mandel-macaque** [comment]
@spouliot I'm thinking something like in the following [diff](https://gist.github.com/mandel-macaque/c6fae25d27c83f118a00462f3ab18b3d)
