### ISSUE TITLE
The `SceneKit.SCNSceneRenderer.OverlayScene` property can not be null (but should be)

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#3392]
I am working on the original Apple sample and found a difference between the API: I can set `null` to the 
[OverlayScene](https://developer.xamarin.com/api/property/SceneKit.ISCNSceneRenderer.OverlayScene/) property using `swift` but can not do it using `Xamarin`.

### Steps to Reproduce

1. Create an instance of `SCNView` 
2. Set not-nullable value to the `OverlayScene` property
3. Set `null` to the `OverlayScene` property 

### Expected Behavior
I can set `null` to the property and it will not crush.

### Actual Behavior
`System.ArgumentNullException` has been thrown.

### Environment

- https://gist.github.com/mykyta-bondarenko-gl/9ca1e16c1f358a21b25a54165c32464e
- swift
```
sceneRenderer?.overlaySKScene = nil
```
- xamarin
```
this.sceneRenderer.OverlayScene = null;
```

### Build Logs

- https://gist.github.com/mykyta-bondarenko-gl/6c453f577c2c4cca4d6a70bd3326e69d

### Example Project 

- [Link to the Xamarin project](https://github.com/mykyta-bondarenko-gl/private-samples/tree/fox-2-scenekit/ios11/Fox2)
- [Link to the original project](https://developer.apple.com/library/content/samplecode/scenekit-2017/Introduction/Intro.html)

**Comment by spouliot** [comment]
The ObjC [documentation](https://developer.apple.com/documentation/scenekit/scnscenerenderer/1524051-overlayskscene?language=objc) does not mention it's `nullable`

However it's optional on the swift [documentation](https://developer.apple.com/documentation/scenekit/scnscenerenderer/1524051-overlayskscene)
