### ISSUE TITLE
[XI]OptimizeGeneratedCodeTest.IntPtrSizeTest :   non-empty body [LinkAll test] failed with Release config on device

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3395]
### Steps to Reproduce

1.  Update System to xamarin.ios-master build, bec116c273ab119c648522a28c3f650881ed4d9e
2. Execute LinkAll tests on device with Release config with or without llvm enabled

### Expected Behavior
All tests should pass

### Actual Behavior
OptimizeGeneratedCodeTest.IntPtrSizeTest :   non-empty body [LinkAll test] failed with Release config on device

### Environment
Build Revision: bec116c273ab119c648522a28c3f650881ed4d9e

### Build Logs
http://xqa.blob.core.windows.net/gist/report-ca1699f85bad479ba01cba5e783f7d78.txt
Test Logs: 
http://xqa.blob.core.windows.net/gist/linkall-ios07-50-59e978c67571aa0652bdb4ad6b8338ec46633e07ef07-50-59-2efba24d567e4e4bac8ede85435be3bc.zip

**Comment by rolfbjarne** [comment]
I can reproduce this, I'll have a look.
