### ISSUE TITLE
MTOUCH : error MT3001: Could not AOT the assembly in eShopOnContainers sample

### ISSUE THREAD

**Issue by kdubau** [xamarin/xamarin-macios#3407]
### Steps to Reproduce

1. Clone https://github.com/dotnet-architecture/eShopOnContainers
2. `nuget restore eShopOnContainers-iOS.sln`
3.  `msbuild eShopOnContainers-iOS.sln /p:Platform=iPhone /p:Configuration=Debug /p:MtouchArch="ARM64" /p:CodesignKey="<your key>" /p:CodesignProvision="<your dev profile>"`

### Expected Behavior
Build succeeds.

### Actual Behavior
AOT compilation fails.
```
"/Users/kylewhite/Workspace/eShopOnContainers/eShopOnContainers-iOS.sln" (default target) (1) ->
"/Users/kylewhite/Workspace/eShopOnContainers/src/Mobile/eShopOnContainers/eShopOnContainers.TestRunner.iOS/eShopOnContainers.TestRunner.iOS.csproj" (default target) (5) ->
(_CompileToNative target) ->
  MTOUCH : error MT3001: Could not AOT the assembly '/Users/kylewhite/Workspace/eShopOnContainers/src/Mobile/eShopOnContainers/eShopOnContainers.TestRunner.iOS/obj/iPhone/Debug/mtouch-cache/64/Build/eShopOnContainers.Core.dll' [/Users/kylewhite/Workspace/eShopOnContainers/src/Mobile/eShopOnContainers/eShopOnContainers.TestRunner.iOS/eShopOnContainers.TestRunner.iOS.csproj]
```

### Environment

```
=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.4 Preview (7.4 build 987)
Installation UUID: 095c3e25-bd72-4b0a-ba05-d4ae011890ba
Runtime:
	Mono 5.8.0.123 (2017-10/38502063cac) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000123

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.1.0
	1.0.4
	1.0.2
	1.0.1
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
	1.0.1
	1.0.0-preview4-004071
	1.0.0-preview2-1-003177
	1.0.0-preview2-003148
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.12 (Visual Studio Community)
Android SDK: /Users/kylewhite/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.2   (API level 17)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.0.19 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.8.0.19 (Visual Studio Community)
Hash: 5b1f7168
Branch: d15-6
Build date: 2018-02-01 18:50:51-0500

=== Build Information ===

Release ID: 704000987
Git revision: cc6c54322b956f90a41870157c10778fd20e9f6c
Build date: 2018-02-05 09:12:46-05
Xamarin addins: 612453baa9a0faea49aa554be49c01c2e0542bf3
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64


```

### Build Logs
This is the diagnostic build output with `/p:MtouchExtraArgs="-v -v -v"`: http://xqa.blob.core.windows.net/gist/17_Build-solution-eShopOnContainers-iOS.sln-iPhone.txt-89515e1b5a3f4498a56668e1044ba52c.txt

### Example Project (If Possible)
Easiest to clone the repo above.

**Comment by spouliot** [comment]
c.c. @vargaz

**Comment by kdubau** [comment]
I should add this happens with the latest commit on that sample repo, but since that might change, it's this commit https://github.com/dotnet-architecture/eShopOnContainers/commit/5b25dfdd256723377ce0da75c5ff162351557d03 at this time.

**Comment by mandel-macaque** [comment]
@kdubau is there any steps I need to follow to compile the app and test it? I did a simple checkout but had the following errors: https://gist.github.com/mandel-macaque/7b5f0c7aaf8fa18ddcc23761aa023de7

**Comment by spouliot** [comment]
@mandel-macaque gist seems incomplete (truncated?)
can you paste the error here (in GitHub) and link to the build log with less verbosity (from msbuild) ?

**Comment by mandel-macaque** [comment]
@spouliot build is complete (gist trucates it, but you can access it) but I'll do an other gist with a smaller amount of verbosity for use to have the information.

**Comment by kdubau** [comment]
@mandel-macaque you should build `eShopOnContainers-iOS.sln` not `eShopOnContainers.sln`.

**Comment by mandel-macaque** [comment]
@kdubau will get back to you asap, thx for the feedback.

**Comment by mandel-macaque** [comment]
@kdubau I just tested the application with master after the mono bump and I got the application to compile and run in an iPad Air 2.

Build env: https://gist.github.com/mandel-macaque/b7b746752e913f88d5d942fd96cca748
Build output: https://gist.github.com/mandel-macaque/f9f73fd8caa597756c276a023a722fb0

commit of the branch: 5b25dfdd256723377ce0da75c5ff162351557d03
