### ISSUE TITLE
Wrong resx resources chosen when multiple languages setup on iOS

### ISSUE THREAD

**Issue by KennethKr** [xamarin/xamarin-macios#3420]
If you setup resx files for several languages and add more languages on the iPhone, the prime language  doesnt seem to be chosen. I've added Norwegian as the only language in a project with a norwegian and english resx, then it works, if I add english as the secondary language on the phone, then the english resx is chosen.

### Steps to Reproduce

1. Add a project with a "Strings.nb-NO.resx" and a "Strings.resx"
2. Setup an iPhone with Norwegian prime language (any language will ofc do, I'm Norwegian..) and English or several other languages and secondary languages

### Expected Behavior

Since Norwegian is the prime language, the nb-NO resx should be chosen. This works when Norwegian is the only language installed on the phone, but fails when I add english as a secondary or supported language

### Actual Behavior

English resx is chosen

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.3.3 (build 5)
Installation UUID: dfec3931-428b-4306-bdf4-b73a222dfc74
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.0
	1.1.4
	1.1.2
	1.1.1
	1.0.7
	1.0.5
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.0.2/Sdks
SDK Versions:
	2.0.2
	2.0.0
	1.1.4
	1.0.4
	1.0.0-rc4-004919
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.3 (Visual Studio Community)
Hash: f70a1348
Branch: xcode9.2
Build date: 2017-12-18 14:47:16-0500

=== Xamarin.Android ===

Version: 8.1.3.0 (Visual Studio Community)
Android SDK: /Users/kenneth/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.0
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 4.0.0.215 (Visual Studio Community)

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703030005
Git revision: b1c2982e201e71ef758866c9ade05f253a8c6f47
Build date: 2017-12-21 11:04:40-05
Xamarin addins: f397ddfbacfb39e60c9cc8d9e410f73faf8c2cbc
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

MvvmCross Template pack 2.0.1
Internet of Things (IoT) development (Preview) 7.1


```

### Example Project (If Possible)
Coming.

**Comment by mandel-macaque** [comment]
Hello, this might be an issue related with [bug 59596](https://bugzilla.xamarin.com/show_bug.cgi?id=59596) 

It is important, not only that you add the resources files but that you let the iOS system know that your application is translated, and which languages it supports. Please can you confirm you are doing so, there is a nice explanation in the following [comment](https://bugzilla.xamarin.com/show_bug.cgi?id=59596#c8).

**Comment by KennethKr** [comment]
Thank you @mandel-macaque. I added the below code to my Info.plist, and now it seems to work.

```
	<key>CFBundleLocalizations</key>
	<array>
		<string>nb</string>
		<string>en</string>
	</array>
```

**Comment by mandel-macaque** [comment]
@KennethKr this is a common mistake. As a rule of thumb, remember that you have to let the iOS system know the app is translated, even if you are not using the Apple translation services, so adding the list is a must. Closing the issue :)
