### ISSUE TITLE
PassTest.BoardingPass : LocalizedName fails on iPad Air 2 device iOS 11.2

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#3445]
### Steps to Reproduce

1. make run-ios-dev64-monotouch-tests using an  iPad Air 2 with iOS 11.2 Build version 15C5092b 

### Expected Behavior

All tests pass.

### Actual Behavior

[FAIL] PassTest.BoardingPass : LocalizedName

### Environment

Failure occurs in

master: https://github.com/xamarin/xamarin-macios/commit/6f59487700ec9af031e2940209bdd4d803cf9286
d15-6: https://github.com/xamarin/xamarin-macios/commit/1c6f300ef26ff1fb06965a8accae473eb5f96ec3

**Comment by spouliot** [comment]
IIRC a large part of PassKit does not work on iPad
@mandel-macaque can you check the tests ? in case it's missing a check to exclude iPads
also add the stack trace of the failure, makes it easier to see what's going on without an iPad around :)

**Comment by rolfbjarne** [comment]
Seems like a language problem.

I get this on one device:

```
	[FAIL] PassTest.BoardingPass :   LocalizedName
  String lengths are both 13. Strings differ at index 9.
  Expected: "Boarding Pass"
  But was:  "Boarding Card"
```

and this on another:

```
	[FAIL] PassTest.BoardingPass :   LocalizedName
  Expected string length 13 but was 19. Strings differ at index 0.
  Expected: "Boarding Pass"
  But was:  "Tarjeta de embarque"
```

**Comment by spouliot** [comment]
we better just assert it's not null for localized output
anything else will be painful to maintain

**Comment by mandel-macaque** [comment]
@spouliot what about the following:

```
var culture = CultureInfo.CurrentCulture.Name;
if (cultureInfo == expectedCultureInfo) {
    Assert.That (pass.LocalizedDescription, Is.EqualTo ("Skyport Boarding Pass"),
        "LocalizedDescription");
    Assert.That (pass.LocalizedName, Is.EqualTo ("Boarding Pass"), "LocalizedName");
} else {
     Assert.That(string.IsNullOrEmpty(pass.LocalizedDescription), Is.False, "LocalizedDescription");
     Assert.That(string.IsNullOrEmpty(pass.LocalizedName), Is.False, "LocalizedName");
}
```

**Comment by mandel-macaque** [comment]
Although just ensuring is not null or empty would be good enough an simple.

**Comment by spouliot** [comment]
There are nunit attributes to set the current culture (for a test)
However that (like your code) does not map to iOS native language - so that will still fail

**Comment by mandel-macaque** [comment]
@spouliot yeah, I'll simply add test to ensure that is not null or empty, that will be more maintainable. (PR in the way).
