### ISSUE TITLE
System.ComponentModel.DataAnnotations throws exception on IOS Actual Device

### ISSUE THREAD

**Issue by jassmith** [xamarin/xamarin-macios#3449]
_From @kishorupare on February 9, 2018 9:44_

I have use System.ComponentModel.DataAnnotations in portable class project. This work great in Android Actual Device but failed on IOS actual device. In IOS emulator it work great but not on Actual iPhone. It thows deployment error as 

Could not AOT the assembly '/Users/rnr_mac/Library/Caches/Xamarin/mtbs/builds/RujulERP_Mobile.iOS/43d2ca3e2c725a70d6f4c6086aa946e8/obj/iPhone/Debug/mtouch-cache/64/Build/System.ComponentModel.DataAnnotations.dll'	RujulERP_Mobile.iOS			

_Copied from original issue: xamarin/Xamarin.Forms#1851_

**Comment by spouliot** [comment]
The Ahead-of-Time (AOT) compiler is only used on device builds. It's a requirement from Apple - using the Just-In-Time (JIT) compiler is not allowed on the App Store.

The [MT3001](https://developer.xamarin.com/guides/ios/troubleshooting/mtouch-errors/#MT3001_Could_not_AOT_the_assembly_) error means the AOT compiler did not produce any output. IOW something went wrong when compiling it - but it does not tell us why.

Please either attach:

* a test case that demonstrate the issue; or
*  your complete build log we can see more details from the AOT compiler output.

Thanks!

**Comment by kishorupare** [comment]
Test case is simple. I have Create EnumPicker same as mentioned in "[](https://intellitect.com/xamarin-forms-enumbindablepicker)/" with description. You can create sample project with EnumPicker and test on iPhone, you will easily get the issue. This work great in Android but failed in IOS. 
will this helpful for you or else guide me to get complete build log since application get crash with error
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not AOT the assembly '/Users/rnr_mac/Library/Caches/Xamarin/mtbs/builds/RujulERP_Mobile.iOS/43d2ca3e2c725a70d6f4c6086aa946e8/obj/iPhone/Debug/mtouch-cache/64/Build/System.ComponentModel.DataAnnotations.dll'	RujulERP_Mobile.iOS

**Comment by spouliot** [comment]
I'm sorry but

> I have Create EnumPicker same as mentioned in "/" with description

does not mean anything to me. I guess it's a XF template ? but without version information I'm not sure it would yield the same results.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by kishorupare** [comment]
Thanks for reply and guidance. 
Exact version information and full build log are attached here. please check them and do inform if required further information.
[VersionInfo.txt](https://github.com/xamarin/xamarin-macios/files/1718889/VersionInfo.txt)
[Build Error.txt](https://github.com/xamarin/xamarin-macios/files/1718905/Build.Error.txt)
[Build Output File.txt](https://github.com/xamarin/xamarin-macios/files/1718906/Build.Output.File.txt)
[Xamarin Dignostic File.txt](https://github.com/xamarin/xamarin-macios/files/1718908/Xamarin.Dignostic.File.txt)

**Comment by spouliot** [comment]
The error was

```
1>  Cannot open assembly '/Users/rnr_mac/Library/Caches/Xamarin/mtbs/builds/RujulERP_Mobile.iOS/43d2ca3e2c725a70d6f4c6086aa946e8/obj/iPhone/Debug/mtouch-cache/32/Build/System.ComponentModel.DataAnnotations.dll': File does not contain a valid CIL image. (TaskId:134)
```

and this is not the version of `System.ComponentModel.DataAnnotations.dll` that ships with Xamarin.iOS. 

```
1>  Dependency "System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35". (TaskId:75)
1>      Resolved file path is "D:\RujulERP\Rujul-TradeERP\Project-RujulTradeERP\RujulERP-Mobile\RujulERP-Mobile\RujulERP_Mobile\bin\Debug\System.ComponentModel.DataAnnotations.dll". (TaskId:75)
1>      Reference found at search path location "D:\RujulERP\Rujul-TradeERP\Project-RujulTradeERP\RujulERP-Mobile\RujulERP-Mobile\RujulERP_Mobile\bin\Debug". (TaskId:75)
1>          For SearchPath "D:\RujulERP\Rujul-TradeERP\Project-RujulTradeERP\RujulERP-Mobile\RujulERP-Mobile\RujulERP_Mobile\bin\Debug". (TaskId:75)
1>          Considered "D:\RujulERP\Rujul-TradeERP\Project-RujulTradeERP\RujulERP-Mobile\RujulERP-Mobile\RujulERP_Mobile\bin\Debug\System.ComponentModel.DataAnnotations.winmd", but it didn't exist. (TaskId:75)
1>      Required by "D:\RujulERP\Rujul-TradeERP\Project-RujulTradeERP\RujulERP-Mobile\RujulERP-Mobile\RujulERP_Mobile\bin\Debug\RujulERP_Mobile.dll". (TaskId:75)
1>      Required by "Syncfusion.Linq.iOS, Version=15.2451.0.46, Culture=neutral, processorArchitecture=MSIL". (TaskId:75)
1>      The ImageRuntimeVersion for this reference is "v4.0.30319". (TaskId:75)
```

it should have been resolved from under

```
1>  TargetFrameworkDirectories: (TaskId:75)
1>      E:\Program Files\VS and SDK\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\,E:\Program Files\VS and SDK\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\ (TaskId:75)
```

Somehow your project has a reference to a different binary. We'll need a self contained test case to figure out what it is.

**Comment by kishorupare** [comment]
I have given reference of same dll from E:\Program Files\VS and SDK\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0 in IOS project only. but this time also build failed.
Please suggest how can i move further

**Comment by spouliot** [comment]
> Please suggest how can i move further

Like I mentioned before: _We'll need a self contained test case to figure out what it is._ Please attach one to the issue and we'll have a look at it.

**Comment by therealjohn** [comment]
@kishorupare 
We have not received the requested information. If you are still experiencing this issue please provide a self contained test case and then click the Reopen Issue button. Thanks!
