### ISSUE TITLE
[XI]BluetoothLeExplorer sample fails to build with Native Linking error with master build

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3463]
### Steps to Reproduce

1. Open https://github.com/xamarin/mobile-samples/tree/master/BluetoothLEExplorer/BluetoothLEExplorer.iOS
2. Build the sample

### Expected Behavior
App should build successfully.

### Actual Behavior
App fails to build with error. MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MBProgressHUDDelegate. The symbol '_OBJC_CLASS_$_MBProgressHUDDelegate' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5202: Native linking failed. Please review the build log.
### Environment

Test Env: Xamarin.iOS
Version: 11.9.0.158 (Visual Studio Community)
Hash: a2afb859

https://gist.github.com/GouriKumari/7c566debdbda3b72c152bfcfc9753ae7

### Build Logs

With master: https://gist.github.com/GouriKumari/c3423cde53c33d51094e7a49e2e5d899

### Example Project (If Possible)

https://github.com/xamarin/mobile-samples/tree/master/BluetoothLEExplorer/BluetoothLEExplorer.iOS

### Regression: yes
Sample builds with d15-6 and d15-5 successfully.
Build Log with d15-6: https://gist.github.com/GouriKumari/e39cefd353c27a2c23f2618d60cc0e9c

**Comment by VincentDondain** [comment]
Hi,

Couple of precisions:

1. The sample from https://github.com/xamarin/mobile-samples/tree/master/BluetoothLEExplorer/BluetoothLEExplorer.iOS isn't up to date, you need to remove `[Register]` that are used between 2 partial classes.
2. The repro is to build against **device**.

Other than that, I could indeed reproduce the MT5211 error with Xamarin.iOS 11.9.0.163. https://gist.github.com/VincentDondain/199453df8f071be235744813ea6431b0

**Comment by spouliot** [comment]
c.c. @rolfbjarne not a lot of changes in this area since 15.6 - at least beside yours :)

**Comment by IndraXamarin** [comment]
We have a Mac app in production that uses bluetooth and that needs a very urgent fix for the issue  https://bugzilla.xamarin.com/show_bug.cgi?id=60696. 

Could Xamarin confirms if it's woking on it and give an estimate on timescales?

Regards

**Comment by rolfbjarne** [comment]
The mbprogresshud component is wildly out of date (it was generated before this fix was released: https://github.com/xamarin/maccore/commit/b9f39f537bb39fa69a1312be097f127901d7b652, i.e. over three years ago).

The fix is to update the component to use the NuGet version instead (which is more up-to-date).
