### ISSUE TITLE
Storyboard/Designer doesn't allow to set font size bigger than 200

### ISSUE THREAD

**Issue by JosePendao** [xamarin/xamarin-macios#3479]
### Steps to Reproduce

1. Open Sample Project 
![image](https://user-images.githubusercontent.com/32713788/36210973-ca2b0c02-1197-11e8-9f01-71e26e040b99.png)

2. Try to set font size > 200 on the Widget, you see that it does not apply
![image](https://user-images.githubusercontent.com/32713788/36210995-d5b1b30a-1197-11e8-8143-5853f0ecdbee.png)

3. If you set it to 150  and you see that it applies correctly
4. This can be done (increase the font size to greater values than 200) through Code, not trough Designer

[200ISSUE.zip](https://github.com/xamarin/xamarin-macios/files/1724440/200ISSUE.zip)

### Expected Behavior
The font size inside the Label changes according to the value specified on the properties window
### Actual Behavior
If the value specified on the Font Size is greater than 200 the value is not applied
### Version Information
Microsoft Visual Studio Enterprise 2017 Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027 
Microsoft .NET Framework Version 4.7.02556
Installed Version: Enterprise

Visual Studio Tools for Universal Windows Apps   15.0.27130.2020
VisualStudio.Mac   1.0 - Mac Extension for Visual Studio
Xamarin   4.8.0.760 (fc93f3f5b) - Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin Designer   4.8.188 (c5813fa34) - Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
Xamarin.iOS and Xamarin.Mac SDK   11.6.1.4 (db807ec)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

> VS bug [#595246](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/595246)

**Comment by alanmcgovern** [comment]
Hi,

It looks like this value used the be the maximum supported by iOS/Xcode back in the day, and we did not update the value when the restriction was lifted from Xcode.

For tracking purposes: https://github.com/xamarin/designer/commit/7fa509e2411d946eb64cb8b4d7a5e8842da94e5b

**Comment by xamarin-release-manager** [comment]
> [sync] [VS-10] Comment by **xamarinc**



Fixed in version 4.18.0.886 (master)



Author: Denis Kandrov  
 Commit: 26981fdd3946f76c9ed7fd30af927686106888ed (xamarin/designer)
