### ISSUE TITLE
linkall fails `LinkAllRegressionTest.AssemblyReferences_16213` with mono 2017-12

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#3480]
### Steps to Reproduce

1. Run linkall unit tests

### Expected Behavior

No failure

### Actual Behavior

`LinkAllRegressionTest.AssemblyReferences_16213` fails

### Environment

master with mono/2017-12

**Comment by marek-safar** [comment]
What is `AssemblyReferences_16213` test about?

**Comment by spouliot** [comment]
it's a canary test so we can detect if `System.Transactions.dll` ever becomes a requirement of the test app (that requirement was removed a long time ago). The app only creates an instance of `SqlConnection`.
