### ISSUE TITLE
[tvOS]LinkExtraDefsTest tests failed on device with Release config

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3516]
### Steps to Reproduce

1. Update System to Xamarin.iOS master mtouch 11.9.0.254 (master: 4cd3f5c2)
2. Execute LinkSdk test with Release config

### Expected Behavior
Tests should pass 
### Actual Behavior
[FAIL] LinkExtraDefsTest.Corlib :   System.Security.PermissionSet
[FAIL] LinkExtraDefsTest.MonoTouch :   [MonoTouch.]CoreBluetooth.CBUUID
[FAIL] LinkExtraDefsTest.System :   System.Net.Mime.ContentType
### Environment
```
mtouch 11.9.0.254 (master: 4cd3f5c2)
```

### Build Logs

http://xqa.blob.core.windows.net/gist/report-28e12fb77c284a08bab99623d1a6b996.txt

Test and Device Log: 
http://xqa.blob.core.windows.net/gist/linksdk-tvos12-38-39b4bdf4adae9fadc66c4ed145b08d35266ec7262c12-38-39-bf21e6ebbc624547b7855338ab0af5bc.zip

**Comment by VincentDondain** [comment]
Confirmed with build logs links in description.

**Comment by spouliot** [comment]
This project should be built with `-xml=${ProjectDir}/extra-linker-defs.xml "` and I don't see it in the build logs.

**Comment by rolfbjarne** [comment]
The same thing happens on our device bots (and locally for me). I'll have a look.
