### ISSUE TITLE
Notification Service Extension does not work in iOS 11 (Rich Push)

### ISSUE THREAD

**Issue by oristanovic** [xamarin/xamarin-macios#3526]
### Steps to Reproduce
 
This is a follow up to the issue https://github.com/xamarin/xamarin-macios/issues/3176

1. Build a blank app with associated Notification Service Extension on device running iOS 11 (11.2.1)
2. Build the same app on iOS 10 (10.3.3)

### Expected Behavior

The Notification Service Extension should not be killed by the system and the rich push should be displayed

### Actual Behavior

The Notification Service Extension is killed by the system and the rich push isn't displayed
### Environment

Visual Studio 7.3.2 (build 12)
Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
Xamarin.iOS 11.6.1.2 (Visual Studio Community)
Xcode 9.2 (13772)

### Build Logs
We did further testing and here's what we got:
No problem whatsoever with Xamarin app running on iOS 10 or with the native app running on iOS 11.
However, every single time we send a rich notification to a Xamarin app running on iOS 11 we get the following log:

Feb 15 10:29:17 iPhone SpringBoard(ApplePushService)[19082] : Delivering message from apsd: 13691 
Feb 15 10:29:17 iPhone SpringBoard(ApplePushService)[19082] : responding with an ack for message with guid 
Feb 15 10:29:17 iPhone SpringBoard(ApplePushService)[19082] : making delegate () calls to deliver message 13691 for topic 
Feb 15 10:29:17 iPhone SpringBoard(ApplePushService)[19082] : calling connection:didReceiveIncomingMessage:
Feb 15 10:29:17 iPhone SpringBoard(ApplePushService)[19082] : returned from connection:didReceiveIncomingMessage:
Feb 15 10:29:17 iPhone SpringBoard(UserNotificationsServer)[19082] : Received incoming message on topic com.accengage.app.recette at priority 10
Feb 15 10:29:17 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette] Received remote notification request 15DD-0D22 [ hasAlertContent: 1, hasSound: 1 hasBadge: 1 hasContentAvailable: 0 hasMutableContent: 1 ]
Feb 15 10:29:17 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette] Getting notification settings
Feb 15 10:29:17 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette] Getting section info
Feb 15 10:29:17 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette] Got section info [ hasResult: 1 ]
Feb 15 10:29:17 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette] Got notification settings [ hasResult: 1 ]
Feb 15 10:29:17 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette] Remote notification request 15DD-0D22 can be modified: 1
Feb 15 10:29:17 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette] Trying to find extension for bundle
Feb 15 10:29:17 iPhone analyticsd[21230] : [] no observers; dropped.
Feb 15 10:29:17 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette] Extension can modify push notification request 15DD-0D22? YES
Feb 15 10:29:17 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette.AccengageNotificationService] Beginning extension session...
Feb 15 10:29:17 iPhone assertiond[67] : PID 19082 requested an assertion for unknown process 21968 that doesn't seem to be an extension
Feb 15 10:29:17 iPhone SpringBoard(PlugInKit)[19082] : plug-in pre-screen sees activating state
Feb 15 10:29:17 iPhone pkd[21878] : allowing host 19082 /System/Library/CoreServices/SpringBoard.app/SpringBoard to use plug-in () uuid=4AB08512-0E3D-4532-A184-C5295B5F1BDA at 
Feb 15 10:29:17 iPhone NotificationServiceExtension(libxamarin-debug.dylib)[22041] : Xamarin.iOS: IDE Port: 51530 Transport: USB
Feb 15 10:29:18 iPhone CommCenter(libATCommandStudioDynamic.dylib)[16783] : QMI: Svc=0x03(NAS) Ind MsgId=0x0051 Bin=['01 1F 00 80 03 04 04 03 35 51 00 13 00 14 06 00 AF F4 8E FF 00 00 A2 01 00 32 A4 03 00 01 64 00']
Feb 15 10:29:18 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette.AccengageNotificationService] Extension will be killed due to sluggish startup
Feb 15 10:29:18 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette] Deliver push notification request 15DD-0D22
Feb 15 10:29:18 iPhone SpringBoard(UserNotificationsServer)[19082] : [com.accengage.app.recette] Send willPresentNotification for notification 15DD-0D22
Feb 15 10:29:18 iPhone SpringBoard(PlugInKit)[19082] : connection to plug-in (4AB08512-0E3D-4532-A184-C5295B5F1BDA) lost
Feb 15 10:29:18 iPhone SpringBoard(PlugInKit)[19082] : Hub connection error Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.accengage.app.recette.AccengageNotificationService" UserInfo={NSDebugDescription=connection to service named com.accengage.app.recette.AccengageNotificationService}

**Comment by dalexsoto** [comment]
I've reopened original issue https://github.com/xamarin/xamarin-macios/issues/3176 in favor of this one so we can have all the info in a single thread. Thanks!
