### ISSUE TITLE
[AppKit] NSApplication.NextEvent should have an override that takes a strongly typed NSRunLoopMode

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/xamarin-macios#3540]
The current declaration takes a string, which we have to marshal, and internally, might not be compared for content equality, but for pointer equality.

```
                [Export ("nextEventMatchingMask:untilDate:inMode:dequeue:"), Protected]
                NSEvent NextEvent (nuint mask, NSDate expiration, string mode, bool deqFlag);
```

**Comment by dalexsoto** [comment]
Is now being addressed here https://github.com/xamarin/xamarin-macios/pull/3542
