### ISSUE TITLE
Unnecessary calls to NSNull.Null slows performance

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#3544]
### Steps to Reproduce

1. Use test case from here: https://github.com/xamarin/xamarin-macios/issues/3488#issuecomment-366817032
2. The code ends up converting a native `NSArray` with thousands of elements to a managed `NSMenuItem[]`.
3. Each array element ends up calling `NSArray.UnsafeGetItem<T>`, which calls `NSNull.Null.Handle`: https://github.com/xamarin/xamarin-macios/blob/2a964030a88efc35acfa987778da7950bb32d1f3/src/Foundation/NSArray.cs#L342

The call to `NSNull.Null` will call native code every time, and also spend time finding/creating the managed wrapper, just to get the handle.

I think it would be better to have a static `NSNull.NullHandle` field, which is used instead:

```csharp
static IntPtr null_handle;
internal IntPtr NullHandle {
    get {
        if (null_handle == IntPtr.Zero)
            null_handle = ...;
        return null_handle;
    }
}
```

**Comment by spouliot** [comment]
We could make `NSNull.Null` avoid (expect the first time) a call to native code (i.e. cache it).
That would not introduce a new API and fix both our (internal) and user code.
