### ISSUE TITLE
[Xcode 9.3] MetalPerformanceShaders Bindings

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/xamarin-macios#3553]
### Bindings of MetalPerformanceShaders and MPS* sub frameworks

Changes introduced in `MetalPerformanceShaders` in Xcode 9.3 are marked as **experimental** inside `MetalPerformanceShaders.h` so we have no way to know which APIs are going to stay and which ones are going to change.

In order to avoid breaking changes in our binaries we will postpone the bindings until we get a more clear picture where the API is going.

https://github.com/xamarin/xamarin-macios/wiki/xcode9.3-Bindings-Status

**Comment by dalexsoto** [comment]
Part 1 of MPS is up https://github.com/xamarin/xamarin-macios/pull/5466

This includes updates for:

MetalPerformanceShaders.framework
MPSCore.framework
MPSImage.framework
MPSMatrix.framework
MPSRayIntersector.framework

Pending:

MPSNeuralNetwork.framework

**Comment by praeclarum** [comment]
Referring to all of these apis: https://github.com/xamarin/xamarin-macios/blob/49ef93670171ef4e11656a8ed0f3e99f20079c65/tests/xtro-sharpie/iOS-MetalPerformanceShaders.ignore#L201

**Comment by dalexsoto** [comment]
Hello @praeclarum we hear you!

I am actively working on `MetalPerformanceShaders` that includes `MPSNeuralNetwork.framework` right now, we could not do it earlier (back on Xcode 9.3) because it was an API that was marked as experimental and just promoted to stable in Xcode 10 and we have a hard policy to maintain binary compatibility between our releases. Also the task to bind it has been pushed back in the past in favor of other tasks mainly because we have not had any previous request for it.

I expect to have this done within the Xcode 10.2 timeframe so hopefully all of this should go out with the next stable release that includes [Xcode 10.2](https://github.com/xamarin/xamarin-macios/commits/xcode10.2), we are tracking our binding progress [here](https://github.com/xamarin/xamarin-macios/wiki/xcode10.2-Bindings-Status).

Now if you want to get your hands dirty what I would do is create a binding project with the classes you need, if you are using other MPS classes that comes from Xamarin.iOS.dll you should automatically link against MPS framework, else you can give `-framework MetalPerformanceShaders` to `mtouch` in your main project.

Or

You can checkout [xcode10.2](https://github.com/xamarin/xamarin-macios/commits/xcode10.2) branch add your classes into [metalperformanceshaders.cs](https://github.com/xamarin/xamarin-macios/blob/xcode10.2/src/metalperformanceshaders.cs) and [build the repo](https://github.com/xamarin/xamarin-macios/wiki/Build-&-Run) and use that `Xamarin.iOS.dll` in your project.

Hope this helps and sorry for the delay.

**Comment by praeclarum** [comment]
Thanks for the details @dalexsoto! I realize I'm probably the only one requesting them but I promise I'll write a beautiful .NET library to use them once available :-) 

I've failed in the past binding the native APIs because I would run into registrar errors. But maybe I'll give it another go. It's just such a big library haha.

**Comment by dalexsoto** [comment]
Hello @praeclarum we just merged the last bits of MetalPerformanceShaders into our xcode10.2 branch, you can have the following builds to give them a go you might want to install Xcode 10.2 Beta along with these:

* https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10.2/46fbf5e76e44c5a9c4c5dd6ccf34eb536d0f6b96/47/package/xamarin.ios-12.4.0.58.pkg

* https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10.2/46fbf5e76e44c5a9c4c5dd6ccf34eb536d0f6b96/47/package/xamarin.mac-5.4.0.58.pkg 

Feel free to open issues if you encounter anything wrong.

Cheers!
