### ISSUE TITLE
[Mac] Help with Runtime.GetNSObject on a dynamically loaded Xamarin.Mac runtime

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/xamarin-macios#3555]
I am trying to update Mono's Winforms stack to use Cocoa, and would like to do this without
setting up a bundle.   There are a few blog posts that describe how to achieve this, but before
I can even get there, I ran into a Xamarin.Mac problem that prevents me from getting the basics
in place.

The `NSApplication.SharedApplication` property is supposed to initialize `NSApplication` on 
demand, and this seems to work, but I get a `null` from our own runtime, which seems to fail
to locate the type.

I could use some help figuring out how to make this work.

### Steps to Reproduce

1. Download the application attached here (a Xamarin.Mac application), compile.
2. Go into the shell and run this command:

```
$ cd loader/bin/Debug/loader.app/Contents/MonoBundle
$ DYLD_LIBRARY_PATH=/Library/Frameworks/Xamarin.Mac.framework/Versions/Current//lib/ MONO_PATH=. mono loader.exe 
```
Reports that the `NSApplication.SharedApplication` is null, despite the fact, that it is not.   
The code immediately following it shows that calling the low-level code returns a value,
and if you look at the class for the type, it returns an actual NSApplication object, but 
somehow the logic in Runtime.TryGetNSObject<NSApplication> does not return a match.

### Expected Behavior

This should show the first line of the output as:

```
$ DYLD_LIBRARY_PATH=/Library/Frameworks/Xamarin.Mac.framework/Versions/Current//lib/ MONO_PATH=. mono loader.exe 
NSApplication.Shared is: <NSApplication: 0x604000116da0>
...
```

### Actual Behavior

When executed from the command line, the first line of output shows a null result:

```
$ DYLD_LIBRARY_PATH=/Library/Frameworks/Xamarin.Mac.framework/Versions/Current//lib/ MONO_PATH=. mono loader.exe 
NSApplication.Shared is: 
...
```
### Example Project (If Possible)

[loader.tar.gz](https://github.com/xamarin/xamarin-macios/files/1742798/loader.tar.gz)

**Comment by spouliot** [comment]
My current mono is not in sync with XM master

```
DYLD_LIBRARY_PATH=/Library/Frameworks/Xamarin.Mac.framework/Versions/Current//lib/ MONO_PATH=. mono loader.exe 
Corlib not in sync with this runtime: expected corlib version 1051000001, found 1051000002.
Loaded from: /Users/poupou/Downloads/loader/loader/bin/Debug/loader.app/Contents/MonoBundle/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```

However using the launcher from the app seems to work from the command-line

```
DYLD_LIBRARY_PATH=/Library/Frameworks/Xamarin.Mac.framework/Versions/Current//lib/ MONO_PATH=. ../MacOS/loader loader.exe 
objc[14641]: Class JSExport is implemented in both /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore (0x7fffadcc0f60) and /Users/poupou/Downloads/loader/loader/bin/Debug/loader.app/Contents/MonoBundle/../MacOS/loader (0x1044a0090). One of the two will be used. Which one is undefined.
objc[14641]: Class MTLCaptureScope is implemented in both /System/Library/Frameworks/Metal.framework/Versions/A/Metal (0x7fffade7b1d0) and /Users/poupou/Downloads/loader/loader/bin/Debug/loader.app/Contents/MonoBundle/../MacOS/loader (0x1044a0220). One of the two will be used. Which one is undefined.
objc[14641]: Class DOMNodeFilter is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy (0x7fffaf256788) and /Users/poupou/Downloads/loader/loader/bin/Debug/loader.app/Contents/MonoBundle/../MacOS/loader (0x1044a0db0). One of the two will be used. Which one is undefined.
objc[14641]: Class WebOpenPanelResultListener is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy (0x7fffaf25a4c8) and /Users/poupou/Downloads/loader/loader/bin/Debug/loader.app/Contents/MonoBundle/../MacOS/loader (0x1044a0ef0). One of the two will be used. Which one is undefined.
objc[14641]: Class WebPolicyDecisionListener is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy (0x7fffaf25a838) and /Users/poupou/Downloads/loader/loader/bin/Debug/loader.app/Contents/MonoBundle/../MacOS/loader (0x1044a0f40). One of the two will be used. Which one is undefined.
NSApplication.Shared is: <NSApplication: 0x7f9b2166b2f0>
NSApplication pointer:: 140736095584368
sharedApplication pointer: 140734557917698
Calling NSApplication.sharedApplication manully, IntPtr result: 140304257037040
NSApplication
Calling Runtime.GetNSObject out of the returned IntPtr=<NSApplication: 0x7f9b2166b2f0>
```

which makes me think it can be some initialization, e.g. making sure you load `AppKit` ...

Also in the attached sample you're not calling (directly) `TryGetNSObject`, instead you call `GetNSObject` - but you should be calling `GetNSObject<NSApplication>`, the later will force the type (instead of guessing it) since sometime the internal type used by Apple is not the documented one.

**Comment by chamons** [comment]
So my initial guess is that one or more parts of the init code we call in startup:

https://github.com/xamarin/xamarin-macios/blob/master/runtime/launcher.m

is needed, but I'll do some digging to see what.

**Comment by chamons** [comment]
Hmmm, when I copy everything into the bin folder I get things mostly working, well until Cocoa throws a fit about no info.plist
```
$ ls
loader.app loader.exe loader.pdb
$ cp /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/4.5/Xamarin.Mac.dll .
donblas:~/Downloads/loader/loader/bin/Debug $ cp /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/libxammac.dylib .
$ mono loader.exe 
NSApplication.Shared is: 
NSApplication pointer:: 140736148533968
sharedApplication pointer: 140734612427007
Calling NSApplication.sharedApplication manully, IntPtr result: 140304458326384
NSApplication
Calling Runtime.GetNSObject out of the returned IntPtr=<NSApplication: 0x7f9b2d662170>
2018-02-21 09:26:51.474 mono[87474:3234739] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting
```

**Comment by chamons** [comment]
Ok, this works:

https://gist.github.com/chamons/c6c3e8273dd93af3f5b5a741aa5ffb81#file-gistfile1-txt-L17

With the important bit being:

	var appkit = ObjCRuntime.Dlfcn.dlopen ("/System/Library/Frameworks/AppKit.framework/AppKit", 0);

Which we normally do here: https://github.com/xamarin/xamarin-macios/blob/master/src/Foundation/NSObject.mac.cs#L46

I am uncertain why we aren't hitting this in your use case, but it isn't one that we test. I can do more digging if desired, but that gist works with a menu / window for me.

**Comment by chamons** [comment]
@alanmcgovern Explained to me why this is the case - A static ctor in NSApplication will cache null if it isn't preloaded.

Seems like this is wrapped up, please reopen if not the case.

**Comment by spouliot** [comment]
> which makes me think it can be some initialization, e.g. making sure you load AppKit ...

😸

**Comment by chamons** [comment]
As usual, your initial guess was correct @spouliot  :)
