### ISSUE TITLE
[MMP] Add recursive ignore directories

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#3568]
Static registrar implementation for VSM added support for recursive search directories for probing for assemblies.

Implement a recursive ignore directories to ignore scanning some directories in the app bundle we have.

This would prevent possible issues such as 2 dlls referencing xammac being out of sync between the bundled Xamarin Inspector app bundle and the main VSM bundle

**Comment by spouliot** [comment]
@Therzok @chamons I think this was solved differently right ?

**Comment by chamons** [comment]
Yes. I believe this was handled.
