### ISSUE TITLE
ACTool is rerun with no source code changes

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#3584]
### Steps to Reproduce

1. Create a Xamarin.Mac project.
2. Add some image assets.
3. Build
4. Build again

### Expected Behavior

The ACTool is executed during first build (step 3), but it is skipped on a rebuild with no changes (step 4).

### Actual Behavior

ACTool is run whether input files have changed or not. This may significantly affect build times during a usual debugging cycles.

### Environment

Visual Studio Professional 2017 for Mac (Preview)
Version 7.4 Preview (7.4 build 985)
Runtime: Mono 5.8.0.123 (2017-10/38502063cac) (64-bit)
Xamarin.Mac Version: 4.2.0.19 (Visual Studio Professional)

### Rationale

There are several tasks that are executed both for libraries and executables that are unnecessarily run over and over again. This is especially annoying when debugging a project in Visual Studio and constantly rebuilding it.

Being no MSBuild expect I think something like this could work as a solution:

```
	<Target Name="_CoreCompileImageAssets" Inputs="@(ImageAsset);$(_AppManifest)" Outputs="$(IntermediateOutputPath)actool/actool.cache">
		<ACTool
			... />
		</ACTool>
		<Touch
			AlwaysCreate="true"
			Files="$(IntermediateOutputPath)actool.cache" />
	</Target>
```

Adding the Inputs and a dummy actool.cache file results in MSBuild checking the timestamps of the Inputs and skipping the build if nothing has changed.

**Comment by dalexsoto** [comment]
We acknowledge this enhancement request 👍, therefore marked it as such. However, this does not necessarily mean we will take actions on it as we still need to discuss its feasibility internally and make sure it is not conflicting with other features.

**Comment by filipnavara** [comment]
Perfectly understood. I was profiling my builds for the last couple of days and this easily added 2 seconds for each project with icon assets. It may not seem like much, but it adds up. If I get annoyed enough I am prepared to take action myself and submit patches.

**Comment by dalexsoto** [comment]
Oh interesting numbers, thanks for sharing! also all contributions are very welcome! :D

**Comment by chamons** [comment]
I can confirm this, and there appears to be logic in the iOS build targets to prevent this unpleasant build behavior that was never ported to Xamarin.Mac.

**Comment by chamons** [comment]
I'm going to close this as it is fixed in master. We are considering adding to d15-9, and I will cherry pick it to d16-0.
