### ISSUE TITLE
Create tests for all platforms which exercise Reference/include hintpaths and PackageReference nugets

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3588]
Multiple times in the past Xamarin.Mac has seen brokenness related to difference between the two styles of include nuget references:

    <Reference Include="Xamarin.Forms.Core">
      <HintPath>..\..\packages\Xamarin.Forms.2.5.0.121934\lib\Xamarin.iOS10\Xamarin.Forms.Core.dll</HintPath>
    </Reference>

and

    <ItemGroup>
        <PackageReference Include="Xamarin.Forms" Version="2.5.0.121934" />
    </ItemGroup>

We should write tests that pick a nuget, reference it both ways, restore/build/run.

It could be manual but automated would be preferable and doable.

**Comment by rolfbjarne** [comment]
In .NET the last variation is pretty much the only one used, so this isn't that much of a problem anymore.
