### ISSUE TITLE
I am getting this error when I am deploying iPhone app into iPhone device

### ISSUE THREAD

**Issue by nitud** [xamarin/xamarin-macios#3592]
### Steps to Reproduce

1. Simple run the app 
2. 
3. 

### Expected Behavior
Should deploy successfully 
### Actual Behavior
Giving error
AppTest/iOS/MTOUCH: Error MT4109: Failed to compile the generated registrar code. Please file a bug report at http://bugzilla.xamarin.com (MT4109) (AppTest.iOS)
### Environment

```
```

**Comment by dalexsoto** [comment]
Hello @nitud 

Please include your full build logs, test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by VincentDondain** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
