### ISSUE TITLE
Where to download Xamarin tools for Visual studio 2015

### ISSUE THREAD

**Issue by SaravananWipro** [xamarin/xamarin-macios#3604]
### Steps to Reproduce
Please share download path for Xamarin tools for Visual Studio 2015 and Xamarin.iOS for Mac.

I am getting release notes from below path but there is no downloadable link.
https://developer.xamarin.com/releases/current/

### Expected Behavior
Need downloadable link

### Actual Behavior
No downloadable link

### Environment

```
```

**Comment by therealjohn** [comment]
@SaravananWipro 

Here is a link to adding Xamarin tools to VS 2015: https://developer.xamarin.com/guides/cross-platform/getting_started/installation/windows/#vs2015

**Comment by SaravananWipro** [comment]
I want download and install in offline, earlier i had option to download as below image from url

https://store.xamarin.com/account/my/subscription/downloads


![capture](https://user-images.githubusercontent.com/35057816/36773425-988c652c-1c7f-11e8-8121-ecd2f820cf28.JPG)
