### ISSUE TITLE
Cannot use nuget package referenced in a .NET standard project

### ISSUE THREAD

**Issue by VictorBriant** [xamarin/xamarin-macios#3646]
### Expected Behavior
We should be able to use a nuget package added to a .NET standard project if our main project has a reference to it
 
### Actual Behavior
There is a linker issue when a .NET standard project reference a nuget package (in our sample Newtonsoft.JSON). Our main project, referencing this .NET standard project, is not able to use the Newtonsoft.JSON package. If we do not use the linker, the reference is working.

### Environment

```
Visual Studio Professional 2017 for Mac
Version 7.3.3 (build 23)
Installation UUID: e095ffc9-e921-45ce-a43a-f3271d43b21d
Runtime:
    Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
    GTK+ 2.24.23 (Raleigh theme)

    Package version: 504010007

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
    2.0.5
    2.0.0
    1.1.1
    1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
    2.1.4
    2.0.0
    1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Xamarin.Android
Version: 8.1.5.0 (Visual Studio Professional)
Android SDK: /Users/pscraire/Library/Developer/Xamarin/android-sdk-macosx
    Supported Android versions:
        6.0 (API level 23)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.iOS
Version: 11.6.1.4 (Visual Studio Professional)
Hash: db807ec9
Branch: xcode9.2
Build date: 2018-01-10 16:45:48-0500

Xamarin.Mac
Version: 4.0.0.216 (Visual Studio Professional)

Build Information
Release ID: 703030023
Git revision: e02ab111d8181ffe766c2258141282c88188ebb6
Build date: 2018-02-20 08:06:38-05
Xamarin addins: 5ce2b6790676a4542aa0d69d07f6a716e17d4e65
Build lane: monodevelop-lion-d15-5

Operating System
Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

Enabled user installed addins
NuGet Package Management Extensions 0.12.4
Internet of Things (IoT) development (Preview) 7.1
```

### Example Project (If Possible)

[StandardTesting.zip](https://github.com/xamarin/xamarin-macios/files/1775556/StandardTesting.zip)

**Comment by mandel-macaque** [comment]
I am confirming the bug but I am not sure if this is the right project to fill it @jstedfast 

I have modified the project to use the class created in the Standard project to make sure we have a crash, for example, doing so you will get the following exception at runtime:

```
2018-03-05 18:04:58.765 StandardTesting[11693:22403641] Could not find `Newtonsoft.Json` referenced by assembly `Standard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`.
2018-03-05 18:04:58.851 StandardTesting[11693:22403641] 
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'Standard.Class1:a' (0) due to: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. assembly:Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed type:<unknown type> member:<none>
2018-03-05 18:04:58.852 StandardTesting[11693:22403641] Unhandled managed exception:
Could not load type of field 'Standard.Class1:a' (0) due to: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. assembly:Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed type:<unknown type> member:<none> (System.TypeLoadException)
(null)
2018-03-05 18:04:58.852 StandardTesting[11693:22403641] critical: Stacktrace:

2018-03-05 18:04:58.853 StandardTesting[11693:22403641] critical: 
Native stacktrace:

2018-03-05 18:04:58.862 StandardTesting[11693:22403641] critical: 	0   StandardTesting                     0x000000010ca4d2e4 mono_handle_native_crash + 244
2018-03-05 18:04:58.863 StandardTesting[11693:22403641] critical: 	1   libsystem_platform.dylib            0x000000011baaef5a _sigtramp + 26
2018-03-05 18:04:58.863 StandardTesting[11693:22403641] critical: 	2   libsystem_kernel.dylib              0x000000011b99d480 libsystem_kernel.dylib + 1152
2018-03-05 18:04:58.863 StandardTesting[11693:22403641] critical: 	3   libsystem_c.dylib                   0x000000011b6730eb abort + 127
2018-03-05 18:04:58.864 StandardTesting[11693:22403641] critical: 	4   StandardTesting                     0x000000010cc1e3cf xamarin_unhandled_exception_handler + 47
2018-03-05 18:04:58.864 StandardTesting[11693:22403641] critical: 	5   StandardTesting                     0x000000010caba2f4 mono_invoke_unhandled_exception_hook + 148
2018-03-05 18:04:58.864 StandardTesting[11693:22403641] critical: 	6   StandardTesting                     0x000000010c9c126f mono_jit_exec + 335
2018-03-05 18:04:58.864 StandardTesting[11693:22403641] critical: 	7   StandardTesting                     0x000000010cc2e021 xamarin_main + 2705
2018-03-05 18:04:58.864 StandardTesting[11693:22403641] critical: 	8   StandardTesting                     0x000000010cc309fd main + 45
2018-03-05 18:04:58.864 StandardTesting[11693:22403641] critical: 	9   libdyld.dylib                       0x000000011b5a0d81 start + 1
2018-03-05 18:04:58.865 StandardTesting[11693:22403641] critical: 
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

```

**Comment by lineker** [comment]
Yeah, I also have this issue. Is frustrating since it works on simulator but doesn't work when running on a real device. Can anyone help ?

**Comment by mandel-macaque** [comment]
@lineker we go through bugs every week and try to address them ASAP. As soon as we do some progress with this one, we will get back you here. We try to be as fast as possible, but sometimes, things happen that make us take a little longer, sorry :(

**Comment by renzska** [comment]
I'm still experiencing this issue in relation to a multi-platform Xamarin application inside of a watchkitextension. Is there an ETA on this?


```
2018-05-29 10:30:07.750 TinyBible.iOS.WatchExtension[9893:715854] Could not find `Newtonsoft.Json` referenced by assembly `TestApp.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`.
2018-05-29 10:30:08.066 TestApp.iOS.WatchExtension[9893:715854] *** Terminating app due to uncaught exception 'System.BadImageFormatException', reason: 'Could not resolve field token 0x0400002f, due to: Could not load type of field 'TestApp.Core.JsonConverterSettings:Settings' (0) due to: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. assembly:Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed type:<unknown type> member:(null) signature:<none> assembly:/Users/user/Library/Developer/CoreSimulator/Devices/9EF37160-D8BE-450C-B129-A65B544E94D6/data/Containers/Bundle/Application/6A3ABF04-DEC6-4159-8D02-ECDE1F141D12/TestApp.iOS.Watch.app/PlugIns/TestApp.iOS.WatchExtension.appex/TestApp.Core.dll type:JsonConverterSettings member:(null) signature:<none>'
```

Thanks,

John

**Comment by mandel-macaque** [comment]
@lineker  @renzska I have tested the provided project with the following [environment](https://gist.github.com/mandel-macaque/aa5b5d4605824cb0b83e8f2d6135a7c3) and it cannot longer reproduce it. I'll close the bug. Please feel free to reopen it if you do experience it with the env I have provided.

**Comment by VictorBriant** [comment]
@mandel-macaque Thanks for your answer indeed we are not able to reproduce the bug using "Release | iPhone" mode. However, now the issue seems to appear using "Debug | iPhone" mode. There still seems to be an issue with the linker. Please find attach the full verbose logs of the sample project built using "Debug | iPhone" mode with following environment : 
`Visual Studio Community 2017 for Mac
Version 7.6.3 (build 1)
Installation UUID: 4321eee9-e7d7-4b07-b1c1-7182ec9ebd8f
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac
Version: 4.6.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

Xamarin.iOS
Version: 11.14.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: HEAD
Build date: 2018-08-28 00:12:06-0400

Xamarin.Android
Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/buildmac/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		7.1   (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 706030001
Git revision: 18a828b090fb6d2cfb0b3576cd6d7eb764f29753
Build date: 2018-08-30 15:12:59+00
Build branch: release-7.6
Xamarin extensions: f4aee57d7b72fa4be6b6d585ac90d614f20fa426

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
NuGet Package Management Extensions 0.12.6
Internet of Things (IoT) development (Preview) 7.5
`

[VerboseLogNetStandard.txt](https://github.com/xamarin/xamarin-macios/files/2357226/VerboseLogNetStandard.txt)

**Comment by lineker** [comment]
Any news on this?

**Comment by rolfbjarne** [comment]
@lineker please update to the latest stable release, since this is probably a duplicate of #4237 (which is fixed there).

If that doesn't work, try this: https://github.com/xamarin/xamarin-macios/issues/3949#issuecomment-420306411

**Comment by VictorBriant** [comment]
Hello @rolfbjarne, 
I tested with latest stable release (see environment below), I am still not able to build the solution in Debug | iPhone. I am getting the same error as my previous post even after executing steps in your #3949 link :
Error MT2001: Could not link assemblies. Reason: Error while processing references of 'StandardTesting, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' (MT2001) (StandardTesting)

`
Visual Studio Community 2017 for Mac
Version 7.6.8 (build 38)
Installation UUID: 4321eee9-e7d7-4b07-b1c1-7182ec9ebd8f
Runtime:
Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)
Package version: 512000309

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac
Version: 5.0.0.0 (Visual Studio Community)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

Xamarin.iOS
Version: 12.0.0.15 (Visual Studio Community)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

Xamarin.Android
Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/buildmac/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		7.1   (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 706080038
Git revision: f4178f550a4de7c03aa23678041abe4fc388cf72
Build date: 2018-09-28 14:21:41+00
Build branch: release-7.6
Xamarin extensions: 051b653186a95ced1c127dfd8c358df1b9315d0d

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
NuGet Package Management Extensions 0.12.6
`

**Comment by rolfbjarne** [comment]
@VictorBriant the workaround from https://github.com/xamarin/xamarin-macios/issues/3949#issuecomment-420306411 worked for me.

This is the diff for StandardTesting.csproj:

```diff
diff --git a/StandardTesting/StandardTesting.csproj b/StandardTesting/StandardTesting.csproj
index 51821b4..04ccf11 100644
--- a/StandardTesting/StandardTesting.csproj
+++ b/StandardTesting/StandardTesting.csproj
@@ -9,6 +9,7 @@
     <RootNamespace>StandardTesting</RootNamespace>
     <AssemblyName>StandardTesting</AssemblyName>
     <IPhoneResourcePrefix>Resources</IPhoneResourcePrefix>
+    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>^M
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
     <DebugSymbols>true</DebugSymbols>
```

How does your StandardTesting.csproj look like after applying the fix?

**Comment by VictorBriant** [comment]
@rolfbjarne Indeed it is working, I had to reload the solution to trigger the package restoring process after adding the line in csproj ... Silly me !
