### ISSUE TITLE
Hardcoded links telling you to file a bug report on Bugzilla

### ISSUE THREAD

**Issue by akoeplinger** [xamarin/xamarin-macios#3647]
### Steps to Reproduce

1. Search for bugzilla.xamarin.com in the source, e.g. with https://github.com/xamarin/xamarin-macios/search?utf8=%E2%9C%93&q=%22file+a+bug%22+bugzilla.xamarin.com&type=Code
2. There are a lot of places telling you to file a bug on Bugzilla, those should be updated to GitHub

### Expected Behavior

GitHub instructions instead of Bugzilla

### Actual Behavior

There are bugzilla links

**Comment by VincentDondain** [comment]
Closing since https://github.com/xamarin/xamarin-macios/pull/4920 was merged into master.
