### ISSUE TITLE
Run simulator tests in older simulators

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#3668]
We should run simulator tests in older simulators, probably the oldest the current version of Xcode supports (currently iOS 8.1, tvOS 9.0 and watchOS 2.0).

This will help catch missing availability attributes, missing version checks in tests, and probably a lot of other issues as well.

It's probably enough to do it for the monotouch-test and introspection tests.

**Comment by VincentDondain** [comment]
@rolfbjarne +1 on this. Did you take inspiration somewhere? :P

https://trello.com/c/1x2pGClP/710-xcode-9-post-mortem#comment-59a5d86e913dddd334b14be4 (oldest comment)

**Comment by rolfbjarne** [comment]
@VincentDondain hehe, I've had it in mind for quite a while, and decided to just document it :smile: I didn't remember seeing it before, but that might very we'll be the inspiration 😄

**Comment by rolfbjarne** [comment]
Martin asked us to run mscorlib and System tests on the earliest iOS version we can as well: 
https://github.com/xamarin/xamarin-macios/pull/4914#issuecomment-429969978

**Comment by rolfbjarne** [comment]
We're doing this, and we have for quite a while already.
