### ISSUE TITLE
[XI]mtouch and mlaunch gives two different versions

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3705]
### Steps to Reproduce

1. Install XI 11.10.0.32 
2. Run /Developer/MonoTouch/usr/bin/mtouch --version and /Developer/MonoTouch/usr/bin/mlaunch --version

### Expected Behavior
Both commands should display the same versions

### Actual Behavior
d15-7:
mtouch: mtouch 11.10.0.32 (d15-7: 4d8c4e32)
mlaunch: Xamarin.Launcher 11.10.0.32 (origin/d15-7: e0a3082)

d15-6:
mtouch 11.8.0.20 (d15-6: 1c6f300e)
Xamarin.Launcher 11.8.0.20 (origin/d15-6: 6affe8d)

I used mtouch in command line testing and recently changed to use mlaunch and noticed the difference. Is this expected?

### Environment
=== Visual Studio Community 2017 for Mac ===

Version 7.4 (build 1033)
Installation UUID: 4b1b3a37-7632-4b67-ab0a-8c2edb0498a3
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.0.20 (Visual Studio Community)

=== Xamarin.Android ===

Not Installed

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 11.8.0.20 (Visual Studio Community)
Hash: 1c6f300e
Branch: d15-6
Build date: 2018-02-07 23:42:40-0500

=== Build Information ===

Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

**Comment by rolfbjarne** [comment]
Yes, this is expected, the mlaunch hash is a hash from the xamarin/maciostools repository.
