### ISSUE TITLE
new ARFaceGeometry(ARBlendShapeLocationOptions) throws on construction

### ISSUE THREAD

**Issue by lobrien** [xamarin/xamarin-macios#3714]
### Steps to Reproduce

(Run attached workbook or...)
[Cannot_Create_ARFaceGeometry.workbook.zip](https://github.com/xamarin/xamarin-macios/files/1798000/Cannot_Create_ARFaceGeometry.workbook.zip)

1. Create a new iOS 11 solution
2. using ARKit;
3. in ViewWillLoad() or similar:

    var expression = new ARBlendShapeLocationOptions();
    var faceForBlending = new ARFaceGeometry(expression);

### Expected Behavior

An `ARFaceGeometry` initialized with default expression (0 values on expression variables). 

### Actual Behavior

Exception: Could not initialize an instance of the type 'ARKit.ARFaceGeometry': the native 'initWithBlendShapes:' method returned nil.
It is possible to ignore this condition by setting MonoTouch.ObjCRuntime.Class.ThrowOnInitFailure to false.
at void Foundation.NSObject.InitializeHandle (IntPtr handle, string initSelector)
at ARKit.ARFaceGeometry..ctor (NSDictionary blendShapes)
at ARKit.ARFaceGeometry..ctor (ARBlendShapeLocationOptions blendShapes)
at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw ()
at void System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (Task task)
at void System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task task)
at void System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (Task task)
at object System.Runtime.CompilerServices.TaskAwaiter<object>.GetResult ()
at void Xamarin.Interactive.CodeAnalysis.EvaluationContext.<RunAsync>d__26.MoveNext ()

### Environment
```
=== Visual Studio Community 2017 for Mac ===

Version 7.4 (build 1033)
Installation UUID: 6b94f136-026d-4a5a-bf6d-af2c0d8dc019
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14126.4)
Build 9Q117m

=== Xamarin.Mac ===

Version: 4.2.0.20 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.0.8 (Visual Studio Community)
Hash: 8ba51035
Branch: xcode9.3
Build date: 2018-03-08 00:56:09-0500

=== Xamarin.Android ===

Version: 8.2.0.15 (Visual Studio Community)
Android SDK: /Users/larryobrien/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 25.0.3
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

AddinMaker 1.4.2
Larry's F# Templates 2.0.8
MicroFramework 1.0.3
Internet of Things (IoT) development (Preview) 7.1


```

**Comment by lobrien** [comment]
This behavior seems to be the same under Swift (see attached screenshot, which shows `nil`). 
<img width="945" alt="screenshot 2018-03-09 08 51 06" src="https://user-images.githubusercontent.com/181571/37224286-18cc00f0-2377-11e8-89c3-7ce82e833be7.png">

**Comment by spouliot** [comment]
Yes, that's by design. A call to a .net `.ctor` cannot return `null`, like a call to `init*` can in ObjC (because it's a method). The only way not to create an invalid managed instance (which would fail later and be much harder to diagnose) is to throw an exception in such case.

It's not really different than creating other instances from the BCL with invalid/incomplete arguments. The main difference is that we cannot be sure if the input is fine (from managed code) since it's a behaviour that can vary across iOS versions. The only check we can safely do is against a `nil` value.

**Comment by lobrien** [comment]
Turns out this is "as documented": Apple's docs for the `init` read: "A face geometry object, or nil if ARKit face tracking is not supported on the current device."
