### ISSUE TITLE
GameplayKit.GKNoise.DisplaceX should be named Displace or DisplaceWithNoises

### ISSUE THREAD

**Issue by lobrien** [xamarin/xamarin-macios#3716]
The function `GameplayKit.GKNoise.DisplaceX` binds `displaceXWithNoise:yWithNoise:zWithNoise:` The name `DisplaceX` incorrectly suggests that displacement can only be done along one axis.

**Comment by dalexsoto** [comment]
Thank you @lobrien! This is getting fixed by PR #3780 👍
