### ISSUE TITLE
Xamarin.Mac MSBuild doesn't implement the build action "CoreMLModel"

### ISSUE THREAD

**Issue by b-straub** [xamarin/xamarin-macios#3719]
### Steps to Reproduce

1. Create a Xamarin.Mac application
2. Add a CoreML model e.g. Google Places 365
3. Use the model e.g. with Vision framework

### Expected Behavior

The application will compile the CoreML model to the compressed representation

### Actual Behavior

The application doesn't compile the CoreML model to the compressed representation, whereas
iOS do, _build action CoreMLModel_ is not implemented for Xamarin.Mac MSBuild

### Environment

```
var url = NSBundle.MainBundle.GetUrlForResource ("googlenet_places365", "mlmodelc");
```

### Run Log

_System.ArgumentNullException
Value cannot be null.
Parameter name: url_

###  Fix

Implement _build action CoreMLModel_ for Xamarin.Mac MSBuild similar to iOS
[xamarin-macios/msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets](url)

**Comment by VincentDondain** [comment]
I can confirm this issue. Support for CoreML with Xamarin.Mac isn't fully done.

Here's a simple test case to reproduce the issue: https://www.dropbox.com/s/9mr3idtw8ie447b/TestCase3719.zip?dl=0

This is a simple XM app created from scratch which has the `MarsHabitatPricer.mlmodel` in its Resources and is using it in the `ViewController.cs`.

```
// Load the ML model
var assetPath = NSBundle.MainBundle.GetUrlForResource ("MarsHabitatPricer", "mlmodelc");
var model = MLModel.Create (assetPath, out NSError mlErr);

var pricerInput = new MarsHabitatPricerInput (2, 5, 10000);

// Use the ML model
var outFeatures = model.GetPrediction (pricerInput, out NSError prErr);
var result = outFeatures.GetFeatureValue ("price").DoubleValue;
Console.WriteLine (prErr == null ? $"Result was {result}" : "Unexpected runtime error " + prErr.Description);
```

The model isn't compiled and embedded into the app, like it is on iOS. Therefore we're getting the same issue reported here with `NSBundle.MainBundle.GetUrlForResource ()`.

**Comment by joaomelo81** [comment]
Any updates on this issue?

**Comment by rolfbjarne** [comment]
This has been implemented for .NET.
