### ISSUE TITLE
Xamarin.Mac New Project does not link on 10.11.6 without Linking enabled

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3725]
### Steps to Reproduce

1. 10.11.6 
2. New XM Project
3. Build

### Expected Behavior

Build Successful

### Actual Behavior

Build Failed

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.4 (build 1033)
Installation UUID: e364076d-676a-4bc8-aefd-8a5e93626e31
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: Not installed
SDK: Not installed
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 8.2.1 (11766.1)
Build 8C1002

=== Xamarin.Mac ===

Version: 4.2.0.20 (Visual Studio Community)

=== Xamarin.iOS ===

Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

=== Xamarin.Android ===

Not Installed

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.11.6
Darwin 15.6.0 Darwin Kernel Version 15.6.0
    Thu Jun 23 18:25:34 PDT 2016
    root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64


```

### Build Logs

https://gist.github.com/chamons/6c534a13e9c882084ecc1696c5295340

**Comment by chamons** [comment]
Diag log: https://gist.github.com/chamons/65b84cdcc898417e7fb4bbd4e9eeb701

**Comment by spouliot** [comment]
```
 ld: framework not found MetalPerformanceShaders
```

The framework did not exists in macOS 10.11. It's the same type of issue people have using old Xcode with XI - and for which we suggest enabling the linker.

In this case we might be able to detect the (native link time) error and provide a better description on the workarounds, i.e. either

* **best** update Xcode to the latest (which might require updating the macOS version); or
* **alternative** enable the linker for platform (minimally) to see if the new types can be removed.

**Comment by chamons** [comment]
So I see the reason we're hitting this:

We have code here:

https://github.com/xamarin/xamarin-macios/blob/master/tools/common/Assembly.cs#L418

that does the right thing and only add the reference if the version check is solid

And 3 more copies of it, including one here:

https://github.com/xamarin/xamarin-macios/blob/master/tools/common/Assembly.cs#L385

that does not honor the version check. In this case, because of a ```App.IsSimulatorBuild``` check that doesn't even exist on macOS.

I believe the correct fix is to turn those 4 into a function, always doing the check, and called by all 4 locations. Testing and PR to come

**Comment by chamons** [comment]
@spouliot See https://github.com/xamarin/xamarin-macios/pull/3757 . We had logic to handle this correctly, but a handful of frameworks were special cased into another code path that did not have it (due to an XI check that wasn't even there for XM).

**Comment by chamons** [comment]
Fixed in master. @spouliot thoughts on 15.7 cherry pick?
