### ISSUE TITLE
HttpClient implementation warning appears when it is not needed

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/xamarin-macios#3740]
From: https://developercommunity.visualstudio.com/content/problem/213524/httpclient-implementation-warning-appears-when-it.html

### Steps to Reproduce

This message appears after the project is built:

Warning XIA0006: We recommend using the native HttpClient handler instead of the managed one for better performance, smaller executable size, and to easily support the newer standards. Double click on your iOS project, go to Build > iOS Build and change the HttpClient implementation to either NSUrlSession (iOS 7+) or CFNetwork to support version preceding iOS 7. (XIA0006)

but the project is already using the NSUrlSession option. Please see the attached screenshots.

![24686-httpclient-setting](https://user-images.githubusercontent.com/204671/37375191-2a9a49fc-26e4-11e8-9e84-091f8d4f888d.png)

![24685-httpclient-warning](https://user-images.githubusercontent.com/204671/37375199-2f181fae-26e4-11e8-9c3b-76b90f4db376.png)

### Expected Behavior
No Warning XIA0006

### Actual Behavior
Warning XIA0006

**Comment by dalexsoto** [comment]
Hello Gary and welcome to our repo!

Please include your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by GEMeyers** [comment]
=== Visual Studio Community 2017 for Mac ===

Version 7.4 (build 1033)
Installation UUID: 00dd6525-c275-4bbe-bae5-1756e6eff981
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.0.20 (Visual Studio Community)

=== Xamarin.Android ===

Version: 8.2.0.15 (Visual Studio Community)
Android SDK: Not found

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 11.8.0.20 (Visual Studio Community)
Hash: 1c6f300e
Branch: d15-6
Build date: 2018-02-07 23:42:40-0500

=== Build Information ===

Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jan 11 22:59:40 PST 2018
    root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

**Comment by dalexsoto** [comment]
Hello @GEMeyers and welcome!! ❤️ 

Thanks for providing the information, unfortunately I am not able to replicate this issue, could you check if this happens in a new solution for you? Is is possible that another of your projects (if any) is causing this?

@VincentDondain do you have any other suggestions?

**Comment by VincentDondain** [comment]
What might happen is that the warning is raised for a configuration different that the Debug|iPhone one shown in the screenshot. The rule are executed against the currently selected configuration. So if you run the rules against let's say Release|iPhone and check the project options for Debug|iPhone it's wrong, you'd have to make sure the project options for the currently selected configuration are right.

Also the analysis rules are being run when clicking Project > Run Code Analysis. It shouldn't happen when building, that would be a bug, can you please confirm that you hit "run code analysis"?

**Comment by GEMeyers** [comment]
I found that the warning message was being shown because the Release build was not set to use this HttpClient option.  I saw this warning message when I was making a Debug build and I have never run Code Analysis on this project.  Now that I've also updated the Release build project options, I don't see the message when making a Debug build.

**Comment by VincentDondain** [comment]
@mandel-macaque you said you could confirm this, can you give me some repro steps? I definitely do now have a warning when making a simple build. It's hard to fix if I can't reproduce it (:

**Comment by dalexsoto** [comment]
@mandel-macaque any update on this?

**Comment by mandel-macaque** [comment]
Let me retry and I will provide the exact steps I  used to reproduce it.

**Comment by mandel-macaque** [comment]
@VincentDondain @dalexsoto I have reviewed the issue with the following [version](https://gist.github.com/mandel-macaque/4ddd39b94962d6480d01bfbefbdfecc9) (from the stable channel) and the issues does not longer occur. @GEMeyers The warning will appear if you have the managed http client selected, but will not in any of the other cases.
