### ISSUE TITLE
_CodesignNativeLibraries No longer getting called in Xamarin iOS 11.8

### ISSUE THREAD

**Issue by borrrden** [xamarin/xamarin-macios#3741]
**NOTE** This is only an issue with 11.8, not 11.6 nor 11.10.  I am just reporting it in case it is going unnoticed.

### Steps to Reproduce

Somewhat unclear

1. Create a project that references a nuget package that has a bundle resource of type dylib inside
2. Build the project via msbuild and observe build output
3. Notice that 11.6 has a section indicating the _CodesignNativeLibraries target was run, while 11.8 does not (and indeed the dylib is unmodified)

### Expected Behavior

The dylib will be code signed, and available for dylib

### Actual Behavior

The dylib is plain and cannot be loaded at runtime

### Environment

Ignore the iOS 11.10, it is just left that way after I did some troubleshooting (the affected version is the released 11.8 which just came out via VS 15.6)

```
Visual Studio Enterprise 2017 for Mac
Version 7.4 (build 1033)
Installation UUID: 9c860ff0-60f7-49fa-9bc5-91a16d0b99b1
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.4
	1.0.7
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 11.10.0.15 (Visual Studio Enterprise)
Hash: 0181ac3d
Branch: d15-7
Build date: 2018-02-28 15:16:10-0500

Xamarin.Android
Version: 8.2.0.15 (Visual Studio Enterprise)
Android SDK: /Users/borrrden/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

Operating System
Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.1

```

### Build Logs

[11.6 build](https://github.com/xamarin/xamarin-macios/files/1809882/output11_6.txt)
[11.8 build](https://github.com/xamarin/xamarin-macios/files/1809883/output11_8.txt)

### Example Project (If Possible)

I am not allowed to distribute the project that I got to show this because it is not mine.  If needed, I will ping the original author to see if they can share it here too.

**Comment by dalexsoto** [comment]
Hello @borrrden 

I think this issue was recently addressed, you can find our Xamarin.iOS 11.8 continuous builds here https://jenkins.mono-project.com/view/Xamarin.MaciOS/job/macios-mac-d15-6/

Please feel free to reopen this issue if the above build does not work for you.
