### ISSUE TITLE
Remove Descriptors/mscorlib.xml

### ISSUE THREAD

**Issue by marek-safar** [xamarin/xamarin-macios#3749]
Mono bundles correct and updated mscorlib descriptor inside every mscorlib. The macios copies should be removed to not confuse the linker.

**Comment by dalexsoto** [comment]
We are indeed loading both xml descriptors and adding them to the pipeline, look at 4 and 5:

<img width="820" alt="screen shot 2018-03-15 at 9 37 17 pm" src="https://user-images.githubusercontent.com/204671/37532570-fc5c86ae-2904-11e8-9345-6460f65bc60e.png">

That said they are not identical:

Description bundled in mtouch:

<img width="465" alt="mtouch pass" src="https://user-images.githubusercontent.com/204671/37532615-2098af34-2905-11e8-823f-d3f4d55800a8.png">

Description bundled in mscorlib:

<img width="470" alt="mscorlib pass" src="https://user-images.githubusercontent.com/204671/37532634-2b461f52-2905-11e8-9a82-8fed9c1fca2a.png">

I think we can remove our mscorlib.xml inside the mtouch/mmp bundle
