### ISSUE TITLE
Deploying to iOS via USB fails and causes soft reset 

### ISSUE THREAD

**Issue by yevgeniy-seleznev** [xamarin/xamarin-macios#3750]
### Steps to Reproduce

1. Attach a provisioned iOS device through USB and attempt to deploy your Xamarin.iOS app to it.
2. Observe error message in log and that the device hangs.
3. After a minute or two, observe a "Failed to launch" message and the device is soft resetting i.e. a black spinning cursor is seen for a while, after which the device returns to the lock screen.

### Expected Behavior

App is launched successfully with debugger attached.

### Actual Behavior

App is not launched, phone is reset.

One of our phones is now bricked as a result of having this happen several times. It no longer can launch any app, not even the iOS Settings app. Each time, it freezes and soft resets.

### Environment
Visual Studio Enterprise 2017 for Mac
Version 7.4 (build 1033)
Installation UUID: 6e029159-d9dc-4e46-a319-e3e299407d8c
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Xamarin.Android
Version: 8.2.0.15 (Visual Studio Enterprise)
Android SDK: /Users/yevgeniy/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 11.8.0.20 (Visual Studio Enterprise)
Hash: 1c6f300e
Branch: d15-6
Build date: 2018-02-07 23:42:40-0500

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:58:50 PST 2018
    root:xnu-4570.51.1~2/RELEASE_X86_64 x86_64

```
```

### Build Logs

			Details:  Failed to start Instruments daemon on device “96dc4562231e94b7a755951afde69c91470cafe4”: Error Domain=com.apple.dtdevicekit Code=-402653150 "An error was encountered while attempting to communicate with this device. (The service is invalid.)" UserInfo={NSLocalizedDescription=An error was encountered while attempting to communicate with this device. (The service is invalid.), com.apple.dtdevicekit.stacktrace=(
				0   DTDeviceKitBase                     0x000000010e811fed DTDKCreateNSError + 113
				1   DTDeviceKitBase                     0x000000010e812831 DTDK_AMDErrorToNSError + 1135
				2   DTDeviceKitBase                     0x000000010e823e8f __63-[DTDKRemoteDeviceConnection startFirstServiceOf:unlockKeybag:]_block_invoke + 300
				3   DTDeviceKitBase                     0x000000010e823521 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
				4   DTDeviceKitBase                     0x000000010e814815 __DTDKExecuteInSession_block_invoke_2 + 35
				5   DTDeviceKitBase                     0x000000010e813c1f __DTDKExecuteWithConnection_block_invoke_2 + 474
				6   DTDeviceKitBase                     0x000000010e813a1a __DTDKExecuteWithConnection_block_invoke + 111
				7   libdispatch.dylib                   0x00007fff6f1abe08 _dispatch_client_callout + 8
				8   libdispatch.dylib                   0x00007fff6f1c27dc _dispatch_sync_invoke_and_complete_recurse + 65
				9   libdispatch.dylib                   0x00007fff6f1c2275 _dispatch_sync_wait + 585
				10  DVTFoundation                       0x000000010d39a6f0 DVTDispatchBarrierSync + 213
				11  DVTFoundation                       0x000000010d373c7a -[DVTDispatchLock performLockedBlock:] + 75
				12  DTDeviceKitBase                     0x000000010e813915 DTDKExecuteWithConnection + 231
				13  DTDeviceKitBase                     0x000000010e814681 DTDKExecuteInSession + 381
				14  DTDeviceKitBase                     0x000000010e823458 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
				15  DVTFoundation                       0x000000010d399a4f __DVTDispatchAsync_block_invoke + 806
				16  libdispatch.dylib                   0x00007fff6f1b364a _dispatch_call_block_and_release + 12
				17  libdispatch.dylib                   0x00007fff6f1abe08 _dispatch_client_callout + 8
				18  libdispatch.dylib                   0x00007fff6f1c0267 _dispatch_queue_serial_drain + 635
				19  libdispatch.dylib                   0x00007fff6f1b31b6 _dispatch_queue_invoke + 373
				20  libdispatch.dylib                   0x00007fff6f1c0f5d _dispatch_root_queue_drain_deferred_wlh + 332
				21  libdispatch.dylib                   0x00007fff6f1c4d71 _dispatch_workloop_worker_thread + 880
				22  libsystem_pthread.dylib             0x00007fff6f4fcfd2 _pthread_wqthread + 980
				23  libsystem_pthread.dylib             0x00007fff6f4fcbe9 start_wqthread + 13
			), NSLocalizedRecoverySuggestion=Please try rebooting and reconnecting the device. (0xE8000022)., NSLocalizedFailureReason=Please try rebooting and reconnecting the device. (0xE8000022).}
			Object:   <DTDKRemoteDeviceConnection: 0x7fefda475d80>
			Method:   -instrumentsConnection
			Thread:   <NSThread: 0x7fefd9f76b70>{number = 11, name = (null)}
			Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
			warning MT1043: Failed to launch the application using the instruments service. Will try launching the app using gdb service.
			Launching 'com.microsoft.seeingai-dev' on the device 'meherk’s iPhone'
			warning HE0030: Could not mount developer tools on 'meherk’s iPhone': Could not locate device support files.
			warning HE0031: Failed to mount developer tools on 'meherk’s iPhone'.
			warning HE0030: Could not mount developer tools on 'meherk’s iPhone': Could not locate device support files.
			warning HE0031: Failed to mount developer tools on 'meherk’s iPhone'.
error MT1007: Failed to launch the application '/Users/yevgeniy/Documents/Source/SeeingAI-Mobile/iOS/App/bin/iPhone/Debug/device-builds/iphone7.1-11.3/SeeingAI.iOS.app' on the device 'meherk’s iPhone': Failed to launch the application 'com.microsoft.seeingai-dev' on the device 'meherk’s iPhone': Invalid Service Error (error: 0xe8000022). You can still launch the application manually by tapping on it.

**Comment by spouliot** [comment]
> Xcode 9.2 (13772)

Your Xcode is recent, what's the iOS version of the device(s) ?

> 		warning HE0030: Could not mount developer tools on 'meherk’s iPhone': Could not locate device support files.
>		warning HE0031: Failed to mount developer tools on 'meherk’s iPhone'.

The warnings should have very little effect. It's generally because your Xcode does not have the disk image that match your device, e.g. old Xcode and new iOS version, so there's some services we cannot use.

> error MT1007

The main effect is that we can't start an app from the Mac when it happens - so you have to tap to start them, which is what the error points out (warnings are too easily ignored).

As for your bricked phone can you connect it to the Mac and use Xcode to see what's the device logs are showing ? there might be clues to what's going on there. I've never bricked a device (came close one time due to an Apple bug) since I started developing XI itself - but I'd rather we take the time to make sure it's not the first time :)

c.c. @rolfbjarne

**Comment by yevgeniy-seleznev** [comment]
The 'meherk's iPhone' that generated the build log above is an iPhone 6+ running iOS 11.3 (15e5201e).

I have an iPhone 8 which is running 11.2.6 which also causes the same log messages.

When this log message which I've pasted is shown, you're right, I can usually manually launch the app and the debugger will attach.

However, on both of these devices I've experienced the crash / soft reset problem. I'll see if the log differs in any way, next time that this happens.

The bricked iPhone 7 was recently updated to the latest 11.3 beta. It experienced the soft reset problem when attaching debugger, and has since not been able to open any apps at all...does soft reset each time. It was then factory reset, so not it has 11.2.6 again, but it still bricked.

Grabbed the device logs off of it, and it seems like there's a kernel panic crash event repeating each time I try to open anything on it. I've attached the latest export of such an event. Let me know and I can export more events like this.

[KernelPanic.crash.zip](https://github.com/xamarin/xamarin-macios/files/1813540/KernelPanic.crash.zip)

Thanks a bunch for anything you can uncover!

**Comment by yevgeniy-seleznev** [comment]
Was able to reproduce the crash while attempting to attach debugger to my iPhone 8.
The device soft reset, spinning cursor then went back to lock screen.
Meanwhile the log had this.

warning MT1043: Failed to launch the application using the instruments service. Will try launching the app using gdb service.
Launching 'com.microsoft.seeingai-dev' on the device 'Yevgeniy’s iPhone'
error MT1007: Failed to launch the application '/Users/yevgeniy/Documents/Source/SeeingAI-Mobile/iOS/App/bin/iPhone/Debug/device-builds/iphone10.4-11.2.6/SeeingAI.iOS.app' on the device 'Yevgeniy’s iPhone': Send Message Error (error: 0xe800002d). You can still launch the application manually by tapping on it.

Although in this case I couldn't tap anything since the phone was soft resetting with spinning cursor.

**Comment by rolfbjarne** [comment]
For the bricked device, I think you'll have to take it to an Apple Store/Service and see what they can do. It may be that the device is broken somehow (which may or may not have something to do with the other problem).

For the soft reset when debugging: does this happen with any app, or just one? (can you try to create a new app from a template and see if that works?)

**Comment by yevgeniy-seleznev** [comment]
Thanks Rolf and Sebastien. Sorry for the sporadic details, as we're running out of devices to test with. 
We now have 3 devices that are in this bricked state and completely unusable. 

Harrison is trying to see if the problem reproes with a template VS app and/or XCode app, on our last remaining test device, which is a 6+. Harrison's personal iPhone 8 is among the ones which got bricked :(

One iPhone 7 which had 11.3 beta and was being deployed to from beta VS bits and XCode 9.3, for ARKit vertical planes. The last one was an iPhone 7 running 11.2.6, and was being deployed to by latest stable VS bits, and stable. XCode 9.2. The other device which got bricked is Harrison's personal iPhone 8.

**Comment by hwray** [comment]
Thanks for the help @rolfbjarne and @spouliot . I was able to deploy a new template single-view app, on a non-bricked phone, and it deployed correctly (although debugger did not attach). 

Note that the soft-reset occurs when trying to open any app on the bricked phones, not just when debugging. The logs from my personal device show some crashes with the error code 0xfaded321. Searching this error code comes up with some references to "watchdog timeout" and jailbroken devices (my device is not jailbroken).

I will try the steps you listed @spouliot, once I finish trying to restore my personal device.

**Comment by spouliot** [comment]
@yevgeniy-seleznev really sorry to hear about that :(

I'm not sure what the issue is, but the fact there's no other report makes me think you're hitting that's specific to your application (API or configuration). It's likely related to a bug in iOS [1] (maybe also in XI) but it's not something that happens generally. 

If you have not already then I suggest you open a priority ticket with Apple to get this sorted out. They are likely the only one that will be able to make sense of the logs.

[1] the iOS sandbox should not allow any individual app to crash others - that's an iOS bug if it happens

**Comment by ChrisColeTech** [comment]
I'm getting the same error. There is something wrong with the latest version of Xamarin and ios 11.2. 
It prevents debugging, it just says:

**Invalid Service Error (error: 0xe8000022). You can still launch the application manually by tapping on it.**

Chances are there wont be a solution until the next "stable" update. 

Workaround: use the simulator if possible

**Comment by rolfbjarne** [comment]
@ChrisColeTech can you try rebooting the device?

**Comment by ChrisColeTech** [comment]
@rolfbjarne Thanks for the reply.... yes I've tried rebooting the device, the PC, the Mac, I have restarted VS many times, I've downloaded Xcode 9.3 beta and pointed to that version instead of Xcode 9.2. I've tried debugging on VS 2015 and VS 2017 - (I get the same result). I've tried the BETA channel instead of "stable".  The only thing I have not tried is re-imaging the computer. It only started happening after I updated the device to iOS 11, and after I updated Xamarin.

It's probably one of those bugs that will "resolve itself" in the next update (wishful thinking, I know). I've been using Xamarin for almost 3yrs now, so I'm accustomed to these types of issues. I know Xamarin is a very unreliable piece of work.

**Comment by rolfbjarne** [comment]
@ChrisColeTech please open a new issue, it does not look like this is the same problem as what was reported here.

**Comment by ispysoftware** [comment]
yep got the same issue here, IOS 11.3

Severity	Code	Description	Project	File	Line	Suppression State
Error		error MT1007: Failed to launch the application 

 Invalid Service Error (error: 0xe8000022). You can still launch the application manually by tapping on it.		 	0

**Comment by ipon85** [comment]
I got this issue too on iphone 6 after update iOS to 11.3. otherwise, on ipad air which has iOS11.1 debug work well. 
Debug on Visual Studio 2015, update 3
MacOS ver. 10.13.3

**Comment by ChrisColeTech** [comment]
Your mac is probably missing the iOS 11.3 support files- that was the issue in my case.

You can get them by upgrading XCode to the latest version.

Xcode 9.3 was officially released on 3/29. That version includes 11.3 support files.

Also, Xcode 9.4 BETA was released on 4/2, so you may want to give that a try also.

**Comment by ipon85** [comment]
@ChrisColeTech  , you were right. after update XCode to 9.3, and VS Community on MAC to newest version, and update xamarin in VS 2015 to latest stable my issue solved. Thanks!

**Comment by dalexsoto** [comment]
We have not received any new information since April, if you are still experiencing this issue feel free to click the Reopen Issue button. Thanks!
