### ISSUE TITLE
[tvOS] Couldn't deploy to the device

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#3753]
### Steps to Reproduce

1. Create an application (tvOS)
2. Run it on the device (Apple TV)

In the "Deploying to Device" window you can show:
```
warning HE0049: Ignoring wireless connection to Apple_TV because wireless debugging is disabled for this device.
Please connect the device ‘Apple_TV’...
```

### Expected Behavior
The application is deployed successfully.

### Actual Behavior
The deployment proccess fails.

### Environment

1. Visual Studio for Mac 7.4 (build 1033)
https://gist.github.com/mykyta-bondarenko-gl/405578e47f5599621d106163011af3d1

### Build Logs

1. `mlaunch --listdev -vvvvv`
https://gist.github.com/mykyta-bondarenko-gl/6af74fe5939fa0eb0e3f25e92d77a5f2
2. `echo 123456789 > ~/.mlaunch-verbosity` + output
https://gist.github.com/mykyta-bondarenko-gl/453e6443f805f2b05ca8892d03b71572

**Comment by VincentDondain** [comment]
Is it an Apple TV 4K or older? Are you deploying wirelessly or with the USB cable? And what is Xcode > Window > Devices and Simulator showing for that Apple TV device (screenshot if possible).

**Comment by rolfbjarne** [comment]
I can reproduce with XI 11.10.0.15, but not with the latest commit from the d15-7 branch, which means this is already fixed.
