### ISSUE TITLE
Native Code Sharing Disabled

### ISSUE THREAD

**Issue by weirdy** [xamarin/xamarin-macios#3761]
Hello, I've come from this thread https://bugzilla.xamarin.com/show_bug.cgi?id=56498
It looks like that this issue should be resolved, but I still experience this problem in my project.

### Steps to Reproduce

I have iOS and iOS share extension projects referencing Realm database. Besides that there are several .Net Standard library projects in the solution.

After building the solution I get the following warning:

`/Users/ilya.khorev/Projects/Jisp/Jisp.xamarin/Jisp.iOS/MTOUCH: Warning MT0113: Native code sharing has been disabled for the extension 'JispiOSShareExtension' because the container app is referencing the assembly 'Realm' from '/Users/ilya.khorev/Projects/Jisp/Jisp.xamarin/Jisp.iOS/bin/iPhone/Debug/Realm.dll', while the extension references a different version from '/Users/ilya.khorev/Projects/Jisp/Jisp.xamarin/Jisp.iOS.ShareExtension/bin/iPhone/Debug/Realm.dll'. (MT0113) (Jisp.iOS)`

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.4 (build 1033)
Installation UUID: 203906ce-9347-4965-a2ac-9071f8c60f77
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Not Installed

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 11.8.0.20 (Visual Studio Community)
Hash: 1c6f300e
Branch: d15-6
Build date: 2018-02-07 23:42:40-0500

=== Build Information ===

Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

```

### Build Logs

[build-log.txt](https://github.com/xamarin/xamarin-macios/files/1818836/build-log.txt)

**Comment by rolfbjarne** [comment]
From the build log it looks like Fody is processing the Realm.dll assembly, and for each project copying it to a project-specific directory.

Additionally Fody is producing different assemblies, because we accept assemblies with two different paths if they're identical: https://github.com/xamarin/xamarin-macios/blob/cf3648e33f72bfe7528167329cd5a6a3f505525b/tools/mtouch/Application.cs#L1069-L1073

This is a valid reason for disabling code sharing, and the warning is correct.

If you want to ignore the warning, you can add `--nowarn:113` to the additional mtouch arguments in the executable project's iOS Build options.

**Comment by SaqibS** [comment]
We're also encountering this issue, and accepting that code sharing is disabled isn't an option. How come the Realm assemblies are not-identical?

**Comment by rolfbjarne** [comment]
@SaqibS The Realm assemblies are different because a third-party component (Fody) modifies them during the build.
