### ISSUE TITLE
ReplayKit experiencing severe frame drop issue when exporting to video which doesn't happen in Xcode/Swift

### ISSUE THREAD

**Issue by SamStone92** [xamarin/xamarin-macios#3765]
### Steps to Reproduce

I am tapping into the RPScreenRecorder.SharedRecorder singleton to record a video of the UIWindow of the app. 

I start the recording using StartCaptureAsync and write out the contents of the buffer to an AVAssetWriter.

I then stop the recording using StopCapture, and then export the asset using FinishWriting() on the AVAssetWriter. The video produced is jumpy, and not the smooth 60fps I was getting writing this natively.

### Expected Behavior

I'm expecting a video outputted at a near constant 60fps.

### Actual Behavior

A video that jumps around and skips frames every few seconds.

### Environment

```
 RPScreenRecorder rp = RPScreenRecorder.SharedRecorder;
        AVAssetWriter assetWriter;

        AVAssetWriterInput videoInput;

        public void StartScreenRecording()
        {
            VideoSettings videoSettings = new VideoSettings();
            NSError wError;
            assetWriter = new AVAssetWriter(videoSettings.OutputUrl, AVFileType.AppleM4A, out wError);
            videoInput = new AVAssetWriterInput(AVMediaType.Video, videoSettings.OutputSettings);

            videoInput.ExpectsMediaDataInRealTime = true;

            assetWriter.AddInput(videoInput);

            if (rp.Available)
            {

                rp.StartCaptureAsync((buffer, sampleType, error) =>
                {
                    if (buffer.DataIsReady)
                    {

                        if (assetWriter.Status == AVAssetWriterStatus.Unknown)
                        {

                            assetWriter.StartWriting();

                            assetWriter.StartSessionAtSourceTime(buffer.PresentationTimeStamp);

                        }

                        if (assetWriter.Status == AVAssetWriterStatus.Failed)
                        {
                            return;
                        }

                        if (sampleType == RPSampleBufferType.Video)
                        {
                            if (videoInput.ReadyForMoreMediaData)
                            {
                                videoInput.AppendSampleBuffer(buffer);
                            }
                        }

                    }

                });
            }

        }

        public void StopRecording()
        {
            rp.StopCapture((error) => {
                if (error == null)
                {
                    assetWriter.FinishWriting(() => { });
                }
            });
        }

//Video settings
 public AVVideoSettingsCompressed OutputSettings
        {
            get
            {
                return new AVVideoSettingsCompressed
                {
                    Codec = AvCodecKey,
                    Width = Convert.ToInt32(UIScreen.MainScreen.Bounds.Size.Width),
                    Height = Convert.ToInt32(UIScreen.MainScreen.Bounds.Size.Height)
                };
            }
        }


```

### Example Project (If Possible)

https://ufile.io/00tzr Can't upload the test project as its over 10mb. Another DL link can be provided if need be :)

**Comment by dalexsoto** [comment]
Hello @SamStone92! Thanks for your report, I am still investigating what is going on in this one since the sample you provided does not work out of the box for me, it crashed when saving the video recording, this seems not to be your fault from what I can tell but still a little unsure.

Could you do two things for me? First provide me with your version information:

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

and second, please double check that the test case you provided works (does not crash) for you.

Thanks!

**Comment by SamStone92** [comment]
Hi @dalexsoto. Here is a paste with everything from that info screen:

```
Visual Studio Community 2017 for Mac
Version 7.3.3 (build 23)
Installation UUID: c3be71c4-61eb-4f24-b787-492a81d5c67b
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Xamarin.Android
Version: 8.1.5.0 (Visual Studio Community)
Android SDK: /Users/samstone/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.0.2
SDK Platform Tools Version: 26.0.0
SDK Build Tools Version: 26.0.1

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.iOS
Version: 11.6.1.4 (Visual Studio Community)
Hash: db807ec9
Branch: xcode9.2
Build date: 2018-01-10 16:45:48-0500

Xamarin Inspector
Not Installed

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Build Information
Release ID: 703030023
Git revision: e02ab111d8181ffe766c2258141282c88188ebb6
Build date: 2018-02-20 08:06:38-05
Xamarin addins: 5ce2b6790676a4542aa0d69d07f6a716e17d4e65
Build lane: monodevelop-lion-d15-5

Operating System
Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

Enabled user installed addins
MFractor 3.02.10
```

I have to do a clean on the project I uploaded for it to run - but afterwards it builds, records, and saves without crashing (albeit with the frame skip issue). Hope this helps, and thanks for looking into it :)

**Comment by SamStone92** [comment]
@dalexsoto I can clean up the Swift version of this project and send it across if that helps?

**Comment by dalexsoto** [comment]
> @dalexsoto I can clean up the Swift version of this project and send it across if that helps?

@SamStone92 that would be awesome please do!

**Comment by SamStone92** [comment]
@dalexsoto Sorry it took a while, a few things cropped up. Super simple - View Controller loads and records the screen. UIBarButtonItem in the top right stops the recording and outputs it to the documents folder on the device. Any questions just shout :) 
[ReplayKItTest-Swift.zip](https://github.com/xamarin/xamarin-macios/files/1831740/ReplayKItTest-Swift.zip)

**Comment by SamStone92** [comment]
Hi @dalexsoto, have there been any updates at all for this one? If not, is there any sort of timeline we can expect a response in?

**Comment by dalexsoto** [comment]
Hey @SamStone92 thanks for checking again, I totally missed your last response, will look at it hopefully so expect something by Monday the latest.

**Comment by SamStone92** [comment]
No worries, thanks @dalexsoto

**Comment by dalexsoto** [comment]
I am able to see the lag now using the Xamarin.iOS app, I am still investigating the reason why this is happening.

**Comment by SamStone92** [comment]
@dalexsoto I appreciate these things can take some time to look into, but do you have any idea on timeframe for a fix? A reasonable chunk of our work is based upon this working, which we assumed wouldn't be a problem given that it was working in Xcode/Swift. Again, thank you for looking into it.

**Comment by dalexsoto** [comment]
Hey @SamStone92 could you try the following? for some reason I am not able to retrieve the video from the documents folder from my phone... My theory is that you are running out of sample buffers and GC is not fast enough to dispose them so you need a `try {} finally {}` block, please let me know if this fixes the issue for you.

```csharp

try {
	// Do stuff with the buffer.
} finally {
	buffer.Dispose ();
}
```


```csharp
if (rp.Available)
{
	// TODO: Also note that we are not using the Async version here
	rp.StartCapture((buffer, sampleType, error) =>
    {
		try {
			if (buffer.DataIsReady) {

				if (assetWriter.Status == AVAssetWriterStatus.Unknown) {

					assetWriter.StartWriting ();

					assetWriter.StartSessionAtSourceTime (buffer.PresentationTimeStamp);

				}

				if (assetWriter.Status == AVAssetWriterStatus.Failed) {
					return;
				}

				if (sampleType == RPSampleBufferType.Video) {
					if (videoInput.ReadyForMoreMediaData) {
						videoInput.AppendSampleBuffer (buffer);
					}
				}

			}
		} finally {
			buffer.Dispose ();
		}
        

    }, null);
}
```

**Comment by dalexsoto** [comment]
Ok, I was able to extract the video and confirm using the `try {} finally {}` block no longer lags:

```csharp
try {
	// Do stuff with the buffer.
} finally {
	buffer.Dispose ();
}
```

Video file:
[render.MP4.zip](https://github.com/xamarin/xamarin-macios/files/1854098/render.MP4.zip)

This is because the GC is not fast enough to realize that the CMSampleBuffer needs to be released and you run out of sample buffers ,and it is the reason why you kind of see lag because until a new buffer was available it took the snapshot of that actual frame.

Also don't worry about calling `Dispose ()` we do the right thing so there is no need for additional checks 

```csharp
public void Dispose ()
{
	this.Dispose (true);
	GC.SuppressFinalize (this);
}

protected virtual void Dispose (bool disposing)
{
	if (this.invalidate.IsAllocated) {
		this.invalidate.Free ();
	}
	if (this.handle != IntPtr.Zero) {
		CFObject.CFRelease (this.handle);
		this.handle = IntPtr.Zero;
	}
}
```

I am closing this issue since it is resolved. feel free to reopen if this does not fix what you are seeing.
