### ISSUE TITLE
[tvOS][SceneKit] Darker scene than other platforms

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#3766]
I am working on Fox2 sample and I found that a tvOS application has darker scene than the original sample and than macos/ios versions.
There is small trick. "Exr" isn’t supported by tvOS so I turn off this part (changed “.exr” extension to “.png”).  After that the original sample looks correctly but mine isn’t, it’s darker.

### Steps to Reproduce

1. Download a ~[project](https://github.com/mykyta-bondarenko-gl/private-samples/tree/fox-2-scenekit/ios11/Fox2)~ [project](https://github.com/xamarin/mac-ios-samples/tree/master/Fox2)
2. Download the original [Apple sample](https://developer.apple.com/library/content/samplecode/scenekit-2017/Introduction/Intro.html)
3. Open, build and run them on a tvOS device.

### Expected Behavior
They look the same.

### Actual Behavior
The Xamarin version is darker than Apple. 

But if you comment invocation of the `TurnOffEXR` method in the `GameController` class in both samples - they will look the same.

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/ae2d488c6f7609ec5572907c290ec0f2
2. Apple TV 4K. 
tvOS 11.2.6 (15K600)

### Screenshots

- Apple
![Apple](https://user-images.githubusercontent.com/32954580/37523159-c330d590-292e-11e8-9198-dc71ff394c88.png)

- Xamarin
![Xamarin](https://user-images.githubusercontent.com/32954580/37523165-c697c8a6-292e-11e8-9fbd-5c0c784264fc.png)

### Example Project 

1. [Link to the Xamarin project](https://github.com/mykyta-bondarenko-gl/private-samples/tree/fox-2-scenekit/ios11/Fox2)
2. [Link to the Apple project](https://developer.apple.com/library/content/samplecode/scenekit-2017/Introduction/Intro.html)

**Comment by dalexsoto** [comment]
@mykyta-bondarenko-gl have you tried cleaning the bin/ and obj/ folders from your tvOS project? maybe something got cached

**Comment by mykyta-bondarenko-gl** [comment]
@dalexsoto yes, I have. 
As I wrote above - we have the same visual result in both samples if the `TurnOffEXR` method is commented. But if we UNcomment it - the visual result is as images above :(

**Comment by VincentDondain** [comment]
So what is happening here is that the `TurnOffEXR` method (and `TurnOffEXRForMaterialProperty`) is re-setting textures (moving from .exr to .png) but it's getting incorrect path which leads to partially no textures (hence the black).

If we look at `scene.Background` for instance we get:

```
<SCNMaterialProperty: 0x6000002c0770 | contents=textures/Background_sky.png>
```

The `content` is `textures/Background_sky.png` when it should be `art.scnassets/textures/Background_sky.png`. The texture is indeed located under `art.scnassets` and the native sample is getting that full path.

I believe this texture is loaded at the same time as the scene `scene = SCNScene.FromFile ("art.scnassets/scene.scn");`. After a quick look at the SceneKit asset compilation step (msbuild) I didn't see any obvious reason for that behavioral difference we're seeing.

Need to investigate more.

### Workaround

In `TurnOffEXRForMaterialProperty` do:

``` C#
propertyPath = propertyPath.DeletePathExtension().AppendPathExtension(new NSString("png"));
property.Contents = new NSString (System.IO.Path.Combine ("art.scnassets", propertyPath));
```

_Note: this is only happening on tvOS because this method is only called on tvOS. If you call it on iOS the same issue happens (not tvOS specific)._

**Comment by rolfbjarne** [comment]
@VincentDondain the current directory is probably different, which would mean that relative paths don't work the same.

**Comment by VincentDondain** [comment]
> the current directory is probably different

What do you mean? Not sure I follow.

**Comment by rolfbjarne** [comment]
@VincentDondain:

>> the current directory is probably different

> What do you mean? Not sure I follow.

These two snippets will behave differently:

```csharp
Environment.CurrentDirectory = "/";
property.Contents = new NSString (System.IO.Path.Combine ("art.scnassets", propertyPath));
```


```csharp
Environment.CurrentDirectory = "/path/to/my.app";
property.Contents = new NSString (System.IO.Path.Combine ("art.scnassets", propertyPath));
```

because `property.Contents` is a relative path.

Try printing out Environment.CurrentDirectory in both the XI sample and the Swift sample and see if they're the same.

**Comment by VincentDondain** [comment]
@rolfbjarne so there is a difference between XI's current directory which is `/private/var/containers/Bundle/Application/79CCEA18-3A12-493F-BA0C-403C12AAFDB5/Fox2.tvOS.app` and the native current directory which is `/` but I don't think that's the issue.

`property.Contents` with XI is `textures/Background_sky.png` when in native it's `Art.scnassets/textures/Background_sky.png`.

So `property.Contents` for us is somehow always wrong (and not used?) but when we extract it, rewrite it and it's used without `Art.scnassets` then it's used and things start breaking. It's confusing, needs further investigation.

**Comment by VincentDondain** [comment]
Like just after the scene is loaded if I asked for `scene.Background.Contents` I get `textures/Background_sky.png` with XI and `Art.scnassets/textures/Background_sky.png` in Swift.

**Comment by mykyta-bondarenko-gl** [comment]
@rolfbjarne can you merge these changes into the d15-9 too?
