### ISSUE TITLE
The iOS Designer requires an active connection to a Mac server. Please connect to a Mac to enable the designer

### ISSUE THREAD

**Issue by ballanyousef** [xamarin/xamarin-macios#3775]
### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

### Example Project (If Possible)

> VS bug [#585134](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/585134), VS bug [#601227](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/601227)

**Comment by dalexsoto** [comment]
Hello @ballanyousef could you provide us with your version information? Also how can we reproduce this? Is your windows machine connected to a Mac via network?

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by ballanyousef** [comment]
Hello Alex,Thank you,I am using vs Enterprise 2017version 15.2(26430.16) release.
I am also using my home network, wifi with the router.Thank you.
Yousef(Joseph) BallanMSc in Software EngineeringAdvanced software solutions Tech.Microsoft.NET & JAVA EE IOS, Android, Windows phone.
Mobile:(972) 050 7 567 269
 

    On Friday, March 16, 2018, 10:24:13 PM GMT+2, Alex Soto <notifications@github.com> wrote:  
 
 
Hello @ballanyousef could you provide us with your version information? Also how can we reproduce this? Is your windows machine connected to a Mac via network?

The easiest way to get exact version information:
   
   - On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
   - On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.   
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by mandel-macaque** [comment]
@ballanyousef We need the full environment information since you can have different versions on Xamarin.iOs with the same VS version. Please follow the steps that @dalexsoto mentioned (The easiest way to get exact version information...)

Thanks!

**Comment by alanmcgovern** [comment]
Hi,

Can you trigger the bug and then click Help -> Xamarin -> OPen Log Directory and attach a copy of the logs which were generated as part of that session? That will help us diagnose the issue!

Thanks!

**Comment by Kuraimegami** [comment]
Same issue here

Microsoft Visual Studio Enterprise 2017 
Version 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Visual C++ 2017   00369-60000-00001-AA661
Microsoft Visual C++ 2017

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.10.0.448 (4373404db)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.270 (82d750d12)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.178 (408d357)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

-------------------------------------------------------------------------------------

Hope this log part is helpful.

System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory|Error|0|An error occurred while connecting via TCP to the endpoint address 10.9.100.72 and port 56553, to establish an MQTT connection
System.Net.Sockets.SocketException (0x80004005): Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte 10.9.100.72:56553
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory.<CreateAsync>d__4.MoveNext()
System.Net.Mqtt.Sdk.MqttClientFactory|Error|0|An error occurred while initializing a client
System.Net.Mqtt.MqttException: An error occurred while connecting via TCP to the endpoint address 10.9.100.72 and port 56553, to establish an MQTT connection ---> System.Net.Sockets.SocketException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte 10.9.100.72:56553
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory.<CreateAsync>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Mqtt.Sdk.Bindings.TcpChannelFactory.<CreateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Mqtt.Sdk.PacketChannelFactory.<CreateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Mqtt.Sdk.MqttClientFactory.<CreateClientAsync>d__5.MoveNext()
Xamarin.Messaging.Ssh.MessagingService|Information|0|Starting Broker 1.1.6.158 in port 56553...
Xamarin.Messaging.Ssh.SshCommandRunner|Warning|0|Failed to execute 'which mono64': ExitStatus = 1
Xamarin.Messaging.Ssh.SshCommands|Information|0|A valid Mono installation has been found at '/Library/Frameworks/Mono.framework/Versions/Current/bin/mono64'

**Comment by alanmcgovern** [comment]
The full set of logs would help us diagnose the issue. Unfortunately that snippet does not contain enough information to show a problem. This is also code which is unrelated to the designer itself.

**Comment by Kuraimegami** [comment]
[2018-05-31_14-27-24.3328.Ide.log](https://github.com/xamarin/xamarin-macios/files/2058524/2018-05-31_14-27-24.3328.Ide.log)

**Comment by alanmcgovern** [comment]
Can you reproduce the problem in Visual Studio and then use ` Help -> Xamarin -> Zip Logs` to create a zip with all the logs from that session. This is the simplest way for us to ensure we're looking at the right set of logs and have all the information we need.

If you don't have time to reproduce the problem again, could you use `Help -> Xamarin -> Zip Logs (last 7 days)` to give us all the logs from the previous week. We should be able to trawl that set and find a session where you encountered a problem.

The log file you attached does not contain information related to the designer and so we cannot see any problem there. The only thing that looks interesting is that it looks like VS is constantly losing the connection to the Mac. I can see 6 connection attempts to the mac. This may or may not be related to the issue you're seeing.

Thanks!

**Comment by Kuraimegami** [comment]
Thank you for taking a look. It is easy to reproduce: just double click a storyboard. Hope this is more helpful. 
[Log.zip](https://github.com/xamarin/xamarin-macios/files/2058644/Log.zip)

**Comment by alanmcgovern** [comment]
Fortunately this has a simple workaround - you need to update Mono on your Mac. It looks like you're on one of the more recent 15.7 builds of Visual Studio so I'd recommend https://dl.xamarin.com/MonoFrameworkMDK/Macx86/MonoFramework-MDK-5.10.1.57.macos10.xamarin.universal.pkg as it is our latest stable release of Mono for Mac.

I believe this problem was fixed for our 15.6 release, so before you update your mac it would be great if you could run `mono --version` and paste the output here so we can verify that it is just an old/out-of-date Mono issue.

Thanks!

**Comment by Kuraimegami** [comment]
As for the mono version before updating: 5.8.0.129
Now that I updated I don't get the message anymore and it looks like it works :) Thank you very much

**Comment by alanmcgovern** [comment]
Great. Glad to hear the upgrade fixed it. We'll look into ways of ensuring mono is kept up to date to prevent problems like this from occurring silently in the future.

Thanks!

**Comment by MasoudShah** [comment]
Hi @alanmcgovern . This problem has happened again in the newer versions. The latest mono version in stable channel is 5.16.0 which is compatible with ios designer, and the storyboard running on visual studio on windows (with remote login) works good. But the latest version of visual studio (which is currently 15.9.1) cannot connect to the mac and it installs mono 5.12 on the mac remotely to connect to it. With mono 5.12 installed on mac, visual studio connects to mac and builds the project successfully, but again opening storyboard crashes and shows the message stated in the title of this page. While vs2017 is connected to mac, if you upgrade mono on mac to version 5.16 the storyboard gets ok and the error message disappears. But again the project cannot be built and if you disconnect from mac, you cannot connect to it and mono version mismatch error appears. What could be the workaround? Thanks in advance.

**Comment by mkzeta** [comment]
Same error and behavior here as @MasoudShah described.

**Comment by andreinitescu** [comment]
same error here

**Comment by andreinitescu** [comment]
@alanmcgovern I have:
On Mac, mono is 5.12.0.309 
On Windows: Visual Studio 15.9.1, Microsoft Visual Studio Enterprise 2017 
Version 15.9.1
VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.69 (d15-9@15fcf6b03)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.4 (128ba449c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.127 (e975299)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.10 (f2a05ed)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by alanmcgovern** [comment]
This is currently being dealt with by our release team. There was a last minute change in the 15.9 release plans which caused this, and we're trying to release an update to address this asap.

**Comment by andreinitescu** [comment]
@alanmcgovern Thank you. Sorry I have to ask, is there an easy workaround in the meantime? Otherwise I can try use the Visual Studio for Code which appears to work OK.

**Comment by MasoudShah** [comment]
Thank you @alanmcgovern. I can wait for the next update because I'm not in hurry.

**Comment by andreinitescu** [comment]
@alanmcgovern I thought you'd like to know that 15.9.2 fixed the issue for me.

**Comment by mkzeta** [comment]
15.9.2 fixed it for me too.

**Comment by 1TheMuffinMan** [comment]
Whelp it's back again in VS2019

**Comment by trikiman** [comment]
![image](https://user-images.githubusercontent.com/39918652/101015660-ca38cd80-3578-11eb-8084-a3f68bdd757e.png)

**Comment by luismts** [comment]
+1

**Comment by 1TheMuffinMan** [comment]
This feature no longer works because it’s been deprecated in favor of Hot Reload which in my opinion is way more convenient. 

On Windows in VS2019 you go to Tools > Options > Debugging > Hot Reload

Unfortunately, the Xamarin team isn’t always that great at designing the UX for us. I think probably their team size is too small for the demands placed on them by the community.

**Comment by luismts** [comment]
What are you talking about @1TheMuffinMan? We can edit .storyboard files in Xamarin.iOS projects. 

Can you help with this @jsuarezruiz?

**Comment by 1TheMuffinMan** [comment]
> What are you talking about

I can't say anything that would further clarify what I said above.
