### ISSUE TITLE
NSTableView RegisterNib throws exception

### ISSUE THREAD

**Issue by Kimosabe** [xamarin/xamarin-macios#3776]
### Steps to Reproduce

1. Call NSTableView.RegisterNib(null, identifier);

### Expected Behavior
According to [documentation](https://developer.apple.com/documentation/appkit/nstableview/1524297-registernib?language=objc), previously registered nib is removed.

### Actual Behavior
ArgumentNullException: value cannot be null. Parameter name: nib

**Comment by dalexsoto** [comment]
@Kimosabe Thanks a lot for your feedback! 

This is getting fixed by PR# 3778
