### ISSUE TITLE
[mtouch] Support netstandard library nuget package with reference assembly

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#3804]
See test case: https://www.dropbox.com/s/btb6rzb636pnutf/Issue3199Test2.zip?dl=0

In this test case the iOS project references a netstandard class library, which references a Nuget Package (System.Runtime.CompilerServices.Unsafe) but the app does NOT reference that package directly.

In this specific case mtouch will fail with MTOUCH : error MT2101: Can't resolve the reference '!!1& System.Runtime.CompilerServices.Unsafe::As(!!0&)', referenced from the method 'System.Void LibWithPackage.Class1::Test()' in 'System.Runtime.CompilerServices.Unsafe, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. as it doesn't have a reference to System.Runtime.CompilerServices.Unsafe.dll.

Full build log: https://gist.github.com/VincentDondain/3a067c97e7f034a2a5c542dc6d3d7072

Env: https://gist.github.com/VincentDondain/20ff66a750277c383d75d518a925ed82

**Comment by spouliot** [comment]
note: logs are truncated when clicking on the link (GitHub ui size restriction). Click on RAW to see the complete version, including the invocation of `mtouch`

`mtouch` is not given a reference to `System.Runtime.CompilerServices.Unsafe.dll`

**Comment by pjcollins** [comment]
I believe that a related discussion has been happening in the following PRs, and may be worth consulting:

* https://github.com/xamarin/xamarin-android/pull/1356
* https://github.com/xamarin/xamarin-android/pull/1459

**Comment by VincentDondain** [comment]
Yup, thanks @pjcollins.

I'm well aware of these android changes but I'm investigating to see if a simpler solution can be found.

For instance https://github.com/xamarin/xamarin-macios/pull/3791 is much simpler than what XA is doing (scanning all the dlls to check if they are reference assemblies).

**Comment by pjcollins** [comment]
@VincentDondain perfect, happy to hear that you're aware of the work going on in XA. I think I should also cc @dellis1972 on here to continue to promote cross team collaboration on this problem 🙂.

**Comment by VincentDondain** [comment]
I slacked with Dean quite a bit too :P
Cross team collaboration at max power!

**Comment by VincentDondain** [comment]
Msbuild on windows seems to be handling packages with reference assemblies properly. See https://github.com/xamarin/xamarin-macios/issues/4009 where we're investigating the differences between msbuild on mac and windows.

I think we should wait before introduce further "fixes/hacks" before we have a better understand of msbuild on windows and why it works properly.

**Comment by VincentDondain** [comment]
We're still waiting on the investigation in https://github.com/xamarin/xamarin-macios/issues/4009. Since MSBuild on windows seems to be handling packages with reference assemblies properly, we might just have to leverage what's being done there.

**Comment by chamons** [comment]
I believe this is working given my investigation at https://github.com/xamarin/xamarin-macios/issues/4009#issuecomment-568586074

and in running the sample on stable without problems. Let me know if I missed something.
