### ISSUE TITLE
msbuild task DetectSigningIdentity does not detect Provisioning Profile

### ISSUE THREAD

**Issue by johannes-schmitt** [xamarin/xamarin-macios#3807]
### Steps to Reproduce
1. Create a Xamarin Forms Mac project
2. Prepare the app to be signed with developer ID, in Apple Developer Center:
2.1 Create an App ID
2.2 Create a Developer Certificate (and install it on your machine)
2.3. Register your device
2.4 Create a provisioning profile for the app and your device (and install it on your machine)
2.5 ...(maybe I missed a step)
3. Configure to sign the application bundle, with provisioning profile and custom entitlements. In Project Options --> Build --> Mac Signing it should be configured as follows:
3.1. Check "Sign the application bundle"
3.2. Identity: Mac Developer (Automatic)
3.3. Provisioning Profile: Automatic
3.4. Custom entitlements: Entitlements.plist
4. Build the project
4.1 In order to get diagnostic build log verbosity, use the msbuild command line, because Visual Studio for Mac is truncating the build logs (I use _msbuild /p:Configuration=Debug /p:Platform=x86 /verbosity:diagnostic /noconsolelogger /fileLogger <solution.sln>_). The error occurs both for Configuration=Release and Debug.

### Expected Behavior
The provisioning profile should be embedded. You can use the app _[RB App Checker lite](https://itunes.apple.com/ca/app/rb-app-checker-lite/id519421117)_ to verify this.
This used to work until Visual Studio for Mac was updated to the latest version.  
In _msbuild.log_ (with VSfM 7.3.3) you should see that the task _DetectSigningIdentity_ detects a provisioning profile to be used, the output is something like this (X-ed out "confidential" stuff), whereas in the last line, you can see that a provisioning profile was detected. 
> Task "DetectSigningIdentity"
>   Task Parameter:AppBundleName=XXXXXXXX
>   Task Parameter:AppManifest=Info.plist
>   Task Parameter:RequireCodeSigning=True
>   Task Parameter:SdkPlatform=MacOSX
>   Task Parameter:ProvisioningProfile=Automatic
>   Task Parameter:SigningKey=Mac Developer
>   Detected signing identity:
>     Code Signing Key: "Mac Developer: XXXXX (XXXX)" (XXXXXX)
>     Provisioning Profile: "XXXX" (XXXXX)
>     Bundle Id: com.XXXX.XXX
>     App Id: XXX.com.XXXX.XXX
>   Output Property: _AppIdentifier=XXX.com.XXXX.XXX
>   Output Property: _BundleIdentifier=com.XXXX.XXX
>   Output Property: _CodeSigningKey=XXXXXXXXXXXXXX
>   Output Property: _CodesignAllocate=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
**>   Output Property: _ProvisioningProfile=XXXXXXXXXXXXXXXXXXXXX**

Further in the log file, one can see that the Task _CompileEntitlements_ is using the provisioning profile:

> Task "CompileEntitlements"
>   Task Parameter:AppBundleDir=bin/Debug/XXXXXX.app
>   Task Parameter:AppIdentifier=XXX.com.XXXX.XXX
>   Task Parameter:BundleIdentifier=com.XXXX.XXX
>   Task Parameter:Entitlements=Entitlements.plist
>   Task Parameter:CompiledEntitlements=obj/x86/Debug/Entitlements.xcent
>   Task Parameter:IsAppExtension=False
**>   Task Parameter:ProvisioningProfile=XXXXXXXXXXXXXXXX**
>   Task Parameter:SdkVersion=10.13
>   Task Parameter:SdkDevPath=/Applications/Xcode.app/Contents/Developer
>   Task Parameter:Debug=True

And a bit later, it's used to in _EmbedProvisionProfile_ to be embedded:

> Task "EmbedProvisionProfile"
>   Task Parameter:AppBundleDir=bin/Debug/XXXXXX.app
**>   Task Parameter:ProvisioningProfile=XXXXXXXXX**

### Actual Behavior
The provisioning profile is not embedded. Compared to above, the msbuild.log file looks also a bit different, because with the latest version of Visual Studio there have been some changes in the msbuild task DetectSigningIdentity (including changes to logging). Nevertheless, you can see that no provisioning profile was detected:

> Task "DetectSigningIdentity"
>   Task Parameter:AppBundleName=XXXXX
>   Task Parameter:AppManifest=Info.plist
>   Task Parameter:RequireCodeSigning=True
>   Task Parameter:SdkPlatform=MacOSX
>   Task Parameter:ProvisioningProfile=Automatic
>   Task Parameter:SigningKey=Mac Developer
>   The certificate 'XXXXXXXXXXXX' does not match any of the prefixes 'Mac Developer'.
>   The certificate 'XXXXXXXXXXXX' does not match any of the prefixes 'Mac Developer'.
>   Available certificates:
>       Mac Developer: XXXXXXX (XXXXXXX)
>   Detected signing identity:
>     Code Signing Key: "Mac Developer: XXXXXXX (XXXXXX)" (XXXXXXXXXXXXXXXXXXXX)
>     Bundle Id: com.XXXX.XXX
>     App Id: com.XXXX.XXX
>   Output Property: _AppIdentifier=com.XXXX.XXX
>   Output Property: _BundleIdentifier=com.XXXX.XXX
>   Output Property: _CodeSigningKey=XXXXXXXXXXXXXXXXXX
>   Output Property: _CodesignAllocate=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate

Because no provisioning profile was detected, CompileEntitlements does not receive a provisioning profile:

> Task "CompileEntitlements"
>   Task Parameter:AppBundleDir=bin/Debug/XXXXXX.app
>   Task Parameter:AppIdentifier=com.XXXX.XXX
>   Task Parameter:BundleIdentifier=com.XXXX.XXX
>   Task Parameter:Entitlements=Entitlements.plist
>   Task Parameter:CompiledEntitlements=obj/x86/Debug/Entitlements.xcent
>   Task Parameter:IsAppExtension=False
>   Task Parameter:SdkVersion=10.13
>   Task Parameter:SdkPlatform=MacOSX
>   Task Parameter:SdkDevPath=/Applications/Xcode.app/Contents/Developer
>   Task Parameter:Debug=True

and because no provisioning profile was detected, the task _EmbedProvisionProfile_ gets skipped:
> _Target "_EmbedProvisionProfile" skipped, due to false condition; ('$(_ProvisioningProfile)' != '') was evaluated as ('' != '')._

### Environment
Everything works with `VSfM 7.3.3 (build 23), Mono 5.4.1.7 (2017-06/e66d9abbb27), Xamarin.Mac 4.0.0.216`
Problem can be reproduced after updating to latest version of `VSfM, one collegue faced this problem with beta channel: 7.5 Preview (7.5 build 933), Mono 5.10.0.179 (2017-12/dac60775616), Xamarin.Mac 4.4.0.31`
Another collegue has the same problem with current stable VSfM (unfortunately, I don't have version details at hand)

### Build Logs
The important pieces of the build log are already quoted above. If you more details are needed, please let me know. 

### Example Project (If Possible)
not possible, from my point of view

**Comment by chamons** [comment]
This appears at first glance to have the same root cause as https://github.com/xamarin/xamarin-macios/issues/3674

**Comment by chamons** [comment]
Could you test the fix listed here:

https://github.com/xamarin/xamarin-macios/issues/3674#issuecomment-371910565

OR

install the latest master build: https://jenkins.mono-project.com/view/Xamarin.MaciOS/job/xamarin-macios-builds-master/

and report back if that "fixes" your issue.

**Comment by chamons** [comment]
The fix in master landed and it's been cherry picked to various release branches, but I don't believe any of them are released yet (thus, let's check master and see if it's fixed).

If you want to do the homework to see what branch has the fix, you first have to pull up the various release branches:

https://github.com/xamarin/xamarin-macios/tree/d15-6
https://github.com/xamarin/xamarin-macios/tree/d15-7

in the Make.config you can check the MAC_PACKAGE_VERSION to see what major/minor each is at. 4.4 in d15-7 and 4.2 in d15.6.

Since it is in 15.7 though, you could grab the latest from the release branch: https://github.com/xamarin/xamarin-macios/tree/d15-7

instead of master I guess.

Then you'd have to determine if your point build of that branch is new enough after the cherry pick of the fix. We auto bump the release version every commit, so sometimes that's non-trivial to figure out.

**Comment by johannes-schmitt** [comment]
Verified, fixed
