### ISSUE TITLE
[msbuild] Add msbuild test for #3791: Skip reference assemblies passed to mtouch

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#3810]
See https://bugzilla.xamarin.com/show_bug.cgi?id=53164.

Our msbuild tests are in fact still using `xbuild`. Because the test case in https://github.com/xamarin/xamarin-macios/pull/3791 is using NugetPackages added via "PackageReference" it needs msbuild. `xbuild` cannot "restore" nor is using the right `ResolveAssemblyReferences` target (that feeds csc with the right assemblies).

Adding the test itself once our tests are using msbuild should be trivial. It's just a matter of building the project with msbuild which will resolve the packages correctly.

**Comment by VincentDondain** [comment]
There should also be a mmptest to cover the Xamarin.Mac side of the house.

https://github.com/xamarin/xamarin-macios/pull/3991

**Comment by VincentDondain** [comment]
xbuild fix now being tracked here: https://github.com/xamarin/xamarin-macios/issues/4110

**Comment by rolfbjarne** [comment]
This is no longer relevant with .NET.
