### ISSUE TITLE
Neverending build on device (due to Mac Agent disconnecting?)

### ISSUE THREAD

**Issue by rihadavid** [xamarin/xamarin-macios#3818]
Ok, this is driving my crazy, iPhone device build stopped working **at all**.

When I try to build my Xamarin.iOS project in the latest Visual Studio in iPhone-device configuration, it never finishes building - does not fail, does not succeed, just keeps building.  

The problem might be that I am getting those logs in Xamarin output, it repeats every few minutes:

> Connection to '192.168.15.128' completed successfully
> Agent Build 4.9.0.752 is not connected...
> Starting registered Agents: Build 4.9.0.752...
> Starting Build 4.9.0.752...
> Starting Agent Build 4.9.0.752...
> Agent Build 4.9.0.752 is running
> Build 4.9.0.752 started
> Starting registered Agents: ...
> The Agents have been started successfully
> Agent Build 4.9.0.752 is not connected...
> Starting registered Agents: Build 4.9.0.752...
> Starting Build 4.9.0.752...
> Starting Agent Build 4.9.0.752...
> Agent Build 4.9.0.752 is running
> Build 4.9.0.752 started
> Starting registered Agents: ...
> The Agents have been started successfully
> Agent Build 4.9.0.752 is not connected...
> Starting registered Agents: Build 4.9.0.752...
> Starting Build 4.9.0.752...
> Starting Agent Build 4.9.0.752...
> Agent Build 4.9.0.752 is running
> Build 4.9.0.752 started
> Starting registered Agents: ...
> The Agents have been started successfully

When I do iPhone Simulator build, it takes 1-3 minutes, succeeds and deploys OK.

But even when building for the simulator, I sometimes (like every 20 minutes I guess) get to situation when after successful build, I am presented with the Mac Agent connection dialog, where my Mac has the 'connected' icon, but when I close the dialog, I get some popup alert that active connection is needed - so what I need to do is Disconnect and Connect again in order to be able to deploy to the simulator.
This little issue is happening a few weeks, it is present since a few releases back. **But the neverending-build issue is only happening since I updated VS to 15.6.4** (but I have skipped a few releases between, like 15.6.2 and 3 I guess, so it might not be related exactly to 15.6.4).

Please also note that I have tried changing many of the properties in iOS project settings, tried rebooting windows, rebooting OS X, rebooting iPhone... basically spend whole day trying to make it work. And sometimes it actually did build (like 3 times during the whole day I guess), but there were erros with deploying (I was trying on iPhone 4 iOS 7, which used to work, like kAMDIncorrectArchitectureError). Then again the next builds were failing.
Also once in the million neverending tries, the build actually failed with error `Invalid bitcode signature`.

### Environment

OS X 10.13.3 inside VMware 14.1.1, XCode 9.2

Microsoft Visual Studio Community 2017 
Version 15.6.4
VisualStudio.15.Release/15.6.4+27428.2015
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual F# Tools 10.1 for F# 4.1   00369-60000-00001-AA614
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10212.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.11027.3
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.752 (0faa808ee)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.58 (cee1369d0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.8.1.28 (3979d08)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Build Logs
Intellisense output:

> [Failure] Could not find file 'D:\Dokumenty-D\aplikace\MyApp\MyApp.iOS\obj\iPhone\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs'.
> [Failure] Could not find file 'D:\Dokumenty-D\aplikace\MyApp\MyApp.iOS\obj\iPhone\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs'.
> [Failure] Could not find file 'D:\Dokumenty-D\aplikace\MyApp\MyApp.iOS\obj\iPhone\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs'.

Build output after 40 minutes of building, just one line:

> 1>------ Rebuild All started: Project: MyApp.iOS, Configuration: Debug iPhone ------

Build output after cancelling the build:
Quite a long diagnostic output, see the attachment:
[log.txt](https://github.com/xamarin/xamarin-macios/files/1850001/log.txt)

Guys, please fix Xamarin!

> VS bug [#591998](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591998)

**Comment by rihadavid** [comment]
This time it failed again with the `Invalid bitcode signature` after few minutes, attaching the log:
[log-2.txt](https://github.com/xamarin/xamarin-macios/files/1850017/log-2.txt)

**Comment by rihadavid** [comment]
To confirm that it is really neverending, not just slow, today I kept the build running the whole night. Yes, it is neverending.

**Comment by rihadavid** [comment]
Clearing `Library/Caches/Xamarin/mtbs`, `Library/Caches/Xamarin` and `%localappdata%\Temp\Xamarin\XMA` seems to help, rebuild is now finished after 7 minutes and additional builds take about 3 minutes. Which is still quite slow and also I got the disconnecting issue after a successful build, but I will probably create a new issue for this.

**Comment by therealjohn** [comment]
@rihadavid That is really interesting. Could you share a successful build log now? I'd like to compare to what you provided before which shows the `Invalid bitcode signature` error. It does seem odd to get that intermittently. 

The mac agent connection window continually popping up sounds similar to an issue being tracked for Visual Studio [here](https://developercommunity.visualstudio.com/content/problem/209831/vs156-xamarinios-still-prompts-for-an-active-mac-w.html). Please log any additional info you have for that there. 

An additional consideration: Is your macOS instance running on a VM in Windows or on Mac hardware?

**Comment by rihadavid** [comment]
Ok, so it seems to be a little more complicated. Now when I set the project properties to the settings that was throwing `Invalid bitcode signature`, I still get the error. See this log [log-4.txt](https://github.com/xamarin/xamarin-macios/files/1857952/log-4.txt)

But when I set the configuration that I am using now, it builds successfully, see the log: [log-5.txt](https://github.com/xamarin/xamarin-macios/files/1857954/log-5.txt)

But when I set the same configuration that I used on Mar 26, which was building whole night (log here [log-3.txt](https://github.com/xamarin/xamarin-macios/files/1857957/log-3.txt))
), it now builds without problems, see the log: [log-6.txt](https://github.com/xamarin/xamarin-macios/files/1857964/log-6.txt)

**Comment by therealjohn** [comment]
@rihadavid 

In the iOS project Properties, uncheck the "Enable device-specific builds" checkbox for your configuration. Then, please rebuild. 

![image](https://user-images.githubusercontent.com/1501196/38090897-f760ceda-3331-11e8-90e4-a0ea75667647.png)

I noticed that the failing log is building for armv7s + arm64 while the non-failing log is only building for armv7. I am wondering if this is a problem with a native library being used or if it's an intermittent error due to the size of the binary being built.

**Comment by mauroa** [comment]
Hi @rihadavid,
Looks like this issue covers different aspects. 
One thing is the device specific build throwing an exception with the Invalid bitcode signature message.
The other one is the connection to the Mac being disconnected or the Build Agent being disconnected and reset. This should be happening for some MSBuild Task getting freezed on the Build Agent in the Mac, or some unhandled exception in the Agent as well.
For this particular case it would be useful to also have the Build agent log from the Mac.
You can get it by:
1 - If the connection to the Mac is still active, you can do from VS: Help > Xamarin > Zip Logs. That will get all the logs from the Mac and also the logs from Windows
2  - If the connection to the Mac is down, you need to get the loc manually from the Mac in: ~/Library/Logs/Xamarin-x.xxx/Build.log

We are investigating the other issue in the meantime.
Thanks

**Comment by mauroa** [comment]
After digging deeper on the MSBuild logs, looks like there are some third party native libraries that maybe doesn't support some specific architectures, like armv7s. Flurry.Analytics is one of them, also the Facebook SDK.

That can explain the linking errors with the invalide bitcode signature and how it disappears when swhitching architectures or disabling Device-specific builds.
It's not very clear on the previous messages with which architectures and configurations you tried with, but playing with the different architectures and also checking/unchecking the Device-specific builds checkbox could help on making a conclussion.

On the other hand there is the never ending issue, which would be good to detect if it's related to the Device-specific builds or not. Do you see it even if you disable the Device-specific builds check?
Comparing the log3 and log6, which are basivally the same but one with the hang and the other without it, I can't infer the cause of the hang.

The Build Agent log could also help to detect if some exception or hang is happening on the other side.
We will continue investigating.

**Comment by mauroa** [comment]
The root cause of the Mac Agent dialog being shown asking for connection when VS shows it as already connected has been found and fixed.

Also, an issue has been found where if for some reason the Build Agent is disconnected and restarted, the Build process was not being cancelled. This could be the underlying reason of the never ending build, given that it's not cancelled because MSBuild is not aware of the Agent re connection.

Finally, some serialization issues on the network messages have been fixed that could be causing some unhandled crashes in the Agents communication.

For these reasons and also because the linking errors mentioned above looks like compatibility problems in third party libraries, I will consider this issue as fixed.

You can give it a try on the next VS d15-8 version and let us know if you have any other related problem.
