### ISSUE TITLE
Failed to determine simulator version for "UDID of the device i provided"

### ISSUE THREAD

**Issue by AtulSree** [xamarin/xamarin-macios#3819]
### Steps to Reproduce

1. Opened a testIOS project as IOS UITest App
2. Provided details of UDID and bundle ID in AppInitializer file.
3. Installed a debug app into a device provisioned for testing. The debug app has calabash component enabled.
4. Installed a developer certificate in the MAC.

### Expected Behavior
1. DeviceAgent should be installed.
2. App should launch.

### Actual Behavior
Three kinds of issues in three different machines.

1. Failed to determine simulator version for "UDID of the device i provided".
2. Failed to install device Agent.
3. Failed to clear app cache data.

### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.4 (build 1033)
Installation UUID: 905bacc1-8b24-498c-bab9-5730c0669d6c
Runtime:
	Mono 5.8.0.129 (2017-10/835a98d8559) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000129

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.15 (Visual Studio Enterprise)
Android SDK: /Users/atul_sreekumar/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.0.20 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.8.0.20 (Visual Studio Enterprise)
Hash: 1c6f300e
Branch: d15-6
Build date: 2018-02-07 23:42:40-0500

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704001033
Git revision: 053991068f3c88497d3e5cc52fe7fdf57c28b62f
Build date: 2018-02-28 05:02:28-05
Xamarin addins: cc3283953e0af0b8bfab1bdfdf847d9e403c4606
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jan 11 22:59:40 PST 2018
    root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64


```

### Example Project (If Possible)

The sample project is just an IOS project opened in XamarinUITest. Open new project-> IOS Test-> UI Test App.

**Comment by AtulSree** [comment]
Hi Team,

Here, the dev team is using Latest Xamarin forms, version 2.5.0.121934, to develop the app.
We have Developer certificates and provisioning profiles in our system.
Request you to provide the exact setup to be followed in order to launch application in IOS Device.

Thanks in advance.
Atul Sreekumar

**Comment by AtulSree** [comment]
Fresh set of Error Logs:

SetUp : Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to clear data for app com.jitr.adecco.client.qa

ExitCode: 5

		-d,--device-id	<device-identifier>	iOS Simulator GUID or 40-digit physical device ID
	0   DTDeviceKitBase                     0x000000010d669fed DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x000000010d66a831 DTDK_AMDErrorToNSError + 1135
	10  DVTFoundation                       0x000000010b93dc7a -[DVTDispatchLock performLockedBlock:] + 75
	11  DTDeviceKitBase                     0x000000010d66b915 DTDKExecuteWithConnection + 231
	12  DTDeviceKitBase                     0x000000010d66c681 DTDKExecuteInSession + 381
	13  DTDeviceKitBase                     0x000000010d67b458 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 119
	14  DVTFoundation                       0x000000010b963a4f __DVTDispatchAsync_block_invoke + 806
	15  libdispatch.dylib                   0x00007fffbb948524 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fffbb93f8fc _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fffbb9559a0 _dispatch_queue_serial_drain + 896
	18  libdispatch.dylib                   0x00007fffbb948306 _dispatch_queue_invoke + 1046
	19  libdispatch.dylib                   0x00007fffbb9416b5 _dispatch_root_queue_drain + 476
	2   DTDeviceKitBase                     0x000000010d67c685 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 98
	20  libdispatch.dylib                   0x00007fffbb94148c _dispatch_worker_thread3 + 99
	21  libsystem_pthread.dylib             0x00007fffbbb8e5a2 _pthread_wqthread + 1299
	22  libsystem_pthread.dylib             0x00007fffbbb8e07d start_wqthread + 13
	3   DTDeviceKitBase                     0x000000010d67b521 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	4   DTDeviceKitBase                     0x000000010d66c815 __DTDKExecuteInSession_block_invoke_2 + 35
	5   DTDeviceKitBase                     0x000000010d66bc1f __DTDKExecuteWithConnection_block_invoke_2 + 474
	6   DTDeviceKitBase                     0x000000010d66ba1a __DTDKExecuteWithConnection_block_invoke + 111
	7   libdispatch.dylib                   0x00007fffbb93f8fc _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fffbb940536 _dispatch_barrier_sync_f_invoke + 83
	9   DVTFoundation                       0x000000010b9646f0 DVTDispatchBarrierSync + 213
	upload-xcappdata <bundle-identifier> <file-path>
), NSLocalizedRecoverySuggestion=Could not find the requested application., NSLocalizedDescription=Could not find the requested application.}]
2018-03-27 19:55:40.822 iOSDeviceManager[22781:2596273]  DTDeviceKit: Could not start house arrest service for app identifier com.jitr.adecco.client.qa [Error Domain=com.apple.dtdevicekit Code=-402653001 "Could not find the requested application." UserInfo={NSLocalizedFailureReason=Could not find the requested application., com.apple.dtdevicekit.stacktrace=(
Error uploading files to application container: Could not find the requested application.

**Comment by therealjohn** [comment]
@AtulSree This is probably best answered by the App Center team. You can reach out to AppCenter support by logging into https://appcenter.ms/apps and clicking the chat icon in the [lower right corner of the screen](https://www.screencast.com/t/uF8S5o0o0). From there, you can start a ticket for support with UITest. I hope that helps!
