### ISSUE TITLE
Question: Building from release tarballs

### ISSUE THREAD

**Issue by wjk** [xamarin/xamarin-macios#3820]
### Steps to Reproduce

1. Go to Releases and download a source tarball/zip file for a tagged release (for example, [`xamarin-mac-4.2.1.28`](https://github.com/xamarin/xamarin-macios/releases/tag/xamarin-mac-4.2.1.28)).
2. Unpack the tarball.
3. Attempt to run `make reset-versions`. Watch the build fail due to the lack of a git checkout.

### Expected Behavior

There should be some way to build Xamarin.Mac from a release source tarball.

### Actual Behavior

You can’t do this.

### Possible Solutions

Would it be possible to manually repack the repository such that all the submodules are included in the release tarball, so that the (very large) tarball would be all you need to build? As it stands today you cannot build from a release version _at all_.

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.4.1 (build 48)
Installation UUID: f4ba95f3-b523-4d1e-a96f-e0510f81d032
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Community)
Android SDK: /Users/wjk/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Community)

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 11.8.1.28 (Visual Studio Community)
Hash: 3979d081
Branch: d15-6
Build date: 2018-03-09 16:22:34-0500

=== Build Information ===

Release ID: 704010048
Git revision: 6a86203dd590c6cfdf814c8832d24d2ad1e2606f
Build date: 2018-03-20 11:16:55-04
Xamarin addins: 8d83cea9e4ae03cb0c14ba3fbaafdbb0cbd170e7
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

EditorConfig 1.2
Eto.Forms Support Addin 2.4.0.0
AddinMaker 1.4.2
Internet of Things (IoT) development (Preview) 7.1
```

**Comment by therealjohn** [comment]
@chamons Would you be able to review and answer this?

**Comment by chamons** [comment]
I can confirm we are stripping out the required information, which makes them totally useless.

The hash (3979d08 in this case) is around, so you could git clone && git checkout 3979d08 and build to get a build, but they why have the tarballs.

Let me see who is generating those and what we can do.

**Comment by chamons** [comment]
After doing some research:

https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release/34721233#34721233

this appears to be a limitation / bug in github. I've found a number of other projects only who's also run into this.

This appears to affect every project that uses submodules, and unfortunately makes the tarballs useless.

Checking out via git and building should work however. Sorry for the trouble, but this is not something we can fix on our end. :(

**Comment by spouliot** [comment]
Even if GitHub had _proper_ support for submodules it would not be correct to do `make reset-versions` since that's meant to sync revisions on git dependencies (submodules or not).
