### ISSUE TITLE
[mono2018-02]System test failures observed on device

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3827]
### Steps to Reproduce

1. Update System to Xamarin.iOS from mono2018-02 branch d458533dc3f48ea4b6e6798feff7617dd340ba96
2. Execute System test on device

### Expected Behavior
Tests should pass successfully
### Actual Behavior
[FAIL] HttpRequestStreamTest.Post_EmptyRequestStream :   #1
[FAIL] HttpResponseStreamTest.AutomaticDecompression : System.Net.WebException : Error getting response stream (ReadAsync): ReceiveFailure Unable to read data from the transport connection: Connection reset by peer.
[FAIL] WebClientTest.GetWebRequestOverriding : System.Net.WebException : The operation has timed out.
### Environment

 Xamarin.iOS from mono2018-02 branch d458533dc3f48ea4b6e6798feff7617dd340ba96

### Build Logs

Build Log: http://xqa.blob.core.windows.net/gist/report-a8c0c5d2cd7141c2bdc6f3640f6be371.txt
Test Log: http://xqa.blob.core.windows.net/gist/System-ios03-58-1587cf18d9f45ef54e0c940cda510cd49c97afeb9a03-58-15-3fe18bc47c024158b7c55eb9968b52b9.zip

## Additional Info:
I could reproduce only  HttpResponseStreamTest.AutomaticDecompression  failure locally .
This issue is also observed on iPhoneX device: http://xqa.blob.core.windows.net/gist/report-7c46777a2fa941bea744213995615b12.txt

**Comment by lewurm** [comment]
can't reproduce it on an iPhone7.  Could this be network related?

**Comment by GouriKumari** [comment]
I can reproduce only  HttpResponseStreamTest.AutomaticDecompression locally. Both the device and my test machine  are on  the same network. This is the same setting for bots and devices as well. I did run the tests twice from bots and HttpResponseStreamTest.AutomaticDecompression fails consistently in every test run. 

Build Log: https://gist.github.com/GouriKumari/0f749983ae91847b795783a53b9c04ba
Test Log: https://gist.github.com/GouriKumari/c433688bfbda8d3ac05265a76df39026

**Comment by lewurm** [comment]
I can reproduce `HttpResponseStreamTest.AutomaticDecompression` now too. It isn't 100% reproducible for me, but fairly likely.

**Comment by lewurm** [comment]
@baulig @marek-safar any idea what this could be about?

**Comment by marek-safar** [comment]
This could be caused by @baulig async changes. Martin could you confirm?

**Comment by lewurm** [comment]
comment by @baulig https://xamarinhq.slack.com/archives/C5P3G23NG/p1522789572000010

**Comment by GouriKumari** [comment]
The above mentioned tests are no longer included in mono2018-02 test run, hence there are no failures related to above tests. There is a random SocketTest failure reported on a single device, [FAIL] SocketTest.SocketErrorTest : SocketError wait timed out which seems to be network related.

## Logs: http://xqa.blob.core.windows.net/gist/System-ios01-10-33e978c67571aa0652bdb4ad6b8338ec46633e07ef01-10-33-e2f11dd682c3425cabc364fdd5471284.zip

**Comment by GouriKumari** [comment]
I am closing this based on the above comment.
