### ISSUE TITLE
New Info.plist does not define CFBundleIdentifier errors in XamarinComponents in 15.6 - Regression?

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3831]
### Steps to Reproduce

1. git clone git@github.com:xamarin/XamarinComponents.git
2. cd XamarinComponents/iOS/iRate/
3. sh ../../build.sh -t samples -v diagnostic

### Expected Behavior

New errors to not appear in upgrading from 15.5 to 15.6

### Actual Behavior

  ```Info.plist : error : Info.plist does not define CFBundleIdentifier [/Users/donblas/XamarinComponents/iOS/iRate/samples/iRateDemo/iRateDemo.csproj]```

### Environment

Fails - xamarin.ios-11.8.1.28.pkg
Works - xamarin.ios-11.6.1.4.pkg

### Build Logs

https://gist.github.com/chamons/3c15650646416d86d9baa08e327ef0a0

**Comment by jstedfast** [comment]
Looks like the error is correct:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>MinimumOSVersion</key>
	<string>8.0</string>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>
</plist>
```

The Info.plist does not seem to contain a CFBundleIdentifier which is required to exist.

**Comment by chamons** [comment]
So this never should have worked? It seems strange that a point release started erroring?

**Comment by jstedfast** [comment]
I think @VincentDondain or someone recently added the same build validation code that iOS has to Mac?

**Comment by chamons** [comment]
This is an iOS app.

**Comment by jstedfast** [comment]
Ah, looks like that's part of the change made to DetectSigningIdentity. It now explicitly bails if the Info.plist does not contain a CFBundleIdentifier which is needed to match against a provisioning profile.

The demo app really should define a CFBundleIdentifier.

**Comment by therealjohn** [comment]
@chamons  It sounds like this is expected behavior now that DetectSigningIdentity found and not a regression - correct? If so, can this issue be closed?

**Comment by chamons** [comment]
It depends on how you slice it. Projects that used to compile fine now don't, but @jstedfast statement suggests those were invalid configured projects.

¯\\_(ツ)_/¯
