### ISSUE TITLE
Question: License of Jenkins artifacts

### ISSUE THREAD

**Issue by wjk** [xamarin/xamarin-macios#3836]
Following the technique outlined in https://github.com/xamarin/xamarin-android/issues/1484#issuecomment-377393450, I tried digging through the Jenkins build history for xamarin-macios. I found the following link:

<https://bosstoragemirror.azureedge.net/wrench/macios-mac-master/b8/b8287d0b33e6fbef0bc18967b9b6284cfa6e8c12/xamarin.mac-4.5.0.102.pkg>

This file points to an installer containing the prebuilt Xamarin.Mac framework, which is really all I need. (See #3820 for why I can't just build from a source snapshot.) However, the license included in the installer file is the standard VSMac EULA, not the MIT license like the source code. I am trying to write an IDE similar to VSMac, except that it uses a native Cocoa UI instead of GTK#. (This is a long-standing pet peeve of mine with regards to VSMac.) I need a copy of the Xamarin.Mac and Xamarin.iOS frameworks I can either redistribute with my installer, or download from the Jenkins URLs at runtime, but I am uncertain if the EULA allows for this.

It seems kind of strange that the binaries built by this MIT-licensed repository are not licensed similarly (modulo any proprietary parts such as `mlaunch`, of course; while I can delete those if I need to, they do not appear to be contained in this installer). Could someone please clarify this? Of course, it would be better if the EULA on these packages be changed to the MIT license, but I don't know how easy/possible this is. Thanks so much!

**Comment by therealjohn** [comment]
Hi @wjk,

I've emailed the team to find out who can address this. Thanks for your patience!

**Comment by migueldeicaza** [comment]
You are correct, the binaries included in that distribution contain proprietary code that is not open source.

For now, you should build the open source repositories, and you can use the result under the MIT license.   As a long-term action for my team, we should setup a CI that publishes just the open source bits.

**Comment by VincentDondain** [comment]
Ok let's keep this issue here as an enhancement as it sounds like we _maybe_ have to update our makefiles so that jenkins can produce a build without the private bits.

That work will need to be coordinated with release engineering (maybe we'll move the issue there at some point). I'll let @rolfbjarne or @spouliot close the issue if nothing needs to be done on the Xamarin.iOS side of the house.

**Comment by rolfbjarne** [comment]
This is no longer relevant with .NET
