### ISSUE TITLE
Unable to configure iOS SDK path in Visual Studio 2017

### ISSUE THREAD

**Issue by bigDave1357** [xamarin/xamarin-macios#3839]
### Steps to Reproduce

1. Tools Menu -> Options -> Xamarin -> iOS Settings
2. Apple SDK Use Default Xcode path is disabled and cannot be selected. It is also unticked. Xcode path is blank.
3. Visual Studio is attempting to locate the SDK at /Applications/Xcode 9.2.app which I have previously configured in this panel. However, I now cannot use this panel to revert the settings.

If I try to connect to my Mac the connection fails because xcodebuild cannot be located at this path. And I cannot reset it as the above form is not working.

### Expected Behavior

Should be able to reconfigure the SDK path using the form above

### Actual Behavior

Forms controls are disabled

### Environment

```
Microsoft Visual Studio Enterprise 2017 
Version 15.6.4
VisualStudio.15.Release/15.6.4+27428.2015
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-90253-22591-AA071
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2017   00369-90253-22591-AA071
Microsoft Visual C++ 2017

Visual F# Tools 10.1 for F# 4.1   00369-90253-22591-AA071
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10212.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   4.0.21208.0
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.0.40322.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.1
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Debugging Tools for Windows   10.0.16292.1001
Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.3.3000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.3000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Redgate ReadyRoll   1.16.18088.9228
Extend DevOps processes to your SQL Server databases and safely automate database deployments.

Visit https://www.red-gate.com/readyroll for more information.

Copyright (C) 2011 Red Gate Software Ltd. All rights reserved.

This software contains components from Component Owl.
SQL Server is a registered trademark of Microsoft Corporation.
Visual Studio is a registered trademark of Microsoft Corporation.

ReadyRoll contains code from the following open source software:

NuGet https://www.nuget.org/
SQL LocalDB Wrapper https://github.com/martincostello/sqllocaldb
Autofac https://autofac.org/
Json.NET https://json.net/
MahApps.Metro http://mahapps.com/
SemVer https://github.com/maxhauser/semver
Log4Net http://logging.apache.org/log4net/
StringTemplate https://github.com/antlr/stringtemplate4
Extended WPF Toolkit https://wpftoolkit.codeplex.com/
Code InfoBox VSX http://www.codeproject.com/Articles/55196/Code-InfoBox-Visual-Studio-Extension-VSX
OctoPack https://github.com/OctopusDeploy/OctoPack
SQLite https://sqlite.org/

This product contains icons from http://www.visualpharm.com distributed under a free backlink license.

For license details or other notices relating to the above software, please see NOTICE.TXT and EULA.rtf in the ReadyRoll application folder.
    

Redgate SQL Prompt   9.1.5.4619
Write, format, and refactor SQL effortlessly

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.8
Visual C++ for Linux Development

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Unity   3.6.0.5
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Driver Kit   10.0.16292.1001
Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)

Xamarin   4.9.0.752 (0faa808ee)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.58 (cee1369d0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.8.1.28 (3979d08)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Example Project (If Possible)

> VS bug [#660394](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/660394)

**Comment by therealjohn** [comment]
@bigDave1357 I just left a comment about this on #3837 but I realize now it's not too helpful since you can't pair to the Mac. Could you make sure you have an Xcode version at that path it expects so you can pair, then adjust it?

**Comment by bigDave1357** [comment]
I've tried to install Xcode 9.2 alongside Xcode 9.3 to resolve the other problem on #3837 but I seem to be stuck in a loop.

Currently on the Mac I have 9.2 installed at /Applications/Xcode 9.2.app and I have Xcode 9.3 installed in the default /Applications/Xcode.app path

On VS I have an SDK path set for /Applications/Xcode 9.2.app

However, I cannot connect. When I try I get the licence popup. I cannot get past this. The licence has been accepted. I've tried changing the SDK path on the Mac to 9.2 and accepting the licence using command line etc. Nothing seems to work.

Looking at the ide log from with VS I can see that there are errors when trying to check and accept the licence file.

Isn't there a way of just forcing the SDK path back to a different path. I've looked in the register and on files. I cannot find where Visual Studio is storing the path.

At the moment I'm at a complete standstill and unable to work. Any help to resolve this would be very gratefully received.

**Comment by bigDave1357** [comment]
I think I've tracked down the problem to a file name issue.

There's an error in one of the logs on VS complaining that the following cannot be executed

/Applications/Xcode 9.2.app/Contents/Developer/usr/bin/xcodebuild -license check

Copying and pasting this into the terminal on the Mac also results in an error and it's because of the space between Xcode and 9.2

If I instead run '/Applications/Xcode 9.2.app/Contents/Developer/usr/bin/xcodebuild' -license check

then all is well.

There's no point in simply renaming Xcode 9.2.app to Xcode9.2.app since this won't be found by VS and since I cannot ever connect, I cannot use the options panel within VS to change this.

The only solution seems to me to manually change the path within VS.

So where is this stored?

**Comment by therealjohn** [comment]
@bigDave1357 I'm checking with the team to see if there is a place you can manually change that.

**Comment by bigDave1357** [comment]
Further searching has found nothing in the registry and nothing comes up. I've tried looking in appropriate files and can find nothing. I've even tried watching decent.exe using ProcessMonitor to see if I can spot from where it's loading the information.

I'm not getting anywhere. Would have thought it's fairly easy to locate this information and manually change it. I guess it's encoded and stored in binary form somewhere.

Re-installing VS is not something I want to do on a whim and since I cannot know for sure that this would erase the problem setting, I'm not going to do it.

I need to know where this setting is stored.

**Comment by therealjohn** [comment]
I have an open question to the team about this. Unfortunately, all of them are on holiday today so the knowledge about this that I have access to is limited. I'll continue to look and ask around and comment here when I figure it out.

**Comment by bigDave1357** [comment]
Thanks for your efforts. Just my luck that everyone needed is on holiday. I was planning to work on Xamarin projects today and this weekend, but seems that's just going to be four days of lost time until the holiday is over.

There are presumably two bugs here. Firstly, that one cannot change the SDK settings in the Options dialog box in VS2017 unless you are connected..... if you cannot connect because the settings are wrong,  you're stuck, as am I.

Secondly, the passing of the commands to the Mac via the ssh command runner should be sent using appropriate ' ' demarcation so that any spaces in paths are handled properly.

**Comment by bigDave1357** [comment]
Uninstalling and re-installing is a big task and there's no guarantee that this will fix anything at all.

If the settings are stored in a file that persists after uninstall and is not overwritten when a new install occurs, then all of that effort will have been wasted.

**Comment by therealjohn** [comment]
Very true. There is someone checking on this so standby.

**Comment by bigDave1357** [comment]
Trying to think laterally....

One of the bugs is that spaces in files names are not handled well. The connection tool is trying to execute the following:

/Applications/Xcode 9.2.app/Contents/Developer/usr/bin/xcodebuild -license check

but this is being interpreted by the shell as an attempt to run:

/Applications/Xcode

and pass arguments:

9.2.app/Contents/Developer/usr/bin/xcodebuild -licence check

So I had an idea - simple really - don't know why I didn't think of it before. Create a simple little executable called Xcode, placed in the Applications directory, which simply returns 0. Simple as in:

int main(void)
{ 
        return 0;
}

Compiling this as Xcode and copying to the failed path means that at least the dodgy command won't fail with an error. Hopefully this will trick the connection tool.

Voila - it works. The connection tool now connects. I'm now able to use the Options dialog box to change the path back to safety - the default path for now - and I've verified that I can connect once again.

I can now remove the hack and go back to trying to get my environment building again as per the problems with #3837 

These two bugs are nasty and others will get stuck, particularly when Xcode releases break things before you guys have had time to sort out compatibility.

So, please raise the following bugs:

1. Users are unable to change SDK setting for iOS unless connected, which is impossible if the reason the user cannot connect is because of the SDK setting. There is no reason to keep the settings disabled until a connection has been made.

2. Commands being passed to the build host do not cope well with spaces in file names. It may be just the two commands that check and attempt to sign the licence remotely. But if a filename with a path is entered into the SDK path, connections will then fail. The user is then trapped by 1 above in an endless cycle.

**Comment by therealjohn** [comment]
@bigDave1357 Clever workaround!

I logged both issues for investigation. They are not related to Xamarin.iOS so they will not appear here. Instead, they are filed in our internal tracker for the Visual Studio Tools for Xamarin.

**Comment by cullenjohnson** [comment]
I was having this issue as well, so I found a different workaround. My workaround was to rename "Xcode 9.2.app" to "Xcode9.2.app" in the Applications folder and then create 2 symbolic links on the Mac:

    ln -s "/Applications/Xcode9.2.app" "/Applications/Xcode"
    ln -s "/Applications/Xcode9.2.app" "/Applications/Xcode 9.2.app"

Voila, now you can edit your Xcode path again. I changed it to "/Applications/Xcode9.2.app" and deleted the symbolic link. Then I restarted VS because of course I did.

Normally I wouldn't expect to have to deal with something like failure to recognize paths with spaces, but this is Xamarin we're talking about here... (Sorry, I'm just kind of peeved that a couple hours of my development time had to be wasted working around yet another Xamarin bug.) ಠ_ಠ
