### ISSUE TITLE
Reference assembly for OpenTK on Xamarin.Mac Full has invalid references

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3844]
# The reference assembly has bad references. We do not ship OpenTK
```
$ monop -r:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/reference/full/OpenTK.dll --refs
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Xamarin.Mac, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

# Not a sym-link
```
$ ls -la /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/reference/full/OpenTK.dll
-rwxr-xr-x  1 donblas  staff  715776 Mar 30 12:22 /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/reference/full/OpenTK.dll
```

# Vs the real assembly
```
$ monop -r:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/4.5/OpenTK.dll --refs
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Xamarin.Mac, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
```

**Comment by VincentDondain** [comment]
We have some QA tests failing on this: see [release pipeline](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=259839&environmentId=1133849&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension) and [gist](http://xqa.blob.core.windows.net/gist/report-806c90dc4476436fa3d2f88132eacf39.txt) of actual error.

To reproduce this locally download https://developer.xamarin.com/samples/mac/GLSLShader and try to build for the XM full profile (double click on the project > Build > General > select Xamarin.Mac Full)

**Comment by VincentDondain** [comment]
Reminder when this is fixed we will need to re-enable QA tests. See https://github.com/xamarin/QualityAssurance/pull/2983

**Comment by chamons** [comment]
This appears to have been fixed in the last year by some unknown PR.

`$ monop -r:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/reference/full/OpenTK.dll --refs`
```
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Xamarin.Mac, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
```
`$ monop -r:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/4.5/OpenTK.dll --refs`
```
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Xamarin.Mac, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
```
