### ISSUE TITLE
Critical : cannot test on IOS device

### ISSUE THREAD

**Issue by ormaa** [xamarin/xamarin-macios#3848]
### Steps to Reproduce

Create a xamarin.forms application.
Compile, select IOS project, IOS device.
click run

Obtain this error : 
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch -sdkroot "/Applications/Xcode.app/Contents/Developer" --installdev "/Users/olivier/Downloads/XamarinRSSFeed-master/iOS/bin/iPhone/Debug/device-builds/iphone6.2-11.3/RSSReader.iOS.app" --device ios "--devname=Iphone 5S ormaa" --install-progress
error HE0003: Could not load the framework 'DADocSetAccess' (path: /Applications/Xcode.app/Contents/SharedFrameworks/DADocSetAccess.framework/DADocSetAccess): not found.

Application could not be uploaded to the device and cannot be tested on device.
application can be tested on simulator

### Expected Behavior
Application can be executed on IOS device.

### Actual Behavior
Application cannot be tested on IOS device

### Environment
MacOS high Sierra 10.13.3
iphone X with IOS 11.2.6
iphone 5S with IOS 11.3
visual studio community , Mac,  version 7.4.1 build 48
nuget packages updated.

swifty 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
xcode 9.3 - 9E145

Please note that xcode is working fine, as daily tool : 
I develop mainly on native application for IOS devices.

I believe that it is coming from swift 4.1 / xcode 9.3 ?

thanks
Olivier

**Comment by rolfbjarne** [comment]
Our stable version of Xamarin.iOS does not support Xcode 9.3 yet, but the versions in the Alpha/Beta channels do.

This means you can:

* Install Xamarin.iOS from the alpha/beta channel.
* Downgrade to (or install separately) Xcode 9.2
* Wait until we release support for Xcode 9.3 in our stable channel (if everything goes as planned this will hopefully be today, but no promises).

**Comment by brendanzagaeski** [comment]
A small correction:

- **Compatible with Xcode 9.3**: Visual Studio for Mac **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update), Xamarin.iOS version 11.9.1.24 as published earlier today.
- **Not compatible with Xcode 9.3**: Visual Studio for Mac **Beta** & **Alpha** [updater channels](https://docs.microsoft.com/visualstudio/mac/update), Xamarin.iOS version 11.10.0.32.

**Duplicate Report**: <https://github.com/xamarin/xamarin-macios/issues/3837>.  See that report for a few additional verification details about Xamarin.iOS version 11.9.1.24.

**Comment by javakian** [comment]
runs on Simulator not Device

I built an app in Xamarin directly to the simulator then tried to run it on my device.  I provisioned the app and selected automatic provisioning and selected the team and the software said “Ready to reply app to connected device”. Selected the iPhone device up top and built the app the error 

“Application could not be uploaded to the device”

Also had the error  “IncorrectArchitecture: Failed to find matching arch for 64-bit Mach-O input file”. And “error MT1006: Could not install the application”
