### ISSUE TITLE
TouchBarExample not showing touchbar in Stable/master

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3849]
### Steps to Reproduce

1. https://github.com/xamarin/mac-samples/tree/master/TouchBarExample/TouchBarExample
2. Run sample

### Expected Behavior

No touchbars.

### Actual Behavior

 It used to show them.

### Environment
Stable or Master

**Comment by spouliot** [comment]
@chamons let's file sample issues in their own repos, not the SDK

**Comment by chamons** [comment]
I filed it here because I expect that it's more than a sample issue, but you are correct, I jumped the gun.

**Comment by spouliot** [comment]
It's fine if it's not sample related (was not clear) and why I did not close or move it :)
