### ISSUE TITLE
Missing App Store Icon - WatchOS Apps

### ISSUE THREAD

**Issue by codethena** [xamarin/xamarin-macios#3860]
### Steps to Reproduce

1. Create an iOS app that has a watch app
2. In WatchApp info.Plist set App Icons to AppIcon (Assets.Xcassets)
3. Add image for AppStore (1024pt)
4. Upload to AppStore

### Expected Behavior
Image is used for AppStore Image like iOS app does
### Actual Behavior
Get an email from Apple:

Missing App Store Icon - WatchOS Apps must include a 1024x1024px App Store Icon in PNG format. Without providing the icon in the Asset Catalog or via iTunes Connect, apps cannot be submitted for App Review or Beta App Review. Refer to https://developer.apple.com/watchos/human-interface-guidelines/icons-and-images/home-screen-icons/ for more information.

### Environment

```
Visual Studio Professional 2017 for Mac
Version 7.4.1 (build 48)
Installation UUID: 1830e166-eb0a-4f6b-a4f0-f2f640f2dd75
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.Mac
Version: 4.2.1.28 (Visual Studio Professional)

Xamarin.iOS
Version: 11.8.1.28 (Visual Studio Professional)
Hash: 3979d081
Branch: d15-6
Build date: 2018-03-09 16:22:34-0500

Xamarin.Android
Version: 8.2.0.16 (Visual Studio Professional)
Android SDK: /Users/aj/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 704010048
Git revision: 6a86203dd590c6cfdf814c8832d24d2ad1e2606f
Build date: 2018-03-20 11:16:55-04
Xamarin addins: 8d83cea9e4ae03cb0c14ba3fbaafdbb0cbd170e7
Build lane: monodevelop-lion-d15-6

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.1

```

**Comment by VincentDondain** [comment]
Hi, could you please also include your full build logs?

In Visual Studio for Mac, to get full build logs just set the log verbosity to diagnostic at the following location: `Preferences > Projects > Build`.

_Note: ideally a small test case that showcases the submission issue would help us investigate you project to try to understand what's happening._

**Comment by dalexsoto** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
