### ISSUE TITLE
Missing ARHitTestResultType.EstimatedVerticalPlane binding for ARKit 1.5

### ISSUE THREAD

**Issue by ggammon** [xamarin/xamarin-macios#3870]
It looks like ARHitTestResult.ExistingPlaneUsingGeometry was picked up but EstimatedVerticalPlane wasn't.

https://developer.apple.com/documentation/arkit/arhittestresult.resulttype/2887455-estimatedverticalplane

**Comment by VincentDondain** [comment]
You are right we somehow missed that binding. Will investigate why...

Thanks for letting us know!
