### ISSUE TITLE
Models are registered using the name of the corresponding protocol

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#3875]
Given the following api description:

```csharp
[Protocol, Model]
[BaseType (typeof(NSObject))]
interface MTLCaptureScope
{
}
```

we generate:

```csharp
[Protocol()]
[Register("MTLCaptureScope", false)]
[Model]
public unsafe abstract partial class MTLCaptureScope : NSObject, IMTLCaptureScope {
}
```

this becomes a problem, because we're effectively declaring an Objective-C type with a name (`MTLCaptureScope`) that might conflict with another platform type.

And that's exactly what happens (https://github.com/mono/monodevelop/issues/4425):

```
objc[88046]: Class MTLCaptureScope is implemented in both /System/Library/Frameworks/Metal.framework/Versions/A/Metal (0x7fff9384e1d0) and /Users/mikayla/code/monodevelop/main/build/bin/MonoDevelop (0x10967c6a0). One of the two will be used. Which one is undefined.
```

This is not a problem unless Apple defines an Objective-C class with the same name as the protocol, but it does sometimes happen.

Another variation of the same problem is if two different binding projects bind the same protocol (issue #3832).

This became worse after 9c2010e44012387803af8bbd460910d28bba0586, because then we started registering these types in the static registrar (previously we wouldn't register types that were also models in the static registrar). This change was implemented to match the dynamic registrar (which did try to register these types, but instead of blindly registering the type, the dynamic registrar would first check if the Objective-C type already existed, and if it did, use the existing Objective-C type. This would obviously have led to quite random and inexplicable behavior if managed code suddenly started wrapping a different Objective-C class than expected (like in the `MTLCaptureScope` case from above)).

Solutions:

1. Change the generator to generate a unique Objective-C name for the model:

```csharp
[Protocol()]
[Register("Xamarin_iOS__MTLCaptureScope", false)]
[Model]
public unsafe abstract partial class MTLCaptureScope : NSObject, IMTLCaptureScope {
}
```

* Con: it would require third-party binding libraries that run into issue #3832 to be rebuilt.

2. Revert 9c2010e44012387803af8bbd460910d28bba0586, and addition fix the dynamic registrar to behave like the static registrar (don't try to register models).

* Con: I'm not even sure this would work (presumably there was a reason models were registered in the first place, but it might just as well have been an oversight too)
* Con: Even if it works in simple cases, it feels like something that might run into unexpected consequences at some point.

> VS bug [#595223](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/595223), VS bug [#595224](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/595224)

**Comment by spouliot** [comment]
A variation of 1 would be to change binding (not the generator) to register a different name for the model. Ideally we can test (I'm fairly sure, without the static registrar at least) that we do not ship conflictual types.

For 3rd parties we can document this case (in the error message, maybe in the bindings too) and have them rebuilt the binaries. It's not the only place where unique names **must** be used.

**Comment by rolfbjarne** [comment]
> A variation of 1 would be to change binding (not the generator) to register a different name for the model.

How would that look like? The name in the api definition must match the name of the protocol, and that's what the generator puts in the [Register] attribute.

> Ideally we can test (I'm fairly sure, without the static registrar at least) that we do not ship conflictual types.

We can test that none of our bound models conflict with any platform types _today_, but Apple might release new OS versions in the future which may add new types.

**Comment by spouliot** [comment]
Yeah, we do end up needing some/different changes in the generator. As for the future types this is an issue not limited to models.

Changing every model _registered_ name can break code that _reflect_ them directly (user code) or indirectly (serialization / NSCoding). Thankfully it's less common than in .net

**Comment by spouliot** [comment]
from #3879 

> Question: should we provide a way in the generator to produce the old code?

I guess you reached the same conclusion :)

To be effective (it's a breaking change) it should be per-type (model), which is why I mentioned tests.

**Comment by dalexsoto** [comment]
I'll speak my mind here first, I really think that `[Model]`'s are an evil that we inherited because we did not have proper protocol support back in the day as we now have today and that they should be eliminated at some point from our public API, maybe when C# language supports [default interface methods](https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md) at some point we can revisit this idea, I really think they bring nothing but pain like retain cycles more easily if not used with caution and if you really want them, you can easily implement them yourself. 

> I can add a Name property to the Model attribute

I think this is the right solution to have, so we can give control over the unmanaged name generated just like we do for everything else (BaseType and Protocol).

**Comment by rolfbjarne** [comment]
@spouliot so I implemented something slightly different: the Model attribute now has two more properties: `Name` and `AutoGeneratedName`.

If none are set, the behavior from today doesn't change.
If `Name` is set, that's the name we'll use.
If `AutoGeneratedName` is set, we'll generate something we think is unique (currently assembly name + type full name).

The `AutoGeneratedName` property is helpful when you need a unique name and the source code is shared between multiple assemblies (case in point: that's what I ended up using in our own source code, since we create multiple assemblies from the same source code).

I'm not very fond of the name though (`AutoGeneratedName`), so suggestions welcome :smile:

**Comment by spouliot** [comment]
backport merged
