### ISSUE TITLE
Can't put application on Device with XCode 9.3

### ISSUE THREAD

**Issue by Rogister** [xamarin/xamarin-macios#3878]
### Steps to Reproduce

Since the last stable version of Visual Studio for XCode 9.3, I can not put my application on the device anymore.

I send you my log and the information.

it works correctly on the simulator.

Alain
[Log.txt](https://github.com/xamarin/xamarin-macios/files/1879870/Log.txt)

=== Visual Studio Community 2017 for Mac ===

Version 7.4.2 (build 12)
Installation UUID: af98516b-7b3c-413e-ba1b-95a1baeaccc6
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version : 4.3.1.4445

=== .NET Core ===

Runtime : /usr/local/share/dotnet/dotnet
Versions du runtime :
	2.0.5
	2.0.0
SDK : /usr/local/share/dotnet/sdk/2.1.4/Sdks
Versions du SDK :
	2.1.4
	2.0.0
SDK MSBuild : /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version : 1.6.1
Emplacement : /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Community)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Xamarin.Android ===

Version : 8.2.0.16 (Visual Studio Community)
Android SDK: /Users/macbookrogister/Library/Developer/Xamarin/android-sdk-macosx
	Versions Android prises en charge :
		6.0(Niveau d’API 23)
		7.1(Niveau d’API 25)

Version des outils du SDK : 25.2.5
Version des outils de plateforme du SDK : 25.0.5
Version des outils de génération du SDK : 25.0.1

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Code EPL d'Android Designer disponible ici :
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704020012
Git revision: 0d8e3f0a4d683771f17959739956fa09c7ba21e3
Build date: 2018-03-30 10:45:17-04
Xamarin addins: 958839ea56ab1e331caf7c92b6ad50fb9e6ee9d2
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

### Environment

```
```

**Comment by VincentDondain** [comment]
Bonjour,

```
Target "_CodesignAppBundle" in file "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets":
  Building target "_CodesignAppBundle" completely.
  Input file "bin/Release/MedinectIPad.app/.monotouch-32/Xamarin.iOS.aotdata.armv7" is newer than output file "bin/Release/MedinectIPad.app/_CodeSignature/CodeResources".
  Using "Codesign" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Tasks.dll".
  Task "Codesign"
    Tool /usr/bin/codesign execution started with arguments: -v --force --sign 07059D234C869E5165B7214B4C0A5C171E6ED689 --entitlements /Users/macbookrogister/Projects/MedinectIOSMACOS/MedinectIOS/obj/iPhone/Release/Entitlements.xcent /Users/macbookrogister/Projects/MedinectIOSMACOS/MedinectIOS/bin/Release/MedinectIPad.app
    Tool /usr/bin/codesign execution finished (exit code = 1).
    bin/Release/MedinectIPad.app : error : /Users/macbookrogister/Projects/MedinectIOSMACOS/MedinectIOS/bin/Release/MedinectIPad.app: unknown error -1=ffffffffffffffff
  Done executing task "Codesign" -- FAILED.
Done building target "_CodesignAppBundle" in project "MedinectIOS.csproj" -- FAILED.
```

`unknown error -1=ffffffffffffffff` can mean a bit anything for code sign and it's not necessarily an issue with Xamarin (: I can deploy on device with the same versions of the product you are using.

Couple of questions for you:

- Did you do a full clean (rebuild) of the solution? You build log doesn't indicated that. Maybe even try to manually remove the `bin/` and `ob/` (though that's what clean should do).
- Did you start Xcode after updating it, so it installs the command line tool?
- Can you deploy on device with a brand new iOS project?
- Can you deploy on device with a new native Xcode project?
- Here are 2 bugs that were solved by users who experienced the same issue after and update: https://bugzilla.xamarin.com/show_bug.cgi?id=59998 and https://bugzilla.xamarin.com/show_bug.cgi?id=60931

If none of that work for you maybe try to send us either your project or a similar test case that showcases the issue and we'll investigate further (;

Cordialement,

Vincent.

**Comment by VincentDondain** [comment]
Also a potential solution in https://stackoverflow.com/questions/44173831/codesign-returned-unknown-error-1-ffffffffffffffff?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa.

**Comment by Rogister** [comment]
I did not install the lines tools commands after XCode update. I did that afterwards, I deleted the Obj and Bin directories. Recompile everything and now everything is OK.

Thank you

Alain

De : Vincent Dondain <notifications@github.com>
Répondre à : xamarin/xamarin-macios <reply@reply.github.com>
Date : jeudi 5 avril 2018 à 16:58
À : xamarin/xamarin-macios <xamarin-macios@noreply.github.com>
Cc : Rogister Alain <alain.rogister@appl.be>, Author <author@noreply.github.com>
Objet : Re: [xamarin/xamarin-macios] Can't put application on Device with XCode 9.3 (#3878)


Bonjour,

Target "_CodesignAppBundle" in file "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets":

  Building target "_CodesignAppBundle" completely.

  Input file "bin/Release/MedinectIPad.app/.monotouch-32/Xamarin.iOS.aotdata.armv7" is newer than output file "bin/Release/MedinectIPad.app/_CodeSignature/CodeResources".

  Using "Codesign" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Tasks.dll".

  Task "Codesign"

    Tool /usr/bin/codesign execution started with arguments: -v --force --sign 07059D234C869E5165B7214B4C0A5C171E6ED689 --entitlements /Users/macbookrogister/Projects/MedinectIOSMACOS/MedinectIOS/obj/iPhone/Release/Entitlements.xcent /Users/macbookrogister/Projects/MedinectIOSMACOS/MedinectIOS/bin/Release/MedinectIPad.app

    Tool /usr/bin/codesign execution finished (exit code = 1).

    bin/Release/MedinectIPad.app : error : /Users/macbookrogister/Projects/MedinectIOSMACOS/MedinectIOS/bin/Release/MedinectIPad.app: unknown error -1=ffffffffffffffff

  Done executing task "Codesign" -- FAILED.

Done building target "_CodesignAppBundle" in project "MedinectIOS.csproj" -- FAILED.

unknown error -1=ffffffffffffffff can mean a bit anything for code sign and it's not necessarily an issue with Xamarin (: I can deploy on device with the same versions of the product you are using.

Couple of questions for you:

  *   Did you do a full clean (rebuild) of the solution? You build log doesn't indicated that. Maybe even try to manually remove the bin/ and ob/ (though that's what clean should do).
  *   Did you start Xcode after updating it, so it installs the command line tool?
  *   Can you deploy on device with a brand new iOS project?
  *   Can you deploy on device with a new native Xcode project?
  *   Here are 2 bugs that were solved by users who experienced the same issue after and update: https://bugzilla.xamarin.com/show_bug.cgi?id=59998 and https://bugzilla.xamarin.com/show_bug.cgi?id=60931

If none of that work for you maybe try to send us either your project or a similar test case that showcases the issue and we'll investigate further (;

Cordialement,

Vincent.

**Comment by spouliot** [comment]
Sadly updating Xcode is not always enough (it varies per versions) and the IDE might need to be started to complete other updates (like the command line, device support...).

>     bin/Release/MedinectIPad.app : error : /Users/macbookrogister/Projects/MedinectIOSMACOS/MedinectIOS/bin/Release/MedinectIPad.app: unknown error -1=ffffffffffffffff

@VincentDondain can we detect this and issue an `MT8xxx` error instead ? that way people that double-click on the error will get to a web page where we can list something like "If you recently update Xcode then you might need to start it manually to complete the upgrade" to a list of potential workarounds.

**Comment by VincentDondain** [comment]
Let me close this issue as you managed to solve it by installing the command line tool.

_Note: I opened an issue to discuss possibilities of us detecting if the command line tools for a newer Xcode have been installed. https://github.com/xamarin/xamarin-macios/issues/3908_
