### ISSUE TITLE
Error retrieving update information while updating Xamarin update channel (stable) on Mac

### ISSUE THREAD

**Issue by SaravananWipro** [xamarin/xamarin-macios#3880]
### Steps to Reproduce
We are always getting below issue while updating Xamarin update channel (stable) on Mac.

**"Error retrieving update information"**

Currently xamarin does not provide direct link as earlier, then how can we download or update if we get this issue always.

Please provide direct link access for Xamarin.iOS, Xamarin VisualStudio plugins 2015...

### Expected Behavior
Direct link to download stable channel
### Actual Behavior
Error retrieving update information
### Environment

```
```

**Comment by VincentDondain** [comment]
Hi,

This is not an issue with Xamarin.iOS (SDK) but maybe with the **updater / IDE**.

I'm not quite sure if you're on Windows or Mac but please report a new issue directly within the IDE

- Mac: use Help > Report a Problem to file your issue.
- Windows: use Help > Send Feedback > Report a Problem to file your issue.

_Note: in any case for an error like this we will more information from you to investigate. IDE logs, full error, version informations._
