### ISSUE TITLE
Xamarin Forms crash in IOS project do not stop at exception line - do not display full exception trace

### ISSUE THREAD

**Issue by jassmith** [xamarin/xamarin-macios#3893]
_From @olivier38070 on April 4, 2018 9:16_

### Description
When I debug an IOS project on a Xamarin Forms solution, when there is exception, 
the debugger do not stop at exception line
the debugger do not display complete exception message
exception message exist : I can copy the text on the popup and paste it in text editor.

The option in Run, New Exception catch-point  + Pause the program + When an exception is thrown are selected.

### Steps to Reproduce

Create a Xamarin forms application
in the xaml page, add a listview, with image and label.
in code behind, load image with RSS feed images
run the IOS project on ios device
scroll the listview
app will crash : see screen shot

for code, please do not hesitate to check my github solution 
note : it is a work in progress, just for me to validate the stability of xamarin tools before working on it on production projects.

https://github.com/ormaa/RSS-Reader_IOS-Android

### Expected Behavior
The app should stop where the exception occurred
the exception popup should display the message and stack trace

### Actual Behavior
the app stop in main.cs
the popup do not display any message, but a hort part of the message. no stack trace.

### Basic Information

Version with issue: visual studio community 7.4.2 build 12
Last known good version: none
MACOS High sierra 10.13.3
Xcode 9.3, swift 4.1

I obtain the same error when I run app on IOS simulator, or IOS device iphone 5S IOS 11.3

### Screenshots
![screen shot 2018-04-04 at 11 01 35](https://user-images.githubusercontent.com/8026564/38298735-7bb40dbc-37f8-11e8-8126-e21bb8d2dc3c.png)

<img width="1547" alt="screen shot 2018-04-04 at 11 08 29" src="https://user-images.githubusercontent.com/8026564/38298758-8e69e9f4-37f8-11e8-9888-0a57643b84e4.png">

_Copied from original issue: xamarin/Xamarin.Forms#2242_

**Comment by VincentDondain** [comment]
@olivier38070 I tried reproducing the issue using your test case (https://github.com/ormaa/RSS-Reader_IOS-Android) with the following environment https://gist.github.com/VincentDondain/88a1eed73a395d08fcaacfd4dddde0e6 but I do not get any exception, the app does not crash for me.

Is the exception raised every time? I just tried to run the app on my iPhone X (Debug mode) and scroll the list, is that correct? Do I need to use a specific branch?

**Comment by mandel-macaque** [comment]
@olivier38070 sorry, can you let me know if that means that the bug does not longer happen?

**Comment by olivier38070** [comment]
I don’t know, I don’t have tested anymore that issue. I worked on another
project, and cannot test it now.

2018-05-23 14:53 GMT+02:00 Manuel de la Pena <notifications@github.com>:

**Comment by therealjohn** [comment]
I tried to reproduce this with a commit from around the time it was originally reported in the Xamarin.Forms repo. Unfortunately, it does not reproduce the error so I can't see the behavior described above. 

@olivier38070 If you can provide a link to a commit for the project that reproduces the issue, please reopen the issue. Thanks!

**Comment by alicint** [comment]
same problem here

**Comment by voxoid0** [comment]
same problem here. For example, in my current case I have a System.NullReferenceException, but debugger does not stop when it is thrown, and this results in an "Unhandled exception" with a native iOS stacktrace in the Debug Output.
