### ISSUE TITLE
Debugger doesn't connect to keyboard extension on any device

### ISSUE THREAD

**Issue by zengable** [xamarin/xamarin-macios#3896]
### Steps to Reproduce

1.  create a keyboard extension
2. add a breakpoint anywhere in the keyboard ext.
3. set the keyboard extension as the project to be run, build and start
4. you'll see the popup after the app is installed on the device to manually start the extension
5. go to keyboard settings on iOS settings app, add your keyboard ext. to the list of keyboards 

### Expected Behavior
Debugging should be possible, the IDE popup asking you to start the extension should disappear after doing so

### Actual Behavior
The VS IDE doesn't detect the keyboard extension start, debug breakpoints don't work at all on the device. After several attempts, the keyboard ext. doesn't even start anymore

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.4.2 (build 12)
Installation UUID: 4c89704f-df6f-403f-b4dd-a7956d6da813
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Community)
Android SDK: /Users/gable/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.28 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Community)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Build Information ===

Release ID: 704020012
Git revision: 0d8e3f0a4d683771f17959739956fa09c7ba21e3
Build date: 2018-03-30 10:45:17-04
Xamarin addins: 958839ea56ab1e331caf7c92b6ad50fb9e6ee9d2
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

```

> VS bug [#596581](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/596581), VS bug [#710185](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/710185)

**Comment by VincentDondain** [comment]
@jstedfast I could confirm this issue locally with the same environment specified above. I can debug other app extensions but not the custom keyboard one. Can you take a look?

**Comment by zengable** [comment]
Ok so the thing is, this used to work properly in Xamarin Studio. If you enable Full Access for the keyboard extension, debugging starts working afterwards. However, there are some deep issues with the keyboard extension in Xamarin. 

I'll give you an example. If I check whether the extension has full access or not, the extension becomes non-responsive. There are a couple ways to check for full access, the most commonly referred way is to paste a string to UIPasteboard.General and see whether it fails or not. If there is no Full Access granted, the write operation will fail, and the keyboard becomes non-responsive. Placing the UIPasteboard.General write operation in a try / catch block does not help at all, no exception is caught.

**Comment by jstedfast** [comment]
Can someone provide me with a sample test case? I also need instructions on how to test this because I cannot for the life of me figure out how to get to a custom keyboard. It would also be nice if someone could provide me with instructions on how to "enable Full Access"? Right now, I have no idea what this all entails.

Thanks.

**Comment by jstedfast** [comment]
I figured out how to get the custom keyboard to display now (I had enabled it in the Settings app, but I guess it must have gotten unset somehow).

Still don't know what "Full Access" means or what I need to change to set that.

**Comment by VincentDondain** [comment]
Full access is network access. I believe you want `RequestsOpenAccess` set to true in the plist.

https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/CustomKeyboard.html

**Comment by zengable** [comment]
1. to be able to see your own custom keyboard extension, you need to turn it on in the Settings app.
2. to have Full Access (network access, etc), you'll need to enable this specifically after enabling your custom keyboard in the Settings app, then tapping on it for further details, then switch on Full Access.
