### ISSUE TITLE
code sign failed because of  bundle format unrecognized, invalid, or unsuitable codesign exited with code 1

### ISSUE THREAD

**Issue by suihanhbr** [xamarin/xamarin-macios#3901]
### Steps to Reproduce
I have a Xamarin.Form project :
![2018-04-09 7 01 47](https://user-images.githubusercontent.com/17265184/38494469-9bd8d832-3c28-11e8-97a1-dc968b4a3cb7.png)

IOSLib and SuiHanLib is the Library wrote by myself .
ThreeDiretion is Xamarin.Form project;
ThreeDiretion.iOS is Xamarin.iOS project;
ThreeDiretionKeyboard is the iOS KeyBoard Extension   project;

At first , only the ThreeDiretionKeyboard project reference to the IOSLib and the SuiHanLib , and it is fine to run , build and archive ,but fail to sign and distrubute. 

I try every way I can find on internet , but they don't work.

finally , I find the solution for this problem. add the reference of the IOSLib and SuiHanLib  to the ThreeDiretion.iOS ,and implement a class to extend anyone class of the IOSLib or SuiHanLib. It will be fine to code sign and everything is OK finally.

I guess maybe the iOS project has different version Xamarin.Sdk.framework with Extension project because of the IOSLib and SuihanLib.

### Environment

```
=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.5 Preview (7.5 build 1062)
Installation UUID: 4e60959a-758f-48ce-ae6d-26e15276ea83
Runtime:
	Mono 5.10.1.16 (2017-12/bf27e254466) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010016

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.4.0.49 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.10.0.50 (Visual Studio Community)
Hash: eb1d7875
Branch: d15-7
Build date: 2018-03-27 23:00:22-0400

=== Xamarin.Android ===

Version: 8.3.0.11 (Visual Studio Community)
Android SDK: /Users/huangboru/myfile/sdk
	Supported Android versions:
		4.4 (API level 19)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705001062
Git revision: 32772489b127be63513c6dffadfa3fff6cb50fad
Build date: 2018-04-05 17:39:38-04
Xamarin addins: e6f615e8ca223dec35e842888a642e5db883abef
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1


```

### Build Logs
Begining distribution, 2018/4/8 12:17:28
Channel: App Store
App Bundle Id: com.suihan.td, Version: 1.0.4
codesign -v -f -s "75BCAB46B9A6F6DDAE4CC293A6086F5C610749AB" "/var/folders/qc/5pggkbx565z7__bvx4fz6gsh0000gn/T/mdTmpDir1132857770/Payload/ThreeDiretion.iOS.app/PlugIns/ThreeDiretionKeyBoard.appex/Frameworks/Xamarin.Sdk.framework"
/var/folders/qc/5pggkbx565z7__bvx4fz6gsh0000gn/T/mdTmpDir1132857770/Payload/ThreeDiretion.iOS.app/PlugIns/ThreeDiretionKeyBoard.appex/Frameworks/Xamarin.Sdk.framework: bundle format unrecognized, invalid, or unsuitable
codesign exited with code 1
ERROR:Code signing failed.
Finshed

**Comment by dalexsoto** [comment]
Hello, thanks for contacting us!

From the provided information is not completely clear how to reproduce the issue you are experiencing, could you create a small test case so we can reproduce the issue? This will reduce guesswork and will be way easier to provide a faster solution. In case you are unable to provide one, could you please list the detailed steps needed to get into this error state?

Thanks!

**Comment by VincentDondain** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
