### ISSUE TITLE
[RFC] Ideas for html report / test reporting

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#3909]
The html report (and in general how we report test results) can always be improved.

This is a meta issue to capture ideas for major (and minor!) improvements. Some of these ideas are major ideas by themselves, and may be split into separate issues.

Some ideas I know about (from https://github.com/xamarin/xamarin-macios/issues/3904#issuecomment-379853610)

* [ ] Make it easier to identify known, random test failures so that such builds can be green'ified, and maybe automate this some day [#3910].
* [ ] Automatically retry test runs in selected scenarios. Any retries should be clearly reflected in the html report.
* [ ] Add instructions how to duplicate any issues (and whenever possible, how to run a subset of the test(s), since some can take quite a while).
* [ ] Separate results for XI and XM. One can be green while the other is not.

**Comment by spouliot** [comment]
As part of the changes we need better ways to monitor results. 

In particular we'll _lose_ wrench table view which was helpful to see the last commit were a test was successful.

**Comment by rolfbjarne** [comment]
This is quite outdated now, so closing.
