### ISSUE TITLE
Add support for Mac.Bindings projects on Windows

### ISSUE THREAD

**Issue by joj** [xamarin/xamarin-macios#3912]
Library authors need to be able to build all the platforms in a single build (or a CI build). At the moment this is not possible because Mac is missing UWP support, and Windows is missing Mac.Bindings support. The shortest way to get there is to add support for Mac.Bindings on Windows.

At the moment it is unclear if this support will be full (like iOS) or build (like Mac). That will be decided based on effort. Full support will require a Windows computer connected to a Mac (like iOS does).

This is an enhancement and ongoing. More information will be added here when available, and also commits will be linked when they happen on the open source repo.

> VS bug [#597758](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597758)

**Comment by emaf** [comment]
We've added offline build support (like Mac) for Mac Binding projects and it will be part of VS 15.8 release.
