### ISSUE TITLE
Xamarin.Mac does not honor AOT options from IDE

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3920]
@mykyta-bondarenko-gl Found a bug yesterday that was fixed in master as:

https://github.com/xamarin/xamarin-macios/commit/659a74cc369395958b9c00d107281ef94873d57d

but was fixed before the issue was actually filed. This is an after-the-fact issue for it, since it needs to be cherry picked to 15.7.

Xamarin.Mac currently accepts "mmp arguments" of "--aot=all|hybrid" in projects and AOTs, but if the project uses the IDE settings and generates project tags of AOTMode / HybridAOT they are ignored.

### Steps to Reproduce

1. Create a new XM Project.
2. Enable AOT using the Mac Build pane.
3. Build - No AOT :(

### Expected Behavior

The two option paths to work identically.

### Environment

master / stable both have issue.

> VS bug [#598586](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/598586)

**Comment by spouliot** [comment]
Shipped with P5
https://releases.xamarin.com/15-7-preview-5/
