### ISSUE TITLE
Typo in targets-file

### ISSUE THREAD

**Issue by taori** [xamarin/xamarin-macios#3922]
https://github.com/xamarin/xamarin-macios/blob/bb79afdfb756a4a9c06a758720def8e30a0ef71e/msbuild/Xamarin.iOS.Tasks.Core/Xamarin.iOS.Common.targets#L224

at least it looks like a typo.

**Comment by dalexsoto** [comment]
@jstedfast / @VincentDondain FYI ^

**Comment by dalexsoto** [comment]
@taori thanks a lot for your report!

@jstedfast / @VincentDondain FYI ^

**Comment by spouliot** [comment]
The fix was merged
