### ISSUE TITLE
[msbuild/tests] Add the equivalent of Xamarin.iOS.Tasks.Tests for Xamarin.Mac

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#3926]
We should have a way to test **individual** XM msbuild tasks.

The first good example that comes to mind, and reason for this request, is to have the XM equivalent of https://github.com/xamarin/xamarin-macios/blob/master/msbuild/tests/Xamarin.iOS.Tasks.Tests/TaskTests/MTouchTaskTests.cs to test MMP.

This test checks that we construct the `mtouch` command line properly and is useful to test response files.

**Comment by rolfbjarne** [comment]
This is will automatically be done when we unify the Xamarin.iOS.Tasks.dll and Xamarin.Mac.Tasks.dll assemblies.
