### ISSUE TITLE
[XM] XM.Full - 'HttpWebRequest' does not contain a constructor that takes 1 arguments

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#3953]
The [HttpClient sample ](https://github.com/xamarin/mac-samples/tree/master/HttpClient) is failed to build in XM.Full mode. Everything is ok in XM.Modern mode

### Steps to Reproduce

1.  Download the [sample](https://github.com/xamarin/mac-samples/tree/master/HttpClient)
2.  Switch to the using of XM.Full Framework
3.  Build

### Expected Behavior
Build successfully.

### Actual Behavior
Build is failed.
```
Error CS1729: 'HttpWebRequest' does not contain a constructor that takes 1 arguments (CS1729) 
```

### Environment

1. VSfM. Also it was checked with XM: `15.5 (4.0.0.216)` and `15.3 (3.6.3.3)`
https://gist.github.com/mykyta-bondarenko-gl/141efda63e0b3f0a28846b50fa35c11c

### Build Logs

1. Output
https://gist.github.com/mykyta-bondarenko-gl/8a3d64768012e55ca2245ca2caaa450a

### Example Project 

[HttpClient](https://github.com/xamarin/mac-samples/tree/master/HttpClient)

**Comment by chamons** [comment]
```
find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/4.5/ -name '*.dll' -print -exec monop -r:{} \; 
```
 confirms this comes from System.dll

I'm going to see if this was a mono breakage by bisecting mono versions and seeing if they broke this somewhere.

**Comment by chamons** [comment]
So I checked all the way back to mono 4.2:

```
5.12.0.298 - Fail not found
5.8.1.0 - Fail not found
4.6 - Fail not accessible
4.2 - Fail not accessible
```

and none of them built with system mono. 🤔

**Comment by chamons** [comment]
I should have checked the source first:

https://github.com/mono/mono/blob/master/mcs/class/System/System.Net/HttpWebRequest.cs#L153

This specific API is MOBILE only, this _never_ worked on Full.

Creating a sample bug to swap to new API then will close.

**Comment by chamons** [comment]
Filed as sample bug: https://github.com/xamarin/mac-samples/issues/101
