### ISSUE TITLE
XmlDateTimeSerializationModeUnspecified failure on iOS device

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3969]
### Steps to Reproduce

1.  Update System to Xamarin.iOS  11.10.1.174 (d15-7: f4933226) 
2. Execute System.Xml tests on device

### Expected Behavior
All tests run successfully
### Actual Behavior
[FAIL] XmlConvertTests.XmlDateTimeSerializationModeUnspecified :   #2
### Environment
```
Operating System: Mac OS X 10.13.4
Mono version: 5.10.1.47 (8eb8f7d5e74)  (2018-04-13 20:18:12 -04:00)
XA version: 8.3.0.18 (HEAD/1f8462ef1) 
XI version: 11.10.1.174 (d15-7: f4933226) 
XM version: 4.4.1.173 (master: f4933226)  (2018-04-18 02:19:00 -04:00)
XVS version: 
XS version: 7.5.0.1183 (f0a7369)  (2018-04-16 12:42:52 -04:00)
[Device] Name: XQAiPadPro105a, Version: 10.3.3
```

### Build Logs

DeviceLog +Test Log: http://xqa.blob.core.windows.net/gist/System.Xml-ios07-28-29e853abb376338c34d84e79b18c6a8ab421a6af8407-28-29-987349fad12e44beb0c7455a049004b5.zip

Build Log: http://xqa.blob.core.windows.net/gist/report-188912ec07944970b10a6a280e6d3c66.txt
### Additional Info

This test failure is seen only on two devices, iPhoneX 11.3 and iPad10.5 10.3.3

Same test with the same commit hash passed on another set of devices: https://devdiv.visualstudio.com/DevDiv/_TestManagement/Runs?_a=resultQuery&runId=1325106

**Comment by mandel-macaque** [comment]
@GouriKumari I have tried the test with the following setup and was not able to reproduce the issue:

* iOS 11.4 Language en-us, region us, tz boston
* iOS 11.4 Language es-sp, region sp, tz, sp
* iOS 11.4 Language es-et (ethiopia, known not supported combination), region utopia, tz boston

I believe we can disregard the issue as a regression, is more a flaky test in a very specific point in time. I would leave it open in case we ever find a setting that can reproduce the failure.

@spouliot thought?

**Comment by spouliot** [comment]
```csharp
DateTime dt1 = XmlConvert.ToDateTime ("0001-02-03T10:20:30.0000+02:00", XmlDateTimeSerializationMode.Unspecified);
DateTime dt2 = XmlConvert.ToDateTime ("0001-02-03T10:20:30.0000", XmlDateTimeSerializationMode.Unspecified);
Assert.AreEqual (false, dt1 == dt2, "#2");
```

Doc is not very clear

`Unspecified` | Treat as a local time if a DateTime is being converted to a string.
https://msdn.microsoft.com/en-us/library/system.xml.xmldatetimeserializationmode(v=vs.110).aspx

But the test convert **from** not **to** a string.

Wild guess (without looking at the BCL code) is that the failing devices are at `+2:00` so the converted time are equal.

@GouriKumari if you can locate the device ping us on slack so we can query it's configuration. Right now I'm assuming it's a configuration issue + imprecise test that cause the failure. Thanks!

**Comment by GouriKumari** [comment]
I couldn't reproduce the issue locally. 

## Logs:
Test Log: https://gist.github.com/GouriKumari/c1f14c60ba9a84b449d91cd99d24b1db
Test Env:  https://gist.github.com/GouriKumari/0f0f8f6f1081b4217b2f160fc8f2cdda

## Device Config:
iPhone X 11.3
TimeZone: EST
Language: en
Region : United Statest

## Additional Details:
Observed that XmlConvertTests.XmlDateTimeSerializationModeUnspecified  passed successfully on XQAiPadPro105a, Version: 10.3.3,  when the test was executed a second time  against the same commit, 11.10.1.174 (d15-7: f4933226)  from the same bot. Initially, test failed on this device.

**Comment by dalexsoto** [comment]
@GouriKumari Have you seen the issue happening again? Should we keep this bug open?

**Comment by dalexsoto** [comment]
Since we have not received more reports since April and we have not been able to repro I guess this is fine to close, feel free to reopen otherwise.
