### ISSUE TITLE
ConditionalWeakTableTest.OldGenStress failure on device

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#3970]
### Steps to Reproduce

1. Update System to Xamarin.iOS 11.10.1.174 (d15-7: f493322)
2. Execute mscorlib tests on device

### Expected Behavior
All tests must pass
### Actual Behavior
[FAIL] ConditionalWeakTableTest.OldGenStress :   #r1-0
### Environment

```
Operating System: Mac OS X 10.13.4
Mono version: 5.10.1.47 (8eb8f7d5e74)  (2018-04-13 20:18:12 -04:00)
XA version: 8.3.0.18 (HEAD/1f8462ef1) 
XI version: 11.10.1.174 (d15-7: f4933226) 
XM version: 4.4.1.173 (master: f4933226)  (2018-04-18 02:19:00 -04:00)
XVS version: 
XS version: 7.5.0.1183 (f0a7369)  (2018-04-16 12:42:52 -04:00)
[Device] Name: XQAiPhoneXa, Version: 11.3, Arch: ARM64, FormFactor: iPhone, PairedPhone: 
```

### Build Logs
Test Log+ Device Log : http://xqa.blob.core.windows.net/gist/mscorlib-ios11-02-05aa8c19b57a6d87f53c46766d844888df126c34e211-02-05-54cf271d979644d7986c4a4f2e2db0e3.zip
Build Log: http://xqa.blob.core.windows.net/gist/report-a1d8fc21f7d64a568032bd01bb3da657.txt

### Additional Info
This issue used to occur in the past, https://bugzilla.xamarin.com/show_bug.cgi?id=59124 and is now occurring frequently on devices.

**Comment by mandel-macaque** [comment]
@GouriKumari tested with an iOs 11.4 device and d15-7 and was not able to reproduce it, do we have more details about the device. Should I downgrade to 11.3?

**Comment by mandel-macaque** [comment]
This does not seem to be a regression of 15-7 AFAIK.

**Comment by dalexsoto** [comment]
Have you guys been able to reproduce this issue? Should we continue to keep this bug open?

**Comment by dalexsoto** [comment]
Since we have not received more reports since April and we have not been able to repro I guess this is fin to close, feel free to reopen otherwise.
