### ISSUE TITLE
Build errors after updating any XIB or Storyboard file 

### ISSUE THREAD

**Issue by ghost** [xamarin/xamarin-macios#3974]
### Steps to Reproduce

Any time making any changes to a XIB or storyboard file using XCode - get build errors in LaunchScreen.storyboard even though LaunchScreen.storyboard didn't change. Only fix is to clean, exit out of Visual Studio for Mac and relaunch it.  VERY frustrating for working on large projects.

### Expected Behavior
build works without issues

### Actual Behavior
Get build errors - forced to clean project several times or restart Visual Studio for Mac before it starts working again.

### Environment
See attached logs

1.
Visual Studio: Help > About Microsoft Visual Studio > Copy Info [button]
Visual Studio for Mac: Visual Studio > About Visual Studio > Show Details > Copy Information [button]

2. Paste into the code block below (between ```)
-->

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.4.3 (build 10)
Installation UUID: 34bee655-6c62-47e9-8e60-463ef21d3764
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.29 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Enterprise)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Enterprise)
Android SDK: /Users/lebeaaa/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704030010
Git revision: 5af3e98549653fcc5335896ccc296343d08f31bb
Build date: 2018-04-12 12:32:07-04
Xamarin addins: fadb82fb0fe2668cb7789f8b524aec6fb8568ee7
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Vim 0.53.1
Internet of Things (IoT) development (Preview) 7.1


```

### Example Project (If Possible)

> VS bug [#604927](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/604927), VS bug [#737245](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/737245)

**Comment by biozal** [comment]
This is a problem with VS for Mac I believe - I opened a bug using Bugzilla and they told me to create the bug here instead.

**Comment by mandel-macaque** [comment]
Hello,

This does look like a bug in VS prese since Xamarin.iOS does not perform any special operation for .xib. I'll triage the bug (label will be added) for the VS for mac developers to take a look. 

If it is possible, can you provide a sample project that exposes the issue? Thx!

**Comment by sgmunn** [comment]
@biozal is it possible to get a copy of the build errors that you are getting?
