### ISSUE TITLE
[mmp] ProcessNativeLibrary and associated logic is byzantine, very difficult to follow, and sometimes wrong

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#3982]
This logic has had a sorrow filled history and much of it never works exactly correctly. False positive warnings (X is missing but really ends up there later, etc) are somewhat common.

https://github.com/xamarin/xamarin-macios/blob/master/tools/mmp/driver.cs#L1629

Much of dates back to Classic and is a scattershot set of rules that are not always consistent.

I am fearful to touch this code for fear of breaking customers. It has happened multiple times in the last few years.

I would like to rip it all out and describe it consistently and\or move to what Xamarin.iOS is doing.

In any case, we are likely going to need to keep it around as some --use-legacy-native-dependency-resolution or the like, since even looking at it wrong will certainly break someone.

**Comment by rolfbjarne** [comment]
This is fixed for .NET (this code isn't used anymore).
