### ISSUE TITLE
Image in assets.xcassets not showing when deployed to simulator

### ISSUE THREAD

**Issue by albilaga** [xamarin/xamarin-macios#3993]
### Steps to Reproduce

1. Add new imageset in assets.xcassets
2.  Open storyboard and add imageview with image from assets.xcassets
3. Try also clean rebuild ( it works first time but after clean rebuild it not working)

### Expected Behavior
Image showing in simulator
### Actual Behavior
Image not showing in simulator. Get error message "Could not load the "homeActive" image referenced from a nib in the bundle with identifier com.xxx.xxx" but it it showing on storyboard
### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.4.3 (build 10)
Installation UUID: 234403a7-43ae-4cb0-a553-9f245478a9fe
Runtime:
	Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508010000

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.4
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.1.3
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.2.1.29 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Community)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Xamarin.Android ===

Version: 8.2.0.16 (Visual Studio Community)
Android SDK: /Users/albilaga/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.1 (API level 16)
		4.4 (API level 19)
		5.0 (API level 21)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 28.0.0 rc1

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704030010
Git revision: 5af3e98549653fcc5335896ccc296343d08f31bb
Build date: 2018-04-12 12:32:07-04
Xamarin addins: fadb82fb0fe2668cb7789f8b524aec6fb8568ee7
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Android Signature Tool 2.1.2
MFractor 3.05.04
MvvmCross Template pack 2.0.1
Internet of Things (IoT) development (Preview) 7.1
```

**Comment by therealjohn** [comment]
Hi @albilaga,

I was not able to reproduce this problem. Please include your full build logs and a test case (to reproduce).

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

Then, copy the Output into a .txt file and attach it to this Issue. Thank you!

**Comment by therealjohn** [comment]
I've not heard back on this with the information requested. If you can provide the requested info please reopen the issue. Thanks!

**Comment by jonathanfontaine** [comment]
I got the same issue, and found how to get away with it.

The following lines were missing in my **.csproj file** :
```
<ImageAsset Include="Resources\Images.xcassets\myImage.imageset\Contents.json">
      <Visible>false</Visible>
</ImageAsset>
```
Then do the following :
1. Uninstall the app on your device
2. Remove **bin** and **obj** folders
3. Restart Visual Studio
4. Launch your app and pray
