### ISSUE TITLE
Don't verify types if you store to a pointer byref

### ISSUE THREAD

**Issue by marek-safar** [xamarin/xamarin-macios#4007]
This is integration tracking issue for https://github.com/mono/mono/issues/8403

**Comment by marek-safar** [comment]
This should be fixed by https://github.com/xamarin/xamarin-macios/commit/7e782c1e09c1d99c4e1608a4dbe0325ef8e66816

**Comment by spouliot** [comment]
QA already created the VSTS issue [1] and the "ask mode" is already filed. c.c. @Aguilex 

[1] https://devdiv.visualstudio.com/DevDiv/Xamarin%20Project%20Mgrs/_queries?_a=query&id=ff9ea6e7-709d-4844-9c04-282b7230ed1d

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '15.7' that is not in the list of supported values
