### ISSUE TITLE
MessageHandler Test failure on iOS device

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4013]
### Steps to Reproduce

1. Update System to XI version: 11.10.1.177 (d15-7: 7e782c1e) 
2. Execute monotouch-test on device

### Expected Behavior
All tests should pass
### Actual Behavior
[FAIL] MessageHandlerTest.DnsFailure(System.Net.Http.HttpClientHandler) :   Exception
[FAIL] MessageHandlerTest.DnsFailure(System.Net.Http.CFNetworkHandler) :   Exception
[FAIL] MessageHandlerTest.DnsFailure(System.Net.Http.NSUrlSessionHandler) :   Exception

### Environment

```
Operating System: Mac OS X 10.13.4
Mono version: 5.10.1.47 (8eb8f7d5e74)  (2018-04-13 20:18:12 -04:00)
XA version: 8.3.0.19 (HEAD/342b2ce96) 
XI version: 11.10.1.177 (d15-7: 7e782c1e) 
XM version: 4.4.1.176 (master: 7e782c1e)  (2018-04-25 15:27:14 -04:00)
XVS version: 
XS version: 7.5.0.1222 (48907c1)  (2018-04-20 18:20:07 -04:00)
[Device] Name: XQAiPhoneXa, Version: 11.3, Arch: ARM64, FormFactor: iPhone, PairedPhone: 
```

### Build Logs

Build Log: http://xqa.blob.core.windows.net/gist/report-4b66fbdb3b3d475d86b210d5f7bda386.txt
Test Log + Device log: http://xqa.blob.core.windows.net/gist/monotouchtest-ios09-33-23aa8c19b57a6d87f53c46766d844888df126c34e209-33-23-331784cae1d544cc930939185b8b1acc.zip

### Example Project (If Possible)

xamarin-macios/tests/monotouch-test

### Additional Info
This issue is occurring only on certain devices like an iPadMini4 and iPhoneX and the issue is not new. With this test run, CI returned test failure results and continued running other tests. Is there anything specific  that needs to be checked if this is network related?

**Comment by VincentDondain** [comment]
Hi,

I couldn't reproduce the issue. @GouriKumari could you please point to the faulty lane?

_Note: I tried on an iPhone X with XI version: 11.10.1.177 (d15-7: 7e782c1e). [Full environment](https://gist.github.com/VincentDondain/281188698d6dcfc79ae226c312e389fe)._

**Comment by GouriKumari** [comment]
Test Env that failed. You can find the bug report at the end: https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?releaseId=97189&_a=release-environment-logs&environmentId=292828.

**Comment by VincentDondain** [comment]
I'll confirm this based on the attached bot test failure (even tough I can't repro locally as I said).

@GouriKumari can you reproduce the issue locally? Is this intermittent? Did it happen with newer builds?

**Comment by GouriKumari** [comment]
I couldn't reproduce it locally. This issue is also not intermittent on iPhoneX and iPadMini4, from bots. I changed the hostname of the bot to use ipaddress to check if it resolves the test failure.

**Comment by GouriKumari** [comment]
MessageHandler test failures occur on devices with the change in hostname to ipaddress.  

## Logs:

Build and Installation logs: http://xqa.blob.core.windows.net/gist/report-effd758c671b4790a9ad344edfdd695b.txt

Device and Test logs: http://xqa.blob.core.windows.net/gist/monotouchtest-ios04-20-05aa8c19b57a6d87f53c46766d844888df126c34e204-20-05-94a4d66b2e214ac6b133ea89abda2b41.zip

**Comment by spouliot** [comment]
>  I changed the hostname of the bot to use ipaddress to check if it resolves the test failure.

what's the diff of that change ?

I'm surprised that the bots could download something from `http://doesnotexist.xamarin.com` unless there's some DNS configuration (in the lab) that redirect everything (not resolved) to some other host.

**Comment by spouliot** [comment]
No, the diff of the source of the tests.

If you use an IP address then there's no name resolution (DNS) required, that already change the test (even if the IP address is not reachable) beyond its original goal.

Still I don't see how http://doesnotexist.xamarin.com could be reachable - which is how (no exception) the test would fail

**Comment by rolfbjarne** [comment]
Maybe we can modify the test to print more info (the downloaded string for instance)?

**Comment by GouriKumari** [comment]
Closing this issue since the test [passed](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=192836&environmentId=757030&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension) in all devices where it failed previously.

[Logs ](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=192836&environmentId=757030&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension)
