### ISSUE TITLE
Metal Shaders hard coded to osx-metal1.0 can't use 1.2 or 2.0

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#4019]
Here we hard code 1.0: https://github.com/xamarin/xamarin-macios/blob/master/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/MetalTaskBase.cs#L80

This likely needs to be more flexible.

**Comment by VincentDondain** [comment]
@jstedfast if this requires a properties panel could you please file VSTS issues for both IDEs?

**Comment by Jorgemagic** [comment]
My Tessellation project ported from MetalBasicTessellation apple demo 
[Tessellation simple demo](https://github.com/Jorgemagic/Metal2-Samples/tree/master/Tesselation)

**Comment by jstedfast** [comment]
@kzu could you file an issue for the VS Windows IDE for this? I'm not familiar enough with VSTS to know the values to use for most of the fields.

**Comment by kzu** [comment]
Area: DevDiv\Mobile Dev Tools\Xamarin\XamarinVS
Iteration: DevDiv\Xamarin\VisualStudio
Type: Bug

That's all you need.

**Comment by jstedfast** [comment]
iOS does have this flag tho: -mios-version-min=11.3
MacOSX has this flag: -mmacosx-version-min=10.12

**Comment by jstedfast** [comment]
ok, this will be fixed in 15.8
