### ISSUE TITLE
The 'isWrapper' argument to the [Register] attribute must be correct for models

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#4065]
This is a breaking change in d15-7 that exposes an old bug in our binding generator, causing build failures (this is an example of the [CorePlot component][1], which hasn't been updated since early 2015):

```
clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: CPTAnimationDelegate. The symbol '_OBJC_CLASS_$_CPTAnimationDelegate' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: CPTAxisDelegate. The symbol '_OBJC_CLASS_$_CPTAxisDelegate' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: CPTBarPlotDataSource. The symbol '_OBJC_CLASS_$_CPTBarPlotDataSource' could not be found in any of the libraries or frameworks linked with your application.
[...]
MTOUCH : error MT5202: Native linking failed. Please review the build log.

````

Old versions of the binding generator would generate the following code:

```csharp
[Model]
[Protocol]
[Register ("CPTAnimationDelegate", true)]
public class CPTAnimationDelegate : NSObject, ICPTAnimationDelegate, INativeObject, IDisposable
{
}
```

The problem is the `true` argument to the `[Register]` attribute: it specifies that the managed class is wrapping an existing Objective-C class. For models (classes with the ´[Model]` attribute) this is incorrect. At the time this did not cause any ill effects, because the value didn't change any behavior.

However, In our most recent release, d15-7 this changed, and now the value must be correct, otherwise the app will fail to build as mentioned above.

The binding generator was fixed in early 2015, which means that the problem only occurs with any binding libraries that haven't been updated since then (such as the CorePlot component).

The fix is to rebuild the binding project with a recent version of Xamarin.iOS (any version from the last two years would do). If the source code isn't available, there is also a [command-line tool][2] available that can fix the library.

Reference (fix): https://github.com/xamarin/maccore/commit/b9f39f537bb39fa69a1312be097f127901d7b652

[1]: https://components.xamarin.com/gettingstarted/coreplot
[2]: https://github.com/rolfbjarne/fix-binding-library

**Comment by rolfbjarne** [comment]
Closing since this issue is purely informational.

**Comment by rolfbjarne** [comment]
@volcano619 if you run into this you need to fix the binding library that causes this problem, it's not something that will be fixed in Xamarin.iOS.

**Comment by volcano619** [comment]
The library is present ,has all the architectures and has the interfaces that it claims to be missing, tried adding [Protocol] annotation but that just seems to bypass the error
Am I missing something , and it was running fine before..
Any inputs would be helpfull
