### ISSUE TITLE
MMP does not quote frameworks/weak frameworks

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#4066]
1.  Create XM project
2. Add native reference to framework with spaces
3. Build

### Expected Behavior

Build successful

### Actual Behavior

Build fails

### Environment

master and stable.

**Comment by chamons** [comment]
Need to check mtouch as well.

**Comment by chamons** [comment]
Needs a fix like https://git.io/vpPNd

**Comment by rolfbjarne** [comment]
Fixed in .NET.
