### ISSUE TITLE
Xcode 9.3 integration - Could not insert new outlet connection

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#4078]
There are multiple people using Xcode 9.3 with Xamarin.Mac who are unable to add outlets to the Xcode project when editing a storyboard.

<img width="268" alt="screen shot 2018-05-10 at 11 20 34 am" src="https://user-images.githubusercontent.com/6392201/39936315-b1218714-5511-11e8-8a50-7a78131f78bf.png">

It appears inconsistent, as it failed for me yesterday but works today?

I am not certain that this is a XM bug, but opened this for tracking.

### Steps to Reproduce

1. Open storyboard
2. In Xcode add control and attempt to create outlet
3. ??

### Expected Behavior

Xcode to allow outlet

### Environment

https://gist.github.com/chamons/c414e2a969a123db4ed3de3930b99a8d

> VS bug [#707079](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/707079)

**Comment by sandyarmstrong** [comment]
[wktest.zip](https://github.com/xamarin/xamarin-macios/files/1996157/wktest.zip)

I've attached a brand new XM project I created that is having the same issue. Trying to add an outlet to the WKWebView I've put in the view.

Xcode 9.3.0
XM 11.10.1.177
VSmac 7.5 (build 1254)

Additional symptoms:
* No auto-complete in ViewController.h.
* Xcode periodically notifies me that workspace has been deleted, so I have to start all over again.

**Comment by abock** [comment]
Same issue out of the box using the vanilla Cocoa project template against Xcode 9.2 and the latest Xamarin from stable.

| Thing | Version | 
| :- | :- |
| Xcode | 9.2 (9C40b) |
| Xamarin.Mac | 4.4.1.178 |
| VS Mac | 7.5.1 (build 22) |
| macOS | 10.13.5 Beta (17F45c) |


![xcode integration broken](https://user-images.githubusercontent.com/49539/40153638-b2134270-5958-11e8-9c91-068fcca844b7.gif)

**Comment by chamons** [comment]
This breaks XM usage hard. Bumping for serious consideration for 15-8.

**Comment by jstedfast** [comment]
Useful info: https://stackoverflow.com/questions/15288773/could-not-insert-new-outlet-connection

For whatever reason, after getting this error, switching tabs to research this, then going back to Xcode and cancelling the Outlet dialog, Xcode decided to index the project. Then once that finished, I tried again, and tada! It worked.

The StackOverflow question has a handful of ideas on how you can force Xcode to (re)index the project. For me, it seemed to just be a matter of time? Or maybe switching back to Xcode from another window? I'm not really sure. I didn't have to explicitly try any of them.

**Comment by sandyarmstrong** [comment]
I am still seeing this error randomly with Xcode 10.0.0, VSmac 7.7 build 1373, and Xamarin.Mac 5.0.0.26. It usually works the second time. At least once, after it seemed to work in Xcode, it was clear that VSmac and Xcode were no longer "connected" and changes stopped being reflected in the `.designer.cs` file.

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '15.8' that is not in the list of supported values

**Comment by spouliot** [comment]
re-label'ed since, as far as I can tell, this not related to the SDK but to the VS4M/Xcode integration in the addin

**Comment by jstedfast** [comment]
I don't think there's anything we can do to fix this :-\

The project format that VSMac exports to Xcode is correct, it's just that Xcode is lazily parsing/indexing the source files.
