### ISSUE TITLE
[mtouch-errors] Document MT1300

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#4079]
It looks like MT1300 isn't documented in our mtouch-error doc, therefore the IDE can't link to it.

See https://github.com/xamarin/xamarin-macios/blob/master/tools/mtouch/BitcodeConverter.cs#L58 and https://github.com/xamarin/xamarin-macios/blob/master/docs/website/mtouch-errors.md#mt13xx-linkwith.

_Note: 1301 and 1302 from `BitcodeConverter.cs` are also absent from this doc._

I'd expect MT1300 to explain where bitcode is supported (tvOS / watchOS), what are the differences between the platforms (missing features) and why it's not supported on iOS.

_Note 2: I believe linking to a more extensive document is also an option here._

**Comment by rolfbjarne** [comment]
Apple is removing bitcode, so this isn't necessary anymore.
