### ISSUE TITLE
Xamarin.iOS: Could not find the assembly 'Xamarin.iOS.dll' in the app. 

### ISSUE THREAD

**Issue by manuelpa-ms** [xamarin/xamarin-macios#4088]
### Steps to Reproduce

IPA submitted to Apple for review crashes on startup. Cannot reproduce locally, only with the Release IPA; cleaned the solution and re-submitted, startup crash persists. Crash log contains the following line:

May  4 16:47:50 iPhone-8plus AppName[407] <Notice>: Xamarin.iOS: Could not find the assembly 'Xamarin.iOS.dll' in the app. This is usually fixed by cleaning and rebuilding your project; if that doesn't work, please file a bug report: http://bugzilla.xamarin.com

The app is already published to the App Store, this is just an updated version.

### Expected Behavior
App works correctly.

### Actual Behavior
See above

### Environment

```
Visual Studio Community 2017 for Mac Version 7.3.3(Build 17)
Xamarin .iOS Version 11.6.1.4
```

### Example Project (If Possible)

Not possible at this time.

**Comment by migueldeicaza** [comment]
Can you run unzip -v file.ipa for us to look at the contents of your app?

Could you provide us access to the IPA that you submitted?

**Comment by migueldeicaza** [comment]
My guess is that you have different settings in Release to store than the one that you are testing.

**Comment by jgold6** [comment]
I have an IPA that indeed us missing the Xamarin.iOS.dll. 
I have the solution (can not share this stuff publicly) and looked over the .csproj file and I see no significant difference in the settings for the Release config vs. the AppStore config. The only difference I see is the CodesignKey used (as expected) and some casing, i.e. `<Optimize>true</Optimize>`
`<ConsolePause>false</ConsolePause>`
vs.
`<Optimize>True</Optimize>`
`<ConsolePause>False</ConsolePause>`

**Comment by jgold6** [comment]
Well this is odd. I just built the customer's solution for Simulator and device using Release configuration. Both apps launched without crashing (cant go further as I do not have credentials to log in to the app). The odd thing is that the iPhone release build did not have Xamarin.iOS.dll in it, but the simulator build did. If I do the simulator Release build without launching to the simulator (using Build All menu) then the Xamarin.iOS.dll is absent from the app package. 

Here is the output of  `ls -la | grep Xamarin` in the .app file for each:
Release | iPhoneSimulator (not deployed, only built)

`
-rw-r--r--    1 jongoldberger  staff    23040 Jun  1 11:34 OxyPlot.Xamarin.iOS.dll
-rw-r--r--    1 jongoldberger  staff    16896 Jun  1 11:34 Xamarin-Sidebar-Unified.dll
`

Release | iPhone (not deployed, only built)

`
-rw-r--r--    1 jongoldberger  staff     72264 Jun  1 11:38 OxyPlot.Xamarin.iOS.aotdata.arm64
-rw-r--r--    1 jongoldberger  staff     72544 Jun  1 11:39 OxyPlot.Xamarin.iOS.aotdata.armv7
-rw-r--r--    1 jongoldberger  staff     15872 Jun  1 11:40 OxyPlot.Xamarin.iOS.dll
-rw-r--r--    1 jongoldberger  staff      3104 Jun  1 11:38 Xamarin-Sidebar-Unified.aotdata.arm64
-rw-r--r--    1 jongoldberger  staff      3128 Jun  1 11:39 Xamarin-Sidebar-Unified.aotdata.armv7
-rw-r--r--    1 jongoldberger  staff     11264 Jun  1 11:40 Xamarin-Sidebar-Unified.dll 
`

Release | iPhoneSimulator (deployed):

`
-rw-r--r--    1 jongoldberger  staff     23040 Jun  1 11:34 OxyPlot.Xamarin.iOS.dll
-rw-r--r--    1 jongoldberger  staff     16896 Jun  1 11:34 Xamarin-Sidebar-Unified.dll
-rwxr-xr-x    1 jongoldberger  staff  14329344 Jun  1 11:34 Xamarin.iOS.dll
`

Release | iPhone (deployed)

`
-rw-r--r--    1 jongoldberger  staff     72264 Jun  1 11:38 OxyPlot.Xamarin.iOS.aotdata.arm64
-rw-r--r--    1 jongoldberger  staff     72544 Jun  1 11:39 OxyPlot.Xamarin.iOS.aotdata.armv7
-rw-r--r--    1 jongoldberger  staff     15872 Jun  1 11:40 OxyPlot.Xamarin.iOS.dll
-rw-r--r--    1 jongoldberger  staff      3104 Jun  1 11:38 Xamarin-Sidebar-Unified.aotdata.arm64
-rw-r--r--    1 jongoldberger  staff      3128 Jun  1 11:39 Xamarin-Sidebar-Unified.aotdata.armv7
-rw-r--r--    1 jongoldberger  staff     11264 Jun  1 11:40 Xamarin-Sidebar-Unified.dll
`

The weird this, as noted, is that the device build does launch and get past the splash screen to a log in screen. No crash. 

I can provide build outputs, device logs, etc privately if needed.

**Comment by jgold6** [comment]
@migueldeicaza Any other ideas as to what may be going on here? I can send you a private link to the IPA, etc. if still needed.

**Comment by jgold6** [comment]
Ah, you know what, I missed hidden folders. Before I just looked into the *.app file using Finder and "Show Package Contents." Using the unzip comand in Terminal I see there are hidden **.monotouch-32** and **.monotouch-64** folders that do have Xamarin.iOS.dll in them. 

```
unzip -v [redacted].ipa | grep Xamarin
...
/[redacted].app/.monotouch-64/Xamarin.iOS.aotdata.arm64
Payload/[redacted].app/.monotouch-64/Xamarin.iOS.dll
...
Payload/[redacted].app/.monotouch-32/Xamarin.iOS.aotdata.armv7
Payload/[redacted].app/.monotouch-32/Xamarin.iOS.dll
...
```

**Comment by jgold6** [comment]
I was just provided a new IPA after stressing I needed the exact IPA that was submitted. That IPA was indeed missing the 64 bit Xamarin.iOS.dll. I am having the customer rebuild making sure they are building for ARMv7 + ARM64 and informed them how to verify presence of both assemblies. 

I will close this issue as soon as I hear back from the customer with positive results.

**Comment by jgold6** [comment]
Closing this issue as customer confirmed issue is resolved.

**Comment by VincentDondain** [comment]
Closing as per pervious comment.
