### ISSUE TITLE
tvOS projects fail to build with native linking error MT5216 failed for libXamarin.TVOS.dll.dylib

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4089]
### Steps to Reproduce

1.  Update System to Xamarin.iOS master build , Version: 11.11.0.313 (Visual Studio Community)
Hash: 0416ea04
2. Build a tvOS sample project, https://github.com/xamarin/ios-samples/tree/master/tvos/tvAlerts

### Expected Behavior
App builds successfully
### Actual Behavior
App fails to build with error, MTOUCH : error MT5216: Native linking failed for '/Users/gourikumari/GitRepo/monotouch-samples/ios-samples/tvos/tvAlerts/tvAlerts/obj/iPhone/Debug/device-builds/appletv5.3-11.4/mtouch-cache/arm64/libXamarin.TVOS.dll.dylib'

## Regression:
This is a regression from preview 1 and seems to have caused in master with https://github.com/xamarin/xamarin-macios/commit/f765d674d3a503f4112a2c5f034af53d3b86b4cc.

Unable to reproduce with template projects. 

### Environment

```
=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.6 Preview (7.6 build 711)
Installation UUID: 74c37335-5878-4fa7-8f71-09bc48b661c5
Runtime:
	Mono 5.12.0.226 (2018-02/9824e260f56) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 512000226

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3 (14154)
Build 9E145

=== Xamarin.Mac ===

Version: 4.5.0.313 (Visual Studio Community)
Hash: 0416ea04
Branch: master
Build date: 2018-05-12 08:05:52-0400

=== Xamarin.iOS ===

Version: 11.11.0.313 (Visual Studio Community)
Hash: 0416ea04
Branch: master
Build date: 2018-05-12 08:05:52-0400

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/gourikumari/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 25.2.3
SDK Platform Tools Version: 25.0.1
SDK Build Tools Version: 25.0.1

Java SDK: /usr
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706000711
Git revision: 634060c6c105fd3ee36678fe547680fd258cbf45
Build date: 2018-05-04 16:11:06-04
Xamarin extensions: c6720450018cb69a3da7c6d0aa0715c013783595
Build lane: monodevelop-lion-master

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Gist Ide Information 1.1.0
Internet of Things (IoT) development (Preview) 7.1

```
### Build Logs
Build Log: https://gist.github.com/GouriKumari/ed7dcf6d60740a85d7aba6e58ccab34f
### Example Project (If Possible)
https://github.com/xamarin/ios-samples/tree/master/tvos/tvAlerts

**Comment by mandel-macaque** [comment]
@GouriKumari I have tried building the sample with current master (1e6851ec67f67ac250026ce9342bbfd562294717) and I was not able to reproduce the error. App was correctly built. Can you double check.

**Comment by GouriKumari** [comment]
Based on[ tvOS test results](https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?releaseId=105666&environmentId=334022&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension), I am closing this issue. 

##Test Env
mtouch 11.11.0.321 (master: 07356b83)
