### ISSUE TITLE
AVCaptureScreenInput

### ISSUE THREAD

**Issue by Terricide** [xamarin/xamarin-macios#4095]
I see AVCaptureScreenInput referenced in the docs. But I don't see it in this repo. Am I missing something?

**Comment by NickSpag** [comment]
It's a code-generated binding so you shouldn't see it in the repo. In a Xamarin.Mac project you can right click on the type and select "Go to Definition" (or apple + D) and you'll see the source binding in the Assembly Browser. 

You'll see that everything in AVCaptureSessionInput is decorated with the `BindingImplOptions.GeneratedCode`- you can see the generator [here](https://github.com/xamarin/xamarin-macios/blob/master/src/generator.cs). If you build Xamarin.Mac locally you'll find AVCaptureScreenInput.g.cs in the xammac build/mac/mobile/AVFoundation directory.

**Comment by Terricide** [comment]
Okay thanks my end goal is to get that api into Mono.Mac since I've got a .net core port of it that seems to be working fine. Unless Xamarin.Mac is working in .net core now?
