### ISSUE TITLE
Not all assemblies for Xamarin.Sdk have link tasks

### ISSUE THREAD

**Issue by cainunable** [xamarin/xamarin-macios#4101]
Our existing Xamarin.iOS project is in the process of a major refactor. Part of this has included relying more on NuGet, although I am not certain that is this the root of the problem.  Currently our project builds and runs fine on the simulator, but if we try to build for a device we get 
```
error MT0099 : Internal error : Not all assemblies for Xamarin.Sdk have link tasks.
```
I have not yet been able to figure out the exact cause of the issue.

### Steps to Reproduce

1.  Build Release Project for Generic Device
2. 
3. 

### Expected Behavior

Project builds correctly and can be deployed in our test environment

### Actual Behavior

"error MT0099 : Internal error : Not all assemblies for Xamarin.Sdk have link tasks." is received in log
### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.5.1 (build 22)
Installation UUID: 16431a6a-5dc0-42b2-8f61-58c958f7f21c
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010047

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.3.1 (14154.1)
Build 9E501

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 11.10.1.178 (Visual Studio Community)
Hash: 408d3574
Branch: d15-7
Build date: 2018-05-08 18:56:30-0400

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/canderson/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.4   (API level 19)
		7.1   (API level 25)

SDK Tools Version: 23.0.5
SDK Platform Tools Version: 21.0.0
SDK Build Tools Version: 21.1.1

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705010022
Git revision: 60442dd643a20c7a4ae1f8705b8d1de8972eee78
Build date: 2018-05-15 01:43:39+00
Xamarin addins: 4194ffe4868321e4c3477bd56aed579bda4c6fbb

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.5

```

### Build Logs

[BuildError5-17.txt](https://github.com/xamarin/xamarin-macios/files/2014697/BuildError5-17.txt)

**Comment by rolfbjarne** [comment]
Would it be possible to get access to your project so that we can reproduce this ourselves?

**Comment by cainunable** [comment]
I've been trying to whittle down the project in size to a manageable size, but I'm not sure I am going to be able to get it down to something that is 10MB or less.

**Comment by cainunable** [comment]
[TestProject.zip](https://github.com/xamarin/xamarin-macios/files/2018264/TestProject.zip)
I managed to get it down to a small enough size for the upload requirements.  The application's functionality no longer exists, but it will at least launch the first screen in the simulator and will still display the build error when attempting to build for generic device.

To test:
Open TestProject>IosGold>IosGold.sln
If it isn't done automatically on load, you may have to do a Restore NuGet Packages.
Debugging on a simulator should display a screen on the simulator
Building for a generic device should display the "Not all assemblies for Xamarin.Sdk have link tasks." error in the build output.

**Comment by rolfbjarne** [comment]
The solution doesn't compile, even after restoring nuget packages.

There seem to be multiple assemblies missing: ShinobiGrids.dll, ShinobiEssentials.dll, various Syncfusion dlls, etc.

You can use a file-sharing service (like Dropbox for instance) and paste the link here to get around the 10MB limit.

**Comment by cainunable** [comment]
Sorry about that.  Something must have got messed up in the refactoring to build for this.  We have managed to solve the issue in house.  Some of the nuget packages were referencing libraries and frameworks that may not have been compatible. Once one of the other developers sorted out those packages, we were able to build normally again.
