### ISSUE TITLE
mmp-tests run on debug fail locally

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#4108]
### Steps to Reproduce

Open mmptest in VSfM and run locally

### Expected Behavior

Our tests to match build machine status

### Actual Behavior

About 19 test failures. I believe some of them are related to debug symbols, but have not researched further.

### Environment

master

**Comment by VincentDondain** [comment]
@chamons which tests failed? I'm re-running all mmp-tests right now but it'll probably be faster if I knew which specific ones to test. A test log would have been nice (:

**Comment by chamons** [comment]
I think it was 19 tests. It would have been grand for me to write them down but i didn't, and VSfM doesn't keep logs. :(

**Comment by VincentDondain** [comment]
@chamons all 161 mmp tests, launched from VSMac passed for me: https://gist.github.com/VincentDondain/4e44cee145db77f4073ad532ff2073b1

Running with latest XM master installed locally: https://gist.github.com/VincentDondain/3e9ddcdae9291db4f6e620b7f00419fa

Can you please re-try with latest master and provide more info on how to reproduce this?

**Comment by chamons** [comment]
I can't reproduce it now, I'll reopen when I do (with a log this time).
