### ISSUE TITLE
msbuild-mac tests should be running with msbuild in addition to xbuild

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#4110]
Initial bug: https://bugzilla.xamarin.com/show_bug.cgi?id=53164 (moving out of bugzilla due to future read-only mode).

This is a tracking bug for updating the tests to support msbuild.

There are at least two tests that are disabled for now until this is fixed.

They can not be enabled yet, so we don't have the infrastructure to build msbuild tests without using the global install, which does not work on bots.

**Comment by rolfbjarne** [comment]
This will be fixed with https://github.com/xamarin/xamarin-macios/pull/4111 (which makes us switch to MSBuild).

One thing will remain after that PR: the msbuild-specific tests (which are currently disabled) must be enabled.

**Comment by chamons** [comment]
When this lands we need to search for all commented out tests, which might have https://bugzilla.xamarin.com/show_bug.cgi?id=53164 or a link to this issue, since a number of them have been commented out.

**Comment by VincentDondain** [comment]
That and we should now be able to do https://github.com/xamarin/xamarin-macios/issues/3810
