### ISSUE TITLE
Xamarin.Mac Full should internally compile against 4.{5,6,7}-api instead of 4.5 to prevent mono mismatches

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#4116]
This is a request from VSfM components to fix a case that can occur when:

- Using XM System TargetFramework
- On a machine with an "older" mono
- Crashes look like this:

```
System.MissingMethodException: Method 'System.Runtime.InteropServices.Marshal.PtrToStringUTF8' not found.
  at ObjCRuntime.Class.ResolveAssembly (System.IntPtr assembly_name) [0x00025] in <e0fc6dbbbd464bec93f9c51c7060c780>:0 
  at ObjCRuntime.Class.ResolveFullTokenReference (System.UInt32 token_reference) [0x00050] in <e0fc6dbbbd464bec93f9c51c7060c780>:0 
  at ObjCRuntime.Class.ResolveTokenReference (System.UInt32 token_reference, System.UInt32 implicit_token_type) [0x00015] in <e0fc6dbbbd464bec93f9c51c7060c780>:0 
```

The ideal fix is to change XM's platform assembly to compile against an API facade instead of the "real" 4.5 binaries we bundle, since System mono _does not_ necessarily have the same "public but not in real .NET" surface.

**Comment by chamons** [comment]
FYI - @rolfbjarne 
From - @alanmcgovern @ermau

**Comment by alanmcgovern** [comment]
💯 

Awesome!

**Comment by alanmcgovern** [comment]
If you push a branch which makes it compile against the right facade then i can help fix any build errors (as long as i can see the failures)

**Comment by chamons** [comment]
Ok, turns out we _can't_ do this - :(

We use things not in 4.7.1-api even, such as Span (see Compression.cs) and cant' "undo" those.

**Comment by marek-safar** [comment]
If your application is supposed to run on "any" Mono you must compile against stable API. Compiling against lib/4.5 is like compiling against .net 4.5 and expect it to  work on .NET 2.0.

**Comment by alanmcgovern** [comment]
If Xamarin.iOS.dll, Xamarin.Mac.dll and Xamarin.Android.dll have exposed this type in their public API by building it into the product, what options do we have?

**Comment by alanmcgovern** [comment]
To be clear about my intention here - I don't want a guarantee that the final assembly can be loaded under $ancient mono, but we do need a guarantee that Xamarin.Mac.dll does not accidentally compile against 'private' APIs in the `lib/4.5` which would mean the final Xamarin.Mac.dll library can only be loaded under a very specific mono revision.

In other words what we need is a safe profile or we need xamarin.mac.

If the solution is actually to bundle the correct matching mono with the final app, then it's up to Xamarin.Mac to bundle a full desktop mono so we can consume it as part of the build.
