### ISSUE TITLE
No way to configure NSPixelFormat for MonoMacGameView so it will always use legacy OpenGL 2

### ISSUE THREAD

**Issue by ghost** [xamarin/xamarin-macios#4117]
### Steps to Reproduce

1. Create a MonoMacGameView
2. Context will always be legacy OpenGL 2
3. Do not see a way to work around this not even with overriding

### Expected Behavior

A way to set the pixel format to something other then the default

### Actual Behavior

pixel format can not be changed from default

### Environment

Xamarin studio 6.3, Xamarin Mac

MonoMacGameView constructor (NSOpenGLContext arg is for a shared context so that won't help)

**Comment by VincentDondain** [comment]
Indeed it looks like it's not possible to manually set the `NSOpenGLPixelFormat` with this API https://github.com/xamarin/xamarin-macios/blob/master/src/OpenGL/MonoMacGameView.cs#L69-L82.

This seems like a valid request to me but I'm not familiar with the API (there might be reasons to justify it can't be manually set). Maybe @chamons can provide more insights.

**Comment by Mohamed477** [comment]
Duplicate of #

**Comment by VincentDondain** [comment]
@Mohamed477 could you re-link what this is a duplicate of please?

**Comment by rolfbjarne** [comment]
We no longer ship OpenTK in .NET, so this doesn't apply anymore. Please use upstream OpenTK binaries instead (https://github.com/opentk/opentk).
