### ISSUE TITLE
Bump XM's min mono version

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#4120]
Reference: #4116.

We should bump Xamarin.Mac's minimum system mono version to something higher than 4.2: https://github.com/xamarin/xamarin-macios/blob/6a3481db5245c56c8d41b24dbc9f9f57429077ae/runtime/launcher.m#L441-L444 and https://github.com/xamarin/xamarin-macios/blob/6a3481db5245c56c8d41b24dbc9f9f57429077ae/tools/mmp/driver.cs#L123

The question is figuring out which version we should bump to. https://github.com/xamarin/xamarin-macios/issues/4116#issuecomment-391466550 indicates that we should bump to something that has `Span` (5.12? this needs testing).

We should also put this min mono version in our `Versions.plist` (using a key such as `MinSystemMono` with a detailed comment/description of the key)

**Comment by rolfbjarne** [comment]
@chamons is this something you can look at?

**Comment by chamons** [comment]
Yeah I can do it.

**Comment by chamons** [comment]
It appears that 5.10 has System.Span but 5.8 does not:
```
 $ monop -r:/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/4.5/mscorlib.dll | grep System.Span\`1
System.Span`1
```
```
$ monop -r:/Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/4.5/mscorlib.dll | grep Span
```

**Comment by chamons** [comment]
Given https://github.com/xamarin/xamarin-macios/issues/4125 we're bumping this out of 15.8 for now until we can settle on a good number.
