### ISSUE TITLE
NSErrorException's Message property should contain more useful information 

### ISSUE THREAD

**Issue by johannes-schmitt** [xamarin/xamarin-macios#4133]
Enhancement: From my point of view, `NSErrorException`'s `Message` property should contain some information about the underlying `NSError`. `Message` is currently "Exception of type 'Foundation.NSErrorException' was thrown."

Consider a project that logs all unhandled exceptions (via `AppDomain.CurrentDomain.UnhandledException`) to a remote error tracking system (like Sentry) or to a log file. In almost all of the cases, these unhandled exceptions are bugs. The existing `Message` property does not help to understand the root cause of the bug and makes it hard to properly fix it.
 
### Steps to Reproduce
1. in iOS (or macOS) project: `throw new NSErrorException(/* ... */)`
2. in platform independent project (e.g. Xamarin Forms), referencing the project from step 1: `AppDomain.CurrentDomain.UnhandledException += (_, e) => { Console.WriteLine(((Exception)e.ExceptionObject).Message); } ;`

### Expected Behavior
`Message` should at least contain `NSError`'s `Code` to be able to understand what the exception was about.
### Actual Behavior
`Message` is "Exception of type 'Foundation.NSErrorException' was thrown."

**Comment by spouliot** [comment]
Make sense :) 

The most useful information, coming from the native code, is the `Description` property, which we default for `ToString ()` on `NSObject` subclasses, however `NSErrorException` is a subclass of `Exception`.

You can probably workaround this with something like
```var msg = (e as NSErrorException)?.Error.Description ?? e.Message;```
where `e` is an `Exception` subclass, until a release is out with the fix.

**Comment by johannes-schmitt** [comment]
I'm not sure, but I think the `Description` property maps to [NSError's LocalizedDescription](https://developer.apple.com/documentation/foundation/nserror/1414418-localizeddescription). If my assumption holds true, it'll be tough to understand what an error means for a language I don't speak. Especially, in a error tracking system it would be helpful to have some non-localized exception information to be able to understand common error across language borders.

I would suggest to override Message so that `Code` (which is language-neutral) is part of it. Something simple like this:
`public override string Message { get { return $"{error.Description} ({error.Code})"; } }`
Maybe also `Domain` should be included, because `Code` is only unique within a domain.
What do you think?

Regarding your suggested workaround: I implemented a similar approch that uses reflection. Why reflection? The type NSErrorException is not available in the platform-independent project.

**Comment by spouliot** [comment]
I'll check if it's localized after WWDC (or in between sessions)
but the output is already like Domain + Error + Description + Extra (user info)
so I don't think it can be very confusing to get the same data

**Comment by johannes-schmitt** [comment]
I've been some days away from that topic. Coming back now, I agree, `NSError.ToString()` is sufficient. Also other exception messages in the .NET world are actually localized.
