### ISSUE TITLE
How UIMenuController Internationalizes

### ISSUE THREAD

**Issue by LeeCenY** [xamarin/xamarin-macios#4134]
### Steps to Reproduce

1.  Xcode  Project -> Info -> Localizations 
![image](https://user-images.githubusercontent.com/9047094/40600720-16f89ef8-6285-11e8-8dc8-c5f4dc5513cf.png)

)
2.  Using Base Internationalization
3.  

### Expected Behavior

![image](https://user-images.githubusercontent.com/9047094/40600876-8f0813d8-6285-11e8-9f1c-177534b78d4e.png)

![image](https://user-images.githubusercontent.com/9047094/40600974-ddfb3a10-6285-11e8-9a42-1d34084e63f5.png)

### Environment

```
```

**Comment by therealjohn** [comment]
@LeeCenY Thanks for filing an issue! Unfortunately, I am not sure what issue you are having. Could you update your comment with more information and fill out the issue template completely?

In the meantime, you can also double check that you set up your Xamarin.iOS project correctly for localization by [referencing the steps from our documentation](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/).

**Comment by LeeCenY** [comment]
@therealjohn Only in the Xcode Project -> Info -> Localizations add Language type and use base internationalization , the Native Development UIMenuController control can be internationalized, without the need for .strings

**Comment by dalexsoto** [comment]
Hello @LeeCenY 

Those are changes that you do in the info.plist and the [documentation](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/#localization-basics-in-ios) that John pointed out should have had you covered. 

I'll close this issue, if you are still having problems please reopen and fill the issue template and provide us more details of what you are having trouble with.
