### ISSUE TITLE
Xamarin.iOS should remove references to bugzilla

### ISSUE THREAD

**Issue by bholmes** [xamarin/xamarin-macios#4173]
There are several references to bugzilla in our source, docs and error messages.  We should audit the hits and change where appropriate.  

https://github.com/xamarin/xamarin-macios/search?q=%22bugzilla%22&unscoped_q=%22bugzilla%22

For example...

### Expected Behavior
`Xamarin.iOS: Internal consistency error, please file a bug (https://github.com/xamarin/xamarin-macios/issues/new). Additional data: found managed object 0x1275a8ea8=0x7f92d401e080 (Linker.Sealer.Unsealable) in native object 0x600000222c20 (AppDelegate).`

### Actual Behavior
`Xamarin.iOS: Internal consistency error, please file a bug (http://bugzilla.xamarin.com). Additional data: found managed object 0x1275a8ea8=0x7f92d401e080 (Linker.Sealer.Unsealable) in native object 0x600000222c20 (AppDelegate).`

**Comment by spouliot** [comment]
dupe of https://github.com/xamarin/xamarin-macios/issues/3647
