### ISSUE TITLE
Xamarin.iOS Threadpool randomly halts when app is suspended and doesn't recover when resumed

### ISSUE THREAD

**Issue by UmeshKanyal** [xamarin/xamarin-macios#4178]
We are facing exactly the same issue as mentioned in [Bug58633](https://bugzilla.xamarin.com/show_bug.cgi?id=58633#c12)
Do we have any resolution to the above issue?

We also use Bluetooth, geofence, beacon, background location, background fetch. 
The ThreadPool randomly stops processing when the app is suspended and brought to the foreground. The main thread keeps on working but no background thread.
We have observed this issue on one specific iPhone 6s with 11.4 device, it works pretty well on rest of the other devices.

**Comment by UmeshKanyal** [comment]
Hi @dalexsoto, I am using the Visual studio for mac, not sure how can I set 'MONO_LOG_LEVEL=debug' and 'MONO_LOG_MASK=threadpool'.

**Comment by jonathanantoine** [comment]
Hello. Any update on this ? This is quite frightening to have this bug in the wild :(

**Comment by jgiacomini** [comment]
Same for me I had this bug on one my app :(
I don't know how to solve it :'(

**Comment by rolfbjarne** [comment]
The environment variables can be set by adding the following to the additional mtouch arguments in the project's iOS Build options:

    --setenv:MONO_LOG_LEVEL=debug --setenv:MONO_LOG_MASK=threadpool

Any output will be printed to the Application Output in the IDE.

**Comment by rolfbjarne** [comment]
I'm also moving this issue to the mono repo, since that's where the threadpool code is.

**Comment by rolfbjarne** [comment]
This issue was moved to mono/mono#12318
