### ISSUE TITLE
UIGestureRecognizer needs a way of surfacing the token for the default action

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/xamarin-macios#4190]
The UIGestureRecognizer can easily create strong cycles when the action is either capturing the context, or is the instance of a class.   And we currently do not have a way of removing the object.

We need a way to surfacing the "Recognizers" or on first creation the first Token, so users have a way of manually unregistering the getsture recognizer.

There is just no way of getting the "Token" for the first instance, only for any manually added targets (when we return the `Token` value from `AddTarget`).

**Comment by migueldeicaza** [comment]
Probably should also support Dispose().

**Comment by ailen0ada** [comment]
Hello! thank you for your kind!

**Comment by migueldeicaza** [comment]
It might be enough to make the fields WeakReferences.

**Comment by migueldeicaza** [comment]
Some additional notes:

* We can use `[Dispose ("OnDispose")]` as a decoration on `UIGestuzeRecognizer` to have some code run on the `Dispose()` method that will clear the objects in `recognizers`.

* The API that we need to call to unregisters handlers requires both the `NSObject` target and the selector.   Currently `recognizers` only stores the target `NSObject` for the single case, or holds a hashtable of the `NSObjects` in there.   We need to track both targets and selectors (because we use different selectors).

* We likely need to make `recognizers` a Dictionary to track these.

* There is a constructor we surface that takes an NSObject/Selector that we currently do not intercept, so we would not be able to Dispose() that particular one, the user would have to do that.

**Comment by rolfbjarne** [comment]
Fixed with PR #4729.
