### ISSUE TITLE
iOS app crash on SGen when builded with LLVM enabled

### ISSUE THREAD

**Issue by skir** [xamarin/xamarin-macios#4192]
Hello, my Xamarin.iOS application crashes after a set of Http requests when it is builded with LLVM compiler enabled. It looks like SGen issue, but I have SGen disabled in project build options.
Here is [crash log](https://gist.github.com/skir/38ae96ab8f6edc7376fb1affb8a1c314)

### Environment

```
Visual Studio Community 2017 for Mac

Version 7.5.2 (build 40)
Installation UUID: 63db3e6c-8307-4b71-b39f-dda5bd648929
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

NuGet

Version: 4.3.1.4445

Xamarin.Profiler

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools

Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac

Version: 4.4.1.193 (Visual Studio Community)

Xamarin.iOS

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

Xamarin Inspector

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information

Release ID: 705020040
Git revision: cfe2fc0566bc4db990242959de40505a13f58352
Build date: 2018-05-30 11:24:18-04
Xamarin addins: 3ac7413ef51a88e06367313c27aec8f7292752a6
Build lane: monodevelop-lion-d15-7

Operating System

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

```

**Comment by dalexsoto** [comment]
Hello @skir, thanks for the report!

Are you able to reproduce this in a test case that you could share with us?

**Comment by skir** [comment]
Hello @dalexsoto . This application has a complex workflow. Right from the start I make requests to my backend service, open camera view, retrieve user media files from gallery, and load a lot of images in to memory. I can try to create test app with reproducible scenario, but it will take time. 
It would be great to understand why the same code works good without LLVM but fails when it is enabled.

**Comment by mandel-macaque** [comment]
@skir without a smaller test case, and access to your code we might not be able to debug this issue. Is you application private? Do you think you con try an recreate the bug? Else we have a situation because we need to be able to reproduce it to move further.

**Comment by mandel-macaque** [comment]
@skir is the issue still a problem? Have you tested it with one of the new releases (15-7)?

**Comment by rolfbjarne** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!

**Comment by skir** [comment]
Hello, Sorry for the late reply.
For now with Xamarin.iOS 12.0.0.15 the issue is no longer reproducible. 
Thanks everyone for your work.
