### ISSUE TITLE
[Debugger] Add tests to ensure that pdbs point to the correct src paths

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#4202]
The code that install the source has unit tests but we do not have tests that will ensure that the pdbs that are generated for the dlls DOES point to the lib path expected in the users machine. Having a test that does this check will ensure that we do not ship dlls with the wrong pathmaps.

This follows the comment from @spouliot in issue https://github.com/xamarin/xamarin-macios/issues/3724

**Comment by rolfbjarne** [comment]
This is different in .NET, and that problem is tracked here: https://github.com/xamarin/xamarin-macios/issues/14895, so closing this.
