### ISSUE TITLE
The return type of NSDistributedNotificationCenter.DefaultCenter is different from Apple's API.

### ISSUE THREAD

**Issue by P3PPP** [xamarin/xamarin-macios#4225]
[Apple's API Documentation](https://developer.apple.com/documentation/foundation/nsdistributednotificationcenter/1412063-defaultcenter?language=objc)

### Steps to Reproduce

None.

### Expected Behavior

```cs
NSDistributedNotificationCenter notificationCenter = NSDistributedNotificationCenter.DefaultCenter;
```

### Actual Behavior

```cs
NSObject notificationCenter = NSDistributedNotificationCenter.DefaultCenter;
```

### Environment

Xamarin.Mac
Version: 4.4.1.193 (Visual Studio Enterprise)

### Build Logs

None.

### Example Project (If Possible)

None.

**Comment by rolfbjarne** [comment]
This was fixed with PR #4227.
