### ISSUE TITLE
error MT0099 : Internal error : Not all assemblies for Xamarin.Sdk have link tasks.

### ISSUE THREAD

**Issue by kdubau** [xamarin/xamarin-macios#4235]
### Description
Not all apps are affected, I'm not sure what is special about this one in particular. Unfortunately we did not catch this sooner because of a mixup with the SeeingAI teams app repo (it moved and we didn't know so we were still testing their old source). Not sure if it's relevant but it seems a similar issue has cropped up (but resolved) in the community: https://github.com/xamarin/xamarin-macios/issues/4101 

### Steps to Reproduce

1. Install XI 11.10.1.177 or later (15.7 RTW)
2. Clone the SeeingAI app (internal)
3. Build it in Release config

### Expected Behavior

Successful build 

### Actual Behavior

```
2018-06-04T20:16:28.9530910Z (_CompileToNative target) -> 
2018-06-04T20:16:28.9553430Z   error MT0099 : Internal error : Not all assemblies for Xamarin.Sdk have link tasks. Please file a bug report with a test case (http://bugzilla.xamarin.com). [/Users/vsts/agent/2.134.2/work/1/s/iOS/App/SeeingAI.iOS.csproj]
2018-06-04T20:16:28.9562760Z 
```

### Environment

```
Xcode | 9.4.0 | Xcode_9.4.xip
Xamarin.iOS | 11.10.1.177 | xamarin.ios-11.10.1.177.pkg
Xamarin.Mac | 4.4.1.176 | xamarin.mac-4.4.1.176.pkg
Visual Studio for Mac | 7.5.0.1254 | VisualStudioForMac-7.5.0.1254.dmg
Mono | 5.10.1.47 | MonoFramework-MDK-5.10.1.47.macos10.xamarin.universal.pkg
```

### Build Logs

Failed 15.7 RTW (11.10.1.177): http://build.devdiv.io/1745621

This is also reproducible with 15.7 SR3 and Master. (Master -> build.devdiv.io/1764931 - see Release config).

Successful 15.6 (11.9.1.24) : http://build.devdiv.io/1746181 - please ignore the failed Windows build (it's failed due to this bug, only the Mac build in this job is truly using 15.6)

### Example Project (If Possible)
 
Contact me on Slack and we can work out getting you access to SeeingAI app.

**Comment by spouliot** [comment]
@rolfbjarne can you have a look ? thanks!

**Comment by kdubau** [comment]
I'll update with 15.8 results as soon as I have them (in progress).

**Comment by kdubau** [comment]
This issue also exists in 15.8 (11.14.0.4) http://build.devdiv.io/1768483 (see Release config build).

**Comment by rolfbjarne** [comment]
I can reproduce.

**Comment by SaqibS** [comment]
Hi, we temporarily got around this by forcing the system to use Mono 5.8.1, as recommended by the team. However, it would be good to get rid of this, yet the problem persists with Mono 5.12.0 and Xamarin.iOS 12.0. Appreciate any assistance.

**Comment by rolfbjarne** [comment]
@SaqibS this issue is fixed in Xamarin.iOS 12.0, so you might be running into something else. Could you file a new issue and include a test project we can use to reproduce your problem?

**Comment by yevgeniy-seleznev** [comment]
This still reproes with Mono 5.16, xamarin.ios 12.2.1.11, using Seeing AI app as the test. The ultimate mtouch error looks suspiciously like the original issue:

error MT0099 : Internal error : Not all assemblies for Xamarin.Sdk have link tasks. Please file a bug report with a test case (http://bugzilla.xamarin.com). [/Users/vsts/agent/2.144.0/work/1/s/iOS/App/SeeingAI.iOS.csproj

Still, I am going to go ahead and create a new bug and attach the full build log as you requested. Just a heads up. Thanks
