### ISSUE TITLE
Xamarin.Linker.SdkTest.NoAssemblyReferenceInAttributes fails with monotouch 

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#4241]
Using the [natural language PR](https://github.com/xamarin/xamarin-macios/pull/4236) as an example. 

The tests ran fine on [initially](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/7342//Test_Report/) but started failing on [later builds](https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/7346//Test_Report/). 

Beware that the failing tests (in the natural lang API) where failing because 32 devices were not running the latests iOS and those failures can be considered noise.

**Comment by rolfbjarne** [comment]
This was fixed in the xcode10 branch here: https://github.com/xamarin/xamarin-macios/commit/ddd7d4cc19b2c3429c116d87f62cbb61c32b38a5.
