### ISSUE TITLE
Missing ICScannerDeviceDelegate/ICDeviceBrowserDelegate bindings make IKScannerDeviceView difficult to use

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#4273]
As noted here: https://forums.xamarin.com/discussion/128020/how-to-use-imagekit-ikscannerdeviceview-to-access-a-scanner-device

You apparently need 3 delegates to use this view:

https://stackoverflow.com/questions/12326156/how-to-use-ikscannerdeviceview-in-cocoa

I've posted the signatures here:

https://gist.github.com/chamons/9eb235fa8690a6e57960e8d0a50c18c0

and should be able to be manually Exported, but this is an ugly hack.

### Steps to Reproduce

1. Try to use IKScannerDeviceView
2. Find https://stackoverflow.com/questions/12326156/how-to-use-ikscannerdeviceview-in-cocoa
3. Find that we don't bind some of the APIs

### Expected Behavior

All of needed APIs or none of them are shipped

**Comment by migueldeicaza** [comment]
I have a pull request for this:

https://github.com/xamarin/xamarin-macios/pull/4404
