### ISSUE TITLE
Unrecognized selector sent to instance 0x1658dfc0 - Native reference

### ISSUE THREAD

**Issue by sinappsys** [xamarin/xamarin-macios#4274]
Hi,
Since I installed the version of Xamarin.iOS 11.12 and xcode 9.4 I have a problem with a native library. The app crashes.

This is the example project:
https://github.com/NAXAM/accountkit-ios-binding

Method: "auth.LoginWithAccountKit(AKFLoginType.Phone, AKFResponseType.AuthorizationCode);" 
Error: "-[AKFActionController initWithNavigationController:]: unrecognized selector sent to instance 0x14e3ef80".

If I set the linker with "Don't Link" it works.
If I set the linker with "Link Framework SDKs Only" does not work.

In previous versions of Xamarin.iOS and xcode it also worked correctly with "Link Framework SDKs Only".

How to solve?

### Info
Visual Studio 2017 - version 15.7.2
Xamarin.iOS 11.12 
xcode 9.4

### Build Logs

2018-06-15 16:33:12.624 Demo[532:167452] -[AKFActionController initWithNavigationController:]: unrecognized selector sent to instance 0x14e3ef80
Unhandled Exception:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[AKFActionController initWithNavigationController:]: unrecognized selector sent to instance 0x14e3ef80
Native stack trace:
	0   CoreFoundation                      0x1df97b55 <redacted> + 152
	1   libobjc.A.dylib                     0x1d21f067 objc_exception_throw + 38
	2   CoreFoundation                      0x1df9cfd1 <redacted> + 0
	3   CoreFoundation                      0x1df9b0c3 <redacted> + 696
	4   CoreFoundation                      0x1dec3dc8 _CF_forwarding_prep_0 + 24
	5   Demo                                0x000639bd -[AKFNavigationController initWithRootViewController:loginController:appEventsLogger:] + 180
	6   Demo                                0x00069025 -[AKFPhoneLoginController startWithPhoneNumber:state:] + 274
	7   Demo                                0x0005894f -[AKFAccountKit viewControllerForPhoneLoginWithPhoneNumber:state:] + 104
	8   Demo                                0x00236af0 wrapper_managed_to_native_ApiDefinition_Messaging_IntPtr_objc_msgSend_intptr_intptr + 220
	9   Demo                                0x0020cd9c Facebook_Accountkit_AKFAccountKit_ViewControllerForPhoneLogin + 300
	10  Demo                                0x00072d50 Demo_AccountKitAuth_LoginWithAccountKit_Facebook_Accountkit_AKFLoginType_Facebook_Accountkit_AKFResponseType + 600
	11  Demo                                0x000725f0 Demo_ViewController_UIButton3_TouchUpInside_UIKit_UIButton + 184
	12  Demo                                0x001912a0 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 232
	13  Demo                                0x00273fc7 mono_jit_runtime_invoke + 822
	14  Demo                                0x002c0101 mono_runtime_invoke_checked + 102
	15  Demo                                0x002c2a7d mono_runtime_invoke + 50
	16  Demo                                0x0006fa6f _ZL30native_to_managed_trampoline_8P11objc_objectP13objc_selectorPP11_MonoMethodP8UIButtonj + 326
	17  Demo                                0x0006f925 -[ViewController UIButton3_TouchUpInside:] + 46
	18  UIKit                               0x231fe3b5 <redacted> + 76
	19  UIKit                               0x231fe349 <redacted> + 62
	20  UIKit                               0x231e8979 <redacted> + 478
	21  UIKit                               0x231fdc85 <redacted> + 604
	22  UIKit                               0x231fd7cf <redacted> + 2094
	23  UIKit                               0x231f870f <redacted> + 2798
	24  UIKit                               0x231ca2bb <redacted> + 308
	25  UIKit                               0x2395d7f7 <redacted> + 2254
	26  UIKit                               0x2395819b <redacted> + 4186
	27  UIKit                               0x2395857d <redacted> + 144
	28  CoreFoundation                      0x1df53fdd <redacted> + 12
	29  CoreFoundation                      0x1df53b05 <redacted> + 424
	30  CoreFoundation                      0x1df51f51 <redacted> + 1160
	31  CoreFoundation                      0x1dea51af CFRunLoopRunSpecific + 470
	32  CoreFoundation                      0x1dea4fd1 CFRunLoopRunInMode + 104
	33  GraphicsServices                    0x1f64fb41 GSEventRunModal + 80
	34  UIKit                               0x2322da53 UIApplicationMain + 150
	35  Demo                                0x001f5340 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 288
	36  Demo                                0x001e2504 UIKit_UIApplication_Main_string___intptr_intptr + 52
	37  Demo                                0x001e24c4 UIKit_UIApplication_Main_string___string_string + 200
	38  Demo                                0x00071aa8 Demo_Application_Main_string__ + 152
	39  Demo                                0x001912a0 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 232
	40  Demo                                0x00273fc7 mono_jit_runtime_invoke + 822
	41  Demo                                0x002c0101 mono_runtime_invoke_checked + 102
	42  Demo                                0x002c3f33 mono_runtime_exec_main_checked + 66
	43  Demo                                0x002610d9 mono_jit_exec + 194
	44  Demo                                0x00347dd0 xamarin_main + 2424
	45  Demo                                0x0007197f main + 102
	46  libdyld.dylib                       0x1d6924eb <redacted> + 2

**Comment by mandel-macaque** [comment]
@sinappsys I am not an expert in the Facebook API but looking in the headers of the attached framework I can see that AKFActionController is a protocol and not an class. And the protocol does not have the initWithNavigationController. Could you please double check your bindings, since it looks like an error in them. I noticed that AKFActionController uses both [Protocol] and [Model] and looking at the headers, I would bind it just using the protocol attr.

**Comment by sinappsys** [comment]
I solved.

I tried another working component.
https://github.com/xamarin/FacebookComponents/tree/master/Facebook.AccountKit.iOS/source/Facebook.AccountKit

Thanks

**Comment by therealjohn** [comment]
Thanks for letting us know. Please reopen if you run into the same issue again.

**Comment by tuyen-vuduc** [comment]
@sinappsys The issue is fixed in Naxam repository.
