### ISSUE TITLE
Extrospection tests do not report some missing methods in categories

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#4285]
While running the xtro tests (make insane etc..) to detect missing API I noticed that some methods where missing, sample PR: https://github.com/xamarin/xamarin-macios/pull/4268

**Comment by VincentDondain** [comment]
I fixed the `missing-protocol-conformance` when protocols are defined in categories a while ago. https://github.com/xamarin/xamarin-macios/pull/4268

@mandel-macaque can you provide concrete examples in this issue for the APIs (in categories) you noticed weren't reported by xtro? It's not clear to me with your PR.

**Comment by mandel-macaque** [comment]
@VincentDondain the PR is an example.

**Comment by VincentDondain** [comment]
Ok so the methods in the linked PR were not reported by xtro. Thanks.

_Sample PR wasn't clear to me :P_

**Comment by spouliot** [comment]
Adding back `need-info` since there's no information about what xtro is not reporting.

Like mentioned above the API from the PR are reported as missing if commented.
```
!missing-selector! NSExtensionContext::dismissNotificationContentExtension not bound
!missing-selector! NSExtensionContext::notificationActions not bound
!missing-selector! NSExtensionContext::performNotificationDefaultAction not bound
!missing-selector! NSExtensionContext::setNotificationActions: not bound
```

@mandel-macaque please double check, thanks!

**Comment by mandel-macaque** [comment]
This got fixed. I did a double check, closing the issue.
