### ISSUE TITLE
Native Binding Build Error: Missing BindingImpl, BindingImplAttribute, BindingImplOptions

### ISSUE THREAD

**Issue by comfr3ak** [xamarin/xamarin-macios#4299]
### Steps to Reproduce

1. Create Xamarin.iOS Native Binding Project
2. Import some functions generated from Objective Sharpie that includes a delegate

    // typedef void (^AccessoryCallback)(AccessoryCallbacks);
    delegate void AccessoryCallback(AccessoryCallbacks arg0);

3. Build and get errors about BindingImplOptions does not exist

: error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)

### Expected Behavior

It should build

### Actual Behavior

Receive errors that BindingImpAttributes, BindingImpl, and BindingImplOptions cannot be found in Trampolines.g.cs

### Environment

```
Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA930
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA930
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA930
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Clang with Microsoft CodeGen   14.0.25516
Clang with Microsoft CodeGen

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual C++ for Cross Platform Mobile Development (Android)   14.0.25401.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   14.0.25401.00
Visual C++ for Cross Platform Mobile Development (iOS)

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.753 (f0f46392f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.96 (a702a9ceb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS   11.9.1.24 (f62de47)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS and Xamarin.Mac SDK   11.9.1.24 (f62de47)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs

1>------ Rebuild All started: Project: iXpandBindingslib, Configuration: Release Any CPU ------
1>  Connecting to Mac server 192.168.1.126...
1>  Connecting to Mac server 192.168.1.126...
1>C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.ObjCBinding.CSharp.targets(60,3): warning : The using directive for `ExternalAccessory' appeared previously in this namespace
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2940,5): warning MSB9004: ManifestResourceWithNoCulture item type is deprecated. Emit EmbeddedResource items instead, with metadata WithCulture='false', Type='Resx', and optional LogicalName.
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(48,4,48,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(48,4,48,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(46,3,46,14): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(48,52,48,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(48,17,48,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(46,3,46,14): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(46,51,46,69): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(46,16,46,34): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(53,4,53,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(53,4,53,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(53,52,53,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(53,17,53,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(66,4,66,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(66,4,66,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(66,52,66,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(66,17,66,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(73,4,73,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(73,4,73,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(73,52,73,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(73,17,73,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(81,4,81,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(81,4,81,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(81,52,81,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(81,17,81,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(102,4,102,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(102,4,102,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(102,52,102,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(102,17,102,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(113,4,113,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(113,4,113,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(113,52,113,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(113,17,113,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(79,5,79,16): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(79,5,79,16): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(79,53,79,71): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(79,18,79,36): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(126,4,126,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(126,4,126,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(126,52,126,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(126,17,126,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(136,4,136,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(136,4,136,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(136,52,136,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(136,17,136,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(149,4,149,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(149,4,149,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(149,52,149,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(149,17,149,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(162,4,162,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(162,4,162,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(162,52,162,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(162,17,162,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(175,4,175,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(175,4,175,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(175,52,175,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(175,17,175,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(188,4,188,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(188,4,188,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(188,52,188,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(188,17,188,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(201,4,201,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(201,4,201,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(201,52,201,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(201,17,201,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(214,4,214,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(214,4,214,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(214,52,214,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(214,17,214,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(223,4,223,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(223,4,223,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(223,52,223,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(223,17,223,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(234,4,234,15): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(234,4,234,15): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(234,52,234,70): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\iXpandBindingslib\iXpandSystemController.g.cs(234,17,234,35): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(87,5,87,16): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(87,5,87,16): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(87,53,87,71): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(87,18,87,36): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(94,5,94,16): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(94,5,94,16): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(94,53,94,71): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(94,18,94,36): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(108,5,108,16): error CS0246: The type or namespace name 'BindingImplAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(108,5,108,16): error CS0246: The type or namespace name 'BindingImpl' could not be found (are you missing a using directive or an assembly reference?)
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(108,53,108,71): error CS0103: The name 'BindingImplOptions' does not exist in the current context
1>C:\2020CAM\RELEASE_4\RELEASE_4_X\CLIENT_GEN_2\1CS\iXpandBindingslib\obj\Release\ios\ObjCRuntime\Trampolines.g.cs(108,18,108,36): error CS0103: The name 'BindingImplOptions' does not exist in the current context
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by comfr3ak** [comment]
[Trampolines.g.cs.zip](https://github.com/xamarin/xamarin-macios/files/2119664/Trampolines.g.cs.zip)

**Comment by VincentDondain** [comment]
Hi, would it be possible for you to provide your binding project and the native library you're bindings as a test case so we can reproduce the issue?

**Comment by VincentDondain** [comment]
Otherwise @rolfbjarne any idea? IIRC you added those new attributes.

**Comment by comfr3ak** [comment]
Here is the entire project which includes the native library. 
[iXpandBindingslib.zip](https://github.com/xamarin/xamarin-macios/files/2119925/iXpandBindingslib.zip)

**Comment by spouliot** [comment]
> Xamarin.iOS   11.9.1.24 (f62de47)

Either
1. Update to a newer version of Xamarin.iOS; or
2. Rebuild the binding assembly with your current version of Xamarin.iOS

What happens is that you have a binding library (binary) that was compiled with a more recent version of Xamarin.iOS (e.g. 11.10). Your older 11.9 version does not have the new attributes and you get this build failure.

**Comment by comfr3ak** [comment]
How do I get it to update to 11.10?

**Comment by comfr3ak** [comment]
Looks like I need to ditch VS2015 for VS2017, would that correct this problem?

**Comment by VincentDondain** [comment]
Please follow these documents to update our Xamarin packages on VS Windows: https://docs.microsoft.com/en-us/xamarin/cross-platform/get-started/installation/windows-preview and https://blog.xamarin.com/staying-date-visual-studio-2017-xamarin-updater/.

**Comment by comfr3ak** [comment]
Upgraded to VS2017, built the binding project without issue. However, when I added it as a reference to my Xamarin iOS project, there are no methods or classes visible on the binding project dll library. Is this a separate issue I should open or something obvious that I need to check or change? Project attached.
 
[iXpandBindingslib.zip](https://github.com/xamarin/xamarin-macios/files/2120824/iXpandBindingslib.zip)

**Comment by mikestuck** [comment]
has anyone got this message when compiling a project with reference to the library 

error MT3001: Could not AOT the assembly '/Users/username/DVSport/shuttle-2/Shuttle/obj/iPhone/Debug/device-builds/ipad7.3-11.2/mtouch-cache/Build/iXpandBindingslib.dll'

**Comment by mikestuck** [comment]
Solved the above issue and now have 104 duplicate symbols
