### ISSUE TITLE
Default MasterDetail template crashes with Xcode 10 beta 2

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#4305]
### Steps to Reproduce

1. Create a new iOS Master Detail template
2. Launch on iOS simulator (with Xcode 10 beta 2 selected)
3. App crashes

### Expected Behavior

The app shouldn't crash.

_Note: workaround, enable the linker._

### Actual Behavior

https://gist.github.com/VincentDondain/d4dc8d59052a311264211833b2739761

### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.5.2 (build 40)
Installation UUID: 00d602ef-271b-479b-9054-0433b5797215
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0-preview2-25407-01
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0-preview2-006497
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14274.19)
Build 10L177m

=== Xamarin.Mac ===

Version: 4.99.0.74 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.99.0.74 (Visual Studio Enterprise)
Hash: 5ef269076
Branch: arkit-b2
Build date: 2018-06-20 12:16:21-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Enterprise)
Android SDK: /Users/vidondai/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3 (API level 10)
		4.3 (API level 18)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705020040
Git revision: cfe2fc0566bc4db990242959de40505a13f58352
Build date: 2018-05-30 11:24:18-04
Xamarin addins: 3ac7413ef51a88e06367313c27aec8f7292752a6
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

AddinMaker 1.4.2
NuGet Package Explorer 0.2
Internet of Things (IoT) development (Preview) 7.5

```

### Build Logs

https://gist.github.com/VincentDondain/ae113d4a50f813ccfdc088aefad8143f
### Example Project (If Possible)

See repro steps.

**Comment by VincentDondain** [comment]
Similar issues happen to the SingleView and Tabbed templates. Not sure it's worth opening issues for each case. Templates behave correctly with the linker on.

**Comment by spouliot** [comment]
_In iOS 8 and later, you can use the UISplitViewController class on all iOS devices; in previous versions of iOS, the class is available only on iPad._
https://developer.apple.com/documentation/uikit/uisplitviewcontroller?changes=_8&language=objc

Not quite sure how the linker helps, likely something is reflected and cause a different code path to be taken.

**Comment by GouriKumari** [comment]
Automation tests included only single view template and rest of the  tests were not included in the RD. All the basic template tests will be included in automation test run starting with beta5.

**Comment by GouriKumari** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638589 is a bug reported by QA with Xcode10 beta2 and the issue seems to be a duplicate. The issue is fixed on enabling linker.

**Comment by mandel-macaque** [comment]
After testing the template we found the following:

1. Using the default settings, on debug|sim the exception is raised.
2. Using the default settings, on release|sim the exception does not occur.

@VincentDondain confirmed this and discovered a more interesting fact, passing `--registrar:static` to the sim/debug build fixes the issue.

**Comment by GouriKumari** [comment]
I created a  Forms app from Blank forms app and Forms app template. In both cases, app crashes on launching on simulator in debug mode. Adding static registrar fixes the issue in both cases.

Screencast: https://www.screencast.com/t/pWV42CWE6owm

Test Env: https://gist.github.com/GouriKumari/77c54ade6de5c2cc8426d70b20731fc6

**Comment by mandel-macaque** [comment]
So I have been tested with the latests Xcode10 branch and Xcode 10 beta 6 and I cannot longer reproduce the issue with the attached project:


[CleanMasterDetail.zip](https://github.com/xamarin/xamarin-macios/files/2297097/CleanMasterDetail.zip)

**Comment by mandel-macaque** [comment]
@VincentDondain can you please test the attached project?

**Comment by mandel-macaque** [comment]
To be clear, please use the [following environment for the testing.](https://gist.github.com/mandel-macaque/f977c7348405f6204fd45665753a6757)

**Comment by VincentDondain** [comment]
This appears to be fixed in Xcode 10 beta 6 now. 🎉

**Comment by VincentDondain** [comment]
Seems like the fix is more an XI built with Xcode 10 beta 6 (e.g:
https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10/347f472b033073e732b05b33a7e6fe93b37a3d49/145/package/xamarin.ios-11.99.3.243.pkg) than just installing the Xcode 10 beta 6 command line tools as I initially thought.
