### ISSUE TITLE
iOS bundle signing manual provisioning issue with visual studio 2017

### ISSUE THREAD

**Issue by ColeXm** [xamarin/xamarin-macios#4309]
When I go to my iOS project properties / bundle signing tab and change the signing identity from developer (automatic) to my distribution identity, and also change the provisioning profile from automatic to the required one, when I save the changes and re-open the project properties they have reset back to what they were before.

I'm using the latest version .
Visual studio: 15.7.4
Xamarin.iOS : 11.12.0.4
XCode: 9.4

> VS bug [#638030](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638030), VS bug [#638031](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638031)

**Comment by VincentDondain** [comment]
Hi, this is a problem with the IDE (provisioning).

I added a special label for triaging purposes but be advised that you will get better support by reporting a new issue with Visual Studio 2017 directly within the IDE. Simply use Help > Send Feedback > Report a Problem to file your issue.

**Comment by emaf** [comment]
Hi @ColeXm, 
We've fixed this issue and it'll be released in Visual Studio 15.8 Preview 3.

Thanks!
