### ISSUE TITLE
CarPlay.CPTravelEstimates.TimeRemaining should be TimeInterval (fp seconds) or TimeSpan 

### ISSUE THREAD

**Issue by lobrien** [xamarin/xamarin-macios#4319]
### Steps to Reproduce

1. Using initial iOS 12 bindings, create a new iOS app.  
2. Open the Assembly Browser and navigate to `CarPlay.CPTravelEstimates.TimeRemaining`
3. Notice that the type is `double`
4. What are the units? Seconds, ticks, etc.? (The answer is seconds. See https://developer.apple.com/documentation/carplay/cptravelestimates/2968410-timeremaining)

### Expected Behavior

The type system should make ambiguous data less unambiguous. 

### Actual Behavior

The interpretation of the property requires reading documentation. 

### Environment

```
=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.4 Preview (7.4 build 884)
Installation UUID: 2a316060-703e-467c-87bd-5d84f5200e4b
Runtime:
	Mono 5.8.0.108 (2017-10/9aa78573ee2) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000108

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

A valid Xcode installation was not found at the configured location: '/Applications/Xcode9-GM.app'

=== Xamarin.Mac ===

Version: 4.99.0.62 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.8.0.8 (Visual Studio Community)
Hash: eaff169d
Branch: d15-6
Build date: 2018-01-09 18:39:05-0500

=== Xamarin.Android ===

Version: 8.2.0.6 (Visual Studio Community)
Android SDK: /Users/lobrien 1/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0-beta1+69
Hash: 4012b4e
Branch: master
Build date: Thu, 07 Dec 2017 16:20:26 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704000884
Git revision: d383ef2e3a41f2c5071929bbf509796816f4599e
Build date: 2018-01-11 02:34:20-05
Xamarin addins: ae86035c1173492d6ade401296b20c4a5e0e7205
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Mon Jun  4 20:32:31 PDT 2018
    root:xnu-4570.70.19.100.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

AddinMaker 1.4.2
Internet of Things (IoT) development (Preview) 7.1

```

**Comment by spouliot** [comment]
Good point.

We can't subclass `Double` to `NSTimeInternal` but we could probably extend `BindAs` to support the conversion of `double` values as `TimeSpan`.

c.c. @dalexsoto @rolfbjarne

**Comment by rolfbjarne** [comment]
Yeah, this looks like the perfect scenario for a `BindAs` improvement.

**Comment by dalexsoto** [comment]
@rolfbjarne if you do not mind I want to take this over and spam lots of questions to you 😄

**Comment by rolfbjarne** [comment]
@dalexsoto that sounds like a great plan 👍  😄

**Comment by dalexsoto** [comment]
@rolfbjarne / @spouliot after looking at it a second time this does not look like a completely good idea, `TimeSpan` is backed by a `long` and `NSTimeInverval` is backed by a `double` maybe doing this conversion once might be acceptable but cumulative ones might result in rounding errors.

As an alternative we could use `[Advice ("")]`.

Maybe I am being paranoid here what do you guys think?

**Comment by rolfbjarne** [comment]
I don't like rounding errors, and IMHO losing information in the translation from native to managed is a bad idea, so I'd continue binding this as double (and add Advice attributes).

**Comment by spouliot** [comment]
Closing the issue, let's discuss solutions on https://github.com/xamarin/xamarin-macios/issues/4364
