### ISSUE TITLE
Smart Enums are not handled correctly on HealtKit.

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#4324]
Smart Enums added under src/HealthKit/Enums.cs are not correctly processed. This make the binding a little uglier because they have to be added in the main api.cs file. This does not occur with other bindings.

The following gist shows an example of what does not work:

https://gist.github.com/mandel-macaque/b42fe978cad88b7f965d52a53ddbd3fa

**Comment by spouliot** [comment]
File needs to be in `*API_SOURCES` to be given to the generator
along with the binding, e.g. `healthkit.cs`, file
`*CORE_SOURCES` works (needed for compatibility) as long as you don’t need the generator support for smart enums
