### ISSUE TITLE
Error MT4125 when building an iOS app which depends on an iOS binding project which references ObjRuntime.INativeObject

### ISSUE THREAD

**Issue by lukepothier** [xamarin/xamarin-macios#4332]
### Steps to Reproduce

1. Create an iOS binding project which includes a reference to the type ObjCRuntime.INativeObject
2. Create an iOS app which depends on the iOS binding project
3. Build the iOS app (with App Center)

### Expected Behavior

App builds successfully

### Actual Behavior

App fails to build with error `MTOUCH : error MT4125: The registrar found an invalid type 'ObjCRuntime.INativeObject' in signature for method '<redacted>': The interface must have a Protocol attribute specifying its wrapper type.`

### Environment

**Build _fails_ on App Center**:
* Mono v5.10.1
* Xcode v9.4

**NOTE: Everything works with my VS installation**:

Microsoft Visual Studio Enterprise 2017 
Version 15.7.3
VisualStudio.15.Release/15.7.3+27703.2026
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.10.10.1 (f1760154c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by therealjohn** [comment]
@lukepothier Would you please include the log files from app center? If this contains private info, please email me an attachment or link to download them. Also, it would be helpful to [include the diagnostic build logs](https://github.com/xamarin/xamarin-macios/wiki/Submitting-Bugs-&-Suggestions#writing-good-bug-reports-and-feature-requests) from your local build too. If you can attach a sample project that has the necessary code, that would be great!

**Comment by lukepothier** [comment]
Thanks @therealjohn - I'm going to try to get clearance to send you App Center and build logs.

**Comment by mandel-macaque** [comment]
@lukepothier any information regarding the inclusion of the App Centre and build logs? I will close the issue to keep our backlog clean but please feel free to reopen the issue and add any extra information that you might have. Thanks in advance.
