### ISSUE TITLE
Share extension doesn't work for App Store apps

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#4337]
### Steps to Reproduce

1. New solution Mac app
2. Set info.plist bundle identifier
3. Enable App Sandbox in Entitlements.plist
4. Create provisioning profile on Apple Developer and set the app to be signed with it
5. Add share extension to solution and edit info.plist so that 
6. Set info.plist bundle identifier to [step 2 identifier].share for extension
7. Create provisioning profile on Apple Developer for the extension and set the extension to be signed with it
8. Run the app
### Expected Behavior
Extension should appear among extensions as it would on iOS app
### Actual Behavior
Extensions doesn't appear
### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: f546b303-006e-4f34-8fa8-4662985b4489
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4 (14160)
Build 9F1027a

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/ivanicin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.5


```

### Example Project (If Possible)

[dummy.zip](https://github.com/xamarin/xamarin-macios/files/2134947/dummy.zip)

**Comment by therealjohn** [comment]
I believe I reproduced this. When I run the project, I don't see any Share extensions listed in Preferences.

**Comment by ivanicin** [comment]
I am not sure exactly what has changed, but after adding the new share extension project on the sandboxed app in the latest version seems to be working fine.

**Comment by ivanicin** [comment]
As my app has failed the App Store certification and after my tests, I can confirm that this is not working again with the latest Xamarin.Mac. I've tried to revert to Visual Studio 2017 but it didn't help and I've also tried to uninstall Xamarin.Mac and after the installation of VS 2017 it has the build date 2019-02-12 and the problem still appears.

As the window in which the problem appears is quite narrow (as you can see in Dec 2018 this worked), I hope this can be fixed easily.

**Comment by ivanicin** [comment]
My mistake, it is still working properly, sorry.
