### ISSUE TITLE
Unable to open a storyboard file via Xcode

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4339]
### Steps to Reproduce

1. Create XM application 
2. Open the `Main.storyboard` file

### Expected Behavior
The file is opened via Xcode.

### Actual Behavior
Xcode shows next message:
```
Project '.../test/obj/Xcode/0/test.xcodeproj' cannot be opened because the project file cannot be parsed.
```

### Environment

1. Visual Studio for Mac 7.6 (build 1806)
https://gist.github.com/mykyta-bondarenko-gl/09e39fded28ad50fe46850172b2089e4
2. `xcode-select -p`
"/Applications/Xcode.app/Contents/Developer"
3. VSfM -> Preferences -> SDK Locations -> Apple -> Apple SDK Location
"/Applications/Xcode.app"

### Build Logs

1. VSfM log
https://github.com/xamarin/xamarin-macios/files/2137301/Xcode4Sync.2018-06-26__16-23-23.log

**Comment by jstedfast** [comment]
This is fixed in md-addins master
