### ISSUE TITLE
[Xcode10] Getting "ERROR ITMS-90265" while submitting the MAC Cool App to AppStore.

### ISSUE THREAD

**Issue by GLjackyvaswani** [xamarin/xamarin-macios#4350]
Description:
Getting below error while submitting the MAC Cool App to AppStore.
ERROR ITMS-90265: "The key LSMinimumSystemVersion in the Info.plist file, which has the value '10.14', must have a value between 10.4 and 10.13.5. For more information, see the Information Property List Key Reference."

===========================================

Steps:
1. Download the latest Submission samples from [https://github.com/xamarin/SubmissionSamples]
2. Open MacCoolApp > Set the deployment target to "10.14"
3. Archive the app & try to submit the app to Appstore.

Actual:
App store submission fail with error ERROR ITMS-90265.

Expected: 
App should get submitted to App store without any error.

===========================================

Environment:
Version 7.5.4 (build 3)
Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
Xamarin.Mac Version: 4.99.0.93
Xamarin.iOS Version: 11.99.0.93
Xamarin.Android Version: 8.3.3.2
Operating System Mac OS X 10.13.4
Apple Developer Tools Xcode 10.0 (14274.19) Build 10L177m

Build Info: https://gist.github.com/GLjackyvaswani/febdd85bddb69339525cb4332ad7a3e6

===========================================

Screencast: https://www.screencast.com/t/iWx8cYUQAK7A

===========================================

Appstore error logs: https://gist.github.com/GLjackyvaswani/be2d8391a60ea7fb02b909d87754cdce
Reproducibility : 100%

===========================================

Test plan: https://testrail.xamarin.com/index.php?/plans/view/55573
Test case Link: https://testrail.xamarin.com/index.php?/tests/view/24456304&group_by=tests:assignedto_id&group_order=asc&group_id=-1

**Comment by spouliot** [comment]
That's totally normal, Apple does **not** accept submissions using beta software/toolchain.
Such test will only work once 10.14 becomes public (next fall)
