### ISSUE TITLE
[Xcode10] [High Sierra] Deployment target "10.13" is not displayed while creating any MAC APP(Cocoa, Scene Kit, SpritKit etc)

### ISSUE THREAD

**Issue by GLjackyvaswani** [xamarin/xamarin-macios#4351]
Description:
Deployment target "10.13" is not displayed while creating any MAC APP(Cocoa, Scene Kit, SpritKit etc)
10.13 is even not displayed for info.plist.

=====================================================

Note:
Issue not reproducible with MAC OS 10.14.

=====================================================

Steps:
1. Create a Mac template application (Cocoa App, Scene Kit, Sprit Kit etc)
2. Check for the deployment target.

Actual: 
Deployment target displayed as Sierra (10.12).
After Creating the APP, open info.plist & check that Deployment target displayed as 10.12, 10.14. "10.13" is missing in info.plist as well.

Expected:
Deployment target should displayed as 10.13 by default

=====================================================

Environment:
Version 7.5.4 (build 3)
Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
Xamarin.Mac Version: 4.99.0.93
Xamarin.iOS Version: 11.99.0.93
Xamarin.Android Version: 8.3.3.2
Operating System Mac OS X 10.13.4
Apple Developer Tools Xcode 10.0 (14274.19) Build 10L177m

Build Info: https://gist.github.com/GLjackyvaswani/febdd85bddb69339525cb4332ad7a3e6

=====================================================
Priority: 0

=====================================================

Screencast: https://www.screencast.com/t/Kfo8DTZPBj

Reproducible: 100%

=====================================================

Testplan: https://testrail.xamarin.com/index.php?/plans/view/55573
Test case link: https://testrail.xamarin.com/index.php?/tests/view/24456321&group_by=tests:assignedto_id&group_order=asc&group_id=-1

=====================================================

Attaching the logs for more detail.
[Ide.2018-06-27__18-52-30.log](https://github.com/xamarin/xamarin-macios/files/2141539/Ide.2018-06-27__18-52-30.log)

> VS bug [#676661](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/676661)

**Comment by rolfbjarne** [comment]
This works fine for me:

<img width="1296" alt="screenshot 2018-09-03 12 23 21 cropped" src="https://user-images.githubusercontent.com/249268/44981994-9410db80-af74-11e8-90a0-5b2b43ee1271.png">

is this what you meant?
