### ISSUE TITLE
op_Implicit(string) for string returns a method that returns char[]

### ISSUE THREAD

**Issue by activa** [xamarin/xamarin-macios#4372]
### Steps to Reproduce

```
var implicitOp = typeof(string).GetMethod("op_Implicit", new[] {typeof(string)});

object result = implicitOp.Invoke(null,new object[] {"x"});
// result is of type char[] : ['x']
```
### Expected Behavior

`typeof(string).GetMethod("op_Implicit",new[] {typeof(string)})` should return null or at least a method that returns a string, not a char[] array

### Actual Behavior

`typeof(string).GetMethod("op_Implicit",new[] {typeof(string)})` returns a method that returns a char array representation of the string parameter

### Environment

Xamarin.iOS 11.12.0.4
Visual Studio 2017 15.7.3

**Comment by activa** [comment]
BTW, this works fine on Xamarin.Android

**Comment by migueldeicaza** [comment]
This is expected, the method that you are calling is retrieveing implicit operators that take a string, and returning the first match it finds.   Your version probably already has the new overloads for `ReadOnlySpans`:

```
public static implicit operator ReadOnlySpan<char> (string value);
```

For implicit operations, you need to retrieve all the methods, and iterate until you find the one that has the proper return type or use a custom `Binder` as described here:

https://msdn.microsoft.com/en-us/library/4s2kzbw8(v=vs.110).aspx
