### ISSUE TITLE
Linking problem after upgrade to iOS 11.4 with Zebra dll libzsdk_iosx.dll.dylib

### ISSUE THREAD

**Issue by twanvermetten** [xamarin/xamarin-macios#4376]
### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
Native linking failed for '/Users/twan/Library/Caches/Xamarin/mtbs/builds/SQ_Mobile_Med.iOS/e7ad5f1b35db29731e2fdba27eaea9f2/obj/iPhone/Debug/device-builds/ipad6.3-11.4/mtouch-cache/arm64/libzsdk_iosx.dll.dylib'. Please file a bug report at http://bugzilla.xamarin.com
```

**Comment by twanvermetten** [comment]
I am using the package LinkOS_Xamarin_SDK V 1.1.75
Working fine until upgrade to iOS 11.4 (I hate upgrades of this kind)
After doing all the required upgrades (Xamarin - xCode - Visual Studio MAC)
I get this linking error.
btw I am using Visual Studio Professional 2017 Version 15.7.4
Any Help appreciated

**Comment by suihanhbr** [comment]
I have the same problem.

`/Users/huangboru/myfile/xamarin_workspace/IflyMSCLib/IflyMSCLib/MTOUCH: Error MT5216: Native linking failed for '/Users/huangboru/myfile/xamarin_workspace/IflyMSCLib/IflyMSCLib/obj/iPhone/Debug/device-builds/iphone8.4-11.4/mtouch-cache/arm64/libSuiHanMSC.dll.dylib'. Please file a bug report at http://bugzilla.xamarin.com (MT5216) (IflyMSCLib)`

**Comment by suihanhbr** [comment]
It work on simulator, but can't work on real phone.

**Comment by suihanhbr** [comment]
[IflyMSCLib.zip](https://github.com/xamarin/xamarin-macios/files/2152426/IflyMSCLib.zip)
this is my project .
and here is my environment:
=== Visual Studio Professional 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: 4e60959a-758f-48ce-ae6d-26e15276ea83
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Professional)
Android SDK: /Users/huangboru/myfile/sdk
	Supported Android versions:
		4.4 (API level 19)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Professional)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Professional)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.5
