### ISSUE TITLE
[XI]mtouch commands fail with a missing method exception with Xamarin.iOS master and mono 5.12

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4384]
### Steps to Reproduce

1.  Install Xamarin.iOS master, Xamarin.iOS
Version: 11.15.0.6 (Visual Studio Community)
Hash: e1106121
2. Install desktop mono, Mono 5.12.0.285 (2018-02/cae8c548849) (64-bit)
3. Execute any mtouch  command, /Developer/MonoTouch/usr/bin/mtouch --listdev

### Expected Behavior
Command should list device info

### Actual Behavior
Fails with a missing method exception. https://gist.github.com/GouriKumari/0465cc5ff0c42166de496fc654d934dc. 

### Environment
```
Xamarin.iOS
Version: 11.15.0.6 (Visual Studio Community)
Hash: e1106121
Mono 5.12.0.285 (2018-02/cae8c548849) (64-bit)
```

### Build Logs

Log: https://gist.github.com/GouriKumari/0465cc5ff0c42166de496fc654d934dc

###Additional Info
Issue is not observed when builds from following branches are installed:
1. XI from master branch after mono2018-04 bump and Desktop mono from 2018-04
2. XI from master branch before mono2018-04 bump and Desktop mono from 2018-02
3. XI from d15-8 branch and Desktop mono from 2018-02

I think bumping XI master to mono2018-04 caused the issue.

**Comment by rolfbjarne** [comment]
I can reproduce this. It's because we build mtouch using the command line, and reference BCL libraries directly (which has unspecified API).

The fix is to build mtouch with the .csproj, and select which BCL API to reference (4.6, 4.7, etc) there.

**Comment by rolfbjarne** [comment]
mmp is also affected (and maybe bgen too)
