### ISSUE TITLE
xtro did not report some missing APIs

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#4407]
Here is the Xcode 10 beta 1 diff for HealthKit on watchOS: https://github.com/xamarin/xamarin-macios/wiki/HealthKit-watchOS-xcode10-beta1.

Some APIs were added in https://github.com/xamarin/xamarin-macios/pull/4405: `prepare `, `end`, `pause`...

Somehow xtro didn't flag them, they weren't in the .todo and we simply missed them. It's not impossible we're missing more.

**Comment by spouliot** [comment]
We'll need to plan this carefully, ideally within `xcode10` (so we don't miss anything else) or later - but not mixing that with beta updates.

**Comment by spouliot** [comment]
Number is much higher than the missing API

```
- (null_unspecified instancetype)init NS_DEPRECATED(10_11, 10_13, 9_0, 11_0, "Use initWithStringValue:");
+ (null_unspecified instancetype)new  NS_DEPRECATED(10_11, 10_13, 9_0, 11_0, "Use 
```

but we can't split them without a review

**Comment by dalexsoto** [comment]
We have some xtro inconsistencies between it and diffs, some changes are not showing up in our todo files

https://github.com/xamarin/xamarin-macios/pull/4478/files
https://github.com/xamarin/xamarin-macios/pull/4479/files
https://github.com/xamarin/xamarin-macios/pull/4480/files

**Comment by spouliot** [comment]
Fix merged in 
https://github.com/xamarin/xamarin-macios/pull/4672
