### ISSUE TITLE
UIPrintPageRenderer returns 'NumberOfPages' as Zero with the big size HTML file having CSS reference and lots of SVGs in it. Due to this, an 'Empty' PDF page is getting created.

### ISSUE THREAD

**Issue by rajesh-nanda** [xamarin/xamarin-macios#4408]
### Steps to Reproduce

1. Prepare a HTML file with more than 10 pages containing CSS and lot of SVGs (so that it takes long time to render)
2. Develop a code to load this HTML file from bundle to WKWebView
3. Create the UIPrintPageRenderer from WKWebView for printing.
4. Verify that 'NumberOfPages' of the UIPrintPageRenderer returns 0 (Zero). For this, empty page PDF file is getting created.

### Expected Behavior
DidFinishNavigation should not return until complete HTML page is fully rendered on the View and the UIPrintPageRenderer should correctly return the number of pages based on the 'page rect' size specified.

### Actual Behavior
The 'NumberOfPages' of the UIPrintPageRenderer returns 0 (Zero). For this, empty page PDF file is getting created.
### Environment
iOS Xamarin (Tested using both Visual studio in Windows and iOS)

```
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01590

Xamarin   4.5.0.443 (c871575)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   7.3.0.13 (448f54f)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   10.10.0.30 (30b6e87)
Visual Studio extension to enable development for Xamarin.iOS.
```

### Example Project (If Possible)

[Html_To_Pdf_Sample.zip](https://github.com/xamarin/xamarin-macios/files/2168974/Html_To_Pdf_Sample.zip)

**Comment by dalexsoto** [comment]
Hello @rajesh-nanda

While you provided some code unfortunately this is not enough to fully reproduce what you are seeing, please include a full iOS solution test case so we can reproduce it and give you a quicker answer to your issue.

Thanks.

**Comment by mandel-macaque** [comment]
@rajesh-nanda I'll test this with our current master and the work we have done for Xcode 10. Thanks for the sample.

**Comment by mandel-macaque** [comment]
@rajesh-nanda while trying the submitted test case I got the following compilation error:

`
/Users/mandel/Downloads/Html_To_Pdf_Sample_All_Files/CSC: Error CS2001: Source file '/Users/mandel/Downloads/Html_To_Pdf_Sample_All_Files/ViewController.cs' could not be found. (CS2001) (PdfTest)
`

Looks like a file is missing, maybe got deleted by accident, can you please provide the missing file or re-submit the sample. Thanks in advance.

**Comment by mandel-macaque** [comment]
@rajesh-nanda We have not received the requested information. If you are still experiencing this issue please provide all the requested information and re-open the bug report. Thanks!
