### ISSUE TITLE
ArgumentNullException on TextContentType property of UITextField

### ISSUE THREAD

**Issue by ste8** [xamarin/xamarin-macios#4409]
### Steps to Reproduce

In the login form of our app we added this property to the password UITextField: 
PasswordField.TextContentType = UITextContentType.Password;

Now when some users update their app to a version that contains this property, they receive the ArgumentNullException described below.

I can't easily reproduce the error: it happens only on some iPad of our users (even with the latests iOS) and only after an update of the app. 
If the user uninstalls the app and installs it again, the exception isn't raised anymore.

### Expected Behavior

No error is raised.

### Actual Behavior

An exception of this type is raised when the TextContentType property is set:

System.ArgumentNullException: Value cannot be null. Parameter name: value
at UIKit.UITextField.set_TextContentType (Foundation.NSString value)

### Environment

App built with AppCenter using Mono version 5.10.1 and Xcode version 9.4.1.

**Comment by spouliot** [comment]
The behaviour should be consistent - at least for the same version of iOS.

Please include a complete stack trace and the complete version information, e.g. you're not using Mono 5.10.1, you using Xamarin.iOS. We also need to know which version(s) of iOS is being used when this happens.

**Comment by NitinRaghuwashi** [comment]
Facing the same issue. For me its happening for iPAD with version 9.3.

**Comment by NitinRaghuwashi** [comment]
UITextContentType is available from iOS version10 while
UITextContentTypeUsername andUITextContentTypePassword  is available from iOS 11.
 
Try using below check:

 if #available(iOS 11.0, *) {
  PasswordField.TextContentType = UITextContentType.Password;
  } else {
  // Fallback on earlier versions
 }
