### ISSUE TITLE
Question: Support for loading XM projects in VS for Windows?

### ISSUE THREAD

**Issue by wjk** [xamarin/xamarin-macios#4413]
The title really says it all here. I want to open and edit (*not* build) a Xamarin.Mac project on my PC in Visual Studio for Windows. I've seen conflicting evidence as to whether or not this is possible. [This stackoverflow question](https://stackoverflow.com/questions/41126995/open-xamarin-mac-project-in-visual-studio-on-pc-without-attaching-to-mac) indicates that it is only possible in very limited circumstances, yet does not fully state what those circumstances are. On the other hand, the mere existence of #4341 implies that this is supported. Which is it, and what gotchas should I be aware of?

I understand that Xamarin.iOS applications are fully supported in VS for Windows, yet that is not the kind of app I am writing. I also understand that the nib file editor won't work in VS for Windows, but that doesn't matter all that much because I am going to be writing a "Nibless" application as described in the XM docs (mainly due to low annoying and clunky the process for editing Mac nibs in VSMac is). Thanks for the clarification!

> VS bug [#644543](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/644543), VS bug [#647994](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/647994)

**Comment by mauroa** [comment]
Hi,
Thanks for your question.
Currently Xamarin Mac has minimum support in Windows. This means that you can just open a solution that has Xamarin Mac projects and also edit and build C# code locally.
What you will not be able to do is to work connected to a Mac, build against a Mac, open or edit designer windows, asset catalogs, manifests and everything that requires remote interaction.
Thanks.
