### ISSUE TITLE
[XM] Add a `Create` method for the 'AppKit.NSOpenGLPixelFormat' type

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4417]
### Steps to Reproduce

1. Download a [sample](https://github.com/xamarin/mac-samples/blob/master/GLSLShader)
2. Build and run it on VM

### Expected Behavior
The sample fails on the [line](https://github.com/xamarin/mac-samples/blob/master/GLSLShader/MyOpenGLView.cs#L54):
```
Could not initialize an instance of the type 'AppKit.NSOpenGLPixelFormat': the native 'init*' method returned nil.
```

If I remove `NSOpenGLPixelFormatAttribute.Accelerated` from atrributes collection it will work properly. This attribute means that an app should use hardware-accelaration only. But it doesn't exist for VM.

It also affects creating of `OpenTK.Platform.MacOS.MonoMacGameView`.

### Actual Behavior
Add a `Create` method that can return null. 

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/abc538c727d0bd6d78a338c2f45d3f3f

### Build Logs

1. Exception
https://gist.github.com/mykyta-bondarenko-gl/ec66e97deada8ea29a5ef5170e144069

### Example Project 
[Download](https://github.com/xamarin/mac-samples/blob/master/GLSLShader)

**Comment by VincentDondain** [comment]
This is making the QA [XM AOT tests](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=257177&environmentId=1117116&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension) fail.

See crash report: https://gist.github.com/VincentDondain/2fb0b74548a390a25a33b81ad2fa172e
