### ISSUE TITLE
NSAttributedString.Key values are not bound

### ISSUE THREAD

**Issue by lobrien** [xamarin/xamarin-macios#4428]
### Steps to Reproduce

1. Create a new Workbook 
2. Add a `UILabel`: 
    var lbl = new UILabel(new CGRect(30, 30, 100, 100)); 
    RootViewController.View.AddSubview(lbl); 
   
3. Create an `NSMutableAttributedString` : 
    var text = new NSMutableAttributedString("Hello, World!");

4. Use the `AddAttribute(NSString, NSObject,NSRange)` method to set the first word to bold:

    text.AddAttribute(new NSString("NSFont"), UIFont.BoldSystemFontOfSize(17), new NSRange(0, 5));
    lbl.AttributedText = text;

### Expected Behavior

The first argument's value should be defined as an easy-to-find constant (e.g., `NSAttributedStringKey`) 

### Actual Behavior

I had to run `NSAttributedString.Key.font as NSString` in a Swift playground to discover the value.

### Environment

=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.6 Preview (7.6 build 1773)
Installation UUID: 6b94f136-026d-4a5a-bf6d-af2c0d8dc019
Runtime:
	Mono 5.12.0.273 (2018-02/f59eac4c0f1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000273

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.5
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.4.0.1 (Visual Studio Community)
Android SDK: /Users/larryobrien/Library/Android/sdk
	Supported Android versions:
		4.1 (API level 16)
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 25.0.3
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.0 (14274.19)
Build 10L177m

=== Xamarin.Mac ===

Version: 4.6.0.4 (Visual Studio Community)
Hash: 29d671b5
Branch: master
Build date: 2018-06-07 11:51:32-0400

=== Xamarin.iOS ===

Version: 11.99.1.41 (Visual Studio Community)
Hash: e51f17bc
Branch: HEAD
Build date: 2018-07-05 18:01:52-0400

=== Build Information ===

Release ID: 706001773
Git revision: e5958ff9015312c81fc3b1b6b6413585575ca869
Build date: 2018-06-19 12:19:27+00
Build branch: release-7.6
Xamarin extensions: 6910f36b43e7d559ff40ae268e73ae26c30a2a6b

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

AddinMaker 1.4.2
Larry's F# Templates 2.0.8
MicroFramework 1.0.3
Internet of Things (IoT) development (Preview) 7.5.3

### Example Project (If Possible)

[NSAttributedStringKey.workbook.zip](https://github.com/xamarin/xamarin-macios/files/2181857/NSAttributedStringKey.workbook.zip)

**Comment by mandel-macaque** [comment]
Those fields are already bound, please take a look at:

https://github.com/xamarin/xamarin-macios/blob/master/src/foundation.cs#L314

Closing the issue :)

**Comment by c-lamont** [comment]
@mandel-macaque The link is now dead.

Could you explain how to get the `NSAttributedString.Key`?

**Comment by ElteHupkes** [comment]
Anybody else randomly ending up here through Google, I found some entries in the `UIStringAttributeKey` class.
