### ISSUE TITLE
Wireless Debugging Warning Still Appears After Disabled in VS and XCode

### ISSUE THREAD

**Issue by PatrickRyder** [xamarin/xamarin-macios#4430]
### Steps to Reproduce

1. In XCode on Mac build server, check 'Connect via network'.
2. In Visual Studio on PC, check 'Debug over WiFi'.
3. Run iOS project on physically connected iPhone.

(I had some problems with this that are not relevant to this bug report.  The problem I am reporting came when I tried to switch back to debugging using the USB-iPhone cable.)

4. On PC, uncheck 'Debug over WiFi'.
5. On Mac in XCode, uncheck 'Connect via network'.
6. Run iOS project on physically connected iPhone.

### Expected Behavior
Application should run with no warnings in the debug output about having to ignore the wifi connection because it is not enabled (see attached screenshot).

### Actual Behavior
Application does launch but I get multiple warnings and pauses because it appears to attempt to debug via wifi, even though this is now disabled.  I am not sure if the debug session runs via WiFi or USB but it does always work, so I am assuming these are just redundant warnings.  It appears that once WiFi-debugging has been used once, turning it off is not recognised by all the code that should be responding to this switch.

I cannot easily check if the debugging the project I have on my PC on the Mac works as expected because I do not have enough disk space to install Visual Studio for Mac.

Creating a brand new project in XCode on the Mac appears to debug fine with the debug over WiFi option unchecked.

### Environment

```
Microsoft Visual Studio Community 2017 
Version 15.7.5
VisualStudio.15.Release/15.7.5+27703.2042
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

C# Tools   2.8.3-beta6-63029-08. Commit Hash: e9a3a6c0ba5b1fde8b1fff964bdfb3fb768ee2eb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

Visual Basic Tools   2.8.3-beta6-63029-08. Commit Hash: e9a3a6c0ba5b1fde8b1fff964bdfb3fb768ee2eb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 173513e369ffb7a1c4d5dccf83696d9aac2ab2d0.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

vsFunnel   1.5.32
Decrease solution loading and re-compilation times dramatically by filtering projects not relevant for the current task. 
For more information about Funnel, see the website at http://www.vsfunnel.com
Copyright © 2013-2016. All rights reserved.

Xamarin   4.10.10.2 (35a01d8dc)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

[2018-07-11_12-26-05.9608.Ide.log](https://github.com/xamarin/xamarin-macios/files/2184258/2018-07-11_12-26-05.9608.Ide.log)
![debugoutput](https://user-images.githubusercontent.com/13526323/42569248-cb241624-8507-11e8-9202-79552888be9e.png)
![visualstudio](https://user-images.githubusercontent.com/13526323/42569249-cb426af2-8507-11e8-86ca-668cf7fd1151.png)
![xcode](https://user-images.githubusercontent.com/13526323/42569250-cb5bd500-8507-11e8-869f-70fc14886ef6.png)
### Example Project (If Possible)

> VS bug [#646657](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646657)

**Comment by mandel-macaque** [comment]
Hello,

Does the wireless debugging work directly on the mac? I'll be adding the tag to ping the VS on Windows developers to take a look. But if we can confirm that it does work directly on the mac, we will be able to reduce the search space.

**Comment by PatrickRyder** [comment]
Hi, Mandel,

I have added more information to my original post.  Hope it helps.  If you need any more information, please ask.

- Patrick

**Comment by emaf** [comment]
Hi @PatrickRyder,
Could you reproduce the issue and then attach the Xamarin logs for that session? You can get those from Help -> Xamarin -> Zip Logs

Thanks!

**Comment by PatrickRyder** [comment]
Hi, @emaf,

The exact warnings vary depending upon quite a complex sequence of steps I might have taken, but I have attached screenshots and log files for the warning message, which hopefully will help.

- Patrick
![build output](https://user-images.githubusercontent.com/13526323/42939167-a27d3dcc-8b4c-11e8-9dc6-8f891ac71375.png)
![visual studio debug settings](https://user-images.githubusercontent.com/13526323/42939169-a297befe-8b4c-11e8-9891-887578904831.png)
![visual studio debug target](https://user-images.githubusercontent.com/13526323/42939171-a2b0697c-8b4c-11e8-9da9-c86815ec8efe.png)
[Xamarin Logs.zip](https://github.com/xamarin/xamarin-macios/files/2209635/Xamarin.Logs.zip)
![xcode settings on mac](https://user-images.githubusercontent.com/13526323/42939172-a2e786b4-8b4c-11e8-9d1c-88167e8d91bc.png)

**Comment by rolfbjarne** [comment]
You can safely ignore the HE0049 warning, it's just a diagnostic message.

We'll have a look and see if we can make it less scary.

**Comment by PatrickRyder** [comment]
Thanks for having a look.

I was worried mainly only because I have been having trouble deploying code to an Apple Watch and I wondered if this was a factor.

**Comment by rolfbjarne** [comment]
> I was worried mainly only because I have been having trouble deploying code to an Apple Watch and I wondered if this was a factor.

It's not.

This document might help you with the Apple Watch: https://github.com/xamarin/xamarin-macios/wiki/Debugging-on-watchOS-device
