### ISSUE TITLE
AppKit outputs some messages (such as autolayout errors) to Console log not stdout/err and don't appears in IDE

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#4433]
### Steps to Reproduce

- Create a simple XM app with an autolayout conflict
- Run from IDE, note no warnings/errors
- Run from command line, same
- Open console, and search, you'll see them here.

It appears Xcode is doing some magic to fold these into the output pane.

See example in https://forums.xamarin.com/discussion/129187/enable-autolayout-diagnosis-messages-in-debug-output?

### Expected Behavior
We should see these messages that show up in Xcode

### Actual Behavior
No messages

> VS bug [#645966](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/645966), VS bug [#680551](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/680551)

**Comment by mandel-macaque** [comment]
@chamons setting to future since you already did all the triaging work ;)

**Comment by VincentDondain** [comment]
Here's a simple test case:

[MyCocoaApp.zip](https://github.com/xamarin/xamarin-macios/files/2460677/MyCocoaApp.zip)
