### ISSUE TITLE
[XCode 10] Metal Game Template app fails to build with MSB6003 error

### ISSUE THREAD

**Issue by GLjackyvaswani** [xamarin/xamarin-macios#4436]
Metal Game Template app fails to build with MSB6003 error

**Build Info:**
 - Version 7.5.4 (build 5)
 - Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
 - Xamarin.Android Version: 8.3.3.2
 - Xamarin.Mac Version: 4.99.1.164
 - Xamarin.iOS Version: 11.99.1.44
 - Apple Developer Tools Xcode 10.0 (14301.4) Build 10L201y
 - Operating System Mac OS X 10.14.0
 - Xamarin.Profiler Version: 1.6.2
 - Xamarin Inspector Version: 1.4.0

**Detailed Build Info:**
https://gist.github.com/GLjackyvaswani/bbf556eb8dbfe16e7619c6013a863a5c

**Steps:**
1. Create a new Metal Game Template project.
2. Build the project.

**Expected Result:**
Project should build successfully.

**Actual Result:**
Build fails with MSB6003 error.

**Reproducible:**
100% Happens Everytime

**Test Case Link:**
https://testrail.xamarin.com/index.php?/tests/view/24588979&group_by=tests:assignedto_id&group_order=desc&group_id=-1

**Test Plan Link:**
https://testrail.xamarin.com/index.php?/plans/view/55801

**Build Output Logs:**
https://gist.github.com/GLjackyvaswani/c0c9b79e1a16e4d6c833d5c955caac04

**Screen Cast Link:**
https://www.screencast.com/t/PQsN83yqIqX

Attached IDE logs for reference.
[Ide.2018-07-12__18-25-27.log](https://github.com/xamarin/xamarin-macios/files/2188702/Ide.2018-07-12__18-25-27.log)

**Comment by mandel-macaque** [comment]
Hello,

Can you please provide me with the link to the project under test. I do not have access to the Test Case/Test Plan.

**Comment by GLjackyvaswani** [comment]
Hello,

Though the issue is not related with any sample, it can be reproduce with creating Metal game template & build it.

Have attached the sample for more info:
[MetalGameTemplate.zip](https://github.com/xamarin/xamarin-macios/files/2191538/MetalGameTemplate.zip)

Also have added the sample on screencast link : https://www.screencast.com/t/jClYezJnlw

**Comment by mandel-macaque** [comment]
Thanks, I can confirm the bug with the following settings:

=== Visual Studio Community 2017 for Mac ===

Version Preview - Internal Dogfood (7.4.3 build 8)
Installation UUID: 8d12e55e-3489-463f-ac52-8cb4573c5a81
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.5
	2.0.0
	1.1.2
	1.0.5
	1.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.4
	2.0.0
	1.0.4
	1.0.0-preview2-003121
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/mandel/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.3   (API level 18)
		4.4   (API level 19)
		5.0   (API level 21)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.4
SDK Build Tools Version: 25.0.1

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 10.0 (14301.4)
Build 10L201y

=== Xamarin.Mac ===

Version: 4.99.1.134 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.99.1.14 (Visual Studio Community)
Hash: 4396b088
Branch: coremidi-xcode10
Build date: 2018-07-13 13:18:21+0200

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 704030008
Git revision: d2c212a04a47c3176572edcc85319459646f9e19
Build date: 2018-04-06 11:21:38-04
Xamarin addins: fadb82fb0fe2668cb7789f8b524aec6fb8568ee7
Build lane: monodevelop-lion-dogfood-vNext

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

WakaTime 3.0.3
Internet of Things (IoT) development (Preview) 7.5

**Comment by rolfbjarne** [comment]
This is a dup of #4576 (already fixed).
