### ISSUE TITLE
watchOS build error when referencing a C static library in Xamarin when in debug mode for Apple Watch device (ARMv7k)

### ISSUE THREAD

**Issue by cmsmith81** [xamarin/xamarin-macios#4445]
### Steps to Reproduce

1. Open Xamarin Project referenced below.
2. Set the build config to Debug and Generic Device
3. Build Project
4. Native Linking Build Error
5. Change project to Release Mode
6. Build Project
7. It builds, runs, and works as expected, although with some warnings.

### Expected Behavior
Project should build in debug mode for "Generic Device" or for actual Apple Watch device.

### Actual Behavior
Project has build errors related to the static C library when building for Debug mode.

### Environment

```
=== Visual Studio Professional 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: []
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.5
	2.0.3
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.4
	2.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Professional)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Professional)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Professional)
Android SDK: /Users/[]/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 28.0.0 rc1

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1


```

### Build Logs

https://gist.github.com/cmsmith81/532493e938012e1255283fb14ecc7507

### Example Project

1. Xamarin Project with Build Error - https://github.com/cmsmith81/staticLibWatchOSTest
2. Static C library built for ARMv7k used in above project (note that the binary libtestCKLib1.a is included in the above project - this is the source for that library) - https://github.com/cmsmith81/testCKLib1

**Comment by mandel-macaque** [comment]
Hello,

I tried the provided project in release mode and I had the following error: https://gist.github.com/mandel-macaque/fd4530532d47d09e53ce272acf1cb267

Can you double check that the project does build on release mode?

**Comment by cmsmith81** [comment]
I see that you were building for the simulator. You need to change it to
either a physical Apple Watch or to "Generic Watch Device" (no watch needed
to build).

The C library is compiled only for ARMv7k which is the Apple Watch device
architecture. The simulator is i386 and the library is not compiled for
that architecture.

The error you are getting is expected behavior for a simulator build.

Let me know if you have any questions.

Thanks!

-Corey Smith
smith@ieee.org

**Comment by mandel-macaque** [comment]
Thanks for the info, I'll retry testing the project with a real device.

**Comment by cmsmith81** [comment]
You can reproduce without an actual device since it's a build error, you
just need to set the build target to to device instead of simulator.

**Comment by rolfbjarne** [comment]
@cmsmith81 try disabling "Enable incremental builds" in the watch extension's `watchOS Build` options, that should work around the linker problem.

**Comment by rolfbjarne** [comment]
@cmsmith81 no need to do something else, we'll handle it from here.

I'll have a look and see if we can fix/improve something on our side.

**Comment by rolfbjarne** [comment]
This is what happens:

* When "Incremental builds" is enabled, we compile each assembly into its own dylib.
* The "-gcc_flags" additional mtouch arguments is only passed to the native linker when linking the executable, not for each dylib that's created when "Incremental builds" is enabled (this is as expected).
* Due to bitcode requirements on watchOS, each P/Invoke must call an existing native function (when AOT-compiling managed code, we call the corresponding native function for each P/Invoke directly).

When all these points come together, you see that the native function `sum` is not linked into the dylib we create for the assembly with the corresponding P/Invoke. This means that the native linker will complain (as you've seen).

There are two solutions:

* Disable "Incremental builds". This means we'll compile everything into the main executable.
* Create a binding library for the native library. In this case, we'll have enough information to correctly link the native library into the dylib for the binding assembly.

I'm updating our documentation for the MT5216 error for this scenario.

**Comment by rolfbjarne** [comment]
BTW thanks for the great test project 👍

**Comment by cmsmith81** [comment]
No problem, thanks for the update!
