### ISSUE TITLE
NSUrl.ItemTitle and .ItemUrl should be .PreviewItemTitle and .PreviewItemUrl

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#4450]
_From @MichaelNorman on July 13, 2018 20:0_

`NSUrl.ItemTitle` and `NSUrl.ItemUrl` should be `NSUrl.PreviewItemTitle` and `NSUrl.PreviewItemUrl`, respectively. They bind `.previewItemTitle` and `.previewItemURL`.

Expected:
`NSUrl.PreviewItemTitle` and `NSUrl.PreviewItemUrl`

Actual:
`NSUrl.ItemTitle` and `NSUrl.ItemUrl` 

_Copied from original issue: xamarin/maccore#885_

**Comment by mandel-macaque** [comment]
Hello, thanks for the bug report, but this is the private repo for the tools that are related to Xamarin.[iOS|Mac]. I'll close the issue and will move it to the correct project.

**Comment by VincentDondain** [comment]
We acknowledge this enhancement request. However this is a breaking change on a protocol so it would only be effective if we even break the APIs again.

**Comment by VincentDondain** [comment]
Also this happens here: https://github.com/xamarin/xamarin-macios/blob/master/src/quicklook.cs#L126-L139 (it's a protocol that NSUrl conforms to).
