### ISSUE TITLE
Visual Studio for Mac crashing at startup after updates

### ISSUE THREAD

**Issue by Maxima078** [xamarin/xamarin-macios#4461]
After last updates I cannot start Visual Studio for Mac, it crash after few seconds. I can see the main page but as soon as I click anywhere the loading wheel is displayed and VS crash.
### Steps to Reproduce

1. Make last updates(?)

### Expected Behavior
Visual Studio does not crash

### Actual Behavior
Visual Studio crash

### Environment
macOS 10.13.6

### Logs
[Ide.2018-07-18__09-42-09.log](https://github.com/xamarin/xamarin-macios/files/2204872/Ide.2018-07-18__09-42-09.log)
[report_vs.log](https://github.com/xamarin/xamarin-macios/files/2204883/report_vs.log)

**Comment by VincentDondain** [comment]
Please report a new issue with Visual Studio for Mac directly within the IDE. Simply use Help > Report a Problem to file your issue.

**Comment by Maxima078** [comment]
I'd like to be able to do so but I can't. Like I said as soon as I click anywhere the loading wheel is displayed and VS crash...

**Comment by Maxima078** [comment]
Found same problem [here](https://developercommunity.visualstudio.com/content/problem/294475/visual-studio-for-mac-crashes-on-startup.html)

**Comment by VincentDondain** [comment]
Please use [this link](https://developercommunity.visualstudio.com/content/problem/post.html?space=41&version=7.5.2.40) to file an issue against Visual Studio for Mac.
