### ISSUE TITLE
"Code object is not signed at all" ... "In architecture: arm64"

### ISSUE THREAD

**Issue by brad302** [xamarin/xamarin-macios#4465]
I'm unable to build my project and debug it on my device.  I'm sure this was working only about 2 to 3 weeks ago and this is consistent across 2 development environments.

### Steps to Reproduce

I perform a build (cleaned or not) and receive the following error ..

Target "_CodesignVerify" in file "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets":
  Task "CodesignVerify" skipped, due to false condition; ('$(IsMacEnabled)' == 'true' And '@(_ResolvedAppExtensionReferences)' != '') was evaluated as ('true' == 'true' And '' != '').
  Using "CodesignVerify" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Tasks.dll".
  Task "CodesignVerify"
    Environment Variables passed to tool:
      CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    /usr/bin/codesign --verify -vvvv -R='anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.1] exists and (certificate leaf[field.1.2.840.113635.100.6.1.2] exists or certificate leaf[field.1.2.840.113635.100.6.1.4] exists)' bin/iPhone/Debug/device-builds/iphone8.1-11.4.1/ReceiptCapture.iOS.app 
    bin/iPhone/Debug/device-builds/iphone8.1-11.4.1/**ReceiptCapture.iOS.app: code object is not signed at all
    In architecture: arm64**
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1977,3): error MSB6006: "codesign" exited with code 1.
  Done executing task "CodesignVerify" -- FAILED.
Done building target "_CodesignVerify" in project "ReceiptCapture.iOS.csproj" -- FAILED.

Done building project "ReceiptCapture.iOS.csproj" -- FAILED.

### Expected Behavior

I've had this from 2 different machines across 2 different projects and both environments are identical as far as I can work out.

### Actual Behavior

As shown above.

### Environment

```
```
=== Visual Studio Community 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: 83f71f98-472d-4714-800a-16fa1baef816
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/braddixon/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

FileNesting 0.1.1
Internet of Things (IoT) development (Preview) 7.5

### Build Logs

I'm a little unsure as to how I can attach the detailed log from the build into this but if requested, I am able to provide it.

**Comment by VincentDondain** [comment]
Please include your full build logs, crash reports (if any) and test case (to reproduce).

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

**Comment by brad302** [comment]
I've added 2 build logs, slightly different for whatever reason, the same error is shown in both however.  One was from Thursday the 19th of July, the other from today.

The log is cut down somewhat given it's size and because the build log window truncated portions of it due to length.

[Build Logs.zip](https://github.com/xamarin/xamarin-macios/files/2217874/Build.Logs.zip)

I hope that helps.

Thanks

Brad

**Comment by VincentDondain** [comment]
Hi, does that happen with new projects? Any chance you can share your project with us so we can check what could be wrong? Maybe the faulty `.app` if you can?

**Comment by VincentDondain** [comment]
Also was that a clean build? The target "_CodesignAppBundle" says "Skipping target "_CodesignAppBundle" because all output files are up-to-date with respect to the input files."

Could you clean everything / delete you /bin folder just in case and re-upload your build logs please?

_Note: trying to understand what could have failed before the `CodesignVerify`._

**Comment by rolfbjarne** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
