### ISSUE TITLE
[msbuild] error CS0227: Unsafe code may only appear if compiling with /unsafe 

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4483]
### Steps to Reproduce

1. Download the [project](https://github.com/xamarin/xamarin-forms-samples/tree/master/SkiaSharpForms/MandelAnima/)
2. Run `nuget restore [solution-path]`
3. Run `msbuild [project-path] /p:Configuration=Debug /p:Platform=iPhoneSimulator`

### Expected Behavior
Build succeeded

### Actual Behavior
Build failed

```
 error CS0227: Unsafe code may only appear if compiling with /unsafe [project-path]
```

The main difference that I think causes that issue is the `/unsafe` parameter:
`/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Roslyn/csc.exe *** /unsafe- *****`
When it fails it's `unsafe-` and `unsafe+` for another cases. I think that It depends on `/p:Platform` parameter. Build fails when it exists.

I can also reproduce it on the stable channel too. 
Also I  should mention that it's a new sample, it was committed on 2 July. 

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/5ae21550e4b1b7882a45640a645920ed

### Build Logs

- msbuild [project-path] 
https://gist.github.com/mykyta-bondarenko-gl/8fbe35ab74320e63c8b2bf453ba82a0c
- msbuild [project-path] /p:Configuration=Debug /p:Platform=iPhoneSimulator
https://gist.github.com/mykyta-bondarenko-gl/ade992e2cdfd7536fb4b63375436c190
- build with vsfm
https://gist.githubusercontent.com/mykyta-bondarenko-gl/6a3a9767168c63eb9e76943be1b7c367/raw/642c18e85b800795e4d83a8d913cf8111ea84107/vsfm
- msbuild [project-path] /p:Configuration=Debug /v:diagnostic
https://gist.githubusercontent.com/mykyta-bondarenko-gl/19199e9eb5d9125a741edad8c809ee37/raw/7cf25ca5aeb4b1c7491f3e6e1ade73eec64e033d/p:Configuration=Debug%2520v:diagnostic

### Example Project
[Project](https://github.com/xamarin/xamarin-forms-samples/tree/master/SkiaSharpForms/MandelAnima/)

**Comment by VincentDondain** [comment]
I'm confused about what you think is an issue? The project you linked is working fine as is. You're trying to understand how to remove the "Allow unsafe" from the shared project? In MainPage.xaml.cs at line 124 there's an `unsafe` directive (that requires the "Allow unsafe"). Remove it and the error goes away (if you don't want to allow unsafe code).

Could you please clarify the issue or close it? (:

**Comment by mykyta-bondarenko-gl** [comment]
Hi @VincentDondain 
I was confused that I have different results using `msbuild` and `vsfm`. 
If  I open the project via `VSfM` and build it - everything will be great, but if I try to build it via `msbuild` -> it fails.

**Comment by VincentDondain** [comment]
Aren't you supposed to pass some `unsafe` parameter / flag when using the command line? That would be the difference, you can check the VSMac build output.
In any case if it works with VSMac and if it's an issue with msbuild on the command line I do not think a bug against Xamarin.iOS will help you much (:

_Note: closing (we can chat offline to see how to get the command line working)._
