### ISSUE TITLE
"Native References" not working in ios library projects

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-macios#4489]
When adding a Native Reference in an ios library project, and including this project in an ios app project, the Native Reference is ignored.

A workaround is to add the Native Reference into the ios app project's Native Reference.

### Steps to Reproduce

1. Create an ios app project and an ios library project
2. In the library project, add as "Native reference" a libwritteninc.a library, which is a fat library written in c, compiled with xcode tools, containing all architectures, and not using any ios frameworks.
3. Add a method with a DllImport attribute to import a c method defined in libwritteninc, using "__Internal" as the library name.
4. Reference the library into the ios app project, and call the method with the DllImport attribute
5. Build

### Expected Behavior
builds fine on both mac and pc

### Actual Behavior
Build errors: undefined symbols.

### Environment
Tryed in both VS windows and VS mac.

note: a workaround is to add the Native Reference into the ios app project's Native Reference.

> VS bug [#652621](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/652621), VS bug [#685241](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/685241)

**Comment by borrrden** [comment]
Same issue here except with a Framework...it just says mtouch failed and scrolling up it says "Couldn't find Framework".  This is a huge headache for a project like ours that has a lot of native functionality.

**Comment by jstedfast** [comment]
Can anyone provide me with a simple test case?

**Comment by softlion** [comment]
Yes, create a simple C library for iOS with one function exported. Compile it to a fat .a library. Then add it in a xamarin ios app project, and create a DllImport for this exported method. It will work fine. Then move the .a and the dllimport in a xamarin ios library that you reference from your xamarin ios app. Clean all obj/bin folder and build.

**Comment by rolfbjarne** [comment]
@jstedfast I think the fix here is to hide the option to add "Native References" for iOS Class libraries, it just won't work properly.

**Comment by softlion** [comment]
#3766 is an issue, not a PR ?

**Comment by dalexsoto** [comment]
Yeah this seems to be fixed in the Visual Studio add-in which is not open source so that PR number does not correspond to the macios repo, looks like this was fixed a long time ago but automation is just catching up.
