### ISSUE TITLE
deleting a "Native Reference" does not delete the file on disk

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-macios#4490]
### Steps to Reproduce
1. Add a "Native reference" to any ios project.
2. Delete this native reference.

### Expected Behavior
The reference is deleted from the project and from the disk.

### Actual Behavior
The reference is deleted from the project but stays on the disk.

### Environment
VS 15.7.5PC and VS 7.5.3MAC (same behavior)

> VS bug [#652623](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/652623)

**Comment by rolfbjarne** [comment]
Closing since the VS bug has been fixed since 2018.
