### ISSUE TITLE
Consider port .net Core 3.0 to xamarin.mac

### ISSUE THREAD

**Issue by juepiezhongren** [xamarin/xamarin-macios#4492]
mono and core convergence is ongoing, but core 3.0 seems to be a important milestone. to make desktop dev for windows and macos both benifiting from core 3.0 is so good a dream!

**Comment by chamons** [comment]
It is not currently possible to use .NET core for building Xamarin.Mac as it is strongly tied to Mono - it is in fact the same codebase that is used for Xamarin.iOS:  There is heavy use of the embedding API, special GC support, and we currently bundle their copies of the BCL. 

In addition, macOS expects applications to bundle their dependencies in a bundle, so any .NET Core solution would need to reproduce at least some of mmp, generating a launcher application with clang.

Generally, we are instead incorporating and sharing into Mono code from CoreCLR and CoreFX so improvements in those flow into Mono, Unity and Xamarin.

If there are particular use cases you feel are underserved, please feel free to open issues describing those.
