### ISSUE TITLE
when will reflection.emit be avaible for ios？

### ISSUE THREAD

**Issue by juepiezhongren** [xamarin/xamarin-macios#4530]
@lewurm shipped with vs 15.8?

**Comment by spouliot** [comment]
It's not for 15.8 nor 15.9.

Basically the interpreter became _available_ in 15.8 (incomplete, not supported) but it still needs to pass our whole test suite. Then there are several options that needs to be revisited to allow SRE to work. E.g. the current linker optimize several things, like doing method devirtualization, based on the _known fact_ that code cannot be downloaded or generated after the application is built. All those assumptions needs to be turned off when the interpreter is enabled or very weird failures will happen.

Of course this is all open source so, if interested, you can build your own XI with SRE support (runtime and class library) and disable the linker.

**Comment by juepiezhongren** [comment]
good to know
