### ISSUE TITLE
Simulator apps with Xcode 10 are not full screen and you can't interact

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#4532]
### Steps to Reproduce

1. Create a new Single View app using VSMac's templates
2. Run on simulator
3. See that the app isn't full screen (2 black bars), the top of the simulator is messed up and you can't interact.

### Expected Behavior

Full screen app, behaving normally.

### Actual Behavior

Can be seen in this video https://www.dropbox.com/s/s1azhk66c4r6r7e/DualSim.mov?dl=0
Or this screenshot:

<img width="545" alt="screenshot 2018-07-31 11 09 58" src="https://user-images.githubusercontent.com/7839202/43469368-00817788-94b4-11e8-90d2-9759ccddad40.png">

### Environment

```
=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.7 Preview (7.7 build 762)
Installation UUID: 00d602ef-271b-479b-9054-0433b5797215
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.5
	2.0.0-preview2-25407-01
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.4
	2.0.0-preview2-006497
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.0.0.17 (Visual Studio Enterprise)
Android SDK: /Users/vidondai/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3 (API level 10)
		4.3 (API level 18)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.0.629.0
Hash: ccfe436f

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.0 (14320.2.4)
Build 10L221o

=== Xamarin.Mac ===

Version: 4.99.2.219 (Visual Studio Enterprise)
Hash: 1ed3eab16
Branch: arkit-aranchorcopying
Build date: 2018-07-31 10:41:40-0400

=== Xamarin.iOS ===

Version: 11.99.2.99 (Visual Studio Enterprise)
Hash: 1ed3eab16
Branch: arkit-aranchorcopying
Build date: 2018-07-31 10:41:39-0400

=== Build Information ===

Release ID: 707000762
Git revision: 8bbc500c47a0bd8f8dc46fcdb6541de5f2707f2a
Build date: 2018-07-30 06:04:39+00
Build branch: master
Xamarin extensions: 720cda319c3eb5d8b8285d7cb7771d763fd86c13

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

AddinMaker 1.4.2
NuGet Package Explorer 0.2
Internet of Things (IoT) development (Preview) 7.5


```

### Example Project (If Possible)

https://gist.github.com/VincentDondain/debae8d24b034c7a70ccd3ef789c0b03

**Comment by VincentDondain** [comment]
Note: if you run the app with say iOS 11.4, you still get the black bars but the app at least is functional.

**Comment by VincentDondain** [comment]
I'm wondering if there is some issue with the LaunchScreen.storyboard... That's what's needed to get rid of those black bars usually. However I cannot see any problem with my local app.

**Comment by VincentDondain** [comment]
I tried to copy the `LaunchScreen.storyboard` and `Main.storyboard` of a brand new Xcode Single View template to see if maybe they updated some values there but that didn't work, same issue.

**Comment by GouriKumari** [comment]
I verified this issue with samples and template projects, in both cases changing dontlink to linksdk in ios build configuration fixes the issue. The above reported issue seems to be related to https://github.com/xamarin/xamarin-macios/issues/4305.

## Projects tested:
Template: https://www.screencast.com/t/JimLnJhYV
Sample (Dynamics Catalog): https://screencast.com/t/FbJopSWHuuY

**Comment by VincentDondain** [comment]
This appears to be fixed in Xcode 10 beta 6 now. 🎉

**Comment by VincentDondain** [comment]
Seems like the fix is more an XI built with Xcode 10 beta 6 (e.g:
https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10/347f472b033073e732b05b33a7e6fe93b37a3d49/145/package/xamarin.ios-11.99.3.243.pkg) than just installing the Xcode 10 beta 6 command line tools as I initially thought.

**Comment by GouriKumari** [comment]
Verified with XI 11.99.3.538 and the issue is fixed.

Screencast: https://screencast.com/t/6TW78uLW
