### ISSUE TITLE
[XI]App with deployment target less than 11.0 fails to build with Invalid architecture error

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4540]
### Steps to Reproduce

1. Open sample app, https://www.dropbox.com/s/wv0o3k7pu8g59ru/simpleapp-with-nativereferences.zip?dl=0 in Debug|iPhone config
2. Change the supported architecture to ARMv7+ARMv64
3. Make sure that no devices are attached while building

### Expected Behavior
App should build successfully

### Actual Behavior
App fails to build. http://xqa.blob.core.windows.net/gist/report-e3d7a84a235f4b3d81d028843b3e4b3e.txt

Error:  MTOUCH : error MT0116: Invalid architecture: ARMv7. 32-bit architectures are not supported when deployment target is 11 or later.

### Environment
```
https://gist.github.com/GouriKumari/a4291fe22b8ea5c8b6b7ea575d0f70ba
```

### Build Logs
http://xqa.blob.core.windows.net/gist/report-e3d7a84a235f4b3d81d028843b3e4b3e.txt

### Example Project (If Possible)
https://www.dropbox.com/s/wv0o3k7pu8g59ru/simpleapp-with-nativereferences.zip?dl=0 

### Additional Details
App builds successfully when a device is attached or supported architecture is changed only to ARM64

**Comment by spouliot** [comment]
Are you sure about your target ?

```
  Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 11.4 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk --compilation-directory /Users/xamarinqa/agent/_work/r29/a/QualityAssurance/Samples/ios/simpleapp-with-nativereferences/photoeditingextension/obj/iPhone/Debug/ibtool /Users/xamarinqa/agent/_work/r29/a/QualityAssurance/Samples/ios/simpleapp-with-nativereferences/photoeditingextension/MainInterface.storyboard
```

^ `ibtool` gets called with 11.4

Please enable MSBuild verbosity or attach the response file to the issue.

**Comment by GouriKumari** [comment]
Build Log: https://gist.github.com/GouriKumari/721b5f5af3045c3d6f4fed056740c1e1

**Comment by spouliot** [comment]
You have more than one project (app + extension) and one of them seems to be set to require 11.4 **and** ask for an `armv7` slice
```
--executable=photoeditingextension
--extension
...
--targetver=11.4
...
'--abi=armv7,arm64'
```
https://gist.github.com/GouriKumari/721b5f5af3045c3d6f4fed056740c1e1#file-gistfile1-txt-L1760

**Comment by GouriKumari** [comment]
Deployment target wasn't set on the Photoeditingextension project and deployment target was automatically defaulting to 11.4.   By setting both the deployment targets to a lower version (8.0), app built successfully.

**Comment by LeGiangAnh** [comment]
@GouriKumari I'd like to contact you. Could you please email me anh.legiang (at) gmail.com or https://twitter.com/LeGiangAnh?
