### ISSUE TITLE
NSSpeechSynthesizer.StartSpeakingtoURL doesn't work on any longer text

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#4545]
### Steps to Reproduce

1. Extract the sample
2. Change the desktop path to your desktop
3. Run the app

### Expected Behavior
The aiff file should be saved to the desktop
### Actual Behavior
Nothing happens
### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.5.4 (build 3)
Installation UUID: f546b303-006e-4f34-8fa8-4662985b4489
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Versions:
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/ivanicin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705040003
Git revision: 6ae731889c896d6733efb8ff5117f5bf5b17b509
Build date: 2018-07-19 13:07:45-04
Xamarin addins: 417fed09624e1e1f76ab0a11e8b97ffd8bbf91e1
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.5

```

### Example Project (If Possible)

[MP3Test.zip](https://github.com/xamarin/xamarin-macios/files/2250067/MP3Test.zip)

Note: this is a very critical issue for my app which is a major app in the Mac App Store in its category, so please provide some feedback on what is the best thing to do.

**Comment by ivanicin** [comment]
Also of note - I've tried something similar in XCode and it works, so it seems to be Xamarin issue. In my experience with Xamarin similar weird issues were related to the garbage collection, though I can't fix this by keeping references so I might be wrong but still the problem may be deeper and might be in that line.

**Comment by ivanicin** [comment]
And changing the garbage collection method to concurrent makes this sample work, though some samples with bigger text wouldn't work, which somewhat further raises the doubt that this is a garbage collection problem.

**Comment by chamons** [comment]
There is no file.aiff attached in the example, so I can not run it. Any way you could attach it?

**Comment by ivanicin** [comment]
Hi Crhis, there shouldn't be such a file, it is the file that should be created with that command but it doesn't. Just as I use the path to my desktop it might not work unless you update the path to your desktop or any folder on your device.

Also you can change the string to something simple like "This is test" and the .aiff file should be created as the process works for a short period of time (exactly that's why I suspect on the garbage collection). If you need even more insight you can create the delegate, follow WillSpeakWord and see that everything works normally till some position when it stops. Changing the garbage collection method changes the position where it stops. So I am 99% sure it gets garbage collected and that's why it is not completed...

**Comment by chamons** [comment]
Hmm, fixing that path produced a 5.5 meg output that had all of the text in question. 

I then added my normal GC stress code:

```new System.Threading.Thread (() => 
{
while (true) {
System.Threading.Thread.Sleep (10);
GC.Collect ();
}
}).Start (); ```

with no change. 🤔

**Comment by chamons** [comment]
I just tried with `Version: 4.4.1.193 (Visual Studio Community)` and still see the same thing.

**Comment by ivanicin** [comment]
I use MacMini 4GB, the lowest end device. This was about the minimal string required to reproduce the problem. If you have the chance to test there it would be the best. I guess that if it is garbage collection related it may vary depending on the device, not sure if it goes to that length that it can't be reproduced on some very long texts. Is there any chance that you can put some fairly large .txt file on your device and load the text from there?

Again I don't think that my Mac has gone crazy as it works from XCode with any text.

**Comment by ivanicin** [comment]
Also of note this method should work as long as you have the disk space on the Mac for the aiff file, so there shouldn't be a text that's too big.

**Comment by chamons** [comment]
I don't happen to have such a machine handy, so I've asked QA to try to reproduce this. 

I however, tried to reproduce this with Obj-C and I can't even make the API work at all:

https://gist.github.com/chamons/991153d874c3d5ac8efd1c7bc58bd5ce

**Comment by GouriKumari** [comment]
I couldn't reproduce this issue in a mac mini. The above mentioned file got saved in desktop.

## Logs:
Application Output: https://gist.github.com/GouriKumari/648cd03e0fe6c004e864571fcba6d98c
Test Env: https://gist.github.com/GouriKumari/05ed7c3bfea7a6c12121a425738e612b
Screenshot: https://www.screencast.com/t/msl1VJnVsAG6

**Comment by ivanicin** [comment]
It seems that something is changed in Xamarin that requires longer text sample to reproduce as this is working for me too. I apologize that it seems that I haven't tested the sample right before posting as it did work before.

I'll send the new sample soon.

**Comment by ivanicin** [comment]
@chamons swift code that works would be:

```
        let synt = NSSpeechSynthesizer(voice: nil)
        synt?.rate = 1
        synt?.startSpeaking(newText, to: URL(fileURLWithPath: "/Users/ivanicin/Desktop/file1.aiff"))
```

I am not sure for Objective C, I know how to read it but not how to write it 😄

**Comment by ivanicin** [comment]
[MP3Test2.zip](https://github.com/xamarin/xamarin-macios/files/2255584/MP3Test2.zip)

This is the new test file. It is changed so that it downloads the text of Alice's adventure in Wonderland and uses it. And also there is a delegate that displays the progress in the output window.

For me this sample stopped at the position 1089 (which is like 1% of the book). Just to note that this book worked without any problems previously, actually much longer books worked.

I believe that this should be now reproducible on every device, though the position where it stops to progress may vary...

**Comment by mandel-macaque** [comment]
@chamons I'll try to reproduce it with the new provided sample.

**Comment by ivanicin** [comment]
While this is likely reproducible, when I used the same text in XCode it did not work either, so it is likely not a Xamarin issue, I guess that some texts work in XCode and not in Xamarin, but it is likely because XCode may leave more memory free or something like that. But very long texts don't work in XCode too. So either Apple API problem or just my Mac.

**Comment by mandel-macaque** [comment]
@ivanicin I have been able to reproduce the issue. Yet, as you mentioned, the issue does happen on Xcode, so I recommend you file a rdar (I will do on our side) for apple to take a look into it.

**Comment by ivanicin** [comment]
Just to note that if someone stumbles on this, this is fixed in Mojave (including current beta). I couldn't get the information whether it will be patched in High Sierra with some later update.
