### ISSUE TITLE
mmp --version giving "wrong" version in d15-7

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#4560]
### Steps to Reproduce

1. sudo installer -pkg xamarin.mac-4.4.1.193.pkg -target /
2. /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp --version
3. You get `mmp 4.4.99.193 (d15-7: 64fece5f)` not 4.4.1.193

### Expected Behavior
Versions match

### Actual Behavior
Versions don't 

### Environment
d15-7 stable installed

**Comment by spouliot** [comment]
That was an incorrect field (in Make.config)
Both mmp and Xamarin.Mac version are 4.4.99.x
note: we already discussed this (a while ago) because of the API diff - but it was too late to change.

**Comment by chamons** [comment]
I can confirm d15-8 is correct. 

I did not realize that Make.config would change the --version but not the pkg name.

Good catch.
