### ISSUE TITLE
Linking error with library created using Objective Sharpie

### ISSUE THREAD

**Issue by vpatelalk** [xamarin/xamarin-macios#4565]
Hello 

I am planning to create a Xamarin binding library interface for our existing iOS Framework. Using the Sharpie tool, I am able to create a binding project after resolving few errors. I created a sample project in Visual Studio in Mac which uses the Binding Project. Compiling works however linking throwing error and advise to log the bug in https://github.com/xamarin.

Following is the brief errors

ld: symbol(s) not found for architecture arm64
    clang : error : linker command failed with exit code 1 (use -v to see invocation)
    
    MTOUCH : error MT5216: Native linking failed for '/Users/macbookpro/Desktop/iOS Xamarin/BindingProjectSolution/xamarinapp/obj/iPhone/Debug/device-builds/iphone10.6-11.4.1/mtouch-cache/arm64/libBindingProject.dll.dylib'. Please file a bug report at http://bugzilla.xamarin.com
Done building target "_CompileToNative" in project "xamarinapp.csproj" -- FAILED.

Done building project "xamarinapp.csproj" -- FAILED.

**Comment by mandel-macaque** [comment]
Hello, can you please provide the following information so that we can correctly triage the bug:

* Full version information of the environment you are using.
* If possible an small sample project to reproduce the issue.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by vpatelalk** [comment]
Dear Sir

Following is the requested information..
Visual Studio for Mac (Community)  - 7.5.2 (build 40)

Please find the attached Visual Studio Binding project and Visual Studio sample application which uses the Binding project. I have used Objective Sharpie to create Structs.cs and APIDefinitions.cs. Let me know if you need more information.. 

[BindingProjectSolution.zip](https://github.com/xamarin/xamarin-macios/files/2263144/BindingProjectSolution.zip)

**Comment by vpatelalk** [comment]
Dear Sir
Please find the revised project which contains all the dependency. Dues to size constraint, I am providing dropbox link.

https://www.dropbox.com/s/c3ia95p9g65v43i/BindingProject_10.4.zip?dl=0

You can also find the Framework which use to create a Structs.cs and APIDefinitions.cs.  

Binding project - Works fine
Sample Application : While linking it generates error.

It will be really appreciated, if you can provide solution as stuck with linking errors.

**Comment by vpatelalk** [comment]
Is there any update on it as I am stuck on linking error?

**Comment by mandel-macaque** [comment]
@vpatelalk Is this the same issue reported in https://github.com/xamarin/xamarin-macios/issues/4638 If that is the case. Lets close this issue and continue with https://github.com/xamarin/xamarin-macios/issues/4638
