### ISSUE TITLE
[xcode 10] Error MM5109: Native linking failed with error code 1.  

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4568]
### Steps to Reproduce

1. Download a [sample](https://github.com/xamarin/mac-samples/tree/master/MarkdownViewer)  
2. Open the solution
3. Build it 

--

Also I can reproduce the same issue with the [SceneKitReel.Mac](https://github.com/xamarin/mac-ios-samples/tree/master/SceneKitReel) sample but only in the `Release` configuration.

### Expected Behavior
Build successfully  

### Actual Behavior
Build fails

```
***/MarkdownViewer/clang: Error: linker command failed with exit code 1 
***/MarkdownViewer/MMP: Error MM5109: Native linking failed with error code 1.  
```

It works properly if I switch to use `Xcode 9.4.1` instead of `Xcode 10 beta (5)`

### Environment

1. VSfM 7.6 Preview (7.6 build 2131)
https://gist.github.com/mykyta-bondarenko-gl/aabc56cbba4768b09ceb05ce76b7a066

### Build Logs

1. Build output
https://gist.github.com/mykyta-bondarenko-gl/3e7b8c1cee9fcfc546c491c79a12faa0

### Example Project

[Sample](https://github.com/xamarin/mac-samples/tree/master/MarkdownViewer)

**Comment by rolfbjarne** [comment]
This is because it's a 32-bit app.

We should really show a better error message from mmp in this scenario (trying to build a 32-bit app with Xcode 10+).

**Comment by rolfbjarne** [comment]
Just to be clear: the sample needs to be changed/ported to a 64-bit Unified app.
