### ISSUE TITLE
mmp: Show a nice error if user tries to build a 32-bit app with Xcode 10

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#4569]
Repro: build a 32-bit XM app with Xcode 10

Result: many linker failures (full sample log: https://gist.github.com/mykyta-bondarenko-gl/3e7b8c1cee9fcfc546c491c79a12faa0#file-output-L1411)

    Undefined symbols for architecture i386:
      ".objc_class_name_NSAlert", referenced from:
          pointer-to-literal-objc-class-name in libxammac-debug.a(launcher-debug.static.i386.o)
      ".objc_class_name_NSArray", referenced from:
          pointer-to-literal-objc-class-name in libxammac-debug.a(trampolines-debug.static.i386.o)
          pointer-to-literal-objc-class-name in libxammac-debug.a(trampolines-invoke-debug.static.i386.o)
      ".objc_class_name_NSAutoreleasePool", referenced from:
          pointer-to-literal-objc-class-name in libxammac-debug.a(shared-debug.static.i386.o)
      ".objc_class_name_NSBundle", referenced from:
          pointer-to-literal-objc-class-name in libxammac-debug.a(runtime-debug.static.i386.o)
          pointer-to-literal-objc-class-name in libxammac-debug.a(launcher-debug.static.i386.o)
      ".objc_class_name_NSDictionary", referenced from:
          pointer-to-literal-objc-class-name in libxammac-debug.a(runtime-debug.static.i386.o)
          pointer-to-literal-objc-class-name in libxammac-debug.a(launcher-debug.static.i386.o)

We should report a better MM#### error instead.

**Comment by spouliot** [comment]
Fix was merged.
