### ISSUE TITLE
[xcode10] 'Metal Game' fails to build 

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4576]
### Steps to Reproduce

1. Open VSfM
2. Create macOS `Metal Game` app
3. Build it

OR

1. Download a [MetalKitEssentials sample](https://github.com/xamarin/mac-ios-samples/tree/master/MetalKitEssentials) 
2. Open and build it

### Expected Behavior
Build is successful

### Actual Behavior
Build is failed

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(3,3): Error MSB6003: The specified task executable "metal" could not be run. ApplicationName='metal', CommandLine=' -arch air64 -emit-llvm -c -gline-tables-only -ffast-math -std=osx-metal1.0 -serialize-diagnostics obj/x86/Debug/metal/Shaders.dia -o obj/x86/Debug/metal/Shaders.air Shaders.metal', CurrentDirectory='', Native error= Cannot find the specified file (MSB6003) (Test)
```

### Environment

1. VSfM 7.6 Preview (7.6 build 2135)
https://gist.github.com/mykyta-bondarenko-gl/ef16ac39ec37d627700a39960f179d05

### Build Logs

1. VSfM output
https://gist.github.com/mykyta-bondarenko-gl/0ac2f4b6f194b6f548ccad9cf0267d08
2. msbuild output
https://gist.github.com/mykyta-bondarenko-gl/0b7d79dbb3e6461c12edc34f2814d97f

### Example Project 
- [Example](https://github.com/xamarin/xamarin-macios/files/2262136/Metal_Game_Sample.zip)
- [MetalKitEssentials](https://github.com/xamarin/mac-ios-samples/tree/master/MetalKitEssentials)

**Comment by mandel-macaque** [comment]
Confirmed with the following [version](https://gist.github.com/mandel-macaque/82c6fb403dee74c396b52602e3eff596).

**Comment by VincentDondain** [comment]
Argh Apple moved the `metal` binary around in Xcode 10. It's no longer at `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/bin/metal`

**Comment by VincentDondain** [comment]
They are using `/Applications/Xcode10-beta5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/metal`

**Comment by VincentDondain** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/pull/4601
