### ISSUE TITLE
[xcode10] 'Tabbed Forms App' template fails on launch (simulator)

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4577]
### Steps to Reproduce

1. Create `Tabbed Forms App`
2. Build it
3. Run it on Simulator 12.0 (it works properly on device 12.0)

OR

1. Download a [sample](https://github.com/xamarin/xamarin-macios/files/2262548/TestTabbed.zip)
2. Build and run it on Simulator 12.0

### Expected Behavior
It runs successfully

### Actual Behavior
It crashes on launch

```
 Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[UIImage _selectedTabBarItemImageWithTintColor:metrics:style:forScreenScale:]: unrecognized selector sent to instance 0x600000236060
```

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/36b0b082a41b9703b9a92fc70c097f1f

### Build Logs

1. Exception
https://gist.github.com/mykyta-bondarenko-gl/086866109af15ad5115733f90894ada3
2. Stacktrace
https://gist.github.com/mykyta-bondarenko-gl/42a643e47895e3ddfa673324ee850c0b
3. VSfM output
https://gist.github.com/mykyta-bondarenko-gl/e5e60b8e7708919a28116cccae4d010d

### Example Project 
[TestTabbed.zip](https://github.com/xamarin/xamarin-macios/files/2262548/TestTabbed.zip)

**Comment by mykyta-bondarenko-gl** [comment]
I think it's similar to: https://github.com/xamarin/xamarin-macios/issues/4305.
But there is another exception.

**Comment by VincentDondain** [comment]
Yea I highly suspect it's similar to #4305 but since it's indeed a different crash I think it's better to keep this as a separate bug. If we fix one of the two bugs we'll check if it fixes the other.

**Comment by mandel-macaque** [comment]
As with issue #4305 passing --registrar:static to mtouch allows to run the app in a sim with the Xcode 10 branch.

**Comment by mandel-macaque** [comment]
@mykyta-bondarenko-gl @VincentDondain I have tested the attached project on a iOS 8.* simulator with Xcode 10 beta 6 and the issue does not longer happen, can you please test it and let me know if that is the case:

[CleanTabbedApp.zip](https://github.com/xamarin/xamarin-macios/files/2297115/CleanTabbedApp.zip)

**Comment by mykyta-bondarenko-gl** [comment]
Hi @mandel-macaque 
Your sample crashes :( 
- Output: https://gist.github.com/mykyta-bondarenko-gl/b9865cc72b39de2b598f9d0f243c78ff
- VSfM: https://gist.github.com/mykyta-bondarenko-gl/2c161812aed7d46397a92235233de591

**Comment by mandel-macaque** [comment]
@mykyta-bondarenko-gl please test with [the following environment](https://gist.github.com/mandel-macaque/f977c7348405f6204fd45665753a6757) if possible. I got the application running without any issues and without needing to change the registrar.

**Comment by VincentDondain** [comment]
Yup I could confirm this works with beta 6 now! 🎉 

Closing the issue.

**Comment by mykyta-bondarenko-gl** [comment]
I confirm that it works for me with the latest xcode10 XI build. Thanks!

**Comment by VincentDondain** [comment]
Seems like the fix is more an XI built with Xcode 10 beta 6 (e.g: 
https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10/347f472b033073e732b05b33a7e6fe93b37a3d49/145/package/xamarin.ios-11.99.3.243.pkg) than just installing the Xcode 10 beta 6 command line tools as I initially thought.
