### ISSUE TITLE
Xamarin.iOS experience is just terrible

### ISSUE THREAD

**Issue by rihadavid** [xamarin/xamarin-macios#4580]
**Please do not take this as an incorrectly specified bug report. I know how a bug report should look.
This is not a bug report.**
**This is a desperate call for reflection on the state of Xamarin.iOS or a general frustration letter.**
I don't know if you even know that things are so terrible.
In case you don't care or don't like my attitude, just close it, sorry.

**So, this is how my iPhone debugging usually goes:**
The app is building a few minutes (not quite fast..), then I get an alert that I am disconnected from Mac, which I am not. So, I disconnect, connect again, dismiss another alert telling me that I was disconnected, go to configuration manager to uncheck build (so that it does not start building again because the build was fine, just the connection failed) and I run the app on my iPhone 5S with iOS 11.4.1.

> _This one bug is actually already [fixed](https://developercommunity.visualstudio.com/content/problem/230433/xamarin-build-host-keeps-disconnecting-after-a-sec.html?childToView=277784#comment-277784) for 3 months (users are complaining about it since April!), but while we got about 10 subversions of VS 15.6 and 15.7, **this bugfix is going to be available in VS 15.8**._

So, the app starts running, my homescreen appears and in a few seconds, before I can actually do anything, the app freezes. Probably some deadlock in the debugger. So I try to deploy again and again and for the fourth try, the app finally runs smoothly.

> _Worth saying, the deadlock is definitely not in my app - it is in the Xamarin.iOS debugger. It never happened in the app without debugging and it never happened in the simulator. I mean never, in a few years. But when debugging on iPhone, it is happening regularly, for a few years now._

Well, when the app is finally running and I want to debug some stuff, it works for a while but then the VS stops responding, because I hover with my mouse over something and it started endlessly "Getting DataTip text" (or I just manually wanted to get some value in Locals, also fails often) and VS gets busy.

> _This is also happening ever since I can remember, I actually tried to report it once, but they said they can't reproduce it._

So I force-restart the VS, which means it does not open the last opened project, so I go to Connections, find my Git, then find my solution and open it. Then I proceed to connecting to Mac Agent, which, brace youself, does not give me the list of devices.

> _This is happening every time. When I force-quit VS because it got busy, I need to restart it twice, because first time, the connected Mac Agent does not offer the devices._

So, restarting VS again, connecting to Mac Agent again. This time, everything will hopefully be ok. I mean, for 10, 20 or 30 minutes. Then all of this starts again. And then again. And again.

Summarized, I can easily spend 20 minutes on a simple iPhone debugging task, which would be done in 5 minutes if things would work. Not mentioning how much it affects my productivity.

Thanks for reading.

Please also note, that I used to report Xamarin bugs in the past, but lately, I feel like it is a worthless effort because it does not get fixed in [MONTHS](https://developercommunity.visualstudio.com/content/problem/230433/xamarin-build-host-keeps-disconnecting-after-a-sec.html?childToView=277784#comment-277784).

### Environment

```
Mac OS X 10.13.4 inside VMWare Workstation 14 Pro (14.1.2)

Microsoft Visual Studio Community 2017 
Version 15.6.6 //yeah, I don't want to get into even more trouble updating to something new, waiting for the xamarin fixes in 15.8
VisualStudio.15.Release/15.6.6+27428.2037
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual F# Tools 10.1 for F# 4.1   00369-60000-00001-AA614
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10402.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

AWS Toolkit for Visual Studio 2017   1.14.4.0
AWS Toolkit for Visual Studio 2017.
Copyright 2011-2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://aws-vs-toolkit.s3.amazonaws.com/versioninfo.html

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License 
  [http://logging.apache.org/log4net/license.html]
- Putty for PPK to PEM conversion, MIT license 
  [http://www.chiark.greenend.org.uk/~sgtatham/putty/licence.html]
- NGit for AWS Elastic Beanstalk incremental push
  [https://github.com/mono/ngit/blob/master/NGit.license.txt]
- NSch dependency for NGit
  [https://github.com/mono/ngit/blob/master/NSch.license.txt]
- Sharpen dependency for NGit
  [https://github.com/mono/ngit/blob/master/Sharpen/AssemblyInfo.cs]
- ICSharpCode.SharpZipLib dependency for NGit
  [http://www.icsharpcode.net/opensource/sharpziplib/]
- Mono.Posix.dll and Mono.Security.dll dependencies for NGit
  [http://mono-project.com/FAQ:_Licensing#Licensing]
- MPFProj for Visual Studio Project Framework
  [http://mpfproj10.codeplex.com/license]
- JSON Checker for JSON validation
  [http://www.raboof.com/projects/jsonchecker/]
- Newtonsoft Json.NET
  [http://www.newtonsoft.com/json] 
- YamlDotNet
  [http://aaubry.net/pages/yamldotnet.html] 
    

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.11027.3
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.753 (f0f46392f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.96 (a702a9ceb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.9.1.24 (f62de47)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

> VS bug [#660373](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/660373)

**Comment by victorgarciaaprea** [comment]
Hi @rihadavid,

First of all, thank you for taking the time to do this write up, this is very appreciated. And I'm very sorry to hear you are having such a bad experience while using our bits.

By going through your list of issues, I believe most of them, if not all, should already be fixed in 15.8.

It's true like you mention that we failed to fix some of them as early as possible (in 15.7) and they didn't make it until 15.8. We have improved our triaging process since then and hopefully this shouldn't happen again. Some others are already in there in 15.7.

I can totally feel your pain, like when you mention the "Getting DataTip text" and VS freezes for a few seconds. In 15.8 we have started using new VS debugger core support for async operations so this is now very fast. This is part of a push we are making to improve the debugging experience in 15.8 and 15.9.

On the Mac connection side, we have been working on fixing and enhancing that experience a lot too, with most of the fixes going into 15.7 and 15.8.

I realize you are on 15.6 and you are not ready to move to 15.8 just yet, and I can understand that too. I hope you give us a chance when 15.8 goes stable because I am sure you will get a much better experience.

It would be great, if you can afford the time, if you can get in contact with me via email (vga AT microsoft DOT com) so I can loop you with the developers involved in the fixes above, and we can make sure that everything you mention above is covered. We can report back to this thread after that.

Sorry again for the bad experience you are currently having on 15.6.

thanks,
-VGA.
