### ISSUE TITLE
[Xcode10]tvOS ODR extension sample submission fails with an error, " "Invalid sdk value. The value provided for the sdk portion of LC_VERSION_MIN_TVOS  is 94.0 which is greater than the maximum allowed value of 12.0."

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4582]
### Steps to Reproduce

1. Archive https://github.com/xamarin/SubmissionSamples/tree/master/ODRsTVOS_Extension
2. Submit tvOS extension.ipa using Application Loader

### Expected Behavior
App gets submitted successfully

### Actual Behavior
App fails to submit with an error ,  "Invalid sdk value. The value provided for the sdk portion of LC_VERSION_MIN_TVOS in ODRsTVOS.app/Frameworks/Mono.framework/Mono is 94.0 which is greater than the maximum allowed value of 12.0."

### Environment
```
=== Visual Studio Community 2017 for Mac ===

Version 7.5.4 (build 7)
Installation UUID: 519fc1da-445a-45d9-9748-27fa26180fd4
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.193 (master / 64fece5f)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Version: 2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.2.4)
Build 10L221o

=== Xamarin.Android ===

Not Installed

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.99.2.130 (Visual Studio Community)
Hash: 86e97b10
Branch: HEAD
Build date: 2018-08-04 01:01:50-0400

=== Build Information ===

Release ID: 705040007
Git revision: 1fcae95fd5b606f806c3b1d445237f675c395fdd
Build date: 2018-08-02 18:48:50+00
Xamarin addins: 48a82b251ec0ef78cb92223061ea448f967f4ec2

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.5
```

### Build Logs

Build Log: https://gist.github.com/GouriKumari/625fe88e90ca1f980db17fb51802274c
Error Log: https://gist.github.com/GouriKumari/e402e5b7f58718b93c4013a80b694c7a

### Example Project (If Possible)
https://github.com/xamarin/SubmissionSamples/tree/master/ODRsTVOS_Extension

**Comment by VincentDondain** [comment]
Mmh not sure where that `LC_VERSION_MIN_TVOS` is located in the IPA. Will try to send to Application Loader tomorrow to confirm this.

**Comment by VincentDondain** [comment]
Ah this issue is similar to https://bugzilla.xamarin.com/show_bug.cgi?id=41597.
I could confirm by doing a `otool -l /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/Xamarin.AppleTVSimulator.sdk/Frameworks/Mono.framework/Mono | grep LC_VERSION_MIN_TVOS -A 3` locally.
It was supposed to be fixed in https://github.com/xamarin/xamarin-macios/commit/834c0a9fd7062c0c25011721fd7d524b8a60b41e

**Comment by VincentDondain** [comment]
Ah that regressed in the bump PR: https://github.com/xamarin/xamarin-macios/commit/2d6ce7459d3e2a04c0dbcb83885cf173cc718b5b#diff-f682ea58f8badb13b9f8ed17cda4deb7R235.

`AppleTVSimulator$(TVOS_SDK_VERSION).sdk` -> `AppleTVSimulator.sdk`

**Comment by VincentDondain** [comment]
@rolfbjarne you undid your own fix in https://github.com/xamarin/xamarin-macios/pull/4179/commits/7227d8c4782f5c2a7b50c2258503539a1513431a (original PR https://github.com/xamarin/xamarin-macios/pull/244). The comment is not specific enough to understand why exactly the change was needed (I'm sure there was a good reason though).

**Comment by spouliot** [comment]
That seems to be the same issue (and `ld` bug) but we should not be building tvOS with Xcode94 inside the `xcode10` branch.

@rolfbjarne in `builds/Makefile` there's a 
```
XCODE_DEVELOPER_ROOT=$(XCODE94_DEVELOPER_ROOT)
export DEVELOPER_DIR=$(XCODE_DEVELOPER_ROOT)
```
are we building everything with 9.4 ?
