### ISSUE TITLE
Xamarin.iOS: Nullable DateTimeOffset can't use Property.SetInfo

### ISSUE THREAD

**Issue by samhouts** [xamarin/xamarin-macios#4584]
_From @MaxFe on August 6, 2018 16:19_

This error occured the first time while deserializing a json string. The destination object had a nullable DateTimeOffset. Using a DateTimeOffset works fine. The statement from Xamarin.iOS documentation is "Using Reflection's Property.SetInfo to set the value on a Nullable<T> is not currently supported.".

### Description
Xamarin.iOS limitations:  https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations  
EF Core should have the same problem: https://bugzilla.xamarin.com/show_bug.cgi?id=61053
Since AutoMapper (version 7.0.1) is using reflection too it might have the same problem (untested).

### Steps to Reproduce

1.  Create an object with nullable DateTimeOffset
2.  Create a json string for that object where the DateTimeOffset variable is null
3.  Deserialize this string -> crash

### Expected Behavior
Should deserialize like not nullable DateTimeOffset

### Actual Behavior
App crash on deserialize nullable DateTimeOffset

### Basic Information

- IDE: Visual Studio for Mac 7.5.4 (Build 3)
- Platform Target Frameworks: 
  - iOS:  11.4.1 (15G77)
- Nuget Packages:  Newtonsoft.Json 11.0.2
- Affected Devices: iPad

_Copied from original issue: xamarin/Xamarin.Forms#3490_

**Comment by VincentDondain** [comment]
Please include a test case (to reproduce), your full build logs, crash reports (if any) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by rolfbjarne** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
