### ISSUE TITLE
[XM] store submission issue ("***apps that use QuickTime or QTKit APIs")

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4594]
### Steps to Reproduce

1. Download a [sample](https://github.com/xamarin/SubmissionSamples/tree/master/MacCoolApp_DontLink)
2. Archive and send it to the `iTunesConnect`

Also you can find a difference between 2 build outputs (`xcode10` and `master`) that can cause the issue. 

### Expected Behavior
Submission is successfully 

### Actual Behavior
A new email from Apple:
```
Deprecated API Usage - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs.
```

Everything is ok if I use `xcode 10` branch build.

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/6d7e01d7c3074921be13d667143e110c
2. `xcode-select -p`
"/Applications/Xcode.app/Contents/Developer"

### Build Logs

1. build output (`xcode10`)
https://gist.github.com/mykyta-bondarenko-gl/81ccd7107035db70ed912be2673bfcda
2. build output (`master`)
https://gist.github.com/mykyta-bondarenko-gl/59526bcbeb8b2e610d565046096fd24d

### Example Project
[Sample](https://github.com/xamarin/SubmissionSamples/tree/master/MacCoolApp_DontLink)

**Comment by chamons** [comment]
@mykyta-bondarenko-gl - Does both xcode10 and master fail to submit or just one? If master does, what about 15-8/15-7?

**Comment by spouliot** [comment]
@chamons it seems the response file is not used for `--linkplatform`

```
  Task "Mmp"
    /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp --linkplatform @/Users/mac_admin/Projects/Xamarin/SubmissionSamples/MacCoolApp_DontLink/MacCoolApp/obj/Release/response-file.rsp 
    Provided arguments:
        --linkplatform
        @/Users/mac_admin/Projects/Xamarin/SubmissionSamples/MacCoolApp_DontLink/MacCoolApp/obj/Release/response-file.rsp
    Provided arguments:
            /verbose
            /output:/Users/mac_admin/Projects/Xamarin/SubmissionSamples/MacCoolApp_DontLink/MacCoolApp/bin/Release/
            /name:MacCoolApp
            '/profile:Xamarin.Mac,Version=v2.0,Profile=Mobile'
            /arch:x86_64
            --http-message-handler=HttpClientHandler
            /minos=10.10
            /nolink
```

^ and the response file `--nolink` is overriding `--linkplatform`

**Comment by chamons** [comment]
@spouliot you nailed the source of the problem exactly. PR coming soon.

**Comment by mykyta-bondarenko-gl** [comment]
Shouldn't be this merged into xcode10 branch? @chamons @spouliot

**Comment by chamons** [comment]
We aren't releasing out of xcode10 for XM. It just needs to be in the respective D15-X branches.

**Comment by spouliot** [comment]
@chamons the commit also change how the arguments are given to mtouch - since the *fixed* (not reported) issue is the extra argument ordering.

**Comment by chamons** [comment]
Good point, thanks for https://github.com/xamarin/xamarin-macios/pull/4769

**Comment by spouliot** [comment]
backport merged in 
https://github.com/xamarin/xamarin-macios/pull/4769
