### ISSUE TITLE
Designer Feature: Regenerate the generated bindings

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/xamarin-macios#4602]
Today when you use the iOS designer, there is no way of generating the classes that are referenced.   This can happen when you copy a storyboard from one project to another, or when you bring an Xcode storyboard into Visual Studio.

Proposal: add a contextual option to regenerate the backing code "Regenerate Bindings".

# Background

There are some workarounds, that include modifying every bound class in the designer to force the generation and then renaming things back - this will usually do the trick.

You can see that this is an issue that our users have struggled for a while:

https://forums.xamarin.com/discussion/7681/how-to-regenerate-a-view-controllers-designer-cs-file

I did try some of those, and while they can be made to work, they require some trial and error until one of those things triggers the change, plus manual cleanup after that.

> VS bug [#661168](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/661168)

**Comment by rolfbjarne** [comment]
The designer has been deprecated/removed, so this doesn't apply anymore.
