### ISSUE TITLE
Designer Feature: Import Xcode storyboard

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/xamarin-macios#4603]
Bringing an Xcode storyboard into Xamarin poses a couple of problems:

* Generally, outlets and connections are not surfaced to user code and can be difficult to diagnose from the generated errors.

* Swift module name is embedded into the storyboard which is not mapped in .NET, leading to difficult to diagnose problems (just a crash on the console showing a mangled type)

It would be nice if we could validate the storyboards that are added in this way, or to have either an analyzer step, or a validation process that guides the user through solving the problem (in this case, remove all outlet connections, inform the user of what to do, and drop the module name)

> VS bug [#661169](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/661169)

**Comment by rolfbjarne** [comment]
The designer has been deprecated/removed, so this doesn't apply anymore.
