### ISSUE TITLE
[metal] Incorrect structs in Metal/Defs.cs

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#4611]
These structs are incorrect: https://github.com/xamarin/xamarin-macios/blob/master/src/Metal/Defs.cs#L278-L305

They do not match the native struct's size and potentially alignment.

```
typedef struct {
    /* NOTE: edgeTessellationFactor and insideTessellationFactor are interpreted as half (16-bit floats) */
    uint16_t edgeTessellationFactor[4];
    uint16_t insideTessellationFactor[2];
} MTLQuadTessellationFactorsHalf;

typedef struct {
    /* NOTE: edgeTessellationFactor and insideTessellationFactor are interpreted as half (16-bit floats) */
    uint16_t edgeTessellationFactor[3];
    uint16_t insideTessellationFactor;
} MTLTriangleTessellationFactorsHalf;
```

We cannot have `ushort[]` the ushort need to be inlined, fixed size.

In addition we should have tests that ensure the size of the managed struct is equal to the size of the native struct.

**Comment by rolfbjarne** [comment]
Ugh, this is ugly.

That said, I wonder if we can fix it with a `[MarshalAs]` attribute on the broken fields (or may just adding `fixed` would fix it).

**Comment by spouliot** [comment]
I think `[MarshalAs]` would fix it - but if need to come with tests that shows the native and managed size are identical.

I wonder if we could generate (something like xtro) a list of struct with size (32/64) and use a test (like intro) to ensure everything match. Might not be possible to have it fully automated - but it would be nice not to test them all manually.
