### ISSUE TITLE
CoreSpotlight.framework/CSSubscriptionManager

### ISSUE THREAD

**Issue by vfumin** [xamarin/xamarin-macios#4616]
### Steps to Reproduce

Need CSSubscriptionManager from CoreSpotlight.framework.
Link with class header:
https://github.com/nst/iOS-Runtime-Headers/blob/master/Frameworks/CoreSpotlight.framework/CSSubscriptionManager.h

### Expected Behavior

CSSuscriptionManager is available for using.

### Actual Behavior

Can't find CSSubscriptionManager in Xamarin

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: a2ffc65f-e20c-48ee-9386-973a53ad4ab3
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: Not found

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.5

```

### Comment

CSSubscriptionManager is hidden in CoreSpotlight, in xcode i can use it by appending header file of this class.

https://github.com/nst/iOS-Runtime-Headers/blob/master/Frameworks/CoreSpotlight.framework/CSSubscriptionManager.h

**Comment by spouliot** [comment]
The link you provide is to a file that is automatically generated from Apple binaries/libraries, i.e. it's not the _official_ (Xcode) Apple SDK headers and such files contains every symbols - including **private** symbols which are **not** allowed in the App Store.

IOW the `CSSubscriptionManager` type/symbol exists but I cannot find any mention, from Apple, that it is **public** symbol available to application developers.

As a policy Xamarin.iOS only ships bindings for public symbols (from Xcode SDK headers). You can, at your own risk, include bindings to private symbols. However your application is likely to be rejected (now or later) in Apple's app submission process.
