### ISSUE TITLE
[mono2018-06]mini test failure with mono2018-06

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4618]
### Steps to Reproduce

1.  Update System to Xamarin.iOS from mono2018-06 branch, XI version: 11.15.0.48 (PR-4277: 3901d8e2) 
2. Execute mini tests on a device. Tests executed on a 32 bit device with iOS version 9.3.5

### Expected Behavior
All tests should pass
### Actual Behavior
[FAIL] JitTests.Objects :   Expected: 0
### Environment
```
Mono version: 5.16.0.108 (7a9c54ebd45)  (2018-08-13 12:19:08 -04:00)
XI version: 11.15.0.48 (PR-4277: 3901d8e2) 
XM version: 4.7.0.48 (3901d8e2)  (2018-08-08 06:27:48 -04:00)
XS version: 7.7.0.830 (2dac6bd)  (2018-08-13 12:35:26 -04:00)
```

### Build Logs

Build Log: http://xqa.blob.core.windows.net/gist/report-f43437d114b945608b86a397311eeabf.txt
Test Log: http://xqa.blob.core.windows.net/gist/mscorlib-tvos06-15-2985652fd1ecb4eddd80ebefb1562b316473fa559b06-15-29-5fa48680f8244f2eb519b3941b11efe5.zip
### Example Project (If Possible)

xamarin-macios/tests/mini/mini-ios

**Comment by lewurm** [comment]
maybe related https://github.com/mono/mono/pull/10096

**Comment by vargaz** [comment]
Will be fixed by
https://github.com/mono/mono/pull/10096

**Comment by spouliot** [comment]
mono `2018-06` was merged in master
The mini tests now run successfully on 32 bits
