### ISSUE TITLE
Interface Builder - Switching back to VS4M causes the project to be unloaded in Xcode

### ISSUE THREAD

**Issue by alexkblount** [xamarin/xamarin-macios#4620]
### Steps to Reproduce

1. Create new Xamarin iOS Application
2. Right Click Storyboard
3. Open in Interface Builder
4. Edit the ViewController
5. Switch focus back to VS4M
6. Switch focus to Xcode

### Expected Behavior

State of Interface Builder should be intact and editing of the Storyboard should be possible.

### Actual Behavior

Xcode project is unloaded and no longer able to edit

### Environment

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.5.4 (build 3)
Installation UUID: 59e8a0c2-a674-42a6-b852-843de896e0eb
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.301/Sdks
SDK Version: 2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Enterprise)
Android SDK: /Users/blounty/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 28.0.2

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Enterprise)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Enterprise)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705040003
Git revision: 6ae731889c896d6733efb8ff5117f5bf5b17b509
Build date: 2018-07-19 13:07:45-04
Xamarin addins: 417fed09624e1e1f76ab0a11e8b97ffd8bbf91e1
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

<img width="1667" alt="screen shot 2018-08-14 at 11 06 52 am" src="https://user-images.githubusercontent.com/30159621/44109555-30399fb0-9fb2-11e8-958d-c32891a826f4.png">

> VS bug [#665000](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/665000), VS bug [#752186](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752186)

**Comment by mandel-macaque** [comment]
Hello, thanks for reporting the issue. Unfortunately this repository is the one that is used to maintain the bindings of the platforms and not the designer itself. Nevertheless no need to worry. I will tag the issue for the designer team to take a look and the will be back to you ASAP. 

Again, thanks for the great report!

**Comment by mandel-macaque** [comment]
So, I'm trying to understand a little further the issue, when you state:

"Edit the ViewController"

Is that from VSfM? Are you ever using the iOS designer from VSfM?

**Comment by alexkblount** [comment]
In Xcode, this issue is if you are trying to edit the UI in Xcode Interface Builder. I had not opened the storyboard in VS4M at all prior.

**Comment by mandel-macaque** [comment]
@alexkblount changed the label accordingly for the right team to take a look

**Comment by jstedfast** [comment]
This seems to happen when your Apple SDK Settings in VSMac point to a Xcode path that does not match the *actual* Xcode path that is running.

For example, if I move my `/Applications/Xcode.app` to `/Applications/Xcode10.app` and then create a symlink from `/Applications/Xcode.app` to `/Applications/Xcode10.app` and configure VSMac to point to the symlink (`/Applications/Xcode.app`), then I can get this to happen.

The solution is to have VSMac point to the actual location of Xcode's app bundle.
