### ISSUE TITLE
MethodInfo.Invoke fails for generic methods with too many/too large arguments

### ISSUE THREAD

**Issue by Dabbel** [xamarin/xamarin-macios#4636]
Is this bug really fixed?

https://bugzilla.xamarin.com/show_bug.cgi?id=59184

Still getting the same error with Xamarin.iOS 11.14.

**Comment by mandel-macaque** [comment]
As per the replies on that issue. Yes it was fixed and release. But that might not be the exact same issue you are experiencing. Can you please provide a sample project that exercises/exposes the issue as well as the full environment information of you system? 

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

**Comment by mandel-macaque** [comment]
@Dabbel I'm setting the issues as a dup of https://github.com/xamarin/xamarin-macios/issues/4635 since @taikodragon provided a sample to reproduce it
