### ISSUE TITLE
MTOUCH: Error MT5216: Native linking failed for libBindingProject.dll.dylib'. MT5216

### ISSUE THREAD

**Issue by vpatelalk** [xamarin/xamarin-macios#4638]
I am trying to use by ObjectiveC library in Xamarin.iOS project. In order to use it, I have used Objective Sharpie and created a Binding project which I refer into Xamarin.iOS application. Binding works however while building Xamarin.iOS application it gives me linking error.

Please find the attached error logs which will give you some insight.
[BuildLog.txt](https://github.com/xamarin/xamarin-macios/files/2297759/BuildLog.txt)

I am using Visual Studio for Mac Community 7.5.2 (build 40)

Please find the attached binding project and sample application. As size is way too large, I have uploaded to dropbox and following is the link to download
https://www.dropbox.com/s/ji8oztok1jh8dy3/BindingProject.zip?dl=0

**Comment by mandel-macaque** [comment]
I have tested the provided sample and can reproduce the build error:

- [Xamarin Env](https://gist.github.com/mandel-macaque/9ba1a9c877ce60e3a79720485e42893e).
-[ Build output.](https://gist.github.com/mandel-macaque/dd69fa5293d4d4c0584222b2df5ee56b)

**Comment by mandel-macaque** [comment]
@vpatelalk to clarify, it looks like the framework does not contain all the architectures required and does fail, for example, when building for the emulator (not ARM).
