### ISSUE TITLE
Reproducible native crash bug with WKWebView in latest Xamarin.iOS, Fixed in Xamarin iOS 11.13.0.19 but not in 11.14(current stable) 

### ISSUE THREAD

**Issue by kalyanmungi** [xamarin/xamarin-macios#4678]
### Steps to Reproduce

1. https://github.com/xamarin/xamarin-macios/issues/4130 -- same issue
2. 
3. 

### Environment

```
```

**Comment by kalyanmungi** [comment]
Closing and opening WKWebView for 2 or 3 times, crashing the app.

**Comment by spouliot** [comment]
The 11.13 package mentioned in #4130 was a "custom" package made from the PR (and not a release branch) to validate the fix.

The milestone for #4130 is `d15.9`, which will be XI 11.16. A preview of this will be available soon but any recent 11.15 build will also have the fix.

**Comment by kalyanmungi** [comment]
I verified this in Xamarin iOS 11.99, which is xcode 10 preview channel, which doesn't have fix too.

**Comment by spouliot** [comment]
**TL&DR in general all minor-even (e.g. XI 11.14) are stable releases, while all minor-odd (e.g. XI 11.13 or 11.99) are unstable/previews.**

> I verified this in Xamarin iOS 11.99, which is xcode 10 preview channel, which doesn't have fix too.

No it won't. It's our Xcode 10 support release and it needs to be ready whenever Apple ships so it's always based on the latest stable. 

The 3rd preview (available right now) that supports Xcode 10 is based on our 15.7 milestone (does not have the fix). Our next 4th preview (soon to be released) will be based on 15.8 milestone (which does not have the fix either).

Our 15.9 milestone will *likely* be released after Apple release Xcode10. In such case the 15.9 milestone, which include the fix, will (again likely) be re-numbered to XI 12.2.
