### ISSUE TITLE
Not able to upload  iOS 12 beta release build to iTunes

### ISSUE THREAD

**Issue by blerb** [xamarin/xamarin-macios#4680]
I am getting error everytime I am trying to upload a build to iTunes.

Build upload error:
ERROR ITMS-90512: "Invalid sdk value. The value provided for the sdk portion of LC_VERSION_MIN_IPHONEOS in yourapp.app/Frameworks/Mono.framework/Mono is 94.0 which is greater than the maximum allowed value of 12.0."

Build Details:
iOS 12 
Xcode 10 beta 6
Xamari.iOS: 11.99.2.130 (Visual Studio Community)

**Comment by VincentDondain** [comment]
That is to be expected.

Apple **does not** accept submissions using **beta** software/toolchain.

Please try again next fall with our Xcode 10 Xamarin.iOS update (you'll see a blog post) after Apple release Xcode 10 publicly.

**Comment by rolfbjarne** [comment]
This is a duplicate of #4582, and will be fixed in the next Xcode 10 preview release.
