### ISSUE TITLE
[XI].ipa created  using release config and archive for publishing behaves differently with wildcard profiles

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4730]
### Steps to Reproduce

1. Open iOS project, https://github.com/xamarin/SubmissionSamples/tree/master/iOSCoolApp
2. Use wildcard iOS distribution profiles
3. Archive the project for publishing
4. App archives successfully and gets uploaded to AppStoreConnect without any error message
5. Build a .ipa using release|iphone config and wildcard iOS distribution profile
6. Upload .ipa using Apploader

### Expected Behavior
App uploads successfully

### Actual Behavior
App fails to upload with an error, ERROR: ERROR ITMS-90211: "Invalid Code Signing Entitlements. The signature for your app bundle contains entitlement values that are not supported. For the 'com.apple.developer.ubiquity-container-identifiers' entitlement, the values in the array must start with the prefix provided by Apple in the provisioning profile, followed by characters that are uppercase or lowercase Roman letters [A-Z, a-z], the digits 0 through 9, dot ['.'], or hyphen ['-'], and not contain any wildcard characters. Specifically, value 'DPXCPAGVTZ.*' for the key 'com.apple.developer.ubiquity-container-identifiers' in 'Payload/iOSCoolApp.app/iOSCoolApp' is not supported."

The issue here is why building of a .ipa behaves differently with release|iPhone and archive for publishing. Results from both steps should be identical

### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.2 (build 33)
Installation UUID: 74c37335-5878-4fa7-8f71-09bc48b661c5
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Enterprise)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/gourikumari/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 25.2.3
SDK Platform Tools Version: 25.0.1
SDK Build Tools Version: 25.0.1

Java SDK: /usr
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 11.14.0.14 (Visual Studio Enterprise)
Hash: 1a6e2786
Branch: HEAD
Build date: 2018-08-28 00:12:06-0400

=== Build Information ===

Release ID: 706020033
Git revision: 609ad78d9663b4881e650898e6b4a4ba86383ba8
Build date: 2018-08-27 21:40:35+00
Build branch: release-7.6
Xamarin extensions: f9882ea2b3117c8baefdb53288c9253760fe5692

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:59:21 PDT 2018
    root:xnu-4903.201.2~4/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Gist Ide Information 1.1.0
Internet of Things (IoT) development (Preview) 7.5

```

### Build Logs

https://gist.github.com/GouriKumari/c809987e6a89dad0d2a02183b4c96ee9
"""
### Example Project (If Possible)

https://github.com/xamarin/SubmissionSamples/tree/master/iOSCoolApp

**Comment by rolfbjarne** [comment]
I don't think it's allowed to publish an app using a wildcard profile, so this seems like expected behavior to me.
