### ISSUE TITLE
xamarin.ios fail to decrypted messaged encryted by dotnet core desktop

### ISSUE THREAD

**Issue by ForkBug** [xamarin/xamarin-macios#4734]
1. Get exception "Bad PKCS7 padding. Invalid length xxx."
callstack is 
  at Crimson.CommonCrypto.FastCryptorTransform.ThrowBadPaddingException (System.Security.Cryptography.PaddingMode padding, System.Int32 length, System.Int32 position) [0x00047] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.13/src/Xamarin.iOS/mcs/class/corlib/CommonCrypto/FastCryptorTransform.cs:198 
  at Crimson.CommonCrypto.FastCryptorTransform.FinalDecrypt (System.Byte[] inputBuffer, System.Int32 inputOffset, System.Int32 inputCount) [0x0011e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.13/src/Xamarin.iOS/mcs/class/corlib/CommonCrypto/FastCryptorTransform.cs:314 
  at Crimson.CommonCrypto.FastCryptorTransform.TransformFinalBlock (System.Byte[] inputBuffer, System.Int32 inputOffset, System.Int32 inputCount) [0x0001b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.13/src/Xamarin.iOS/mcs/class/corlib/CommonCrypto/FastCryptorTransform.cs:345 

2. Decryption code:
`  
            _aes = Aes.Create();

            _aes.BlockSize = 128;

            _aes.KeySize = 256;

            _aes.Mode = CipherMode.CBC;       
     
             _aes.GenerateKey();

                _aes.Padding = PaddingMode.PKCS7;

                Decryptor = _aes.CreateDecryptor();

                Encryptor = _aes.CreateEncryptor();

                Decryptor.TransformFinalBlock(b2, 0, b2.Length);`

Exception got throw in  Decryptor.TransformFinalBlock

Encryption code:
`            
Aes = Aes.Create();

            Aes.BlockSize = 128;

            Aes.KeySize = 256;

            Aes.Padding = PaddingMode.PKCS7;

            Aes.Mode = CipherMode.CBC;
`
3. Encryption always works but decryption not.
4. Decryption works in dotnet core desktop, iphone simulator and previous xamarin.ios version. But not for the one with vs 2017 15.8.2 on iphone
5. It works if  we retry it after some seconds later.

**Comment by mandel-macaque** [comment]
@ForkBug Thanks for the issue report. Can I ask you for some extra information to filly understand what is going on. First, could you provide the FULL environment information? I know you provide the vs version, but I little more information will be welcome.

The easiest way to get exact version information:
- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.
Then copy/paste the version information (you can use the "Copy Information" button).

Also, could you provide a small sample the reproduces the issue? I will be good to fully understand the problem and also to debug the issue. Thanks in advance!

**Comment by ForkBug** [comment]
Mini reproduced project https://github.com/ForkBug/AESBug
1. Run Encryption, get "pwd" and "data" files
2.copy the 2 files to AESBug\AESBug\Resources
3. run AESBug on iphone, an exception throw in TransformFinalBlock .
I think the key is, the desktop version of TransformFinalBlock could handle data longer than one block size but xamarin.ios not.

It may be about robustness, not a bug.

**Comment by mandel-macaque** [comment]
@ForkBug oh! nice find, so the git file does not work, yet the one locally does? how are you pushing that guy?

**Comment by spouliot** [comment]
If you use [`ICryptoTransform`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.icryptotransform.canreusetransform?view=netframework-4.7.2) directly then you have to check its properties, e.g. `CanReuseTransform` and `CanTransformMultipleBlocks` and adjust your code appropriately. The _transform_ instance being return varies across implementation and those properties allows higher-level code to adjust themselves.

To avoid this you should use [`CryptoStream`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptostream?view=netframework-4.7.2) (or something even more high level) as it will do all the right checks for you.
