### ISSUE TITLE
[regression] iOS app build fails when referencing package (e.g. Entity Framework Core 2.1) that depends on newer System.Memory in d15-9

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#4761]
### Steps to Reproduce

1. Install Xamarin.iOS 11.16 (d15-9)
2. Download, extract, open & build https://github.com/xamarin/xamarin-macios/files/2350303/iOSEFCore212.zip

### Expected Behavior

No build failure (just like in d15-8).

### Actual Behavior

    MTOUCH : error MT2101: Can't resolve the reference 'System.ReadOnlySpan`1<System.Char> System.MemoryExtensions::AsSpan(System.String,System.Int32,System.Int32)', referenced from the method 'System.ReadOnlySpan`1<System.Char> Microsoft.Extensions.Primitives.StringSegment::AsSpan()' in 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [/Users/rolf/Downloads/iOSEFCore21/iOSEFCore21.csproj]

This is a repeat/regression of #4168, just that it only happens in d15-9.

### Build Logs

Failing build log (with Xamarin.iOS 11.16.0.26): https://gist.github.com/rolfbjarne/9b1cecf7968f6958a667204dda49a09f
Working build log (with Xamarin.iOS 11.14.0.14): https://gist.github.com/rolfbjarne/a4e0a0859a627777f8302cda841ada19
Diff between build logs: https://gist.github.com/rolfbjarne/76c1dab569d0994497a8754910a5de63

The significant difference seems to be that we're shipping System.Memory.dll in d15-9, which we end up using, while in d15-8 we use the nuget-provided version:

https://gist.github.com/rolfbjarne/76c1dab569d0994497a8754910a5de63#file-build-diff-L47-L52
https://gist.github.com/rolfbjarne/76c1dab569d0994497a8754910a5de63#file-build-diff-L207

This is supported by the fact that if I remove the System.Memory.dll we ship in d15-9:

    rm /Library/Frameworks/Xamarin.iOS.framework/Versions/11.16.0.26/lib/mono/Xamarin.iOS/Facades/System.Memory.dll

then the project builds fine.

The project also builds fine if I use a version of Xamarin.iOS that has bumped to mono 2018-06 (from PR #4277):

* XI version: mtouch 11.17.0.66 (PR #4277: c7654a04)
* Build log: https://gist.github.com/rolfbjarne/1778a1ed3f6fdc48aa03cc72d02b73d8

which seems to indicate that this is a problem in mono's `2018-04` branch (`d15-8` used mono's `2018-02` branch, while `d15-9` is using mono's `2018-04` branch).

**Comment by rolfbjarne** [comment]
@spouliot @marek-safar This is a regression in `d15-9`.

Could a potential solution be to not ship `System.Memory.dll` in `d15-9`?

**Comment by marek-safar** [comment]
That error is quite strange. We don't ship System.Memory (which is actually an issue on our side) but the current setup should still work. I'll check if I can reproduce it as well

**Comment by spouliot** [comment]
@marek-safar it was removed in 15.8 (mono 2018-02) but, IIRC, you mentioned there was a fix in progress for the next mono, i.e. my understanding is that System.Memory.dll was not removed in mono master (which became the 2018-04 we're presently using for 15.9).
