### ISSUE TITLE
[XM] app crashes in 'Release' mode if the Distribution profile and Entitlements.plist is set

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#4766]
### Steps to Reproduce

1. Create an XM app
2. Switch to the `Release` mode
3. Set right bundle identifier 
4. Sign the app and the installer package with a special provisioning profile
5. Set 'Entitlements.plist' to the `Custom entitlements` field. 
6. Run the application

----
The application is successfully passed the store certification and is uploaded to the iTunesConnect.

### Expected Behavior
The application runs successfully

### Actual Behavior
The application crashes on start

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/dc016e071435159723c78263bc0aefaf
2. xcode-select -p
`/Applications/Xcode-beta.app/Contents/Developer`

Checked next versions of XM too (the same results):
- 4.6.0.14
- 4.8.0.26
- 4.9.0.40
- 4.99.3.716

### Build Logs

1. System Log
https://gist.github.com/mykyta-bondarenko-gl/6eb53b6b616bffcc309086c3e4ec56c4
2. Configuration 
![image](https://user-images.githubusercontent.com/32954580/45162517-da756d00-b1f6-11e8-9952-203ddff450d1.png)

**Comment by rolfbjarne** [comment]
Looks like the signature is invalid:

```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
```

**Comment by mykyta-bondarenko-gl** [comment]
Shouldn't it fail on submission step if it'd be invalid? @rolfbjarne

**Comment by mykyta-bondarenko-gl** [comment]
Also I forgot to add - everything will be ok if I clear the 'Custom entitlements' field

**Comment by rolfbjarne** [comment]
@mykyta-bondarenko-gl apparently not... maybe it runs into a condition Apple doesn't have automated tests for.

**Comment by chamons** [comment]
Thoughts @jstedfast ?

**Comment by jstedfast** [comment]
What entitlements are set?

**Comment by mykyta-bondarenko-gl** [comment]
There are no entitlements @jstedfast

**Comment by jstedfast** [comment]
Might have to use codesign --verify to figure out what it thinks is wrong and then maybe that will give us a clue?

**Comment by mykyta-bondarenko-gl** [comment]
`codesign --verify` says that everything is ok
@jstedfast ^

**Comment by mykyta-bondarenko-gl** [comment]
Do you have any updates? 
@jstedfast @chamons ^

**Comment by jstedfast** [comment]
Oh, the problem is that you are signing it in order to distribute via the App Store?

I think what happens is that your Mac won't run that because it's not signed by Apple. The apps submitted to the App Store are re-signed by Apple before anyone downloads them to run the apps.

I'm not sure it's really expected to be able to run the app when signed with the key you've chosen.

**Comment by jstedfast** [comment]
If you select a Developer signing key, it works, right?

**Comment by mykyta-bondarenko-gl** [comment]
@jstedfast you are right. 
I've installed the latest master build and I can't reproduce it now. Looks like it was fixed. 

Here is my current env:
https://gist.github.com/mykyta-bondarenko-gl/e947f97798681f5456c3eb91bbdaf919

**Comment by chamons** [comment]
If you can reproduce a set of settings that should work but doesn't, please re-open or file a new issues.
