### ISSUE TITLE
Can not build an app from the Windows using this SDK 

### ISSUE THREAD

**Issue by xtmq** [xamarin/xamarin-macios#4771]
### Steps to Reproduce

1. Take a mac machine. 
    - Download and install xcode, Visual Studio for mac.
    - Clone this repository and build iOS SDK according to build instructions.  
2. Take a windows machine. 
    - Build MsBuild and install iOS sdk (from step 1) in it.
    - Try to build a simple iOS Xamarin project:

`
C:\work\App1>msbuild App1.csproj /p:ServerAddress=IP /p:ServerUser=USER /p:Platform=iPhoneSimulator /p:ServerPassword=PASSWORD
`

### Expected Behavior

MsBuild builds a project using a remote mac machine or report an error about connection to the mac machine. 

### Actual Behavior

Errors:
`
C:\Work\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(626,3): error : Could not find a valid Xcode app bundle at '/Applications/Xcode.app'. Please update your Apple SDK location in Visual Studio's preferences (Project > SDK Locations > Apple > Apple SDK). 
`

`
C:\Work\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(626,3): error : Could not find 'Xamarin.iOS'
`

### Investigation
There is no `Xamarin.Messaging.targets` and related stuff in the assembled iOS SDK. Probably I have built it in a wrong way?

**Comment by rolfbjarne** [comment]
We recommend developing on the Mac if you're building the SDK from source, since there are a few more hoops/hacks you'll have to go through if you want to use your own SDK from Windows.

In any case, I'll try to help you.

The first step would be make sure everything is working on the Mac: can you try creating a new project in Visual Studio for Mac and see if that works?

**Comment by xtmq** [comment]
Thanks! It seems it works. It least `make install-system` works without any errors and I am able to run a simple iOS app from VS for Mac. In the build output I see the next line:
`
FrameworkPathOverride          = /Users/evgeniystepanov/work/xamarin-macios/_ios-build/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS
`

So VS for Mac uses my iOS SDK as far as I can see.

**Comment by rolfbjarne** [comment]
OK, that's good.

Where's your Xcode.app on the mac? Do you have it in /Applications/Xcode94.app as the build instructions here tell you to? In that case you need to `Please update your Apple SDK location in Visual Studio's preferences (Project > SDK Locations > Apple > Apple SDK).`

Another alternative is to make /Application/Xcode.app a symlink to /Applications/Xcode94.app.

On Windows, you need to install the workload to get Xamarin.iOS in Visual Studio (I don't regularly use VS on Windows, so I don't remember the exact process). In fact a different process might have been easier: first install everything you need using the normal install process (and make sure everything works), then you just run `make system-install` in your xamarin-macios directory, and that custom build should then be used. Unfortunately the bits to get Xamarin.iOS working on Windows (i.e. the "bridge" to the mac) are not open sourced, so on Windows you need to get the bits using existing packages (and try to get the a version as close as possible to the xamarin-macios branch you're building).

**Comment by xtmq** [comment]
So if I have no Visual Studio on my Windows machine I can not use iOS SDK?

**Comment by xtmq** [comment]
Ok thanks, you can close the issue =)
