### ISSUE TITLE
Disable the GC pump by default

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#4772]
Disable the GC pump by default, since it may interfere with debugging (objects are collected when inspecting them).

Reference: https://developercommunity.visualstudio.com/content/problem/210870/objects-in-list-are-being-garbage-collected-during.html?childToView=329416#comment-329416

**Comment by spouliot** [comment]
https://github.com/xamarin/xamarin-macios/pull/4781
