### ISSUE TITLE
[iOS 12] Permissions error when attempting to access HKClinicalType data

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/xamarin-macios#4788]
I am attempting to utilize some of the new HealthKit features in a Xamarin.Forms app running on iOS. There was a prior issue (#4657) which has been resolved, and I am able to get the `HKClinicalType`, but when requesting access to the data via `RequestAuthorizationToShare` it throws an error:

>Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: Authorization to read the following types is disallowed: HKClinicalTypeIdentifierAllergyRecord
Native stack trace:
	0   CoreFoundation                      0x0000000117bf729b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000118933735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000117bf70f5 +[NSException raise:format:] + 197
	3   HealthKit                           0x000000010fa57ec0 -[HKHealthStore _throwIfAuthorizationDisallowedForSharing:types:] + 540
	4   HealthKit                           0x000000010fa56912 -[HKHealthStore _validateAuthorizationRequestWithShareTypes:readTypes:] + 224
	5   HealthKit                           0x000000010fa56a82 -[HKHealthStore requestAuthorizationToShareTypes:readTypes:shouldPrompt:completion:] + 321
	6   HealthKit                           0x000000010fa5680f -[HKHealthStore requestAuthorizationToShareTypes:readTypes:completion:] + 77
	7   HealthRecordsSample.iOS             0x000000010a6f76e9 xamarin_dyn_objc_msgSend + 217
	8   ???                                 0x000000013d25413e 0x0 + 5320819006

The clinical types are read only, so they should be passed in as the second argument when requesting authorization, like so:

`healthKitStore.RequestAuthorizationToShare(new NSSet(), new NSSet(new[] { allergyType }), ReactToHealthCarePermissions);`

Using older sample code and requesting types such as heart rate works (specifically using code from [these docs](https://docs.microsoft.com/en-us/xamarin/ios/platform/healthkit#permissions-walkthrough), so the entitlements and Info.plist values should presumably be correct (there is always a chance that this is not the case, however). The simulator and device (configured in provisioning to work with my iPhone X) both fail. 

[Apple's docs](https://developer.apple.com/documentation/healthkit/health_and_fitness_samples/accessing_health_records) for reference.

I will attach two samples; one is the C# app in Xamarin.Forms (using a `DependencyService` to access the iOS feature), the other a Swift-based app.

### Steps to Reproduce

1. Run each app, respectively
2. Click the button to request permissions

### Expected Behavior

Both should request permissions for clinical data

### Actual Behavior

The Xamarin.Forms app fails, and the Swift app does not

### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.1 (build 7)
Installation UUID: 36f8475d-6533-435d-b0bf-f4b14538d280
Runtime:
	Mono 5.12.0.305 (2018-02/e0e035e3b14) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000305

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.0.1
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.2
	1.0.0-preview2-003131
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.1.0.18 (Visual Studio Enterprise)
Android SDK: /Users/paul/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.0
SDK Build Tools Version: 26.0.1

Java SDK: /usr
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.0 (14320.12.2)
Build 10L232m

=== Xamarin.Mac ===

Version: 4.99.3.658 (Visual Studio Enterprise)
Hash: 1eefd4e3
Branch: 
Build date: 2018-08-21 15:01:53-0400

=== Xamarin.iOS ===

Version: 11.99.3.538 (Visual Studio Enterprise)
Hash: 1eefd4e3
Branch: HEAD
Build date: 2018-08-21 15:01:52-0400

=== Build Information ===

Release ID: 706010007
Git revision: 7c9e755fe667840f2eed42b2e7910ec18ef51b82
Build date: 2018-08-24 02:25:33+00
Build branch: release-7.6-xcode10
Xamarin extensions: 1196f085605a84ce99f390a1aaee0bf257d31a50

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.31
NuGet Package Management Extensions 0.13
Internet of Things (IoT) development (Preview) 7.5
```

### Build Logs

None at this time.

### Example Project (If Possible)

[HealthRecordsSampleForms.zip](https://github.com/xamarin/xamarin-macios/files/2372516/HealthRecordsSampleForms.zip)

[HealthRecordsTest.zip](https://github.com/xamarin/xamarin-macios/files/2372420/HealthRecordsTest.zip)

**Comment by spouliot** [comment]
It works if you copy the swift entitlements (2 items) over yours (one item)

**Comment by Uttam115** [comment]
@pauldipietro I am facing the same issue. Same Clinical record is accessible in Xcode project but in Xamarin forms, I am getting same exception as yours. Can you please tell how did you solve this ?

**Comment by laibulle** [comment]
+1

**Comment by qaliwebguru** [comment]
same issue facing. Not sure if there is any fix available?
