### ISSUE TITLE
Native Reference unable to be consumed from Nuget

### ISSUE THREAD

**Issue by borrrden** [xamarin/xamarin-macios#4823]
### Steps to Reproduce

1. Create a new Xamarin.iOS project
2. Add Couchbase.Lite from Nuget (or Couchbase.Lite.Enterprise)
3. Make a device build (i.e. msbuild project.sln /p:Platform=iPhone)

### Expected Behavior

The build should succeed

### Actual Behavior

clang fails being unable to find a framework that is included in the Nuget package

>   ld: framework not found LiteCore
clang : error : linker command failed with exit code 1 (use -v to see invocation)

Note that [this file](https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Support.Apple/iOS/ios.targets) is included in the Nuget package as `build/xamarinios/Couchbase.Lite.Support.iOS.targets` and oddly, even if I remove the build folder from the nuget package all together is still says the same thing.  So where is it determining the need for LiteCore if not from the native reference?

### Environment

```
Visual Studio Community 2017 for Mac
Version 7.6.5 (build 20)
Installation UUID: 9c860ff0-60f7-49fa-9bc5-91a16d0b99b1
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.4
	1.0.7
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found

Apple Developer Tools
Xcode 9.4.1 (14161)
Build 9F2000

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 11.14.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: HEAD
Build date: 2018-08-28 00:12:06-0400

Xamarin.Android
Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/borrrden/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 706050020
Git revision: f6a29a810eb4b81ceb9a4ea4ba411da98b6e25cf
Build date: 2018-09-11 21:34:07+00
Build branch: release-7.6
Xamarin extensions: 097e18c3e104c652bde3a02799dcba13eaad6f7b

Operating System
Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
Internet of Things (IoT) development (Preview) 7.5
```

### Build Logs

https://gist.github.com/borrrden/5a58e51af5bec86689cbae4bf4d000f4

**Comment by borrrden** [comment]
Note: The build logs use the new csproj packagereference style, and another project I made to confirm the repro steps uses packages.config, so both are affected.  I should have attached this above but here is the example project I made:

[wtf.zip](https://github.com/xamarin/xamarin-macios/files/2385322/wtf.zip)

**Comment by borrrden** [comment]
Four different versions of Xamarin iOS all showed this problem...I would like to say it's something I am doing but nothing obvious sticks out to me.

**Comment by borrrden** [comment]
Things I have tried:

- Adding folder with LiteCore.framework in it to my path (no go)
- Putting the LiteCore.framework into the obj/Debug/arm64 folder while the build was happening (no go)
- Putting LiteCore.framework into the SDK path (inside Xcode application directory) alongside things like Foundation.framework (worked, but impractical)

**Comment by borrrden** [comment]
Changing the linker behavior to "Link All" also seems to let the compile succeed.  Is this a requirement?

**Comment by borrrden** [comment]
Another nugget:  The mere presence of `@rpath/LiteCore.framework/LiteCore` in a `DllImport` statement seems to trigger this search for a global "LiteCore" framework that causes the error.  When a static library is added, a search path entry and library name get added, but this trigger only adds a framework name it seems...

**Comment by borrrden** [comment]
Thanks for the workaround!  I would have never thought to do that.

**Comment by Grzesik** [comment]
Hi,

I've now the same problem in VS 2019 16.10.2 / XCode 12.5 and the newest nuget packages / Xamarin.Forms. 

The app try to deploy the app to the iPhone and breaks with the message:

PackageInspectionFailed: Failed to load Info.plist from bundle at path /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.8ED3x8/extracted/ROP_App.iOS.app/Frameworks/LiteCore.framework; Extra info about "/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.8ED3x8/extracted/ROP_App.iOS.app/Frameworks/LiteCore.framework/Info.plist": Couldn't stat /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.8ED3x8/extracted/ROP_App.iOS.app/Frameworks/LiteCore.framework/Info.plist: No such file or directory

Do you have any workaround?

Thanks

**Comment by rolfbjarne** [comment]
@Grzesik that looks like #11786 / #11728. There's a few workarounds here: https://github.com/xamarin/xamarin-macios/issues/11786#issuecomment-853966158

**Comment by Grzesik** [comment]
@rolfbjarne thanks for your answer. I really had all the problems after I updated my system, like the problem with the icons and SkaiSharp in iOS. But this one is new. I've also wrote in Couchbase forum about the problem and wait for an answer. It seems to have something to do with Couchbase.Lite.

**Comment by rolfbjarne** [comment]
This is not an issue in .NET (because incremental builds don't exist in the same way anymore in .NET).
