### ISSUE TITLE
iOS 12 Credential Provider Extension doesn't invoke PrepareCredentialList() in ASCredentialProviderViewController

### ISSUE THREAD

**Issue by kspearrin** [xamarin/xamarin-macios#4854]
### Steps to Reproduce

1. Create a credential provider app extension.
2. Override `ASCredentialProviderViewController` for the extension.
3. Set proper entitlements for your app to use `com.apple.developer.authentication-services.autofill-credential-provider`
4. Enable your app for autofill under Settings in iOS.
5. Launch app extension from QuickType bar when on a login form.

### Expected Behavior

`void PrepareCredentialList(ASCredentialServiceIdentifier[] serviceIdentifiers)` is called in your overloaded `ASCredentialProviderViewController` class.

### Actual Behavior

Only `ViewDidLoad()` is called.

### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.6 (build 17)
Installation UUID: 8b377b50-d1a6-4663-aa90-32789adbaee7
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/kyle/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Enterprise)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Enterprise)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706060017
Git revision: 822323b5f6295b271d4c9bfaca4129f90ec41f38
Build date: 2018-09-18 20:19:40+00
Build branch: release-7.6-xcode10
Xamarin extensions: a83eb4b7ad9174ac2e705f2c4257ecd15688ba97

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64


```

### Build Logs

https://gist.github.com/kspearrin/b7013078b61d6e7dcba27685a49a9e95

### Example Project (If Possible)

The following OSS project will reproduce the issue:

https://github.com/bitwarden/mobile

Relative parts:
https://github.com/bitwarden/mobile/tree/master/src/iOS.Autofill
https://github.com/bitwarden/mobile/blob/master/src/iOS.Autofill/CredentialProviderViewController.cs

Running the autofill extension in debug mode against Safari you can see the debug log message for ViewDidLoad (and hit breakpoints), but nothing is called for `PrepareCredentialList` as expected.

**Comment by rolfbjarne** [comment]
I can reproduce the problem.

However, the `PrepareCredentialList` method is called if I create a new AutoFill extension in Xcode, and copy the `MainInterface.storyboard` from that extension ([example](https://gist.github.com/rolfbjarne/902da87298a7b588537300e0623a6d62)), so there's something specific in the storyboard that needs to change.

I believe this should get you further.

We should also investigate and see what's different in Xcode's storyboard.

**Comment by kspearrin** [comment]
I figured out the issue. Your initial view controller cannot be a NavigationViewController for whatever reason. I got rid of that and it works.

**Comment by kspearrin** [comment]
Feel free to close this since I don't think it is Xamarin related.

**Comment by rolfbjarne** [comment]
Great, thanks for letting us know why it didn't work!
