### ISSUE TITLE
 UI Thread Freeze on WebClient DownloadDataAsync

### ISSUE THREAD

**Issue by manuelpa-ms** [xamarin/xamarin-macios#4858]
### Steps to Reproduce

1. Environment: iOS device is connected to an Access Point with limited connectivity (no internet access, no DNS resolution).
2. In a Xamarin.iOS application, run the following code (first button on shared sample):
private void RunTest()
{
var wc1 = new WebClient();
wc1.DownloadDataAsync(new Uri("http://www.test.aero"));
var wc2 = new WebClient();
wc2.DownloadDataAsync(new Uri("http://www.test.aero"));
// Execution will never reach here. The above call will simply lock up.
}

Possible changes listed here: https://developer.xamarin.com/releases/ios/api_changes/ios-11-12-0-11-14-0/#Namespace_System.Net

### Expected Behavior
The UI thread should not freeze; the DownloadDataAsync functions should return. This is the behavior on Xamarin.iOS 11.12

### Actual Behavior
UI thread freezes even if running this code from a background thread. The stacktrace while frozen is as follows:

System.Net.ServicePoint.SendRequest(System.Net.WebOperation operation, string groupName) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/ServicePoint.cs:267
System.Net.HttpWebRequest.SendRequest(bool redirecting, System.Net.BufferOffsetSize writeBuffer, System.Threading.CancellationToken cancellationToken) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs:851
System.Net.HttpWebRequest.MyGetResponseAsync() in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs:995
System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.HttpWebResponse>.Start<System.Net.HttpWebRequest.<MyGetResponseAsync>d__243>(System.Net.HttpWebRequest stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
System.Net.HttpWebRequest.MyGetResponseAsync(System.Threading.CancellationToken cancellationToken) in 
System.Net.HttpWebRequest.RunWithTimeout<System.Net.HttpWebResponse>(System.Func<System.Threading.CancellationToken,System.Threading.Tasks.Task<System.Net.HttpWebResponse>> func, int timeout, System.Action abort) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs
System.Net.HttpWebRequest.RunWithTimeout<System.Net.HttpWebResponse>(System.Func<System.Threading.CancellationToken,System.Threading.Tasks.Task<System.Net.HttpWebResponse>> func) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs
System.Net.HttpWebRequest.BeginGetResponse(System.AsyncCallback callback, object state) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/System/System.Net/HttpWebRequest.cs:1169
System.Net.WebClient.GetWebResponseTaskAsync() in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/external/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:268
System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.WebResponse>.Start<System.Net.WebClient.<GetWebResponseTaskAsync>d__112>(System.Net.WebClient stateMachine) in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
System.Net.WebClient.GetWebResponseTaskAsync(System.Net.WebRequest request) in 
System.Net.WebClient.DownloadBitsAsync() in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/external/corefx/src/System.Net.WebClient/src/System/Net/WebClient.cs:865

### Environment

Xamarin.iOS and Xamarin.Mac SDK   11.14.0.14
Working correctly on Xamarin.iOS 11.12.x

```
```

### Example Project (If Possible)

[WebClientFreezesUIFromBackgroundThread_ext.zip](https://github.com/xamarin/xamarin-macios/files/2401841/WebClientFreezesUIFromBackgroundThread_ext.zip)

**Comment by rolfbjarne** [comment]
I can reproduce this in the simulator if I set Apple's Network Link Conditioner to "100% Loss".

Full stack traces, both kill -QUIT and lldb: https://gist.github.com/rolfbjarne/4698d9d6e8697d8f963ea7c66c300555

**Comment by rolfbjarne** [comment]
This issue was moved to mono/mono#10719
