### ISSUE TITLE
[Tests] If Constants.Version is not correctly generated, builds do not fail

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#4859]
If during a merge, there is an issue and the Constants.Version is not correctly generated, we do have no automated way to notice it. This has happened already at least once resulting in the PR  https://github.com/xamarin/xamarin-macios/pull/4856 after @spouliot show it manually, the monitoring team missed it because the build was successful.

**Comment by spouliot** [comment]
@mandel-macaque double check (it might exists) but a `Version.[Try]Parse]` tests that ensure it works and that `Revision` is not `-1` (iirc it's the default) should to the trick.

**Comment by mandel-macaque** [comment]
@spouliot if it exists, is not ran in the bots, which is also an issue :/ 

I should have seen a failure in the commits.

**Comment by spouliot** [comment]
@mandel-macaque I meant that a `Version.Parse` test on that string might already exists and "12.3." could be a valid string :) In that case we simply need to check there's a valid (not default) `Revision`

**Comment by spouliot** [comment]
So `Version.TryParse ("12.3.", out var version)` returns `false` and would have caught the situation. I'll add this to our unit tests (both XI and XM).
