### ISSUE TITLE
[XM]Various options of NSVisualEffectView gives a System.Exception while executing VisualEffectPlayground on Mojave

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4863]
### Steps to Reproduce
1.  Install Xamarin.Mac, Version: 4.99.3.741 (Visual Studio Community), Hash: eeca0b87 on Mojave
2. Execute VisualEffectPlayground 
3. Click on  BasicSideBar+Images or Text

### Expected Behavior
Correct view should display

### Actual Behavior
Getting an exception .
Exception Log: https://gist.github.com/GouriKumari/7fd46c3d48b5bb37036dd59054ea421d

### Environment

Test Env:https://gist.github.com/GouriKumari/abed951b2b807632973a0c2ae6ad7767
Both with Xcode10 and Xcode10.1
This issue occurs with XM build with Xcode10 support and XM stable + Mojave. 
This issue didn't occur with XM stable build or XM with Xcode10 support on HighSierra

### Build Logs

Build Log: https://gist.github.com/GouriKumari/8d39c2c71df974e552007536ff613094
Application Output: https://gist.github.com/GouriKumari/51632b6244273d8b3871aac21b4c46e9

**Comment by chamons** [comment]
```  at Foundation.NSObject.InitializeHandle (System.IntPtr handle, System.String initSelector) [0x00095] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.99.3.741/src/Xamarin.Mac/Foundation/NSObject2.cs:498
  at AppKit.NSImage..ctor (System.String fileName) [0x00032] in /Library/Frameworks/Xamarin.Mac.framework/Versions/4.99.3.741/src/Xamarin.Mac/AppKit/NSImage.g.cs:360
at VisualEffectPlayground.DemoFaceTimeWindowController.WindowDidLoad () [0x0005d] in /Users/xamarinqa/GitRepo/mac-samples/yosemite/VisualEffectPlayground/VisualEffectPlayground/DemoFaceTimeWindowController/DemoFaceTimeWindowController.cs:21```

The sample is using hard coded pahts into desktop images that don't exist on 10.14. If you fix them to point to different images, you may see different issues.

**Comment by GouriKumari** [comment]
This sample needs to be updated to make it work both in High Sierra and Mojave.

**Comment by VincentDondain** [comment]
https://github.com/xamarin/xamarin-macios/issues/4863#issuecomment-423610961 yea so this doesn't sound like a XM issue. Incorrect hardcoded path. Please reopen or file a new issue if you have an other problem with this sample.

Thanks.

**Comment by VincentDondain** [comment]
This issue was moved to xamarin/mac-samples#103
