### ISSUE TITLE
[XM]SceneKitViewer failed to build with native linking failure with xcode10

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4866]
### Steps to Reproduce

1. Update System to XM stable build and install Xcode10 on machine
2. Build SceneKitViewer with Release config

### Expected Behavior
App builds successfully

### Actual Behavior
App fails to build with a native linking failure. There is a fatal error that cmath file cannot be found in Xcode10. This was working with Xcode9.x.

### Environment
https://gist.github.com/GouriKumari/a249cfc11f13655e671b1d34b55f63be

### Build Logs

Build Log: https://gist.github.com/GouriKumari/dea060286ef50af9dc9615f3e266fe60

### Example Project (If Possible)

mac-samples/ScenekitViewer

**Comment by rolfbjarne** [comment]
This is because the current stable version of Xamarin.Mac doesn't support Xcode 10.

It is fixed in our xcode10 branch.
