### ISSUE TITLE
[XM]FinderSyncExtension sample failed to build with error "Utilities.dll' could not be found" with xcode10

### ISSUE THREAD

**Issue by p-lad** [xamarin/xamarin-macios#4872]
Pre-Condition:-
Download sample from:- https://github.com/xamarin/mac-samples/tree/master/ExtensionSamples

Steps to Reproduce
1. Update System to XM stable build and install Xcode10 on machine
2. Build Finder SyncExtension with Release config

Expected Behavior
App builds and run in debug and release successfully

Actual Behavior
FinderSyncExtension sample failed to build with error "Utilities.dll' could not be found" with xcode10

Environment
https://gist.github.com/p-lad/e9e7ecd0cf27caf6e292d0e2693c8adb

Build Logs
https://gist.github.com/p-lad/cbea1a32e3d34626aaa5d39c4d7887d5

Example Project (If Possible)
mac-samples/ExtensionSamples/FinderSyncExtension

Test plan link :- https://testrail.xamarin.com/index.php?/runs/view/56673&group_by=tests:assignedto_id&group_order=asc&group_id=-1

Test Case link :- https://testrail.xamarin.com/index.php?/tests/view/25755963&group_by=tests:assignedto_id&group_order=asc&group_id=-1

**Comment by p-lad** [comment]
Hello,
The above issue is also observed for ShareExtension and TodayExtension  samples.
The above samples can taken from :- https://github.com/xamarin/mac-samples/tree/master/ExtensionSamples

TodayExtension Sample build logs :- https://gist.github.com/p-lad/0b5ac14ada6003e63c3d0bec3504a864

ShareExtension Build Logs :- 
https://gist.github.com/p-lad/d3d557e40cc1240b2337ec824629ccfa

Thanks.

**Comment by spouliot** [comment]
Somehow its looking for an assembly built with `Debug`

```
CSC : error CS0006: Metadata file '/Users/globallogic/Downloads/mac-samples-master 2/ExtensionSamples/Utilities/bin/Debug/Utilities.dll' could not be found
```

Can you confirm the same work with the current stable XM ?

**Comment by GouriKumari** [comment]
Pratik tested it with XM stable + Xcode10 and Mojave. 

>>Can you confirm the same work with the current stable XM ?
 I  can't reproduce it both on a High Sierra and Mojave machine with XM stable and xcode10. It worked on both cases. 

Test Env: https://gist.github.com/GouriKumari/7fcc98e0d9e2d37f4b6c958b1c3b610b
Build Log: https://gist.github.com/GouriKumari/4a105b61af32360d0a9438accf3cbe1c (HighSierra)\
Build Log: https://gist.github.com/GouriKumari/612e3d06a77da59ce39f9b3c99800dcd

**Comment by GLjackyvaswani** [comment]
Have retested it with latest build shared, issue is not reproducible.

Screencast: https://www.screencast.com/t/8zIQDKNBkY

Tested On:

Version 7.6.8 (build 38)
Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
Xamarin.Mac Version: 5.0.0.0
Xamarin.iOS Version: 12.0.0.15
Xamarin.Android Version: 9.0.0.20


Build Info: https://gist.github.com/mohakbarokar/6f7cb0a0834ecc8ad21bc054aaa2f3ea
