### ISSUE TITLE
Remove API diff XML references from repository

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#4891]
Our API diff is based on XML definitions. They are huge (about 327MB today) and while bots needs them (all the time) many people can live happy lives without them.

Removing them from the repo would have some advantages, e.g.
- faster clone of the repository;
- less conflicts when merging branches;
- less branches to update when a new stable is released;

The downside is that we need to store them elsewhere and download (cache) them on-demand (being text they should compress well - *update* a simple, default zip is 14.2MB). 

We are already doing similar caching for other things so it's nothing really new.

Notes:
* `xi` and `xm` directories should be split (to download) since they can diverge

**Comment by rolfbjarne** [comment]
What if we don't store the reference XML at all? We could download the .pkg for the (stable) release we want to compare against, extract the dlls, and create the reference XML on the fly.

Con: it's slower than storing the reference XML, although some of it can probably be parallelized with the build itself.

**Comment by spouliot** [comment]
To expand on the *con* it's not only slower, we need to download for *both* XI and XM stable packages and it's not small either :(

My _guess_ is that 

* the download (packages or XML) can be done without much impact on the build time (in parallel, largely network IO). This can _probably_ be ignored but larger download means higher failure rate and are harder to cache;

* decompression will take longer for the packages (than for XML). That be easily be measured;

* disk space might be an issue, on some bots, for packages. That's a bit hard to predict (but time consuming to fix/rebuild) so we better err on the safer side;

* processing, to created the XML from assemblies, takes takes about 1 minute (on my laptop). Not a huge difference (but if we want, again, PR results in 60m then it's still noticeable and avoidable);

Now we can create a script that does that, whatever the storage (or lack of) we still need to create the XML files, and do the timing before deciding what to download :)

**Comment by spouliot** [comment]
A middle ground between a new (out of repo) location and packages (big) would be to use [bundle.zip](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/master/3517433f7f9d3e80b3e705eb96249d369d96b13a/442/package/bundle.zip) as it
* contains all assemblies, both XI and XM (single vs dual downloads)
* it's smaller (about 120 MB) than the packages (XI 614 MB, XM 136 MB)
* the download time is likely _similar_ (or closer) to checking out 320+ MB (XML)
