### ISSUE TITLE
[XI]monotouch-test failure on new iOS devices

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#4900]
### Steps to Reproduce

1. Update System to Xamarin.iOS stable build, Version: 12.0.0.15 (Visual Studio Enterprise)
Hash: 84552a46
2. Execute monotouch-test on a new iPhoneXSMax device

### Expected Behavior
All tests pass
### Actual Behavior
[FAIL] NLTaggerTest.GetTag : System.NullReferenceException : Object reference not set to an instance of an object
[FAIL] VTDecompressionSessionTests.DecompressionSessionSetDecompressionPropertiesTest :   SetDecompressionProperties
### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.7 (build 49)
Installation UUID: 74c37335-5878-4fa7-8f71-09bc48b661c5
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.24)
Build 10A254a

=== Xamarin.Mac ===

Version: 4.6.0.14 (Visual Studio Enterprise)
Hash: 1a6e2786
Branch: 
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Enterprise)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/gourikumari/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 25.2.3
SDK Platform Tools Version: 25.0.1
SDK Build Tools Version: 25.0.1

Java SDK: /usr
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706070049
Git revision: 0b48ccfb376397678b3bc3653da2c6603d35357d
Build date: 2018-09-20 21:14:23+00
Build branch: release-7.6
Xamarin extensions: b25fd1e2b9a7859aff9536924e8edb6cbfb78637

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:59:21 PDT 2018
    root:xnu-4903.201.2~4/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Gist Ide Information 1.1.0
```
### Build Logs

Build Log: https://gist.github.com/GouriKumari/0817fc876ae8b282550ad0a2c4ab4318
Test Log: https://gist.github.com/GouriKumari/6ad56210aa607f9a794d505a7d013a67

### Example Project (If Possible)

xamarin-macios/tests/monotouch-test

## Additional Info:
These tests didn't fail on old iOS devices with iOS 12 versions.

**Comment by VincentDondain** [comment]
Need to borrow and iPhone X[s] to confirm that (:

**Comment by VincentDondain** [comment]
I was able to confirm that issue only on iPhone X[s].

**Comment by VincentDondain** [comment]
Looks like this puppy in particular -> https://github.com/xamarin/xamarin-macios/blob/master/tests/monotouch-test/VideoToolbox/VTDecompressionSessionTests.cs#L62 <- doesn't work on iPhone X[s] anymore...

**Comment by VincentDondain** [comment]
Filed a radar for `[FAIL] NLTaggerTest.GetTag` https://trello.com/c/3oN5kuYk

**Comment by VincentDondain** [comment]
Also filed a radar for `VTSessionSetProperty kVTDecompressionPropertyKey_RealTime` https://trello.com/c/R1EGBDkA

**Comment by GouriKumari** [comment]
[FAIL] NLTaggerTest.GetTag issue is also observed on an iPhone7 device with iOS12.0. 

### Logs:
Failure: 
[FAIL] NLTaggerTest.GetTag : System.NullReferenceException : Object reference not set to an instance of an object
		  at MonoTouchFixtures.NaturalLanguage.NLTaggerTest.GetTag () <0x1044831c0 + 0x0014c> in <26d47237c4e84c9ab0574455791f7974#6d35562cf99273050aa5bdf467136ea7>:0 
		  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
		  at System.Reflection.MonoMethod.Invoke (System.Object , System.Reflection.BindingFlags , System.Reflection.Binder , System.Object[] , System.Globalization.CultureInfo ) <0x104712580 + 0x000a7> in <f273051fbe6e45148d98eaa15f039f66#6d35562cf99273050aa5bdf467136ea7>:0 

Test Log: https://gist.github.com/GouriKumari/a3c22ff238854b4fccc5c21cd0c5de7d
Test Env: XI 12.3.1.9, dev16-p1 candidate)

**Comment by spouliot** [comment]
PR #5057 fix (the test) wrt the `NullReferenceException` in `NLTaggerTest.GetTag`

**Comment by spouliot** [comment]
@GouriKumari can you check if `VTSessionSetProperty kVTDecompressionPropertyKey_RealTime` still fails on the latest phones and iOS 12.1 ? thanks!

**Comment by GouriKumari** [comment]
I verified this with an iPhone6Plus 12.1 device and tests passed successfully. 

Test Log: https://gist.github.com/GouriKumari/4df40a19dfe073a96f7eee08b4428ba4

But with iPhoneXSMax device, I couldn't build the test due to https://github.com/xamarin/xamarin-macios/issues/5065

**Comment by GouriKumari** [comment]
I checked the issue on iPhoneXsMax 12.0.1 and VTSessionSetProperty kVTDecompressionPropertyKey_RealTime still fails on it.

##
Build Log: https://gist.github.com/GouriKumari/8fc2c52f628bcf463c6268b712d2418b
Test Log: https://gist.github.com/GouriKumari/0ee14607472d626a06bf8f4c8574f2d5

**Comment by spouliot** [comment]
We have not heard back from Apple rdar - but this is already tracked in https://github.com/xamarin/xamarin-macios/issues/5086 so this issue can be closed.
