### ISSUE TITLE
Xib templates seem to need `customObjectInstantitationMethod="direct"` added

### ISSUE THREAD

**Issue by iainx** [xamarin/xamarin-macios#4902]
Xib files created from Xcode (from at least 9.4.1) have an additional `customObjectInstantitationMethod="direct"` property on their `document` property. 

Not sure why this is needed, there doesn't seem to be much documentation on it, but not having it breaks using `NSWindow.GetWindowWithContentViewController`. The window is created, and the content is there, but doesn't resize and doesn't always render correctly

### Steps to Reproduce

1. Clone https://github.com/iainx/testsplitpane
   This application opens two windows using view controllers defined in xib files. The Xib files are identical, except one has `customObjectInstantitationMethod="direct"` and the other doesn't.
2. Build and run. 
3. The broken window is missing the split pane's slider, and the content does not resize when you resize the window. The working window has neither of these issues.

### Environment

```
=== Visual Studio Community 2017 for Mac (Preview) ===

Version 7.8 Preview (7.8 build 485)
Installation UUID: a9ace71a-8828-4c14-aafb-07330e5fd481
Runtime:
	Mono 5.14.0.177 (2018-04/f3a2216b65a) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 514000177

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.7
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.200
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.14.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)
Hash: 64fece5f
Branch: master
Build date: 2018-05-29 20:00:45-0400

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/iain/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.1    (API level 16)
		4.2    (API level 17)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.1.652.0
Hash: d9c8ea86

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 708000485
Git revision: 395086ec96857817571c0615b8d7b94abb318d73
Build date: 2018-09-12 17:24:06+00
Build branch: master
Xamarin extensions: 876804254701660cf6ab3573aa56283d9f26b891

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

```

### Example Project (If Possible)

https://github.com/iainx/testsplitpane

> VS bug [#695017](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/695017), VS bug [#699713](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/699713)

**Comment by VincentDondain** [comment]
@iainx if we're talking about the file templates lacking properties this is a VSMac issue. I added the right label.

**Comment by iainx** [comment]
@VincentDondain That's what I thought, but @chamons told me to file it here

**Comment by chamons** [comment]
@VincentDondain @jstedfast may need to look it, I wasn't sure if it was a template or syncing issue. Fair point though, we could have done a VSTS

**Comment by iainx** [comment]
I'll file it there.

**Comment by VincentDondain** [comment]
@iainx by adding the external label it automatically created a VSTS issue 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/695017. Since you closed this issue it marked the VSTS issue as resolved. Probably better to re-open it in VSTS or file a new VSTS issue.

**Comment by sgmunn** [comment]
@chamons is this really a templating issue? what would happen to existing projects that do not have this property? This sample seems to me to represent what could happen for a user with an existing project. Adding the property in new projects only really solves 1/2 the issue right?

**Comment by sgmunn** [comment]
@chamons understood, but this doesn't really answer the question I had with respect to existing projects. We can add the value to the template easily enough, I'm just curious about whether there is an impact on existing projects that we are missing.

**Comment by chamons** [comment]
I honestly don't know, I don't understand the internals of AppKit \ storyboards well enough to generalize.

There is _frightful_ little documentation on any of this.

**Comment by jstedfast** [comment]
How does Xcode deal with older projects (i.e. projects created with an older version of Xcode?)

**Comment by chamons** [comment]
That is a great question that I have no idea how to begin to research :(

**Comment by iainx** [comment]
I can check it later. I'll put a xib file without the property in a objc project, and see what Xcode does to it.
