### ISSUE TITLE
[RFC] Expose the cpu architecture to managed code

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#4907]
Up until now we've been able to handle cpu-specific managed code (stret/variadic functions) by look at Runtime.Arch and IntPtr.Size.

Unfortunately this comes to an end with arm64_32, because there will be no way to distinguish it from armv7k (Runtime.Arch will be DEVICE and IntPtr.Size=4 for both) - and the ABI for variadic functions is different in these two architectures (see https://github.com/xamarin/xamarin-macios/issues/4864#issuecomment-426493904).

Proposal: add a Runtime.CpuArchitecture property:

```csharp
class Runtime {
    public enum CpuArchitecture {
        I386 = 1,
        X86_64 = 2,
        Armv7 = 3,
        Armv7s = 4,
        Armv7k = 5,
        Arm64 = 6,
        Arm64_32 = 7,
        Arm64e = 8,
    }

    [DllImport ("__Internal")]
    static extern int xamarin_get_cpu_architecture ();

    public CpuArchitecture CpuArchitecture {
        get { return xamarin_get_cpu_architecture (); }
    }
}
```

```c
// runtime/product.h
enum CpuArchitecture {
    CpuArchitecture_I386 = 1, 
    // ...
}
#if defined (__i386__)
    #define CPU_ARCHITECTURE CpuArchitectures_I386
#elif ...
#else
    #error Unknown architecture
#endif

// runtime/runtime.m
int32_t
xamarin_get_cpu_architecture ()
{
    return CPU_ARCHITECTURE;
}
```

We should also update our optimizer to inline this function call whenever possible.

**Comment by spouliot** [comment]
Q: is there already a native enum we can (re)use ? it might prove useful if some other API (using it) are bound later

**Comment by rolfbjarne** [comment]
AFAIK there's no native enum.

We could base the enum values on the standard cputype/cpusubtype: https://github.com/xamarin/xamarin-macios/blob/183cb81583857b9bd1464987e6b403f169f645d6/tools/common/MachO.cs#L385-L409

and put them in a 64-bit value:

```csharp
public enum CpuArchitecture : ulong {
        I386 = 7 << 32,
        X86_64 = 7 << 32 | 0x01000000,
        Armv7 = 12 << 32 | 9,
        Armv7s = 12 << 32 | 11,
        Armv7k = 12 << 32 | 12,
        Arm64 = 12 << 32 | 0x01000000,
        Arm64_32 = ?,
        Arm64e = ?,    
}
```

at runtime we could P/Invoke into [NXGetLocalArchInfo](https://opensource.apple.com/source/cctools/cctools-495.2/include/mach-o/arch.h.auto.html) to get cpu(sub)type.

**Comment by rolfbjarne** [comment]
The problem that made me come up with this suggestion was solved differently, by adding a `Runtime.IsARM64CallingConvention` property: https://github.com/xamarin/xamarin-macios/blob/cd9a151c984d814fb4f5ac83291620fc206d4ec7/src/ObjCRuntime/Runtime.cs#L1759

Which means that this RFC is not needed anymore, so I'm closing it.
