### ISSUE TITLE
[mmp] Need `libmono-system-native.a` support

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#4977]
Mono has introduced a new `libmono-system-native.a` library that mmp needs to know about. If you build some projects linking against System mono you will see this on new mono (5.18):

```
  Undefined symbols for architecture x86_64: (TaskId:394)
    "_mono_pal_init", referenced from: (TaskId:394)
       -u command line option (TaskId:394)
ld: symbol(s) not found for architecture x86_64 (TaskId:394)
```

~~This was introduced in a mono that is shipping with d16-0-p1, so the fix will need to be applied there as well.~~

**Comment by spouliot** [comment]
`d16-0-p1` was branched before mono 2018-06 was merged, i.e. only `master` is affected.
P2 will be branched from master, so the fix is needed before that.

**Comment by spouliot** [comment]
@chamons I think you forgot to link https://github.com/xamarin/xamarin-macios/pull/4980 to this bug ? (or there was another part ?!?)

**Comment by chamons** [comment]
Guilty as charged.

I commented on the PR which is the best I think I can do at this point.
