### ISSUE TITLE
Branch information is missing in VSM

### ISSUE THREAD

**Issue by alanmcgovern** [xamarin/xamarin-macios#4990]
![screen shot 2018-10-16 at 11 50 34](https://user-images.githubusercontent.com/264396/47011586-3a3a2e80-d13a-11e8-95dd-1febbd552f45.png)

The `branch` component of the version information is not being displayed in VSM, but it is being displayed for the Xamarin.iOS product.

**Comment by spouliot** [comment]
This seems to work fine when XM is built locally (from master), e.g. I get
```
Xamarin.Mac
Version: 5.5.1.52 (Visual Studio Enterprise)
Hash: b2a596d6
Branch: master
Build date: 2018-10-15 21:22:26-0400
```

The above was missing from 
https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/master/2b3ef0e1832cc71adc91eb995cbc7099c123cbe8/105/package/xamarin.mac-5.5.1.0.pkg

**Comment by spouliot** [comment]
The above package does not report it's branch name. It seems it's the same (XM missing, XI fine) with later packages to (looked at x.y.1.23)

**Comment by spouliot** [comment]
latest build from `master` shows

```
Xamarin.Mac
Version: 5.5.1.59 (Visual Studio Enterprise)
Hash: 6044a74ae
Branch: master
Build date: 2018-10-17 02:15:06-0400
```
