### ISSUE TITLE
[watchOS] not all methods are invoked in `WCSessionDelegate` on device

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#5008]
I am porting the [WatchConnectivity](https://developer.apple.com/documentation/watchconnectivity/using_watch_connectivity_to_communicate_between_your_apple_watch_app_and_iphone_app) sample. I've found that some methods of the `WCSessionDelegate` are not invoked when the app is running on a real watchOS device. Everything is ok on iPhone (simulator/device) and watchOS simulator. 

_(I use the same `WCSessionDelegate` implementation for both (iOS and watchOS) apps)_

Methods that are not invoked in a watch app on device:
- `DidReceiveApplicationContext`
- `DidReceiveFile`
- `DidFinishFileTransfer`
- `DidReceiveUserInfo`
- `DidFinishUserInfoTransfer `

### Steps to Reproduce

1. Download a [sample](https://github.com/xamarin/private-samples/tree/watch-connectivity/ios12/SimpleWatchConnectivity) 
2. Run it on a device
3. Tap on "UpdateAppContext" button on iOS app.

Also you can run it on simulator before, to look how it should work on device.

### Expected Behavior
You see "Received at {time}" text

<img width="200" src="https://user-images.githubusercontent.com/32954580/47162185-2b02de80-d2fc-11e8-9756-628913e15358.png" />

### Actual Behavior
There is no UI changes

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/2a8268e58509c9924510b1e082c0bb6c
2. iPhone 7
`iOS 12.0.1 (16A404)`
3. Apple Watch 3 - 38 mm
`watchOS 5.0.1 (16R381)`

### Build Logs

1. Build output
https://gist.github.com/mykyta-bondarenko-gl/2ccaf04ff2087606a1a29bc35225f4ee

### Example Project

[Sample](https://github.com/xamarin/private-samples/tree/watch-connectivity/ios12/SimpleWatchConnectivity)

**Comment by VincentDondain** [comment]
@mykyta-bondarenko-gl mmh you don't need the debugger for build logs (:

**Comment by VincentDondain** [comment]
Super wild guess this could be related to incorrect entitlement / signing.

**Comment by mykyta-bondarenko-gl** [comment]
> Super wild guess this could be related to incorrect entitlement / signing.

in that way it shouldn't work at all, but app-groups works well and other methods are invoked too.

**Comment by mykyta-bondarenko-gl** [comment]
> @mykyta-bondarenko-gl mmh you don't need the debugger for build logs (:

sorry, I meant that I can't get any launching and running logs. Is any build logs are required for this issue?

**Comment by VincentDondain** [comment]
Always a good idea to attach build logs, that's why it's in the template (;

**Comment by spouliot** [comment]
hmm... still fighting Xcode to work with new watch :(
@rolfbjarne can you confirm the above ? thanks!

**Comment by spouliot** [comment]
Got Xcode to work on an old phone/watch :(

@mykyta-bondarenko-gl - why are you expecting no UI change ? there's an update when using Xcode. Is it possible you switched Expected and Actual results ?

> Expected Behavior
> There is no UI changes

**Comment by mykyta-bondarenko-gl** [comment]
@spouliot, sorry, you are right, I've just mixed up 'Expected' and 'Actual' results when filed the issue. 
Updated it already.

**Comment by mykyta-bondarenko-gl** [comment]
@spouliot, sorry, you are right, I've just mixed up 'Expected' and 'Actual' results when filed the issue. 
Updated it already.

**Comment by mykyta-bondarenko-gl** [comment]
@spouliot, sorry, you are right, I've just mixed up 'Expected' and 'Actual' results when filed the issue. 
Updated it already.

**Comment by mykyta-bondarenko-gl** [comment]
@rolfbjarne, do you mean on real device? what the version of XI you use?

**Comment by rolfbjarne** [comment]
However, debugging on watch device is broken in newer VSfM versions (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/712824) - either run in release mode or launch manually by tapping on the watch app.

**Comment by mykyta-bondarenko-gl** [comment]
I do in the same way. But the items that I had described before don't work properly (from watch side). If it's ok in your side we can close the issue. In that way it means that it's my local env issue.

**Comment by spouliot** [comment]
`TransferCurrentComplicationUserInfo` did not work on Xcode too IIRC. I was expecting it was related to the fact I had not run the (included) complication project yet.

**Comment by mykyta-bondarenko-gl** [comment]
@spouliot as I found there is no correct complication part (for any of these samples). So the main accent was to check 3 cases: Application Context, File Transfer, User Info Transfer

**Comment by rolfbjarne** [comment]
@mykyta-bondarenko-gl yes, on device, using XI master.

**Comment by mykyta-bondarenko-gl** [comment]
hm, I've checked it with the latest XI master build and it works for me well. 
@rolfbjarne @spouliot ^

**Comment by spouliot** [comment]
I cannot recall nothing watchOS specific in master that is not in 15.9, @rolfbjarne ?

I believe it's more likely a device issue that _solved itself_ when rebuilding from clean. You might want to try it again on 15.9.

**Comment by rolfbjarne** [comment]
I can't remember anything would cause a difference in behavior between master and d15-9 either.

**Comment by mykyta-bondarenko-gl** [comment]
I've checked it again with the latest `master` and `d15-9` builds. Everything works fine. 
@spouliot @rolfbjarne thank you! I think the issues is not actual and it can be closed.

**Comment by spouliot** [comment]
Random issues are _less_ random on watch than other platforms :)
Thanks for double-checking @mykyta-bondarenko-gl !
