### ISSUE TITLE
[XI]DontLink test failing to launch on 32 bit device

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#5018]
### Steps to Reproduce

1. Update System to Xamarin.iOS, Version: 12.2.1.9 (Visual Studio Enterprise)
Hash: 62840955
2. Execute DontLink test with or without fastdev enabled on a 32 bit device

### Expected Behavior
App should launch successfully
### Actual Behavior
App fails to launch successfully with a critical stacktrace.
### Environment
```
=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.7 Preview (7.7 build 1669)
Installation UUID: 74c37335-5878-4fa7-8f71-09bc48b661c5
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000189

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.189 (2018-06/2343f267067) (64-bit)
	Package version: 516000189

=== NuGet ===

Version: 4.7.0.5148

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.0 (14320.24)
Build 10A254a

=== Xamarin.Mac ===

Version: 5.2.1.9 (Visual Studio Enterprise)
Hash: 62840955
Branch: 
Build date: 2018-10-09 19:53:55-0400

=== Xamarin.iOS ===

Version: 12.2.1.9 (Visual Studio Enterprise)
Hash: 62840955
Branch: d15-9
Build date: 2018-10-09 19:53:55-0400

=== Xamarin.Android ===

Version: 9.1.0.33 (Visual Studio Enterprise)
Android SDK: /Users/gourikumari/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)

SDK Tools Version: 25.2.3
SDK Platform Tools Version: 25.0.1
SDK Build Tools Version: 25.0.1

Java SDK: /Users/gourikumari/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: dd6b1cc3

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 707001669
Git revision: 9c94fee7d22eddf2204bbb67419bcd55784b6683
Build date: 2018-10-17 18:29:16+00
Build branch: release-7.7
Xamarin extensions: 51533dd69d6de15e3e2c0257bc13c34aefa39c70

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:59:21 PDT 2018
    root:xnu-4903.201.2~4/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Gist Ide Information 1.1.0

```

### Build Logs
 Build Log: https://gist.github.com/GouriKumari/ce87a6ff6ffbb771b9bc313fda68d1cf
Stack Trace: https://gist.github.com/GouriKumari/dfa0859602fe5ea3a094e9101e456460
Device Log: https://gist.github.com/GouriKumari/c20878f9d30e46e707d0d1dd70ca99ab

### Example Project (If Possible)

xamarin-ios/tests/linker/ios/DontLink

### Additional Info:
This issue is not reproducible on a 64 bit device. Tests execute successfully.

**Comment by spouliot** [comment]
I have no problem (on master) to run the 32bits don't link tests.

@GouriKumari Is this something you have been able to reproduce locally ?

Can you double check on that device if it happens again (and get the device logs) and then reboot it ? Thanks!

**Comment by GouriKumari** [comment]
@GouriKumari Is this something you have been able to reproduce locally ?
yes, this issue is reproducible locally on the same device. 

I restarted the device and re-checked again, issue is reproducible. I see this with Dontlink test on the device, monotouch-test launched and executed successfully on the same device.

Console Log: https://gist.github.com/GouriKumari/a2b82570421caf66448deca7be97ff03

**Comment by spouliot** [comment]
So I can reproduce on 15.9. Like @rolfbjarne mentioned on today's call this is the same issue as the old 
https://bugzilla.xamarin.com/show_bug.cgi?id=1102. There's a size limit for arm 32 bits binaries and we're getting close (with Don't Link) of hitting it with our test app.

`master` (and 16.0) has some optimization that makes the test pass again. Hopefully long enough for Apple to complete it's 32bits removal.
