### ISSUE TITLE
Unable to run mbuild/tests in VS since swap to msbuild

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5042]
It is currently impossible to run\debug the iOS msbuild tests (msbuild/tests).

You get this error for your trouble:

```
SetUp : Microsoft.Build.Exceptions.InvalidProjectFileException : The imported project "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/xbuild/Xamarin/iOS/Xamarin.iOS.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  /Users/donblas/Programming/macios/master/xamarin-macios/msbuild/tests/MySingleView/MySingleView.csproj
```
Apparently xharness works just fine though.

### Steps to Reproduce

1. Open msbuild/Xamarin.MacDev.Tasks.sln
2. Build
3. Try to run a test

### Environment

Latest master

**Comment by chamons** [comment]
I can confirm the work around works.

**Comment by rolfbjarne** [comment]
> Debugging is also limited since this uses ILRepack and (at least right now) we lose debugging symbols.

This has been fixed in master, debugging should now work.
