### ISSUE TITLE
TcpClient network stream ignores network connectivity changes

### ISSUE THREAD

**Issue by borrrden** [xamarin/xamarin-macios#5044]
### Steps to Reproduce

1. Start up a server that listens for incoming TCP connections
2. Create a client that connects using TcpClient and writes to the stream returned by `GetStream()`
3. Allow at least one write to go through and then switch the phone to airplane mode
4. The write (and flush) continues to succeed despite the lack of network connectivity, making ability to detect a disconnected stream impossible

### Expected Behavior

There should be an exception thrown during the write call.  This is the behavior when calling `Connect` with airplane mode already on.

### Actual Behavior

The write succeeds and sends the bytes to ??? (I don't know where)

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.6.5 (build 20)
Installation UUID: 9c860ff0-60f7-49fa-9bc5-91a16d0b99b1
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.4
	1.0.7
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 11.14.0.14 (Visual Studio Community)
Hash: 1a6e2786
Branch: HEAD
Build date: 2018-08-28 00:12:06-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/borrrden/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706050020
Git revision: f6a29a810eb4b81ceb9a4ea4ba411da98b6e25cf
Build date: 2018-09-11 21:34:07+00
Build branch: release-7.6
Xamarin extensions: 097e18c3e104c652bde3a02799dcba13eaad6f7b

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Internet of Things (IoT) development (Preview) 7.5
```

### Build Logs

n/a

### Example Project (If Possible)

[WTFSocket.zip](https://github.com/xamarin/xamarin-macios/files/2518912/WTFSocket.zip)

**Comment by spouliot** [comment]
It's a platform _feature/issue_ where things do not work like most people expects it.

What happens is that the OS socket is **not** closed in airplane mode (might be after a while, e.g. if the app goes to the background). As such any operation on the sockets seems fine and no exception will be reported.

You can see this by:
- starting your TCP server;
- starting your app (it works);
- switch to airplane mode (no exception / timeout);
- switch off airplane mode (still works);
- close your server -> bang a `SocketException` (which means the socket was never closed earlier)

The _right_ (Apple) way to solve this is to detect the reachability of your service (and yes this has it's own set of issues) and, if not reachable, decide if you want to wait or cancel any pending communication.

**Comment by borrrden** [comment]
I don't understand this response.  Even if the OS socket is closed is should not be functional anymore.  It will fail to get any ACK responses for its transmissions and shut itself down, would it not?

**Comment by snej** [comment]
I don't agree with this answer either.

If you write to a TCP socket, it will send a packet (immediately or after a slight delay).
In airplane mode I would expect there to be no route to the host, since no interface is up. In that case the write will fail with an error.
Even if something weird is going on, like the WiFi interface remaining up but simply dropping all packets, then the socket will time out after failing to receive an ACK, and close with an error. (This takes about 10-15 sec, IIRC.)

**Comment by spouliot** [comment]
Try my steps above and let me know if you get different results (or interpretation of the results). Our SDK is open source and you can step down all the code to see there are no _ignored_ errors from the sockets and we're not recreating a new connection once airplane mode is disabled.

I agree (and mentioned) that the socket is likely closed at some point - but, beside being out of our control, it breaks (or delay) the code implementing the timeout.

**Comment by borrrden** [comment]
Further research does appear to suggest that @spouliot is right.  It appears that at the end of the day mono is using `send` with cleared flags to write to the socket (which, if I understand, is equivalent to what `write` would be doing since the file descriptor is a socket).  With airplane mode or without airplane mode the calls to `send` happily keep succeeding, against all logic and reason.
