### ISSUE TITLE
XM forcing provisioning with custom entitlements when Xcode does not 

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5061]
### Steps to Reproduce

1.  Create new Xcode macOS project. 
2. Add custom entitlements
3. Build and check signing. Provisioning not required:

![screen shot 2018-10-31 at 9 20 06 am](https://user-images.githubusercontent.com/6392201/47794982-929f2d80-dcef-11e8-863f-11d3b984a5de.png)

4. Create new XM project
5. Add same custom entitlement file to signing settings
6. Try to build. Get error stating that entitlements are required:

![screen shot 2018-10-31 at 9 20 14 am](https://user-images.githubusercontent.com/6392201/47795035-acd90b80-dcef-11e8-8ace-c36df1d6bd91.png)

### Expected Behavior

XM signing to match Xcode signing.

### Actual Behavior

Signing requires differ.

### Environment

https://gist.github.com/chamons/9283e9d56b1f4f5e51bce2edc19f5c6e

### Build Logs

https://gist.github.com/chamons/886d38dd03ed558af70da69fc6bfe360

**Comment by spouliot** [comment]
It's worth noting that, if you have a (Mac) provisioning profile, then it's possible to use **None** in the UI.

IOW the current code makes a difference between *None* (where no `.provisionprofile` file exists) and **None** (when the existing file(s) are simply ignored for the build)

**Comment by albilaga** [comment]
Any news when this is available? Will try to use without provisioning profile to submit rejected appstore submission again

**Comment by albilaga** [comment]
@spouliot you actually can’t do that. If you do that you actually still embed provisioning profile in mac.app. It is different with what XCode does when you use none in XCode it will not embed provisioning profile. You can try to Show Package Content in app that build with signing application bundle but with provisioning profile set to None. There is still embedded.provisionprofile inside the app

**Comment by albilaga** [comment]
Any update with this? My app still rejected because of this

**Comment by chamons** [comment]
I have not been able to reproduce an app rejection due to this.

Can you post the message and details?

**Comment by albilaga** [comment]
Yes. It is works right now. I also dunno what happen. I am just using VS for mac 2019. Anyway thanks for the concern

**Comment by jstedfast** [comment]
Possible solution:

Edit Xamarin.Mac.Common.targets:

```diff
- <_RequireProvisioningProfile Condition="'$(CodesignEntitlements)' != ''">True</_RequireProvisioningProfile>
+ <_RequireProvisioningProfile Condition="'$(CodeSignProvision)' != ''">True</_RequireProvisioningProfile>
```

**Comment by jstedfast** [comment]
The above change will allow codesigning with custom entitlements w/o a provisioning profile

**Comment by chamons** [comment]
This is now fixed in d16-1 and master.
