### ISSUE TITLE
[Xcode10.1] Apps not building  due to a new type introduced with Xcode10.1

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#5062]
### Steps to Reproduce

1. Install Xamarin.iOS 12.1.0.15 and Xcode10.1 stable
2. Build and Run sample MarsHabitatCoreMLTimer with Debug mode

### Expected Behavior
Apps should build successfully

### Actual Behavior
App fails to build with error 

```"/Users/xamarinqa/agent/_work/r1/a/monotouch-samples/ios12/MarsHabitatCoreMLTimer/MarsHabitatCoreMLTimer.csproj" (Build target) (1) ->
(_CompileToNative target) -> 
  /Users/xamarinqa/agent/_work/r1/a/monotouch-samples/ios12/MarsHabitatCoreMLTimer/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.h(3584,51): error GE30F8103: type argument 'UIPencilInteractionDelegate' must be a pointer (requires a '*') [/Users/xamarinqa/agent/_work/r1/a/monotouch-samples/ios12/MarsHabitatCoreMLTimer/MarsHabitatCoreMLTimer.csproj]
  /Users/xamarinqa/agent/_work/r1/a/monotouch-samples/ios12/MarsHabitatCoreMLTimer/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.h(3584,42): error GC919C233: type arguments cannot be applied to non-parameterized class 'NSObject' [/Users/xamarinqa/agent/_work/r1/a/monotouch-samples/ios12/MarsHabitatCoreMLTimer/MarsHabitatCoreMLTimer.csproj]
  /Users/xamarinqa/agent/_work/r1/a/monotouch-samples/ios12/MarsHabitatCoreMLTimer/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.m(50191,4): error G464A8611: cannot find protocol declaration for 'UIPencilInteractionDelegate' [/Users/xamarinqa/agent/_work/r1/a/monotouch-samples/ios12/MarsHabitatCoreMLTimer/MarsHabitatCoreMLTimer.csproj]
  MTOUCH : error MT4109: Failed to compile the generated registrar code. Please file a bug report at http://bugzilla.xamarin.com [/Users/xamarinqa/agent/_work/r1/a/monotouch-samples/ios12/MarsHabitatCoreMLTimer/MarsHabitatCoreMLTimer.csproj]

    2 Warning(s)
    4 Error(s)
```
### Environment

```
Mono version: 5.12.0.309 (39d89a335c8)  (2018-09-27 06:54:53 -04:00)
XA version: 9.0.0.20 (HEAD/86d33f45b) 
XI version: 12.1.0.15 (xcode10.1: cbfb047a) 
XM version: 5.0.0.0 (b40230c0)  (2018-09-27 11:41:37 -04:00)
XVS version: 
XS version: 7.6.11.7 (7cfeee4)  (2018-10-30 22:39:47 -04:00)
[Device] Name: XQA-AppleTV-3, Identifier: c38e2c74bad7b1d5ec5a0f95289b4c0d5e90e85d
```

### Build Logs

http://xqa.blob.core.windows.net/gist/report-0bea45694b0a4f12b2c1b4ed33140d19.txt

### Additional Info:
This issue is observed in  iOS samples and BCL tests
1. [Sample Failures](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=187163&environmentId=720377&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension)

2. [BCL test failure ](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=187163&_a=release-environment-extension&environmentId=720382&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab)

Please click on each failure to get the error report link. 

### Example Project (If Possible)

1. https://github.com/xamarin/ios-samples/tree/master/ios12/MarsHabitatCoreMLTimer
Other Samples are listed in additional Info failures.

**Comment by spouliot** [comment]
from slack

> seems to be a beta
> lrwxr-xr-x   1 xamarinqa  admin     37 Oct 16 17:19 Xcode.app -> /Applications/Xcode_10.1.0-beta.3.app

I can't reproduce this with the final version. It also make sense (the error) since that type was added in the final (and not part of beta 3)

**Comment by GouriKumari** [comment]
Verified with Xcode10.1 stable and XI 12.1.0.15 and the app builds successfully. 
Build Log: https://gist.github.com/GouriKumari/595c2c610b1a268f9ba521b615b0b005
Test Env: https://gist.github.com/GouriKumari/8ef6d7f319c0ef5ad5f5ebb36854b8c1

The error reported was due to the usage of an old QA repo build which did not have the commit to update Xcode10.1 change. This is now fixed.
