### ISSUE TITLE
Need to implement multi language feature in my xamarin IOS project

### ISSUE THREAD

**Issue by JindalArun** [xamarin/xamarin-macios#5075]
Expected Behavior - App should respond to multi language

Actual Behavior - Currently working in english language only

Environment - Xamarin IOS

Please provide me some documentation via which i can implement localization in my xamarin ios app.

**Comment by spouliot** [comment]
https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/

Note that for support requests you should use https://www.xamarin.com/support
Have a nice day!
