### ISSUE TITLE
App crashes when binding static library, but runs fine when Incremental Builds enabled

### ISSUE THREAD

**Issue by lexboss93** [xamarin/xamarin-macios#5124]
I've bound libstunnel.a static library to my xamarin.iOS project.

```
[DllImport("__Internal", CallingConvention = CallingConvention.Cdecl)]
public static extern int stunnel_main(int argc, [In, Out] string[] argv);
```

The problem is the app crashes after I make one call to a function of libstunnel.a and then make call to any iOS-framework code, for example NSUrl.FromString or UIColor.FromRGB.

```
System.NullReferenceException: Object reference not set to an instance of an object
  at ObjCRuntime.Class.FindType (System.IntPtr class, System.Boolean& is_custom_type) [0x00075] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/ObjCRuntime/Class.cs:309 
  at ObjCRuntime.Class.LookupClass (System.IntPtr klass, System.Boolean throw_on_error) [0x00002] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/ObjCRuntime/Class.cs:187 
  at ObjCRuntime.Class.Lookup (System.IntPtr klass) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/ObjCRuntime/Class.cs:173 
  at ObjCRuntime.Runtime.GetNSObject[T] (System.IntPtr ptr) [0x0003b] in <3dd904f9e3f64b43ae39970fe24f5cc3>:0 
  at Foundation.NSRunLoop.get_Main () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/Foundation/NSRunLoop.g.cs:287 
  at UIKit.UIKitSynchronizationContext.Post (System.Threading.SendOrPostCallback d, System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.1.0.15/src/Xamarin.iOS/UIKit/UIKitSynchronizationContext.cs:24 
```

Crash only happens when "Enable incremental builds" option is unset. When I switch this option on the app runs without crashes.
Maybe because in MtouchFastDev-enabled mode each assembly is compiled into a separate shared library libstunnel.a can't somehow corrupt memory.

I want to understand if it's the problem in xamarin side or in the static library itself or maybe in the way I'm binding this library.

When libstunnel.a used in xcode project it runs fine.

### Steps to Reproduce

1. Download provided sample project
2. Set your BundleId in Info.plist file
3. Start on a device
4. See app crashed

### Expected Behavior
App doesn't crash
### Actual Behavior
App crashes
### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.6.11 (build 9)
Installation UUID: 2596bb01-d8d8-4a3a-9db8-ea70559e0714
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Community)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.1.0.15 (Visual Studio Community)
Hash: cbfb047a
Branch: xcode10.1
Build date: 2018-10-30 22:57:23-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/user/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706110009
Git revision: d7cd66f5e3acd3d46ba0b94a0c935378f828bde0
Build date: 2018-10-31 17:17:12+00
Build branch: release-7.6
Xamarin extensions: bc9b985bfcb480b04a208a6d4045adc443a07857

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

```

### Build Logs

https://gist.github.com/lexboss93/153f3c6e45313cd9a309f94f96abbb9d

### Example Project

https://github.com/lexboss93/StunnelBindingCrash

p.s. The libstunnel.a is provided by [CryptoPro](https://www.cryptopro.ru/products/other/stunnel-msspi).
Their xcode sample project and the whole sdk can be downloaded [here](https://www.cryptopro.ru/products/csp/downloads) (Search for "iOS"). Download requires registration. Xcode project located in ios-uni/iStunnelSimple/.

**Comment by dalexsoto** [comment]
I can duplicate the current behavior with the provided [example project](url
https://github.com/lexboss93/StunnelBindingCrash)

**Comment by lexboss93** [comment]
Is there any workaround for this problem?

**Comment by rolfbjarne** [comment]
The problem is a symbol clash: both the native library and our libxamarin.a defines a symbol named `options`. After the native linker has executed, only a single version is left, which all the code uses. This becomes problematic because they obviously do not agree what the contents of the variable should be, so the app ends up crashing.

As a workaround, try adding the following to the additional mtouch arguments in the project's iOS Build options:

```
--assembly-build-target=@sdk=framework=Xamarin.Sdk --assembly-build-target=@all=staticobject
```

This will make us use a Xamarin.framework instead of libxamarin.a, which means that the native executable will only have one library using the the `options` symbol.
