### ISSUE TITLE
Build error for library project with SceneKit asset after updating to Xamarin.iOS 12.2.1.10

### ISSUE THREAD

**Issue by mikebluestein** [xamarin/xamarin-macios#5129]
### Steps to Reproduce

1. Create an iOS library project
2. Add a file with SceneKitAsset as the build action
3. Build project

### Expected Behavior
Project builds

### Actual Behavior
Build failure: 

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1281,3): error MSB4044: The "CompileSceneKitAssets" task was not given a value for the required parameter "AppBundleDir".

### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.11 (build 9)
Installation UUID: 0cc4e5d4-daf4-4e4e-bf89-0c02c659a044
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/mikeb/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Enterprise)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.2.1.10 (Visual Studio Enterprise)
Hash: f2a05edd
Branch: d15-9
Build date: 2018-10-31 18:55:57-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706110009
Git revision: d7cd66f5e3acd3d46ba0b94a0c935378f828bde0
Build date: 2018-10-31 17:17:12+00
Build branch: release-7.6
Xamarin extensions: bc9b985bfcb480b04a208a6d4045adc443a07857

=== Operating System ===

Mac OS X 10.14.1
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Fri Oct  5 19:41:49 PDT 2018
    root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.31
Redth's Addins 1.0.9

```

### Build Logs

https://gist.github.com/mikebluestein/2b204eee75a71cf806271bc3fcde6db7

### Example Project (If Possible)

[foo.zip](https://github.com/xamarin/xamarin-macios/files/2580947/foo.zip)

**Comment by GouriKumari** [comment]
I can reproduce this with the attached library project. 

## Build Log:
https://gist.github.com/GouriKumari/7062d429582124e6cdb4500ea47f432a

##Test Env:
https://gist.github.com/GouriKumari/ed9cf7fb4fada557e0fd38f982b337f6

## Additional Info:
This builds successfully with 12.1.0.15 and is a regression.
Build Log: https://gist.github.com/GouriKumari/63c72b8d2c7b93dfaa886610457bd821
Test Env: https://gist.github.com/GouriKumari/dc4592d601dcac10a2c8fd83b58ee667

**Comment by spouliot** [comment]
@jstedfast does this ring a bell ?

**Comment by jstedfast** [comment]
Yea, looks like 0d65ed93578d45183b704ccef98f3f939721b9fc caused this

**Comment by mikebluestein** [comment]
Is there a workaround, such as adding something directly to the project file?

**Comment by mikebluestein** [comment]
thanks, that worked

**Comment by spouliot** [comment]
@rolfbjarne SR1 is already out (or at least frozen) and the bar for 15.9 SRx is very high (even more if a workaround is available). Let's monitor how many people are affected (cc. @dalexsoto).

**Comment by spouliot** [comment]
Fixed for preview 2
