### ISSUE TITLE
[API] NSString constructors for substrings without allocating a new managed string

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#5134]
Currently, `NSString` APIs allow only to pass a managed string.

This forces APIs which would typically just use a substring be forced to allocate a string for the substring itself.

```
var myString = "asdf";
var myNSString = new NSString (myString.Subtring (0, 2));
```

Proposed APIs:
```
public NSString (string str, int start, int length) {}
```

The implementation would then just marshal part of the string, avoiding an intermediate string allocation.

NetStandard 2.0 thoughts:
Maybe the APIs could take a `ReadOnlySpan<char>` which would automatically handle slicing and offset calculation.

**Comment by dalexsoto** [comment]
I really like the `ReadOnlySpan<char>` idea.

**Comment by Therzok** [comment]
`ReadOnlySpan<char>` would probably leak out in API and not benefit people targeting .NET 4.5. I'll settle for the offset+length parameters.
