### ISSUE TITLE
MT3001 when attempting to build iOS Device project that uses Net Core SignalR with Linking off

### ISSUE THREAD

**Issue by BenBtg** [xamarin/xamarin-macios#5137]
### Steps to Reproduce
Just create a blank forms app and add Microsoft,AspNetCore.SignalR.Client, turn off linking and build release or debug for device (not simulator)
1. Create a blank Forms App
2. Add Microsoft,AspNetCore.SignalR.Client (1.0.4)
3. Turn off linking
4. Add the following block of code if Main.xaml.cs just to reference package
        HubConnection hubConnection;
        public MainPage()
        {
            InitializeComponent();

            hubConnection = new HubConnectionBuilder()
                .WithUrl($"https://mccommunicator.azurewebsites.net/chat")
                .Build();
        }
5. Build

### Expected Behavior
Clean build

### Actual Behavior
MT3001 build error
MTOUCH: Error MT3001: Could not AOT the assembly 'Test.iOS/obj/iPhone/Debug/device-builds/iphone10.6-12.1.1/mtouch-cache/3-Build/System.Threading.Channels.dll' (MT3001) (Test.iOS)

### Environment
Have tested on Stable and Alpha also.

=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.7 Preview (7.7 build 1829)
Installation UUID: 24266b2a-cbb7-4ca0-8c26-6ef9f17371b7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000209

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.209 (2018-06/709b46e3338) (64-bit)
	Package version: 516000209

=== NuGet ===

Version: 4.7.0.5148

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.2
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Version: 2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.1.0.38 (Visual Studio Enterprise)
Android SDK: /Users/benbtg/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Java SDK: /Users/benbtg/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: ee948863

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.10 (Visual Studio Enterprise)
Hash: f2a05edd
Branch: 
Build date: 2018-10-31 18:55:58-0400

=== Xamarin.iOS ===

Version: 12.2.1.10 (Visual Studio Enterprise)
Hash: f2a05edd
Branch: d15-9
Build date: 2018-10-31 18:55:57-0400

=== Build Information ===

Release ID: 707001829
Git revision: 2e0bc097db3ec4bff2bb76153a1d3c956c74a5e1
Build date: 2018-11-02 21:08:01+00
Build branch: release-7.7
Xamarin extensions: aa3663e75d1924e4fe293d8eab6f6f2d98ef1ebf

=== Operating System ===

Mac OS X 10.14.1
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Fri Oct  5 19:41:49 PDT 2018
    root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Archiver 1.0
Redth's Addins 1.0.9

### Example Project (If Possible)
Any sample app that uses SignalR

**Comment by dalexsoto** [comment]
This has been confirmed and now it is being tracked here https://github.com/mono/mono/issues/11731

**Comment by dalexsoto** [comment]
Hello, the mono team has fixed the issue and we have some build candidates here 
https://github.com/xamarin/xamarin-macios/issues/5158#issuecomment-440673490 please let us know if these fixes your issue. Report back to https://github.com/xamarin/xamarin-macios/issues/5158.

Thanks!
