### ISSUE TITLE
Unable to run\debug mmp\msbuild-mac tests in IDE

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5145]
[This](https://github.com/xamarin/xamarin-macios/commit/f865694f86dca326a5721c1e0ba5795e7971d5e6) commit breaks running\debugging tests that use the new xibuild.

The root cause is that that we are add xibuild to the path in tests/Makefile with the incorrect assumption that it will affect all usages. The IDE does not inherit that setting.

```
System.ComponentModel.Win32Exception : ApplicationName='xibuild', CommandLine=' --  /verbosity:diagnostic  /property:XamarinMacFrameworkRoot=/Users/donblas/Programming/macios/master/xamarin-macios/_mac-build/Library/Frameworks/Xamarin.Mac.framework/Versions/Current /property:Configuration=Debug /Users/donblas/Programming/macios/master/xamarin-macios/tests/mmptest/bin/Debug/tmp-test-dir/Xamarin.MMP.Tests.MMPTests.RunMMPTest/MobileBinding.csproj', CurrentDirectory='', Native error= Cannot find the specified file
```

cc: @radical

**Comment by jdpcharter** [comment]
Would this be an instance of this issue? In visual studio for mac
1. File => New Solution
2. Multiplatform => App => Xamarin.Forms => Blank forms app => next => give this a unique name => target iOS => create
3. Build and run the app in the iOS simulator
4. View => Test => <yourappname>.UITests.Tests => Tests(iOS) => run _WelcomeTextIsDisplayed_

This will fail with this output
`SetUp : Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to install DeviceAgent

ExitCode: 1

		-c,--codesign-identity	<codesign-identifier> [OPTIONAL] 	Identity used to codesign app bundle [device only]. Deprecated - should use profile path.	DEFAULT=
		-d,--device-id	<device-identifier>	iOS Simulator GUID or 40-digit physical device ID
		-f,--force	<force-reinstall-app> [OPTIONAL] 	Reinstall the app if the device contains an older version than the bundle specified	DEFAULT=0
		-i,--resources-path	<resources-path> [OPTIONAL] 	Path to resources (executables) to inject into app directory. A list of colon separated files may be specified.
		-p,--profile-path	<profile-path> [OPTIONAL] 	Path to provisioning profile
	install <app-path>
App com.apple.test.DeviceAgent-Runner is not installed on 96634AB2-ECA8-4883-851B-93C673ED2F68
Error installing application: Error Domain=com.facebook.FBSimulatorControl Code=0 "Simulator does not support any of the architectures ([x86_64, i386]) of the executable at /var/folders/ng/_lmtqng90fqgzbsyrj9y3fpc0000gq/T/xdb/DeviceAgent.iOS.Dependencies/9a7eae887a041f733c06f5eef3e12600/app/DeviceAgent-Runner.app/DeviceAgent-Runner. Simulator Archs ([(null)])" UserInfo={NSLocalizedDescription=Simulator does not support any of the architectures ([x86_64, i386]) of the executable at /var/folders/ng/_lmtqng90fqgzbsyrj9y3fpc0000gq/T/xdb/DeviceAgent.iOS.Dependencies/9a7eae887a041f733c06f5eef3e12600/app/DeviceAgent-Runner.app/DeviceAgent-Runner. Simulator Archs ([(null)])}`

The same will occur testing on physical devices.

**Comment by rolfbjarne** [comment]
@jdpcharter no, that's unrelated (this issue is just about internal testing issues on our end).

Your issue seems AppCenter-related; my suggestion would be to contact AppCenter and see if they have a solution to your problem.

**Comment by jdpcharter** [comment]
Thank you, AppCenter's team has been helpful. I would like to clarify to prevent further posts, that from the customer's point of view while AppCenter is the correct place to contact, this issue has nothing obvious to do with AppCenter, as it impacts local simulator and local physical device UI tests.

**Comment by chamons** [comment]
This has been fixed by some change in the last year and you can debug them.

Ideally we should move msbuild-mac to mmp at this point.
