### ISSUE TITLE
warning in static registrar created code when building with target as Xamarin.Mac Full 

### ISSUE THREAD

**Issue by jesweare** [xamarin/xamarin-macios#5152]
### Description

When building a project targeted for Xamarin.Mac full, a warning related to the static registrar occurs, which mentions a single method in one of the protocols not implemented. 
Changing to dynamic registrar settings (`--registrar:dynamic`) removes the warning, but the scope of its effects is considered too large right now to use as a workaround for the sake of removing a warning.
I do see past issues that report similar warnings but all seem to be addressed so currently I cannot find info that explains this behavior.

If there was a background that indicates the warning as something that can be ignored, pointing that out would help.

### Steps to Reproduce

1. Open Visual Studio for Mac and create new Xamarin.Mac project (Cocoa App suffices)
2. Set Project build to Release
3. Under Project Options > General, set Target Framework to "Xamarin.Full"
4. Build solution

### Expected Behavior
App builds without errors or warnings

### Actual Behavior
The following warning appears:
`
/mmp-cache/registrar.m(17,17):　Warning GC27A339F: method 'deviceBrowserView:selectionDidChange:'　in protocol 'IKDeviceBrowserViewDelegate' not implemented [-Wprotocol]　(GC27A339F)
`

### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.11 (build 9)
Installation UUID: 4fec54fe-349d-44bb-a234-e53ab7b55b68
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.2
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Version: 2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Enterprise)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.1.0.15 (Visual Studio Enterprise)
Hash: cbfb047a
Branch: xcode10.1
Build date: 2018-10-30 22:57:23-0400

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/<username>/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706110009
Git revision: d7cd66f5e3acd3d46ba0b94a0c935378f828bde0
Build date: 2018-10-31 17:17:12+00
Build branch: release-7.6
Xamarin extensions: bc9b985bfcb480b04a208a6d4045adc443a07857

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

```

### Example Project (If Possible)

This can be reproduced using the standard template project pointed in "Reproduce Steps".

**Comment by dalexsoto** [comment]
Hello, Thank you for your feedback!

You are right, the warning shows up here and you actually found a small issue with the generated static-registrar code but, it is a harmless one so you can safely ignore it. we'll take a look and fix this in a later release.

**Comment by chamons** [comment]
This appears to have been fixed in the last year, but now we warn with:

MMP : warning MM5220: Skipping framework 'QTKit'. It is prohibited (rejected) by the Mac App Store

Which I think is fair. You really should enable some form of linking for Release builds.

**Comment by xavier-rigau** [comment]
> This appears to have been fixed in the last year, but now we warn with:
> 
> MMP : warning MM5220: Skipping framework 'QTKit'. It is prohibited (rejected) by the Mac App Store
> 
> Which I think is fair. You really should enable some form of linking for Release builds.

How you suppress the warning : MMP : warning MM5220: Skipping framework 'QTKit'. It is prohibited (rejected) by the Mac App Store?

**Comment by chamons** [comment]
From ` /Library/Frameworks/Xamarin.Mac.framework/Commands/mmp --help`

```
      --nowarn[=VALUE]       An optional comma-separated list of warning codes
                               to ignore (if no warnings are specified all
                               warnings are ignored).
```

You can pass that as additional mmp arguments in your mac build project configuration.

**Comment by xavier-rigau** [comment]
Thanks Chris,
I should had phrased the question better.
Is this a bogus warning or a real one. If real, what changes do I have to make it in the project to not used the QTkit?

**Comment by chamons** [comment]
So the warning:
```
MMP : warning MM5220: Skipping framework 'QTKit'. It is prohibited (rejected) by the Mac App Store
```
is mostly what it says on the tin, but let me give some context:

- Your application has not enabled any linking, so every XM binding is in your final app
- To make those work, we have to link against every one of Apple's frameworks
- One of those is QTKit, which Apple won't let you use if you are using the App store
- That will make your app get rejected if you try to submit it.

If you aren't submitting to the app store, it's mostly harmless for now. However, if you enable some form of [linking](https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/linker#platform-linking), it will go away. 

We have a "platform" linking which is the least invasive, if you want the minimum work or are using the Full [target framework](https://developer.xamarin.com/guides/mac/advanced_topics/target-framework/). 

If you are using modern, you can enable SDK linking to further reduce application size, but that might require some work if you are using reflection.
