### ISSUE TITLE
Incomplete System.Threading.Tasks.Extensions Facade in 15.9

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#5158]
An incomplete facade assembly for `System.Threading.Tasks.Extensions` was included in `d15.9`. This breaks projects that were previously using the implementation provided by a nuget.

# Workaround

On Windows delete the file
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades\System.Threading.Tasks.Extensions.dll`

On macOS delete the files
```
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib//mono/Xamarin.TVOS/Facades/System.Threading.Tasks.Extensions.dll
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib//mono/2.1/Facades/System.Threading.Tasks.Extensions.dll
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib//mono/Xamarin.WatchOS/Facades/System.Threading.Tasks.Extensions.dll
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib//mono/Xamarin.iOS/Facades/System.Threading.Tasks.Extensions.dll
/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib//mono/Xamarin.Mac/Facades/System.Threading.Tasks.Extensions.dll
```

This will fallback to using the nuget version, like the previous stable release was doing.

# Issues
* https://github.com/mono/mono/issues/11731
* https://github.com/aspnet/SignalR/issues/3307
* https://github.com/xamarin/xamarin-macios/issues/5135
* https://developercommunity.visualstudio.com/content/problem/383917/build-issue-when-updateing-to-xamarinios-122110.html
* https://github.com/xamarin/xamarin-macios/issues/5137
* https://github.com/xamarin/xamarin-macios/issues/5133

> VS bug [#732659](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732659), VS bug [#732660](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732660)

**Comment by xamarin-release-manager** [comment]
[VS sync] The field 'Milestone' contains the value '15.9' that is not in the list of supported values

**Comment by spouliot** [comment]
@dalexsoto please update the list of issues (with closed ones and new ones). thanks!

**Comment by spouliot** [comment]
Builds candidates (unverified at this time)
* https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d15-9/5ef73d34476630f441635d878360e94b95a048ee/45/package/xamarin.ios-12.2.1.11.pkg
* https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d15-9/5ef73d34476630f441635d878360e94b95a048ee/45/package/xamarin.mac-5.2.1.11.pkg

**Comment by CliffAgius** [comment]
This issues seems to have re-appeared in the VS19 Pre.1 release I have been playing with today.
