### ISSUE TITLE
NSFormatter IsPartialStringValid issue

### ISSUE THREAD

**Issue by equinox2k** [xamarin/xamarin-macios#5171]
I think there is an issue with

` public override bool IsPartialStringValid(ref string partialString, out NSRange proposedSelRange, string origString, NSRange origSelRange, out string error)`
 
as soon as you try to implement and is called app crashes with exception...

"Unable to marshal byref parameter type"

Original signature for ref..

`- (BOOL)isPartialStringValid:(NSString **)partialStringPtr proposedSelectedRange:(NSRangePointer)proposedSelRangePtr originalString:(NSString *)origString originalSelectedRange:(NSRange)origSelRange errorDescription:(NSString **)error
`

**Comment by equinox2k** [comment]
@spouliot 

I think yours works because not bound to a text box and not physically type a char into box.

I have created a test app to show issue...

https://www.dropbox.com/s/qlgp5znoqxu0chs/TextFormatter.zip?dl=0

Just of code is...

```
    public class FormatterSubclass : NSFormatter
    {
        public override string StringFor(NSObject value)
        {
            var text = value as NSString;
            return text ?? string.Empty;
        }

        public override bool GetObjectValue(out NSObject obj, string str, out NSString error)
        {
            error = null;
            obj = new NSString(str);
            return true;
        }

        public override bool IsPartialStringValid(ref string partialString, out NSRange proposedSelRange, string origString, NSRange origSelRange, out string error)
        {
            return base.IsPartialStringValid(ref partialString, out proposedSelRange, origString, origSelRange, out error);
        }
    }
```

```
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            textField.Formatter = new FormatterSubclass();

        }
```

"Unable to marshal byref parameter type"
"  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])\n  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.0.0.0/src/Xamarin.Mac/AppKit/NSApplication.cs:100 \n  at TextFormatter.MainClass.Main (System.String[] args) [0x00007] in /Users/ptribe/Documents/TextFormatter/TextFormatter/Main.cs:10 "

**Comment by equinox2k** [comment]
Additionally 

proposedSelectedRange on native method indicates it is a ref where as in Xamarin implementation its only an out.

**Comment by spouliot** [comment]
I can reproduce.

`Unable to marshal byref parameter type` comes from `runtime/trampolines-invoke.m`.

@rolfbjarne we should look at having a generator check (and/or a test) that ensure we don't produce bindings that can trigger this.

**Comment by rolfbjarne** [comment]
There are multiple bugs here 😒 

1. The generator generates the wrong code for non-out parameters: when calling ObjC it doesn't pass the initial value (it treats the parameter as an out parameter, where the value at input is not necessary).

2. Neither the static nor the dynamic registrar handle this case properly (the static registrar silently does the wrong thing, the dynamic registrar at least throws an exception).
