### ISSUE TITLE
[Foundation]NSUrlSessionHandler does not respect the timeout that is set in the HttpClient.

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#5190]
Following the description found in https://developercommunity.visualstudio.com/content/problem/388530/httpclienttimeout-values-set-above-default-100-sec.html I have been able to confirm that when using the NSUrlSessionHandler as the message handler for the HttpClient, we do not respect the given timeout. The following code can be used as an example:

```CSharp
 HttpClient client = new HttpClient();
 client.Timeout = TimeSpan.FromSeconds (150);
 client.BaseAddress = new Uri("http://slowwly.robertomurray.co.uk");
 client.DefaultRequestHeaders.Accept.Clear();
 client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
 HttpResponseMessage response = await client.GetAsync("http://slowwly.robertomurray.co.uk/delay/160000/url/http://www.google.co.uk");
response.EnsureSuccessStatusCode();
```

This happens because, when the message handler is instantiated the NSUrlSessionConfiguration does not has its TimeoutIntervalForRequest set to the correct value and uses the default, which is 60 seconds. 

The solution would be to set the timeout used by the handler so that when the configuration is created the correct timeout is used.

**Comment by mandel-macaque** [comment]
The work around is to create the NSUrlSessionHandler manually via a configuration and then instantiate the HttpClient:

```CSharp
var configuration = NSUrlSessionConfiguration.DefaultSessionConfiguration; // or any other needed
configuration.TimeoutIntervalForRequest = 160;
var handler = new NSUrlSessionHandler (configuration);
var client = new HttpClient (handler);
```

**Comment by spouliot** [comment]
That's a bug - the two (managed/client vs native/handler) timeouts are fighting each other. 

When using `HttpClient` the user code should not have know anything basic (defined in `HttpClient`, like `Timeout`). To achieve that the native timeout needs to be disabled or, in case they cannot be, longer than the native ones.

Note: in most cases the workaround is _fine_ but it won't work if `HttpClient` is used in a 3rd party binary assembly.

**Comment by spouliot** [comment]
Test case with public web site

```
		async Task Test (HttpMessageHandler handler)
		{
			Console.WriteLine ($"### {handler}");
			var now = DateTime.UtcNow;
			try {
				var client = new HttpClient (handler);
				client.Timeout = TimeSpan.FromSeconds (150);
				HttpResponseMessage response = await client.GetAsync ("https://httpstat.us/200?sleep=120000");
				response.EnsureSuccessStatusCode ();
				Console.WriteLine ("PASS");
			} catch (Exception e) {
				Console.WriteLine ($"FAIL {e}");
			} finally {
				Console.WriteLine ($"Time {(DateTime.UtcNow - now).TotalSeconds}");
			}
		}
```

**Comment by spouliot** [comment]
The `CFNetworkHandler` issue is different, it hangs because there's an Open and Close (no data in between) so it _might_ be unrelated to the timeout (just a different, less common issue). I'll open another bug for it since it lives in the mono repo and won't be fixed by the same PR.
