### ISSUE TITLE
[Xamarin.Mac/Modern] System.IO.FileSystemWatcher throws NotImplementedException

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#5197]
From https://bugzilla.xamarin.com/show_bug.cgi?id=42935 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735558.

Let's keep an issue in this repo to track the work needed to support `System.IO.FileSystemWatcher` on Xamarin.Mac Modern.

_Note: this is supported in Xamarin.Mac Full._

**Comment by rolfbjarne** [comment]
This should work in .NET.
