### ISSUE TITLE
[XM] Mac application has 'iPhone/iPhoneSimulator' configurations 

### ISSUE THREAD

**Issue by mykyta-bondarenko** [xamarin/xamarin-macios#5201]
### Steps to Reproduce

1. Open VSfM 
2. Create new XM project (there are only `Debug` and `Release`)
3. Add new XI project
   - XI is a start project - there are `Debug` and `Release`
   - XM is a start project - there are  `Debug|x86`, `Release|x86`, `Debug|iPhone`, `Release|iPhone`, `Debug|iPhoneSimulator` and `Release|iPhoneSimulator` 

### Expected Behavior
There are `Debug` and `Release` configurations

### Actual Behavior
There are `Debug|iPhone`, `Release|iPhone`, `Debug|iPhoneSimulator` and `Release|iPhoneSimulator` configurations

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/282d2a3abfdcff122b5eeccf04b4cdc1

> VS bug [#737219](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/737219)

**Comment by VincentDondain** [comment]
Oh yea I can confirm that part:

1. Open VSfM
2. Create new XM project (there are only Debug and Release)
3. Add new XI project  
    - XI is a start project - there are Debug and Release
    - XM is a start project - there are Debug|x86, Release|x86, Debug|iPhone, Release|iPhone, Debug|iPhoneSimulator and Release|iPhoneSimulator

That is not correct (:

A new XM project has the correct config, a new XI project does too but adding an XI project to a solution with a Mac project mixes things up.

This is an **md-addin** issue though (added appropriate label).
