### ISSUE TITLE
RegistrarAttribute without explicit name isn't honored by Xcode project generator

### ISSUE THREAD

**Issue by wjk** [xamarin/xamarin-macios#5204]
### Steps to Reproduce

1. Download and open the repro project linked below.
2. Open the Main.storyboard file. Notice how the `AppDelegate` ObjC class files are present. Quit Xcode.
3. Open `AppDelegate.cs`, and change the line `[Register("AppDelegate")]` to just `[Register]`.
4. Reopen the Main.storyboard file. Notice how the AppDelegate ObjC classes are now missing.

### Expected Behavior

The Xcode project generator should generate a name automatically from the full name of the C# class [like the registrar does](https://github.com/xamarin/xamarin-macios/blob/8a81607279c08a36021b562154f911e692a1c87b/src/ObjCRuntime/Registrar.cs#L2522-L2523), and write that name into the generated ObjC files in the Xcode project.

### Actual Behavior

It doesn't do this, and ignores the AppDelegate class when generating the Xcode project. This will cause problems later, when I try to edit the storyboard or run the app.

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.6.11 (build 9)
Installation UUID: 2f7490c4-93db-429d-9511-4b9317c93fbc
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.3
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.401/Sdks
SDK Versions:
	2.1.401
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Community)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.1.0.15 (Visual Studio Community)
Hash: cbfb047a
Branch: xcode10.1
Build date: 2018-10-30 22:57:23-0400

=== Xamarin.Android ===

Not Installed

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706110009
Git revision: d7cd66f5e3acd3d46ba0b94a0c935378f828bde0
Build date: 2018-10-31 17:17:12+00
Build branch: release-7.6
Xamarin extensions: bc9b985bfcb480b04a208a6d4045adc443a07857

=== Operating System ===

Mac OS X 10.14.1
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Fri Oct  5 19:41:49 PDT 2018
    root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

EditorConfig 1.2
Eto.Forms Support Addin 2.4.0.0
AddinMaker 1.4.3
.NET Core Extended Target Framework Support 1.0
EditorConfig Support 0.1
```

### Build Logs

I don't see how these are relevant, as this isn't a build issue.

### Example Project

[RegistrarRepro.zip](https://github.com/xamarin/xamarin-macios/files/2631685/RegistrarRepro.zip)

> VS bug [#738504](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/738504)

**Comment by VincentDondain** [comment]
Well the simple answer to this is: do not change `[Register("AppDelegate")]` (:

I've never explored this myself but I believe there _might_ indeed be a chance to improve the Xcode syncing logic of VSMac (assigning the right label).

In any case this is probably not high priority as I believe the current solution works as expected (unless you can point at limiting factors).

**Comment by wjk** [comment]
@VincentDondain The only reason I brought this up is because I like to have the namespace of my types show up in the Obj-C class names. I could of course do this by hand by changing the string argument to the RegisterAttribute; I was just wondering if it could be done automatically. Thanks for checking for me!
