### ISSUE TITLE
[msbuild] Mac should support `ArchiveAppBundle` like iOS

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5236]
See https://github.com/xamarin/mirepoix/commit/05ff27d77b19546a65f5a1589ca991e7d5fbe118 for a potential implementation.

**Comment by VincentDondain** [comment]
@chamons I am not quite sure a. what's the benefit of having zipping the app bundle on the Mac on build (we already can either produce a .pkg and .xcarchive so...) and b. which iOS code you're referring to and how to use it.

**Comment by rolfbjarne** [comment]
See also: https://trello.com/c/n8cY8Tbs

**Comment by chamons** [comment]
@abock Could you comment on this? I filed it after your comment, but i'm not honestly sure how `ArchiveAppBundle` works even...

**Comment by spouliot** [comment]
Not enough context. `ArchiveAppBundle` does not exists (at least by that name) for iOS projects.

@abock ? @chamons ?

**Comment by chamons** [comment]
I'm honestly not sure, I filed it after @abock complained about it.

**Comment by chamons** [comment]
Closed after no comment from original reporter. I do not remember sufficient context right now.
