### ISSUE TITLE
[XI]mscorlib test failures on 32 bit device with master

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#5258]
### Steps to Reproduce

1. Update System to Xamarin.iOS master build 
2. Execute mscorlib test on 32 bit device

### Expected Behavior
All tests should pass

### Actual Behavior
There are 6 failures.
       [FAIL] DoubleFormatterTest.TestFormatStringsN1 :   DblFn1 #216
	[FAIL] DoubleFormatterTest.TestFormatStringsN1_Fixed :   DblFn1 #200
	[FAIL] DoubleFormatterTest.TestFormatStringsN2 :   DblFn2 #216
	[FAIL] DoubleTest.LongLongValueRoundtrip :   Expected string length 21 but was 1. Strings differ at index 0.
	[FAIL] Rfc2898DeriveBytesTest.ConstructorPasswordSaltLengthZero : An unexpected exception type was thrown
	[FAIL] Rfc2898DeriveBytesTest.ConstructorPasswordSaltLengthZeroIterations : An unexpected exception type was thrown

### Environment

```
Mono version: 5.18.0.219 (f919fb58c4e)  (2018-12-04 12:36:55 -05:00)
XA version: 9.1.199.34 (HEAD/e9570566) 
XI version: 12.5.1.313 (master): 3621032d) 
XM version: 5.5.1.313 (master: 3621032d)  (2018-12-07 14:59:44 -05:00)
XVS version: 
XS version: 7.8.0.1362 (fc834dd)  (2018-12-07 14:06:35 -05:00)
[Device] Name: XQAiPad2b, Identifier: 0c3a0d1d60fbd11401f1d6ca33518e9a31bafab4
32 bit device: iPad2
```

### Build Logs

Build Log+Installation Log: http://xqa.blob.core.windows.net/gist/report-68c060035e62461db0fc9c020a3b5557.txt
Test+DeviceLog: http://xqa.blob.core.windows.net/gist/mscorlib-ios06-12-190c3a0d1d60fbd11401f1d6ca33518e9a31bafab406-12-19-dc865843b8f54ef284be2448e1c78782.zip

Verified Locally: https://gist.github.com/GouriKumari/498036ef7aef60dc495720d4867d6ce2
Last test run against master is with 12.2.1.316 which also has the same test failures.

### Example Project (If Possible)

xamarin-macios/tests/bcl-tests/mscorlib

mono2018-08 tests from bots didn't run on the 32 bit device.

**Comment by rolfbjarne** [comment]
The four first have been reported here: https://github.com/mono/mono/issues/11965

**Comment by VincentDondain** [comment]
I do not have a 32 bit device to reproduce but I'll trust those results and given that we already filed 
https://github.com/mono/mono/issues/11965 let's just add `[FAIL] Rfc2898DeriveBytesTest.ConstructorPasswordSaltLengthZero : An unexpected exception type was thrown` and `[FAIL] Rfc2898DeriveBytesTest.ConstructorPasswordSaltLengthZeroIterations : An unexpected exception type was thrown` to the existing list.
