### ISSUE TITLE
Security KeyTest does not clean up after itself

### ISSUE THREAD

**Issue by MSylvia** [xamarin/xamarin-macios#5266]
Security tests that create public and private test keys in the user keychain (`NotDefault` and `<key>`) are not cleaned up after test completion.

> Ref: https://github.com/xamarin/xamarin-macios/blob/master/tests/monotouch-test/Security/KeyTest.cs#L520

### Steps to Reproduce

1. Run test that executes CreateRandomKeyTest

### Expected Behavior
Keys created by test in the users keychain are created and removed after test is complete
### Actual Behavior
The keys are never removed. This significantly slows down operations that iterate over keychain items.
### Environment
macOS any

**Comment by VincentDondain** [comment]
After discussing with Matt, the issue he's seeing on the bots it an explosion of the number of keys in the keychain (nameless keys).

See:

<img width="989" alt="screenshot 2018-12-12 14 54 25" src="https://user-images.githubusercontent.com/7839202/49895291-12a3d180-fe1e-11e8-90b1-d899285b4207.png">

This happens on my iMac (pretty old work machine) but did not yet happen on my recently formatted MacBook Pro. So the assumption is that I didn't yet run the tests that lead to that scenario.

It's worth pointing that I did run the monotouch-test KeyTests mentioned in the description on the fresh MacBook Pro and I do not have the nameless keys.

All the tests in this file seem to create random keys without deleting them but I do not, yet, see where they are in the keychain.

**Comment by VincentDondain** [comment]
This needs further investigation as I'm not sure it's at all related to the tests mentioned in this issue.

**Comment by rolfbjarne** [comment]
@VincentDondain try executing xammac_tests instead of monotouch-test, since monotouch-test probably only add keys to the simulator's keychain, and not the mac's.

**Comment by rolfbjarne** [comment]
Fixed in 86bfa92466e260a2a2b19fb898e19800bbe95aeb.
