### ISSUE TITLE
NSObject.SetAsProxy looks unnecessary

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#5268]
NSObject.SetAsProxy looks unnecessary: https://github.com/xamarin/xamarin-macios/blob/f77b1b712eedc1072d2f31e8ac68fc60d12cee17/src/Foundation/NSObject.mac.cs#L121-L123

This method was introduced some time ago:

https://github.com/mono/monomac/commit/0f91a72e4ef0663e01cbf80aa856fa4b5c4a02cb
https://github.com/mono/maccore/commit/cc2eb799386c4dab22ca6a77405492d4395e6b81

I don't quite understand what setting IsDirectBinding to true supposed to accomplish (and when it actually changes something: which would only be if it ran into user types); there are no comments and no tests either.

We should look into this and see if it's really needed, and either remove it, or add tests + comments.

**Comment by filipnavara** [comment]
Here's an excerpt from the [original bug report](https://bugzilla.novell.com/show_bug.cgi?id=670844) that it was supposed to fix:

> Whats going on is Animator creates a proxy object, that we cannot differentiate from the SharedContentView object (handles differ, but [self class] is identical) and we presume that this object is not a direct binding, and direct the call the NSView, but since the Animator proxy isn't really a SharedContentView, the call to AddSubview crashes when trying to access internal members it thinks exist on the type.
> 
> We can work around this by annotating any method which returns these type of proxys with an [return: Proxy] attribute, and setting IsDirectBinding to true in the wrapper, this will ensure we go to the proxy implementation which is responsible for connecting the appropriate plumbing.
> 
> I'm not 100% happy with the approach, but I cannot think of anything better at this time.

Not sure how long the Bugzilla link will work, so attaching the test project here for reference:
[AnimatorAddSubview.zip](https://github.com/xamarin/xamarin-macios/files/2675141/AnimatorAddSubview.zip)

**Comment by spouliot** [comment]
Nice detective work! We don't go back to Novell Bugzilla very often these days :)

**Comment by fiam** [comment]
This seems to have regressed lately. I'm experiencing this problem on Xamarin.Mac 5.16.1.24. Calling `fooViewObject.Animator` ends up calling into the `FooView(IntPtr handle)` constructor with the proxy, which obviously ends up crashing as soon as a some method that the animation proxy doesn't support ends up being called.

Visual Studio Community 2019 for Mac
Version 8.3.10 (build 2)
Installation UUID: 6bff98f4-31ae-40c7-a2b2-5c17cd7b11f9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)
	Package version: 604000208

Mono Framework MDK
Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

**Comment by rolfbjarne** [comment]
The test case that was previously attached seems to continue to work fine (once converted to Unified: 
[AnimatorAddSubview-f003518.zip](https://github.com/xamarin/xamarin-macios/files/3945313/AnimatorAddSubview-f003518.zip)).

@fiam You're likely running into a different problem, so please file a new issue with a test project we can use to reproduce the issue and we'll have a look.

**Comment by rolfbjarne** [comment]
NSObject.SetAsProxy was removed here: d8ee4d202e32f4bb407ddf2851bd978ddbc5152b
