### ISSUE TITLE
[linker] OpenTK not fully stripped away

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#5275]
### Steps to Reproduce

1. Open the attached sample.
2. Build for device.
3. Open the `.app`, search for the OpenTK dll and open it in VS for Mac's assembly browser (drag and drop).

### Expected Behavior

Since we're only calling `Color` we shouldn't have all the junk that's in this screenshot:

<img width="351" alt="screenshot 2018-12-13 18 19 22" src="https://user-images.githubusercontent.com/7839202/49973563-a3081200-ff03-11e8-93f2-3c4a7454b3b9.png">

*Note: Xamarin.iOS.dll also has a bunch of things that should probably have been linked away because of OpenTK.*

### Actual Behavior

Many things aren't linked away.

### Environment

https://gist.github.com/VincentDondain/390f1d6f63fefeabfc9d8c2adbfde397

### Build Logs

https://gist.github.com/VincentDondain/c42db086881155d6f2e865bef7bb95a9

### Example Project (If Possible)

[LinkerTest.zip](https://github.com/xamarin/xamarin-macios/files/2678058/LinkerTest.zip)

**Comment by rolfbjarne** [comment]
This is not an issue anymore in .NET, where we don't ship OpenTK-1.0.dll.
