### ISSUE TITLE
[xharness] Executing a make inside xamain-macios/tests is throwing an exception with latest master build

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#5291]
### Steps to Reproduce

1. Update System to xamarin-ios master, xamarin.ios-12.7.0.5.pkg
2. Execute make inside xamarin-macios/tests

### Expected Behavior
It will run successfully and generate all test projects

### Actual Behavior
Fails to generate  test projects with file not found exception,
https://gist.github.com/GouriKumari/a11b9c63c82db75f7b1cda77a03a2847#file-gistfile1-txt-L28

### Environment

Test Env: 
XI: xamarin.ios-12.7.0.5.pkg , master 

This issue is not occuring with xamarin.ios 12.7.0.3, master build. 

### Example Project (If Possible)

xamarin-macios/tests/make

**Comment by rolfbjarne** [comment]
@mandel-macaque can you have a look at this?

**Comment by GouriKumari** [comment]
This blocks all XI bcl test and tvOS test runs on device for master builds.

**Comment by mandel-macaque** [comment]
@GouriKumari @rolfbjarne I'll take a look today, early tom.

**Comment by mandel-macaque** [comment]
FYI This is in progress

**Comment by GouriKumari** [comment]
This issue is no longer reproducible with XI 12.7.0.117.pkg. [Tests](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=250019&_a=release-environment-extension&environmentId=1078269&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab) are generated correctly and executed with master build. 
Issue is reproducibe with  : XI 12.7.0.108.pkg 
Not reproducible: XI 12.7.0.117.pkg, hence closing this issue.
