### ISSUE TITLE
[XM] Can't run app if application bundle is signed and installer package is signed

### ISSUE THREAD

**Issue by albilaga** [xamarin/xamarin-macios#5330]
### Steps to Reproduce

1.  Archive app
2. Sign and distribute using App Store/Mac Installer Package
3. Run the pkg file

### Expected Behavior
Apps in /Applications running
### Actual Behavior
Apps in /Applications always force close after run it

Notes:
Apps without signed run well
### Environment
```
=== Visual Studio Community 2017 for Mac ===

Version 7.7.2 (build 21)
Installation UUID: 604c8381-2bd0-4f31-8ed6-4fbf83a66fd0
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.0
	2.1.2
SDK: /usr/local/share/dotnet/sdk/2.2.100/Sdks
SDK Versions:
	2.2.100
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.1.4.2 (Visual Studio Community)
Android SDK: /Users/albilaga/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Java SDK: /Users/albilaga/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: 06ceaea1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

=== Xamarin.iOS ===

Version: 12.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 707020021
Git revision: f1fea53df9eb0bb5890a9563c0d7ea7b03922144
Build date: 2018-12-14 18:37:35+00
Build branch: release-7.7
Xamarin extensions: 9c5cea335e6a9ce4ccfde31c4aa06c25a3576085

=== Operating System ===

Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Android Signature Tool 2.1.2
MFractor 3.6.9
Mutatio 1.0.2

```

**Comment by chamons** [comment]
I believe "App Store/Mac Installer Package" is the issue.

If you choose the app store Apple needs to process it else it is considered invalid signed and crashes on launch. 

Try another signing configuration to verify, but this does not surprise me.

**Comment by albilaga** [comment]
The problem is with signing I think. I am using the same configuration for archive (Mac Application) but one with sign the bundle and one without it. The one without it running fine. The one with signed bundle with force close directly at first launch

**Comment by albilaga** [comment]
If I try to run directly from VS for Mac it showing "Cannot execute /Users/.../App.exe" and I don't know why it generated .exe at that time. If I try to deploy without signing app it works fine.

**Comment by chamons** [comment]
I currently do not believe this is a bug without more information. In general getting code signing setup correctly can be difficult. I'd suggest you read the associated documentation:

https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/publishing-to-the-app-store/signing

https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html

https://developer.apple.com/library/archive/technotes/tn2206/_index.html

You could use:

```
codesign --verify --deep --strict --verbose=2 Foo.app
```

to see why your app is failing code signing

or launch it from the command line:

```
./Foo.app/Contents/MacOS/Foo
```

or check the crash report for more details.

**Comment by albilaga** [comment]
I think the problem is not code signing but custom entitlements in signing mode. If i leave custom entitlements with blank it work fine. But if I use entitlement.plist in custom entitlements it will force close when launch.

the output from `codesign --verify --deep --strict --verbose=2 Foo.app` is
```
Foo.app: valid on disk
Foo.app: satisfies its Designated Requirement
```
and if I try `./Foo.app/Contents/MacOS/Foo` it will showing
`terminated by signal SIGKILL (Forced quit)`

Here I also attach crash log 

> Process:               Foo [31360]
> Path:                  /Users/USER/Documents/*/Foo.app/Contents/MacOS/Foo
> Identifier:            Foo
> Version:               ???
> Code Type:             X86-64 (Native)
> Parent Process:        fish [31251]
> Responsible:           Foo [31360]
> User ID:               501
> 
> Date/Time:             2019-01-04 23:29:36.992 +0700
> OS Version:            Mac OS X 10.14.2 (18C54)
> Report Version:        12
> Anonymous UUID:        70B62E4D-2545-5EB7-D1DB-FA35D2FAD32F
> 
> 
> Time Awake Since Boot: 130000 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        Unknown
> 
> Exception Type:        EXC_CRASH (Code Signature Invalid)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Reason:    Namespace CODESIGNING, Code 0x1
> 
> kernel messages:
> 
> Backtrace not available
> 
> Unknown thread crashed with X86 Thread State (64-bit):
>   rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
>   rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffedfcea9f0
>    r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
>   r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
>   rip: 0x0000000115992000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
>   
> Logical CPU:     0
> Error Code:      0x00000000
> Trap Number:     0
> 
> 
> Binary images description not available
> 
> 
> External Modification Summary:
>   Calls made by other processes targeting this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by this process:
>     task_for_pid: 0
>     thread_create: 0
>     thread_set_state: 0
>   Calls made by all processes on this machine:
>     task_for_pid: 119624
>     thread_create: 0
>     thread_set_state: 0

**Comment by albilaga** [comment]
I am also checking inside Foo.App. For now I replace the failed Foo. (with custom entitlements) inside MacOs directory with the success Foo (without custom entitlements) and it works fine. But I am still wondering why a custom entitlements difference creating different file in MacOs directory inside Foo.App?

**Comment by chamons** [comment]
I just tested a simple XM app with custom entitlements, with the Mac-developer ID and a valid provisioning profile and it worked.

I understand getting code signing is frustrating, but consider reading the documentation listed.

**Comment by albilaga** [comment]
What Mac Developer and provisioning profile do you use? Is that developer ID or App Store? because I am using App store distribution and it not working for me

**Comment by albilaga** [comment]
So using Xamarin.Mac we can't use App Store signing configuration? Or my mistake in setting up signing configuration? Because I am already trying different signing configuration (but still same App Store because our app needed to upload to app store) and still got the same error

**Comment by albilaga** [comment]
Looks like you are correct @chamons . It is the problem with code signing. I also try in xcode to sign test app using my certificate (manual) and it also directly force closed. I only can successfully generate if I am using automatically manage signing which is not possible in VS4Mac. I also try archive in VS4Mac then sign using XCode with automatically manage signing but got error "RSync Failed" Thanks for your time. I will try looking for another solution

**Comment by jstedfast** [comment]
You cannot use App Store signing configuration because that won't run on your local machine.

App Store signing is only used by Apple. What happens is that they re-codesign it with their key and that's when it becomes valid for you to run it on your machine. Until then, it's not valid.

**Comment by albilaga** [comment]
I see @jstedfast but I got response from AppStore saying my app force close when launch. Then I try to compare the app built with XCode. With XCode when I try to sign using certificate without provisioning profile or automatically manage signing, I can run the app directly from the build or app from the installer generated. But if I use manual signing with provisioning profile it will showing the same error like above. That is why I think the problem is in this https://github.com/xamarin/xamarin-macios/issues/5061 because in VS for mac is not possible to sign app without provisioning profile

**Comment by PopAndCode** [comment]
I'm experiencing a similar issue. When i signed my app with a "Mac App Distribution" certificate in release mode, i can not launch my app (foo.app) neither my .pkg in local. @jstedfast if i understand correctly, it's an expected behavior or i'm missing something ?

**Comment by jstedfast** [comment]
I haven't worked on this since 2019, so my memory is foggy, but yes, I believe that is expected behavior.
