### ISSUE TITLE
iOS HttpClient GetAsync hangs indefinitely

### ISSUE THREAD

**Issue by jonathanantoine** [xamarin/xamarin-macios#5333]
### Steps to Reproduce

In certain case when the app is suspended, thread / http requests are no more created and hangs forever.

Steps to reproduce the issue :
1. Launch the app.
2. Wait for this log to be displayed 'Batch X created'.
3. Wait 1 second.
4. Put the app in background ( press the home button for example).
5. Wait 10 seconds and put the app in foreground.
6. Notice that no more thread / requests are made.

(I sometimes have to do it several times for the bug to happen).

### Expected Behavior
Threads and requests are created / send. 
### Actual Behavior
No more threads are created and no more http requests are send.
Example of error log : [logs.zip](https://github.com/xamarin/Xamarin.Forms/files/2714686/logs.zip)

### Environment

```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.7.2 (build 21)
Installation UUID: 37cc8c40-d076-4974-8bf8-344f707f4364
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.0
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.2.101/Sdks
SDK Versions:
	2.2.101
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 12.2.1.12 (Visual Studio Enterprise)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

=== Xamarin.Android ===

Version: 9.1.4.2 (Visual Studio Enterprise)
Android SDK: /Users/jonathanantoine/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.2

Java SDK: /Users/jonathanantoine/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: 06ceaea1

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 707020021
Git revision: f1fea53df9eb0bb5890a9563c0d7ea7b03922144
Build date: 2018-12-14 18:37:35+00
Build branch: release-7.7
Xamarin extensions: 9c5cea335e6a9ce4ccfde31c4aa06c25a3576085

=== Operating System ===

Mac OS X 10.14.1
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Fri Oct  5 19:41:49 PDT 2018
    root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.31
NuGet Package Management Extensions 0.13


```

### Build Logs

I have none.

### Example Project (If Possible)

[ReproTaskPoolNotWorking.zip](https://github.com/xamarin/xamarin-macios/files/2714717/ReproTaskPoolNotWorking.zip)

The code is pretty simple :
` public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.

            ThreadPool.SetMinThreads(70, 70);
            ThreadPool.SetMaxThreads(70, 70);

            Task.Run(() => StartTheLoopAsync().ConfigureAwait(false));
        }

        private const int howMuchLoop = 60;
        private long _taskCounter = 1;
        private async Task StartTheLoopAsync()
        {
            while (true)
            {
                Debug.WriteLine($"[{_taskCounter:D4}]Will be starting batch {_taskCounter}");

                var toWait = new List<Task<HttpResponseMessage>>(howMuchLoop);
                for (int i = 0; i < howMuchLoop; i++)
                {
                    toWait.Add(Task.Factory.StartNew(
                    () => { return new HttpResponseMessage() { StatusCode = HttpStatusCode.OK }; }
                    , CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default));

                    var httpClient = new HttpClient
                    {
                        Timeout = TimeSpan.FromSeconds(10)
                    };
                    toWait.Add(httpClient.GetAsync(
            "https://url.com?q=dede" + Guid.NewGuid().ToString("N").Substring(0, 5)));

                }

                Debug.WriteLine($"[{_taskCounter:D4}] Batch {_taskCounter} created");

                try
                {
                    await Task.WhenAll(toWait);
                }
                catch (Exception)
                {
                    // ignore
                }
                var howMuchErrors = toWait.Count(t =>
                {
                    try
                    {
                        return t.Exception != null || !t.Result.IsSuccessStatusCode;
                    }
                    catch (Exception)
                    {
                        return true;
                    }
                }) ;

                toWait.Clear();
                Debug.WriteLine($"[{_taskCounter:D4}]batch {_taskCounter} has now been executed : {howMuchErrors} errors.");

                _taskCounter++;
                await Task.Delay(1000).ConfigureAwait(false);
            }
        }`

**Comment by jonathanantoine** [comment]
Hello again,

It seems related to a change in ios12 socket management (interesting reading here : https://github.com/AFNetworking/AFNetworking/issues/4279#issuecomment-447108981) and I managed to create a working "sample" by using background task execution. For those interested it's here : [Workaround.zip](https://github.com/xamarin/xamarin-macios/files/2714886/Workaround.zip).

**Comment by mandel-macaque** [comment]
@jonathanantoine I have two PRs that will fix what you are experiencing, once we get a +1 from QA I'll merge and will close the issue.

Really appreciate the help and the PR you proposed, we wanted to make a more complete fix that will always ensure that the state machine from the Task worked in a deterministic manner. But nevertheless I would have never found the issue without your help, thanks again.

**Comment by jonathanantoine** [comment]
Thanks a lot @mandel-macaque for the follow up. I didn't find the time to fix my PR (and I am sorry for this).

Regards.

**Comment by mandel-macaque** [comment]
Closing after https://github.com/xamarin/xamarin-macios/pull/5463 was merged.
