### ISSUE TITLE
Calling ARConfiguration.SupportedVideoFormats crash

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#5347]
### Steps to Reproduce

1.  call `ARConfiguration.SupportedVideoFormats`

### Expected Behavior

no crash

### Actual Behavior

Native exception `NSInvalidArgumentException Reason: Supported video formats should be called on individual configuration class` leading to crash

**Comment by yevgeniy-seleznev** [comment]
Thanks for the quick fix @spouliot
