### ISSUE TITLE
IDE (VS4Mac at least) does not see assets added from Xcode

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#5359]
See https://github.com/xamarin/xamarin-macios/issues/5339#issuecomment-452442169 for details.

This issue is to track the addin (VS4Mac).

The original issue will track the (ms)build missing logic.

> VS bug [#762465](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/762465)

**Comment by spouliot** [comment]
@emaf can you check if the same issue exists in XVS ? thanks!

**Comment by emaf** [comment]
@spouliot thanks for the heads up. Does this happen with any Asset type or just with Color Set assets?

**Comment by spouliot** [comment]
@emaf based on comments (in the original issue) I think the synchronization does not work at all - but I only confirmed the color case.

FWIW I think we should consider this directory as a file, i.e.
* it's either included in the project (.csproj) or not;
* anything that changes under the directory requires `actool` to be run again (since we do not know the exact, or future, logic of Apple to process it's content)
