### ISSUE TITLE
Some classes from 'Metal Performance Shaders' framework are missed

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#5362]
I am porting [this sample](https://developer.apple.com/documentation/metalperformanceshaders/metal_for_accelerating_ray_tracing) and found that some classes are missed. 

### Steps to Reproduce

1. Create a new XI project
2. Add 2 new fields to the view controller
```
private MPSTriangleAccelerationStructure accelerationStructure;
private MPSRayIntersector intersector;
```

### Expected Behavior
This classes are existed

### Actual Behavior
There are no these classes 

### Environment

1. VSfM
https://gist.github.com/mykyta-bondarenko-gl/5e81c09f268cc679aae0cf5e1cc8ab8d

**Comment by spouliot** [comment]
assigned to @dalexsoto in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/758633

Missing API are listed by [xtro](http://xamarin-storage/jenkins/xamarin-macios/master/a42b6b7237003118e1e8f2416e8c5ded04ec8251/313/jenkins-results/tests/Xtro/562/xtro-20190109_024840/MetalPerformanceShaders.ignore.html).

**Comment by dalexsoto** [comment]
yes, current WIP thanks for assigning it to me.

**Comment by dalexsoto** [comment]
@mykyta-bondarenko-gl the APIs you need should be in the latest build of https://github.com/xamarin/xamarin-macios/commits/xcode10.2 here are the latest packages as of today

* 
https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10.2/5fd44acc9a722668061161aca9fc4f56e3365bc3/25/package/xamarin.ios-12.4.0.29.pkg
* 
https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode10.2/5fd44acc9a722668061161aca9fc4f56e3365bc3/25/package/xamarin.mac-5.4.0.29.pkg

feel free to reopen or file a new issue if you encounter anything else!

Thank you for your report!
