### ISSUE TITLE
[interpreter]AudioGenerator sample fails to launch with System.ArrayTypeMismatchException

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#5363]
### Steps to Reproduce

1.  Install Xamarin.iOS build from master branch, 12.7.0.30 (master): aa77c673c)  or latest Version: 12.7.0.35 (Visual Studio Enterprise), Hash: 327c0a8d
2. Build and run AudioGenerator sample on a 64 bit device in debug mode.

### Expected Behavior
App builds and launches successfully
### Actual Behavior
App builds successfully but fail to launch with a System.ArrayTypeMismatch Exception. 
Unhandled Exception:
System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
### Environment

```
### Environment ###
Operating System: Mac OS X 10.14.1
Mono version: 5.18.0.225 (bac9fc1f889)  (2018-12-21 11:33:29 -05:00)
XA version: 
XI version: 12.7.0.35 (master): 327c0a8d) 
XM version: 5.2.1.12 (65ec520f)  (2018-12-05 12:06:09 -05:00)
XVS version: 
XS version: 7.8.0.1487 (0311f28)  (2018-12-19 13:37:11 -05:00)
[Device] Name: XQAiPhoneXb, Identifier: e978c67571aa0652bdb4ad6b8338ec46633e07ef
```

### Build Logs

Build Log: https://gist.github.com/GouriKumari/7a3cc9409fe1cf257e1bf62456ba1bf2
Exception log: http://xqa.blob.core.windows.net/gist/report-98e83226406b46d891d1ff99b5f0087b.txt

### Example Project (If Possible)

https://github.com/xamarin/ios-samples/tree/master/AudioGenerator

###Additional info:
App launches if interpreter is not enabled.

**Comment by spouliot** [comment]
Not obvious from the stack trace but the exception occurs on
https://github.com/xamarin/ios-samples/blob/master/AudioGenerator/AppDelegate.cs#L57

```
            var buffers = new AudioQueueBuffer* [numBuffers];
            for (int i = 0; i < numBuffers; i++)
            {
                queue.AllocateBuffer(bufferByteSize, out buffers[i]); // !!! HERE !!!
                GenerateTone(buffers[i]);
                queue.EnqueueBuffer(buffers[i], null);
            }
```

note the use of `unsafe` code - it's likely not a common pattern

**Comment by GouriKumari** [comment]
Issue is seen with Release configuration as well. 

Crash Log with test environment: http://xqa.blob.core.windows.net/gist/report-ca9a263784d1403796659ad60c42cfb9.txt
