### ISSUE TITLE
[interpreter]Extension samples fail to build with an error " Not all assemblies for Xamarin.Sdk have link tasks"

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#5365]
### Steps to Reproduce

1. Install Xamarin.iOS build from master branch, 12.7.0.30 (master): aa77c67) or latest Version: 12.7.0.35 (Visual Studio Enterprise), Hash: 327c0a8
2. Build Extension Sample, eg: Lister, ImageInverter, PhotoFilter 

### Expected Behavior
App builds successfully
### Actual Behavior
App fails to build with error, error MT0099 : Internal error : Not all assemblies for Xamarin.Sdk have link tasks. Please file a bug report with a test case (https://github.com/xamarin/xamarin-macios/issues/new).
    2 Warning(s)
    1 Error(s)
### Environment

```
### Environment ###
Operating System: Mac OS X 10.14.3
Bot Name: XQA-XI-Mojave-1
Mono version: 5.18.0.225 (bac9fc1f889)  (2018-12-21 11:33:29 -05:00)
XA version: 9.2.99.2 (HEAD/d3c55ecb) 
XI version: 12.7.0.30 (master): aa77c673c) 
XM version: 5.7.0.30 (master: aa77c673c)  (2019-01-04 18:12:40 -05:00)
XVS version: 
XS version: 7.7.3.35 (2790c07)  (2018-12-18 16:47:29 -05:00)
```

### Build Logs
Build Log:
http://xqa.blob.core.windows.net/gist/report-6b0c9e5ebe424bd7b5d5f259549e29bf.txt
http://xqa.blob.core.windows.net/gist/report-6f0faa91e7f44f7b821378c1ff95559d.txt
http://xqa.blob.core.windows.net/gist/report-ac5cb55f4dbb4b22acd7c7617f2ac182.txt
http://xqa.blob.core.windows.net/gist/report-de83d1acbe6645bf8ae2ca39e382ef61.txt
http://xqa.blob.core.windows.net/gist/report-ef60a8998dbb4249a84b70ef30bcd8ac.txt
http://xqa.blob.core.windows.net/gist/report-6bb03917e4574cbc91552f8038c06eea.txt
http://xqa.blob.core.windows.net/gist/report-9ce35f84ade347fd84a2b8289526a77c.txt
http://xqa.blob.core.windows.net/gist/report-0daa0ee66c0c47feb31f1991f31a7be2.txt

### Example Project (If Possible)

https://github.com/xamarin/ios-samples/tree/master/ios8/PhotoFilter
https://github.com/xamarin/ios-samples/tree/master/ios8/ExtensionsDemo
https://github.com/xamarin/ios-samples/tree/master/ios8/ImageInverter
https://github.com/xamarin/ios-samples/tree/master/ios8/KannadaKeyboard
https://github.com/xamarin/ios-samples/tree/master/ios8/Share

**Comment by spouliot** [comment]
c.c. @rolfbjarne since this a build issue
