### ISSUE TITLE
Incomplete dispatch bindings

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#5368]
At least `dispatch_block_create_with_qos_class` is missing.

Ref: https://xamarinhq.slack.com/archives/C03CCJHCF/p1547066638055500

For some reason the xtro tests aren't reporting these functions as missing either.

**Comment by spouliot** [comment]
wrt xtro I think it's because most (all?) of `dispatch_` API are in `libc` and that was ignored since we only bind a few of those API.

**Comment by spouliot** [comment]
c9e424c9abce52dd6cfa8a911f712309fdd5d092 added the mentioned API

**Comment by rolfbjarne** [comment]
I think this can be considered done, as far as I can remember I bound every missing dispatch API.
