### ISSUE TITLE
[interpreter]Debugging sample crashes when interpreter is enabled

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#5381]
### Steps to Reproduce

1. Install Xamarin.iOS master, Version: 12.7.0.35 (Visual Studio Enterprise) 327c0a8d
2.  Set a breakpoint against Line7 in ClassesUnderTest/SimpleBreakpoints.cs
2. Build and deploy cross platform debugging app on device with interpreter enabled for iOS.Debugging.
3. GoTo SimpleBreakPoint and click Start

### Expected Behavior
Breakpoint should get hit and user must able to debug app successfully.
### Actual Behavior
Connection to the debugger is lost and app crashes with an error, 2019-01-11 10:27:16.744 XiOSDebugging[2297:333230] error: * Assertion at /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mono/mini/debugger-engine.c:359, condition `ji' not met

### Environment
```
=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.8 Preview (7.8 build 1487)
Installation UUID: fe2e3011-6fdf-476f-9a39-d7d6b435ddd1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.1 (d16-0 / 2e9867a4)

	Package version: 518000225

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.0.225 (2018-08/bac9fc1f889) (64-bit)
	Package version: 518000225

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.2
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Version: 2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.12 (Visual Studio Enterprise)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

=== Xamarin.iOS ===

Version: 12.7.0.35 (Visual Studio Enterprise)
Hash: 327c0a8d
Branch: master
Build date: 2019-01-08 23:25:33-0800

=== Xamarin.Android ===

Not Installed

=== Microsoft Mobile OpenJDK ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.8.1.0
Hash: 06ceaea1

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 708001487
Git revision: 0311f28ad5352750c02c4854a36587e47f4806be
Build date: 2018-12-19 18:37:11+00
Build branch: release-7.8
Xamarin extensions: 1de2700808f1ef0e06199d64e043bc2ae523d700

=== Operating System ===

Mac OS X 10.14.1
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Fri Oct  5 19:41:49 PDT 2018
    root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
```
### Build Logs

Build Log: https://gist.github.com/GouriKumari/26eafacbd0e746e405b0807adc71efe0
Application Output: https://gist.github.com/GouriKumari/edfe0fde10ce6a745fa0c25644e17f89
Crash Log: https://gist.github.com/GouriKumari/8037dc279a34dfcf408e1e728743f5a7

### Example Project (If Possible)
https://www.dropbox.com/s/zabk8nwa3bvjzsr/CrossPlatformDebugging.zip?dl=0

## Additional Info:
This works when interpreter is disabled.

**Comment by spouliot** [comment]
Side note: the debugger (and breakpoints) works in other conditions (I've been using them)

**Comment by GouriKumari** [comment]
I was testing the various scenarios:
Failed Scenarios include:
Simple BreakPoints
MultiThreaded BreakPoints
Shared BreakPoints
Delegate Breakpoints
PCL Breakpoints
Regular Exception
PCL in PCL Nested Library breakpoints
PCL in iOS Class Library Nested Class Libraries
Net Standard in NetStandard Nested Libraries
NetStandard in iOS Class Libraries in NetStandard Nested Libraries
