### ISSUE TITLE
AVCaptureSession not working on Xam.Mac

### ISSUE THREAD

**Issue by roesterr** [xamarin/xamarin-macios#5390]
### Steps to Reproduce

1. Build and run attached test project on MacOS "avcapturesessiontest" on a computer that has a video source like a USB webcam or iSight cam.
2. The ViewController class then
2b. Asks permission to access camera and microphone for input.
2c. Creates and AVCaptureSession object
2d. Finds default video input and creates input device object
2e. Adds input device to AVCaptureSession
2f. Adds output for live preview to AVCaptureSession with sample buffer output delegate
2g. Creates AV PreviewLayer from AVCaptureSession
2h. Adds live preview layer as layer or sublayer of ViewController's NSView object.
2g. AVCaptureSession.StartRunning is called.
3. Nothing displays in preview layer, and no sample buffers are output even though current state of AVCaptureSession.Running is true.

### Expected Behavior
Upon application launch, live camera/video input should be displayed in View of ViewController.
Sample Buffer should be ouput to delegate with every frame of video input.

### Actual Behavior
Nothing displays in preview layer, and no sample buffers are output even though current state of AVCaptureSession.Running is true.

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.7.2 (build 21)
Installation UUID: de744c9b-b199-48dd-bd61-8ec92c74e63c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.2
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Version: 2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Not Installed

=== Android Device Manager ===

Version: 7.7.1.0
Hash: 06ceaea1

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

=== Xamarin.iOS ===

Version: 12.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

=== Build Information ===

Release ID: 707020021
Git revision: f1fea53df9eb0bb5890a9563c0d7ea7b03922144
Build date: 2018-12-14 18:37:35+00
Build branch: release-7.7
Xamarin extensions: 9c5cea335e6a9ce4ccfde31c4aa06c25a3576085

=== Operating System ===

Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

### Build Logs

Building solution avcapturesessiontest (Debug|x86)
Build started 1/11/2019 8:02:21 PM.
__________________________________________________
Project "/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/avcapturesessiontest.csproj" (Build target(s)):

Target _BeforeCoreCompileImageAssets:
    Directory "obj/x86/Debug/actool" doesn't exist. Skipping.
Target _CoreCompileImageAssets:
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/actool execution started with arguments: --errors --warnings --notices --output-format xml1 --output-partial-info-plist /Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/actool/partial-info.plist --app-icon AppIcon --minimum-deployment-target 10.14 --platform macosx --compile /Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/actool/bundle /Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/actool/cloned-assets/Assets.xcassets
Target _CoreCompileInterfaceDefinitions:
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 10.14 --sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk --compilation-directory /Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/ibtool /Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/Main.storyboard
      BundleResources Output:
        obj/x86/Debug/ibtool/Main.storyboardc/Info.plist
        obj/x86/Debug/ibtool/Main.storyboardc/MainMenu.nib
        obj/x86/Debug/ibtool/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib
        obj/x86/Debug/ibtool/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib
      OutputManifests Output:
        obj/x86/Debug/ibtool-manifests/Main.storyboardc
Target _CoreCompileColladaAssets:
  Skipping target "_CoreCompileColladaAssets" because it has no inputs.
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target CoreCompile:
    /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Roslyn/csc.exe /noconfig /nowarn:1701,1702,2008 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /define:__UNIFIED__;__MACOS__;DEBUG /errorendlocation /preferreduilang:en-US /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/mscorlib.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/System.Core.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/System.dll /reference:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Xamarin.Mac.dll /debug+ /debug:portable /optimize- /out:"obj/x86/Debug/AVCaptureSession Test.exe" /target:exe /utf8output Main.cs AppDelegate.cs ViewController.cs ViewController.designer.cs "/var/folders/hk/h7k72k7d655dh4hrxb80g9jc0000gn/T/Xamarin.Mac,Version=v2.0.AssemblyAttributes.cs"
    ViewController.cs(27,13,27,37): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
    ViewController.cs(28,13,28,37): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
    ViewController.cs(174,18,174,47): warning CS0219: The variable 'bThisLineIsJustForABreakPoint' is assigned but its value is never used
Done building target "CoreCompile" in project "avcapturesessiontest.csproj".
Target CopyFilesToOutputDirectory:
    Copying file from "/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/AVCaptureSession Test.exe" to "/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.exe".
    avcapturesessiontest -> /Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.exe
    Copying file from "/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/AVCaptureSession Test.pdb" to "/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.pdb".
Target _DetectSigningIdentity:
    Detected signing identity:
      Bundle Id: com.companyname.avcapturesessiontest
      App Id: com.companyname.avcapturesessiontest
Target _CopyContentToBundle:
    Creating directory '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.app/Contents/Resources'
    Copying file from '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/actool/bundle/AppIcon.icns' to '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.app/Contents/Resources/AppIcon.icns'
    Copying file from '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/actool/bundle/Assets.car' to '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.app/Contents/Resources/Assets.car'
    Creating directory '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.app/Contents/Resources/Main.storyboardc'
    Copying file from '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/ibtool/Main.storyboardc/Info.plist' to '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.app/Contents/Resources/Main.storyboardc/Info.plist'
    Copying file from '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/ibtool/Main.storyboardc/MainMenu.nib' to '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.app/Contents/Resources/Main.storyboardc/MainMenu.nib'
    Copying file from '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/ibtool/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib' to '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.app/Contents/Resources/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib'
    Copying file from '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/ibtool/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib' to '/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/bin/Debug/AVCaptureSession Test.app/Contents/Resources/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib'
Target _CompileToNative:
    /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp @/Users/ro/Desktop/avcapturesessiontest/avcapturesessiontest/obj/x86/Debug/response-file.rsp 

Done building project "avcapturesessiontest.csproj".

Build succeeded.

ViewController.cs(27,13,27,37): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
ViewController.cs(28,13,28,37): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
ViewController.cs(174,18,174,47): warning CS0219: The variable 'bThisLineIsJustForABreakPoint' is assigned but its value is never used
    3 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.98

========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Build: 0 errors, 3 warnings

### Example Project (If Possible)

[avcapturesessiontest.zip](https://github.com/xamarin/xamarin-macios/files/2751552/avcapturesessiontest.zip)

**Comment by spouliot** [comment]
The attached sample works for me. I hit the breakpoint (in the delegate) and removing it shows video of me in the bottom left corner.

It might be timing sensitive since you're calling async code in your .ctor (see compiler warnings) ?
Or your app window is too small and the video is outside the bounds ?

**Comment by roesterr** [comment]
There were two issues... I've confirmed there was a timing issue with the resource access permissions for video and audio input executing prior to creation of the capture session. Also one of the USB video input devices did not work as an input while others did. I'm investigating further to see if I need to specify framerate or other parameters to get the capture session to display a preview. Please consider the initial issue for this post resolved-OE.

**Comment by spouliot** [comment]
Thanks for following up!
