### ISSUE TITLE
Request: MacOS Remote USB - please bring it back.

### ISSUE THREAD

**Issue by tlhintoq** [xamarin/xamarin-macios#5442]
###Request###
Please re-active the MacOS remote debugging feature from 2016.  It worked great then just disappeared without a final release.

This feature got a standing ovation at Evolve 2016. It was around for about a week, then pulled.
There was a survey on Twitter that MANY people didn't know about. Then ... well .... hello ... nothing.

The thread for it on Xamarin Forums still has people wanting to know when this will be available again.
https://forums.xamarin.com/discussion/comment/311153#Comment_311153

Please bring this back - when it was there it worked great.
### Steps to Reproduce

1. Nothing to reproduce
2. 
3. 

### Expected Behavior
To remotely use an iOS device connected to the Windows PC, as if it were connected directly to the Macintosh build host that is **commonly in a rack someplace other than the developer desk**.

### Actual Behavior
Worked great at Evolve 2016 - then disappeared.

### Environment
Windows has the iOS device connected by USB.
Mac sees the device as if it were connected directly to the mac.

### Build Logs
Nothing to log

### Example Project (If Possible)
No example required

Related to #[1360 ](https://github.com/xamarin/Xamarin.Forms/issues/1360) where it was simply closed as 'wrong area' but the closer didn't mention what would be the right area.  @johnhair suggested the iOS area.

> VS bug [#772684](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/772684)

**Comment by spouliot** [comment]
@tlhintoq GitHub issues are _meant_ for the open sourced SDK [1]. The best place for IDE (or non-open source) feature requests is Visual Studio Community https://developercommunity.visualstudio.com/spaces/8/index.html

[1] we can sync the issue to our internal bug tracker so the XVS (Windows side team will see the issue) but that does not have the exact same visibility.

**Comment by tlhintoq** [comment]
Thanks for the response.  What do _you_ think is the **best** thing to do with the request so it gets the right visibility from the team and maybe some love with respect to it being worked on?

**Comment by spouliot** [comment]
@tlhintoq in both cases (here or Visual Studio Community) there will be an internal issue created, so "team wise" it's identical (same end result).

You might get more _external_ visibility (e.g. more community comments) in [Visual Studio Community](https://developercommunity.visualstudio.com/spaces/8/index.html) since this is where the IDE (both Windows and Mac) redirect their users for feedback.

**Comment by joj** [comment]
Hi! Please add this as a suggestion in Developer Community (where @spouliot pointed. The feature was cut because it required a lot of setup from the user and we could never get it to the quality level we expect from these features. We are thinking of and developing alternative ways of solving the same issue, and more information should be publicly available soon. Thanks! J

**Comment by tlhintoq** [comment]
So cut it altogether with nothing to replace it.  Rather than tell users _"Some users on less powerful systems may see some sluggishness"._

> The feature was cut because it required a lot of setup from the user

And what... Now we're coding to the lowest IQ developer in their mom's basement and the professional that wasn't too stupid to set this up and get good results looses out?  How many other systems out there _require lots of setup from the user_? Ever set up IIS on your local PC to mimic your server?  Its not a single paragraph setup, but it is what it is. Saying its too much work for the user is insulting.

Honestly - back in 2016 on a medium powered machine of that era this worked well and was a way to develop against a real, honest, physical device - instead of a simulator.  **I did it for weeks before it was yanked. Without seeing any performance issues.**  

If that carries with it a performance penalty for _some_ users so be it. They can still use the simulator.  But at least they have a choice.  Maybe they use the simulator Mon-Thur and just run on the physical on Friday as a way to confirm all the earlier week.  Whatever the use-case it just seems wrong to take away known working tools and stick them in mothballs on a shelf without having a replacement to put out.
