### ISSUE TITLE
VS4Mac: unable to debug via wifi

### ISSUE THREAD

**Issue by curia-damiano** [xamarin/xamarin-macios#5448]
### Steps to Reproduce

1. Create an empty app in Visual Studio for Mac
2. Set a breakpoint in the AppDelegate.FinishedLaunching method
3. Debug via USB: the breakpoint is hit correctly
4. Debug via wifi: VS4Mac hangs with "Waiting for the debugger.... on port 32758 via Wifi"
 
### Expected Behavior
I would expect to be able to debug even via wifi

### Actual Behavior
VS4Mac hangs

### Environment
MacOSX 10.14.2, VS4Mac 7.7.3 (build 43), iOS 12.1.2

```
```

**Comment by curia-damiano** [comment]
VS4Mac info:

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.7.3 (build 43)
Installation UUID: 589a483c-43ce-47f0-952e-e7a338c0b1ac
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.1.5.1 (Visual Studio Enterprise)
Android SDK: /Users/damianocuria/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/damianocuria/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.1.0
Hash: 06ceaea1

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.13 (Visual Studio Enterprise)
Hash: a4332c90
Branch: 
Build date: 2019-01-11 13:08:10-0500

=== Xamarin.iOS ===

Version: 12.2.1.13 (Visual Studio Enterprise)
Hash: a4332c90
Branch: d15-9
Build date: 2019-01-11 13:08:09-0500

=== Build Information ===

Release ID: 707030043
Git revision: 5896ab2acba037c62271742e9e56b900c96c1d8f
Build date: 2019-01-15 21:18:33+00
Build branch: release-7.7
Xamarin extensions: e5b43ba963b7b407aa5b9f2c59018c32a709e6ab

=== Operating System ===

Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by spouliot** [comment]
I have no problem using wifi to deploy and start debugging applications.

Can you make sure your [setup](https://docs.microsoft.com/en-ca/xamarin/ios/deploy-test/wireless-deployment?tabs=macos) is correct ?
and that you are on the same wifi network ?

Also please provide the logs from VS4Mac "Application Output", they should look like mine:

```
Launched application 'com.companyname.dynloadios' on 'IPhone X' with pid 28095
2019-01-21 15:14:37.551 dynloadios[28095:2725512] Xamarin.iOS: Added IP to look for the IDE: 192.168.2.36
2019-01-21 15:14:37.551 dynloadios[28095:2725512] Xamarin.iOS: Added IP to look for the IDE: 192.168.2.35
2019-01-21 15:14:37.551 dynloadios[28095:2725512] Xamarin.iOS: Added IP to look for the IDE: 169.254.213.185
2019-01-21 15:14:37.552 dynloadios[28095:2725512] Xamarin.iOS: Added IP to look for the IDE: fe80::14b1:4d21:7756:9dfa
2019-01-21 15:14:37.552 dynloadios[28095:2725512] Xamarin.iOS: Added IP to look for the IDE: fe80::877:1ec0:8e81:8f66
2019-01-21 15:14:37.552 dynloadios[28095:2725512] Xamarin.iOS: Added IP to look for the IDE: fe80::5098:d1ff:fe06:a011
2019-01-21 15:14:37.552 dynloadios[28095:2725512] Xamarin.iOS: Added IP to look for the IDE: fe80::75b2:89c1:f21d:5df1
2019-01-21 15:14:37.552 dynloadios[28095:2725512] Xamarin.iOS: Added IP to look for the IDE: fdca:7734:c2c4:d7ed:75b2:89c1:f21d:5df1
2019-01-21 15:14:37.552 dynloadios[28095:2725512] Xamarin.iOS: Added IP to look for the IDE: fe80::8a6:50f0:7eb4:86fb
2019-01-21 15:14:37.552 dynloadios[28095:2725512] Xamarin.iOS: Added IP to look for the IDE: fe80::f6c8:1eb8:54a0:18fb
2019-01-21 15:14:37.552 dynloadios[28095:2725512] Xamarin.iOS: IDE Port: 46815 Transport: WiFi
2019-01-21 15:14:37.552 dynloadios[28095:2725512] Xamarin.iOS: Failed to connect to fe80::14b1:4d21:7756:9dfa on port 46815: No route to host
2019-01-21 15:14:37.553 dynloadios[28095:2725512] Xamarin.iOS: Failed to connect to fe80::877:1ec0:8e81:8f66 on port 46815: No route to host
2019-01-21 15:14:37.553 dynloadios[28095:2725512] Xamarin.iOS: Failed to connect to fe80::5098:d1ff:fe06:a011 on port 46815: No route to host
2019-01-21 15:14:37.553 dynloadios[28095:2725512] Xamarin.iOS: Failed to connect to fe80::75b2:89c1:f21d:5df1 on port 46815: No route to host
2019-01-21 15:14:37.553 dynloadios[28095:2725512] Xamarin.iOS: Failed to connect to fdca:7734:c2c4:d7ed:75b2:89c1:f21d:5df1 on port 46815: No route to host
2019-01-21 15:14:37.553 dynloadios[28095:2725512] Xamarin.iOS: Failed to connect to fe80::8a6:50f0:7eb4:86fb on port 46815: No route to host
2019-01-21 15:14:37.553 dynloadios[28095:2725512] Xamarin.iOS: Failed to connect to fe80::f6c8:1eb8:54a0:18fb on port 46815: No route to host
2019-01-21 15:14:37.555 dynloadios[28095:2725512] Xamarin.iOS: Established connection with the IDE (fd: 3)
2019-01-21 15:14:37.558 dynloadios[28095:2725512] Xamarin.iOS: Processing: 'start debugger: sdb'
2019-01-21 15:14:37.559 dynloadios[28095:2725476] Xamarin.iOS: Debugger loaded with custom transport (fd: 3)
2019-01-21 15:14:37.561 dynloadios[28095:2725512] Xamarin.iOS: Established connection with the IDE (fd: 4)
2019-01-21 15:14:37.565 dynloadios[28095:2725512] Xamarin.iOS: Processing: 'connect output'
2019-01-21 15:14:37.567 dynloadios[28095:2725512] Xamarin.iOS: Established connection with the IDE (fd: 5)
2019-01-21 15:14:37.570 dynloadios[28095:2725512] Xamarin.iOS: Processing: 'start profiler: no'
2019-01-21 15:14:37.570 dynloadios[28095:2725476] Xamarin.iOS: Profiler not loaded (disabled)
```

**Comment by curia-damiano** [comment]
Hi,
I have reformatted the Mac and installed XCode and VS4Mac in the latest release, stable versions.

I have added the -vvv to the build options and here is the following output:



Building Test (Debug|iPhone)
Build started 1/22/2019 5:35:42 PM.
__________________________________________________
Project "/Users/damianocuria/Desktop/Test/Test/Test.csproj" (Build target(s)):

Target _CoreCompileInterfaceDefinitions:
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 12.1 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk --compilation-directory /Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool /Users/damianocuria/Desktop/Test/Test/LaunchScreen.storyboard
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 12.1 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk --compilation-directory /Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool /Users/damianocuria/Desktop/Test/Test/Main.storyboard
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 12.1 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk --link /Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link /Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool/LaunchScreen.storyboardc /Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool/Main.storyboardc
      BundleResources Output:
        obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib
        obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/LaunchScreen.storyboardc/Info.plist
        obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib
        obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib
        obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/Main.storyboardc/Info.plist
        obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/Main.storyboardc/UIViewController-BYZ-38-t0r.nib
      OutputManifests Output:
        obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-manifests/LaunchScreen.storyboardc
        obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-manifests/Main.storyboardc
        obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-manifests/link
Target _BeforeCoreCompileImageAssets:
    Directory "obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/actool" doesn't exist. Skipping.
Target _CoreCompileImageAssets:
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/actool execution started with arguments: --errors --warnings --notices --output-format xml1 --output-partial-info-plist /Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/actool/partial-info.plist --app-icon AppIcon --compress-pngs --filter-for-device-model iPhone11,6 --filter-for-device-os-version 12.1.2 --target-device iphone --target-device ipad --minimum-deployment-target 12.1 --platform iphoneos --compile /Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/actool/bundle /Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/actool/cloned-assets/Assets.xcassets
    /Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/actool/cloned-assets/Assets.xcassets : actool warning : The app icon set "AppIcon" has an unassigned child.
Done building target "_CoreCompileImageAssets" in project "Test.csproj".
Target _CoreCompileColladaAssets:
  Skipping target "_CoreCompileColladaAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _CoreCompileSceneKitAssets:
  Skipping target "_CoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _CoreCompileTextureAtlases:
  Skipping target "_CoreCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileCoreMLModels:
    Directory "obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/coremlc" doesn't exist. Skipping.
Target _CoreOptimizePngImages:
  Skipping target "_CoreOptimizePngImages" because it has no outputs.
Target _CoreOptimizePropertyLists:
  Skipping target "_CoreOptimizePropertyLists" because it has no inputs.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because it has no inputs.
Target CoreCompile:
    /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Roslyn/csc.exe /noconfig /nowarn:2008 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /define:__IOS__;__MOBILE__;__UNIFIED__;DEBUG;ENABLE_TEST_CLOUD /errorendlocation /preferreduilang:en-US /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/mscorlib.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Core.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Xml.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Xamarin.iOS.dll /debug+ /debug:portable /optimize- /out:obj/iPhone/Debug/Test.exe /target:exe /utf8output Main.cs AppDelegate.cs ViewController.cs ViewController.designer.cs "/var/folders/71/l59pymcs07g8j1j6p0gk3_yh0000gn/T/Xamarin.iOS,Version=v1.0.AssemblyAttributes.cs"
Target CopyFilesToOutputDirectory:
    Copying file from "/Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/Test.exe" to "/Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/Test.exe".
    Test -> /Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/Test.exe
    Copying file from "/Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/Test.pdb" to "/Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/Test.pdb".
Target _DetectSigningIdentity:
    Multiple provisioning profiles match the bundle identifier; using the first match.
      1. Provisioning Profile: "iOS Team Provisioning Profile: *" (0a690e98-5865-4d35-8677-ea71de031598)
         Signing Identity: "iPhone Developer: Damiano Curia (FWV3PGBSPY)"
      2. Provisioning Profile: "DEV Provisioning Profile" (604a0d0b-a478-47ef-93fb-6e6bfa2fe3c1)
         Signing Identity: "iPhone Developer: Damiano Curia (FWV3PGBSPY)"
    Detected signing identity:
      Code Signing Key: "iPhone Developer: Damiano Curia (FWV3PGBSPY)" (BCAF299B576AC3A61202C6A408738D8EE878C849)
      Provisioning Profile: "iOS Team Provisioning Profile: *" (0a690e98-5865-4d35-8677-ea71de031598)
      Bundle Id: com.companyname.Test
      App Id: LA5247PXS2.com.companyname.Test
Target _CopyResourcesToBundle:
    Creating directory '/Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/LaunchScreen.storyboardc'
    Copying file from '/Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib' to '/Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib'
    Copying file from '/Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/LaunchScreen.storyboardc/Info.plist' to '/Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/LaunchScreen.storyboardc/Info.plist'
    Copying file from '/Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib' to '/Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib'
    Creating directory '/Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/Main.storyboardc'
    Copying file from '/Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib' to '/Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib'
    Copying file from '/Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/Main.storyboardc/Info.plist' to '/Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/Main.storyboardc/Info.plist'
    Copying file from '/Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/ibtool-link/Main.storyboardc/UIViewController-BYZ-38-t0r.nib' to '/Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/Main.storyboardc/UIViewController-BYZ-38-t0r.nib'
Target _DetectDebugNetworkConfiguration:
      DebugIPAddresses: 192.168.8.101;fe80::b4:a734:d925:f90c;fe80::74d7:24ff:fe22:3321;fe80::e347:b8e8:8064:3df2
Target _CompileAppManifest:
    Directory "bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app.dSYM" doesn't exist. Skipping.
Target _ParseExtraMtouchArgs:
      NoSymbolStrip Output: true
      NoDSymUtil Output: false
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/response-file.rsp 
    Creating "bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/mtouch.stamp" because "AlwaysCreate" was specified.
Target _CopyITunesArtwork:
  Skipping target "_CopyITunesArtwork" because it has no inputs.
Target _CopyAppExtensionsToBundle:
    Directory "bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/PlugIns/_CodeSignature" doesn't exist. Skipping.
    Directory "bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/../.dSYM" doesn't exist. Skipping.
Target _GenerateAppExtensionDebugSymbols:
    Directory "bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/../.dSYM" doesn't exist. Skipping.
Target _CollectFrameworks:
    No Frameworks directory found.
Target _GenerateFrameworkDebugSymbols:
  Skipping target "_GenerateFrameworkDebugSymbols" because it has no inputs.
Target _GenerateDebugSymbols:
    Directory "bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app.dSYM" doesn't exist. Skipping.
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -t 4 -z -o bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app.dSYM bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/Test 
    /usr/bin/mdimport bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/../ 
Target _CodesignNativeLibraries:
    Tool /usr/bin/codesign execution started with arguments: -v --force --sign BCAF299B576AC3A61202C6A408738D8EE878C849 --timestamp=none bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/libTest.exe.dylib
    Tool /usr/bin/codesign execution started with arguments: -v --force --sign BCAF299B576AC3A61202C6A408738D8EE878C849 --timestamp=none bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/libmonosgen-2.0.dylib
    Tool /usr/bin/codesign execution started with arguments: -v --force --sign BCAF299B576AC3A61202C6A408738D8EE878C849 --timestamp=none bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/libXamarin.iOS.dll.dylib
    Tool /usr/bin/codesign execution started with arguments: -v --force --sign BCAF299B576AC3A61202C6A408738D8EE878C849 --timestamp=none bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/libmono-profiler-log.dylib
    Tool /usr/bin/codesign execution started with arguments: -v --force --sign BCAF299B576AC3A61202C6A408738D8EE878C849 --timestamp=none bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/libmscorlib.dll.dylib
    Tool /usr/bin/codesign execution started with arguments: -v --force --sign BCAF299B576AC3A61202C6A408738D8EE878C849 --timestamp=none bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/libxamarin-debug.dylib
Target _CodesignAppBundle:
    Tool /usr/bin/codesign execution started with arguments: -v --force --sign BCAF299B576AC3A61202C6A408738D8EE878C849 --entitlements /Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/Entitlements.xcent --timestamp=none /Users/damianocuria/Desktop/Test/Test/bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app
    Touching "bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app.dSYM/Contents/Info.plist".
    Touching "bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app/_CodeSignature/CodeResources".
Target _CodesignVerify:
    /usr/bin/codesign --verify -vvvv -R='anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.1] exists and (certificate leaf[field.1.2.840.113635.100.6.1.2] exists or certificate leaf[field.1.2.840.113635.100.6.1.4] exists)' bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app 
    bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app: valid on disk
    bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app: satisfies its Designated Requirement
    bin/iPhone/Debug/device-builds/iphone11.6-12.1.2/Test.app: explicit requirement satisfied

Done building project "Test.csproj".

Build succeeded.

/Users/damianocuria/Desktop/Test/Test/obj/iPhone/Debug/device-builds/iphone11.6-12.1.2/actool/cloned-assets/Assets.xcassets : actool warning : The app icon set "AppIcon" has an unassigned child.
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:19.98

========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Build: 0 errors, 1 warning

**Comment by curia-damiano** [comment]
P.S. Mac and iPhone are in the same wifi; also deploying via USB works just fine

**Comment by curia-damiano** [comment]
Hi,
sorry for the late reply, I was busy with customers in the past days.
Yesterday night I've tried again and it worked.
The only difference is that I have updated my phone to iOS 12.1.3.
Now I'm not able to reproduce the issue anymore, so I'm going to close it...
Thank you all for your support!
