### ISSUE TITLE
[tests] Introspection iOS Unified 64-bits - simulator failing on 5 selector not found for UIKit.UIPreviewInteraction

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#5471]
### Steps to Reproduce

1. Run iOS introspection tests for iOS Unified 64-bits 

### Expected Behavior

Tests shouldn't fail with "selector not found for UIKit.UIPreviewInteraction"

### Actual Behavior

5 selector not found for UIKit.UIPreviewInteraction

```
[FAIL] Selector not found for UIKit.UIPreviewInteraction : cancelInteraction 
[FAIL] Selector not found for UIKit.UIPreviewInteraction : locationInCoordinateSpace: 
[FAIL] Selector not found for UIKit.UIPreviewInteraction : delegate 
[FAIL] Selector not found for UIKit.UIPreviewInteraction : setDelegate: 
[FAIL] Selector not found for UIKit.UIPreviewInteraction : view 
```

### Environment

Latest builds from https://github.com/xamarin/xamarin-macios/tree/xcode10.2. After https://github.com/xamarin/xamarin-macios/pull/5470 is merged.

**Comment by spouliot** [comment]
That was fixed (as in ignored in tests) in both `xcode10.2` and `master` branches - 
https://github.com/xamarin/xamarin-macios/pull/5573
