### ISSUE TITLE
MT5216 Error when Building for device

### ISSUE THREAD

**Issue by alf002** [xamarin/xamarin-macios#5494]
### Steps to Reproduce

1. Create a binding of the SignificantSDK from Xyzmo
2. Add the binding project and PDFNet iOS native library to the Xamarin iOS project
3. Build the project on device

### Expected Behavior
Build and run the application on device
### Actual Behavior
Doesn't build and generates the following error "".../MTOUCH: Error MT5216: Native linking failed for '/.../obj/iPhone/Debug/device-builds/ipad6.8-12.1/mtouch-cache/arm64/libSIGNificantStandaloneSDK.dll.dylib"

However if we build for the simulator it run perfectly and the functions of the binding project are working fine.
### Environment
macOS Majove , Visual Studio Community 7.7.3

=== Visual Studio Community 2017 for Mac ===

Version 7.7.3 (build 43)
Installation UUID: ac1bc5c7-c02b-448c-bb17-cb4f38ab5204
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.13 (Visual Studio Community)
Hash: a4332c90
Branch: 
Build date: 2019-01-11 13:08:10-0500

=== Xamarin.iOS ===

Version: 12.2.1.13 (Visual Studio Community)
Hash: a4332c90
Branch: d15-9
Build date: 2019-01-11 13:08:09-0500

=== Build Information ===

Release ID: 707030043
Git revision: 5896ab2acba037c62271742e9e56b900c96c1d8f
Build date: 2019-01-15 21:18:33+00
Build branch: release-7.7
Xamarin extensions: e5b43ba963b7b407aa5b9f2c59018c32a709e6ab

=== Operating System ===

Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by dalexsoto** [comment]
Hello @alf002 

Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs, a test case (to reproduce) and all your version information.

 To get full build logs just set the log verbosity to diagnostic at the following locations:

 - On Visual Studio for Mac: Preferences > Projects > Build
 - On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

 On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

 Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

 The easiest way to get exact version information:

 - On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
 - On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

 Then copy/paste the version information (you can use the "Copy Information" button).

 We look forward to hearing from you!

**Comment by spouliot** [comment]
We have not received the requested information (build log and/or test case).

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
