### ISSUE TITLE
[RFC] Use Mono.Cecil from NuGet.

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#5507]
Proposal:

* Consume Mono.Cecil from NuGet instead of the source code from mono's submodule (external/mono/external/cecil).

Problems it solves:

* One less source dependency from mono.
* An upcoming Cecil change (https://github.com/jbevain/cecil/pull/554) requires an update on our side (https://github.com/rolfbjarne/xamarin-macios/commit/53874c863996656eaba43a5582731b93eb6f53b7), but we can't apply the update until we've updated to the new Cecil. Using Mono.Cecil from NuGet allows us to consume the updated Cecil right away (and apply our fix).

Current cecil source consumers:

```
$ git grep ProjectReference.*Mono.Cecil.csproj
tests/mtouch/mtouch.csproj:    <ProjectReference Include="..\..\external\mono\external\cecil\Mono.Cecil.csproj">
tools/mmp/mmp.csproj:    <ProjectReference Include="..\..\external\mono\external\cecil\Mono.Cecil.csproj">
tools/mtouch/mtouch.csproj:    <ProjectReference Include="..\..\external\mono\external\cecil\Mono.Cecil.csproj">
```

**Comment by spouliot** [comment]
The cecil revision is currently harmonized (RE) across all products (IDE/SDK) to avoid different bugs/fixes. That could also be done using nugets but it needs to be raised outside the team.

**Comment by rolfbjarne** [comment]
This was implemented with the mono archive.
