### ISSUE TITLE
MT0000: Unexpected error 

### ISSUE THREAD

**Issue by rwelz** [xamarin/xamarin-macios#5516]
You asked my for a bug report - here you are :)

Visual Studio Enterprise 2017 for Mac
Version 7.7.3 (build 43)
Installation UUID: 770293c7-777b-465a-be9b-390706d1e7c0
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

Mono Framework MDK
Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

NuGet
Version: 4.8.0.5385

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.0.5
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.4
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.2.1.13 (Visual Studio Enterprise)
Hash: a4332c90
Branch: 
Build date: 2019-01-11 13:08:10-0500

Xamarin.iOS
Version: 12.2.1.13 (Visual Studio Enterprise)
Hash: a4332c90
Branch: d15-9
Build date: 2019-01-11 13:08:09-0500

Xamarin.Android
Version: 9.1.5.1 (Visual Studio Enterprise)
Android SDK: /Volumes/MacintoshHD/Users/rwelz/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		6.0   (API level 23)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Microsoft Mobile OpenJDK
Java SDK: /Volumes/MacintoshHD/Users/rwelz/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 7.7.1.0
Hash: 06ceaea1

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 707030043
Git revision: 5896ab2acba037c62271742e9e56b900c96c1d8f
Build date: 2019-01-15 21:18:33+00
Build branch: release-7.7
Xamarin extensions: e5b43ba963b7b407aa5b9f2c59018c32a709e6ab

Operating System
Mac OS X 10.14.3
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Thu Dec 20 20:46:53 PST 2018
    root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64

### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

### Build Logs

Building ThinPrintMobileSessionPrintClientiOS (internal PreviewTests and distribution plus logging|iPhone)
Build started 30.01.2019 08:56:19.
__________________________________________________
Project "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/ThinPrintMobileSessionPrintClientiOS.csproj" (Build target(s)):

Target CheckPrerequisites:
    __________________________________________________
    Project "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/ThinPrintMobileSessionPrintClientiOS.csproj" is building "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/.nuget/NuGet.targets" (_DownloadNuGet target(s)):

Target RestorePackages:
    mono --runtime=v4.0.30319 "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/.nuget/NuGet.exe" install "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/packages.config" -source "https://ctd-sv01.thinprint.de:440/nexus/service/local/nuget/nuget-group/"    -OutputDir "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/packages"
Target _BeforeCoreCompileInterfaceDefinitions:
  Skipping target "_BeforeCoreCompileInterfaceDefinitions" because all output files are up-to-date with respect to the input files.
Target _CoreCompileInterfaceDefinitions:
  Skipping target "_CoreCompileInterfaceDefinitions" because all output files are up-to-date with respect to the input files.
Target _BeforeCoreCompileImageAssets:
    Deleting file "obj/iPhone/internal PreviewTests and distribution plus logging/actool/_PartialAppManifest.items".
    Deleting file "obj/iPhone/internal PreviewTests and distribution plus logging/actool/_BundleResourceWithLogicalName.items".
    Removing directory "obj/iPhone/internal PreviewTests and distribution plus logging/actool".
Target _CoreCompileColladaAssets:
  Skipping target "_CoreCompileColladaAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _CoreCompileSceneKitAssets:
  Skipping target "_CoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _CoreCompileTextureAtlases:
  Skipping target "_CoreCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileCoreMLModels:
    Deleting file "obj/iPhone/internal PreviewTests and distribution plus logging/coremlc/_PartialAppManifest.items".
    Deleting file "obj/iPhone/internal PreviewTests and distribution plus logging/coremlc/_BundleResourceWithLogicalName.items".
    Removing directory "obj/iPhone/internal PreviewTests and distribution plus logging/coremlc".
Target _CoreOptimizePngImages:
  Skipping target "_CoreOptimizePngImages" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizePropertyLists:
    /usr/bin/plutil -convert binary1 -o "obj/iPhone/internal PreviewTests and distribution plus logging/optimized/Settings.bundle/Root.plist" Settings.bundle/Root.plist 
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target GenerateBindingRedirects:
    No suggested binding redirects from ResolveAssemblyReferences.
Target _UnpackLibraryResources:
        Up to date: LoggingDetailViewController.nib
        Up to date: progress-circle.png
        Up to date: progress-circle@2x.png
        Up to date: progress-circle@2x~ipad.png
        Up to date: progress-circle~ipad.png
        Up to date: progress-circle-back.png
        Up to date: progress-circle-back@2x.png
        Up to date: progress-circle-back@2x~ipad.png
        Up to date: progress-circle-back~ipad.png
Target PreBuildEvent:
    "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/../Tools/beforeBuild.sh" -c "internal PreviewTests and distribution plus logging"
    + getopts c: option
    ~/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/bin/iPhone/intPrevTestDistPlusLog ~/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/bin/iPhone/intPrevTestDistPlusLog
    + case "$option" in
    + configname='internal PreviewTests and distribution plus logging'
    + getopts c: option
    + plistBuddy=/usr/libexec/PlistBuddy
    + pushd .
    ++ dirname /Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/../Tools/beforeBuild.sh
    + cd /Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/../Tools
    ++ pwd
    + basePath=/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/Tools
    + cd ..
    + chmod a+w ThinPrintMobileSessionPrintClient/Info.plist
    + chmod a+w ThinPrintMobileSessionPrintClient/Settings.bundle/Root.plist
    + mono ./Tools/mkversiov3.exe ThinPrintMobileSessionPrintClient/Info.plist ThinPrintMobileSessionPrintClient/Settings.bundle/Root.plist pom.xml -vf relversion_file.txt -vp relversion_prod.txt
    mkversiov3 V3.1.27.1
    BuildServerBuild = False
    Parse Arguments...
    Call git with 'rev-parse --short HEAD'...
    Git returned '7e26deb'
    Call git with 'branch --list'
    git returned 'develop
    * moving-more-constants-to-Constants.cs
      support/10.7'
    GIT repository: build from non-release branch
    Version: '10.7.9.1'
    Processing files...
    Preparing plist file 'Info.plist'
    Preparing plist file 'Root.plist'
    Preparing xml file 'pom.xml'
    writing changes to manifest/XML file
    writing '10.7.9' to 'relversion_file.txt'
    writing '10.7.9' to 'relversion_prod.txt'
    Command successfully completed.
    configname = internal PreviewTests and distribution plus logging
    + echo 'configname = internal PreviewTests and distribution plus logging'
    + '[' 'internal PreviewTests and distribution plus logging' == 'internal PreviewTests and distribution' ']'
    + '[' 'internal PreviewTests and distribution plus logging' == 'EnterpriseBuild development' ']'
    + '[' 'internal PreviewTests and distribution plus logging' == 'internal PreviewTests and distribution plus logging' ']'
    + /usr/libexec/PlistBuddy -c 'Set :CFBundleIdentifier com.thinprint.mobileprint' ThinPrintMobileSessionPrintClient/Info.plist
    + popd
    ~/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/bin/iPhone/intPrevTestDistPlusLog
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target CoreCompile:
    /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Roslyn/csc.exe /noconfig /nowarn:1701,2008 /nostdlib+ /errorreport:prompt /warn:4 /define:__IOS__;__MOBILE__;__UNIFIED__;LOGFILE;INTERNAL_PREVIEWTESTS_AND_DISTRIBUTION_PLUS_LOGGING_APN /errorendlocation /preferreduilang:en-US /reference:/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/packages/Cortado.Workplace.Client.1.1.16/lib/portable-net40+sl50+win+wp80+Xamarin.iOS10+MonoAndroid10+MonoTouch10/Cortado.Workplace.Client.dll /reference:/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/packages/Cortado.Workplace.Client.iOS.1.2.2/lib/portable-net40+sl50+win+wp80+Xamarin.iOS10+MonoAndroid10+MonoTouch10/Cortado.Workplace.Client.iOS.dll /reference:/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/packages/modernhttpclient-updated.2.7.2/lib/xamarinios10/ModernHttpClient.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Mono.Security.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/mscorlib.dll /reference:/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/packages/Newtonsoft.Json.7.0.1/lib/portable-net40+sl5+wp80+win8+wpa81/Newtonsoft.Json.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Core.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Net.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Net.Http.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Xml.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Xamarin.iOS.dll /debug+ /debug:portable /optimize+ /out:"obj/iPhone/internal PreviewTests and distribution plus logging/ThinPrintMobileSessionPrintClientiOS.exe" /target:exe /utf8output UIUtilities.cs FireAndForgetExtensionMethod.cs PrintJob.cs UserDeviceConfigResponseDTO.cs X509Certificate2Converter.cs Certificate.cs ClientInfo.cs TPMPSSSLServerCert.cs CertificateValidator.cs LogToFile.cs Reachability.cs Constants.cs "View Controller/ConfigurationChangedViewController.cs" "View Controller/ConfigurationChangedViewController.designer.cs" "View Controller/ConfigurationCompletedViewController.cs" "View Controller/ConfigurationCompletedViewController.designer.cs" "View Controller/EmailHasBeenSentViewController.cs" "View Controller/EmailHasBeenSentViewController.designer.cs" "View Controller/EMailLinkOpenedViewController.cs" "View Controller/EMailLinkOpenedViewController.designer.cs" "View Controller/MainViewController.cs" "View Controller/MainViewController.designer.cs" "View Controller/NoPrintJobAvailableViewController.cs" "View Controller/NoPrintJobAvailableViewController.designer.cs" "View Controller/PrintJobAvailableViewController.cs" "View Controller/PrintJobAvailableViewController.designer.cs" "View Controller/RegistrationScreenViewController.cs" "View Controller/RegistrationScreenViewController.designer.cs" MyExceptions.cs APNHelper.cs NSUserDefaultsHelper.cs PersistentData.cs "View Controller/Communicator.cs" CustomClasses/MyNSUrlConnectionDataDelegate.cs CustomClasses/iSecurity.cs Main.cs AppDelegate.cs "/var/folders/ff/gqzq5zqd1159cd18b0dnn0wr0000gn/T/Xamarin.iOS,Version=v1.0.AssemblyAttributes.cs"
    UIUtilities.cs(26,12,26,84): warning CS0618: 'UIAlertView.UIAlertView(string, string, UIAlertViewDelegate, string, params string[])' is obsolete: 'Use overload with a IUIAlertViewDelegate parameter'
    UIUtilities.cs(58,13,58,84): warning CS0618: 'UIAlertView.UIAlertView(string, string, UIAlertViewDelegate, string, params string[])' is obsolete: 'Use overload with a IUIAlertViewDelegate parameter'
    View Controller/RegistrationScreenViewController.cs(528,34,528,37): warning CS0168: The variable 'ex2' is declared but never used
    View Controller/EMailLinkOpenedViewController.cs(335,9,335,37): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
    View Controller/EMailLinkOpenedViewController.cs(364,10,364,38): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
    APNHelper.cs(475,9,475,148): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
    APNHelper.cs(486,10,486,134): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
    View Controller/Communicator.cs(193,35,193,46): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
    View Controller/Communicator.cs(331,35,331,54): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
    View Controller/Communicator.cs(389,35,389,49): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
    View Controller/Communicator.cs(409,35,409,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
    View Controller/MainViewController.cs(1139,6,1139,147): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
    View Controller/MainViewController.cs(1208,7,1208,148): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
    View Controller/MainViewController.cs(1237,8,1237,149): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
    View Controller/MainViewController.cs(1242,8,1242,149): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
    View Controller/MainViewController.cs(1251,7,1251,148): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Done building target "CoreCompile" in project "ThinPrintMobileSessionPrintClientiOS.csproj".
Target _CopyFilesMarkedCopyLocal:
    Touching "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/obj/iPhone/internal PreviewTests and distribution plus logging/ThinPrintMobileSessionPrintClientiOS.csproj.CopyComplete".
Target _CopyAppConfigFile:
  Skipping target "_CopyAppConfigFile" because all output files are up-to-date with respect to the input files.
Target CopyFilesToOutputDirectory:
    Copying file from "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/obj/iPhone/internal PreviewTests and distribution plus logging/ThinPrintMobileSessionPrintClientiOS.exe" to "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/bin/iPhone/intPrevTestDistPlusLog/ThinPrintMobileSessionPrintClientiOS.exe".
    ThinPrintMobileSessionPrintClientiOS -> /Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/bin/iPhone/intPrevTestDistPlusLog/ThinPrintMobileSessionPrintClientiOS.exe
    Copying file from "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/obj/iPhone/internal PreviewTests and distribution plus logging/ThinPrintMobileSessionPrintClientiOS.pdb" to "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/bin/iPhone/intPrevTestDistPlusLog/ThinPrintMobileSessionPrintClientiOS.pdb".
Target ThinPrintMsBuildCheckNuget:
    Target ResolveVisualStudioProject:
        Resolved CurrentVisualStudioProject: '/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/ThinPrintMobileSessionPrintClientiOS.csproj'
        VCBuildConfig: 
        BuildingInsideVisualStudio: true
    Target ThinPrintMsBuildCreateNugetPackage:
        __________________________________________________
        Project "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/ThinPrintMobileSessionPrintClientiOS.csproj" is building "/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/ThinPrintMobileSessionPrintClientiOS.csproj" (ThinPrintMsBuildDoCreateNugetPackage target(s)):

Target _DetectSigningIdentity:
    Detected signing identity:
      Code Signing Key: "iPhone Developer: Robert Welz (2W592SK85V)" (990C32A6734FFC49B901A410C3BEB22FE2EB57B2)
      Provisioning Profile: "Mobile Printing Dev" (3307e1df-1b82-4608-9350-82e5fdfbe10a)
      Bundle Id: com.thinprint.mobileprint
      App Id: E6SHW9T26D.com.thinprint.mobileprint
Target _CopyResourcesToBundle:
  Building target "_CopyResourcesToBundle" partially, because some output files are out of date with respect to their input files.
    Copying file from '/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/obj/iPhone/internal PreviewTests and distribution plus logging/optimized/Settings.bundle/Root.plist' to '/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/bin/iPhone/intPrevTestDistPlusLog/ThinPrintMobileSessionPrintClientiOS.app/Settings.bundle/Root.plist'
Target _DetectDebugNetworkConfiguration:
      DebugIPAddresses: 
Target _CompileAppManifest:
    Directory "bin/iPhone/intPrevTestDistPlusLog/ThinPrintMobileSessionPrintClientiOS.app.dSYM" doesn't exist. Skipping.
Target _ParseExtraMtouchArgs:
      NoSymbolStrip Output: False
      NoDSymUtil Output: false
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch "@/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/obj/iPhone/internal PreviewTests and distribution plus logging/response-file.rsp" --dsym=true -v -v -v -v 
    MTOUCH : error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
    System.IO.DirectoryNotFoundException: Could not find a part of the path '/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/bin/iPhone/intPrevTestDistPlusLog/ThinPrintMobileSessionPrintClientiOS.app.dSYM'.
      at System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) [0x00207] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/__error.cs:188 
      at System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) [0x00006] in <98fac219bd4e453693d76fda7bd96ab0>:0 
      at System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () [0x00054] in <98fac219bd4e453693d76fda7bd96ab0>:0 
      at System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) [0x000d6] in <98fac219bd4e453693d76fda7bd96ab0>:0 
      at System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) [0x00009] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/filesystemenumerable.cs:48 
      at System.IO.Directory.EnumerateFileSystemNames (System.String path, System.String searchPattern, System.IO.SearchOption searchOption, System.Boolean includeFiles, System.Boolean includeDirs) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/directory.cs:1007 
      at System.IO.Directory.InternalEnumerateFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/directory.cs:942 
      at System.IO.Directory.EnumerateFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) [0x00038] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/directory.cs:930 
      at Xamarin.Bundler.Application.BuildDsymDirectory () [0x0005a] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:2050 
      at Xamarin.Bundler.Application.BuildEnd () [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:864 
      at Xamarin.Bundler.Application+<>c.<BuildAll>b__140_3 (Xamarin.Bundler.Application v) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:790 
      at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x0001e] in <98fac219bd4e453693d76fda7bd96ab0>:0 
      at Xamarin.Bundler.Application.BuildAll () [0x000a3] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:790 
      at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x00423] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/mtouch.cs:1402 
      at Xamarin.Bundler.Driver.Main (System.String[] args) [0x00015] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/mtouch.cs:934 
Done building target "_CompileToNative" in project "ThinPrintMobileSessionPrintClientiOS.csproj" -- FAILED.

Done building project "ThinPrintMobileSessionPrintClientiOS.csproj" -- FAILED.

Build FAILED.

UIUtilities.cs(26,12,26,84): warning CS0618: 'UIAlertView.UIAlertView(string, string, UIAlertViewDelegate, string, params string[])' is obsolete: 'Use overload with a IUIAlertViewDelegate parameter'
UIUtilities.cs(58,13,58,84): warning CS0618: 'UIAlertView.UIAlertView(string, string, UIAlertViewDelegate, string, params string[])' is obsolete: 'Use overload with a IUIAlertViewDelegate parameter'
View Controller/RegistrationScreenViewController.cs(528,34,528,37): warning CS0168: The variable 'ex2' is declared but never used
View Controller/EMailLinkOpenedViewController.cs(335,9,335,37): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
View Controller/EMailLinkOpenedViewController.cs(364,10,364,38): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
APNHelper.cs(475,9,475,148): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
APNHelper.cs(486,10,486,134): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
View Controller/Communicator.cs(193,35,193,46): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
View Controller/Communicator.cs(331,35,331,54): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
View Controller/Communicator.cs(389,35,389,49): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
View Controller/Communicator.cs(409,35,409,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
View Controller/MainViewController.cs(1139,6,1139,147): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
View Controller/MainViewController.cs(1208,7,1208,148): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
View Controller/MainViewController.cs(1237,8,1237,149): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
View Controller/MainViewController.cs(1242,8,1242,149): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
View Controller/MainViewController.cs(1251,7,1251,148): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
MTOUCH : error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
    16 Warning(s)
    1 Error(s)

Time Elapsed 00:00:15.80

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 16 warnings

**Comment by dalexsoto** [comment]
It seems that dSYM directory is not getting generated:

```
Directory "bin/iPhone/intPrevTestDistPlusLog/ThinPrintMobileSessionPrintClientiOS.app.dSYM" doesn't exist. Skipping.
...
MTOUCH : error MT0000: Unexpected error - Please file a bug report at http://bugzilla.xamarin.com
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Volumes/MacintoshHD/Users/rwelz/Documents/Development/Cortado/ThinPrintMobilePrint/ThinPrintMobileSessionPrintClient/bin/iPhone/intPrevTestDistPlusLog/ThinPrintMobileSessionPrintClientiOS.app.dSYM'.
```

Any reason you are passing `--dsym=true` to your additional mtouch args? IIRC there is no need for this, we generate the `.dsym` in device builds and you should be able to find it inside your `bin` directory along with the `.app` bundle without anything extra.

Can you check if removing said parameter makes your project build again?

**Comment by mandel-macaque** [comment]
@rwelz I am closing the issue since we have had not replies for a long time. Please, if you consider this wrong, feel free to open it.
