### ISSUE TITLE
[xcode10.2] CALayerInvalidGeometry Reason: CALayer position contains NaN

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#5564]
I've found that [DocumentWatermark](https://github.com/xamarin/ios-samples/tree/5a315ce8cb13d6fb058237b0978d39595e4f3f0a/ios11/PDFDocumentWatermark) and [PDFAnnotationWidgetsAdvanced](https://github.com/xamarin/ios-samples/tree/5a315ce8cb13d6fb058237b0978d39595e4f3f0a/ios11/PDFAnnotationWidgetsAdvanced) fails on launch with the xcode10.2 build

### Steps to Reproduce

1. Run one of the projects on iPhone with 12.2 iOS

_(It runs successfully on phones with 12.1.2 iOS and 12.0.1 iOS)_

### Expected Behavior
It runs successfully

### Actual Behavior
It crashes on launch

### Environment

1. `OSX` 10.14.3
2. `XI` 12.4.0.37
3. `Mono` 5.16.0.233
4. `Xcode` 10.2.0

### Build Logs

1. Output Logs:
    - DocumentWatermark 
http://xqa.blob.core.windows.net/gist/report-c63a4e20a4ad482aaefe3dada93b0657.txt
    - PDFAnnotationWidgetsAdvanced 
http://xqa.blob.core.windows.net/gist/report-56bd1129d01d487e923ae64a3699d177.txt
2. Device Logs
    - DocumentWatermark 
http://xqa.blob.core.windows.net/gist/DocumentWatermark-2019-02-06-053246-XQAiPhone8Plusb-4bec26b28a3240dfab82c64a46aeb71d.txt
    - PDFAnnotationWidgetsAdvanced 
http://xqa.blob.core.windows.net/gist/PDFAnnotationWidgetsAdvanced-2019-02-06-052429-XQAiPhone8Plusb-f6e4a423c0c74956907025e561ec3764.txt

### Example Project

-  [DocumentWatermark](https://github.com/xamarin/ios-samples/tree/5a315ce8cb13d6fb058237b0978d39595e4f3f0a/ios11/PDFDocumentWatermark)
-  [PDFAnnotationWidgetsAdvanced](https://github.com/xamarin/ios-samples/tree/5a315ce8cb13d6fb058237b0978d39595e4f3f0a/ios11/PDFAnnotationWidgetsAdvanced)

**Comment by dalexsoto** [comment]
It is very likely that Apple added some more exhaustive API checks in iOS 12.2+ so it is likely that we need to revisit said samples for example DocumentWatermark fails with

```
Name: CALayerInvalidGeometry Reason: CALayer position contains NaN: [nan nan]
```

Not a Xamarin.iOS/Mac SDK issue per se at first glance but definitely we need to revisit both samples.

**Comment by dalexsoto** [comment]
@mykyta-bondarenko-gl requested for help on this, I'll have a look

**Comment by dalexsoto** [comment]
This is not a Xamarin.iOS issue, the error gets issued inside the Apple stack also their own [sample](https://developer.apple.com/documentation/pdfkit/custom_graphics?language=objc) crashes the same way.
