### ISSUE TITLE
'InstanceID' does not contain definition for 'SetApnsToken' after updating Firebase packages

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/xamarin-macios#5595]
In my Xamarin.iOS project I started getting errors after updating Firebase nuget packages. Before updating packages all code was working fine. 

This is my code

```
   // You'll need this method if you set "FirebaseAppDelegateProxyEnabled": NO in GoogleService-Info.plist
        public override void RegisteredForRemoteNotifications (UIApplication application, NSData deviceToken)
        {
            NSUserDefaults.StandardUserDefaults.SetString(deviceToken.ToString(),"dToken");
            #if DEBUG

            Firebase.InstanceID.InstanceId.SharedInstance.SetApnsToken(deviceToken, Firebase.InstanceID.ApnsTokenType.Sandbox);
#if RELEASE
            Firebase.InstanceID.InstanceId.SharedInstance.SetApnsToken(deviceToken, Firebase.InstanceID.ApnsTokenType.Prod);

        }
```
I have installed these Firebase packages

_Xamarin.Firebase.Analytics
Xamarin.Firebase.CloudeMessaging
Xamarin.Firebase.Core
Xamarin.Firebase.InstanceID_

How can I solve this issue?

### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

### Example Project (If Possible)

<img width="1248" alt="screenshot 2019-02-12 at 4 38 47 pm" src="https://user-images.githubusercontent.com/19743421/52632822-99d9f800-2ee8-11e9-8ac4-38b1987d9f6f.png">

**Comment by dalexsoto** [comment]
Hello, thank you for your report,

This repository is for the Xamarin iOS and Mac SDKs, Firebase is a third party component and you might get a better answer to your question here https://github.com/xamarin/GoogleApisForiOSComponents, I'll move your issue to said repository.

**Comment by dalexsoto** [comment]
This issue was moved to xamarin/GoogleApisForiOSComponents#238
