### ISSUE TITLE
Release build crashes at start

### ISSUE THREAD

**Issue by Dabbel** [xamarin/xamarin-macios#5611]
Maybe not direct a issue but i can't figure out why the app crashes in release build and in debug build everything works fine.

### Environment

Will update environment infos tomorrow when i'm back in office

```
Visual Studio for Mac 2019 Preview 2

Xamarin.iOS https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-0/7397aab9ca5791ed437dbf8fd364c0deb37b76d0/23/package/xamarin.ios-12.6.0.22.pkg
```

### Build Logs

This is the only log i found. App id is "de.greengate.gstouch"

[release_crash.txt](https://github.com/xamarin/xamarin-macios/files/2864987/release_crash.txt)

**Comment by dalexsoto** [comment]
Hello @Dabbel 

Unfortunately I don't see anything obvious in the provided log, do you happen to have a crash report from the device you are testing? Maybe that can give us more hints of what is going on

**Comment by Dabbel** [comment]
I don't really know how to get more logs/reports from the device. That was the output from Xcode from the device. I didn't see any other logs/reports for the device.

If it helps i could provide the IPA file signed with an apple enterprise developer account.

**Comment by dalexsoto** [comment]
Hello @Dabbel!

Have a look at the following link https://jmillerdev.net/symbolicating-ios-crash-files-xamarin-ios/ should help you on how to get a crash report 👍

**Comment by Dabbel** [comment]
I found the problem.

"Linker Behavior" and EntityFramework.Core doesn't work well together.

If "Linker Behavior" is set to "Link Framework SDKs Only" type initializer for "Microsoft.EntityFrameworkCore.Query.ResultOperators.Internal.TrackingExpressionNode" fails.

Setting "Linker Behavior" to "Don't Link" everything works fine.
[linker_error.txt](https://github.com/xamarin/xamarin-macios/files/2868834/linker_error.txt)

**Comment by spouliot** [comment]
3rd party (everything not part of the SDK) libraries might not be safe to be linked, e.g. they might use reflection and the managed linker (based one static analysis) won't know that some types/methods are required at runtime.

If you have (or can find) the source code for such 3rd party code you might be able to _hint_ the linker about the extra requirements. E.g. you can use `--linkskip=ASSEMBLY` to avoid linking a specific assembly or use an XML file to define, more precisely, which extraneous types and methods the linker must preserve. Doing this will make your final application a lot smaller and faster to build/deploy on devices.
