### ISSUE TITLE
[2018-10] dontlink tvOS crash with incremental builds or mono as a framework

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#5612]
### Steps to Reproduce

1. Launch xharness, and run any of the `dont link/tvOS - device/AssemblyBuildTarget: *` tests.

### Expected Behavior

Successful test execution.

### Actual Behavior

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: /work/maccore/mono-master/xamarin-macios/external/mono/sdks/out/ios-targettv-release/lib/libmonosgen-2.0.1.dylib | Referenced from: /private/var/containers/Bundle/Application/6677C0EC-D3CA-4117-A839-D1C83005500C/dont link.app/libmono-native-compat.dylib | Reason: image not found
Triggered by Thread:  0
```

Complete crash log: https://gist.github.com/rolfbjarne/53dd7e1b8dff1030d58035b9c17f3d75

The same tests work fine on iOS, so it's probably an if or switch somewhere that must be updated to include tvOS.

### Environment

PR #4904.

### Build Logs

https://gist.github.com/rolfbjarne/cd17b6b685e89fecf9556b27b3a9036b

**Comment by akoeplinger** [comment]
Fixed in mono-2018-10
