### ISSUE TITLE
[2018-10] mono-native-[compat|unified] fails on tvOS device: [FAIL] Introspection.CheckSymbols : dlsym() found mono_native_initialize() 

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#5613]
### Steps to Reproduce

1. Launch xharness, and run the `mono-native-compat/tvOS - device/Debug` test.

### Expected Behavior

Test passes.

### Actual Behavior

```
[FAIL] Introspection.CheckSymbols : dlsym() found mono_native_initialize() 
```

Complete test log: https://gist.github.com/rolfbjarne/193337daeda0bd1e452774dce2ba72b4

### Environment

PR #4904.

### Build Logs

https://gist.github.com/rolfbjarne/5708f34438de8f6fadf5a05b4e29b000

**Comment by akoeplinger** [comment]
Fixed in mono-2018-10
