### ISSUE TITLE
UIPanGestureRecognizer not working when accessibility enabled

### ISSUE THREAD

**Issue by Sasikumar3595** [xamarin/xamarin-macios#5615]
### Steps to Reproduce

1. Enable accessibility on iPhone
2. Run the sample, which contains UIPanGestureRecognizer
3. UIPanGestureRecognizer does not listen the swiping on sample view

### Example Project 

[PanGesture-iOS.zip](https://github.com/xamarin/xamarin-macios/files/2868817/PanGesture-iOS.zip)

### Expected Behavior

- UIPanGestureRecognizer action get triggered

### Actual Behavior

- UIPanGestureRecognizer action not triggered

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.4.3 (build 10)
Installation UUID: 8859c4ae-14dc-4daa-9c45-000125bedc9b
Runtime:
	Mono 5.16.0.220 (2018-06/bb3ae37d71a) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 516000220

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.0.5
	2.0.3
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/SasikumarArumugam/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.1 (API level 16)
		4.2 (API level 17)
		4.3 (API level 18)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.0 (13247)
Build 9A235

=== Xamarin.Mac ===

Version: 4.2.1.29 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.9.1.24 (Visual Studio Community)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

=== Build Information ===

Release ID: 704030010
Git revision: 5af3e98549653fcc5335896ccc296343d08f31bb
Build date: 2018-04-12 12:32:07-04
Xamarin addins: fadb82fb0fe2668cb7789f8b524aec6fb8568ee7
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Gorilla Player 1.2.2.0
```

**Comment by mandel-macaque** [comment]
Hello, I have created the following "simpler solution" that prints a message when the user slides:

[PanGesture-iOS.zip](https://github.com/xamarin/xamarin-macios/files/2880247/PanGesture-iOS.zip)

I have enabled the accessibility as follows:

![screenshot 2019-02-19 at 14 51 47](https://user-images.githubusercontent.com/2190086/53019832-ec219880-3455-11e9-822b-d903ee1157e1.png)

And the output is:

> 2019-02-19 14:46:28.353432+0100 iOSDemo[92200:62507400] Xamarin.iOS: Established connection with the IDE (fd: 5)
> 2019-02-19 14:46:28.353767+0100 iOSDemo[92200:62507400] Xamarin.iOS: Processing: 'start profiler: no'
> 2019-02-19 14:46:28.353912+0100 iOSDemo[92200:62507137] Xamarin.iOS: Profiler not loaded (disabled)
> 2019-02-19 14:46:28.373792+0100 iOSDemo[92200:62507137] Xamarin.iOS: Added dllmap for objc_msgSend
> Loaded assembly: /Users/mandel/Library/Developer/CoreSimulator/Devices/143CD3D7-C264-404E-BA13-08FA5EDC3007/data/Containers/Bundle/Application/4986E9CF-3C6C-4BCE-A4BE-BE8C3E859284/iOSDemo.app/Xamarin.iOS.dll
> Loaded assembly: /Users/mandel/Library/Developer/CoreSimulator/Devices/143CD3D7-C264-404E-BA13-08FA5EDC3007/data/Containers/Bundle/Application/4986E9CF-3C6C-4BCE-A4BE-BE8C3E859284/iOSDemo.app/iOSDemo.exe
> Loaded assembly: /Users/mandel/Library/Developer/CoreSimulator/Devices/143CD3D7-C264-404E-BA13-08FA5EDC3007/data/Containers/Bundle/Application/4986E9CF-3C6C-4BCE-A4BE-BE8C3E859284/iOSDemo.app/iOSNativeLibrary.dll
> 2019-02-19 14:46:28.592601+0100 iOSDemo[92200:62507137] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=92200
> 2019-02-19 14:46:28.592872+0100 iOSDemo[92200:62507137] SecTaskCopyDebugDescription: iOSDemo[92200]/0#-1 LF=0
> 2019-02-19 14:47:46.478024+0100 iOSDemo[92200:62507137] Panning detected
> 2019-02-19 14:47:46.484318+0100 iOSDemo[92200:62507137] Gesture recognizer state: Began
> 2019-02-19 14:47:46.492612+0100 iOSDemo[92200:62507137] Panning detected
> 2019-02-19 14:47:46.492821+0100 iOSDemo[92200:62507137] Gesture recognizer state: Changed
> 2019-02-19 14:47:46.493098+0100 iOSDemo[92200:62507137] Panning detected
> 2019-02-19 14:47:46.493250+0100 iOSDemo[92200:62507137] Gesture recognizer state: Changed
> 2019-02-19 14:47:46.515300+0100 iOSDemo[92200:62507137] Panning detected
> 2019-02-19 14:47:46.515524+0100 iOSDemo[92200:62507137] Gesture recognizer state: Changed
> 2019-02-19 14:47:46.537948+0100 iOSDemo[92200:62507137] Panning detected
> 2019-02-19 14:47:46.538173+0100 iOSDemo[92200:62507137] Gesture recognizer state: Changed
> 2019-02-19 14:47:46.561712+0100 iOSDemo[92200:62507137] Panning detected
> 2019-02-19 14:47:46.561925+0100 iOSDemo[92200:62507137] Gesture recognizer state: Changed
> 2019-02-19 14:47:46.582895+0100 iOSDemo[92200:62507137] Panning detected
> 2019-02-19 14:47:46.583109+0100 iOSDemo[92200:62507137] Gesture recognizer state: Changed
> 2019-02-19 14:47:46.605194+0100 iOSDemo[92200:62507137] Panning detected
> 2019-02-19 14:47:46.605399+0100 iOSDemo[92200:62507137] Gesture recognizer state: Changed
> 2019-02-19 14:47:46.627520+0100 iOSDemo[92200:62507137] Panning detected
> 2019-02-19 14:47:46.627707+0100 iOSDemo[92200:62507137] Gesture recognizer state: Changed
> 2019-02-19 14:47:46.634133+0100 iOSDemo[92200:62507137] Panning detected
> 2019-02-19 14:47:46.634316+0100 iOSDemo[92200:62507137] Gesture recognizer state: Ended

I believe that the issue you are experiencing is that you are not performing the right gesture. For users with disability, the correct gesture to perform the pan is one-finger double-tap and hold before continuing with the gesture. 

Closing the issue as it is working with:

https://gist.github.com/mandel-macaque/a2557942dac91fcb294d61cdfa89bc89
