### ISSUE TITLE
getting an error when trying to run Xamarin.iOS project from the sample downladed from the link https://github.com/Azure-Samples/active-directory-xamarin-native-v2.git

### ISSUE THREAD

**Issue by Gold14388** [xamarin/xamarin-macios#5642]
### Steps to Reproduce
Configure the solution to run UserDetailsClient.iOS project, While building the project, error is thrown

### Expected Behavior
Project should build successfully
### Actual Behavior
Project does not build successfully and throws an error mentioned below
**_Severity	Description	Project	File	Line	Suppression State
Error	Can't resolve the reference 'System.String System.String::TrimStart(System.Char)', referenced from the method 'Microsoft.Identity.Json.Schema.JsonSchema Microsoft.Identity.Json.Schema.JsonSchemaBuilder::ResolveReferences(Microsoft.Identity.Json.Schema.JsonSchema)' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.	UserDetailsClient.iOS_**

**Comment by mandel-macaque** [comment]
@Gold14388 I have checked out the project with the [following  version of xamarin](https://gist.github.com/mandel-macaque/f5a5e97cc5d3fc43e0571878c9bdd086) and I have had no issues compiling and running the project. Can you please provide the env you have.

**Comment by spouliot** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
