### ISSUE TITLE
CookieContainer support in NSUrlSessionHandler

### ISSUE THREAD

**Issue by cosminstirbu** [xamarin/xamarin-macios#5665]
### Steps to Reproduce

1. Create a `NSUrlSessionHandler`
2. Try to assign a `CookieContainer` (similar to how you would assign it to `HttpClientHandler`)
3. See that there is no `CookieContainer` property on `NSUrlSessionHandler`

### Expected Behavior

Be able to use `NSUrlSessionHandler` with a `CookieContainer`.

### Actual Behavior

Can't use `NSUrlSessionHandler` with a `CookieContainer`.

**Comment by mandel-macaque** [comment]
@cosminstirbu thanks for the report. We did not implement the CookieContainer because we did not have any user requesting it. I'll take a look at the work to be done and will get back with a possible fix. 

Thanks!

**Comment by mandel-macaque** [comment]
@cosminstirbu  please take a look at the PR and the tests to make sure that I fully implemented what is expected, specially related to the Set-Cookie header. Sorry for the delay, this was an enhancement not an issue ;)

**Comment by beeradmoore** [comment]
I've come across an issue where when using a NSUrlSessionHandler generated in the following way 
```
var config = NSUrlSessionConfiguration.CreateBackgroundSessionConfiguration(Xamarin.Essentials.AppInfo.PackageName);
var sessionHandler = new NSUrlSessionHandler(config);
var client = new HttpClient(sessionHandler);
```

Will uses cookies perfectly on iOS 11.1 through to 13.3. However from iOS 11.0 and below it never sends or receives cookies. I'm hoping this cookie container PR will fix this issue. It's on master branch, I don't see it being in d16-5 (which I believe is the next release). 

I need to pull and build master to confirm it fixes my issue, but is there any ETA on when a change like this would end up into the stable Xamarin.iOS channels?

**Comment by rolfbjarne** [comment]
> I need to pull and build master to confirm it fixes my issue,

You can also just download a pkg from master (click on the red X or green checkmark on any of the top commits here: https://github.com/xamarin/xamarin-macios/commits/master and download `PKG-Xamarin.iOS-notarized`)

> is there any ETA on when a change like this would end up into the stable Xamarin.iOS channels

It'll be in the d16-6 release, but that's still a few months away (probably somewhere in late spring / early summer)

**Comment by beeradmoore** [comment]
Oh handy, didn't know I could get them from there. Thanks @rolfbjarne. I'll see if this fixes my issue tomorrow, and if not I'll try debug it more tomorrow so I can report it.
