### ISSUE TITLE
System.Memory.dll not being copied anywhere when Roslyn package is referenced

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5672]
Steps to reproduce:

0. XM 5.6.0.23, Mono 5.18.0.266
1. Create a new XM app
2. Switch to XM Full: .NET 4.7.2
3. Add a package reference to Microsoft.CodeAnalysis.Common 3.0.0-beta3-final
4. Note that System.Memory is a dependency.
5. Build

Expected Results:

System.Memory.dll ends up in output area and app bundle.

Actual Results:

System.Memory.dll is nowhere to be found.

This report was originally from @sandyarmstrong internally.

**Comment by chamons** [comment]
Bisecting has determined that this was introduced in [this commit](https://github.com/xamarin/xamarin-macios/commit/0e98097c339e22e14b2f905e74921c0e32a30101). 

Research found that we ship [different facades](https://gist.github.com/chamons/84e4dcb795052cbab9376b94b83c97a7) for Full and Modern, and that shipping the same list was wrong.

@VincentDondain is working on the fix.

**Comment by VincentDondain** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/pull/5674
