### ISSUE TITLE
dynamic is not building on iOS using --interp

### ISSUE THREAD

**Issue by viniciusjarina** [xamarin/xamarin-macios#5673]
Xamarin.iOS custom build 
```
Xamarin.iOS
Version: 12.7.1.69 (Visual Studio Enterprise)
Hash: 011f73e9
Branch: xi-interpreter
```

Using `dynamic` is causing an build error:

```csharp
dynamic creator = methodCreator.Invoke (null, BindingFlags.Public | BindingFlags.Static, null, new object[] { dfsValue, null }, null);
object maze = creator.Create (rows, columns);
```

Error: **` ViewController.cs(85,18,85,25): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'`**

Source: https://github.com/viniciusjarina/MazeInterpreter/blob/master/test_interpreter/ViewController.cs#L85

**Comment by spouliot** [comment]
The project was missing a reference to `Microsoft.CSharp.dll`. Once added the build is fine (which makes sense since it's a compiler error).

I need to check how that's handled in _normal_ (desktop) scenarios.

**Comment by spouliot** [comment]
I copied your code into a new **Console** template project and it failed the same way.
```
Program.cs(65,18,65,25): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.78
```

Did you had some reason to think the assembly reference would not be needed ?

**Comment by spouliot** [comment]
We have not received the requested information. If think the behaviour is incorrect then please explain why and click the Reopen Issue button. Thanks!
