### ISSUE TITLE
Verify that classes implementing INativeObject follow our constructor pattern

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#5693]
We have a common pattern for constructors for classes that implement INativeObject:

```csharp
class MyObject : INativeObject {
    IntPtr handle;
    internal MyObject (IntPtr handle)
        : this (handle, false)
    {
    }
    internal MyObject (IntPtr handle, bool owns)
    {
        this.handle = handle;
        if (!owns)
            Retain (handle);
    }
}
```

An alternative to this is to subclass `NativeObject` instead.

Due to historical reasons, many of our classes don't follow this pattern (they were implemented before the pattern was established). Most importantly the reference counting semantics may differ for the IntPtr constructor: does the constructor retain the handle or not? According to the pattern, the handle should be retained (when applicable).

We should go through and fix all the cases where it's not a breaking change to do so (if the IntPtr constructor is public changing the reference counting semantics is a breaking change), and when it is, we should change it for XAMCORE_4_0.

Here is a test that finds at least some of the problematic types: https://github.com/rolfbjarne/xamarin-macios/commit/tests-inativeobject-constructors ([Failures](https://gist.github.com/rolfbjarne/893c2ed01ccc159bf804fb0ebd7b47ec))

**Comment by spouliot** [comment]
Great test :) but are you sure the results are all fine ?

```
CoreFoundation.CFBundle's IntPtr constructor does not call the IntPtr, bool constructor: /work/maccore/arm32_64/xamarin-macios/src/CoreFoundation/CFBundle.cs:74
```

```csharp
		internal CFBundle (IntPtr handle) : this (handle, false)
		{
		}
```

**Comment by rolfbjarne** [comment]
> but are you sure the results are all fine

I'm sure they're _not_ fine 😄

**Comment by rolfbjarne** [comment]
This was implemented for .NET.
