### ISSUE TITLE
Missing binding for CFStringTransform API

### ISSUE THREAD

**Issue by ForkBug** [xamarin/xamarin-macios#5705]
We want to convert some strings but couldn't find  the equivalence of CFStringTransform

**Comment by spouliot** [comment]
There's currently no bindings for the [CFStringTransform](https://developer.apple.com/documentation/corefoundation/1542411-cfstringtransform?language=objc) API.

Most of the `CFString` API have equivalents in `NSString` and most of them are bound - or have better .NET alternative. However I don't think there's an actual match in Foundation (`NSString`) or .NET for this one.

In case you need it quickly, it's a C-based (Carbon) API so a _regular_ p/invoke can be used directly inside your application.

**Comment by ForkBug** [comment]
I added a binding to my project to fix this. 
But it will be more elegant exporting apis in xamarin.

Thank you! Expecting the new release so we could remove the extra binding project ：）
