### ISSUE TITLE
Some macOS types are missing Mac/Introduced attribute 

### ISSUE THREAD

**Issue by stephen-hawley** [xamarin/xamarin-macios#5714]
The following types need to have an attribute signaling their provenance:

`Foundation.NSItemProviderErrorCode` introduced 10.10
`Foundation.NSLengthFormatterUnit` introduced 10.10
`Foundation.NSMassFormatterUnit` introduced 10.10
`Foundation.NSQualityOfService` introduced 10.10

**Comment by spouliot** [comment]
```
	[iOS (8,0)]
	[Mac (10,10)]
	[Native]
	public enum NSQualityOfService : long {
```

The last one is already decorated properly. Wrong copy/paste ?

**Comment by rolfbjarne** [comment]
> The last one is already decorated properly. Wrong copy/paste ?

It was fixed fairly recently: https://github.com/xamarin/xamarin-macios/commit/946651928b33afc2dd87c2cf6264474d319f050a, and SoM is using an older version of XM.
