### ISSUE TITLE
Xamarin Doesn't Implement All Of NSIndexPath's Constructors

### ISSUE THREAD

**Issue by csnazell-linn** [xamarin/xamarin-macios#5722]
### Steps to Reproduce

N/A

### Expected Behavior

Xamarin iOS should implement all of [NSIndexPath](https://developer.apple.com/documentation/foundation/nsindexpath?language=objc)'s  initialisers. 

### Actual Behavior

Xamarin iOS does not implement all of the class' initialisers, it is missing [+indexPathWithIndexes:length:](https://developer.apple.com/documentation/foundation/nsindexpath/1521015-indexpathwithindexes?language=objc) / [-initWithIndexes:length:](https://developer.apple.com/documentation/foundation/nsindexpath/1416906-initwithindexes?language=objc).

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.8.2 (build 1)
Installation UUID: 61b53bfe-4ff2-41d0-83d1-ee6d13f00866
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.0.0.0 ( / b40230c0)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.504/Sdks
SDK Versions:
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.15 (Visual Studio Community)
Hash: d60abd198
Branch: 
Build date: 2019-02-01 12:23:30-0500

=== Xamarin.iOS ===

Version: 12.2.1.15 (Visual Studio Community)
Hash: d60abd198
Branch: d15-9
Build date: 2019-02-01 12:23:29-0500

=== Xamarin.Android ===

Version: 9.1.8.0 (Visual Studio Community)
Android SDK: /Users/csnazell/Library/Android/sdk
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/csnazell/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
1.8.0-9
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.8.1.0
Hash: 8924ea4a

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 708020001
Git revision: 13e0e5b7e85ffe742957e6f204bab5c06c644f0e
Build date: 2019-02-27 19:33:14+00
Build branch: release-7.8
Xamarin extensions: 23eaa7c9cdc9a3f55be7bb87b485a790ec82ef25

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Sun Feb 10 20:20:48 PST 2019
    root:xnu-4570.71.29~1/RELEASE_X86_64 x86_64

```

### Build Logs

N/A

### Example Project (If Possible)

Rationale for including missing behaviour:

NSIndexPath is an array of index values of arbitrary length. The missing initialisers, although not commonly used, are in fact the generic use case. The supplied .FromIndex(), .FromItemSection() &  .FromRowSection() methods only deal with NSIndexPaths that are only 1 or 2 items deep and are, as such, special cases.

Currently the only practical solution to working with NSIndexPaths of arbitrary length is to start with a zero-depth NSIndexPath and loop through the indices that should be included in the NSIndexPath pushing the index onto the path and generating an arbitrary number of interim NSIndexPath objects that must then be disposed of.

**Comment by mandel-macaque** [comment]
Hello,

The indexPathWithIndexes:length: method is already present in  https://github.com/xamarin/xamarin-macios/blob/master/src/foundation.cs#L9614 which is internal and later exposed here https://github.com/xamarin/xamarin-macios/blob/master/src/Foundation/NSIndexPath.cs#L32

AFAIK we already offer Create methods similar to the API provided by initWithIndexes:length:.
