### ISSUE TITLE
Fonts missing in Release Build

### ISSUE THREAD

**Issue by dansiegel** [xamarin/xamarin-macios#5725]
## Description

As discussed with @spouliot in Gitter, when building locally fonts are included the finalized app, however when building on Azure DevOps for Release with the Distribution (Enterprise) cert, the custom fonts for Font Awesome are missing from the app resulting in a bunch of broken icons. 

### Steps to Reproduce

I have only been able to get this problem to present while building with a Production Enterprise certificate on Azure DevOps. Building locally I do not experience any problems. 

### Expected Behavior

Bundled resources should always be bundled....

### Actual Behavior

Bundled resources are missing in Release build on Azure DevOps. Note that the actual files are present in the output directory (bin/iPhone/Release/{appname}.app/) though they are missing from the generated IPA. 

### Build Logs

The following are the abbreviated logs from the Azure DevOps build.

```
_CopyResourcesToBundle:
  Copying file from '/Users/vsts/agent/2.147.1/work/1/s/src/platforms/MyApp.iOS/Resources/fa5pro-brands.otf' to '/Users/vsts/agent/2.147.1/work/1/s/src/platforms/MyApp.iOS/bin/iPhone/Release/MyApp.iOS.app/fa5pro-brands.otf'
  Copying file from '/Users/vsts/agent/2.147.1/work/1/s/src/platforms/MyApp.iOS/Resources/fa5pro-light.otf' to '/Users/vsts/agent/2.147.1/work/1/s/src/platforms/MyApp.iOS/bin/iPhone/Release/MyApp.iOS.app/fa5pro-light.otf'
  Copying file from '/Users/vsts/agent/2.147.1/work/1/s/src/platforms/MyApp.iOS/Resources/fa5pro-regular.otf' to '/Users/vsts/agent/2.147.1/work/1/s/src/platforms/MyApp.iOS/bin/iPhone/Release/MyApp.iOS.app/fa5pro-regular.otf'
  Copying file from '/Users/vsts/agent/2.147.1/work/1/s/src/platforms/MyApp.iOS/Resources/fa5pro-solid.otf' to '/Users/vsts/agent/2.147.1/work/1/s/src/platforms/MyApp.iOS/bin/iPhone/Release/MyApp.iOS.app/fa5pro-solid.otf'
```

The following are the abbreviated logs from the local VS Mac 2019 build.

```
Target _CopyResourcesToBundle:
  Building target "_CopyResourcesToBundle" completely.
  Output file "bin/iPhone/Debug/device-builds/iphone9.2-12.1/MyApp.iOS.app/Assets.car" does not exist.
  Output file "bin/iPhone/Debug/device-builds/iphone9.2-12.1/MyApp.iOS.app/fa5pro-brands.otf" does not exist.
  Output file "bin/iPhone/Debug/device-builds/iphone9.2-12.1/MyApp.iOS.app/fa5pro-light.otf" does not exist.
  Output file "bin/iPhone/Debug/device-builds/iphone9.2-12.1/MyApp.iOS.app/fa5pro-regular.otf" does not exist.
  Output file "bin/iPhone/Debug/device-builds/iphone9.2-12.1/MyApp.iOS.app/fa5pro-solid.otf" does not exist.
    Using "SmartCopy" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Tasks.dll".
  Task "SmartCopy"
      Copying file from '/Users/dansiegel/Repos/MyApp/src/platforms/MyApp.iOS/Resources/fa5pro-brands.otf' to '/Users/dansiegel/Repos/MyApp/src/platforms/MyApp.iOS/bin/iPhone/Debug/device-builds/iphone9.2-12.1/MyApp.iOS.app/fa5pro-brands.otf'
    Copying file from '/Users/dansiegel/Repos/MyApp/src/platforms/MyApp.iOS/Resources/fa5pro-light.otf' to '/Users/dansiegel/Repos/MyApp/src/platforms/MyApp.iOS/bin/iPhone/Debug/device-builds/iphone9.2-12.1/MyApp.iOS.app/fa5pro-light.otf'
    Copying file from '/Users/dansiegel/Repos/MyApp/src/platforms/MyApp.iOS/Resources/fa5pro-regular.otf' to '/Users/dansiegel/Repos/MyApp/src/platforms/MyApp.iOS/bin/iPhone/Debug/device-builds/iphone9.2-12.1/MyApp.iOS.app/fa5pro-regular.otf'
    Copying file from '/Users/dansiegel/Repos/MyApp/src/platforms/MyApp.iOS/Resources/fa5pro-solid.otf' to '/Users/dansiegel/Repos/MyApp/src/platforms/MyApp.iOS/bin/iPhone/Debug/device-builds/iphone9.2-12.1/MyApp.iOS.app/fa5pro-solid.otf'
```

### Example Project 

[FontInclusionIssue.zip](https://github.com/xamarin/xamarin-macios/files/2932348/FontInclusionIssue.zip)

**Comment by mandel-macaque** [comment]
The fact that it can only be reproduced in Azure DevOps makes it quite hard to debug. Let me try to find some extra information to see who can give you a hand.

**Comment by dansiegel** [comment]
@mandel-macaque I finally figured out what was going on... It seems that the git attributes didn't address an otf font and git was treating it like a standard text file instead of a binary file thus corrupting the font files. 

I would say this exposes a weakness in the build where we can get into a situation where a bundle resource such as a Font file or Image could be included, but not recognized by the OS due to it becoming corrupted.

**Comment by spouliot** [comment]
hmm... interesting - still I don't see why we would not copy it (even if it might not work) since that logic is, afaik, unaware if files are binary or text.

OTOH that should make it easier for @mandel-macaque to reproduce the issue, so thanks!

**Comment by dansiegel** [comment]
@spouliot if you look at the logs... the corrupted assets are getting copied... but there is nothing in the build process that catches that validates the assets are intact and haven't become corrupted. It's one of those fail silently scenarios... the only thing that finally gave me a hint was that I was experiencing the same issue when I added the Android build.

**Comment by rolfbjarne** [comment]
I don't think it's our responsibility to ensure that assets are valid, it would be another thing we'd have to play catch-up with Apple whenever they add new valid formats for assets.
