### ISSUE TITLE
[xunit] Tests run: 0 shouldn't result in a green test execution

### ISSUE THREAD

**Issue by akoeplinger** [xamarin/xamarin-macios#5767]
### Steps to Reproduce

1. Run xunit tests where no tests actually run (maybe due to filter or a bug etc)
2. It returns as green even though no tests actually ran: `Tests run: 0 Passed: 0 Inconclusive: 0 Failed: 0 Ignored: 0`

### Expected Behavior

At least a warning, maybe even error.

### Actual Behavior

No warning/error, easy to miss.

**Comment by spouliot** [comment]
Got a link to where it happened on bots ?

**Comment by akoeplinger** [comment]
Yup, check https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/9524/Test_20Report/
