### ISSUE TITLE
Step-by-step guide with cookbook for Xamarin IDE for MacOS, iOS, watchOS & tvOS

### ISSUE THREAD

**Issue by shyamalschandra** [xamarin/xamarin-macios#5773]
Is there going to be more information on step-by-step guides to Xamarin Apple development on Mac than the following in the near future?

https://www.amazon.com/Beginning-Xamarin-Development-Mac-Xamarin-iOS-ebook/dp/B078HQS883/
https://www.amazon.com/gp/product/B076T7FS1P?ref=dbs_p2d_P_R_popup_yes_pony_T1
https://docs.microsoft.com/en-us/xamarin/mac/

Thanks in advance!

**Comment by spouliot** [comment]
Microsoft documentation is in constant evolution and it's also open source so anyone, including you, can participate and provide better or more information and guides.

**Comment by shyamalschandra** [comment]
There is alot of nuanced notation (e.g. VS2019 Beta) in the syntax of C# for Mac/iOS/tvOS/watchOS.  There is no way to generalize to create your own code from scratch unless you know why there are changes.

**Comment by shyamalschandra** [comment]
For instance, there were changes to the C# code examples on github:

Why are there square brackets with contents inside them (e.g. [Export ("initWithLayer:")])?  Where's the reference for that change?  Is there a clearly-written release log with the syntax changes?

```
using System;
using System.Collections.Generic;
using System.Linq;
using CoreGraphics;
using System.Timers;

using Foundation;
using AppKit;
using CoreAnimation;
using CoreGraphics;

namespace AnimatedClock
{
	class ClockLayer : CALayer {
		public ClockLayer ()
		{
		}
		
		[Export ("initWithLayer:")]
		public ClockLayer (CALayer other)
			: base (other)
		{
		}
		
		public override void Clone (CALayer other)
		{
			ClockColor = ((ClockLayer) other).ClockColor;
			base.Clone (other);
		}
		
		[Export ("clockColor")]
		public CGColor ClockColor { get; set; }
		
		[Export ("needsDisplayForKey:")]
		static bool NeedsDisplayForKey (NSString key)
		{
			switch (key.ToString ()) {
			case "clockColor":
				return true;
			default:
				return CALayer.NeedsDisplayForKey (key);
			}
		}

		public override void DrawInContext (CGContext context)
		{
			base.DrawInContext (context);
			
			context.AddEllipseInRect (Bounds);
			context.SetFillColor (ClockColor);
			context.FillPath ();
		}
	}
}
```
