### ISSUE TITLE
Xamarin.Mac fail to register push notification

### ISSUE THREAD

**Issue by ObelixSoftware** [xamarin/xamarin-macios#5778]
### Steps to Reproduce

1. Working Xcode app attached written in Objective C
2. Failed Xamarin.Mac app attached

### Expected Behavior

Fire RegisteredForRemoteNotifications with device token for push notifications.

### Actual Behavior

Fire the FailedToRegisterForRemoteNotifications method with exception 

### Environment

```
=== Visual Studio Community 2019 Preview for Mac ===

Version 8.0 Preview (8.0 build 1805)
Installation UUID: d494562d-3cfd-4a9a-88bf-edefd0dee053
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518000248

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.0.248 (2018-08/a4956c837e1) (64-bit)
	Package version: 518000248

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.6
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.500/Sdks
SDK Versions:
	2.1.500
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.1.0.38 (Visual Studio Community)
Android SDK: /Users/lennie/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/lennie/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
1.8.0-9
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.11
Hash: 7c083b2
Branch: remotes/origin/d16-0
Build date: 2019-01-31 18:05:18 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin Designer ===

Version: 4.17.4.258
Hash: 32bf53413
Branch: remotes/origin/d16-0
Build date: 2019-01-23 17:25:28 UTC

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.11 (Visual Studio Community)
Hash: 5ef73d34
Branch: 
Build date: 2018-11-21 00:03:25-0500

=== Xamarin.iOS ===

Version: 12.2.1.11 (Visual Studio Community)
Hash: 5ef73d34
Branch: d15-9
Build date: 2018-11-21 00:03:24-0500

=== Build Information ===

Release ID: 800001805
Git revision: 976f9866afea4b6a99d4e875e9bf9b060a9f4024
Build date: 2019-01-31 18:09:53+00
Build branch: master
Xamarin extensions: 16ded92f644e8fcbad9a798adaab198a198dc651

=== Operating System ===

Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64


```

### Example Project

[MacPush.zip](https://github.com/xamarin/xamarin-macios/files/2973703/MacPush.zip)
[HelloMac.zip](https://github.com/xamarin/xamarin-macios/files/2973704/HelloMac.zip)

**Comment by spouliot** [comment]
Can you please clarify what exception you're seeing.

What I get "as-is" using the XM app is
```
Foundation.You_Should_Not_Call_base_In_This_Method: Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method' was thrown.
  at AppKit.NSApplicationDelegate.FailedToRegisterForRemoteNotifications (AppKit.NSApplication application, Foundation.NSError error) [0x00001] in /Users/poupou/git/master/xamarin-macios/src/build/mac/mobile/AppKit/NSApplicationDelegate.g.cs:787
  at MacPush.AppDelegate.FailedToRegisterForRemoteNotifications (AppKit.NSApplication application, Foundation.NSError error) [0x00001] in /Users/poupou/Downloads/MacPush/MacPush/AppDelegate.cs:20
  at at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain(int,string[])
  at AppKit.NSApplication.Main (System.String[] args) [0x00040] in /Users/poupou/git/master/xamarin-macios/src/AppKit/NSApplication.cs:100
  at MacPush.MainClass.Main (System.String[] args) [0x00007] in /Users/poupou/Downloads/MacPush/MacPush/Main.cs:10
```

which is _normal_ since your override is calling `base` on something that the OS does not provide you with a default implementation.

```csharp
        public override void FailedToRegisterForRemoteNotifications(NSApplication application, NSError error)
        {
            base.FailedToRegisterForRemoteNotifications(application, error);
        }
```

Replace this call with 
```csharp
System.Console.WriteLine (error.DebugDescription);
```

and you'll see this error in the application output
```
Error Domain=NSOSStatusErrorDomain Code=13 "Application not properly entitled for push notifications." UserInfo={NSDebugDescription=Application not properly entitled for push notifications.}
```

which makes sense as the project as the _default_ provisioning profile - which is not the same as your Xcode project is set.

**Comment by ObelixSoftware** [comment]
This is the MacPush sample that fail in Xamarin.Mac

<img width="765" alt="Screenshot 2019-03-20 at 17 53 06" src="https://user-images.githubusercontent.com/687793/54699111-1770d380-4b39-11e9-9af6-31da08971f81.png">

This one that is in Xcode that use the exact same provisioning profile pass

<img width="677" alt="Screenshot 2019-03-20 at 17 54 14" src="https://user-images.githubusercontent.com/687793/54699220-4d15bc80-4b39-11e9-99ec-3ea4a60a3ac2.png">

Both applications use the exact same Apple account, same provisioning profile etc.

**Comment by spouliot** [comment]
That's not what I got from the zip file but that's likely because the provisioning profile was not found (and VS4M did not show it).

Still your override of `FailedToRegisterForRemoteNotifications` is incorrect (calling `base`) and that will throw (by design since the OS does not provide a default code to call into).

It's possible that fixing the override will solve your problem since the error I get is about incorrect entitlement. 

Replace the call to `base` with the `Console.WriteLine` and, if things don't work, then you should get a hint about the failure (from `NSError` description).

**Comment by ObelixSoftware** [comment]
Am getting the following error that doesn't make sense to me since both apps use the same provisioning profile :

Error Domain=NSOSStatusErrorDomain Code=13 "Application not properly entitled for push notifications." UserInfo={NSDebugDescription=Application not properly entitled for push notifications.}

**Comment by spouliot** [comment]
Your Entitlement.plist is different from your Xcode and VSMac projects.

The former enabled sandboxing (not the issue) and Push Notification (see image)
<img width="850" alt="Screen Shot 2019-03-20 at 12 40 14 PM" src="https://user-images.githubusercontent.com/260465/54706683-7f112980-4b0d-11e9-8d1b-437868c2a0df.png">

Those entries are not in your VS4M project so the error message makes sense.

**Comment by ObelixSoftware** [comment]
The option to enable Push notifications under Entitlement is not available in Visual Studio for Mac. So how do I know what the entries must b?

**Comment by spouliot** [comment]
If I turn off **Push Notifications** in Xcode I get the same
```
2019-03-20 12:55:53.950603-0500 HelloMac[890:51812198] application:didFailToRegisterForRemoteNotificationsWithError: with error = Error Domain=NSOSStatusErrorDomain Code=13 "Application not properly entitled for push notifications." UserInfo={NSDebugDescription=Application not properly entitled for push notifications.}
```

**Comment by spouliot** [comment]
I'll file an issue about the missing UI. The extra XML content (in my case) is
```
	<key>com.apple.application-identifier</key>
	<string>DX9KVARB8M.com.poupou</string>
	<key>com.apple.developer.aps-environment</key>
	<string>development</string>
	<key>com.apple.developer.team-identifier</key>
	<string>DX9KVARB8M</string>
```

**Comment by ObelixSoftware** [comment]
I copied the entries over and tried again. Same error.

**Comment by spouliot** [comment]
You can't copy the above. You need to use your team identifier and application bundle name.

IOW the keys are correct but the values `DX9KVARB8M` and `DX9KVARB8M.com.poupou` needs to match your application and provisioning profile.

**Comment by ObelixSoftware** [comment]
Yes I did update it accordingly. Same error in the code.

**Comment by spouliot** [comment]
Do you have the entitlements file in your signing options ? (it might not be there since it was empty).

![Screen Shot 2019-03-20 at 1 46 14 PM](https://user-images.githubusercontent.com/260465/54710846-97397680-4b16-11e9-9b68-3807f2a2c97f.png)

I might have added it earlier while testing, but before I got it working...

**Comment by ObelixSoftware** [comment]
Problem resolved. 👍 

Thank you very much

**Comment by HenrikHolmIT** [comment]
Old topic but I'm currently trying to get Push Notifications to work on a MacOS Xamarin app but it just will not work. I'm getting all kinds of weird errors.

Is there a step by step guide available somewhere that describes the steps needed to get this working?

**Comment by CMarcher** [comment]
> Old topic but I'm currently trying to get Push Notifications to work on a MacOS Xamarin app but it just will not work. I'm getting all kinds of weird errors.
> 
> Is there a step by step guide available somewhere that describes the steps needed to get this working?
> 
> I've tried to follow this convo but when I select my Entitlements.plist on the project properties page my app will not start. App exits before any code has run and VS errors out with a message saying 'app crashed quickly'

Late, but for anyone facing this issue, it could be very well to do with your provisioning profile not being set up.
