### ISSUE TITLE
Getting 'pass.dll' and 'fail.dll' not found errors on building "dynamicload" sample

### ISSUE THREAD

**Issue by p-lad** [xamarin/xamarin-macios#5788]
### Build taken
Xamarin.iOS → https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xi-interpreter/b80d20ac447948b2574e73d57ab17dcf68e582fd/17/package/xamarin.ios-12.7.1.74.pkg

All the other build from Xamarin Preview Channel.

### Document Link

https://paper.dropbox.com/doc/Interpreter-Test-Instructions-lUU5inenHHqAKHhsgrkIO
https://paper.dropbox.com/doc/Xamarin.iOS-Interpreter-Preview-Blog-gqE9yzBaobBDxuTJgVkon

### Steps to Reproduce

1. Download the sample "dynamicload" from link https://github.com/spouliot/interpreter
2. Unzip the folder and load dynamicload.sln
3. Build sample

### Expected Behavior
Sample should build successfully

### Actual Behavior
Sample gives following error:
error :   Bundle Resource 'pass.dll' not found on disk (should be at /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(511,3): error :   Bundle Resource 'pass.dll' not found on disk (should be at '/Users/globallogic/Downloads/interpreter-master/dynamicload/dynloadios/pass.dll')
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(511,3): error :   Bundle Resource 'fail.dll' not found on disk (should be at '/Users/globallogic/Downloads/interpreter-master/dynamicload/dynloadios/fail.dll')

### Environment

```
https://gist.github.com/p-lad/3de0f52ea349e3dd4f0c5d1e3a09f364
[Ide.2019-03-19__13-15-18.log](https://github.com/xamarin/xamarin-macios/files/2982248/Ide.2019-03-19__13-15-18.log)

```

### Build Logs

https://gist.github.com/p-lad/8cbf1fdf5be0e64ff8c5d62427c41dee

### Regression
Not a Regression (Feature Testing)

### IDE Logs
[Ide.2019-03-19__13-15-18.log](https://github.com/xamarin/xamarin-macios/files/2982269/Ide.2019-03-19__13-15-18.log)

**Comment by p-lad** [comment]
This issue is also applicable for VS 2019

Workaround for this issue is:
Go the root directory of https://github.com/spouliot/interpreter and run the command this should do it: `msbuild dynamicload/pass/pass.csproj && cp dynamicload/pass/bin/Debug/pass.dll dynamicload/dynloadios/ && msbuild dynamicload/fail/fail.csproj && cp dynamicload/fail/bin/Debug/fail.dll dynamicload/dynloadios/`

This will not give error for missing .dll files

Thanks.

**Comment by spouliot** [comment]
It's by design (of the sample).

The sample wants to run code that is not part of the original project, so there's no reference to the other project (adding one would not test the same thing since mtouch would be aware of the code).

You have to build the "interpreted" assemblies project first (you can do it in the IDE, no need to use the command line) and then the main (iOS) project. I'll amend the sample documentation to mention this.
