### ISSUE TITLE
Getting 'customcode.dll' not found on building SubClass sample

### ISSUE THREAD

**Issue by p-lad** [xamarin/xamarin-macios#5789]
### Build Taken
Xamarin.iOS → https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xi-interpreter/b80d20ac447948b2574e73d57ab17dcf68e582fd/17/package/xamarin.ios-12.7.1.74.pkg

All the other build from Xamarin Preview Channel.

### Document Link
https://paper.dropbox.com/doc/Interpreter-Test-Instructions-lUU5inenHHqAKHhsgrkIO
https://paper.dropbox.com/doc/Xamarin.iOS-Interpreter-Preview-Blog-gqE9yzBaobBDxuTJgVkon

### Steps to Reproduce

1. Download the sample "SubClass" from link https://github.com/spouliot/interpreter
2. Unzip the folder and load subclass.sln
3. Build Sample

### Expected Behavior
Sample should build successfully

### Actual Behavior
Getting error:
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(511,3): error :   Bundle Resource 'customcode.dll' not found on disk (should be at '/Users/globallogic/Downloads/interpreter-master/subclass/customcode/bin/Debug/customcode.dll')

### Environment

```
https://gist.github.com/p-lad/a648ea5d5d46ee894bd6c03173af12b2
```

### Build Logs

https://gist.github.com/p-lad/07e7e5e33aeeb3f9c486be5e522240d2

### Regression
Not a Regression (Feature Testing)

### IDE logs
[Ide.2019-03-19__14-19-11.log](https://github.com/xamarin/xamarin-macios/files/2982407/Ide.2019-03-19__14-19-11.log)

**Comment by spouliot** [comment]
It's by design (of the sample).

The sample wants to run code that is not part of the original project, so there's no reference to the other project (adding one would not test the same thing since `mtouch` would be aware of the code).

I'll amend the sample documentation to mention this.
