### ISSUE TITLE
WkWebView not invoking C# function in Xamarin IOS

### ISSUE THREAD

**Issue by sameedtariq** [xamarin/xamarin-macios#5793]
### Steps to Reproduce

1. Build an application in IOS device (iPhone)
2. Load an initial template on the first page (Main Page).
3. Load a second template on the first page (Main Page) from the second page.  
4. Hit the button to invoke C# function from JavaScript.

**Note**: The C# function is always invoked from the default template loaded first time in WkWebView.  

### Expected Behavior
The WkWebView should invoke C# function from JavasScript when a new template is loaded
### Actual Behavior
The C# function is invoked sometimes and sometimes it does not. The sequence of code execution remains the same. 

### Environment

1. IOS 11 (iPhone)

```

[assembly: ExportRenderer (typeof(HybridWebView), typeof(HybridWebViewRenderer))]
namespace Osram.Demo.iPad
{
    public class HybridWebViewRenderer : ViewRenderer<HybridWebView, WKWebView>, IWKScriptMessageHandler
    {
        const string JavaScriptFunction = "function invokeCSharpAction(data){window.webkit.messageHandlers.invokeAction.postMessage(data);}";
        WKUserContentController userController;
        ILogUtils log = DependencyService.Get<ILogUtils>();
        private WKWebView webView;

        protected override void OnElementChanged(ElementChangedEventArgs<HybridWebView> e)
        {
            base.OnElementChanged(e);

            if (Control == null)
            {
                
                userController = new WKUserContentController();
                var script = new WKUserScript(new NSString(JavaScriptFunction), WKUserScriptInjectionTime.AtDocumentEnd, false);
                userController.AddUserScript(script);
                userController.AddScriptMessageHandler(this, "invokeAction");
                

                var config = new WKWebViewConfiguration { UserContentController = userController };
                webView = new WKWebView(Frame, config);
                //custom delegate for enabling alert
                webView.UIDelegate = new MyWKWebViewDelegate();
               // webView.NavigationDelegate = new MyWKNavigationDelegate();
                SetNativeControl(webView);
                
            }
            if (e.OldElement != null)
            {
                e.OldElement.PageChange -= UpdateUri;
                userController.RemoveAllUserScripts();
                userController.RemoveScriptMessageHandler("invokeAction");     
                var hybridWebView = e.OldElement as HybridWebView;
                hybridWebView.Cleanup();
            }
            if (e.NewElement != null)
            {
                
                e.NewElement.PageChange += UpdateUri;
                //e.NewElement.PropertyChanged += HybridWebView_PropertyChanged;

            }
        }

        private void HybridWebView_PropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            Console.WriteLine("Working");
            
        }

        //this method gets called when invokeCSharpAction(data) in javascript gets called
        public void DidReceiveScriptMessage(WKUserContentController userContentController, WKScriptMessage message)
        {
            //send data to arduino
            Console.WriteLine("Data Send to Arduino "+ message.Body.ToString());
            BluetoothManager.SendData(message.Body.ToString());
            
        }

        public void UpdateUri(object sender, PageChangeEventArgs e)
        {
            try
            {           
                string filePath = Path.Combine(AppConstants.IOS_DIRECTORY, e.Uri);
                //this is the path for the assets
                //string filePath = Path.Combine(NSBundle.MainBundle.BundlePath, string.Format("Content/{0}", e.Uri));

                //this method tests if all files exist
                //bool allFilesExist = DoAllFilesExist();
                //if (!allFilesExist)
                //{
                //    log.Log("HybridWebViewRenderer.UpdateUri: Error - Not all files exist locally!");
                //}

                //this method tests if you can iterate from the .../index.html to the .../js/ files
                //IterateDirectories(filePath);

                bool fileExist = File.Exists(filePath);
                if (fileExist)
                {
                    /*  If you want to use external local files(js, css, ...) you have to give the file the access to read the whole directory
                       --> LoadFileUrl( url: filePath , allowingReadAccessTo: AppConstants.IOS_DIRECTORY
                     */
                    Control.LoadFileUrl(new NSUrl(filePath, false), new NSUrl(AppConstants.IOS_DIRECTORY, true));
                }
                else
                {
                    Control.LoadHtmlString("<p>Error: File doesn't exist</p>", null);
                    log.Log("HybridWebViewRenderer.UpdateUri: Error - File does not exist");
                }
                              

            }
            catch (Exception ex)
            {
                //When there is a Error loading the file, load the following HTML-ErrorMessage
                //log.Log("HybridWebViewRenderer.UpdateUri: " + ex.Message);
                Control.LoadHtmlString("<p>Error</p>", null);
                log.Log("HybridWebViewRenderer.UpdateUri: " + ex.Message);

            }
        }

       

        public bool DoAllFilesExist()
        {
            iOSFileHandler handler = new iOSFileHandler();
            return handler.checkIfAllFilesAvailable(AppConstants.IOS_DIRECTORY);
        }

        public void IterateDirectories(string filePath)
        {
            try
            {
                string abc = Path.GetDirectoryName(filePath);
                string[] abcFiles = Directory.GetFiles(abc);
                string documents = Path.GetDirectoryName(abc);
                string[] documentChildFolders = Directory.GetDirectories(documents);

                string js = Path.Combine(documents, "js");
                string[] jsFiles = Directory.GetFiles(js);
                for(int i=0; i < jsFiles.Length; i++)
                {
                    string content = File.ReadAllText(jsFiles[i]);
                }
            }            
            catch(Exception e)
            {

            }
        }
    }
    
}
```

### Example Project (If Possible)

1. https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/HybridWebView

**Comment by spouliot** [comment]
It's not clear if this is a bug and, if it is, if it's related to the custom renderer (in XF) or Xamarin.iOS.
Please add a self-contained test case and include which versions of the product you used. Thanks.

**Comment by sameedtariq** [comment]
The IOS version is 11.1.2 in A1457 - iPhone 5s. Can you please elaborate on the self-contained test case. I already mentioned the second scenarios in which  //this method gets called when invokeCSharpAction(data) in javascript gets called
       ` DidReceiveScriptMessage(WKUserContentController userContentController, WKScriptMessage message)` is not invoked when the different template is loaded.

**Comment by spouliot** [comment]
We need the version of our products (not iOS). That's part of the issue template, i.e.

```
1.
Visual Studio: Help > About Microsoft Visual Studio > Copy Info [button]
Visual Studio for Mac: Visual Studio > About Visual Studio > Show Details > Copy Information [button]
2. Paste into the code block below (between ```)
```

A self-contained test case is either a project on GitHub or in an attached zip file that we can build and confirm (with the above) product that we get the same results.

From there we'll be able to see if it's an issue or not. Thanks!

**Comment by sameedtariq** [comment]
The info is given below. I will ask my supervisor to upload the code on GitHub repository and share it on a public forum. Is there any way to share code privately. 

Microsoft Visual Studio Community 2017 
Version 15.9.3
VisualStudio.15.Release/15.9.3+28307.145
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA462
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.11-pre (400cfb1)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.73 (d15-9@20b35b881)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.5 (6b9f32067)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.127 (e975299)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.0.38 (HEAD/61d16aa23)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.11 (5ef73d3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by spouliot** [comment]
It's often simpler (both for debugging and approval) if you can remove as much code as possible from the application before zipping (or creating a repo).

**Comment by spouliot** [comment]
We have not received the requested information. If you can provide a test case please re-open the issue. Thanks!
