### ISSUE TITLE
Unhandled exception while copying ObservableCollection to List

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#5805]
### Steps to Reproduce
I've got the error from the App Center report, so I can't say how to reproduce it but it obviously happens in the Xamarin code.

What the app does is that it copies the ObservableCollection to the List with ToList() method as you will see in the crash report below.

### Expected Behavior
It would be expected that this work. If it is needs to crash it should send less cryptic message

### Actual Behavior
This is the crash report:
Array.Copy (System.Array sourceArray, System.Int32 sourceIndex, System.Array destinationArray, System.Int32 destinationIndex, System.Int32 length)
Destination array was not long enough. Check destIndex and length, and the array's lower bounds
Array.Copy (System.Array sourceArray, System.Int32 sourceIndex, System.Array destinationArray, System.Int32 destinationIndex, System.Int32 length)
List`1[T].CopyTo (T_REF[] array, System.Int32 arrayIndex)
Collection`1[T].CopyTo (T_REF[] array, System.Int32 index)
System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) <0x10476c774 + 0x000f3> in <2b439461a53d406abf16d6e5e34ece7f#b36d1afe6b432fea26ad687582c8a2ab>:0
Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source)
### Environment

```
Microsoft Visual Studio Community 2017 
Version 15.9.9
VisualStudio.15.Release/15.9.9+28307.518
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA347
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.9.02046.0
Azure Functions and Web Jobs Tools

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

File Differ   1.4.25
The easiest way to diff two files directly in Solution Explorer

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

Multilingual App Toolkit   4.0
Multilingual App Toolkit helps you localize your Windows Store app by providing file management, pseudo and machine translation, translation editor, and build integration. http://aka.ms/matinstall

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61903.01040
Microsoft SQL Server Data Tools

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.489
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.80 (d15-9@914127c74)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.15 (d60abd1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by spouliot** [comment]
`Destination array was not long enough.` that's an exception, not a _direct_ crash. It might lead to a crash if nothing handles it. 

As to why ? there's not enough details here to know if it's related to user code or to the BCL code (the stack trace is incomplete).

Ideally we would need a test case but minimally the full stack trace along with the symbolication crash report along with all your build options (or build logs).

**Comment by ivanicin** [comment]
If you ask me why, I would have to guess that the ObservableCollection has been changed while copying to the list, that is the only possible problem that I can see. But if that was the case there should be some other exception raised IMHO.

The remaining part of the stacktrace shows that there is a timer in my app that activates one method which then calls ToList. As ToList raises exception so it is raised in Xamarin's code not in the app code, it is quite clear IMHO, if you have any doubt on why it could be app's bug please share as according to my knowledge I can't see any such possibilities.

So the remaining stacktrace is:
VModel+<reorderPlayItems>d__472.MoveNext ()
VModel+<<askReorderPlayItems>b__471_0>d.MoveNext ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state)
QueueUserWorkItemCallback.WaitCallback_Context (System.Object state)
ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
IThreadPoolWorkItem.ExecuteWorkItem ()
ThreadPoolWorkQueue.Dispatch ()
Runtime.ThreadPoolDispatcher (System.Func`1[TResult] callback)
_ThreadPoolWaitCallback.PerformWaitCallback ()

**Comment by spouliot** [comment]
There's no doubt the exception is raised from the BCL code - but it's very likely raised because of application code. E.g. if it's threaded then it's possible that the number of items has changed during the copying, i.e. that would explain a `Destination array was not long enough.` exception.

Again having the requested information will help us diagnose the issue.

**Comment by ivanicin** [comment]
Yes, it would be theoretically possible that the number of items has changed during the copy, that's what I do suggest. It is like that by design as it is highly improbable and most users will never face this problem in the app in their entire life, while all users together will probably see them just once in many years.

So for now if we agree that this is most likely cause that we should accept as valid for now, then I hope you also agree that the exception should be more clear regarding that - if it was more clear we wouldn't have even to guess what the problem is, so take this as a request to improve on that.

**Comment by spouliot** [comment]
I don't see how that specific code can know if the input is incorrect or if the collection size changed between calls. This situation is not unique and many .net types are documented for this, e.g.

_A Collection<T> can support multiple readers concurrently, as long as the collection is not modified. Even so, enumerating through a collection is intrinsically not a thread-safe procedure. To guarantee thread safety during enumeration, you can lock the collection during the entire enumeration. To allow the collection to be accessed by multiple threads for reading and writing, you must implement your own synchronization._

https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1?view=netframework-4.7.2#thread-safety

The BCL code used in Xamarin.iOS (and other SDK) is is shared code with coreclr so you might want to suggest changes in https://github.com/dotnet/coreclr
