### ISSUE TITLE
Add padding to UILabel control

### ISSUE THREAD

**Issue by MookieFumi** [xamarin/xamarin-macios#5863]
### Steps to Reproduce

1. It's a new feature related with [an existing issue in the Xamarin.Forms repo](https://github.com/xamarin/Xamarin.Forms/issues/4784) because it's useful in a Xamarin Forms app avoid extra Layouts so we should have available a Padding property.

`<Label
            BackgroundColor="Silver"
            Text="Welcome to Xamarin.Forms!"
            Padding="20"/>`

2. I've been researching and the UILabel control doesn't have any property to do it.

### Expected Behavior

The **UILabel** should have a property to add **padding** and I've checked it and there's a type called **UIEdgeInsets** to get it.

### Actual Behavior

No padding in UILabel without creating extra layouts.

### Example Project (If Possible)

[PaddeableLabel.zip](https://github.com/xamarin/xamarin-macios/files/3051562/PaddeableLabel.zip)

**Comment by rolfbjarne** [comment]
We only bind the API Apple/iOS provides, so if you want to be able to specify padding for a UILabel control, you have to [ask Apple](https://bugreport.apple.com) to implement it.

It seems the most common workaround is to subclass UILabel and add this functionality yourself:

* https://stackoverflow.com/a/5155382/183422
* https://blog.chrishannah.me/adding-insets-to-a-uilabel/
