### ISSUE TITLE
[XM] `LoadNibNamed` adds extra NSApplication object to the result array

### ISSUE THREAD

**Issue by mykyta-bondarenko-gl** [xamarin/xamarin-macios#5866]
### Steps to Reproduce

1. Download a sample 
[sample](https://github.com/xamarin/xamarin-macios/files/3053631/NibIssue.zip)
2. Open `ViewController.cs` file and put a breakpoint to line 20. 
3. Run the application

**Reproducibility is not 100%.**

### Expected Behavior
Variable `view` is `TestView`

### Actual Behavior
Variable `view` is `NSApplication`

![Screen Shot 2019-04-08 at 12 28 48](https://user-images.githubusercontent.com/32954580/55714000-833cb280-59fa-11e9-950e-c5d77258997c.png)

### Environment

1. Xcode 10.1 or 10.2 (no matter)
2. VSfM
https://gist.github.com/mykyta-bondarenko-gl/442f017eb6fe994494ef3533d3b3e0f7

### Build Logs

1. Output
https://gist.github.com/mykyta-bondarenko-gl/a39671a9e4f9749e2792a6c6709378ab
2. System Log
https://gist.github.com/mykyta-bondarenko-gl/2161311c410d51b3de05be9732216b65
3. Ide.log
https://gist.github.com/mykyta-bondarenko-gl/3ade78a986168dbf9d87616e2c66e9a4

### Example Project

[Sample](https://github.com/xamarin/xamarin-macios/files/3053631/NibIssue.zip)

**Comment by chamons** [comment]
This line is wrong:

```var view = array.GetItem<TestView>(0);```

as you can see in the screenshot

![Screen Shot 2019-04-08 at 9 33 29 AM](https://user-images.githubusercontent.com/6392201/55732348-7069b400-59e1-11e9-8832-6dbfa36bb99d.png)

your view is not element 0 in the array. This is how Apple handles things for some reason when inflating a xib. You'll need to start at element 1 or walk list looking for specific class.
