### ISSUE TITLE
[MT5201] Native linking fails for iOS project - SDK version 12.2, xCode 10.2

### ISSUE THREAD

**Issue by spatialguy** [xamarin/xamarin-macios#5880]
### Steps to Reproduce

1. This issue happens on Mac with xCode 10.2 (10E125)
2. Open the attached project in Visual Studio 2019 for Mac (stable  vs. preview version does not seem to make any difference)
3. Build the project for iOS simulator

> The project uses google maps so google maps key is required for proper functionality - i replaced mine with [INSERT GOOGLE MAPS KEY HERE] string in android manifest and ios app delegate.

### Expected Behavior
App should build and run successfully

### Actual Behavior
Build error:

```shell
error MT5209 : Native linking error : targeted OS version does not support use of thread local variables in __ZN9GMSx_absl18container_internal21ShouldInsertBackwardsEmPa for architecture x86_64
MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -ObjC -ObjC -ObjC -lc++ -lz
```

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.0 (build 3001)
Installation UUID: f41f244d-5f3a-44db-b12c-9abfc88ae9ba
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)
	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.3
	2.2.1
	2.1.6
	2.1.5
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.0
	1.0.1
SDK: /usr/local/share/dotnet/sdk/2.2.105/Sdks
SDK Versions:
	2.2.105
	2.2.103
	2.1.500
	2.1.403
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.0-preview2-1-003177
	1.0.0-preview2-003131
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.2.0.5 (Visual Studio Community)
Android SDK: /Users/petrpokorny/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ad371dab1b
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/master@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/petrpokorny/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-03-27 18:41:02 UTC

=== Apple Developer Tools ===

Xcode 10.2 (14490.120)
Build 10E125

=== Xamarin.Mac ===

Version: 5.6.0.25 (Visual Studio Community)
Hash: 50f75273
Branch: d16-0
Build date: 2019-03-05 11:50:33-0800

=== Xamarin.iOS ===

Version: 12.6.0.25 (Visual Studio Community)
Hash: 50f75273
Branch: d16-0
Build date: 2019-03-05 11:50:33-0800

=== Xamarin Designer ===

Version: 4.17.4.414
Hash: 55b8d07ef
Branch: remotes/origin/d16-0
Build date: 2019-03-22 21:44:12 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800003001
Git revision: 16b11d379aeff65cd1e81d3616c267ad4251ad36
Build date: 2019-03-28 13:14:24+00
Build branch: master
Xamarin extensions: efad41c7f410d8e6d43361236e0e778cf6f9b4a5

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

LiveXAML 1.3.50
XAMLator 1.0.7
```
```

### Build Logs
[BuildLog.txt.zip](https://github.com/xamarin/xamarin-macios/files/3060294/BuildLog.txt.zip)

### Example Project (If Possible)
[TrackerSample.zip](https://github.com/xamarin/xamarin-macios/files/3060280/TrackerSample.zip)

**Comment by rolfbjarne** [comment]
You need to update the minimum deployment target in your project to iOS 9.0+, because Google dropped support for iOS 8: https://github.com/xamarin/GoogleApisForiOSComponents/issues/255

**Comment by spatialguy** [comment]
@rolfbjarne thank you very much for your help!
