### ISSUE TITLE
xcode 10.2 is currently selected in preferences and is currently incompatible

### ISSUE THREAD

**Issue by abusalaa7** [xamarin/xamarin-macios#5885]
### Steps to Reproduce

1. Install VS 2019 for mac on macOS 10.13.6
2. Update will install the latest xamarin.ios v12
3. The latest xamarin.ios requires xcode 10.2
4. xcode 10.2 can't be installed on mac os high sierra and no way to downgrade back to xamarin.iosv11

### Expected Behavior
Update to xamarin.ios shouldn't have run in the first place or at least an easy way to downgrade should be available
### Actual Behavior
Stuck with an error and xamarin.ios app won't compile. Error says "xcode 10.2 is currently selected in preferences and is currently incompatible". Latest xcode available for macOS I'm running is 10.1.
### Environment
macOS 10.13.6

```
=== Visual Studio Community 2019 for Mac ===

Version 8.0.2 (build 23)
Installation UUID: 00fc1179-97ba-4461-966e-4887ef0d7996
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.3
	2.1.8
SDK: /usr/local/share/dotnet/sdk/2.2.105/Sdks
SDK Versions:
	2.2.105
	2.1.504
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.2.0.5 (Visual Studio Community)
Android SDK: /Users/ahmedmansour/Library/Android/sdk
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ad371dab1b
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/master@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/ahmedmansour/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-04-05 16:58:56 UTC

=== Xamarin Designer ===

Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 12.8.0.0 (Visual Studio Community)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800020023
Git revision: c576bb008dfe54cdcf596237e09564ebd2da4343
Build date: 2019-04-06 10:06:46+00
Build branch: master
Xamarin extensions: 2c996830618e7cb8e8be97984d643eb86f122e8d

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Wed Feb 27 00:43:23 PST 2019
    root:xnu-4570.71.35~1/RELEASE_X86_64 x86_64


```

**Comment by rolfbjarne** [comment]
Is there any particular reason you can't upgrade to Mojave?

**Comment by skir** [comment]
Hello, I have the same issue.
I use an old iMac (late 2009). It is a great machine, with good performance. I don't see any reasons to upgrade it to something newer, except it is not supported by Mojave update.

**Comment by abusalaa7** [comment]
I have a mac from 2011 that’s ineligible for mojave update.


________________________________

**Comment by rolfbjarne** [comment]
I'll try to figure out a way to downgrade to the previous version of Visual Studio for Mac.

Although if you're publishing to the App Store, have in mind that Apple will likely require you to build with Xcode 10.2 later this year.

**Comment by rolfbjarne** [comment]
In the meantime you can downgrade your version of Xamarin.iOS to the previous stable version.

You can find packages on GitHub: https://github.com/xamarin/xamarin-macios/commits/d15-9, click on the green checkmark for the topmost commit, and download the [xamarin.ios-12.2.1.16.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d15-9/2dc06c712629feeb179ed112a590d9922caac6e7/53/package/xamarin.ios-12.2.1.16.pkg) package.

While technically it's not a supported configuration to use Visual Studio for Mac 8.0 with the previous stable version of Xamarin.iOS, I believe it'll work fine.

**Comment by abusalaa7** [comment]
Works fine so far. Thank you.


________________________________

**Comment by gonzajaimes** [comment]
Does this mean that we have to buy a new MacBook Pro ???  I also have a 2011 Mac Book Pro.   I don´t have the money to buy a new computer as mine works and run just fine,   this is unbelievable!

**Comment by rolfbjarne** [comment]
> I'll try to figure out a way to downgrade to the previous version of Visual Studio for Mac.

You can download Visual Studio for Mac 2017 (v7.8) from here: https://aka.ms/vs/mac/2017-download

@gonzajaimes Unfortunately there's not much we can do once Apple makes Xcode 10.2 a requirement for shipping apps to the App Store.

**Comment by cmroanirgo** [comment]
Visual Studio upgraded me to 8.3 (from 7.x) and it's incompatible with High Sierra. Upgrading an OS for the sake of a build tool is not a valid solution. My XCode is 10.1 and it runs fine (and is the latest release I can put onto my machine). What doesn't work is this whole xamarin platform.

**Comment by rolfbjarne** [comment]
@cmroanirgo you can install the older versions of Visual Studio for Mac and Xamarin.iOS manually, and then disable automatic updates in Visual Studio for Mac.

**Comment by cmroanirgo** [comment]
@rolfbjarne sadly this is not true. The link you specify downloads the same "visual studio installer" as you get from the front page of MS's visual studio: both always downloads and installs the latest.

**Comment by rolfbjarne** [comment]
@cmroanirgo try this: [visualstudioformac-7.8.4.1.dmg](https://download.visualstudio.microsoft.com/download/pr/bc3fb5bd-c066-47fd-8563-b9c54f8b5e91/a8ea761ac1c65beedc9564aded3d1458/visualstudioformac-7.8.4.1.dmg).

**Comment by aestsoftware** [comment]
version 8.3.5(build 13) 
update visual studio for mac give the same error one again 
error this 
(Search/Find FindAccountsForServiceAsync Object reference not set to an instance of an object)
plz resolve it my old xamarin app is not working for this error last time i have to install and download the xamarin.ios-12.2.1.16.pkg package.
