### ISSUE TITLE
Launching in earlier simulator versions crash upon launch

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#5888]
### Steps to Reproduce

1. Create a new iOS single view app.
2. Change the deployment target to iOS 8.0.
3. Run in an iOS 8 or iOS 9 simulator.

### Expected Behavior

Successful launch.

### Actual Behavior

Crash:

```
Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
  Referenced from: /System/Library/Frameworks/Intents.framework/Intents
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices: mach-o, but not built for iOS simulator
```

[Complete crash report](https://gist.github.com/rolfbjarne/1c87042cb1a0f089377f151cba2fed50)

What happens is that macOS launches the app, and can't find the Intents framework in the simulator runtime. For some reason, macOS decides to look on the Mac as well, and lo and behold, the Intents framework is there! Unfortunately it's not compatible, so things fail.

It's trivial to reproduce the same problem in Xcode: http://openradar.appspot.com/radar?id=6149006350614528

### Environment

macOS Mojave
Xcode 10.2
Xamarin.iOS 12.4+

**Comment by rolfbjarne** [comment]
Workaround: change the `Linker behavior` in the iOS project's Build options to `Link Framework SDKs only` _and_ add `--registrar:static` to the additional mtouch arguments in the same Build options page.

**Comment by djseng** [comment]
Thanks. Relief from a couple of days of hair pulling.
