### ISSUE TITLE
Investigate removal of repl (monotouch_runtime) assemblies

### ISSUE THREAD

**Issue by akoeplinger** [xamarin/xamarin-macios#5889]
If possible we should remove the special repl assemblies (they're not well tested on the mono side, e.g. https://github.com/mono/mono/issues/13526) and with the interpreter etc. we might not need them anymore.

Marek asked me to file this issue to see what it would take to remove them in the future.

/cc @marek-safar @rolfbjarne

**Comment by spouliot** [comment]
We're actually using those REPL assemblies for the interpreter (so they will get tested) so the AOT-only builds don't have SRE bits (or that they throws `PlatformNotSupportedException`) and continue to use the SLE interpreter.

Also I'm not 100% sure but I think they are also used for the designer. c.c. @alanmcgovern @chkn 

In order to remove them we'll need to find a way that do not penalize (app size and build time) the normal AOT builds.

**Comment by marek-safar** [comment]
A few things to clarify
- SLE Interpreter is obsolete and should not be used (one of the reasons why we worked on the general interpreter was to fix the bugs there).
- The size numbers we tried showed that SLE interpreter was about the same size as correctly linked interpreter + SRE
- We already have an option to force the removal of SRE in the linker
- I think we now always build runtime with reflection emit enabled

**Comment by spouliot** [comment]
@marek-safar that does not match the sizes I've seen in the interpreter branch but things might have changed in mono/master... Do you have those numbers/test case somewhere ? 

Also SRE runtime code is not enabled in device builds in `xamarin-macios/master`

**Comment by chkn** [comment]
Looks like the designer just switched to the repl assemblies a couple months ago: https://github.com/xamarin/designer/commit/1ef2d700cea5882b49a21c38bc040d8c3dd563e7

This was just for higher performance for SLE. We are not using SRE to my knowledge, but it would be good to have it enabled anyway, as user code might start calling into it now.

**Comment by marek-safar** [comment]
> Also SRE runtime code is not enabled in device builds in xamarin-macios/master

Does it mean there is still no support for SRE in XI?

@chkn performance wise native interpreter for SLE will be much faster than managed one

**Comment by alanmcgovern** [comment]
As in the commit @chkn referenced:

```
[build] Use the repl version of mscorlib

This gives us the Reflection.Emit APIs we want to use.
```

The previewer does use reflection emit APIs which are not available in the non-repl assemblies. If all the reflection emit APIs we need are put in the non-repl assemblies then we can definitely stop using the repl versions.

/cc @drewgillies @TimBarham

**Comment by rolfbjarne** [comment]
This is not relevant in .NET.
