### ISSUE TITLE
Xamarin.Mac Notary Support

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5896]
MacOS Notary support is something we've known about [for awhile](https://github.com/xamarin/xamarin-macios/issues/4288), specifically related to the hardened runtime requirement. 

However, [Apple announced](https://developer.apple.com/news/?id=04102019a) a specific release and a top level issue tracking the progress would be useful.

**Comment by chamons** [comment]
Current Status:
- It was believe that support was complete awhile ago, but a crash was found when using System.Reflection.Emit or some delegate constructs last week.
- [d16-1 branch](https://github.com/xamarin/xamarin-macios/commits/d16-1) latest commit has a fix it.
- It also has `<UseHardenedRuntime>true</UseHardenedRuntime>` msbuild support.
- It does _not_ yet have IDE support for that option or the associated entitlements. That work is scheduled.

**Comment by chamons** [comment]
Rough steps to update a project:

- Open your application and confirm that codesigning with an entitlement file is enabled for Release builds. Make sure your application launches successfully. 
- Use d16-1 build noted above.
- Open your Xamarin.Mac application csproj and add `<UseHardenedRuntime>true</UseHardenedRuntime>` to the Release section
- Open your entitlement file and add
```
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
```
- Build and test release build.

Here is Apple's documentation on submitting to the notary:
- https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/customizing_the_notarization_workflow?language=objc#3087734
- https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/customizing_the_notarization_workflow?language=objc#3087720

This were the (app specific) commands I used to test it:

```$xcrun altool --notarize-app --primary-bundle-id "com.xamarin.test.XMAppForNotary" --username "MY_EMAIL" --password "@keychain:AC_PASSWORD" --file XMAppForNotary-1.0.pkg```

```$ xcrun stapler staple "XMAppForNotary-1.0.pkg"```

The `@keychain:AC_PASSWORD` magic is describe in this documentation linked above, and looks into keychain for the password.

**Comment by achuchev** [comment]
@chamons Thanks for the good summary!
Do you know when the change from will be officially released?
How can I get a build from d16-1 branch?

**Comment by chamons** [comment]
The steps to download a build are on [the wiki](https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build) in general. 

However [the blog](https://devblogs.microsoft.com/xamarin/macos-hardened-runtime-notary/) links to a specific build.

You can get that build [here](https://dl.xamarin.com/uploads/ukw5a1stfj5/xamarin.mac-5.10.0.148.pkg).

**Comment by chamons** [comment]
d16-1 is in preview channel now. You can read about the VS release cycle [here](https://docs.microsoft.com/en-us/visualstudio/productinfo/release-rhythm). I don't have a concrete date I can share now, but within a few months is a good guess.

**Comment by achuchev** [comment]
@chamons Thanks!

**Comment by chamons** [comment]
d16-1 is currently in the Alpha and Beta channels, and scheduled to hit stable at some point. I'm going to close this issue now that support is available.
