### ISSUE TITLE
visual studio 2019 for mac unable to determine simulator version

### ISSUE THREAD

**Issue by urnanda** [xamarin/xamarin-macios#5897]
OS 14.4
Visual Studio 2019
Xcode 10.1 
Xcode 10.2

UT Test cases are NOT working after upgrade

> VS bug [#847992](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/847992)

**Comment by joj** [comment]
Hi! I this still an issue? We fixed simulator discovery for the latest release of Xcode (including previous versions) so it might be fixed by that.

**Comment by joj** [comment]
We don't have enough info to investigate this. Please reopen if needed. Thanks! J
