### ISSUE TITLE
[Packaging ]License is not present in the release package.

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#5902]
The project license is not where to be found after installation.

### Steps to Reproduce

1. Install Xamarin.iOS or Xamarin.Mac package.
2. Try to find the License or the project.

### Expected Behavior

Install the package and be able to find the license.

### Actual Behavior

License is missing.

### Environment

Can be reproduce in current master: https://github.com/xamarin/xamarin-macios/commit/d4e41445a20d8b1655c2db07e71bbadb40fbeb4b

**Comment by chamons** [comment]
It has been decided that it is not necessary, the IDE will handle this.
