### ISSUE TITLE
Missing test coverage for XI ArchiveOnBuild builds and incomplete tests in XM as well

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5903]
This was merged with a half baked test:

https://github.com/xamarin/xamarin-macios/pull/5862

And I found out we don't have a single XI test for this use case.

We should have something to at least build that configuration for XI and XM.

**Comment by rolfbjarne** [comment]
We have tests for `ArchiveOnBuild` now for .NET.
