### ISSUE TITLE
Xcode 10.x: list of changes to be reviewed/reverted before final release

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#5906]
**Xcode 10 (pending rdar update)**

* [ ] rdar://41135211: RPSystemBroadcastPickerView is not available on sim. Still failing with Xcode 10.2.

**Comment by chamons** [comment]
So Xcode 10.x and 11.x went out the door, so we're way past when this issue would be able to affect our bindings. 

@spouliot - Feel free to reopen if necessary.
