### ISSUE TITLE
Xamarin.iOS will be incompatible with older macs because we cannot update to Xcode 10.2

### ISSUE THREAD

**Issue by gonzajaimes** [xamarin/xamarin-macios#5911]
### Steps to Reproduce

1. Install VS 2019 for mac on macOS 10.13.6
2. Update will install the latest xamarin.ios v12
3. The latest xamarin.ios requires xcode 10.2
4. xcode 10.2 can't be installed on mac os high sierra 

### Expected Behavior

Being able to build for the latest iOS version without having to buy a new computer

### Actual Behavior

Stuck with an error and xamarin.ios app won't compile. Error says "xcode 10.2 is currently selected in preferences and is currently incompatible". Latest xcode available for macOS I'm running is 10.1.

### Environment

```
Visual Studio Community 2019 for Mac
Version 8.0.3 (build 14)
Installation UUID: ba3a324d-e621-483b-b38c-c5d15e3a57c2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

Mono Framework MDK
Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

NuGet
Versión: 4.8.2.5835

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Versiones de tiempo de ejecución:
	2.1.9
	2.1.8
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
Versiones del SDK:
	2.1.505
	2.1.504
	2.1.302
	2.1.301
SDK de MSBuild: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Versión: 1.6.9
Ubicación: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Versión: 11

Xamarin.Android
Versión: 9.2.0.5 (Visual Studio Community)
Android SDK: /Users/gonzajaimes/Library/Android/sdk
	Versiones de Android admitidas:
		5.0 (nivel de API 21)
		8.1 (nivel de API 27)

Versión de SDK Tools: 26.1.1
Versión de las herramientas de plataforma del SDK: 28.0.0
Versión de las herramientas de compilación del SDK: 27.0.3

```

**Comment by chamons** [comment]
Please read the following documentation:

https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/old-version-xcode

It is possible to work around this on older macOS, for a time. 

However, you'll need to install the older Xcode (available at http://developer.apple.com/) and possibly an older Xamarin.iOS. 

There are a number of consequences of not using the latest, and the document discusses them in detail.

In the end however, Apple strongly wants people to use the newest Xcode when submitting to their store and sets the required macOS versions. There isn't much we can do about that for you.

**Comment by davidglassborow** [comment]
I've also had this issue, and solved it by installing the previous Xamarin.iOS version from here: https://jenkins.xamarin.com/view/Xamarin.MaciOS/job/xamarin-macios-builds-master/
