### ISSUE TITLE
[Bug] Video from local storage not playing in WebView (Xamarin.Forms, iOS) after latest iOS update (12.2)

### ISSUE THREAD

**Issue by anakochevska** [xamarin/xamarin-macios#5920]
### Description

I have an existing Xamarin Forms application, for Android and iOS, which shows some HTML content from local storage (the purpose is to view this content while offline) in WebView.

After the latest iOS update (12.2), the videos in that HTML stopped working. White background is shown on the place of the video, with the symbol "Play" but no action is possible.

I have tried changing the video tags to include autoplay, mute, etc but no success.

### Steps to Reproduce

1. Create a simple local HTML file, that has HTML5 video tag. 
2. Set the source of the video tag also from a local storage
3. Set the source of the WebView to the local HTML. 
4. Run it on iOS device. 
`<video width="560" height="315" controls>`
`<source src="Absolute-3D.mp4" type="video/mp4">`
`</video>`

### Expected Behavior
It should show the video with the option to play/pause/stop. 
### Actual Behavior
It shows blank space, with only the play icon and clicking the icon doesn't do anything. 
### Basic Information

- Version with issue: 
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  12.2
- Affected Devices: Every iOS device. 

### Screenshots

https://i.imgur.com/sVXEmxX.jpg

**Comment by mairi17** [comment]
I'm seeing the same issue on a non-Xamarin iOS project.

**Comment by chamons** [comment]
I believe this is due to https://webkit.org/blog/6784/new-video-policies-for-ios/

and is completely unrelated to Xamarin.iOS or Xamarin.Forms.

At the point we're hitting the video, it's a webview and safari is smacking your hand. We're just hosting that WebView.
