### ISSUE TITLE
DangerousRetain is never called

### ISSUE THREAD

**Issue by clintonrocksmith** [xamarin/xamarin-macios#5950]
https://github.com/xamarin/xamarin-macios/blob/66ba411303205bb1638451f93cc9c588ce02a241/src/UIKit/UIGestureRecognizer.cs#L49

We found the issue with the crash from the previous commit, however, with the null check before this, the rest of the code will not be called ever.

**Comment by rolfbjarne** [comment]
I'm not sure I understand the problem: if there are no recognizers, then there's no need to call DangerousRetain/DangerousRelease in the first place.

**Comment by spouliot** [comment]
If you are still experiencing this issue please provide additional information, like a test case, and click the Reopen Issue button.

Thanks!
