### ISSUE TITLE
[iOS] Notification Center kills outstanding debugging sessions

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#5959]
### Steps to Reproduce

1. New iOS App. Add a button and an event handler on press
2. Run, note button event fires on press
3. Background app, open notification center
4. Swap back to app. No events or logs since connection is dead.

### Expected Behavior
Backgrounding + Notification center to not kill app debugging.

A simple test suggests that it does not with Xcode.

### Actual Behavior

Kills debugging session.

### Environment

https://gist.github.com/chamons/77c1a8f713edd9d3b5c9438851ae747e

### Example Project (If Possible)

> VS bug [#857360](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/857360)

**Comment by SteveFarmerJr** [comment]
Why was this removed? I still experience this issue.  It's yet another frustration when working with iOS notifications.

**Comment by chamons** [comment]
@SteveFarmerJr - Apologies, as this is a bug in the IDE, we moved it to a private bug (the VSTS number), and sometimes our syncing took does the wrong thing.

This bug is still valid, they just don't use our "Future" milestone internally.

**Comment by rolfbjarne** [comment]
The VS issue has been closed.
