### ISSUE TITLE
MVVM Light two way binding is not working while changing the target property in Xamarin iOS.

### ISSUE THREAD

**Issue by divi1411** [xamarin/xamarin-macios#5964]
### Description

Description:

When I change the  property of custom UITextView in TouchesBegan method, the corresponding view model source property which is two way binded is not updating.

In my sample, I have created a custom view inherited from UITextView . I have created a property of type string  in the custom view class.  I have a ViewModel class with a property of type string. I have binded these two properties using MVVM light with BindingMode as TwoWay.  If I change the view model property , it is reflecting in the target property (of custom view class). But when I change the custom view property in TouchesBegan method, it is not reflecting in source property. If I directly edit the custom UITextView then it is working.

### Steps to Reproduce

1. Run the sample
2. Touch the custom UITextView (In touch began method I have changed the target property value)
3. Check the view model source property. This will not update

### Expected Behavior

- Source property must updated while updating target property if TwoWay binding is provided.

### Actual Behavior

- Source property not getting updated. 

### Example Project (If Possible)

[XamarinIosMvvmLightBindings-master 3.zip](https://github.com/xamarin/xamarin-macios/files/3131482/XamarinIosMvvmLightBindings-master.3.zip)

**Comment by chamons** [comment]
I do not believe this is a Xamarin.iOS bug, I think this is caused by difficulty using MVVMLight. 

It [appears](https://ulrichbodentien.com/2015/10/11/xamarin-ios-two-way-binding-with-mvvm-light/) two way binding require a `UpdateTargetTrigger` so your library knows what the UI property is set.
