### ISSUE TITLE
[Mac] hanged in InvokeOnMainThread

### ISSUE THREAD

**Issue by msasso69** [xamarin/xamarin-macios#6018]
My application has several background threads created by Parallel.ForEach that update the same controls in the UI using at the end NSObject.InvokeOnMainThread.
At the begin all is almost fine (I say almost because sometimes switching to the ui thread takes several seconds), but after some while all my threads get stuck in:
```
Messaging.void_objc_msgSend_IntPtr_IntPtr_bool (d.Handle, Selector.PerformSelectorOnMainThreadWithObjectWaitUntilDoneHandle, 
		                                                                NSDispatcher.Selector.Handle, d.Handle, true);
``` 
Is this method thread safe?
Why switching to the ui thread takes sometimes so much time? I assume that my background threads might not give the ui thread a chance to run so I placed some Thread.Sleep to pause my threads, but it did not help. Is it possible to give the ui thread a higher priority compared to the threads launched with Parallel.ForEach?

Thanks for your support.

### Environment

```
Visual Studio Community 2017 for Mac
Version 7.7.4 (build 1)
Installation UUID: e409d373-5fb2-462c-80fe-83508116ec94
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

Mono Framework MDK
Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

NuGet
Version: 4.8.0.5385

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.7
	2.1.2
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.503/Sdks
SDK Versions:
	2.1.503
	2.1.302
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Android
Not Installed

Microsoft Mobile OpenJDK
Java SDK: 
No Java runtime present, requesting install.

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 7.7.5.0
Hash: 06ceaea1

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Xamarin.Mac
Version: 5.2.1.13 (Visual Studio Community)
Hash: a4332c90
Branch: 
Build date: 2019-01-11 13:08:10-0500

Xamarin.iOS
Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

Build Information
Release ID: 707040001
Git revision: 2a4679454f31c8bb887cfd181ea133c9149d3cad
Build date: 2019-01-30 16:18:21+00
Build branch: release-7.7.4
Xamarin extensions: c8b4305fd4c60b9c25947072eb150fdc3a5aa2b5

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Mon Mar  5 22:24:32 PST 2018
    root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
Eto.Forms Support Addin 2.4.9999.0
```

**Comment by VincentDondain** [comment]
Hi,

It is tough to answer why switching to the ui thread takes sometimes so much time because we don't know how many threads were created (:

Threading is hard and it all depends on your code, if you could share a test case maybe we could help you understand the situation better.

Also I do not think you can give higher priority to the UI thread as you don't own/control it.

**Comment by msasso69** [comment]
Yes, thanks for your answer, 
I understand that it is hard to give an answer without a repro,
I was hoping that there was a way to prioritize the UI thread even if in fact that would only minimize the problem that all my threads hang in InvokeOnMainThread. I really sense that they deadlock inside that call because at the beginning everything goes fine (my threads are only five and they are not doing heavy processing), bu they do a lot of updates in the UI (that I want to happen in a syncronous way).
What happens is that at a certain point the callback event that should update the UI starts piling up and the number of threads taken in the threading pool start increasing indefinitely and all stuck in InvokeOnMainThread. When my original five threads end their duty and they don't fire anymore any event to update the UI, the threads stop increasing in number but remain stuck in InvokeMainThread (and now the UI thread should have all the cpu for itself).
I'm now trying to synchronize the access to the main thread with a lock, but my app grew quite big and putting a lock wherever I need to access the UI means a lot of refactoring with a constant risk of deadlock if not done wisely, and I was wondering if such an effort will really solve my problem. That's why I was asking whether InvokeOnMainThread is thread safe or not :)

**Comment by chamons** [comment]
So, this issue was never set as need-info last year, despite having no sample / actual concrete bug.

Unfortuntely Apple does not document the thread safely of each API, which would be awesome. In general, you can write a tiny Obj-C sample using that API, run it under Apple's thread verify tool, and see if it complains.

Xamarin.iOS and Mac tend to be more conservative and add thread checks by default in places, as messing this up can corrupt internal unmanaged state and lead to "fun" crashes.

Please feel free to open a new issue if you have concerns.

**Comment by msasso69** [comment]
I could not isolate a problem in a simple repro but synchronizing all switches to the UI thread with a lock solved my problem, so I assume that InvokeOnMainThread is definitely not thread safe and calling it cuncurrently leads to a deadlock. Hope this helps others :)
