### ISSUE TITLE
Remove unnecessary Mono .dylib's from XM package

### ISSUE THREAD

**Issue by akoeplinger** [xamarin/xamarin-macios#6023]
During some discussion on Slack today @rolfbjarne and I discovered that the XM .pkg includes some Mono .dylibs that are apparently unused (according to Rolf XM only uses the static libmono*.a files):

- libMonoPosixHelper.dylib
- libmonosgen-2.0.dylib
- libmono-2.0.dylib
- libmono-native-compat.dylib
- libmono-native-unified.dylib

Removing them will reduce the .pkg size.

**Comment by spouliot** [comment]
I thought they, or some, were needed for AOT.
Doing a grep shows `libMonoPosixHelper.dylib` used in `src/aot.cs` for a XM test.

**Comment by spouliot** [comment]
yup, did not dream that one
```
./MacCoolApp_DontLink/MacCoolApp/bin/Release/MacCoolApp.app/Contents/MonoBundle/libMonoPosixHelper.dylib
```
but I don't recall ever seeing the `libmono*.dylib` in XM apps. @chamons ?

**Comment by chamons** [comment]
I thought we needed that for some internal mono stuff:

```tests/mmptest/src/CodeStrippingTests.cs:                                // Mono's linker is smart enough to remove libMonoPosixHelper unless used (DeflateStream uses it)
```

There are a number of MMP tests that will need tweaks if we can remove it.

**Comment by spouliot** [comment]
pretty sure `libMonoPosixHelper.dylib` can't be removed
less sure about others - can't remember code (mmp) or apps with them

**Comment by akoeplinger** [comment]
because we P/Invoke into the library? in that case I guess we can only remove libmonosgen-2.0.dylib.

**Comment by mikkeljohnsen** [comment]
Is "libmono-native-compat.dylib" removed.
I can't compile mono-6.0.0.319 on macOS, since "libmono-native-compat.dylib" is not found.

System.DllNotFoundException: libmono-native-compat.dylib

**Comment by chamons** [comment]
We are shipping it as of 5.14. 

`/Library/Frameworks/Xamarin.Mac.framework//Versions/5.14.0.114/lib/libmono-native-compat.dylib`

If you are having issues, please consider opening an issue with build logs and steps to reproduce.

**Comment by rolfbjarne** [comment]
This is no longer applicable to .NET.
