### ISSUE TITLE
NSTextField.Formatter missing null-allowed

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#6032]
### Steps to Reproduce

1.  Set `NSTextField`'s `Formatter` to `NSNumberFormatter`
2. Set `NSTextField`'s `Formatter` to null.
3. Observe ArgumentNullException

### Expected Behavior
No Exception

### Actual Behavior
ArgumentNullException

### Environment
any

```
```

### Example Project (If Possible)

Swift seems to have nullable here. No special annotation on objc.
https://developer.apple.com/documentation/appkit/nscontrol/1428887-formatter
![image](https://user-images.githubusercontent.com/109974/57468994-403a5d00-728e-11e9-8c3e-fce640c01d50.png)

**Comment by CartBlanche** [comment]
Tagging so I get notified :)
