### ISSUE TITLE
iOS 9: Could not find the assembly 'Xamarin.iOS.dll' in the app.

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/xamarin-macios#6047]
Because of a watchOS project within my app, I'm currently forced to use the Xamarin.iOS Version mentioned in this post: https://devblogs.microsoft.com/xamarin/apple-new-processor-architecture/ 

But if I do so, I got the following error when trying to debug on iOS 9 (or run my TF version on it): 

```
Please connect the device 'iPhone-4S'...
objc[219]: Class MSService is implemented in both /System/Library/PrivateFrameworks/MailServices.framework/MailServices and /var/containers/Bundle/Application/0CE07819-522A-4C48-B036-2BC6EBC37612/MyApp.iOS.app/MyApp.iOS. One of the two will be used. Which one is undefined.
Launched application 'com.SoftwareNotion.MyApp' on 'Sebastians-iPhone-4S' with pid 219
2019-05-14 11:39:55.779 MyApp.iOS[219:7343] Xamarin.iOS: Could not find the assembly 'Xamarin.iOS.dll' in the app. This is usually fixed by cleaning and rebuilding your project; if that doesn't work, please file a bug report: https://github.com/xamarin/xamarin-macios/issues/new

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x21c02c5c):0x21c02c4c  1c ff 2f e1 1e ff 2f e1 52 cf a0 e3 80 00 00 ef  ../.../.R.......
0x21c02c5c  04 00 00 3a 04 c0 9f e5 0c c0 9f e7 00 00 00 ea  ...:............
0x21c02c6c  b8 13 e1 13 1c ff 2f e1 1e ff 2f e1 53 cf a0 e3  ....../.../.S...
0x21c02c7c  80 00 00 ef 04 00 00 3a 04 c0 9f e5 0c c0 9f e7  .......:........

=================================================================
	Native stacktrace:
=================================================================
	0x22815f9 - /private/var/containers/Bundle/Application/0CE07819-522A-4C48-B036-2BC6EBC37612/MyApp.iOS.app/Frameworks/Mono.framework/Mono : mono_dump_native_crash_info
	0x227995f - /private/var/containers/Bundle/Application/0CE07819-522A-4C48-B036-2BC6EBC37612/MyApp.iOS.app/Frameworks/Mono.framework/Mono : mono_handle_native_crash
	0x21ca6077 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x21cac733 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x21b970ad - /usr/lib/system/libsystem_c.dylib : abort
	0x1c94428 - /var/containers/Bundle/Application/0CE07819-522A-4C48-B036-2BC6EBC37612/MyApp.iOS.app/MyApp.iOS : xamarin_get_block_descriptor
	0x1c95da4 - /var/containers/Bundle/Application/0CE07819-522A-4C48-B036-2BC6EBC37612/MyApp.iOS.app/MyApp.iOS : xamarin_find_protocol_wrapper_type
	0x1c9daf8 - /var/containers/Bundle/Application/0CE07819-522A-4C48-B036-2BC6EBC37612/MyApp.iOS.app/MyApp.iOS : xamarin_release_block_on_main_thread
	0x9c5e1 - /var/containers/Bundle/Application/0CE07819-522A-4C48-B036-2BC6EBC37612/MyApp.iOS.app/MyApp.iOS : _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy
	0x21b2f873 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
Application 'com.SoftwareNotion.MyApp' terminated.
```

**Comment by chamons** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by rolfbjarne** [comment]
@Sebastian1989101 can you try disabling LLVM in your release build to see if that makes a difference?

**Comment by Sebastian1989101** [comment]
@rolfbjarne If I don't forget it, I can do this with the next TF Version. But this issue also happens when debugging where LLVM is not enabled.

**Comment by rolfbjarne** [comment]
@Sebastian1989101 then we'll need a way to reproduce the crash; could we get access to your project, or could you provide a test project we can use?

Alternatively you can try a preview of our next major release (d16-2) here: [xamarin.ios-12.14.0.87.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-2/72c4a8ab9045f809eda72bf8416043bceb036629/25/package/xamarin.ios-12.14.0.87.pkg), to see if that works (this contains support for the new watch as well).

**Comment by spouliot** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
