### ISSUE TITLE
[msbuild][mmp] Not linking with `runtimes/osx/native` lib from nuget reference?

### ISSUE THREAD

**Issue by hauteur** [xamarin/xamarin-macios#6065]
Using the Google Ads API works fine from a .net core console app, but the build fails when I try to include a reference in either a Xamarin.Mac or a Xamarin.iOS app.  I didn't try Android or UWP.  Unfortunately, the build log doesn't give me much to go on.

Initially, I created an [issue](https://github.com/googleads/googleads-dotnet-lib/issues/214) on the Google Ads github page, but they think it is an issue with Xamarin.Mac and/or Xamarin.iOS being able to find the x86 binaries.

### Steps to Reproduce

1.  Create a new Xamarin.Mac or Xamarin.iOS app (both have errors, but they appear different)
2. Add Nuget package Google.Ads.GoogleAds
3. Build the project

### Expected Behavior

The project should build

### Actual Behavior

The build process fails with very little information in the build log.

>
> ld: symbol(s) not found for architecture x86_64
> clang : error : linker command failed with exit code 1 (use -v to see invocation)
>     
> MMP : error MM5109: Native linking failed with error code 1.  Check build log for details.
> The command exited with code 1.
> Done executing task "Mmp" -- FAILED.
> Done building target "_CompileToNative" in project "RRVGenerator.Mac.csproj" -- FAILED.
> 
> Done building project "RRVGenerator.Mac.csproj" -- FAILED.
> 
> Build FAILED.
> 
> clang : error : linker command failed with exit code 1 (use -v to see invocation)
> MMP : error MM5109: Native linking failed with error code 1.  Check build log for details.
>     0 Warning(s)
>     2 Error(s) 
> 

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.0.6 (build 4)
Installation UUID: 1f6c8de2-520b-4149-a4ab-ef0e3cabc0f8
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.1
	2.1.9
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.2.103/Sdks
SDK Versions:
	2.2.103
	2.1.505
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.8.0.0 (Visual Studio Community)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Xamarin.iOS ===

Version: 12.8.0.2 (Visual Studio Community)
Hash: f2248ae6
Branch: d16-0
Build date: 2019-04-23 11:59:04-0400

=== Xamarin Designer ===

Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

=== Xamarin.Android ===

Version: 9.2.3.0 (Visual Studio Community)
Android SDK: /Users/mmiller/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ac37ccd385
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/mmiller/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-04-05 16:58:56 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800060004
Git revision: 889a91b9b9d44b10ef4d1bc5eb3cfb46ecf992c1
Build date: 2019-05-07 17:06:59+00
Build branch: release-8.0
Xamarin extensions: 3b90188697a1755849b0d7d322d2651033204242

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64


```

### Build Logs
[BuildLog.txt](https://github.com/xamarin/xamarin-macios/files/3188754/BuildLog.txt)

### Example Project (If Possible)
[GoogleAdsTest.zip](https://github.com/xamarin/xamarin-macios/files/3188762/GoogleAdsTest.zip)

**Comment by hauteur** [comment]
By the way - I did find a couple of other mentions of this issue.

[Visual Studio Dev Community](https://developercommunity.visualstudio.com/content/problem/229311/linker-command-failed-with-error-1.html)
Setting the Linker Behavior does allow the project to build, but then it crashes on start when I have it hooked to a Xamarin Forms project (It does not crash in an empty Xamarin.Mac app.  I didn't try actually calling any of the Google Ads API operations):  

> Default constructor not found for type Xamarin.Forms.Platform.MacOs.ResourcesProvider

[Xamarin Forums](https://forums.xamarin.com/discussion/96593/solved-xamarin-mac-error-mm5109-in-release-build-related-to-ikimagebrowserdatasource)
Setting --registrar=dynamic had no effect.

**Comment by AnashOommen** [comment]
Yes, I am fine keeping the issue open until we have a resolution. I'll also loop in a few grpc folks to see if they have more context.

**Comment by chamons** [comment]
These are the mmp errors in question:

https://gist.github.com/chamons/4e10025b809acf5b4945e16a3e618462

From what I can tell, these are supplied by:

`packages/Grpc.Core.1.20.1/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib`

Adding a native reference to the path seems to allow linking.

I am uncertain if there is a bug in our nuget support (should we be linking this library auto-magically?) so I'll leave it open.

**Comment by rolfbjarne** [comment]
This is fixed in .NET.
