### ISSUE TITLE
[xharness] Unexpected "skip" should fail tests

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#6074]
@rolfbjarne @mandel-macaque ?

**Comment by chamons** [comment]
At one point, tests could “skip” and it wouldn’t show up as a red fail. They tests just didn’t run even though they should. 

I don’t have context beyond that. If this hasn’t happened in awhile, feel free to close.

**Comment by rolfbjarne** [comment]
I believe this is how it currently works.
