### ISSUE TITLE
UINavigationBar.Appearance changes do not work as they do in ObjC

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#6094]
Compare:
`[[UINavigationBar appearance] setBarTintColor:UIColor.redColor];`
![image](https://user-images.githubusercontent.com/6392201/58121625-76040d80-7bcd-11e9-8145-6340e4a249e2.png)
to
`UINavigationBar.Appearance.TintColor = UIColor.Red;`
![image](https://user-images.githubusercontent.com/6392201/58121636-7ac8c180-7bcd-11e9-9112-767311d68b58.png)

### Steps to Reproduce

1.  Open attached projects, build and compare.

[NavColorBar.zip](https://github.com/xamarin/xamarin-macios/files/3203975/NavColorBar.zip)

[NavColorBarManaged.zip](https://github.com/xamarin/xamarin-macios/files/3203973/NavColorBarManaged.zip)

### Expected Behavior

Both to appear the same or an obvious warning/error.

### Actual Behavior

Different behaviors.
### Environment
https://gist.github.com/chamons/ae41c1ee5f59a49b853dcf6e87ec3c08

### Build Logs

https://gist.github.com/chamons/cd7785487a2d06e153e332746307070b

**Comment by chamons** [comment]
This was raised in https://developercommunity.visualstudio.com/content/problem/570558/uinavigationbar-bartintcolor-not-being-set.html

**Comment by spouliot** [comment]
works fine when using 
```sharp
UINavigationBar.Appearance.BarTintColor = UIColor.Red;
```
instead of
```csharp
UINavigationBar.Appearance.TintColor = UIColor.Red;
```
(missing `Bar`)
which is also what the ObjC code does
```objc
    [[UINavigationBar appearance] setBarTintColor:UIColor.redColor];
```
