### ISSUE TITLE
[XHarness] Add a proper message when tests fail and there are no devices not found

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#6167]
When we have failures and 0 devices not found, xharness message is not quite right:

`3 tests failed, 0 tests' device not found, 92 tests passed.`

Found in https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/10108/Test_20Report/ 

The change was introduced in https://github.com/xamarin/xamarin-macios/pull/6066

**Comment by rolfbjarne** [comment]
Already fixed: https://github.com/xamarin/xamarin-macios/commit/dbc9157945e1ed4482038dca3a119032f38feee1#diff-6f227b39f02c167ab381c32973b161ff

**Comment by spouliot** [comment]
hmm... that just happened in https://github.com/xamarin/xamarin-macios/pull/6164
and @rolfbjarne PR was merged 7 days ago

**Comment by spouliot** [comment]
nm - it was not back ported to d16-2

**Comment by rolfbjarne** [comment]
Backport PR: #6169.
