### ISSUE TITLE
Testflight startup crash for app build with Xamarin.iOS greater than 12.2.1.11

### ISSUE THREAD

**Issue by cosminstirbu** [xamarin/xamarin-macios#6177]
### Steps to Reproduce

1. Use a Xamarin.iOS version greater than 12.2.1.11 (e.g. 12.8.0.2)
2. Archive any iOS application in Release mode and submit it to Testflight
3. Install and open the application 
4. The application shouldn't crash

### Actual Behavior

The application crashes. If you use the Device Log (from Xcode) you'll see:

```
Attempt to add an app with insufficient id, info {
    BKSApplicationStateAppIsFrontmost = 1;
    BKSApplicationStateExtensionKey = 0;
    SBApplicationStateDisplayIDKey = "com.example.app";
    SBApplicationStateKey = 8;
    SBApplicationStateProcessIDKey = 20699;
    SBMostElevatedStateForProcessID = 8;
} 
```
Interestingly enough there is no crashed reported on the device.

Interestingly enough, if I distribute the same app (100% same build settings) using an Ad-Hoc provisioning profile the issue doesn't reproduce.

I've tried recreating the production certificate and provisioning profile, and the issue still reproduces.

### Environment

It works for instance with (extracted from a script used on Azure Pipelines to control the SDK versions):

XCODE_PATH="/Applications/Xcode_10.1.app"
MONO_VERSION="5.16.1"
XAMARIN_IOS_VERSION="12.2.1.11"

it doesn't work however with 

XCODE_PATH="/Applications/Xcode_10.2.app"
MONO_VERSION="5.16.1"
XAMARIN_IOS_VERSION="12.2.1.16"

or

XCODE_PATH="/Applications/Xcode_10.2.app"
MONO_VERSION="5.16.1"
XAMARIN_IOS_VERSION="12.8.0.2"

or

XCODE_PATH="/Applications/Xcode_10.2.1.app"
MONO_VERSION="5.16.1"
XAMARIN_IOS_VERSION="12.8.0.2"

Can't tell if it's a a Xamarin.iOS or an Xcode issue, or an interoperability issue.

Also I've found this recent Xamarin Forums post mentioning the same issue:

https://forums.xamarin.com/discussion/155777/ios-app-runs-perfectly-on-device-but-not-in-testflight?

**Comment by dalexsoto** [comment]
Hello, 

Most of the time errors like this are due to code signing issues, I see you already re-created the profiles, my other suggestion would be to check if you are using any framework that contains a sub framework, look at the generated app bundle inside the Frameworks/foo.framework/bar.framework if you happen to encounter a sub-framework this one would also need to be codesigned.

**Comment by cosminstirbu** [comment]
If it helps, I can send you the .ipa file that has the problems and the build logs as well.
There is no crash log as mentioned, the only device log is the one I've posted above.

What would be a good way to upload them without making them public?

Also, if it's not too much to ask, can you try to reproduce it with the mentioned versions on a sample app of your own that has an App Store connect entry?

**Comment by dalexsoto** [comment]
You can reach me at alexsoto - microsoft.com if you want to send a private link to your IPA, I do not have an app registered in the AppSore connect but will try to get one to test

**Comment by cosminstirbu** [comment]
Hi @dalexsoto 

Did you get the chance to investigate this issue? Do you have any news on it?

Thank you,
Cosmin

**Comment by DottorPagliaccius** [comment]
I've this problem too, please help

**Comment by dalexsoto** [comment]
Hello, please try again with our new stable release from today and let us know if this fixes your issue.

**Comment by cosminstirbu** [comment]
After further investigations we found out that the issue was caused by building with Xcode 10.2+ but referencing Swift standard libraries from Xcode 9 as one of our dependencies was built with Swift 4.1.2

The fix was to update our dependency, since the latest version was build with Xcode 11.1 and Swift 5.1
