### ISSUE TITLE
[Xcode 11] Simulator provisioning got disabled in the Xcode 11 branch 

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#6205]
We had to disable the simulator provisioning here https://github.com/xamarin/xamarin-macios/pull/6204 to get the project to compile with Xcode 11 beta 1and unblock the bindings. We should re-enable it when possible.

**Comment by rolfbjarne** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/commit/6e469327fc3b993867d755323cfe932b083aff19.
