### ISSUE TITLE
Bump min iOS version to 7.0

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#6213]
It seems Xcode 11 drops support for iOS versions < 8.0

So we'll have to do the same.

* [ ] Fix Make.config
* [ ] Remove dead errors/warnings/logic from mtouch
* [ ] Fix test projects / templates.
* [ ] IDE?

**Comment by spouliot** [comment]
Release notes are not matching the behaviour you described (I have more trust in the later)

_Xcode 11 supports on-device debugging for iOS 8 and later, tvOS 9 and later, and watchOS 2 and later._
https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_release_notes?language=objc

Simulator support is, for beta1, much more restrictive. In fact the above looks more like what Xcode 10.x had.

**Comment by spouliot** [comment]
for reference
```
/Users/poupou/git/d16-1/xamarin-macios/tests/monotouch-test/ld: Warning: OS version (6.0.0) too small, changing to 8.0.0 (monotouch-test)
```

**Comment by spouliot** [comment]
Test results from https://github.com/xamarin/xamarin-macios/issues/6257
suggest that 8.0.0 is set as minimum for simulator but
7.0.0 is used for device builds (so what can be submitted)
The later is likely what we should target as an absolute minimum

**Comment by rolfbjarne** [comment]
Yes, it seems 7.0.0 is the minimum for device builds, and 8.0.0 for simulator builds:

```
$ /Applications/Xcode11-beta7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang test.m -arch arm64 -isysroot /Applications/Xcode11-beta7.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=6.0 -framework Foundation
ld: warning: OS version (6.0.0) too small, changing to 7.0.0

$ /Applications/Xcode11-beta7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang test.m -arch x86_64 -isysroot /Applications/Xcode11-beta7.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -miphoneos-version-min=6.0 -framework Foundation
ld: warning: OS version (6.0.0) too small, changing to 8.0.0
```

**Comment by rolfbjarne** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/commit/344dadb212dc34db398f765af1d0ec79876b6323.
