### ISSUE TITLE
Can't build xamarin-macios on Catalina because of the Xcode 9.4 requirement

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#6217]
During the compilation of the project on catalina I got the following message:

`The license for Xcode 9.4 has not been accepted. Execute 'sudo /Applications/Xcode94.app/Contents/Developer/usr/bin/xcodebuild' to review the license and accept it.`

When trying to execute the xcodebuild the following error occurs:

`dyld: Symbol not found: _OBJC_IVAR_$_NSFont._fFlags
  Referenced from: /Applications/Xcode94.app/Contents/SharedFrameworks/DVTDocumentation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
  Expected in: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 in /Applications/Xcode94.app/Contents/SharedFrameworks/DVTDocumentation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
Abort trap: 6`

**Comment by rolfbjarne** [comment]
Current status:

* We need Xcode 9.4 to build our libraries in 32-bit mode to support 32-bit Xamarin.Mac (both Classic and Unified). We're dropping support for 32-bit Xamarin.Mac in the `xcode11` branch.
* We need Xcode 9.4 to build tooling for our watchOS support (some of the tools we use are 32-bit executables). These tools will become 64-bit executables in mono's `2019-06` branch, which is currently being integrated into our `master`, and will be a part of our `d16-3` release.

When both of these Xcode 9.4 usages have been removed, we can drop the Xcode 9.4 dependency. This will happen when we merge our `xcode11` branch back into `master` just after Xcode 11 becomes stable this fall.

**Comment by praeclarum** [comment]
This is working for me on Catalina. I think this can be closed? With one note: it doesn't seem to be building tvOS or watchOS. But perhaps that's my error.

**Comment by rolfbjarne** [comment]
Yes, this is working now.

It should build for tvOS and watchOS as well. Cleaning your checkout and rebuilding should fix any issues you have.

**Comment by jenniewilliams** [comment]
I just came across this and was hoping to find an answer to my error when trying to install fclust in R....is there anything I need to install? 

dyld: Symbol not found: _OBJC_IVAR_$_NSFont._fFlags
  Referenced from: /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
  Expected in: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
make: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
make: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
ERROR: compilation failed for package ‘fclust’

**Comment by jenniewilliams** [comment]
I am on. mac with Catalina and using R Studio v 1.2.5033 and R v 3.6

**Comment by rolfbjarne** [comment]
@jenniewilliams I have no idea about what you're trying to install or the tools you're using, but that error is because you're trying to use Xcode 9.4 (or earlier) on macOS Catalina, which doesn't work (as you can see). You need to upgrade to a newer version of Xcode.

**Comment by jenniewilliams** [comment]
Many thanks, just doing that now, definitely needed I think, when I went to the App store it said upgrade......its slow though.

Stay safe 🙂


Jennie Williams

PhD Student: Mapping Knowledge with Data Science

Twitter: @JenniexWilliams

Department of Geography,

Bush House North East Building

King’s College London

WC2B 4BG

Email: jennie.williams@kcl.ac.uk<mailto:margaret.kadiri@kcl.ac.uk>

Days on campus: Semester 1: Mondays, Wednesdays & Thursdays

________________________________
