### ISSUE TITLE
The views override of NSGridView.Create has an incorrect signature

### ISSUE THREAD

**Issue by abock** [xamarin/xamarin-macios#6232]
Our binding over [`NSGridView gridViewWithViews:`](https://developer.apple.com/documentation/appkit/nsgridview/1639782-gridviewwithviews?language=objc) is incorrect. This is a convenience method (actually, incredibly convenient) that is unusable in C# as we declare the parameter as `NSView[]`.

#### Native Signature

```objective-c
+ (instancetype)gridViewWithViews:(NSArray<NSArray<NSView *> *> *)rows;
```

#### Actual Signature

```csharp
[Static]
[Export ("gridViewWithViews:")]
NSGridView Create (NSView [] rows);
``` 

#### Expected Signatures

```csharp
[Static]
[Export ("gridViewWithViews:")]
NSGridView Create (NSView [][] rowsAndColumns);

[Static]
[Export ("gridViewWithViews:")]
NSGridView Create (NSView [,] rowsAndColumns);
```

_I think a proper two-dimensional array makes sense here, but you don't see them often in C#, so array of arrays might feel more natural to some - maybe we could provide both._

**Comment by dalexsoto** [comment]
Agreed, we should deprecate and fix this issue, or we could also fix this 

```
NSGridView Create (NSView [] rows);
```
 to actually manually wrap `rows` into `NSArray[0]` then send that to native land and make this convenient method actually work.

**Comment by abock** [comment]
Given that the existing binding will and always has just hard-crashed the app, no one is using it, anywhere 😄 

However, it would be an API break to remove it, so we should just `[Obsolete]` the broken one and hide it from IntelliSense with `[EditorBrowsable(EditorBrowsableState.Never)]`. And of course `#if !XAMCORE_WHATEVER_IS_NEXT_API_BREAK` so it gets removed on the next API break.

**Comment by joconte** [comment]
Hello, I tried to fix this but I have a problem : 

```NSView[][]```doesn't fit with ```INativeObject```
same with ```NSView[,]```

<img width="1261" alt="Capture d’écran 2019-06-24 à 23 44 15" src="https://user-images.githubusercontent.com/41507018/60054208-20de7e80-96da-11e9-8874-78ede567283f.png">

**Comment by rolfbjarne** [comment]
@joconte exactly what did you change? can you show your code?

**Comment by joconte** [comment]
@rolfbjarne sorry for the late answer, here are my changes in appkit.cs:

Before : 
```
[Static]
[Export ("gridViewWithViews:")]
NSGridView Create (NSView [] rows);
``` 

After:
```
#if !XAMCORE_4_0
		[EditorBrowsable(EditorBrowsableState.Never)]
		[Obsolete]
		[Static]
		[Export ("gridViewWithViews:")]
		NSGridView Create (NSView [] rows);
#endif
		[Static]
		[Export ("gridViewWithViews:")]
		NSGridView Create (NSView [][] rowsAndColumns);

		[Static]
		[Export ("gridViewWithViews:")]
		NSGridView Create (NSView [,] rowsAndColumns);
```

**Comment by joconte** [comment]
When I build I have an error in the generated file NSGridView.g.cs here : 
```

		[Export ("gridViewWithViews:")]
		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		public static NSGridView Create (NSView[,] rowsAndColumns)
		{
			global::AppKit.NSApplication.EnsureUIThread ();
			if (rowsAndColumns == null)
				throw new ArgumentNullException ("rowsAndColumns");
			var nsa_rowsAndColumns = NSArray.FromNSObjects (rowsAndColumns);
			
			NSGridView ret;
			ret =  Runtime.GetNSObject<NSGridView> (global::ObjCRuntime.Messaging.IntPtr_objc_msgSend_IntPtr (class_ptr, selGridViewWithViews_Handle, nsa_rowsAndColumns.Handle));
			nsa_rowsAndColumns.Dispose ();
			
			return ret;
		}
```
```
NSArray.FromNSObjects (rowsAndColumns);
```
Complaining that ```NSView[,]``` object must be convertible to ```INativeObject```

**Comment by rolfbjarne** [comment]
So the problem is that we've never had to bind multidimensional arrays before, so this needs some extra work.

I think the best fix would probably be to also implement NSArray.FromNSObjects overloads that take multidimensional arrays:

```csharp
public static NSArray FromNSObjects<T> (params T [,] items) where T: class, INativeObject
{
    // ...
}

public static NSArray FromNSObjects<T> (params T [] items) where T: class, INativeObject
{
    // ...
}
```

around here: https://github.com/xamarin/xamarin-macios/blob/1d541fea7131c1465e08bedf3ed032910d538623/src/Foundation/NSArray.cs#L62

**Comment by joconte** [comment]
@rolfbjarne Thanks,  I will look into it when I get back from work

**Comment by joconte** [comment]
@rolfbjarne I'm still stuck with the two dimensional array but I may have found a solution for the array of array. What do you think about this : 

```C#
public static NSArray FromNSObjects<T> (params T [][] items) where T: class, INativeObject
		{
			if (items == null)
				return null;

			try {
				var ret = new NSMutableArray ((nuint)items.Length);
				foreach (var t in items)
					ret.Add (NSArray.FromNSObjects (t));

				return ret;
			} catch {
				return null;
			}
		}
```
It compiles.

**Comment by rolfbjarne** [comment]
Don't catch exceptions, those should be surfaced to the caller, otherwise it looks good.

**Comment by joconte** [comment]
Ok great, I know why I'm stuck with the two dimensional array :

https://docs.microsoft.com/fr-fr/dotnet/csharp/language-reference/keywords/params
"The declared type of the params parameter must be a single-dimensional array, as the following example shows. Otherwise, a compiler error CS0225 occurs."

I will find a workaround and I keep you updated.

**Comment by rolfbjarne** [comment]
> "The declared type of the params parameter must be a single-dimensional array

Just remove the `params` keyword then :smile:

**Comment by joconte** [comment]
@rolfbjarne Yes it's what I did :smile:  but then I have to convert the two-dimesional array to single-dimensionnal array I know how to do it but I'm at work actually I don't have the time. I will try to finish this after work.

**Comment by joconte** [comment]
What about this for the two-dimensional array ? 

```C#
public static NSArray FromNSObjects<T> (T [,] items) where T: class, INativeObject
		{
			var index = 0;
			var width = items.GetLength (0);
			var height = items.GetLength (1);
			var single = new T [width * height];
			for (var y = 0; y < height; y++)
			{
				for (var x = 0; x < width; x++)
				{
					single [index] = items [x, y];
					index++;
				}
			}
			return FromNativeObjects (single);
		}
```

It compiles but I must admit I don't know how to test it.

**Comment by joconte** [comment]
Hmm It's not good, I call ```FromNativeObjects()```that is buggy. I find another way : 

```C#
public static NSArray FromNSObjects<T> (T [,] items) where T: class, INativeObject
		{
			var width = items.GetLength (0);
			var height = items.GetLength (1);
			var ret = new NSMutableArray ((nuint)(width * height));
			for (var y = 0; y < height; y++)
			{
				for (var x = 0; x < width; x++)
				{
					ret.Add (NSArray.FromNSObjects (items [x, y]));
				}
			}
			return ret;
		}
```
It compiles and doesn't crash
