### ISSUE TITLE
[xcode11-feature] Verify features are "API only" and do not require tooling

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#6242]
There were a number of features mentioned in WWDC that likely are "just" API changes, and won't require tooling changes. 

For each of these:
- Please ✔️ them once you've 98% certain they won't require anything beyond API bindings. 
- Please ~cross~ them out and link a new issue if they require entitlements / tooling / IDE changes

---

- [ ] Extended Runtime for WatchOS
- [ ] WatchOS Streaming API
- [ ] `IOHIDRequestAccess` (macOS) needed to check permissions (user consent), without triggering any UI, for new checks (e.g. screen or keyboard recording) in 10.15 (part of IOKit?)
- [ ] `NSOpenPanel` and `NSSavePanel` now out of process (10.15) and this changed the type hierarchy
- [ ] (macOS) DriverKit API is C++17
- [ ] Adaptive Materials?

**Comment by rolfbjarne** [comment]
Closing, this is outdated now.
