### ISSUE TITLE
[xcode11-support] xcframework support

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#6246]
xcframework are a new format of frameworks which allow multiple platforms to live side by side.

We should teach binding projects (XI and XM) to accept xcframework bundles.

In addition, we need to research how we can leverage this:

- Packaging some of our libraries our outputs?
- Embeddinator output (if so, [file issue with details](https://github.com/mono/embeddinator-4000/) and move on)

**Comment by awattar** [comment]
Hi. Any ETA for this enhancement?

**Comment by chamons** [comment]
Thanks for the interest @awattar - In general we don't have ETA for enhancements. Either they are in work or our backlog. 

Right now the teams is focused on Xcode 12 and the port to .NET 6, so it may be some time before we pick this up.

**Comment by awattar** [comment]
Thanks @chamons. It started to be a problem because apps referencing dynamic frameworks cannot be distributed to AppStore due to unsupported architecture - x86_64 so most of them were switched to modern xcframeworks that are currently unsupported by the Xamarin.iOS bindings/apps. Workarounds require special IPA handling or creating cumbersome configurations for simulator/device.

It is not something new but over a year old enhancement that could be put somewhere in the schedule for the sake of loyal developers and their customers ;)

**Comment by nrbrook** [comment]
@awattar @chamons It is possible to strip architectures out of dynamic frameworks during build using a script [such as Realm's](https://github.com/realm/realm-cocoa/blob/master/scripts/strip-frameworks.sh). However, an even greater problem is approaching with Apple Silicon. Xcode 12 builds simulator binaries for x86_64, i386, and now arm64 by default, for running in simulator on Apple Silicon. If attempting to make a fat binary, the arm64 simulator slice conflicts with the iOS arm64 slice. The arm64 simulator slice can be removed with lipo, but this means that the framework can't run in simulator on Apple Silicon. As such, I have to distribute a fat binary which doesn't support Apple Silicon for Xamarin. This means that until XCFrameworks is supported, many Xamarin projects using binary libraries and frameworks will not run in the simulator on Apple Silicon.

**Comment by rolfbjarne** [comment]
@nrbrook that's a very good point, and we'll have it in mind when we're adding simulator support on Apple Silicon

**Comment by tonyarnold** [comment]
We've just hit this with [Reveal's SDK](https://revealapp.com/) - we're in a tight spot here: we can't really afford _not_ to support Apple Silicon in our framework, but this necessitates shipping as an XCFramework so that there's no overlapping slices. 

Is there an ETA on support for Xamarin consuming XCFrameworks?

**Comment by chamons** [comment]
It's in work - https://github.com/xamarin/xamarin-macios/pull/10046

**Comment by spouliot** [comment]
#10046 has landed in `main`

**Comment by fklingler** [comment]
@spouliot 

I'm on the Xamarin.iOS 14.9.0.27 that should have #10046, but I'm still having this problem:


`warning: ignoring file /<ProjectPath>/obj/iPhoneSimulator/Debug - Staging/device-builds/iphone12.8-14.2/mtouch-cache/<FrameworkName>.xcframework, building for iOS Simulator-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x50 0x4B 0x03 0x04 0x14 0x00 0x00 0x00 0x08 0x00 0xD1 0x83 0x8F 0x51 0xD8 0x5E )`

My csproj contains this

```
    <NativeReference Include="Frameworks\<FrameworkName>.xcframework">
      <Kind>Framework</Kind>
      <Frameworks>Foundation</Frameworks>
    </NativeReference>
```

Am I doing something wrong?

**Comment by spouliot** [comment]
@fklingler yes, an xcframework is a directory, which has several subdirectories for arch/platforms. A valid mach-o file inside them would start with:

> 0000000 ca fe ba be

but yours is

> 0000000 50 4b 03 04

which looks like a ZIP archive.

**Comment by spouliot** [comment]
> I'm on the Xamarin.iOS 14.9.0.27 that should have #10046,

Also the [commit](https://github.com/xamarin/xamarin-macios/commit/3bd14c3eefaad5533c59ba6a0ff35c430037b6c3) associated with PR#10046 shows the first package to have this code is [14.9.0.52](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/main/3bd14c3eefaad5533c59ba6a0ff35c430037b6c3/565/package/notarized/xamarin.ios-14.9.0.52.pkg).

**Comment by fklingler** [comment]
I'm not sure I understood your first answer, as my xcframework is a directory and not a zip archive.
Thanks anyway! I'm gonna wait for the 14.9.0.52 build to be released and will try again.

**Comment by antonioseric** [comment]
I try to use 14.9.0.52 version it is not adding native reference (xcframework) as resource to dll. It is in bin folder as `.resource` folder.

**Comment by spouliot** [comment]
@antonioseric that's right. Side-car for framework was optional, since it was added after framework support but, for xcframework, side-car is the only supported option.

The main reason is that a binding assembly works for a single platform (e.g. if reference Xamarin.iOS or Xamarin.TVOS or Xamarin.WatchOS or Xamarin.Mac assemblies). Have the xcframework embedded inside each one would lead to a lot of duplication. A

Also the time to decompress them is not negligible since, even for frameworks, we have seen assemblies that were larger than what PE32 could handle. Large size often happens when bitcode is enabled, but even decompressing 100MB still has a noticeable impact on your build times.

**Comment by leonluc-dev** [comment]
It seems a binding project using a XCFramework reference builds fine for me, but once I try to use the resulting DLL in a Xamarin.iOS project I get the following build error for all classes in the binding:
`MT5211: Native linking failed, undefined Objective-C class: InsertClassNameHere. The symbol '_OBJC_CLASS_$_InsertClassNameHere' could not be found in any of the libraries or frameworks linked with your application.`

Is there a workaround to this?

**Comment by spouliot** [comment]
@leonluc-dev if you see this `unknown-unsupported file format message then you're not using an xcframework (which is a directory).

`0x50 0x4B 0x03 0x04` are the first bytes (headers) of a ZIP file. I'm not sure how you ended up in this situation but the tooling will only work with a (uncompressed) xcframework.

**Comment by spouliot** [comment]
> I am using Xamarin.iOS 14.10.0.4 for both the binding and app project.

Xamarin.iOS 14.10.0.4 is the Xcode 12.4 support release made on top (service release) of our `d16-8` milestone.

The xcframework feature is only available on `d16-9` builds, which is Xamarin.iOS 14.4.2.x - available in the preview channel right now.

**Comment by alexsorokoletov** [comment]
@spouliot if I build a binding project with d16-9 and then publish it as a Nuget, will it be possible for users with stable Xamarin version to use that Nuget package in their apps?

**Comment by alexsorokoletov** [comment]
> @fklingler yes, an xcframework is a directory, which has several subdirectories for arch/platforms. A valid mach-o file inside them would start with:
> 
> > 0000000 ca fe ba be
> 
> but yours is
> 
> > 0000000 50 4b 03 04
> 
> which looks like a ZIP archive.

One note here regarding the .xcframework I have here.
I get the same error as @fklingler however if I check the file

`od -t x1 My.framework/My | head`
I see that it starts with correct bytes 

> 0000000 ca fe ba be

**Comment by leonluc-dev** [comment]
I see. 
I checked the xcframework and both mach-o files seem to match the expected Mach-o 64-bit signature.
```
od -t x1 FrameworkName.xcframework/ios-arm64/FrameworkName.framework/FrameworkName | head
0000000    cf  fa  ed  fe
```
```
od -t x1 FrameworkName.xcframework/ios-x86_64-simulator/FrameworkName.framework/FrameworkName | head
0000000    cf  fa  ed  fe
```

So the issue might just be related to the Xamarin.iOS version I'm using. I expected 14.10 to support xcframeworks as well since a few post earlier it was mentioned a 14.9 package supported it, but I'll test with the preview of 14.14 to see if it works properly.

**Comment by alexsorokoletov** [comment]
As a workaround, we used stable Xamarin and the arm64/arm7 subfolder of the `.xcframework` (that's just a `.framework`) for the bindings.

Preview compiled the binding project fine, however, the actual app's linking process failed. (Thus the workaround).

**Comment by spouliot** [comment]
> Preview compiled the binding project fine, however, the actual app's linking process failed. (Thus the workaround).

This is basically what we're doing. The msbuild task is resolving the correct `.framework` path inside the `.xcframework` based on the OS and architecture. The rest of the build (e.g. `mtouch` and native compiler/linker) are unaware of XCFrameworks.

**Comment by spouliot** [comment]
Closing: d16-9 (XI 14.14) was released to stable

**Comment by 4brunu** [comment]
Does this means that now Xamarin fully supports XCFrameworks?

**Comment by leonluc-dev** [comment]
There are still a few issues with this it seems.
On Visual Studio for Mac (using Xamarin.iOS 14.4.2.5) I can build a binding project with a xcframework native reference fine and judging by the resulting DLL size and content the xcframework is included within it.

However when I use said DLL (or direct project reference) in a Xamarin.iOS app an issue occurs.
While the C# classes part of the binding are available it seems the framework (derived from the embedded xcframework) is not included in the app build, leading to the same MT5211 errors mentioned earlier.
The only way I can make the binding DLL work is explicitly include the xcframework in the Xamarin.iOS app itself as well as a native reference.

For binding projects with references to static libraries (.a) or non-xc frameworks it still works as expected (.a and .framework embedded in the binding are included in the build).

**Comment by 4brunu** [comment]
Is there any issue where we I can follow this problem?

**Comment by leonluc-dev** [comment]
I've created a new issue for the binding project issue specifically:  #10774

**Comment by leonluc-dev** [comment]
There is also a Windows exclusive bug regarding xcframeworks.
Whenever a Xamarin.iOS app references a xcframework (and builds fine on mac) the build process produced the following error on Windows (connected to a Mac build server):

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(142,3): error : Universal.xcframework has an incorrect or unknown format and cannot be processed.`

This seems to be error E0174 which can only be found in the code block below, but I haven't been able to figure out why it happens/why it only happens on Windows builds.

https://github.com/xamarin/xamarin-macios/blob/5ef69f173bcab367117f031bc4faa48dfec3e42c/msbuild/Xamarin.MacDev.Tasks.Core/Tasks/ResolveFrameworksBase.cs#L149-L163

**Comment by nguyenhuutinh** [comment]
@leonluc-dev :  does Xamarin fully supports XCFrameworks now?

**Comment by leonluc-dev** [comment]
@nguyenhuutinh I don't know the exact details (I'm not part of the Xamarin team). But Xamarin does support XCFrameworks on Mac, although with a few quirks to keep in mind. On Windows it's still broken (as of April 23, 2021).

* Binding projects using XCFrameworks cannot be properly built on Windows (your resulting binaries and resources will be incomplete). 
* Any Xamarin.iOS apps referencing a XCframework based binding projects will not build on Windows (the compiler will show linker errors)

On Mac using XCFrameworks in Xamarin binding projects works, but there are a few things to keep in mind:

* You add the XCFramework to the binding project as a native reference just like you would a regular framework or static library.

* There is currently a bug in Visual Studio for Mac which causes any XCFramework native reference to be marked as a static library after they are added to the project. You need to manually change this flag back to Framework.

* Any binding project using XCFramework requires the <X> value to be set on the project file. As of now, Visual Studio for Mac doesn't do this for you, so you have to set this value manually.

* ApiDefinition.cs and Structs.cs files are written the same way as with static libraries and regular frameworks

* After building the binding project the output folder will contain a dll file and a .resources folder. You need both the dll file and the resources folder to use the binding in a Xamarin.iOS app. 

* If you add the binding to a Xamarin.iOS app as a project reference the .resources folder will be handled automatically.
If you reference the resulting dll directly make sure the .resources folder is in the same location as the dll for it to work (you don't need to explictly reference the .resources folder. It being in the same folder as the dll is enough.)

**NOTE:** As for now, tools to automatically generate most of the ApiDefinition.cs files like Objective Sharpie cannot handle XCFrameworks yet. So you have to write the definition files manually or generate the files from a regular framework version of the library you want to bind and reuse them were possible.

Hopefully most of the bugs on Windows and in Visual Studio for Mac get ironed out soon. But this should at least get your a working XCFramework binding on Mac.

**Comment by nguyenhuutinh** [comment]
@leonluc-dev thanks for your detail information.
Yes, I got problem when using Objective Sharpie to generate metadata from XCFramework.
let me try to do it manually.

Thank you

**Comment by nguyenhuutinh** [comment]
hi @leonluc-dev , thanks, I tried with your suggestion. I can compile now.
But I got this error due to new instance of my class in framework.
```
Could not create an native instance of the type 'Library.CoverService': the native class hasn't been loaded.
```
seems that Xamarin didnot load my xcframework correctly.
have you experienced on this or any suggestion?

Thanks

**Comment by leonluc-dev** [comment]
@nguyenhuutinh The most common causes I've seen for that error is an incomplete/faulty ApiDefinitions.cs specification or the binding project is missing a required Objective-C compiler flag for the framework.
In both of these cases the binding project will still compile but will give runtime errors when used in an app.

**Comment by nguyenhuutinh** [comment]
ok thank you.
 
I used this command to generate binding files: 
`sharpie bind -framework ./CoverSDK.xcframework/ios-arm64_armv7/CoverSDK.framework --namespace CoverSDK`

**Comment by nguyenhuutinh** [comment]
@leonluc-dev : I just found that if I add native reference to the .framework subfolder inside the xcframework folder. it works.
so I think the IDE don't understand XCFramework
do you have any idea?
here is my xcframework structure:

```
DemoWrapper.xcframework
  - ios-arm64/
     - DemoWrapper.framework/
  - ios-arm64_x86_64-simulator
    - DemoWrapper.framework/
  - Info.plist
```

Thanks
