### ISSUE TITLE
[xcode11] link sdk: [FAIL] LinkSdkRegressionTest.Bug865_CanOpenUrl : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInvalidArgumentException Reason: *** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil URLString parameter 

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#6256]
https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/10186/Test_20Report/

```
[FAIL] LinkSdkRegressionTest.Bug865_CanOpenUrl : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInvalidArgumentException Reason: *** +[NSURLComponents initWithURL:resolvingAgainstBaseURL:]: nil URLString parameter 
```

**Comment by spouliot** [comment]
```csharp
UIApplication.SharedApplication.CanOpenUrl (null)
```
looks like the API is not happy with `null` 

I'll check the headers (to see if it's allowed) and, if needed, file a radar/feedback

**Comment by spouliot** [comment]
https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl?language=objc

and from sharpie
```csharp
	// -(BOOL)canOpenURL:(NSURL * _Nonnull)url __attribute__((availability(ios, introduced=3.0)));
	[iOS (3,0)]
	[Export ("canOpenURL:")]
	bool CanOpenURL (NSUrl url);
```

so it looks like we allowed it (old API) based on it's behaviour (well before annotations were available)

**Comment by spouliot** [comment]
Since the API
* returns a `bool` (and `false` is better than an exception);
* was an [old bug fix](https://bugzilla.xamarin.com/show_bug.cgi?id=865);

I added a `[PreSnippet]` so our behaviour does not change

Fixed in https://github.com/xamarin/xamarin-macios/pull/6264 merge
