### ISSUE TITLE
[xcode11] All BCL tests fail to build

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#6261]
https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/10186/Test_20Report/

Every test fails with a variation of:

```
Harness exception for '[NUnit] Mono BCL tests group 1': System.IO.FileNotFoundException: Could not find file "/Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/bcl-test/BCLTests/BCL tests group 1.csproj"
```

**Comment by spouliot** [comment]
@mandel-macaque I guess that's because we're building our own mono, right ?

Might be easier to backport / hack to get `master` consume mono binaries than fixing this...

**Comment by rolfbjarne** [comment]
Fixed with https://github.com/xamarin/xamarin-macios/commit/04d4f1a2b3c8e41d8ff7359bde7c3f3e2ac6421b.
