### ISSUE TITLE
Methods inside generic classes use Reflection even with Static Registar 

### ISSUE THREAD

**Issue by DavidKarlas** [xamarin/xamarin-macios#6268]
### Steps to Reproduce

1. Run Visual Studio for Mac.app, which uses static registar
2. Use new editor and place breakpoint
3. Scroll up and down
4. Using profiling tool you could notice callstack below:
![image](https://user-images.githubusercontent.com/774791/59298411-c7626280-8c8a-11e9-8bba-a1791c0c19ea.png)

### Expected Behavior
No Reflection is used.
### Actual Behavior
Reflection is used for native calls into managed methods inside `generic` class.
This has big performance impact. In our use case.
### Environment
https://gist.github.com/DavidKarlas/43b97c1590cdda11e6d2e74563ffdacd
### Build Logs
N/A

**Comment by Therzok** [comment]
I think this can be avoided by providing specific implementations of the generic class.

**Comment by rolfbjarne** [comment]
This is expected and documented: https://docs.microsoft.com/en-us/xamarin/ios/internals/api-design/nsobject-generics#performance

As @Therzok says, the workaround is to not use export generic classes to Objective-C.

**Comment by DavidKarlas** [comment]
Would it be possible to detect this at build time and report as warning?

**Comment by Therzok** [comment]
cc @kzu @tondat

**Comment by rolfbjarne** [comment]
> Would it be possible to detect this at build time and report as warning?

Yes, it's possible, but I'm not sure we should do it. It might make more sense as a code analyzer somewhere (@VincentDondain do we have code analyzers for XI/XM code?)

**Comment by sandyarmstrong** [comment]
Can we re-open this and make it about implementing either a warning or a code analyzer, so this doesn't get forgotten?

**Comment by rolfbjarne** [comment]
> Can we re-open this and make it about implementing either a warning or a code analyzer, so this doesn't get forgotten?

I've filed #6289.
