### ISSUE TITLE
Error "Assembly not found for net 4.x" with Xamarin.Mac Full Net 4.x

### ISSUE THREAD

**Issue by TomQv** [xamarin/xamarin-macios#6273]
Visual Studio Mac 8.0.9, mono 5.18.1.3

- Create new Cocoa App
- Project options - Build - General - Target Framework
- Change to Xamarin.Mac Full Net 4.6, or anything else higher then 4.5

![grafik](https://user-images.githubusercontent.com/6605960/59343003-2d8eca00-8d0b-11e9-856a-612ee9b37c16.png)

In Solution Explorer errors showing up "Assembly not found for net 4.6"

![grafik](https://user-images.githubusercontent.com/6605960/59343094-60d15900-8d0b-11e9-9c0a-df0275ae7a92.png)

This error occurs for all net versions. Only Xamarin.Mac Full Net 4.5 is fine.
Regardless of the error, build is successful.

Very irritating..........

Does this mean, I have to use net 4.5 on mac? Am I not allowed to use net 4.7.2?

> VS bug [#1049470](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1049470), VS bug [#1049962](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1049962)

**Comment by joconte** [comment]
Hello, 

Actually I couldn't reproduce your error using Visual Studio Mac 8.0.9, mono 5.18.1.3. 
I invite you to copy/paste your Visual Studio spec : 
-> Visual studio -> About Visual Studio -> Show details -> Copy information

**Comment by dalexsoto** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide all your version information. The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by TomQv** [comment]
Thanks for taking care of the issue. Here is the version info:
```

Visual Studio Community 2019 for Mac
Version 8.0.9 (build 5)
Installation UUID: 12f4c6cd-7385-43cc-beab-f6feedc1cfe4
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

Mono Framework MDK
Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

NuGet
Version: 4.8.2.5835

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.2.1 (14490.122)
Build 10E1001

Xamarin.Mac
Version: 5.8.0.0 (Visual Studio Community)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

Xamarin.iOS
Version: 12.8.0.2 (Visual Studio Community)
Hash: f2248ae6
Branch: d16-0
Build date: 2019-04-23 11:59:04-0400

Xamarin Designer
Version: 4.17.4.420
Hash: 0a2420845
Branch: remotes/origin/d16-0
Build date: 2019-05-23 23:40:02 UTC

Xamarin.Android
Version: 4.20.0.28 (Visual Studio Community)
Android SDK: /Users/tomflemming/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 24.0.2
SDK Platform Tools Version: 21.0.0
SDK Build Tools Version: 21.1.2

Microsoft Mobile OpenJDK
Java SDK: /Users/tomflemming/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-05-28 18:18:20 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 800090005
Git revision: 72a44477dd706608c2300a568f71e5769f89f7ef
Build date: 2019-05-29 15:19:54+00
Build branch: release-8.0
Xamarin extensions: 3e94aa3836143b8f5a5b9151b61a80e2fd278d62

Operating System
Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

```

**Comment by Vladislav52** [comment]
<img width="353" alt="Screen Shot 2019-11-06 at 09 31 53" src="https://user-images.githubusercontent.com/57431267/68273857-9ee36680-0078-11ea-81bd-488a3ac83a4e.png">

Hi. I have the same problem with migrating from Xamarin.Mac Full .Net Framework 4.5 to Xamarin.Mac Full .Net Framework 4.6.2.

**Have you any solutions?**

Thanks.

Visual Studio Mac info:
`=== Visual Studio Community 2019 for Mac ===

Version 8.3.6 (build 4)
Installation UUID: 5a2db039-b8c1-4205-9f8d-79590d005c01
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.2 (15526)
Build 11B52

=== Xamarin.Mac ===

Version: 6.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin.iOS ===

Version: 13.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin Designer ===

Version: 16.3.0.247
Hash: 52eac1a9e
Branch: remotes/origin/d16-3
Build date: 2019-10-03 23:04:28 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft Mobile OpenJDK ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-10-10 12:15:44 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-10-10 12:16:06 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803060004
Git revision: 081f7b8bbd534cb73bbfb5cff3d9aa4907396a4f
Build date: 2019-10-31 17:10:49+00
Build branch: release-8.3
Xamarin extensions: ade6d975df7634a5d81feda320a6102e5bacf309

=== Operating System ===

Mac OS X 10.15.1
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Thu Oct 17 16:17:15 PDT 2019
    root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

NuGet Package Management Extensions 0.20

`

**Comment by chamons** [comment]
Sorry for the long delay in response. This is a cosmetic issue with VSfM, and should not affect your ability to use types in net 4.x assemblies.

**Comment by rolfbjarne** [comment]
This is not any issue anymore in .NET.
