### ISSUE TITLE
InvalidOperationException in NSUrlSessionHandler

### ISSUE THREAD

**Issue by johnthiriet** [xamarin/xamarin-macios#6274]
### Steps to Reproduce

Threading issue hard to reproduce.

### Expected Behavior

An exception should not be thrown.

### Actual Behavior

An exception is raised:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### Environment

Production application build with Visual Studio for Mac.

```
Version 8.0.4 (build 0)
Installation UUID: e7968add-33ac-44ad-adb7-bac0ae10fe26
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.147 (Visual Studio Enterprise)
Hash: a5f2633f
Branch: d16-1
Build date: 2019-04-10 09:42:20-0400

=== Xamarin.iOS ===

Version: 12.10.0.147 (Visual Studio Enterprise)
Hash: a5f2633f
Branch: d16-1
Build date: 2019-04-10 09:42:19-0400

=== Xamarin Designer ===

Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

=== Xamarin.Android ===

Version: 9.3.0.14 (Visual Studio Enterprise)
Android SDK: /Users/username/Library/Android/sdk
	Supported Android versions:
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08@bf4e8d2ae19
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/master@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-04-05 16:58:56 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800040000
Git revision: 09831ae7eef8ea58cdfad2e923c65a5bf70d27fd
Build date: 2019-04-15 23:04:13+00
Build branch: master
Xamarin extensions: 5efedb990d786142d3b54351c01ce867af7b7680

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64


```

### Build Logs
No Build log but AppCenter error traces avaible here : [https://gist.github.com/johnthiriet/41383909ba1da19f6f931e14b1e274d1](https://gist.github.com/johnthiriet/41383909ba1da19f6f931e14b1e274d1)

### Example Project (If Possible)

No sample project.

### Comments

From what I see in the source code on the NSUrlSessionHandler we see a comment telling that a lock is not needed in the BackgroundNotificationCb.
Maybe it is possible that some locking mecanism is in fact needed:

```
void BackgroundNotificationCb (NSNotification obj)
{
	// we do not need to call the lock, we call cancel on the source, that will trigger all the needed code to 
	// clean the resources and such
	foreach (var r in inflightRequests.Values) {
		r.CompletionSource.TrySetCanceled ();
	}
}
```

**Comment by mandel-macaque** [comment]
@johnthiriet do you have a full stack trace?

**Comment by mandel-macaque** [comment]
@johnthiriet also, that means that the apps is going into background mode while performing a download. which is why it is cancelling the request. I mention this because if you are expecting the downloads to work, they won't and they will be canceled once the app is not in the foreground. 

To be able to do that you should use a background session.

**Comment by johnthiriet** [comment]
@mandel-macaque The full callstack that I have is the one I have posted in this link [https://gist.github.com/johnthiriet/41383909ba1da19f6f931e14b1e274d1](https://gist.github.com/johnthiriet/41383909ba1da19f6f931e14b1e274d1).
This is what is retrieve from our AppCenter Crashes.

In our app, we cancel any tasks when a viewcontroller gets disposed and we even call dispose ourselves on modal viewcontrollers do be sure the memory is free.
Whatever happens in the app, I think the exception thrown in this crash is not really relevant for the user of the NSUrlSessionHandler since it means we have to look at the source code of the framework to understand what is happening.

Maybe doing something like this would prevent the issue without locking the whole thing ?

```
void BackgroundNotificationCb (NSNotification obj)
{
        var arr = inflightRequests.Values.ToArray(); // Copy the list of requests currently running to prevent modifications by other threads.
	foreach (var r in arr) {
		r.CompletionSource.TrySetCanceled();
	}
}
```
But since I am not sure on how to test that the bug is fixed witht his code I hesitate to do a pull request.

```

**Comment by mandel-macaque** [comment]
@johnthiriet I'm piking this up, do you still have the issue (sorry for the delay, we are working hard on xcode 11)

**Comment by johnthiriet** [comment]
@mandel-macaque Sorry for the late response. As we were about to publish a new version into production last week I waited a bit to be sure. I can confirm that we still have the issue as it happened today.

Here is the log :
[https://gist.github.com/johnthiriet/954e92d54c9d6df9cc7bc38fe4f0d46b](https://gist.github.com/johnthiriet/954e92d54c9d6df9cc7bc38fe4f0d46b)

**Comment by btctcn** [comment]
<img width="891" alt="Screenshot 2019-08-22 at 16 51 47" src="https://user-images.githubusercontent.com/11044605/63520314-323ae000-c4fd-11e9-99ae-9ffe53eba0b9.png">

@mandel-macaque Please force fixing. It's really a big problem.

**Comment by mandel-macaque** [comment]
This issue has already been fixed in https://github.com/xamarin/xamarin-macios/pull/6877
