### ISSUE TITLE
Inform the user somehow if exporting generic types to Objective-C due to performance reasons

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#6289]
Calling Objective-C exported functions for generic managed types is slower than calling exported functions for non-generic types. This is known and [documented](https://docs.microsoft.com/en-us/xamarin/ios/internals/api-design/nsobject-generics#performance).

However, it can come as a surprise to the user (#6268), so we might want to find a way to inform the user about such scenarios.

Ideas:

* mtouch/mmp warning
  * I don't like this much, since we'd be showing a warning for a completely valid scenario.
* code analyzer
  * I'm not sure we have XI/XM-specific code analyzers right now, so this might be a bit more complicated.

Other ideas?

**Comment by chamons** [comment]
@rolfbjarne - Could this be a roslyn analyzer?

**Comment by Therzok** [comment]
Yup, that could completely work as a roslyn analyzer.

**Comment by chamons** [comment]
Added to board of potential projects: https://github.com/xamarin/maccore/projects/3
