### ISSUE TITLE
Is Project Catalyst on the timeline yet for Xamarin Forms

### ISSUE THREAD

**Issue by rscholey** [xamarin/xamarin-macios#6317]
Would love to see my application running on a Mac OS.

**Comment by dalexsoto** [comment]
@rscholey You definitely can currently run Xamarin.Forms on macOS see https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac

That said for Xcode 11 features please see https://github.com/xamarin/xamarin-macios/issues/6206 one thing I would like you to take into account is that Catalyst is macOS 10.15 and up so any apps targeting Catalyst would require that minimum OS.

I'll close this issue in favor of #6206.
