### ISSUE TITLE
[mono 2019-06][Tests] mono-native-compat fails on the iOS Unified Today Extension 64-bit large

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#6319]
Several tests fall in the extension on release mode:

> [FAIL] NativePlatformTest.PlatformType : System.EntryPointNotFoundException : mono_native_get_platform_type 
> [FAIL] NativePlatformTest.TestInitialize : System.EntryPointNotFoundException : mono_native_initialize 
> [FAIL] Introspection.CheckSymbols : System.EntryPointNotFoundException : mono_native_initialize 
> [FAIL] Introspection.TestInvoke : System.EntryPointNotFoundException : mono_native_initialize 
> [FAIL] NativePlatformConfig.PlatformType : System.EntryPointNotFoundException : mono_native_get_platform_type 
> Tests run: 6 Passed: 1 Inconclusive: 0 Failed: 5 Ignored: 0

**Comment by rolfbjarne** [comment]
This might not be due to 2019-06, since we don't run these tests (today extension tests) in CI.

**Comment by mandel-macaque** [comment]
No related to 2019-06, is an issue in the tests.

**Comment by mandel-macaque** [comment]
I have ran the tests locally. Tests pass in simulator and device. Sometimes they are reported as a crash but the tests do pass. Also AFAIK a number of the tests got moved to the new mscorlib tests since they overlap.
