### ISSUE TITLE
[mono 2019-06] Monotouch tests fail on the today extension

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#6320]
The following tests do fail on the today extension:

> [FAIL] MessageHandlerTest.AcceptSslCertificatesServicePointManager(System.Net.Http.HttpClientHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.AcceptSslCertificatesServicePointManager(System.Net.Http.NSUrlSessionHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.DnsFailure(System.Net.Http.HttpClientHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.DnsFailure(System.Net.Http.CFNetworkHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.DnsFailure(System.Net.Http.NSUrlSessionHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.RedirectionWithAuthorizationHeaders(System.Net.Http.HttpClientHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.RedirectionWithAuthorizationHeaders(System.Net.Http.CFNetworkHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.RedirectionWithAuthorizationHeaders(System.Net.Http.NSUrlSessionHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.RejectSslCertificatesServicePointManager(System.Net.Http.HttpClientHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.RejectSslCertificatesServicePointManager(System.Net.Http.NSUrlSessionHandler) : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] MessageHandlerTest.TestNSUrlSessionHandlerCookies() : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] SystemSoundTest.FromFile : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] SystemSoundTest.TestCallbackPlayAlert : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] SystemSoundTest.TestCallbackPlaySystem : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] CategoryTest.NavigationControllerOverride : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] BundleTest.TestExecutableUrl : Expected: String containing "monotouchtest.app/monotouchtest" 
> [FAIL] BundleTest.TestGetMain : Expected string length 26 but was 47. Strings differ at index 26. 
> [FAIL] BundleTest.TestResourcesDirectoryUrl : Expected: String containing "monotouchtest.app/" 
> [FAIL] BundleTest.TestSupportFilesDirectoryUrl : Expected: String containing "monotouchtest.app/" 
> [FAIL] BundleTest.TestUrl : Expected: String containing "monotouchtest.app/" 
> [FAIL] DispatchBlockTest.NotifyAction : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] DispatchBlockTest.NotifyDispatchBlock : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] DispatchGroupTest.NotifyWithAction : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] DispatchGroupTest.NotifyWithDispatchBlock : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] DispatchQueueTests.DispatchAsync : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] DispatchQueueTests.DispatchBarrierAsync : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] FunctionTest.Test : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] PatternTest.DrawTest : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] ThreadTest.GetEntryAssemblyReturnsOk : Expected: not null 
> [FAIL] UrlSessionTest.CreateDataTaskAsync : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] UrlSessionTest.DownloadDataAsync : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] LeaderboardViewControllerTest.DefaultCtor : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] GKAgent3DTest.RotationTest : System.EntryPointNotFoundException : x_get_matrix_float3x3 
> [FAIL] LocalSearchTest.EmptyRequest : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] MDCameraTest.ProjectionMatrix : System.EntryPointNotFoundException : x_get_matrix_float4x4 
> [FAIL] MDLMaterialPropertyTest.Ctors : System.EntryPointNotFoundException : x_get_matrix_float4x4 
> [FAIL] MDLStereoscopicCameraTest.Properties : System.EntryPointNotFoundException : x_get_matrix_float4x4 
> [FAIL] MDLTransformComponentTest.CreateGlobalTransformTest : System.EntryPointNotFoundException : x_mdltransform_create_global_transform 
> [FAIL] MDLTransformComponentTest.LocalTransformTest : System.EntryPointNotFoundException : x_mdltransformcomponent_get_local_transform 
> [FAIL] MDLTransformComponentTest.MatrixTest : System.EntryPointNotFoundException : x_get_matrix_float4x4 
> [FAIL] MDLTransformTest.Ctors : System.EntryPointNotFoundException : x_get_matrix_float4x4 
> [FAIL] MDLTransformTest.GetRotationMatrixTest : System.EntryPointNotFoundException : x_mdltransform_get_rotation_matrix 
> [FAIL] VpnManagerTest.SharedManager : LocalizedDescription 
> [FAIL] RegistrarTest.BlockCollection : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] SKTransformNodeTest.RotationMatrix : System.EntryPointNotFoundException : x_get_matrix_float3x3 
> [FAIL] UniformTest.Create : System.EntryPointNotFoundException : x_get_matrix_float2x2 
> [FAIL] UniformTest.Ctors : System.EntryPointNotFoundException : x_get_matrix_float2x2 
> [FAIL] ActionSheetTest.CtorAllNulls : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] ActionSheetTest.CtorDefault : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] ActionSheetTest.CtorDelegate : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] ActionSheetTest.InitWithFrame : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] AlertViewTest.CtorDelegate : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] AlertViewTest.CtorNull : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] AlertViewTest.FirstOtherButtonIndex : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] AlertViewTest.InitWithFrame : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] GuidedAccessRestrictionTest.GuidedAccessConfigureAccessibilityFeaturesTest : System.NullReferenceException : Object reference not set to an instance of an object 
> [FAIL] UIAlertControllerTest.InitWithNibNameTest : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] UISpringLoadedInteractionSupportingTest.UIAlertControllerSpringLoadTest : Foundation.MonoTouchException : Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Feature not available in extensions of type com.apple.widget-extension 
> [FAIL] WeakReferenceTest.NoRetainCyclesExpectedTest : System.NullReferenceException : Object reference not set to an instance of an object 
> Tests run: 2450 Passed: 2363 Inconclusive: 28 Failed: 59 Ignored: 34

This happens on all configurations.

**Comment by rolfbjarne** [comment]
This might not be due to 2019-06, since we don't run these in CI.

**Comment by mandel-macaque** [comment]
@rolfbjarne yes, I'm setting it to be 2019-06 because I have not tested in master. Once I run all the tests there, I'll update the issues.

**Comment by mandel-macaque** [comment]
Happens outside 2019-06, moving to future.

**Comment by mandel-macaque** [comment]
Tested with master 002b4dffd2ebb9882f92c7d8c9772cefc77f8692 and test pass.
