### ISSUE TITLE
[tests] Sample tests are failing on the `GenerateDepsFile` task

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#6336]
This seems to be because we're using a newer VSMac as of https://github.com/xamarin/xamarin-macios/commit/b1f7039ecdab752fe431529998df29e0c29f1106

Might or might not be fixed with https://github.com/xamarin/xamarin-macios/pull/6279.

It started happening here: https://github.com/xamarin/xamarin-macios/commit/a568b39807386733206c0f77242cb7b0654918a1#commitcomment-33951291

**Comment by rolfbjarne** [comment]
Duplicate of https://github.com/xamarin/maccore/issues/1811.
