### ISSUE TITLE
AppDelegate DidFailToContinueUserActivitiy method name typo

### ISSUE THREAD

**Issue by justintoth** [xamarin/xamarin-macios#6339]
There is a typo in the method name in AppDelegate:

```
[MethodImpl (MethodImplOptions.NoInlining)]
		[Export ("application:didFailToContinueUserActivityWithType:error:")]
		[Introduced (PlatformName.iOS, 8, 0, PlatformArchitecture.All, null)]
		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		public virtual void DidFailToContinueUserActivitiy (UIApplication application, string userActivityType, NSError error);
```

It should be DidFailToContinueUserActivity, not DidFailToContinueUserActivitiy.

**Comment by dalexsoto** [comment]
Thank you for your input, unfortunately fixing this is a breaking change, this issue has been marked as such and whenever we are able to break binary compatibility we'll fix it.

Thank you so much again!

**Comment by rolfbjarne** [comment]
We've already covered this is our code base for when (in our future) we can do breaking changes , so I'm closing this bug report: https://github.com/xamarin/xamarin-macios/blob/a8fdf6db6e165e4426fe397c814501a47d054b53/src/uikit.cs#L3485-L3489
