### ISSUE TITLE
[xcode11] Bind CIFilters and fix test

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#6340]
Xcode 11 added some new filters: CIGaborGradients, CIKeystoneCorrectionCombined, CIKeystoneCorrectionHorizontal, CIKeystoneCorrectionVertical, CIPerspectiveRotate

I ignored those for now so the tests don't complain, we need to update the tests again when we bind `CoreImage`.

**Comment by spouliot** [comment]
added in https://github.com/xamarin/xamarin-macios/pull/6358
