### ISSUE TITLE
mscorlib tests fail on iOS32b

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#6343]
This happens on the latests master (4992af65b60e80b84bfcb73a3260b7db5a411111) and only on iOS 32b devices:

> [FAIL] System.Tests.ConvertToInt16Tests.FromDouble 
> [FAIL] System.Tests.ConvertToInt16Tests.FromDouble Test name: System.Tests.ConvertToInt16Tests.FromDouble 
> [FAIL] System.Tests.ConvertToInt16Tests.FromInt32 
> [FAIL] System.Tests.ConvertToInt16Tests.FromInt32 Test name: System.Tests.ConvertToInt16Tests.FromInt32 
> [FAIL] System.Tests.ConvertToInt16Tests.FromStringWithBase 
> [FAIL] System.Tests.ConvertToInt16Tests.FromStringWithBase Test name: System.Tests.ConvertToInt16Tests.FromStringWithBase 
> [FAIL] System.Tests.ConvertToInt16Tests.FromInt64 
> [FAIL] System.Tests.ConvertToInt16Tests.FromInt64 Test name: System.Tests.ConvertToInt16Tests.FromInt64 
> [FAIL] System.Tests.ConvertToInt16Tests.FromSByte 
> [FAIL] System.Tests.ConvertToInt16Tests.FromSByte Test name: System.Tests.ConvertToInt16Tests.FromSByte 
> [FAIL] System.Tests.ConvertToInt16Tests.FromInt16 
> [FAIL] System.Tests.ConvertToInt16Tests.FromInt16 Test name: System.Tests.ConvertToInt16Tests.FromInt16 
> [FAIL] System.Tests.ConvertToInt16Tests.FromDecimal 
> [FAIL] System.Tests.ConvertToInt16Tests.FromDecimal Test name: System.Tests.ConvertToInt16Tests.FromDecimal 
> [FAIL] System.Tests.ConvertToInt16Tests.FromSingle 
> [FAIL] System.Tests.ConvertToInt16Tests.FromSingle Test name: System.Tests.ConvertToInt16Tests.FromSingle 
> [FAIL] System.Tests.ConvertToInt16Tests.FromString 
> [FAIL] System.Tests.ConvertToInt16Tests.FromString Test name: System.Tests.ConvertToInt16Tests.FromString 
> [FAIL] System.Tests.MathTests.Clamp_SByte(value: -1, min: -1, max: 1, expected: -1) 
> [FAIL] System.Tests.MathTests.Clamp_SByte(value: -1, min: -1, max: 1, expected: -1) Test name: System.Tests.MathTests.Clamp_SByte(value: -1, min: -1, max: 1, expected: -1) 
> [FAIL] System.Tests.MathTests.Clamp_SByte(value: -2, min: -1, max: 1, expected: -1) 
> [FAIL] System.Tests.MathTests.Clamp_SByte(value: -2, min: -1, max: 1, expected: -1) Test name: System.Tests.MathTests.Clamp_SByte(value: -2, min: -1, max: 1, expected: -1) 
> [FAIL] System.Tests.MathTests.Min_SByte 
> [FAIL] System.Tests.MathTests.Min_SByte Test name: System.Tests.MathTests.Min_SByte 
> [FAIL] System.Tests.MathTests.Clamp_Short(value: -2, min: -1, max: 1, expected: -1) 
> [FAIL] System.Tests.MathTests.Clamp_Short(value: -2, min: -1, max: 1, expected: -1) Test name: System.Tests.MathTests.Clamp_Short(value: -2, min: -1, max: 1, expected: -1) 
> [FAIL] System.Tests.MathTests.Clamp_Short(value: -1, min: -1, max: 1, expected: -1) 
> [FAIL] System.Tests.MathTests.Clamp_Short(value: -1, min: -1, max: 1, expected: -1) Test name: System.Tests.MathTests.Clamp_Short(value: -1, min: -1, max: 1, expected: -1) 
> [FAIL] System.Tests.MathTests.Min_Int16 
> [FAIL] System.Tests.MathTests.Min_Int16 Test name: System.Tests.MathTests.Min_Int16

**Comment by rolfbjarne** [comment]
This will not be an issue in .NET 8 (we're dropping 32-bit support).
