### ISSUE TITLE
BCL test applications cannot be built for iOS 32b due to the lag of linker

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#6345]
Large applications fail with the following errors when building:

> 1:05:56.2160820 /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/obj/iPhone/Debug32/mtouch-cache/armv7/monotouch_System.Core_xunit-test.dll.s(1508937,8): error GDC116A36: can not encode offset '0x10000AC' in resulting scattered relocation. [/Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/BCL tests group 4.csproj] 
> 11:05:56.2165020 /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/obj/iPhone/Debug32/mtouch-cache/armv7/monotouch_System.Core_xunit-test.dll.s(1508939,8): error GDC116A36: can not encode offset '0x10000CC' in resulting scattered relocation. [/Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/BCL tests group 4.csproj] 
> 11:05:56.2167260 /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/obj/iPhone/Debug32/mtouch-cache/armv7/monotouch_System.Core_xunit-test.dll.s(1508960,8): error GDC116A36: can not encode offset '0x100018C' in resulting scattered relocation. [/Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/BCL tests group 4.csproj] 
> 11:05:56.2269430 /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/obj/iPhone/Debug32/mtouch-cache/armv7/monotouch_System.Core_xunit-test.dll.s(1508962,8): error GDC116A36: can not encode offset '0x10001AC' in resulting scattered relocation. [/Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/BCL tests group 4.csproj] 
> 11:05:56.2271500 /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/obj/iPhone/Debug32/mtouch-cache/armv7/monotouch_System.Core_xunit-test.dll.s(1508989,8): error GDC116A36: can not encode offset '0x10002BC' in resulting scattered relocation. [/Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/BCL tests group 4.csproj] 
> 11:05:56.2273000 /Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/obj/iPhone/Debug32/mtouch-cache/armv7/monotouch_System.Core_xunit-test.dll.s(1508991,8): error GDC116A36: can not encode offset '0x10002DC' in resulting scattered relocation. [/Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/tmp-test-dir/[xUnit] Mono BCL tests group 4432/BCL tests group 4.csproj] 

Looks like we are hitting the limit, so we should make the apps smaller for iOS32.

**Comment by rolfbjarne** [comment]
This will not be an issue in .NET 8 (we're dropping 32-bit support).
