### ISSUE TITLE
Properties are not available in TypeDescriptor.GetProperties() method while setting Linker settings as LinkAll

### ISSUE THREAD

**Issue by shivagurunathan** [xamarin/xamarin-macios#6347]
The properties are not available in the TypeDescriptor.GetProperties() method while setting the Linker setting as LinkAll. But the properties are available if we set the Linker settings as Link Framework SDKs Only. 

### Steps to Reproduce

1.  Run the attached Xamarin.iOS sample with Linker settings as LinkAll.
2.  Check the ItemProperties variable.
3. Note that properties are not available while setting Linker settings as LinkAll.
4. We have tested the issue in iPhone 7 device.

### Expected Behavior

Required properties should be available in the TypeDescriptor.GetProperties() method while setting Linker settings as LinkAll.

### Actual Behavior

Properties are not available in the TypeDescriptor.GetProperties() method while setting Linker settings as LinkAll. 

### Environment

```
```

### Example Project (If Possible)

I have attached the sample below.
[Custom_Font (2).zip](https://github.com/xamarin/xamarin-macios/files/3301158/Custom_Font.2.zip)

Refer the screenshots for reference:
[Linker_issue.zip](https://github.com/xamarin/xamarin-macios/files/3301166/Linker_issue.zip)

**Comment by spouliot** [comment]
I'll have a look but I suspect it's normal. The `TypeDescriptor` is a reflection API [1] and the linker cannot, by static analysis, guess what the code might reflect upon.

IOW if you're using reflection then you must, manually, preserve (by any mean) any API that you want available at runtime.

[1] https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typedescriptor?view=netframework-4.8

**Comment by spouliot** [comment]
So there's nothing that preserve the `getter` of the properties.

Either 
* add `[Preserve (AllMembers = true)]` to your `OrderInfo` type; or
* use the getters in your code, e.g.

```csharp
public override string ToString ()
{
	return $"{Date} - {OrderID} - {CustomerID} - {Customer} - {ShipCountry} - {ShipCity}";
}
```

and all 6 properties will be visible.

**Comment by shivagurunathan** [comment]
Hi @spouliot,
Thanks, it works man.
