### ISSUE TITLE
[mtouch] Measure performance of not passing `--debug` to AOT unconditionally

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#6353]
Xamarin.Mac users have found a non-trivial performance hit when adding --debug to the AOT compiler invocation in applications that are AOT'ed. 

During the PR, it was mentioned that iOS unconditionally adds `--debug` to the AOT compiler. 

Maybe we should see if there is a similar performance hit on iOS?

**Comment by vargaz** [comment]
These 2 PRs _might_ fix the issue:
https://github.com/mono/mono/pull/15239
https://github.com/mono/mono/pull/15250

**Comment by rolfbjarne** [comment]
This is not applicable to .NET.
