### ISSUE TITLE
UISegmentedControl binding error

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#6357]
The binding for `UISegmentedControl` has...

```csharp
[BindingImpl(BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
[Export("dividerImageForLeftSegmentState:rightSegmentState:barMetrics:")]
public virtual UIImage DividerImageForLeftSegmentStaterightSegmentStatebarMetrics(UIControlState leftState, UIControlState rightState, UIBarMetrics barMetrics);
```

which, for consistency, should be `GetDividerImage(...)` rather than `DividerImageForLeftSegmentStaterightSegmentStatebarMetrics(...)`

I realize it's a breaking change, but I believe it's also one where the compiler error would be instantly recognizable and immediately understood by anyone who has overridden or needed to make use of this call.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/538692/uisegmentedcontrol-binding-error.html
VSTS ticketId: 850102_

**Comment by dalexsoto** [comment]
Thank you for the feedback, as you mention this is a breaking change unfortunately we cannot make the change right away but it will be fixed in the future when we are able to break the API.

Thanks again!

**Comment by rolfbjarne** [comment]
@dalexsoto this method is not in a protocol, so we can at least implement the better named version and obsolete the old one already.
