### ISSUE TITLE
Generated binding compile time error when conforming to 2 protocols with the same @required member

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#6366]
Since two protocols have the same required member we generate it twice - so the C# compiler is not happy.

AFAIK the two protocols can be used separately, so the definition should be in both, or together (and the declaration should be merged)

### Steps to Reproduce

1. Uncomment `bool Available { [Bind ("isAvailable")] get; }` in `NFCNdefTag` (corennfc.cs)
2. Build

### Expected Behavior

No error.

### Actual Behavior

```
error CS0102: The type 'NFCFeliCaTagWrapper' already contains a definition for 'Available'
```

### Environment

`xcode11`

### Example Project (If Possible)

See (upcoming) PR for `corenfc` support

**Comment by rolfbjarne** [comment]
Fixed: https://github.com/xamarin/xamarin-macios/commit/3ee1329e0e3f501afd5aa59979f8d37f88c5d96e.
