### ISSUE TITLE
[WIKI] both subscribe and archives links are broken

### ISSUE THREAD

**Issue by joconte** [xamarin/xamarin-macios#6409]
![image](https://user-images.githubusercontent.com/41507018/59976681-3ebbbe80-95c8-11e9-95ab-645dc9f675b4.png)

 Both subscribe and archives links are broken :

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/41507018/59976696-70348a00-95c8-11e9-801c-8e93a2ac0b62.png">

**Comment by rolfbjarne** [comment]
The mailing list archive can be read here instead: https://mono.github.io/mail-archives/macios-devel/index.html, but in any case this mailing list has been retired (https://mono.github.io/mail-archives/macios-devel/2018-May/000048.html).

**Comment by rolfbjarne** [comment]
I've removed the info about the mailing list from the wiki.
