### ISSUE TITLE
NSObject2.cs IsProtocol method has noticable overhead

### ISSUE THREAD

**Issue by DavidKarlas** [xamarin/xamarin-macios#6444]
### Steps to Reproduce

1. Start profiling VSfM
2. Type some code fast
3. Profiling results will include noticeable time spent in `IsProtocol` calls

### Expected Behavior
Little to no overhead for `IsProtocol` calls.

### Actual Behavior
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/774791/60260325-95cbd700-98d9-11e9-98ac-4c9f8bdba21d.png">

### Environment
https://gist.github.com/DavidKarlas/6b0c909c25212844a6557bf26a21b14d

### Build Logs
N/A

### Example Project (If Possible)
Not sure how to cause this method to be called.

**Comment by rolfbjarne** [comment]
@DavidKarlas can you try [xamarin.mac-5.15.0.247.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/issue-6444-cached-isprotocol/b241e4964e319ce3f36c31a049300a9fd30962a8/1/package/xamarin.mac-5.15.0.247.pkg) to see if that's better?

**Comment by DavidKarlas** [comment]
Hi, after 1 year... I'm back, maybe summer time is when we think VSMac is slow and start working on perf, no idea :D
So... I found repro for this:
Create new Cocoa app and change file ViewController.cs to:
```csharp
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using AppKit;
using CoreGraphics;
using Foundation;

namespace Repro6444
{
	public partial class ViewController : NSViewController
	{
		public ViewController(IntPtr handle) : base(handle)
		{
		}

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();

			await Task.Delay(1000);
			var sw = Stopwatch.StartNew();
			for (int i = 0; i < 100000; i++) {
				var view = new MyNSView(new CGRect(10, 10, 30, 30));
				View.AddSubview(view);
				view.RemoveFromSuperview();
			}
			sw.Stop();
			View.Window.Title = sw.Elapsed.ToString();
		}

		private class MyNSView : NSView
		{
			public MyNSView(CGRect frameRect) : base(frameRect)
			{
			}
		}
	}
}
```
Build from previous comment improves things, but there is still path in `ConfirmsToProtocol` that uses Reflection, so I wonder if its possible to do this caching on `ConfirmsToProtocol` level?
Here is ActivityMonitor sample with above build:
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/774791/86900119-3b2fa280-c10b-11ea-8f9e-29f8ac8baf99.png">

**Comment by stephen-hawley** [comment]
Compiling against the .NET sdk v 6.0.402, I'm not seeing any appreciable differences between using a cache and not using a cache. When initially run against the 'current' SDK, the reported time for the app was ~22 seconds. When run against 6.0.402, the time is around 8.4 seconds and there is no appreciable difference between caching and no caching. I suspect that the runtime is caching the reflection information, but I wasn't able to verify it.
