### ISSUE TITLE
[xcode11-support] XI/XM packages can't be installed without override in System Preferences (Security) (signing?)

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#6452]
### Steps to Reproduce

1.  Download https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode11/903c3eec31bc7c9f819f958df5f2a567b2d30631/64/package/xamarin.mac-5.99.0.159.pkg
2. Try to install 
3. 
<img width="532" alt="screen_shot_2019-06-27_at_12 12 15_pm" src="https://user-images.githubusercontent.com/6392201/60286665-9a8e8c00-98d5-11e9-9023-526a1e9017b6.png">

### Expected Behavior

Installing cleanly

### Actual Behavior

Dialog that require override to pass

### Environment
10.15 Beta

**Comment by dalexsoto** [comment]
I can confirm this happens on a clean installation of Catalina

**Comment by dalexsoto** [comment]
As a workaround you can follow these steps:

1. Right click on the installer file (.pkg).
2. Click `Open` (The very first option of the right click menu).
3. Click `Open` in the presented dialog.
4. Follow on screen instructions to install.

![Screen Recording 2019-06-27 at 1 40 14 PM](https://user-images.githubusercontent.com/204671/60289144-c153bf00-98e3-11e9-8b21-72a5ee72d7d2.gif)

**Comment by Sevenish** [comment]
The workaround worked for xamarin.mac-5.99.0.159.pkg

But I still cannot install xamarin.ios-12.99.0.159.pkg
Error: This package is incompatible with this version of macOs. The package us trying to install content to the system volume...

macOS Catalina 10.15 beta 3 (19A501i)

**Comment by aphex3k** [comment]
This seems solved for Xamarin.Mac but not Xamarin.iOS? Any timeline?

**Comment by dalexsoto** [comment]
@aphex3k Could you try the following package? 

https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode11/d4b8c3ab737cc6250e563722a029a6830fa93a68/164/package/xamarin.ios-12.99.2.16.pkg

**Comment by aphex3k** [comment]
@dalexsoto, That one worked without problem. It gave me a prompt to access my download folder though...

**Comment by chamons** [comment]
I believe it prompts based where the file is located. If you moved it to Desktop I'd expect a prompt there.

**Comment by aphex3k** [comment]
That would make sense...

**Comment by aphex3k** [comment]
@dalexsoto Can you provide a download link for Xamarin.iOS-12.99.2.40.pkg just like you did for 12.99.2.16 please?

**Comment by rolfbjarne** [comment]
@aphex3k [xamarin.ios-12.99.2.40.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode11/d883febff0331421d9099ea3192bb9d5d43e72dd/189/package/xamarin.ios-12.99.2.40.pkg)

**Comment by rolfbjarne** [comment]
This is working now that we have notarized packages.
