### ISSUE TITLE
[XCode 11] Rebuilding existing Xamarin.iOS with Xcode 11 Beta 2 fails with various MTOUCH native linking errors

### ISSUE THREAD

**Issue by stefandevo** [xamarin/xamarin-macios#6471]
### Steps to Reproduce

Installed XCode 11 Beta 2 on Mac Mojave 10.14.5 (18F132), Preview of VSforMac, building a non modified app is building with XCode 10.

### Expected Behavior

The application is building without errors.

### Actual Behavior

The application build provides following errors

```
MTOUCH : warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'System.Net.Security' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
clang : error : linker command failed with exit code 1 (use -v to see invocation)
error MT5209 : Native linking error : framework not found WatchKit
MTOUCH : error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /MyAppPath/obj/iPhoneSimulator/Debug/device-builds/iphone11.8-13.0/Entitlements.xcent
MTOUCH : error MT5202: Native linking failed. Please review the build log.
    73 Warning(s)
    4 Error(s)
```

### Environment

```
=== Visual Studio Enterprise 2019 for Mac (Preview) ===

Version 8.2 Preview (8.2 build 874)
Installation UUID: dec165e8-57fe-48f8-9c2e-66efab8f08b9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.83 (d16-2 / f08d4e3e)

	Package version: 600000296

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.296 (2019-02/1e9f3bfbc5a) (64-bit)
	Package version: 600000296

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.2
	2.2.1
	2.2.0
	2.1.4
	2.1.2
	2.1.1
	2.1.0
	2.1.0-rc1
	2.1.0-preview2-26406-04
	2.0.7
	2.0.6
	2.0.5
	2.0.4
	2.0.3
	2.0.0
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.2.104/Sdks
SDK Versions:
	2.2.104
	2.2.102
	2.1.402
	2.1.302
	2.1.301
	2.1.300
	2.1.200
	2.1.105
	2.1.101
	2.1.4
	2.1.3
	2.0.3
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.0 (14855.21)
Build 11M337n

=== Xamarin.Mac ===

Version: 5.99.0.159 (Visual Studio Enterprise)
Hash: 903c3eec
Branch: xcode11
Build date: 2019-06-27 10:01:06-0400

=== Xamarin.Android ===

Version: 9.4.0.34 (Visual Studio Enterprise)
Commit: xamarin-android/d16-2/7cce305
Android SDK: /Users/stefan/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.3
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-02@c6edaa62f94
Java.Interop: xamarin/java.interop/d16-2@b2b2610
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@4f717b6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/stefan/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2
Build date: 2019-06-19 16:30:22 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 12.14.0.91 (Visual Studio Enterprise)
Hash: 2f1cc7bb
Branch: d16-2
Build date: 2019-06-07 02:49:22-0400

=== Xamarin Designer ===

Version: 16.2.0.325
Hash: f10cfbf83
Branch: remotes/origin/d16-2
Build date: 2019-06-19 19:00:46 UTC

=== Build Information ===

Release ID: 802000874
Git revision: e57770efe0d2b92ade1e1b75e52731614e5f9487
Build date: 2019-06-25 19:43:32+00
Build branch: release-8.2-preview2
Xamarin extensions: a74fb3eb8717fbcb82500b3a107694ad5185aa48

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64


```

**Comment by rolfbjarne** [comment]
Apple forgot to ship the WatchKit framework (for iOS) with their Xcode betas, so this won't work until Apple fixes their SDK (you'd get the same problem with Xcode).

Hopefully they'll have it fixed in Beta 3.

**Comment by spouliot** [comment]
@stefandevo if your application does not use WatchKit then enabling the managed linker (e.g. **Link SDK frameworks only**) should remove the associated code (so the native linker won't report an error).

**Comment by stefandevo** [comment]
Thanks @spouliot that fixed the problem too (as I normally never Link for Simulator builds).

**Comment by jmlumpkin** [comment]
This does not work still as of Beta 6. The same workaround works, but if trying to use other features, like the inspector, that requires this, it does not work.

**Comment by spouliot** [comment]
@jmlumpkin more details in https://github.com/xamarin/xamarin-macios/pull/6503

This will be part of our 5th preview (going out real-soon-now™️)

**Comment by joehanna** [comment]
This is started happening today with Xcode 11 (11A420a) released via Mac AppStore.
Visual Studio Mac 8.2.6 (build 26)

**Comment by EricNgo1972** [comment]
It happens today (Sep 21st 2019) with Xcode 11. VS2019 Windows.

**Comment by mrutter** [comment]
This is started happening today for me too with Xcode 11 (11A420a) released via Mac AppStore (downloaded and installed automatically by Mac OS).

Visual Studio Mac 8.2.6 (build 26)

**Comment by dbwelch** [comment]
Same issue, but, what does "link framework SDK only" mean?  Is there a setting for this in Xamarin?  Some details would be helpful.

**Comment by mrutter** [comment]
@dbwelch: you have to open the properties window (options) of the iOS project, then go to "iOS Build", "Linker behavior" and set the appropriate value.

Hope it helps.

**Comment by dbwelch** [comment]
Got it, thanks!

**Comment by TrueGeek** [comment]
I started getting this issue this morning as well when XCode updated. However, I already have Link Framework SDKs Only. I'm unable to build the project.

**Comment by illialarka** [comment]
> 
> 
> @stefandevo if your application does not use WatchKit then enabling the managed linker (e.g. **Link SDK frameworks only**) should remove the associated code (so the native linker won't report an error).

Thanks! That works for me.  This issue has appeared when I  updated XCode, new simulators were added for iPhone 11, iPhone Pro, iPhone Pro Max. Thanks a lot!

**Comment by IsaacBarham** [comment]
Hot Reload won't work if the linker is not set to Don't Link. There seems to be no way around this.

**Comment by dariokwo** [comment]
Just updated Xcode and wish I didn't. This is quite disturbing considering I'm on a middle of a project Building Cross-platform Apps with Xamain and C# on VS 2019. Was working fine, but then this error after the updating. Hopefully they release an update with a fix soon. 

Btw, is it possible to revert to previous version of Xcode after reinstalling

**Comment by CDBridger** [comment]
Same situation for me as @dariokwo

**Comment by MurrayJack** [comment]
Also having this issue, after being forced to upgrade.

**Comment by MurrayJack** [comment]
I am on VS2019, and changing my linker behavior to "Link All" meant I could build

**Comment by rscholey** [comment]
Having same problem.  Now I'm stuck and can't do any more with on my application

**Comment by rolfbjarne** [comment]
Our current stable version of Xamarin.iOS is not compatible with Xcode 11.

We'll release a version of Xamarin.iOS that is compatible with Xcode 11 later today. A more immediate solution is to install our preview version of Xamarin.iOS with support for Xcode 11.

**Comment by Syed-Esqimo** [comment]
Ok why is this being overlooked and not synced with Xcode release? Thanks for breaking productivity

**Comment by sehuff** [comment]
This is still a problem not sure why this is "closed".  All sort of errors that seem to be around "framework not found WatchKit".

**Comment by sehuff** [comment]
Installing the "Xcode 11 previews" for "XCode 11 Beta releases" fixes the issue.  It's a shame they didn't take the time to make this a stable release this weekend when it went live and out of beta.  #Xamarinfail

**Comment by bradlak** [comment]
Be careful with the beta version. I also installed the newest one because of that error and I can't sign application for app store now. Visual freezes and not responding.

**Comment by VeryKross** [comment]
I also want to add that this XCode update is also breaking your ability to edit Storyboards in either the Windows or MacOS version of Visual Studio. Both throw an extensive error about the designer not being able to initialize.
![image](https://user-images.githubusercontent.com/11561147/65436912-dfe92980-ddf0-11e9-97ff-c79490815c06.png)

**Comment by TomSoderling** [comment]
> Just updated Xcode and wish I didn't. This is quite disturbing considering I'm on a middle of a project Building Cross-platform Apps with Xamain and C# on VS 2019. Was working fine, but then this error after the updating. Hopefully they release an update with a fix soon.
> 
> Btw, is it possible to revert to previous version of Xcode after reinstalling

I've used Time Machine to revert an Xcode update before

**Comment by bo3po** [comment]
> This is still a problem not sure why this is "closed". All sort of errors that seem to be around "framework not found WatchKit".

I get this also...

**Comment by gacantorm** [comment]
Do you know what time the update is going to solve the problem?
<img width="623" alt="Captura de Pantalla 2019-09-23 a la(s) 11 36 38 a  m" src="https://user-images.githubusercontent.com/6685373/65451010-f8167400-de03-11e9-8461-1c9f68712f74.png">

**Comment by gacantorm** [comment]
<img width="609" alt="Captura de Pantalla 2019-09-23 a la(s) 1 20 27 p  m" src="https://user-images.githubusercontent.com/6685373/65451513-f13c3100-de04-11e9-85b7-049ddd83916a.png">
I just started the update to see what happens

**Comment by PaoloLeva** [comment]
It worked for me after last update on stable channel

**Comment by bradlak** [comment]
> Be careful with the beta version. I also installed the newest one because of that error and I can't sign application for app store now. Visual freezes and not responding.

Still doesnt work with stable version.

**Comment by rickburn** [comment]
> > Be careful with the beta version. I also installed the newest one because of that error and I can't sign application for app store now. Visual freezes and not responding.
> 
> Still doesnt work with stable version.

Same here.

**Comment by HK-AERIAL-VTOL** [comment]
> > > Be careful with the beta version. I also installed the newest one because of that error and I can't sign application for app store now. Visual freezes and not responding.
> > 
> > 
> > Still doesnt work with stable version.
> 
> Same here.

I as well cannot do any more because of this fiasco. When can we dev in Xamarin again?

**Comment by rolfbjarne** [comment]
If there are issues after upgrading to the latest stable version of Visual Studio 2019 / Visual Studio for Mac, then please file new issues and we'll have a look.

**Comment by SatinderSidhu** [comment]
wow... thanks Xamarin for giving surprises :) . I started making a video for my channel https://www.youtube.com/sidhusatinder few days back & got these errors half way through. 
Now back on track. Thanks everyone 

> <img alt="Captura de Pantalla 2019-09-23 a la(s) 1 20 27 p m" width="609" src="https://user-images.githubusercontent.com/6685373/65451513-f13c3100-de04-11e9-85b7-049ddd83916a.png">
> 
>I just started the update to see what happens

**Comment by candyd8** [comment]
> @stefandevo if your application does not use WatchKit then enabling the managed linker (e.g. **Link SDK frameworks only**) should remove the associated code (so the native linker won't report an error).

bless your soul

**Comment by Zorgino** [comment]
Works for me.

**Comment by aimore** [comment]
Still have this issue
```MTOUCH : warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'System.Net.Security' might require additional -framework=XXX or -lXXX instructions to the native linker
clang : error : linker command failed with exit code 1 (use -v to see invocation)
error MT5209 : Native linking error : library not found for -lstdc++.6
MTOUCH : error MT5202: Native linking failed. Please review the build log.```
Apple Developer Tools
Xcode 11.4 (16134)
Build 11E146

Xamarin.Mac
Version: 6.16.0.11 (Visual Studio Enterprise)
Hash: aa73e4125
Branch: d16-5-xcode11.4
Build date: 2020-03-25 11:04:02-0400

Xamarin.iOS
Version: 13.16.0.11 (Visual Studio Enterprise)
Hash: aa73e4125
Branch: d16-5-xcode11.4
Build date: 2020-03-25 11:04:03-0400

**Comment by rolfbjarne** [comment]
@aimore that's a different problem than the one reported here, so please file a new issue and we'll have a look.
