### ISSUE TITLE
[Tests][Today Extensions] mono-native-unified and mono-native-compat tests fail on iOS 64 Today extensions

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#6494]
The tests have the following failures, which do not happen on 2019-02:

> [FAIL] NativePlatformTest.PlatformType : System.EntryPointNotFoundException : mono_native_get_platform_type 
> [FAIL] NativePlatformTest.TestInitialize : System.EntryPointNotFoundException : mono_native_initialize 
> [FAIL] Introspection.CheckSymbols : System.EntryPointNotFoundException : mono_native_initialize 
> [FAIL] Introspection.TestInvoke : System.EntryPointNotFoundException : mono_native_initialize 
> [FAIL] NativePlatformConfig.PlatformType : System.EntryPointNotFoundException : mono_native_get_platform_type 

Tests fail on Release and Debug configurations but do pass on the other configurations.

Useful info:

* [Build log](https://gist.github.com/mandel-macaque/98b7f181149fbd55b989879c48763f81)
* [Run log](https://gist.github.com/mandel-macaque/8a2668dbaf8809c4a3e6cb926cbaa876)

**Comment by rolfbjarne** [comment]
I can't reproduce this anymore.
