### ISSUE TITLE
The source file `Trampolines.g.cs` is not included in the packages

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#6507]
### Steps to Reproduce

1.  `find /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/ -name Trampolines.g.cs`

### Expected Behavior

The file should be present - it's useful if you need your own `[BlockProxy]`

### Actual Behavior

The file is missing

### Environment

`master`

**Comment by rolfbjarne** [comment]
We'll look into this as part of https://github.com/xamarin/xamarin-macios/issues/14895.
