### ISSUE TITLE
Xamarin packages will show dialogs in Catalina which makes the Xamarin Installer fail.

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#6528]
Looks like Apple changes the rights that are required to write in the System volume. When trying to use the current installer in Catalina we get the following dialog:
![Screen Shot 2019-07-08 at 2 50 03 PM](https://user-images.githubusercontent.com/2190086/60835019-6c0c8d00-a1c2-11e9-8fef-f51b553840fc.png)

Also, in the very first use, the user will also have to grant access to the installer to the destination file. These two dialogs are not shown in the installer, making it fail. Full logs of the installation of the package can be found [here](https://gist.github.com/mandel-macaque/986dfcc7988a9c277ca1f48902b4bcab).

**Comment by rolfbjarne** [comment]
This looks like a dup of #6504.

**Comment by spouliot** [comment]
> Also, in the very first use, the user will also have to grant access to the installer to the destination file. 

that first dialog might be due to (lack of) notarization on the package ?

**Comment by mandel-macaque** [comment]
@rolfbjarne @spouliot we have confirmation that the dialog from https://github.com/xamarin/xamarin-macios/issues/6504 was the only one preventing the installer from working. And the first dialog is either handled by the installer, or we don't really care when the user uses a .pkg, so I'm closing this as soon as we have some feedback from @GouriKumari  :)

**Comment by GouriKumari** [comment]
I checked the above issue in Catalina beta3  using VSFMac installer with the packages linked here, https://github.com/xamarin/installer/commit/1c9711d9d6022746df9723016974f813f669c6fd.  As far as I can see XI and XM installs without any issues. 
https://gist.github.com/GouriKumari/42c03ff0dab924f6e9cd41be3695a056#file-gistfile1-txt-L76. 
https://gist.github.com/GouriKumari/956bebd0d7713c993e298a5dfd843080#file-gistfile1-txt-L796
Upgrade path was tested in Mojave and it worked.

Note:   Issue https://github.com/xamarin/xamarin-macios/issues/6452 is not fixed for VSFMac or VSFMac Installer, until it is fixed user need to give permissions first for these products to start working with XI or XM in Catalina.
