### ISSUE TITLE
asset catalog support for fonts

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#6551]
Xcode 11 beta 2 adds a new, iOS only, API `CTFontManagerRegisterFontsWithAssetNames` to register fonts from asset catalogs. 

Apple doc (nothing so far) https://developer.apple.com/documentation/coretext/3326997-ctfontmanagerregisterfontswithas?language=objc

Apple headers diff https://github.com/xamarin/xamarin-macios/wiki/CoreText-iOS-xcode11-beta2

However VS4M (and likely VS4W) don't support adding fonts to the asset catalog.

> VS bug [#944954](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/944954), VS bug [#944955](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/944955)

**Comment by rolfbjarne** [comment]
Closing, both VS bugs were closed as "Won't fix"
