### ISSUE TITLE
[xcode11-support][XM]mmp throws an error mono.framework mdk is missing on building installer on macOS10.15

### ISSUE THREAD

**Issue by GouriKumari** [xamarin/xamarin-macios#6578]
### Steps to Reproduce
1.  Build Installer project  on macOS10.15 beta3 with Xcode11 beta 3 installed
### Expected Behavior
Installer project should build successfully
### Actual Behavior
Installer build fails with an error MMP : error MM5202: Mono.framework MDK is missing. Please install the MDK for your Mono.framework version from https://www.mono-project.com/download/
### Environment
https://gist.github.com/GouriKumari/48f78ed39b36bda2920f6539b8b4923a
### Build Logs
Build Log: 

Command Line: https://gist.githubusercontent.com/GouriKumari/d050aa7db2600972f20de45e5bdffdb9/raw/25f4e8ffae0f74547cb37b872abe087ae897dc7e/gistfile1.txt

IDE: https://gist.github.com/GouriKumari/9acfd99355dec69a67a5a19559b9043f#file-gistfile1-txt-L1041
### Example Project (If Possible)
https://github.com/xamarin/installer/blob/master/XamarinInstaller.Mac.sln

### Additional Behaviour:
Installer build and launched successfully with preview builds on Mojave, https://gist.github.com/GouriKumari/37f1057a246f9787d5d9427a2913f234

Test Env: https://gist.github.com/GouriKumari/047280158693ce66c962a33b96e5fd6c

**Comment by spouliot** [comment]
Mono 6.0.0 is way too old (2019-02) to be used on macOS 10.15 (Catalina) as it still contains 32bits tools

**Comment by GouriKumari** [comment]
I installed mono 6.4.x and since the preview builds are based of d16.2, it is not possible to check whether the issue is resolved. 
Currently VSFMac 8.2 preview  gives an error that "Did not find msbuild for runtime 6.0.0.296".

**Comment by GouriKumari** [comment]
This issue is resolved. I could build installer successfully in Catalina with 8.3 Xcode11 bits. 
https://gist.github.com/GouriKumari/988ef30df02752cfb5c3e2e1dbbd5b48
