### ISSUE TITLE
[GameController] Attributes on Structs not Compiling

### ISSUE THREAD

**Issue by tj-devel709** [xamarin/xamarin-macios#6590]
### Steps to Reproduce

1. In /Users/tjlambert/xamarin-ios/xcode11/xamarin-macios/src/GameController/GCMotion.cs, if I add attributes such as "[iOS (13,0), Mac (10,15, onlyOn64: true), TV (13,0)]" the methods that use these structs to do not compile.

### Expected Behavior
I expect the API to compile

### Actual Behavior
The API does not compile with errors such as "error MT4162: The type 'GameController.GCQuaternion' (used as a parameter in GameController.GCMotion.SetAttitude) is not available in iOS 13.0 (it was introduced in iOS 13.0.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode)." 
-where GameController.GCQuaternion is a method that uses the structs in GCMotion.cs

### Environment
xcode11 branch

```
```

### Build Logs

https://gist.github.com/tj-devel709/465211b41e7a5e0e52f08a9462fa5313

**Comment by rolfbjarne** [comment]
You must use the long-form `[Introduced (PlatformName.iOS, 13, 0)]` in non-api source code.
