### ISSUE TITLE
[xcode11-feature] [MediaPlayer] AVMediaSelectionGroup & AVMediaSelectionOption not available on Watch

### ISSUE THREAD

**Issue by tj-devel709** [xamarin/xamarin-macios#6597]
### Steps to Reproduce

1. Use AVMediaSelectionGroup or AVMediaSelectionOption on watch
-Dependent on AVFoundation

### Expected Behavior
To be able to use it

### Actual Behavior
Says that the type or namespace does not exist in the namespace AVFoundation 

### Environment
xcode11

```
```

### Build Logs

build/watch/watch/MediaPlayer/AVMediaSelectionGroup_MPNowPlayingInfoLanguageOptionAdditions.g.cs(41,120): error CS0234: The type or namespace name 'AVMediaSelectionGroup' does not exist in the namespace 'AVFoundation' (are you missing an assembly reference?)
build/watch/watch/MediaPlayer/AVMediaSelectionOption_MPNowPlayingInfoLanguageOptionAdditions.g.cs(41,110): error CS0234: The type or namespace name 'AVMediaSelectionOption' does not exist in the namespace 'AVFoundation' (are you missing an assembly reference?)
make[1]: *** [build/watch/watch-32/Xamarin.WatchOS.dll] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all-recurse] Error 1

**Comment by chamons** [comment]
This required Xcode 11 AVFoundation to land first.

**Comment by rolfbjarne** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/commit/f5cbe60ae9514b4410cda301f35e6ae76486f7c2.
