### ISSUE TITLE
Unwanted space between subviews while subviews height value as decimal value

### ISSUE THREAD

**Issue by Sasikumar3595** [xamarin/xamarin-macios#6599]
### Description

We are adding UILabels as subviews of UIView on vertical manner and height of the subviews as calculated by current display width. If height of the subview as decimal value then unwanted spaces will be displayed between subviews.

### Steps to Reproduce

1. Run the attached project
2. See the reported issue

### Expected Behavior

Remove the unwanted space between the subviews

### Actual Behavior

There is some unwanted space between the subviews

### Environment

- All the Visual studio version

### Example Project (If Possible)

Sample : [iOS-Sample.zip](https://github.com/xamarin/xamarin-macios/files/3401651/iOS-Sample.zip)

**Comment by chamons** [comment]
This is behavior from Apple and not related to Xamarin.iOS. The following Objective-C code reproduces your issue:

```
    [self view].backgroundColor = UIColor.redColor;
    //// If the height value has decimal value then the issue will raise.
    double height = 36.60f;
    for (int i = 0; i < 10; i++)
    {
        UILabel* label = [[UILabel alloc] init];
        label.backgroundColor = UIColor.whiteColor;
        label.frame = CGRectMake (100, i * height, 100, height);
        [self.view addSubview:label];
    }
```
