### ISSUE TITLE
Xamarin does not install an older version to support older systems

### ISSUE THREAD

**Issue by shejan0** [xamarin/xamarin-macios#6648]
### Steps to Reproduce

1. Use a Mac (Macbook 7,1) which is only limited to MacOS 10.13.6 through normal means (10.14 is possible through modified installations, but I do not feel safe yet doing so)
2. Install Visual Studio normally through the website process
3. Install XCode 10.1 through https://developer.apple.com/download/ as that is the last version to support 10.13 (XCode 10.2, is a macOS 10.14 and higher requirement) 

### Expected Behavior
Xamarin.Mac should still operate on XCode 10.1, and Visual Studio/Xamarin does not attempt to install an older version that does support a copy of XCode that is installed on the machine
### Actual Behavior
Simply recieved error:
"/Users/mac/Documents/Visual Studio/LearningVisualStudioMac/LearningVisualStudioMac/MMP: Warning MM0079: The recommended Xcode version for Xamarin.Mac 5.10.0 is Xcode 10.2 or later. The current Xcode version (found in /Applications/Xcode.app/Contents/Developer) is 10.1. (MM0079)"

### Environment
Visual Studio for Mac on Macbook 7,1 running macOS 10.13.6

=== Visual Studio Community 2019 for Mac ===

Version 8.1.4 (build 5)
Installation UUID: 5a34fc03-c28c-47ec-ba8c-d27a387b1f22
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.11
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Version: 2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

=== Xamarin.iOS ===

Version: 12.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

=== Xamarin Designer ===

Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft Mobile OpenJDK ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 801040005
Git revision: 9c98f365cacfac65fbbaf0a77b2ea7864abef759
Build date: 2019-06-28 21:07:05+00
Build branch: release-8.1
Xamarin extensions: 8cc25b5cb090e6c23b62a7901000c299977eb08d

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Wed Apr 24 21:17:24 PDT 2019
    root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64

=== Visual Studio Community 2019 for Mac ===

Version 8.1.4 (build 5)
Installation UUID: 5a34fc03-c28c-47ec-ba8c-d27a387b1f22
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.1.11
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Version: 2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

=== Xamarin.iOS ===

Version: 12.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

=== Xamarin Designer ===

Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft Mobile OpenJDK ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 801040005
Git revision: 9c98f365cacfac65fbbaf0a77b2ea7864abef759
Build date: 2019-06-28 21:07:05+00
Build branch: release-8.1
Xamarin extensions: 8cc25b5cb090e6c23b62a7901000c299977eb08d

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Wed Apr 24 21:17:24 PDT 2019
    root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64

### Example Project (If Possible)

The default Xamarin.Mac C# Cocoa App

**Comment by chamons** [comment]
```
 "/Users/mac/Documents/Visual Studio/LearningVisualStudioMac/LearningVisualStudioMac/MMP: Warning MM0079: The recommended Xcode version for Xamarin.Mac 5.10.0 is Xcode 10.2 or later. The current Xcode version (found in /Applications/Xcode.app/Contents/Developer) is 10.1. (MM0079)"
```

This is not an error, it is a **warning**.

You can disable it by using the --nowarn option in the "Additional MMP Arguments" section of the build configuration.
