### ISSUE TITLE
lipo is reporting x86_64 arch in a native iOS lib, but mtouch reports x86_64 is not present

### ISSUE THREAD

**Issue by jsauve** [xamarin/xamarin-macios#6693]
### Steps to Reproduce
See Expected Behavior

### Expected Behavior
We're integrating with Epic Systems' MyChart native iOS library (libMyChart.a), version 8.8. The lib is supposed to support armv7, x86_64, & arm64 architectures. This is found to be true by querying the lib with the lipo tool
The command:
`xcrun -sdk iphoneos lipo -info /path/to/libMyChart.a`
...yields the output:
`Architectures in the fat file: /path/to/libMyChart.a are: armv7 x86_64 arm64`

When building our iOS app against the lib, we get the error:
`error MT5209: Error: warning: ignoring file /path/to/iOSProject/obj/iPhoneSimulator/Debug/device-builds/iphone11.2-12.1/mtouch-cache/libMyChart.a, file is universal (3 slices) but does not contain the x86_64 architecture: /path/to/iOSProject/obj/iPhoneSimulator/Debug/device-builds/iphone11.2-12.1/mtouch-cache/libMyChart.a ([our app identifier]) Native linking`

We're not understanding how it can be that lipo is reporting that x86_64 is supported in the lib, but that mtouch is apparently reporting that x86_64 is NOT supported, despite the tooling also reporting that it found 3 slices (supported architecture binaries) in the library file.

Full build output, sanitized by removing identifying orgs, app names, and users:
https://gist.github.com/jsauve/9adaad8b65c092b6fb20b396aa3f8d41

We have MyChart 8.7 in production today, but now we're seeing these arch-related build issues with 8.8. Because lipo tells us that the lib contains the architectures we expect it to, we believe that it's something in the mtouch tooling that may be erroneously reporting a missing architecture.

### Actual Behavior
See Expected Behavior

### Environment
VS4Mac environment dump:
https://gist.github.com/jsauve/23b54fafd7ac0a28b822031dc0274e4e
(We're unable to use latest Xamarin tools right now, because the MyChart lib does not yet support the latest Xamarin.Android, and we need MyChart feature parity between platforms for our releases)

### Build Logs
Full build output, sanitized by removing identifying orgs, app names, and users:
https://gist.github.com/jsauve/9adaad8b65c092b6fb20b396aa3f8d41

### Example Project (If Possible)
Example project is not currently possible because of firewalled dev environments and code sensitivity, but we will be trying to put together a repo we can provide access to.

**Comment by jonj-reviewer19** [comment]
Thanks for sharing I'll take this and get started with efforts for troubleshooting. Can you confirm what version of Xcode you're running?

**Comment by jsauve** [comment]
Xcode 10.1 (14460.46)
Build 10B61

**Comment by dalexsoto** [comment]
Hello @jsauve!

is there any chance you could provide us with a small test case for this? this is indeed a bit weird. Also as an additional comment, `x86_64` is only required for simulator builds, as a workaround you can use device for now until we investigate more.

**Comment by jsauve** [comment]
Hello @dalexsoto!

We have provided repo access information to @jonj-reviewer19 via the Microsoft support system.

You're right about `x86_64` and simulator builds, but the problem is that some of our developers are offsite (including me), and all dev environments are behind a VPN which we are unable to access from off-site iOS devices. We are, however, able to connect to the VPN from our MacBooks and then debug the app on the iOS simulator. So, we don't need `x86_64` for device deployment, but we do need it for ongoing development in our case.

**Comment by chamons** [comment]
Hey everyone - 👋 

I don't believe @jonj-reviewer19 works at Microsoft. He's a community account created 6 days ago. @dalexsoto would be someone who would look at a customer issue.

@jonj-reviewer19 I'm happy for you to drop by our [gitter](https://gitter.im/xamarin/xamarin-macios) if you'd like to contribute to xamarin-macios.

**Comment by jsauve** [comment]
@chamons, sorry I was trying to tag Jonathan Jackson in Microsoft support, which is where this support request started before bringing it over into GitHub. He responded earlier in the thread. I'm fairly certain that's the correct account.

**Comment by jonj-reviewer19** [comment]
Hi @chamons I am updating my GitHub account, @jsuave was answering some additional questions prior to setting this up on GitHub. At the moment they are using a lib that's not working correctly in the Xamarin build. The error code they've encountered actually is labeled as a warning. The code MT5209 states a Native linking error. @dalexsoto is looking for header files for the lib they are using.

**Comment by jsauve** [comment]
Just for clarity, I'm @jsauve, not jsuave. The "a" & "u" make a difference.

**Comment by jonj-reviewer19** [comment]
> Just for clarity, I'm @jsauve, not jsuave. The "a" & "u" make a difference.

My mistake. @jsauve

**Comment by jsauve** [comment]
@jonj-reviewer19, I've uploaded into the MSFT secure file exchange a sample solution that reproduces the error. We also noticed that the error is not just confined to x86_64; if we build for iPhone instead of iPhoneSimulator, we see the same build error about slices and architectures occurring for ARM64.

**Comment by jonj-reviewer19** [comment]
Sounda good I'll review and test in my environment.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jonj-reviewer19** [comment]
Hi @jsauve can you please go ahead and close this out. If you have any additional questions please follow-up via the email chain I've already sent..

Thanks.

**Comment by jsauve** [comment]
Hi Jonathan,

We still have some more feedback to provide, but we can't get to it until
Wed Aug 7th because we're delivering a different app to market in the next
48 hrs. We plan on providing more info on Wed, so if we can leave the
ticket open until then, we would really appreciate it.

**Comment by jonj-reviewer19** [comment]
@jsauve Your support ticket will remain open for the time you've requested, but this GitHub will not be answered. I suggest you close this post and you will be able to continue communication via the email I've sent last Friday.

**Comment by jsauve** [comment]
Ok, cool, thx Jonathan

**Comment by jsauve** [comment]
Continuing support request via MSFT support system.
