### ISSUE TITLE
iOS 13: MKPolygon with interior polygon and dynamic fill color causes UIKitThreadAccessException

### ISSUE THREAD

**Issue by Physikbuddha** [xamarin/xamarin-macios#6706]
### Steps to Reproduce
1. Use the latest Xamarin beta 12.99 for Xcode 11 / iOS 13 support.
2. Create an `MKPolygon` that has at least one interior polygon and add it to an `MKMapView`.
3. Override the `mapView:rendererForOverlay:` method of the `MKMapView`'s delegate. Choose a dynamic color for the `MKPolygonRenderer`'s FillColor or StrokeColor.

### Expected Behavior
On a native project coded in Xcode with Swift, this gives a polygon with a hole that changes color when you toggle between light and dark mode.

### Actual Behavior
Using Xamarin.iOS the app crashes with an 

> UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.

**This error does not occur if you use a plain old static UIColor instead, or create an MKPolygon without any interior polygons.**

Of course, this crash can be suppressed by setting `UIApplication.CheckForIllegalCrossThreadCall = false;`, but this shouldn't be neccessary here.

### Environment

=== Visual Studio Community 2019 for Mac ===
Version 8.2 (build 1124)
Installation UUID: 15a38fd4-49ee-4754-9b2f-2574ae3942f9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)
	Package version: 600000311

=== Mono Framework MDK ===
Runtime:
	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
	Package version: 600000311

=== NuGet ===
Version: 5.1.0.6013

=== .NET Core ===
Laufzeit: /usr/local/share/dotnet/dotnet
Runtime versions:
	2.2.4
	2.1.9
	2.1.8
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.2.203/Sdks
SDK versions:
	2.2.203
	2.1.505
	2.1.504
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===
Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===
Version: 11

=== Apple Developer Tools ===
Xcode 11.0 (14908.4)
Build 11M382q

=== Xamarin.iOS ===
Version: 12.99.2.26 (Visual Studio Community)
Hash: d095f754
Branch: xcode11
Build date: 2019-07-25 06:36:54-0400

=== Xamarin Designer ===
Version: 16.2.0.391
Hash: 216490cf5
Branch: remotes/origin/d16-2-xcode11
Build date: 2019-07-25 17:42:00 UTC

=== Xamarin Inspector ===
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===
Release ID: 802001124
Git revision: 0797bb4dfcd2cbad030d7fce609e247e23f855ca
Build date: 2019-07-26 12:13:29+00
Build branch: release-8.2-xcode11
Xamarin extensions: d663a25405cd5e7d0b0deefd2a26d548680f16f5

=== Operating System ===
Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

### Example Project (Both Xamarin and working Xcode projects included)

[MapCrash_Projects.zip](https://github.com/xamarin/xamarin-macios/files/3460921/MapCrash_Projects.zip)

    using CoreLocation;
    using Foundation;
    using MapKit;
    using System;
    using UIKit;

    namespace MapCrashNet
    {
        public partial class MapViewController : UIViewController, IMKMapViewDelegate
        {
            public MapViewController(IntPtr handle) : base(handle)
            { }

            public override void ViewDidLoad()
            {
                base.ViewDidLoad();
                this.MapView.Delegate = this;

                // Uncomment to suppress the crash
                // UIApplication.CheckForIllegalCrossThreadCalls = false;

                var coords = new CLLocationCoordinate2D[]
                {
                    new CLLocationCoordinate2D(10, 10),
                    new CLLocationCoordinate2D(10, 50),
                    new CLLocationCoordinate2D(50, 50),
                    new CLLocationCoordinate2D(50, 10)
                };

                var innerCoords = new CLLocationCoordinate2D[]
                {
                    new CLLocationCoordinate2D(20, 20),
                    new CLLocationCoordinate2D(20, 40),
                    new CLLocationCoordinate2D(40, 40),
                    new CLLocationCoordinate2D(40, 20)
                };

                var interiorPolys = new MKPolygon[]
                {
                    MKPolygon.FromCoordinates(innerCoords)
                };

                var poly = MKPolygon.FromCoordinates(coords, interiorPolys);
                this.MapView.AddOverlay(poly);
            }

            [Export("mapView:rendererForOverlay:")]
            public MKOverlayRenderer OverlayRenderer(MKMapView mapView, IMKOverlay overlay)
            {
                if (overlay is MKPolygon polygon)
                {
                    UIColor dynColor = UIColor.FromDynamicProvider(traits =>
                        traits.UserInterfaceStyle == UIUserInterfaceStyle.Dark ?
                            UIColor.FromRGB(255, 255, 255) :
                            UIColor.FromRGB(0, 0, 0));

                    MKPolygonRenderer polygonView = new MKPolygonRenderer(polygon)
                    {
                        FillColor = dynColor,
                        StrokeColor = UIColor.Red,
                        LineWidth = 2
                    };

                    return polygonView;
                }

                return new MKOverlayRenderer();
            }
        }
    }

**Comment by chamons** [comment]
Thank you for the wonderfully complete bug report @Physikbuddha !

@dalexsoto - Looks like we need some threading attributes on some bits of the new UIKit API. Can you run this down (see if there are other new colo rAPIs that should allow non-ui thread as well). 

https://github.com/xamarin/xamarin-macios/blob/xcode11/src/uikit.cs#L5115

**Comment by rolfbjarne** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/commit/cd7e293ce0648bb347db0ee47ad7d5711f4d80ea.
