### ISSUE TITLE
[xcode11] Some APIs are ambiguous, leading to build issues

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#6724]
### Steps to Reproduce

1. Try the samples mentioned in the "example project" section, building then with latest `xcode11` bits.

### Expected Behavior

Ideally we would not have build issues and ambiguous APIs (for instance we could have an enum to switch between 2 similar APIs). If we really have to have ambiguous APIs then we need to fix the samples.

### Actual Behavior

The call is ambiguous between the following methods or properties...

### Environment

`xcode11` branch

### Example Project (If Possible)

https://github.com/xamarin/maccore/issues/1877 and https://github.com/xamarin/maccore/issues/1910

**Comment by VincentDondain** [comment]
`ViewController.cs(63,21,63,48): error CS0121: The call is ambiguous between the following methods or properties: 'UIAccessibilityCustomAction.UIAccessibilityCustomAction(string, Func<UIAccessibilityCustomAction, bool>)' and 'UIAccessibilityCustomAction.UIAccessibilityCustomAction(string, UIAccessibilityCustomActionHandler)` is because of https://github.com/xamarin/xamarin-macios/blob/xcode11/src/uikit.cs#L1629 which is conflicting with https://github.com/xamarin/xamarin-macios/blob/xcode11/src/UIKit/UIAccessibilityCustomAction.cs#L29

**Comment by VincentDondain** [comment]
`/Users/vsts/agent/2.154.1/work/1/s/tests/sampletester/bin/Debug/repositories/ios-samples/ios11/WeatherWidget/WeatherWidget.Shared/Weather.cs(47,33): error CS0121: The call is ambiguous between the following methods or properties: 'UIImage.FromBundle(string, NSBundle, UITraitCollection)' and 'UIImage.FromBundle(string, NSBundle, UIImageConfiguration)' ` is because https://github.com/xamarin/xamarin-macios/blob/xcode11/src/uikit.cs#L7494 is conflicting with https://github.com/xamarin/xamarin-macios/blob/xcode11/src/uikit.cs#L7763

**Comment by rolfbjarne** [comment]
In both cases I think the samples need to be updated.

**Comment by VincentDondain** [comment]
https://github.com/xamarin/maccore/issues/1910 and https://github.com/xamarin/maccore/issues/1877 fixed by https://github.com/xamarin/ios-samples/pull/383
