### ISSUE TITLE
Apple reports WatchOSExtension does not contain bitcode.

### ISSUE THREAD

**Issue by rachael-ross** [xamarin/xamarin-macios#6725]
After uploading ipa to AppStore Connect, I'm getting emails from Apple stating that the watch extension doesn't contain bitcode.

### Steps to Reproduce

1. Add WatchKit App / Extension projects to solution containing parent iOS app.
2. Configure new "release" type build config in VS for Mac called "Staging-TestFlight" (didn't want to use built-in Release build config since this is for purpose of publishing to TestFlight but using staging api resources) 
3. Enable optimizations on Mobile app for new build config
4. Mobile Extension:
    a. SDK version 12.4
    b. Linker Link Framework SDKs Only
    c. Supported architectures: ARMv7k + ARM64_32
    d. User LLVM optimizing compiler
    e. Strip native debugging symbols
    f.  User the concurrent garbage collector
    g. Optimize PNG images
    h. Sign with Distribution identity and corresponding provisioning profile.
    i.  Manually added `<MtouchEnableBitcode>true</MtouchEnableBitcode>` to csproj file for Watch Extension for the new build config.
5. Using VS for Mac, created Archive for Publishing; signed parent app and watch app/extension with distribution profiles (3 separate for 3 separate app Ids)
6. Using Application Loader, published to Apple TestFlight. No errors - validation and upload were successful.

### Expected Behavior

To receive an email from Apple for successful publish and ready for testing.

### Actual Behavior

Received email from Apple stating there is an issue with the newly uploaded app:

ITMS-90496: Invalid Executable - The executable '[Obfuscated].Mobile.iOS.app/Watch/[Obfuscated].WatchOSApp.app/PlugIns/[Obfuscated].WatchOSExtension.appex/[Obfuscated].WatchOSExtension' **does not contain bitcode.**

### Environment

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.2 (build 1105)
Installation UUID: ca24e45a-55d6-4d50-adc1-686bec512c93
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000311

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
	Package version: 600000311

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.9
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.505
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.4.0.51 (Visual Studio Professional)
Commit: xamarin-android/d16-2/9fa7775
Android SDK: /Users/rachael.ross/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 25.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/rachael.ross/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-16 17:37:14 UTC

=== Xamarin Designer ===

Version: 16.2.0.354
Hash: 5f80a14f8
Branch: remotes/origin/d16-2
Build date: 2019-07-11 17:28:26 UTC

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.110 (Visual Studio Professional)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:43-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 12.14.0.110 (Visual Studio Professional)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:42-0400

=== Build Information ===

Release ID: 802001105
Git revision: a187f6852ae62ba52b944b47e53702957edfcf7b
Build date: 2019-07-22 18:20:10+00
Build branch: release-8.2
Xamarin extensions: 34bd2378d8d707df25989727c23ce68d9a232a67

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64


**I am using XCode 10.3**
```

### Example Project (If Possible)

**Additional Info:**

If I examine the info.plist file for the watch extension by unzipping the .ipa file, this is what is present:

![image](https://user-images.githubusercontent.com/17603150/62559703-45c52600-b830-11e9-9b18-4c3af3e65abb.png)

This is the config in the .csproj file for the watch extension:

```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Staging-TestFlight|iPhone' ">
    <Optimize>true</Optimize>
    <OutputPath>bin\iPhone\Staging-TestFlight</OutputPath>    <DefineConstants>__WATCHOS__;__MOBILE__;__UNIFIED__;STAGING_TESTFLIGHT</DefineConstants>
    <WarningLevel>4</WarningLevel>
<ErrorReport>prompt</ErrorReport>
    <CodesignKey>iPhone Distribution</CodesignKey>
    <MtouchUseLlvm>true</MtouchUseLlvm>
    <MtouchFloat32>true</MtouchFloat32>
    <MtouchEnableBitcode>true</MtouchEnableBitcode>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <MtouchLink>SdkOnly</MtouchLink>
    <MtouchArch>ARMv7k, ARM64_32</MtouchArch>    
    <MtouchTlsProvider>Default</MtouchTlsProvider>
    <CodesignProvision>Obfuscated Watch Extension - Staging-TestFlight</CodesignProvision>
  </PropertyGroup>
```
I've also attempted to use otool to examine the executable using the command line below, but always get "Not a directory". I've unzipped the ipa and examined the contents all the way down to the watch extension and my path is correct.

```
otool -l "same path reported by Apple above" | grep bitcode
```

I'm not sure what to do at this point to make sure bitcode is created/included/indicated in the package uploaded to TestFlight.

**Comment by chamons** [comment]
@VincentDondain - Can you please double check or run the submission tests (do those include watch), and if not try watch. Please compare to this report.

**Comment by rachael-ross** [comment]
FYI.... I've added the following PlistBuddy commands to a target in .csproj as a **temporary** workaround. Although I'm compiling against watchOS 5.3, I'm telling Apple that is 4.3. I've confirmed that I can successfully install this build on watches running 5.3, but at some point, this workaround may stop working if Apple performs any validation of watchOS sdk.

```
<Target Name="BeforeCodesign" Condition="'$(Configuration)|$(Platform)' == 'Staging-TestFlight|iPhone'">
    <Exec Command="mv '$(_NativeExecutable)' '$(_NativeExecutable).armv7k'" />
    <Exec Command="xcrun bitcode-build-tool -j 8 -o '$(_NativeExecutable).arm64_32' --translate-watchos '$(_NativeExecutable).armv7k'" />
    <Exec Command="xcrun lipo -create -output '$(_NativeExecutable)' '$(_NativeExecutable).arm64_32' '$(_NativeExecutable).armv7k'" />
    <Exec Command="rm -f '$(_NativeExecutable).arm64_32' '$(_NativeExecutable).armv7k'" />
    <Exec Command="/usr/libexec/PlistBuddy -c 'Set :DTPlatformBuild 15T212' $(_AppBundlePath)Info.plist" />
    <Exec Command="/usr/libexec/PlistBuddy -c 'Set :DTPlatformVersion 4.3'  $(_AppBundlePath)Info.plist" />
    <Exec Command="/usr/libexec/PlistBuddy -c 'Set :DTSDKBuild 15T212'      $(_AppBundlePath)Info.plist" />
    <Exec Command="/usr/libexec/PlistBuddy -c 'Set :DTSDKName watchos4.3'   $(_AppBundlePath)Info.plist" />
    <Exec Command="/usr/libexec/PlistBuddy -c 'Set :DTXcode 0940'           $(_AppBundlePath)Info.plist" />
    <Exec Command="/usr/libexec/PlistBuddy -c 'Set :DTXcodeBuild 9F1027a'   $(_AppBundlePath)Info.plist" />
</Target>
```

**Comment by rolfbjarne** [comment]
I can't reproduce this.

@rachael-ross can you try submitting your app using the Release configuration to see if that works? That should narrow it down a little bit at least.

**Comment by rolfbjarne** [comment]
@VincentDondain I've already tried the submission tests (they passed), no need for you to do the same.

**Comment by rachael-ross** [comment]
I did and it failed for the same reason specified above. Could it have something to do with me having XCode 10.2?

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Comment by erumhannan-techlogix** [comment]
The executable 'AppName.app/Watch/OBDXWatchApp.app/PlugIns/OBDXWatchAppExtension.appex/OBDXWatchAppExtension' does not contain bitcode.

how u resolve this issue ?

**Comment by chamons** [comment]
@erumhannan-techlogix - This issue was closed half a year ago. If you have an issue, please open a new one and complete the template.
