### ISSUE TITLE
MT2101 Can't resolve the reference 'System.String SQLitePCL.raw::sqlite3_errmsg(SQLitePCL.sqlite3)

### ISSUE THREAD

**Issue by Lerseb** [xamarin/xamarin-macios#6734]
/Users/sebastienleroux/Mega/@Coding/ObserVision1/iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.String SQLitePCL.raw::sqlite3_errmsg(SQLitePCL.sqlite3)', referenced from the method 'System.String SQLite.SQLite3::GetErrmsg(SQLitePCL.sqlite3)' in 'SQLitePCLRaw.core, Version=1.1.11.121, Culture=neutral, PublicKeyToken=1488e028ca7ab535'. (MT2101) (ObserVision1.iOS)
-->
### Steps to Reproduce

Just Compiling my project
Still running on SQLitePCLRaw.Bundle_green (V 1.1.11) and SQLitePCLRaw.Core(V 1.1.11) in my PCL (and VS is not able to update those packages) whereas I have SQLitePCLRaw.Bundle_green (V 2.0.0) and SQLitePCLRaw.Core(V 2.0.0) in my iOS project.

### Actual Behavior

Cannot compile the project. Assemblies may not be compatible

### Environment

Visual Studio Professional 2019 for Mac
Version 8.2.2 (build 21)
Installation UUID: e6b22f69-4e3a-40cc-831b-ee7663b7f839
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000319

Mono Framework MDK
Runtime:
	Mono 6.0.0.319 (2019-02/52203786470) (64-bit)
	Package version: 600000319

NuGet
Version: 5.1.0.6013

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.6
	2.2.2
	2.1.8
	2.1.7
SDK: /usr/local/share/dotnet/sdk/2.2.401/Sdks
SDK Versions:
	2.2.401
	2.2.104
	2.1.504
	2.1.503
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

### Build Logs

Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Xamarin.iOS.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Mono.Security.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/ObserVision1.iOS.exe
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Xamarin.Forms.Platform.iOS.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/ObserVision1.dll
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Xamarin.Forms.Core.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/netstandard.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Core.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Xml.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Numerics.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Data.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Transactions.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Drawing.Common.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.IO.Compression.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.IO.Compression.FileSystem.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.ComponentModel.Composition.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Net.Http.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Runtime.Serialization.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.ServiceModel.Internals.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Web.Services.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Xml.Linq.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Xamarin.Forms.Platform.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Runtime.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Xamarin.Forms.Xaml.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/SQLite-net.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/SQLitePCLRaw.core.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Memory.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Collections.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Runtime.Extensions.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Linq.Expressions.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Reflection.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Diagnostics.Debug.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Threading.Tasks.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Linq.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/SQLitePCLRaw.batteries_v2.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/SQLitePCLRaw.nativelibrary.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/SQLitePCLRaw.provider.dynamic_cdecl.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Threading.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Reflection.Extensions.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Globalization.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.ObjectModel.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Plugin.Geolocator.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Plugin.Permissions.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Text.RegularExpressions.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Diagnostics.Tools.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Xamarin.Forms.Maps.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Plugin.AudioRecorder.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Plugin.Media.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/System.ComponentModel.dll [External]
Loaded assembly: /Users/sebastienleroux/Library/Developer/CoreSimulator/Devices/1C3EBB66-3D1B-407F-B066-13907A893112/data/Containers/Bundle/Application/2965B608-B6CC-44FE-8068-16F17093E06C/ObserVision1.iOS.app/Xamarin.Forms.Maps.iOS.dll [External]
2019-08-07 08:11:34.618943-0400 ObserVision1.iOS[8490:463306] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=8490
2019-08-07 08:11:34.619465-0400 ObserVision1.iOS[8490:463306] SecTaskCopyDebugDescription: ObserVision1.iOS[8490]/0#-1 LF=0

**Comment by chamons** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by Lerseb** [comment]
I just solved the issue.
Here is what I did : 
Just delete all the SQLiteRaw.... packages as well as SQLite-net-pcl In the iOS project
Then just add the SQLite-net-pcl again.

**Comment by suihanhbr** [comment]
> I just solved the issue.
> Here is what I did :
> Just delete all the SQLiteRaw.... packages as well as SQLite-net-pcl In the iOS project
> Then just add the SQLite-net-pcl again.

I meet the same problem . But it don't work with you way.

**Comment by chamons** [comment]
Please consider opening a new issue with full build logs, steps to reproduce, and an example.

**Comment by starinfo** [comment]
Thank you folks for the idea
I was having the same issue here, and removed the Nugets (in PCL project and android project) and after added it manually one by one.
The big change is that packages started becoming nested to each others (in PCL project)
probably is because they wore not recongnized before.

**Comment by LeroyStaines** [comment]
For me this happens when targeting Android 9+

**Comment by mcrozier-ngn** [comment]
This is also happening to me targeting Android 9.0. it started after migrating PCL libraries to .net standard.

**Comment by eliotg** [comment]
I having this exact problem building for watchOS.  Reinstalling packages didn't work and, worse, it worked last time I opened VS but this time it's different somehow, despite no source files changing.
`error MT2101: Can't resolve the reference 'System.String SQLitePCL.raw::sqlite3_errmsg(SQLitePCL.sqlite3)', referenced from the method 'System.String SQLite.SQLite3::GetErrmsg(SQLitePCL.sqlite3)' in 'SQLitePCLRaw.core, Version=1.1.13.388, Culture=neutral, PublicKeyToken=1488e028ca7ab535'.`

**Comment by chamons** [comment]
Just a friendly reminder - If you having issues with Xamarin.iOS or Mac, posting on a closed issue will not be very effective.

Consider filing a [new issue](github.com/xamarin/xamarin-macios/issues/new) with the template completed filled out.

**Comment by eliotg** [comment]
Just a friendly reminder that the community helps themselves faster and a lot more effectively than Microsoft (or just about any other company) does with its limited interface.

Also, I think I figured this issue out for myself (either that or it went away magically on its own): I had the packages installed in both the Xamarin watchOSApp and watchOSExtension, but I think maybe some of the packages revved while I was investigating a different SQLite problem and I had version 2.0.2 installed in one and 2.0.3 in the other.  Now I'm back to "The type initializer for 'SQLite.SQLiteConnection' threw an exception."
