### ISSUE TITLE
[MTouch] The assembly was loaded from a different path than the provided path when using PackageReference

### ISSUE THREAD

**Issue by cosminstirbu** [xamarin/xamarin-macios#6758]
### Steps to Reproduce

Build the attached iOS project (targeting the simulator for example)

### Expected Behavior

No warnings should be reported

### Actual Behavior

`The assembly 'System.Text.Encoding.CodePages.dll' was loaded from a different path than the provided path (provided path: /Users/cosminstirbu/.nuget/packages/system.text.encoding.codepages/4.4.0/runtimes/win/lib/netstandard2.0/System.Text.Encoding.CodePages.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/12.16.0.5/lib/mono/Xamarin.iOS/Facades/System.Text.Encoding.CodePages.dll).` is reported.

Interestingly enough, on my real project, two other warnings are reported as well when building the project using Cake / MSBuild:

`
MTOUCH : warning MT0109: The assembly 'Syncfusion.Compression.Portable.dll' was loaded from a different path than the provided path (provided path: /Users/vsts/.nuget/packages/syncfusion.xamarin.compression/17.2.0.34/lib/netstandard2.0/Syncfusion.Compression.Portable.dll, actual path: /Users/vsts/.nuget/packages/syncfusion.compression.net.core/17.2.0.34/lib/netstandard2.0/Syncfusion.Compression.Portable.dll). [/Users/vsts/agent/2.155.1/work/1/s/***.MyApp.iOS/***.MyApp.iOS.csproj]
MTOUCH : warning MT0109: The assembly 'Syncfusion.Pdf.Portable.dll' was loaded from a different path than the provided path (provided path: /Users/vsts/.nuget/packages/syncfusion.xamarin.pdf/17.2.0.34/lib/netstandard2.0/Syncfusion.Pdf.Portable.dll, actual path: /Users/vsts/.nuget/packages/syncfusion.pdf.net.core/17.2.0.34/lib/netstandard2.0/Syncfusion.Pdf.Portable.dll). [/Users/vsts/agent/2.155.1/work/1/s/***.MyApp.iOS/***.MyApp.iOS.csproj]
MTOUCH : warning MT0109: The assembly 'System.Text.Encoding.CodePages.dll' was loaded from a different path than the provided path (provided path: /Users/vsts/.nuget/packages/system.text.encoding.codepages/4.4.0/runtimes/win/lib/netstandard2.0/System.Text.Encoding.CodePages.dll, actual path: /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.11/lib/mono/Xamarin.iOS/Facades/System.Text.Encoding.CodePages.dll). [/Users/vsts/agent/2.155.1/work/1/s/***.MyApp.iOS/***.MyApp.iOS.csproj]
`

but maybe that's because on Azure Devops we're using an older version of Mono and Xamarin.iOS

### Environment

Visual Studio Enterprise 2019 for Mac (Preview)
Version 8.3 Preview (8.3 build 867)
Installation UUID: d4952962-f22d-4fe9-ac97-42305c5b746c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.0.5 (d16-3 / 26f04c54)

	Package version: 604000081

Mono Framework MDK
Runtime:
	Mono 6.4.0.81 (2019-06/f55e0a671c0) (64-bit)
	Package version: 604000081

NuGet
Version: 5.2.0.6067

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.9
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 10.2 (14490.120)
Build 10E125

Xamarin.Mac
Version: 5.16.0.5 (Visual Studio Enterprise)
Hash: 26f04c54
Branch: d16-3
Build date: 2019-06-28 01:31:14-0400

Xamarin.iOS
Version: 12.16.0.5 (Visual Studio Enterprise)
Hash: 26f04c54
Branch: d16-3
Build date: 2019-06-28 01:31:14-0400

Xamarin Designer
Version: 16.3.0.17
Hash: 73f0a446c
Branch: remotes/origin/d16-3-release-8.3-p1
Build date: 2019-07-22 17:05:22 UTC

Xamarin.Android
Version: 9.5.0.27 (Visual Studio Enterprise)
Commit: xamarin-android/d16-3/16c4494
Android SDK: /Users/cosminstirbu/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Microsoft Mobile OpenJDK
Java SDK: /Users/cosminstirbu/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 1.4.0.8
Hash: 28342d0
Branch: remotes/origin/backport-pr-235-to-d16-3~2
Build date: 2019-07-18 16:54:46 UTC

Android Device Manager
Version: 1.2.0.75
Hash: bf6d603
Branch: remotes/origin/backport-pr-369-to-d16-3~1
Build date: 2019-07-18 16:55:08 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 803000867
Git revision: ab4af85ea561e474b545e0eada75c5bfe8a92297
Build date: 2019-07-24 14:13:44+00
Build branch: release-8.3-preview1
Xamarin extensions: 45290013e165bcd2db7acbb310e0c16bfe04f0c3

Operating System
Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

Enabled user installed extensions
DeepClean 1.2.5
StyleCop Support 1.1.0.2
Straight8's SpecFlow Integration 1.11.3.0
FileNesting 0.1.2
NuGet Package Management Extensions 0.19

### Example Project (If Possible)

[PackageReference.zip](https://github.com/xamarin/xamarin-macios/files/3497310/PackageReference.zip)

**Comment by rolfbjarne** [comment]
The problem is that the `Syncfusion.Pdf.Net.Core` nuget wants to use its own version of `System.Text.Encoding.CodePages.dll` when Xamarin.iOS provides its own copy of this assembly:

```json
      "Syncfusion.Pdf.Net.Core/17.2.0.41": {
        "dependencies": {
          "NETStandard.Library": "2.0.3",
          "Syncfusion.Compression.Net.Core": "17.2.0.41",
          "Syncfusion.Licensing": "17.2.0.41",
          "System.Text.Encoding.CodePages": "4.4.0"
        },
        // ...
      },
      "System.Text.Encoding.CodePages/4.4.0": {
        "runtime": {
          "lib/netstandard2.0/System.Text.Encoding.CodePages.dll": {
            "assemblyVersion": "4.1.0.0",
            "fileVersion": "4.6.25519.3"
          }
        }
      }
```

The warning is shown because we'll always prefer any assemblies we ship over assemblies from a package. Since this may be a problem sometimes, we warn about it. I'm not entirely sure where the issue is exactly in this particular case, but I believe the problem lies in the nuget somehow, more investigation is needed in order to figure it out.

In any case you can safely ignore this warning if there are no other problems.

**Comment by cosminstirbu** [comment]
Is there a way I could explicitly specify these overrides somewhere so I could avoid these warnings on any future changes of the current behaviour of MTouch?

**Comment by rolfbjarne** [comment]
You can ignore warnings by adding `--nowarn:109` to the additional mtouch arguments in the project's iOS Build options (you'll have to do this one per project configuration).  m

**Comment by cosminstirbu** [comment]
So in theory all these 3 assemblies (System.Text.Encoding.CodePages.dll, Syncfusion.Compression.Portable.dll, Syncfusion.Pdf.Portable.dll) that are in multiple locations are most likely identical (maybe except for System.Text.Encoding.CodePages.dll which is loaded from Xamarin.iOS rather than the .NET Standard / .NET Core runtime)?

**Comment by cosminstirbu** [comment]
In the meanwhile I've also logged a Syncfusion issue on their forums https://www.syncfusion.com/forums/146698/mtouch-assembly-loading-warnings

**Comment by rolfbjarne** [comment]
It seems that you were able to find a solution according to the last comment in the Syncfusion post?

**Comment by cosminstirbu** [comment]
Hi, I did find a solution indeed and that was to reference Syncfusion.Xamarin.Pdf in the .NET Standard project instead of Syncfusion.Pdf.Net.Core.

Thanks for looking into this as well.
