### ISSUE TITLE
Xamarin.iOS - iPadOS 13 integration?

### ISSUE THREAD

**Issue by parmjitv** [xamarin/xamarin-macios#6764]
Hello All,

I have been developing iOS apps with Xamarin for several years now, and I must say it works great!

I have a question regarding the immediate roadmap for Xamarin.iOS development.  As you are aware, this September Apple will introduce a new entity called iPadOS 13 as part of its iOS 13 product rollout.  Apparently iPadOS is intended to supplant iOS as the preferred development platform for iPad devices.

My question is - will the functionality for both iOS 13 and iPadOS 13 be contained within Xamarin.iOS alone?  Or should we expect the functionality for iPadOS be moved off into a new product, say Xamarin.iPadOS or similar?  i.e. same as Xamarin.Mac, Xamarin.Android etc.

It is not clear from the official documentation if iPadOS is actually a brand new OS with its own SDK, or if it is just a superset of iOS within the same SDK - any clarification here would be greatly appreciated.

Many Thanks!

Parmjit V.

**Comment by spouliot** [comment]
Thanks for your feedback :)

The situation might change over time but, right now, iPadOS is mostly a marketing name, e.g. Xcode itself ships a single iPhone SDK for both iOS and iPadOS (actually one for simulator and one for devices - but there's no phone/pad distinction).

There are differences between the iPhone and iPad, including API support, but that's not a new situation (it's been this way forever). Still this might diverge more in future releases - that only Apple knows...

As for packaging Xamarin.iOS already support iOS, tvOS and watchOS (3 different SDK) so adding a fourth one (if ever needed) for iPadOS should not be a problem. 

Xamarin.Mac / macOS is a bit different. Beside some historical reasons (e.g not targeting a mobile OS) one remaining reason for a different package/product is that it is generally not released at the same time as iOS (and tvOS/watchOS) - close but not quite the same day (and generally later).

So we can't guess how things will evolve for iPadOS but rest assured we'll do our best to minimize the impact on our customers and strive to keep things as simple as possible. Everyone, even us, prefer it this way :)

**Comment by parmjitv** [comment]
@spouliot - Thanks for your prompt reply, and please excuse the lateness of my response.  I also had the impression that the iPadOS moniker was more of a marketing ploy rather than a new OS, but as you mention we will need to wait and see how this plays out over time.

Generally speaking, can we expect Xamarin apps already developed against the iOS 12 SDK to also run under iOS 13 / iPadOS?  Or will these apps require a re-development against the new iOS 13 SDK?

I have a number of Xamarin apps currently out in the field for iPad devices, and I want to ensure they do not all stop working once a user installs the new version of iOS / iPadOS on their device  come September.

Cheers,

Parmjit V.

**Comment by rolfbjarne** [comment]
> Generally speaking, can we expect Xamarin apps already developed against the iOS 12 SDK to also run under iOS 13 / iPadOS? 

Correct, generally speaking existing apps will continue to work.

> Or will these apps require a re-development against the new iOS 13 SDK?

No, but there may of course be bugs, either in iOS/iPadOS itself, Xamarin.iOS, or your apps.

> I have a number of Xamarin apps currently out in the field for iPad devices, and I want to ensure they do not all stop working once a user installs the new version of iOS / iPadOS on their device come September.

The way to do this is to install the iOS/iPadOS beta on one of your devices, and test your apps.

**Comment by parmjitv** [comment]
@rolfbjarne @spouliot - Thank you gentlemen!  Your feedback is much appreciated.
