### ISSUE TITLE
Build fails with 'can not encode offset '0x........' in resulting scattered relocation'

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#6787]
## Symptom

Thousands of build errors like this:

    error GDC116A36: can not encode offset '0x100018C' in resulting scattered relocation.

Another variation is that the build never seem to finish (due to the thousands of build errors overloading various parts of the build).

## Cause

This can occur when building for 32-bit arm architectures (armv7 and/or armv7s), and the AOT compiler produces native code that's too big for the 32-bit Mach-O file format to handle.

## Potential workarounds

* Only build for ARM64. This can be changed in the project's iOS Build options, and it's by far the easiest solution. Apple is on its way to removing the 32-bit ARM architectures, so this will eventually be the final solution too.
* Enable the linker for all assemblies (or review any custom linker arguments, such as linker definition files, to avoid skipping the linker). The idea is for the linker to remove more unused code, and if enough unused code is removed, then the size limit won't be reached.
* Disable debugging. Debugging support makes the AOT compiler produce more code, which can be enough to hit the limit. This can be changed in the project's iOS Debug options (but the downside is of course that debugging won't work).
* Enable LLVM. The LLVM compiler can sometimes produce smaller code, which can be enough to get below the size limit. The downside is that debugging won't work, and the build will be much slower.
* There's usually a particularly big assembly that's causing problems; sometimes it can help to split such assemblies into smaller assemblies. This can be a significant amount of work though, and there's no guarantee it would eventually work.
* Remove code from the app that isn't needed/used.

### References

#6125, #5815, #5810, #5512, #6345, #6526
https://bugzilla.xamarin.com/show_bug.cgi?id=1102

**Comment by spouliot** [comment]
There are a few recent issue like https://developercommunity.visualstudio.com/content/problem/683945/mtouch-hangs-after-upgrading-to-ios-12140114.html where the 32bits part of the build looks hung - but, if very patient, we see 25k+ errors from Apple's `ld` linker.

That looks like a _new twist_ on this old issue.

**Comment by taublast** [comment]
Why this HAS to be fixed: App working fine on simulator iphone 5 ios 10.3. Appl crashes on real iphone 5 ios 10.3. Trying to build to debug on real device?.. Nah, error GDC116A36: can not encode offset '0xBlaBla' in resulting scattered relocation.

**Comment by EvoPulseGaming** [comment]
I second this, not sure why this was closed as the referenced topic is misleading as if you wait it will provide this error

**Comment by wislon** [comment]
Still an issue on VS 2019 16.5 with all the latest versions of everything.

**Comment by qmark** [comment]
Still an issue, VS for Mac 8.6.1 build 26 (just updated, had it on previous version too), iPhone 4s, iOS 9.3.6, ARMv7. "Link all" or "Link Framework SDKs only" work as a workaround

**Comment by rolfbjarne** [comment]
This will not be an issue in .NET 8 ([we're dropping 32-bit support](https://github.com/xamarin/xamarin-macios/issues/15216)).
