### ISSUE TITLE
mtouch errors after updating Visual Studio 2019 through "Xcode 11 Previews" channel

### ISSUE THREAD

**Issue by royaza** [xamarin/xamarin-macios#6840]
I updated the VS in the channel "Xcode 11 Previews" some days ago. I could deploy my app on iPhone(ios 13) without any problem. Today (23 Aug), I downloaded the latest updates of Visual studio. Consequently, I can not build the code anymore. Visual Studio shows me two errors although I did not touch the code from yesterday.

### Steps to Reproduce

1. Update the Visual Studio through  "Xcode 11 Previews" channel

### Expected Behavior

The app was deployed on iPhone 7( ios 13) without any problem.

### Actual Behavior

The errors:

1. myApp/myApp.iOS/obj/iPhone/Debug/device-builds/iphone9.3-13.0/mtouch-cache/registrar.m(4,4): Error GBDAA8BF8: cannot find protocol declaration for 'UIContextMenuInteractionAnimating' (GBDAA8BF8)

2. myApp/myApp.iOS/MTOUCH: Error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new (MT4109)

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.2.4 (build 45)
Installation UUID: 747366b1-8101-46a6-9fec-40c60ef06d3c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000327

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.327 (2019-02/f8ea05bddcb) (64-bit)
	Package version: 600000327

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.9
	2.1.3
	2.1.2
	2.1.1
	2.0.6
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.505
	2.1.401
	2.1.302
	2.1.301
	2.1.101
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/bue/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/bue/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-20 15:19:18 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 11.0 (14908.4)
Build 11M382q

=== Xamarin.Mac ===

Version: 5.99.3.5 (Visual Studio Community)
Hash: dd394471
Branch: xcode11
Build date: 2019-08-21 07:29:09-0400

=== Xamarin.iOS ===

Version: 12.99.3.5 (Visual Studio Community)
Hash: dd394471
Branch: xcode11
Build date: 2019-08-21 07:29:08-0400

=== Xamarin Designer ===

Version: 16.2.0.414
Hash: a1c119d5f
Branch: remotes/origin/d16-2-xcode11
Build date: 2019-08-20 22:38:28 UTC

=== Build Information ===

Release ID: 802040045
Git revision: 7da3e8d5e4b3bf8f0d4cf83f92d60c82094502b2
Build date: 2019-08-21 17:33:58+00
Build branch: release-8.2-xcode11
Xamarin extensions: 12c306582cf9fe4ef451e9b27422c416d11c6491

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64



```

### Build Logs

[logFile_VS_MAC.txt](https://github.com/xamarin/xamarin-macios/files/3533684/logFile_VS_MAC.txt)

**Comment by projectgoav** [comment]
If you look in `~\Library\Caches\VisualStudio\8.0\TempDownload\` you may still have the old `Xamarin.iOS-12.99.2.40.pkg` installer.

Re-installing that old version helped fix the issues I saw in #6838, #6839. Hope this maybe helps you :)

**Comment by royaza** [comment]
Thank you, Ewan. I downgraded the Xamarin.iOS to the version "12.99.2.40"
as you suggested. It works correctly.

**Comment by rolfbjarne** [comment]
> === Apple Developer Tools ===
> 
> Xcode 11.0 (14908.4)
> Build 11M382q

This is Xcode 11 beta **5**.

> === Xamarin.iOS ===
> 
> Version: 12.99.3.5 (Visual Studio Community)
> Hash: dd394471
> Branch: xcode11
> Build date: 2019-08-21 07:29:08-0400

This version of Xamarin.iOS was built for Xcode 11 beta **6**.

Could you update to Xcode 11 beta 6 and see if that fixes the issue?

**Comment by aphex3k** [comment]
@projectgoav Where do i find the Xamarin.iOS-12.99.2.40.pkg if I don't have a local copy anymore?

**Comment by rolfbjarne** [comment]
@aphex3k you can find download links here on GitHub. This is explained [here](https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build).

The link for your particular package version is [xamarin.ios-12.99.2.40.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode11/d883febff0331421d9099ea3192bb9d5d43e72dd/189/package/xamarin.ios-12.99.2.40.pkg)

**Comment by royaza** [comment]
@rolfbjarne I confirm you. I updated the Xcode to the version "11 beta 6". Now, it works correctly.
Thank you.

**Comment by rolfbjarne** [comment]
@royaza great, I'm closing this then, thanks for confirming!
