### ISSUE TITLE
Xamarin.iOS.framework mlaunch quit unexpectedly

### ISSUE THREAD

**Issue by codeashoby** [xamarin/xamarin-macios#6841]
### Steps to Reproduce
Scenario 1
1. VS 2019 Win -> Pair to Mac
2. Connection to Mac establishes successfully, but "mlaunch quit unexpectedly" problem window is opened on Mac

Scenario 2
1. VS 2019 Win -> Build Xamarin.iOS project
2. "mlaunch quit unexpectedly" problem window is opened on Mac

### Expected Behavior
No problem window is open on Mac
### Actual Behavior
"mlaunch quit unexpectedly" problem window is opened on Mac
### Environment
macOS Catalina v10.15 beta, Xamarin.iOS v12.99.3.5
see attached files
[xamarin.ios_mlaunch_quit_unexpectedly.txt](https://github.com/xamarin/xamarin-macios/files/3533830/xamarin.ios_mlaunch_quit_unexpectedly.txt)
[AboutVSforMAC.txt](https://github.com/xamarin/xamarin-macios/files/3533831/AboutVSforMAC.txt)

**Comment by rolfbjarne** [comment]
I can reproduce; it's only a problem with the latest preview when using Catalina, everything works fine when using Mojave.

**Comment by projectgoav** [comment]
Reverting to the previous version of Xamarin iOS (on Mac) fixes this issue.

**Comment by rolfbjarne** [comment]
This has been fixed, and the fix will be included in the next preview.
