### ISSUE TITLE
[intro] check for duplicate or inconsistent availability attributes

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#6856]
### Duplicates

This can easily happen when existing type(s) or framework are added to a platform. E.g.

```csharp
[Watch (6,0)][iOS (9,0)]
interface AVFoo {
   [Watch (6,0)][iOS (13,0)]
   void NewMember ();
}
```

Here we have duplicate attributes and, while not confusing, it does mean extra (and non required) metadata into the platform assemblies.

### Inconsistent

```csharp
[Watch (6,0)][iOS (9,0)]
interface AVFoo {
   [Watch (5,0)][iOS (13,0)]
   void NewMember ();
}
```

Here we declare a member as available when the type is not. I'm not sure how the IDE will react - but this should be audited since one of them is wrong (whatever the IDE behaviour is).

**Comment by rolfbjarne** [comment]
> this should be audited

It should be possible to make it automated.

**Comment by spouliot** [comment]
The tests exists but are commented since they were/are very noisy.

Inside `ApiAvailabilityTest.cs`
```csharp
					// Duplicate checks, e.g. same attribute on member and type (extranous metadata)
					if (ma.Version == ta.Version) {
// about 4000
//						AddErrorLine ($"[FAIL] {ma.Version} (Member) == {ta.Version} (Type) on '{m}'.");
					}
					// Consistency checks, e.g. member lower than type
					// note: that's valid in some cases, like a new base type being introduced
					if (ma.Version < ta.Version) {
// about 8000
//						AddErrorLine ($"[FAIL] {ma.Version} (Member) < {ta.Version} (Type) on '{m}'.");
					}
```

Numbers now are
* [FAIL] Introduced : 11141 API with unneeded or incorrect version information (equal, instead of 4000)
* [FAIL] Introduced : 16987 API with unneeded or incorrect version information (earlier, instead of 8000)

**Comment by spouliot** [comment]
hmm, I did not buy that increase in size... the existing test did included inherited members - which is wrong (or at best duplicate things).

Numbers (for iOS) are now

[FAIL] Introduced : 711 API with unneeded or incorrect version information
[FAIL] Introduced : 205 API with unneeded or incorrect version information

Still large (wrt creating merge conflicts) but fixable :)

**Comment by spouliot** [comment]
With filtering out inlined protocols (which bring their own availability) the numbers are
* [FAIL] Introduced : 287 API with unneeded or incorrect version information
* [FAIL] Introduced : 54 API with unneeded or incorrect version information
