### ISSUE TITLE
Could not AOT the assembly 

### ISSUE THREAD

**Issue by GabrielMunhoz** [xamarin/xamarin-macios#6860]
[Saída-Compilação.txt](https://github.com/xamarin/xamarin-macios/files/3547697/Saida-Compilacao.txt)

**Comment by rolfbjarne** [comment]
This is the error:

>  Cannot open assembly '/Users/macdev/Library/Caches/Xamarin/mtbs/builds/Appname.iOS/7e0351db7d5a9ec7d59f32137a566148/obj/iPhone/Debug/device-builds/iphone8.1-12.4/mtouch-cache/3-Build/System.ComponentModel.DataAnnotations.dll': File does not contain a valid CIL image.

I've never seen this before, so I don't know what's happening.

Does it work if you build from the Mac instead of using Windows?

**Comment by rolfbjarne** [comment]
OK, then I think we'll need a way to reproduce this ourselves. Would it be possible to get access to your project?
