### ISSUE TITLE
Task.Run body taking a long time to start execution

### ISSUE THREAD

**Issue by timgithb** [xamarin/xamarin-macios#6862]
We've observed an intermittent and rare issue recently during development testing on iOS where it appears that the body of a Task.Run call is being executed after a significant delay (minutes). This issue has not been observed on the Android version of the app as of yet. The issue has manifested in a different area of code each time and in each case in an area of code that has not been changed in a long time. We have also not made any updates to our VS/Xamarin/etc build versions on our build server for weeks before the issue was first observed.

In the example log entries below the 'Updating' log entry is logged on the main thread and the 'Retrieving' entry is the first line in the body of a Task.Run with little impeding code between. In the first exchange here there is no issue and the body executes within < 50 ms but in the following three cases the body does not execute and the user ends up triggering it again. There are no locks that could be impeding the execution in this scenario. However ~4 minutes later we see all three of the bodies execute.

2019-08-20 19:36:26.817 [DEBUG] (1:) [HistoryViewModel] : Updating history for display
...
2019-08-20 19:36:26.865 [DEBUG] (7:Thread Pool Worker) [RetrieveHistory] : Retrieving history
...
2019-08-20 19:40:17.571 [DEBUG] (1:) [HistoryViewModel] : Updating history for display
...
2019-08-20 19:40:35.336 [DEBUG] (1:) [HistoryViewModel] : Updating history for display
...
2019-08-20 19:40:43.907 [DEBUG] (1:) [HistoryViewModel] : Updating history for display
...
2019-08-20 19:44:20.030 [DEBUG] (20:Thread Pool Worker) [RetrieveHistory] : Retrieving history
2019-08-20 19:44:20.031 [DEBUG] (20:Thread Pool Worker) [RetrieveHistory] : Retrieving history
2019-08-20 19:44:20.032 [DEBUG] (20:Thread Pool Worker) [RetrieveHistory] : Retrieving history

As the issue is occurring in different parts of stable code I suspect the issue is elsewhere in the app or system. Any areas to investigate would be greatly appreciated.

Issue observed on: iPhone8,4 (12.0), iPhone10,2 (12.0), iPhone9,2 (12.1.4), iPhone10.1 (12.1.2)

### Steps to Reproduce

No steps to reproduce this issue have been identified

### Expected Behavior

Task.Run body executes within milliseconds

### Actual Behavior

Task.Run body execution can be delayed by several minutes

### Environment

Builds are initiated from the Windows machine

```
Microsoft Visual Studio Enterprise 2019
Version 16.1.4
VisualStudio.16.Release/16.1.4+29020.237
Microsoft .NET Framework
Version 4.7.03062

Installed Version: Enterprise

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Professional Edition   4.41.1.9417-95d9eec7a
Dotfuscator for Visual Studio.  Copyright (C) 2002-2019 PreEmptive Solutions LLC

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.1.0.545 (d16-1@db7c858e8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3a07bd426d3
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26


Xamarin.iOS and Xamarin.Mac SDK   12.10.0.157 (6bd9475)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

--- Mac Build Machine VS ---

{\rtf1\ansi\ansicpg1252\cocoartf1671
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 === Visual Studio Enterprise 2017 for Mac ===\
\
Version 7.6.9 (build 22)\
Installation UUID: 47bac5da-aaaa-4e10-a555-3574784e8dde\
Runtime:\
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)\
	GTK+ 2.24.23 (Raleigh theme)\
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)\
\
	Package version: 518010003\
\
=== NuGet ===\
\
Version: 4.3.1.4445\
\
=== .NET Core ===\
\
Runtime: /usr/local/share/dotnet/dotnet\
Runtime Versions:\
	2.1.2\
	2.0.5\
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks\
SDK Versions:\
	2.1.302\
	2.1.4\
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks\
\
=== Xamarin.Profiler ===\
\
Version: 1.6.3\
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler\
\
=== Xamarin.Android ===\
\
Version: 9.0.0.20 (Visual Studio Enterprise)\
Android SDK: /Users/build_adm/Library/Developer/Xamarin/android-sdk-macosx\
	Supported Android versions:\
		7.1 (API level 25)\
		8.1 (API level 27)\
\
SDK Tools Version: 26.1.1\
SDK Platform Tools Version: 26.0.2\
SDK Build Tools Version: 26.0.3\
\
Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home\
java version "1.8.0_131"\
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)\
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)\
\
Android Designer EPL code available here:\
https://github.com/xamarin/AndroidDesigner.EPL\
\
=== Xamarin Inspector ===\
\
Version: 1.4.3\
Hash: db27525\
Branch: 1.4-release\
Build date: Mon, 09 Jul 2018 21:20:18 GMT\
Client compatibility: 1\
\
=== Apple Developer Tools ===\
\
Xcode 10.1 (14460.46)\
Build 10B61\
\
=== Xamarin.Mac ===\
\
Version: 5.0.0.0 (Visual Studio Enterprise)\
Hash: b40230c0\
Branch: \
Build date: 2018-09-27 11:41:37-0400\
\
=== Xamarin.iOS ===\
\
Version: 12.6.0.25 (Visual Studio Enterprise)\
Hash: 50f75273\
Branch: d16-0\
Build date: 2019-03-05 11:50:33-0800\
\
=== Build Information ===\
\
Release ID: 706090022\
Git revision: 0a0ba3c4593e9adb1c6ff6324e641036146af376\
Build date: 2018-10-05 16:38:51+00\
Build branch: release-7.6\
Xamarin extensions: f7856b13f2c03a58e08381d3a5970bba18f5c7d7\
\
=== Operating System ===\
\
Mac OS X 10.14.0\
Darwin 18.0.0 Darwin Kernel Version 18.0.0\
    Wed Aug 22 20:13:40 PDT 2018\
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64\
\
}
```

### Build Logs

n/a

### Example Project (If Possible)

n/a

**Comment by timgithb** [comment]
I was able to induce similar behavior in the app by intentionally bombarding the system with a lot of short lived tasks while otherwise using the app normally. In this case the threadpool utilization remained fairly low but I could see my task execution get delayed by upwards of ~50 seconds while testing on an iPhone 6, though the amount of delay is not deterministic (also this code does eventually cause the iOS app to terminate due to exceeding it's wakeup limit). Running the same code on Android yields similar results so this seems to indicate that if this is the root cause it may be in the iOS specific code or some condition in shared code that so far has only triggered on iOS. I'm reviewing the Task usage for places that could potentially fall into this pattern.

        Task testTask;

        void TestShortLivedTasks()
        {
            testTask= Task.Factory.StartNew(() =>
            {
                ThreadPool.GetMaxThreads(out var maxWorkerThreads, out var maxCompletionThreads);

                while (true)
                {
                    for (var i = 0; i < 180; i++)
                    {
                        Task.Run(() =>
                        {
                            ThreadPool.GetAvailableThreads(out var workerThreads, out var completionThreads);

                            Console.WriteLine($"[TEST] [{Thread.CurrentThread.ManagedThreadId}] Starting short lived task: {workerThreads}/{maxWorkerThreads}");

                            Thread.Sleep(10);
                        });
                    }

                    Thread.Sleep(25);
                }
            }
            , CancellationToken.None, TaskCreationOptions.LongRunning, TaskScheduler.Default);
        }

**Comment by mandel-macaque** [comment]
@timgithb that is good news (at least for us ;) ). Please keep us up to date we might be able to help a little with the debugging. But it does look like is an issue in your iOS code base.

**Comment by mandel-macaque** [comment]
@timgithb I suppose that you have not seen any issues with it. Closing the issue, please feel free to re-open it if needed.
