### ISSUE TITLE
ITMS-90806: CFBundleIdentifier collision

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#6920]
### Steps to Reproduce

1. Submit **"Intents Sample**

### Expected Behavior

No error

### Actual Behavior

An email with
```
ITMS-90806: CFBundleIdentifier collision - Each bundle must have a unique bundle identifier. The bundle identifier 'xamarin.ios.xamarin-framework' is used in the bundles '[Xamarin.framework, Xamarin.framework]'

ITMS-90806: CFBundleIdentifier collision - Each bundle must have a unique bundle identifier. The bundle identifier 'xamarin.ios.mono-framework' is used in the bundles '[Mono.framework, Mono.framework]'
```

### Environment

`d16-3` but it's likely unrelated - this seems to be a **new** check

My initial guess is that it does not like the iOS app and the watchOS app to have similar frameworks (even if they differ wrt their architectures)

**Comment by whitneyschmidt** [comment]
From @spouliot - this passed on August 23rd.

**Comment by spouliot** [comment]
It can probably be workaround by disabling the app/extension code sharing (which uses frameworks instead of statically linking the code).

**Comment by spouliot** [comment]
# Workaround

Add `--nodevcodeshare` in the **Additional mtouch arguments** of every projects part of the submitted application.

**Comment by rolfbjarne** [comment]
Should be fixed by https://github.com/xamarin/xamarin-macios/commit/a9abc07cb357f9f012e3da66c70fa09d96bf02f7.

**Comment by spouliot** [comment]
Submission tests using `Xcode11` branch are not reporting this with the fix
