### ISSUE TITLE
AOT-compilation for 32-bit architectures fails on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#6925]
### Steps to Reproduce

1. Create a new iOS project, select a device configuration, and choose 'ARMv7' as the architecture in the project's iOS Build options.
2. Compile for device.

This affects watchOS too, since most watchOS apps have 32-bit executables.

### Expected Behavior

Successful compilation.

### Actual Behavior

> error MT3001: Could not AOT the assembly ...

### Environment

This only happens when running on macOS 10.15 Catalina.

### Diagnosis

The reason this fails is that the 32-bit AOT compilers we're shipping with Xamarin.iOS 12.99 (and 13.0) are themselves 32-bit binaries, and 32-bit binaries won't execute on macOS 10.15 Catalina.

### Workarounds

1. This has been fixed in the upcoming d16-3 release, which means that the latest d16-3 preview works.
2. Use only 64-bit architectures in the project.
3. Build on macOS 10.14 Mojave.

**Comment by xperseguers** [comment]
This still does not seem to be available/fixed in the "Xcode 11 Previews" channel, which is needed to take advantage of iOS 13.

**Comment by rolfbjarne** [comment]
> This still does not seem to be available/fixed in the "Xcode 11 Previews" channel, which is needed to take advantage of iOS 13.

It won't be fixed in the initial release with Xcode 11 support, it will be fixed in a release which comes out shortly after.

**Comment by zerokewl88** [comment]
Any news on this, found this a extremely annoying AOT Compile error, and had to investigate / waste alot of time, just to realize this is the cause..

**Comment by rolfbjarne** [comment]
This has been fixed for a while (d16-3 was released some time ago).

If you get an AOT compile error with the current stable version of Xamarin.iOS, it's a different issue, so please file it, attach your build log, and we'll have a look.
