### ISSUE TITLE
Xamarin.iOS - 32-bit architectures required?

### ISSUE THREAD

**Issue by parmjitv** [xamarin/xamarin-macios#6937]
Hello All,

When generating release builds for Xamarin.iOS apps, when is it proper to restrict support to the ARM64 architecture alone?

I am developing a new Xamarin.iOS app with the intended target devices as the iPhone 7 series and higher, and the iPad Pro line of products.  Is it necessary to also include release support for the ARMv7 and ARMv7s architectures?

My understanding is that ARMv7 and ARMv7s provide support for legacy iOS devices that still use 32-bit processors, i.e. iPhone 5 and iPad Mini, or run a 32-bit version of iOS such as v10 or earlier.  Is this correct?

Many Thanks!

Parmjit V.

**Comment by rolfbjarne** [comment]
> I am developing a new Xamarin.iOS app with the intended target devices as the iPhone 7 series and higher, and the iPad Pro line of products. Is it necessary to also include release support for the ARMv7 and ARMv7s architectures?

No, in this case you only need ARM64.

You can see a list of the devices that have an ARMv7(s) CPU [here](https://stackoverflow.com/a/12510245/183422) (all newer devices that aren't listed there are ARM64 devices).

> My understanding is that ARMv7 and ARMv7s provide support for legacy iOS devices that still use 32-bit processors, i.e. iPhone 5 and iPad Mini, or run a 32-bit version of iOS such as v10 or earlier. Is this correct?

Correct.
