### ISSUE TITLE
[iOS 13] UINavigationBar.Appearance doesn't expose new appearance proxies

### ISSUE THREAD

**Issue by projectgoav** [xamarin/xamarin-macios#6938]
### Steps to Reproduce

1. Create new project targetting iOS 13
2. `UINavigationBar.Appearance.[Compact|Standard|ScrollEdge]Appearance`
3. Compile error

### Expected Behavior
`UINavigationBar.Appearance` should return an appearance proxy exposing properties allowing the use of `UINavigationBarAppearance` instances.

### Actual Behavior
Compile error. Return type of `Appearance` property is incorrect. 

Available in Swift
```swift
let barAppearance = UINavigationBarAppearance()

// Set some properties... 

UINavigationBar.appearance().standardAppearance = barAppearance
```

#### Edit 
Given an instance of UINavigationBar, the new properties are exposed. It's just the static property that is incorrect.

```C#
var bar = new UINavigationBar(/*...*/);
bar.StandardAppearance = new UINavigationBarAppearance();
```

### Environment

Visual Studio Mac 8.2.5 (Build 42)
Mono MDK 6.0.0.333 (2019/02)
Xamarin iOS 5.99.4.26

**Comment by chamons** [comment]
This looks reasonable. I'm adding to xcode11 milestone for now, but we can add this later if necessary (since it shouldn't be a breaking change).

Thanks for the report!

**Comment by FlavioGoncalves-Cayas** [comment]
Any updates on this? Without the proxies I have to set the appearances on each UIViewController separately.

**Comment by rolfbjarne** [comment]
These proxies appearance proxies are available our iOS 13.2 release (the current stable version of Xamarin.iOS), so I'm closing this. Feel free to reopen if you continue to have problems with these appearance proxies.

See also #6834.

**Comment by FlavioGoncalves-Cayas** [comment]
I'm on the iOS 13.2 release, but the **static** property Appearance on UINavigationBar of type UINavigationBarAppearance is not exposing CompactAppearance, StandardAppearance and ScrollEdgeAppearance.

**Comment by rolfbjarne** [comment]
You're correct, a fix is in progress now.

**Comment by rolfbjarne** [comment]
Fixed in https://github.com/xamarin/xamarin-macios/commit/3ec3470a4ef6313f47edd70b1f919699acd7a38c.

**Comment by VladimirAbakumov** [comment]
There are stil not appearance properties CompactAppearance, StandardAppearance and ScrollEdgeAppearance on the static property Appearance on UINavigationBar.

`UINavigationBar.Appearance.StandardAppearance` -
Error	CS1061	'UINavigationBar.UINavigationBarAppearance' does not contain a definition for 'StandardAppearance' and no accessible extension method 'StandardAppearance' accepting a first argument of type 'UINavigationBar.UINavigationBarAppearance' could be found (are you missing a using directive or an assembly reference?)


Xamarin.iOS
Version: 13.2.0.47
Hash: c2cbd3480
Branch: d16-3
Build date: 2019-09-30 22:37:32-0400

**Comment by rolfbjarne** [comment]
@VladimirAbakumov it'll be in the next release, which will come out within the next few days.
