### ISSUE TITLE
XmlSerializer not Using UTF-8 as Default Encoding (.NET 4.8 Mac)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#6944]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/722323/xmlserializer-not-using-utf-8-as-default-encoding.html)._

---
I’ve been using .NET Framework 4.7.x for my Xamarin.Mac app quite a while.
And my apps are using XmlSerializer for storing configurations and other data.
Couple of days ago I upgraded them to .NET Framework 4.8 hoping that will somehow … ease future migration path to the upcoming .NET 5…
Since then all XMLs created by XmlSerializer are encoded as us-ascii instead of utf-8 resulting entire data broken!!! (e.g. all asian texts are unanimously replaced by question mark(?) …) 
Currently I hot-fixed the issue by implementing XmlWriter’s Settings manually but this should absolutely be addressed ASAP!!!

(By the way, I am fortunate that I had implemented auto-backup solution a month ago so I was able to restore the important a year-worth data.)

---
#### Visual Studio Feedback System on 9/5/2019, 01:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by chamons** [comment]
This issue was moved to mono/mono#16741
