### ISSUE TITLE
Code 100% impossible to translate the same code in 100% pure Xamarin ios.

### ISSUE THREAD

**Issue by softlion** [xamarin/xamarin-macios#6965]
Given the solution described here to easily localize a storyboard https://medium.com/@mario.negro.martin/easy-xib-and-storyboard-

It seems 100% impossible to translate the same code in 100% pure Xamarin ios.

Can you confirm ?

```
protocol Localizable {
    var localized: String { get }
}
extension String: Localizable {
    var localized: String {
        return NSLocalizedString(self, comment: "")
    }
}

protocol XIBLocalizable {
    var xibLocKey: String? { get set }
}

extension UILabel: XIBLocalizable {
    @IBInspectable var xibLocKey: String? {
        get { return nil }
        set(key) {
            text = key?.localized
        }
    }
}
```

**Comment by chamons** [comment]
I am not a Swift expert but I believe that is called "retroactive modeling" and beyond the power of C# extensions. You can't add a protocol to an existing type in C#.

I'm going to close this issue, as it isn't something we can fix in Xamarin.iOS since you can't express it in C#.

If you'd like to make a suggestions on the design of C#, please consider opening a discussion here:

https://github.com/dotnet/csharplang

**Comment by softlion** [comment]
You were able to translate these in C# using bindings. Why are you not able to translate this one using the same transformation?

**Comment by chamons** [comment]
The ability to add arbitrary protocols to an existing class is something you can't express in C#. Extensions in c# can add methods, but not interfaces. 

Xamarin.iOS tries to be a "thin layer" over Apple's APIs, so bundling in a specific localization strategy is outside our mandate.

**Comment by Therzok** [comment]
@softlion for this capability, we would need https://github.com/dotnet/csharplang/issues/110 to actually be implemented in C#.

**Comment by softlion** [comment]
Well the idea here is not to add an interface, it's to add a property to an existing class. It is necessary so the iOS storyboard "mapper service" finds the property on the class. Otherwise it will throw an error "this class is not key/value compliant for key "xxxx").

To be able to do that, ios tries to get this property using an unknown mechanism.
Maybe you already hooked this mechanism ?

**Comment by chamons** [comment]
I do not believe there are extension properties in C#, just extension methods.

I believe Obj-C is just invoking a selector. 

It might be possible to port such a system to ObjC. I'm not sure without doing more research, but I suspect it will involve a lot of hacking. 

In any case, this is not really a bug report :)

**Comment by rolfbjarne** [comment]
I wonder how this swift code would be expressed in Objective-C, because if it's done using categories, we can model that in C#.

**Comment by rolfbjarne** [comment]
If someone can create an Xcode sample written in Objective-C, I can translate that to C#.
