### ISSUE TITLE
UIApplication.OpenURLOptionsKey.sourceApplication

### ISSUE THREAD

**Issue by Carl-Wen** [xamarin/xamarin-macios#7002]
I am build a demo with third party login, I meet a problem about "UIApplication.OpenURLOptionsKey.sourceApplication", I can not find the key string in Xamarin.iOS. Can any one help me?

in swift:
![image](https://user-images.githubusercontent.com/38063530/64932038-def34d80-d86e-11e9-9032-6b30e42e136e.png)
```Swift
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        let urlKey: String = options[UIApplication.OpenURLOptionsKey.sourceApplication] as! String
        
        if urlKey == "com.tencent.mqq" {
            return TencentOAuth.handleOpen(url)
        }
        
        return application(app, open: url, options: options)
    }
```

And in C#:
![image](https://user-images.githubusercontent.com/38063530/64932161-b455c480-d86f-11e9-99b3-992fa519c479.png)
```C#
public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
        {
            var urlKey = options[UIApplication.LaunchOptionsUrlKey]?.ToString();

            if (urlKey == "com.tencent.mqq")
            {
                return TencentOAuth.HandleOpenURL(url);
            }
            return base.OpenUrl(app, url, options);
        }
```

**Comment by whitneyschmidt** [comment]
Hi Carl,

Thank you for your feedback! 

It is likely that `UIKit.UIApplicationOpenUrlOptions` is the API you are looking for.

For more information about dictionary wrappers, check out: https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/binding-types-reference#strongly-typed-dictionaries

**Comment by Carl-Wen** [comment]
> Hi Carl,
> 
> Thank you for your feedback!
> 
> It is likely that `UIKit.UIApplicationOpenUrlOptions` is the API you are looking for.
> 
> For more information about dictionary wrappers, check out: https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/binding-types-reference#strongly-typed-dictionaries
------
> Hello, thanks for your reply, do you mean this class:(I tried, but it didn't work, 
But I think I need a static const string here.)
![image](https://user-images.githubusercontent.com/38063530/65004653-b67f5800-d92f-11e9-95ec-b18db3ba4515.png)
![image](https://user-images.githubusercontent.com/38063530/65004789-2db4ec00-d930-11e9-8b59-876ef896c9fa.png)
Maybe this class(below) should be used here, but I don't know why it is internal.  
![image](https://user-images.githubusercontent.com/38063530/65004913-ab78f780-d930-11e9-9d36-bde711be3a5d.png)

------
Do you know what should I do?

**Comment by chamons** [comment]
Try creating a new instance with:

```public UIApplicationOpenUrlOptions (NSDictionary dictionary)```

and then poking ﻿﻿SourceApplication

I thought we exposed those keys as well, but apparently aren't. I'm looking into that.

**Comment by dalexsoto** [comment]
Hello 👋 

Yeah as @chamons said you want to do this

```csharp
public override bool OpenUrl (UIApplication app, NSUrl url, NSDictionary options)
{
        var openOptions = new UIApplicationOpenUrlOptions (options);
        if (openOptions?.SourceApplication == "blah")
                // handle scenario
        return base.OpenUrl(app, url, options);
}
```

Hope this helps.

**Comment by Carl-Wen** [comment]
@chamons @dalexsoto Thank you very much! It works well now!
