### ISSUE TITLE
Position 103:18. Type ios:UISegmentedControl not found in xmlns clr-namespace:UIKit;assembly=Xamarin.iOS;targetPlatform=iOS with iOS 13

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#7024]
Steps to reproduce:

1. Download the Archive.zip project
2. set Xappy.iOS as startup project
3. Deploy application to a device. 
     a. I'm deploying this to an iPad (6th Generation) running 13.1 not sure if the exception is specific to that device or if it will show up on other devices as well

I'm on 10.15 Beta (19A558d) of Catalina and using the latest XCode 11 GM 2

Installed:

https://gist.github.com/chamons/12b3c334e3add1a85a0cbf301a3eb354

[Archive.zip](https://github.com/xamarin/xamarin-macios/files/3628100/Archive.zip)
[msbuild2.binlog.zip](https://github.com/xamarin/xamarin-macios/files/3628101/msbuild2.binlog.zip)

Originally https://devdiv.visualstudio.com/DevDiv/_workitems/edit/985030

**Comment by PureWeen** [comment]
It looks like this is related to linking. 

I tested this on xCode 10/Mojave/vs mac 8.2 and was able to recreate against a simulator by turning on SDKONLY for the linking

Though from previous conversations I thought that if something inherited from NSObject then it wouldn't get linked out? 

https://xamarinhq.slack.com/archives/C03CCJNR7/p1567818035412800

I guess UISegmentedControl is one of the special ones that will get linked out?

**Comment by spouliot** [comment]
There's nothing using `UISegmentedControl` in a way that makes any of the assemblies metadata refer to the type - so the linker will remove it.

> Though from previous conversations I thought that if something inherited from NSObject then it wouldn't get linked out?

I was not precise enough :)

**Comment by spouliot** [comment]
side note: I don't know enough about XF builds (so take this with a grain, or two, of salt) but...

Since you're processing the `xaml` file you could, in theory, detect the types that are present there, like `UISegmentedControl` and generate/update some code behind file that would just include a bun of lines like:

```csharp
[assembly: Preserve (typeof (UISegmentedControl), AllMembers = true)]
```
