### ISSUE TITLE
[Xcode11] Introspection failures in Mac OS X 10.15

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#7026]
We have several introspection failures in mac os x 10.15: https://jenkins.internalx.com/blue/organizations/jenkins/macios/detail/master-xcode11/1/pipeline/220/

**Comment by mandel-macaque** [comment]
This should have been fixed by https://github.com/xamarin/xamarin-macios/pull/6999 is interesting we see them in that commit after the xcode11 merge.

**Comment by spouliot** [comment]
maybe the merge to master was done with an earlier commit of `xcode11` ?
that's one of the reason why we needed to close `xcode11` - we can't continually merge it everywhere and keep track of what's in or out

**Comment by mandel-macaque** [comment]
Closing after looking at the source: https://github.com/xamarin/xamarin-macios/blob/master/src/MapKit/MKEnums.cs#L117
