### ISSUE TITLE
[watchOS] ARM64_32 not automatically selected for new watchOS projects

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#7046]
### Steps to Reproduce

1. Create a new iOS project
2. Right click on the project and select "Add project"
3. Create watchOS project

### Expected Behavior

In the watchOS build option, the architecture should be ARM64_32 (new devices)

### Actual Behavior

Architecture is still set to the old one ARMv7k

### Environment

https://gist.github.com/VincentDondain/ca9f89718402b9c6c46acd3cf0633e6d

> VS bug [#986823](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/986823)

**Comment by rolfbjarne** [comment]
Closing since we don't support watchOS anymore.
