### ISSUE TITLE
MT4109: Failed to compile the generated registrar code

### ISSUE THREAD

**Issue by bonbon2106** [xamarin/xamarin-macios#7047]
I'm using VS 2019 (version 16.2.5, .Net Framework 4.7.03190) on Window and pare with MAC to compile my project. After updating Xcode on MAC to version 11.0 (11A420a), I get an error while building my project with the following message:
>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error GEA45E82A: expected identifier or '{'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

Please help me to check this issue.

Thanks so much!

```
```

**Comment by rolfbjarne** [comment]
The problem is that your Mac auto-upgraded Xcode to the new Xcode 11, and our current version of Xamarin.iOS is not compatible with Xcode 11.

We'll release a version of Xamarin.iOS that is compatible with Xcode 11 later today. A more immediate solution is to install our preview version of Xamarin.iOS with support for Xcode 11.

**Comment by neilbhasme** [comment]
Hi,

Any updates to this issue? My nicely building project is not building anymore with error code and environment details exactly as posted by bonbon2016. Steps to resolve this if any would be highly appreciated if any already exists (am  new to Xamarin dev)
