### ISSUE TITLE
MTOUCH (MT4109) ERROR

### ISSUE THREAD

**Issue by venkatvidyut** [xamarin/xamarin-macios#7048]
/Volumes/Data/Development/Xamarin/BinanceExchange/BinanceExchange.iOS/MTOUCH: Error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new (MT4109) (BinanceExchange.iOS)

after updating xcode this error has been come.

**Comment by rolfbjarne** [comment]
The problem is that our current version of Xamarin.iOS is not compatible with Xcode 11.

We'll release a version of Xamarin.iOS that is compatible with Xcode 11 later today. A more immediate solution is to install our preview version of Xamarin.iOS with support for Xcode 11.
