### ISSUE TITLE
Can't build any iOS project after Xcode 11 upgrade

### ISSUE THREAD

**Issue by esenciadev** [xamarin/xamarin-macios#7050]
Existing and new iOS Forms projects fail to compile after update to Xcode 11.

### Steps to Reproduce

1. Create New Forms solution
2. Restore NuGet references
2 (alt). Update NuGet references, same error occurs
3. Build project

### Expected Behavior

Project builds successfully

### Actual Behavior

Linker errors regarding WatchKit framework

### Environment

Visual Studio Community 2019 for Mac
Version 8.2.6 (build 26)
Installation UUID: 66597600-a967-44ee-af5a-64184618d5eb
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000334

Mono Framework MDK
Runtime:
	Mono 6.0.0.334 (2019-02/6256b82d62f) (64-bit)
	Package version: 600000334

NuGet
Version: 5.1.0.6013

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.7
	2.2.2
	2.2.0
	2.1.9
	2.1.8
	2.1.6
	2.1.5
SDK: /usr/local/share/dotnet/sdk/2.2.402/Sdks
SDK Versions:
	2.2.402
	2.2.104
	2.2.100
	2.1.505
	2.1.504
	2.1.500
	2.1.403
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

Xamarin.Profiler
Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 11.0 (14936)
Build 11A420a

Xamarin.Mac
Version: 5.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

Xamarin.iOS
Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

Xamarin Designer
Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

Xamarin.Android
Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/ryan/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Microsoft Mobile OpenJDK
Java SDK: /Users/ryan/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 802060026
Git revision: a4ea4d00345f4d98a95bd2322b1d04935eb553e1
Build date: 2019-09-05 18:24:25+00
Build branch: release-8.2
Xamarin extensions: 366997b587d63360705507e281ae75025762cadf

Operating System
Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

### Build Logs

https://gist.github.com/esenciadev/bfa51f165e51cb4c8163944b2b47f072

### Example Project (If Possible)

[Archive.zip](https://github.com/xamarin/xamarin-macios/files/3639098/Archive.zip)

**Comment by freppps** [comment]
Haven't tried running your project, writing from my phone. Had the same error, try setting the "Linker behavior" to "Link Framework SDKs Only".

If you are using Xamarin Forms with XAML Hot Reload (Like me) - it will be disabled since the "Link Framework SDKs Only" option isn't supported.

**Comment by starkos** [comment]
This issue was originally reported in #6471, which was closed with "Apple forgot to ship the WatchKit framework (for iOS) with their Xcode betas, so this won't work until Apple fixes their SDK". But the [XCode 11 Release Notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes) say "The WatchKit framework is no longer included in the iOS SDK. If you’re using WatchKit APIs from iOS, you need to remove this use. The WatchKit framework remains available on watchOS. If you’re using WatchKit APIs from iOS to infer availability of features on the paired Apple Watch, include information about your use case when you submit feedback to Feedback Assistant. (49707950)".

In the meantime, the workaround from #6471 still applies: in the iOS project settings > Build > iOS Build change "Linker behavior" to "Link Framework SDKs only".

**Comment by Drew-FitEpic** [comment]
> In the meantime, the workaround from #6471 still applies: in the iOS project settings > Build > iOS Build change "Linker behavior" to "Link Framework SDKs only".

Didn't work for me.  

VS Community- 16.2.5,
Xcode - 11.0.  

To the best of my knowledge, I am not referencing/utilizing any of the WatchKit APIs.

**Comment by freppps** [comment]
> > In the meantime, the workaround from #6471 still applies: in the iOS project settings > Build > iOS Build change "Linker behavior" to "Link Framework SDKs only".
> 
> Didn't work for me.
> 
> VS Community- 16.2.5,
> Xcode - 11.0.
> 
> To the best of my knowledge, I am not referencing/utilizing any of the WatchKit APIs.

Tried deleting delete bin + obj folders etc?
Have a look at https://github.com/xamarin/xamarin-macios/issues/6471#issuecomment-533813071

**Comment by Drew-FitEpic** [comment]
> > > In the meantime, the workaround from #6471 still applies: in the iOS project settings > Build > iOS Build change "Linker behavior" to "Link Framework SDKs only".
> > 
> > 
> > Didn't work for me.
> > VS Community- 16.2.5,
> > Xcode - 11.0.
> > To the best of my knowledge, I am not referencing/utilizing any of the WatchKit APIs.
> 
> Tried deleting delete bin + obj folders etc?
> Have a look at [#6471 (comment)](https://github.com/xamarin/xamarin-macios/issues/6471#issuecomment-533813071)

Still no bueno.  Deleting the bin + obj folders is always one of the first things I try.  But just to be sure, I did it again (and again).

**Comment by itoshinji** [comment]
me too

**Comment by apicquot** [comment]
Weirdly,
 I can make it work for the iphone simulator config with "Link Framework SDKs only" and the architecture "x86_64" but no luck for the iphone config "ARM64".

**Comment by lesterbotello** [comment]
I can confirm this is a problem. For me, enabling the linker with "Link Framework SDKs only" got my project running again.

**Comment by apicquot** [comment]
Not working for me even after removing bin and obj. That is my config

![image](https://user-images.githubusercontent.com/10003557/65394051-c4c9db80-dd56-11e9-9b38-3e47c35dae29.png)

**Comment by rolfbjarne** [comment]
The problem is that our current version of Xamarin.iOS is not compatible with Xcode 11.

We'll release a version of Xamarin.iOS that is compatible with Xcode 11 later today. A more immediate solution is to install our preview version of Xamarin.iOS with support for Xcode 11.
