### ISSUE TITLE
Upload to AppStore not documented, Xcode 11

### ISSUE THREAD

**Issue by DM1145** [xamarin/xamarin-macios#7058]
With the release of Xcode 11 (conveniently auto-updated through the App store), support for the Application Loader was removed and that application is no longer available.  

My VS version is 8.2.6 (build26) for Mac.  

What is the new optimal/referred method of pushing IPA archives to the Apple App store for distribution?

Thank you

**Comment by Mikilll94** [comment]
I also have this problem. This should be described in Xamarin.iOS docs.

**Comment by MartinZikmund** [comment]
Also encountered this. For now the workaround seems to be to do it directly on mac via Terminal https://community.adobe.com/t5/Animate/Xcode-11-don-t-have-application-loader/td-p/10516050

    $ xcrun altool --upload-app -f ./path/to/my.ipa -t ios -u myappleid@example.com -p mypassword

**Comment by chamons** [comment]
You are absolutely correct, we missed documenting it. Apologies.

I've contacted people, who are working on it. Until it is fixed, I will keep this issue open so you can track the work.

**Comment by spouliot** [comment]
https://github.com/MicrosoftDocs/xamarin-docs/issues/2163

**Comment by MartinZikmund** [comment]
Any chance of a UI tool for this purpose directly in VS Mac 😅 ?

**Comment by jimmgarrido** [comment]
That's exactly what we did 😄 

Visual Studio for Mac 8.3 introduces the ability to upload your app directly to App Store Connect. We've updated the [publishing to app store](https://docs.microsoft.com/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=macos#build-and-submit-your-app) with the new workflow. Thanks everyone!

**Comment by MartinZikmund** [comment]
@jimmgarrido wow, epic!!!

**Comment by DM1145** [comment]
Updated VS, works quite nicely. 

@jimmgarrido, will VS cache the App Store password, or will it need to be entered each upload?

**Comment by jimmgarrido** [comment]
@DM1145 It's cached on VS for Mac so I believe it's a bug on Windows. I'll file an issue for the team, thanks for the feedback!

**Comment by DM1145** [comment]
@jimmgarrido I'd likely prefer it to be cached until VS is closed - or at least have that as an option.  
Just my 2 cents worth..

Thanks!

**Comment by Laumania** [comment]
@jimmgarrido It the app specific password suppose to be cached? It's not for me on Mac.. I have to get a new everytime, which is very annoying.
