### ISSUE TITLE
Failed to compile the generated registrar code.

### ISSUE THREAD

**Issue by PetrosSarantakos** [xamarin/xamarin-macios#7062]
1. Trying to build an app in iphone 7(iOS 13.0) or ipad 6th gen (iOS 12.4.1)
2. The error above appears. 

### Expected Behavior
Should build normally, as before update to xcode 11
### Actual Behavior
Getting the same error, can only build in iphone simulator
### Environment

```
Microsoft Visual Studio Enterprise 2019
Version 16.2.5
VisualStudio.16.Release/16.2.5+29306.81
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Application Insights Tools for Visual Studio Package   9.1.00611.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.2.292.25104
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.2.292.25104
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.2.292.25104
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.2.292.25104
Azure Functions and Web Jobs Tools

C# Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20626.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.2.6 (4cfc7c3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10627.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.2.0.95 (d16-2@37df81894)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.117 (59a59e8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.1.1 (d16-2/cec9eb4)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969


Xamarin.iOS and Xamarin.Mac SDK   12.14.0.114 (c669116)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs		

1>------ Build started: Project: FSRDemoApp, Configuration: Debug Any CPU ------
1>C:\Users\p.sarantakos\source\repos\PobucaSales_Xamarin\FSRDemoApp\FSRDemoApp\FSRDemoApp.csproj : warning NU1701: Package 'Microsoft.Bcl 1.1.6' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
1>C:\Users\p.sarantakos\source\repos\PobucaSales_Xamarin\FSRDemoApp\FSRDemoApp\FSRDemoApp.csproj : warning NU1701: Package 'Microsoft.Bcl.Async 1.0.165' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
1>C:\Users\p.sarantakos\source\repos\PobucaSales_Xamarin\FSRDemoApp\FSRDemoApp\FSRDemoApp.csproj : warning NU1701: Package 'PCLStorage 1.0.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
1>FSRDemoApp -> C:\Users\p.sarantakos\source\repos\PobucaSales_Xamarin\FSRDemoApp\FSRDemoApp\bin\Debug\netstandard2.0\FSRDemoApp.dll
1>Done building project "FSRDemoApp.csproj".
2>------ Build started: Project: FSRDemoApp.iOS, Configuration: Debug iPhone ------
2>  Executing SayHello Task to establish a connection to a Mac Server. 
2>  						 Properties: SessionId=7ca2c435a746db308125842d8b48b3c0, 
2>  							ServerPort=57187, 
2>  							ServerAddress=10.16.2.216, 
2>  							ServerUser=KostasSkoul, 
2>  							ServerPassword=, 
2>  							SSHKey=, 
2>  							SSHPassPhrase=,
2>  							AppName=FSRDemoApp.iOS,
2>  							ContinueOnDisconnected=False
2>  Connecting to Mac server 10.16.2.216...
2>  Executing SayHello Task to establish a connection to a Mac Server. 
2>  						 Properties: SessionId=7ca2c435a746db308125842d8b48b3c0, 
2>  							ServerPort=57187, 
2>  							ServerAddress=10.16.2.216, 
2>  							ServerUser=KostasSkoul, 
2>  							ServerPassword=, 
2>  							SSHKey=, 
2>  							SSHPassPhrase=,
2>  							AppName=FSRDemoApp.iOS,
2>  							ContinueOnDisconnected=False
2>  Connecting to Mac server 10.16.2.216...
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1225,3): warning : The file "58.png" for the image set "AppIcon" does not exist.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1225,3): warning : The file "58.png" for the image set "AppIcon" does not exist.
2>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/768x1024 (1).png" "obj/iPhone/Debug/device-builds/iphone9.3-13.0/optimized/768x1024 (1).png" 
2>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/pobuca_sales_horisontal_logo.png obj/iPhone/Debug/device-builds/iphone9.3-13.0/optimized/pobuca_sales_horisontal_logo.png 
2>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/products.png obj/iPhone/Debug/device-builds/iphone9.3-13.0/optimized/products.png 
2>  /usr/bin/plutil -convert binary1 -o obj/iPhone/Debug/device-builds/iphone9.3-13.0/optimized/Settings.bundle/Root.plist Settings.bundle/Root.plist 
2>  No way to resolve conflict between "System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Numerics, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". Choosing "System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
2>  No way to resolve conflict between "System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>  Consider app.config remapping of assembly "System.Numerics, Culture=neutral, PublicKeyToken=b77a5c561934e089" from Version "2.0.5.0" [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\System.Numerics.dll] to Version "4.0.0.0" [C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll] to solve conflict and get rid of warning.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
2>C:\Users\p.sarantakos\source\repos\PobucaSales_Xamarin\FSRDemoApp\FSRDemoApp.iOS\Controls\CustomEntryRenderer .cs(18,21,18,34): warning CS0169: The field 'CustomEntryRenderer.vUpdatedEntry' is never used
2>C:\Users\p.sarantakos\source\repos\PobucaSales_Xamarin\FSRDemoApp\FSRDemoApp.iOS\Controls\CustomEntryRenderer .cs(17,18,17,28): warning CS0169: The field 'CustomEntryRenderer.buttonRect' is never used
2>  FSRDemoApp.iOS -> C:\Users\p.sarantakos\source\repos\PobucaSales_Xamarin\FSRDemoApp\FSRDemoApp.iOS\bin\iPhone\Debug\FSRDemoApp.iOS.exe
2>  Detected signing identity:
2>    Code Signing Key: "iPhone Developer: Petros Sarantakos (K646ZW5U34)" (AF140A4CC1AE50BAE14ED7705EACC67E65BA61D0)
2>    Provisioning Profile: "PobucaSalesDev" (25fb2ada-5596-4b58-8423-4414576690c9)
2>    Bundle Id: com.pobuca.sales
2>    App Id: FARVYQX77A.com.pobuca.sales
2>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/pobuca/Library/Caches/Xamarin/mtbs/builds/FSRDemoApp.iOS/7ca2c435a746db308125842d8b48b3c0/obj/iPhone/Debug/device-builds/iphone9.3-13.0/response-file.rsp -v -v -v -v 
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): warning MT0127: Incremental builds have been disabled because this version of Xamarin.iOS does not support incremental builds in projects that include more than one third-party binding libraries.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): warning : The runtime version supported by this application is unavailable.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error GEA45E82A: expected identifier or '{'
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(804,3): error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by rolfbjarne** [comment]
The problem is that your Mac auto-upgraded Xcode to the new Xcode 11, and our current version of Xamarin.iOS is not compatible with Xcode 11.

We'll release a version of Xamarin.iOS that is compatible with Xcode 11 later today. A more immediate solution is to install our preview version of Xamarin.iOS with support for Xcode 11.
