### ISSUE TITLE
MTOUCH : error MT4109: Failed to compile the generated registrar code. After updating XCode 11.

### ISSUE THREAD

**Issue by venkatvidyut** [xamarin/xamarin-macios#7064]
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
Build Successfully.

### Actual Behavior
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/Photos.framework/Headers/PHImageManager.h(17,47): error GEA45E82A: expected identifier or '{'

MTOUCH : error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new

### Environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.2.6 (build 26)
Installation UUID: 3ce8d037-dc25-4f2f-9289-205f0918c0d7
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000334

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.334 (2019-02/6256b82d62f) (64-bit)
	Package version: 600000334

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/admin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/admin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Community)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802060026
Git revision: a4ea4d00345f4d98a95bd2322b1d04935eb553e1
Build date: 2019-09-05 18:24:25+00
Build branch: release-8.2
Xamarin extensions: 366997b587d63360705507e281ae75025762cadf

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.HotReload 1.0.0.2910000


```

### Build Logs
Task Performance Summary:
        * ms  MSBuild                                    4 calls
        0 ms  AssignCulture                              1 calls
        0 ms  GetFrameworkPath                           1 calls
        0 ms  FindAppConfigFile                          1 calls
        0 ms  ParseExtraMtouchArgs                       1 calls
        0 ms  DetectDebugNetworkConfiguration            1 calls
        0 ms  ConvertToAbsolutePath                      1 calls
        0 ms  ResolveNonMSBuildProjectOutput             1 calls
        0 ms  GetReferenceAssemblyPaths                  1 calls
        0 ms  MakeDir                                    1 calls
        1 ms  Delete                                     2 calls
        1 ms  AssignProjectConfiguration                 1 calls
        1 ms  CollectBundleResources                     2 calls
        1 ms  CreateAssetPackManifest                    1 calls
        1 ms  FindItemWithLogicalName                    1 calls
        1 ms  ParseDeviceSpecificBuildInformation        1 calls
        1 ms  GetReferenceNearestTargetFrameworkTask     1 calls
        1 ms  ComputeBundleResourceOutputPaths           1 calls
        1 ms  Hash                                       1 calls
        1 ms  Touch                                      2 calls
        2 ms  RemoveDuplicates                           2 calls
        2 ms  Message                                    4 calls
        2 ms  AssignTargetPath                          10 calls
        3 ms  ResolvePackageFileConflicts                1 calls
        5 ms  FindUnderPath                              5 calls
       16 ms  WriteLinesToFile                           1 calls
       19 ms  CompileEntitlements                        1 calls
       20 ms  GetNativeExecutableName                    1 calls
       20 ms  ReadLinesFromFile                          1 calls
       21 ms  UnpackLibraryResources                     1 calls
       47 ms  ResolveNuGetPackageAssets                  1 calls
       55 ms  ReadItemsFromFile                          5 calls
       65 ms  Copy                                       3 calls
      243 ms  DetectSdkLocations                         1 calls
      351 ms  XamlCTask                                  1 calls
      593 ms  DetectSigningIdentity                      1 calls
      834 ms  ResolveAssemblyReference                   1 calls
     2749 ms  Csc                                        1 calls
    112776 ms  MTouch                                     1 calls
        (* = timing was not recorded because of reentrancy)

Build FAILED.

/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2126,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk/System/Library/Frameworks/Photos.framework/Headers/PHImageManager.h(17,47): error GEA45E82A: expected identifier or '{'
MTOUCH : error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
    1 Warning(s)
    2 Error(s)

Time Elapsed 00:02:00.13

========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

Build: 2 errors, 1 warning

**Comment by rolfbjarne** [comment]
The problem is that your Mac auto-upgraded Xcode to the new Xcode 11, and our current version of Xamarin.iOS is not compatible with Xcode 11.

We'll release a version of Xamarin.iOS that is compatible with Xcode 11 later today. A more immediate solution is to install our preview version of Xamarin.iOS with support for Xcode 11.

**Comment by venkatvidyut** [comment]
Thank you for your reply i will check with preview version.

**Comment by venkatvidyut** [comment]
After installing Xamarin Ios preview version also not solved my problem.

**Comment by leonvandebroek** [comment]
I can confirm the exact same problem on my iMac: using preview version does not help.
