### ISSUE TITLE
Xcode 11 FINAL Support

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/xamarin-macios#7071]
Xcode 11 Final dropped last Friday September 20th around 5 pm ET, Xamarin prepared support for it and it is due to be released later today during http://www.dotnetconf.net

# Update

Xcode 11 support is **out** to **stable** channels in both Visual Studio on Windows and macOS.

**Comment by hanseul1795** [comment]
Is there a way to use this in visual studio 2017? 
still having this issue https://github.com/xamarin/xamarin-macios/issues/7050 in vs 2017.

**Comment by Shirk** [comment]
Likewise, can't build against xcode 11 if my Windows client is VS2017. Is there any statement about the official support of this on VS != 2019?

**Comment by rolfbjarne** [comment]
> Is there any statement about the official support of this on VS != 2019

Xamarin.iOS 13 (which is the release that supports Xcode 11 and iOS 13) is only available for VS 2019.

**Comment by HappyTreesDev** [comment]
So what you are saying is VS 2017 is no longer supported for use of iOS development?

**Comment by Shirk** [comment]
Since you need Xamarin.iOS 13.x to use Xcode11 and Apple will make building agains the iOS13 SDK mandatory in early 2020 your answer is “yes”.

Even Xamarin.iOS 12.x on VS2017 is right now a few versions behind the VS2019 release already.

**Comment by HappyTreesDev** [comment]
It stinks that VS2017 has been given up on so quickly but I understand its hard to focus on supporting multiple things. Thanks for clarifying.

**Comment by dalexsoto** [comment]
Not need for this anymore, builds are released.
