### ISSUE TITLE
Broken object_getClass workaround in Xcode 11

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#7077]
Broken object_getClass: [70844a8](https://github.com/xamarin/xamarin-macios/commit/70844a81df218f9464750c6140059a9c9659ea68) ([FB6153904](https://trello.com/c/2g7qtnGO/143-fb6153904-classcopyprotocollist-crashes-in-ios-13))

    Feedback has not been answered.
    Still broken in Xcode 11 b7.

Originally in https://github.com/xamarin/xamarin-macios/issues/6212

**Comment by chamons** [comment]
FYI @rolfbjarne I made this since I closed the meta list.

**Comment by rolfbjarne** [comment]
Apple fixed the bug in iOS 13.1, but they did not fix it for the final iOS 13 release.

This means that we'll need the workaround until we drop support for iOS 13... which will take a few years, so I'm closing this.
