### ISSUE TITLE
error MT4109: Failed to compile the generated registrar code. 

### ISSUE THREAD

**Issue by zerople** [xamarin/xamarin-macios#7089]
### Steps to Reproduce
Same environment, difference link behavior.
**1. Linker Behavior : Don't Link => Build Error**
2. Linker Behavior : Link Framework SDKs Only => Success.

### Environment

1. Visual Studio 2019 Preview 1.0
2. Xamarin.Forms 4.2.0.815419 & Xamarin.Forms 4.3.0.819712-pre2 
3. SDK Version : 13.0

```
```

### Build Logs

....

17>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/iosdev/Library/Caches/Xamarin/mtbs/builds/Nz.Taycan.iOS/3b11a69b8d6b6cf0ea1b443de21d20d1/obj/iPhone/Debug/response-file.rsp 
17>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(801,3): error GEA45E82A: expected identifier or '{'
17>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(801,3): error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
========== Build: 16 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by rolfbjarne** [comment]
This is fixed in the latest stable version of Xamarin.iOS, which was released yesterday.
