### ISSUE TITLE
Error when building to iOS from Windows

### ISSUE THREAD

**Issue by marcussogeti** [xamarin/xamarin-macios#7102]
Building a Xamarin App targeting iOS and Andrioid. I'm building it on a PC with a MacBook Pro as a build server. I have no problem running in a simulator.

### Steps to Reproduce

1. Connect to mac
2. Debug > Start Debugging

### Expected Behavior
App deploys to connected iphone
### Actual Behavior
Build stops with build errors
### Environment
Windows 10, macOs 10.14.4, Xcdoe 11

```
```

### Build Logs

Severity	Code	Description	Project	File	Line	Suppression State
Error		expected identifier or '{'	UL.App.iOS	C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets	804

**Comment by rolfbjarne** [comment]
This has been fixed in the latest stable release, which came out on Monday.
