### ISSUE TITLE
[ObjectiveSharpie] Unsupported clang availability platform: 'macCatalyst' 

### ISSUE THREAD

**Issue by w1ck3l** [xamarin/xamarin-macios#7109]
### Steps to Reproduce
Terminal commnad:
sharpie bind --output=BRPtouchPrinterKit --namespace=BRPtouchPrinterKit --sdk iphoneos13.0 BRPtouchPrinter.h

### Expected Behavior
This should have built the ApiDefinition.cs and the StructsandEnums.cs files
### Actual Behavior
Gives: [ObjectiveSharpie] Unsupported clang availability platform: 'macCatalyst' 
### Environment
MacBook Pro: MacOS Mojave 10.14.6

```
=== Visual Studio Community 2019 for Mac ===

Version 8.3 (build 1805)
Installation UUID: 1d586663-f7f3-4963-805f-893b8a370d14
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000198

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
	Package version: 604000198

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12

=== Xamarin.Profiler ===

Version: 1.6.11.16
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Android ===

Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/jhess/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/jhess/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin Designer ===

Version: 16.3.0.230
Hash: bbe518670
Branch: remotes/origin/d16-3-xcode11
Build date: 2019-09-17 18:39:30 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803001805
Git revision: df50511ccb08d4d84a53939f1d7fc0b40cbb0ee1
Build date: 2019-09-20 16:10:55+00
Build branch: release-8.3
Xamarin extensions: da8d448cd65f2cc87c5e6dc7e2c2ca7b96d20c72

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64


```

### Build Logs

BICNJC02NX14UG3:headers jhess$ sharpie xcode -sdks
sdk: appletvos13.0    arch: arm64   
sdk: iphoneos13.0     arch: arm64   armv7   
sdk: driverkit19.0    arch: x86_64  i386    
sdk: macosx10.15      arch: x86_64  i386    
sdk: watchos6.0       arch: armv7k  
BICNJC02NX14UG3:headers jhess$ 

<img width="1185" alt="Screen Shot 2019-09-25 at 3 03 38 PM" src="https://user-images.githubusercontent.com/31547452/65639929-672bce00-dfa6-11e9-973b-73babbe6d67f.png">

**Comment by chamons** [comment]
Can you try with the latest build from http://aka.ms/objective-sharpie and report back. 

That works for us internally?

**Comment by w1ck3l** [comment]
You're my hero.  This did work.  I thought that I was at the most recent version.  Clearly that was not it.  Thank you very much.

**Comment by tarrball** [comment]
@chamons the package provided by you above, currently [v3.4.47](https://aka.ms/objective-sharpie), will not open for me in Catalina, I get the warning:

"objectivesharpie-3.4.47.pkg” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

**Comment by chamons** [comment]
@tarrball - You are correct. I've filed that as https://github.com/xamarin/xamarin-macios/issues/7422

However, you should be able to right click -> open and bypass the check for now.

**Comment by jingliancui** [comment]
@chamons hi, I think you should update the sharpie download link to this docs https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-sharpie/get-started
and update the update feature of the command line `sharpie update`

**Comment by dalexsoto** [comment]
Good catch, I’ll take care of docs. Thanks for the heads up, the evergreen link is http://aka.ms/objective-sharpie

**Comment by dalexsoto** [comment]
thanks for the report in the meantime please use http://aka.ms/objective-sharpie to download the latest available version

**Comment by alexsorokoletov** [comment]
> hi @dalexsoto , have you experienced on this issue?
> 
> ```
> -MacBook-Pro-2:~ nguyenhuutinh$ sharpie update
> Current version: 3.5.41
> Checking stable channel for newer version ...
> 
> Unhandled Exception:
> System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Security.Interface.TlsException: CertificateUnknown
>   at Mono.AppleTls.AppleTlsContext.EvaluateTrust () [0x000c6] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.AppleTls.AppleTlsContext.ProcessHandshake () [0x00075] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000da] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
>   at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000fc] in <18c41f10b495466c9921b9b6dccaed31>:0
>    --- End of inner exception stack trace ---
>   at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00262] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x000c3] in <06ded3dcfc81410db8be9bd115706db1>:0
>    --- End of inner exception stack trace ---
>   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x00102] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00322] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpClient.FinishGetStreamAsync (System.Threading.Tasks.Task`1[TResult] getTask) [0x0006f] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at Sharpie.UpdateTool.GetLatestReleaseAsync (System.String channel) [0x00045] in /Users/runner/work/1/s/Sharpie/UpdateTool.cs:121
>    --- End of inner exception stack trace ---
>   at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029
>   at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:496
>   at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:466
>   at Sharpie.UpdateTool.GetLatestRelease (System.String channel) [0x00001] in /Users/runner/work/1/s/Sharpie/UpdateTool.cs:115
>   at Sharpie.UpdateTool.Run () [0x00039] in /Users/runner/work/1/s/Sharpie/UpdateTool.cs:52
>   at Sharpie.Tooling.Tool.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x0011c] in /Users/runner/work/1/s/Sharpie.Core/Tooling/Tool.cs:180
>   at Sharpie.Tooling.ToolRunnerTool.Run () [0x000eb] in /Users/runner/work/1/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:95
>   at Sharpie.Tooling.Tool.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x0011c] in /Users/runner/work/1/s/Sharpie.Core/Tooling/Tool.cs:180
>   at Sharpie.Tooling.ToolRunnerTool.Run (System.Collections.Generic.IEnumerable`1[T] args, System.Action`1[T] aboutToRunToolHandler) [0x00008] in /Users/runner/work/1/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:68
>   at Sharpie.Entry.Main (System.String[] args) [0x00142] in /Users/runner/work/1/s/Sharpie/Entry.cs:89
> ---> (Inner Exception #0) System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Security.Interface.TlsException: CertificateUnknown
>   at Mono.AppleTls.AppleTlsContext.EvaluateTrust () [0x000c6] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.AppleTls.AppleTlsContext.ProcessHandshake () [0x00075] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000da] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
>   at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000fc] in <18c41f10b495466c9921b9b6dccaed31>:0
>    --- End of inner exception stack trace ---
>   at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00262] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x000c3] in <06ded3dcfc81410db8be9bd115706db1>:0
>    --- End of inner exception stack trace ---
>   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x00102] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00322] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpClient.FinishGetStreamAsync (System.Threading.Tasks.Task`1[TResult] getTask) [0x0006f] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at Sharpie.UpdateTool.GetLatestReleaseAsync (System.String channel) [0x00045] in /Users/runner/work/1/s/Sharpie/UpdateTool.cs:121 <---
> 
> [ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Security.Interface.TlsException: CertificateUnknown
>   at Mono.AppleTls.AppleTlsContext.EvaluateTrust () [0x000c6] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.AppleTls.AppleTlsContext.ProcessHandshake () [0x00075] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000da] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
>   at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000fc] in <18c41f10b495466c9921b9b6dccaed31>:0
>    --- End of inner exception stack trace ---
>   at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00262] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x000c3] in <06ded3dcfc81410db8be9bd115706db1>:0
>    --- End of inner exception stack trace ---
>   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x00102] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00322] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpClient.FinishGetStreamAsync (System.Threading.Tasks.Task`1[TResult] getTask) [0x0006f] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at Sharpie.UpdateTool.GetLatestReleaseAsync (System.String channel) [0x00045] in /Users/runner/work/1/s/Sharpie/UpdateTool.cs:121
>    --- End of inner exception stack trace ---
>   at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029
>   at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:496
>   at System.Threading.Tasks.Task`1[TResult].get_Result () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:466
>   at Sharpie.UpdateTool.GetLatestRelease (System.String channel) [0x00001] in /Users/runner/work/1/s/Sharpie/UpdateTool.cs:115
>   at Sharpie.UpdateTool.Run () [0x00039] in /Users/runner/work/1/s/Sharpie/UpdateTool.cs:52
>   at Sharpie.Tooling.Tool.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x0011c] in /Users/runner/work/1/s/Sharpie.Core/Tooling/Tool.cs:180
>   at Sharpie.Tooling.ToolRunnerTool.Run () [0x000eb] in /Users/runner/work/1/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:95
>   at Sharpie.Tooling.Tool.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x0011c] in /Users/runner/work/1/s/Sharpie.Core/Tooling/Tool.cs:180
>   at Sharpie.Tooling.ToolRunnerTool.Run (System.Collections.Generic.IEnumerable`1[T] args, System.Action`1[T] aboutToRunToolHandler) [0x00008] in /Users/runner/work/1/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:68
>   at Sharpie.Entry.Main (System.String[] args) [0x00142] in /Users/runner/work/1/s/Sharpie/Entry.cs:89
> ---> (Inner Exception #0) System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Security.Interface.TlsException: CertificateUnknown
>   at Mono.AppleTls.AppleTlsContext.EvaluateTrust () [0x000c6] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.AppleTls.AppleTlsContext.ProcessHandshake () [0x00075] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake (Mono.Net.Security.AsyncOperationStatus status, System.Boolean renegotiate) [0x000da] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at (wrapper remoting-invoke-with-check) Mono.Net.Security.MobileAuthenticatedStream.ProcessHandshake(Mono.Net.Security.AsyncOperationStatus,bool)
>   at Mono.Net.Security.AsyncHandshakeRequest.Run (Mono.Net.Security.AsyncOperationStatus status) [0x00006] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000fc] in <18c41f10b495466c9921b9b6dccaed31>:0
>    --- End of inner exception stack trace ---
>   at Mono.Net.Security.MobileAuthenticatedStream.ProcessAuthentication (System.Boolean runSynchronously, Mono.Net.Security.MonoSslAuthenticationOptions options, System.Threading.CancellationToken cancellationToken) [0x00262] in <18c41f10b495466c9921b9b6dccaed31>:0
>   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x000c3] in <06ded3dcfc81410db8be9bd115706db1>:0
>    --- End of inner exception stack trace ---
>   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore (System.IO.Stream stream, System.Net.Security.SslClientAuthenticationOptions sslOptions, System.Threading.CancellationToken cancellationToken) [0x00102] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x00322] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync (System.Threading.Tasks.ValueTask`1[TResult] creationTask) [0x000a2] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken) [0x00089] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x000ba] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at System.Net.Http.HttpClient.FinishGetStreamAsync (System.Threading.Tasks.Task`1[TResult] getTask) [0x0006f] in <06ded3dcfc81410db8be9bd115706db1>:0
>   at Sharpie.UpdateTool.GetLatestReleaseAsync (System.String channel) [0x00045] in /Users/runner/work/1/s/Sharpie/UpdateTool.cs:121 <---
> ```

I get the exactly same result calling `sharpie update` with 3.5.45.
