### ISSUE TITLE
iPhone Simulator always remains black

### ISSUE THREAD

**Issue by RidaNoor** [xamarin/xamarin-macios#7122]
Hi,

I am developing a Xamarin.Forms application. I try to run it on iPhone Simulator , build is successful but the simulator always remain black and in Visual Studio, its always "Lauching the app on iPhone Xs 12.0 "...
I am using Visual Studio 2019. And I am using MVVMCross in the App.
Any quick help will be really appreciated.

> VS bug [#991522](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/991522)

**Comment by chamons** [comment]
Thank you for your feedback!

I've moved it to the correct teham.

For us to investigate this further, could you please provide your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by attrib75** [comment]
I have this same issue ever since the latest update on MAC to 13.0

**Comment by chamons** [comment]
As I noted above, we need logs, in particular IDE logs to make any progress on this:

https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/version-logs#windows-logs

**Comment by attrib75** [comment]
This was solved for me after upgrading Visual Studio to 16.3.2 thanks

**Comment by chamons** [comment]
Thanks for the update. Please feel free to reopen (or open another bug) as necessary.

**Comment by attrib75** [comment]
Ok no problem.  It was solved for me, though I don't know about the original poster

**Comment by SoledadIce** [comment]
Have this issue again, for iOS 13.2, VS 2019: 16.3.8
