### ISSUE TITLE
Visual Studio 2019 and Xamarin.iOS: Warning MSB3341: Could not resolve reference "libMicrosoft.CognitiveServices.Speech.core.a", however build works ok.

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#7133]
Steps to reproduce:

Using Visual Studio 2019, version 16.2.4

1. Build following quick start using Microsoft Cognitive Services Speech SDK on Xamarin iOS
 https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp-xamarin

Expected output:

    No warnings

Actual output:

```
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2006,5): warning MSB3341: Could not resolve reference "C:\Users\VssAdministrator\.nuget\packages\microsoft.cognitiveservices.speech\1.7.0\build\Xamarin.iOS\\libMicrosoft.CognitiveServices.Speech.core.a". If this reference is required by your code, you may get compilation errors. [D:\a\1\s\quickstart\csharp-xamarin\helloworld\helloworld.iOS\helloworld.iOS.csproj]
```

Build still works OK in both iPhone and iPhoneSimulator, so static library is being built to the application.

Could you help me to figure out why this warning happens and for solution ? 

Could this be due to how Microsoft.CognitiveServices.Speech nuget targets the libMicrosoft.CognitiveServices.Speech.core.a binary ?

Microsoft.CognitiveServices.Speech nuget contains following target file for Xamarin.iOS, which you can find under .nuget\packages\microsoft.cognitiveservices.speech\1.7.0\build\Xamarin.iOS folder.
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>​
    <NativeReference Include="$(MSBuildThisFileDirectory)\libMicrosoft.CognitiveServices.Speech.core.a">​
      <Kind>Static</Kind>​
      <ForceLoad>True</ForceLoad>​
      <IsCxx>True</IsCxx>​
      <Frameworks>AudioToolbox</Frameworks>​
    </NativeReference>​
  </ItemGroup>​
</Project>
```

Originally: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/988986

**Comment by chamons** [comment]
So this is due to a conflict between Xamarin.iOS's NativeReference and the general one listed here:

https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019#nativereference

Unfortunately, there isn't an obvious fix, we can't change the property without breaking lots of projects.

You could disable that specific warning using NoWarn in your nuget msbuild logic if desired.

**Comment by anders9ustafsson** [comment]
> You could disable that specific warning using NoWarn in your nuget msbuild logic if desired.

@chamons Do you have a working example of this? If I simply put the specific warning inside `<NoWarn>` in the project file, it has no effect. Where more exactly should I place the `NoWarn` element?

**Comment by chamons** [comment]
NoWarn should do the right thing, I assume. Make sure you have it in the right section.

Something like: 
    <NoWarn>3341</NoWarn>

If that doesn't work, feel free to attach a project and full build log, and i'll take a look.

**Comment by anders9ustafsson** [comment]
As far as I know, MSB-type warnings are ignored by `<NoWarn/>`. I have tested, using both code 3341 and MSB3341 in the `<NoWarn>` line, but warnings are still displayed. Not entirely related, but further discussion can be found [here](https://stackoverflow.com/a/37770210/650012).

**Comment by chamons** [comment]
Interesting - that is something I did not know about MSB warnings.
