### ISSUE TITLE
DirectoryInfo.GetFiles (System.String searchPattern, System.IO.SearchOption searchOption) crashes

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#7159]
### Steps to Reproduce

I use this line of code: 
`var files = DirectoryInfo.GetFiles ("*.*", System.IO.SearchOption.AllDirectories);`

For one user (who seems to have a lot of files created inside), this crashes with SIGABRT: Operation not permitted, and from the stacktrace you can see that the bug is coming from Xamarin code, not from my code, here it is:
 
    FileSystemEnumerator`1[TResult].CreateDirectoryHandle (System.String path, System.Boolean ignoreNotFound)
    FileSystemEnumerator`1[TResult].DequeueNextDirectory ()
    FileSystemEnumerator`1[TResult].DirectoryFinished ()
    FileSystemEnumerator`1[TResult].FindNextEntry (System.Byte* entryBufferPtr, System.Int32 bufferLength)
    FileSystemEnumerator`1[TResult].MoveNext ()
    LargeArrayBuilder`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] items)
    EnumerableHelpers.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source)
    MonoLinqHelper.ToArray[T] (System.Collections.Generic.IEnumerable`1[T] source)
    DirectoryInfo.GetFiles (System.String searchPattern, System.IO.EnumerationOptions enumerationOptions)
    DirectoryInfo.GetFiles (System.String searchPattern, System.IO.SearchOption searchOption)
    SettingsController+<>c__DisplayClass2_0.<ViewDidLoad>b__5 ()
    UIGestureRecognizer+ParameterlessDispatch.Activated ()
    (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
    UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
    UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
    Application.Main (System.String[] args)

### Expected Behavior
It should work, if there is some problem it should raise an exception, not to crash inside the method
### Actual Behavior
It crashes inside the method while trying to enumerate subdirectories
### Environment

```
Microsoft Visual Studio Community 2019
Version 16.2.5
VisualStudio.16.Release/16.2.5+29306.81
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA588
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00611.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.2.292.25104
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.2.292.25104
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.2.292.25104
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.2.292.25104
Azure Functions and Web Jobs Tools

C# Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (master@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20626.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.2.6 (4cfc7c3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10627.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.2.1-beta4-19408-03+2fc6a04980f800c59e8ede97e6ae294ff47d666e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.2.0-beta.19321.1+a24d94ecf97d0d69d4fbe6b8b10cd1f97737fff4
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.2.0.149 (d16-2-xcode11@c5da8fd8b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.118 (c29ca2a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.1.1 (d16-2/cec9eb4)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969


Xamarin.iOS and Xamarin.Mac SDK   12.99.2.40 (d883feb)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by Therzok** [comment]
Looks like the same issue we had in vsmac:
https://github.com/mono/mono/issues/15738

**Comment by ivanicin** [comment]
According to this: https://github.com/dotnet/corefx/issues/39768#issuecomment-515169831 , this could be avoided if the method used Directory.GetDirectories instead of Directory.EnumerateDirectories. As this method is clearly labeled as 'Get' and not 'Enumerate', this needs to be changed accordingly.

**Comment by chamons** [comment]
This issue was moved to mono/mono#17171

**Comment by chamons** [comment]
Thanks for the report. I've moved this to the runtime team (mono) for investigation.

**Comment by chamons** [comment]
For anyone not tracking the mono/mono issue, here is the final result:

> To clarify - This turns out to not be a bug but mis-use of the API in question.
> 
> Here's the text from the linked corefx bug comment which can explain it better than I can:
> EnumerateDirectories needs to open a handle and keep it open while enumerating; the alternative would be to open the handle, cache everything into a data structure, close the handle, and then return the data structure. But that's exactly what GetDirectories does, and EnumerateDirectories was introduced later specifically to avoid these overheads.
> 
> If a developer actually wants the caching behavior, they can use GetDirectories (or use ToArray). If a developer wants the recursive behavior, they can specify so with SearchOption and let the implementation handle everything. If the developer is explicitly calling other things while holding open the handle, well, that's what they get.
