### ISSUE TITLE
SocketException in tcpClient.connectAync could not be caught in try-catch

### ISSUE THREAD

**Issue by ideveloperaz** [xamarin/xamarin-macios#7182]
After last update of XCode and VS - SocketException in tcpClient.connectAync could not be caught in try-catch

### Steps to Reproduce

this is for iOS only

1. turn off all networking (wifi, mobile data etc)
2. open app that uses TcpClient.ConnectAsync wrapped in try-catch block
3. raised SocketException could not be caught by try-catch block

### Expected Behavior
catch block should catch SocketException
 
### Actual Behavior
SocketException is not caught in try-catch block

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.3.1 (build 18)
Installation UUID: f3992657-2718-41e7-955c-06f496e0aa5a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000198

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.198 (2019-06/fe64a4765e6) (64-bit)
	Package version: 604000198

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Version: 6.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin.iOS ===

Version: 13.2.0.42 (Visual Studio Community)
Hash: 5e8a208b
Branch: d16-3
Build date: 2019-09-17 14:19:30-0400

=== Xamarin Designer ===

Version: 16.3.0.244
Hash: e15b2ee97
Branch: remotes/origin/d16-3
Build date: 2019-09-25 00:03:16 UTC

=== Xamarin.Android ===

Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/rufat/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@7af64d1ebe9
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/rufat/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803010018
Git revision: 272ab73f00ab2b13ec97dc8b31d02980cf66d47f
Build date: 2019-09-27 19:26:51+00
Build branch: release-8.3
Xamarin extensions: 451b00e65052c11c16b79e6d31a24c4cf0d1b794

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64


```

**Comment by mandel-macaque** [comment]
@ideveloperaz can you please provide a sample. The socket class is part of the BCL and we might need to report the issue to mono but first I'd like to take a closer look. 

Thanks! 

(I request the sample, because while it seems to be a simple sample, I prefer to be explicit, you never know :) )

**Comment by ideveloperaz** [comment]
Hi @mandel-macaque  it is as simple as this one:
Catch block could not  catch SocketException here if all wifi and mobile data turned off.
I have updates yesterday to the latest big update at VS but it is sill the same. Before that two last VS updates catch block could catch SocketException. 

            Task.Run(async () =>
            {
                try
                {
                    var _tcpClient = new TcpClient();

                    await _tcpClient.ConnectAsync(<any host>, <any port>);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);
                }
            });

**Comment by ideveloperaz** [comment]
this is regarding tcpClient.ConnectAsync ... 

only tcpclient.BeginConnect works here and could catch SocketException in the same scenario

**Comment by ideveloperaz** [comment]
I susspect that ConnectAsync here not returning task thats why it could not be awaited and SocketException happens outside of context thus could not be caught.

**Comment by mandel-macaque** [comment]
Sorry for the delay, got caught in Xcode11 release, will take a look at it ASAP.

**Comment by mandel-macaque** [comment]
Hello,

I have tested the above code trying to connect with a localhost that refused connections (to make sure we did get an exception) and the code works as expected. This was tested with the[ following environment](https://gist.github.com/mandel-macaque/87c29cd8cae68676f2918095345ef015). 

I am going to close the issue since it is fixed in master. Please, if you don't think this is correct, reopen the issue and provide all the required environment information. We need the Xamarin.iOS version which you are running.
