### ISSUE TITLE
Xamarin.IOS version mismatch Latest VS Mac (13.2.0.47) & Latest VS 2019 Windows (13.2.0.42)

### ISSUE THREAD

**Issue by mbullock976** [xamarin/xamarin-macios#7191]
Hi

My Visual Studio for Mac was updated to now use Xamarin.IOS 13.2.0.47, however the latest Visual Studio 2019 for Windows 16.3.1 which was released today only supports 13.2.0.42. 

This means I cannot upgrade windows to .47 and don't know how or if I should downgrade Mac to .42

If I try and pair to Mac from windows VS 2019, I get a versions mismatch which tries to install .42 over the .47 on my Mac but it fails to install without a reason.

Please help

Thank you

**Comment by mbullock976** [comment]
Hi

Ratherthan waiting to Microsoft to release a new update to VS 2019 for windows that supports Xamarin.ios 13.2.0.47

I instead downgrade my Mac from 13.2.0.47 to 13.2.0.42 by downloading the pkg file on my Mac and installing it. Now my VS Mac is showing Xamarin.IOS 13.2.0.42 and I'm able to pair to mimic again from windows

**Comment by bnserig** [comment]
Why VS 2019 Windows version is not released at the same time ?

**Comment by mbullock976** [comment]
I have no idea why. Microsoft released new update for VS 2019 today v16.3.1 but this does not support the latest xamarin iOS release

I could wait for Microsoft to release the compatible version but instead chose to downgrade my Mac

I’ve switched off auto check updates in my visual studio for Mac now

**Comment by dalexsoto** [comment]
Hello @bnserig and @mbullock976 👋 

Sorry for the trouble, VS Windows should now have the same version as VSMac.

**Comment by biapar** [comment]
The problem happened again.

**Comment by CMD73** [comment]
You can download the exact matching version on the Mac and install manually, as per this older post: https://stackoverflow.com/questions/41991122/xamarin-studio-for-mac-standalone-xamarin-ios-installer

https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-13.10.0.17.pkg

This seemed to work for me, and I was able to pair the Mac in VS2019.
