### ISSUE TITLE
error GF203180B: redefinition of 'UIImageOrientation' xamarin forms

### ISSUE THREAD

**Issue by ZeyadZarzour** [xamarin/xamarin-macios#7199]
### Expected Behavior
my code is running without error on xamarin Andriod, but when i running it on xamarin iOS is failed!
i use Xam.plugin.Media to take a photo is that why the error happened on new Xcode?

### Environment
i use VS2019 on windows 10
vs19 on mac
xcode 11.2 beta
Xamarin.iOS 6.3 (build 864)

```
1>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/ziadzarzour/Library/Caches/Xamarin/mtbs/builds/ParkingManager.iOS/ca6beb9b5e64df983a6c3e2d5c77b568/obj/iPhone/Debug/device-builds/iphone9.3-13.1.2/response-file.rsp 
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error GF203180B: redefinition of 'UIImageOrientation'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
```
### Example Project (If Possible)
        async System.Threading.Tasks.Task cameraButten_ClickedAsync()
        {
            await CrossMedia.Current.Initialize();

            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                DependencyService.Get<IMessage>().LongAlert("No camera available!");
                return;
            }

            var file = await CrossMedia.Current.TakePhotoAsync(new 
            Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                Directory = "Test",
                SaveToAlbum = true,
                CompressionQuality = 75,
                CustomPhotoSize = 50,
                PhotoSize = PhotoSize.MaxWidthHeight,
                MaxWidthHeight = 500,
                DefaultCamera = CameraDevice.Rear,
                AllowCropping = true
            });

            if (file == null)
                return;

            byte[] cropedBytes = await CrossXMethod.Current.CropImageFromOriginalToBytes(file.Path);

           

            if (cropedBytes != null)
            {
                PhotoSource = ImageSource.FromStream(() =>
                {
                    var cropedImage = new MemoryStream(cropedBytes);
                    file.Dispose();
                    return cropedImage;
                });
            }
            else
            {
                file.Dispose();
            }
        }

**Comment by ZeyadZarzour** [comment]
the problem solved when i use Xcode 11.1 stable

**Comment by mateuswolkmer** [comment]
Also happening for me using Xcode 11.1 stable. Can't deploy my app because of this bug.

**Comment by atrodriguez88** [comment]
This Bug continue. I'm Xcode 11.1 stable. Just install the plugin and create a attribute
private MediaFile file;
**Build failed**
[https://github.com/jamesmontemagno/MediaPlugin/issues/763](url)

**Comment by mateuswolkmer** [comment]
For anyone that encouters this, it was happening for me in Xcode 11.1 stable because of a change I made to a Xcode file (`HeadersPHImageManager.h`) to solve another issue in previous versions. Its explained in https://github.com/xamarin/xamarin-macios/issues/6716#issuecomment-543212190.
