### ISSUE TITLE
Map Foundation.NSBackgroundActivityScheduler API

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#7224]
Currently `Foundation.NSBackgroundActivityScheduler` API for macOS (https://developer.apple.com/documentation/foundation/nsbackgroundactivityscheduler) is not mapped.

As discussed on https://forums.xamarin.com/discussion/171116/any-plans-for-nsbackgroundactivityscheduler : 

> Just found that it is not mapped, and as I understand that macOS isn't planned to be 100% covered, just wanted to suggest that at least for me this feels pretty essential to be mapped.
> 
> Are there any chance for that? This would be needed for example for the background fetch which is possible on iOS so it feels a bit odd that macOS is less supported than iOS, though I understand it is not completely directly comparable.

**Comment by whitneyschmidt** [comment]
@ivanicin Thank you for filing this issue! As Chris said, this is a reasonable enhancement request.

We've marked it for future work. You can follow progress on this issue thread. However, this does not necessarily mean we will take action on it immediately.

**Comment by tipa** [comment]
Is there any timeline when this new bindings will make it to the stable version of Xamarin.MacOS?
