### ISSUE TITLE
LibVLCSharp.Shared issue on real apple TV device.

### ISSUE THREAD

**Issue by ayasoftware** [xamarin/xamarin-macios#7228]
UNABLE TO TEST ON REAL DEVICE - works fine when i test my code on Simulator. 
if I use:

using LibVLCSharp.Shared;
using MediaPlayera = LibVLCSharp.Shared.MediaPlayer;

I got this: 

/Users/mylaptop/Projects/xamarin/xamarin/MTOUCH: Error MT5216: Native linking failed for '/Users/mylaptop/Projects/xamarin/xamarin/obj/iPhone/Debug/device-builds/appletv5.3-13.0/mtouch-cache/arm64/libLibVLCSharp.dll.dylib'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new (MT5216) (xamarin)

I have this in packages.conf

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="LibVLCSharp" version="3.2.3" targetFramework="xamarintvos10" />
  <package id="Newtonsoft.Json" version="12.0.2" targetFramework="xamarintvos10" />
  <package id="VideoLAN.LibVLC.tvOS" version="3.2.0.1" targetFramework="xamarintvos10" />
</packages>

**Comment by whitneyschmidt** [comment]
@ayasoftware Thank you for your feedback!

Could you attach your solution files (for reproducing the issue) as well as logs and version info?

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by ayasoftware** [comment]
=== Visual Studio Community 2019 for Mac ===

Version 8.3.3 (build 8)
Installation UUID: 91ff2833-9db4-4ed8-ac06-307bda4be1ea
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.504
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.8

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.0.3.0 (Visual Studio Community)
Commit: xamarin-android/d16-3/4d45b41
Android SDK: /Users/ayasoftware/Library/Android/sdk
	Supported Android versions:
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@5608fe0abb3
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/ayasoftware/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:20 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:44 UTC

=== Apple Developer Tools ===

Xcode 11.1 (15405)
Build 11A1027

=== Xamarin.Mac ===

Version: 6.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin.iOS ===

Version: 13.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin Designer ===

Version: 16.3.0.247
Hash: 52eac1a9e
Branch: remotes/origin/d16-3
Build date: 2019-10-03 23:04:28 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803030008
Git revision: fb0d3af49f0ea88661a4f469b9dfd1018dc099cd
Build date: 2019-10-10 10:53:35+00
Build branch: release-8.3
Xamarin extensions: 3f8e699ba26ed5f69b7a6466ba679f4a328fadb4

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.Forms HotReload extension 1.4.0

**Comment by ayasoftware** [comment]
to test it,  create a simple controller and debug on real apple TV (simulator works fine)

`using LibVLCSharp.Platforms.tvOS;
using LibVLCSharp.Shared;
using System;
using UIKit;

namespace xamarin
{
    public partial class InfoViewController : UIViewController
    {
        public InfoViewController (IntPtr handle) : base (handle)
        {
        }
        

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.
            VideoView _videoView;
            LibVLC _libVLC;
            LibVLCSharp.Shared.MediaPlayer _mediaPlayer;


            _libVLC = new LibVLC();
            _mediaPlayer = new LibVLCSharp.Shared.MediaPlayer(_libVLC);

            _videoView = new VideoView { MediaPlayer = _mediaPlayer };

            View = _videoView;

            _videoView.MediaPlayer.Play(new Media(_libVLC, "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", FromType.FromLocation));

        }
    }
}`

**Comment by ayasoftware** [comment]
application output

Loaded assembly: /Users/ayasoftware/Library/Developer/CoreSimulator/Devices/84E2234B-2686-4219-8BD4-18C319FBAD08/data/Containers/Bundle/Application/808A889D-6A13-4F98-B9AC-FD0A17884AF9/xamarin.app/Xamarin.TVOS.dll [External]
Loaded assembly: /Users/ayasoftware/Library/Developer/CoreSimulator/Devices/84E2234B-2686-4219-8BD4-18C319FBAD08/data/Containers/Bundle/Application/808A889D-6A13-4F98-B9AC-FD0A17884AF9/xamarin.app/System.dll [External]
Loaded assembly: /Users/ayasoftware/Library/Developer/CoreSimulator/Devices/84E2234B-2686-4219-8BD4-18C319FBAD08/data/Containers/Bundle/Application/808A889D-6A13-4F98-B9AC-FD0A17884AF9/xamarin.app/Mono.Security.dll [External]
Loaded assembly: /Users/ayasoftware/Library/Developer/CoreSimulator/Devices/84E2234B-2686-4219-8BD4-18C319FBAD08/data/Containers/Bundle/Application/808A889D-6A13-4F98-B9AC-FD0A17884AF9/xamarin.app/xamarin.exe
Loaded assembly: /Users/ayasoftware/Library/Developer/CoreSimulator/Devices/84E2234B-2686-4219-8BD4-18C319FBAD08/data/Containers/Bundle/Application/808A889D-6A13-4F98-B9AC-FD0A17884AF9/xamarin.app/System.Xml.dll [External]
Loaded assembly: /Users/ayasoftware/Library/Developer/CoreSimulator/Devices/84E2234B-2686-4219-8BD4-18C319FBAD08/data/Containers/Bundle/Application/808A889D-6A13-4F98-B9AC-FD0A17884AF9/xamarin.app/System.Numerics.dll [External]
Loaded assembly: /Users/ayasoftware/Library/Developer/CoreSimulator/Devices/84E2234B-2686-4219-8BD4-18C319FBAD08/data/Containers/Bundle/Application/808A889D-6A13-4F98-B9AC-FD0A17884AF9/xamarin.app/System.Core.dll [External]
Loaded assembly: /Users/ayasoftware/Library/Developer/CoreSimulator/Devices/84E2234B-2686-4219-8BD4-18C319FBAD08/data/Containers/Bundle/Application/808A889D-6A13-4F98-B9AC-FD0A17884AF9/xamarin.app/LibVLCSharp.dll [External]
2019-10-17 11:23:33.242374-0400 xamarin[2976:885521] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=2976
2019-10-17 11:23:33.242968-0400 xamarin[2976:885521] SecTaskCopyDebugDescription: xamarin[2976]/0#-1 LF=0
2019-10-17 11:23:33.262305-0400 xamarin[2976:885521] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=2976
2019-10-17 11:23:33.262788-0400 xamarin[2976:885521] SecTaskCopyDebugDescription: xamarin[2976]/0#-1 LF=0
2019-10-17 11:23:37.594719-0400 xamarin[2976:885521] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000016cd1c0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2019-10-17 11:23:38.073454-0400 xamarin[2976:885645] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=2976
2019-10-17 11:23:38.073643-0400 xamarin[2976:885645] SecTaskCopyDebugDescription: xamarin[2976]/0#-1 LF=0
2019-10-17 11:23:38.078537-0400 xamarin[2976:885645] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=2976
2019-10-17 11:23:38.078703-0400 xamarin[2976:885645] SecTaskCopyDebugDescription: xamarin[2976]/0#-1 LF=0
2019-10-17 11:23:38.080200-0400 xamarin[2976:885525] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=2976
2019-10-17 11:23:38.080349-0400 xamarin[2976:885525] SecTaskCopyDebugDescription: xamarin[2976]/0#-1 LF=0

**Comment by ayasoftware** [comment]
Fixed by turning "enable incremental builds" off.
