### ISSUE TITLE
INStartCallIntent not bound

### ISSUE THREAD

**Issue by Adam-Langley** [xamarin/xamarin-macios#7272]
Overview.
It appears that the SiriKit API has not been fully bound/mapped. This is a problem for apps implementing CallKit.
Launching a CallKit VOIP app by means of "calling" a Contact from Apple Address Book, prior to iOS 13 used to pass a user activity intent of "StartAudioCall".
Since iOS 13, this now piggy backs on SiriKit, and instead passes "StartCall".
Because "StartCall" is not yet implemented in Xamarin - there is now no way for a CallKit app to respond user clicks on telephone numbers in the Contacts app, or telephone Recents list.
Because this used to work, it is a functional regression.

### Steps to Reproduce

1. Implement ContinueUserActivity on iOS application (AppDelegate)
2. Attempt to reference enum class "INIntentIdentifier.StartCall"

### Expected Behavior
member should be found, code should compile

### Actual Behavior
member does not exist.
At runtime, "userInteraction.GetInteraction().Intent" throws an exception "Cannot create an instance of Intents.INIntent because it is an abstract class"

### Environment
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.3.4 (build 8)
Installation UUID: 05db84d1-79da-4c0d-8650-8d750540201f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.2.205
	2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.2.6
	2.1.13
	2.1.12

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.1 (15405)
Build 11A1027

=== Xamarin.Mac ===

Version: 6.4.0.2 (Visual Studio Enterprise)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin.iOS ===

Version: 13.4.0.2 (Visual Studio Enterprise)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin Designer ===

Version: 16.3.0.247
Hash: 52eac1a9e
Branch: remotes/origin/d16-3
Build date: 2019-10-03 23:04:28 UTC

=== Xamarin.Android ===

Version: 10.0.3.0 (Visual Studio Enterprise)
Commit: xamarin-android/d16-3/4d45b41
Android SDK: /Users/adam.langley/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@5608fe0abb3
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/adam.langley/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:20 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:44 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803040008
Git revision: 8da5857bc3d33e5667cacaab3bd1ab55375ed3e3
Build date: 2019-10-14 18:26:13+00
Build branch: release-8.3
Xamarin extensions: 61c91e660a01512a3b8187c749fd3bccc75a2bf4

=== Operating System ===

Mac OS X 10.15.0
Darwin 19.0.0 Darwin Kernel Version 19.0.0
    Wed Sep 25 20:18:50 PDT 2019
    root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

**Comment by mandel-macaque** [comment]
Correct, adding @prmallic to take a look since it is in the TODO files.

**Comment by Adam-Langley** [comment]
Thanks @mandel-macaque.
I'd just like to reiterate that this is a regression, breaking existing CallKit apps which previously used to function in this respect - hopefully prioritising this as a 'fix' rather than an 'enhancement'?
Thanks.

**Comment by dalexsoto** [comment]
Fixed by #8025
