### ISSUE TITLE
Xcode 11.1 update automatically change my app constraints and storyboard design in visual studio for mac..

### ISSUE THREAD

**Issue by sumitkrmishra** [xamarin/xamarin-macios#7273]
Hi,
We are working on xamarin.ios native app development. My app is already published on App Store.
We got an update from apple for Xcode 11.1 and We have updated Xcode 11.1 and visual studio for Mac as well.
After update when we have open storyboard it’s showing me to open project in Xcode. So we have open my project in Xcode and Xcode update my storyboard constrains automatically and my apps design looking so bad. All controller design has been changed and looking very bad.

Can you please guide me what’s problem happened in Xcode 11.1 with visual studio and how to solve it now or future update.

Why design constraints working good in previous Xcode 10 version and What is wrong in current 11.1 update. We are using visual studio for mac to develop design and code. is Any bug in visual studio?

> VS bug [#1029061](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1029061)

**Comment by mandel-macaque** [comment]
@sumitkrmishra unfortunately there is nothing we can do to avoid the Apple developer tools from changing the storyboards when they are opened. The Apple tools are not something we have control over and this looks more like an issue you should be reporting to Apple.

Before I close the issue, can you confirm me that I understood correctly, and that the file was changed by Xcode and not the VSMac designer?

**Comment by sumitkrmishra** [comment]
Hi @mandel-macaque ,
I understand your point but can you please tell me why visual studio is showing “open storyboard in Xcode interface builder” most of time and after Xcode update you must have to open project in Xcode. It seems like both VS and Xcode not synchronising properly. There is something mismatch in designer tools in visual studio from Xcode. So that  Xcode changed it accordingly.

**Comment by chkn** [comment]
@sumitkrmishra Note that Visual Studio for Mac 8.3.3 is the first stable release to support Xcode 11.1 with the integrated designer. If you were using an older release, that could be why you were seeing the prompt to open your storyboard in Xcode. Also, the integrated designer does not currently support watchOS storyboards with Xcode 11 or newer.

If you have updated to the latest stable Visual Studio for Mac release and are still seeing this issue with storyboards other than watchOS, it would be very helpful if you could share the latest `iOSDesigner` log file that can be found by choosing Help -> Open Log Directory. Thanks!
