### ISSUE TITLE
UIElements becomes inactive when RootViewController is set from SceneDelegate.cs on iOS 13.1 update

### ISSUE THREAD

**Issue by theuchenna** [xamarin/xamarin-macios#7289]
### Steps to Reproduce

1. Have at least two ViewControllers in your Main.StoryBoard
2. Write the Code to set RootViewController

`UIWindowScene windowScene = new UIWindowScene(session, connectionOptions);
            Window = new UIWindow(windowScene);
            var storyboard = UIStoryboard.FromName("Main", null);

            var registerController = storyboard.InstantiateViewController("LoginViewController") as LoginViewController;
            Window.RootViewController = registerController;
            Window?.MakeKeyAndVisible();
            Window.MakeKeyWindow();
            this.SetWindow(Window);`

### Expected Behavior
UIElements are inactive. UITextfields, for instance, will not receive inputs when the app loads up.

### Environment

```=== Visual Studio Community 2019 for Mac ===

Version 8.3.4 (build 8)
Installation UUID: 3e49c496-feff-4454-a223-5d6b49516a43
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.2
	2.1.1

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.1 (15405)
Build 11A1027

=== Xamarin.Mac ===

Version: 6.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin.iOS ===

Version: 13.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin Designer ===

Version: 16.3.0.247
Hash: 52eac1a9e
Branch: remotes/origin/d16-3
Build date: 2019-10-03 23:04:28 UTC

=== Xamarin.Android ===

Version: 10.0.3.0 (Visual Studio Community)
Commit: xamarin-android/d16-3/4d45b41
Android SDK: /Users/elatechlimited/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-06@5608fe0abb3
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/elatechlimited/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:20 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:44 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803040008
Git revision: 8da5857bc3d33e5667cacaab3bd1ab55375ed3e3
Build date: 2019-10-14 18:26:13+00
Build branch: release-8.3
Xamarin extensions: 61c91e660a01512a3b8187c749fd3bccc75a2bf4

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64


```

**Comment by whitneyschmidt** [comment]
@theuchenna Thank you for your feedback!

Could you please detail how this behavior was different before version 13.1? 

Additionally, could you attach your solution file so that we can try and reproduce this issue?

**Comment by spouliot** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Comment by theuchenna** [comment]
> @theuchenna Thank you for your feedback!
> 
> Could you please detail how this behavior was different before version 13.1?
> 
> Additionally, could you attach your solution file so that we can try and reproduce this issue?

Before the advent of iOS13, you can easily set any of the ViewController as your RootViewController
by writing the following code  in your AppDelegate.cs file

` Window = new UIWindow(UIScreen.MainScreen.Bounds);
            var storyBoard = UIStoryboard.FromName("Main", null);
            var mainViewController = storyBoard.InstantiateViewController("MainViewController") as MainViewController;
            this.SetWindow(Window);
            Window.RootViewController = mainViewController;`

Every works properly without any problems.

For iOS 13;
One can set the RootViewController of a window in the SceneDelegate.cs file. I used the following code to set the RootViewController of my window.

`  UIWindowScene WindowScene = new UIWindowScene(session, connectionOptions);
            Window = new UIWindow(WindowScene);
            var storyboard = UIStoryboard.FromName("Main", null);

            var mainViewController = storyboard.InstantiateViewController("MainViewController") as MainViewController;
            Window.RootViewController = mainViewController;
            Window?.MakeKeyAndVisible();
            this.SetWindow(Window);`

After loading up my RootViewController using this method, I discovered that I can't make input into any text field.

**Comment by whitneyschmidt** [comment]
@theuchenna - thank you for providing us with more steps to reproduce this issue.

I tried to reproduce this issue, but I wasn't sure what template you were using and couldn't get any code running.

**_Could you attach a small sample solution? This is the best way for us to reproduce the issue and investigate it._**

**Comment by rahulbansal1991** [comment]
I found a solution of this problem. Instead of creating a new `UIWindow` object, use the existing one provided by `SceneDelegate`

Adding below code snipped in the `SceneDelegate` works for me,
`var storyboard = UIStoryboard.FromName("Main", null);`
`var mainViewController = storyboard.InstantiateViewController("ViewController") as ViewController;`
`Window.RootViewController = mainViewController;`
`Window?.MakeKeyAndVisible();`
