### ISSUE TITLE
New AVMetadataObject types not handled

### ISSUE THREAD

**Issue by jmattia** [xamarin/xamarin-macios#7291]
Looks like iOS 13 introduced new AVMetadataObject types that are not handled in the following object's methods.

https://github.com/xamarin/xamarin-macios/blob/master/src/AVFoundation/AVMetadataObject.cs

New types (last 3) - https://developer.apple.com/documentation/avfoundation/avmetadataobject/objecttype

**Comment by whitneyschmidt** [comment]
@jmattia Thank you for your feedback!

This is a bug in our code, we should have support for `CatBody`, `DogBody`, `HumanBody`, and `SalientObject`. I've marked it as such :)

**Comment by whitneyschmidt** [comment]
@jmattia I merged a fix for this issue! It will be available in Xamarin's d16-3 release.

**Comment by jmattia** [comment]
@whitneyschmidt Thanks!
