### ISSUE TITLE
[Bug] iPhone app crashes when launching camera / gallery in iOS 13.2 beta 3

### ISSUE THREAD

**Issue by Gowthamk10** [xamarin/xamarin-macios#7300]
# # Description 
iPhone app crashes when launching camera / gallery in iOS 13.2 beta 3, no issue observer with lower versions like 13.1.2 / 13.1.3/ 12 

### Expected Behavior
Camera should open to capture the image
### Actual Behavior
App crashing 
### Basic Information

- Version with issue: iOS 13.2 beta 3
- Last known good version: iOS 13.1.3
- IDE: Visual Studio 2017 version 15.9.16 and Xamarin 4.12.3.83
- Platform Target Frameworks:  .NET Framework 4.8.03761
  - iOS:  Xamarin.iOS and Xamarin.Mac SDK 12.4.0.64
  - Android:  
  - UWP:   
- Android Support Library Version:

**Comment by whitneyschmidt** [comment]
@Gowthamk10 +1 to Sam, if you are able to upload a solution file that demonstrates this problem we can try to reproduce and investigate :)

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

**Comment by PetrosSarantakos** [comment]
Having the same issue while trying to access gallery images through application, using PHImageManager, used to work in previous versions.

**Comment by spouliot** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
