### ISSUE TITLE
[Bug] [Xamarin.Forms] [iOS] SIGABRT: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

### ISSUE THREAD

**Issue by AbdellahOusrhireDev** [xamarin/xamarin-macios#7301]
### Description
Sometimes I'm getting a bug when my app starts; when my homepage is appearing and a request is made

### Steps to Reproduce

1. Using the NSUrlSession
2. making an api request as usual
3. app crashes

### Expected Behavior
request finishes successfully with no crash
### Actual Behavior
I'm getting an ArgumentOutOfRange exception

### Basic Information
- Possible issues related to this bug:
https://forums.xamarin.com/discussion/163418/is-this-xamarin-ios-bug
https://github.com/xamarin/xamarin-macios/issues/6443
https://github.com/xamarin/xamarin-macios/issues/6387
https://github.com/xamarin/xamarin-macios/issues/7152
https://github.com/xamarin/xamarin-macios/pull/6537
https://github.com/xamarin/xamarin-macios/pull/7184

- Version with issue:
- Last known good version:
- HttpClient Implementation: NSSessionUrl
- IDE: VS for Mac Community 8.3.4 Build 8
- Platform Target Frameworks: 
  - iOS:  Version: 12.10.0.157 (Visual Studio Community)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400
- Nuget Packages:
- Xamarin.Forms **4.2.0.778463**
- Affected Devices:
- iOS Simulator & An iPad 12.1.1 (16C50) (for testing)
### Screenshots

<img width="1371" alt="Capture d’écran 2019-10-18 à 11 19 19" src="https://user-images.githubusercontent.com/32442464/67086750-5e8b7980-f199-11e9-8c1d-f99b832b105c.png">

**Comment by whitneyschmidt** [comment]
@AbdellahOusrhireDev Thank you for digging deeper on this issue and updating your Xamarin install - was it resolved with the latest release?

**Comment by AbdellahOusrhireDev** [comment]
@whitneyschmidt @samhouts Sorry for the late reply. I did the tests & apparently, the update to Xamarin.iOS **13.4.0.2 fixed** the issue.

**Comment by whitneyschmidt** [comment]
@AbdellahOusrhireDev Thanks for closing this out! 💯
