### ISSUE TITLE
"Linked Away" exception when using CurrentPrincipal with SDK linking enabled

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#7321]
### Steps to Reproduce

1. Open attached project.
2. Run on simulator with and without SDK linking enabled
3. Note different behaviors.

### Expected Behavior

Linked and non-linked to behave the same

### Actual Behavior

Different behavior

### Environment
https://gist.github.com/chamons/fd0e35cb9262e2ed0f4762f058e4f9ca

### Example Project (If Possible)

[CurrentPrincipalCrash.zip](https://github.com/xamarin/xamarin-macios/files/3780802/CurrentPrincipalCrash.zip)

### Workaround
Add `--nolinkaway` to additional mtouch arguments

**Comment by chamons** [comment]
This older [blog post](https://spouliot.wordpress.com/2011/11/01/linker-vs-linked-away-exceptions/) from 2011 has details on where "Linked Away" comes from.

But in short:
- There are parts of the base class library that use bits that the runtime on iOS does not support
- Global settings like this tend to use remoting, which the runtime does not have enabled.
- There is an optimization that we enable during linking which replaces these code paths (remoting, etc) with "Linked Away"

You can work around this by disabling that optimization with `--nolinkaway` additional mtouch argument.

However, I believe that this used to work. It may be a regression due to runtime changes (we are now calling more remoting code that we did before when using this API?)

**Comment by spouliot** [comment]
```csharp
IPrincipal principal = currentThread.GetExecutionContextReader ().LogicalCallContext.Principal;
```
Looks like the old MONOTOUCH (or MOBILE) code paths were removed from mono and the current code goes thru domain/remoting code that we do not include in our runtime/BCL by default.

**Comment by spouliot** [comment]
likely worked before https://github.com/mono/mono/commit/d45fb4e882f802ce2e060061ed656ebf7c5487a5 got merged
