### ISSUE TITLE
xamarin.mac.sdk/0.29.0/Sdk/Sdk.props(35,7): error MSB4184

### ISSUE THREAD

**Issue by knocte** [xamarin/xamarin-macios#7344]
### Steps to Reproduce

1. Clone monodevelop master branch.
2. Fix .net4.7.2 build problem with https://github.com/knocte/monodevelop/commit/496c5cd8139e6f61aba83c442a2939fe9bd7ff5d (in case you're interested, I did this because I was trying to fix this other bug: https://github.com/mono/monodevelop/issues/9174)
3. Build with GithubActionsCI.

### Expected Behavior

Should build, like it builds on non-virtual macOS.

### Actual Behavior

Build fails with:
```
/Users/runner/.nuget/packages/xamarin.mac.sdk/0.29.0/Sdk/Sdk.props(35,7): error MSB4184: The expression ""%(Identity)".Substring(0, -1)" cannot be evaluated. Length cannot be less than zero. [/Users/runner/runners/2.159.2/work/monodevelop/monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/BraceCompletion/BraceCompletionImpl.csproj]
/Users/runner/.nuget/packages/xamarin.mac.sdk/0.29.0/Sdk/Sdk.props(35,7): error MSB4184: Parameter name: length [/Users/runner/runners/2.159.2/work/monodevelop/monodevelop/main/external/vs-editor-api/src/Editor/Text/Impl/BraceCompletion/BraceCompletionImpl.csproj]
```

### Environment

The GithubActionsCI yml file is using the `macOS-latest` VM, for reference: https://github.com/knocte/monodevelop/commit/702481bc383602a6abd8f5997ea2aaebf5d26943

### Build Logs

https://github.com/knocte/monodevelop/runs/282811849

### Example Project (If Possible)

https://github.com/knocte/monodevelop/commits/githubActionsCI

### Culprit?

The problem seems to be this part of the Sdk.props file:

```
  <ItemGroup>
    <Compile Update="*.designer.cs">
      <!--
      Produce DependentUpon item metadata via convention:
        <Compile Include="Foo.designer.cs">
          <DependentUpon>Foo.cs</DependentUpon>
        </Compile>
      -->
      <DependentUpon>$([System.String]::Copy('%(Identity)').Substring(
          0,
          $([System.String]::Copy('%(Identity)').LastIndexOf(
            '.designer.cs',
            System.StringComparison.OrdinalIgnoreCase))
        )).cs</DependentUpon>
    </Compile>
  </ItemGroup>
```
```

**Comment by chamons** [comment]
So, I'm confused why this is filed against xamarin-macios and not monodevelop.

xamarin.mac.sdk is not something we ship at all. I also don't see it in monodevelop.

Where did that file come from?

**Comment by knocte** [comment]
I'm also confused, I thought this file was in this repo since it's named `packages/xamarin.mac.sdk/0.29.0/Sdk/Sdk.props`

**Comment by chamons** [comment]
Xamarin.Mac and Xamarin.iOS don't have SDK style packages (yet), so that is not us.

Maybe I should move this to monodevelop?

**Comment by knocte** [comment]
> Maybe I should move this to monodevelop?

I don't find that file in MonoDevelop repo either.

Anyway, I just realised that `.LastIndexOf('.designer.cs')` shouldn't return -1 on files that match the pattern `*.designer.cs`, so maybe this is an msbuild bug?

**Comment by chamons** [comment]
It's a bug in whoever has that msbuild, but i'm not sure who.

**Comment by chamons** [comment]
I'm going to close this as this isn't from Xamairn.iOS or Mac, and the msbuild is question is not what we ship at all.

**Comment by knocte** [comment]
@radical hey Ankit, do you mind advising here if I should open this bug in mono/msbuild repo or mono/mono? 

> Anyway, I just realised that .LastIndexOf('.designer.cs') shouldn't return -1 on files that match the pattern *.designer.cs, so maybe this is an msbuild bug?

Also, any hints on how to debug the inconsistency above?
