### ISSUE TITLE
error: unable to open output file '.libs/mac/extension-main.x86_64.o': 'No such file or directory'

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/xamarin-macios#7354]
This happened when building `xamarin-macios` `d16-4` branch.

```
error: unable to open output file '.libs/mac/extension-main.x86_64.o': 'No such file or directory'
```

This issue can sometimes be encountered when building `xamarin-macios`. 

This is because locally `runtime/.libs/mac` doesn't exist.

I managed to workaround this by doing multiple `make git-clean-all` and rebuilding.

**Comment by rolfbjarne** [comment]
When this happens, please execute the following:

    make V=1 -C runtime

(and nothing else, in particular no `-jX`) and then attach the entire output here.

**Comment by rolfbjarne** [comment]
Not reproducible, so I'm closing.
