### ISSUE TITLE
error MT4109: Failed to compile the generated registrar code

### ISSUE THREAD

**Issue by KhurramAliKhan** [xamarin/xamarin-macios#7359]
### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

**Comment by chamons** [comment]
You appear to have accidentally submitted the issue without any details.

For issues like this we need steps to reproduce or a sample project showing the issue.

A full build log is also very helpful.

**Comment by whitneyschmidt** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
