### ISSUE TITLE
Support Metal in Simulator (iOS 13)

### ISSUE THREAD

**Issue by chingham** [xamarin/xamarin-macios#7392]
### Steps to Reproduce

1. Target iOS 13
2. Add some Metal code with Metal Shader
3. Compile on the Simulator

### Expected Behavior
With iOS 13, Metal is supported in the Simulator, but Xamarin build has not been updated for this.

### Actual Behavior
Compiler says that Metal is not supported in the Simulator.

### Environment
Xamarin.iOS 13.6.0.12
XCode 11.2
macOS 10.15

**Comment by chingham** [comment]
There is no ETA for this? It doesn't seem too hard and would allow to develop Metal apps much faster (given the time to deploy on device versus the time to deploy on simulator)

**Comment by dotMorten** [comment]
Any update on this? This is a showstopper for us, as Metal support is being required by Apple soon

**Comment by dotMorten** [comment]
@rolfbjarne you're my hero today

**Comment by chingham** [comment]
Wonderful ! Thank you so much !
