### ISSUE TITLE
Memory leak occurs when using NSData in Thread, but it's ok when run in async/await method.

### ISSUE THREAD

**Issue by lexboss93** [xamarin/xamarin-macios#7410]
### Steps to Reproduce

I have two similar methods one is invoked simply calling `AsyncFunc()`, and the other by creating a Thread object and starting it: `new Thread(ThreadFunc).Start()`.

When I look into Activity Monitor I see the second method has a memory leak. The memory consumed by an app is increasing without end. But the async/await counterpart method doesn't have a such flaw.

I've checked it in iPhone 11 13.2 simulator.

The following code snippet reproduces the issue:
```
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Foundation;
using UIKit;

namespace NsDataLeak
{
    [Register("AppDelegate")]
    public class AppDelegate : UIResponder, IUIApplicationDelegate
    {
        [Export("application:didFinishLaunchingWithOptions:")]
        public bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
        {
            //uncomment one of the following methods

            //AsyncFunc(); //this will run ok

            //new Thread(ThreadFunc).Start(); //this has a memory leak

            return true;
        }

        string GetString() => string.Concat(Enumerable.Repeat("adiwejdoqiwejfqoiwjfqowifjqowifjqwf", 2000));

        async Task AsyncFunc()
        {
            int i = 0;

            while (true)
            {
                i++;

                using (var data = NSData.FromString(GetString()))
                    ;

                if (i % 1000 == 0)
                    System.Diagnostics.Debug.WriteLine($"alive {i}");

                await Task.Delay(1);
            }
        }

        void ThreadFunc()
        {
            int i = 0;

            while (i < 1000 * 1000)
            {
                i++;

                using (var data = NSData.FromString(GetString()))
                    ;

                if (i % 1000 == 0)
                    System.Diagnostics.Debug.WriteLine($"alive {i}");

                Thread.Sleep(1);
            }

            System.Diagnostics.Debug.WriteLine("exited");
        }
    }
}
```

### Environment
[gist](https://gist.github.com/lexboss93/66dcec1eb3cd4dcd0383d124d04bf34d)

**Comment by rolfbjarne** [comment]
Try adding an NSAutoreleasePool to your thread:

```csharp
while (i < 1000 * 1000)
{
    using (var pool = new NSAutoreleasePool ())
    {
        i++;

        using (var data = NSData.FromString(GetString()))
            ;

        if (i % 1000 == 0)
            System.Diagnostics.Debug.WriteLine($"alive {i}");

        Thread.Sleep(1);
    }
}
```

**Comment by lexboss93** [comment]
> Try adding an NSAutoreleasePool to your thread:

@rolfbjarne that solves an issue.
But is this just a workaround or a something that we should always have in code?

**Comment by rolfbjarne** [comment]
@lexboss93 this is the fix, on Apple platforms it's assumed that there's always an NSAutoreleasePool somewhere up the stack. We automatically create one for every async processing event (which is why the async version of your code works), and also for each thread (but unless something else is done, the thread must exit before the NSAutoreleasePool is drained, which is why creating an NSAutoreleasePool for each iteration of the loop makes the problem go away for you, since then the closest pool is drained every iteration).
