### ISSUE TITLE
[Sharpie] Public release not signed/notarized

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#7422]
As noted here:

https://github.com/xamarin/xamarin-macios/issues/7109#issuecomment-553540588

We currently don't sign/notarize sharpie.

You can right click -> open and bypass the check, but we should fix it at some point.

**Comment by dalexsoto** [comment]
Objective-Sharpie is now notarized and available via http://aka.ms/objective-sharpie
