### ISSUE TITLE
Cannot build app - fails due to Native linking failed

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/xamarin-macios#7438]
This issue is occuring on some of the apps we develop in that when we build app in adhoc configuration it fails with errors. I have the linking set to Link Framework SDK's Only, supported architecture is arm64, I am also using SDK version 13.2 and Xamarin Forms 4.3.0.991211

### Steps to Reproduce

1. Change config to adhoc
2. Build
3. Build fails

### Expected Behavior

Build to succeed

### Actual Behavior

Build fails

### Environment

Microsoft Visual Studio Community 2019
Version 16.3.9
VisualStudio.16.Release/16.3.9+29509.3
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

ASP.NET and Web Tools 2019   16.3.286.43615
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.286.43615
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.286.43615
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.3.286.43615
Azure Functions and Web Jobs Tools

C# Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20816.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.83+gbc8a4b23ec
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.3.7 (9d260c5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.3.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Productivity Power Tools 2017/2019   16.0
Installs the individual extensions of Productivity Power Tools 2017/2019

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61908.27190
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

TypeScript Tools   16.0.10821.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.1-beta3-19461-02+2fd12c210e22f7d6245805c60340f6a34af6875b
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19455.1+0422ff293bb2cc722fe5021b85ef50378a9af823
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.3.0.278 (d16-3@40034cd)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.3.0.256 (remotes/origin/d16-3@8a223bfd7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   10.0.6.2 (d16-3/c407838)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@476d72b9e32
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

Xamarin.iOS and Xamarin.Mac SDK   13.6.0.12 (e3c2b40)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Build Logs

```csharp
<3>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT5211: Native linking failed, undefined Objective-C class: SFAuthenticationSession. The symbol '_OBJC_CLASS_$_SFAuthenticationSession' could not be found in any of the libraries or frameworks linked with your application.
3>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT5211: Native linking failed, undefined Objective-C class: SFSafariViewController. The symbol '_OBJC_CLASS_$_SFSafariViewController' could not be found in any of the libraries or frameworks linked with your application.
3>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT5202: Native linking failed. Please review the build log.
3>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error : linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by chamons** [comment]
Please attach a full build log so we can see the settings you are using. A project would be even better.

```<3>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT5211: Native linking failed, undefined Objective-C class: SFAuthenticationSession. The symbol '_OBJC_CLASS_$_SFAuthenticationSession' could not be found in any of the libraries or frameworks linked with your application.
3>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT5211: Native linking failed, undefined Objective-C class: SFSafariViewController. The symbol '_OBJC_CLASS_$_SFSafariViewController' could not be found in any of the libraries or frameworks linked with your application.
3>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error MT5202: Native linking failed. Please review the build log.
3>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): error : linker command failed with exit code 1 (use -v to see invocation)```

**Comment by LeoJHarris** [comment]
Hi @chamons 

Im having issues now adding an apple account to visual studio, dialog login is stuck and attached is logs:

[logs.zip](https://github.com/xamarin/xamarin-macios/files/3848664/logs.zip)

**Comment by LeoJHarris** [comment]
Here is the build log as requested:

[Output-Build.txt](https://github.com/xamarin/xamarin-macios/files/3848907/Output-Build.txt)

Looks like might be an issue the architecture armv7 but I havnt previously encountered this issue.

**Comment by LeoJHarris** [comment]
I think this issue is actually to do with the AppCenter SDK, after downgrading on some our app the nuget from version 2.6.1 down to version 2.5.0 the issue went away.

Closing this issue for now.
