### ISSUE TITLE
DispatchData does not have a very user friendly API

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#7446]
The class does not have very user friendly methods as well as could use some updates to be able to handler ReadOnlySpan.

Useful methods to add to the current API:

* `DispatchData FromReadOnlySpan (ReadOnlySpan<byte>)`
* `DispatchData FromReadOnlySpan (ReadOnlySpan<byte>, int start, int length)`
*  `byte [] ToArray ()`
* `ReadOnlySpan <byte> ToSpan ()`

**Comment by Therzok** [comment]
The start/length overloads are pretty much redundant with ReadOnlySpan.

You can do `obj.AsSpan(start, length)` or `span.Slice(start, length)` at almost no cost.

**Comment by Therzok** [comment]
Also, maybe provide `in Span<T>` support.

**Comment by spouliot** [comment]
not sure what's the most common name in the BCL update but `FromReadOnlySpan` has no verb and we generally don't use that pattern

**Comment by Therzok** [comment]
BCL usually uses overloaded `From`, since there is overloadability in parameter type.
