### ISSUE TITLE
which tags can I use build with mono-6.0.0.334

### ISSUE THREAD

**Issue by srxqds** [xamarin/xamarin-macios#7449]
We embed mono used tag mono-6.0.0.334, but we found **System.Net.Http.dll** referenced **Xamarin.iOS.dll**, how can I build it with mono-6.0.0.334?

The issue : https://github.com/mono/mono/issues/17797

**Comment by chamons** [comment]
This is a question more appropriate to our [gitter channel](https://gitter.im/xamarin/xamarin-macios) than a bug:

Mono 6.0.x is 2019-02 branch - https://github.com/mono/mono/blob/2019-02/configure.ac#L4

The [release notes](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/12/12.0) say Xamarin.iOS 12.0 was built against 2019-02.

https://github.com/xamarin/xamarin-macios/tree/d15-9 is your branch
