### ISSUE TITLE
Document Download Links of Xamarin.iOS & Mono Version to Match

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/xamarin-macios#7462]
When setting up CI it is very nice to use Boots to control the install process on macOS for the version of Xamarin.iOS & Android to install along with the version of Mono required.

Xamarin.Android has it documented lovely with each release and it would be nice to have this match on Xamarin.iOS:

Reference:
https://github.com/xamarin/xamarin-android#downloads

**Comment by chamons** [comment]
This is not a bad idea at all. We'll talk about it this week.

**Comment by chamons** [comment]
Sorry for the delay @jamesmontemagno but we dug into this. The short answer is that generating the table for macOS pkgs is simple, but it gets exceptionally difficult on the Windows side (visx) due to the remote build agent.

Would there be value in a macOS only table here?

**Comment by jamesmontemagno** [comment]
Yes, I think that would be very useful as the final packages are compiled on macOS anyways :)

**Comment by chamons** [comment]
Done!
