### ISSUE TITLE
[linker] Remove Nullability Attributes via linker (from C# 8)

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#7469]
Related to:

https://github.com/xamarin/xamarin-macios/issues/6154

The nullability attribute is powered by an attribute, that we should remove in our linker, and write a test for it.

CC: @rolfbjarne

**Comment by Therzok** [comment]
@chamons See https://sharplab.io/#v2:D4AQTAjAsAUAxAOwK4BsUEMBGKCmACHBLXWWcAZjwG9Y868QIA2BgFjwBEB7ACkYAY8AfnQBKagF9YEoA===

Nullability is encoded differently than System.Diagnostics.CodeAnalysis attributes

**Comment by spouliot** [comment]
This was fixed with #8301
