### ISSUE TITLE
FSEventStream bindings are incomplete

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#7481]
### Steps to Reproduce

EDIT: SEE COMMENTS BELOW!

~1. Try to use FSEventStream~
~2. Nothing to use~

### Environment

Xamarin.Mac
Version: 6.14.0.7 (Visual Studio Enterprise)
Hash: 28a560c8
Branch: d16-5
Build date: 2019-11-12 09:11:24-0500

**Comment by prmallic** [comment]
@Therzok . I think the bindings are there in `src/CoreServices/FSEvents.cs`. Is there some specific API that you want to use and is missing?

**Comment by Therzok** [comment]
Hah, could not find it initially.

It seems though that the manual binding could cripple GC performance under VSMac (due to marshalling arrays on every event).

Might be solvable if we let macOS reduce event duplication, but need to check.

From the looks of it, the binding is incomplete. FSEventStreamSet DispatchQueue/ExclusionPaths are missing

**Comment by Therzok** [comment]
Also, the API is not high performance suited - array allocations on every native callback instead of having a callback per file.
