### ISSUE TITLE
Xamarin iOS random crash

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [xamarin/xamarin-macios#7501]
Below is the log, some time it work fine, some time it crashed.

Unhandled Exception:
System.InvalidCastException: Unable to cast object of type 'Foundation.NSObject' to type 'CoreGraphics.CGColor'.
  at ObjCRuntime.Runtime.GetINativeObject (System.IntPtr ptr, System.Boolean owns, System.Type target_type, System.Type implementation) [0x000cc] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1420 
  at ObjCRuntime.Runtime.GetINativeObject (System.IntPtr ptr, System.Boolean owns, System.Type target_type) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1382 
  at ObjCRuntime.Runtime.GetINativeObject_Dynamic (System.IntPtr ptr, System.Boolean owns, System.IntPtr type_ptr) [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:692 
  at ObjCRuntime.Runtime.get_inative_object_dynamic (System.IntPtr obj, System.Boolean owns, System.IntPtr type, System.Int32& exception_gchandle) [0x00003] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/runtime/Delegates.generated.cs:327 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at connect.me.mobile.iOS.Application.Main (System.String[] args) [0x00001] in /Volumes/Data/OpenSources/TDTRelease/trangdangtin/connect.me.mobile.iOS/Main.cs:12 
2019-11-27 20:24:12.973 connect.me.mobile.iOS[1234:714489] Unhandled managed exception: Unable to cast object of type 'Foundation.NSObject' to type 'CoreGraphics.CGColor'. (System.InvalidCastException)
  at ObjCRuntime.Runtime.GetINativeObject (System.IntPtr ptr, System.Boolean owns, System.Type target_type, System.Type implementation) [0x000cc] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1420 
  at ObjCRuntime.Runtime.GetINativeObject (System.IntPtr ptr, System.Boolean owns, System.Type target_type) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1382 
  at ObjCRuntime.Runtime.GetINativeObject_Dynamic (System.IntPtr ptr, System.Boolean owns, System.IntPtr type_ptr) [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:692 
  at ObjCRuntime.Runtime.get_inative_object_dynamic (System.IntPtr obj, System.Boolean owns, System.IntPtr type, System.Int32& exception_gchandle) [0x00003] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/runtime/Delegates.generated.cs:327 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.6.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at connect.me.mobile.iOS.Application.Main (System.String[] args) [0x00001] in /Volumes/Data/OpenSources/TDTRelease/trangdangtin/connect.me.mobile.iOS/Main.cs:12 

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10b648a5c - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x10b63e840 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x10b647f1c - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x195548894 - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x19554d1d8 - /usr/lib/system/libsystem_pthread.dylib : <redacted>
	0x1954a1844 - /usr/lib/system/libsystem_c.dylib : abort
	0x10b809d84 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : xamarin_get_block_descriptor
	0x10b6a965c - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : mono_pmip
	0x10b63e210 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x10b63cc38 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x10b6327b0 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x1020f8e8c - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x10b71955c - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : mono_pmip
	0x10b809af0 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : xamarin_get_block_descriptor
	0x10b80996c - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : xamarin_get_block_descriptor
	0x101694fac - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x101752cb8 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x19c2e7084 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c2e3dc8 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c2b04ac - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c2b0160 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c2b196c - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c17b954 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c2b19b8 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c2a8b9c - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c2ba930 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c2036c4 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c22d3b0 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x19c16b1c8 - /System/Library/Frameworks/QuartzCore.framework/QuartzCore : <redacted>
	0x196783a2c - /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit : IODispatchCalloutFromCFMessage
	0x19578f8ac - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1957b907c - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1957b87a8 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1957b367c - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1957b2adc - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x19f73c328 - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x1998adae0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x1047d22f0 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x103f2f01c - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x103f2eea4 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x1017b40d0 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x102089374 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x10b650538 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : mono_pmip
	0x10b70d2b0 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : mono_pmip
	0x10b713578 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : mono_pmip
	0x10b62e704 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x10b81bb80 - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : xamarin_localized_string_format_9
	0x1017b16bc - /private/var/containers/Bundle/Application/296F7E0C-C87C-48CE-B018-A3561D8DA5BF/connect.me.mobile.iOS.app/connect.me.mobile.iOS : _ZN9GMSx_absl13base_internal10AtomicHookIPFvPKciS3_S3_S3_EE13DummyFunctionES3_iS3_S3_S3_
	0x19563c360 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x195631ec4):0x195631eb4  c0 03 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
0x195631ec4  e3 00 00 54 fd 7b bf a9 fd 03 00 91 25 7c ff 97  ...T.{......%|..
0x195631ed4  bf 03 00 91 fd 7b c1 a8 c0 03 5f d6 c0 03 5f d6  .....{...._..._.
0x195631ee4  90 29 80 d2 01 10 00 d4 e3 00 00 54 fd 7b bf a9  .).........T.{..

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================

VS for Mac 8.3.10 build 02
Xamarin.iOS
Version: 13.6.0.12
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:08-0400

**Comment by xamarindevelopervietnam** [comment]
<img width="1011" alt="Screen Shot 2019-11-27 at 19 57 29" src="https://user-images.githubusercontent.com/16578966/69727140-7ec53580-1154-11ea-8e1f-65246ef4d17e.png">

**Comment by chamons** [comment]
It would be exceptionally helpful to have a sample application that reproduces this. It will be difficult if not impossible to pin this down without more info.

**Comment by xamarindevelopervietnam** [comment]
it's a big project, give me your email, i will invite you to access into repo and talk more about this issue. Thanks!

**Comment by chamons** [comment]
@xamarindevelopervietnam - If your project reproduces the problem consistently and is reasonable to build you can send chris.hamons@xamarin.com an invite.

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Comment by RadoslawKubas** [comment]
@xamarindevelopervietnam Did you find any solution for this problem? I have very similar (or same) issue. It seems to be random, but usual trigger is 
1. In NaviagationPage open PageA
2. Naviage from PageA to PageB
3. In PageB naviagate outside the app (Xamarin.Essentials.Launcher.OpenAsync("https://appwithkiss.com"))
4. Immediately return to the app
5. Immediately GoBack from PageB to PageA.

It usually works fine, let's say 80%, but if you repeat it, it crashes faster or later with same exception. The crash appears after PageA is correctly displayed, I believe it is something not exactly with PageA, more something with destroying PageB, but of course can't be sure.
