### ISSUE TITLE
Incorrect changes from int to (unsigned) long in the runtime

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#7509]
The native `long` and `unsigned long` are 64-bit on a 64-bit OS and 32-bit on a 32-bit OS.

This means that this change is incorrect: https://github.com/xamarin/xamarin-macios/commit/2e5b64893f694bb8b65d5626e556d3805d81428e#diff-ef40c5787a0475f88e10461efe5f3c01L55-R55

Any (unsigned) int -> (unsigned) long commits must be fully reviewed again, there are several other places where there are bugs:

https://github.com/xamarin/xamarin-macios/commit/2e5b64893f694bb8b65d5626e556d3805d81428e#diff-ef40c5787a0475f88e10461efe5f3c01L206-R206

https://github.com/xamarin/xamarin-macios/commit/2e5b64893f694bb8b65d5626e556d3805d81428e#diff-5ca7e9836bcee437c268d6065e2c6eaeL26-R26 (breaking API change)

https://github.com/xamarin/xamarin-macios/commit/2e5b64893f694bb8b65d5626e556d3805d81428e#diff-a41cda5f508168c4aafab2b33741eed4L384-R384 (breaking API change)

https://github.com/xamarin/xamarin-macios/commit/2e5b64893f694bb8b65d5626e556d3805d81428e#diff-ba72c2a1b404212ae58242dc25660defL12-R13 (breaking API change - this one actually causes the link all tests to crash when run on a device in release mode)

https://github.com/xamarin/xamarin-macios/commit/2e5b64893f694bb8b65d5626e556d3805d81428e#diff-6ddca81e8497599c1b02b643c8ed5128L29-R29 (breaking API change)

https://github.com/xamarin/xamarin-macios/commit/2e5b64893f694bb8b65d5626e556d3805d81428e#diff-ae96dff46e2db1f319d0331d9beed8d2L184-R184 (breaking API change)

https://github.com/xamarin/xamarin-macios/commit/2e5b64893f694bb8b65d5626e556d3805d81428e#diff-0689f45915b28af398ed3ac8f5d98545L38-R38 (breaking API change)

**Comment by rolfbjarne** [comment]
This also causes https://github.com/xamarin/maccore/issues/2072.

**Comment by spouliot** [comment]
@mandel-macaque it needs to be backported to d16-5 since we still have test failures in that branch

**Comment by spouliot** [comment]
Some stuff was indirectly backported to d16-5 (thru a merge) and that's why the above backport was also needed. Now merged so those errors should be gone...
