### ISSUE TITLE
[xcode11.3] Test failure: Xamarin.ApiTest.ApiTest.AlwaysOptimizable: All methods calling optimizable API must be optimizable

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#7513]
Test failures:

* Xamarin.ApiTest.ApiTest.AlwaysOptimizable(macOSMobile): All methods calling optimizable API must be optimizable

    > The method Network.NWParameters Network.NWParameters::CreateCustomIP(System.Byte,System.Action`1<Network.NWProtocolOptions>) calls System.Void ObjCRuntime.BlockLiteral::SetupBlockUnsafe(System.Delegate,System.Delegate), but it does not have a [BindingImpl (BindingImplOptions.Optimizable)] attribute.

* Xamarin.ApiTest.ApiTest.AlwaysOptimizable(macOSFull): All methods calling optimizable API must be optimizable
    
    > The method Network.NWParameters Network.NWParameters::CreateCustomIP(System.Byte,System.Action`1<Network.NWProtocolOptions>) calls System.Void ObjCRuntime.BlockLiteral::SetupBlockUnsafe(System.Delegate,System.Delegate), but it does not have a [BindingImpl (BindingImplOptions.Optimizable)] attribute.

See http://xamarin-storage/jenkins/xamarin-macios/xcode11.3/bcf3899893c0ee1a0bbcd814164a08423f0d543a/21/jenkins-results/tests/index.html for https://github.com/xamarin/xamarin-macios/commit/bcf3899893c0ee1a0bbcd814164a08423f0d543a.

**Comment by mandel-macaque** [comment]
Hmmm expected this to be closed after the PR was merged.
