### ISSUE TITLE
Updated Frameworks not being updated in final app package without rebuild

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-macios#7514]
### Steps to Reproduce

1. Create an iOS project
2. Install SkiaSharp 1.68.0
3. Write some code that does something with SkiaSharp and call one of the dispose methods
4. [Re]build and deploy
5. Upgrade SkiaSharp to 1.68.1
6. Build (not rebuild) and deploy
7. Observe a entry point not found exception
8. REBUILD and deploy
8. Observe NO exception

I have been getting quite a few reports of people upgrading to a new version of SkiaSharp and then reporting that there are missing entry points. This is because I added new entries to the new version. The reason this is happening is that the process of update-NuGet-and-then-just-build is not triggering the bits to repackage the native bits into the package. A rebuild fixes this.

An example issue: https://github.com/mono/SkiaSharp/issues/968

### Expected Behavior

No exception

### Actual Behavior

EntryPointNotFoundException

### Environment

Recent versions (not sure how far it goes back)

**Comment by spouliot** [comment]
I did not get the error but...

> Write some code that does something with SkiaSharp and call one of the dispose methods

I might not have hit a good API to suffer from the lack of the new symbol.

Can you share a project and, if possible, the build log too (just in case something else can be masking this).

I'll still look what's happening the the native library in the build, after the upgrade.

**Comment by spouliot** [comment]
> 5.5. Change some source code

Otherwise nothing gets rebuilt... which already shows a problem since the .dll was updated.

```
System.EntryPointNotFoundException: sk_refcnt_safe_unref assembly:<unknown assembly> type:<unknown type> member:(null)
  at at (wrapper managed-to-native) SkiaSharp.SkiaApi.sk_refcnt_safe_unref(intptr)
  at SkiaSharp.SKObjectExtensions.SafeUnRef (SkiaSharp.ISKReferenceCounted obj) [0x00017] in <a7c90b8c47404850a87d153c500104ed>:0
  at SkiaSharp.SKObject.DisposeNative () [0x0000a] in <a7c90b8c47404850a87d153c500104ed>:0
  at SkiaSharp.SKNativeObject.Dispose (System.Boolean disposing) [0x0002a] in <a7c90b8c47404850a87d153c500104ed>:0
  at SkiaSharp.SKObject.Dispose (System.Boolean disposing) [0x00000] in <a7c90b8c47404850a87d153c500104ed>:0
  at SkiaSharp.SKSurface.Dispose (System.Boolean disposing) [0x00000] in <a7c90b8c47404850a87d153c500104ed>:0
  at SkiaSharp.SKNativeObject.DisposeInternal () [0x00000] in <a7c90b8c47404850a87d153c500104ed>:0
  at SkiaSharp.SKNativeObject.Dispose () [0x00009] in <a7c90b8c47404850a87d153c500104ed>:0
  at gh7514.ViewController.ViewDidLoad () [0x0004f] in /Users/poupou/Projects/gh7514/gh7514/ViewController.cs:26
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/poupou/git/xamarin/xamarin-macios/src/UIKit/UIApplication.cs:86
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/poupou/git/xamarin/xamarin-macios/src/UIKit/UIApplication.cs:65
  at gh7514.Application.Main (System.String[] args) [0x00001] in /Users/poupou/Projects/gh7514/gh7514/Main.cs:12
```

**Comment by spouliot** [comment]
Adding this (and the `using SkiaSharp;`) is enough to trigger it
```csharp
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			using (var surface = SKSurface.Create (640, 480, SKImageInfo.PlatformColorType, SKAlphaType.Premul)) {
				Console.WriteLine (surface.Handle);
			}
		}
```
change `640` for `641` to Build (not Rebuild) again

**Comment by spouliot** [comment]
```
Prerequisite '/Users/poupou/.nuget/packages/skiasharp/1.68.1/lib/Xamarin.iOS/SkiaSharp.dll' is older than the target '/Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/device-builds/iphone12.1-13.2/mtouch-cache/libSkiaSharp.framework.zip'.
    Target '/Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/device-builds/iphone12.1-13.2/mtouch-cache/libSkiaSharp.framework' is up-to-date.
    /usr/bin/unzip -u -o -d /Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/device-builds/iphone12.1-13.2/mtouch-cache/libSkiaSharp.framework /Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/device-builds/iphone12.1-13.2/mtouch-cache/libSkiaSharp.framework.zip
    Archive:  /Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/device-builds/iphone12.1-13.2/mtouch-cache/libSkiaSharp.framework.zip
```

**Comment by spouliot** [comment]
```
   Extracted third-party framework 'libSkiaSharp.framework' from '/Users/poupou/.nuget/packages/skiasharp/1.68.0/lib/Xamarin.iOS/SkiaSharp.dll' to '/Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/device-builds/iphone12.1-13.2/mtouch-cache/libSkiaSharp.framework.zip'
```

the framework is inside the .dll (not good for build times)
but once extracted it gets the current date/time which is later compared to the date/time of the .dll

**Comment by spouliot** [comment]
Fixing the extract date (to match the .dll date) leads to another issue later :(

```
  Prerequisite '/Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/mtouch-cache/libSkiaSharp.framework/libSkiaSharp' is older than the target '/Users/poupou/Projects/gh7514/gh7514/bin/iPhoneSimulator/Debug/gh7514.app/Frameworks/libSkiaSharp.framework/libSkiaSharp'.
    Target '/Users/poupou/Projects/gh7514/gh7514/bin/iPhoneSimulator/Debug/gh7514.app/Frameworks/libSkiaSharp.framework/libSkiaSharp' is up-to-date
    Prerequisite '/Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/mtouch-cache/libSkiaSharp.framework/Modules/module.modulemap' is newer than the target '/Users/poupou/Projects/gh7514/gh7514/bin/iPhoneSimulator/Debug/gh7514.app/Frameworks/libSkiaSharp.framework/Modules/module.modulemap'.
    Prerequisite '/Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/mtouch-cache/libSkiaSharp.framework/Modules/module.modulemap' is newer than the target '/Users/poupou/Projects/gh7514/gh7514/bin/iPhoneSimulator/Debug/gh7514.app/Frameworks/libSkiaSharp.framework/Modules/module.modulemap'.
    Prerequisite '/Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/mtouch-cache/libSkiaSharp.framework/Info.plist' is newer than the target '/Users/poupou/Projects/gh7514/gh7514/bin/iPhoneSimulator/Debug/gh7514.app/Frameworks/libSkiaSharp.framework/Info.plist'.
    Prerequisite '/Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/mtouch-cache/libSkiaSharp.framework/Info.plist' is newer than the target '/Users/poupou/Projects/gh7514/gh7514/bin/iPhoneSimulator/Debug/gh7514.app/Frameworks/libSkiaSharp.framework/Info.plist'.
    Prerequisite '/Users/poupou/Projects/gh7514/gh7514/obj/iPhoneSimulator/Debug/mtouch-cache/3-Build/gh7514.exe' is newer than the target '/Users/poupou/Projects/gh7514/gh7514/bin/iPhoneSimulator/Debug/gh7514.app/gh7514.exe'.
```

**Comment by mattleibow** [comment]
I have been considering moving all the .frameworks, .a and .so files out of the dlls. Is using a .targets the best way to do this? 

Also, if I do move it out, the second thing will happen, right? The date will be earlier than the one on the device.

**Comment by spouliot** [comment]
> I have been considering moving all the .frameworks, .a and .so files out of the dlls. 

That would be much better for build times. Today every rebuild is extracting 20MB from the dll. That's quite bigger on iOS than other platforms (in your case). Not sure why since you should not need bitcode (which is what bloats binaries the most).

For application size (and deploy times) the use of static libraries is better, since it let the native linker remove code (not just unused architectures). Of course that varies a lot depending on how much the application uses the native libraries...

>  Is using a .targets the best way to do this?

We have "sidecar" support for extra binaries in a nuget. I don't recall the details, @chamons implemented on this a while back.

> Also, if I do move it out, the second thing will happen, right? 

No, it should not. Pretty sure that this happens because of the change I made (which moved the problem).

**Comment by chamons** [comment]
That work was done in https://github.com/xamarin/xamarin-macios/pull/5167

If you set `<NoBindingEmbedding>true</NoBindingEmbedding>` in your binding project csproj property group, next to your library we'll make a folder with the same name and a `.resources` extension. 

Example: `Foo.dll -> Foo.resources folder`

As long as the assembly and the resource folder are next to (thus the sidecar nickname), we'll resolve there when building your app.

Be aware, if your library is a framework you need to take care when moving it around to not break any symbolic links inside.

There are auto tests, so I expect it should work, but this was never a documented producized feature.

**Comment by mattleibow** [comment]
@chamons is there a way to do this without using a binding project - maybe some sort of targets file property? The reason is that I would like to get away form binding projects as they don't build on Windows. In the case of SkiaSharp, it is also not a real binding project as I use p/invokes to the C API.

**Comment by chamons** [comment]
This is obviously not a "supported" technique, but we are just looking for a certain folder with a manifest and the libraries in question. 

Maybe you could use a binding project one time, and use it to create the correct structure outside of a binding project? It's just a folder w\ an XML file really, next to the assembly in question.

**Comment by spouliot** [comment]
there's more than one problem... or at least an earlier one that thrown me into the wrong direction 

```
        -r=/Users/poupou/.nuget/packages/xamarin.essentials/1.2.0/lib/xamarinios10/Xamarin.Essentials.dll
        ' --target-framework=Xamarin.iOS,v1.0'
        --root-assembly=/Users/poupou/Projects/gh7514/gh7514/bin/iPhoneSimulator/Debug/gh7514.exe
        ' -v -v -v -v'
Using Xcode 11.2 (11B52) found in /Applications/Xcode112.app/Contents/Developer
Xamarin.iOS 13.15.0.94 (master): 611d6f37f) using framework: /Applications/Xcode112.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk
A full rebuild will be performed because the arguments to mtouch has changed with regards to the cached data.
A full rebuild has been forced because the cache for gh7514 is not valid.
```

a new nuget version means the argument to mtouch differs which should rebuild everything
but we store the framework in the directory _above_ so that does not get _fully_ cleaned up

**Comment by spouliot** [comment]
There's more than one issue but the root problem is that `CopyFileCallback` fails to copy over the binary, `stage == CopyFileStep.Err` which means the old content remains for the newer build (even with force) and a _real_ Rebuild would nuke the directory (so the copy would be fine)

`strerror` returns `260` which might be `FileReadNoSuchFile` but both source and target exists (and are not even symlinks)

Deleting the directory when `Driver.Force` is set makes it work... but, while good, it's not clear if we can run (or not) into the same situation when `Force` is not set (like it is, or should be, in this case).

**Comment by spouliot** [comment]
(No so funny) fact: Logs used `strerror` which returns `Unknown error : 260` which `msbuild` interprets (and report) as a build error :(
