### ISSUE TITLE
Xamarin.iOS version mismatch Latest VS Mac (18.3.10 build 2) & VS 2019 Windows (16.3.10)

### ISSUE THREAD

**Issue by ncarandini** [xamarin/xamarin-macios#7518]
### Steps to Reproduce
1. Open VS for Mac (18.3.10 build 2);
2. Check for updates on channel "stable", download and install updates;
3. Open a Xamarin solution with Visual Studio 2019 (16.3.10);
4. From the VS 2019 Windows instance, connect to Mac.

### Expected Behavior
The pairing works like a charm.

### Actual Behavior
The pairing procedure stops with a warning message about Xamarin.iOS SDK mismatch, asking to downgrade the VS for Mac Xamarin.iOS SDK (13.6.0.12) to the lower Visual Studio version (13.4.0.2).

### Environment
VS for Mac (18.3.10 build 2)
Visual Studio 2019 (16.3.10)

> VS bug [#1029497](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1029497)

**Comment by josegallardo** [comment]
Hi @ncarandini 

Current VS 2019 16.3.10 uses the same Xamarin.iOS 13.6.0.12 you seems to have installed on your Mac, and shouldn't ask for downgrading (as it doesn't do in my local test, and we didn't get any other similar report about that).
The only potential issue would be if you have some preview installation on top of your VS instance (like an Alpha Pack for an Xcode preview).

Can you please double check if that's the case?

Thanks!
