### ISSUE TITLE
Xamarin iOS - DuplicateIdentifier attempting to debug app with today extension

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#7526]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/526872/xamarin-ios-duplicateidentifier-attempting-to-debu.html)._

---
After updating to the latest versions of VS & VS for Mac, attempting to debug an app (with today extension) on a device, I get:

DuplicateIdentifier: Found bundle at /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.qsd258/extracted/MyApp.app/Frameworks/Xamarin.framework with the same identifier (xamarin.ios.xamarin-framework) as bundle at /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.qsd258/extracted/MyApp.app/Frameworks/Xamarin-debug.framework

Launch failed. The app 'MyApp' could not be launched on 'My iPhone'. Error: error MT1006: Could not install the application '/Users/ralphjacobson/Library/Caches/Xamarin/mtbs/builds/MyApp/2b490f54bf795647752419e416f925bf/bin/iPhone/Debug/device-builds/iphone9.3-12.2/MyApp.app' on the device 'My iPhone': AMDeviceSecureInstallApplicationBundle returned: 0xe80000b0 (This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique.).. Please check the logs for more details.

- Versions:
- VS 2019 16.0.1
- VS for Mac 8.0.2
- Xamarin iOS 12.8.0.0

I have cleaned the solution, deleted bin and obj folders but to no avail.

Debugging worked fine before the update.

---
#### Visual Studio Feedback System on 4/10/2019, 09:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Emanuel Fernandez Dell'Oca [MSFT] on 4/11/2019, 10:06 AM: 

<p>Hi!</p><p>It looks like two frameworks with the same identifier are being included in your bundle, could you add &quot;-v -v -v&quot; as &quot;Additional mtouch arguments&quot; in the iOS Build project properties page and then provide us a Detailed build output? You can change the build output verbosity from Tools -&gt; Options -&gt; Project and Solutions -&gt; Build and Run -&gt; MSBuild project build output verbosity.</p><p><br></p><p>Thanks for reporting!</p><p><br></p><p>Use these instructions to respond to More Info requests from Visual Studio:  https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info .</p>

#### Ralph Jacobson on 4/12/2019, 02:20 AM: 

Hi<br><br>Please find the build output attached.<br><br>Thank you.<br>Ralph
#### Emanuel Fernandez Dell'Oca [MSFT] on 4/12/2019, 08:51 AM: 

<p>Hi Ralph!</p><p>I see you attached all the logs, but I don't see any build output. Sorry if I wasn't clear enough, what we need you to do is grab the content of the Build pane of the Output window after rebuilding the app (with the settings from my last comment) and then attach it in a text file.</p><p><br></p><p>Thanks!</p>
#### Ralph Jacobson on 4/15/2019, 03:31 AM: 

Hi Emanuel<br><br>That's exactly what I did, am I missing something?<br><br>Originally I only added "-v -v -v" to the main iOS project, I'm now including logs where I've added it to the widget project as well.<br><br>Thanks<br>Ralph
#### Emanuel Fernandez Dell'Oca [MSFT] on 4/15/2019, 01:49 PM: 

<p>Hi Ralph!</p><p>It looks like there's a problem when you upload the file then, what's the name of it? I'm seeing more than 100 new log files but none of those seem to be a build output, maybe I'm missing it between all these files.</p><p><br></p><p>Thanks!</p>
#### Ralph Jacobson on 4/16/2019, 03:46 AM: 

Hi<br><br>It's called output2.7z.  I'll attach another copy.<br><br>Thank you<br><br>Ralph
#### Emanuel Fernandez Dell'Oca [MSFT] on 4/17/2019, 10:11 AM: 

<p>Hi Ralph,</p><p>That file is not present in the attachments, the system might be filtering it because of the 7z extension, could you try uploading the text file directly to see if that works?</p><p><br></p><p>Thanks!</p><p><br></p>
#### Ralph Jacobson on 5/2/2019, 01:55 AM: 

Hi<br><br>Please find the file called output2.txt attached.<br><br>Regards<br>Ralph
#### Emanuel Fernandez Dell'Oca [MSFT] on 5/2/2019, 09:19 AM: 

<p>Thanks for the build output Ralph! </p><p><br></p><p>I'm redirecting this issue to the appropiate team, so they can investigate why the SDK is including both frameworks.</p>

#### Vincent Dondain [MSFT] on 5/12/2019, 07:58 PM: 

<p>I couldn't reproduce the specific error you got but the today extension widget was unable to load and later I couldn't deploy the extension anymore. This might be related to the issue you're experiencing.</p><p><br></p><p>This issue is currently being investigated. We will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p><p><br></p><p>Thanks for the feedback.</p>

#### Aleksander Dejewski on 6/19/2019, 06:14 AM: 

<p>I think I am experiencing same problem. I get "duplicated identifier" error on both VS2017 and VS2019. What is interesting I can create IPA fila and upload it to TestFlight. But as <a rel="user" href="https://developercommunity.visualstudio.com/users/19755/eda4ea7a-33db-408c-b40c-0416bd6bc8f0.html" nodeid="19755">@Vincent Dondain [MSFT]</a> wrote today extension widget is unable to load. Is there any workaround? </p>

---
### Original Solutions
(no solutions)

**Comment by spouliot** [comment]
This looks similar to https://github.com/xamarin/xamarin-macios/issues/6920

I'm closing this since nothing recent was added to the original (azdo) issue and the above (#6920) was solved in `xcode11` branch, so XI 13.0, while the bug mention XI 12.8.
