### ISSUE TITLE
[Meta] .NET 5 Support

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#7528]
As [previously announced](https://devblogs.microsoft.com/dotnet/introducing-net-5/) .NET 5 is going to be a huge step forward for the platform. 

For anyone interested, I would strongly suggest reading the post for more details on what it will entail.

The iOS/Mac SDK team, and much of Xamarin as a whole, are working through the implications of .NET 5 and the work required. This work is now in the earliest phases, and there is little to share today.

This meta task is a good place to subscribe for details as they become available.

**Comment by juepiezhongren** [comment]
will it be possible that xmac app runs on top of coreclr？

**Comment by chamons** [comment]
Answering that, and what it looks like, is part of this effort @juepiezhongren .

**Comment by NogginBops** [comment]
Will #5107 be considered for .NET 5?
It seems like a good opportunity to clean out the cruft and make life easier for a lot of people.

**Comment by chamons** [comment]
@NogginBops - We are considering an API break, as there will be some form of project format break likely. 

However, the currently feeling on the team is to avoid it if possible for fear of making the transition of our users to .NET 5 even more difficult.

Is there a specific bug fix / binding fix you are interested in, or just the idea of a general cleanup.

API compatibility is hard, and if we are forced to break the API there are many on the team who will be happy to clean house.

**Comment by NogginBops** [comment]
Thanks for the quick response!
I'm mostly interested in https://github.com/mono/opentk/issues/19 which have resulted in some heated discussions earlier but I really think it's the right move to make and as the user base relying on these outdated types is very small it wouldn't make updating that much harder.

The issue is basically that there are legacy OpenTK types defined in the main assembly, preventing the use of any other version of OpenTK than the outdated version in Xamarin.
If the concern is taking types out and not providing an alternative it would be sufficient to move the types to a new assembly as that would allow for that assembly to be ignored, fixing the name-clash issue. While keeping the old types still available.

**Comment by chamons** [comment]
That is a interesting issue that I was not fully aware of. 

I've raised this up for consideration internally. Any change would be in lock step with the other Xamarin SDKs.

Xamarin whenever possible tends to not break API compatibility, as many customers depend upon binary or 3rd party components that are sometimes very difficult to get updates. 

However, I understand the significant pain this is causing you.

I'll reply if and when I have more information.

**Comment by patr0nus** [comment]
Hi, [it seems](https://github.com/xamarin/xamarin-macios/pull/7346) the managed implementation of http client is coming to xamarin. Will the same thing happen to the TLS implementation when .NET 5 comes?

I am under the impression that the TLS implementation in iOS/Mac is based on Apple’s SecureTransport, which is now [considered legacy](https://developer.apple.com/documentation/security/secure_transport). It seems to be a good time  now to bring Corefx’s TLS to Xamarin in .NET 5.

**Comment by chamons** [comment]
Possible implementation detail: https://github.com/xamarin/xamarin-macios/issues/7924

**Comment by danipen** [comment]
Great to hear that!

We offer to test an alpha/beta version and help in the development process as soon as it is available.

**Comment by spouliot** [comment]
> I am under the impression that the TLS implementation in iOS/Mac is based on Apple’s SecureTransport,

@patr0nus I'm more complicated than that.

Some of the TLS API use SecureTransport. This includes using the existing **managed** HttpClient handler. We also have bindings for the newer Network framework in case you need direct TLS support.

However when you're `HttpClient` with a native handler, like `NSUrlSessionHandler`, you do not use SecureTransport or _legacy_ code. The native handlers are the only ones to support switching wifi/cellular antennas and background operations.

So .net5 will give you the new socket-based managed handler but the TLS support is not managed  - it comes from native code (and extra library), calling Apple's API and I'm not sure if they are from SecureTransport or not.

**Comment by chamons** [comment]
They everyone for the feedback and interest. 

We have more clarity now, and a few changes, and I've created https://github.com/xamarin/xamarin-macios/issues/8955 with all of the new info.
