### ISSUE TITLE
Trying to override AccessibilityElementCount method for iOS

### ISSUE THREAD

**Issue by edenwaith** [xamarin/xamarin-macios#7575]
### Steps to Reproduce

I am trying to add VoiceOver support to a collection view which is contained within a table view cell.  However, there is a well known issue with this design where VoiceOver can only scroll a couple cells through the collection view before it moves on to the next table view cell, instead of moving through all of the collection view cells.  I've come across a couple of proposed solutions, and the following blog perfectly describes the situation I'm encountering and how to solve this issue:

https://www.blog.kevin-hirsch.com/tips-and-tricks-1-making-collection-views-inside-table-views-accessible/

This blog recommends overriding the `AccessibilityElementCount` method, which is what I'm trying to do in my UICollectionView subclass.

The problem I'm encountering here is that when I create a subclass of a UICollectionView and then try and write and override method for `AccessibilityElementCount` (a method of the IUIAccessibilityContainer protocol), Visual Studio says that there is "no suitable method found to override" 

My example method is:
```
public override nint AccessibilityElementCount()
{
   ...
   // return the number of accessible elements
}
```

On our project, we have encountered some limitations/inconsistencies with Xamarin and accessibility.  We had to swizzle the `SetAccessibilityElements` method to be able to access the `accessibilityElements` property, so it makes me wonder if this is a similar case where other IUIAccessibilityContainer methods are not being called/handled properly.

If I can override these IUIAccessibilityContainer methods, I'm hoping this will resolve the issue I'm encountering which will provide additional flexibility for VoiceOver in the app.

### Expected Behavior

Overriding a IUIAccessibilityContainer method, such as `AccessibilityElementCount` should be called.

### Actual Behavior

Trying to override `AccessibilityElementCount` does not work.  The compiler says that there is nothing to override.

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.3.2 (build 32)
Installation UUID: a95c3856-bacb-40c3-a5df-9ae359aa603a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.1.701
	2.1.700
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13
	2.1.12
	2.1.11

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.2.0.47 (Visual Studio Community)
Hash: c2cbd3480
Branch: d16-3
Build date: 2019-09-30 22:37:32-0400

=== Xamarin Designer ===

Version: 16.3.0.247
Hash: 52eac1a9e
Branch: remotes/origin/d16-3
Build date: 2019-10-03 23:04:28 UTC

=== Xamarin.Android ===

Version: 10.0.3.0 (Visual Studio Community)
Commit: xamarin-android/d16-3/4d45b41
Android SDK: /Users/chad.armstrong/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 29.0.0 rc3

Build Information: 
Mono: mono/mono/2019-06@5608fe0abb3
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/chad.armstrong/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:42:44 UTC

=== Android Device Manager ===

Version: 1.2.0.115
Hash: 724ea69
Branch: remotes/origin/d16-3
Build date: 2019-09-19 20:43:06 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803020032
Git revision: cac56af22091d80a4c339532595ed90228d87eb0
Build date: 2019-10-04 06:43:01+00
Build branch: release-8.3
Xamarin extensions: 2fc34e1d5c594f52abf0e0e9e14f4945adec6c7f

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64


```

**Comment by whitneyschmidt** [comment]
@edenwaith Thank you for your feedback!

Could you attach small sample solution that reproduces the issue? That way we can test and reproduce the problem locally :)

**Comment by edenwaith** [comment]
@whitneyschmidt : I cannot share the original project, so I'd have to construct a new sample project to display the project.  In the meantime, here are a couple of additional references which discuss the existing issue and necessary workarounds to get VoiceOver to properly navigate through a horizontal collection view that is located within a table view cell:

- https://stackoverflow.com/questions/13448279/voice-over-can-only-see-a-page-of-a-uicollectionview
- https://www.blog.kevin-hirsch.com/tips-and-tricks-1-making-collection-views-inside-table-views-accessible/
- https://github.com/ashfurrow/Collection-View-in-a-Table-View-Cell/issues/12

Kevin Hirsch's blog entry seems to perfectly detail a solution I'd like to try, but the UIAccessibilityContainer protocol methods don't seem to be entirely handle properly by Xamarin.  So either something is not properly connected, or I am missing something to properly override the protocol methods.

I'll see if I can construct a small demo project as an example.

**Comment by whitneyschmidt** [comment]
@edenwaith Thanks for getting back with more info! 

I'll take a look at the links you posted, but a small sample is really the best way for us to investigate further.

**Comment by whitneyschmidt** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Comment by edenwaith** [comment]
I'll need to spin up a new example project and will provide the demo.
