### ISSUE TITLE
UIElements becomes inactive when RootViewController is set from SceneDelegate.cs on iOS 13.1 update 

### ISSUE THREAD

**Issue by theuchenna** [xamarin/xamarin-macios#7603]
@theuchenna Thank you for your feedback!

Could you please detail how this behavior was different before version 13.1? 

Additionally, could you attach your solution file so that we can try and reproduce this issue?

_Originally posted by @whitneyschmidt in https://github.com/xamarin/xamarin-macios/issues/7289#issuecomment-546061384_

Before the advent of iOS13, you can easily set any of the ViewController as your RootViewController
by writing the following code  in your AppDelegate.cs file

` Window = new UIWindow(UIScreen.MainScreen.Bounds);
            var storyBoard = UIStoryboard.FromName("Main", null);
            var mainViewController = storyBoard.InstantiateViewController("MainViewController") as MainViewController;
            this.SetWindow(Window);
            Window.RootViewController = mainViewController;`

Every works properly without any problems.

For iOS 13;
One can set the RootViewController of a window in the SceneDelegate.cs file. I used the following code to set the RootViewController of my window.

`  UIWindowScene WindowScene = new UIWindowScene(session, connectionOptions);
            Window = new UIWindow(WindowScene);
            var storyboard = UIStoryboard.FromName("Main", null);

            var mainViewController = storyboard.InstantiateViewController("MainViewController") as MainViewController;
            Window.RootViewController = mainViewController;
            Window?.MakeKeyAndVisible();
            this.SetWindow(Window);`

After loading up my RootViewController using this method, I discovered that I can't make input into any text field.

**Comment by whitneyschmidt** [comment]
@theuchenna thank you for including code snippets!

I tried to reproduce this issue, but was unable to with the given info (e.g. I don't know what template you are using or what the rest of your code looks like).

**_The best way for us to investigate is if you are able to attach a small sample solution that reproduces this issue._**

We look forward to hearing back from you!

**Comment by whitneyschmidt** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
