### ISSUE TITLE
ASWebAuthenticationSession Does not Launch in IOS 13

### ISSUE THREAD

**Issue by shudson302** [xamarin/xamarin-macios#7641]
With IOS 13 using ASWebAuthenticationSession does not launch the OAuth login window.    How can we specify the ASWebAuthenticationPresentationContextProviding interface in order for this to work in IOS 13?

See this article:

https://dev.to/robotsquidward/quick-guide-to-aswebauthenticationsession-api-changes-in-ios-13-4m8i

**Comment by whitneyschmidt** [comment]
Thank you for your feedback @shudson302 !

For us to investigate this further, could you please provide your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

**_The most useful thing you can provide is small sample solution that reproduces the issue._**

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
