### ISSUE TITLE
mtouch requires too strict response files (.rsp)

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#7644]
spec https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/response-file-compiler-option

This is not a common issue since the main producer (msbuild tasks) does _mostly_ match what _mtouch_ support.

### Steps to Reproduce

1. Create a `test.rsp` file
2. Add `-v -v` inside it (same line)
3. Run `mtouch` a first time
4. Replace the earlier line with `-v -v -v -v` (all on the same line)
5. Run `mtouch` again

### Expected Behavior

`mtouch` should ignore them (for caching purpose)

Code is in `CollectArgumentsForCache` (`cache.cs`) but expect a single option per line. 

In contrast the spec mention: _In a response file, multiple compiler options and source code files can appear on one line._

### Actual Behavior

Project is rebuilt as the `-v` are not ignored since they are all on the same line.

### Environment

master

### Additional

* Comments are not supported, i.e. changing the comment should not invalidate the cache

Spec: _Response files can have comments that begin with the # symbol._

Related to https://github.com/xamarin/xamarin-macios/issues/7514 but the issue is larger than it.

**Comment by rolfbjarne** [comment]
This is not an issue in .NET anymore.
