### ISSUE TITLE
[iOS] CultureInfo works differently on a simulator vs physical device

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/xamarin-macios#7676]
### Description

Not sure if this is an issue on older simulators, but I was just testing an app that gets current country by querying `RegionInfo.CurrentRegion`. It looks like this property throws a `System.NotImplementedException` depending on how the thread culture is set.

### Steps to Reproduce

1. Run the attached app on iOS 12 simulator
2. Click the content button
3. Observe that the debugger throws an exception
4. Go to MainPage.xaml.cs and uncomment the line that sets `name` to `en-US`
5. Run the app again and observe that the exception is no longer thrown

### Expected Behavior

This issue does not exist on iOS or Android **devices** (did not test Android simulators). Simulators and devices should behave similarly, in my opinion.

### Actual Behavior
System.NotImplementedException: Neutral region info

A device defaults "en" to "en-US" whereas the simulator treats it as a neutral region since the country code was not provided when setting `CurrentCulture` and `CurrentUICulture`.

### Reproduction Link

[App1Test.zip](https://github.com/xamarin/Xamarin.Forms/files/2431921/App1Test.zip)

**Comment by chamons** [comment]
It appears we are invoking [this line of C#](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Globalization/RegionInfo.cs#L91) calling into mono [here](https://github.com/mono/mono/blob/master/mono/metadata/locales.c#L575).

That bit of mono digs [here](https://github.com/mono/mono/blob/master/mono/metadata/culture-info-tables.h#L1523), and respects US but not EN.

Then it falls and starts [here](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Globalization/RegionInfo.cs#L94), and from there we appear to be in mono BCL code (or CoreFX).

**Comment by chamons** [comment]
This issue was moved to mono/mono#18404
