### ISSUE TITLE
System.Reflection.DispatchProxy support

### ISSUE THREAD

**Issue by darkl** [xamarin/xamarin-macios#7679]
Hi,

I am wondering if the newest version of Xamarin.iOS supports `System.Reflection.DispatchProxy`. I know that it used to throw a `NotImplementedException` (see [here](https://github.com/Code-Sharp/WampSharp/issues/257)).

I was referred to this repository from the following [issue](https://github.com/dotnet/runtime/issues/1275).

Thanks
Elad

**Comment by chamons** [comment]
The documentation here:

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.dispatchproxy?view=netcore-3.1

suggests it works:
```
Xamarin.iOS
10.8
```

but I believe the best way to check would be to try it out. I've never used that class, so I'm not sure on it's exact usage.
