### ISSUE TITLE
Font Color not Visible in live site only

### ISSUE THREAD

**Issue by raj9772** [xamarin/xamarin-macios#7684]
When we save my site ( https://www.vanhorlicks.com/ ) in the local PC then show the font color but live website not show the font color. I have tired to check from google web tool or roboto.txt

**Comment by geek007322** [comment]
That looks awesome!😊👍

**Comment by chamons** [comment]
Thank you for your feedback, however I do not believe this is related to the Xamarin.iOS or Mac SDK.

Please reopen with concrete details and steps to reproduce if you believe this was done in error.
