### ISSUE TITLE
Could not AOT the assembly

### ISSUE THREAD

**Issue by lingvoamanto** [xamarin/xamarin-macios#7687]
I have cut the code right back two two classes that cause the error and believe the error is due to the interface file IRepository.cs. It works fine on the simulator, but fails when deploying to the device.

### Steps to Reproduce

1. Create a simple tabbed application
2. Use c# v8.
2. Add the microsoft data sqlite package
3. Add the two classes below

### Expected Behavior
Successfully deploys

### Actual Behavior
Could not AOT the assembly

### Environment

[OpenTrader-iPhone.zip](https://github.com/xamarin/xamarin-macios/files/4032870/OpenTrader-iPhone.zip)

### Build Logs

/Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2126,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
StockSource.cs(11,16,11,30): warning CS0414: The field 'StockSource.CellIdentifier' is assigned but its value is never used
/Users/mikaelaldridge/Projects/OpenTrader-iPhone/OpenTrader-iPhone/obj/iPhone/Debug/device-builds/iphone9.3-13.3/mtouch-cache/registrar.h(31,43): warning GBD8E3C1A: 'retain (or strong)' attribute on property 'window' does not match the property inherited from 'UIWindowSceneDelegate' [-Wproperty-attribute-mismatch]
/Users/mikaelaldridge/Projects/OpenTrader-iPhone/OpenTrader-iPhone/obj/iPhone/Debug/device-builds/iphone9.3-13.3/mtouch-cache/registrar.h(50,43): warning GBD8E3C1A: 'retain (or strong)' attribute on property 'window' does not match the property inherited from 'UIApplicationDelegate' [-Wproperty-attribute-mismatch]
MTOUCH : error MT3001: Could not AOT the assembly '/Users/mikaelaldridge/Projects/OpenTrader-iPhone/OpenTrader-iPhone/obj/iPhone/Debug/device-builds/iphone9.3-13.3/mtouch-cache/3-Build/OpenTrader_iPhone.exe'
    4 Warning(s)
    1 Error(s)

Time Elapsed 00:00:22.20

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 4 warnings

**Comment by chamons** [comment]
The attached project does not build for me with the errors in question:

```
Repository/Respository.cs(5,12,5,16): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'Mono' (are you missing an assembly reference?)
Repository/Respository.cs(6,7,6,13): error CS0246: The type or namespace name 'AppKit' could not be found (are you missing a using directive or an assembly reference?)
Repository/Respository.cs(28,23,28,39): error CS0246: The type or namespace name 'SqliteConnection' could not be found (are you missing a using directive or an assembly reference?)
Repository/Respository.cs(211,39,211,55): error CS0246: The type or namespace name 'SqliteDataReader' could not be found (are you missing a using directive or an assembly reference?)
Repository/Respository.cs(320,42,320,55): error CS0246: The type or namespace name 'SqliteCommand' could not be found (are you missing a using directive or an assembly reference?)
Repository/Respository.cs(25,26,25,42): error CS0246: The type or namespace name 'SqliteConnection' could not be found (are you missing a using directive or an assembly reference?)
```

even after restoring the nuget in question. Please attach a project showing the error in question.

**Comment by lingvoamanto** [comment]
* I have removed the obj and bin directories from attached zip file in order to get it to a size that GitHub will allow to be uploaded. You will need to remove Microsoft.Data.SQLite from the Packages folder and then readd it.  It then works fine.

[OpenTrader-iPhone.zip](https://github.com/xamarin/xamarin-macios/files/4036939/OpenTrader-iPhone.zip)

**Comment by lingvoamanto** [comment]
It is definitely in the IRepository interface. It seems the AOT compiler is not handling c# 8 interfaces properly, whereas it compiles fine for the simulator.

**Comment by chamons** [comment]
```    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/donblas/Downloads/OpenTrader-iPhone/OpenTrader-iPhone/obj/iPhone/Debug/response-file.rsp --registrar:dynamic 
    AOT Compilation exited with code 134, command:
    MONO_PATH=/Users/donblas/Downloads/OpenTrader-iPhone/OpenTrader-iPhone/obj/iPhone/Debug/mtouch-cache/3-Build /Library/Frameworks/Xamarin.iOS.framework/Versions/13.8.3.0/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=/Users/donblas/Downloads/OpenTrader-iPhone/OpenTrader-iPhone/obj/iPhone/Debug/mtouch-cache/arm64/OpenTrader_iPhone.aotdata.arm64,static,asmonly,direct-icalls,full,soft-debug,dwarfdebug,no-direct-calls,outfile=/Users/donblas/Downloads/OpenTrader-iPhone/OpenTrader-iPhone/obj/iPhone/Debug/mtouch-cache/arm64/OpenTrader_iPhone.exe.s "/Users/donblas/Downloads/OpenTrader-iPhone/OpenTrader-iPhone/obj/iPhone/Debug/mtouch-cache/3-Build/OpenTrader_iPhone.exe"
    Mono Ahead of Time compiler - compiling assembly /Users/donblas/Downloads/OpenTrader-iPhone/OpenTrader-iPhone/obj/iPhone/Debug/mtouch-cache/3-Build/OpenTrader_iPhone.exe
    AOTID EFB3E5A4-D207-4C6A-AD33-0BA60A4BC269
    * Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-08/ios/release/mono/mini/calls.c:336, condition `!rgctx_arg || !imt_arg' not met
    
    MTOUCH : error MT3001: Could not AOT the assembly '/Users/donblas/Downloads/OpenTrader-iPhone/OpenTrader-iPhone/obj/iPhone/Debug/mtouch-cache/3-Build/OpenTrader_iPhone.exe'
Done building target "_CompileToNative" in project "OpenTrader-iPhone.csproj" -- FAILED.```

This has the same root cause as https://github.com/mono/mono/issues/18276

**Comment by chamons** [comment]
From: https://github.com/mono/mono/issues/18276#issuecomment-572290249

> This fix will very likely be in d16-5 Preview 3, in preview likely mid-February and stable a month or two later.
> 
> If you'd like, I can point you to a build hot off our build machines if you want to try it sooner.
