### ISSUE TITLE
Xamarin.iOS project fails to build when referencing System.Reactive on Azure Build Machines 

### ISSUE THREAD

**Issue by nexxuno** [xamarin/xamarin-macios#7702]
Hello,
I'm opening this bug that looks very similar to #4629 

### Steps to Reproduce

1. Add a reference to latest system.reactive in a xamarin ios project
2. Try and build it in a azure CI pipeline on a MS hosted machine

### Expected Behavior
Builds successfully

### Actual Behavior
Doesn't build, see log below.

### Environment
Azure hosted pipeline macOS

### Build Logs
Log with additional mtouch -v -v -v -v
[log.txt](https://github.com/xamarin/xamarin-macios/files/4052925/log.txt)

**Comment by rolfbjarne** [comment]
You're using Xamarin.iOS 11.14.0.13, which is almost 18 months old (the same version as the reporter of #4629 was using).

This explains how to select the Xamarin.iOS version: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=designer#xamarin

Please use the newest version of Xamarin.iOS, and feel free to reopen this bug if that doesn't work and we'll have a look at it again.

**Comment by nexxuno** [comment]
Thanks. Since I didn't specify any specific version and as far as I know you don't specify that in any file of the solution, why is it taking such an old version by default on devops machines? Am I missing something?

Anyway this problem is fixed, thanks.

**Comment by rolfbjarne** [comment]
> why is it taking such an old version by default on devops machines?

I don't know, Azure is usually somewhat behind our stable releases (because we release fairly often and there's a non-significant amount of work for them to add new software to their base images), but this seems rather excessive. I don't know more than that, so if you want to dig further the next step would be to contact the Azure team and ask them.
