### ISSUE TITLE
Xamarin.Mac: Remove/stub out 32-bit only frameworks (QuickTime, QTKit, QuartzComposer)

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#7704]
We're currently shipping bindings for a few 32-bit only macOS-specific frameworks (QUickTime, QTKit, QuartzComposer). This is redundant since we don't support 32-bit Xamarin.Mac apps anymore.

The enhancement would be to either:

* Remove these bindings (would be a breaking change, most space saved).
* Stub them out and make them throw an exception (no breaking changes, but less space saved).

Ref: #6300.

**Comment by spouliot** [comment]
* QuickTime - we never bound the old (32bits only) C API -> nothing to do
* QTKit - we have bindings, there's no header anymore so it's unusable
* QuartzComposer - it's deprecated, but it's still present on 10.15 (not 32bits only) and pass our tests (intro, xtro)

I wrote a quick tool to stub code, I'll PR the QTKit stuff. Even stubbed it still saves about 150kb of code/metadata.
