### ISSUE TITLE
Xamarin: Getting error MT0145 when using ARMv7k, ARM64_32 in release mode

### ISSUE THREAD

**Issue by IntuitiveCode** [xamarin/xamarin-macios#7709]
### Steps to Reproduce

1. set watch extension build configuration to release
2. set supported architectures to ARMv7k, ARM64_32.
3. Build> Archive for Publishing

### Expected Behavior
Create an archive
### Actual Behavior
produces error "MT0145: Please use device specific builds on WatchOS when building for Debug."
### Environment
Visual Studio 8.4.1, Xcode 11.3

```
```

**Comment by chamons** [comment]
@IntuitiveCode - Please attach a full build log showing the issue.

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!

**Comment by onurhazar** [comment]
Please reopen the issue. We have the same error when attempt to build for physical device.

**Comment by chamons** [comment]
@onurhazar Please open a new issue and attach the requested information, without build logs and versions info it is not actionable.

**Comment by joeka-N** [comment]
We are facing the same issue when we are targeting both architectures ARMv7k and ARM64_32, the apple watch extension doesn't build.
any idea ?

**Comment by chamons** [comment]
@joeka-N As requested above, please open a new issue and attach the required information (build log, sample project showing issue). Without that, people are at best guessing.

**Comment by joeka-N** [comment]
> @joeka-N As requested above, please open a new issue and attach the required information (build log, sample project showing issue). Without that, people are at best guessing.

this issue is resolved as per my comment in [#7982]
