### ISSUE TITLE
Missing NSScrollView.WillStartLiveScrollNotification and NSScrollView.Notifications.ObserveWillStartLiveScroll

### ISSUE THREAD

**Issue by aconcagua21** [xamarin/xamarin-macios#7712]
### Steps to Reproduce
Use intellisense or assembly browser to look up the  NSScrollView.WillStartLiveScrollNotification constant or try using it in the code.

### Expected Behavior
It should be there

### Actual Behavior
Its not there

### Environment
Xamarin.Mac 6.8.3.0

### Build Logs
error CS0117: 'NSScrollView' does not contain a definition for 'WillStartLiveScrollNotification'

**Comment by chamons** [comment]
extro agrees:

```
tests/xtro-sharpie/macOS-AppKit.ignore:!missing-field! NSScrollViewWillStartLiveScrollNotification not bound
```
