### ISSUE TITLE
when builds xamarin ios project

### ISSUE THREAD

**Issue by EngPeterMaged** [xamarin/xamarin-macios#7715]
Severity	Code	Description	Project	File	Line	Suppression State

Error		Could not link assemblies. Reason: Error while processing references of 'Presentation, Version=2.3.3.32176, Culture=neutral, PublicKeyToken=null'	Presentation

**Comment by johnDoe619** [comment]
Try Clean and rebuild, or delete bin, obj, restart VS, clean and rebuild. Sometimes it works for me, could be different for you

**Comment by chamons** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by spouliot** [comment]
A `2001` error means something has gone wrong in the linker pipeline (which is used to load assemblies, even if not linking them).

Scanning the logs you'll find the reason why, in the last case:

```
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Topten.RichTextKit, Version=0.1.118.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Topten.RichTextKit, Version=0.1.118.0, Culture=neutral, PublicKeyToken=null'
```

It means that your code (some binary) refers to an assembly that is not found by the linker.

It’s a potential runtime issue for the simulator (JIT) but it’s a compile time error (linker or AOT) for device builds.

From the logs you can see it’s referenced from
```
   Loaded assembly 'MorePath.Skia, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' from MyPath/MyProject/bin/Debug/netstandard2.0/MorePath.Skia.dll
        References: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
        References: 'MorePath.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
        References: 'SkiaSharp, Version=1.68.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
        References: 'Topten.RichTextKit, Version=0.1.118.0, Culture=neutral, PublicKeyToken=null'
```

If you add a reference to that missing assembly/nuget then it should build just fine.

**Comment by nor0x** [comment]
thanks for the explanation this is really helpful for me while i'm investigating the logs 👍

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
