### ISSUE TITLE
error MT2101: Can't resolve the reference 'System.String[] System.String::Split(System.Char,System.StringSplitOptions)', referenced from the method 'UIKit.UIFont Xamarin.Forms.Platform.iOS.FontExtensions::_ToNativeFont(System.String,System.Single,Xamarin.Forms.FontAttributes)

### ISSUE THREAD

**Issue by johnDoe619** [xamarin/xamarin-macios#7719]
failing when building on Azure DevOps (formerly VSTS) using the Microsoft Hosted MacOS agent, mac-os-10.14

### Steps to Reproduce

1. Update Xcode Version, Xamarin forms, SDK, and Nuget
2. Build project
3. ---

### Expected Behavior
Compiles successfully without any build error 

### Actual Behavior
Build fails with error MT4109

### Environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.4.1 (build 4)
Installation UUID: 1b63757d-df76-44cf-be32-c4667c711155
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.100/Sdks
SDK Versions:
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0
	3.0.1
	3.0.0
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.2

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Version: 6.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin.iOS ===

Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin Designer ===

Version: 16.4.0.478
Hash: 95f0ab363
Branch: remotes/origin/d16-4
Build date: 2020-01-08 23:59:46 UTC

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed
Android SDK: /Users/name/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/name/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-08 19:54:56 UTC

=== Android Device Manager ===

Version: 16.4.0.28
Hash: 68e9956
Branch: remotes/origin/d16-4
Build date: 2020-01-08 19:55:18 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 804010004
Git revision: 5f675128315bd5886b283aa192b334a02bc8a758
Build date: 2020-01-10 13:54:46+00
Build branch: release-8.4
Xamarin extensions: 6e5c119bf1e7b092680c1491be659f152329f74e

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64


```

### Build Logs
_DetectDebugNetworkConfiguration:
    DebugIPAddresses: 
_CompileAppManifest:
  Directory "bin/iPhone/AppStore/Mobile.AccuRound.iOS.app.dSYM" doesn't exist. Skipping.
_ParseExtraMtouchArgs:
    NoSymbolStrip Output: False
    NoDSymUtil Output: false
_CompileToNative:
  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/runner/runners/2.163.1/work/1/s/I/Mobile.AccuRound/Mobile.AccuRound.iOS/obj/iPhone/Ad-Hoc/response-file.rsp 
MTOUCH : error MT2101: Can't resolve the reference 'System.String[] System.String::Split(System.Char,System.StringSplitOptions)', referenced from the method 'UIKit.UIFont Xamarin.Forms.Platform.iOS.FontExtensions::_ToNativeFont(System.String,System.Single,Xamarin.Forms.FontAttributes)' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [/Users/runner/runners/2.163.1/work/1/s/Mobile.AccuRound/Mobile.AccuRound.iOS/Mobile.AccuRound.iOS.csproj]

Done Building Project "/Users/runner/runners/2.163.1/work/1/s/.Mobile/Mobile.AccuR/Mobile.AccuRound.iOS/Mobile.AccuRound.iOS.csproj" (default targets) -- FAILED.

"/Users/runner/runners/2.163.1/work/1/s/.Mobile/Mobile.AccuRound/Mobile.AccuRound.iOS/Mobile.AccuRound.iOS.csproj" (default target) (1) ->
  /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Roslyn/Microsoft.CSharp.Core.targets(84,5): warning MSB3052: The parameter to the compiler is invalid, '/define:AD-HOC' will be ignored. [/Users/runner/runners/2.163.1/work/1/s/.Mobile/Mobile.AccuRound/Mobile.AccuRound.iOS/Mobile.AccuRound.iOS.csproj]

"/Users/runner/runners/2.163.1/work/1/s/.Mobile/Mobile.AccuRound/Mobile.AccuRound.iOS/Mobile.AccuRound.iOS.csproj" (default target) (1) ->
(_CompileToNative target) -> 
  MTOUCH : error MT2101: Can't resolve the reference 'System.String[] System.String::Split(System.Char,System.StringSplitOptions)', referenced from the method 'UIKit.UIFont Xamarin.Forms.Platform.iOS.FontExtensions::_ToNativeFont(System.String,System.Single,Xamarin.Forms.FontAttributes)' in 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. 
[/Users/runner/runners/2.163.1/work/1/s/.Mobile/Mobile.AccuRound/Mobile.AccuRound.iOS/Mobile.AccuRound.iOS.csproj]
    1 Error(s)

Time Elapsed 00:00:43.36
##[debug]rc:1
##[debug]success:false
##[debug]task result: Failed
##[error]Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild failed with return code: 1. For guidance on setting up the build pipeline, see https://go.microsoft.com/fwlink/?LinkId=760847.
##[debug]Processed: ##vso[task.issue type=error;]Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild failed with return code: 1. For guidance on setting up the build pipeline, see https://go.microsoft.com/fwlink/?LinkId=760847.
##[debug]Processed: ##vso[task.complete result=Failed;]Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild failed with return code: 1. For guidance on setting up the build pipeline, see https://go.microsoft.com/fwlink/?LinkId=760847.
##[section]Finishing: Build Xamarin.iOS csproj

### Example Project (If Possible)

n/a

**Comment by chamons** [comment]
This looks a lot like:

https://github.com/xamarin/xamarin-macios/issues/4609

where the mono on the system was much too old.

Is the environment posted in the issue your local dev machine or the build agent in question?

**Comment by johnDoe619** [comment]
> This looks a lot like:
> 
> #4609
> 
> where the mono on the system was much too old.
> 
> Is the environment posted in the issue your local dev machine or the build agent in question?

Its the local dev machine

**Comment by chamons** [comment]
Contact the Azure DevOps folks and ask them to update their mono, or see if you can update it as part of your build. 

If you find that the mono is recent mono 6.6 or something, please reopen and we'll look at some more.
