### ISSUE TITLE
Incorrect binding NSMenuToolbarItem: missing correct constructor (AppKit)

### ISSUE THREAD

**Issue by Sevenish** [xamarin/xamarin-macios#7720]
`NSMenuToolbarItem` does not have a correct constructor defined.

The native `NSMenuToolbarItem` uses the init inherited from the base init method `initWithItemIdentifier:` from `NSToolbarItem`

**Comment by chamons** [comment]
I believe we have this bound correctly. See the definition here:

https://github.com/xamarin/xamarin-macios/blob/master/src/appkit.cs#L19823

If you believe this is incorrect, please post an example ObjC or C# program that shows your issue.

**Comment by Sevenish** [comment]
Oh I am sorry, Don't know how this happend. But I put the wrong class in this issue. It is `NSMenuToolbarItem` that is missing the constructor

**Comment by Sevenish** [comment]
I am no binding export but it probably needs that exact same constructor binding that you linked to for NSToolbarItemGroup. They both inherit from NSToolbarItem and both do not have their own initializers.

**Comment by chamons** [comment]
I believe we have that as well?

https://github.com/xamarin/xamarin-macios/blob/master/src/appkit.cs#L19825

**Comment by Sevenish** [comment]
You are linking to NSToolbarItemGroup. BUT I am talking about **NSMenuToolBarItem**
**NSMenuToolBarItem** is new in 10.15

No initWithItemIdentifier constructor there:
https://github.com/xamarin/xamarin-macios/blob/master/src/appkit.cs#L27436

**Comment by haritha-mohan** [comment]
Issue fixed in [15087](https://github.com/xamarin/xamarin-macios/pull/15087)
