### ISSUE TITLE
Xamarin iOS app won't launch after upgrade to Xcode 11.3.1 and Xamarin.IOS 13.10.0.17

### ISSUE THREAD

**Issue by rdorta** [xamarin/xamarin-macios#7730]
### Steps to Reproduce

1. Upgrade Xcode to version 11.3.1
2. Upgrade Visual Studio for Mac to version 8.4.1
3. Upgrade Xamarin.iOS to version 13.10.0.17

### Expected Behavior
App will continue to launch as it was in previous versions

Works with:
[WorkingDev2.txt](https://github.com/xamarin/xamarin-macios/files/4091346/WorkingDev2.txt)
[WorkingDev1.txt](https://github.com/xamarin/xamarin-macios/files/4091347/WorkingDev1.txt)

### Actual Behavior
Application terminates upon launch with error message:
dyld: symbol '_mono_interp_callbacks_pointer' not found

### Environment
```
=== Visual Studio Community 2019 for Mac ===

Version 8.4.1 (build 4)
Installation UUID: 2178346c-a6bf-47b3-b670-7975d09b3e63
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.100/Sdks
SDK Versions:
	3.1.100
	3.0.101
	3.0.100
	2.2.300
	2.2.107
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0
	3.0.1
	3.0.0
	3.0.0-preview5-27626-15
	2.2.5
	2.1.14
	2.1.13
	2.1.9

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/ricardodorta/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/ricardodorta/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-08 19:54:56 UTC

=== Android Device Manager ===

Version: 16.4.0.28
Hash: 68e9956
Branch: remotes/origin/d16-4
Build date: 2020-01-08 19:55:18 UTC

=== Xamarin.iOS ===

Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin Designer ===

Version: 16.4.0.478
Hash: 95f0ab363
Branch: remotes/origin/d16-4
Build date: 2020-01-08 23:59:46 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 804010004
Git revision: 5f675128315bd5886b283aa192b334a02bc8a758
Build date: 2020-01-10 13:54:46+00
Build branch: release-8.4
Xamarin extensions: 6e5c119bf1e7b092680c1491be659f152329f74e

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Sun Dec  1 18:59:03 PST 2019
    root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.Forms HotReload extension 1.4.0
LiveXAML 1.3.51


```

### Build Logs

Project builds correctly as it was before.

[BuildInfo.txt](https://github.com/xamarin/xamarin-macios/files/4091258/BuildInfo.txt)

### Crash Logs
[CrashLogs.txt](https://github.com/xamarin/xamarin-macios/files/4091329/CrashLogs.txt)

### Example Project (If Possible)

I will try to reproduce in a smaller project to be able to share.

**Comment by rdorta** [comment]
Important information about this project is that we have multiple native bindings that use swift. We use this package to control the versions and copy the required dylibs to the final package.
https://github.com/Flash3001/Xamarin.Swift
But that should not interfere with Mono specific dylibs.

**Comment by rdorta** [comment]
Updated info on 2 working dev environments and added CrashLog from the device

**Comment by spouliot** [comment]
to note
```
Termination Description: DYLD, symbol '_mono_interp_callbacks_pointer' not found, expected in '/private/var/containers/Bundle/Application/FFA36EA6-4A30-451F-85A5-2DABC801A511/[Redacted].iOS.app/Frameworks/Mono.framework/Mono', needed by '/private/var/containers/Bundle/Application/FFA36EA6-4A30-451F-85A5-2DABC801A511/[Redacted].iOS.app/[Redacted].iOS'
```
it's the Mono.framework (not lib mono) being used.

I wonder if this it could be hot-reload enabled (with newer IDE) and the lack of (confirmed) support for interpreter inside `Mono.framework` ?

**Comment by spouliot** [comment]
discussions happening on gitter 
internal link: https://xamarinhq.slack.com/archives/C99ER4A1M/p1579612768000100

**Comment by rdorta** [comment]
Disabled Hot Reload and removed interpreter flag from build.

App still won't start but with a different crash error:
[CrashLogsWithoutHotReload.txt](https://github.com/xamarin/xamarin-macios/files/4091791/CrashLogsWithoutHotReload.txt)

**Comment by spouliot** [comment]
@rdorta can you double check that a clean and rebuild lead to the same crash ? it's unrelated (90%) and is not a place that should fail (unless something is out-of-sync in the build)

Also 
* can you try with `--mono=static` in your debug projects ? that will switch to the libmono (library) instead of the framework;
* see if the release version launch fine;

I'll try to set up a similar (assuming it's a hotreload/interpreter/framework issue) project on my side to see if I can duplicate the issue. Thanks!

**Comment by rdorta** [comment]
@spouliot sorry for the late feedback, the clean rebuild seemed to make it work. But without the interpreter. If I turn on the interpreter, it starts happening again.

**Comment by spouliot** [comment]
@rdorta could you answer the above questions ?

> can you try with --mono=static in your debug projects ?

> see if the release version launch fine;

**Comment by gianlucaparadise** [comment]
I had the same problem and I fixed it upgrading Xamarin.iOS to version 13.10.0.21

**Comment by whitneyschmidt** [comment]
@gianlucaparadise Thanks for posting about how you resolved the issue!

@rdorta - we have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
