### ISSUE TITLE
Redundant EnsureUIThread assertion in NSColorSpace.SRGBColorSpace

### ISSUE THREAD

**Issue by aconcagua21** [xamarin/xamarin-macios#7731]
All NSColorSpace getters that return predefined color spaces (like SRGBColorSpace),  contain redundant NSApplication.EnsureUIThread() assertion, that makes them unusable in background threads, although they're perfectly OK with it.

### Steps to Reproduce
Call NSColorSpace.SRGBColorSpace getter from background thread.

### Expected Behavior
Should proceed

### Actual Behavior
Will throw

### Environment
Xamarin.Mac 6.8.3.0

**Comment by chamons** [comment]
Thanks for the report!

Do you know of a sample or documentation that says NSColorSpace can be used off of the main UI thread or uses it that way?

By default we mark all APIs as requiring the UI thread, as Apple is not always clear what just works vs what works now but will corrupt your state in a future update.

You can disable this by setting [this](https://github.com/xamarin/xamarin-macios/blob/master/src/AppKit/NSApplication.cs#L34) to false with:

`NSApplication.CheckForIllegalCrossThreadCalls = false;`

**Comment by chamons** [comment]
Ok, I ran an obj-c sample with the apple thread checker:

```
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        NSColorSpace * s = [NSColorSpace sRGBColorSpace];
    });
```

and documentation suggests (but not states) that CoreGraphics can work on non-ui threads.

**Comment by aconcagua21** [comment]
Hi, thank you for response and sorry for being late.

The documentation of NSColor states that NSColor is thread-safe, and couple of it's methods work with NSColorSpace. Therefore, also NSColorSpace should be thread safe, although it's not an implication and it does not mean that also NSColorSpace class getters are TS. But it wouldn't make sense otherwise. Besides, we've been using it bkg threads without a hitch, and the Internet believes that CA and CG frameworks are generally TS.

**Comment by chamons** [comment]
NSColor already has ThreadSafe applied. #7740 will add them to NSColorSpace.

**Comment by chamons** [comment]
Fixed in master. Will be in d16-6 later this year.
