### ISSUE TITLE
iOS AOT Exception: VAR 0 (T1) cannot be expanded with type 0x11

### ISSUE THREAD

**Issue by balbarak** [xamarin/xamarin-macios#7734]
### Steps to Reproduce

Direct Steps:

1. Unzip 
[3-Build.zip](https://github.com/xamarin/xamarin-macios/files/4148723/3-Build.zip)

2. Run make
3. 
```
MONO_PATH=. /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/arm64-darwin-mono-sgen --debug -O=gsharedvt -O=-float32  --aot=mtriple=arm64-ios,data-outfile=Microsoft.Extensions.DependencyModel.aotdata.arm64,static,asmonly,direct-icalls,interp,full,soft-debug,dwarfdebug,no-direct-calls,outfile=Microsoft.Extensions.DependencyModel.dll.s Microsoft.Extensions.DependencyModel.dll
Mono Ahead of Time compiler - compiling assembly /Users/donblas/Desktop/3-Build/Microsoft.Extensions.DependencyModel.dll
AOTID 9521AEA2-F876-F399-7F1B-4E2607B30474
* Assertion at /Users/builder/jenkins/workspace/archive-mono/2019-08/ios/release/mono/mini/mini-generic-sharing.c:1228, condition `is_ok (error)' not met, function:get_wrapper_shared_vtype, VAR 0 (T1) cannot be expanded with type 0x11

``` 

Original Steps:

1. `Enable the Mono interpreter` from `iOS Build` options
2. Add `Microsoft.Extensions.DependencyInjection` package in Xamarin.Forms library project
3. Build the porject

### Expected Behavior
it should build successfully

### Actual Behavior
Project is not built

### Environment
Visual Studio for mac v8.4.2 (build 59)

```
```

### Build Logs

`MTOUCH: Error MT3001: Could not AOT the assembly '/**/**/Microsoft.Extensions.DependencyModel.dll' (MT3001)`

**Comment by chamons** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide your **full build logs**, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by StevenGranados** [comment]
I have also been having this issue for a couple of months.
Here is the build log and version info.
[version-info.txt](https://github.com/xamarin/xamarin-macios/files/4108014/version-info.txt)
[Output-Build.txt](https://github.com/xamarin/xamarin-macios/files/4108006/Output-Build.txt)
As for a repro, for me this only occurs with the mono interpreter enabled on iPhone and not the simulator. I attempted a repro but I got a "codesign exited with code 1" error I believe due to lack of certificates for the new project.
Personally my project also uses EFCore if it's any help.

**Comment by kaniosm** [comment]
Same issue here with VS 2019

**Comment by chamons** [comment]
I'm having trouble reproducing this on latest stable. 

Can you please attach a test project that reproduces it?

**Comment by kaniosm** [comment]
I'm having trouble to reproduce on a separate project too!
I'm comparing the new projects side by side...
Same references, same configuration, even deleted the cache at the Mac!
I'll let you know if I manage to reproduce it! I might move the whole project to a fresh project

**Comment by kaniosm** [comment]
I managed to reproduce the issue!
The problem seems to be caused by Microsoft.EntityFrameworkCore.Sqlite 3.1.1
When I switched to version 2.2.6 I don't get this error.
You can identify the issue in the project attached.


[App3.zip](https://github.com/xamarin/xamarin-macios/files/4142723/App3.zip)

**Comment by robertsundstrom** [comment]
I experience the same issue.

**Comment by chamons** [comment]
This issue was moved to mono/mono#18676

**Comment by chamons** [comment]
Thanks for the sample, it was very helpful and I've been able to isolate it to a one line command that reproduces and send it to the runtime team.

**Comment by balbarak** [comment]
Thanks for your help and support

**Comment by Licantrop0** [comment]
experiencing the same while compiling iOS in appcenter, will downgrade EntityFrameworkCore, thanks!

**Comment by BobbyCannon** [comment]
Having this issue with EF Core 3.1.3, I have not figured out a workout. Do we have to wait for updates with Xamarin?

**Comment by chamons** [comment]
We are waiting on https://github.com/mono/mono/issues/18676 being fixed.

**Comment by samirchakour-crossover** [comment]
Is there any fix for this issue ? I am facing the same with EntityFrameworkCore 3.1.3!
