### ISSUE TITLE
Objective Sharpie fails after generating bindings when copying files

### ISSUE THREAD

**Issue by michaelstonis** [xamarin/xamarin-macios#7743]
### Steps to Reproduce

1. Install Objective Sharpie `3.4.47-7642024`
2. From a terminal run `sharpie pod init ios IQKeyboardManager`
3. Upon completion, run `sharpie pod bind`

### Expected Behavior
Bindings will generate and all of the framework files, etc will be migrated over.

### Actual Behavior
Bindings appear to generate, but it will fail when it appears to be trying to copy over the framework files to the `Binding` directory. The framework folder will be there, but there will be no files within it. Application output included in build logs.

### Environment

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.4.2 (build 59)
Installation UUID: b4aedf2a-f9b0-4a1f-ac7e-801dde48510f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
SDK Versions:
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	3.0.100-rc1-014190
	2.2.402
	2.2.300
	2.2.107
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	3.0.0-rc1-19456-20
	3.0.0-preview8-28405-07
	2.2.7
	2.2.5
	2.1.15
	2.1.14
	2.1.13
	2.1.9

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Version: 6.10.0.17 (Visual Studio Enterprise)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin.iOS ===

Version: 13.10.0.17 (Visual Studio Enterprise)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin Designer ===

Version: 16.4.0.478
Hash: 95f0ab363
Branch: remotes/origin/d16-4
Build date: 2020-01-08 23:59:46 UTC

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Enterprise)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/mstonis/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/mstonis/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:04 UTC

=== Android Device Manager ===

Version: 16.4.0.30
Hash: f9172e2
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 804020059
Git revision: eb6fcdd83a227678e487aa733df3c8745f54fafc
Build date: 2020-01-17 12:12:02+00
Build branch: release-8.4
Xamarin extensions: ec32c90978c94f03d72f507b01f5aee70952ce87

=== Operating System ===

Mac OS X 10.15.2
Darwin 19.2.0 Darwin Kernel Version 19.2.0
    Sat Nov  9 03:47:04 PST 2019
    root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5
Xamarin.Forms HotReload extension 1.4.0
Continuous Coding 2.0.6
Internet of Things (IoT) extras 8.4
Comet.Reload.VSMac 0.1.2
Internet of Things (IoT) development (Preview) 8.4
FileNesting 0.1.2
Meadow 0.5.2
Android Signature Tool 2.2.0
AddinMaker 1.5.0
NuGet Package Explorer 0.4


```

### Build Logs

```
** BUILD SUCCEEDED **

Parsing 1 header files...

Binding...
  [write] ApiDefinitions.cs
  [write] StructsAndEnums.cs

Binding Analysis:
  Automated binding is complete, but there are a few APIs which have been flagged with [Verify] attributes. While the entire binding should be audited for best API
  design practices, look more closely at APIs with the following Verify attribute hints:

  MethodToProperty (10 instances):
    An Objective-C method was bound as a C# property due to convention such as taking no parameters and returning a value (non-void return). Often methods like these
    should be bound as properties to surface a nicer API, but sometimes false-positives can occur and the binding should actually be a method.

  ConstantsInterfaceAssociation (3 instances):
    There's no foolproof way to determine with which Objective-C interface an extern variable declaration may be associated. Instances of these are bound as [Field]
    properties in a partial interface into a nearby concrete interface to produce a more intuitive API, possibly eliminating the 'Constants' interface altogether.

  Once you have verified a Verify attribute, you should remove it from the binding source code. The presence of Verify attributes intentionally cause build failures.
  
  For more information about the Verify attribute hints above, consult the Objective Sharpie documentation by running 'sharpie docs' or visiting the following URL:

    http://xmn.io/sharpie-docs

Done.

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Mono.Unix.Native.Syscall' threw an exception. ---> System.DllNotFoundException: /Library/Frameworks/ObjectiveSharpie.framework/Versions/3.4.47/../lib/libMonoPosixHelper.dylib
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall:get_at_fdcwd ()
  at Mono.Unix.Native.Syscall..cctor () [0x0000a] in <046e822f7a9d4e47a2b412ddee64d670>:0 
   --- End of inner exception stack trace ---
  at Mono.Unix.UnixSymbolicLinkInfo.GetFileStatus (System.String path, Mono.Unix.Native.Stat& stat) [0x00000] in <046e822f7a9d4e47a2b412ddee64d670>:0 
  at Mono.Unix.UnixFileSystemInfo.Refresh (System.Boolean force) [0x00014] in <046e822f7a9d4e47a2b412ddee64d670>:0 
  at Mono.Unix.UnixFileSystemInfo..ctor (System.String path) [0x0001f] in <046e822f7a9d4e47a2b412ddee64d670>:0 
  at Mono.Unix.UnixSymbolicLinkInfo..ctor (System.String path) [0x00000] in <046e822f7a9d4e47a2b412ddee64d670>:0 
  at Sharpie.PodTool+PodBindTool.CopyDirectory (Sharpie.FilePath sourceDir, Sharpie.FilePath destDir) [0x0008c] in /Users/builder/vsts-agent/_work/5/s/Sharpie/PodTool.cs:329 
  at Sharpie.PodTool+PodBindTool.Run () [0x001ca] in /Users/builder/vsts-agent/_work/5/s/Sharpie/PodTool.cs:314 
  at Sharpie.Tooling.Tool.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x0011c] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/Tool.cs:180 
  at Sharpie.Tooling.ToolRunnerTool.Run () [0x000eb] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:95 
  at Sharpie.Tooling.Tool.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x0011c] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/Tool.cs:180 
  at Sharpie.Tooling.ToolRunnerTool.Run () [0x000eb] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:95 
  at Sharpie.Tooling.Tool.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x0011c] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/Tool.cs:180 
  at Sharpie.Tooling.ToolRunnerTool.Run (System.Collections.Generic.IEnumerable`1[T] args, System.Action`1[T] aboutToRunToolHandler) [0x00008] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:68 
  at Sharpie.Entry.Main (System.String[] args) [0x00142] in /Users/builder/vsts-agent/_work/5/s/Sharpie/Entry.cs:89 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Mono.Unix.Native.Syscall' threw an exception. ---> System.DllNotFoundException: /Library/Frameworks/ObjectiveSharpie.framework/Versions/3.4.47/../lib/libMonoPosixHelper.dylib
  at (wrapper managed-to-native) Mono.Unix.Native.Syscall:get_at_fdcwd ()
  at Mono.Unix.Native.Syscall..cctor () [0x0000a] in <046e822f7a9d4e47a2b412ddee64d670>:0 
   --- End of inner exception stack trace ---
  at Mono.Unix.UnixSymbolicLinkInfo.GetFileStatus (System.String path, Mono.Unix.Native.Stat& stat) [0x00000] in <046e822f7a9d4e47a2b412ddee64d670>:0 
  at Mono.Unix.UnixFileSystemInfo.Refresh (System.Boolean force) [0x00014] in <046e822f7a9d4e47a2b412ddee64d670>:0 
  at Mono.Unix.UnixFileSystemInfo..ctor (System.String path) [0x0001f] in <046e822f7a9d4e47a2b412ddee64d670>:0 
  at Mono.Unix.UnixSymbolicLinkInfo..ctor (System.String path) [0x00000] in <046e822f7a9d4e47a2b412ddee64d670>:0 
  at Sharpie.PodTool+PodBindTool.CopyDirectory (Sharpie.FilePath sourceDir, Sharpie.FilePath destDir) [0x0008c] in /Users/builder/vsts-agent/_work/5/s/Sharpie/PodTool.cs:329 
  at Sharpie.PodTool+PodBindTool.Run () [0x001ca] in /Users/builder/vsts-agent/_work/5/s/Sharpie/PodTool.cs:314 
  at Sharpie.Tooling.Tool.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x0011c] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/Tool.cs:180 
  at Sharpie.Tooling.ToolRunnerTool.Run () [0x000eb] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:95 
  at Sharpie.Tooling.Tool.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x0011c] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/Tool.cs:180 
  at Sharpie.Tooling.ToolRunnerTool.Run () [0x000eb] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:95 
  at Sharpie.Tooling.Tool.Run (System.Collections.Generic.IEnumerable`1[T] args) [0x0011c] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/Tool.cs:180 
  at Sharpie.Tooling.ToolRunnerTool.Run (System.Collections.Generic.IEnumerable`1[T] args, System.Action`1[T] aboutToRunToolHandler) [0x00008] in /Users/builder/vsts-agent/_work/5/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:68 
  at Sharpie.Entry.Main (System.String[] args) [0x00142] in /Users/builder/vsts-agent/_work/5/s/Sharpie/Entry.cs:89 
```

**Comment by dalexsoto** [comment]
Hello, we have an experimental version of sharpie, could you give this one a try and see if it fixes your issue?

[ObjectiveSharpie-3.5.17.zip](https://github.com/xamarin/xamarin-macios/files/4104464/ObjectiveSharpie-3.5.17.zip)

**Comment by michaelstonis** [comment]
This does resolve the issue. I tried it against a handful of bindings that I was running into issues with and everything outputs as expected!

Thanks!

**Comment by jameslavery** [comment]
> Hello, we have an experimental version of sharpie, could you give this one a try and see if it fixes your issue?
> 
> [ObjectiveSharpie-3.5.17.zip](https://github.com/xamarin/xamarin-macios/files/4104464/ObjectiveSharpie-3.5.17.zip)

I had the same problem as @michaelstonis.  I've downloaded 3.5.17, but am getting the error below. Does this version need a different mono runtime or something?

> Unhandled Exception:
> System.DllNotFoundException: libmono-native-compat.dylib assembly:<unknown assembly> type:<unknown type> member:(null)
>   at (wrapper managed-to-native) Interop+Sys.OpenDir(string)
>   at System.IO.Enumeration.FileSystemEnumerator`1[TResult].CreateDirectoryHandle (System.String path, System.Boolean ignoreNotFound) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs:81 
>   at System.IO.Enumeration.FileSystemEnumerator`1[TResult]..ctor (System.String directory, System.IO.EnumerationOptions options) [0x00048] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs:49 
>   at System.IO.Enumeration.FileSystemEnumerable`1+DelegateEnumerator[TResult]..ctor (System.IO.Enumeration.FileSystemEnumerable`1[TResult] enumerable) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerable.cs:57 
>   at System.IO.Enumeration.FileSystemEnumerable`1[TResult]..ctor (System.String directory, System.IO.Enumeration.FileSystemEnumerable`1+FindTransform[TResult] transform, System.IO.EnumerationOptions options) [0x00042] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerable.cs:29 
>   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles (System.String directory, System.String expression, System.IO.EnumerationOptions options) [0x00014] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerableFactory.cs:90 
>   at System.IO.Directory.InternalEnumeratePaths (System.String path, System.String searchPattern, System.IO.SearchTarget searchTarget, System.IO.EnumerationOptions options) [0x0003c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Directory.cs:178 
>   at System.IO.Directory.EnumerateFiles (System.String path, System.String searchPattern, System.IO.EnumerationOptions enumerationOptions) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Directory.cs:207 
>   at System.IO.Directory.EnumerateFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Directory.cs:204 
>   at Sharpie.FilePath+<EnumerateFiles>d__23.MoveNext () [0x00026] in /Users/runner/runners/2.164.6/work/1/s/Sharpie.Core/FilePath.cs:119 
>   at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00029] in <e22351e395f44d7b8c4860fca2dcee71>:0 
>   at System.Linq.Enumerable+ConcatIterator`1[TSource].MoveNext () [0x0002b] in <e22351e395f44d7b8c4860fca2dcee71>:0 
>   at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () [0x00038] in <e22351e395f44d7b8c4860fca2dcee71>:0 
>   at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:1108 
>   at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:87 
>   at Sharpie.Tooling.ToolRunnerTool..ctor (System.Collections.Generic.IEnumerable`1[T] toolAssemblies) [0x00031] in /Users/runner/runners/2.164.6/work/1/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:46 
>   at Sharpie.Entry+SharpieToolRunnerTool..ctor (System.Collections.Generic.IEnumerable`1[T] toolAssemblies) [0x00000] in /Users/runner/runners/2.164.6/work/1/s/Sharpie/Entry.cs:24 
>   at Sharpie.Entry.Main (System.String[] args) [0x0013b] in /Users/runner/runners/2.164.6/work/1/s/Sharpie/Entry.cs:87 
> [ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: libmono-native-compat.dylib assembly:<unknown assembly> type:<unknown type> member:(null)
>   at (wrapper managed-to-native) Interop+Sys.OpenDir(string)
>   at System.IO.Enumeration.FileSystemEnumerator`1[TResult].CreateDirectoryHandle (System.String path, System.Boolean ignoreNotFound) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs:81 
>   at System.IO.Enumeration.FileSystemEnumerator`1[TResult]..ctor (System.String directory, System.IO.EnumerationOptions options) [0x00048] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs:49 
>   at System.IO.Enumeration.FileSystemEnumerable`1+DelegateEnumerator[TResult]..ctor (System.IO.Enumeration.FileSystemEnumerable`1[TResult] enumerable) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerable.cs:57 
>   at System.IO.Enumeration.FileSystemEnumerable`1[TResult]..ctor (System.String directory, System.IO.Enumeration.FileSystemEnumerable`1+FindTransform[TResult] transform, System.IO.EnumerationOptions options) [0x00042] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerable.cs:29 
>   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles (System.String directory, System.String expression, System.IO.EnumerationOptions options) [0x00014] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Enumeration/FileSystemEnumerableFactory.cs:90 
>   at System.IO.Directory.InternalEnumeratePaths (System.String path, System.String searchPattern, System.IO.SearchTarget searchTarget, System.IO.EnumerationOptions options) [0x0003c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Directory.cs:178 
>   at System.IO.Directory.EnumerateFiles (System.String path, System.String searchPattern, System.IO.EnumerationOptions enumerationOptions) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Directory.cs:207 
>   at System.IO.Directory.EnumerateFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/Directory.cs:204 
>   at Sharpie.FilePath+<EnumerateFiles>d__23.MoveNext () [0x00026] in /Users/runner/runners/2.164.6/work/1/s/Sharpie.Core/FilePath.cs:119 
>   at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00029] in <e22351e395f44d7b8c4860fca2dcee71>:0 
>   at System.Linq.Enumerable+ConcatIterator`1[TSource].MoveNext () [0x0002b] in <e22351e395f44d7b8c4860fca2dcee71>:0 
>   at System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () [0x00038] in <e22351e395f44d7b8c4860fca2dcee71>:0 
>   at System.Collections.Generic.List`1[T].AddEnumerable (System.Collections.Generic.IEnumerable`1[T] enumerable) [0x00059] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:1108 
>   at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00062] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:87 
>   at Sharpie.Tooling.ToolRunnerTool..ctor (System.Collections.Generic.IEnumerable`1[T] toolAssemblies) [0x00031] in /Users/runner/runners/2.164.6/work/1/s/Sharpie.Core/Tooling/ToolRunnerTool.cs:46 
>   at Sharpie.Entry+SharpieToolRunnerTool..ctor (System.Collections.Generic.IEnumerable`1[T] toolAssemblies) [0x00000] in /Users/runner/runners/2.164.6/work/1/s/Sharpie/Entry.cs:24 
>   at Sharpie.Entry.Main (System.String[] args) [0x0013b] in /Users/runner/runners/2.164.6/work/1/s/Sharpie/Entry.cs:87
