### ISSUE TITLE
"Debug|iPhoneSimulator" disappeared in Visual Studio for Mac

### ISSUE THREAD

**Issue by arivoir** [xamarin/xamarin-macios#7751]
I'm trying to run a Xamarin.iOS project in Visual studio for Mac, but the "Debug|iPhoneSimulator" configuration is not available, only "Debug" and "Release" appear

<img width="297" alt="image" src="https://user-images.githubusercontent.com/17496741/73033289-48d4c280-3e20-11ea-9c62-c712df3def21.png">

When inspecting the "Options" of the solution I see the configurations are there

<img width="287" alt="image" src="https://user-images.githubusercontent.com/17496741/73033460-d3b5bd00-3e20-11ea-945e-d557283b0c74.png">

Unfortunately the Debug configuration doesn't run 

> MTOUCH: Error MT0074: Xamarin.iOS 13.10.0 does not support a deployment target of 13.3 for iOS (the maximum is 13.2). Please select an older deployment target in your project's Info.plist or upgrade to a newer version of Xamarin.iOS. (MT0074) (Test2)

I tried downloading previous simulators from Xcode, but they don't appear either.

The issue is reproducible creating a blank project.

Visual studio for Mac Enterprise 8.4.2 (build 59)
Xamarin.iOS Version: 13.10.0.17

**Comment by chamons** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide a test case (to reproduce) and all your version information.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

I suspect that your solution is misconfigured, but without an example it is difficult to determine what's going on.

We look forward to hearing from you!

**Comment by arivoir** [comment]
The repro steps are the following

- Open Visual Studio for Mac.
- Create New Project.
- Choose Single iOS App.
- Enter Name and press "Create".
- Open configuration combo box and only "Debug" and "Release" are present.

Here is the solution file


> Microsoft Visual Studio Solution File, Format Version 12.00
> # Visual Studio 15
> Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Test3", "Test3.csproj", "{2EE668DA-EB20-44D7-883C-78B0FF9B7CD0}"
> EndProject
> Global
> 	GlobalSection(SolutionConfigurationPlatforms) = preSolution
> 		Debug|iPhoneSimulator = Debug|iPhoneSimulator
> 		Release|iPhoneSimulator = Release|iPhoneSimulator
> 		Debug|iPhone = Debug|iPhone
> 		Release|iPhone = Release|iPhone
> 	EndGlobalSection
> 	GlobalSection(ProjectConfigurationPlatforms) = postSolution
> 		{2EE668DA-EB20-44D7-883C-78B0FF9B7CD0}.Debug|iPhoneSimulator.ActiveCfg = Debug|iPhoneSimulator
> 		{2EE668DA-EB20-44D7-883C-78B0FF9B7CD0}.Debug|iPhoneSimulator.Build.0 = Debug|iPhoneSimulator
> 		{2EE668DA-EB20-44D7-883C-78B0FF9B7CD0}.Release|iPhoneSimulator.ActiveCfg = Release|iPhoneSimulator
> 		{2EE668DA-EB20-44D7-883C-78B0FF9B7CD0}.Release|iPhoneSimulator.Build.0 = Release|iPhoneSimulator
> 		{2EE668DA-EB20-44D7-883C-78B0FF9B7CD0}.Debug|iPhone.ActiveCfg = Debug|iPhone
> 		{2EE668DA-EB20-44D7-883C-78B0FF9B7CD0}.Debug|iPhone.Build.0 = Debug|iPhone
> 		{2EE668DA-EB20-44D7-883C-78B0FF9B7CD0}.Release|iPhone.ActiveCfg = Release|iPhone
> 		{2EE668DA-EB20-44D7-883C-78B0FF9B7CD0}.Release|iPhone.Build.0 = Release|iPhone
> 	EndGlobalSection
> EndGlobal

And here is the visual studio information

> === Visual Studio Enterprise 2019 for Mac ===
> 
> Version 8.4.2 (build 59)
> Installation UUID: 93af0e06-190e-4a4c-98b0-7379db2cc831
> 	GTK+ 2.24.23 (Raleigh theme)
> 	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)
> 
> 	Package version: 606000155
> 
> === Mono Framework MDK ===
> 
> Runtime:
> 	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
> 	Package version: 606000155
> 
> === Roslyn (Language Service) ===
> 
> 3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d
> 
> === NuGet ===
> 
> Version: 5.3.0.6192
> 
> === .NET Core SDK ===
> 
> SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
> SDK Versions:
> 	3.1.101
> 	3.1.100
> 	3.0.101
> 	3.0.100
> 	2.1.701
> 	2.1.700
> 	2.1.505
> 	2.1.504
> 	2.1.503
> 	2.1.302
> 	2.1.301
> 	2.1.4
> 	2.0.0
> 	1.0.3
> MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks
> 
> === .NET Core Runtime ===
> 
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Versions:
> 	3.1.1
> 	3.1.0
> 	3.0.1
> 	3.0.0
> 	2.1.15
> 	2.1.14
> 	2.1.13
> 	2.1.12
> 	2.1.11
> 	2.1.9
> 	2.1.8
> 	2.1.7
> 	2.1.2
> 	2.1.1
> 	2.0.5
> 	2.0.0
> 	1.1.1
> 	1.0.4
> 
> === Xamarin.Profiler ===
> 
> Version: 1.6.12.26
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> === Updater ===
> 
> Version: 11
> 
> === Xamarin.Android ===
> 
> Version: 10.1.3.7 (Visual Studio Enterprise)
> Commit: xamarin-android/d16-4/d66aed0
> Android SDK: /Users/alvaror/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		8.1 (API level 27)
> 
> SDK Tools Version: 26.1.1
> SDK Platform Tools Version: 29.0.5
> SDK Build Tools Version: 29.0.2
> 
> Build Information: 
> Mono: fd9f379
> Java.Interop: xamarin/java.interop/d16-4@c4e569f
> ProGuard: xamarin/proguard/master@905836d
> SQLite: xamarin/sqlite/3.28.0@46204c4
> Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b
> 
> === Microsoft Mobile OpenJDK ===
> 
> Java SDK: /Users/alvaror/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
> 1.8.0-25
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> === Android SDK Manager ===
> 
> Version: 16.4.0.9
> Hash: 3f7256f
> Branch: remotes/origin/d16-4
> Build date: 2020-01-14 22:19:04 UTC
> 
> === Android Device Manager ===
> 
> Version: 16.4.0.30
> Hash: f9172e2
> Branch: remotes/origin/d16-4
> Build date: 2020-01-14 22:19:24 UTC
> 
> === Xamarin Inspector ===
> 
> Version: 1.4.3
> Hash: db27525
> Branch: 1.4-release
> Build date: Mon, 09 Jul 2018 21:20:18 GMT
> Client compatibility: 1
> 
> === Xamarin Designer ===
> 
> Version: 16.4.0.478
> Hash: 95f0ab363
> Branch: remotes/origin/d16-4
> Build date: 2020-01-08 23:59:46 UTC
> 
> === Apple Developer Tools ===
> 
> Xcode 11.3.1 (15715)
> Build 11C504
> 
> === Xamarin.Mac ===
> 
> Version: 6.10.0.17 (Visual Studio Enterprise)
> Hash: 5f802ef53
> Branch: xcode11.3
> Build date: 2020-01-07 11:53:06-0500
> 
> === Xamarin.iOS ===
> 
> Version: 13.10.0.17 (Visual Studio Enterprise)
> Hash: 5f802ef53
> Branch: xcode11.3
> Build date: 2020-01-07 11:53:06-0500
> 
> === Build Information ===
> 
> Release ID: 804020059
> Git revision: eb6fcdd83a227678e487aa733df3c8745f54fafc
> Build date: 2020-01-17 12:12:02+00
> Build branch: release-8.4
> Xamarin extensions: ec32c90978c94f03d72f507b01f5aee70952ce87
> 
> === Operating System ===
> 
> Mac OS X 10.15.2
> Darwin 19.2.0 Darwin Kernel Version 19.2.0
>     Sat Nov  9 03:47:04 PST 2019
>     root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
> 
>

**Comment by chamons** [comment]
I believe this is expected behavior and not a bug. We no longer swap between Sim and Device here:

![image](https://user-images.githubusercontent.com/6392201/73304819-95cce600-41de-11ea-8468-ca6298eef3ba.png)

but in the second device button here:

![image](https://user-images.githubusercontent.com/6392201/73304848-a2513e80-41de-11ea-95a3-5f1705b3f1b6.png)

Does that make sense? If not, please explain what exactly is broken.

**Comment by arivoir** [comment]
In that case there are 2 bugs.

1) Some projects are actually loading the "Debug|iPhoneSimulator" in the vs4mac first combobox
<img width="498" alt="image" src="https://user-images.githubusercontent.com/17496741/73312814-67640080-4208-11ea-9581-08ab48b66fb8.png">

2) There is something that doesn't allow the projects to build. Neither the default project created with the default project is working.
The building error is the following

> /Users/alvaror/Projects/Test3/MTOUCH: Error MT0074: Xamarin.iOS 13.10.0 does not support a deployment target of 13.3 for iOS (the maximum is 13.2). Please select an older deployment target in your project's Info.plist or upgrade to a newer version of Xamarin.iOS. (MT0074) (Test3)

I suspect this error is because the incorrect configuration is loaded somewhere.

**Comment by arivoir** [comment]
I forgot to mention that the same projects that aren't building in vs4mac build fine in vs4win

**Comment by chamons** [comment]
On this:

```
    /Users/alvaror/Projects/Test3/MTOUCH: Error MT0074: Xamarin.iOS 13.10.0 does not support a deployment target of 13.3 for iOS (the maximum is 13.2). Please select an older deployment target in your project's Info.plist or upgrade to a newer version of Xamarin.iOS. (MT0074) (Test3)
```

This is actually only half a bug, as our release notes document:

```
Xcode 11.3 doesn't ship an iOS/tvOS 13.3 SDK, therefore the maximum deployment target remains 13.2
```

The IDE shouldn't suggest 13.2, but Xcode doesn't ship a 13.3 SDK with Xcode 13.3, only 13.2 

Changing your info.plist to 13.2 will solve that.

On the other one, if you can attach a project showing that, I'll pass it on to the IDE folks for consideration.

**Comment by arivoir** [comment]
The problem in the default template project is the default target is 13.3, changing it to 13.2 works. It's weird a newest version exist and appear but it doesn't work.

The I found a series of problems that apparently are unrelated, but strangely only apear in vs4mac, and were working in previous versions.

Some projects had the following code

```
  <PropertyGroup Condition=" '$(OS)' == 'Unix' ">
    <CscToolExe>mcs.exe</CscToolExe>
  </PropertyGroup>
```

This was because it was needed when vs4mac just appeared. Now this provokes a building error

> Error CS1617: Invalid -langversion option `7.3'. It must be `ISO-1', `ISO-2', Default, Latest or value in range 1 to 7.2 (CS1617) (C1Gauge101)

When a project doesn't have a &lt;OutputPath&gt; set for the current configuration it doesn't allow to build in vs4mac

**Comment by chamons** [comment]
Please don't set CscToolExe unless absolutely necessary, we've been using csc for a number of releases, and mcs is not tested or significantly maintained. 

And yes, we expect OutputPath to be set to have a sane build. You may want to compare your hand edited csproj files to a new project and see what settings you have that are no longer necessary.

If after that you are still having issues, please attach an example project.

**Comment by arivoir** [comment]
I think we don't need CscToolExe anymore, it was needed a time ago and remained in a set of samples.

Everything is running fine now. Anyway I don't understand how the first configuration combobox is populated in vs4mac. In some cases there is only "Debug" and "Release" but in others are a long list. What should I expect to see there?

**Comment by chamons** [comment]
I'm not honestly sure why it shows it differently. I'm asking around now. 

However, they both should work even if the UX is different.

**Comment by chamons** [comment]
I'm not sure why the differences in UX, I have not heard back. Would you like me to convert this to a IDE bug to request more, or should I consider this closed @arivoir ?

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
