### ISSUE TITLE
iOS App Crashes on Launch w/ Linker Set to "Don't Link"

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-macios#7775]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/858562/ios-app-crashes-on-launch-w-linker-set-to-dont-lin.html)._

---
A new Xamarin.Forms iOS app using Xamarin.Forms (4.4.x) crashes on launch for device builds with linker set to “don’t link.”

---
#### Visual Studio Feedback System on 12/18/2019, 01:32 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by chamons** [comment]
I'm not seeing this on 13.10.0.17 which is current stable. 

13.6 is before Xcode 11.3 support, but you are building with Xcode 11.3. 

Can you try updating and report back?
Can you post a device log or crash report showing the issue in question?

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
