### ISSUE TITLE
Where can I find standalone installers?

### ISSUE THREAD

**Issue by robertsundstrom** [xamarin/xamarin-macios#7792]
Where can I find standalone installers for Xamarin.iOS on macOS?

The version of VS 2019 (for Windows) Preview (Version 16.5.0 Preview 2.0) that I run just get stuck when attempting to download.

The version that I need is 13.14.1.17.

**Comment by chamons** [comment]
If you want them directly from our build lane (no QA) you can follow:

https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build

On occasion we do provide direct "released" URLs, specially when requested. That build is:

https://download.visualstudio.microsoft.com/download/pr/8c5f8169-31f5-4dec-a235-f3ad6feb713d/654793ae54b0ce7fa2c3d6209cf4bf29/xamarin.ios-13.14.1.17.pkg
