### ISSUE TITLE
Installing a new Xamarin.Mac framework does not uninstall the old ones

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#7800]
### Steps to Reproduce

1. Install 6.14.0.7
2. Install 6.14.1.17

### Expected Behavior

6.14.0.7 is uninstalled.

### Actual Behavior

6.14.0.7 is kept. This takes up disk space on the device.

```
➜ ls /Library/Frameworks/Xamarin.Mac.framework/Versions
6.14.0.7
6.14.1.14
6.14.1.23
```

**Comment by chamons** [comment]
This is expected, and how XI works as well.

Only the installers nuke the old version.

It makes it easy to swap back from your dev build to current stable.
