### ISSUE TITLE
Move RequiresSuper attribute so that it is not a subclass of AdviceAttribute

### ISSUE THREAD

**Issue by whitneyschmidt** [xamarin/xamarin-macios#7823]
This enhancement is to improve the Roslyn Xamarin.iOS analyzer experience in one edge case.

Currently there are two Xamarin.iOS analyzers in https://github.com/xamarin/CodeAnalysis/tree/master/src/Xamarin.CodeAnalysis/Apple

They both populate intellisense for the `[RequiresSuper]` attribute. XIA001 detects all Advice attributes, XIA specifically for the `[RequiresSuper]` attribute. As a result, there are two things populated for `[RequiresSuper]`. These two analyzers will be bundled into the same nuget package.

Moving the RequiresSuperAttribute avoid duplicate and potentially confusing messages.

```
ObjCRuntime/RequiresSuperAttribute.cs
//
// RequiresSuperAttribute.cs:
//
// Authors:
//   Sebastien Pouliot  <sebastien.pouliot@microsoft.com>
//
// Copyright 2017 Xamarin Inc.

using System;
using Foundation;

namespace ObjCRuntime {

        // https://clang.llvm.org/docs/AttributeReference.html#objc-requires-super-clang-objc-requires-super
        [AttributeUsage (AttributeTargets.Method, AllowMultiple = false)]
        public sealed class RequiresSuperAttribute : AdviceAttribute {
                public RequiresSuperAttribute ()
                        : base ("Overriding this method requires a call to the overriden method.")
                {
                }
        }
}
```

**Comment by spouliot** [comment]
That's a breaking change :(

Maybe the `[Advice]` analyzer can check the actual type and skip the `[RequiresSuper]` ?

**Comment by whitneyschmidt** [comment]
:( Modifying the analyzer to take into account this special is definitely an option. I will leave this issue open until I log an issue against the `CodeAnalysis` repo.

**Comment by kzu** [comment]
I think the tricky thing here @spouliot is how to distinguish this particular advice from others. The workaround in the https://github.com/xamarin/CodeAnalysis/pull/5 PR is to check for the string, which I think is brittle.

**Comment by spouliot** [comment]
@kzu long answer in https://github.com/xamarin/CodeAnalysis/pull/5#issuecomment-594280202

basically why can't the actual attribute type name be used ? That won't ever change, for the same reason the attribute must remain a subclass, since it would be a breaking change.

**Comment by rolfbjarne** [comment]
Closing, since I believe the correct solution is what @spouliot suggested in the previous comment.
