### ISSUE TITLE
mmp requesting System.Runtime.Loader dll even

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#7893]
### Steps to Reproduce

mmp should not be requesting System.Runtime.Loader library if it's included via packagereference. In a Full Framework/System mono configuration, it should consider dropping that reference, as it is a .netcore-only assembly and the nuget package itself does not contain a dll for full framework.
 
### Expected Behavior

`System.Runtime.Loader` assembly reference is discarded.

### Actual Behavior

A .netcore only assembly is being requested by mmp, and none of the other tools (msbuild, nuget), consider it.

### Environment

```
```

### Build Logs

https://gist.github.com/iainx/3c4c7d937f30555db726d2c7e7bb5f39

### Example Project (If Possible)

Not sure about a simplified sample, but I think it boils down to including Roslyn as a dependency in a XamMac app. cc @iainx 

### Context

1. Create a XamMac app
2. Switch to XamMac Full
3. Add System.Runtime.Loader package
4. Observe you can't use AssemblyLoadContext.

After some digging around, I found out the following info:

1. https://github.com/dotnet/sdk/issues/7915
2. https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-3.1 (try switching to any other target)
3. https://github.com/microsoft/msbuild/blob/86d9494e446de002ea6a4f08d6fbd111b1041059/src/Directory.BeforeCommon.targets#L120-L122

It seems like the nuget package is not supposed to work on .netframework. The Loader package only works on .netcore, and you need to add runtime checks for it to actually work. So the assembly reference to it exists, but it never is going to be used.

Not sure why the corefx team did a _._ folder for net462, probably so you can install it everywhere but still need a runtime check to use it. It’s even marked as a Facade in mono:
https://github.com/mono/mono/blob/master/mono/metadata/assembly.c#L257

**Comment by spouliot** [comment]
> it should consider dropping that reference, as it is a .netcore-only assembly

If you get there then it's being referenced by some other assembly.

> the nuget package itself does not contain a dll for full framework.

mmp does not know about nuget (or it's structure) but only about the binaries it's given. Some actions requires resolving references - but here the context is not complete,

Please add `-v -v -v -v` and attach/link to the complete build logs.

**Comment by Therzok** [comment]
> If you get there then it's being referenced by some other assembly.

Yeah, it's Roslyn. Roslyn builds against netstandard 2.0 thus brings in the netstandard assembly (with runtime checks to not use it). But a desktop app will use net462 when targeting, so it won't pull in the actual reference.

Is there any possibility to filter out dlls we _know_ won't be called?

**Comment by Therzok** [comment]
@spouliot From what @iainx tells me, that's with `-v -v -v -v`

**Comment by iainx** [comment]
I'll get the complete build logs now

**Comment by iainx** [comment]
and yes, a option to ignore certain dlls would be perfect

**Comment by iainx** [comment]
https://microsofteur-my.sharepoint.com/:u:/g/personal/iaholmes_microsoft_com/Efr4xwmRDuxDu5m3b3jeNeMBBLWWvVwMEV0fH4XkMNERrA?e=oFebfY

**Comment by iainx** [comment]
FWIW, this is blocking some important work on the VSMac side of things

**Comment by spouliot** [comment]
It's not linking so it should be possible (since we don't rewrite the assembly) to ignore a missing assembly (and let this fail at JIT/runtime is the code is ever reached).

**Comment by spouliot** [comment]
So I created a XM project, use Full, then add package Microsoft.CodeAnalysis.Scripting, so it refers to System.Runtime.Loader.dll (I could not use the package directly). The I added a reference to a type with 

```
Console.WriteLine (Microsoft.CodeAnalysis.Scripting.Hosting.MemberDisplayFormat.Hidden);
```

that would bring the dependency. It built fine and failed, like expected, at runtime (not at build time).

```
Could not find `System.Runtime.Loader` referenced by assembly `Microsoft.CodeAnalysis.Scripting, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35`.
Could not find `System.Runtime.Loader` referenced by assembly `gh7893, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`.
2020-02-14 14:45:13.084 gh7893[40127:30598597] 
Unhandled Exception:
System.IO.FileNotFoundException: Could not load the file 'System.Runtime.Loader'.
File name: 'System.Runtime.Loader'
  at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef, System.Security.Policy.Evidence assemblySecurity) [0x00073] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/corlib/System/AppDomain.cs:758 
  at (wrapper remoting-invoke-with-check) System.AppDomain.Load(System.Reflection.AssemblyName,System.Security.Policy.Evidence)
  at System.AppDomain.Load (System.Reflection.AssemblyName assemblyRef) [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/corlib/System/AppDomain.cs:724 
  at (wrapper remoting-invoke-with-check) System.AppDomain.Load(System.Reflection.AssemblyName)
  at System.Reflection.Assembly.Load (System.Reflection.AssemblyName assemblyRef) [0x00000] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/corlib/System.Reflection/Assembly.cs:440 
  at ObjCRuntime.Runtime.CollectReferencedAssemblies (System.Collections.Generic.List`1[T] assemblies, System.Reflection.Assembly assembly) [0x00085] in /Users/poupou/git/xamarin/xamarin-macios/src/ObjCRuntime/Runtime.cs:544 
  at ObjCRuntime.Runtime.CollectReferencedAssemblies (System.Collections.Generic.List`1[T] assemblies, System.Reflection.Assembly assembly) [0x00085] in /Users/poupou/git/xamarin/xamarin-macios/src/ObjCRuntime/Runtime.cs:544 
  at ObjCRuntime.Runtime.RegisterEntryAssembly (System.Reflection.Assembly entry_assembly) [0x00032] in /Users/poupou/git/xamarin/xamarin-macios/src/ObjCRuntime/Runtime.cs:505 
  at ObjCRuntime.Runtime.RegisterAssemblies () [0x00001] in /Users/poupou/git/xamarin/xamarin-macios/src/ObjCRuntime/Runtime.cs:481 
  at AppKit.NSApplication.Init () [0x00022] in /Users/poupou/git/xamarin/xamarin-macios/src/AppKit/NSApplication.cs:56 
  at gh7893.MainClass.Main (System.String[] args) [0x00001] in /Users/poupou/Projects/bugs/gh7893/Main.cs:9 
```

**Comment by spouliot** [comment]
Build logs shows warnings, like expected for failing to load `System.Runtime.Loader`

```
/Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(2101,5): warning MSB3277: Found conflicts between different versions of "System.Text.Encoding.CodePages" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
MMP : warning MM2013: Failed to resolve the reference to \"System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\", referenced in \"Microsoft.CodeAnalysis.CSharp.Scripting, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\". The app will not include the referenced assembly, and may fail at runtime.
MMP : warning MM2013: Failed to resolve the reference to \"System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\", referenced in \"Microsoft.CodeAnalysis.Scripting, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\". The app will not include the referenced assembly, and may fail at runtime.
MMP : warning MM2006: Native library 'Microsoft.DiaSymReader.Native.x86.dll' was referenced but could not be found.
MMP : warning MM2006: Native library 'Microsoft.DiaSymReader.Native.amd64.dll' was referenced but could not be found.
MMP : warning MM2006: Native library 'mscoree.dll' was referenced but could not be found.
MMP : warning MM2006: Native library 'clr' was referenced but could not be found.
    7 Warning(s)
    0 Error(s)
```

**Comment by spouliot** [comment]
So it works in some cases and I'm not sure why it does not in your :|
Can you attach a test case so we can debug it ? thanks!

**Comment by iainx** [comment]
Sadly the only test case we have is the pyro-broken branch of https://github.com/xamarin/vsmac

**Comment by iainx** [comment]
I suspect, but have no verified, that mmp makes it an error rather than a warning if Microsoft.CodeAnalysis.Scripting isn't a direct reference of the project, but a reference of a reference of the project. That's how it is in the vsmac project anyway.

**Comment by spouliot** [comment]
Yes, it's quite likely this is hitting a different code path that what I did.

@iainx is that _indirect_ reference public (so I can try this quickly) ?

**Comment by spouliot** [comment]
I moved the code to an assembly (dll) and referred it from a new app (exe) but it still fails at runtime (and not at build time).

note: `NSApplication.IgnoreMissingAssembliesDuringRegistration = true;` makes it work (at runtime).

**Comment by spouliot** [comment]
it might work on recent XM because of https://github.com/xamarin/xamarin-macios/pull/7628
which solves some linker behaviour changes (exceptions beings wrapped)
so the old (correct) behaviour is now present in `master` (and d16-6)
I'll double check that

**Comment by spouliot** [comment]
While not 100% conclusive the older versions of XM (without the PR above) behave identically with my test case.

**Comment by spouliot** [comment]
@iainx I did not have much luck in building that branch - and it conflicts with other stuff I need so everything takes longer. Can you zip me up the binaries ? since the problem starts with `mmp` then the build (from source) is already over so I should be able to repro with binaries only. Thanks!

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
