### ISSUE TITLE
MM0000: Unexpected error -> when using `--xml=${ProjectDir}` and `-v -v -v -v`

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#7904]
Split from https://github.com/xamarin/xamarin-macios/issues/7897

### Steps to Reproduce

1. Create a XM project
2. Add a linker definition file (.xml)
3. Add `--xml=file` to the additional mmp arguments
4. Add `-v -v -v -v` to the additional mmp arguments

### Expected Behavior

Success

### Actual Behavior

`MM0000`

https://github.com/xamarin/xamarin-macios/issues/7897#issuecomment-586413915

**Comment by spouliot** [comment]
c.c. @tipa

**Comment by spouliot** [comment]
```
MMP: Error MM2004: Extra linker definitions file 'mac/${ProjectDir}/linker.xml' could not be located. (MM2004)
```

I cannot duplicate the `MM0000` but it looks like `${ProjectDir}` is **not** expanded correctly, so what's given to `mmp` is incorrect.

@tipa try adding the full path (or a relative one) to the XML file.

**Comment by tipa** [comment]
Maybe you can reproduce the issue with this example project?
[LinkerProblem.zip](https://github.com/xamarin/xamarin-macios/files/4207197/LinkerProblem.zip)

It seems to work when using a relative Path like this: `--xml=LinkDescription.xml`
Is the mmp command always executed in the current project directory or could the relative path lead to problems when building via e.g. Azure Pipelines?

**Comment by spouliot** [comment]
I do not get the `MM0000` with the attached project - but the stack trace suggest it was an incorrect message format (and could have been fixed). I'll try again later with an older XM version.


With XI a `.csproj` with 
```
<MtouchExtraArgs>-v -v -xml=${ProjectDir}/extra-linker-defs.xml</MtouchExtraArgs>
```
result in the argument
```
 '-xml=/Users/poupou/git/d16-6/xamarin-macios/tests/linker/ios/link sdk/extra-linker-defs.xml'
```

but with XM (attached) `.csproj`
```
<MonoBundlingExtraArgs>--xml=${ProjectDir}/LinkDescription.xml</MonoBundlingExtraArgs>
```
results in 
```
/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp @/Users/poupou/Downloads/LinkerProblem/LinkerProblem/obj/Debug/response-file.rsp   --xml=${ProjectDir}/LinkDescription.xml  -q
```
where the variable was not expanded

**Comment by spouliot** [comment]
The `MM0000` happened with XM 6.10

```
Xamarin.Mac
Version: 6.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500
```

**Comment by spouliot** [comment]
Funny to debug since it's expanded in normal (console) projects (so it works)

The error is that it tries to log (`-v -v`) arguments and ends up trying to print
```
    '--xml=${xProjectDir}/LinkDescription.xml'
```
The extra `x` was to avoid the expansion of the variable while debugging.

Of course `Console.WriteLine` is not happy to see a `{xxx}` without any arguments and that throws an exception - which `mmp` translate into the an `MM0000`.

**Comment by spouliot** [comment]
The `MM2004` is appropriate with XM 6.14 (preview channel).

```
    MMP : error MM2004: Extra linker definitions file '/Users/poupou/Downloads/LinkerProblem/LinkerProblem/${ProjectDir}/LinkDescription.xml' could not be located.
```

```
Xamarin.Mac
Version: 6.14.1.24 (Visual Studio Community)
Hash: fa00d7a6
Branch: d16-5
Build date: 2020-01-28 19:38:51-0500
```

but it's **not** fixed. It's because there was a change of the default level of verbosity while logging. Adding `-v -v -v -v` to the attached project gives again the `MM0000`.

I'm opening a new one for the lack of expansion of `${ProjectDir}` since it's also a different issue from this one...
