### ISSUE TITLE
Variable `${ProjectDir}` is not expanded before reaching `mmp`

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#7918]
Split from https://github.com/xamarin/xamarin-macios/issues/7897 and https://github.com/xamarin/xamarin-macios/issues/7904

### Steps to Reproduce

1. Use the test case https://github.com/xamarin/xamarin-macios/files/4207197/LinkerProblem.zip 
2. Build project

### Expected Behavior

Works

### Actual Behavior

```
MMP : error MM2004: Extra linker definitions file '/Users/poupou/Downloads/LinkerProblem/LinkerProblem/${ProjectDir}/LinkDescription.xml' could not be located.
```

`mmp` is given `${ProjectDir}` directly - i.e. it's not expanded into the project directory (like it would be for XI/mtouch).

### Environment

With XM 6.10 (stable) you'll get a `MM0000` due to extra (default) `-v` verbosity. That's being handled int #7904

With XM 6.14 (preview) and more recent you'll get the above `MM2204`

> VS bug [#1090518](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1090518)

**Comment by rolfbjarne** [comment]
This is not applicable to .NET anymore.
