### ISSUE TITLE
Dependencies on Mono class libraries not present in dotnet/runtime

### ISSUE THREAD

**Issue by filipnavara** [xamarin/xamarin-macios#7924]
When running on .NET 5 runtime with the new class libraries the following dependencies are currently not available:

- [Mono.SystemDependencyProvider.Initialize](
https://github.com/xamarin/xamarin-macios/blob/master/src/ObjCRuntime/Runtime.cs#L256)
- [System.Threading._ThreadPoolWaitCallback.SetDispatcher](https://github.com/xamarin/xamarin-macios/blob/59faa728cdd611d200d65c8858296a48b829eb9b/src/ObjCRuntime/Runtime.cs#L280)

Additionally, the version returned by [Mono.Runtime.GetDisplayName()](https://github.com/xamarin/xamarin-macios/blob/09cf9a92dc4df123c2382ce8e6555b553bed2928/src/ObjCRuntime/Runtime.mac.cs#L121-L152) may no longer be relevant.

Related to #7528.

**Comment by chamons** [comment]
Mostly FYI @rolfbjarne of possible implementation details noted by our community

**Comment by lambdageek** [comment]
Some of the previous `SetDispatcher` discussion is here: https://github.com/mono/mono/pull/17387#issuecomment-545540303

I don't think there's an issue open in dotnet/runtime about bringing (some form of) `SetDispatcher` back.

**Comment by filipnavara** [comment]
> I don't think there's an issue open in dotnet/runtime about bringing (some form of) `SetDispatcher` back.

No issue for that yet. I'll bring it up.

**Comment by marek-safar** [comment]
The work to clean up the binding to build against clean netcore app API has not been done so the binding still depends on some APIs not available on netcore

**Comment by lambdageek** [comment]
SystemDependencyProvider looks like some indirection that @baulig added to help `corlib` and `System` reference each other to get at the system cert store (I think).

So I think there are two possibilities (maybe Martin can correct me if I'm wrong):
1. This isn't needed in .NET 5 because there's some other mechanism to integrate the system cert store into the runtime
2. There's no such support in .NET 5 at all and work would need to be done on the .NET 5 libraries side.

**Comment by filipnavara** [comment]
The ThreadPool issue is [filed](https://github.com/dotnet/runtime/issues/32543).

`SystemDependencyProvider` is no longer necessary with the new BCL. The certificate APIs work just fine.

One thing I forgot about is that the `HttpClient` handlers may behave differently. I only checked it on macOS where the managed code was used by default and worked properly. It may be an issue on iOS though.

**Comment by filipnavara** [comment]
> The work to clean up the binding to build against pure netcore API has not been done so the bindings still depend on some APIs not available on netcore

I am aware of that. I've been building Xamarin myself with the problematic code patched out. I thought it may be useful to open an issue to give a perspective on the scope of the work necessary.

**Comment by baulig** [comment]
> SystemDependencyProvider looks like some indirection that @baulig added to help `corlib` and `System` reference each other to get at the system cert store (I think).

The sole purpose of this class is to inject APIs that reside in `System.dll` into `corlib.dll`, to allow code in corlib to access some of the crypto and certificate code that resides in `System.dll`.

I believe that we can simply short-circuit this for .NET 5 - remove that entire class (and it's implementations) completely and use the relevant APIs correctly.

**Comment by filipnavara** [comment]
This has been largely addressed by #8070. Remaining pieces are marked as `NET_TODO` in the source code and/or tracked in individual issues.
