### ISSUE TITLE
NSApplication.SharedApplication regression

### ISSUE THREAD

**Issue by m3th0d** [xamarin/xamarin-macios#7932]
### Steps to Reproduce

1. Download attached solution and open it in VS for Mac
2. Run OldXamMacTest project (uses Xamarin.Mac.dll 6.2.0.42, d16-3 / 5e8a208b5f44c4885060d95e3c3ad68d6a5e95e8 and corresponding libxammac.dylib) and wait for `SharedApplication = ...` output
3. Run NewXamMacTest project (uses Xamarin.Mac.dll 6.14.0.15, d16-5 / 5c5112e7d40276d8f82193935a66aab1cd5f944b and corresponding libxammac.dylib) and wait for `SharedApplication = ...` output

### Expected Behavior

Both OldXamMacTest and NewXamMacTest output `SharedApplication = <NSApplication: 0x...>` since they contain same code and the only thing changed is the _newer_ versions of XamarinMac.dll and libxammac.dylib are used

### Actual Behavior

OldXamMacTest outputs `SharedApplication = <NSApplication: 0x...>`
NewXamMacTest outputs `SharedApplication = null`

### Environment

```
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.6 Preview (8.6 build 2075)
Installation UUID: e2193507-a4e2-4e66-95a8-2443f5f2c6d2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.1 (d16-6 / ad6b9f582)

	Package version: 610000064

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.64 (2019-12/0011444f0b6) (64-bit)
	Package version: 610000064

=== Roslyn (Language Service) ===

3.5.0-beta2-20052-02+04aada103893143c9da8a96bdc465e106c1f0151

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.100/Sdks
SDK Versions:
	3.1.100
	3.1.100-preview3-014645
	2.2.203
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0
	3.1.0-preview3.19553.2
	2.2.4

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.2.99.193 (Visual Studio Community)
Commit: xamarin-android/master/2c24731
Android SDK: /Users/ab/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 27.0.0

Build Information: 
Mono: 8b72dbb
Java.Interop: xamarin/java.interop/master@d99c809
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@bfb66f3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/ab/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.27
Hash: 437a46c
Branch: remotes/origin/test-repair-on-xammac~1
Build date: 2020-02-07 02:17:52 UTC

=== Android Device Manager ===

Version: 16.6.0.48
Hash: c7a575a
Branch: remotes/origin/feature/emulator-tel-events~5
Build date: 2020-02-07 02:18:12 UTC

=== Apple Developer Tools ===

Xcode 11.3 (15712)
Build 11C29

=== Xamarin.Mac ===

Version: 6.9.0.13 (Visual Studio Community)
Hash: 5e52f30c0
Branch: xcode11.3
Build date: 2019-11-14 09:24:15-0500

=== Xamarin.iOS ===

Version: 13.14.1.17 (Visual Studio Community)
Hash: d30880059
Branch: d16-5
Build date: 2020-01-07 18:20:41-0500

=== Xamarin Designer ===

Version: 16.6.99.33
Hash: 58b0fe29c
Branch: fixes
Build date: 2020-02-13 12:03:11 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 806002075
Git revision: f8ed198cc33344f6680982c8ec6594d66aeae50c
Build date: 2020-02-11 04:55:50-05
Build branch: master
Xamarin extensions: f8ed198cc33344f6680982c8ec6594d66aeae50c

=== Operating System ===

Mac OS X 10.15.3
Darwin 19.3.0 Darwin Kernel Version 19.3.0
    Thu Jan  9 20:58:23 PST 2020
    root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

### Example Project (If Possible)

[XamMacTest.zip](https://github.com/xamarin/xamarin-macios/files/4219899/XamMacTest.zip)

**Comment by chamons** [comment]
So just running msbuild project.csproj with 6.10.0.17 "shows" this, and these are the MONO_LOG_LEVEL=debug logs, with pointers and names stripped out.

https://gist.github.com/chamons/cebcf791978209c785b6b1545ad0fe89

I need to install matching XM as noted as see if they still reproduce.

**Comment by chamons** [comment]
Still reproduces w\ matching XM from reporter.

**Comment by spouliot** [comment]
The root issue is that `NSApplication.class_ptr` is not valid (`IntPtr.Zero`) after `Init` is called.

This looks like a timing issue when using custom initialization. It's a bit hard to ensure `NSApplication.cctor` is not called before the native side is ready. As a comparison a _normal_ app bundle (.app) has a lot of things loaded/initialized before reaching the same code.

E.g. In the attached code just removing the line
```csharp
NSApplication.IgnoreMissingAssembliesDuringRegistration = false;
```

makes it work. The value (`false`) is not important, i.e. switching to `true` does not make it work. It's just the fact that the `NSApplication.cctor` gets called a bit (too) earlier. 

What you can do (that involves ObjC) before `NSApplicationMain` is called is rather limited (and undefined / subject to change).

In this case the timing window change was likely triggered by https://github.com/xamarin/xamarin-macios/commit/a239fa9ebd5071d9e72b1d3b72633e5b2864425e#diff-4aa19167162888aec0ccc2261a7ddbd3

Which removed a workaround from 2010 https://github.com/xamarin/maccore/commit/4fac0f3afa8fe4c07174b1bd250cce3f30368dd9
Itself modified in 2014 in https://github.com/xamarin/maccore/commit/c56f280069ea974d8d76cbc875d342c6f421df5c#diff-4aa19167162888aec0ccc2261a7ddbd3

**Comment by spouliot** [comment]
A workaround (until the fix is released) is to add the line'

```csharp
typeof (NSApplication).GetField ("class_ptr", BindingFlags.Static | BindingFlags.NonPublic).SetValue (null, Class.GetHandle ("NSApplication"));
```

just after your call to `Init`
