### ISSUE TITLE
[Documentation] 404 on 'Earlier version archive'

### ISSUE THREAD

**Issue by ColbyRingeisen** [xamarin/xamarin-macios#7939]
### Steps to Reproduce

1. Click 'Earlier version archive' link from left hand menu on page "https://docs.microsoft.com/en-us/xamarin/ios/release-notes/"
2. receive '404 - Page not found' error

### Expected Behavior
I expect the link to take me to earlier versions of the Xamarin.iOS release notes.

### Actual Behavior
404 - page not found

### Environment
Latest Edge browser

```
```

**Comment by chamons** [comment]
I can confirm. Thanks for the report.

**Comment by conceptdev** [comment]
The menu has been updated with the correct link to the [earlier versions](https://github.com/xamarin/release-notes-archive/tree/master/release-notes/ios).
