### ISSUE TITLE
mac: Inconsistent property naming in NSColor

### ISSUE THREAD

**Issue by hbons** [xamarin/xamarin-macios#7945]
It looks like NSColor has some properties with inconsistent naming. The intended scheme seems to be to remove redundant "Color" strings from the end of properties, but this isn't true for all of them.

### Steps to Reproduce

1. Type "NSColor." to open autocomplete list of properties
2. Notice some property names end in "Color" and others don't.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/103326/74889747-3f3c6d00-5382-11ea-9d99-f3da9fcfd0f8.png">

### Expected Behavior

Property names in NSColor should not end with "Color".

### Actual Behavior

Some property names end with "Color".

### Environment

=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.5 Preview (8.5 build 2739)
Installation UUID: 8f65d14f-fc2e-4997-a6c3-8b82c2dc6813
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.24 (d16-5 / fa00d7a6)

	Package version: 608000104

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.104 (2019-10/1cca0cfebfc) (64-bit)
	Package version: 608000104

=== Roslyn (Language Service) ===

3.4.0-beta4-19568-04+82f2e2541478e239dc4b04f231e90dc2b3dcb422

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.100/Sdks
SDK Versions:
	3.1.100
	3.0.100
	2.2.203
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.0
	3.0.0
	2.2.4
	2.1.14
	2.1.13
	2.1.9

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.2.0.84 (Visual Studio Community)
Commit: xamarin-android/d16-5/ac3f71f
Android SDK: /Users/hbons/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: df42020
Java.Interop: xamarin/java.interop/d16-5@c0cc770
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/hbons/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.38
Hash: 5adcbfa
Branch: remotes/origin/d16-5
Build date: 2020-01-24 03:00:54 UTC

=== Android Device Manager ===

Version: 16.5.0.65
Hash: 327dcef
Branch: remotes/origin/d16-5
Build date: 2020-01-24 03:01:14 UTC

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin Designer ===

Version: 16.5.0.459
Hash: 8aade6148
Branch: remotes/origin/d16-5
Build date: 2020-02-04 08:22:34 UTC

=== Xamarin.Mac ===

Version: 6.14.1.24 (Visual Studio Community)
Hash: fa00d7a6
Branch: d16-5
Build date: 2020-01-28 19:38:51-0500

=== Xamarin.iOS ===

Version: 13.14.1.24 (Visual Studio Community)
Hash: fa00d7a6
Branch: d16-5
Build date: 2020-01-28 19:38:52-0500

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805002739
Git revision: 263967358dccc898fdabde5fc9cc6fbd037580ef
Build date: 2020-02-06 16:15:04-05
Build branch: release-8.5-preview2.1
Xamarin extensions: 263967358dccc898fdabde5fc9cc6fbd037580ef

=== Operating System ===

Mac OS X 10.15.3
Darwin 19.3.0 Darwin Kernel Version 19.3.0
    Thu Jan  9 20:58:23 PST 2020
    root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

AddinMaker 1.5.0

**Comment by chamons** [comment]
You appear to be correct, we are inconsistent. 

However, as Xamarin.iOS and Mac has a strict API stability, we can't remove the older names until our next API break. We call this XAMCORE_4_0, based on our defines.

We could re-export them with two names, but I think that adds more confusion.

**Comment by knocte** [comment]
> We could re-export them with two names, but I think that adds more confusion.

Why not export them with two names, but mark the Color-ending ones with `[Obsolete]` attrib so that it doesn't show in intellisense?

**Comment by chamons** [comment]
We could, but it turns out there are a _lot_ of colors in https://github.com/xamarin/xamarin-macios/blob/master/src/appkit.cs and we are pretty inconsistent.
