### ISSUE TITLE
tSystem.Runtime.Serialization.SerializationException detected: Error in line 1 position 216. Expecting element 'ExceptionDetail' from namespace 'http://schemas.datacontract.org/2004/07/System.ServiceModel'.. Encountered 'Element'  with name 'ApiFault', namespace 'https://bingads.microsoft.com/Customer/v11'.. Thrown from: ExceptionDispatchInfo.Throw().\t0\t0\t1\tOnRetrying\tRetryPolicy\t

### ISSUE THREAD

**Issue by yingfangdu** [xamarin/xamarin-macios#7957]
### Steps to Reproduce

When Editor gets some fault exception from [a wcf service ](https://github.com/yingfangdu/TempFolder/blob/master/Reference.cs), It will will throw the errors like [this](https://github.com/yingfangdu/TempFolder/blob/master/exception.txt).
The fault response body is like the below image, while System.ServiceModel cannot de-serialize the fault exception to the proper one on Mac which should be 

`FaultException<Microsoft.AdvertisingDesktop.Sync.BingAds.CustomerManagementServiceV13.ApiFault`

In fact, it looks like trying to convert into 

`FaultException<ExceptionDetail>`

Response body from the service.
![image](https://user-images.githubusercontent.com/9310605/75067007-f16a5680-54a0-11ea-9c14-f6f63613bae1.png)

### Expected Behavior
Should convert to the proper exception.

### Environment
The latest Xamarin.Mac build I can get. Xamarin.Mac 6.18

```
```

**Comment by yingfangdu** [comment]
It is similar issue reported [here](https://forums.xamarin.com/discussion/72425/how-to-handle-fault-in-wcf-service-call).

**Comment by chamons** [comment]
This issue was moved to mono/mono#18996
