### ISSUE TITLE
error mt5212 with .a file on xamarin not on xcode project

### ISSUE THREAD

**Issue by jingliancui** [xamarin/xamarin-macios#7960]
https://1drv.ms/u/s!AiLsd2NKfovHnLVKTK0ZbzO-N1GREQ?e=t4wPgI

I had uploaded the zip file to onedrive because the .a file is about 180MB.
Then the .h file and the mtouchargument included in the zip file.

Step:
1.create an xcode project and import the .a file and the header file and the dependent framework which descripted in the mtouchargument.txt.Then invoke the .h api just for finished compile and running the app.Result→OK
2.Create normal iOS binding project an bind the .a file
3.create xamarin.ios project and use the dll file and invoke the dll's api , add the mtoucharguemt. Build project.Result->MT5212
4.Use the mt5212 tutorial checking the same sambol but show no sambol.

**Comment by jingliancui** [comment]
[api_struct.zip](https://github.com/xamarin/xamarin-macios/files/4243036/api_struct.zip)
here the binding api and struct files.

**Comment by jingliancui** [comment]
Is it possible about this two issue?
https://github.com/xamarin/xamarin-macios/pull/5876
https://github.com/xamarin/xamarin-macios/issues/4889

**Comment by chamons** [comment]
Thank you for your feedback and partial example project.

For us to investigate this further, could you attach the binding project itself, your version info, and the full build log. 

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

There are many ways to configure the csproj, and I'm not seeing the error in the version I tried.

**Comment by jingliancui** [comment]
@chamons Sure.you can download the zip file to review it here
https://1drv.ms/u/s!AiLsd2NKfovHnLVNfwbR4XVc9Zs9bw?e=SsxHLy

The native library is a 3rd party.
vs for mac info.txt→vs version 
xcode version.png→xcode version
app error message→vs for mac ios app build log.txt
binding success message→vs for mac binding build log.txt

binding is alway success.
xamarin app is alway error.
xcode project is alway succeed to run.
test device is iphone5s real phone and os version is 12.4.5.
osx is macOS Catalina version 10.15.3.
sharpie version is 3.5.22-be043142.

I have share all xcode project file and xamarin project file to you at the code project.zip.

demo the issue:
1.runing the binding project and build it result a dll file.
2.runing the xamarin project and reference the dll file .
3.rebuild the xamarin project.
4.result the error.

**Comment by chamons** [comment]
Your project is not setup in a way that works on other machines, with relative paths, but I believe I've reproduced your issue:

```
/Users/donblas/Downloads/GithubIssue/Archive/XamarinApp/DemoApp/DemoApp/error MT5209: Error: warning: ignoring file /Users/donblas/Downloads/GithubIssue/Archive/XamarinApp/DemoApp/DemoApp/obj/iPhoneSimulator/Debug/device-builds/iphone 11-13.3/mtouch-cache/libUxunThreeXinSDK.a, missing required architecture x86_64 in file /Users/donblas/Downloads/GithubIssue/Archive/XamarinApp/DemoApp/DemoApp/obj/iPhoneSimulator/Debug/device-builds/iphone 11-13.3/mtouch-cache/libUxunThreeXinSDK.a (2 slices) (DemoApp) Native linking
/Users/donblas/Downloads/GithubIssue/Archive/XamarinApp/DemoApp/DemoApp/MTOUCH: Error MT5211: Native linking failed, undefined Objective-C class: UxunThreeGorgesSDK. The symbol '_OBJC_CLASS_$_UxunThreeGorgesSDK' could not be found in any of the libraries or frameworks linked with your application. (MT5211) (DemoApp)
/Users/donblas/Downloads/GithubIssue/Archive/XamarinApp/DemoApp/DemoApp/MTOUCH: Error MT5202: Native linking failed. Please review the build log. (MT5202) (DemoApp)
/Users/donblas/Downloads/GithubIssue/Archive/XamarinApp/DemoApp/DemoApp/clang: Error: linker command failed with exit code 1 (use -v to see invocation) (DemoApp)```

The native library you are linking against only has slices for iOS devices, not simulator:

```
/Users/donblas/Downloads/GithubIssue/Archive/XamarinApp/DemoApp/DemoApp/obj/iPhoneSimulator/Debug/device-builds/iphone 11-13.3/mtouch-cache/libUxunThreeXinSDK.a (for architecture armv7):	current ar archive
/Users/donblas/Downloads/GithubIssue/Archive/XamarinApp/DemoApp/DemoApp/obj/iPhoneSimulator/Debug/device-builds/iphone 11-13.3/mtouch-cache/libUxunThreeXinSDK.a (for architecture arm64):	current ar archive
```

so it will fail if you try to build for simulator. You need to either rebuild your native library against x86_64, contact the vendor for that build, or not use iOS simulator.

**Comment by jingliancui** [comment]
@chamons ,I had used the device to build it not build for simulator, and it will built with error mt5212.
I know this .a file not have the x86_64.
But my issue is the mt5212 duplicate symbol and not other mt error issue

**Comment by jingliancui** [comment]
The key is that the xcode project can run normal in my device,and the Xamarin iOS project build error with mt5212.

**Comment by chamons** [comment]
See the documentation here for details: https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#mt5212-native-linking-failed-duplicate-symbol-

But converting your binding project to enable smart link "fixed" it for me.

https://gist.github.com/chamons/808a4d66b3150398b1c305bc4c39995d

**Comment by jingliancui** [comment]
@chamons Are your app of Xamarin project compile error fixed? Or just your binding project was fixed?

I follow your gist to edit my .csproj file:
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectTypeGuids>{8FFB629D-F513-41CE-95D2-7ECE97B6EEEC};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <ProjectGuid>{CD67B49C-AF81-466F-85D5-A991E57C1D92}</ProjectGuid>
    <TemplateGuid>{b6f3ff35-79b2-4f25-a2fc-60a7cf61013b}</TemplateGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>NativeLibrary</RootNamespace>
    <IPhoneResourcePrefix>Resources</IPhoneResourcePrefix>
    <AssemblyName>UxunHySDK</AssemblyName>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>full</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="Xamarin.iOS" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
  </ItemGroup>
  <ItemGroup>
    <ObjcBindingCoreSource Include="Structs.cs" />
  </ItemGroup>
  <ItemGroup>
    <NativeReference Include="libUxunThreeXinSDK.a">
      <Kind>Static</Kind>
      <IsCxx>True</IsCxx>
      <ForceLoad>True</ForceLoad>
    </NativeReference>
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.ObjCBinding.CSharp.targets" />
</Project>
```

binding project is always success.
app of xamarin project still show mt5212 error.
Are you sure your project run fine?
Can you provide the DLL file to text.

**Comment by jingliancui** [comment]
@chamons Hi, chamons.
I think What you should concern is that :
1.	The addition mtouch argument.
2.	In the Xamarin app(not binding project),If you do not invoke the api from the reference DLL file , VS will compile without any error(success).
If you have any question about these investigation work ,just ask me .
Thanks.

**Comment by chamons** [comment]
These are the only two files I changed, and yes, the device build completed with zero errors.

Changed I made:

- The binding project update (as noted before)
- Update your relative path to point to the correct location for the binding lib
- Remove the now unnecessary mtouch args

[Projects.zip](https://github.com/xamarin/xamarin-macios/files/4314568/Projects.zip)
