### ISSUE TITLE
/Users/aressmacmini110/Projects/Xamarin/hems-remote/EQ2/EQ2.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.String SQLitePCL.raw::sqlite3_errmsg(SQLitePCL.sqlite3)', referenced from the method 'System.String SQLite.SQLite3::GetErrmsg(SQLitePCL.sqlite3)' in 'SQLitePCLRaw.core, Version=1.1.11.121, Culture=neutral, PublicKeyToken=1488e028ca7ab535'. (MT2101) (EQ2.iOS)

### ISSUE THREAD

**Issue by SushmitaGupta** [xamarin/xamarin-macios#7972]
### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

**Comment by chamons** [comment]
Thank you for your feedback!

However, without any information beyond the error message in the title no one will be able to look into your issue/question.

Please file a new issue, fill out the template, and attach a build log/sample project.
