### ISSUE TITLE
Carplay: App don't show up & methods are not called

### ISSUE THREAD

**Issue by Suplanus** [xamarin/xamarin-macios#8020]
I want to make a blog post with a demo application for CarPlay in Xamarin.
In the Demo app I have a Audio player (Xamarin.Forms).

Found no other examples or references for Xamarin. Thats the reason why I want to share this 🦄

### Steps to Reproduce
Run the demo application.

### Expected Behavior

- App should be displayed in Carplay
- Methods in `AppDelegateDataSource` & `PlayableContentDelegate` don't called

### Actual Behavior

![image](https://user-images.githubusercontent.com/2002916/75609762-873e5b00-5b0b-11ea-8632-a9d0805f11b4.png)

### Example Project

You can run the application from [this repo](https://github.com/Suplanus/Xamarin.Demo.Carplay).

**Comment by chamons** [comment]
According to:

https://developer.apple.com/videos/play/wwdc2017/719/?time=185

```If you think your audio, automaker, messaging or VoIP calling app has the potential to be supported by CarPlay tell us about it at the CarPlay developer portal. There you'll be able to request an entitlement to get your app running in CarPlay```

So it sounds like you need to contact Apple for that entitlement.

**Comment by chamons** [comment]
If after getting that entitlement things do not work, please reopen with details.

**Comment by Suplanus** [comment]
The entitlement is not needed for simulator.
But I also ask Apple and got the entitlement for my provisioning profile.

Don't think this is the problem.

**Comment by chamons** [comment]
Ok, with the entitlement from Apple you are still seeing this @Suplanus in simulator? If so we can rule that out and investigate.

**Comment by Suplanus** [comment]
Yes, the problem is there. With and without the entitlement from Apple.
As I said, in the simulator you don't need the Apple entitlement.

I can't reopen the issue. Could you please reopen it?

Thanks for your feedback 🦄

**Comment by Suplanus** [comment]
I added a working [demo in swift](https://github.com/Suplanus/Xamarin.Demo.Carplay/tree/master/src/Swift).
Here you can see that no entitlement is needed for the simulator.

**Comment by chamons** [comment]
Interesting, reopening for consideration.

**Comment by chamons** [comment]
While you have the correct entitlement in the file, you weren't actually including it in your build.

Fixed in https://github.com/Suplanus/Xamarin.Demo.Carplay/pull/2

**Comment by Suplanus** [comment]
Oh my... 🤦‍♂️
Thanks a lot 💕

Good point to start. Will update with an hopefully blog post about Carplay & Xamarin here.
