### ISSUE TITLE
[Intents] Annotate breaking changes with XAMCORE_4_0

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/xamarin-macios#8024]
Apple made a lot of breaking changes (see the intents xtro `todo` files) like the one below on macOS and watchOS in Xcode 11, these we can't do right away because of our binary compatibility.

```diff
-API_AVAILABLE(ios(11.0), watchos(4.0), macosx(10.13))
+API_AVAILABLE(ios(11.0), watchos(4.0))
+API_UNAVAILABLE(macos, tvos)
 @interface INCallDestinationTypeResolutionResult : INIntentResolutionResult
```

**Comment by rolfbjarne** [comment]
I believe this is all fixed now in .NET, the xtro todo files for .NET are all clear of breaking changes, and there are no more XAMCORE_4_0 defines in Intents code either.
