### ISSUE TITLE
Xamarin.Mac Application Freezes for some Mac Users

### ISSUE THREAD

**Issue by BobMilanov** [xamarin/xamarin-macios#8035]
Hi, after moving our diagramming software MyDraw to Xamarin.Mac 5.14, we started receiving reports from some Mac users that the application freezes (hangs completely) on their Macs. We continued to receive such reports after updating to Xamarin.Mac 6 and newer, too (we tested with Xamarin.Mac 6.10, too).  When we downgrade to Xamarin.Mac 5.0, the application works fine for those users.

### Steps to Reproduce

1. [Download MyDraw](https://www.mydraw.com/_AUTHOR/RES/Downloads/MyDrawSetup.pkg)
2. Install the application on a Mac and start it.
3. Click any of the templates to open it or select "Blank Drawing" and then click "File" from the ribbon and then "About".

### Expected Behavior

The application should work and open the clicked template or the "About" dialog.

### Actual Behavior

The application freezes for some Mac users.

### Environment

We've received freezing issue reports for Mac users using even the most recent macOS versions: macOS 10.14: "Mojave" and macOS 10.15: "Catalina".

### Example Project (If Possible)

Unfortunately, we can't reproduce the issue on the Macs we have in the office, so we can't send any error logs or more details. To summarize the issue, our application freezes for some Mac users using the most recent version of Xamarin.Mac (freezing reports started with Xamarin.Mac 5.14), but works fine for those users with Xamarin.Mac 5.0.

Here's a link to MyDraw with Xamarin.Mac 6.10. Some Mac users report that the application freezes on their Macs:
[MyDraw with Xamarin.Mac 6.10](https://www.mydraw.com/_AUTHOR/RES/Downloads/MyDrawSetup.pkg)

Here's a link to a version of MyDraw that uses Xamarin.Mac 5.0 and works fine for the Mac users who experience freezing issues with the newer versions of Xamarin.Mac:
[MyDraw with Xamarin.Mac 5.0](https://www.mydraw.com/_AUTHOR/RES/Downloads/MyDrawSetup-4-2-0-Xamarin5.pkg)

Any suggestions or recommendations will be greatly appreciated.

Thank you!

**Comment by chamons** [comment]
So I can reproduce the hang I believe on my 10.15 laptop. 

However, I can't attach lldb to the binary and a sample taken in Activity Monitor was less than helpful:

https://gist.github.com/chamons/f48eff1d71490771ac1822b0df1bc318

The biggest change between 5.0 and 5.14 was likley mono runtime, but we also likely built against newer Xcode bits.

Here are a few ideas off of the top of my head:

- Enable [AOT compilation](https://docs.microsoft.com/en-us/xamarin/mac/internals/aot) and attach a link to a binary built (or mail me a link). I'll hang it here, and see if we get more useful stack information. Debug would be preferrable.
- 5.0 to 5.14 is a huge delta. Here are the releases in between:
   - [5.0](https://download.visualstudio.microsoft.com/download/pr/3849ffa9-0763-4727-8ae1-d67da9a6e60c/5c02d563ef9568fa79ba6dcf0cfeabd0/xamarin.mac-5.0.0.0.pkg)
   - [5.2](https://download.visualstudio.microsoft.com/download/pr/b4e72dff-9996-486d-9dea-3d5cb44c6789/d73a391a98ff7c6e5b404e292abda85b/xamarin.mac-5.2.1.16.pkg)
   - [5.6](https://download.visualstudio.microsoft.com/download/pr/0174da02-9f57-4527-9273-5cc5946cc4bd/33d246d2e5108df8c3190c5b50203a67/xamarin.mac-5.6.0.25.pkg)
   - [5.10](https://download.visualstudio.microsoft.com/download/pr/fdaee266-06e3-46f0-bd67-5081279dd1cf/577697f6fbddd9542d1c862a8603d362/xamarin.mac-5.10.0.157.pkg)
   - [5.14](https://download.visualstudio.microsoft.com/download/pr/9753ad10-d060-4427-880b-b4e0288878e1/140f9d84b62b3c57f00279f2b32360ce/xamarin.mac-5.14.0.114.pkg)

You could rebuild against different ones to try to narrow down the range.

- A couple questions:
   - Are both versions built against the same Xcode? 
   - Are you using the hardened runtime?
   - Are you using any tool post build to modify the binary (obfuscation, security, stripping)?

**Comment by chamons** [comment]
Just a note for the log. The user contacted me, and appears a modal dialog is in front, which is why it is "digging" and the UI isn't responding.

They are looking into their runModalForWindow and other similar calls. As there is no public sample, and I currently believe this is an issue on their end, I'm going to close this.

If the report is able to provide a small sample showing the issue and attaches it, we can look into it farther. They also have my e-mail for limited communication if needed as well.
