### ISSUE TITLE
Packaging could could warn on unused Entitlements.plist to prevent confusion

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#8102]
Recently we've had a number of users run into confusion with custom entitlements:

https://github.com/xamarin/xamarin-macios/issues/8020
https://github.com/xamarin/xamarin-macios/issues/7995

They add the specific entitlement to the file but then don't include it in the build:

![image](https://user-images.githubusercontent.com/6392201/76556356-5ba26580-6467-11ea-837f-b425f97598bb.png)

Maybe mmp/mtouch or msbuild should warn if Entitlements.plist is not empty/exists and not included in the build?

Any change should verify that new project in VSfM / VS doesn't hit this unnecessarily.

**Comment by tryadelion** [comment]
How can a problem like the related issue (8430) be solved when this issue arises? do we have to modify some step of the Xamarin build, or a configuration XML file?

**Comment by rolfbjarne** [comment]
In .NET we'll automatically include the Entitlements.plist file in the build.
