### ISSUE TITLE
[xharness] incorrect attachments in azdo ?

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#8146]
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3559942&view=ms.vss-test-web.build-test-results-tab&runId=11890976&resultId=749457&paneView=attachments shows App Build [xUnit] Mono SystemCoreXunit Part 1 failed twice

1st time I don’t get attachments
2nd time I get attachments that suggest execution

so something is really off - either the reported result or the attachment

### Expected Behavior

no execution attachment on something that reported as not built

### Actual Behavior

* App Build [xUnit] Mono SystemCoreXunit Part 1
* with attachment logs showing execution

### Environment

master

**Comment by spouliot** [comment]
There can be huge difference in timestamps between the attached logs
https://github.com/xamarin/xamarin-macios/commit/ec420e674004c187f4beb7119aab45b215c7a765

![Screen Shot 2020-03-20 at 2 31 36 PM](https://user-images.githubusercontent.com/260465/77195163-946dba80-6ab7-11ea-85c3-c1a2e8642fcf.png)

**Comment by mandel-macaque** [comment]
Taking a look at this one atm.
