### ISSUE TITLE
[meta][xharness] azdo / ddfun specific issues

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#8175]
These issues seems related to xharness and not the bots/devices

from: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3575009&view=ms.vss-test-web.build-test-results-tab&runId=11983954&paneView=attachments&resultId=118020

# azdo duration (table view) always shows "0:00:00.000"

Makes it hard to see if it's a real timeout and, if so, what was the allotted time for the test to run.

# Timeout too short

```
09:14:45.7485710 Test launch timed out after 3 minute(s).
```
Tests were still executing. On some devices 3 minutes is likely not enough - even less for something like BCL tests group 1.

# Download crash reports has issues

```
09:14:56.5404540 /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch --download-crash-report=./com.xamarin.bcltests.BCL tests group 1-2020-03-20-091453.ips --download-crash-report-to=/Users/xamarinqa/azdo/_work/49/s/xamarin-macios/jenkins-results/tests/[NUnit] Mono BCL tests group 1/1389/com.xamarin.bcltests.BCL tests group 1-2020-03-20-091453.ips --sdkroot=/Applications/Xcode113.app --devname=XQAiPadAira
09:14:57.0921820 error MT0010: Could not parse the command line arguments: System.AggregateException: One or more errors occurred. (Unknown command line argument: 'tests') (Unknown command line argument: 'group') (Unknown command line argument: '1-2020-03-20-091453.ips') (Unknown command line argument: 'Mono') (Unknown command line argument: 'BCL') (Unknown command line argument: 'tests') (Unknown command line argument: 'group') (Unknown command line argument: '1/1389/com.xamarin.bcltests.BCL') (Unknown command line argument: 'tests') (Unknown command line argument: 'group') (Unknown command line argument: '1-2020-03-20-091453.ips') ---> Xamarin.Launcher.LauncherException: Unknown command line argument: 'tests'
```

## Double logs (already filed)

**Comment by spouliot** [comment]
17x MT0010 in

http://xamarin-storage/jenkins/xamarin-macios/master/e9ff1f854dc8445380ae79a896fc52d507a8ce79/3577557/device-tests/jenkins-results/tests/index.html

**Comment by premun** [comment]
> ```09:14:57.0921820 error MT0010: Could not parse the command line arguments: System.AggregateException: One or more errors occurred. (Unknown command line argument: 'tests') (Unknown command line argument: 'group') (Unknown command line argument: '1-2020-03-20-091453.ips') (Unknown command line argument: 'Mono') (Unknown command line argument: 'BCL') (Unknown command line argument: 'tests') (Unknown command line argument: 'group') (Unknown command line argument: '1/1389/com.xamarin.bcltests.BCL') (Unknown command line argument: 'tests') (Unknown command line argument: 'group') (Unknown command line argument: '1-2020-03-20-091453.ips') ---> Xamarin.Launcher.LauncherException: Unknown command line argument: 'tests'```

@spouliot this is a problem of not escaping arguments correctly (paths with spaces) which I noticed is happening while working on https://github.com/xamarin/xamarin-macios/pull/8167 and the fix is there (plus bunch of unit tests for this). @mandel-macaque is helping me to figure out why the CI in that PR fails and once we get that we can resolve this issue.

**Comment by mandel-macaque** [comment]
https://github.com/xamarin/xamarin-macios/pull/8167 looks like it is fix for it.

**Comment by spouliot** [comment]
# Reported to Github
https://github.com/xamarin/xamarin-macios/commit/49f6846a7202e1d799b2afeccedb8c433c3f444d

🚧 Experimental DDFun pipeline

🔥 Device tests completed (Failed) on iOS-DDFun on Azure DevOps(iOS-DDFun) 🔥

Test results

21 tests failed, 129 tests passed.

# Reported by AzDO
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3642324&view=ms.vss-test-web.build-test-results-tab

451 Failed tests (+48)
48 New
403 Existing
