### ISSUE TITLE
Secure Text Proerety not shows correctlly after enabled

### ISSUE THREAD

**Issue by john-heaven** [xamarin/xamarin-macios#8178]
### Steps to Reproduce

1.  Create a new Xamarin iOS application in Visual Studio or VS for Mac with latest version .
2.  Add a Text Field in StoryBoard , with some text as follow :
![image](https://user-images.githubusercontent.com/7145819/77410195-7aa0e000-6df5-11ea-8cb6-d8c12bf39ec1.png)

3.  Then enable the `Secure Text` property , however the views not shows your want .
![image](https://user-images.githubusercontent.com/7145819/77410386-c18ed580-6df5-11ea-8248-b1b9681ea687.png)

### Environment

VS for Mac : 8.5
Visual Studio 2019 : 16.5.0

**Comment by chamons** [comment]
Thank you for your feedback!

The description sounds to be all in Xcode, so I'm not sure if this is a Xamarin.iOS bug.

For us to investigate this further, could you please provide your full build logs, crash reports (if any), test case (to reproduce) and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
