### ISSUE TITLE
Dollar sign in BUILD_REVISION

### ISSUE THREAD

**Issue by premun** [xamarin/xamarin-macios#8185]
Looks like we are adding an extra character when calling `mlaunch`.

https://github.com/xamarin/xamarin-macios/blob/a0aa48465b718c67c8508d0883875d351ab9ff63/tests/xharness/AppRunner.cs#L397

This ends up adding following argument:
```
-setenv=BUILD_REVISION=$jenkins
```

Not sure the `$` is intentional there but other parts of the code are adding just the string `jenkins`:
https://github.com/xamarin/xamarin-macios/blob/a0aa48465b718c67c8508d0883875d351ab9ff63/tests/xharness/Jenkins/Jenkins.cs#L1159

**Comment by premun** [comment]
@rolfbjarne can you take a look at this and verify whether this is intentional?

**Comment by rolfbjarne** [comment]
This is not intentional, it should do `BUILD_REVISION=jenkins`.

**Comment by premun** [comment]
I will make a fix for this. But would merge https://github.com/xamarin/xamarin-macios/pull/8167 first to be honest. To unblock the pipeline
