### ISSUE TITLE
MT3001: Could not AOT the assembly 'StackExchange.Redis.dll'

### ISSUE THREAD

**Issue by realzhaorong** [xamarin/xamarin-macios#8193]
MT3001: Could not AOT the assembly 'StackExchange.Redis.dll'

The error occurred when deploy my iOS project to iPhone after I upgrade Xamarin.iOS to 13.14.1.39. It works well on 13.10.0.17 & 13.10.0.21

Xamarin.Forms: 4.5.0.396
StackExchange.Redis: 2.0.601

Addition: it't just OK in Debug/Release+iPhoneSimulator mode.

**Comment by chamons** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs, crash reports (if any), test case and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by realzhaorong** [comment]
Visual Studio Community 2019 for Mac
Version 8.5 (build 3183)
Installation UUID: 144e27d3-30a4-4fe4-b628-362e337db55f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 608000123

Mono Framework MDK
Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123

Roslyn (Language Service)
3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

NuGet
Version: 5.4.0.6315

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.102
	2.2.207
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.1.0
	3.0.2
	2.2.8
	2.1.16
	2.1.15
	2.1.14

Xamarin.Profiler
Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin Designer
Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

Xamarin.Android
Version: 10.2.0.100 (Visual Studio Community)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Users/rong/Library/Android/sdk
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

Microsoft Mobile OpenJDK
Java SDK: /Users/rong/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-02-20 23:25:56 UTC

Android Device Manager
Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5
Build date: 2020-02-20 23:26:18 UTC

Apple Developer Tools
Xcode 11.4 (16134)
Build 11E146

Xamarin.Mac
Version: 6.14.1.39 (Visual Studio Community)
Hash: 30e8706b4
Branch: d16-5
Build date: 2020-02-20 16:41:47-0500

Xamarin.iOS
Version: 13.14.1.39 (Visual Studio Community)
Hash: 30e8706b4
Branch: d16-5
Build date: 2020-02-20 16:41:48-0500

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 805003183
Git revision: 60e06e010baa677204535600661dda3fb4677c2f
Build date: 2020-03-20 06:18:03-04
Build branch: release-8.5
Xamarin extensions: 60e06e010baa677204535600661dda3fb4677c2f

Operating System
Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by chamons** [comment]
Could you please also attach a test case, as requested?

 An AOT failure will require us to be able to try AOTing the assembly to fix it.

**Comment by realzhaorong** [comment]
[Building Redigo.iOS (Release|iPhone).txt](https://github.com/xamarin/xamarin-macios/files/4388043/Building.Redigo.iOS.Release.iPhone.txt)

**Comment by chamons** [comment]
That is a build log, and while useful:

```    MTOUCH : error MT3001: Could not AOT the assembly '/Users/rong/Code/Nerosoft/Redigo/Redigo.iOS/obj/iPhone/Release/mtouch-cache/3-Build/StackExchange.Redis.dll'```

Is not a test case.

**Comment by realzhaorong** [comment]
I do not have a test case.
You can create a empty Xamarin.Forms project, then install package of StackExchange.Redis(2.0.601), of course you must add a assembly reference to System.Diagnostics.PerformanceCounter.dll.
Build the project with iPhone.

**Comment by chamons** [comment]
When I try to reference StackExchange.Redis and such, I get error MT2001 which is not what you are seeing.

Without a sample showing your behavior, little progress will likely be made on this issue.

**Comment by realzhaorong** [comment]
I will supply a sample later.

**Comment by realzhaorong** [comment]
[RedisSample.zip](https://github.com/xamarin/xamarin-macios/files/4397195/RedisSample.zip)

**Comment by chamons** [comment]
I just tested this with latest Xamarin.iOS and Mono and it AOTs fine for me.

You are on mono 6.8 and XI 13.14. Update to latest and try again.

**Comment by realzhaorong** [comment]
I noticed that 6.8 is the latest stable mono version.

**Comment by chamons** [comment]
You are on:
 Version: 13.14.1.39 (Visual Studio Community)
 Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)

Latest stable is:
13.16.0.13
6.8.0.123

I'm unsure why a XI change would AOT, but it's worth checking. 

As I said, I was able to AOT successfully, so I'm trying to figure out what the difference is.

**Comment by whitneyschmidt** [comment]
@realzhaorong Closing this issue as it is over a month old.

If you are still encountering this problem with the latest releases feel free to reopen.
