### ISSUE TITLE
UIPickerView text color doesn't change initially but it gets update on a swipe inside picker

### ISSUE THREAD

**Issue by KarthikRajaAKR** [xamarin/xamarin-macios#8202]
I am using UIKit.UIPickerView in Xamarin.iOS project.
Here, I can customize the color of Background using BackgrounColor property.
But can't change the text color. I used below method,
`pickerView.SetValueForKeyPath(UIColor.White, (NSString)"textColor");`

This doesn't change the color on initial loading but color gets updated if you swipe the picker itself.

### Steps to Reproduce

1.  Run the attached sample
2. Note there is no change in text color of picker
3. Now scroll picker up and down, you can see the changes in text color.

### Images
Initial Loading
![image](https://user-images.githubusercontent.com/41435300/77646871-6262c980-6f8b-11ea-8c95-1500e9ff4c8d.png)

After a swipe
![image](https://user-images.githubusercontent.com/41435300/77646905-76a6c680-6f8b-11ea-9b42-300d044d70f4.png)

### Expected Behavior
Text Color could be changed on initial loading of Picker.
### Actual Behavior
Text color doesn't reflect on picker.
### Environment
1. Visual Studio 2017 and 2019, iPhone 8  
2. 
```
 var pickerView = new UIPickerView();
 pickerView.Model = new PickerSource();

 pickerView.BackgroundColor = UIColor.Blue;
 pickerView.SetValueForKeyPath(UIColor.White, (NSString)"textColor");
```

### Example Project (If Possible)
[PickerRenderer.zip](https://github.com/xamarin/xamarin-macios/files/4387087/PickerRenderer.zip)

Please help me to come out from this, **I would really appreciate if there is any other way to change the TextColor of UIPickerView.**

**Comment by chamons** [comment]
I'm not seeing this on Xcode 11.3 and Xamarin.iOS  13.10.0.21.

The color is white on startup:

![image](https://user-images.githubusercontent.com/6392201/77657062-bf865d00-6f42-11ea-99fe-a3c129eae733.png)

What Xcode version are you building against? What Xamarin.iOS version? Please post the version info as the issue template requests.

**Comment by KarthikRajaAKR** [comment]
Hi @chamons, I'm using Xamarin.iOS 12.0 and XCode version 10.0.

**Comment by chamons** [comment]
That build is too old for me to even install on my machine. Try updating to more recent Xcode / XI builds and see if that changes the behavior.

I strongly suspect this is an Apple/UIKit behvaior change.

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
