### ISSUE TITLE
Missing values in NFCTagType enum

### ISSUE THREAD

**Issue by FinHorsley** [xamarin/xamarin-macios#8210]
The [NFCTagType](https://docs.microsoft.com/en-us/dotnet/api/corenfc.nfctagtype?view=xamarin-ios-sdk-12) Enum is missing values in iOS 13; the Microsoft docs state the following, but new values were added as of iOS 13
> Enumerates the kinds of NFC tags that can be read (currently only ISO-15693)

### Added in iOS 13  - taken from the [Apple Docs](https://developer.apple.com/documentation/corenfc/nfctagtype)
These are the new values added by Apple that are missing in Xamarin.iOS
- `NFCTagTypeISO15693` - An NFC tag of type ISO 15693.
- `NFCTagTypeISO7816Compatible `- An NFC tag of type ISO 7816.
- `NFCTagTypeFeliCa` - An NFC tag of type FeliCa.
- `NFCTagTypeMiFare` - An NFC tag of type MIFARE.

### Environment
- iOS 13
- Visual Studio Mac - 8.5 (3183)

**Comment by spouliot** [comment]
yes, the three new members are indeed missing, thanks for the report :)

In the meantime you can typecast them as integrals, e.g.
```csharp
NFCTagType FeliCa = (NFCTagType) 1;
NFCTagType ISO7816Compatible = (NFCTagType) 2;
NFCTagType MiFare = (NFCTagType) 3;
```

**Comment by FinHorsley** [comment]
Just catching up with this, thanks for such a quick reply, and fix! Your interim solution worked, but it looks like we won’t need it for long 🙂
