### ISSUE TITLE
macOS: Implement IEnumerable for PHFetchResult

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-macios#8225]
### Steps to Reproduce
```
var allPhotos = PHAsset.FetchAssets(new PHFetchOptions());
foreach (var photo in allPhotos) <-- error on macOS
{

}
```

### Expected Behavior
Compiles and works (it does for iOS)

### Actual Behavior
`Error CS1579: foreach statement cannot operate on variables of type 'PHFetchResult' because 'PHFetchResult' does not contain a public instance definition for 'GetEnumerator' (CS1579)`

### Possible solution
Implement IEnumaerable for PHFetchResult for macOS as well ([it is implemented for iOS](https://github.com/xamarin/xamarin-macios/blob/bc492585d137d8c3d3a2ffc827db3cdaae3cc869/src/Photos/PHFetchResult.cs))

**Comment by chamons** [comment]
Good spot. Looks like there are more than one bits that were missed.

**Comment by chamons** [comment]
Thanks for the report! Fixed in master and d16-6 release.
