### ISSUE TITLE
[Harness] Harness throws an exception when there are no simulators or runtasks 

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#8271]
When executing xharness we noticed that the following line throws and exception:

https://github.com/xamarin/xamarin-macios/blob/master/tests/xharness/Jenkins/TestTasks/AggregatedRunSimulatorTask.cs#L66

In the case when there are no tasks we get exceptions like the following: http://xamarin-storage/jenkins/xamarin-macios/PR-8269/7bbc0c974ca7201576c261cdc60a9351293533ae/1/jenkins-results/tests/index.html

That should not happen and we should ignore the test to the very least.

**Comment by rolfbjarne** [comment]
https://github.com/xamarin/xamarin-macios/blob/5aa2b1c34fdd544ae42a20f28ee3b51b9703abde/tests/xharness/Jenkins/TestTasks/TestTask.cs#L35-L40
