### ISSUE TITLE
Xamarin.Mac.Common.targets errors out when compiling vsmac.

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#8277]
### Steps to Reproduce

1. Clone and compile vsmac

### Expected Behavior

Successful build

### Actual Behavior

```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.Common.targets(674,3): error MSB4044: The "CompileSceneKitAssets" task was not given a value for the required parameter "TargetFrameworkMoniker". [/Users/therzok/Work/md/vsmac/main/external/VS-Platform/src/Editor/FPF/WindowsBase/WindowsBase.csproj]
```

### Environment

6.19.0.151 (PR build for ui thread check)

```
```

**Comment by rolfbjarne** [comment]
Can you post a diagnostic or binary build log?

**Comment by Therzok** [comment]
https://microsofteur-my.sharepoint.com/:u:/g/personal/maungu_microsoft_com/ESNWz_TzsdFLuWQe5pmEf3sBjEliGppQNs9KycF6-w1pNQ?e=gXqTbn

**Comment by rolfbjarne** [comment]
New packages to test will show up here in a few hours: https://github.com/xamarin/xamarin-macios/commit/5c6055abc8b0a121fdf215306fe3332b78ab6daa

**Comment by rolfbjarne** [comment]
Package is available: [xamarin.mac-6.19.0.412.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/ui-thread-gen/5c6055abc8b0a121fdf215306fe3332b78ab6daa/2/package/notarized/xamarin.mac-6.19.0.412.pkg)

**Comment by Therzok** [comment]
Can confirm it works!
