### ISSUE TITLE
Xamarin.Forms app completly broken after Xamarin.iOS update

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/xamarin-macios#8292]
After updating my VS for Mac and the installed Xamarin.iOS version today, nothing in my Xamarin.Forms app works anymore. Even with the latest stable version of Xamarin.Forms everything is broken. 

The version of Xamarin.iOS I'm using right now is this one: 
```
Xamarin.iOS
Version: 13.16.0.11 (Visual Studio Enterprise)
Hash: aa73e4125
Branch: d16-5-xcode11.4
Build date: 2020-03-25 11:04:03-0400
```

After the update, I can open and close my master menu but cannot click on anything in it. No touch on the menu items is registered and other TapGestureRecognizers on Labels, Grids, etc. does also no longer execute. 

Also replacing tabs in a tabbed page on runtime causes a app crash now. 

Is there any way to downgrade Xamarin.iOS?

**Comment by chamons** [comment]
This is very likely https://github.com/xamarin/Xamarin.Forms/issues/10162

See: https://github.com/xamarin/Xamarin.Forms/issues/10162#issuecomment-607585466

**Comment by Sebastian1989101** [comment]
@chamons I will test this but my MasterMenu navigation is done by selection change event of the list view control from Xamarin.Forms. Also I see no direct connection why the app crashes on iOS 12.x and older on a tabbed page if I replace a tab. I think the 2nd bug is related to https://github.com/xamarin/Xamarin.Forms/issues/10213 even if I don't know why this is happening with Forms 4.5.
