### ISSUE TITLE
[xharness] Html report isn't generated anymore for mtouch tests

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#8308]
No html report:

<img width="718" alt="Screenshot 2020-04-08 09 16 16" src="https://user-images.githubusercontent.com/249268/78755530-9cfc3700-7979-11ea-8934-f5a212933521.png">

from http://xamarin-storage/jenkins/xamarin-macios/dotnet-tools/2c9eb40b95ab2027a0db3b00d053110b149c262b/11/jenkins-results/tests/index.html

**Comment by mandel-macaque** [comment]
I missed this issue and created https://github.com/xamarin/xamarin-macios/issues/8364 which is closed.
