### ISSUE TITLE
[xharness] Test failures aren't shown in the html report anymore

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#8309]
See:

<img width="718" alt="Screenshot 2020-04-08 09 16 16" src="https://user-images.githubusercontent.com/249268/78755796-0e3bea00-797a-11ea-9eb0-6edc50ce05fd.png">

from http://xamarin-storage/jenkins/xamarin-macios/dotnet-tools/2c9eb40b95ab2027a0db3b00d053110b149c262b/11/jenkins-results/tests/index.html

vs

<img width="725" alt="Screenshot 2020-04-08 09 19 55" src="https://user-images.githubusercontent.com/249268/78755831-1eec6000-797a-11ea-8a50-7d72c00d6ea5.png">

from http://xamarin-storage/jenkins/xamarin-macios/d16-5/30e8706b4fd666503870d5f2b481584d5fe06a1d/54/jenkins-results/tests/index.html

**Comment by mandel-macaque** [comment]
I missed this issue and created https://github.com/xamarin/xamarin-macios/issues/8364 which is closed. Closing.
