### ISSUE TITLE
Undefined symbol: ___darwin_check_fd_set_overflow when building against older Xcode

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#8325]
As [documented](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/old-version-xcode), the recommended configuration is the latest Xamarin.iOS or Mac along side the latest Xcode from Apple.

In many cases one can enable the static registrar and use a newer Xamarin.iOS with an older Xcode. The error messages suggest this as well:

```
This version of Xamarin.iOS requires the tvOS 13.4 SDK (shipped with Xcode 11.4). 
Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). (MT0091)
```

Due to a [bug](https://openradar.appspot.com/FB7647406) introduced in Xcode 11.4 by Apple this currently does not work with the latest Xamarin.iOS. This is being [tracked in mono](https://github.com/mono/mono/issues/19393) as well.

Until then, your best option is to have a matching Xcode and Xamarin SDK either by:
- Upgrading your Xcode to 11.4 to use with recent Xamarin.iOS and Mac
- Downgrading your Xamarin.iOS to match your Xcode.

**Comment by rolfbjarne** [comment]
This doesn't seem to be an issue anymore.
