### ISSUE TITLE
Installer does not bundle generated binding source

### ISSUE THREAD

**Issue by Therzok** [xamarin/xamarin-macios#8338]
### Steps to Reproduce

```
cd /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/AppKit
ls *NSTextField*
```

Observe only the non-generated NSTextField.cs code is bundled.

### Expected Behavior

Generated code is bundled too.

### Actual Behavior

It's not.

### Environment

6.19.0.412

**Comment by Therzok** [comment]
also, probably typo'd, `/Library/Frameworks/Xamarin.Mac.framework/Versions/6.18.1.20/src/Xamarin.Mac/enerated.cs` instead of generated

**Comment by chamons** [comment]
I checked this back to d16-3, and I don't see generated code there. I'm unsure if I went farther back if we ever shipped it.

**Comment by mandel-macaque** [comment]
Very probably, an issue with the source installer code and that it was always like this.

**Comment by rolfbjarne** [comment]
We'll handle this in https://github.com/xamarin/xamarin-macios/issues/14895.
