### ISSUE TITLE
Generator test fail in master 

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#8347]
Generator tests started failing: 

http://xamarin-storage/jenkins/xamarin-macios/master/48b813e8a37a2af272b9cf13be70fb498725ab1f/1415/jenkins-results/tests/index.html

I cannot pin point a commit because we started having issues with xamarin-storage which means that we have to dig throw the build logs. Will post here once I get one.

**Comment by mandel-macaque** [comment]
So after so digging I have the following:

The issue happens because when looking at the attributes of a method/class we are finding a NullableContextAttribute. To be more precise we get to https://github.com/xamarin/xamarin-macios/blob/master/src/generator-attribute-manager.cs#L198 which does not have a special case of that attribute, that returns null, and therefore we get an internal error in the tests.

looking at the liner sources, I though we would not have the attribute: https://github.com/xamarin/xamarin-macios/blob/b279401727fcc608868ecdd82297eb1744ba0f96/tools/linker/MobileRemoveAttributes.cs#L42 

So there is something fishy, either the linker is not doing its job, or maybe the generator tests are using a dll without the attrs removed?

**Comment by spouliot** [comment]
@mandel-macaque most of the tests are not using the linker (or at least not always). Same for our normal code, i.e. linking is optional. In this case the generator is almost always (99+%) working on non-linked code (since only apps are linked and the generator works on assemblies).

**Comment by spouliot** [comment]
Console/Makefile and xharness results differ :(

```
Run Settings
    DisposeRunners: True
    WorkDirectory: /Users/poupou/git/d16-6/xamarin-macios/tests/generator
    ImageRuntimeVersion: 4.0.30319
    ImageTargetFrameworkName: .NETFramework,Version=v4.6.1
    ImageRequiresX86: False
    ImageRequiresDefaultAppDomainAssemblyResolver: False
    NumberOfTestWorkers: 8

Test Run Summary
  Overall result: Passed
  Test Count: 132, Passed: 132, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2020-04-14 13:47:16Z
    End time: 2020-04-14 13:48:01Z
    Duration: 44.516 seconds

Results (nunit2) saved as /Users/poupou/git/d16-6/xamarin-macios/tests/generator/TestResult.xml
```
