### ISSUE TITLE
Simple Android program doe's not run. everytime new Response.ErrorListener()  called

### ISSUE THREAD

**Issue by samarkuila** [xamarin/xamarin-macios#8351]
package com.example.senddatasql;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.view.ViewDebug;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.android.volley.AuthFailureError;
import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.StringRequest;
import com.android.volley.toolbox.Volley;

import org.w3c.dom.Text;

import java.security.PublicKey;
import java.util.HashMap;
import java.util.Map;

public class MainActivity extends AppCompatActivity {

    EditText editTextName;
    EditText editTextEmail ;
    Button btn;

    String name,email;
    String url="192.168.225.45/insert.php";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        editTextName= (EditText) findViewById(R.id.Name);
        editTextEmail=(EditText) findViewById(R.id.Email);
        btn=(Button) findViewById(R.id.button) ;
        btn.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View view) {
        insertData();
    }
});
    }
    public void insertData(){
        name= editTextName.getText().toString();
        email= editTextEmail.getText().toString();
        RequestQueue requestQueue= Volley.newRequestQueue(this);
        StringRequest stringRequest=new StringRequest(Request.Method.POST,url,
                new Response.Listener<String>() {
                    @Override
                    public void onResponse(String response){
                        Toast.makeText(MainActivity.this, response, Toast.LENGTH_SHORT).show();
                          }
                    },new Response.ErrorListener() {
                        public void onErrorResponse(VolleyError Error){
                            Toast.makeText(MainActivity.this,"Try Again",Toast.LENGTH_SHORT).show();
                    }
                }
        ){
            @Override
            protected Map<String, String> getParams() {
                Map<String,String> params= new HashMap<String,String>();
                params.put("name",name);
                params.put("email",email);
                return params;
            }
        };
        requestQueue.add(stringRequest);
    }

}

**Comment by enisuce** [comment]
> paket com.example.senddatasql;
> 
> ithalat androidx.appcompat.app.AppCompatActivity;
> 
> ithalat android.os.Bundle;
> ithalat android.view.View;
> ithalat android.view.ViewDebug;
> ithalat android.widget.Button;
> ithalat android.widget.EditText;
> ithalat android.widget.Toast;
> 
> import com.android.volley.AuthFailureError;
> ithalat com.android.volley.Request;
> import com.android.volley.RequestQueue;
> ithalat com.android.volley.Response;
> import com.android.volley.VolleyError;
> import com.android.volley.toolbox.StringRequest;
> ithalat com.android.volley.toolbox.Volley;
> 
> import org.w3c.dom.Text;
> 
> import java.security.PublicKey;
> içe aktar java.util.HashMap;
> import java.util.Map;
> 
> public class MainActivity, AppCompatActivity'yi genişletir {
> 
> ```
> EditText editTextName;
> EditText editTextEmail ;
> Button btn;
> 
> String name,email;
> String url="192.168.225.45/insert.php";
> 
> 
> 
> @Override
> protected void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
>     setContentView(R.layout.activity_main);
> 
>     editTextName= (EditText) findViewById(R.id.Name);
>     editTextEmail=(EditText) findViewById(R.id.Email);
>     btn=(Button) findViewById(R.id.button) ;
>     btn.setOnClickListener(new View.OnClickListener() {
> @Override
> public void onClick(View view) {
>     insertData();
> }
> ```
> 
> });
> }
> public void insertData(){
> name= editTextName.getText().toString();
> email= editTextEmail.getText().toString();
> RequestQueue requestQueue= Volley.newRequestQueue(this);
> StringRequest stringRequest=new StringRequest(Request.Method.POST,url,
> new Response.Listener() {
> @override
> public void onResponse(String response){
> Toast.makeText(MainActivity.this, response, Toast.LENGTH_SHORT).show();
> }
> },new Response.ErrorListener() {
> public void onErrorResponse(VolleyError Error){
> Toast.makeText(MainActivity.this,"Try Again",Toast.LENGTH_SHORT).show();
> }
> }
> ){
> @override
> protected Map<String, String> getParams() {
> Map<String,String> params= new HashMap<String,String>();
> params.put("name",name);
> params.put("email",email);
> return params;
> }
> };
> requestQueue.add(stringRequest);
> }
> 
> }

@samarkuila

**Comment by samarkuila** [comment]
I solve it.
