### ISSUE TITLE
[Bug] When connecting to Mac, the process gets stuck in a loop Resolving certificates

### ISSUE THREAD

**Issue by JohnLivermore** [xamarin/xamarin-macios#8404]
### Description
When connecting to Mac, the process gets stuck in a loop Resolving certificates.  See log output below the full session.  You can see where it starts to repeat itself. 

It sits on this screen forever...

![image](https://user-images.githubusercontent.com/1489667/79263804-22d82080-7e59-11ea-902d-cbec40d77e64.png)

Here is my setup...

![image](https://user-images.githubusercontent.com/1489667/78812337-dd1ae400-7990-11ea-8ad6-94384a71857d.png)

### Xamarin log output

Checking Broker 16.5.000.533 installation...
Starting Broker 16.5.000.533 in port 57996...
Broker 16.5.000.533 started successfully
Starting IDB Local Agent...
Checking Agent IDB.Local 16.5.000.533 installation...
Starting Agent IDB.Local 16.5.000.533 in port 57996...
Agent IDB.Local 16.5.000.533 started successfully
The required Apple Support libraries have not been found. Please ensure to have a valid iTunes installation in order to communicate with Apple devices in Windows. Windows Store iTunes installations are not supported right now.
Checking host configuration for connecting to 'John’s MacBook Pro'...
Checking SSH configuration...
Initializing environment...
Checking available disk space...
Checking Mono installation...
Checking Xamarin iOS installation...
Checking host configuration for connecting to 'John’s MacBook Pro'...
Host 'John’s MacBook Pro' is configured correctly
Starting connection to 'John’s MacBook Pro'...
Checking Broker 16.5.000.533 installation...
Starting Broker 16.5.000.533 in port 50062...
Broker 16.5.000.533 started successfully
Starting connection to 'John’s MacBook Pro'...
SSH connection to 'John’s MacBook Pro' has been established...
Starting registered Agents: Build 16.5.000.533, IDB 16.5.000.533...
Starting Build 16.5.000.533...
Checking Agent Build 16.5.000.533 installation...
Starting IDB 16.5.000.533...
Checking Agent IDB 16.5.000.533 installation...
Starting Agent Build 16.5.000.533 in port 50062...
Starting Agent IDB 16.5.000.533 in port 50062...
Agent Build 16.5.000.533 started successfully
Build 16.5.000.533 started
Agent IDB 16.5.000.533 started successfully
IDB 16.5.000.533 started
Starting registered Agents: ...
The Agents have been started successfully
Performing server validations against 'John’s MacBook Pro'...
Initializing IDB environment...
Validating Mac operating system version compatibility...
Checking Xcode version compatibility...
Validating Xcode license state...

Resolving certificate...
Fetching valid and locally installed signing identities...
Syncing certificates for "WolfePak Software, LLC" team...
Saving Apple Development certificates...
Verifying installed Xcode tools...
Checking Xcode tool package 'MobileDeviceDevelopment.pkg' installation...
Syncing App IDs for "WolfePak Software, LLC" team...
Making sure that connected devices are registered in "WolfePak Software, LLC" team...
Syncing devices for "WolfePak Software, LLC" team...
Processing ios devices...
Xcode tool package 'MobileDeviceDevelopment.pkg' is up to date
Checking Xcode tool package 'CoreTypes.pkg' installation...
Syncing provisioning profiles for "WolfePak Software, LLC" team...
Saving iOS profiles...
Fetching additional data about profile's certificates and devices for VS: WildCard Development...
Downloading the list of devices and certificates for VS: WildCard Development...
Running update request for VS: WildCard Development...
Xcode tool package 'CoreTypes.pkg' is up to date
Checking Xcode tool package 'MobileDevice.pkg' installation...
Downloading provisioning profile: VS: WildCard Development...
Saving provisioning profile: VS: WildCard Development...
Xcode tool package 'MobileDevice.pkg' is up to date
Checking Xcode tool package 'XcodeSystemResources.pkg' installation...
Xcode tool package 'XcodeSystemResources.pkg' is up to date
Checking provisioning information...
Fetching valid and locally installed signing identities...

Resolving certificate...
Syncing certificates for "WolfePak Software, LLC" team...
Saving Apple Development certificates...
Syncing App IDs for "WolfePak Software, LLC" team...
Making sure that connected devices are registered in "WolfePak Software, LLC" team...
Processing ios devices...
Syncing devices for "WolfePak Software, LLC" team...
Syncing provisioning profiles for "WolfePak Software, LLC" team...
Saving iOS profiles...
Fetching additional data about profile's certificates and devices for VS: WildCard Development...
Downloading the list of devices and certificates for VS: WildCard Development...
Running update request for VS: WildCard Development...
Downloading provisioning profile: VS: WildCard Development...
Saving provisioning profile: VS: WildCard Development...

Resolving certificate...
Syncing certificates for "WolfePak Software, LLC" team...
Fetching valid and locally installed signing identities...
Saving Apple Development certificates...
Syncing App IDs for "WolfePak Software, LLC" team...
Making sure that connected devices are registered in "WolfePak Software, LLC" team...
Processing ios devices...
Syncing devices for "WolfePak Software, LLC" team...
Syncing provisioning profiles for "WolfePak Software, LLC" team...
Saving iOS profiles...
Downloading the list of devices and certificates for VS: WildCard Development...
Fetching additional data about profile's certificates and devices for VS: WildCard Development...
Running update request for VS: WildCard Development...
Downloading provisioning profile: VS: WildCard Development...
Saving provisioning profile: VS: WildCard Development...

Resolving certificate...
Fetching valid and locally installed signing identities...
Saving Apple Development certificates...
Syncing certificates for "WolfePak Software, LLC" team...
Syncing App IDs for "WolfePak Software, LLC" team...
Syncing devices for "WolfePak Software, LLC" team...
Processing ios devices...
Making sure that connected devices are registered in "WolfePak Software, LLC" team...
Syncing provisioning profiles for "WolfePak Software, LLC" team...
Saving iOS profiles...
Downloading the list of devices and certificates for VS: WildCard Development...
Fetching additional data about profile's certificates and devices for VS: WildCard Development...
Running update request for VS: WildCard Development...
Downloading provisioning profile: VS: WildCard Development...
Saving provisioning profile: VS: WildCard Development...

Resolving certificate...
Fetching valid and locally installed signing identities...
Saving Apple Development certificates...
Syncing certificates for "WolfePak Software, LLC" team...
Syncing App IDs for "WolfePak Software, LLC" team...
Making sure that connected devices are registered in "WolfePak Software, LLC" team...
Syncing devices for "WolfePak Software, LLC" team...
Processing ios devices...
Syncing provisioning profiles for "WolfePak Software, LLC" team...
Saving iOS profiles...
Downloading the list of devices and certificates for VS: WildCard Development...
Fetching additional data about profile's certificates and devices for VS: WildCard Development...
Running update request for VS: WildCard Development...
Downloading provisioning profile: VS: WildCard Development...
Saving provisioning profile: VS: WildCard Development...

Resolving certificate...
Syncing certificates for "WolfePak Software, LLC" team...
Saving Apple Development certificates...
Fetching valid and locally installed signing identities...
Syncing App IDs for "WolfePak Software, LLC" team...
Processing ios devices...
Making sure that connected devices are registered in "WolfePak Software, LLC" team...
Syncing devices for "WolfePak Software, LLC" team...
Syncing provisioning profiles for "WolfePak Software, LLC" team...
Saving iOS profiles...
Downloading the list of devices and certificates for VS: WildCard Development...
Fetching additional data about profile's certificates and devices for VS: WildCard Development...
Running update request for VS: WildCard Development...
Downloading provisioning profile: VS: WildCard Development...
Saving provisioning profile: VS: WildCard Development...
Fetching valid and locally installed signing identities...

Resolving certificate...
Saving Apple Development certificates...
Syncing certificates for "WolfePak Software, LLC" team...
Syncing App IDs for "WolfePak Software, LLC" team...
Making sure that connected devices are registered in "WolfePak Software, LLC" team...
Syncing devices for "WolfePak Software, LLC" team...
Processing ios devices...
Syncing provisioning profiles for "WolfePak Software, LLC" team...
Saving iOS profiles...
Fetching additional data about profile's certificates and devices for VS: WildCard Development...
Downloading the list of devices and certificates for VS: WildCard Development...
Running update request for VS: WildCard Development...
Downloading provisioning profile: VS: WildCard Development...
Saving provisioning profile: VS: WildCard Development...

Resolving certificate...
Fetching valid and locally installed signing identities...
Syncing certificates for "WolfePak Software, LLC" team...
Saving Apple Development certificates...
Syncing App IDs for "WolfePak Software, LLC" team...
Making sure that connected devices are registered in "WolfePak Software, LLC" team...
Syncing devices for "WolfePak Software, LLC" team...
Processing ios devices...
Syncing provisioning profiles for "WolfePak Software, LLC" team...
Saving iOS profiles...
Fetching additional data about profile's certificates and devices for VS: WildCard Development...
Downloading the list of devices and certificates for VS: WildCard Development...
Running update request for VS: WildCard Development...
Downloading provisioning profile: VS: WildCard Development...
Saving provisioning profile: VS: WildCard Development...
Fetching valid and locally installed signing identities...

Resolving certificate...
Syncing certificates for "WolfePak Software, LLC" team...
Saving Apple Development certificates...
Syncing App IDs for "WolfePak Software, LLC" team...
Syncing devices for "WolfePak Software, LLC" team...
Making sure that connected devices are registered in "WolfePak Software, LLC" team...
Processing ios devices...
Syncing provisioning profiles for "WolfePak Software, LLC" team...
Saving iOS profiles...
Fetching additional data about profile's certificates and devices for VS: WildCard Development...
Downloading the list of devices and certificates for VS: WildCard Development...
Running update request for VS: WildCard Development...
Downloading provisioning profile: VS: WildCard Development...
Saving provisioning profile: VS: WildCard Development...

> VS bug [#1106488](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1106488)

**Comment by emaf** [comment]
Hi @JohnLivermore, could you attach the Xamarin logs? You can get the logs from `Help -> Xamarin -> Zip Logs`

Could you also try switching to **Manual Provisioning** in the **iOS Bundle Signing** project properties page and see if that ends the loop?

Thanks!

**Comment by JohnLivermore** [comment]
I switched to manual.  Same issue.

![image](https://user-images.githubusercontent.com/1489667/79909654-f71de300-83e2-11ea-8df3-8eb4560544c7.png)

One thing I noticed is I had added my development certificate manually on the Mac.  Then, when the automatic provisioning occured, it added the same certificate again (or seemed to be the same).  I tried deleting both, had the auto provision add the one it wants, but it remained stuck in the loop.

I then deleted that one, reimported the one I downloaded from Apple, and tried using manual prov.  Same loop occured.

I have attached the logs...

[xamarinlogs.zip](https://github.com/xamarin/xamarin-macios/files/4512412/xamarinlogs.zip)

**Comment by kiddailey** [comment]
I've also been having this issue for a while now and I have Manual Provisioning set up.  I also did add my development certificates manually on the Mac (if I remember correctly, it was because it wasn't working originally).

In any case, the connection always succeeds, but it takes about 15-20 minutes for the Pair To Mac Connection to complete for me every time I try to connect.

**Comment by 3hs4n** [comment]
Deleting all downloaded provisioning profiles in the following folder did the trick for me. 
%LOCALAPPDATA%\Xamarin\iOS\Provisioning\Profiles

**Comment by kiddailey** [comment]
> Deleting all downloaded provisioning profiles in the following folder did the trick for me.
> %LOCALAPPDATA%\Xamarin\iOS\Provisioning\Profiles

THANK YOU so much for reminding me of this folder!  To my surprise, there were almost 20,000 files totaling 150MB in mine!   I cleared it and now I'm connecting instantly again.  I've only got a small collection of provisioning profiles, so I have no idea how or why it got this way.

**Comment by kiddailey** [comment]
Just a follow-up on my previous post.  I've started running into this issue again and the profiles folder has over 1300 entries in it again.  According to the file dates, it just started happening about 10 days ago for no obvious reason.

It may be coincidence, but I did have to log into the Apple Developer portal recently to agree to new terms of agreement.  Not sure if that has anything to do with it, but figured it was worth mentioning.  Will keep an eye on it and see if happens again.

**Comment by lukewis** [comment]
I'm seeing similar behavior, but I'm stuck on the "Configuring SSH Part".  I'm happy to open a separate issue if this sounds unrelated.  Here's the relevant section of my logs.  It just continues on like this indefinitely.....I'm able to ssh from the terminal to the remote machine without issue.
```
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : Checking SSH configuration...: 11/09/2021 17:47:12Z
    DateTime=2021-11-09T17:47:12.3531117Z: 11/09/2021 17:47:12Z
Xamarin.Messaging.Integration.State.ServerStateContext Information: 0 : !Checking SSH configuration...: 11/09/2021 17:47:12Z
    DateTime=2021-11-09T17:47:12.3531117Z: 11/09/2021 17:47:12Z
Xamarin.Messaging.Client.PingHandler Information: 0 : vs11444lawis received ping. Sending acknowledge...: 11/09/2021 17:47:16Z
    DateTime=2021-11-09T17:47:16.2981203Z: 11/09/2021 17:47:16Z
Xamarin.Messaging.Client.PingHandler Information: 0 : vs11444lawis received ping. Sending acknowledge...: 11/09/2021 17:47:21Z
    DateTime=2021-11-09T17:47:21.3190955Z: 11/09/2021 17:47:21Z
Xamarin.Messaging.Client.PingHandler Information: 0 : vs11444lawis received ping. Sending acknowledge...: 11/09/2021 17:47:26Z
    DateTime=2021-11-09T17:47:26.3397766Z: 11/09/2021 17:47:26Z
Xamarin.Messaging.Client.PingHandler Information: 0 : vs11444lawis received ping. Sending acknowledge...: 11/09/2021 17:47:31Z
    DateTime=2021-11-09T17:47:31.3616925Z: 11/09/2021 17:47:31Z
Xamarin.Messaging.Client.PingHandler Information: 0 : vs11444lawis received ping. Sending acknowledge...: 11/09/2021 17:47:36Z
    DateTime=2021-11-09T17:47:36.3945129Z: 11/09/2021 17:47:36Z
Xamarin.Messaging.Client.PingHandler Information: 0 : vs11444lawis received ping. Sending acknowledge...: 11/09/2021 17:47:41Z
    DateTime=2021-11-09T17:47:41.4278910Z: 11/09/2021 17:47:41Z
```
