### ISSUE TITLE
Consider making experimental-xforms-product-type functionality GA (removing flag)

### ISSUE THREAD

**Issue by jfversluis** [xamarin/xamarin-macios#8407]
This functionality was mainly introduced for the `UIWebView` deprecation in Xamarin.Forms in order to not make it a breaking change.

Since this was a potential impactful change, it was released behind a flag to first gather some experience on how this would behave in the wild. To date we have been able to fix all the `UIWebView` warnings (see [here](https://github.com/xamarin/Xamarin.Forms/issues/9823) and [here](https://github.com/xamarin/Xamarin.Forms/issues/7323) for reference) and did not encounter any issues with it. That is why I wanted to raise the issue to see if we can maybe remove the flag so we can make this process a little easier also for potential future cases.

If not, what is required for you to consider it?

Thanks!

/cc: @PureWeen

**Comment by spouliot** [comment]
This is largely up to you (XF). The flag makes the tooling consider (one of) your assemblies as a platform (not user) assembly. This comes with additional responsibilities, like ensuring everything is linker safe (e.g. reflection).

If this is not handled then things won't work (once linked) and it won't be an SDK or linker bug :)

> and did not encounter any issues with it

Not quite ;-)
https://github.com/xamarin/Xamarin.Forms/issues/9436

**Comment by PureWeen** [comment]
> and did not encounter any issues with it
Anh that was prerelease so it doesn't count :-) 

We were all too busy setting up VS 2017 compatibility testing lanes 😢  at that point so hadn't setup the ios linker testing yet. 

At this point our tests are all running with full linker and we haven't had any issues logged post stable. 🤞 that maintains once it's just there by default. 

Having to deal with and account for linker related issues is fairly common already on the Android side (see proguard) so this isn't really any different than what we have already been testing for on Android

Unless we actually remove UIWebView (which we might)  from our assembly this behavior is a necessary part of life so the flag doesn't really make sense to have. 

If we decide to rollback from being linker safe we'll just add a Preserve Attribute :-)

**Comment by chamons** [comment]
@spouliot - Between Shane (here) and a conversation with Sam I believe we're gotten enough :+1: for this - How hard would it be to make it happen?

**Comment by spouliot** [comment]
@chamons quite easy - I'll PR it
