### ISSUE TITLE
SecRandomCopyBytes not available on Xamarin.iOS

### ISSUE THREAD

**Issue by aimore** [xamarin/xamarin-macios#8415]
### Steps to Reproduce
I need to use the function SecRandomCopyBytes available in native iOS under security framework,
as suggested in this thread:
https://forums.xamarin.com/discussion/29750/how-to-call-secrandomcopybytes
@spouliot affirmed that using RNGCryptoServiceProvider type will internally call SecRandomCopyBytes, so it is **identical**.

Looking the Apple developer documentation we have the following description of this Function:

SecRandomCopyBytes
Generates an array of cryptographically secure random bytes.
Declaration
int SecRandomCopyBytes(SecRandomRef rnd, size_t count, void *bytes);

And looking to the Xamarin.iOS RNGCryptoServiceProvider reference we have:
``` 
public class RNGCryptoServiceProvider : RandomNumberGenerator
{
	public RNGCryptoServiceProvider ();

	public RNGCryptoServiceProvider (byte[] rgb);

	public RNGCryptoServiceProvider (CspParameters cspParams);

	public RNGCryptoServiceProvider (string str);

	~RNGCryptoServiceProvider ();

	public override void GetBytes (byte[] data);

	internal unsafe void GetBytes (byte* data, IntPtr data_length);

	public override void GetNonZeroBytes (byte[] data);
}

```

 How do I get the Function SecRandomCopyBytes returning a int?

**Comment by spouliot** [comment]
> @spouliot affirmed

Still around and sticking to my story :)

Here's the source file for the `RNGCryptoServiceProvider` implementation that ships with XI and XM

https://github.com/mono/mono/blob/2020-02/mcs/class/corlib/CommonCrypto/RNGCryptoServiceProvider.cryptor.cs

calling into

```
static internal unsafe void GetRandom (byte* data, IntPtr data_length)
{
	if (SecRandomCopyBytes (IntPtr.Zero, data_length, data) != 0)
		throw new CryptographicException (Marshal.GetLastWin32Error ()); // errno
}
```

https://github.com/mono/mono/blob/58b04da0d7c746c1a45eee1a14db1f50653e545f/mcs/class/corlib/CommonCrypto/CommonCrypto.cs#L114

> How do I get the Function SecRandomCopyBytes returning a int?

Why do you want the `int` ? it's not a random integer it's the static code that the API return.

> Return Value
> A result code set to errSecSuccess or some other value on failure.

https://developer.apple.com/documentation/security/1399291-secrandomcopybytes?language=objc

From the code above you can see that if any error occur (when fetching random data) then a `CryptographicException` will be thrown.

What developers _generally_ want is the random data and that's what `GetBytes` overloads gives you: they fill the supplied array with random bytes, throwing if the operation cannot be done.

If you really want the API then you can copy the p/invoke from https://github.com/mono/mono/blob/58b04da0d7c746c1a45eee1a14db1f50653e545f/mcs/class/corlib/CommonCrypto/CommonCrypto.cs#L104 and handle the validations and bytes-copying yourself.
