### ISSUE TITLE
Xamarin.iOS app crashes on startup during AppStore approval only

### ISSUE THREAD

**Issue by fettergabor** [xamarin/xamarin-macios#8416]
### Steps to Reproduce

The app starts up correctly on Simulator and device builds.
The app passes Testflight beta approval and starts up on various devices.
The very same binary fails during AppStore approval due to crash during startup.

### Expected Behavior

App launches successfully

### Actual Behavior

App crashes within a second during Xamarin intialzation. See crashlog below

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.5.3 (build 16)
Installation UUID: aecb18cf-c8fa-4072-8879-873fb667d5a0
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 608000123

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123

=== Roslyn (Language Service) ===

3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.101
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	2.1.17
	2.1.16
	2.1.15

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/gaborfetter/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/gaborfetter/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-04-09 23:37:36 UTC

=== Android Device Manager ===

Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5~1
Build date: 2020-04-09 23:37:56 UTC

=== Apple Developer Tools ===

Xcode 11.4.1 (16137)
Build 11E503a

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.16.0.13 (Visual Studio Community)
Hash: b75deaf82
Branch: d16-5-xcode11.4
Build date: 2020-04-01 21:33:19-0400

=== Xamarin Designer ===

Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805030016
Git revision: f2a24521eeb2011bdeea209eda827029938791fe
Build date: 2020-04-09 19:26:17-04
Build branch: release-8.5
Xamarin extensions: f2a24521eeb2011bdeea209eda827029938791fe

=== Operating System ===

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
[](url)
```

### Build Logs

Crash log:
{"app_name":"<app>","timestamp":"2020-04-07 11:51:41.94 -0700","app_version":"2.3.0","slice_uuid":"c19c8030-22c4-3771-a1f2-ba73661a9975","adam_id":1137566612,"build_version":"187","bundleID":"com.olympus-mobility.olympus","share_with_app_devs":false,"is_first_party":false,"bug_type":"109","os_version":"iPhone OS 13.3.1 (17D50)","incident_id":"63878985-72D9-4B41-8207-945039FE9DDE","name":"OlympusMobilityTouch"}
Incident Identifier: 63878985-72D9-4B41-8207-945039FE9DDE
CrashReporter Key:   0cf4898b22fa8325c3996b774dc58a6aa95ee653
Hardware Model:      iPad11,3
Process:             OlympusMobilityTouch [1161]
Path:                /private/var/containers/Bundle/Application/D6A90D1E-E03D-4E96-BE30-E04E8E7B88A2/<app>.app/<app>
Identifier:          com.olympus-mobility.olympus
Version:             187 (2.3.0)
AppStoreTools:       11E146
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.olympus-mobility.olympus [844]

Date/Time:           2020-04-07 11:51:41.2762 -0700
Launch Time:         2020-04-07 11:51:40.4410 -0700
OS Version:          iPhone OS 13.3.1 (17D50)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Thread 0 name:  tid_407  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001a4638efc 0x1a4613000 + 155388
1   libsystem_pthread.dylib       	0x00000001a45588b8 0x1a4556000 + 10424
2   libsystem_c.dylib             	0x00000001a44e8a74 0x1a4472000 + 486004
3   OlympusMobilityTouch          	0x0000000106ca4b18 xamarin_initialize.cold.1 + 0
4   OlympusMobilityTouch          	0x0000000106c9a470 xamarin_printf + 40920176 (runtime.m:2468)
5   OlympusMobilityTouch          	0x0000000106b5af30 mono_invoke_unhandled_exception_hook + 39612208 (exception.c:1299)
6   OlympusMobilityTouch          	0x0000000106aef570 mono_handle_exception_internal + 39171440 (mini-exceptions.c:2778)
7   OlympusMobilityTouch          	0x0000000106aedf94 mono_handle_exception + 39165844 (mini-exceptions.c:3102)
8   OlympusMobilityTouch          	0x0000000106ae37a0 mono_arm_throw_exception + 39122848 (exceptions-arm64.c:400)
9   OlympusMobilityTouch          	0x000000010513ca0c throw_exception + 172
10  OlympusMobilityTouch          	0x0000000104eef6fc System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw + 44
11  OlympusMobilityTouch          	0x0000000104ef6544 System_Runtime_CompilerServices_AsyncMethodBuilderCore__c__ThrowAsyncb__7_0_object + 84
12  OlympusMobilityTouch          	0x0000000105d667cc Foundation_NSAsyncSynchronizationContextDispatcher_Apply + 24979404 (NSAction.cs:178)
13  OlympusMobilityTouch          	0x00000001050fe340 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 272
14  OlympusMobilityTouch          	0x0000000106b0142c mono_jit_runtime_invoke + 39244844 (mini-runtime.c:3164)
15  OlympusMobilityTouch          	0x0000000106bc1b74 mono_runtime_invoke_checked + 40033140 (object.c:3212)
16  OlympusMobilityTouch          	0x0000000106bc5478 mono_runtime_invoke + 40047736 (object.c:3099)
17  OlympusMobilityTouch          	0x0000000104be5068 native_to_managed_trampoline_8(objc_object*, objc_selector*, _MonoMethod**, unsigned int) + 6623336 (registrar.m:341)
18  OlympusMobilityTouch          	0x0000000104c1b67c -[__MonoMac_NSAsyncSynchronizationContextDispatcher xamarinApplySelector] + 6846076 (registrar.m:22529)
19  libobjc.A.dylib               	0x00000001a4562a4c 0x1a4561000 + 6732
20  Foundation                    	0x00000001a4c43c00 0x1a4b01000 + 1321984
21  CoreFoundation                	0x00000001a47ca108 0x1a471c000 + 712968
22  CoreFoundation                	0x00000001a47ca05c 0x1a471c000 + 712796
23  CoreFoundation                	0x00000001a47c97c8 0x1a471c000 + 710600
24  CoreFoundation                	0x00000001a47c4694 0x1a471c000 + 689812
25  CoreFoundation                	0x00000001a47c3f40 0x1a471c000 + 687936
26  GraphicsServices              	0x00000001aea54534 0x1aea51000 + 13620
27  UIKitCore                     	0x00000001a894f580 0x1a7f0c000 + 10761600
28  OlympusMobilityTouch          	0x0000000105dbb9fc wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 348
29  OlympusMobilityTouch          	0x0000000105d2bdc0 UIKit_UIApplication_Main_string___intptr_intptr + 24739264 (UIApplication.cs:86)
30  OlympusMobilityTouch          	0x0000000105d2bd44 UIKit_UIApplication_Main_string___string_string + 24739140 (UIApplication.cs:66)
31  OlympusMobilityTouch          	0x0000000104c477f4 Olympus_Mobility_Touch_Application_Main_string__ + 7026676 (/<unknown>:1)
32  OlympusMobilityTouch          	0x00000001050fe340 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 272
33  OlympusMobilityTouch          	0x0000000106b0142c mono_jit_runtime_invoke + 39244844 (mini-runtime.c:3164)
34  OlympusMobilityTouch          	0x0000000106bc1b74 mono_runtime_invoke_checked + 40033140 (object.c:3212)
35  OlympusMobilityTouch          	0x0000000106bc7f80 mono_runtime_exec_main_checked + 40058752 (object.c:5273)
36  OlympusMobilityTouch          	0x0000000106adf580 mono_jit_exec + 39105920 (driver.c:1267)
37  OlympusMobilityTouch          	0x0000000106ca1798 xamarin_main + 40949656 (monotouch-main.m:0)
38  OlympusMobilityTouch          	0x0000000104c328c0 main + 6940864 (main.m:190)
39  libdyld.dylib                 	0x00000001a4642e18 0x1a4642000 + 3608

Thread 1:
0   libsystem_pthread.dylib       	0x00000001a455f9e0 0x1a4556000 + 39392

Thread 2:
0   libsystem_pthread.dylib       	0x00000001a455f9e0 0x1a4556000 + 39392

Thread 3 name:  Dispatch queue: com.google.FirebaseInstanceID.Keychain
Thread 3:
0   libsystem_kernel.dylib        	0x00000001a4616c04 0x1a4613000 + 15364
1   libsystem_kernel.dylib        	0x00000001a4616020 0x1a4613000 + 12320
2   libdispatch.dylib             	0x00000001a4509510 0x1a44f1000 + 99600
3   libdispatch.dylib             	0x00000001a4509904 0x1a44f1000 + 100612
4   libxpc.dylib                  	0x00000001a4449594 0x1a443d000 + 50580
5   Security                      	0x00000001a569db18 0x1a567d000 + 133912
6   Security                      	0x00000001a569e58c 0x1a567d000 + 136588
7   Security                      	0x00000001a5724d24 0x1a567d000 + 687396
8   Security                      	0x00000001a572377c 0x1a567d000 + 681852
9   Security                      	0x00000001a572263c 0x1a567d000 + 677436
10  Security                      	0x00000001a5723000 0x1a567d000 + 679936
11  Security                      	0x00000001a5724c10 0x1a567d000 + 687120
12  Security                      	0x00000001a5720bdc 0x1a567d000 + 670684
13  Security                      	0x00000001a5723f34 0x1a567d000 + 683828
14  FirebaseInstanceID            	0x0000000107b5e740 __39-[FIRInstanceIDKeychain itemWithQuery:]_block_invoke + 44
15  libdispatch.dylib             	0x00000001a44f3fd8 0x1a44f1000 + 12248
16  libdispatch.dylib             	0x00000001a45007f4 0x1a44f1000 + 63476
17  FirebaseInstanceID            	0x0000000107b5e6dc -[FIRInstanceIDKeychain itemWithQuery:] + 124
18  FirebaseInstanceID            	0x0000000107b5f3f8 FIRInstanceIDKeyDataWithTag + 116
19  FirebaseInstanceID            	0x0000000107b60434 +[FIRInstanceIDKeyPairStore keyPairForPrivateKeyTag:publicKeyTag:error:] + 156
20  FirebaseInstanceID            	0x0000000107b60368 -[FIRInstanceIDKeyPairStore cachedKeyPairWithSubtype:error:] + 108
21  FirebaseInstanceID            	0x0000000107b60280 -[FIRInstanceIDKeyPairStore validCachedKeyPairWithSubtype:error:] + 232
22  FirebaseInstanceID            	0x0000000107b5fcbc -[FIRInstanceIDKeyPairStore loadKeyPairWithError:] + 292
23  FirebaseInstanceID            	0x0000000107b5fac8 -[FIRInstanceIDKeyPairStore appIdentityWithError:] + 36
24  FirebaseInstanceID            	0x0000000107b52798 -[FIRInstanceID+ 26520 (Private) appInstanceID:] + 56
25  OlympusMobilityTouch          	0x0000000104b604f4 -[APMIdentity firebaseInstanceID] + 152
26  OlympusMobilityTouch          	0x0000000104b6c448 -[APMMeasurement createRawEventMetadataWithUserAttributes:] + 608
27  OlympusMobilityTouch          	0x0000000104b697e0 __42-[APMMeasurement writeEventOnWorkerQueue:]_block_invoke.1192 + 256
28  OlympusMobilityTouch          	0x0000000104b90c84 -[APMSqliteStore performTransaction:] + 92
29  OlympusMobilityTouch          	0x0000000104b687ec -[APMMeasurement writeEventOnWorkerQueue:] + 1404
30  OlympusMobilityTouch          	0x0000000104b67fd4 -[APMMeasurement handleEventOnWorkerQueue:] + 1320
31  OlympusMobilityTouch          	0x0000000104b7c710 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 44
32  libdispatch.dylib             	0x00000001a44f2b7c 0x1a44f1000 + 7036
33  libdispatch.dylib             	0x00000001a44f3fd8 0x1a44f1000 + 12248
34  libdispatch.dylib             	0x00000001a44fa450 0x1a44f1000 + 37968
35  libdispatch.dylib             	0x00000001a44fae7c 0x1a44f1000 + 40572
36  libdispatch.dylib             	0x00000001a4503f20 0x1a44f1000 + 77600
37  libsystem_pthread.dylib       	0x00000001a45596d0 0x1a4556000 + 14032
38  libsystem_pthread.dylib       	0x00000001a455f9e8 0x1a4556000 + 39400

**Comment by chamons** [comment]
```
5 OlympusMobilityTouch 0x0000000106b5af30 mono_invoke_unhandled_exception_hook + 39612208 (exception.c:1299)
6 OlympusMobilityTouch 0x0000000106aef570 mono_handle_exception_internal + 39171440 (mini-exceptions.c:2778)
7 OlympusMobilityTouch 0x0000000106aedf94 mono_handle_exception + 39165844 (mini-exceptions.c:3102)
8 OlympusMobilityTouch 0x0000000106ae37a0 mono_arm_throw_exception + 39122848 (exceptions-arm64.c:400)
9 OlympusMobilityTouch 0x000000010513ca0c throw_exception + 172
10 OlympusMobilityTouch 0x0000000104eef6fc System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw + 44
11 OlympusMobilityTouch 0x0000000104ef6544 System_Runtime_CompilerServices_AsyncMethodBuilderCore__c__ThrowAsyncb__7_0_object + 84
12 OlympusMobilityTouch 0x0000000105d667cc Foundation_NSAsyncSynchronizationContextDispatcher_Apply + 24979404 (NSAction.cs:178)
13 OlympusMobilityTouch 0x00000001050fe340 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 272
14 OlympusMobilityTouch 0x0000000106b0142c mono_jit_runtime_invoke + 39244844 (mini-runtime.c:3164)
15 OlympusMobilityTouch 0x0000000106bc1b74 mono_runtime_invoke_checked + 40033140 (object.c:3212)
16 OlympusMobilityTouch 0x0000000106bc5478 mono_runtime_invoke + 40047736 (object.c:3099)
17 OlympusMobilityTouch 0x0000000104be5068 native_to_managed_trampoline_8(objc_object*, objc_selector*, _MonoMethod**, unsigned int) + 6623336 (registrar.m:341)
18 OlympusMobilityTouch 0x0000000104c1b67c -[MonoMac_NSAsyncSynchronizationContextDispatcher xamarinApplySelector] + 6846076 (registrar.m:22529)
```

That suggests we had some managed exception that "bubbled up" and was unhandled. However, without a sample or more details it is impossible to know more.

Please attach more details and/or a sample project showing the issue.

**Comment by fettergabor** [comment]
Thank you for the feedback!
Meanwhile Apple approved the binary without comments.
Also I came across a thread where people claim that this kind of crash happens when using certain versions of Firebase nuget: https://github.com/firebase/firebase-ios-sdk/issues/4504
