### ISSUE TITLE
NSInvalidArgumentException: -[NSScreen localizedName]: unrecognized selector sent to instance 0x7fece30c9f70

### ISSUE THREAD

**Issue by spouliot** [xamarin/xamarin-macios#8420]
### Steps to Reproduce

1. run apitest test on headless mac

### Expected Behavior

no failure

### Actual Behavior

```
NSInvalidArgumentException: -[NSScreen localizedName]: unrecognized selector sent to instance 0x7fece30c9f70
```

### Environment

`master`

### Build Logs

See https://github.com/xamarin/xamarin-macios/commit/28eddda4391cc8854c00d07eff8aaab1948d8013

**Comment by mandel-macaque** [comment]
Was closed by https://github.com/xamarin/xamarin-macios/pull/8422
