### ISSUE TITLE
Hide advanced NSObject members to follow Xamarin.Android

### ISSUE THREAD

**Issue by rolfbjarne** [xamarin/xamarin-macios#8439]
Suggestion:

Hide members from NSObject that customers shouldn't use.

Candidates:

* Handle: https://github.com/xamarin/xamarin-macios/blob/337f3efac4062ad07fd6f9f9c9fd6db40d2454cc/src/Foundation/NSObject2.cs#L461
* SuperHandle: https://github.com/xamarin/xamarin-macios/blob/337f3efac4062ad07fd6f9f9c9fd6db40d2454cc/src/Foundation/NSObject2.cs#L446
* IntPtr constructor (never seen this constructor used): https://github.com/xamarin/xamarin-macios/blob/337f3efac4062ad07fd6f9f9c9fd6db40d2454cc/src/Foundation/NSObject2.cs#L134
* IntPtr, bool constructor (never seen this constructor get used): https://github.com/xamarin/xamarin-macios/blob/337f3efac4062ad07fd6f9f9c9fd6db40d2454cc/src/Foundation/NSObject2.cs#L137
* Alloc (never seen this method used): https://github.com/xamarin/xamarin-macios/blob/337f3efac4062ad07fd6f9f9c9fd6db40d2454cc/src/Foundation/NSObject.iOS.cs#L31
* Init (never seen this method used): https://github.com/xamarin/xamarin-macios/blob/337f3efac4062ad07fd6f9f9c9fd6db40d2454cc/src/Foundation/NSObject.iOS.cs#L36
* IsDirectBinding (required by binding code, but afaik never called directly by customers): https://github.com/xamarin/xamarin-macios/blob/337f3efac4062ad07fd6f9f9c9fd6db40d2454cc/src/Foundation/NSObject2.cs#L96
* IsNewRefCountEnabled (should never need to be called by customers since does nothing but return a constant value): https://github.com/xamarin/xamarin-macios/blob/337f3efac4062ad07fd6f9f9c9fd6db40d2454cc/src/Foundation/NSObject2.cs#L166
* MarkDirty (required by binding code afaik, but shouldn't have to be called by customers): https://github.com/xamarin/xamarin-macios/blob/337f3efac4062ad07fd6f9f9c9fd6db40d2454cc/src/Foundation/NSObject2.cs#L177

Ref:

* https://github.com/xamarin/xamarin-android/pull/4583
* https://xamarinhq.slack.com/archives/C03CCJNR7/p1587407994218100

**Comment by spouliot** [comment]
Semi random thoughts...

I do not see an issue hiding the properties (`[Super]Handle`) from intellisense but IMO they should remain visible in the debugger.

The only times I recall seeing `NSObject` constructors are related to manual binding code for
* adding a `NSObject`-based pointer to a weak/native managed collection (processed by native code);
* create an instance of an unknown type to get its description

TBH we forgot to make them `protected` in `XAMCORE_2_0` like the generated bindings for the subclasses. So the same _solution_ is that use `Runtime.GetNSObject<NSObject> (ptr)` if it's really needed (not that we're talking about removing them).

**Comment by dalexsoto** [comment]
By Hide you mean adding `EditorBrowsable` with `Advanced` or `Never` right? If so 👍 but I have to agree with @spouliot that `[Super]Handle` should still be visible under the debugger.
