### ISSUE TITLE
Xamarin AOT compiler error for 32 bit architecture

### ISSUE THREAD

**Issue by omatrot** [xamarin/xamarin-macios#8448]
### Steps to Reproduce

1. Create a new Xamarin.iOS project
2. Add the SixLabors.ImageSharp nuget beta-0007
3. Add some code to use the library
4. Make sure to target armv7.

### Expected Behavior

Build without error

### Actual Behavior

The assembly 'SixLabors.ImageSharp.dll' can't be AOT-compiled for 32-bit architectures because the native code is too big for the 32-bit ARM architecture

### Environment

```
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.6 Preview (8.6 build 4243)
Installation UUID: 044fc49d-ee45-4736-9dc5-fcb04c42c8b1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000101

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.101 (2019-12/6f0bf73005d) (64-bit)
	Package version: 610000101

=== Roslyn (Language Service) ===

3.6.0-3.20209.3+34fad56309fc96f2af1171df6ea012cbf991c27d

=== NuGet ===

Version: 5.5.0.6473

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.100
	3.1.100-preview3-014645
	3.1.100-preview2-014569
	3.0.100
	3.0.100-rc1-014190
	3.0.100-preview9-014004
	3.0.100-preview8-013656
	2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.0
	3.1.0-preview3.19553.2
	3.1.0-preview2.19525.6
	3.0.0
	3.0.0-rc1-19456-20
	3.0.0-preview9-19423-09
	2.1.17
	2.1.16
	2.1.14
	2.1.13
	2.1.12

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.4.1 (16137)
Build 11E503a

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.18.1.31 (Visual Studio Community)
Hash: b3eedfed9
Branch: d16-6
Build date: 2020-04-09 10:22:36-0400

=== Xamarin Designer ===

Version: 16.6.0.320
Hash: dcc2cd183
Branch: remotes/origin/d16-6
Build date: 2020-04-10 18:49:40 UTC

=== Xamarin.Android ===

Version: 10.3.0.74 (Visual Studio Community)
Commit: xamarin-android/d16-6/964ac42
Android SDK: /Users/omatrot/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/omatrot/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.46
Hash: f6bfa7b
Branch: remotes/origin/dev/joe/d16-6~2
Build date: 2020-04-09 20:14:24 UTC

=== Android Device Manager ===

Version: 16.6.0.75
Hash: 4509c53
Branch: remotes/origin/d16-6~6
Build date: 2020-04-09 20:14:50 UTC

=== Build Information ===

Release ID: 806004243
Git revision: dda82db2458288a91a58f44d24abe41cf0d25bb6
Build date: 2020-04-14 16:13:25-04
Build branch: release-8.6
Xamarin extensions: dda82db2458288a91a58f44d24abe41cf0d25bb6

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Sun Apr  5 21:30:12 PDT 2020
    root:xnu-6153.120.27~16/RELEASE_X86_64 x86_64


```

### Example Project (If Possible)

=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.6 Preview (8.6 build 4243)
Installation UUID: 044fc49d-ee45-4736-9dc5-fcb04c42c8b1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000101

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.101 (2019-12/6f0bf73005d) (64-bit)
	Package version: 610000101

=== Roslyn (Language Service) ===

3.6.0-3.20209.3+34fad56309fc96f2af1171df6ea012cbf991c27d

=== NuGet ===

Version: 5.5.0.6473

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.100
	3.1.100-preview3-014645
	3.1.100-preview2-014569
	3.0.100
	3.0.100-rc1-014190
	3.0.100-preview9-014004
	3.0.100-preview8-013656
	2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.0
	3.1.0-preview3.19553.2
	3.1.0-preview2.19525.6
	3.0.0
	3.0.0-rc1-19456-20
	3.0.0-preview9-19423-09
	2.1.17
	2.1.16
	2.1.14
	2.1.13
	2.1.12

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.4.1 (16137)
Build 11E503a

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.18.1.31 (Visual Studio Community)
Hash: b3eedfed9
Branch: d16-6
Build date: 2020-04-09 10:22:36-0400

=== Xamarin Designer ===

Version: 16.6.0.320
Hash: dcc2cd183
Branch: remotes/origin/d16-6
Build date: 2020-04-10 18:49:40 UTC

=== Xamarin.Android ===

Version: 10.3.0.74 (Visual Studio Community)
Commit: xamarin-android/d16-6/964ac42
Android SDK: /Users/omatrot/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/omatrot/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.46
Hash: f6bfa7b
Branch: remotes/origin/dev/joe/d16-6~2
Build date: 2020-04-09 20:14:24 UTC

=== Android Device Manager ===

Version: 16.6.0.75
Hash: 4509c53
Branch: remotes/origin/d16-6~6
Build date: 2020-04-09 20:14:50 UTC

=== Build Information ===

Release ID: 806004243
Git revision: dda82db2458288a91a58f44d24abe41cf0d25bb6
Build date: 2020-04-14 16:13:25-04
Build branch: release-8.6
Xamarin extensions: dda82db2458288a91a58f44d24abe41cf0d25bb6

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Sun Apr  5 21:30:12 PDT 2020
    root:xnu-6153.120.27~16/RELEASE_X86_64 x86_64

build log as an attachment.
[build.log](https://github.com/xamarin/xamarin-macios/files/4522064/build.log)

**Comment by chamons** [comment]
As the error suggests:

`MTOUCH : error MT5107: The assembly 'SixLabors.ImageSharp.dll' can't be AOT-compiled for 32-bit architectures because the native code is too big for the 32-bit ARM architecture.`

the problem here is that the generated code is too big for the limits of 32-bit binaries. 

This is a limitation of the 32-bit format, not a bug in Xamarin.iOS. The same exact thing can happen to any tool generating native code.

You have a few options:

- Drop 32-bit archs
- Reduce your binary size, by [enabling the linker](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=macos), removing code, etc

**Comment by FrankSzendzielarz** [comment]
Well, would be if Hot Reload didn't require "Don't Link"
