### ISSUE TITLE
clang: error: linker command failed with exit code 1 ... error MT5216: Native linking failed

### ISSUE THREAD

**Issue by douglaskbell** [xamarin/xamarin-macios#8449]
### Steps to Reproduce

1. Built Mac > Visual Studio > Xamarion.ios .Net Standard class library 
2. Embeddinator-4000/objcgen/_build/objcgen     ... bin/Debug/netstandard2.0/my_app.dll --target=framework --platform=iOS --outdir=output -c --debug
3. 

### Expected Behavior
Prepare a Xamarin.ios project for use by an Xcode ObjC project.
### Actual Behavior
objCgen (step 2 above) got Linker error:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error MT5216: Native linking failed for '/PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/arm64/ACQUISITION_USB_HOST_STUBBED_OUT'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new

### Environment

```
```

### Build Logs

DOUGs-MacBook-Pro:SYSTEM_HUB_-_baseline dbell$ /PRIMARY/WORK/attempt4_3-24-20b/Embeddinator-4000/objcgen/_build/objcgen     "/PRIMARY/WORK/SYSTEM_HUB_-_baseline/ACQUISITION_USB_HOST_CS_STUBBED_OUT/bin/Debug/netstandard2.0/ACQUISITION_USB_HOST_STUBBED_OUT.dll" --target=framework --platform=iOS --outdir=output -c --debug
Parsing assemblies...
	Parsed '/PRIMARY/WORK/SYSTEM_HUB_-_baseline/ACQUISITION_USB_HOST_CS_STUBBED_OUT/bin/Debug/netstandard2.0/ACQUISITION_USB_HOST_STUBBED_OUT.dll'
Processing assemblies...
	2 types found
Generating binding code...
	Generated: output/bindings.h
	Generated: output/bindings-private.h
	Generated: output/bindings.m
	Generated: output/bindings.xml
	Generated: output/embeddinator.h
	Generated: output/glib.h
	Generated: output/mono_embeddinator.h
	Generated: output/mono-support.h
	Generated: output/objc-support.h
	Generated: output/glib.c
	Generated: output/mono_embeddinator.c
	Generated: output/objc-support.m
	Generated: output/Make.config
Compiling binding code...
Found Mono 6.8.0.123 (between 5.16.0.221 and 5.16.0.221)
Found Xamarin.iOS 13.16.0.13 (between 12.2.1.12 and 12.2.1.12)
	xcode-select -p
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/glib.c -o output/armv7/glib.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/mono_embeddinator.c -o output/armv7/mono_embeddinator.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/objc-support.m -o output/armv7/objc-support.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/bindings.m -o output/armv7/bindings.o 
	xcrun ar cru output/armv7/ACQUISITION_USB_HOST_STUBBED_OUT.a output/armv7/glib.o output/armv7/mono_embeddinator.o output/armv7/objc-support.o output/armv7/bindings.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/glib.c -o output/armv7s/glib.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/mono_embeddinator.c -o output/armv7s/mono_embeddinator.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/objc-support.m -o output/armv7s/objc-support.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/bindings.m -o output/armv7s/bindings.o 
	xcrun ar cru output/armv7s/ACQUISITION_USB_HOST_STUBBED_OUT.a output/armv7s/glib.o output/armv7s/mono_embeddinator.o output/armv7s/objc-support.o output/armv7s/bindings.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/glib.c -o output/arm64/glib.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/mono_embeddinator.c -o output/arm64/mono_embeddinator.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/objc-support.m -o output/arm64/objc-support.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/bindings.m -o output/arm64/bindings.o 
	xcrun ar cru output/arm64/ACQUISITION_USB_HOST_STUBBED_OUT.a output/arm64/glib.o output/arm64/mono_embeddinator.o output/arm64/objc-support.o output/arm64/bindings.o 
	xcrun lipo output/armv7/ACQUISITION_USB_HOST_STUBBED_OUT.a output/armv7s/ACQUISITION_USB_HOST_STUBBED_OUT.a output/arm64/ACQUISITION_USB_HOST_STUBBED_OUT.a -create -output output/iPhoneOS/ACQUISITION_USB_HOST_STUBBED_OUT.a
	xcrun --show-sdk-version --sdk iphoneos
	/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch --dev /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/ACQUISITION_USB_HOST_STUBBED_OUT --abi=armv7,armv7s,arm64 --sdkroot /Applications/Xcode.app --targetver 8.0 --dsym:false --msym:false --embeddinator /PRIMARY/WORK/SYSTEM_HUB_-_baseline/ACQUISITION_USB_HOST_CS_STUBBED_OUT/bin/Debug/netstandard2.0/ACQUISITION_USB_HOST_STUBBED_OUT.dll -r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Xamarin.iOS.dll --sdk 13.2 --linksdkonly --xml=output/bindings.xml --registrar:static --cache /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache --debug --assembly-build-target=@all=framework=ACQUISITION_USB_HOST_STUBBED_OUT.framework --target-framework Xamarin.iOS,v1.0 "--gcc_flags=-force_load /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/ACQUISITION_USB_HOST_STUBBED_OUT.a" 
warning MT0079: The recommended Xcode version for Xamarin.iOS 13.16.0 is Xcode 11.4 or later. The current Xcode version (found in /Applications/Xcode.app) is 11.3.1.
Xamarin.iOS 13.16.0.13 (d16-5-xcode11.4): b75deaf82) using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk
Compilation failed with code 1, command:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -framework UIKit -framework Foundation -weak_framework CFNetwork -weak_framework GSS -Xlinker -rpath -Xlinker @executable_path/ /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/arm64/ACQUISITION_USB_HOST_STUBBED_OUT.dll.o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/arm64/mscorlib.dll.o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/arm64/System.dll.o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/arm64/Xamarin.iOS.dll.o /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libmonosgen-2.0.a /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libxamarin-debug.a /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libmono-native-compat.a /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/arm64/registrar.o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/arm64/main.o -force_load /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/ACQUISITION_USB_HOST_STUBBED_OUT.a -lz -liconv -lz -gdwarf-2 -std=c++14 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/SDKs/MonoTouch.iphoneos.sdk/usr/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -Qunused-arguments -miphoneos-version-min=8.0 -arch arm64 -shared -lz -liconv -install_name @rpath/ACQUISITION_USB_HOST_STUBBED_OUT.framework/ACQUISITION_USB_HOST_STUBBED_OUT -fapplication-extension -o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/arm64/ACQUISITION_USB_HOST_STUBBED_OUT -D DEBUG
Undefined symbols for architecture arm64:
  "___darwin_check_fd_set_overflow", referenced from:
      _monotouch_connect_usb in libxamarin-debug.a(monotouch-debug-debug.arm64.o)
      _monotouch_connect_wifi in libxamarin-debug.a(monotouch-debug-debug.arm64.o)
      _monotouch_debug_listen in libxamarin-debug.a(monotouch-debug-debug.arm64.o)
      _monotouch_debug_connect in libxamarin-debug.a(monotouch-debug-debug.arm64.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Compilation failed with code 1, command:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -framework UIKit -framework Foundation -weak_framework CFNetwork -weak_framework GSS -Xlinker -rpath -Xlinker @executable_path/ /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7/ACQUISITION_USB_HOST_STUBBED_OUT.dll.o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7/mscorlib.dll.o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7/System.dll.o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7/Xamarin.iOS.dll.o /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libmonosgen-2.0.a /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libxamarin-debug.a /Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/SDKs/MonoTouch.iphoneos.sdk/usr/lib/libmono-native-compat.a /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7/registrar.o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7s/registrar.o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7/main.o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7s/main.o -force_load /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/ACQUISITION_USB_HOST_STUBBED_OUT.a -lz -liconv -lz -gdwarf-2 -std=c++14 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/13.16.0.13/SDKs/MonoTouch.iphoneos.sdk/usr/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -Qunused-arguments -miphoneos-version-min=8.0 -arch armv7 -shared -read_only_relocs suppress -lz -liconv -install_name @rpath/ACQUISITION_USB_HOST_STUBBED_OUT.framework/ACQUISITION_USB_HOST_STUBBED_OUT -fapplication-extension -o /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7/ACQUISITION_USB_HOST_STUBBED_OUT -D DEBUG
ld: warning: ignoring file /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7s/registrar.o, building for iOS-armv7 but attempting to link with file built for iOS-armv7s
ld: warning: ignoring file /PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/armv7s/main.o, building for iOS-armv7 but attempting to link with file built for iOS-armv7s
Undefined symbols for architecture armv7:
  "___darwin_check_fd_set_overflow", referenced from:
      _monotouch_connect_usb in libxamarin-debug.a(monotouch-debug-debug.armv7.o)
      _monotouch_connect_wifi in libxamarin-debug.a(monotouch-debug-debug.armv7.o)
      _monotouch_debug_listen in libxamarin-debug.a(monotouch-debug-debug.armv7.o)
      _monotouch_debug_connect in libxamarin-debug.a(monotouch-debug-debug.armv7.o)
      _monotouch_connect_usb in libxamarin-debug.a(monotouch-debug-debug.armv7.o)
      _monotouch_connect_wifi in libxamarin-debug.a(monotouch-debug-debug.armv7.o)
      _monotouch_debug_listen in libxamarin-debug.a(monotouch-debug-debug.armv7.o)
      _monotouch_debug_connect in libxamarin-debug.a(monotouch-debug-debug.armv7.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error MT5216: Native linking failed for '/PRIMARY/WORK/SYSTEM_HUB_-_baseline/output/iPhoneOS/build-cache/arm64/ACQUISITION_USB_HOST_STUBBED_OUT'. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new

Done
DOUGs-MacBook-Pro:SYSTEM_HUB_-_baseline dbell$ 
DOUGs-MacBook-Pro:SYSTEM_HUB_-_baseline dbell$

**Comment by chamons** [comment]
This should really be filed in https://github.com/mono/embeddinator-4000/issues/new

I believe you are hitting https://github.com/xamarin/xamarin-macios/issues/8325

To quote that issue:

```
Due to a bug introduced in Xcode 11.4 by Apple this currently does not work with the latest Xamarin.iOS. This is being tracked in mono as well.

Until then, your best option is to have a matching Xcode and Xamarin SDK either by:

    Upgrading your Xcode to 11.4 to use with recent Xamarin.iOS and Mac
    Downgrading your Xamarin.iOS to match your Xcode.
```

**Comment by douglaskbell** [comment]
Yep, that was the problem.

CLOSED.
