### ISSUE TITLE
iOS Extension projects run in Debug can show "Unable to Load" or have difficulty debugging

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#8470]
### Steps to Reproduce

1. New iOS Project
2. Add iOS Today Extension
3. Launch app
4. Add extension to today screen

### Expected Behavior

Debug extensions to work. 

### Actual Behavior

Extension shows up as "Unable to Load" or breakpoints do not work.

### Environment

https://gist.github.com/chamons/b717a9f04143f0670a27131b49a415fa

### Example Project (If Possible)

[AppWithExtension.zip](https://github.com/xamarin/xamarin-macios/files/4552184/AppWithExtension.zip)

> VS bug [#1112705](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1112705), VS bug [#1112706](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1112706), VS bug [#1114734](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1114734)

**Comment by chamons** [comment]
A possible work around for some use cases:

Add `--profiling=false` to the "Additional mtouch arguments" of both your iOS main project and the extension

**Comment by marek-safar** [comment]
@lambdageek do we know what is causing profiling failures in this scenario?

**Comment by chamons** [comment]
Sorry, one bit didn't make it into the issue:

```
Termination Description: DYLD, dependent dylib '@rpath/libmono-profiler-log.dylib' not found for '/private/var/containers/Bundle/Application/7657D8B0-A89D-4F3D-B735-D72F5E02C111/AppWithExtension.app/PlugIns/TodayTest.appex/TodayTest', tried but didn't find: '/private/var/containers/Bundle/Application/7657D8B0-A89D-4F3D-B735-D72F5E02C111/AppWithExtension.app/PlugIns/TodayTest.appex/Frameworks/libmono-profiler-log.dylib' '/private/var/containers/Bundle/Application/7657D8B0-A89D-4F3D-B735-D72F5E02C111/AppWithExtension.app/PlugIns/TodayTest.appex/../../Frameworks/libmono-profiler-log.dylib' '/private/var/containers/Bundle/Application/7657D8B0-A89D-4F3D-B735-D72F5E02C111/AppWithExtension.app/PlugIns/TodayTest.appex//libmono-profiler-log.dylib' '/private/var/containers/Bundle/Application/7657D8B0-A89D-4F3D-B735-D72F5E02C111/AppWithExtension.app/PlugIns/TodayTest.appex/../../libmono-profiler-log.dylib' '@rpath/libmono-profiler-log.dylib' '/usr/local/lib/libmono-profiler-log.dylib' '/usr/lib/libmono-profiler-log.dylib'
```

I'm assuming we could tweek mtouch to copy this into the extension, if this is a supported use case?

**Comment by rolfbjarne** [comment]
> I'm assuming we could tweek mtouch to copy this into the extension, if this is a supported use case?

Yes, the problem is probably that we're not copying it where the executable expects it.

**Comment by spouliot** [comment]
You can also remove this line (twice, two configs) from `TodayTest.csproj`
```
    <MtouchProfiling>true</MtouchProfiling>
```
that will disable profiling. That is, of course, a workaround if you don't need profiling.

That's the msbuild property that maps to `[x] Enable profiling` under the **iOS Debug** options.

The problem seems to be in `Target.cs` where we link with the library but only copy it it the app has a framework directory, which differs a bit for extensions.

```csharp
switch (App.LibProfilerLinkMode) {
case AssemblyBuildTarget.DynamicLibrary:
	libprofiler = Path.Combine (libmonodir, "libmono-profiler-log.dylib");
	linker_flags.AddLinkWith (libprofiler);
	if (App.HasFrameworksDirectory)
		AddToBundle (libprofiler);
	break;
```
