### ISSUE TITLE
[Meta] Xcode 11.5 Support

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#8475]
This is a meta issue tracking the status of our Xcode 11.5 support.

## Status

Xcode 11.5 GA is out now and support has been merged into [d16-6](https://github.com/xamarin/xamarin-macios/commits/d16-6) branch.

The team is working on producing the next service release, our candidates are:

- [xamarin.ios-13.18.2.0.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-6/7af99d6e88aa7102ae371743ff10abe7877c452a/48/package/notarized/xamarin.ios-13.18.2.0.pkg)
- [xamarin.mac-6.18.2.0.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-6/7af99d6e88aa7102ae371743ff10abe7877c452a/48/package/notarized/xamarin.mac-6.18.2.0.pkg)

If you are looking for the Exposure Notification APIs go [here](https://github.com/xamarin/xamarin.exposurenotification).

**Comment by beeradmoore** [comment]
I just received Xamarin.iOS 13.18.2.1 in the VS4Mac via the stable updater.

**Comment by dalexsoto** [comment]
Xamarin.iOS 13.18.2.1 is in the stable channel, this issue is not needed anymore. **If you are looking for the Exposure Notification APIs go [here](https://github.com/xamarin/xamarin.exposurenotification).**
