### ISSUE TITLE
[Harness] Xharness does not use the xcode-select value to find xcode.

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#8584]
This supposes  a problem when using a different path. Xharness should not look for a specific path, but should use what xcode-select returns instead.

Failure example: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3721428&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=f8b2b113-8dc4-5f3a-9c34-f3fdcd1cb70c

**Comment by rolfbjarne** [comment]
It's the other way around, the system Xcode (what xcode-select returns) should be made to point to the Xcode configured in xamarin-macios.

**Comment by rolfbjarne** [comment]
Actually, I think xharness should not use the system Xcode, because that makes it impossible to run tests from different branches that uses different Xcode's at the same time (yes, I do that locally).

**Comment by whitneyschmidt** [comment]
```
[21:43:28 ERR] /Users/xamarinqa/azdo/_work/92/s/xamarin-macios/tools/devops/device-tests-provisioning.csx(9,71): error CS1739: The best overload for 'XcodeSelect' does not have a parameter named 'symlinkTarget'
```

**Comment by mandel-macaque** [comment]
@whitneyschmidt that is a not related issue, that is because the provisionator was not released with my changes, @cadsit already fixed that.

**Comment by rolfbjarne** [comment]
Closing according to my latest comment.
