### ISSUE TITLE
Can't build a release package

### ISSUE THREAD

**Issue by c0d3l3ss** [xamarin/xamarin-macios#8604]
Building SophiaMobile.iOS (Release)
Build started 5/16/2020 3:36:42 AM.
__________________________________________________
Project "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile/SophiaMobile.csproj" (Build target(s)):

Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target XamlG:
  Skipping target "XamlG" because all output files are up-to-date with respect to the input files.
Target CssG:
  Skipping target "CssG" because it has no outputs.
Target CssG:
  Skipping target "CssG" because it has no outputs.
Target CoreGenerateAssemblyInfo:
  Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
Target CoreCompile:
  Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
Target XamlC:
  Skipping target "XamlC" because all output files are up-to-date with respect to the input files.
Target _CopyOutOfDateSourceItemsToOutputDirectory:
  Skipping target "_CopyOutOfDateSourceItemsToOutputDirectory" because all output files are up-to-date with respect to the input files.
Target GenerateBuildDependencyFile:
  Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
Target CopyFilesToOutputDirectory:
    SophiaMobile -> /Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile/bin/Release/netstandard2.0/SophiaMobile.dll
__________________________________________________
Project "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile.iOS/SophiaMobile.iOS.csproj" (Build target(s)):

Target _BeforeCoreCompileInterfaceDefinitions:
  Skipping target "_BeforeCoreCompileInterfaceDefinitions" because all output files are up-to-date with respect to the input files.
Target _CoreCompileInterfaceDefinitions:
  Skipping target "_CoreCompileInterfaceDefinitions" because all output files are up-to-date with respect to the input files.
Target _BeforeCoreCompileImageAssets:
  Skipping target "_BeforeCoreCompileImageAssets" because all output files are up-to-date with respect to the input files.
Target _CoreCompileImageAssets:
  Skipping target "_CoreCompileImageAssets" because all output files are up-to-date with respect to the input files.
Target _CoreCompileColladaAssets:
  Skipping target "_CoreCompileColladaAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _CoreCompileSceneKitAssets:
  Skipping target "_CoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _CoreCompileTextureAtlases:
  Skipping target "_CoreCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileCoreMLModels:
  Skipping target "_BeforeCompileCoreMLModels" because all output files are up-to-date with respect to the input files.
Target _CoreCompileCoreMLModels:
  Skipping target "_CoreCompileCoreMLModels" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizePngImages:
  Skipping target "_CoreOptimizePngImages" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizePropertyLists:
  Skipping target "_CoreOptimizePropertyLists" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizePropertyLists:
  Skipping target "_CoreOptimizePropertyLists" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because all output files are up-to-date with respect to the input files.
Target _GetProjectReferenceTargetFrameworkProperties:
    __________________________________________________
    Project "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile.iOS/SophiaMobile.iOS.csproj" is building "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile/SophiaMobile.csproj" (GetTargetFrameworks target(s)):

Target ResolveProjectReferences:
    __________________________________________________
    Project "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile.iOS/SophiaMobile.iOS.csproj" is building "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile/SophiaMobile.csproj" (GetTargetPath target(s)):

    __________________________________________________
    Project "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile.iOS/SophiaMobile.iOS.csproj" is building "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile/SophiaMobile.csproj" (GetNativeManifest target(s)):

Target GenerateBindingRedirects:
    No suggested binding redirects from ResolveAssemblyReferences.
Target _UnpackLibraryResources:
        Up to date: DefaultAvatar.ttf
        Up to date: inputlayout_togglecollapseicon.png
        Up to date: input_layout_drop_down_icon.png
        Up to date: inputlayout_togglevisibleicon.png
        Up to date: Avatar1.png
        Up to date: Avatar10.png
        Up to date: Avatar2.png
        Up to date: Avatar3.png
        Up to date: Avatar4.png
        Up to date: Avatar5.png
        Up to date: Avatar6.png
        Up to date: Avatar7.png
        Up to date: Avatar8.png
        Up to date: Avatar9.png
        Up to date: Avatar11.png
        Up to date: Avatar12.png
        Up to date: Avatar13.png
        Up to date: Avatar14.png
        Up to date: Avatar15.png
        Up to date: Avatar16.png
        Up to date: Avatar17.png
        Up to date: Avatar18.png
        Up to date: Avatar19.png
        Up to date: Avatar20.png
        Up to date: Avatar21.png
        Up to date: Avatar22.png
        Up to date: Avatar23.png
        Up to date: Avatar24.png
        Up to date: Avatar25.png
        Up to date: Avatar26.png
        Up to date: Avatar28.png
        Up to date: Avatar27.png
        Up to date: Avatar29.png
        Up to date: Avatar30.png
        Up to date: PDFViewer_iOS_Font
        Up to date: Font size Font
        Up to date: PdfViewer_Text_font
        Up to date: PdfViewer_FONT
        Up to date: Signature_PDFViewer_FONT
        Up to date: Font Page icons
        Up to date: V1 Font Material icon
        Up to date: Roboto-Bold
        Up to date: Roboto-Regular
        Up to date: Roboto-Medium
        Up to date: Font Print
        Up to date: Search.png
        Up to date: Annotation.png
        Up to date: Bookmark.png
        Up to date: More.png
        Up to date: Viewmode.png
        Up to date: Font Stepprogress icon.ttf
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target XamlG:
  Skipping target "XamlG" because it has no outputs.
Target CssG:
  Skipping target "CssG" because it has no outputs.
Target CssG:
  Skipping target "CssG" because it has no outputs.
Target XamlG:
  Skipping target "XamlG" because it has no outputs.
Target CoreCompile:
  Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
Target XamlC:
  Skipping target "XamlC" because all output files are up-to-date with respect to the input files.
Target _CopyFilesMarkedCopyLocal:
    Touching "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile.iOS/obj/iPhone/Release/SophiaMobile.iOS.csproj.CopyComplete".
Target GetCopyToOutputDirectoryItems:
    Target _GetCopyToOutputDirectoryItemsFromTransitiveProjectReferences:
        __________________________________________________
        Project "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile.iOS/SophiaMobile.iOS.csproj" is building "/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile/SophiaMobile.csproj" (GetCopyToOutputDirectoryItems target(s)):

Target _CopyOutOfDateSourceItemsToOutputDirectory:
  Skipping target "_CopyOutOfDateSourceItemsToOutputDirectory" because all output files are up-to-date with respect to the input files.
Target CopyFilesToOutputDirectory:
    SophiaMobile.iOS -> /Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile.iOS/bin/iPhone/Release/SophiaMobile.iOS.exe
Target _DetectSigningIdentity:
    Detected signing identity:
      Code Signing Key: "Apple Distribution: Ahmed Ameen (AX2DW2CCUD)" (AC39C738FFE01913204AA93C5D1E297ECF994E83)
      Provisioning Profile: "Sophia Book Profile" (f87361c5-efd9-4b7c-9dfe-06fbaee66d1d)
      Bundle Id: com.SophiaBookStore.SophiaBookStore
      App Id: AX2DW2CCUD.com.SophiaBookStore.SophiaBookStore
Target _CopyResourcesToBundle:
  Skipping target "_CopyResourcesToBundle" because all output files are up-to-date with respect to the input files.
Target _DetectDebugNetworkConfiguration:
      DebugIPAddresses: 
Target _CompileAppManifest:
  Skipping target "_CompileAppManifest" because all output files are up-to-date with respect to the input files.
Target _ParseExtraMtouchArgs:
      NoSymbolStrip Output: False
      NoDSymUtil Output: false
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch "@/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile.iOS/obj/iPhone/Release/response-file.rsp" "--gcc_flags=-ObjC -lc++ -lsqlite3 -lz -ObjC -lsqlite3 -ObjC -lz -lsqlite3" 
    Xamarin.iOS 13.16.0.13 (d16-5-xcode11.4): b75deaf82) using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
    MTOUCH : error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
    System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
      at System.IO.BinaryReader.FillBuffer (System.Int32 numBytes) [0x0007a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/binaryreader.cs:600 
      at System.IO.BinaryReader.ReadUInt32 () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/binaryreader.cs:191 
      at Xamarin.MachO.ReadFile (System.IO.BinaryReader reader, System.String filename) [0x00001] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/MachO.cs:187 
      at Xamarin.MachO.ReadFile (System.String filename) [0x00014] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/MachO.cs:216 
      at Xamarin.MachO.SelectArchitectures (System.String filename, System.Collections.Generic.ICollection`1[T] abis) [0x00039] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/MachO.cs:268 
      at Xamarin.Bundler.Application.BuildBundle () [0x00880] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:1795 
      at Xamarin.Bundler.Application.BuildAll () [0x0009c] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:852 
      at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x00433] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/mtouch.cs:1340 
      at Xamarin.Bundler.Driver.Main (System.String[] args) [0x00015] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/mtouch.cs:849 
Done building target "_CompileToNative" in project "SophiaMobile.iOS.csproj" -- FAILED.

Done building project "SophiaMobile.iOS.csproj" -- FAILED.

Build FAILED.

MTOUCH : error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:02:09.98

Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new

**Comment by chamons** [comment]
``` /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch "@/Users/ahmed/Desktop/Sophia Mobile Platform/Last Sophia/SophiaMobile/SophiaMobile.iOS/obj/iPhone/Release/response-file.rsp" "--gcc_flags=-ObjC -lc++ -lsqlite3 -lz -ObjC -lsqlite3 -ObjC -lz -lsqlite3"
Xamarin.iOS 13.16.0.13 (d16-5-xcode11.4): b75deaf) using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk
MTOUCH : error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
at System.IO.BinaryReader.FillBuffer (System.Int32 numBytes) [0x0007a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-10/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/binaryreader.cs:600```

It looks like we're trying to read some binary and hitting the end too soon, maybe a native library?

Please attach a sample application, so we can dig into this.

**Comment by c0d3l3ss** [comment]
this issue is sorted when i downgrade (xamarin.google.ios.ads) to version 7.47.0 from 7.57

**Comment by whitneyschmidt** [comment]
@c0d3l3ss I'm glad that you were able to resolve this. The underlying issue might still be in existence, if you provide a full sample showing the error we'll dig into it further.
