### ISSUE TITLE
Add Obsolete to ReleasedWhenClosed in NSWindow

### ISSUE THREAD

**Issue by chamons** [xamarin/xamarin-macios#8607]
See https://github.com/xamarin/xamarin-macios/issues/8606

This property is not safe, and will cause heartache.

**Comment by aconcagua21** [comment]
Adding 'Obsolete' flag to this property would not solve the issue described in #8606:

If you don't use storyboards nor nibs for creating windows, then closing the window with ReleasedWhenClosed=false causes not disposing managed NSWindow and not deallocating native NSWindow. Then sure the #8606 issue won't appear. But - it's not a solution, it's just a side-effect of another issue.

If you set ReleasedWhenClosed=true, then it depends on how you close the window:

1. The red semaphore button sends "close" message, then Cocoa sends retain and consequently dealloc. The Dispose method is called eventually from GC.Collect().
2. Close() method calls CFRetain() and then immediately calls Dispose(). Then (not immediately, however) Cocoa sends release, which in turn causes sending dealloc. Between Dispose and dealloc, Cocoa sends "isKeyWindow", and here is the problem: Dispose() had already been called. You can detect this situation by overriding Dispose(), but you can also have bad luck - if the GC collects garbage in the mean time.

Therefore, to really fix issues like #8606, you would have to change the Dispose/dealloc mechanism for NSWindow in some clever way.

**Comment by chamons** [comment]
Let's keep the discussion in https://github.com/xamarin/xamarin-macios/issues/8606 until we agree that ReleasedWhenClosed = true is valid in a managed context.

**Comment by rolfbjarne** [comment]
In #17105 I've obsoleted ReleasedWhenClosed, and added a DangerousReleasedWhenClosed (to match DangerousRetain, DangerousRelease, etc.) - and also fixed #8606.
