### ISSUE TITLE
SpatialOS compiling error in Xamarin Mac

### ISSUE THREAD

**Issue by DeuSens** [xamarin/xamarin-macios#8656]
[Program.cs.zip](https://github.com/xamarin/xamarin-macios/files/4666720/Program.cs.zip)

### Steps to Reproduce

1. Running the project (or building)
2. 
3. 

### Expected Behavior
The solution runs correctly and shows the login form
### Actual Behavior
The build crashes with the MM2101 error on the SpatialOS method
### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.6 (build 4520)
Installation UUID: fbf88839-c156-4742-aeed-a06bf59950f6
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000104

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.300/Sdks
SDK Versions:
	3.1.300
	3.1.202
	3.1.200
	3.0.100
	2.2.207
	2.1.701
	2.1.504
	2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.4
	3.1.2
	3.0.0
	2.2.8
	2.1.18
	2.1.16
	2.1.12
	2.1.8
	2.1.2

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.3.1.0 (Visual Studio Community)
Commit: xamarin-android/d16-6/3fe860a
Android SDK: Not found

=== Microsoft Mobile OpenJDK ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-04-30 04:01:22 UTC

=== Android Device Manager ===

Version: 16.6.0.95
Hash: 45d17b5
Branch: remotes/origin/d16-6
Build date: 2020-04-30 04:01:42 UTC

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Apple Developer Tools ===

Xcode 11.5 (16139)
Build 11E608c

=== Xamarin.Mac ===

Version: 6.18.1.31 (Visual Studio Community)
Hash: b3eedfed9
Branch: d16-6
Build date: 2020-04-09 10:22:36-0400

=== Xamarin.iOS ===

Version: 13.18.1.31 (Visual Studio Community)
Hash: b3eedfed9
Branch: d16-6
Build date: 2020-04-09 10:22:36-0400

=== Build Information ===

Release ID: 806004520
Git revision: 9c92c7baceef7771f8dcf5c86e1e1a66fdc26182
Build date: 2020-05-18 10:05:00-04
Build branch: release-8.6
Xamarin extensions: 9c92c7baceef7771f8dcf5c86e1e1a66fdc26182

=== Operating System ===

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

```

### Build Logs

Building InstaladorEventosOnline (Debug)
Build started 22/05/2020 9:29:59.
__________________________________________________
Project "/Users/DeuSens8/ProyectosUnity/InstaladorEventosOnline/InstaladorEventosOnline/InstaladorEventosOnline.csproj" (Build target(s)):

Target _BeforeCoreCompileImageAssets:
  Skipping target "_BeforeCoreCompileImageAssets" because all output files are up-to-date with respect to the input files.
Target _CoreCompileImageAssets:
  Skipping target "_CoreCompileImageAssets" because all output files are up-to-date with respect to the input files.
Target _CoreCompileInterfaceDefinitions:
      BundleResources Output:
        obj/Debug/ibtool/Main.storyboardc/MainMenu.nib
        obj/Debug/ibtool/Main.storyboardc/XfG-lQ-9wD-view-m2S-Jp-Qdl.nib
        obj/Debug/ibtool/Main.storyboardc/NSWindowController-B8D-0N-5wS.nib
        obj/Debug/ibtool/Main.storyboardc/Info.plist
      OutputManifests Output:
        obj/Debug/ibtool-manifests/Main.storyboardc
Target _CoreCompileColladaAssets:
  Skipping target "_CoreCompileColladaAssets" because it has no inputs.
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target CoreCompile:
  Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
Target _CopyFilesMarkedCopyLocal:
    Touching "/Users/DeuSens8/ProyectosUnity/InstaladorEventosOnline/InstaladorEventosOnline/obj/Debug/InstaladorEventosOnline.csproj.CopyComplete".
Target _CopyAppConfigFile:
  Skipping target "_CopyAppConfigFile" because all output files are up-to-date with respect to the input files.
Target CopyFilesToOutputDirectory:
    InstaladorEventosOnline -> /Users/DeuSens8/ProyectosUnity/InstaladorEventosOnline/InstaladorEventosOnline/bin/Debug/InstaladorEventosOnline.exe
Target _DetectSigningIdentity:
    Detected signing identity:
      Bundle Id: com.deusens.InstaladorEventosOnline
      App Id: com.deusens.InstaladorEventosOnline
Target _CopyContentToBundle:
  Skipping target "_CopyContentToBundle" because all output files are up-to-date with respect to the input files.
Target _CompileAppManifest:
  Skipping target "_CompileAppManifest" because all output files are up-to-date with respect to the input files.
Target _CompileToNative:
    /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp @/Users/DeuSens8/ProyectosUnity/InstaladorEventosOnline/InstaladorEventosOnline/obj/Debug/response-file.rsp  -q
    -q
    -q
    -q
     
    MMP : error MM2101: Can't resolve the reference 'System.Void Grpc.Core.ClientBase`1<Improbable.SpatialOS.Deployment.V1Beta1.DeploymentService/DeploymentServiceClient>::.ctor(Grpc.Core.Channel)', referenced from the method 'System.Void Improbable.SpatialOS.Deployment.V1Beta1.DeploymentService/DeploymentServiceClient::.ctor(Grpc.Core.Channel)' in 'Grpc.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad'.
Done building target "_CompileToNative" in project "InstaladorEventosOnline.csproj" -- FAILED.

Done building project "InstaladorEventosOnline.csproj" -- FAILED.

Build FAILED.

MMP : error MM2101: Can't resolve the reference 'System.Void Grpc.Core.ClientBase`1<Improbable.SpatialOS.Deployment.V1Beta1.DeploymentService/DeploymentServiceClient>::.ctor(Grpc.Core.Channel)', referenced from the method 'System.Void Improbable.SpatialOS.Deployment.V1Beta1.DeploymentService/DeploymentServiceClient::.ctor(Grpc.Core.Channel)' in 'Grpc.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad'.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:06.80

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 0 warnings

### Example Project (If Possible)

using AppKit;
using Google.Protobuf.WellKnownTypes;
using Improbable.SpatialOS.Deployment.V1Beta1;
using Improbable.SpatialOS.Platform.Common;
using Improbable.SpatialOS.PlayerAuth.V2Alpha1;
using System;
using System.ComponentModel;
using System.Drawing;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
//using System.Windows.Forms;

//namespace Windows
//{
    class Program
    {
        /// <summary>
        ///     PLEASE REPLACE.
        ///     Your SpatialOS project name.
        ///     It should be the same as the name specified in the local project definition file (spatialos.json) used to start the local API service.
        /// </summary>
        private const string ProjectName = "beta_triple_nineteen_940";

        /// <summary>
        ///     PLEASE REPLACE.
        ///     The path to a valid launch configuration JSON file.
        /// </summary>
        private const string LaunchConfigFilePath = "../blank_project/default_launch.json";

        /// <summary>
        ///     PLEASE REPLACE.
        ///     The assembly you want the cloud deployment to use.
        /// </summary>
        private const string AssemblyId = "blank_deployment";

        private const string LocatorServerAddress = "locator.improbable.io";
        private const int LocatorServerPort = 443;
        private const string ScenarioDeploymentTag = "bring_your_own_auth";
        private const string ScenarioWorkerType = "UnityClient";
        private const string Command = ".\\app/UnityClient@Windows.exe";
        private const string zipUrl = "https://eventosonline.s3.eu-west-3.amazonaws.com/UnityClient%40Windows.zip";
        private static string args;
        //private static FormDeusSens form;
        private static int percentege;

        private static string RefreshToken;
        //private static string RefreshToken =>
        //    Environment.GetEnvironmentVariable("IMPROBABLE_REFRESH_TOKEN") ?? "4/NDQ0NTIzODkyODU1OrsCoPlzQX2B0bOW1Fs+HXK/zOc7LNkV0NVihSfDmz53";

        static void Main(string[] args)
        {
            NSApplication.Init();
            NSApplication.Main(args);
        }

        public static void Start(Response response)
        {
            RefreshToken = response.objeto.token;
            RunService(response.objeto);
        }

        private static string RunService(ResponseBody body)
        {
            try
            {
                PlatformRefreshTokenCredential credentialWithProvidedToken =
                    new PlatformRefreshTokenCredential(RefreshToken);

            // ---------- Este mtoeodo es el que falla 1 ----------------------------
            DeploymentServiceClient deploymentServiceClient =
               DeploymentServiceClient.Create(credentials: credentialWithProvidedToken);

            // ---------- Este mtoeodo es el que falla 2 ----------------------------
            PlayerAuthServiceClient playerAuthServiceClient =
                    PlayerAuthServiceClient.Create(credentials: credentialWithProvidedToken);

            // Console.WriteLine("Creating a PlayerIdentityToken");
            var playerIdentityTokenResponse = playerAuthServiceClient.CreatePlayerIdentityToken(
                    new CreatePlayerIdentityTokenRequest
                    {
                        Provider = "provider",
                        PlayerIdentifier = "player_identifier",
                        ProjectName = ProjectName
                    });

                //Console.WriteLine("Verifying PlayerIdentityToken");
                var decodePlayerIdentityTokenResponse = playerAuthServiceClient.DecodePlayerIdentityToken(
                    new DecodePlayerIdentityTokenRequest
                    {
                        PlayerIdentityToken = playerIdentityTokenResponse.PlayerIdentityToken
                    });
                var playerIdentityToken = decodePlayerIdentityTokenResponse.PlayerIdentityToken;
                if (playerIdentityToken.Provider != "provider") throw new Exception("Provider not recognised.");
                if (playerIdentityToken.ProjectName != ProjectName) throw new Exception("Project not recognised.");
                if (DateTime.Now.CompareTo(playerIdentityToken.ExpiryTime.ToDateTime()) > 0)
                    throw new Exception("PlayerIdentityToken expired.");

                //Console.WriteLine("Choosing a deployment");
                var listDeploymentsRequest = new ListDeploymentsRequest
                {
                    ProjectName = ProjectName,
                    Filters =
                    {
                        new Filter
                        {
                            TagsPropertyFilter = new TagsPropertyFilter
                            {
                                Tag = "player_auth_tag",
                                Operator = TagsPropertyFilter.Types.Operator.Equal,
                            },
                        }
                    }
                };
                var suitableDeployment = deploymentServiceClient.ListDeployments(listDeploymentsRequest).First();

                //Console.WriteLine("Creating a LoginToken for the selected deployment");
                var createLoginTokenResponse = playerAuthServiceClient.CreateLoginToken(
                    new CreateLoginTokenRequest
                    {
                        PlayerIdentityToken = playerIdentityTokenResponse.PlayerIdentityToken,
                        DeploymentId = suitableDeployment.Id.ToString(),
                        //DeploymentId = "Wannabe",
                        LifetimeDuration = Duration.FromTimeSpan(new TimeSpan(0, 0, 30, 0)),
                        WorkerType = ScenarioWorkerType
                    });

                string token = createLoginTokenResponse.LoginToken;
                string tokenIdentity = playerIdentityTokenResponse.PlayerIdentityToken;

                args =
                    " -appName beta_triple_nineteen_940 -projectName beta_triple_nineteen_940 -deploymentName blank_deployment -loginToken " +
                    token +
                    " -locatorHost locator.improbable.io -infraServicesUrl https://api.spatial.improbable.io -playerIdentityToken " +
                    tokenIdentity + "  -assetDatabaseStrategy Streaming'";

                if (CheckVersion(body.version))
                {
                    System.Diagnostics.Process.Start(Command, args);
                    Environment.Exit(0);
                }
                else
                {
                    DownloadZip(body.version);
                }

                return Command + args;
            }
            catch (Exception e)
            {
                //MessageBox.Show(e.Message);
                return e.Message;
            }
        }

        private static void DownloadZip(string version)
        {
            WebClient client = new WebClient();

            client.DownloadFileCompleted += (object sender, AsyncCompletedEventArgs asyncCompletedEventArgs) =>
            {
                client_DownloadDataCompleted(version);
            };
            client.DownloadProgressChanged += (sender, eventArgs) =>
            {
                percentege = eventArgs.ProgressPercentage;
                //form.progressBar1.Value = percentege;
            };

            client.DownloadFileAsync(new Uri(zipUrl), "./app.zip");

            //form.progressBar1.Visible = true;
            //form.label3.Visible = true;
            //form.label3.ForeColor = Color.White;
            //form.label3.Text = "Descargando";
        }

        private static async void client_DownloadDataCompleted(string version)
        {
            //form.label3.Text = "Extrayendo";
            Directory.CreateDirectory("./app");
            Directory.Delete("./app", true);
            Task extractTask = Task.Run(() => ZipFile.ExtractToDirectory("./app.zip", "./app"));
            await extractTask.ContinueWith(antecedent =>
            {
                File.WriteAllText("./app/version.json", version);
                System.Diagnostics.Process.Start(Command, args);
                Environment.Exit(0);
            });
    }

        private static bool CheckVersion(string version)
        {
            if (Directory.Exists("./app"))
            {
                if (File.Exists("./app/version.json"))
                {
                    string storedVersion = File.ReadAllText("./app/version.json");
                    if (storedVersion.Equals(version))
                        return true;

                    return false;
                }
            }
            else
            {
                Directory.CreateDirectory("./app");
            }
            return false;
        }
    //}
}

**Comment by spouliot** [comment]
The attachment is not complete enough to reproduce your issue. Please attach a self-contained project that we can build and get the same error that you described. Thanks!

**Comment by whitneyschmidt** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
