### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by tranb3r** [xamarin/xamarin-macios#8661]
I cannot find the release notes for xamarin.ios 13.18 and 13.20.
Could you please publish them ?

**Comment by whitneyschmidt** [comment]
@tranb3r Thank you for your feedback! We are actively working on release notes for 13.18 and 13.20 and will update you here once they are available :)

**Comment by tranb3r** [comment]
@whitneyschmidt Any progress ??

**Comment by whitneyschmidt** [comment]
@tranb3r Thanks for checking in!

Xamarin.iOS release notes from 13.18 can be found here: https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.18

Xamarin.Mac 6.18: https://docs.microsoft.com/en-us/xamarin/mac/release-notes/6/6.18

13.20 and 6.20 notes are in progress.

**Comment by tranb3r** [comment]
@whitneyschmidt The version for xamarin.ios in the last release of VS 2019 (16.6.1) is 13.18.2.1. The link you've provided for 13.18 only mentions 13.18.1.31. What's new in 13.18.2.1 ?

**Comment by whitneyschmidt** [comment]
@tranb3r There aren't many changes between 13.18.1.31 and 13.18.2.1. The biggest one is that Xamarin.iOS and Xamarin.Mac are now compatible with Xcode 11.5.

I'll post here again when the release notes are officially available.

**Comment by whitneyschmidt** [comment]
@tranb3r Apologies for the delays, release notes are now published and up for viewing through 13.20 and 6.20:
[iOS](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.20)

[Mac](https://docs.microsoft.com/en-us/xamarin/mac/release-notes/6/6.20)

**Comment by tranb3r** [comment]
@whitneyschmidt 
13.20.1.44 has been released. What's new compared to 13.20.1.18 ?

**Comment by tranb3r** [comment]
@whitneyschmidt 
Come on guys. 13.20.2.2 is out. Could you please update the release notes?

**Comment by whitneyschmidt** [comment]
@tranb3r Thanks for your patience and reminders. No excuses for 13.20.1.44 - we dropped a set of notes.

Release notes for d16-7 are in progress will be coming within the next couple of days. When they are public I'll post here, and you'll also be able to find them in the usual place.

**Comment by whitneyschmidt** [comment]
https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.20
https://docs.microsoft.com/en-us/xamarin/mac/release-notes/6/6.20

**Comment by tranb3r** [comment]
@whitneyschmidt 
Hi again. What's in 13.22.1.3 and 13.22.1.8 ?
Could you please make sure those release notes are published immediately when a new version of visual studio 2019 (preview or release) is available ?

**Comment by whitneyschmidt** [comment]
@tranb3r That's a great question. Unfortunately we're behind, but we are aware that these need to be written up and we're actively working on it.

**Comment by chamons** [comment]
Hey @tranb3r - manager of the macios team here. 

We've reworking our processes to make release notes align better, but we're not there yet.

In particular we know that our d16-8 (preview) release notes are out of sync again.

As you can imagine our tracking of Xcode 12 has us quite busy this summer, and we dropped this ball here.

**Comment by tranb3r** [comment]
@chamons 
One more release of visual studio preview and still no release notes for xamarin.ios (13.22.1.3, 13.22.1.8, 13.22.1.23)

**Comment by tranb3r** [comment]
Xcode 12 has been released. 
But it's not even clear whether 11.7 is supported or not in X.iOS 13.22.*.
This is such a mess...

**Comment by chamons** [comment]
Thanks for the feedback.

After the recent surprises Apple dropped on us, the teams has been scrambling to catch up.

Delaying the release notes (d16-8 and xcode12) was the impact.

**Comment by tranb3r** [comment]
No release notes for 14.9.0.27.
cc @whitneyschmidt @chamons

**Comment by chamons** [comment]
Please consider opening a new issue, this one is months old.

cc @dalexsoto

**Comment by tranb3r** [comment]
I'd rather re-open this issue since obviously your release process is missing the "publish release notes" step...
