### ISSUE TITLE
http://xamarin.com/mobile-licensing in NOTICE file in app package, might be dead link

### ISSUE THREAD

**Issue by takeshik** [xamarin/xamarin-macios#8732]
All app packages that is powered with Xamarin contains `NOTICE` file:

https://github.com/xamarin/xamarin-macios/blob/392200d93068883754bf6710b4e0dcd16feb108a/tools/mtouch/Application.mtouch.cs#L1306-L1308

However, http://xamarin.com/mobile-licensing in this NOTICE file, seems to be a dead link; this URL is redirected to https://dotnet.microsoft.com/apps/xamarin .
(http://xamarin.com/xxxxxx is redirected similarly.)

According to Internet Archive, [there was a license notice page, until at least 2015](https://web.archive.org/web/20150905190726/http://xamarin.com/mobile-licensing).

I think this link should be indicated license information even now.

**Comment by chamons** [comment]
Thanks for the report. I can confirm this. Looking into it now.

**Comment by chamons** [comment]
I'm still working on fixing the redirect, but the new location of this information is https://github.com/xamarin/xamarin-macios/issues/8849

That issue links to the iOS, macOS, and Android specific notices.

**Comment by duncanmak** [comment]
@chamons Can we close this issue now?

**Comment by chamons** [comment]
Yes @duncanmak - I was waiting on both redirects to be live, and they are.

We've completed redirecting URLs to the new location. Please reopen if you have other licensing concerns.

Thanks for noticing this and opening a report!
