### ISSUE TITLE
Error MT2101: Can't resolve the reference 'System.Security.Cryptography.DSACng'

### ISSUE THREAD

**Issue by BlueFire-LLC** [xamarin/xamarin-macios#8772]
**Bug:**

Build throws the following error:
Error MT2101: Can't resolve the reference 'System.Security.Cryptography.DSACng', referenced from the method 'Org.BouncyCastle.Crypto.AsymmetricKeyParameter MimeKit.Cryptography.AsymmetricAlgorithmExtensions::GetAsymmetricKeyParameter(System.Security.Cryptography.DSACng)' in 'System.Security.Cryptography.Cng, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. (MT2101) (Motorhomes.iOS)

**Platform:**
 - OS: MacOS
 - Visual Studio 2019 latest version
 - iOS Project
 - Xamarin.IOS latest version
 - MimeKit Version: 2.8

**Reference:**
 - https://github.com/jstedfast/MailKit/issues/1035

**Comment by jstedfast** [comment]
Just a bit of history here that *may* be useful.

MimeKit used to (up through 2.7) have Xamarin-specific build targets, but I dropped those in 2.8 because Xamarin.iOS/Android have supported netstandard2.0 for so long at this point, it didn't seem worth continuing to provide Xamarin-specific dll's in the nuget packages.

What *also* happened in MimeKit 2.8 was the addition of support for RSACng and DSACng keys in X509Certificates (MimeKit has to "convert" between System.Security X509Certificate2's and BouncyCastle X509Certificates and also the private keys because MimeKit uses BouncyCastle for most of the S/MIME crypto).

**Comment by jstedfast** [comment]
Something I just noticed is `'System.Security.Cryptography.Cng, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

It *should* be loading System.Security.Cryptography.Cng 4.4.0.0

Why is it trying to load 4.3.0.0?

MimeKit's nuget package has a dependency on 4.4.0 (`<dependency id="System.Security.Cryptography.Cng" version="4.4.0" />`) and MimeKit.NetStandard.csproj has a `<PackageReference Include="System.Security.Cryptography.Cng" Version="4.4.0" />`

**Comment by jstedfast** [comment]
@BlueFire-LLC My guess is that if you add an explicit dependency on System.Security.Cryptography.Cng 4.4.0 to your project, it will build.

**Comment by spouliot** [comment]
Unlike `DSACryptoServiceProvider` [1] the newer `DSACng` [2] is not part of `netstandard2.0`.

It _might_ be possible to have an additional nuget package to satisfy the requirement. I'll leave you discuss this possibility together.

However, as this stands now, the package is not compatible, by itself, with the mobile profile used for Xamarin SDK. Assemblies must either be build against the SDK assemblies or with a supported version of `NETStandard`.

[1] https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.dsacryptoserviceprovider
[2] https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.dsacng

**Comment by jstedfast** [comment]
Weird, in some docs (on MSDN somewhere) I came across when I implemented this, it suggested RSACng was supported by netstandard2.0 via System.Security.Cryptograsphy.Cng >= 4.3.0 and DSACng was supported in netstandard2.0 via System.Security.Cryptography.Cng >= 4.4.0

Also, obviously, MimeKit itself builds successfully for the netstandard2.0 target.

**Comment by spouliot** [comment]
It's not *in* `netstandard2.0` but it's possible some nuget can add support for them.
However it does not mean those extraneous nuget are available (or working) for iOS, Mac ... YMMV

**Comment by jstedfast** [comment]
Ah, gotcha.

**Comment by jstedfast** [comment]
@spouliot does that go for RSACng as well? Just trying to figure out if I need to do something about RSACng support as well or if it's limited to DSACng.

**Comment by spouliot** [comment]
@jstedfast on our side yes, but I have no clue about the extra nugets which could, in theory, have a workable subset

**Comment by BlueFire-LLC** [comment]
@jstedfast - I did try System.Security.Cryptography.Cng 4.7 with no luck. FYI, MailKit 2.7 works on all other platforms (Android, UWP, and MacOS). It's just iOS that it fails.

**Comment by chekm8** [comment]
> It's not _in_ `netstandard2.0` but it's possible some nuget can add support for them.
> However it does not mean those extraneous nuget are available (or working) for iOS, Mac ... YMMV

@spouliot Are there plans to have support for RsaCng in  .netstandard?

**Comment by spouliot** [comment]
@BlueFire-LLC most platform are JIT only and will complain at runtime if a type is missing. iOS (tvOS and watchOS too) requires Full AOT which makes such errors appears at build time.

@chekm8 there's no plan for any newer version of netstandard (than the existing 2.1) as we're converging everything into `net5` (or `net6`) and so on. However the type is part of .netcore 3 (and 5) so it should be _present_ in the future versions of Xamarin.iOS (planned for .net6).

Note that CNG is something very Windows specific I do not know if it will work at runtime. Nor do I know if MailKit needs the type at runtime (or just at build time).

**Comment by ndastur** [comment]
Any news on this ?

**Comment by BlueFire-LLC** [comment]
I'm still using MailKit 2.6.0. I keep trying the latest version every time there is an update but with no success.

**Comment by BlueFire-LLC** [comment]
See this thread - https://github.com/xamarin/xamarin-macios/issues/10802#issuecomment-811899388
