### ISSUE TITLE
NSPasteboardTests_WriteObjectTests fails with a NRE

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#8787]
The test does not always fail and does not do it in all the OS versions. Looking at the code of the test, the nspastebin is not released, leading to a leak, which might be the root cause of the issue. The issue started to occur after: https://github.com/xamarin/xamarin-macios/commit/5d2598af695c41c32712cd136d02c0e8cdfcac5e

**Comment by spouliot** [comment]
That would not be a classic _memory_ leak since it survive app restart.

>  Because the lifetime of a unique pasteboard is not related to the lifetime of the creating app, you must release a unique pasteboard by calling releaseGlobally to avoid possible leaks.

https://developer.apple.com/documentation/appkit/nspasteboard/1528936-pasteboardwithuniquename?language=objc

Not clear if a reboot can solve the `null` being returned on bots...

**Comment by rolfbjarne** [comment]
I think we should try to reboot the affected bots, they've been up 450+ days.
