### ISSUE TITLE
"Preserve vector data" option in Assets

### ISSUE THREAD

**Issue by ivanicin** [xamarin/xamarin-macios#8789]
### Steps to Reproduce

Open Assets and select an item with imported pdf file.

### Expected Behavior
There should be an option "Preserve vector data" like in XCode.

### Actual Behavior
There is no such an option in Visual Studio (both for Windows and Mac)
### Environment

```
Microsoft Visual Studio Community 2019
Version 16.6.1
VisualStudio.16.Release/16.6.1+30128.74
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA588
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.6.936.3669
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.936.3669
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.936.3669
Azure App Service Tools v3.0.0

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (master@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

Multilingual App Toolkit   4.0
Multilingual App Toolkit helps you localize your Windows Store app by providing file management, pseudo and machine translation, translation editor, and build integration. http://aka.ms/matinstall

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62004.28040
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.6.000.1061 (d16-6@8e68aa8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3


Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Example Project (If Possible)

> VS bug [#1136980](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1136980), VS bug [#1138468](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1138468), VS bug [#1138469](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1138469), VS bug [#1138767](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1138767), VS bug [#1151802](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1151802), VS bug [#1151910](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1151910), VS bug [#1152435](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1152435), VS bug [#1152476](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1152476), VS bug [#1152689](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1152689), VS bug [#1153348](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1153348), VS bug [#1153855](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1153855), VS bug [#1154530](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1154530), VS bug [#1155028](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1155028), VS bug [#1155095](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1155095), VS bug [#1155239](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1155239), VS bug [#1155858](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1155858), VS bug [#1156446](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1156446), VS bug [#1157096](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1157096)

**Comment by whitneyschmidt** [comment]
@ivanicin Thank you for your feedback!

Was this feature previously available in VS Windows or VS Mac? If so, what was the last time it was working?

We look forward to hearing back from you :)

**Comment by ivanicin** [comment]
@whitneyschmidt I have searching for it now, so I am not sure if this existed before but the answer is likely not. Just some my pdf files don't appear smooth on the screen and I guess it is because this option is missing.

**Comment by whitneyschmidt** [comment]
@ivanicin I'll ask around and see whether there's more info on supporting vector files.

Could you attach the file you're trying to add or a similar example that produces the same behavior?

**Comment by ivanicin** [comment]
@whitneyschmidt there is the support for vector files as that you can import pdf file. However since some not so recent version XCode also includes this option "Preserve vector data" which is crucial for the quality results and seems to be missing from Xamarin's tools.

**Comment by whitneyschmidt** [comment]
There's some info on using pdf formatted vector images here: [Mac](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/displaying-an-image?tabs=macos#using-vector-images-in-asset-catalogs), [Windows](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/displaying-an-image?tabs=windows#using-vector-images-in-asset-catalogs)

From the docs:

As of iOS 8, special Vector class has been added to Image Sets that allows the developer to include a PDF formatted vector image in the cassette instead including individual bitmap files at the different resolutions. Using this method, supply a single vector file for the @1x resolution (formatted as a vector PDF file) and the @2x and @3x versions of the file will be generated at compile time and included in the application's bundle.

**Comment by whitneyschmidt** [comment]
+ @victorgarciaaprea @emaf

**Comment by emaf** [comment]
Hi all, that option is not available in any of the IDEs, as a workaround you can edit your asset's Contents.json file to enable it.

**Comment by ivanicin** [comment]
> 
> 
> There's some info on using pdf formatted vector images here: [Mac](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/displaying-an-image?tabs=macos#using-vector-images-in-asset-catalogs), [Windows](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/displaying-an-image?tabs=windows#using-vector-images-in-asset-catalogs)
> 
> From the docs:
> 
> As of iOS 8, special Vector class has been added to Image Sets that allows the developer to include a PDF formatted vector image in the cassette instead including individual bitmap files at the different resolutions. Using this method, supply a single vector file for the @1x resolution (formatted as a vector PDF file) and the @2x and @3x versions of the file will be generated at compile time and included in the application's bundle.

I understand, but that is what native tools offered many years ago, I would expect some more up to date support, that is what this issue is about.

**Comment by whitneyschmidt** [comment]
@ivanicin Thank you for your feedback - the support does appear to be out of date. We've marked this as a bug.

However, this does not necessarily mean we will take actions on it as we still need to discuss its feasibility internally and make sure it is not conflicting with other features.

cc @emaf

**Comment by mrward** [comment]
This bug seems to be generating multiple duplicate bugs in the Azure DevOps/VSTS. I marked some as duplicates and now that has closed this bug and I do not have permission to re-open it.

**Comment by ivanicin** [comment]
> 
> 
> @ivanicin Thank you for your feedback - the support does appear to be out of date. We've marked this as a bug.
> 
> However, this does not necessarily mean we will take actions on it as we still need to discuss its feasibility internally and make sure it is not conflicting with other features.
> 

It appears that manual editing of content.json files delivers proper results as suggested by @emaf . Also this means that required work to make this reality is minimal, I guess it is maximum 1 work day for one Visual Studio platform, so hopefully it will make sense to schedule this work - low effort high impact.
