### ISSUE TITLE
No watchOS debugging on Series 4+ devices

### ISSUE THREAD

**Issue by onurhazar** [xamarin/xamarin-macios#8810]
Hello,
Unfortunately, we are unable to debug on physical apple watch devices. Getting different errors no matter we do in build properties. The app ids and profiles are all correct since we were able to debug before this problem raised. We can't reproduce every case by debugging on a simulator. Debugging is crucial for us to solve bugs on time and give stable releases. This issue occurs since almost a year so please fix asap. Any help or guidance would be appreciated. Thanks for support!

We followed the steps through the documentation link below;
https://docs.microsoft.com/en-us/xamarin/ios/watchos/deploy-test/device

Here is the build log;
[BuildLog.txt](https://github.com/xamarin/xamarin-macios/files/4750668/BuildLog.txt)

Here is the app output when debugger tries to start;

`Please connect the device 'Onur???s Apple??Watch'...
Launched watch application 'com.x.x.watchkitapp' on 'Onur???s Apple??Watch' with pid 211
Xamarin.WatchOS: Found debug mode http in environment variables
Xamarin.WatchOS: Found port 57374 in environment variables
Xamarin.WatchOS: Added IP to look for the IDE: ::ffff:192.168.1.26
Xamarin.WatchOS: IDE Port: 57374 Transport: HTTP
2020-06-09 10:42:36.956671+0300 WatchOSExtension[211:10594] Xamarin.WatchOS: Connecting to 1 IPs.
2020-06-09 10:42:37.649735+0300 WatchOSExtension[211:10592] Xamarin.WatchOS: Connection to the debugger failed (id: 1 didCompleteWithError: Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <A56272C7-2DC5-4D6E-898D-5987CF1B77CF>.<1>, NSLocalizedDescription=Could not connect to the server., _kCFStreamErrorCodeKey=61, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <A56272C7-2DC5-4D6E-898D-5987CF1B77CF>.<1>"
), NSErrorFailingURLStringKey=http://localhost::ffff:192.168.1.26:57374/download?pid=211&id=1&uniqueRequest=1, _kCFStreamErrorDomainKey=1, NSErrorFailingURLKey=http://localhost::ffff:192.168.1.26:57374/download?pid=211&id=1&uniqueRequest=1} task: <__NSCFLocalDataTask: 0x17261000>{ taskIdentifier: 1 } { completed } url: http://::ffff:192.168.1.26:57374/download?pid=211&id=1&uniqueRequest=1)
Xamarin.WatchOS: Waiting for connection to the IDE...
Xamarin.WatchOS: Waiting for connection to the IDE...
Xamarin.WatchOS: Waiting for connection to the IDE...
Xamarin.WatchOS: Waiting for connection to the IDE...
error HE0038: Failed to launch the app 'com.x.x.watchkitapp' on the device 'Onur???s Apple??Watch': The operation couldn???t be completed. (FBSOpenApplicationErrorDomain error 1.)`

Screenshots of the ios project properties;
![iOS1](https://user-images.githubusercontent.com/5585009/84121703-2a263f80-aa40-11ea-8ec7-0cd75c62ab9a.png)
![iOS2](https://user-images.githubusercontent.com/5585009/84121710-2c889980-aa40-11ea-90af-16e4fa4672d8.png)
![iOS3](https://user-images.githubusercontent.com/5585009/84121715-2eeaf380-aa40-11ea-8d83-7cf979f175b7.png)

Screenshots of the watch ext project properties;
![watch1](https://user-images.githubusercontent.com/5585009/84121772-3e6a3c80-aa40-11ea-9b6d-818340302db3.png)
![watch2](https://user-images.githubusercontent.com/5585009/84121786-42965a00-aa40-11ea-8302-26d3375522d8.png)
![watch3](https://user-images.githubusercontent.com/5585009/84121801-44601d80-aa40-11ea-81ff-cf0dad886ad3.png)

**Comment by t9mike** [comment]
I thought 64-bit was not supported at all for debug? Did this change? I just created HelloWorld via master branch Xamarin.iOS and got "Application could not be uploaded to the device" when I tried Debug launch against watchOS 7 44mm watch.

**Comment by chamons** [comment]
@t9mike Please create a new issue for that, along with full build logs / project.

**Comment by t9mike** [comment]
@chamons I decided yesterday to abandon the Apple Watch version of my app. Apple Watch with Xamarin has too many obstacles and papercuts, large and small. It is complicated I know and I am amazed my watch app worked as well as it did. But I am throwing in the towel. https://www.youtube.com/watch?v=W6kTcRkQZhs&feature=youtu.be&t=68

**Comment by ThumbGen** [comment]
> @chamons I decided yesterday to abandon the Apple Watch version of my app. Apple Watch with Xamarin has too many obstacles and papercuts, large and small. It is complicated I know and I am amazed my watch app worked as well as it did. But I am throwing in the towel.

Same goes for me... after waiting an eternity for the HttpClient crash to reach 'stable' mono ( #8232 )  few days ago I updated to some mono version, the Apple Watch app started to work, then today I've updated to latest 'stable' mono and it crashes again right after startup. It is NOT possible to build quality Apple Watch apps using Xamarin; I will inform our management and hopefully discontinue the app. It becomes way too expensive to develop/maintain it.

**Comment by chucker** [comment]
@t9mike FWIW, I fixed that by editing my WatchOSExtension project to change `MtouchArch` to `ARMv7k,ARM64_32` (_only_ on the non-simulator configs, i.e. on Debug|iPhone and Release|iPhone). Deploying to device now works; debugging, however, does not (see #9767, apparently).

**Comment by jigneshbodarya** [comment]
Are debugging **Debug|iPhone** works with physical watchOS and iPhone?

**Comment by jigneshbodarya** [comment]
@t9mike  Are you know that physical watch debugging working well with latest Xcode 12.5?

**Comment by SprengerS** [comment]
@jigneshbodarya How do you did this. I have installed Xcode 13 and my Apple Watch Serie 7 will be find via wifi. I can deploy on my Watch and the WatchApp will be started. But the Debugger is always waiting for Connection. So I cannot really debug on the Watch App

**Comment by rolfbjarne** [comment]
Closing, since watchOS isn't supported in .NET, and Xamarin is not supported anymore.
