### ISSUE TITLE
Xamarin.iOS.Common.targets Fails Linking

### ISSUE THREAD

**Issue by alaskanrogue** [xamarin/xamarin-macios#8840]
Using the latest libraries, I have begun encountering the following errors regarding Xamarin.iOS.Common.targets:

- Native linking failed, undefined Objective-C class: SBRegistration. The symbol '_OBJC_CLASS_$_SBRegistration' could not be found in any of the libraries or frameworks linked with your application.
Native linking failed, undefined Objective-C class: SBRegistration. The symbol '_OBJC_CLASS_$_SBRegistration' could not be found in any of the libraries or frameworks linked with your application.
Native linking failed, undefined Objective-C class: SBTokenProvider. The symbol '_OBJC_CLASS_$_SBTokenProvider' could not be found in any of the libraries or frameworks linked with your application.
Native linking failed, undefined Objective-C class: StoredRegistrationEntry. The symbol '_OBJC_CLASS_$_StoredRegistrationEntry' could not be found in any of the libraries or frameworks linked with your application.
Native linking failed, undefined Objective-C class: SBLocalStorage. The symbol '_OBJC_CLASS_$_SBLocalStorage' could not be found in any of the libraries or frameworks linked with your application.
Native linking failed, undefined Objective-C class: SBConnectionString. The symbol '_OBJC_CLASS_$_SBConnectionString' could not be found in any of the libraries or frameworks linked with your application.
[BuildOutput.txt](https://github.com/xamarin/bugzilla-archives/files/4764396/BuildOutput.txt)

### Steps to Reproduce

1. Select iOS project and build
2. 
3. 

### Expected Behavior

Successful build

### Actual Behavior

Component Linker Errors

### Environment

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.7.0 Preview 2.0
VisualStudio.16.Preview/16.7.0-pre.2.0+30128.36
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00435-60000-00000-AA455
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2019   00435-60000-00000-AA455
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.7.276.48084
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2027706+d321ccdb871e2035eade5f4be27354e84f99313d
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.276.48084
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.276.48084
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.7.276.48084
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.6000.1
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.7.0-2.20270.4+205504dfd0f686370cffae5df068024c8a2b427f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.6000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.6000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30415.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.2 (c19c9c3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Project System Tools   1.0
Tools for working with C#, VisualBasic, and F# projects.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62005.01040
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20528.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-2.20270.4+205504dfd0f686370cffae5df068024c8a2b427f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20230.7+082844d9aaa5d2893680b05a1fe0b77ee18719dd
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.200 (master@c631c2f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.340 (remotes/origin/d16-7@f61b59c2e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.61 (87c64b8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.99.259 (d16-7/feabf52)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 075c3f0
    Java.Interop: xamarin/java.interop/d16-7@d6024f1
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@23c4fe0

Xamarin.iOS and Xamarin.Mac SDK   13.20.0.22 (c2a220d84)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

2. Paste into the code block below (between ```)
-->

```
```

### Build Logs

[BuildOutput.txt](https://github.com/xamarin/xamarin-macios/files/4764486/BuildOutput.txt)

**Comment by whitneyschmidt** [comment]
@alaskanrogue Thank you for filing this issue!

Would it be possible to share a small sample that reproduces the error? That's the best way for us to begin investigating.

**Comment by whitneyschmidt** [comment]
@alaskanrogue Thank you for

**Comment by alaskanrogue** [comment]
Test project attached.
[iosTest.zip](https://github.com/xamarin/xamarin-macios/files/4773546/iosTest.zip)

**Comment by chamons** [comment]
The library in question appears to be AppCenterPush.a, which is a nuget that you are referencing:

 $ monodis --presources ~/.nuget/packages/microsoft.appcenter.push/3.2.1/lib/Xamarin.iOS10/Microsoft.AppCenter.Push.iOS.Bindings.dll 
       0: AppCenterPush.a (size 2066360)

$ nm "/Users/donblas/Downloads/iosTest/iosTest/iosTest.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone 11-13.5/mtouch-cache/AppCenterPush.a" | grep MSAbstractLog
                 U _OBJC_CLASS_$_MSAbstractLog
                 U _OBJC_METACLASS_$_MSAbstractLog

I would suggest starting with the documentation to confirm you have the project configured correctly: https://docs.microsoft.com/en-us/appcenter/push/

However given this news: https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/

It may change your plans as well. In any case, this is not a Xamarin.IOS bug.
