### ISSUE TITLE
[Question] How can I use self signed certificates on iOS to load images over https?

### ISSUE THREAD

**Issue by nschoenberg** [xamarin/xamarin-macios#8841]
I don't know where I could ask this question so I hope some people here can maybe help me.

I currently have a SSL issue with a root domain certificate my company created them self to use it on an internal web server that serves content over https protocol. So, its clear for me that it is against best practice to have invalid certificates, never the less I want to / need to do it :)

What I did so far:
* Installed the self signed certificate on my apple hardware as suggested in different apple guides. After installation I activated the certificate in my custom profiles like this 

![Image](https://i.imgur.com/gD6oHxM.png)

* After I did that, I can open pictures on the webserver using safari without any security concerns, so Safari is very happy
* I Expected I can now load images from that webserver into UIImage without any problems, but I still get SSL warnings / Exceptions

This is the Code that is not working and throwing an Exception:
```
var client = new HttpClient(new NSUrlSessionHandler());
using (var response = await client.GetAsync(
       "https://my-company-image-server:7443/images/pic1.jpg",
       HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false)) {

}
```

Exception: System.Net.Http.HttpRequestException: 'An SSL error has occurred and a secure connection to the server cannot be made.'

StackTrace:
```
  at System.Net.Http.NSUrlSessionHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) [0x001d4] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.18.2.1/src/Xamarin.iOS/Foundation/NSUrlSessionHandler.cs:523 
  at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) [0x000b3] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:531 
```

I got further details from iOS System Log that for me looks fine, the correct certificate is used:
```
2020-06-11 11:50:20.246732+0200 Futura.IA.iOS[18065:751783] ATS failed system trust
2020-06-11 11:50:20.246837+0200 Futura.IA.iOS[18065:751783] Connection 1: system TLS Trust evaluation failed(-9802)
2020-06-11 11:50:20.246942+0200 Futura.IA.iOS[18065:751783] Connection 1: TLS Trust encountered error 3:-9802
2020-06-11 11:50:20.247033+0200 Futura.IA.iOS[18065:751783] Connection 1: encountered error(3:-9802)
2020-06-11 11:50:20.248502+0200 Futura.IA.iOS[18065:751783] Task <7C2C913E-A1EE-4579-A648-AC6F9CDA7006>.<1> HTTP load failed, 0/0 bytes (error code: -1200 [3:-9802])
2020-06-11 11:50:20.253148+0200 Futura.IA.iOS[18065:751783] Task <7C2C913E-A1EE-4579-A648-AC6F9CDA7006>.<1> finished with error [-1200] Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(0x7ff2ea269a00) s: Futura FAS HO i: Futura 4Pos Infrastructure FAS HO Intermediate CA>",
    "<cert(0x7ff2ea27b600) s: Futura 4Pos Infrastructure FAS HO Intermediate CA i: Futura 4Pos Infrastructure Intermediate CA>",
    "<cert(0x7ff2ea27c000) s: Futura 4Pos Infrastructure Intermediate CA i: Futura Root Certification Authority>",
    "<cert(0x7ff2ea27ca00) s: Futura Root Certification Authority i: Futura Root Certification Authority>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://my-company-image-server:7443/images/pic1.jpg, NSErrorFailingURLStringKey=https://my-company-image-server:7443/images/pic1.jpg, NSUnderlyingError=0x600002382850 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x600001fd0bd0>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x7ff2ea269a00) s: Futura FAS HO i: Futura 4Pos Infrastructure FAS HO Intermediate CA>",
    "<cert(0x7ff2ea27b600) s: Futura 4Pos Infrastructure FAS HO Intermediate CA i: Futura 4Pos Infrastructure Intermediate CA>",
    "<cert(0x7ff2ea27c000) s: Futura 4Pos Infrastructure Intermediate CA i: Futura Root Certification Authority>",
    "<cert(0x7ff2ea27ca00) s: Futura Root Certification Authority i: Futura Root Certification Authority>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <7C2C913E-A1EE-4579-A648-AC6F9CDA7006>.<1>"
), _kCFStreamErrorCodeKey=-9802, _NSURLErrorFailingURLSession
TaskErrorKey=LocalDataTask <7C2C913E-A1EE-4579-A648-AC6F9CDA7006>.<1>, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x600001fd0bd0>, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.}
**System.Net.Http.HttpRequestException:** 'An SSL error has occurred and a secure connection to the server cannot be made.'
```

I can work around this Issue by using Managed HTTP Client like this:

```
var handler = new HttpClientHandler();
handler.ServerCertificateCustomValidationCallback += (sender, certificate, chain, errors) => true; // DO SSL Pinning here!

var client = new HttpClient(handler);
using (var response = await client.GetAsync(
    "https://my-company-image-server:7443/images/pic1.jpg",
     HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false)) {

}
```

Is it some how possible to configure NSSessionHandler to accept my certificate? I played around with some properties but I could not find any good reference on how to do it correctly.

Thanks alot

**Comment by whitneyschmidt** [comment]
Adding @mandel-macaque

**Comment by whitneyschmidt** [comment]
@nschoenberg Were you able to find a solution or workaround for this? Closing as it's been a while since this was first opened.

If you are still experiencing this issue then click the Reopen Issue button and we can investigate.

Thanks!

**Comment by nschoenberg** [comment]
@whitneyschmidt  Thanks for coming back to me. There are many workarounds possible to achieve the goal to show insecure image resources on iOS. By insecure I mean http connections or https connections with an invalid certificate.

1) Using .net HttpClient instead of the native NSUrlSession
This way a developer can attach the global callback event `ServerCertificateCustomValidationCallback` and is able to ignore invalid certificates. The drawback is that using NSUrlSession is the recommended way to have best performance.

2) Opt-Out of TLS by changing info.plist
This way a developer can partially or completely opt-out of TLS. A Description is provided by [Microsoft](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/ats#configuring-ats-options) and [Apple](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads). The drawback of this workaround is that it will require additional justification arguments when trying to push this into the apple app store. Quote from Apple:

> You must supply a justification during App Store review if you set the key’s value to YES, as described in Provide Justification for Exceptions. Use this key with caution because it significantly reduces the security of your app. In most cases, it’s better to upgrade your servers to meet the requirements imposed by ATS, or at least to use a narrower exception.

Therefore, the absolute best option for my scenario is to install the custom SSL certificate on the Apple device. This way, my connection should be trusted without any drawbacks. Because none of the described workarounds is something I can do, I reopen the issue as suggested.

**Comment by whitneyschmidt** [comment]
@nschoenberg Hm...the reopen button is directly to the left of the comment button for me. I would _expect_ you to have appropriate permissions to reopen the issue but I'm not sure.

**Comment by whitneyschmidt** [comment]
@mandel-macaque Do you have any ideas on this issue? Is there any additional information @nschoenberg could provide that might be useful?

**Comment by mandel-macaque** [comment]
Sorry for the late reply, I must have missed the notification :/

@nschoenberg you mentioned that you looked at using the .net managed client to perform the validation of the certificate using ServerCertificateCustomValidationCallback but there is no need for you to use the managed implementation to do this, you can use the native NSUrlSessionHanlder implementation AND perform the verification. We provide a callback to do so.

* Delegate signature can be seen here: https://github.com/xamarin/xamarin-macios/blob/main/src/Foundation/NSUrlSessionHandler.cs#L55
* The delegate can be set suing the NSUrlSessionHandler *TrustOverrideForUrl*: https://github.com/xamarin/xamarin-macios/blob/main/src/Foundation/NSUrlSessionHandler.cs#L314

So the above will allow you to be able to implement the required validation since you will receive the following:

* url: The url that was used for the request.
* trust: The SecTrust object to validate. 

You can use the SecTrust object to validate the certificate via de [Evaluate method](https://github.com/xamarin/xamarin-macios/blob/main/src/Security/SecTrust.cs#L227). When calling evaluate, the SecTrust object will do the following as per apple docs:

> If the trust management instance lacks some of the certificates needed to verify the leaf certificate, SecTrustEvaluateWithError searches for certificates:
>
> * In the user’s keychain.
> * Among any certificates you previously provided by calling SecTrustSetAnchorCertificates.
> * In a system-provided set of keychains provided for this purpose.
> * Over the network, if certain extensions are present in the certificate used to build the chain.

In this case I believe that since you installed the certificate in the device, we should be in the first case.

**Comment by chamons** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
