### ISSUE TITLE
Upload fail after edited library project

### ISSUE THREAD

**Issue by suihanhbr** [xamarin/xamarin-macios#8850]
My solution include a Xamarin.iOS project and some library project which be referenced by the Xamarin.iOS project. I change the codes of library project and then run the Xamarin.iOS project . It build successful, but upload fail unless I clean the Xamarin.iOS.

### Steps to Reproduce

1. change library codes.
2. run the Xamarin.iOS project
3. project build successful but upload fail to device.

### Expected Behavior
run successful
### Actual Behavior
can run unless clean the Xamarin.iOS 
### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.6.3 (build 30)
Installation UUID: 4e60959a-758f-48ce-ae6d-26e15276ea83
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000104

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.300/Sdks
SDK Versions:
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.100
	3.0.100-preview5-011568
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.0
	3.0.0-preview5-27626-15
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.5 (16139)
Build 11E608c

=== Xamarin.Mac ===

Version: 6.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:04-0400

=== Xamarin.iOS ===

Version: 13.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:05-0400

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Xamarin.Android ===

Version: 10.3.1.4 (Visual Studio Community)
Commit: xamarin-android/d16-6/3a10de9
Android SDK: /Users/huangboru/myfile/sdk
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.1
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/huangboru/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-05-15 00:43:06 UTC

=== Android Device Manager ===

Version: 16.6.0.95
Hash: 45d17b5
Branch: remotes/origin/d16-6
Build date: 2020-05-15 00:43:26 UTC

=== Build Information ===

Release ID: 806030030
Git revision: f43dfeb8c84a15c535a3a0861dcbc4c68bd73815
Build date: 2020-06-04 12:43:00-04
Build branch: release-8.6
Xamarin extensions: f43dfeb8c84a15c535a3a0861dcbc4c68bd73815

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Tue May 26 20:41:44 PDT 2020
    root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Log Monitor 0.2
.NET Core support for Mono.Debugging 8.0.5
NuGet Package Management Extensions 0.21
Open With 0.2


```

### Build Logs

 PackageInspectionFailed: Failed to load Info.plist from bundle at path /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.VjXR7R/extracted/Payload/SuiHanIME.iOS.app/Frameworks/Xamarin.Sdk.framework; Extra info about plist: ACL=<not found> 
error MT1006: Could not install the application '/Users/huangboru/myfile/xamarin_workspace/version4/iOS/bin/iPhone/Release/SuiHanIME.iOS.app' on the device 'SuiHan Phone': Package Inspection Failed Error (error: 0xe8000051).

**Comment by chamons** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs and/or test case (to reproduce).

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

We look forward to hearing from you!

**Comment by suihanhbr** [comment]
There are the Information of Deploying to Device and Build Output.

[Deploying to Device.txt](https://github.com/xamarin/xamarin-macios/files/4786097/Deploying.to.Device.txt)
[Build Ouput.txt](https://github.com/xamarin/xamarin-macios/files/4786098/Build.Ouput.txt)

**Comment by chamons** [comment]
The error in particular:

```
error MT1006: Could not install the application '/Users/huangboru/myfile/xamarin_workspace/version4/iOS/bin/iPhone/Release/SuiHanIME.iOS.app' on the device 'SuiHan Phone': Package Inspection Failed Error (error: 0xe8000051).
```

There are a huge number of people hitting this error online using only Xcode:

https://stackoverflow.com/questions/26015194/xcode-could-not-inspect-the-application-package
https://stackoverflow.com/questions/33182564/app-installation-failed-could-not-inspect-the-application-package
https://stackoverflow.com/questions/13659409/xcode-error-message-could-not-inspect-application-package
https://stackoverflow.com/questions/14630828/could-not-inspect-application-package-xcode

And some people with project specific configuration issues.

That error is coming from the underlying Apple tooling, we are just bubbling the error up as MT1006.

To proceed further, we need an example project that reproduces the problem.

**Comment by suihanhbr** [comment]
The phenomenon disappeared after I carried my code to a new Xamarin.iOS project. I think it is because the old format of .csproj.

**Comment by chamons** [comment]
Thanks for the follow up. 

If you run into this issue again, please try to create a sample and reopen with details.
