### ISSUE TITLE
Xamarin iOS build with Strip Native Debugging Symbols enabled contains symbols

### ISSUE THREAD

**Issue by jkavanaghrdm** [xamarin/xamarin-macios#8881]
### Steps to Reproduce

1. Run msbuild to output iOS build with "Strip Native Debugging Symbols" enabled

### Expected Behavior
Application binary that is generated does not contain symbols.

### Actual Behavior
Application binary that is generated contains symbols e.g. __mh_execute_header _xamarin_IntPtr_objc_msgSendSuper_IntPtr _xamarin_IntPtr_objc_msgSend_IntPtr _xamarin_find_protocol_wrapper_type _xamarin_get_block_descriptor _xamarin_release_block_on_main_thread _AVCaptureSessionInterruptionEndedNotification etc

Note the following section of the build output log states:

Task "SymbolStrip"
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -i -s obj/iPhone/Release/mtouch-symbols.list bin/iPhone/Release/SDXiOS.app/SDXiOS 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: **removing global symbols from a final linked no longer supported**.  Use -exported_symbols_list at link time when building: /Users/t445780/dev/rdm/sdm/src/SDX.UI.iOS/bin/iPhone/Release/SDXiOS.app/SDXiOS
Done executing task "SymbolStrip".

Is there another way to direct the build to strip all symbols?

### Environment
Visual Studio for Mac

### Build Logs
[buildoutput.txt](https://github.com/xamarin/xamarin-macios/files/4795318/buildoutput.txt)

**Comment by chamons** [comment]
There are some distinctions to be made between symbols in a binary symbols and debug symbols, they aren't necessarily the same thing. I do not believe this is a bug once you understand the difference.

Tools such as nm and other resolve "symbols" in a binary file. These "symbols" are items you can locate with [dlsym](https://pubs.opengroup.org/onlinepubs/009695399/functions/dlsym.html), and are often global named functions and constants. In general, they are written in low level languages such as C or Objective-C, where there is a one to one mapping between a section of a binary. Some of them are required by the Objective-C runtime to be able to instance our types and call back into our code.

In addition to the named sections that are baked into a native binary, additional debugging information is baked into the binary. Things like mapping between sections of the binary and the respective lines in the source code, for example. In the "Strip Native Debugging Symbols" feature we are asking Apple's strip tool to remove this debugging information from the binaries. Those can be stored in a dSYM file next to the binary in question, and not within. You can read about this here: https://lldb.llvm.org/use/symbols.html

An application having public symbols does not necessarily mean that the debugging information hasn't been stripped, the named symbol location of a binary and the debugging information that gets moved into dSYM files are different.

If you want to get a better understanding of what's going on, do a build without "Strip Native Debugging Symbols" enabled and compare the output size and symbols.

I'm sure there are further optimizations we can make in our runtime, and some symbols may not be strictly necessary, but we'd notice very quickly if debugging symbols weren't being stripped in Release binaries, they are very large.

**Comment by jkavanaghrdm** [comment]
Thanks for the update and the clarification. I appreciate the detail. With that, is there a way to direct the release build to strip all symbols?

**Comment by chamons** [comment]
As I noted before, some symbols are required for various reasons. The warning from strip:

```
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: removing global symbols from a final linked no longer supported. Use -exported_symbols_list at link time when building: /Users/t445780/dev/rdm/sdm/src/SDX.UI.iOS/bin/iPhone/Release/SDXiOS.app/SDXiOS
```

suggests you could run your own strip with -exported_symbols_list and specify exactly what symbols you want exported, but that is likely to break things.

Why the interest in the exported native symbols? Every symbol you listed so far is either internal to Xamarin.iOS's runtime or generated support code for an API binding.

**Comment by jkavanaghrdm** [comment]
These symbols are being reported in a vulnerability assessment on Xamarin builds for iOS and so I'm trying to determine if there is a way to remove them. If these are actually needed and cannot be removed then so be it. Just wanted to make sure I exhausted all options before we look at alternative approaches. Please confirm they cannot be removed.

**Comment by chamons** [comment]
I do not believe there are security implications here and that it's a false positive in your tool, but I'll let @spouliot comment to confirm.

**Comment by spouliot** [comment]
> Please confirm they cannot be removed.

Hard to say without seeing a list of symbols :) Most of the symbols you mentioned in your original description cannot be removed.

What tool are you using ? and can you share your results with us (privately) ?

We have seen tools that don't (even try to) understand Xamarin binaries and assume ObjC code. That makes their report largely unusable, unless you know what can (should) be filtered out.

The linkers (both the Xamarin/managed one and the Apple/native one) only include the code that is referenced (needed) by your application. So the code (and number of symbols) will vary by your usage of the APIs. Some symbols will *always* be present since the mono (or xamarin) runtime(s) are using them.

In any case striping the symbols would not remove the code. You can hide symbols (e.g. make them private) but that would not change the potential vulnerabilities in your application.

**Comment by jkavanaghrdm** [comment]
I've reached out for more information and will respond back asap.
