### ISSUE TITLE
Xamarin.iOS versions mismatch: Never ending install

### ISSUE THREAD

**Issue by NimeCloud** [xamarin/xamarin-macios#8975]
My kudos goes to engineer who designs this. Notice to download percentage! I'm stuck and can't do my work for two days. This issue seems like never fixed for months, either.

![mismatch](https://user-images.githubusercontent.com/2706637/86143313-f0a39a00-bafc-11ea-90fa-8092470db9c1.png)

Any cool idea?

> VS bug [#1149290](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1149290)

**Comment by mauroa** [comment]
Hi,
The percentage overflow issue has already been fixed so if you install the latest VS 16.6 or any VS 16.7 Preview version you should not experience this anymore. Based on your comments, I assume you are not using those versions. 

Here's a link to the same issue already reported and fixed: https://developercommunity.visualstudio.com/content/problem/957757/percentage-display-incorrect-when-installing-missi.html

On the other hand, it's better if you report VS related issues in the VS dev community, find the link for the next time: https://developercommunity.visualstudio.com/spaces/8/index.html

Finally, if after updating the versions you are already experiencing installation issues, please attach the VS log (from VS: `Help > Xamarin > Zip Logs...`) so we can investigate further.

As a not recommended workaround, you can temporarily disable Xamarin iOS checks by editing this registry key: `Computer\HKEY_CURRENT_USER\Software\Xamarin\VisualStudio\MacAgent` and adding this value: `DisableXamariniOSValidation` -> `True`. This can cause unwanted effects if you let it disabled forever, so try to use it a last resource.

I'm closing this issue but feel free to re-opening it if you still experience issues after updating.
Thanks
