### ISSUE TITLE
AutoFill Credential Provider and other iOS 11+ extensions are broken during build process

### ISSUE THREAD

**Issue by kiddailey** [xamarin/xamarin-macios#9000]
It is not possible to create a working AutoFill Credential Provider Extension or any extension type introduced in iOS 11+.  Although code support appears to be present, the build process breaks the integration with iOS because all NSExtensionPoints introduced after iOS 10 are undefined.

The credential provider is the focus of the information below as that is my immediate need.  I have already applied a fix to Xamarin-macios and Xamarin-MacDev in my environment, confirmed that my code changes resolve the issue and allow the extension to function as expected, and will submit a pull request.  My assumption is that similar changes can be applied to allow for the other missing extension types to be supported.

### Steps to Reproduce

1. Create an Action Extension as a baseline a template for Credential Provider is not available
2. Modify the extension to conform to a Credential Provider extension (sample project provided below)
3. Attempt to build and run the extension

### Expected Behavior

* Extension should appear in iOS Settings > Passwords & Accounts > AutoFill Passwords as a credential provider

### Actual Behavior

* Build console displays warning: 

> warning : The App Extension 'Extension' has an unrecognized NSExtensionPointIdentifier value ('com.apple.authentication-services-credential-provider-ui').

* Extension does not appear as credential provider in iOS settings

### Environment

Both Windows and Mac

Windows:
https://gist.github.com/kiddailey/23946ab84ae9f2e4439ff3f5ea51b76b

Mac:
https://gist.github.com/kiddailey/7aed782c076875b64f26892c50620253

### Build Logs

https://gist.github.com/kiddailey/042fecd335fb4fc24fa708afe128e257

### Example Project (If Possible)

[AutoFillCredentialProviderExampleApp.zip](https://github.com/xamarin/xamarin-macios/files/4871325/AutoFillCredentialProviderExampleApp.zip)

### Additional Notes

* There are two sets of changes required to resolve this for the credential provider:
  * Update Xamarin.MacDev
  * Update Xamarin-macios

**Comment by chamons** [comment]
It looks like you've worked through this in:

https://github.com/xamarin/Xamarin.MacDev/pull/75

**Comment by kiddailey** [comment]
Yup. There's also a corresponding change to Xamarin-macios and per the suggestion of @rolfbjarne, I will submit a pull request for that once the MacDev change is merged.

Once I have more time, I may go through and submit changes for the other missing NSEntryPoints as well.

**Comment by rolfbjarne** [comment]
@kiddailey could you try the package with the fix (https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/main/97d09a7b243ea5d1d64a37c05faa7ec1e354a7f0/95/package/notarized/xamarin.ios-13.21.1.274.pkg) and verify that it works for you?

**Comment by kiddailey** [comment]
Installed fine, verified that my "current" is the newly installed version and built the example Credential provider project.  Received no warnings and the extension worked ask expected.  Also tried it with a more complex extension setup and it worked as expected there as well.  Thanks!

**Comment by rolfbjarne** [comment]
Great, thanks! I'm going to close this then, and we're going to try to get this in our `d16-8` release later this fall.
