### ISSUE TITLE
Failing to archive solution with Notification Extension from Windows

### ISSUE THREAD

**Issue by taublast** [xamarin/xamarin-macios#9007]
When you create an app with Notification Service Extension it fails to archive in Visuial Studio for Windows. Haven't tried from mac.

The main error is like 
`Could not find a part of the path "/Users/Username/Library/Caches/Xamarin/mtbs/builds/BlaBla.iOS/c53f41a2a149592e299c552833a05746/F:/BlaBla/Src/BlaBla.OneSignalNotificationServiceExtension/bin/iPhone/Release/OneSignalNotificationServiceExtension.appex/Info.plist".`

The bug is that the for the path on mac it is creating folder "F/" for "F:" then subfolder "Blabla" etc and the plist file is well there. Obviously it cannot the find the part of path ..5746/F:/Bl.." as it created "..5746/F//Bl.." on disk.

You can find more info here: https://forums.xamarin.com/discussion/comment/416067#Comment_416067

### Steps to Reproduce

1. in apple developper console create app ids: com.bug.app, com.bug.app.extension.
add them both to group group.com.bug.app.extension.push. have them push notifications enabled too,

2. create profiles ad-hoc for both

3.  Create a new project from template Mobile App Xamarin Forms, you need iOS only for our case. Edit manifest, set bundle as com.bug.app, deployment target 10.0.

4.  Add a new project from template "Notification Service Extension (iOS)" to solution, Edit manifest, set bundle as com.bug.app.extension, deployment target 10.0.

5. for both projects edit entitlements: 
enable push notifications, 
enable app groups, add "group.com.bug.app.extension.push". 
Avoid another bug, edit entitlement code manually change 
```
	<key>aps-environment</key>
	<string>development</string>
```
change "development" to "production". 

3. Set configuration to Release, 

4. add project reference com.bug.app.extension to com.bug.app. This step creates the bug, without this step the extension just won't work obviously.

5 Insure solution builds and runs on your real device.

6. Now Right-click main iOS project, select archive, observe the bug.

### Expected Behavior

To archive ok. 

### Actual Behavior

![t5ouw54mfoav](https://user-images.githubusercontent.com/25801194/86530647-016c5b00-bec3-11ea-8ac1-fce59416c6e3.png)

### Environment

Microsoft Visual Studio Community 2019
Version 16.6.3
Xamarin   16.6.000.1062 (d16-6@41e1f0e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3
Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

> VS bug [#1152252](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1152252)

**Comment by chamons** [comment]
Looks like straightforward Windows -> macOS path mapping issue.

**Comment by mshuf** [comment]
+1

@taublast Did you find a work-around by any chance?

**Comment by sasa-bobic** [comment]
This is still a problem with VS 2019 16.8.4 and latest Xamarin.IOS.

Is there any workaround for this?

**Comment by marosbeno** [comment]
I had the same problem. Tried setting "Copy to Output Directory" to "Copy if newer" on Notification Service Extensions Info.plist file and it worked for me.

**Comment by ispysoftware** [comment]
still not working vs 2022 17.0.4

**Comment by fdsdev** [comment]
+1
Still not work  with vs 16.11.11.
Any update?

**Comment by Matti-Koopa** [comment]
Why is this closed?
