### ISSUE TITLE
Support Xcode 12 before new APIs fully supported

### ISSUE THREAD

**Issue by t9mike** [xamarin/xamarin-macios#9066]
My Apple Watch app crashes on watchOS 7 Beta. All I want to do is figure out why it is crashing, not support new APIs, etc. I want to run my app in Xcode 12 debugger against watchOS 7 simulator.

Please for new major Xcode releases, support the new Xcode toolchain only ASAP. APIs can come later.

**Comment by chamons** [comment]
Until Apple releases a final GM of a major Xcode release, it is premature for us to declare any build as containing tooling support. Historically Apple has added breaking changes all the way up to their final, though the first few betas are always the roughest.

Apple did make one launcher break in this first Xcode which we [cherry picked](https://github.com/xamarin/xamarin-macios/commit/32c359768dce16a8150143481ec9b5831e282982) to the current Beta in an attempt to reduce everyone's pain this fall when Xcode auto-updates before the Xamarin update goes live on stable.

If you are interested in testing out Xcode 12, I'd suggest on a mac:

- [Downloading the latest Xamarin.iOS build](https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build) of the SDK, currently https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode12/8a57e7daf69bcffee528ad632e74ca05a7aa3420/56/package/notarized/xamarin.ios-13.99.0.56.pkg (We know for sure that using stable XI will not work).
- If that fails, open an issue with the full build log, IDE logs, and crash log. 
- "It crashed" is not actionable - we don't know if it's an Apple bug, a Xamarin bug, or a behavior change causing your application to now change. 
- The project itself would be bonus points, along with testing a brand new empty watchOS project on your watch as well.

Testing during Xcode season is always appreciated, just expect some rough edges (both Apple's and ours) along the way.

**Comment by t9mike** [comment]
While I appreciate being pointed to the latest build, the issue I have is there is never any advertised way to get these early releases. Yes I know things change. And you keep up with them. But before you do your preview release that is much more complete, you need to have a place developers can go to and fetch this preliminary work (and not stumble on it in a ticket like this).

That should be either:

- New preview channel (Xcode 12 Alpha) in Visual Studio
- A standard location on Website that can be found every release cycle, pointed to by blog post, etc.

Because if I search for xamarin.ios xcode 12 I find little.

I started building from source last night. I would rather avoid this and will try the download.

**Comment by t9mike** [comment]
What I am trying to say is you desperately need a place where, every year, folks who need new Xcode ASAP for whatever reason -- mine #1 is just being able to debug against new OS simulators -- can go to. Nightly builds may not always be the best. This can have latest known issues, best latest nightly build to use, log of major fixes/updates, etc.

**Comment by chamons** [comment]
We are trying to better document what people should expect during the summer. See: https://github.com/xamarin/xamarin-macios/wiki/Xcode-Summer-Expectations

We plan on having a public preview channel in VSfM in the coming weeks, we just haven't dug out enough from Beta 1 & 2 to have something useful for most people right now (this is the case every year at this point). 

Until we get that public preview out, if you want to try things early then https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build has instructions and you can grab packages off our branch.
