### ISSUE TITLE
Error MT4109

### ISSUE THREAD

**Issue by tuongnd2020** [xamarin/xamarin-macios#9077]
### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

**Comment by chamons** [comment]
Thank you for your feedback!

It sounds like you are running into issues with MT4109. However, without the information requested in the template it will not be possible for anyone to assist you.

Please open a new issue, with the requested information. In particular, a full build log, the version of Xamarin.iOS and Xcode, and preferably a sample project.
