### ISSUE TITLE
interface NFCIso15693Tag : NFCTag is out of date in iOS 13

### ISSUE THREAD

**Issue by Stuey2** [xamarin/xamarin-macios#9159]
The implementation of `interface NFCIso15693Tag : NFCTag` (see [current implementation](https://github.com/xamarin/xamarin-macios/blob/98a4c2bd609df1718f536b70004dd2c5dea3cf4c/src/corenfc.cs#L136-L138)) is out of date. In iOS 13 `NFCIso15693Tag` inherits from `NFCNdefTag`, similar to `interface NFCIso7816Tag : NFCTag, NFCNdefTag` (see [iso7816 implementation](https://github.com/xamarin/xamarin-macios/blob/98a4c2bd609df1718f536b70004dd2c5dea3cf4c/src/corenfc.cs#L743-L745))

Please could this be updated to reflect the current iOS protocols, see [NFCISO15693Tag](https://developer.apple.com/documentation/corenfc/nfciso15693tag) and [NFCISO7816Tag](https://developer.apple.com/documentation/corenfc/nfciso7816tag) **Relationships** heading, which show that both inherit from `NFCNDEFTag`

**Comment by chamons** [comment]
This may be fixable without an API break:

`REQUIRES JUDGMENT: Introducing a new base class`

from

https://docs.microsoft.com/en-us/dotnet/core/compatibility/

**Comment by spouliot** [comment]
`NFCIso7816Tag ` is a protocol (interface) which makes it easier, unless inlined (which I don't think it is)

**Comment by spouliot** [comment]
It's not an issue to update it.
We'll include this in our `xcode12` support since it's _likely_ the next (non frozen) branch to be released.

**Comment by spouliot** [comment]
fix is in `xcode12` branch
