### ISSUE TITLE
iOS14 simulator is not listing in Xamarin

### ISSUE THREAD

**Issue by xhashimks** [xamarin/xamarin-macios#9163]
I have downloaded XCode12 beta 2 and added Apple SDK in Visual Studio for Mac. When I select the simulator, it does not list any of the simulators.

Mac OS - Catalina 10.15.5 (19F101)
Visual Studio for Mac: 8.6.5 (build 23)
Xamarin.iOS : 13.18.2.1
Xamarin.Forms: 4.7.0.1080

Attached the screenshots from my IDE
<img width="728" alt="Screenshot 2020-07-17 at 10 52 49 PM" src="https://user-images.githubusercontent.com/47141601/87814010-9f2b3700-c880-11ea-8a8a-401bd924b223.png">
<img width="552" alt="Screenshot 2020-07-17 at 10 53 02 PM" src="https://user-images.githubusercontent.com/47141601/87814016-a18d9100-c880-11ea-86dc-7a14c6d63c31.png">

**Comment by chamons** [comment]
13.18.2.1 does not support Xcode 12, so I'm not surprised things aren't working at all.

You can use the instructions [here](https://github.com/xamarin/xamarin-macios/wiki#downloading-a-build) to download a build from our [Xcode 12 lane](https://github.com/xamarin/xamarin-macios/tree/xcode12) or wait for our first public review.

**Comment by xhashimks** [comment]
I managed to install iOS14 beta in a latest device and used that for debug purpose.

**Comment by Ranjith4Git** [comment]
Hi, I have tried preview Version: 13.22.1.2 (Xamarin.iOS - preview) and able to install my application in iOS 14 simulator. 
Still, if anyone are not able to see the iOS 14 simulator option in Visual Studio. 
Then create and deploy a native iOS application (sample) in iOS 14 simulator using Xcode 12 beta. Then you should able to see the iOS 14 simulator option in Visual Studio.
