### ISSUE TITLE
[Bug] iOS 14 Beta: App name incorrect when searching

### ISSUE THREAD

**Issue by mictmccarthy** [xamarin/xamarin-macios#9216]
### Description
On the iOS 14 Beta, the App Name shows correctly on the home screen. However when you swipe down on the home screen and search for your app, it will show up as the iOS Project name (Ex.Ample.iOS) instead of the app name (Example App).

### Steps to Reproduce

1. Update your device to the iOS 14 beta
2. Search for your Xamarin Forms App
3. 

### Expected Behavior
When searching for your app, it shows the App Name.

### Actual Behavior
When searching for your app, it shows the name of your iOS project.

### Basic Information

- Version with issue: 
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  iOS 14
- Nuget Packages:
- Affected Devices: All iOS Devices

**Comment by chamons** [comment]
It appears that `Bundle display name` (CFBundleDisplayName) is being used for the home screen name and `Bundle name` (CFBundleName) is being used for search, at least in my test project.

Please confirm that there is a difference between the keys in your test project, try setting them to the same and reporting back, and if that does not resolve it please attach a small test project.

**Comment by chamons** [comment]
One other note, Apple is using these keys internally to generated the UI, as of right now I don't believe any of this is Xamarin.iOS related.

**Comment by svaldetero** [comment]
This issue does not appear to be happening in Developer Beta 4.

**Comment by valdetero** [comment]
This issue does not appear to be happening in Developer Beta 4.

**Comment by whitneyschmidt** [comment]
@valdetero Glad to hear that you are no longer running into this :)

@mictmccarthy we have not received the requested information - if you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
