### ISSUE TITLE
Xamarin doesn't implement .net standard 2.1

### ISSUE THREAD

**Issue by GSerjo** [xamarin/xamarin-macios#9255]
### Steps to Reproduce

**Try to use `AesGcm`**

as per the source code, there's `PlatformNotSupportedException`

![image](https://user-images.githubusercontent.com/1163475/89128310-e0e3f080-d4c2-11ea-8b77-ad242ae8e65e.png)

as per this table. Xamarin fully support .net standard 2.1
![image](https://user-images.githubusercontent.com/1163475/89128358-2bfe0380-d4c3-11ea-8277-64d3ae242c0b.png)
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

```
=== Visual Studio Community 2019 for Mac ===

Version 8.6.8 (build 2)
Installation UUID: ad237128-4113-433e-bff0-a7eb954305ae
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 610000106

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.106 (2019-12/77769615db1) (64-bit)
	Package version: 610000106

=== Roslyn (Language Service) ===

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===

Version: 5.6.0.6591

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.302/Sdks
SDK Versions:
	3.1.302
	3.1.301
	3.1.300
	3.1.201
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.6
	3.1.5
	3.1.4
	3.1.3
	2.1.20
	2.1.19
	2.1.18

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin.Mac ===

Version: 6.18.3.2 (Visual Studio Community)
Hash: ce0cc74a3
Branch: d16-6-xcode11.6
Build date: 2020-07-16 18:15:27-0400

=== Xamarin.iOS ===

Version: 13.18.3.2 (Visual Studio Community)
Hash: ce0cc74a3
Branch: d16-6-xcode11.6
Build date: 2020-07-16 18:15:27-0400

=== Xamarin.Android ===

Version: 10.3.1.4 (Visual Studio Community)
Commit: xamarin-android/d16-6/3a10de9
Android SDK: /Users/nelibur/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/nelibur/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-06-10 22:42:50 UTC

=== Android Device Manager ===

Version: 16.6.0.96
Hash: 6e8b80b
Branch: remotes/origin/d16-6
Build date: 2020-06-10 22:43:28 UTC

=== Build Information ===

Release ID: 806080002
Git revision: e999e2934e8c771fdf6494b80361dacef9427565
Build date: 2020-07-24 15:17:52-04
Build branch: release-8.6
Xamarin extensions: e999e2934e8c771fdf6494b80361dacef9427565

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Sun Jul  5 00:43:10 PDT 2020
    root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

```

Could you please clarify why in the documentation there's full support and in the code `PlatformNotSupportedException`?

**Comment by chamons** [comment]
Thanks for the report. As this has to do with our BCL (Base Class Library) I'm going to move this over to mono for review.

**Comment by chamons** [comment]
This issue was moved to mono/mono#20200

**Comment by GSerjo** [comment]
Hi @chamons,

Thank you for the quick reply. Formally, Xamarin.iOS doesn't implement .net standard 2.1 too. It's not only Mono issue, it's Xamarin issue. 

Xamarin uses Mono, Mono doesn't implement .net Standard 2.1  => Xamarin.iOS/Mac doesn't implement this standard too.

Could you please create a request/update documentation on Microsoft site, Xamarin doesn't implement .net standard 2.1 the same for Mono

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by chamons** [comment]
See this reply: https://github.com/mono/mono/issues/20200#issuecomment-668142737

**Comment by GSerjo** [comment]
I hope it's a misunderstanding. 

@chamons  could you please reopen the issue

![image](https://user-images.githubusercontent.com/1163475/89214034-0db40880-d594-11ea-85c9-e3666bb36b2a.png)

**Comment by chamons** [comment]
@GSerjo - There is nothing to really reopen here, the issue was moved to mono/mono for a reason. My team is not responsible for the active BCL surface. 

Xamarin.iOS and Mac consumes the BCL from mono directly, and this specific API is not currently implemented in the mobile profiles. 

You could open a feature request in mono/mono, but given the comment about One.NET it may be on the possible roadmap anyway. 

If you have specific feedback, you can consider directing it to our team’s [program manager](david.ortinau@microsoft.com).

**Comment by GSerjo** [comment]
thank you, will do. as per this statement mono and Xamarin implement .net standard. in reality, it's not.

looks like the approach with just throwing an exception and moving to prod it's your approach.

![image](https://user-images.githubusercontent.com/1163475/89215760-34c00980-d597-11ea-9a4e-da5ba2d8fe43.png)

**Comment by chamons** [comment]
I understand your frustration, but I don't believe you are being constructive here. 

I, or Marek on the mono/mono issue, would be happy to go into the difference between API surface and platform availability if you want details, but this is not a new or unique circumstance.

**Comment by GSerjo** [comment]
just don't say Xamarin supports .net standard 2.1 it's not true.

>.NET Standard does not say anything about implementation only about API availability. Throwing PNSE is hence valid implementation.

as for me it's not a good approach, in this case just throw exceptions everywhere.

I reported the issue.. and in both teams, I got it's not an issue and throwing expectation it's an appropriate implementation
