### ISSUE TITLE
AudioUnit.SetLatency should not exist

### ISSUE THREAD

**Issue by bastos80** [xamarin/xamarin-macios#9256]
### Steps to Reproduce

1. Create an AudioUnit object
2. Call SetLatency on it
### Expected Behavior

SetLatency should be removed since kAudioUnitProperty_Latency is read-only according to the [specs](https://developer.apple.com/documentation/audiotoolbox/kaudiounitproperty_latency).

### Actual Behavior

Returns InvalidProperty

**Comment by bastos80** [comment]
By the way, the correct way to set the latency for an AudioUnit would be the following (somewhat unintuitive) method:

```c#
static OSStatus SetCurrentIOBufferFrameSize(AudioUnit inAUHAL,
                                        UInt32 inIOBufferFrameSize)
{
  return AudioUnitSetProperty(inAUHAL,
                              kAudioDevicePropertyBufferFrameSize,
                              kAudioUnitScope_Global,
                              0,
                              &inIOBufferFrameSize, sizeof(UInt32));
}
```

See [this StackOverflow article](https://stackoverflow.com/questions/33030913/avaudioengine-any-way-to-control-buffer-size-latency?rq=1)

**Comment by whitneyschmidt** [comment]
@bastos80 Thank you for your feedback!

I was able to validate that it's possible to call `SetLatency` with the following code:

```
var audioComponent = AudioComponent.FindComponent (AudioTypeOutput.VoiceProcessingIO);
var audioUnit = new AudioUnit.AudioUnit (audioComponent);
audioUnit.SetLatency (1.0);
```

I'm marking this as an `enhancement` since it's not a breaking bug, but it should be fixed. Thanks for bringing awareness to this issue!
