### ISSUE TITLE
Update downloads sections of readme.md to include 13.20 PKG

### ISSUE THREAD

**Issue by SaqibS** [xamarin/xamarin-macios#9337]
In readme.md, the Downloads section includes a table of downloadable packages up to 16.6. Please could you add a download link to 16.7, for the download.visualstudio.microsoft.com link.

We use this table to make sure our CI pipelines are using the latest _stable_ Xamarin.iOS, without trying to do a headless Visual Studio install.

**Comment by dalexsoto** [comment]
Thanks for reaching out, this will be resolved shortly, thanks for the heads up!
