### ISSUE TITLE
File.Open doesn't throw IOException when file is locked by another process in xamarin.mac application

### ISSUE THREAD

**Issue by vincentSerrano** [xamarin/xamarin-macios#9341]
Hello,

I observe that a console application behaves differently from a xamarin.mac application when calling System.IO.File.Open method
I can't figure out if this is an expected behavior or not.

Any help is welcome !

Thanks

### Steps to Reproduce

1. Open FileOpenBehavior.sln
2. Define filePath with an opened Word document path in projects:
    * filesystem.cocoa (Main.cs) 
    * filesystem.console (Program.cs)
    * FileSystem.Lib.Tests (FileSystemWrapperTest.Test_IsFileLocked)

3. Execute filesystem.cocoa, filesystem.console and FileSystem.Lib.Tests

### Expected Behavior

- filesystem.cocoa => File is detected as locked
- filesystem.console => File is detected as locked
- FileSystem.Lib.Tests => File is detected as locked

### Actual Behavior

- **filesystem.cocoa => File is not detected as locked**
- filesystem.console => File is detected as locked
- FileSystem.Lib.Tests => File is detected as locked

### Environment
Visual studio for Mac 8.7 (build 2037) 

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.7 (build 2037)
Installation UUID: ac3be361-08fa-4874-8008-172381b0d9c9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000089

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.89 (2020-02/e59c1cd70f4) (64-bit)
	Package version: 612000089

=== Roslyn (Language Service) ===

3.7.0-6.20371.12+917b9dfae12e3b6cb266a3c062fb20a1e9d5fb06

=== NuGet ===

VersionÂ : 5.7.0.6702

=== Kit SDK .NET Core ===

SDKÂ : /usr/local/share/dotnet/sdk/3.1.302/Sdks
Versions du SDKÂ :
	3.1.302
	3.1.301
SDK MSBuildÂ : /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== Runtime .NET Core ===

RuntimeÂ : /usr/local/share/dotnet/dotnet
Versions du runtimeÂ :
	3.1.6
	3.1.5
	2.1.20
	2.1.19

=== Xamarin.Profiler ===

VersionÂ : 1.6.15.68
EmplacementÂ : /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

VersionÂ : 11

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Professional)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 13.20.2.2 (Visual Studio Professional)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Xamarin.Android ===

Non installÃ©

=== Microsoft OpenJDK for Mobile ===

Java SDK: Introuvable

Code EPL d'Android Designer disponible iciÂ :
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/dev/jmt/d16-7readconfig~2
Build date: 2020-07-23 22:38:02 UTC

=== Android Device Manager ===

Version: 16.7.0.18
Hash: 4b44bc1
Branch: remotes/origin/d16-7
Build date: 2020-07-23 22:38:26 UTC

=== Build Information ===

Release ID: 807002037
Git revision: b7706774ff5a1b761a7eb7f2d116d0d2c29ad87c
Build date: 2020-07-31 04:14:15-04
Build branch: release-8.7
Xamarin extensions: b7706774ff5a1b761a7eb7f2d116d0d2c29ad87c

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
    Tue May 26 20:41:44 PDT 2020
    root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
```

### Build Logs

[output.build.txt](https://github.com/xamarin/xamarin-macios/files/5051491/output.build.txt)

### Example Project (If Possible)

[FileOpenBehavior.zip](https://github.com/xamarin/xamarin-macios/files/5051373/FileOpenBehavior.zip)

**Comment by whitneyschmidt** [comment]
This issue was moved to mono/mono#20229

**Comment by whitneyschmidt** [comment]
cc @rolfbjarne 

It looks like this is probably on us or the IDE team? The expected behavior is that the file is locked, which is the case in all scenarios (including mono console app) except the .net console app.

**Comment by rolfbjarne** [comment]
I added a better test case to the mono bug.
