### ISSUE TITLE
[XHarness] The parsing of xml results sometimes ignores certain failures.

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#9400]
The following is an example:
```
<message>
<![CDATA[ Status not ok Expected: Unauthorized But was: GatewayTimeout ]]>
</message>
<stack-trace>
<![CDATA[ at MonoTests.System.Net.Http.MessageHandlerTest.GHIssue8342 (System.Net.HttpStatusCode expectedStatus, System.String validUsername, System.String validPassword, System.String username, System.String password) [0x000bd] in /Users/builder/jenkins/workspace/xamarin-macios-pr-builder/tests/monotouch-test/System.Net.Http/MessageHandlers.cs:532 ]]>
```
from https://github.com/xamarin/xamarin-macios/pull/9399

**Comment by rolfbjarne** [comment]
This happened again here: https://github.com/xamarin/xamarin-macios/pull/9537#issuecomment-682579041

Test xml (remove .txt extension): [vsts-nunit-test-watchos-20200828_092639.xml.txt](https://github.com/xamarin/xamarin-macios/files/5142564/vsts-nunit-test-watchos-20200828_092639.xml.txt)
