### ISSUE TITLE
OSLog Xcode12 Bindings Postponed

### ISSUE THREAD

**Issue by tj-devel709** [xamarin/xamarin-macios#9480]
Due to other higher priorities, OSLog's xcode12 bindings will be postponed until a later date.

The selectors that will not be available are the following:
**For iOS and tvOS**
OSLogEntryLogLevel
OSLogEntrySignpostType
OSLogEntryStoreCategory
OSLogEnumeratorOptions
OSLogMessageComponentArgumentCategory
OSLogStoreScope
OSLogEntryFromProcess
OSLogEntryWithPayload
OSLogStore::storeWithScope:error:
OSLogStore::storeWithURL:error: 
OSLogEntry::composedMessage
OSLogEntry::date
OSLogEntry::storeCategory
OSLogEntryActivity::parentActivityIdentifier
OSLogEntryLog::level
OSLogEntrySignpost::signpostIdentifier
OSLogEntrySignpost::signpostName
OSLogEntrySignpost::signpostType
OSLogMessageComponent::argumentCategory
OSLogMessageComponent::argumentDataValue
OSLogMessageComponent::argumentDoubleValue
OSLogMessageComponent::argumentInt64Value
OSLogMessageComponent::argumentNumberValue
OSLogMessageComponent::argumentStringValue
OSLogMessageComponent::argumentUInt64Value
OSLogMessageComponent::formatSubstring 
OSLogMessageComponent::placeholder
OSLogStore::entriesEnumeratorAndReturnError:
OSLogStore::entriesEnumeratorWithOptions:position:predicate:error:
OSLogStore::positionWithDate:
OSLogStore::positionWithTimeIntervalSinceEnd:
OSLogStore::positionWithTimeIntervalSinceLatestBoot:
OSLogEntry
OSLogEntryActivity 
OSLogEntryBoundary 
OSLogEntryLog 
OSLogEntrySignpost 
OSLogEnumerator 
OSLogMessageComponent
OSLogPosition
OSLogStore

**macOS**
The above selectors will also not be available in macOS in addition to:
OSLogStore::localStoreAndReturnError:

**Comment by spouliot** [comment]
Xcode 12 GM removed iOS, tvOS and watchOS support for OSLog (back to macOS only)

**Comment by spouliot** [comment]
support added in `xcode12.2` branch
