### ISSUE TITLE
AVFoundation.AVAudioSourceNodeRenderHandler delegate is incorrectly bound, causing a crash when it is used as a parameter to AVAudioSourceNode constructor

### ISSUE THREAD

**Issue by KumarKodali** [xamarin/xamarin-macios#9538]
### Steps to Reproduce

1. Create an instance of AVAudioSourceNode with AVAudioSourceNodeRenderHandler call back
2. Connect to AudioEngine's OutputNode using OutputNode's Bus 0 InputFormat
3. Start AudioEngine

### Expected Behavior
AVAudioSourceNodeRenderHandler delegate should be called for audio buffers.

Also, shouldn't AVAudioSourceNodeRenderHandler's isSilence parameter be a reference as AVAudioSourceNodeRenderBlock's isSilence parameter is a pointer to BOOL?

`public delegate int AVAudioSourceNodeRenderHandler (bool isSilence, AudioTimeStamp timestamp, uint frameCunt, ref AudioBuffers outputData);`

`typedef OSStatus (^AVAudioSourceNodeRenderBlock)(BOOL *isSilence, const AudioTimeStamp *timestamp, AVAudioFrameCount frameCount, AudioBufferList *outputData);`

### Actual Behavior

=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10dd0fa45 - /Users/kumarkodali/Library/Developer/CoreSimulator/Devices/7B82221D-E0F5-4A85-8974-555DD0F30BBF/data/Containers/Bundle/Application/B3C622FE-6F02-445A-8035-D50B455F7F59/AudioTest.app/AudioTest : mono_dump_native_crash_info
	0x10dd045a5 - /Users/kumarkodali/Library/Developer/CoreSimulator/Devices/7B82221D-E0F5-4A85-8974-555DD0F30BBF/data/Containers/Bundle/Application/B3C622FE-6F02-445A-8035-D50B455F7F59/AudioTest.app/AudioTest : mono_handle_native_crash
	0x10dd1633b - /Users/kumarkodali/Library/Developer/CoreSimulator/Devices/7B82221D-E0F5-4A85-8974-555DD0F30BBF/data/Containers/Bundle/Application/B3C622FE-6F02-445A-8035- D50B455F7F59/AudioTest.app/AudioTest : mono_sigsegv_signal_handler_debug
	0x7fff522ab5fd - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x7fc702d050c0 - Unknown
	0x10dd7197e - /Users/kumarkodali/Library/Developer/CoreSimulator/Devices/7B82221D-E0F5-4A85-8974-555DD0F30BBF/data/Containers/Bundle/Application/B3C622FE-6F02-445A-8035-D50B455F7F59/AudioTest.app/AudioTest : buffer_add_value_full
	0x10dd86e07 - /Users/kumarkodali/Library/Developer/CoreSimulator/Devices/7B82221D-E0F5-4A85-8974-555DD0F30BBF/data/Containers/Bundle/Application/B3C622FE-6F02-445A-8035-D50B455F7F59/AudioTest.app/AudioTest : add_var
	0x10dd7eee3 - /Users/kumarkodali/Library/Developer/CoreSimulator/Devices/7B82221D-E0F5-4A85-8974-555DD0F30BBF/data/Containers/Bundle/Application/B3C622FE-6F02-445A-8035-D50B455F7F59/AudioTest.app/AudioTest : frame_commands
	0x10dd7671c - /Users/kumarkodali/Library/Developer/CoreSimulator/Devices/7B82221D-E0F5-4A85-8974-555DD0F30BBF/data/Containers/Bundle/Application/B3C622FE-6F02-445A-8035-D50B455F7F59/AudioTest.app/AudioTest : debugger_thread
	0x10de7c723 - /Users/kumarkodali/Library/Developer/CoreSimulator/Devices/7B82221D-E0F5-4A85-8974-555DD0F30BBF/data/Containers/Bundle/Application/B3C622FE-6F02-445A-8035-D50B455F7F59/AudioTest.app/AudioTest : start_wrapper_internal
	0x10de7c56e - /Users/kumarkodali/Library/Developer/CoreSimulator/Devices/7B82221D-E0F5-4A85-8974-555DD0F30BBF/data/Containers/Bundle/Application/B3C622FE-6F02-445A-8035-D50B455F7F59/AudioTest.app/AudioTest : start_wrapper
	0x7fff522b7109 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_pthread.dylib : _pthread_start
	0x7fff522b2b8b - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_pthread.dylib : thread_start

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x10dd71c68):0x10dd71c58  c4 c8 00 00 00 5b 41 5c 41 5d 41 5e 41 5f 5d c3  .....[A\A]A^A_].
0x10dd71c68  4d 8b 7d 00 49 8b 4e 08 49 8b 46 10 48 89 c2 48  M.}.I.N.I.F.H..H
0x10dd71c78  29 ca 48 85 d2 7f 3d 49 8b 3e 29 f8 48 c1 e0 20  ).H...=I.>).H.. 
0x10dd71c88  48 bb 00 00 00 00 21 00 00 00 48 01 c3 48 c1 fb  H.....!...H..H..

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
### Environment

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.7.3 (build 13)
Installation UUID: 79be6188-aad6-46d9-bc7a-cfca875f0ce2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000090

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.90 (2020-02/d3daacdaa80) (64-bit)
	Package version: 612000090

=== Roslyn (Language Service) ===

3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.401/Sdks
SDK Versions:
	3.1.401
	3.1.302
	3.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.7
	3.1.6
	3.1.5
	2.1.21
	2.1.20
	2.1.19

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.20.2.2 (Visual Studio Enterprise)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-08-13 18:19:24 UTC

=== Android Device Manager ===

Version: 16.7.0.22
Hash: 576004d
Branch: remotes/origin/d16-7
Build date: 2020-08-13 18:19:46 UTC

=== Build Information ===

Release ID: 807030013
Git revision: 793cad2e5999f9797bc6bc71759f31e97f57d94a
Build date: 2020-08-13 12:22:13-04
Build branch: release-8.7
Xamarin extensions: 793cad2e5999f9797bc6bc71759f31e97f57d94a

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

```

### Build Logs

Building AudioTest (Debug|iPhoneSimulator)
Build started 8/27/2020 1:50:32 PM.
__________________________________________________
Project "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/AudioTest.csproj" (Build target(s)):

Target _CoreCompileInterfaceDefinitions:
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 13.6 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk --compilation-directory "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool" /Users/kumarkodali/Documents/src/AudioTest/AudioTest/LaunchScreen.storyboard
            
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 13.6 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk --compilation-directory "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool" /Users/kumarkodali/Documents/src/AudioTest/AudioTest/Main.storyboard
            
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool execution started with arguments: --errors --warnings --notices --output-format xml1 --minimum-deployment-target 13.6 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk --link "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link" "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool/LaunchScreen.storyboardc" "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool/Main.storyboardc"
            
      BundleResources Output:
        obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/Main.storyboardc/UIViewController-BYZ-38-t0r.nib
        obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib
        obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/Main.storyboardc/Info.plist
        obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib
        obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib
        obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/LaunchScreen.storyboardc/Info.plist
      OutputManifests Output:
        obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-manifests/LaunchScreen.storyboardc
        obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-manifests/Main.storyboardc
        obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-manifests/link
Target _BeforeCoreCompileImageAssets:
    Directory "obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/actool" doesn't exist. Skipping.
Target _CoreCompileImageAssets:
    Tool /Applications/Xcode.app/Contents/Developer/usr/bin/actool execution started with arguments: --errors --warnings --notices --output-format xml1 --output-partial-info-plist "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/actool/partial-info.plist" --app-icon AppIcon --compress-pngs --filter-for-device-model iPhone 11 Pro Max --filter-for-device-os-version 13.6 --target-device iphone --target-device ipad --minimum-deployment-target 13.6 --platform iphonesimulator --compile "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/actool/bundle" "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/actool/cloned-assets/Assets.xcassets"
            
Target _CoreCompileColladaAssets:
  Skipping target "_CoreCompileColladaAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCoreCompileSceneKitAssets:
  Skipping target "_BeforeCoreCompileSceneKitAssets" because it has no inputs.
Target _CoreCompileSceneKitAssets:
  Skipping target "_CoreCompileSceneKitAssets" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileTextureAtlases:
  Skipping target "_BeforeCompileTextureAtlases" because it has no inputs.
Target _CoreCompileTextureAtlases:
  Skipping target "_CoreCompileTextureAtlases" because it has no inputs.
Target _BeforeCompileCoreMLModels:
    Directory "obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/coremlc" doesn't exist. Skipping.
Target _CoreOptimizePngImages:
  Skipping target "_CoreOptimizePngImages" because it has no outputs.
Target _CoreOptimizePropertyLists:
  Skipping target "_CoreOptimizePropertyLists" because it has no inputs.
Target _CoreOptimizeLocalizationFiles:
  Skipping target "_CoreOptimizeLocalizationFiles" because it has no inputs.
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target CoreCompile:
    /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Roslyn/csc.exe /noconfig /nowarn:2008 /nostdlib+ /errorreport:prompt /warn:4 /define:__IOS__;__MOBILE__;__UNIFIED__;DEBUG /errorendlocation /preferreduilang:en-US /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/mscorlib.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/OpenTK-1.0.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Core.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Facades/System.Drawing.Common.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Numerics.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Numerics.Vectors.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/System.Xml.dll /reference:/Users/kumarkodali/.nuget/packages/xamarin.essentials/1.5.3.2/lib/xamarinios10/Xamarin.Essentials.dll /reference:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Xamarin.iOS.dll /debug+ /debug:full /optimize- /out:obj/iPhoneSimulator/Debug/AudioTest.exe /target:exe /utf8output /langversion:7.3 Main.cs AppDelegate.cs SceneDelegate.cs ViewController.cs ViewController.designer.cs "obj/iPhoneSimulator/Debug/Xamarin.iOS,Version=v1.0.AssemblyAttributes.cs"
    Using shared compilation with compiler from directory: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Roslyn
Target _CopyFilesMarkedCopyLocal:
    Copying file from "/Users/kumarkodali/.nuget/packages/xamarin.essentials/1.5.3.2/lib/xamarinios10/Xamarin.Essentials.dll" to "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/Xamarin.Essentials.dll".
    Copying file from "/Users/kumarkodali/.nuget/packages/xamarin.essentials/1.5.3.2/lib/xamarinios10/Xamarin.Essentials.pdb" to "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/Xamarin.Essentials.pdb".
    Creating "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/AudioTest.csproj.CopyComplete" because "AlwaysCreate" was specified.
Target CopyFilesToOutputDirectory:
    Copying file from "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/AudioTest.exe" to "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/AudioTest.exe".
    AudioTest -> /Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/AudioTest.exe
    Copying file from "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/AudioTest.pdb" to "/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/AudioTest.pdb".
Target _DetectSigningIdentity:
    Detected signing identity:
            
      Bundle Id: com.test.AudioTest
      App Id: com.test.AudioTest
Target _CopyResourcesToBundle:
    Creating directory '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/Main.storyboardc'
            
    Copying file from '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/Main.storyboardc/UIViewController-BYZ-38-t0r.nib' to '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/Main.storyboardc/UIViewController-BYZ-38-t0r.nib'
            
    Copying file from '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib' to '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib'
            
    Copying file from '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/Main.storyboardc/Info.plist' to '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/Main.storyboardc/Info.plist'
            
    Creating directory '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/LaunchScreen.storyboardc'
            
    Copying file from '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib' to '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib'
            
    Copying file from '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib' to '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib'
            
    Copying file from '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/ibtool-link/LaunchScreen.storyboardc/Info.plist' to '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/LaunchScreen.storyboardc/Info.plist'
            
    Copying file from '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/actool/bundle/AppIcon60x60@2x.png' to '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/AppIcon60x60@2x.png'
            
    Copying file from '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/actool/bundle/AppIcon76x76@2x~ipad.png' to '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/AppIcon76x76@2x~ipad.png'
            
    Copying file from '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/actool/bundle/Assets.car' to '/Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app/Assets.car'
            
Target _DetectDebugNetworkConfiguration:
      DebugIPAddresses: 127.0.0.1
Target _CompileAppManifest:
    Directory "bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app.dSYM" doesn't exist. Skipping.
Target _ParseExtraMtouchArgs:
      NoSymbolStrip Output: False
      NoDSymUtil Output: false
Target _CompileToNative:
    /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch "@/Users/kumarkodali/Documents/src/AudioTest/AudioTest/obj/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/response-file.rsp" 
    Xamarin.iOS 13.20.2.2 (d16-7): 817b6f72a using framework: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.6.sdk
    /Users/kumarkodali/Documents/src/AudioTest/AudioTest/bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/AudioTest.app built successfully.
    Creating "bin/iPhoneSimulator/Debug/device-builds/iphone 11 pro max-13.6/mtouch.stamp" because "AlwaysCreate" was specified.
Target _CopyAppExtensionsToBundle:
  Skipping target "_CopyAppExtensionsToBundle" because it has no inputs.
Target _CollectFrameworks:
    No Frameworks directory found.
            

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:13.63

========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Build successful.
### Example Project (If Possible)

[AudioTest.zip](https://github.com/xamarin/xamarin-macios/files/5138827/AudioTest.zip)

**Comment by whitneyschmidt** [comment]
@KumarKodali Thank you for your feedback! We were able to reproduce this locally and are working on a fix (you can see the linked issue above).

**Comment by KumarKodali** [comment]
@whitneyschmidt Thank you for taking time to look into this. I would also like to add that it also crashes in WatchOS 6.0+ as well.
