### ISSUE TITLE
Xamarin.iOS dll for iOS 14 changes not available

### ISSUE THREAD

**Issue by adityal** [xamarin/xamarin-macios#9579]
I am working on iOS14 changes in LocationManager framework in xamarin.iOS but I didn't find the changed api in LocationManager in current xamarin.iOS dll available publicly in visual studio for Mac . I need a Xamarin.iOS dll which contains the changed accuracy authorisation api's as per iOS 14 .
### Steps to Reproduce

1. 
2. 
3. 

### Environment
=== Visual Studio Community 2019 for Mac (Preview) ===

Version 8.8 Preview (8.8 build 1532)
Installation UUID: f43c7598-6c1f-4154-90ea-223d304fcfde
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000090

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.90 (2020-02/d3daacdaa80) (64-bit)
	Package version: 612000090

=== Roslyn (Language Service) ===

3.8.0-2.20410.4+2c664a69b93a3464f4422b2419c2868018450dde

=== NuGet ===

Version: 5.8.0.6753

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.401/Sdks
SDK Versions:
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	3.0.100-preview8-013656
	2.1.701
	2.1.700
	2.1.302
MSBuild SDKs: /Applications/Visual Studio (old).app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	3.0.0-preview8-28405-07
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.2

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.0.99.34 (Visual Studio Community)
Commit: xamarin-android/d16-8/49ba90e
Android SDK: /Users/aditya.aggarwal/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-8@a92fd18
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/aditya.aggarwal/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.14
Hash: 5b09caf
Branch: remotes/origin/HEAD
Build date: 2020-08-19 22:19:16 UTC

=== Android Device Manager ===

Version: 16.8.0.25
Hash: b5b938b
Branch: remotes/origin/master
Build date: 2020-08-19 22:19:38 UTC

=== Apple Developer Tools ===

Xcode 12.0 (17210.1)
Build 12A8189n

=== Xamarin.Mac ===

Version: 6.22.1.8 (Visual Studio Community)
Hash: 6f5adef8e
Branch: d16-8
Build date: 2020-07-29 02:26:57-0400

=== Xamarin.iOS ===

Version: 13.22.1.8 (Visual Studio Community)
Hash: 6f5adef8e
Branch: d16-8
Build date: 2020-07-29 02:26:58-0400

=== Xamarin Designer ===

Version: 16.8.0.228
Hash: 71e562541
Branch: remotes/origin/d16-8
Build date: 2020-08-14 04:05:14 UTC

=== Build Information ===

Release ID: 808001532
Git revision: 9371dc3f2c98f351acb45d90220f54f51021fc9c
Build date: 2020-08-20 10:54:43-04
Build branch: release-8.8
Xamarin extensions: 9371dc3f2c98f351acb45d90220f54f51021fc9c

=== Operating System ===

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

```
```

**Comment by adityal** [comment]
@rolfbjarne Could you please redirect me in right direction as I am not able to find the iOS 14 api changes in latest xamarin.iOS dll available in visual studio. for mac.

**Comment by whitneyschmidt** [comment]
@adityal Thank you for filing this issue :)

Our Xcode 12/iOS 14 update status can be found on our wiki here: https://github.com/xamarin/xamarin-macios/wiki/xcode12-Bindings-Status

It looks like the CoreLocation framework has been bound (you can view the linked PRs) and is available in the latest Xcode 12 preview of Xamarin.iOS. From the version information you've provided, you have a Xamarin.iOS dll based off d16-8, which does not contain Xcode 12 API updates.

Instructions to download the latest Xcode 12 preview and more details on the changes can be found in our release notes: https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.99

It's also possible that we missed an API or incorrectly updated something. If you are unable to find the APIs you are looking for after updating to the latest Xcode 12 preview, please let us know!

**Comment by adityal** [comment]
@whitneyschmidt Thank you so much!!

**Comment by adityal** [comment]
@whitneyschmidt I am not able to download the latest Xcode 12 preview from the link you shared . I would be thankful to you if you can share with me the xamarin.ios dll for iOS14 support.

**Comment by rolfbjarne** [comment]
@adityal can you try this package: [xamarin.ios-13.20.3.4.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/d16-7-xcode11.7/e3900927d46c9b13edefa5388abf3cc74e500839/6/package/notarized/xamarin.ios-13.20.3.4.pkg)? This is the upcoming release that contains support for Xcode 11.7, and OK for publishing apps to the App Store.

**Comment by adityal** [comment]
@rolfbjarne Thanks for providing the package , but I was just looking for iOS 14 api changes more precisely Core Location api changes. I would be grateful to you if you can help me to get the dll containing the iOS 14 changes .

**Comment by rolfbjarne** [comment]
@adityal ah, sorry, I got confused. You can select the Xcode 12 Preview channel in Visual Studio for Mac where you check for updates (you'll have to sign in first, otherwise the preview channel won't show up).

Have in mind that Apple does not yet allow publishing apps to the App Store with apps built with Xcode 12, there's no way around this requirement until Apple allows it.

**Comment by adityal** [comment]
@rolfbjarne Thank you so much for guiding me in right direction, I got the xamarin.ios dll compatible with Xcode 12 preview channel.

**Comment by rolfbjarne** [comment]
OK, I'm closing this then.
