### ISSUE TITLE
Xcode 12 Preview Channel not shown

### ISSUE THREAD

**Issue by t9mike** [xamarin/xamarin-macios#9590]
### Steps to Reproduce
[edit: this issue is present if I am logged out of Visual Studio for Mac ] 

Switch from Preview channel to Stable. Update. Let restart. Still no Xcode 12 Preview channel. Only preview. This on two different Macs. I rebooted one. No dice. I downloaded the VS.NET for Mac installer and ran. It told me I was up-to-date.

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.7.4 (build 38)
Installation UUID: 560181d5-e6ce-41bf-9175-9c583156a838
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000090

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.90 (2020-02/d3daacdaa80) (64-bit)
	Package version: 612000090

=== Roslyn (Language Service) ===

3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.401/Sdks
SDK Versions:
	3.1.401
	3.1.302
	3.1.301
	3.1.200
	3.1.101
	3.1.100
	3.0.100
	2.1.701
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.7
	3.1.6
	3.1.5
	3.1.2
	3.1.1
	3.1.0
	3.0.0
	2.1.21
	2.1.20
	2.1.19
	2.1.16
	2.1.15
	2.1.13
	2.1.12

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Apple Developer Tools ===

Xcode 12.0 (17210.1)
Build 12A8189n

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 13.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-08-19 22:18:28 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-08-19 22:18:52 UTC

=== Build Information ===

Release ID: 807040038
Git revision: 7f322926a2e0a5fa0c1e3833215a191883f7514a
Build date: 2020-08-20 10:10:20-04
Build branch: release-8.7
Xamarin extensions: 7f322926a2e0a5fa0c1e3833215a191883f7514a

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Sun Jul  5 00:43:10 PDT 2020
    root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64

**Comment by rolfbjarne** [comment]
Did you log in in Visual Studio for Mac? The Xcode 12 preview channel only shows up for me if I'm logged in.

**Comment by t9mike** [comment]
That did if @rolfbjarne. Thank you! I hope this is kept open as it is a bug. I have Enterprise but get logged out, never need Enterprise features on Mac, and therefore do not notice. Everything else runs fine logged out.

**Comment by Difegue** [comment]
This should probably be mentioned in https://github.com/xamarin/xamarin-macios/issues/8931 at least, as I wandered for a little while without figuring out why the Preview branch wasn't showing up on my VSMac install. Thanks!

**Comment by rolfbjarne** [comment]
> This should probably be mentioned in #8931 at least

I've modified the text a bit to note that you have to log in to see the preview channel.

I'm closing this issue since it seems things are working for you now.

**Comment by t9mike** [comment]
@rolfbjarne  can you create ticket against VS for Mac that is should state in the Updates window:

> You must be logged in to see certain channels, including Xcode Previews (when available)

Someone should not have to notice blurb in another ticket to know this is a requirement.

**Comment by rolfbjarne** [comment]
> @rolfbjarne can you create ticket against VS for Mac that is should state in the Updates window:
> 
> > You must be logged in to see certain channels, including Xcode Previews (when available)
> 
> Someone should not have to notice blurb in another ticket to know this is a requirement.

The best way to get this to the VS for Mac team would be for you to file an issue here: https://developercommunity.visualstudio.com/spaces/41/index.html

**Comment by jamescoverdale** [comment]
I'm having the same problem, is the Xcode 12 channel still available?

Visual Studio Mac: 8.8 Preview Build 2120

I've tried logging in with both a community account and a enterprise account, restarting the mac and visual studio numerous times, still only have the 'Stable' & 'Preview' channels available in the drop down.

**Comment by rolfbjarne** [comment]
Because Apple released Xcode 12 (as a stable release), we've also released support for Xcode 12 to our stable channel. This means that you should use the stable channel now for Xcode 12 support.
