### ISSUE TITLE
DER length is '63' and cannot be more than 4 bytes.

### ISSUE THREAD

**Issue by samosim** [xamarin/xamarin-macios#9591]
I wanted to pair a Windows machine with Mac one. After the last macOS Catalina update, I get the following error:

An unexpected error occurred while checking the SSH configuration of 'Samo'
DER length is '63' and cannot be more than 4 bytes.

### Environment
I am using Visual Studio version 16.7.2 on a windows machine and version 8.7.4 on mac machine.

```
```

### Example Project (If Possible)

> VS bug [#1197965](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1197965)

**Comment by rolfbjarne** [comment]
I've assigned the issue to the team responsible for our Visual Studio/Windows integration.

**Comment by samosim** [comment]
Thanks, rolfbjarne.  Where can I expect a reply to my question?

**Comment by mauroa** [comment]
Hi @samosim. macOS Catalina introduced some critical updates related to OpenSSH, which affected the way we communicate from VS to the Mac. In this case it looks like something is not well with your SSH keys and passphrase (VS generates them). I would suggest you to remove them and let VS to re-create it.
Please follow the next steps:

- Ensure VS is closed
- Delete the following files from the folder `%LOCALAPPDATA%\Xamarin\MonoTouch`: id_rsa, id_rsa.pub and passphrase.key
- Open VS and try to connect to the Mac again

Doing so VS will generate the SSH keys again and register them on your Mac. Hopefully this will unblock you.
Let me know how that goes.
Thanks.
