### ISSUE TITLE
[Bug] Error publishing watchOS app

### ISSUE THREAD

**Issue by jWalker92** [xamarin/xamarin-macios#9618]
### Description
Apple gives me this error when uploading an iOS App with a bundled watchOS app:

ITMS-90484: Invalid WatchKit Support - The WatchKitSupport2 folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

### Basic Information
- XCode Version: 11.7
- VS 2019 Version 16.7.3
- XF Version 4.8.0.1364

> VS bug [#1214349](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1214349)

**Comment by rolfbjarne** [comment]
Please provide a complete build log, as well as the .ipa you tried to upload. 

To get a complete build log:

1. Logs can be found in the Build Output tab of the Errors pad in Visual Studio. To get full build logs, set the log verbosity to diagnostic at the following locations:
- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run
On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.
2. Attach build log here or link to gist (https://gist.github.com/) of the log.

**Comment by jWalker92** [comment]
> > Rebuild your app using the current public (GM) version of Xcode and resubmit it.
> 
> have you tried this ?

Yes, 11.7 is the current GM according to https://xcodereleases.com/

**Comment by jWalker92** [comment]
https://gist.github.com/jWalker92/155e79053bad68f1144ce0a6e43892d6

@rolfbjarne what service is preferred for uploading the IPA?

**Comment by rolfbjarne** [comment]
@jWalker92 

> @rolfbjarne what service is preferred for uploading the IPA?

Whatever is easiest for you as long as we can download it. Dropbox is pretty common, but there are plenty of other services.

**Comment by jWalker92** [comment]
@rolfbjarne https://www.dropbox.com/s/fuz42lb0rqubzkv/VrhealthLife.iOS.ipa?dl=0 that work?

**Comment by rolfbjarne** [comment]
@jWalker92 Yes, that works, I'll have a look next week since it's getting late here.

**Comment by rolfbjarne** [comment]
This might be something that happens when building from Windows.

@jWalker92 can you try building using Visual Studio for Mac, and see if the resulting .ipa contains a `WatchKitSupport2/WK` file? The .ipa is just a zip file, so you can view the contents using any tool that can look into zip files.

**Comment by jWalker92** [comment]
![image](https://user-images.githubusercontent.com/4966636/93145995-0b45e200-f6ee-11ea-9c3c-2655b9924dc0.png)
Can confirm, VS-Mac creates the ipa correctly, whereas VS-Windows does not. So workaround is publishing on the Mac.

**Comment by rolfbjarne** [comment]
@jWalker92 ok, thanks for confirming that. I've assigned this to the team responsible for Xamarin.iOS on VS/Windows.

**Comment by grantkiwi** [comment]
Any workaround for this using Xamarin on Windows

**Comment by grantkiwi** [comment]
Hi this was logged a month ago, we cannot update our watch app.  Is there an ETA?

**Comment by chucker** [comment]
Was this closed because there’s a fix, or because there never will be one?
