### ISSUE TITLE
[tvos] Top shelf extension crashes on device after going through TestFlight

### ISSUE THREAD

**Issue by szymonkalista** [xamarin/xamarin-macios#9622]
We are experiencing a problem with the top shelf extension for tvOS.

The extension runs as expected on a simulator and on a device when it's deployed from visual studio.
However, when the same application with extension is obtained from TestFlight it crashes just after launching - when application expands to fullscreen.

Ipa bundling and uploading is done through VS archive feature. Both container app and extension are signed with correct provisioning profile. The same goes for Azure pipeline that is used for release.

When the reference to the top shelf extension is removed from the tvOS app, the application works as expected.

Attached sample can be uploaded to TestFlight after adjusting bundle id and version to match your provisioning profiles.

When Xcode is used to create a native sample it works as alright.
### Steps to Reproduce

1. Build attached sample project.
2. Pass the application through TestFlight.
3. Install application on an Apple TV through TestFlight.
4. Launch application on an Apple TV.

### Expected Behavior
Application launches properly and top shelf extension is working without crashing.

### Actual Behavior
Application crashes at startup.

### Environment

```
=== Visual Studio Community 2019 for Mac ===
 

Version 8.6.8 (build 2)

Installation UUID: ebcc26e7-1edd-487c-a379-8480dc58bdb9

GTK+ 2.24.23 (Raleigh theme)

Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

 

Package version: 610000106

 

=== Mono Framework MDK ===

 

Runtime:

Mono 6.10.0.106 (2019-12/77769615db1) (64-bit)

Package version: 610000106

 

=== Roslyn (Language Service) ===

 

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

 

=== NuGet ===

 

Version: 5.6.0.6591

 

=== .NET Core SDK ===

 

SDK: /usr/local/share/dotnet/sdk/3.1.302/Sdks

SDK Versions:

3.1.302

3.1.301

3.1.300

3.1.200

MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

 

=== .NET Core Runtime ===

 

Runtime: /usr/local/share/dotnet/dotnet

Runtime Versions:

3.1.6

3.1.5

3.1.4

3.1.2

2.1.20

2.1.19

2.1.18

2.1.16

 

=== Xamarin.Profiler ===

 

Version: 1.6.13.11

Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

 

=== Updater ===

 

Version: 11

 

=== Apple Developer Tools ===

 

Xcode 11.7 (16142)

Build 11E801a

 

=== Xamarin.Mac ===

 

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

 

=== Xamarin.iOS ===

 

Version: 13.18.3.2 (Visual Studio Community)

Hash: ce0cc74a3

Branch: d16-6-xcode11.6

Build date: 2020-07-16 18:15:27-0400

 

=== Xamarin Designer ===

 

Version: 16.6.0.329

Hash: d4f8bcd13

Branch: remotes/origin/d16-6

Build date: 2020-04-24 02:16:02 UTC

 

=== Xamarin.Android ===

 

Version: 10.3.1.4 (Visual Studio Community)

Commit: xamarin-android/d16-6/3a10de9

Android SDK: /Users/mkrzywda/Library/Developer/Xamarin/android-sdk-macosx

Supported Android versions:

None installed

 

SDK Tools Version: 26.1.1

SDK Platform Tools Version: 29.0.5

SDK Build Tools Version: 29.0.2

 

Build Information: 

Mono: 165f4b0

Java.Interop: xamarin/java.interop/d16-6@2cab35c

ProGuard: xamarin/proguard/master@905836d

SQLite: xamarin/sqlite/3.31.1@49232bc

Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

 

=== Microsoft OpenJDK for Mobile ===

 

Java SDK: /Users/mkrzywda/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25

1.8.0-25

Android Designer EPL code available here:

https://github.com/xamarin/AndroidDesigner.EPL

 

=== Android SDK Manager ===

 

Version: 16.6.0.50

Hash: 5901879

Branch: remotes/origin/d16-6

Build date: 2020-06-10 22:42:50 UTC

 

=== Android Device Manager ===

 

Version: 16.6.0.96

Hash: 6e8b80b

Branch: remotes/origin/d16-6

Build date: 2020-06-10 22:43:28 UTC

 

=== Build Information ===

 

Release ID: 806080002

Git revision: e999e2934e8c771fdf6494b80361dacef9427565

Build date: 2020-07-24 15:17:52-04

Build branch: release-8.6

Xamarin extensions: e999e2934e8c771fdf6494b80361dacef9427565

 

=== Operating System ===

 

Mac OS X 10.15.6

Darwin 19.6.0 Darwin Kernel Version 19.6.0

  Thu Jun 18 20:49:00 PDT 2020

  root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

 

=== Enabled user installed extensions ===

 

Visual Studio for Mac Extension for Tizen 1.1
```

### Build Logs

https://gist.github.com/szymonkalista/9828ad8d6ba62ab701adbaedf3dd64b4
### Example Project (If Possible)

[TopTest.zip](https://github.com/xamarin/xamarin-macios/files/5209076/TopTest.zip)

**Comment by rolfbjarne** [comment]
Can you try adding `--nodevcodeshare` to the additional mtouch arguments for both the extension project and the main project and see if that fixes the issue?

Also, when you were testing locally, did you test the Release configuration, or the Debug configuration?

**Comment by szymonkalista** [comment]
Sure, I'll try that and I'll let you know, thanks!

Release and Debug configurations were tested, both present the same behaviour.

**Comment by rolfbjarne** [comment]
Do you get any crash reports when the app crashes? You can find crash reports in Xcode (open Xcode, Window -> Devices and Simulators, select your device on the left and then "View Device Logs"). Getting the console output from the apple tv when the app tries to launch would also be nice (you can see the console output from the same Devices and Simulators window, by clicking "Open Console")

**Comment by szymonkalista** [comment]
Device logs: "In device logs there is no entry dated today". Checked few times after crashing the application.

Console output: https://gist.github.com/szymonkalista/e51c48bc7a58aa40fd1bad1653736927

Bundle id is in the form of tv.XXX.app where XXX is a string without any special characters or numbers.

**Comment by rolfbjarne** [comment]
Looks like there should have been a crash report (https://gist.github.com/szymonkalista/e51c48bc7a58aa40fd1bad1653736927#file-console-output-L1569)

    default	14:44:39.710988+0200	ReportCrash	Formulating fatal report for corpse[209] TopShelf

and

    default	14:44:39.743062+0200	osanalyticshelper	Saved type '109(<private>)' report (3 of max 25) at /private/var/mobile/Library/Logs/CrashReporter/TopShelf-2020-09-16-144439.ips.beta

maybe it was sent to test flight? (https://gist.github.com/szymonkalista/e51c48bc7a58aa40fd1bad1653736927#file-console-output-L1586-L1587)

    default	14:44:39.751229+0200	ReportCrash	Sending event: com.apple.stability.crash {"appVersion":"1.0","bundleID":"tv.xxxxxxxx.app.topshelf","exceptionCodes":"0x0000000000000000, 0x0000000000000000","logwritten":1,"process":"TopShelf","terminationReasonExceptionCode":"0x1","terminationReasonNamespace":"DYLD"}
    default	14:44:39.751720+0200	analyticsd	Received event: com.apple.stability.crash {"appVersion":"1.0","bundleID":"tv.xxxxxxxx.app.topshelf","exceptionCodes":"0x0000000000000000, 0x0000000000000000","logwritten":1,"process":"TopShelf","terminationReasonExceptionCode":"0x1","terminationReasonNamespace":"DYLD"}

In any case, would it be possible to get access to the .ipa you uploaded to TestFlight?

**Comment by szymonkalista** [comment]
In iTunesConnect when navigated to Test flight -> tvOS -> Crashes I have no option to select tvOS related devices, versions etc. Only iOS related information is available. 

Sure, you can get the .ipa from here. We used this one to check whether clean project would cause the same issue:
https://stagebtvassetstorage.blob.core.windows.net/mobile/TopTest.ipa

Thanks for such a quick responses!

**Comment by rolfbjarne** [comment]
I can reproduce after publishing to test flight, and I think I know what's going on.

In any case, adding `--mono:static --nodevcodeshare` to both the main project's and the extension project's additional mtouch arguments works around the crash for me.

**Comment by rolfbjarne** [comment]
This is the significant part of the crash report:

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, dependent dylib '/Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/sdks/out/ios-targettv-release/lib/libmonosgen-2.0.1.dylib' not found for '/private/var/containers/Bundle/Application/EEA4419A-FE32-4321-A0A9-AED951F6F99F/TopTest.app/TopTest', tried but didn't find: '/Users/builder/jenkins/workspace/archive-mono/2020-02/ios/release/sdks/out/ios-targettv-release/lib/libmonosgen-2.0.1.dylib' '/usr/local/lib/libmonosgen-2.0.1.dylib' '/usr/lib/libmonosgen-2.0.1.dylib'
Highlighted by Thread:  0
```

the my guess is that the reason it only happens on TestFlight and not locally, is because the TestFlight version has been re-compiled from bitcode.

**Comment by szymonkalista** [comment]
Thanks!

After adding these arguments, the crash no longer occurs.

**Comment by rolfbjarne** [comment]
This is no longer an issue in .NET.
