### ISSUE TITLE
Failed to compile the generated registrar code

### ISSUE THREAD

**Issue by rlasker-b2w** [xamarin/xamarin-macios#9673]
### Steps to Reproduce

1. Attempt to deploy debug code to a physically attached device from Visual Studio for Mac
2. Physical device is an iPhone 8 with 13.7
3. Code deploys to Simulators fine.

### Expected Behavior
App launches

### Actual Behavior
Get error: MTOUCH: Error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new (MT4109)

### Environment

```
Visual Studio Enterprise 2019 for Mac
Version 8.7.7 (build 10)
Installation UUID: 4a3c058b-f288-4f26-8fff-7a6a591ed523
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

Mono Framework MDK
Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

Roslyn (Language Service)
3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

NuGet
Version: 5.7.0.6702

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	2.1.701
	2.1.700
	2.1.505
	2.1.302
	2.1.301
	2.1.200
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	2.1.22
	2.1.16
	2.1.15
	2.1.14
	2.1.12
	2.1.11
	2.1.9
	2.1.2
	2.1.1
	2.0.7

Xamarin.Profiler
Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 12.0 (17219)
Build 12A7209

Xamarin.Mac
Version: 6.20.2.2 (Visual Studio Enterprise)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

Xamarin.iOS
Version: 13.20.2.2 (Visual Studio Enterprise)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

Xamarin Designer
Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

Xamarin.Android
Version: 11.0.2.0 (Visual Studio Enterprise)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/richardlasker/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Microsoft OpenJDK for Mobile
Java SDK: /Users/richardlasker/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-08-19 22:18:28 UTC

Android Device Manager
Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-08-19 22:18:52 UTC

Build Information
Release ID: 807070010
Git revision: e58142243407a357198d18ee1a37b1e67a702eff
Build date: 2020-09-10 11:48:02-04
Build branch: release-8.7
Xamarin extensions: e58142243407a357198d18ee1a37b1e67a702eff

Operating System
Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

### Build Logs

https://gist.github.com/rlasker-b2w/d26d8bbd5f607f7490a2bee1081b126c

**Comment by rolfbjarne** [comment]
You're using Xcode 12 (which was released last week):

> Apple Developer Tools
> Xcode 12.0 (17219)
> Build 12A7209

while using Xamarin.iOS 13.20.2.2 (which was released a while ago):

> Xamarin.iOS
> Version: 13.20.2.2 (Visual Studio Enterprise)
> Hash: 817b6f72a
> Branch: d16-7
> Build date: 2020-07-18 18:45:00-0400

and unfortunately these two versions are not compatible.

We're going to release a version of Xamarin.iOS which is compatible with Xcode 12 in the upcoming days.

If you don't want to or can't wait, there are a couple of options:

* Install the previous version of Xcode 11.7 (you can download it from [Apple](https://developer.apple.com/download/more/)).
* Install the preview version of Xamarin.iOS 14 (either from the preview channel in Visual Studio, or the latest daily package: [xamarin.ios-14.0.0.3.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode12.2/4028e53d9844b534d384dfe7b2d28355de9f69f1/1/package/notarized/xamarin.ios-14.0.0.3.pkg)).

**Comment by rlasker-b2w** [comment]
@rolfbjarne Thank you for the Xamarin.IOS 14 preview I am able to deploy to my device now. Out of curiosity, why does it deploy to a Simulator and not a physical device?
