### ISSUE TITLE
Xamarin.iOS Compiletime Error After update to latest version

### ISSUE THREAD

**Issue by NiladriPadhy** [xamarin/xamarin-macios#9678]
Dear Team,

Recently I have updated Visual Studio, Xcode and ios Command line tools. After update iOS app is not compiling, showing below error.

/.../obj/iPhoneSimulator/Debug/device-builds/iphone 11-14.0/mtouch-cache/registrar.m(4,4): Error GBDAA8BF8: cannot find protocol declaration for 'NSFileProviderItemDecorating' (GBDAA8BF8) (thebigword.iOS)

/.../obj/iPhoneSimulator/Debug/device-builds/iphone 11-14.0/mtouch-cache/registrar.m(4,4): Error GBDAA8BF8: cannot find protocol declaration for 'NSFileProviderItemFlags' (GBDAA8BF8) (thebigword.iOS)

/.../MTOUCH: Error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new (MT4109) (thebigword.iOS)

Please look into this error.

Thanks
Niladri

**Comment by rolfbjarne** [comment]
You're most likely using Xcode 12 (which was released last week), while using Xamarin.iOS 13.20.2.2 (which was released a while ago), and unfortunately these two versions are not compatible.

We're going to release a version of Xamarin.iOS which is compatible with Xcode 12 in the upcoming days.

If you don't want to or can't wait, there are a couple of options:

* Install the previous version of Xcode 11.7 (you can download it from [Apple](https://developer.apple.com/download/more/)).
* Install the preview version of Xamarin.iOS 14 (either from the preview channel in Visual Studio, or the latest daily package: [xamarin.ios-14.0.0.3.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode12.2/4028e53d9844b534d384dfe7b2d28355de9f69f1/1/package/notarized/xamarin.ios-14.0.0.3.pkg)).

**Comment by VictorKochetkov** [comment]
Latest version of Visual Studio from preview channel NOT working :(

**Comment by NiladriPadhy** [comment]
Thanks @rolfbjarne for quick help. I have installed 11.7 and referenced in Visual Studio. Now I am able to compile and run the code without any issues.

**Comment by NiladriPadhy** [comment]
> Latest version of Visual Studio from preview channel NOT working :(

In Visual Studio Mac Preview channelm, Xamarin.iOS 14 is not available. Install the latest daily package: [xamarin.ios-14.0.0.3.pkg](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/xcode12.2/4028e53d9844b534d384dfe7b2d28355de9f69f1/1/package/notarized/xamarin.ios-14.0.0.3.pkg). Or Install XCode 11.7 from App Store. 

Rather than installing xamarin ios from preview channel, install additionally xcode 11.7 along with latest version. I think this will be the good approach as a temporary solution. When Xamarin.ios 14 will be released, we can refer back to Xcode 12. And I followed the same approach and now I am able to compile and run the code without having any issues.
