### ISSUE TITLE
[Xcode12] Re-enable Xamarin.Mac

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#9680]
Xamarin.Mac was disabled after the last GM because Apple removed a number of headers that got found, probably this headers will be re-added, At that point we need to re-enabled the build changing:

https://github.com/xamarin/xamarin-macios/pull/9672/files#diff-f682ea58f8badb13b9f8ed17cda4deb7R184

**Comment by rolfbjarne** [comment]
Xamarin.Mac has been re-enabled, so this can be closed.
