### ISSUE TITLE
Archive path encoding bug

### ISSUE THREAD

**Issue by LITTOMA** [xamarin/xamarin-macios#9683]
### Steps to Reproduce

1. Create a Xamarin.iOS project
2. Build the project
3. Archive the project.

### Expected Behavior
Successfully archived.

### Actual Behavior
Archive failed. Chinese characters in the archive folder path encoded in the wrong way.

### Environment
Windows 10 with **zh-CN language**.
Visual Studio 2019 with **Chinese interface**.

**Comment by rolfbjarne** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs and all your version information.

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

The easiest way to get exact version information:

- On Visual Studio for Mac: "Visual Studio" menu, "About Visual Studio" item, "Show Details" button.
- On Visual Studio for Windows: "Help menu", "About Microsoft Visual Studio" item.

Then copy/paste the version information (you can use the "Copy Information" button).

We look forward to hearing from you!

**Comment by tj-devel709** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
