### ISSUE TITLE
Xharness cannot be executed from VSMac

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/xamarin-macios#9716]
Using main with hash the following error occurs:

```
/usr/local/share/dotnet/sdk/5.0.100-rc.2.20459.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(5,5): Error MSB4186: Invalid static method invocation syntax: "[MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')". Method '[MSBuild]::GetTargetFrameworkIdentifier' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)). Check that all parameters are defined, are of the correct type, and are specified in the right order. (MSB4186) (Microsoft.DotNet.XHarness.iOS.Shared)
```
I built the project with ./configure --enable-dotnet to see if that fixed the issue.

**Comment by rolfbjarne** [comment]
It works for me. Can you attach the full build log/error? And which VSM version do you have?

**Comment by mandel-macaque** [comment]
I have modified the version I have of vsmac, we get:

* Version 8.8 Preview (8.8 build 2120) - **Success** [Full env info](https://gist.github.com/mandel-macaque/8ac668395e6abbc789bb1ae716f11bc4)
* Version 8.7.8 (build 4) - **Failure** [Full env info](https://gist.github.com/mandel-macaque/beea610c674f1c93955174d8813e816f)

There is no more than the following
```
Error: Unable to create package spec for project. '/Users/mandel/Xamarin/xamarin-macios/master/xamarin-macios/tests/xharness/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests.csproj'. Please see the Package Console for more details.
```

**Comment by rolfbjarne** [comment]
This seems to be working now.
