### ISSUE TITLE
Connectivity to macmini using visual studio 2019 16.7.5 error

### ISSUE THREAD

**Issue by developer9969** [xamarin/xamarin-macios#9742]
Hi 
We cannot longer connect to our mac mini and we get the following error
![image](https://user-images.githubusercontent.com/16970109/94719263-dae78000-034a-11eb-8736-daa39492db83.png)

We use Visual Studio to do all the xamarin forms development  connecting  to the macmini using the following software

- Visual studio 2019 16.7.5
- MacMini
- macOS Catalina 10.15.6
- Xcode 12.0.1
- Visual studio for mac   8.7.8 (build 4)
- Xamarin.iOS 14.0.0.0

Any suggestions on why is this happening? it was working before the upgrade to the latest visual studio.

We had to install xCode 12 as Visual studio was not happy about it.

At times when trying to add the mac I get same issue as 
https://forums.xamarin.com/discussion/185273/cannot-pair-vs-to-mac-access-a-socket-in-a-way-forbidden

![image](https://user-images.githubusercontent.com/16970109/94723608-eb025e00-0350-11eb-97d2-22fbdd4ad588.png)

thanks for any input

> VS bug [#1223858](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1223858)

**Comment by mauroa** [comment]
Hi.
Thanks for your feedback. 
I need to get more details about the SSH configuration issue that is preventing the connection to succeed.
Could you please start VS with the `/log` argument (devenv.exe /log), try to connect again and then attach the VS log (Ide.log)? You can get the log by doing `Help > Xamarin > Zip Logs...`.
Thanks.

**Comment by developer9969** [comment]
Hi there, 
I have the logs but not sure where to email it to, I would rather not attach. Below is an extract.
Wondering if this gives you any clue?


System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs16180Gabri - Dispatching PublishAck message to flow PublishSenderFlow
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from DisconnectingState to DisconnectedState on 10.80.4.32 (10.80.4.32)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting disconnection from 10.80.4.32...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|The connection to '10.80.4.32' has been finished
Xamarin.Messaging.Integration.State.ServerStateContext|Error|0|An unexpected error occurred while checking the SSH configuration of '10.80.4.32'
System.ArgumentException: username
   at Renci.SshNet.AuthenticationMethod..ctor(String username)
   at Xamarin.Messaging.Integration.State.ConfiguringState.<VerifySshKeysAsync>d__16.MoveNext() in C:\A\1\62\s\External\messaging\src\Xamarin.Messaging.Integration\State\ConfiguringState.cs:line 218
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Xamarin.Messaging.Integration.State.ConfiguringState.<CheckHostConfigurationAsync>d__15.MoveNext() in C:\A\1\62\s\External\messaging\src\Xamarin.Messaging.Integration\State\ConfiguringState.cs:line 150
Xamarin.VisualStudio.Android.Setup.AndroidSdkSetup|Information|0|androidsdksetup: verify error: 
System.Net.Mqtt.Sdk.ClientPacketListener|Information|0|Client vs16180Gabri - Dispatching Publish message to flow PublishReceiverFlow and topic vs16180Gabri/response/xma/ping/Broker167000452

**Comment by mauroa** [comment]
Thanks @developer9969,
Looks like something is wrong with the SSH credentials and key used to authenticate to the Mac. I would suggest you to let VS re-create and register them into the Mac, so we can discard any noise with your keys and your Mac. To do so, please remove the following files from `%LOCALAPPDATA%\Xamarin\MonoTouch`: id_rsa, id_rsa.pub and passphrase.key.
Please ensure to close VS first and then after deleting the files open VS and try again.

In case you still have issues please email me the Ide.log at maagno@microsoft.com and we can follow up in there.
Thanks for your help.

**Comment by developer9969** [comment]
Hi there thanks for your reply I have removed those files but the issue still persist.
I have even reinstalled visual studio but nothing.
I have sent you the ide.log at the address provided. Very grateful if you could have a look. Any other file I can delete?

**Comment by developer9969** [comment]
Hi there, I still cannot use the macmini on my laptop. any suggestions or to reset it if you like? Do I have to format my laptop to factory settings? Pretty drastic but not sure what todo
