### ISSUE TITLE
Not deploying on simulator (13.5 - 14.0) while no issues on real device (14.0) [iOS]

### ISSUE THREAD

**Issue by erlandvr** [xamarin/xamarin-macios#9777]
### Steps to Reproduce

1. deploy app on simulator
2. 
3. 

### Expected Behavior
app opens in simulator

### Actual Behavior
simulator is open, build succeeded
-> 
```
Cannot execute Users/.../bin/iPhoneSimulator/Development.../...iOS.exe
```
### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.7.8 (build 4)
Installation UUID: c81dfd88-2309-445c-8c44-078e27d986c5
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.401
	3.1.302
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.300
	2.2.104
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.7
	3.1.6
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.5
	2.2.2
	2.1.22
	2.1.21
	2.1.20
	2.1.18
	2.1.17
	2.1.15
	2.1.14
	2.1.13
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.0.5

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.0.1 (17220)
Build 12A7300

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/erland/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/erland/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Build Information ===

Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

=== Operating System ===

Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64


```

**Comment by chamons** [comment]
Thank you for your feedback!

For us to investigate this further, could you please provide your full build logs, crash reports (if any), and test case (to reproduce).

To get full build logs just set the log verbosity to diagnostic at the following locations:

- On Visual Studio for Mac: Preferences > Projects > Build
- On Visual Studio for Windows: Tools > Options > Projects and Solutions > Build and Run

On Visual Studio for Windows you also want to add `-v -v -v -v` to the mtouch additional arguments by right-clicking the project in the solution explorer and selecting `Properties`.

Note: this is done automatically on Visual Studio for Mac when the log verbosity is set to diagnostic.

We look forward to hearing from you!

**Comment by erlandvr** [comment]
I have been having this problem since updating to the xcode 12 preview channel.
In the mean while I have deleted all simulators and reinstalled all simulators, switched to stable and reinstalled xcode. 
I see no errors when deploying. If I manually drag the app into my simulator. I get an app icon that closes immediately after opening. 

I know the app is not the problem, because I am currently the only member of my team having this issue.

**Comment by erlandvr** [comment]
I've put the diagnostic build log here:
https://gist.github.com/erlandvr/7e7a352b2d3c836466d6a1a6d14010fd

**Comment by chamons** [comment]
@erlandvr - Thanks for the build log, I don't see anything obvious in it to explain the deployment errors.

Could you attach the IDE logs from: 
https://docs.microsoft.com/en-us/visualstudio/mac/troubleshooting?view=vsmac-2019#viewing-logs-in-visual-studio-for-mac

And see if you can dig up the simulator logs here:
https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/version-logs#ios-simulator-logs-on-mac

It is not clear yet if it's an issue in Visual Studio for Mac or an issue with the Xcode on your system.

**Comment by erlandvr** [comment]
I can't explain why, but while getting the extra logs; my simulators appear to be working. After at least one month of not working, the issue appears to be resolved without doing any manual change. ¯\_(ツ)_/¯ Thanks for all the help though, I appreciate it.

**Comment by chamons** [comment]
Strange @erlandvr but not unheard of. I'm going to close this for now. 

Please open a new issue with logs if it appears again.
