### ISSUE TITLE
Pipeline Build Fails When Specifying Xamarin.iOS 14.0.0.0 Version

### ISSUE THREAD

**Issue by Axemasta** [xamarin/xamarin-macios#9832]
### Steps to Reproduce

1. Create a Xamarin Forms app targeting iOS 14
2. Create an Azure Build Pipeline
3. Use the [Boots](https://github.com/jonathanpeppers/boots) task in the pipeline before the Xamarin.iOS build task, target the following version: Xamarin.iOS, d16-7 14.0.0.0 ([pkg link](https://download.visualstudio.microsoft.com/download/pr/c939bb72-556b-4e8a-a9b4-0f90e9b5e336/f906a6ce183fb73f1bcd945ac32f984b/xamarin.ios-14.0.0.0.pkg), [docs link](https://github.com/xamarin/xamarin-macios#Downloads))
```
https://download.visualstudio.microsoft.com/download/pr/c939bb72-556b-4e8a-a9b4-0f90e9b5e336/f906a6ce183fb73f1bcd945ac32f984b/xamarin.ios-14.0.0.0.pkg
```
4. The iOS build fails with the following error:
**...is not available in iOS 13.7 (it was introduced in iOS 14.0). Please build with a newer iOS SDK...**
```
"/Users/runner/work/1/s/src/MyApp.sln" (default target) (1) ->
"/Users/runner/work/1/s/src/MyApp/MyApp.iOS/MyApp.iOS.csproj" (default target) (9) ->
(_CompileToNative target) -> 
  /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UISplitViewController.g.cs(1208): error MT4162: The type 'UIKit.UISplitViewControllerColumn' (used as a return type in UIKit.UISplitViewController/_UISplitViewControllerDelegate.GetTopColumnForCollapsing) is not available in iOS 13.7 (it was introduced in iOS 14.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode). [/Users/runner/work/1/s/src/MyApp/MyApp.iOS/MyApp.iOS.csproj]
  /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UISplitViewController.g.cs(1208): error MT4162: The type 'UIKit.UISplitViewControllerColumn' (used as a parameter in UIKit.UISplitViewController/_UISplitViewControllerDelegate.GetTopColumnForCollapsing) is not available in iOS 13.7 (it was introduced in iOS 14.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode). [/Users/runner/work/1/s/src/MyApp/MyApp.iOS/MyApp.iOS.csproj]
  /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UISplitViewController.g.cs(1286): error MT4162: The type 'UIKit.UISplitViewControllerColumn' (used as a parameter in UIKit.UISplitViewController/_UISplitViewControllerDelegate.WillHideColumn) is not available in iOS 13.7 (it was introduced in iOS 14.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode). [/Users/runner/work/1/s/src/MyApp/MyApp.iOS/MyApp.iOS.csproj]
  /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UISplitViewController.g.cs(1322): error MT4162: The type 'UIKit.UISplitViewControllerColumn' (used as a parameter in UIKit.UISplitViewController/_UISplitViewControllerDelegate.WillShowColumn) is not available in iOS 13.7 (it was introduced in iOS 14.0). Please build with a newer iOS SDK (usually done by using the most recent version of Xcode). [/Users/runner/work/1/s/src/MyApp/MyApp.iOS/MyApp.iOS.csproj]
```

### Expected Behavior

The app is built successfully with the iOS 14.0.0.0 SDK

### Actual Behavior

An error occurs when building the app
```
[/Users/runner/work/1/s/src/MyApp/MyApp.iOS/MyApp.iOS.csproj]
  /Library/Frameworks/Xamarin.iOS.framework/Versions/14.0.0.0/src/Xamarin.iOS/UIKit/UISplitViewController.g.cs(1286): 
  error MT4162: The type 'UIKit.UISplitViewControllerColumn' 
  (used as a parameter in UIKit.UISplitViewController/_UISplitViewControllerDelegate.WillHideColumn) 
  is not available in iOS 13.7 (it was introduced in iOS 14.0). 
  Please build with a newer iOS SDK (usually done by using the most recent version of Xcode). 
```

The error seems to suggest that the version of Xamarin.iOS used does not support iOS 14 and instead is targeting iOS 13.7.

My Local version of Xamarin.iOS 14.0.0.0 appears to be different to the version available on this repoistories readme:

**Local VS Mac Version**
```
Xamarin.iOS
Version: 14.0.0.0 (Visual Studio Professional)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400
```

I might be installing the wrong version in the pipeline, are there multiple 14.0.0.0 versions available?

### Removing Boots

If I take boots out of the equation and don't specify the exact version of Xamarin.iOS to use, the build will succeed. However I want to use boots so that future updates to any SDK don't affect my build pipelines before I get the chance to update.

### Environment

Azure Pipeline, VMImage: `macos-latest`

### Build Logs

[pipeline build logs](https://github.com/xamarin/xamarin-macios/files/5353916/buildlog.zip)

**Comment by rolfbjarne** [comment]
From your build log:

> warning MT0079: The recommended Xcode version for Xamarin.iOS 14.0.0 is Xcode 12.0 or later. The current Xcode version (found in /Applications/Xcode.app/Contents/Developer) is 11.7

Installing Xcode 12 should fix the build.

Using an older Xcode than the one we recommend may sometimes work, but sometimes it doesn't (it depends on what's new in each version of Xcode, and what each app does, so there's no specific rule). Here's more information: https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/old-version-xcode

**Comment by Axemasta** [comment]
This is happening on a pipeline agent though, they have lots of version of xcode [installed, currently 10.3-12.2](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode)

If I don't lockdown the version of Xamarin.iOS to 14.0.0.0, the pipeline will always suceed and it fails everytime I lock it down with this error 😟

**Comment by rolfbjarne** [comment]
You can choose the version of Xcode to use: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#xcode

**Comment by Axemasta** [comment]
Ah excellent, I had missed that section!

For anyone interested my yaml looked something like this:

```
    - task: CmdLine@2
      inputs:
        script: '/bin/bash -c "echo ''##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]''$(xcodeRoot);sudo xcode-select --switch $(xcodeRoot)/Contents/Developer"'
    - task: Boots@1
      inputs:
        uri: 'https://download.mono-project.com/archive/6.10.0/macos-10-universal/MonoFramework-MDK-6.10.0.104.macos10.xamarin.universal.pkg'
    - task: Boots@1
      inputs:
        uri: 'https://download.visualstudio.microsoft.com/download/pr/c939bb72-556b-4e8a-a9b4-0f90e9b5e336/f906a6ce183fb73f1bcd945ac32f984b/xamarin.ios-14.0.0.0.pkg'
```
