### ISSUE TITLE
[Bug] HttpClient.PostAsync stop working on IOS14, but on IOS13 is working

### ISSUE THREAD

**Issue by CsabaZsigmond** [xamarin/xamarin-macios#9848]
```
public static async Task<HttpResponseMessage> Login(string email, string password)
        {
            string URL = Constants.BASE_PATH + "/oauth/token";
            HttpClientHandler handler = new HttpClientHandler();
            handler.ServerCertificateCustomValidationCallback += (sender, cert, chaun, ssPolicyError) => { return true; };

            try
            {
                HttpClient _client = new HttpClient(handler);
                var post = new LoginData { email = email, password = password, grant_type = "password" };
                var json = JsonConvert.SerializeObject(post);
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var response = await _client.PostAsync(URL, content);
                return response;
            }
            catch (Exception ex)
            {
                return null;
            }
        }


```

- Version with issue: Xamarin Forms 4.8.0.1534
- Affected Devices: Iphone simulator with IOS14

The HttpClient.PostAsync is not working on IOS14.
 I'm using the above code for login, the web server has all certificates installed correctly. I made some tests on local web server environment, the server response is fine, but the app is freezed.
On Android is working fine and on the previous versions of IOS(13.2).

**Comment by chamons** [comment]
If the same application built against the same SDK works on iOS 13.2 but fails on iOS 14, it suggests that this may not be an SDK bug. 

I'll do some digging to try to get details on what's going on though.

**Comment by mandel-macaque** [comment]
Hello,

We need more info to be able to debug this. Can you please provide the following:

1. Full information of your development environment
2. ServerCertificateCustomValidationCallback does not work ion iOS, you have to use https://github.com/xamarin/xamarin-macios/blob/main/src/Foundation/NSUrlSessionHandler.cs#L55 Can you please create your own instance of the NSUrlSesisonHandler and use the provided callback?
3. Can you let me know the following, when you say iOS 14, you mean the actual OS and not the new version of Xamarin, is that correct?

**Comment by CsabaZsigmond** [comment]
Hi,
I created an Xamarin Forms app one year ago for both devices: Android and IOS.
I'm using Visual studio for Mac, vers. 8.7.8
Installation UUID: 64c9cb6a-c1cb-4f28-b17a-c17dce03c055
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
	Package version: 612000093

Operating System
Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

Xamarin.iOS
Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

Xamarin.Android
Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/gma/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

I'm talking about the IOS 14 - Iphone operating sistem.
I didn't touched the login section code since 6 months, and now when I run the app on IOS 13.2 it's working fine, it makes the login, and if I change it to IOS 14, I do the same thing and I didn't get any response, or to throw an error. It is stuck in the beyond section of code. The server send the response.
**One strange thing, if the status code is not 200, it is working.**

> var response = await _client.PostAsync(URL, content);

**Comment by CsabaZsigmond** [comment]
The latest update in Xamarin Forms - 4.8.0.1560, fixed the issue. Now it's working fine. This issue can be closed.
