### ISSUE TITLE
NSTextView on Xamarin.MacOS lacks set property for NSMutableAttributedString

### ISSUE THREAD

**Issue by tekmun** [xamarin/xamarin-macios#9861]
For me, the availability of Xamarin.Essentials for MacOS in Version 1.6 makes it possible to build MacOS app using Xamarin.Forms.  In my attempt, I encountered an issue with Label custom renderer.  I am not able to set it to NSTextView native control because NSTextView for MacOS lacks the set property for NSMutableAttributedString.  It only has get property.

In general, Xamarin should make all native APIs for MacOS available in Xamarin.MacOS.

**Comment by tekmun** [comment]
Hi,
There is no AttributedStringValue property in Xamarin.MacOS for NSTextView.  I am using Xamarin.Forms 4.8.0.1534.  I cannot use Xamarin.Forms 5.0.0.1539-pre2 because it crashes the MacOS app.

**Comment by chamons** [comment]
Thanks for the feedback.

NSControl has the AttributeStringValue property that you are referencing, as you can see here: https://github.com/xamarin/xamarin-macios/blob/main/src/appkit.cs#L4815

If that does not resolve your issue, please attach a sample project showing your particular problem.

**Comment by tekmun** [comment]
[GitHub.zip](https://github.com/xamarin/xamarin-macios/files/5385285/GitHub.zip)

Hi,
As requested, this simple project shows that NSTextView does not have AttributedStringValue property at all.  Go to MacOS directory -> BibleDisplayLabelRenderer.cs.  If the subclass for Xamarin Label is NSTextField, AttributedStringValue is available.  If it is NSTextView, an error occurs.

Thanks.

**Comment by tekmun** [comment]
Hi,
Can this feature be incorporated soon?  My application requires NSTextView with NSMutableAttributedString to work properly since it is a reading app.  Thanks.

**Comment by GalaxiaGuy** [comment]
`NSTextView` is a bit more complicated to use (and I haven't used it myself). The actual string content is managed through its `TextStorage` property. Something like the following should work:

```
textView.TextStorage.SetString(myAttributedString);
```

**Comment by tekmun** [comment]
Hi,
I made the necessary changes in the attached GitHub.zip code to incorporate your suggestion to use textView.TextStorage.SetString(myAttributedString).  Unfortunately, no text is shown at all.

**Comment by chamons** [comment]
This appears to be AppKit weirdness. I added this:

```
                _label.AllowsEditingTextAttributes = true;
```

as shown here:

https://stackoverflow.com/questions/8684972/nstextfields-attributed-string-is-delayed-in-rendering

And it works for me:

![image](https://user-images.githubusercontent.com/6392201/96507023-30ae9a00-121e-11eb-9047-67513cbe413b.png)

**Comment by tekmun** [comment]
Hi,
In GitHub.zip project, I subclass the NSTextField.  You need to change it to NSTextView.
NSTextView does not have method "AllowsEditingTextAttributes".  Hence, this issue is still unresolved.

**Comment by chamons** [comment]
By adding this line 

```
      _label.AllowsEditingTextAttributes = true;
```

after this one:

```
  _label = new CustomNSTextView();
```

and correcting your subclass declaration:

```
  public class CustomNSTextView : NSTextField //NSTextField
```

I was able to correct your sample application, as I noted above. 

Github issues are not the best place for assistance in learning Xamarin.Forms and Xamarin.iOS 

The broader developer community would be the best and quickest place for additional troubleshooting help on issues like this. 

Consider also reading the [documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/) if you have difficulty in the future.

**Comment by tekmun** [comment]
Hi,

The issue is with NSTextView, not NSTextField.

`
public class CustomNSTextView : NSTextView
`
In NSTextView, "AllowsEditingTextAttributes" property does not exist.  This property only exist in NSTextField.
Thanks.

**Comment by chamons** [comment]
In that case as noted in 

https://stackoverflow.com/questions/25496651/cant-insert-nsattributedstring-into-nstextview
and
https://stackoverflow.com/questions/36280699/how-to-set-a-custom-views-intrinsic-content-size-in-swift

You'll need use `_label.TextStorage.Append (newattrString);` and override `IntrinsicContentSize` (or use constraints).

Sample: https://gist.github.com/chamons/fad58f8dc1df38fd362273d4f77fb93a

As noted before:

> Github issues are not the best place for assistance in learning Xamarin.Forms and Xamarin.iOS
> The broader developer community would be the best and quickest place for additional troubleshooting help on issues like this.
> Consider also reading the documentation if you have difficulty in the future.
