### ISSUE TITLE
linker_config XML file does not work for Xamarin.iOS

### ISSUE THREAD

**Issue by awasilik** [xamarin/xamarin-macios#9882]
### Steps to Reproduce

1. Prepare not linker safe environment (reflection etc)
2. Set the linker for SdkOnly
3. Add linker_config.xml file excluding all types within System.Collections.Generic

### Expected Behavior
Types contained in linker_config should not be stripped out of code.

### Actual Behavior
Types are still stripped out of code

### Worth to notice
Additional mtouch arguments **--linkskip=mscorlib** make my code work

### Environment

Visual Studio version: 16.7.5
Visual Studio for mac version: 8.7.8
Mono version (mac): 6.12.0.93
Xamarin iOS version: 14.0.0.0 (7ec3751a1)
Xcode version: 12.0.1

My linker config file:
```
<linker>
	<assembly fullname="mscorlib">
		<type fullname="System.Collections.Generic.*" preserve="all" />
	</assembly>
</linker>
```
My csproj file: 
```
<LinkDescription Include="linker_config.xml">
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</LinkDescription>
```
I've tried the approach with excluding whole assembly with no result as well:
```
<linker>
	<assembly fullname="mscorlib" preserve="all"  />
</linker>
```
### Build Logs

None

**Comment by chamons** [comment]
Thank you for your feedback!

I'm wondering if your project is correctly configured to use the xml file. We would need to see a project to confirm. 

For us to investigate this further, could you please provide a test case to reproduce your issue.

We look forward to hearing from you!

**Comment by tj-devel709** [comment]
We have not received the requested information so we will be closing this issue.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
