### ISSUE TITLE
remove libcore and hello links on my iphone

### ISSUE THREAD

**Issue by trinatimbes** [xamarin/xamarin-macios#9908]
### Steps to Reproduce

1. 
2. 
3. 

### Environment

```
```

**Comment by chamons** [comment]
Thanks for your feedback, unfortunately it looks like you didn't provide any information in the issue body. Without details we're unable to help resolve your issues.

Please open a new issue with details included.

**Comment by trinatimbes** [comment]
My husband has put prentice respository links to my phone can you break it?
Or tell me how?

**Comment by chamons** [comment]
You should be able to configure github notifications on this page: https://github.com/settings/notifications
