### ISSUE TITLE
Building iOS binding library fails on second system

### ISSUE THREAD

**Issue by pumaprod** [xamarin/xamarin-macios#9929]
#9691 # Environment
=== Visual Studio Community 2019 for Mac ===
Version 8.6.3 (build 30)
Installation UUID: eaa2b22d-aa01-4339-a6a0-f72758deeded
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
	Package version: 610000104

=== Mono Framework MDK ===
Runtime:
	Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
	Package version: 610000104

=== Roslyn (Language Service) ===
3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===
Version : 5.6.0.6591

=== Kit SDK .NET Core ===
SDK : /usr/local/share/dotnet/sdk/3.1.300/Sdks
Version du SDK : 3.1.300
SDK MSBuild : /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== Runtime .NET Core ===
Runtime : /usr/local/share/dotnet/dotnet
Version du runtime : 3.1.4

=== Xamarin.Profiler ===
'/Applications/Xamarin Profiler.app' introuvable

=== Updater ===
Version : 11

=== Xamarin.Android ===
Non installé

=== Microsoft OpenJDK for Mobile ===
Java SDK: /Users/simon/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Code EPL d'Android Designer disponible ici :
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===
Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-05-15 00:43:06 UTC

=== Android Device Manager ===
Version: 16.6.0.95
Hash: 45d17b5
Branch: remotes/origin/d16-6
Build date: 2020-05-15 00:43:26 UTC

=== Xamarin Designer ===
Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Apple Developer Tools ===
Xcode 12.0.1 (17220)
Build 12A7300

=== Xamarin.Mac ===
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===
Version: 13.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:05-0400

=== Build Information ===
Release ID: 806030030
Git revision: f43dfeb8c84a15c535a3a0861dcbc4c68bd73815
Build date: 2020-06-04 12:43:00-04
Build branch: release-8.6
Xamarin extensions: f43dfeb8c84a15c535a3a0861dcbc4c68bd73815

=== Operating System ===
Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

### Build Logs

https://gist.github.com/chamons/5f18a02074c72f5e103256195151ce3b

The project builds correctly on my colleagues mac.
In fact, should I create an empty project - no code - it will compile to a nuget correctly.
If I add a C++ library (.a), it will fail in the same way.

Here is my colleagues setup : 
=== Visual Studio Community 2019 for Mac ===
Version 8.6.3 (build 30)
Installation UUID: b0277faa-b307-45e5-ae3f-aaf8bbb18b08
    GTK+ 2.24.23 (Raleigh theme)
    Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
    Package version: 610000104

=== Mono Framework MDK ===
Runtime:
    Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
    Package version: 610000104

=== Roslyn (Language Service) ===
3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

=== NuGet ===
Version : 5.6.0.6591

=== Kit SDK .NET Core ===
SDK : /usr/local/share/dotnet/sdk/3.1.300/Sdks
Versions du SDK :
    3.1.300
    3.1.200
    3.1.102
    3.1.101
    3.1.100
    3.0.100
SDK MSBuild : /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== Runtime .NET Core ===
Runtime : /usr/local/share/dotnet/dotnet
Versions du runtime :
    3.1.4
    3.1.2
    3.1.1
    3.1.0
    3.0.0
    2.1.18
    2.1.17
    2.1.16
    2.1.15
    2.1.14
    2.1.13

=== Xamarin.Profiler ===
Version : 1.6.12.29
Emplacement : /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===
Version : 11

=== Apple Developer Tools ===
Xcode 11.5 (16139)
Build 11E608c

=== Xamarin.Mac ===
Version: 6.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:04-0400

=== Xamarin.iOS ===
Version: 13.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:05-0400

=== Xamarin Designer ===
Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

=== Xamarin.Android ===
Version : 10.3.1.4 (Visual Studio Community)
Commiter : xamarin-android/d16-6/3a10de9
Android SDK: /Users/qdifant/Library/Developer/Xamarin/android-sdk-macosx
    Versions Android prises en charge :
        8.1(Niveau d’API 27)

Version de SDK Tools : 26.1.1
Version des outils de plateforme du SDK : 28.0.2
Version des outils de génération du SDK : 28.0.3

Informations de build : 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

=== Microsoft OpenJDK for Mobile ===
Java SDK: /Users/qdifant/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Code EPL d'Android Designer disponible ici :
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===
Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-05-15 00:43:06 UTC

=== Android Device Manager ===
Version: 16.6.0.95
Hash: 45d17b5
Branch: remotes/origin/d16-6
Build date: 2020-05-15 00:43:26 UTC

=== Build Information ===
Release ID: 806030030
Git revision: f43dfeb8c84a15c535a3a0861dcbc4c68bd73815
Build date: 2020-06-04 12:43:00-04
Build branch: release-8.6
Xamarin extensions: f43dfeb8c84a15c535a3a0861dcbc4c68bd73815

=== Operating System ===
Mac OS X 10.15.6
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Jun 18 20:49:00 PDT 2020
    root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

-------------------------------------------------------
This is a blocking issue for us.
What can be done, please ?

**Comment by chamons** [comment]
Thank you for your feedback!

It looks like the build system crashed while processing your library. Was there any obfuscation involved at some point?

For us to investigate this further, could you please provide test case so we can dig into this.

We look forward to hearing from you!

**Comment by pumaprod** [comment]
Good afternoon,

Thank you for your reply.
After having tried changing the VS version to match that which my colleague
uses, I am still in the same situation.
However, I have noticed that in the detailed build trace, xcode does not
seem to be detected, whereas on my colleagues system it is (presence of
XCODE_DEVELOPER_DIR_PATH) - this could indicate something ?
How can I send you test files without sharing publicly ?

Cordialement
Simon

Le mar. 20 oct. 2020 à 19:07, Chris Hamons <notifications@github.com> a
écrit :

**Comment by chamons** [comment]
I believe the information [here](https://forums.xamarin.com/discussion/150918/the-microsoft-xamarin-support-team-is-here-to-help#latest) is still accurate on the process:

> If you want one on one support via email (business hours only) or need to provide private code or other sensitive info, then please submit a support request to the Xamarin support team at this [link](https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=211dd84f-3474-c3c5-79bf-66db630c92a6).

**Comment by pumaprod** [comment]
Hi Chris,

The support option you proposed is not free - I am working for a university
research team.
What can you propose otherwise to be able to continue with this channel of
support, please ?

Best regards
Simon Giddings

Le jeu. 22 oct. 2020 à 22:19, Chris Hamons <notifications@github.com> a
écrit :

**Comment by pumaprod** [comment]
Hi Chris,

So, after some collaboration with my colleague for which the original
project works, it turns out that VS does not like iOS targeted C++
libraries built in debug mode.
When we built them in release mode, the project compiled, no problem.
However, there is still the strange warning message.

So, we can close this issue.

Best regards
Simon Giddings

Le ven. 23 oct. 2020 à 11:17, Simon Giddings <mr.s.giddings@gmail.com> a
écrit :
