### ISSUE TITLE
Clarification: Debug Symbols for Binding Library

### ISSUE THREAD

**Issue by bruno-garcia** [xamarin/xamarin-macios#9934]
I couldn't find an answer to this or any documentation so trying my luck here:

When creating a binding library, the shared libraries goes into the nupkg.

How can I make the debug symbols available to the user so that crashes from the final app can be symbolicated. Is there a symbol server we can use here or the user would need to chase each library author for the symbols?

I tried my luck on [Discord, for context.](https://discord.com/channels/732297728826277939/732297808148824115/765741599585992714)Thanks.

**Comment by chamons** [comment]
It looks like nuget has support for this via:

https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

But it sounds like it may not work here:

https://developercommunity.visualstudio.com/idea/649946/add-source-link-support-when-debugging-xamarin-app.html

I would reach out to nuget for more information if the documentation is insufficient.

**Comment by bruno-garcia** [comment]
Symbol package is not a solution as @rolfbjarne said:

![image](https://user-images.githubusercontent.com/1633368/96912972-0ef92100-1471-11eb-8e6f-f164aa5c18f4.png).

Since the binding package is a solution offered by Xamarin, I'm not sure the NuGet team will be able to help me out.

**Comment by chamons** [comment]
Hmm, @rolfbjarne can you comment on how we should proceed here?

**Comment by rolfbjarne** [comment]
@bruno-garcia the simplest solution would be to include debug symbols in the native library itself (and thus embedded indirectly in the NuGet). At build time we'll then create a .dSYM directory which will contain the debug information, and the app developer then can use to symbolicate crash reports.

**Comment by bruno-garcia** [comment]
Oh so the build tool does pull symbols attached to the binding project into the final `.dSYM`? That sounds like a simple solution then. Thanks for clarifying.

I would really recommend adding this information to the docs. I recently went through those and tried to create a binding library. There was no mention on what to do with the symbols. And it was generally not very straight forward (specially compared to React Native and Flutter).

I'm sure better docs and tools on how to create binding libraries will lower the entry barrier and help grow the ecosystem.
