### ISSUE TITLE
application only works with -nolink

### ISSUE THREAD

**Issue by fhintsch** [xamarin/xamarin-macios#9956]
### Steps to Reproduce

1. Run the app with Debug configuration on iPhone
2. Switch to Ad-Hoc configuration
3. Run the app with Ad-hoc configuration on iPhone

### Expected Behavior

The app in Debug config runs fine.
The app in Ad-hoc config should work either.

### Actual Behavior

The app in Ad-hoc config does not work. Immediately after start of the app it seems to crash and the iOS home screen is displayed. On the other hand the app is still in the task list, i.e. if I swipe up with my finger to see running apps I see my up on the first position. I can bring it in foreground again but it will disappear at once and stay in background.

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.7.8 (build 4)
Installation UUID: c63d4ddb-4398-4935-a384-ca72c29bb572
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK-Versionen:
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.201
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.300
	2.2.107
	2.2.104
	2.2.103
	2.1.505
	2.1.402
MSBuild-SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core-Runtime ===

Laufzeit: /usr/local/share/dotnet/dotnet
Laufzeitversionen:
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.3
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.5
	2.2.2
	2.2.1
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.9
	2.1.4

=== Xamarin.Profiler ===

Version: 1.6.12.26
Speicherort: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.0.1 (17220)
Build 12A7300

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Community)
Hash: 817b6f72a
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/frankhintsch/Library/Developer/Xamarin/android-sdk-macosx
	Unterstützte Android-Versionen:
		4.4 (API-Ebene 19)
		6.0 (API-Ebene 23)
		7.1 (API-Ebene 25)
		8.0 (API-Ebene 26)
		8.1 (API-Ebene 27)

Version von SDK Tools: 26.1.1
Version der SDK-Plattformtools: 29.0.6
Version der SDK-Buildtools: 29.0.2

Buildinformationen: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/frankhintsch/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL-Code ist hier verfügbar:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Build Information ===

Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

```

### Build Logs

Since the build output is very large (> 3MB) it does not fit in this comment (!). Therefore I provide this [link](https://www.dropbox.com/s/q1gi0gmxo4ewbgp/linker-output.txt.gz?dl=0)

**Comment by chamons** [comment]
Thanks for the feedback.

As the application works in Debug configuration, I strongly suspect that you have a misconfigured code signing setting.

Code signing can be very difficult to configure correctly, I would suggest reading the [associated documentation](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/ad-hoc-distribution?tabs=windows).

Without a sample project to reproduce though, no one will be able to look at this very closely. Please attach a sample project showing the issue at hand.

A copy of the crash report would also be helpful.

Another approach you could take would be to configure a project in Xcode using the same application identifier and launching it ad-hoc. Xcode may provision the device and download the correct certificates for you.

**Comment by fhintsch** [comment]
I forgot to mention an important thing: If I add only

`<MtouchLink>None</MtouchLink>`

to the Ad-hoc configuration the app runs fine. 
So I assume, it is not a code signing issue.
In the past few weeks I already created valid Ad-hoc certificates and distributed and loaded ipa file versions, using the Debug configuration as a workaround.

Regarding the crash report: I searched with Xcode for a crash report, but could not find any. This corresponds to this strange foreground/background behavior I described yesterday.

**Comment by chamons** [comment]
As I noted before, a sample project is really required before anyone can look at this. Knowing the total differences between the different configurations is critical in understanding what's going on.

**Comment by fhintsch** [comment]
I understand. I will try to strip it down to sample project… This will last a few days.

**Comment by fhintsch** [comment]
Hello Chris,

the situation becomes somewhat confusing: In order to provide you with a sample project I created a new project and used the Multi Platform Empty Forms App template. I did not add any code to the template, just updated nuget packages, compiled and loaded. 
I ended up with this screen on my iPhone :



As you can see, the lower part of the form is not displayed!

In the beginning of my test sequence everything works fine: I could load the app with debug mode and release mode as well. Then I switched over to my original app which was running in another VS instance, just to check the provisioning scheme. (I very often have multiple instances open, could this generate some interferences? ) Back to the test app I see the described strange behavior. At this point I decided to stop although the seen error seems different from the original one.
I made an archive of the complete directory including working files which you can access here: https://www.dropbox.com/s/zn4jle4cobo5u38/adHocTest.zip?dl=1

Hope, this helps
Frank

**Comment by rolfbjarne** [comment]
I'm not able to reproduce any crashes with the sample solution you provided, but I'm a bit confused regarding your last comment: exactly what is the behavior you're seeing (with the sample solution), and what's the behavior you're expecting? You're mentioning a screenshot, but it seems it wasn't attached successfully.

**Comment by fhintsch** [comment]
This was the screenshot:




As you can see, the lower part of the form is not displayed!

**Comment by rolfbjarne** [comment]
@fhintsch I still can't see the screenshot - it looks like GitHub won't include images when you respond to their notifications by email, you'll probably have to open this page in a browser and attach it that way.

**Comment by fhintsch** [comment]
Trying this way to provide the screenshot:
![IMG_2418](https://user-images.githubusercontent.com/3294876/101880004-7dfe1680-3b92-11eb-953a-ff3242a3c47b.PNG)

**Comment by spouliot** [comment]
@fhintsch this looks like an issue when the title text/font is too large to fit on a single line. I'm not sure if that's the expected behaviour or not. Please file a different issue for this with the XF team -> https://github.com/xamarin/Xamarin.Forms

>  At this point I decided to stop although the seen error seems different from the original one.

Please reply to this issue if/when you can duplicate the original crash. Make sure to include updated test case and versions information so we can duplicate the crash ourselves. Thanks!

**Comment by rolfbjarne** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
