### ISSUE TITLE
Failed to debug on iOS share extension project. MT1008

### ISSUE THREAD

**Issue by onurhazar** [xamarin/xamarin-macios#9961]
We are having problems while debugging the share extension project of our iOS app. Previously, we had no problem. With iOS 14, debugging works for iOS project but it starts failing to debug for share extension project on simulator when I select target MyApp.iOS.ShareExtension.

In addition; In release mode; we have also another problem when we try to share a selected photo from photos app, it gives; "Unable to share - there was an error while preparing to share. Please try again later." popup. Please see the screenshot below.

We are sure that we have correct profiles including correct app group for both app and share extension. Entitlements also contains app group key.

**Application Output** (-v -v -v -v included)

```
Failed to launch the simulator: Object reference not set to an instance of an object
error MT1008: Failed to launch the simulator: Object reference not set to an instance of an object
```

**Environment**

=== Visual Studio Community 2019 for Mac ===

Version 8.7.8 (build 4)
Installation UUID: 079b55bd-54e7-4320-8ac6-5e78dd6c7488
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000093

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.93 (2020-02/620cf538206) (64-bit)
	Package version: 612000093

=== Roslyn (Language Service) ===

3.7.0-6.20427.1+18ede13943b0bfae1b44ef078b2f3923159bcd32

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.402/Sdks
SDK Versions:
	3.1.402
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.8
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.22
	2.1.19
	2.1.18
	2.1.16
	2.1.15
	2.1.14
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.1 (17222)
Build 12A7403

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-0400

=== Xamarin Designer ===

Version: 16.7.0.495
Hash: 03d50a221
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-08-28 13:12:52 UTC

=== Xamarin.Android ===

Version: 11.0.2.0 (Visual Studio Community)
Commit: xamarin-android/d16-7/025fde9
Android SDK: /Users/onur.hazar/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.0
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: 83105ba
Java.Interop: xamarin/java.interop/d16-7@1f3388a
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/onur.hazar/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/d16-7~2
Build date: 2020-09-16 05:12:24 UTC

=== Android Device Manager ===

Version: 16.7.0.24
Hash: bb090a3
Branch: remotes/origin/d16-7
Build date: 2020-09-16 05:12:46 UTC

=== Build Information ===

Release ID: 807080004
Git revision: 9ea7bef96d65cdc3f4288014a799026ccb1993bc
Build date: 2020-09-16 17:22:54-04
Build branch: release-8.7
Xamarin extensions: 9ea7bef96d65cdc3f4288014a799026ccb1993bc

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Mon Aug 31 22:12:52 PDT 2020
    root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Essential UI Kit for Xamarin.Forms - Syncfusion 3.0.0.0

**Console Log**

```
error	17:47:27.256897+0300	com.apple.FontServices.UserFontManager	registeredFontsInfoForIdentifier refused access "com.myapp.share.ios.qa"
error	17:47:29.390309+0300	chronod	Failed to get the extension point ID of plugin <LSPlugInKitProxy: 0x7fe46c11bc70> pluginID=com.myapp.share.ios.qa.shareextension UUID=A28D1979-BC19-40FC-BE47-507F91946AA0 version=1.0
error	17:47:29.396243+0300	pkd	Error getting name for com.myapp.share.ios.qa: Error Domain=NSOSStatusErrorDomain Code=-10813 "(null)" UserInfo={_LSLine=355, _LSFunction=-[_LSDReadClient getLocalizedNameWithBundleType:bundleIdentifier:bundleUUID:context:shortNameOnly:preferredLocalizations:validationToken:completionHandler:]}
error	17:47:29.412628+0300	callservicesd	Attempt to retrieve application record for bundle identifier com.myapp.share.ios.qa failed with error: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=1482, _LSFunction=runEvaluator}
error	17:47:29.451179+0300	SpringBoard	[com.myapp.share.ios.qa] Push registration with a nil environment was encountered, will not invalidate token
error	17:47:32.689357+0300	com.apple.FontServices.UserFontManager	registeredFontsInfoForIdentifier refused access "com.myapp.share.ios"
error	17:47:33.814966+0300	chronod	Failed to get the extension point ID of plugin <LSPlugInKitProxy: 0x7fe46c106070> pluginID=com.myapp.share.ios.shareextension UUID=DCA6140A-7AE7-4E90-99B5-9D6754427215 version=1.0
error	17:47:33.840703+0300	callservicesd	Attempt to retrieve application record for bundle identifier com.myapp.share.ios failed with error: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=1482, _LSFunction=runEvaluator}
error	17:47:33.878668+0300	SpringBoard	[com.myapp.share.ios] Push registration with a nil environment was encountered, will not invalidate token
error	17:47:37.137259+0300	appstored	Failed to set fraction completed: 0.00 for: com.myapp.share.ios.qa
error	17:47:37.136213+0300	SpringBoard	Non-demoted placeholder for com.myapp.share.ios.qa has no associated NSProgress!
error	17:47:37.402283+0300	splashboardd	Error generating launch image for com.myapp.share.ios.qa: <XBLaunchImageError: 0x7f8fc8524050; domain: XBLaunchStoryboardErrorDomain; code: 2; reason: "[com.myapp.share.ios.qa] Estimated size (48707456) is over limit (25000000)">
error	17:47:37.403208+0300	SpringBoard	Snapshot generation resulted in an error with code: 2 for app bundleID: com.myapp.share.ios.qa, noting this until it is updated.
error	17:47:37.403366+0300	SpringBoard	Skipping launch request <XBLaunchStateRequest: 0x600003b85490> due to denied app: com.myapp.share.ios.qa.
error	17:53:12.366727+0300	appstored	Failed to set fraction completed: 0.00 for: com.myapp.share.ios.qa
error	17:53:12.612512+0300	appstored	Failed to set fraction completed: 0.62 for: com.myapp.share.ios.qa
error	17:53:13.115138+0300	appstored	Failed to set fraction completed: 0.96 for: com.myapp.share.ios.qa
error	17:53:13.151717+0300	chronod	Failed to get the extension point ID of plugin <LSPlugInKitProxy: 0x7fe466f34a90> pluginID=com.myapp.share.ios.qa.shareextension UUID=86633377-1FF0-40EE-8DA4-BEB513187C8D version=1.0
error	17:53:13.241506+0300	splashboardd	Error generating launch image for com.myapp.share.ios.qa: <XBLaunchImageError: 0x7f8fc8526f00; domain: XBLaunchStoryboardErrorDomain; code: 2; reason: "[com.myapp.share.ios.qa] Estimated size (48707456) is over limit (25000000)">
error	17:53:13.242346+0300	SpringBoard	Snapshot generation resulted in an error with code: 2 for app bundleID: com.myapp.share.ios.qa, noting this until it is updated.
error	17:53:13.242474+0300	SpringBoard	Skipping launch request <XBLaunchStateRequest: 0x600003b90700> due to denied app: com.myapp.share.ios.qa.

```
**Screenshots**

![image](https://user-images.githubusercontent.com/5585009/97189099-493a2980-17b5-11eb-85a9-6eccf866d03b.png)

![image](https://user-images.githubusercontent.com/5585009/97189408-9d450e00-17b5-11eb-8dff-983191cf6e7e.png)

![image](https://user-images.githubusercontent.com/5585009/97189425-a0d89500-17b5-11eb-9817-c261f3f0f61b.png)

![image](https://user-images.githubusercontent.com/5585009/97189818-0fb5ee00-17b6-11eb-95bc-be2957152890.png)

**Comment by chamons** [comment]
I'm seeing this:

```
Failed to launch the simulator: Object reference not set to an instance of an object
error MT1008: Failed to launch the simulator: Object reference not set to an instance of an object
``` 

as well.

**Comment by michaellavender** [comment]
Onur, did you ever find a resolution for this issue? We also have an app with a share extension and have had it working successfully for some time, but when we build for release the iOS sharing window never appears and when we run in debug mode to a simulated device we now receive the "Unable to Share - There was an error while preparing to share. Please try again later." message. This has worked for us for months, but now isn't functioning at all. All of our certificates and app group are properly configured, but now we can't get a build where our share extension functions at all.

Any help would really be appreciated as being able to share photos is a major part of our app's functionality.

**Comment by rolfbjarne** [comment]
@michaellavender it's unlikely you're running into the same problem as this issue refers to; I recommend opening a new issue instead.
