### ISSUE TITLE
Carplay - ios 14 Broken feature. CPListImageRowItem can't be used in CPListSection

### ISSUE THREAD

**Issue by ghost** [xamarin/xamarin-macios#9996]
In the carplay framework, it's impossible to use the new CPListImageRowItem from ios 14 with the current version of xamarin-ios-14.2.0.12.

In the Apple ios api, the init function for CPListSection is (NSArray<id<CPListTemplateItem>> *)items; 
Both CPListItem and CPListImageRowItem implements CPListTemplateItem via CPSelectableListItem, but the Xamarin API doesn't allow CPListTemplateItem in the constructor.

### Actual Behavior
In Xamarin, CPListSection constructor is takes a CPListItem [] items, but CPListImageRowItem doesn't inherit from this interface. 
Both CPListItem and CPListImageRowItem have the CPSelectableListItem interface. 
We can't create a CPListSection with CPListImageRowItem

### Expected Behavior
We should be able to create CPListSection with CPListTemplateItem. The binding should probably be change to make
CPListSection constructor take an array of CPListTemplateItem instead of CPListItem

### Workaround

https://github.com/xamarin/xamarin-macios/issues/9996#issuecomment-1182188805

**Comment by chamons** [comment]
So according to [this](https://developer.apple.com/documentation/carplay/cplistsection/2977575-initwithitems?language=objc) the definition is:

- (instancetype)initWithItems:(NSArray<id<CPListTemplateItem>> *)items;

This code compiles in ObjC:

```
    CPListItem * item = [[CPListItem alloc] initWithText:@"Test" detailText:@"Details"];
    CPListImageRowItem * rowItem = [[CPListImageRowItem alloc] initWithText:@"Test" images:@[]];
    CPListSection * section = [[CPListSection alloc] initWithItems:@[item, rowItem]];
```

this code fails to compiler in C#:

```
			var item = new CPListItem ("Text", "Details");
			var rowItem = new CPListImageRowItem ("test", new UIImage[] { });
			var section = new CPListSection (new CPListItem[] { rowItem, section });
```
with
```
ViewController.cs(62,62): Error CS0029: Cannot implicitly convert type 'CarPlay.CPListImageRowItem' to 'CarPlay.CPListItem' (CS0029) (CarPlayAPICheck)
```

**Comment by chamons** [comment]
There is no great work around available, since the class hierarchy is wrong in C#. 

A possible work around would be something like this:

```
var item = new CPListItem("Text", "Details");
var rowItem = new CPListImageRowItem("test", new UIImage[] { });
var rowItemHack = ObjCRuntime.Runtime.GetINativeObject<CPListItem>(rowItem.Handle, true, false);
var section = new CPListSection(new CPListItem[] { item, rowItemHack });
```

which compiles (and doesn't crash), but I don't have a CarPlay test app to test it.

What we are doing is using a low level API (GetINativeObject) along with forced_type, which tells our runtime "I know exactly what I'm doing, trust me :tm:". 

Thoughts @rolfbjarne? Am I missing something here?

This is in general dangerous, because if you are wrong you'll get a native object running around in a managed object that doesn't match, and the first invocation may crash. However, in this case it should be safe.

**Comment by janwiebe-jump** [comment]
@chamons Thanks so much, it works!

**Comment by janwiebe-jump** [comment]
Hmm,
Sometimes I get a weird exception when tapping on a `CPListImageRowItem` image.
Any clue?
```
Unable to cast object of type 'CarPlay.CPListItem' to type 'CarPlay.CPListImageRowItem'.
  at ObjCRuntime.Runtime.GetNSObject[T] (System.IntPtr ptr) [0x00135] in <c07d1d2ff2fb499fb8eca9a33aeb3c2e>:0 
  at ObjCRuntime.Trampolines+SDCPListImageRowItemHandler.Invoke (System.IntPtr block, System.IntPtr item, System.nint index, System.IntPtr completionBlock) [0x00016] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/ObjCRuntime/Trampolines.g.cs:1635 
  at (wrapper native-to-managed) ObjCRuntime.Trampolines+SDCPListImageRowItemHandler.Invoke(intptr,intptr,System.nint,intptr)
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.Type principalClass, System.Type delegateClass) [0x0003b] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:85 
  at FamilyStream.iOS.Application.Main (System.String[] args) [0x00001] in D:\Projecten\FamilyStream\app\FamilyStream\FamilyStream.iOS\Main.cs:17 
```

This is my code:
```
private CPListSection CreateSection()
{

	var item = new CPListImageRowItem("Title", images); // The array of images has been created before.

	item.Handler = new CPSelectableListItemHandler(ImageListRowHandler);
	item.ListImageRowHandler = new CPListImageRowItemHandler(ImageListRowItemHandler);
	try
	{
		// We need to hack a little: https://github.com/xamarin/xamarin-macios/issues/9996#issuecomment-1182188805
		var rowItem = ObjCRuntime.Runtime.GetINativeObject<CPListItem>(item.Handle, true, false);

		var section = new CPListSection(new CPListItem[] { rowItem });
		return section
	}
        catch(Exception exc)
	{
	// No exception is caught here, since it occurs on tap of the image item.
	}
}
```

**Comment by chamons** [comment]
Hmm, that exception suggests that you have a CPListItem that is being `GetINativeObject<CPListItem>`'ed into a CPListImageRowItem incorrectly.

Is that the only location you have a GetINativeObject call in your code base?

Without a sample showing the issue, it will be difficult to track this down.

**Comment by chamons** [comment]
Also, in the future this really should have been a new issue.
